### ISSUE TITLE
Heiman HS1SA Smoke detector could not reconnect to ZigBee adapter

### ISSUE THREAD

**Issue by ardu1** [ioBroker/ioBroker.zigbee#1004]
Hello, 

I have a ConBee II coordinator connected to the Zigbee adapter in my ioBroker. I use the actual js-controler and the 1.4.4 ZigBee adapter and also the other software is up to date.  

My problem:

I use several Heiman Smoke detector. The most work without problems, but one lost the connection and one did´t connect. The detectors are new.  I deleted the lost detector in the adapter and tried to connect new (after I set die detector back to factory setting). When I startet the pairing (the detector flashes fast) normal there comes after some seconds the message pairing has startetd. This message comes not in my case. I started the whole machine new, also put out the battery and tried again, no success. I talked to the support, but the told me the problem could be that the device is not deleted correctly and so it would not connect again? 

This is the information in the log:

![Screenshot-20-25-2021_12 25 57](https://user-images.githubusercontent.com/36503094/108593899-da419b80-7376-11eb-88cb-d74623aae02f.jpg)

Does anyone has an idea to solve the problem?

**Comment by asgothian** [comment]
Duplicate of #995 

No data is stored for devices which cannot be interviewed. If any information remains it remains in the device.

**Comment by ardu1** [comment]
Thanks, I will let the battery outside for one day, may be this helps? On Monday I have a date with the support of Heiman.

**Comment by ardu1** [comment]
Hello, after several times I tried to connect without success I asked the support from Heiman again. They told me, that the problem is may be the max. number of devices. If there is only one coordinator, it is possible to connect 8-10 devices. I there are any repeater the number could be higher. I have 4 Zigbee lamps and 6 plugs. 
I have 45 devices connected to my ConBee II. 
How many devices could I connect?

**Comment by asgothian** [comment]
I don’t know the exact limit for the conbee, but it should be higher than 45. what you can do to verify this is to remove one of the devices from the network and then try to pair the device which refuses.

A.

**Comment by ardu1** [comment]
I use 43 devices. I deleted one and tried to connect again the fire sensor. But it does not run. I will try to send it back to the manufacturer.

**Comment by ardu1** [comment]
Hello, I could solve the problem. The dealer sent me 2 new sensors and I could pair them without any problem. So it was a hardware problem.
