### ISSUE TITLE
1.4.4 - update only all 60sec!

### ISSUE THREAD

**Issue by Day1983** [ioBroker/ioBroker.zigbee#1005]
Hi,

the stats are updating only all 60sec - i can change the timer in teh instanz to 10sec, but update only all 60sec.

**Comment by asgothian** [comment]
Please provide sufficient information for this. Required information:
- which device
- What kind of system
- Which state
- What kind of coordinator are you using
- What log entries do you get
- ...


No information = no support.

**Comment by Day1983** [comment]
ohhh Sorry vergessen:

All meine Devices + all die State updaten den Status alle 60sec.
Devices ==> Steckdose, Buttons, Sensoren... Es betrifft alle States

Als Coordinator hab ich den CC26X2R1 Board. Auf einen Raspberry 4b mit 2GB

Im Adapter hab ich bei Einstellungen den Timer von 60sec auf 10 runtergesetzt, aber weiterhin werden nur alle 60sec die States aktualisiert.
Im Zeitstempfel kann man sehen, dass es nur alle 60sec was ändert - bei einer Steckdose die Leistungsmessung macht, kommt nur alle 60sec was an...

![image](https://user-images.githubusercontent.com/77491820/108636435-75289b80-7485-11eb-9a75-d587154fbc5e.png)

![image](https://user-images.githubusercontent.com/77491820/108636440-8a052f00-7485-11eb-9287-1459b7df1491.png)

**Comment by asgothian** [comment]
The Setting you changed is the timeout for pairing devices. The Adapter does not have a heartbeat to update all states.
The 60 second update interval for the power measurement of the blitzwolf plugs is part of the plug configuration.
It may be possible to change that through a state on the blitzwolf plug. I am not sure about this as I don’t have one of these.

A.

**Comment by Day1983** [comment]
Thx for this information.

one question about that:
Is it possible, that you can implement this?

https://github.com/Koenkk/zigbee2mqtt/issues/3812#issuecomment-724014395

Or is it ongoing only by the mqtt?


==> Sorry, i´m a newbee...
