### ISSUE TITLE
1.4.4 - link quality only 10

### ISSUE THREAD

**Issue by Day1983** [ioBroker/ioBroker.zigbee#1006]
Hi,
 after the update to 1.4.4 show the objects about the link quality only "10"...

**Comment by asgothian** [comment]
You need to wait for the devices to send an update to the link quality. Until such messages are received, link quality will be stuck at 10.

In the Future you will need to update the issue with details about your System if you want any additional assistance.

to quote my forum signature: „shit don’t work“ is not an error message. It’s just a curse.
