### ISSUE TITLE
Nach Update kein paring mehr

### ISSUE THREAD

**Issue by Schmusekater76** [ioBroker/ioBroker.zigbee#1007]
Nach dem Update auf 1.4.4 kann ich keine Geräte mehr anlernen, er findet einfach nichts mehr.

**Comment by asgothian** [comment]
Please do the following:
- Stop the Adapter
- Disconnect your coordinator from usb
- wait 30 seconds
- Reconnect the coordinator to usb
- start the adapter
- Wait 5 minutes
- Attempt to pair again.

while waiting, you need to update the issue with details about your System if you want any additional assistance.

to quote my forum signature: „shit don’t work“ is not an error message. It’s just a curse.

**Comment by asgothian** [comment]
No reaction - assuming issue is fixed.

A.
