### ISSUE TITLE
No Paring to IKEA Tradfri LED1836 Bulb

### ISSUE THREAD

**Issue by bikejoco** [ioBroker/ioBroker.zigbee#1008]
Hi!
I'm new in using the ZigBee-Adapter. My Hardware is:
Raspi 4, CC2531 (Firmware: CC2531_DEFAULT_20201127 ZigBee Version 1.2???), ioBroker (3.1.6) with Zigbee-Adapter (1.3.1).

I can pair to the IKEA Tradfri E173 Remote an some other Remotes (GIRA). But with many tries I can't get different IKEA Tradfri LED1836 Bulb connected. When I connect the Remote to the Bulb directly it works fine without a problem.

I tried a different Firmware (CC2531_SOURCE_ROUTING_20201128) but the Problem is the same.

Do anyone has an idea what is my mistake?

Thanks for your help
JOHANNES

**Comment by bikejoco** [comment]
UPDATE: I also tried it with the Dresden Elektronic ComBee2 Stick in an 2nd ZigBee-Adapter. But I didn't get the Bulb paired.
Other devices like Lidl HG06337 EU-Plug, Lidl HG06335 Motion-Sensor and Lidl HG06106C RGB-Bulb works fine with my CC2531.
Anyone with an idea?
Thanks for your support
JOHANNES

**Comment by asgothian** [comment]
> Anyone with an idea?
> Thanks for your support

If the bulb does not want to pair with any coordinator it is most likely defective. It might (for example) refuse to switch zigbee channels when searching for a coordinator. It is also possible that it only works on one of the ZLL compatible channels (11,15,20,26). 
Do you have other Ikea Bulbs in your zigbee Network ? If so I would return the bulb as defective and get a different one.

**Comment by bikejoco** [comment]
Problem solved. ON/OFF vor 6-times is pairing, ON/OFF vor 7-times is factory reset. So it was my mistake. Thanks for your support.
