### ISSUE TITLE
mixed-up objects

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#101]
Hi .. I could be mistaken but IMO these Objects are mixed-up:

From top side on flip 90°
To top side on flip 90°

And tap-events don't work for me (do nothing).

**Comment by kirovilya** [comment]
Sorry, I have no cube now...
Try to double tap/knock cube on the table. And look at "tap_side" state - here will a top side of cube.
Then try slide cube and look at "slide_side" - it must be the same side.
Then flip cube on 90 angle... And what you will see in "flip90_from" and "flip90_to" state?
"flip90_from" was be equal "slide_side".

**Comment by daniel-lo** [comment]
I'm in the office now .. but to be a bit clearer:
I tried "From top side on flip 90" and the signal appeared on "To top side on flip 90°" and vice versa.

The tap seems to work when I have the cube in my hand (bigger shake) .. but I only saw a responce doing one of those (don't remember) .. so tapping while the cube is on the desk doesn't work (maybe this is normal?!).

Shake works .. and so does turning it. By the way .. many users seem to have problems with the rotation angles that are output and write scripts to circumvent. Wouldn't it be a bright idea to provide an object that is already normalized form -100 to +100 to better control volume and stuff. Just a thought :-)

**Comment by kirovilya** [comment]
Here my "tap" example :) https://youtu.be/YEgOZrM1rFg?t=14
And here sides after tab and after flip 90° - it is equal
![image](https://user-images.githubusercontent.com/8360230/48534599-9c14c200-e8b9-11e8-88a1-2e657b4a153e.png)

**Comment by daniel-lo** [comment]
Thx. I will have to validate this tonight .. will get back to this asap. 

I see your objects are named differently .. but I assume this is due to an older version.

**Comment by daniel-lo** [comment]
Video was helpful .. thanks .. didn't understand the concept of the two options .. currently I have the feeling all works well.
