### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by moelski** [ioBroker/ioBroker.zigbee#1013]
Hi !

After installing 1.4.4 the adapter runs into an error: 

> zigbee.0 | 2021-02-27 05:39:51.186 | warn | (25323) Terminated (UNCAUGHT_EXCEPTION): Without reason
> -- | -- | -- | --
> zigbee.0 | 2021-02-27 05:39:51.184 | info | (25323) terminating
> zigbee.0 | 2021-02-27 05:39:51.181 | info | (25323) cleaned everything up...
> zigbee.0 | 2021-02-27 05:39:51.138 | error | (25323) Cannot read property 'split' of undefined
> zigbee.0 | 2021-02-27 05:39:51.138 | error | (25323) TypeError: Cannot read property 'split' of undefined     at Zigbee.getExternalDefinition (/opt/iobroker/node_modules/iobroker.zigbee/main.js:150:47)     at getExternalDefinition.next (<anonymo
> zigbee.0 | 2021-02-27 05:39:51.134 | error | (25323) unhandled promise rejection: Cannot read property 'split' of undefined
> zigbee.0 | 2021-02-27 05:39:51.133 | error | (25323)  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
> zigbee.0 | 2021-02-27 05:39:51.096 | info | (25323) starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.24.0, js-controller: 3.2.16

Any hint what causes this error? Or better .. any fix? 

regards
  Dominik

**Comment by asgothian** [comment]
> Any hint what causes this error? Or better .. any fix?

Both. It seems that you did not install the new version from the GUI of ioBroker. The adapter is missing an "upload", which causes the external definition variable to be undefined. (See issue #998).

Solution should be to perform an upload and then restart.

A.

**Comment by moelski** [comment]
iobroker upload zigbee
That was the trick. 
Thx for the help !
