### ISSUE TITLE
Colours Network card

### ISSUE THREAD

**Issue by david883** [ioBroker/ioBroker.zigbee#1016]
Hello everyone, I might have a strange request for one or the other, is it possible to change the colors of the offline devices or the online devices on the network card? The background is that I am color blind, especially with green and red. So I don't see any differences between the devices that are available and devices that are not available. Kind regards David

**Comment by asgothian** [comment]
Do you have any suggestions for viable colors or would a different method of showing online status be better for your case ?

A.

**Comment by david883** [comment]
I can only speak of my perception now; I would suggest blue, black or yellow, for example. These are colors that are easy to see for me and where confusion is impossible. Perhaps the device which is offline or the connection of the device could be displayed as a dotted ............... line or as a dash-dot line.-.-.-.-.-.

**Comment by asgothian** [comment]
Was hältst Du davon wenn dem Namen des Gerätes ein (x) voran gestellt wird, und wir die Farben so lassen wie sie sind ?

A.

**Comment by david883** [comment]
Yes this will Work to. I think

**Comment by asgothian** [comment]
Additional "disconnected" text on devices the map consider unconnected is now available.

A.
