### ISSUE TITLE
feature requests: Devices cards - list mode - sort + search function

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.zigbee#1017]
Hi, thank you for this greatful adapter, works very good. ( lxc debian 10, node 14.16.0, js-controller 3.2.16 )
I've now 140+ devices, and after add a new one it's a mess to search the new device in the list.. 
I can't add the next one of the same type, if I'd renamed the first one..

Here I wish a search and sort function, that I can sort the devices alphabetically, or search for a name.

I'm a console-user, and the usage of the scrollwheel of the mouse is not my favorite move..  
Thanks in advance!

**Comment by arteck** [comment]
this is a Admin issue.. not zigbee adapter

**Comment by Ilovegym66** [comment]
I found out, that the new assigned devices are at the top, if all other devices are assigned to a room! 
That's very good, but works only on my desk big screen, not with my laptop, can be the resolution or the different browser..

**Comment by asgothian** [comment]
Sorting and filtering is now available in the current "latest" version. Please test version 1.5.1

A.
