### ISSUE TITLE
Network map doesn't display any device

### ISSUE THREAD

**Issue by Alexalex89** [ioBroker/ioBroker.zigbee#102]
Hey,

first of all, thanks for this great plugin!
I installed v0.8.0b and after pairing some devices (Tradfri/Osram), it does not show any device on the network map. Not even the Coordinator itself.
I can reach the devices.

The logfile says:
`
List of ports: []
Error: spawn udevadm ENOENT
`

Do you have any suggestion?

Cheers
Alex

**Comment by Apollon77** [comment]
The error means that the serial port list could not be requested. What you haves selected for the adapter as serial port for the Stick?

**Comment by Alexalex89** [comment]
I think this is related to something else... If I reinstall and reconfigure the adapter, it works. Still having other problems, but so far no bugs.
So this is closed.

**Comment by Alexalex89** [comment]
> The error means that the serial port list could not be requested. What you haves selected for the adapter as serial port for the Stick?

Thanks for your answer! I selected /dev/ttyUSB0 (CC2530). It works now and I can control my Zigbee devices.
But I still get this ENOENT error and some "Timed out after 30000 ms" errors, although the link quality should be sufficient. All devices at least 18, up to 102.
