### ISSUE TITLE
Door magnetic sensor ZM-CG205

### ISSUE THREAD

**Issue by kuumaur** [ioBroker/ioBroker.zigbee#1021]
Hi folks,
i think i dont have really luck with my Zigbee gear.
It looks like, that i have another device which is not identified.
Door magnetic sensor ZM-CG205.
I bought it as Tuya compatible, but i suppose it is not.
Does some know this device?

I these entries in the Log file:

zigbee.0 | 2021-03-06 16:15:45.552 | debug | (566)  Routing for '0x7cb03eaa0a0b22c9':  {"neighbors":[{"linkquality":20,"networkAddress":53877,"ieeeAddr":"0x7cb03eaa0a0aeec3","relationship":2,"depth":1},{"linkquality":46,"networkAddress":28260,"iee
-- | -- | -- | --
zigbee.0 | 2021-03-06 16:15:35.513 | debug | (566)  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - mgmtLqiRsp -  {"srcaddr":52105,"status":0,"neighbortableentries":13,"startindex":9,"neighborlqilistcount":3,"neighborlqilist":[{"extPandId":"0x6e
zigbee.0 | 2021-03-06 16:15:33.458 | debug | (566)  Type attributeReport device  {"type":"device","device":{"ID":30,"_type":"Unknown","_ieeeAddr":"0x00124b001aa69ec5","_networkAddress":23529,"_endpoints":[{"ID":1,"inputClusters":[],"outputClusters
zigbee.0 | 2021-03-06 16:15:33.458 | debug | (566)  Received Zigbee message from '0x00124b001aa69ec5', type  'attributeReport', cluster 'genPowerCfg', data '{"batteryVoltage":30}'  from endpoint 1 with groupID 0
zigbee.0 | 2021-03-06 16:15:33.458 | debug | (566)  handleMessage.  {"type":"attributeReport","device":{"ID":30,"_type":"Unknown","_ieeeAddr":"0x00124b001aa69ec5","_networkAddress":23529,"_endpoints":[{"ID":1,"inputClusters":[],"outputClusters":[]
zigbee.0 | 2021-03-06 16:15:33.316 | warn | (566) Device '0x00124b001aa69ec5' announced itself
zigbee.0 | 2021-03-06 16:15:33.316 | debug | (566)  handleDeviceAnnounce.  {"device":{"ID":30,"_type":"Unknown","_ieeeAddr":"0x00124b001aa69ec5","_networkAddress":23529,"_endpoints":[],"_interviewCompleted":false,"_interviewing":true,"_skipDefault
zigbee.0 | 2021-03-06 16:15:33.316 | debug | (566) zigbee-herdsman:controller:log Device announce '0x00124b001aa69ec5'
zigbee.0 | 2021-03-06 16:15:33.315 | debug | (566)  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - endDeviceAnnceInd -   {"srcaddr":23529,"nwkaddr":23529,"ieeeaddr":"0x00124b001aa69ec5","capabilities":128}
zigbee.0 | 2021-03-06 16:15:32.686 | info | (566) Starting interview of '0x00124b001aa69ec5'
zigbee.0 | 2021-03-06 16:15:32.686 | debug | (566) zigbee-herdsman:controller:device:log Interview - start device '0x00124b001aa69ec5'
zigbee.0 | 2021-03-06 16:15:32.686 | debug | (566)  handleDeviceInterview.  {"status":"started","device":{"ID":30,"_type":"Unknown","_ieeeAddr":"0x00124b001aa69ec5","_networkAddress":23529,"_endpoints":[],"_interviewCompleted":false,"_interviewing
zigbee.0 | 2021-03-06 16:15:32.686 | debug | (566) zigbee-herdsman:controller:log Interview '0x00124b001aa69ec5' start
zigbee.0 | 2021-03-06 16:15:32.685 | debug | (566)  handleDeviceJoined.  {"device":{"ID":30,"_type":"Unknown","_ieeeAddr":"0x00124b001aa69ec5","_networkAddress":23529,"_endpoints":[],"_interviewCompleted":false,"_interviewing":false,"_skipDefaultR
zigbee.0 | 2021-03-06 16:15:32.684 | debug | (566) zigbee-herdsman:controller:log Creating device '0x00124b001aa69ec5'
zigbee.0 | 2021-03-06 16:15:32.684 | debug | (566) zigbee-herdsman:controller:log New device '0x00124b001aa69ec5' joined
zigbee.0 | 2021-03-06 16:15:32.684 | debug | (566) zigbee-herdsman:controller:log Device '0x00124b001aa69ec5' joined
zigbee.0 | 2021-03-06 16:15:32.684 | debug | (566)  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd -  {"nwkaddr":23529,"extaddr":"0x00124b001aa69ec5","parentaddr":52105}

I think i need a helping hand. All these herdsman-zigbee-debug-xyz is a jungle for me.
I gave up this issue https://github.com/ioBroker/ioBroker.zigbee/issues/996#issue-810437533 , but it looks that i need to dive into that more because i have too many devices that are not pairable.
Is some willing and has the patience to support a Noob?
Br Kuumaur

**Comment by asgothian** [comment]
I can offer to hold a session via discord / anydesk where we look at both devices and make some changes on your system to try and get these devices integrated. 
With the changes introduced into 1.4.5 this should no longer be such a big deal. Let me know if that is of interest to you.

A.

**Comment by kuumaur** [comment]
That would be great, really.
I take the opportunity for Anydesk.
I am living in the time zone Europe/Berlin.
Br Kuumaur

**Comment by asgothian** [comment]
I am afraid we will need both software tools, as we need to be able to speak to each other. That way i can explain what i am doing while i am doing it. Keep in mind that you won't be able to use the computer to message me while i am controlling it via anydesk. 
I would suggest we meet Tuesday or Thursday around 18:00 on the ioBroker Discord ?

**Comment by kuumaur** [comment]
Thanx,
Anydesk and Discord are prepared.
Tuesday 18:00 is fine
Thank you in advance
Kuumaur

**Comment by asgothian** [comment]
Sensor does not work with herdsman-converters
Integration in herdsman-converters not likely due to sensor Behavior
