### ISSUE TITLE
Sonoff SNZB-01 Langer klick

### ISSUE THREAD

**Issue by MarkStephan89** [ioBroker/ioBroker.zigbee#1023]
Hallo zusammen, 
funktioniert bei euch auch der Lange klick (long click) bei dem sonoff SNZB-01 nicht?

Ich habe es schonmal hier gepostet: https://github.com/Koenkk/zigbee2mqtt/issues/6538

Dort wurde mir gesagt, dass es erstmal hier besser aufgehoben ist :)

Gruß
Mark

**Comment by asgothian** [comment]
- which adapter version are you using ?
- did you add the SNZB-01 to the "exclude list" (Ausschlussliste)
- what is the expected behavior ?
- what is the observed behavior ?

**Comment by 1N4148** [comment]
Long click is working fine with Adapter 1.4.4 & CC2652P-Stick. Long click event is raised after approx. 2sec of button holding.
