### ISSUE TITLE
xiaomi motion sensor 2 not implemented yet?

### ISSUE THREAD

**Issue by coolmcmarty** [ioBroker/ioBroker.zigbee#1027]
I bought 2 xiaomi motion sensors 2. 

When trying to pair them to my conbee2-stick (running on a raspberry pi with iobroker and zigbee-adapter version 1.4.4) it seems not to be recognized. 
Other sensors (xiaomi temperature sensor or snzb-01 button) can be paired without any problems. 

How did I try:
I tried pairing them by putting the zigbee-adapter into pairing mode and then hold the pairing button on motion sensor for 5 seconds (until it starts blinking blue). Then I keep pushing the button from every few seconds to keep it alive. 
But the pairing-log-output just counts down to 0 without any message of device-communication. 
I tried to change id, the channel and the timeout in the adapter-settings - but it is not helping. 
I tried to reset/remove battery from sensors - but it is not helping.
I tried different distances from the conbee-stick (0 to a few meters) - but it is not helping.
I tried to change batteries (3.1V) - but it is not helping.
I tried to restart the adapter and to remove/plug in again the conbee2-stick - but it is not helping.
I tried both motion-sensors (same type) that I bought - but same result/behaviour. 

Can it be that this Version "2" is not yet implemented in the zigbee-adapter? Is this a new version?
The label on the box says something like 2020.11 (beside many chinese letters).  
The device looks slightly different to previous versions and not exactly like the product pictures. On the pictures the motion-sensors do have a little hole right next to the white shield - the sensors I got do not have that but oval-shaped binding-buttons at the back. 

Thanks for your support. I can provide you debug-information during pairing-process, if you tell me how to get it. 

Bests,
Martin

**Comment by asgothian** [comment]
Please post a bit more information on your system:
- which channel are you using
- what is the exact device description of the sensor.

Note that even if a device is not supported yet it must show up during pairing attempts. It is possible that the newer Devices limit their channels to the ZLL channels.

A.

**Comment by coolmcmarty** [comment]
Thanks for your quick response.

I tried channel 11, 12, 15 (and another I do not remember). I can try others if you think that this is the problem. Is there any specific channel that should always work?

Do you mean by by "exact device description" the information printed on the bottom of the sensor? 
It starts with "mi" followed by some chinese characters ending with "2" (I think its the name).
next lines look like (where # are some chinese letters i cannot write):
# #: RTCGQ02LM  (0 might be an O - not sure)
####: CR2450  (I think thats the battery-type)
CMIT ID: 2020DP12044
#############################
####

is that what you meant?

**Comment by asgothian** [comment]
If the device designation is correct then it will never work with the conbee II (or any other zigbee gateway), as it uses Bluetooth for connection.

![Screen Shot 2021-03-10 at 18 48 55 ](https://user-images.githubusercontent.com/45667167/110673595-46265f80-81d1-11eb-8451-3f75fe72cf02.png)

**Comment by coolmcmarty** [comment]
That would be a very good reason...  🙈
Thanks for your help/investigation!
