### ISSUE TITLE
direct binding of two Tradfri devices fails with error: TIMEOUT

### ISSUE THREAD

**Issue by cherberg** [ioBroker/ioBroker.zigbee#1028]
I am trying to establish a direct binding of two IKEA Tradfri devices 

Source: E1524/E1810  - Endpoint 1 All
Target: LED1732G11 - Endpoint 1 All

Binding fails with following Error message.

Failed to bind cluster 'genOnOff' from '0x680ae2fffe3e9cb4' to '0x680ae2fffe4a0685' (Error: Bind 0x680ae2fffe3e9cb4/1 genOnOff from '0x680ae2fffe4a0685/1' failed (waiting for response TIMEOU

**Comment by asgothian** [comment]
Did you keep the Ikea remote awake during the binding attempt ? Else it may be unavailable for the binding when the coordinator attempts to create it.

A.

**Comment by cherberg** [comment]
> 
> 
> Did you keep the Ikea remote awake during the binding attempt ? Else it may be unavailable for the binding when the coordinator attempts to create it.
> 
> A.
> 
> (Duplikate of #1029)

Thanx, I was not aware that this needs to be done, unfortunately I have not found any documentation.

I have clicked the buttons on the remote during the binding process and indeed the binding is reporter as successful.

Unfortunately the binding itself seems to be not functioning: no action of the remote results in a change on the bulb.

Both the trial to change the Endpoint from 1 All to any other as well as unbinding the two devices now fails with error message:

Failed to unbind cluster 'genOnOff' from '0x680ae2fffe3e9cb4' to '0x680ae2fffe4a0685' (Error: Unbind 0x680ae2fffe3e9cb4/1 genOnOff from '0x680ae2fffe4a0685/1' failed (Error: status: 136))

**Comment by asgothian** [comment]
Did you keep the remote awake during the unbinding as well ?

As a general rule, battery powered devices **must** be kept awake during any communication attempt from ioBroker due to their tendency to go to sleep to reduce battery drain.

Also: did you check the "unbind remote from coordinator" option when trying to perform the binding ?

A.

**Comment by cherberg** [comment]
> 
> 
> Did you keep the remote awake during the unbinding as well ?
> 
> As a general rule, battery powered devices **must** be kept awake during any communication attempt from ioBroker due to their tendency to go to sleep to reduce battery drain.
> 
> Also: did you check the "unbind remote from coordinator" option when trying to perform the binding ?
> 
> A.

Yes I am keeping the remote alive by clicking the buttons every few seconds, same as I did when establishing the binding.

The remote I used was freshly added to the Zigbee adapter and is not connected to any other device. I did not check the option "unbind remote from coordinator" during binding.
