### ISSUE TITLE
Binding of Remote with Group fails with Warning: EP undefined & Timeout 

### ISSUE THREAD

**Issue by cherberg** [ioBroker/ioBroker.zigbee#1029]
I have clustered 4 IKEA/Tradfri LED1623G12 into one group and I am trying to establish a direct binding with an IKEA/Trafri Remote, this fails

Source: E1524/E1810                    EP: 1 all
Target: Group of 4 LED1623G12   EP: **cannot be selected**

Log shows a warning first:
getBindEp called with illegal ep: undefined

then an Error:
Failed to bind cluster 'genOnOff' from '0x680ae2fffe3e9cb4' to 'Group 1' (Error: Bind 0x680ae2fffe3e9cb4/1 genOnOff from '1' failed (waiting for response TIMEOUT))

**Comment by asgothian** [comment]
Did you keep the Ikea remote awake during the binding attempt ? Else it may be unavailable for the binding when the coordinator attempts to create it.

A.

**Comment by asgothian** [comment]
Closed - further handling of this issue in #1028
