### ISSUE TITLE
wrong status of connection status / availability of Tradfri devices

### ISSUE THREAD

**Issue by cherberg** [ioBroker/ioBroker.zigbee#1030]
Dear Developer

I have two Tradfri Repeater that show disconnected/unavailable in the devices tab. Also under objects the datapoint "availability" of the two devices shows as "false". 
![grafik](https://user-images.githubusercontent.com/8701752/110988431-cf27cd00-8370-11eb-8b88-311da826b877.png)
![grafik](https://user-images.githubusercontent.com/8701752/110988470-dcdd5280-8370-11eb-9dbd-6685c938ba2f.png)
![grafik](https://user-images.githubusercontent.com/8701752/110988579-0302f280-8371-11eb-9fc2-02f532d6c2dd.png)
![grafik](https://user-images.githubusercontent.com/8701752/110988530-f41c4000-8370-11eb-9a0b-d547feebe009.png)
![grafik](https://user-images.githubusercontent.com/8701752/110989442-2da17b00-8372-11eb-82e9-f8bcf3b51b3a.png)
![grafik](https://user-images.githubusercontent.com/8701752/110989378-1b274180-8372-11eb-9640-ecc75855eb33.png)
![grafik](https://user-images.githubusercontent.com/8701752/110990224-54ac7c80-8373-11eb-85a7-521d284ecb13.png)

Both repeater devices are powered without interruption and should be available. In the in tab "network map" both devices show active with connections to other devices:
![grafik](https://user-images.githubusercontent.com/8701752/110988831-583f0400-8371-11eb-8a11-bc6d71556156.png)
![grafik](https://user-images.githubusercontent.com/8701752/110988898-6ab93d80-8371-11eb-9639-d8793c108a6d.png)

the bulbs can be controlled from the objects tab and also show available in the network map:
![grafik](https://user-images.githubusercontent.com/8701752/110989938-eb2c6e00-8372-11eb-9e13-5c1f6147be20.png)
![grafik](https://user-images.githubusercontent.com/8701752/110989976-faabb700-8372-11eb-9e02-1340a1608296.png)

Device Information Repeater:

    model:E1746
    description:TRADFRI signal repeater

    modelZigbee:TRADFRI Signal Repeater
    type:Router
    nwk:19508
    manuf id:4476
    manufacturer:IKEA of Sweden
    power:Mains (single phase)
    app version:33
    hard version:1
    zcl version:3
    stack version:98
    date code:20190311
    build:2.2.005
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genAlarms (9)
    haDiagnostic (2821)
    touchlink (4096)
    output clusters:genOta (25)
    genPollCtrl (32)
    touchlink (4096)

    endpoint:242
    profile:41440
    input clusters:greenPower (33)
    output clusters:greenPower (33)

Device Information bulbs:

Geräteinformation

    model:LED1623G12
    description:TRADFRI LED bulb E27 1000 lumen, dimmable, opal white

    modelZigbee:TRADFRI bulb E27 W opal 1000lm
    type:Router
    nwk:35841
    manuf id:4476
    manufacturer:IKEA of Sweden
    power:Mains (single phase)
    app version:33
    hard version:1
    zcl version:3
    stack version:98
    date code:20201102
    build:2.3.068
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    touchlink (4096)
    64636
    output clusters:genScenes (5)
    genOta (25)
    genPollCtrl (32)
    touchlink (4096)

    endpoint:242
    profile:41440
    input clusters:greenPower (33)
    output clusters:greenPower (33)

Geräteinformation

    model:LED1903C5/LED1835C6
    description:TRADFRI bulb E14 WS 470 lumen, dimmable, white spectrum, opal white

    modelZigbee:TRADFRI bulb E14 WS 470lm
    type:Router
    nwk:61729
    manuf id:4476
    manufacturer:IKEA of Sweden
    power:Mains (single phase)
    app version:33
    hard version:1
    zcl version:3
    stack version:98
    date code:20190312
    build:2.1.022
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    lightingColorCtrl (768)
    touchlink (4096)
    output clusters:genScenes (5)
    genOta (25)
    genPollCtrl (32)
    touchlink (4096)

    endpoint:242
    profile:41440
    input clusters:greenPower (33)
    output clusters:greenPower (33)

**Comment by asgothian** [comment]
- The map shows a snapshot of the configuration. Having lines in the map is not necessarily equivalent to having the devices be connected and usable.
- If bulbs can be controlled by changing the states it means that the bulb receives the message sent by the coordinator. The key question there is if you get any warning/error messages in the log when you control the bulb and if the state changes are "acknowledged" (turn green in the object tree) after changing. This would indicate that the bulb responds to the control command and as such should be set as available. In this case,  you may need to empty the browser cache and reload the page to get the correct state information visible.
- If the repeaters are available or not is hard to determine, as they do not regularly send messages.

In the end, the availability state relies on the so called "ping" function, which may be deactivated in the adapter settings. Please verify that this is not the case.

If the devices do not respond to the query sent during the ping they will be set as unavailable. As written above, this is not necessarily identical to you not being able to control the device, but it does mean that the device function may be unstable as the wireless communication is not working as intended.

If you want to debug this further, you need to
- install the current GitHub version
- Enter the IEEE address(es) (without the leading 0x) of the affected devices, split by ';' in the state zigbee.x.info.debugmessages (example: 5c0272fffe8a16dd;90fd9ffffe6c9550)
- watch the log for warn messages with the keyword "ELEVATED" to see if messages are sent to and/or received from the device.
Devices which never send any messages will end up considered unavailable by the Adapter.

Note that the available state is not currently used to block attempts to send commands to the lamp as there are a number of situations where a device will be listed as unavailable but still be controllable by the adapter.

A.

**Comment by cherberg** [comment]
_The map shows a snapshot of the configuration. Having lines in the map is not necessarily equivalent to having the devices be connected and usable._
I do have devices which on the map only show a coonnecion to the repeater in doubt. Still the function fine, therefor I believe the repeaters are active and status is wrong. 

_If bulbs can be controlled by changing the states it means that the bulb receives the message sent by the coordinator. The key question there is if you get any warning/error messages in the log when you control the bulb and if the state changes are "acknowledged" (turn green in the object tree) after changing. This would indicate that the bulb responds to the control command and as such should be set as available. In this case, you may need to empty the browser cache and reload the page to get the correct state information visible._
I can confirm that the command is properly accepted and the change is acknowledged (turns green in the object tree) Yet the availability remains false. I emptied the browser cache with no change in the behaviour.

_If the repeaters are available or not is hard to determine, as they do not regularly send messages._
I do have one identical repeater which shows properly connected.

_In the end, the availability state relies on the so called "ping" function, which may be deactivated in the adapter settings. Please verify that this is not the case._
I can confirm that this function is not deactivated.

On the debugging further I am afraid to say that I am a Windows / GUI user and I do not have the skillset to proceed with what you described.

_install the current GitHub version_
How do I do that?

_Enter the IEEE address(es) (without the leading 0x) of the affected devices, split by ';' in the state zigbee.x.info.debugmessages (example: 5c0272fffe8a16dd;90fd9ffffe6c9550)_
where would I need to enter this?

**Comment by asgothian** [comment]
> On the debugging further I am afraid to say that I am a Windows / GUI user and I do not have the skillset to proceed with what you described.
> 
> _install the current GitHub version_
> How do I do that?
> 
> _Enter the IEEE address(es) (without the leading 0x) of the affected devices, split by ';' in the state zigbee.x.info.debugmessages (example: 5c0272fffe8a16dd;90fd9ffffe6c9550)_
> where would I need to enter this?

Due to this we will need to go a different route. Please perform the following steps:

- Go to the Adapter list (in expert mode) and swap the zigbee Adapter to "debug".
- Run the adapter in Debug for at least 60 minutes while attempting to control the affected lightbulbs.
- Return to the Adapter List and swap the zigbee Adapter back to "info"
- go to the "log" tab and download todays log file. Note - you may have to tell your browser to download the text file instead of showing it.
- Open the log file in a text editor and remove all lines which do not include the text "zigbee.0" 
- go through the log and search for messages which contain the IEEE Address of the affected devices (without 0x, e.g 90fd9ffffe6c9550 for one of your lamps) The interesting messages are:
-- Successfully pinged ...
-- Failed to ping ...
-- Stopping to ping ...
-- Type (xxx) device (yyy) incoming event
Note that (xxx) and (yyy) can have various content depending on the device the event originated from

Please do NOT attempt to display either the device list or the map from within the zigbee configuration as this will cause issues with the recorded messages.

It is my expectation that:
- all Devices which do not show up as available will not generate "Successfully pinged..." messages.
- There will be no incoming event messages from devices which do not show up as available.
If this is correct the reason for this behavior lies with the hardware and not with the zigbee adapter and there is little we can do to fix it.

A.

**Comment by cherberg** [comment]
I am sorry (or happy) to say that I cannot proceed with the analysis since after a few reboots the issue no longer persists: all repeaters and all bulbs show active in the device tab and also in the network map.

P.S.: Thanx alot for your time and effort to develop such a great adapter. I have struggeled with an unstable Deconz/Phoscon app+adapter unstable that was partly "losing" devices for so long and I am now very happy to have switched to your adapter.
