### ISSUE TITLE
Link to zigbee2mqtt.io

### ISSUE THREAD

**Issue by Sacred-Shadow** [ioBroker/ioBroker.zigbee#1031]
![image](https://user-images.githubusercontent.com/61997661/111039598-22f8eb80-842f-11eb-951f-ee067b934918.png)

model: 902010/24 is correct 

The following link is generated from this: https://www.zigbee2mqtt.io/devices/902010/24.html
However, the correct link is: https://www.zigbee2mqtt.io/devices/902010_24.html

Apparently the / must be replaced by _ here.

Version 1.4.4

**Comment by kirovilya** [comment]
thanks. try to update from github

**Comment by asgothian** [comment]
Assumed fixed as OP referenced the issue in another PR.
