### ISSUE TITLE
Hue smart button and dimmer switch recognized but no values for events

### ISSUE THREAD

**Issue by boust3r** [ioBroker/ioBroker.zigbee#1033]
Hello,
I am quite new to the whole iobroker and zigbee adapter stuff. Please be pacient with me.

I set up my raspberry pi 4 with a cc2530 and got the zigbee network working. I managed to get several osram light bulbs and light stripes working as well as different kinds of aqara sensors. I used to have my Hue smart button working as well but it got lost on the way (I think after an update of the zigbee adapter which also caused general problems so I needed to flash my cc2530 again).

Now I am facing the problem that I just can't manage to integrate the Hue smart button (8718699693985) nor my Hue dimmer switch (324131092621). The are shown in the zigbee adapter and also in the objects of iobroker but the only values that are shown are:

**Hue smart button**:
ID                                 value
available                       true
battery                         88,5%
link_quality                   13

**Hue dimmer switch**:
ID                                value
available                      true
link_quality                  18

My adapters have the following versions:
admin 4.2.1
zigbee 1.4.4

I followed the cheat sheet and ended up here asking for help. If I need to provide more information please let me know which.

**Comment by asgothian** [comment]
Can you please check the log if you get messages about the Hue dimmer switch being configured ? As far as i remember the Dimmer requires a configuration to provide messages to the Coordinator.

A.

**Comment by boust3r** [comment]
Thank you for your fast answer. Yes I get a notification about it:

zigbee.0 | 2021-03-19 05:55:47.220 | warn | at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
-- | -- | -- | --
zigbee.0 | 2021-03-19 05:55:47.220 | warn | (2974) DeviceConfigure failed 0x001788010927d88e RWL022, attempt 1 (TypeError: Cannot read property 'write' of undefined
zigbee.0 | 2021-03-19 05:55:46.585 | info | (2974) Configuring 0x001788010927d88e RWL022
zigbee.0 | 2021-03-19 05:55:46.582 | info | (2974) Device '0x001788010927d88e' is supported, identified as: Philips Hue dimmer switch (324131092621)
zigbee.0 | 2021-03-19 05:55:46.580 | info | (2974) Successfully interviewed '0x001788010927d88e', device has succesfully been paired
zigbee.0 | 2021-03-19 05:55:33.005 | warn | (2974) Device '0x001788010927d88e' announced itself
zigbee.0 | 2021-03-19 05:55:32.983 | warn | (2974) Device '0x001788010927d88e' announced itself
zigbee.0 | 2021-03-19 05:55:32.835 | info | (2974) Starting interview of '0x001788010927d88e'

**Comment by asgothian** [comment]
Please pair the remote again. While pairing the remote, keep pressing a button on the remote every 2 to 3 seconds to keep the remote alive until you see a message that the device configure was successful.

Afterwards, the remote should work.

The same should hold true for the dimmer switch.

A.

**Comment by boust3r** [comment]
Thank you, the button now works, but unfortunately it didn't help for the dimmer switch:


zigbee.0 | 2021-03-19 07:02:33.254 | warn | at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
-- | -- | -- | --
zigbee.0 | 2021-03-19 07:02:33.254 | warn | (2974) DeviceConfigure failed 0x001788010927d88e RWL022, attempt 5 (TypeError: Cannot read property 'write' of undefined
zigbee.0 | 2021-03-19 07:02:32.751 | info | (2974) Configuring 0x001788010927d88e RWL022
zigbee.0 | 2021-03-19 07:02:31.449 | warn | at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
zigbee.0 | 2021-03-19 07:02:31.449 | warn | (2974) DeviceConfigure failed 0x001788010927d88e RWL022, attempt 4 (TypeError: Cannot read property 'write' of undefined
zigbee.0 | 2021-03-19 07:02:30.973 | info | (2974) Configuring 0x001788010927d88e RWL022
zigbee.0 | 2021-03-19 07:02:30.244 | warn | at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
zigbee.0 | 2021-03-19 07:02:30.244 | warn | (2974) DeviceConfigure failed 0x001788010927d88e RWL022, attempt 3 (TypeError: Cannot read property 'write' of undefined
zigbee.0 | 2021-03-19 07:02:29.542 | info | (2974) Configuring 0x001788010927d88e RWL022
zigbee.0 | 2021-03-19 07:02:27.536 | warn | at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
zigbee.0 | 2021-03-19 07:02:27.536 | warn | (2974) DeviceConfigure failed 0x001788010927d88e RWL022, attempt 2 (TypeError: Cannot read property 'write' of undefined
zigbee.0 | 2021-03-19 07:02:26.861 | info | (2974) Configuring 0x001788010927d88e RWL022
zigbee.0 | 2021-03-19 07:02:24.526 | warn | at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
zigbee.0 | 2021-03-19 07:02:24.526 | warn | (2974) DeviceConfigure failed 0x001788010927d88e RWL022, attempt 1 (TypeError: Cannot read property 'write' of undefined
zigbee.0 | 2021-03-19 07:02:23.901 | info | (2974) Configuring 0x001788010927d88e RWL022
zigbee.0 | 2021-03-19 07:02:23.899 | info | (2974) Device '0x001788010927d88e' is supported, identified as: Philips Hue dimmer switch (324131092621)
zigbee.0 | 2021-03-19 07:02:23.898 | info | (2974) Successfully interviewed '0x001788010927d88e', device has succesfully been paired
zigbee.0 | 2021-03-19 07:02:19.064 | warn | (2974) Device '0x001788010927d88e' announced itself
zigbee.0 | 2021-03-19 07:02:19.038 | warn | (2974) Device '0x001788010927d88e' announced itself
zigbee.0 | 2021-03-19 07:02:18.894 | info | (2974) Starting interview of '0x001788010927d88e'

**Comment by boust3r** [comment]
Do you have another idea what I can do?

**Comment by asgothian** [comment]
Not off the top of my head. I did just notice that the log from the RWL022 you posted is incomplete. Most notably, the device configure error message is truncated.

Can you please retry and post the relevant log section from a downloaded log (as opposed to a log you copied from the admin interface) ?

A.

**Comment by vaaarg** [comment]
I have the same problems. 

zStack3x0
version:2-1.2.7.1.
revision:20210120
Zigbee 1.4.4
Node.js
v14.16.0 
CC26X2R1 TI Launchpad


None of the Hue Dimmer Switches are working. 
I can pair them without error but none of the buttons are working. no reaction is displayed within iobroker.
other xiaomi switches are working properly.

**Comment by asgothian** [comment]
Do you 
- keep them alive to get configured after pairing ?
- see messages that the configuring was successful after the pairing ?
- get error message on the attempt to configure them ?

A.

**Comment by vaaarg** [comment]
yes but no reaction

New device joined '0x0017880104e62664' model 324131092621
Interview successful: {"friendly_name":"0x0017880104e62664","model":"324131092621","vendor":"Philips","description":"Hue dimmer switch","supported":true}

Device '0x0017880104e62664' announced itself
Interview started: 0x0017880104e62664

**Comment by asgothian** [comment]
This is just the interview itself. The log should contain messages containing either
`DeviceConfigure failed 0x001788010927d88e RWL022`
or 
`DeviceConfigure successful 0x001788010927d88e RWL022`

A.

**Comment by vaaarg** [comment]
yes ok but when i press the pairing button above messages come within few seconds.
afterwards i also pressed the device buttons several times but nothing showed up.

the hue button and bulbs worked.

any other suggestions ?

**Comment by asgothian** [comment]
There is no other suggestion.

The Remote needs to be configured to send button press events to the zigbee Coordinator. This is done automatically by the zigbee adapter
- the first time the device is paired
- every time the adapter is restarted.
If you cannot find a notification on a successful device configuration after pairing the device the remote **will not send events to the iobroker**

A.

**Comment by vaaarg** [comment]
one switch now working, the others show successfully configured but also do not recognize any buttons.

i will keep tryin ;)

DeviceConfigure successful 0x001788010673435e RWL021
Configuring 0x001788010673435e RWL021
Device '0x001788010673435e' is supported, identified as: Philips Hue dimmer switch (324131092621)
Successfully interviewed '0x001788010673435e', device has succesfully been paired

**Comment by boust3r** [comment]
Hello again, 

thanks for your answers. I will provide the log as soon as the zigbee adapter works again... when trying to pair the dimmer switch the whole adapter crashend and doesn't start anymore. This is the second time this happend when trying to pair the dimmer switch. 
The only way I figured so far to get it running again is reflashing the CC2530 stick. Unfortunately this will take me a while to reconfigure all other devices again.  I'll send a log as soon as possible, hopefully by the end of this week. 

Again thank you for your support =)

B.

**Comment by boust3r** [comment]
I managed to get if fixed today early and only tried to enter the Hue dimmer switch for now. I continually pressed some buttons on the dimmer switch for the whole duration until the info "zigbee stop joining". 
The downloaded log reads as follows:


2021-04-06 12:58:42.125  - info: zigbee.0 (3054) Zigbee: allowing new devices to join.
--
2021-04-06 12:58:55.809  - info: zigbee.0 (3054) Starting interview of '0x001788010927d88e'
2021-04-06 12:58:59.924  - info: zigbee.0 (3054) Successfully interviewed '0x001788010927d88e', device has succesfully been paired
2021-04-06 12:58:59.925  - info: zigbee.0 (3054) Device '0x001788010927d88e' is supported, identified as: Philips Hue dimmer switch (324131092621)
2021-04-06 12:58:59.930  - info: zigbee.0 (3054) Configuring 0x001788010927d88e RWL022
2021-04-06 12:59:00.848  - warn:  zigbee.0 (3054) DeviceConfigure failed 0x001788010927d88e RWL022,  attempt 1 (TypeError: Cannot read property 'write' of undefined
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
2021-04-06 12:59:01.413  - info: zigbee.0 (3054) Configuring 0x001788010927d88e RWL022
2021-04-06 12:59:02.638  - warn:  zigbee.0 (3054) DeviceConfigure failed 0x001788010927d88e RWL022,  attempt 2 (TypeError: Cannot read property 'write' of undefined
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
2021-04-06 12:59:03.298  - info: zigbee.0 (3054) Configuring 0x001788010927d88e RWL022
2021-04-06 12:59:04.445  - warn:  zigbee.0 (3054) DeviceConfigure failed 0x001788010927d88e RWL022,  attempt 3 (TypeError: Cannot read property 'write' of undefined
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
2021-04-06 12:59:06.520  - info: zigbee.0 (3054) Configuring 0x001788010927d88e RWL022
2021-04-06 12:59:07.760  - warn:  zigbee.0 (3054) DeviceConfigure failed 0x001788010927d88e RWL022,  attempt 4 (TypeError: Cannot read property 'write' of undefined
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:3984:29))
2021-04-06 12:59:08.646  - info: zigbee.0 (3054) Configuring 0x001788010927d88e RWL022
2021-04-06 12:59:19.271  - warn:  zigbee.0 (3054) DeviceConfigure failed 0x001788010927d88e RWL022,  attempt 5 (Error: Bind 0x001788010927d88e/1 genLevelCtrl from  '0x00124b0014d96946/1' failed (AREQ - ZDO - bindRsp after 10000ms)
at Timeout.waiter.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10))
2021-04-06 12:59:43.380  - info: zigbee.0 (3054) Zigbee: stop joining

**Comment by asgothian** [comment]
> 2021-04-06 12:59:19.271 - warn: zigbee.0 (3054) DeviceConfigure failed 0x001788010927d88e RWL022, attempt 5 (Error: Bind 0x001788010927d88e/1 genLevelCtrl from '0x00124b0014d96946/1' failed (AREQ - ZDO - bindRsp after 10000ms)
> at Timeout.waiter.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
> at ontimeout (timers.js:436:11)
> at tryOnTimeout (timers.js:300:5)
> at listOnTimeout (timers.js:263:5)
> at Timer.processTimers (timers.js:223:10))
> 2021-04-06 12:59:43.380 - info: zigbee.0 (3054) Zigbee: stop joining

Zumindest diese Fehlermeldung deutet darauf hin das der Hue Dimmer Switch aus welchem Grund auch immer nicht auf die Versuche ihn zu Konfigurieren antwortet.

Leider kann ich nur eines empfehlen: Weiter probieren.

A.

**Comment by boust3r** [comment]
Oh man. So ein mist. Hab es schon ca. 50 mal probiert...

Danke für die Hilfe.

@vaaarg was ist denn bei dem einen Dimmer switch der funktioniert anders gelaufen?

B.

**Comment by vaaarg** [comment]
> Oh man. So ein mist. Hab es schon ca. 50 mal probiert...
> 
> Danke für die Hilfe.
> 
> @vaaarg was ist denn bei dem einen Dimmer switch der funktioniert anders gelaufen?
> 
> B.

war wohl Zufall. Habe danach noch 10 x versucht die restlichen 2 einzubinden ohne Erfolg.
Obwohl alles als erfolgreich gemeldet wird funktioniert kein tastendruck.

**Comment by boust3r** [comment]
Welche Taste drückst du denn immer? Und wie oft? Hab auch noch 3 weiter hier, aber noch nicht ausgepackt.

**Comment by vaaarg** [comment]
> Welche Taste drückst du denn immer? Und wie oft? Hab auch noch 3 weiter hier, aber noch nicht ausgepackt.

zum pairen einmal die setup taste kurz. das hat früher ausgereicht um das gerät in betrieb zu nehmen.
man kann wohl alle 4 tasten ein paar sekunden drücken für einen "reset". brachte aber keinen erfolg

**Comment by boust3r** [comment]
Also ich habe nun auch die anderen Dimmer Switches probiert und kein einziger kann konfiguriert werden vom Zigbee Adapter. Da  muss doch ein systematischer Fehler vorliegen.

**Comment by arteck** [comment]
das geht ... ich hab die auch im einsatz.. 
hatte aber zuletzt auch Probleme mit dem anlernen .. 

probier mal so:

anlernen dann siehst du die Kachel..
adapter stop
warte 3 sek
adapter start
und jetzt einmal hinten in das kleine Loch reinstochern in Coordinator nähe

**Comment by vaaarg** [comment]
> das geht ... ich hab die auch im einsatz..
> welchen Kanal benutzt du ?

Also ich habe auf Kanal 11. Habe es nun nochmal wie im letzten post beschrieben versucht. keine änderung.
Die Switches sind angelernt und konfigueriert aber es wird keinerlei tastendruck übermittelt.

**Comment by boust3r** [comment]
Nach dem neuen Update des Zigbee Adapters wurden die Schalter endlich gefunden. Ich habe keine Änderung vorgenommen und musst nicht neu koppeln.
