### ISSUE TITLE
Cannot bind devices

### ISSUE THREAD

**Issue by easybeat** [ioBroker/ioBroker.zigbee#1034]
Hi

I'm new with this adapter and I just can't bind any devices. Is there something else I have to configure?

My coordinator looks OK:
![image](https://user-images.githubusercontent.com/37217887/111611348-a5413100-87dc-11eb-8f8f-8bbfab4f5866.png)

My stick is Electrolama zig-a-zig-ah! (zzh!) CC2652R.

Any help would be very helpful.

Thanks

**Comment by easybeat** [comment]
I also just tried with a conbee II with latest firmware and same effect. I can start Join and it counts down but the device never get paired.

I'm running ioBroker on Proxmox. Any idea where the problem could be`?

**Comment by asgothian** [comment]
- Did you ensure that the device you want to pair is actually in pairing mode ?
- Which device(s) did you try ?
A.

**Comment by easybeat** [comment]
Hi
yes as I'm using Deconz and just want to test this Zigbee adapter, I know exactly how to pair a device and how to set it in pairing mode.

I tried 2 different devices:
- Aqara Opple 2x Switch WXCJKG12LM
- Fantem 4in1 sensor ZB003-X (⭐EXP)

Thanks

**Comment by asgothian** [comment]
did you 
- remove the devices from deconz before trying
- disable deconz for the attempt ?
Especially the Xiaomi Devices will attempt to rejoin a known network if it is still available at the time.

A.

**Comment by easybeat** [comment]
I used completely new devices fresh unpacked and yes for sure deconz was disabled.

Also just tried a Osram GU10 light...just no reaction at all.

Is it working with ioBroker on a Proxmox VM?

**Comment by easybeat** [comment]
OK I found the problem and I hope this might help others!

I had a power problem on the USB devices attached to my Intel NUC as I also had an external hdd and a zwave stick attached.

Only with the zigbee stick in USB it works fine....not sure how I can solve this but that's another problem.

Thanks for your inputs.
