### ISSUE TITLE
No connection to zigbee (worked a few hours ago)

### ISSUE THREAD

**Issue by PhagoZ** [ioBroker/ioBroker.zigbee#1035]
![adapter_issue_log](https://user-images.githubusercontent.com/53466094/111683353-a21e6300-8825-11eb-980f-9f80299985ab.JPG)

This morning it worked fine, and now it´s broken.

tried to update to github version, but nothing happens.

runs on a rasp pi 4

Does anyone have an idea?

**Comment by asgothian** [comment]
Please do the following:

- stop the zigbee adapter
- Unplug the coordinator
- Wait 30 seconds
- Plug in the coordinator
- Start the zigbee adapter

if It does not run post the complete startup log, not just the broken final few seconds.

A.

**Comment by PhagoZ** [comment]
I did all this befor I opened the issue.
I switched to a conbee2 stick, which I had laying around.
Now it is working, I just have to rename all my devices.

looks like 33 devices (incl. 4 osram repeater) are too much for the CC... stick
