### ISSUE TITLE
Please implement Ikea Styrbar Remote *THX*

### ISSUE THREAD

**Issue by bigmaxking** [ioBroker/ioBroker.zigbee#1039]
STYRBAR Ikea Remote Zigbee
Model W2049 19972
2x AAA 1.5V

thank you guys!!! Stay healthy 
max
![image](https://user-images.githubusercontent.com/81173525/112008453-c5972580-8b25-11eb-80d5-9d7953f410b5.jpg)
![Uploading image.jpg…]()

![image](https://user-images.githubusercontent.com/81173525/112008052-73ee9b00-8b25-11eb-98b4-73e2c1b9310c.jpg)
![image](https://user-images.githubusercontent.com/81173525/112007994-6802d900-8b25-11eb-8ec2-a13f4a1800c7.jpg)

**Comment by asgothian** [comment]
This device is not currently supported in the zigbee-herdsman-converters project (not listed at zigbee2mqtt.io) and as such cannot directly be supported by the zigbee adapter. Implementing it will require access to the hardware (which i do not have as it is not offered by Ikea here) or patience until it is implemented [here](https://github.com/Koenkk/zigbee-herdsman-converters/issues)

Alternatively, you can follow [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device) and attempt integration.

A.

**Comment by bigmaxking** [comment]
Thank you @asgothian! I will have a try with the guideline for unknown devices

**Comment by Velonaut** [comment]
@asgothian Hi, the device is listet in zigbee2mqtt.io
https://www.zigbee2mqtt.io/devices/W2049.html

**Comment by TZanke** [comment]
My STYRBAR is white only and has the Type: W2118 printed inside. Outside it is printed TYPE:E2002

See: https://www.zigbee2mqtt.io/devices/E2001_E2002.html

Maybe this helps. But the Zigbee adapter shows W2049:
zigbee V 1.5.6

![image](https://user-images.githubusercontent.com/1613368/141687099-e924e417-11c6-4e80-a4db-810ac31c741b.png)
