### ISSUE TITLE
Mesh priority

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#104]
I only have 3 devices .. the Coordinator, an Osram socket which can also repeat and the Aqara cube. The Coordinator is furthest away but my Cube won't connect to the Osram socket. Maybe Zigbee sorts itself (sorry .. I have no idea how Zigbee works) but maybe it could also be a good idea to tell the Cube to prioritize the connection to the Osram socket. Chances are that the signal strength to the Cube is higher the way it is .. but how should I know?!

**Comment by kirovilya** [comment]
For this case press small green-pairing button on Osram card (not big green button on top) in adapter settings dialog. This will allow you to pair new devices only with the router - Osram in your case.

**Comment by daniel-lo** [comment]
I tried that .. but it didn't work. Something like a could not register node error (or so).

**Comment by daniel-lo** [comment]
Just tried again .. so I can be more precise:

zigbee.0 | 2018-11-22 11:08:41.330 | error | Cannot get the Node Descriptor of the Device: 0x00158d000278e743 (Error: Timed out after 10000 ms)
-- | -- | -- | --

Generally chaining works for me .. but not with the Aqara Cube!

**Comment by daniel-lo** [comment]
Hi .. is the issue clear .. or can I help with more information? Will u address this?

**Comment by kirovilya** [comment]
Do not quite understand what is not working.
The cube does not pairing?

**Comment by daniel-lo** [comment]
It pairs with the coordinator but not with an attached Osram socket .. I use the pairing symbol on the socket but all I see is one line with the error above.

**Comment by daniel-lo** [comment]
I did so .. I know how to pair it with the coordinator .. so I don't thing I'm doing anything wrong.

**Comment by kirovilya** [comment]
@daniel-lo maybe...

**Comment by daniel-lo** [comment]
Just received an aqara door sensor .. same thing .. cannot pair via socket

**Comment by kirovilya** [comment]
Try to bring the sensor close to the socket during pairing.

**Comment by daniel-lo** [comment]
Strange things happening. Paring with socket failed .. then tried to pair with coordinator .. was also not working well .. now the device is paired with the socket?! I guess I should stick to testing with cube ;-)

**Comment by daniel-lo** [comment]
I tried again with my cube .. this time I didn't use the pairing button on the socket symbol but the general one .. but I was closer to the socket than to the coordinator. Now the qube is paired to the socket.
Are the pairing buttons all the same and the mesh is something that changes by itself by field strenght?

**Comment by kirovilya** [comment]
Big button - starts pairing all over the network at once: coordinator and all routers

**Comment by daniel-lo** [comment]
ok .. thanks .. maybe there is something fishy with the pairing button on the osram socket

**Comment by allofmex** [comment]
@daniel-lo 
There is sadly no way to force a enddevice to a specific parent/router. You may pair with a specific router only, but **the enddevice** may switch its parent later (hopefully to the one with strongest signal). This is zigbee's design.
The new NetworkMap shows you the current parent (as reported by routers), the previous map was not always correct in this reguard.
