### ISSUE TITLE
Implement SOS-EF-3.0 Heimann 

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.zigbee#1041]
Hi, implement SOS-EF-3.0 from Heimann ( looks like same model https://www.zigbee2mqtt.io/devices/HS1EB_HS1EB-E.html ), please.

![grafik](https://user-images.githubusercontent.com/36229898/112590474-2ca52a80-8e03-11eb-9eaf-2cbe35c5ba56.png)
![grafik](https://user-images.githubusercontent.com/36229898/112590696-8d346780-8e03-11eb-9a00-833f911683e5.png)

thanks in advance!

**Comment by asgothian** [comment]
Implementing this device requires a working implementation in the zigbee-herdsman-converters project. Doing this requires physical access to the device.

At this point, your best chances for this are
- attempt the integration yourself using the documentation provided in the wiki and/or at zigbee2mqtt.io
- make an issue at the zigbee-herdsman-converters repository asking for someone to implement the device.
A.
