### ISSUE TITLE
Netzwerkkarte und Anzeige Empfangsqualität

### ISSUE THREAD

**Issue by Reto84** [ioBroker/ioBroker.zigbee#1042]
Hallo zusammen,

Ich betreibe den Iobroker in einer Ubuntu VM und der Zigbee Adapter ist ein Conbee II.

Ich habe mit dem Adapter 2 Probleme:

**Netzwerkkarte**
Die ersten paar Tage nach der Installation des Adapters und dem Anlernen der Geräte (Hauptsächlich Xiaomi DoorSensor, Schalter und Temperatur) wurde die Netzwerkkarte immer korrekt aufgebaut. Jedoch habe ich nun seit mehreren Wochen das sich die Karte in den seltensten Fällen aufbaut, es sieht dann so aus:

![Netzwerkkarte](https://user-images.githubusercontent.com/81419898/112627766-4dd13f80-8e32-11eb-9889-a94c27d24a72.JPG)

Ich warte dann auch entsprechend 1-2 Minuten auf der Seite, aber die Karte zeigt alle Sensoren Offline an.

**Empfangsqualität**
Wenn ich den Adapter (oder den Server) neu starte, haben die Sensoren extrem schlechte Empfangswerte (zwischen 0 und 5), dann dauert es jeweils mehrere Tage und die Empfangswerte steigern sich wieder (bis 200) und fallen dann aber wieder. Interessant ist, das alle Sensoren dann immer die gleichen Empfangswerte haben, z.B. wie jetzt 59:

![Sensoren](https://user-images.githubusercontent.com/81419898/112628117-c0421f80-8e32-11eb-9801-89aef3ca1d25.JPG)

Die Sensoren funktionierten auch leider nicht zuverlässig.

Hat jemand eine Idee woran dies liegen könnte?

Danke&Gruss Reto

**Comment by asgothian** [comment]
- Which adapter version are you running ?
- Please verify if the link quality matches the one reported by the devices (run the adapter in Debug for a day, download the log and search the log for messages containing the keyword "linkquality". These messages show the link quality reported to the adapter for each device.
A.

**Comment by arteck** [comment]
after adapter start you can see ALL devs have a link quality 10.. this is correct and increases after next ping or 'hello' message..its normal

**Comment by asgothian** [comment]
No response - assumed closed.

**Comment by larryxxl2** [comment]
zigbee läuft 3 Tage absolut perfect..  Dann fangen die Probleme an. Geräte melden sich offline sind aber teilweise noch erreichbar. unter Objekte verschwinden dann Datenpunkte. 
![image](https://user-images.githubusercontent.com/96195330/146224546-4d61ffef-a40a-447b-bc20-abfe30462b04.png)

Zigbee 1.6.8
