### ISSUE TITLE
Xiaomi Opple 3-fach Taster

### ISSUE THREAD

**Issue by superpoli** [ioBroker/ioBroker.zigbee#1044]
Hallo,
ich habe diverse Geräte mit Zigbee und Skripten hinterlegt. Jetzt neu einen Aqura Opple 3-Fach Doppeltaster.
Frisch in ioBroker angelernt(ohne irgendwelche Verknüpfungen) schaltet er mir meine Osram Lampen einer Gruppe mit Taste 1.
Wie kann das sein?

**Comment by arteck** [comment]
lerne den ncohmal an ohne den zu löschen.. der hat sein configure nicht bekommen..

**Comment by superpoli** [comment]
Komme leider nur immer wieder bis "announced self", die Konfiguration scheint er sich nicht zu ziehen.

**Comment by Flipperbastler** [comment]
> 
> 
> Komme leider nur immer wieder bis "announced self", die Konfiguration scheint er sich nicht zu ziehen.
> Wird aber unter Geräte richtig angezeigt.

Nach "announced self" nochmals kurz (!) die Pairing- / Reset-Taste drücken, dann wird die Config übertragen.

**Comment by superpoli** [comment]
Nochmal gelöscht und neu angelegt, jetzt ist alles tutti.
