### ISSUE TITLE
missing stats

### ISSUE THREAD

**Issue by serav993** [ioBroker/ioBroker.zigbee#1046]
hi guys,

i bought some https://www.zigbee2mqtt.io/devices/AC08560.html of these and there is no level.color.rgb states in the objects.
i used cc3125 as coordinator
Do you might have any idea?

**Comment by asgothian** [comment]
- which adapter version are you using ?
- What happens if you add the device to the exclude list in the adapter ?
A.

**Comment by serav993** [comment]
i use version 1.4.4
and what do you mean with, add device to exclude list ?

**Comment by asgothian** [comment]
There should be a tab „ausschließen“ or „exclude“ where you can add device types.

A.

**Comment by asgothian** [comment]
No response, assumed closed.

**Comment by serav993** [comment]
Sorry, I travel around the world because of work. I solved the Prob. Execlude current device type was the correct workaround. Thanks a lot and sorry my english is not very good
