### ISSUE TITLE
Integration Temperatursensor

### ISSUE THREAD

**Issue by andreas0022** [ioBroker/ioBroker.zigbee#1048]
Hallo, habe einen Temperatursensor, die als TS0601 in zigbee erkannt wird, aber nichts weiteres... muss diese noch integriert werden?
hier ein paar Bilder:

![image](https://user-images.githubusercontent.com/54526221/114262439-425c4780-99e0-11eb-9079-8ca789f54788.png)

![20210410_084556](https://user-images.githubusercontent.com/54526221/114262615-489ef380-99e1-11eb-9299-078066c80ece.jpg)

![20210410_084350](https://user-images.githubusercontent.com/54526221/114262637-62d8d180-99e1-11eb-8406-fc313a792761.jpg)
![20210410_084328](https://user-images.githubusercontent.com/54526221/114262639-653b2b80-99e1-11eb-9f58-4485cfa6bf19.jpg)
![image](https://user-images.githubusercontent.com/54526221/114262705-b519f280-99e1-11eb-92e6-2df94a63124f.png)

danke

**Comment by asgothian** [comment]
Mit welcher Adapter version hast du das probiert ?

A.

**Comment by andreas0022** [comment]
mit dieser:

![image](https://user-images.githubusercontent.com/54526221/114273176-6e47ef00-9a19-11eb-8edb-622b15c880b4.png)


Danke, A.

**Comment by pjanfred** [comment]
Wenn du auf das "i" unten links klickst, steht da unter manufacturer zufällig "_TZE200_cwnjrr72"? Falls ja musst du nur warten bis die neue "zigbee-herdsman-converters" Version eingebunden wurde. Da wurde das Gerät nämlich vor 12 Tagen integriert.

**Comment by pjanfred** [comment]
Ich weiß das es nicht state-of-the-art ist, aber ich habe es gerade bei mir gefixt indem ich die fehlende ID einfach in der entsprechenden zigbee-herdsman-converters Datei ergänzt habe. Wird ja dann mit dem nächsten Update vermutlich eh kommen.

Datei lag bei mir an folgendem Ort:
/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js

Hab dann die ID von einem funktionierenden Thermostat gesucht. In meinem Fall: ywdxldoj
Den entsprechenden JSON block kopiert, die ID geändert und den Adapter neugestartet ;).
Workaround läuft!

**Comment by andreas0022** [comment]
Hallo,
nicht ganz; dort steht "_TZE200_bq5c8xfe"
![image](https://user-images.githubusercontent.com/54526221/114293571-7c3c5500-9a97-11eb-8b64-83b5d98f1db0.png)

was das workaround betrifft, bin ich (noch) nicht so bewandert, bin eher der Anwender-Typ. aber ich werde mich mal einlesen und gegebenenfalls probieren.

Besten Dank, Andreas
