### ISSUE TITLE
Device MLI-404011 (ZBT-Remote-ALL-RGBW) Müller Licht missing groups object

### ISSUE THREAD

**Issue by dembach** [ioBroker/ioBroker.zigbee#1049]
I am missing the possiblity to assign and use the groups for the Device.

on [](https://www.zigbee2mqtt.io/devices/MLI-404011.html) you can see that there should be a groups object.

thanks

Markus

**Comment by asgothian** [comment]
- on (missing information here) you can see that there should be a groups object ?
- Binding remotes to a group is usually done via the "binding" menu. The remote is not part of a group but bound to the group to control it.
- Keep in mind when binding the remote to the group that you have to keep the remote "awake" during the binding process or it may fail with an error code.

A.

**Comment by dembach** [comment]
okay.. let me share the link for that device on zigbee2mqtt:

[https://www.zigbee2mqtt.io/devices/MLI-404011.html](https://www.zigbee2mqtt.io/devices/MLI-404011.html)

**Comment by asgothian** [comment]
As i wrote above: 

Remotes are added as group members but bound to the group using the binding feature.

A.
