### ISSUE TITLE
no battery.percent anymore ?

### ISSUE THREAD

**Issue by rewegit** [ioBroker/ioBroker.zigbee#105]
Is it possible that the state battery.percent is no longer written? In ioBroker there is apparently no more change.
And in devstates.js I see no getter: now.

    battery: {
        id: 'battery',
        prop: 'battery',
        name: 'Battery percent',
        icon: 'img/battery_p.png',
        role: 'battery.percent',
        write: false,
        read: true,
        type: 'number',
        unit: '%',
        min: 0,
        max: 100
    },

**Comment by kirovilya** [comment]
`getter` is needed if you need to convert values. now the value of the battery percent is taken ready from the incoming message

**Comment by rewegit** [comment]
Thanks for the information.
Do you happen to know which formula was used to calculate it?

Thank you very much for your great work.

**Comment by kirovilya** [comment]
formula is here https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L206
conversion table is used

**Comment by rewegit** [comment]
Thank you very much
