### ISSUE TITLE
Livarno Lux smart LED light does not exposing effect enums in iobroker

### ISSUE THREAD

**Issue by CorruptOffset** [ioBroker/ioBroker.zigbee#1054]
Hi,

The following device does not support the effect enum like provided here[LINK](https://www.zigbee2mqtt.io/devices/HG06104A.html)

Is there a workaround to this ? Following I pasted from device.js from Adapter 1.4.4?

`ieee:0x588e81fffed0e317
nwk:46471 (0xb587)
model:HG06104A`

` {
        fingerprint: [{modelID: 'TS0505A', manufacturerName: '_TZ3000_riwp3k79'}, {manufacturerName: '_TZ3000_riwp3k79'}],
        model: 'HG06104A',
        vendor: 'Lidl',
        description: 'Livarno Lux smart LED light strip 2.5m',
        ...preset.light_onoff_brightness_colortemp_color({disableColorTempStartup: true}),
        meta: {applyRedFix: true, configureKey: 1},
        configure: async (device, coordinatorEndpoint, logger) => {
            device.getEndpoint(1).saveClusterAttributeKeyValue('lightingColorCtrl', {colorCapabilities: 31});
        }, `

Regards Offset

**Comment by asgothian** [comment]
I am afraid i cannot make sense of this issue:

- The code pasted is code from the zigbee-herdsman-converters, not from the zigbee Adapter.
- The device is implemented explicitly in the devices.js.
- The description and the title do not match and are ambiguous, please clarify: Does the device itself not support the effects state (which is generated by the converters expose functionality), or is the effects state missing in your object tree ?

In case of the latter: Adding the device class to the "excludes" (and subsequently restarting the adapter) should make the state available in ioBroker.

A.

**Comment by CorruptOffset** [comment]
Sorry for the confusion. With the Code Above I only wanted to specify the device I have issues with. 
What I meant is that the device supprots "effects" like said on "zigbee2mqtt" but the enum is not exposed in the object tree in ioBroker.

I see you already provided the solution. Can you assist here with a specifc example what to change and where to change?

Furthermore the attribute transitiontime is not taking into efffect any value when changing color or whatsso ever. Everything works fine. 
Thanks for your support.
Regards

**Comment by asgothian** [comment]
See this screenshot. Go to the "To Exclude" tab and add the device to the list, then restart.
<img width="825" alt="Screen Shot 2021-04-14 at 19 51 55 " src="https://user-images.githubusercontent.com/45667167/114756357-f3554000-9d5a-11eb-9fa0-cc0b23a41dce.png">

**Comment by CorruptOffset** [comment]
Thanks. The eextra fields are now usable in the object tree. Sadly they have no effect when changing them.

Can you explain why the excluding of the device let's the attributes appear again? my guess  that there is a custom converter for the iobroker the zigbee implementation?

**Comment by asgothian** [comment]
Please read [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/Exposes-for-device-integration) about the expose functionality. It will explain some of the background. What remains is this:

- Devices which are listed in the devices.js file in the zigbee adapter will use the configuration defined there
- Devices which are not listed in the devices.js file in the zigbee adapter will use the exposed configuration
- Devices which are listed in the exclude list will use the exposed configuration even if a configuration is present in devices.js

Note that this is only true while the device is in the exclude list. Adding / Removing a device to/from the exclude list requires an adapter restart and will modify the device states. As such, it is advised to use the "cleanup states" button which is available in the adapter configuration to remove states which are no longer linked to the device.

Messages should be printed to the log file if changing a state does not result in any reaction of the device itself. It may be necessary to run the adapter in debug mode to see these messages.

A.
