### ISSUE TITLE
Hue Aurelle is shown like this

### ISSUE THREAD

**Issue by WernerRH21** [ioBroker/ioBroker.zigbee#1057]
![image](https://user-images.githubusercontent.com/67897090/114640667-e12ebf80-9cd0-11eb-92d5-293cee04dee3.png)
Switch state is possible.
I have installed the latest 1.4.6 adapter.
Thanks for your help.

**Comment by asgothian** [comment]
Please install the current 'latest' adapter and see if that changes the display issue.

A.

**Comment by asgothian** [comment]
How does the device detail card for this device look ? Since you renamed the device, the actual Identifier of the device is missing from the tile.

Please click the "name" (Flurlicht) to turn the tile over and post the content.

A.
