### ISSUE TITLE
zzh! CC2652R Router error

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.zigbee#1058]
Hi Guys,

I added a zzh! (CC2652R) stick as router to my zigbee network, that worked ok.

But it does not seem to work and I constantly get the following errors in the log:
`(1654) Device 0x00124b0021b9505d "ti.router" not described in statesMapping.
(1654) Device 00124b0021b9505d "ti.router" not described in statesMapping.`

The router is shown like this:
![image](https://user-images.githubusercontent.com/69499563/114759710-cefb6280-9d5e-11eb-9aa9-8080127523d1.png)

And in objects like this:
![image](https://user-images.githubusercontent.com/69499563/114759796-e76b7d00-9d5e-11eb-9802-ab3976d85cb8.png)

Its also not visible in the network tab.
Can you help me to fix this error?

As coordinator I use a CC1352P-2 device connected to ioBroker on a Raspberry 4.
I use the latest stable version (1.4.4) of the adapter.

Thx and brgds,

Claus

**Comment by Claus1985** [comment]
@kirovilya does that mean that if I install the newest build from GitHub it’s fixed?
Thx!

**Comment by kirovilya** [comment]
Yes

**Comment by Claus1985** [comment]
@kirovilya Thx for the tipp!
When I try to install it from github I get an error:
`Fertig mit Fehler: internal/modules/cjs/loader.js:1044 throw err; ^SyntaxError: /opt/iobroker/node_modules/iobroker.zigbee/io-package.json: Unexpected token } in JSON at position 160 at parse () at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:480:19) at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1632:24 at ChildProcess. (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:481:47) at ChildProcess.emit (events.js:314:20)`

Do you know how to fix this?

**Comment by kirovilya** [comment]
ahhh... my mistake

**Comment by kirovilya** [comment]
try again

**Comment by Claus1985** [comment]
Worked! Router is acknowledged without errors, thx!
Until now it’s only connected to another router and not to devices, but I guess that’s a matter of time until the Network changes?
