### ISSUE TITLE
Aqara single wall switch / wrong state

### ISSUE THREAD

**Issue by skroob** [ioBroker/ioBroker.zigbee#1060]
Long press state is wrong. Stay always true.

JS-Controler: 3.2.16
Zigbee-Adapter: 1.5.1
Conbee 2 Stick

![2021-04-17_171443](https://user-images.githubusercontent.com/17686871/115117919-2f79e200-9fa1-11eb-98a1-333811f93e50.jpg)
![2021-04-17_171453](https://user-images.githubusercontent.com/17686871/115117926-34d72c80-9fa1-11eb-9ecd-5110a9fca8ee.jpg)
![2021-04-17_171515](https://user-images.githubusercontent.com/17686871/115117928-36085980-9fa1-11eb-9bb4-5d7f8c63916d.jpg)

**Comment by asgothian** [comment]
Please verify if holding the switch will
- generate a message (see the log)
- change the hold state back to false when you let go.

A.

**Comment by skroob** [comment]
Hi,
I have check this. When I push the long, the state in ioBroker switch short to green. But the data point text never change, it always true. The time stamp will updated correct. No warnings in log.

![2021-04-22_082844](https://user-images.githubusercontent.com/17686871/115667818-8fc4a700-a346-11eb-95bd-7bbb2ceb7842.jpg)

**Comment by asgothian** [comment]
Is this switch currently set in the exclude list of the adapter ? If not, can you please (temporarily0 add it to the exclude list and restart the adapter to see if the states generated through the exposes show correct behaviour ? If it is, can you please (again temporarily) remove the switch from the exclude list and restart the adapter ?

For the exclude list check the attached screenshot. The "to Exclude" tab is where you can perform this action.

<img width="702" alt="Screenshot 2021-04-22 at 13 03 08" src="https://user-images.githubusercontent.com/45667167/115704013-19866b80-a36b-11eb-82a2-941216e4fb91.png">

A.

**Comment by skroob** [comment]
Hi,
normaly the switch is not in the exclude list. So I set him to the exclude list, becomes the switch new names in state single click, double click and hold. In this setting the hold state runing well (switching false to true and back). So I set the switch out of the exclude list and delete all click states. Push all states for initialisation, then dosn't function hold state and stay always in true.
