### ISSUE TITLE
Feature Discussion

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.zigbee#1061]
Hello All,

with the new dashboard feature of the devices display for the Zigbee adapter, a new method of dealing with groups and group members seems sensible:

- Add Group Tiles to the Devices / Dashboard so that groups can be controlled from the dashboard as well
- List group members on the group tile
- Add new groups through a new button next to the "Pairing" button
- Handle group rename / removal identical to device rename/removal

Good news: I managed to patch the card display in with limited effort/impact. (See attached Screenshot - note that i did not modify the standard card / dashcard functions, nor did i add an icon yet)

Questions: 
- Should this be continued ? 
- Should this lead to removing the "groups" Tab as all actions can be performed in the devices tab ?

Thoughts ?

A.

**Comment by kirovilya** [comment]
I agree that groups can also be displayed on the devices panel.
Display the list of devices on the "back" side of the group card.
In this case, we can delete the tab for the groups.

where is the attached screenshot? :)

**Comment by asgothian** [comment]
It does help to attach it :)

<img width="1310" alt="Screen Shot 2021-04-18 at 14 23 48 " src="https://user-images.githubusercontent.com/45667167/115145418-b25a7580-a051-11eb-81e5-95418bc8f9fe.png">

Left card is turned to device card
Right card is turned to dashcard

**Comment by asgothian** [comment]
I have an initial working version at
https://github.com/asgothian/ioBroker.zigbee/tarball/GroupsOnDashboard.
So far, my tests were successful. There still are a few minor issues to iron out (limit card size for large groups, allow device removal from the group card, unneccessary error messages, but it should be fine to test.

<img width="810" alt="Screen Shot 2021-04-21 at 20 15 29 " src="https://user-images.githubusercontent.com/45667167/115601631-535d6080-a2de-11eb-8da3-824961109db3.png">
