### ISSUE TITLE
innr sp120 no power consumption value available

### ISSUE THREAD

**Issue by p3ab0dy** [ioBroker/ioBroker.zigbee#1064]
Hey guys I have a problem with version 1.5.1.
I'm using the TI CC26x2r1.

My SP120 don't show power consumption ...

I already saw this issue: https://github.com/ioBroker/ioBroker.zigbee/issues/983 
and added the SP120 to "Ausschlussliste" I see all availabel parameters but no values.

![2021-04-20 13_14_19-objects - ioBroker](https://user-images.githubusercontent.com/11159624/115387051-71419d00-a1da-11eb-9b30-55342ad1ba2b.png)

The TI is new and arrived today. I flashed it with the coordinator role and the howto priveded here: https://www.zigbee2mqtt.io/information/supported_adapters.html

I hope anyone has an idea

**Comment by asgothian** [comment]
Are you certain that your SP120 still provides the measurement ? Innr removed the ability when moving to the latest SP120 version.

A.

**Comment by p3ab0dy** [comment]
I'm glad to haven an old vhw version 1 plug. 
It was also working nice with the conbee II stick before I swtiched to the TI.

**Comment by o0shojo0o** [comment]
I have the same combination with me running and can not determine this behavior 
![image](https://user-images.githubusercontent.com/19333515/115395619-5d9b3400-a1e4-11eb-9f4a-d86b7fc46850.png)
![image](https://user-images.githubusercontent.com/19333515/115395639-612ebb00-a1e4-11eb-96ea-587badd34ec4.png)

**Comment by p3ab0dy** [comment]
Hm ok after fourth attemp to relearn it to the controller it finally worked. I think because I left the entry of the SP120 in "Ausschlussliste" did the trick.
![2021-04-20 16_39_08-objects - ioBroker](https://user-images.githubusercontent.com/11159624/115415186-fb97fa00-a1f6-11eb-933e-8ee63f58d190.png)

Thanks for guideance and assuring that the powerplug is working with the controller.
