### ISSUE TITLE
Busch+Jäger 6737 - row 3 and 4 not working

### ISSUE THREAD

**Issue by Ellerburg** [ioBroker/ioBroker.zigbee#1066]
Hi,
after connecting my Busch Jaeger 6737 via Deconz Stick and the Zigbee adapter to iobroker I am not able to get the row 3 and 4 to work as expected.

Please find below the details of the object and the warning messages from the log.

I am on version 1.4.4

Thanks for any hint how to get the issue resolved!

Cheers!

![Screenshot 2021-04-21 204246](https://user-images.githubusercontent.com/82972590/115607482-5576ed80-a2e5-11eb-9fba-7bee66140341.png)
![Screenshot 2021-04-21 204619](https://user-images.githubusercontent.com/82972590/115607496-5871de00-a2e5-11eb-87e8-cc09b3fb9b3e.png)

**Comment by asgothian** [comment]
The log shows that your device refuses the required reporting configuration for specific endpoints. Please attempt to pair the remote again (after deleting) and keeping it awake by pressing button until the configuration has been successfully completed. You will need to watch the log for this.

A.

**Comment by Ellerburg** [comment]
Hi @asgothian 

Thanks for your feedback!
Unfortunately it dint work by just pressing a button to keep the device alive...
Within seconds the device is paired and also failed to pair the row 3 and 4...

Do you have any addditional suggestion how to proceed?

![image](https://user-images.githubusercontent.com/82972590/117055944-09cc3700-ad1c-11eb-815d-d48275f6050c.png)

Thanks!

**Comment by Ellerburg** [comment]
Hi @asgothian ,

I tried to repair several times now - without any success for rows 3 and 4.

Do you have any other idea how to get it work?

Thanks in advance!

E

**Comment by asgothian** [comment]
I am afraid not. What you can do is raise an issue at the zigbee-herdsman-converters. The key pieces of information you should provide in the issue are:
- the exact device ID
- the fact that the device refuses configuration (and the error message from the log)
- your current version of the zigbee-herdsman-converters library (easiest way to find out: on the console in the folder /opt/iobroker enter the command npm list | grep zigbee-herdsman-converters)


A.

**Comment by froogl** [comment]
I had the same problem with Zigbee2Mqtt. In the Zigbee2Mqtt documentation it is stated that sometimes you need to set up the bindings to the coordinator manually. I don't know ioBroker, but maybe this can also help there:

https://www.zigbee2mqtt.io/devices/6735_6736_6737.html

It might be worth a chance to remove all bindings and then recreate them one by one. As I said, this helped me in Z2M.
