### ISSUE TITLE
Tab icon in Admin 5

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.zigbee#1068]
Did you already test your adapter in Admin 5 with React? (I can't test it right now as I'm on my phone)

From what I can see, you used an HTML hack to use your own tab icon instead of a standard FA icon.

If you really want to keep using your icon, I would suggest to create a PR for Admin which makes it possible to support SVG icons other than FA. This would have to be done in a way that is backwards compatible.

I would also suggest to use a theme compatible svg (using the special color `currentColor`), so it is more in line with the FA icons of other tabs (ie monochrome). Here are examples how I achieved this for the dev portal: https://github.com/UncleSamSwiss/iobroker-dev-portal/blob/1cc4d5b10083b37c95c04e326886e096a2c7aa15/express/frontend/src/components/Icons.tsx#L27

**Comment by asgothian** [comment]
I have tested the Adapter with React - it behaves as expected.
- Within the adapter config, the theme is ignored, the HTML is displayed as it would be without react
- With the Tab, parts of the theme are honored (background color), but many are not (text color on some tabs, Coloring of Buttons and other UI elements.
As far as the tab icon goes, the Zigbee Tab is in good company with the Backitup, EChards and Javascript adapter.

A.

**Comment by UncleSamSwiss** [comment]
OK, sounds good. How about a Change Request (Issue) for Admin to officially support non-FA icons?

**Comment by kirovilya** [comment]
all works fine with original icons. not only our adapter
![image](https://user-images.githubusercontent.com/8360230/116606068-dd3da700-a938-11eb-8f75-fd83d645a6b8.png)

**Comment by UncleSamSwiss** [comment]
It seems like everything works fine.
What I don't like (from a maintainability perspective) is that there is a "hack" to display another icon. I believe there should be a straight forward way to define a non-FontAwesome icon.

Currently you are using this:
https://github.com/ioBroker/ioBroker.zigbee/blob/dbe52d251fca2e767ff860d4b449286ab23835c2/io-package.json#L183

I would prefer if admin 5 supported something like 
```json

        "adminTab": {
            ...
            "icon": "zigbee.svg"
        }
```

See also my request here: https://github.com/ioBroker/ioBroker.admin/issues/797

**Comment by UncleSamSwiss** [comment]
Admin 5 will no longer use tab specific icons but rather just the adapter icon. Thus, this is no longer an issue.
