### ISSUE TITLE
Wrong link on tile for for Tradfri E1525/E1745

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.zigbee#1069]
The tile for Tradfri device E1525 / E1745 has the wrong link to the device Database: 

Wrong
https://www.zigbee2mqtt.io/devices/E1525/E1745.html

Right: 
https://www.zigbee2mqtt.io/devices/E1525_E1745.html

**Comment by asgothian** [comment]
closed in latest GitHub version.+

Testing required.

**Comment by Grothesk242** [comment]
I can confirm that the link is working now.

**Comment by Grothesk242** [comment]
Sorry, I just found that the link in the popup, that pops up when clicking the i-icon bottom left still goes into a 404.
