### ISSUE TITLE
battery percentage is wrong

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#107]
battery stat percentage is different between gateway and cc2531
here same sensor
![cc2531](https://user-images.githubusercontent.com/6681528/48705854-afe26000-ebfa-11e8-9687-efe3c52da408.png)
![xiaomi](https://user-images.githubusercontent.com/6681528/48705855-b07af680-ebfa-11e8-893e-4645affaf8c3.png)

**Comment by kirovilya** [comment]
:) Gateway not send percent - it is calculating in our (iobroker) adapter https://github.com/ioBroker/ioBroker.mihome/blob/master/lib/Sensors/Cube.js#L31
https://github.com/ioBroker/ioBroker.mihome/blob/master/lib/Sensors/MotionSensor.js#L19
At first, we also used this formula, but then someone it seemed that it was not correct.

**Comment by arteck** [comment]
you right.. I did not think about that
