### ISSUE TITLE
Firefox: Netzwerkkarte wird "abgeschnitten"

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.zigbee#1075]
Wenn ich auf die Netzwerkkarte gehe, wird nur ein Teil des Bildschirms genutzt und die Übersicht somit abgeschnitten. Wenn ich auf den Refresh button klicke ist alles in Ordnung und der Bildschirm wird voll genutzt. Wenn ich dann im zigbee Adapter z.B. auf Geräte klicke und dann wieder auf Netzwerkkarte wird wieder abgeschnitten.
Das hab ich jetzt erst im Rahmen von Tests (admin 5.0.x) gemerkt
Das Problem tritt bei Firefox und Firefox Nightly auf, Opera und Chrome sind ok...

![grafik](https://user-images.githubusercontent.com/45561610/116477422-e0735d00-a87c-11eb-86d0-4ac865243d00.png)

firefox browser, Konsole sagt
`[2021-04-28T21:58:11.619Z] Try to connect socket.io.js:59:41
"A-Z": {"en": "A-Z", "de": "A-Z", "ru": "A-Z", "pt": "A-Z", "nl": "A-Z", "fr": "A-Z", "es": "A-Z", "pl": "A-Z", "it": "A-Z", "zh-cn": "A-Z"}, translate.js:24:17
"Default": {"en": "Default", "de": "Default", "ru": "Default", "pt": "Default", "nl": "Default", "fr": "Default", "es": "Default", "pl": "Default", "it": "Default", "zh-cn": "Default"}, translate.js:24:17
"Tranport Key Text": {"en": "Tranport Key Text", "de": "Tranport Key Text", "ru": "Tranport Key Text", "pt": "Tranport Key Text", "nl": "Tranport Key Text", "fr": "Tranport Key Text", "es": "Tranport Key Text", "pl": "Tranport Key Text", "it": "Tranport Key Text", "zh-cn": "Tranport Key Text"}, translate.js:24:17
"Disable active availability check": {"en": "Disable active availability check", "de": "Disable active availability check", "ru": "Disable active availability check", "pt": "Disable active availability check", "nl": "Disable active availability check", "fr": "Disable active availability check", "es": "Disable active availability check", "pl": "Disable active availability check", "it": "Disable active availability check", "zh-cn": "Disable active availability check"}, translate.js:24:17
"Expert mode": {"en": "Expert mode", "de": "Expert mode", "ru": "Expert mode", "pt": "Expert mode", "nl": "Expert mode", "fr": "Expert mode", "es": "Expert mode", "pl": "Expert mode", "it": "Expert mode", "zh-cn": "Expert mode"}, translate.js:24:17
"Exclude configuration": {"en": "Exclude configuration", "de": "Exclude configuration", "ru": "Exclude configuration", "pt": "Exclude configuration", "nl": "Exclude configuration", "fr": "Exclude configuration", "es": "Exclude configuration", "pl": "Exclude configuration", "it": "Exclude configuration", "zh-cn": "Exclude configuration"}, translate.js:24:17
"exclude device": {"en": "exclude device", "de": "exclude device", "ru": "exclude device", "pt": "exclude device", "nl": "exclude device", "fr": "exclude device", "es": "exclude device", "pl": "exclude device", "it": "exclude device", "zh-cn": "exclude device"}, translate.js:24:17
"Channels": {"en": "Channels", "de": "Channels", "ru": "Channels", "pt": "Channels", "nl": "Channels", "fr": "Channels", "es": "Channels", "pl": "Channels", "it": "Channels", "zh-cn": "Channels"}, translate.js:24:17
"clear": {"en": "clear", "de": "clear", "ru": "clear", "pt": "clear", "nl": "clear", "fr": "clear", "es": "clear", "pl": "clear", "it": "clear", "zh-cn": "clear"}, translate.js:24:17
"Add exlude": {"en": "Add exlude", "de": "Add exlude", "ru": "Add exlude", "pt": "Add exlude", "nl": "Add exlude", "fr": "Add exlude", "es": "Add exlude", "pl": "Add exlude", "it": "Add exlude", "zh-cn": "Add exlude"}, translate.js:24:17
"Filter": {"en": "Filter", "de": "Filter", "ru": "Filter", "pt": "Filter", "nl": "Filter", "fr": "Filter", "es": "Filter", "pl": "Filter", "it": "Filter", "zh-cn": "Filter"}, translate.js:24:17
"A-Z": {"en": "A-Z", "de": "A-Z", "ru": "A-Z", "pt": "A-Z", "nl": "A-Z", "fr": "A-Z", "es": "A-Z", "pl": "A-Z", "it": "A-Z", "zh-cn": "A-Z"}, translate.js:24:17
"Default": {"en": "Default", "de": "Default", "ru": "Default", "pt": "Default", "nl": "Default", "fr": "Default", "es": "Default", "pl": "Default", "it": "Default", "zh-cn": "Default"}, translate.js:24:17
"All": {"en": "All", "de": "All", "ru": "All", "pt": "All", "nl": "All", "fr": "All", "es": "All", "pl": "All", "it": "All", "zh-cn": "All"}, translate.js:24:17
"Tranport Key Text": {"en": "Tranport Key Text", "de": "Tranport Key Text", "ru": "Tranport Key Text", "pt": "Tranport Key Text", "nl": "Tranport Key Text", "fr": "Tranport Key Text", "es": "Tranport Key Text", "pl": "Tranport Key Text", "it": "Tranport Key Text", "zh-cn": "Tranport Key Text"}, translate.js:24:17
"Disable active availability check": {"en": "Disable active availability check", "de": "Disable active availability check", "ru": "Disable active availability check", "pt": "Disable active availability check", "nl": "Disable active availability check", "fr": "Disable active availability check", "es": "Disable active availability check", "pl": "Disable active availability check", "it": "Disable active availability check", "zh-cn": "Disable active availability check"}, translate.js:24:17
"Expert mode": {"en": "Expert mode", "de": "Expert mode", "ru": "Expert mode", "pt": "Expert mode", "nl": "Expert mode", "fr": "Expert mode", "es": "Expert mode", "pl": "Expert mode", "it": "Expert mode", "zh-cn": "Expert mode"}, translate.js:24:17
"Exclude configuration": {"en": "Exclude configuration", "de": "Exclude configuration", "ru": "Exclude configuration", "pt": "Exclude configuration", "nl": "Exclude configuration", "fr": "Exclude configuration", "es": "Exclude configuration", "pl": "Exclude configuration", "it": "Exclude configuration", "zh-cn": "Exclude configuration"}, translate.js:24:17
"exclude device": {"en": "exclude device", "de": "exclude device", "ru": "exclude device", "pt": "exclude device", "nl": "exclude device", "fr": "exclude device", "es": "exclude device", "pl": "exclude device", "it": "exclude device", "zh-cn": "exclude device"}, translate.js:24:17
"Channels": {"en": "Channels", "de": "Channels", "ru": "Channels", "pt": "Channels", "nl": "Channels", "fr": "Channels", "es": "Channels", "pl": "Channels", "it": "Channels", "zh-cn": "Channels"}, translate.js:24:17
"clear": {"en": "clear", "de": "clear", "ru": "clear", "pt": "clear", "nl": "clear", "fr": "clear", "es": "clear", "pl": "clear", "it": "clear", "zh-cn": "clear"}, translate.js:24:17
"Add exlude": {"en": "Add exlude", "de": "Add exlude", "ru": "Add exlude", "pt": "Add exlude", "nl": "Add exlude", "fr": "Add exlude", "es": "Add exlude", "pl": "Add exlude", "it": "Add exlude", "zh-cn": "Add exlude"}, translate.js:24:17
"Filter": {"en": "Filter", "de": "Filter", "ru": "Filter", "pt": "Filter", "nl": "Filter", "fr": "Filter", "es": "Filter", "pl": "Filter", "it": "Filter", "zh-cn": "Filter"}, translate.js:24:17

​`

intel nuc mit proxmox vm (debian 10)
node-js 14.16.1
npm 6.14.12
admin adapter 5.0.10 mit react UI
zigbee 1.5.1

**Comment by asgothian** [comment]
Please test with
- the current version (1.5.5)
- the current Admin (not Admin 5)

**Comment by amg666** [comment]
Looks good even with Admin 5.0.26 which I have in use
