### ISSUE TITLE
js-controller 3.3.x

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.zigbee#1077]
![image](https://user-images.githubusercontent.com/19333515/116661728-34716500-a995-11eb-832e-a295542b3217.png)
![image](https://user-images.githubusercontent.com/19333515/116661850-5965d800-a995-11eb-837a-a70a2c5008c7.png)

**Comment by kueppert** [comment]
und hier auch als Text:

zigbee.0 | 2021-04-30 14:51:28.140 | warn | (18311) State value to set for "zigbee.0.00158d00036b2c08.pressure" has value "1002" greater than max "100"
zigbee.0 | 2021-04-30 14:50:16.260 | warn | (18311) State value to set for "zigbee.0.00158d000273d4a7.pressure" has value "1002.6" greater than max "100"
zigbee.0 | 2021-04-30 14:49:25.116 | warn | (18311) State value to set for "zigbee.0.00158d000278952b.pressure" has value "1002" greater than max "100"

**Comment by arteck** [comment]
fixed
