### ISSUE TITLE
Warnmeldungen nach JS-Controller Update

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.zigbee#1079]
Hi,
bekomme im Log folgende Warnmeldungen,

Adaptername | Zeit | Status | Meldung
-- | -- | -- | --
zigbee.0 | 2021-04-30 17:41:09.191 | warn | zigbee.0 (17015) State value to set for "zigbee.0.60a423fffeab479f.local_temperature_calibration" has value "-1" less than min "undefined"
zigbee.0 | 2021-05-01 13:13:59.073 | warn | Read-only  state "zigbee.0.info.pairingMessage" has been written without ack-flag  with value "Device '0x60a423fffeab4b27' announced itself"

EDIT: die zweite Zeile kam gerade auch noch dazu

**Comment by JBSullivan** [comment]
Schließe mich dem an, allerdings mit der folgenden Meldung und den entsprechenden RAW Daten des DP.

`
influxdb.0 | 2021-05-01 22:44:31.533 | info | (6880) Do not store value "" for zigbee.0.ccccccfffeb3c8d4.state because no number
-- | -- | -- | --
web.0 | 2021-05-01 22:44:30.521 | info | (11564) State value to set for "zigbee.0.ccccccfffeb3c8d4.state" has to be type "boolean" but received type "string"

`

`{
  "type": "state",
  "common": {
    "name": "Available",
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "state"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1612453185829,
  "_id": "zigbee.0.ccccccfffeb3c8d4.available",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by asgothian** [comment]
> Schließe mich dem an, allerdings mit der folgenden Meldung und den entsprechenden RAW Daten des DP.
> 
> `
> 
> influxdb.0	2021-05-01 22:44:31.533	info	(6880) Do not store value "" for zigbee.0.ccccccfffeb3c8d4.state because no number
> web.0	2021-05-01 22:44:30.521	info	(11564) State value to set for "zigbee.0.ccccccfffeb3c8d4.state" has to be type "boolean" but received type "string"
> `
> 
> `{ "type": "state", "common": { "name": "Switch state", "type": "boolean", "read": true, "write": true, "role": "switch", "custom": { "influxdb.0": { "enabled": true, "changesOnly": true, "debounce": "1000", "maxLength": 10, "retention": "31536000", "changesRelogInterval": "3600", "changesMinDelta": 0, "storageType": "Number", "aliasId": "" } } }, "native": {}, "from": "system.adapter.zigbee.0", "user": "system.user.admin", "ts": 1612453185829, "_id": "zigbee.0.ccccccfffeb3c8d4.state", "acl": { "object": 1636, "state": 1636, "owner": "system.user.admin", "ownerGroup": "system.group.administrator" } }`

An dieser Stelle ist deine vis / der influx Adapter für die Warnmeldungen verantwortlich. Der state ist sauber als “Boolean” definiert und wird auch als Boolean vom zigbee Adapter gesteuert.

**Comment by asgothian** [comment]
> Hi,
> bekomme im Log folgende Warnmeldungen,
> 
> Adaptername	Zeit	Status	Meldung
> zigbee.0	2021-04-30 17:41:09.191	warn	zigbee.0 (17015) State value to set for "zigbee.0.60a423fffeab479f.local_temperature_calibration" has value "-1" less than min "undefined"
> zigbee.0	2021-05-01 13:13:59.073	warn	Read-only state "zigbee.0.info.pairingMessage" has been written without ack-flag with value "Device '0x60a423fffeab4b27' announced itself"
> EDIT: die zweite Zeile kam gerade auch noch dazu

Das müssen wir uns anschauen. Es kann aber ein paar Tage dauern.

A.

**Comment by arteck** [comment]
jo die hab ich auch 
![grafik](https://user-images.githubusercontent.com/6681528/116807362-1a6d8900-ab33-11eb-9b43-dcd5ee6d546b.png)

**Comment by arteck** [comment]
Read-only state "zigbee.0.info.pairingMessage" has been written without ack-flag with value "Device '0x60a423fffeab4b27' announced itself"

gerade gefixt

**Comment by MMeinhardt1** [comment]
Hi @asgothian,
ich habe Deine Fragen im Forum gelesen daher hier mal die RAW Daten des DP,

{
  "type": "state",
  "common": {
    "name": "Offset to be used in the local_temperature",
    "type": "number",
    "unit": "°C",
    "read": true,
    "write": true,
    "role": "state",
    "min": 0
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1618635807293,
  "_id": "zigbee.0.60a423fffeab3359.local_temperature_calibration",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

Ich hoffe das hilft weiter.

Sonnige Grüße

**Comment by asgothian** [comment]
bitte das genaue device dazu schreiben, sowie ob es über exposes oder devices eingebunden ist.

A

**Comment by MMeinhardt1** [comment]
Siehe den Beitrag dazu, [hier](https://forum.iobroker.net/topic/44200/zigbee-neue-version-1-5-x/32?_=1619978403021)
Es sind die MOES HY368 Heizungsthermostaten und eingetragen unter "ausschliessen".

Danke

**Comment by MMeinhardt1** [comment]
Hi, gibt es zu dem Problem zufällig schon Neuigkeiten?

**Comment by MMeinhardt1** [comment]
@asgothian @arteck @kirovilya 
Habt ihr eine Idee ob und wann ihr euch dem beschriebenen Problem annehmen könnt?

**Comment by asgothian** [comment]
Wir werden uns des Problems annehmen, aktuell gibt es aber wegen Anpassungen im herdsman einige Probleme die erst gelöst werden müssen

A.

**Comment by MMeinhardt1** [comment]
Hi @asgothian und @arteck,
wollte gerade mal schauen ob sich was getan hat mit V1.6.0 und habe den Temperatur-Offset getestet, es sieht jetzt so aus. Die Meldung kommt nicht mehr von Zigbee Adapter sondern vom Admin und aus dem „undefined“ ist „0“ geworden, könntet ihr da nochmal nachbessern?

`2021-08-19 20:22:47.342 - warn: admin.0 (24925) State value to set for "zigbee.0.60a423fffea0d030.local_temperature_calibration" has value "-1" less than min "0"`

vielen Dank

**Comment by x-Rainer-x** [comment]
I have an issue with a Shelly 1PM
State value to set for "shelly.0.SHSW-PM#E8DB84D7EBB5#1.Relay0.longpush" has to be type "string" but received type "boolean"

As quick fix I have updated the file shelly1pm.js in folder /opt/iobroker/node_modules/iobroker.shelly/lib/devices


'Relay0.longpush': {
    coap: {
      coap_publish: '2102', // CoAP >= FW 1.8
      coap_publish_funct: (value) => { return value === 'L'; }
    },
    mqtt: {
      mqtt_publish: 'shellies/<mqttprefix>/longpush/0',
      mqtt_publish_funct: (value) => { return value; }
    },
    common: {
      'name': 'Longpush',
      'type': '**boolean**',
      'role': 'state',
      'read': true,
      'write': false
    }

**Comment by Apollon77** [comment]
@x-Rainer-x Why you add this to an already closed zigbee issue when it affects shelly?
