### ISSUE TITLE
Philips Hue Dimmer Switch - Short and Long press

### ISSUE THREAD

**Issue by Bearonic** [ioBroker/ioBroker.zigbee#108]
Hi,

in principle, the Hue Dimmer Switch (ioBroker zigbee adapter 0.7.7 / flashed CC2531 on RPi3) does work. But there is a different behavior compared to when it is paired with an Hue Bridge.

Previosly, I had it paired with an Hue Bridge 2.1 and used a script with node-hue-api in ioBroker to poll the states. That way it was possible to distinguish between short and long (> ~1s) presses for all 4 buttons.

With zigbee2mqtt it is not possible to detect short and long presses. Rather, the "I" and "O" buttons do only toggle one state and the darker/brighter buttons always create a "button down" followed by a "button released" event. This reduces the flexibility and range of functions of the Dimmer Switch significantly.

I would love to see the same behavior as when using a Hue Bridge. Would this be possible? I already digged into the 'devices.js' and 'fromZigbee.js', but I have no idea what's to do.

Note:
Interestingly, the flashing of the LED on the Dimmer Switch differs from when paired with the Hue Bridge. I guess, this means, that the Hue Bridge sends messages to the Dimmer Switch as well.

**Comment by dwm66** [comment]
Agreed, this would make the device much more useful. 
Additionally, would be great to get "button down" and "button up" events (at least from the dimmer buttons) separately, so a script could emulate the "normal" behavior (when long pressed, dim up or down respectively, until released).

**Comment by Bearonic** [comment]
Over at zigbee2mqtt the problem seems to be solved: https://github.com/Koenkk/zigbee2mqtt/issues/585
Would be great, if the new implementation could be transfered to iobroker.zigbee soon as well.

**Comment by Bearonic** [comment]
Can this implementation be integrated to the zigbee adapter here? That would be awsome.
I don't know, how this is to be done, because there's some cross dependencies which aren't up to date.

**Comment by arteck** [comment]
see new Version
