### ISSUE TITLE
All devices disappeared in Dashboard after upgrading the adapter

### ISSUE THREAD

**Issue by DaCHRIS** [ioBroker/ioBroker.zigbee#1080]
Hi together, 

after upgrading the zigbee adapter to version 1.5.3 all devices disappeared from the dashboard. 

Pairing new devices is still possible, but the new devices are not shown too. 

JS-Controller: 3.3.4
ZigBee Adapter: 1.5.3

![image](https://user-images.githubusercontent.com/8064903/116783696-8d71f380-aa90-11eb-877d-2c57f5ea44b0.png)

I am not able to identify any errors in the logs, so I have no idea how to look deeper in this. 

Anyone can help me with this? 

Cheers 

Chris

**Comment by skvarel** [comment]
Same here!

**Comment by FredF63** [comment]
Same here.
Admin 4.2.1
js-controller 3.2.16
zigbee 1.5.1

**Comment by DaCHRIS** [comment]
I tried several things, and for me it lastly it worked to:

- downgrade to 1.4.1
- upgrade to 1.5.3 again
- rebooting the pi 

There are still a lot of warnings and the map isn't working, but the dashboard has all devices and the devices can be controlled.

**Comment by DaCHRIS** [comment]
Reopened for @skvarel cause his issue is ongoing.

**Comment by DaCHRIS** [comment]
@skvarel 

![image](https://user-images.githubusercontent.com/8064903/116809782-1d22ab00-ab40-11eb-9f36-3606bf7e4be4.png)

**Comment by mediaDS** [comment]
Same here. 

### General System Information:

**System**: ioBroker
**Hostname**: Casper
**Platform**: Linux arm64 @  Odroid-C2 
**Memory**: 2 GB
**Node.js**: 12.22.0
**NPM**: 6.14.11
**JS-Controller**: 3.2.16
**Admin Adapter**: 5.0.12
**JS Script Engine**: 5.1.3

### Adapter Information:

**Z-Wave Adapter**: 1.10.0
**Zigbee Adapter**: 1.5.3
**MQTT Adapter**: 2.3.5 (Broker)
**Z-Wave Controller**: USB ZME-UZB1
**Zigbee Controller**: CC2531 PCB zStack12 v2.0.2.6.3

### Z-Wave Devices (24): 

7 x Roller Shutter Controller: Fibaro FGRM-222
1 x Multisensor: Aotec MS ZW100
2 x Multisensor: DB5
4 x Multisensor: Fibaro FGMS-001
1 x Siren: Everspring SE812
1 x Water Sensor: Everspring ST812
1 x Water Sensor: Fibaro FGFS-101
3 x Dimmer: Fibaro FGD-212
2 x Main Switches: Greenwave NS310
1 x Window Sensor: Schwaiger ZHS09
1 x Smoke Detector: Vision ZS6101

### Zigbee Devices (14):

1 x Mueller Color LED A60 ZBT-Extended Color
2 x Philips Hue Motion Sensr SML001
6 x Philips Hue White Single Bulb B22 LWB010
1 x Philips Hue White Ambience E14 LTW012
1 x Philips Hue White and Color LCT010
3 x Philips Hue White A60 LWA001

### WiFi Devices:

1 x Weather station ESP32 via MQTT
1 x Radar Motion Sensor ESP8266 via MQTT

### Visualisation Displays:

2 x Waveshare 10.1" Touch Display, Raspbian Buster @ Raspberry 3B+

**Comment by skvarel** [comment]
The the latest github (02.May. 11:24) repo/update was succesful.

Thx a lot for the great job!

**Comment by asgothian** [comment]
> Same here. Downgraded. Upgraded. Rebootet. All empty. But - all devices are working fine. Very strange.
> 

Not strange. The issues may be connected.. Please open the JavaScript debug console on your browser and check for errors occurring when loading the device overview.

You can also attempt to install from my test branch to see if a fix i introduced there will change the behavior on your side. (https://github.com/asgothian/ioBroker.zigbee/tarball/GroupsOnDashboard). Note that you will have to perform a manual adapter upload after installing this version.

The device with address 0x0 must be present in your shepherd.db. You should be able to force delete it once you regain access to the device cards. I assume that it is this device which is also at fault for the devices to not show, but manually editing the shepherd.db is not an easy fix.

A.

**Comment by asgothian** [comment]
PR #1084 should fix this. Closed.
