### ISSUE TITLE
Datapoint for (air)pressure max value to low

### ISSUE THREAD

**Issue by eric2905** [ioBroker/ioBroker.zigbee#1082]
Since update to controller v3.3.5 I get for every air pressure datapoint (“pressure”) a warning.
Value is higher than the max value…. “State value to set for "zigbee.1.xxxxxxx.pressure" has value "980" greater than max ….”

Max value for this datapoint is set to 100 … a little bit to low 😉
Manual set max. value to 2000 works fine

**Comment by asgothian** [comment]
Please post which device types generate this error as reference. Fix should be small, but finding the correct state may be tricky.

A.

**Comment by eric2905** [comment]
> Please post which device types generate this error as reference. Fix should be small, but finding the correct state may be tricky.
> 
> A.

It is the Aqara temperatur, humidity and pressure sensor
https://www.amazon.de/Aqara-Temperature-Humidity-Sensor-Feuchtigkeitssensor/dp/B07D37FKGY

**Comment by arteck** [comment]
is fixed
