### ISSUE TITLE
Fehler mit zweiter Instanz nach Update Node.js v10 auf 12

### ISSUE THREAD

**Issue by Lassebroker** [ioBroker/ioBroker.zigbee#1085]
Moin,

nach dem Update auf v12.22.1 habe ich folgendes Problem: Erste Instanz funktioniert, zweite Instanz bleibt gelb und liefert folgende Fehler:
`

zigbee.1 | 2021-05-02 15:42:19.376 | error | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
-- | -- | -- | --
zigbee.1 | 2021-05-02 15:42:19.376 | error | at SerialPort._error (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee.1 | 2021-05-02 15:42:19.376 | error | at SerialPort.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
zigbee.1 | 2021-05-02 15:42:19.376 | error | at __awaiter (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
zigbee.1 | 2021-05-02 15:42:19.376 | error | at new Promise (<anonymous>)
zigbee.1 | 2021-05-02 15:42:19.376 | error | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
zigbee.1 | 2021-05-02 15:42:19.376 | error | at Generator.next (<anonymous>)
zigbee.1 | 2021-05-02 15:42:19.376 | error | at Znp.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
zigbee.1 | 2021-05-02 15:42:19.376 | error | (22752) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
zigbee.1 | 2021-05-02 15:42:19.374 | error | (22752) Failed to start Zigbee
zigbee.1 | 2021-05-02 15:42:14.121 | info | (22752) Installed Version: iobroker.zigbee@1.4.4
zigbee.1 | 2021-05-02 15:42:14.064 | info | (22752) Starting Zigbee npm ...
zigbee.1 | 2021-05-02 15:42:14.062 | info | (22752) Try to reconnect. 1 attempts left
javascript.0 | 2021-05-02 15:42:04.076 | info | (22183) script.js.Eigene_Skripte.##on_log_-_Überwachung_und_telegram: ERROR an telegram gesendet
javascript.0 | 2021-05-02 15:42:04.069 | info | (22183) script.js.Eigene_Skripte.##on_log_-_Überwachung_und_telegram: ERROR an telegram gesendet
zigbee.1 | 2021-05-02 15:42:04.060 | error | at rejected (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
zigbee.1 | 2021-05-02 15:42:04.060 | error | at Generator.throw (<anonymous>)
zigbee.1 | 2021-05-02 15:42:04.060 | error | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
zigbee.1 | 2021-05-02 15:42:04.060 | error | (22752) Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
zigbee.1 | 2021-05-02 15:42:04.056 | error | (22752) Failed to start Zigbee

`

Bitte um Hilfe. Danke!

**Comment by asgothian** [comment]
Stell bitte sicher das die 2. Instanz nicht die gleiche Konfiguration wie die 1. Instanz nutzt. Du kannst mit einem Koordinator nur eine Instanz betreiben. Eine 2. Instanz benötigt auch einen zweiten Koordinator.

A.

**Comment by Lassebroker** [comment]
Achso, sorry, da hätte ich wohl ein paar zusätzliche Infos geben sollen:

zigbee.0 hat einen CC2538, darüber läuft alles mit der Ausnahme des SML002
zigbee.1 hat einen CC2531, darüber läuft nur ein SML002 (9290019758) - der hat sonst immer Zicken gemacht

Konfiguration ist verschieden und lief bis zum Update ca. 7 Monate stabil. Erst seit dem Update gestern kommen bei zigbee.1 die Fehlermeldungen. 

Beim Öffnen der Konfig von zigbee.1 kommt übrigens "You need save and run adapter before pairing!" und dann nach einer Änderung (mit Speichern und Schließen):

`
zigbee.1 | 2021-05-02 17:02:35.215 | error | (24948) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port' at Znp.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-he
-- | -- | -- | --
zigbee.1 | 2021-05-02 17:02:35.214 | error | (24948) Failed to start Zigbee

`

**Comment by Lassebroker** [comment]
Dachte mir gerade, dass ich zigbee.1 ja auch löschen und nochmal neu anlegen könnte.  Dafür hab ich zigbee.2 angelegt und es kommt direkt ein Fehler:

`

zigbee.2 | 2021-05-02 17:09:42.945 | error | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
-- | -- | -- | --
zigbee.2 | 2021-05-02 17:09:42.945 | error | at SerialPort._error (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee.2 | 2021-05-02 17:09:42.945 | error | at SerialPort.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
zigbee.2 | 2021-05-02 17:09:42.945 | error | at __awaiter (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
zigbee.2 | 2021-05-02 17:09:42.945 | error | at new Promise (<anonymous>)
zigbee.2 | 2021-05-02 17:09:42.945 | error | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
zigbee.2 | 2021-05-02 17:09:42.945 | error | at Generator.next (<anonymous>)
zigbee.2 | 2021-05-02 17:09:42.945 | error | at Znp.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
zigbee.2 | 2021-05-02 17:09:42.945 | error | (25198) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'

`

**Comment by asgothian** [comment]
Diese Meldung:
Error: Error Resource temporarily unavailable Cannot lock port
Besagt das die serielle Schnittstelle die du öffnen möchtest nicht verfügbar ist. Bitte verifizieren:
- Beide Sticks erzeugen jeweils ein eigenes Device und dieses ist auch nutzbar.
- Lassen sich die Instanzen getrennt voneinander starten (beide / alle Anhalten, sicherstellen das keine mehr läuft, eine Instanz starten)

A.

**Comment by Lassebroker** [comment]
Danke schonmal, komme aber noch nicht weiter:

1. Wie kann ich herausfinden, ob das Device nutzbar ist?
    Mit  ls -la /dev/serial/by-id/
    kommt:
`lrwxrwxrwx 1 root root 13 Dez  9 10:52 usb-Texas_Instruments_CC2538_USB_CDC-if00 -> ../../ttyACM0     
lrwxrwxrwx 1 root root 13 Dez  9 10:52 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E2ECE5-if00 -> ../../ttyACM1
`


2. Nein, auch wenn ich beide anhalte kann ich zigbee.1 nicht starten:

`

zigbee.1 | 2021-05-02 18:43:31.635 | error | (25175) Cannot read property 'getEntries' of null
-- | -- | -- | --
zigbee.1 | 2021-05-02 18:43:31.634 | error | at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8620:22)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at Zigbee.emit (events.js:314:20)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:581:41)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:310:20)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:192:42)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:222:43)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:206:49)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at Controller.getDevices (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:289:31)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at Function.all (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:241:16)
zigbee.1 | 2021-05-02 18:43:31.634 | error | at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:221:55)
zigbee.1 | 2021-05-02 18:43:31.634 | error | (25175) TypeError: Cannot read property 'getEntries' of null
zigbee.1 | 2021-05-02 18:43:31.621 | error | (25175) unhandled promise rejection: Cannot read property 'getEntries' of null
zigbee.1 | 2021-05-02 18:43:31.621 | error | (25175) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

`

**Comment by asgothian** [comment]
die verlinkten Nachrichten sind Folgefehler. Bitte das komplette Log posten vom start der Instanz bis zum Ende.

**Comment by Lassebroker** [comment]
`

zigbee.1 | 2021-05-02 20:07:48.895 | error | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
-- | -- | -- | --
zigbee.1 | 2021-05-02 20:07:48.895 | error | at SerialPort._error (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee.1 | 2021-05-02 20:07:48.895 | error | at SerialPort.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
zigbee.1 | 2021-05-02 20:07:48.895 | error | at __awaiter (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
zigbee.1 | 2021-05-02 20:07:48.895 | error | at new Promise (<anonymous>)
zigbee.1 | 2021-05-02 20:07:48.895 | error | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
zigbee.1 | 2021-05-02 20:07:48.895 | error | at Generator.next (<anonymous>)
zigbee.1 | 2021-05-02 20:07:48.895 | error | at Znp.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
zigbee.1 | 2021-05-02 20:07:48.895 | error | (24713) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
zigbee.1 | 2021-05-02 20:07:48.893 | error | (24713) Failed to start Zigbee
zigbee.1 | 2021-05-02 20:07:43.685 | info | (24713) Installed Version: iobroker.zigbee@1.4.4
zigbee.1 | 2021-05-02 20:07:43.663 | info | (24713) Starting Zigbee npm ...
zigbee.1 | 2021-05-02 20:07:43.662 | info | (24713) Try to reconnect. 1 attempts left
zigbee.1 | 2021-05-02 20:07:33.660 | error | at rejected (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
zigbee.1 | 2021-05-02 20:07:33.660 | error | at Generator.throw (<anonymous>)
zigbee.1 | 2021-05-02 20:07:33.660 | error | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
zigbee.1 | 2021-05-02 20:07:33.660 | error | (24713) Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
zigbee.1 | 2021-05-02 20:07:33.658 | error | (24713) Failed to start Zigbee
zigbee.1 | 2021-05-02 20:06:54.058 | info | (24713) Installed Version: iobroker.zigbee@1.4.4
zigbee.1 | 2021-05-02 20:06:53.315 | info | (24713) Starting Zigbee npm ...
zigbee.1 | 2021-05-02 20:06:53.192 | info | (24713) starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.2.16
host.raspberrypi | 2021-05-02 20:06:50.093 | info | instance system.adapter.zigbee.1 started with pid 24713
host.raspberrypi | 2021-05-02 20:06:50.052 | info | "system.adapter.zigbee.1" enable

`

**Comment by asgothian** [comment]
Du hast ein Problem mit der cc2531 Hardware. Bitte den Stick entfernen, 30 sekunden warten, Stick einstecken, neu versuchen. Wenn das nicht geht solltest du schauen ob die Firmware noch ok ist, bzw. den Stick mit einer USB Verlängerung nutzen.

A.

**Comment by Lassebroker** [comment]
Mmh, alles versucht. Nicht ändert sich. Im Log ergibt sich auch, dass die Fehler erst genau nach dem Update aufgetreten sind.

Habe nun ein backup eingespielt - nun gehen beide Instanzen wieder. Komisch.

Leider gibt es nun ein paar Verbindungsprobleme. Der SML002 wird zwar unter "Netzwerkkarte" gezeigt (in rot) unter "Geräte" ist er aber nicht - obwohl ich ihn gerade neben den Stick gelegt habe. Soll ich den neu pairen?

**Comment by asgothian** [comment]
> Mmh, alles versucht. Nicht ändert sich. Im Log ergibt sich auch, dass die Fehler erst genau nach dem Update aufgetreten sind.
> 
> Habe nun ein backup eingespielt - nun gehen beide Instanzen wieder. Komisch.
> 
> Leider gibt es nun ein paar Verbindungsprobleme. Der SML002 wird zwar unter "Netzwerkkarte" gezeigt (in rot) unter "Geräte" ist er aber nicht - obwohl ich ihn gerade neben den Stick gelegt habe. Soll ich den neu pairen?

Nein - die Netzwerkkarte ist nur eine Momentaufnahme.

**Comment by Lassebroker** [comment]
> Nein - die Netzwerkkarte ist nur eine Momentaufnahme.

Hab ich gestern Abend nun doch gemacht. Seitdem geht (fast) alles. Versteh nicht, warum, aber trotz des alten Backups ist die Node version geblieben (Node.js: v12.22.1) und es bleibt nur bei laufenden Warnmeldungen

`
zigbee.1 | 2021-05-04 10:38:30.784 | warn | (7562) Device '0x001788010647b6f7' announced itself
-- | -- | -- | --
zigbee.1 | 2021-05-04 10:38:30.579 | warn | (7562) Device '0x001788010647b6f7' announced itself
zigbee.1 | 2021-05-04 10:27:46.822 | warn | (7562) Device '0x001788010647b6f7' announced itself
zigbee.1 | 2021-05-04 10:27:36.822 | warn | (7562) Device '0x001788010647b6f7' announced itself

`

Also, ich check es nicht, aber das Ursprungsproblem hat sich jetzt hoffentlich gelöst.

**Comment by Lassebroker** [comment]
@asgothian 
Lief nun bis heute stabil. Hab das Update von 1.4.4 auf 1.5.5 versucht. Danach hat er wieder o. g. Fehler zum serialport ausgespuckt. 

Geholfen hat dann wieder CC2531 Stick entfernen **_und_** backup einspielen. 

Irgendetwas hängt da schief. Kann ich den zigbee-Adapter irgendwie komplett löschen und sauber neu wieder aufsetzen?

Oder gibt es noch eine andere Möglichkeit?

**Comment by asgothian** [comment]
Der normale weg wäre:
- shepherd.db und nvbackup.json sichern
- zigbee adapter löschen
- zigbee adapter in neuer Version installieren
- shepherd.db und nvbackup.json wiederherstellen, sofern sie gelöscht wurden
- zigbee adapter starten.

Was du vorher probieren kannst ist:
- Zigbee Adapter anhalten
- 30 Sekunden warten
- Update des Zigbee Adapter anstossen
- neuen Zigbee Adapter starten.

A.
