### ISSUE TITLE
js-controller Update lässt alle Geräte verschwinden

### ISSUE THREAD

**Issue by Frank1604** [ioBroker/ioBroker.zigbee#1086]
Ich habe keine Ahnung wie das zusammen hängt, aber es ist (leider) reproduzierbar bei mir so, dass alle angelernten Zigbee Geräte verschwunden sind, wenn ich den Host-controller (js-controller) aktualisiere.

Ich habe innerhalb einer Woche 3mal alle Geräte neu anlernen müssen, das ist bei 62 Geräten die teilweise in Unterputzdosen und hinter Schaltern in der Wand stecken kein Spaß.

Das erste mal aufgetreten ist das als ich auf Version 3.3.1 altualisiert habe. Die Updates auf 3.3.4 und 3.3.5 haben das Gleiche ausgelöst. Sobald ich den Host-controller update und ioBroker starte meldet mir der ZigBee Stick das zur Zeit keine Geräte angemeldet sind. Restore bringt auch nichts, die Geräte sind weg. Ich sehe die Objekte im ioBroker, aber der Stick hat sie nicht mehr.

Als das zum ersten Mal vor einer Woche aufgetreten ist, habe ich den CC2531 raus geschmissen und stattdessen den hier schon liegenden CC2652RB verwendet mit neuer PAN-ID natürlich. Die nächsten beiden Updates des js-controllers ließen aber wieder alle Geräte verschwinden.

Alle anderen Updates sind kein Problem, auch Update des Zigbee Adapters macht keine Probleme. Neustart des Systems auch nicht.

Hatte auch schon [hier](https://github.com/ioBroker/ioBroker.js-controller/issues/1329) ein Ticket geöffnet, aber die wollen das da nicht haben. ;)

**Comment by Frank1604** [comment]
Ok, ich habe etwas merkwürdiges gefunden. Meine Konsolensuche nach der shepherd.db brachte 2 Dateien zutage.

/opt/iobroker/iobroker-data/zigbee_0/shepherd.db
/opt/iobroker/node_modules/iobroker.js-controller/undefinedzigbee_0/shepherd.db

Ich denke da wird der Fehler liegen, das soll so sicher nicht sein.
Fehlt da irgendwo eine Variable zum Datenverzeichnis?

**Comment by Apollon77** [comment]
Ok, das würde erklären warum das File wegfliegt weil npm bei einem Paket install "aufräumt"

**Comment by Frank1604** [comment]
Ja, das denke ich auch. Die Frage ist nur, wie lässt sich das beheben?
Ich denke wenn ich mir die DB sichere brauche ich die Geräte nicht neu anlernen, aber trotzdem muss das ja irgendwie bereinigt werden.
Ich hatte den Adapter auch schon komplett deinstalliert und neu installiert, das scheint aber auch nichts gebracht zu haben.

**Comment by Apollon77** [comment]
Wir sind gerade auch auf js-controller Ebene dabei das zu prüfen bzw adapter-core. Es gab jetzt einen weiteren Fall ...

**Comment by Frank1604** [comment]
Ok, vielen Dank schonmal für eure Arbeit. Wenn ich etwas tun oder Daten liefern kann, sagt Bescheid.

**Comment by asgothian** [comment]
Für eine Lösung siehe hier: 
https://forum.iobroker.net/topic/44200/zigbee-neue-version-1-5-x/217?_=1621934151160

**Comment by Frank1604** [comment]
Wenn ich das richtig verstehe wird die fehlende Variable wieder hergestellt beim Update auf 3.3.11 und der Zigbee Adapter sucht seine db wieder im korrekten Verzeichnis. 
Wenn ich nun hergehe und vor dem Update die db aus dem falschen Verzeichnis ins eigentlich richtige kopiere, müsste ich um das Anlernen der Geräte drum herum kommen. Macht das Sinn, könnte das klappen?

**Comment by Apollon77** [comment]
Ja sollte so klappt. am besten iobroker stoppen (mindestens mal zigbee Adapter)

**Comment by Frank1604** [comment]
Es hat funktioniert, vielen Dank! 👍
