### ISSUE TITLE
Host updates breaks zigbee adapter

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1087]
Hi .. I experienced this several times .. after host update zigbee doesn't turn green anymore.

See here: https://github.com/ioBroker/ioBroker.js-controller/issues/1300#issuecomment-831031231

Logfile below that entry:

https://github.com/ioBroker/ioBroker.js-controller/issues/1300#issuecomment-831033214

**Comment by asgothian** [comment]
Just host update or also nodejs update ?

**Comment by daniel-lo** [comment]
Just host .. I have been on v12.22.1 a bit longer

**Comment by daniel-lo** [comment]
Another try after yesterdays update (failed):
[iobroker.2021-05-05.zip](https://github.com/ioBroker/ioBroker.zigbee/files/6425146/iobroker.2021-05-05.zip)

**Comment by kirovilya** [comment]
Please record zigbee adapter log with **debug** mode. we needed more info

**Comment by daniel-lo** [comment]
interesting that only I seem to be effected .. will do but will take some time .. not so much fun having to restore a backup every day (as I just did) .. ;-)

**Comment by kirovilya** [comment]
yes you are the only one :)

**Comment by daniel-lo** [comment]
I hate it :-(

**Comment by kirovilya** [comment]
You can also share your database of devices  iobroker-data/zigbee_0/shepherd.db

**Comment by daniel-lo** [comment]
[iobroker.2021-05-05.zip](https://github.com/ioBroker/ioBroker.zigbee/files/6425286/iobroker.2021-05-05.zip)
[shepherd.zip](https://github.com/ioBroker/ioBroker.zigbee/files/6425293/shepherd.zip)
[backup_2021_05_05-08_09_35.tar.gz](https://github.com/ioBroker/ioBroker.zigbee/files/6425297/backup_2021_05_05-08_09_35.tar.gz)

**Comment by daniel-lo** [comment]
hope this helps .. restoring backup ;-)

**Comment by kirovilya** [comment]
try to stop js-script _Bewegungsmelder_Rückfallwert_ before start zigbee-adapter

**Comment by daniel-lo** [comment]
So I should update host wait for zigbee red .. stop zigbee .. do in terminal
stop js-script Bewegungsmelder_Rückfallwert before start zigbee-adapter
then restart zigbee?

**Comment by kirovilya** [comment]
yes. it seems to me that your script crashes the adapter

**Comment by daniel-lo** [comment]
hmm .. but it works before the update .. at least the zigbee dot is green

**Comment by kirovilya** [comment]
if you disable the script, does the zigbee adapter work?

**Comment by daniel-lo** [comment]
don't know yet .. will have to update hosts again .. will get back to you asap

**Comment by daniel-lo** [comment]
Yes .. it's green when that script is paused.
Is there anything you can/will do on your side? Or how can I fix this?

**Comment by kirovilya** [comment]
There are two ways out: 1) fix the script so that it does not torment the zigbee until it starts.
2) fix the zigbee adapter so that it does not receive messages until it starts.
faster to do 1) :)
over 2) needs to be finalized ...

**Comment by Apollon77** [comment]
@daniel-lo beside that I also had a look at the log. maybe better discussed in forum in detail, but:
* what happened 8:03? I see many disconnects from network and also SIGTERM for controlelr. Did yoiu stopped it? Network issue? Looks like a more or less "hard "stop

@kirovilya Maybe zigbee is simply doinfg the "subscribe" too early? Ideally just subscribe in adapter AFTER all initialization is done. so you make sure that no stateChanges come in before anything is initialized

**Comment by daniel-lo** [comment]
@Apollon77 
At 8:03 I did the host update .. so I started the procedure in the instructions

@kirovilya
Just poking in the dark .. but I use German diacritics in the script name .. and I have "()" in object names. Wouldn't know why it worked formerly though.

**Comment by kirovilya** [comment]
@Apollon77 this is one of the solutions.
think it's better to prevent processing state changes if there is no zigbee connection.

**Comment by daniel-lo** [comment]
Please let me know when I can reactivate the script :-)

**Comment by kirovilya** [comment]
@daniel-lo you can try to reactivate script after zigbee starts :)

**Comment by kirovilya** [comment]
@daniel-lo Then you can try the version from github

**Comment by daniel-lo** [comment]
tried adapter restart and iobroker restart .. works :-)

Thank you!
