### ISSUE TITLE
Version 1.5.4

### ISSUE THREAD

**Issue by skvarel** [ioBroker/ioBroker.zigbee#1088]
Nach einem Update hat sich die Kanalnummer eigenständig geändert. Alle Geräte waren weg. Beim erneuten Pairing stürzt die Instanz sofort ab.

Zigbee: 1.5.4
Admin 5.0.13
js-controller 3.3.7

Der ioBroker meldet folgenden Fehler:
![grafik](https://user-images.githubusercontent.com/1114419/116888749-1d987000-ac2c-11eb-9a37-01f1ee5020fc.png)

**Comment by asgothian** [comment]
Gibt es logs vom Absturz / Neustart ?

**Comment by skvarel** [comment]
Im Moment gibt es keine Abstürze.

Ich vermute, es lag an den fehlenden Verbindungen. Unter 'Objekte' waren noch alle Datenpunkte vorhanden, in der Geräteliste (Zigbee Instanz) war alledings alles leer.

Eine Frage bleibt, kann sich eine Kanalnummer eigenständig ändern? Kann es am Adapter-Updtae gelegen haben oder eventuell am js-Controller-Update?

**Comment by asgothian** [comment]
das Update des Adapters sollte die Einstellungen nicht verändern können. 

Closed due to 1.5.5
