### ISSUE TITLE
Failed to DeviceConfigure.onZigbeeEvent (Error: 'ZNLDP12LM' has no configure at Object.getConfigureKey

### ISSUE THREAD

**Issue by Shadesh** [ioBroker/ioBroker.zigbee#1091]
After installing the latest Github Version from today, the log shows a error with all ZNLDP12LM devices:

zigbee.0 | 2021-05-07 12:59:04.505 | error | at ZigbeeController.handleMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:568:14))
-- | -- | -- | --
zigbee.0 | 2021-05-07 12:59:04.505 | error | at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:196:42)
zigbee.0 | 2021-05-07 12:59:04.505 | error | at DeviceConfigure.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:76:22)
zigbee.0 | 2021-05-07 12:59:04.505 | error | at DeviceConfigure.shouldConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:33:38)
zigbee.0 | 2021-05-07 12:59:04.505 | error | at Object.getConfigureKey (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/configureKey.js:20:15)
zigbee.0 | 2021-05-07 12:59:04.505 | error | (13079) Failed to DeviceConfigure.onZigbeeEvent (Error: 'ZNLDP12LM' has no configure
zigbee.0 | 2021-05-07 12:58:09.767 | error | at ZigbeeController.handleMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:568:14))
zigbee.0 | 2021-05-07 12:58:09.767 | error | at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:196:42)
zigbee.0 | 2021-05-07 12:58:09.767 | error | at DeviceConfigure.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:76:22)
zigbee.0 | 2021-05-07 12:58:09.767 | error | at DeviceConfigure.shouldConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:33:38)
zigbee.0 | 2021-05-07 12:58:09.767 | error | at Object.getConfigureKey (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/configureKey.js:20:15)
zigbee.0 | 2021-05-07 12:58:09.767 | error | (13079) Failed to DeviceConfigure.onZigbeeEvent (Error: 'ZNLDP12LM' has no configure
zigbee.0 | 2021-05-07 12:58:09.563 | error | at ZigbeeController.handleMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:568:14))
zigbee.0 | 2021-05-07 12:58:09.563 | error | at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:196:42)
zigbee.0 | 2021-05-07 12:58:09.563 | error | at DeviceConfigure.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:76:22)
zigbee.0 | 2021-05-07 12:58:09.563 | error | at DeviceConfigure.shouldConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:33:38)
zigbee.0 | 2021-05-07 12:58:09.563 | error | at Object.getConfigureKey (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/configureKey.js:20:15)
zigbee.0 | 2021-05-07 12:58:09.563 | error | (13079) Failed to DeviceConfigure.onZigbeeEvent (Error: 'ZNLDP12LM' has no configure
zigbee.0 | 2021-05-07 12:58:08.525 | error | at ZigbeeController.handleMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:568:14))
zigbee.0 | 2021-05-07 12:58:08.525 | error | at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:196:42)
zigbee.0 | 2021-05-07 12:58:08.525 | error | at DeviceConfigure.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:76:22)
zigbee.0 | 2021-05-07 12:58:08.525 | error | at DeviceConfigure.shouldConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:33:38)
zigbee.0 | 2021-05-07 12:58:08.525 | error | at Object.getConfigureKey (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/configureKey.js:20:15)
zigbee.0 | 2021-05-07 12:58:08.525 | error | (13079) Failed to DeviceConfigure.onZigbeeEvent (Error: 'ZNLDP12LM' has no configure

**Comment by Shadesh** [comment]
New Error with todays fix:

```
2021-05-14 16:17:22.857  - error: zigbee.0 (1443) TypeError: Cannot read property 'error' of undefined
    at ZnpAdapterManager.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/manager.js:193:41)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/manager.js:24:58)
2021-05-14 16:17:32.859  - info: zigbee.0 (1443) Try to reconnect. 1 attempts left
2021-05-14 16:17:32.861  - info: zigbee.0 (1443) Starting Zigbee  npm ...
2021-05-14 16:17:32.891  - info: zigbee.0 (1443) Installed Version: ioBroker/ioBroker.zigbee#master
2021-05-14 16:17:33.159  - error: zigbee.0 (1443) Failed to start Zigbee
2021-05-14 16:17:33.160  - error: zigbee.0 (1443) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at Znp.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
```

Had to rollback to 1.5.3 to get it back to life.

**Comment by Apollon77** [comment]
> Error Resource temporarily unavailable Cannot lock port

normally means that the serialport is blocked by an other process

**Comment by Shadesh** [comment]
True but even a reboot didn't help. As soon as I reverted to 1.5.3 it started up again without a problem.
