### ISSUE TITLE
Seit Jahren Osram Motion Sensor  no battery indicator

### ISSUE THREAD

**Issue by elzershark** [ioBroker/ioBroker.zigbee#1092]
https://www.zigbee2mqtt.io/devices/AC01353010G.html

Osram Motion Sensor
no battery indicator

Batterie Anzeige fehlt immer noch. 
Das seit Jahren.

Oder erscheint der Datenpunkt, wenn Batterie low ist?
Ich finde da nichts drüber.
Falls er doch auftaucht, wie heisst dieser Datenpunkt?
Wo kann man das sehen im Script?

lg,

**Comment by asgothian** [comment]
Bitte trag den Motion Sensor im "Ausschliessen" Tab ein um zu sehen ob ein entsprechender Datenpunkt erzeugt wird. Wenn ja, sollte das Gerät über die vom Herdsman bereitgestellten States betrieben werden.

A.

**Comment by elzershark** [comment]
oh, dachte hab das geschlossen. Der Datenpunkt ist nicht abrufbahr. Derkommt wenn es soweit ist. Also wenn Batterie leer ist..
