### ISSUE TITLE
restart loop detected

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1095]
adapter is green but I get this warning:

![grafik](https://user-images.githubusercontent.com/4311558/117532869-f3f39600-afe9-11eb-8ad3-766d2f7b7881.png)

**Comment by Apollon77** [comment]
Chwck the timestam in the message (down right corner). It was happening at that timepoint!

Check your logs for the reasons whx the adapter was ended unexpectly

**Comment by daniel-lo** [comment]
Good point .. it sais: 2021-04-28 20:17:56.370
How do I remove this error since happend long time ago.

**Comment by Apollon77** [comment]
"Bestätigen" löscht die Meldung

**Comment by daniel-lo** [comment]
*facepalm*

**Comment by daniel-lo** [comment]
Lustig .. hatte vorhin bestätigt .. ist jetzt aber wieder da die Meldung .. mit den alten Zeitstempeln.

**Comment by Apollon77** [comment]
Dann bitte Admin Issue anlegen

**Comment by daniel-lo** [comment]
OK .. heute morgen waren sie nicht wieder zu sehen .. wenn sie das nächste Mal auftauchen gibt's dort ein Ticket.
