### ISSUE TITLE
Paired Device Wrong Identification

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.zigbee#1096]
![Screenshot 2021-05-11 07 43 53](https://user-images.githubusercontent.com/59663011/117771787-bfc0e500-b236-11eb-9425-35382ed1b2bb.png)

Das Gerät heist eigentlich NAS-TH01
So sieht die Kachel aus. Es werden keine Werte außer Link quality und Battery Percent übertragen. Illumination wird nicht angelegt als Datenpunkt aber per manuelle Abfrage kommt ein Phantasiewert heraus. Battery Voltage wird nicht abgefragt nur auf manuelle Abfrage hin wird der Wert übermittelt. Bei Abfrage von Temp und Feuchtigkeit zeigt er einen Fehler 134.

**Comment by asgothian** [comment]
Verrat doch mal mehr über das device ? Was soll es liefern ? Wie sieht es aus ?

**Comment by Dragon0501** [comment]
Es handelt sich um [dieses Gerät](https://de.aliexpress.com/item/1005002434939226.html?spm=a2g0o.productlist.0.0.277e297bya6RAJ&algo_pvid=null&algo_expid=null&btsid=0b0a050b16207981701861925ee95f&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)

Es soll Helligkeit, Temperatur und Feuchtigkeit liefern. Das sagt zumindest die Anleitung. 
Ich denke weiter sollten die Datenpunkte für die Batterie, die Link Quality, den Verbindungsstatus und die jeweiligen Korrekturwerte im Nachgang existieren.

**Comment by Dragon0501** [comment]
Brauchst du Bilder von der BDA oder dem gerät selbst oder iwas anderes?

**Comment by arteck** [comment]
pack das Device bitte in unter den Ausschliessen Tab rein..

**Comment by Dragon0501** [comment]
Ein kurzes how-to bitte. Wie bekomme ich ein device unter den ausschließen Tab? Und was passiert dann?

**Comment by Dragon0501** [comment]
Gelöst, nach einem Update des Adapters konnte ich es nun hinzufügen. 

Habe aber auch zwei Geräte die tatsächlich ein TS0201 sind. Funktionieren die dann auch nicht mehr?

**Comment by Dragon0501** [comment]
Also habe es zu Ausschließen hinzugefügt. An dem nicht funktionieren vom Device hat sich nichts geändert lediglich eines der anderen beiden Devices überträgt jetzt anstatt 3V eine Spannung von 3000V. 
Leider eine Verschlimmbesserung... Habe ich etwas falsch gemacht?

**Comment by asgothian** [comment]
- Nimm die Geräte wieder aus der Ausschlussliste heraus.
- Lass den Adapter die "falschen" states aufräumen 
<img width="98" alt="Screen Shot 2021-05-25 at 11 11 36 " src="https://user-images.githubusercontent.com/45667167/119471854-f96f1100-bd49-11eb-9e47-0d29416cb489.png">
- Sieh nach ob exakt dieses Gerät bei Zigbee2mqtt.io in der Liste der unterstützten Geräte auftaucht. 

Taucht es auf kann ein Update des Zigbee Adapters auf die aktuelle Version Abhilfe schaffen. Tut es das nicht ist das ein Problem das im Zigbee-Herdsman-Converters adressiert werden muss.

Ohne das Gerät physikalisch zu haben ist eine Integration bei diesem Gerät fast ausgeschlossen.

A.

**Comment by Dragon0501** [comment]
Wenn es dich oder den Adapter weiterbringt kann ich dir das Device gern leihweise zur Verfügung stellen. Ist leider nicht unter den kompatiblen Geräten aufgeführt....

**Comment by asgothian** [comment]
Ich fürchte ich habe aktuell zu wenig Zeit mich in die Details eines neuen TuYa Gerätes einzuarbeiten. Das ist eine deutlich zu grosse Wundertüte, da TuYa nicht die üblichen Zigbee Cluster zur Kommunikation nutzt sondern die meisten Daten im Cluster 57346 (Manufacturerspecific TuYa) übermittelt.

A.

**Comment by Dragon0501** [comment]
Ok, trotzdem vielen Dank. Mich sprach einfach nur das Design dieses Sensors mehr an als der Runde... Aber kein Problem, nutze ich eben die runden. Trotzdem ein schönes Wochenende.

LG
    D
