### ISSUE TITLE
Error loading settings

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1098]
I assume this has something to do with the new admin:

![grafik](https://user-images.githubusercontent.com/4311558/118265488-8c41bd00-b4b9-11eb-8275-75b656ab7980.png)

**Comment by di3t0** [comment]
I have the same problem after updating to the new admin

**Comment by daniel-lo** [comment]
Seems to be fixed in Admin v5.0.26

**Comment by asgothian** [comment]
Duplicate of #1100
