### ISSUE TITLE
Serialport Error after Hosts JS-Controller update

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1099]
Updated Host to 3.3.10 .. incl. iobroker-fix and reboot:

**Comment by daniel-lo** [comment]
<html><body>


host.iobroker | 2021-05-14 17:44:21.506 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
zigbee.0 | 2021-05-14 17:44:20.426 | error | Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
zigbee.0 | 2021-05-14 17:44:20.426 | error | Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'     at Driver.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:160:28)     at Generator.next (<anonymous>)     at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71     at new Promise (<anonymous>)     at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)     at SerialPort.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:158:45)     at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)     at /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
zigbee.0 | 2021-05-14 17:44:20.426 | error | unhandled promise rejection: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
zigbee.0 | 2021-05-14 17:44:20.425 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
zigbee.0 | 2021-05-14 17:44:10.411 | error | TIMEOUT
zigbee.0 | 2021-05-14 17:44:10.410 | error | Failed to start Zigbee
zigbee.0 | 2021-05-14 17:43:30.732 | error | Error: Error while opening serialport 'Error: Error: No such device, cannot open /dev/ttyACM0'     at Driver.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:160:28)     at Generator.next (<anonymous>)     at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71     at new Promise (<anonymous>)     at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)     at SerialPort.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:158:45)     at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)     at /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
zigbee.0 | 2021-05-14 17:43:30.728 | error | Failed to start Zigbee


</body>
</html>

**Comment by daniel-lo** [comment]
Turned green after a while.

**Comment by Apollon77** [comment]
"device not existing" anc "can not lock port" means it was "not there" and/or "blocked by another process

**Comment by daniel-lo** [comment]
Maybe just a timing thing .. since it healed itself (I think  .. because lamp turned green .. Interface not working atm).

**Comment by arteck** [comment]
Error while opening serialport .. not adapter issue...
