### ISSUE TITLE
Switching Osram Smart Plug / Xiaomi Lumi Plug works in 0.7.6 but not in 0.7.7

### ISSUE THREAD

**Issue by snador1977** [ioBroker/ioBroker.zigbee#110]
Switching Osram Smart Plug / Xiaomi Lumi Plug works in 0.7.6 but not in 0.7.7. When switching to the plugs (hardware buttons), the states are transmitted correctly, but switching in the admin / scripts does not work. The plugs are functionless. In 0.7.6 this is still possible ...

**Comment by arteck** [comment]
can you check the 0.8.0b version or my Repo plz

**Comment by snador1977** [comment]
Will I check in the next 1-2 days

**Comment by snador1977** [comment]
0.8.0b works - all is fine!
