### ISSUE TITLE
can't connect to cc26x2r

### ISSUE THREAD

**Issue by Toysman** [ioBroker/ioBroker.zigbee#1101]
Hello,

after new installing ioBroker only Zigbee 1.4.4 is installed, but I can't connect to the cc26x2r Board. Will get the errorbox
"Einige Daten wurden nicht gespeichert. Verwerfen?"  The INSTANZ stay on yellow - don't go on GREEN

Node.js        12.22.1
NPM             6.14.12
js-controller  3.2.16
admin            4.2.1

COM Port   usb-Texas_Instruments_XDS110__03.00.00.13__Embed_with_CMSIS-DAP_L1100NN8-if00

zigbee.0 | 2021-05-15 14:40:15.777 | info | (1647) Installed Version: iobroker.zigbee@1.4.4
-- | -- | -- | --
zigbee.0 | 2021-05-15 14:40:15.771 | error | at /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
zigbee.0 | 2021-05-15 14:40:15.771 | error | at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee.0 | 2021-05-15 14:40:15.771 | error | at SerialPort.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
zigbee.0 | 2021-05-15 14:40:15.771 | error | at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
zigbee.0 | 2021-05-15 14:40:15.771 | error | at new Promise (<anonymous>)
zigbee.0 | 2021-05-15 14:40:15.771 | error | at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
zigbee.0 | 2021-05-15 14:40:15.771 | error | at Generator.next (<anonymous>)
zigbee.0 | 2021-05-15 14:40:15.771 | error | at Znp.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
zigbee.0 | 2021-05-15 14:40:15.771 | error | (1647) Error: Error while opening serialport 'Error: Error: No such  file or directory, cannot open  usb-Texas_Instruments_XDS110__03.00.00.13__Embed_with_CMSIS-DAP_L1100NN8-if00'
zigbee.0 | 2021-05-15 14:40:15.769 | error | (1647) Failed to start Zigbee

need some help plz

**Comment by arteck** [comment]
Error: No such file or directory  not adapter issue
