### ISSUE TITLE
Can't install Zigbee Adapter after Upgrade JS-Controller to 3.3.10 -  Uncaught Rejection: TypeError: Cannot read property 'common' of undefined

### ISSUE THREAD

**Issue by FoRealx** [ioBroker/ioBroker.zigbee#1102]
Here the output from the logfile.

Maybe someone can help. Thanks!

$ ./iobroker add zigbee  --host iobroker
host.iobroker install adapter zigbee
ERROR: host.iobroker error: reading io-package.json SyntaxError: /opt/iobroker/node_modules/iobroker.zigbee/io-package.json: Unexpected token } in JSON at position 167
ERROR: Uncaught Rejection: TypeError: Cannot read property 'common' of undefined    at Install.installAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:745:25)    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:859:29)    at processImmediate (internal/timers.js:463:21)
ERROR: process exited with code 27

**Comment by kirovilya** [comment]
it may be a bug of version 1.5.0, which has already been fixed. open the file /opt/iobroker/node_modules/iobroker.zigbee/io-package.json and correct it like here https://github.com/ioBroker/ioBroker.zigbee/commit/a5042cfd2c35886b8ce75db9ae2dc9000b4687deff2bb5bb9ae2dc9000b6757deff2ef2ef2ff2dc9000b4687deff2ff2ff2fdb9e2dc9000b4687deff2ff2ff2fdb9e2dc9000b4687eff2efa

**Comment by FoRealx** [comment]
Seems to work!

Thank you for the quick help! :)
