### ISSUE TITLE
TuYa TS011F_wall_outlet 

### ISSUE THREAD

**Issue by Ricox1975** [ioBroker/ioBroker.zigbee#1103]
TuYa TS011F_wall_outlet verlieren immer mal wieder die aktive Verbindung. Die Linkqualität steht bei null. Nach manueller Auslösung des Datenpunktes trigger device query werden die Geräte wieder schaltbar.
![TeekarPlug](https://user-images.githubusercontent.com/52467622/118626657-5b200000-b7cb-11eb-8cbb-37fad2d78700.JPG)

**Comment by asgothian** [comment]
Please test: Will the device switch if you just try to change the on/off State of the switch, rather than using the device query ? Also please verify if there are log entries about not being able to ping the devices.

A.

**Comment by Ricox1975** [comment]
Die Geräte lassen sich dann nicht schalten. Im Log erscheinen die Plugs auch nicht. Ich habe 1.5.5 installiert.

**Comment by Ricox1975** [comment]
Nach Downgrade auf 1.4.4 sind die Verbindungsabbrüche verschwunden.
