### ISSUE TITLE
TS601 Smart Airtracker Tuya Probleme

### ISSUE THREAD

**Issue by 4358haltern** [ioBroker/ioBroker.zigbee#1107]
Hallo

Folgendes Adapter Version: 1.5.5.
Folgendes Problem:

Ich bekomme den Tuya AirTracker nicht 100%ig ins Zigbee netzwerk eingebunden.
Ich habe den Tracker einige mal versucht einzubinden doch ohne sichtlichen erfolg....
kann leider kein vergleichbares problem finden...
deswegen hoffe ich auf lösungs findung.
Es Handelt sich um:

![grafik](https://user-images.githubusercontent.com/84634956/119233357-e5989480-bb28-11eb-93a9-d7fc2b299e4b.png)
![grafik](https://user-images.githubusercontent.com/84634956/119233366-f34e1a00-bb28-11eb-98f3-90e42bf4fa3b.png)

**Comment by VBen** [comment]
Siehe #1108 , der PR sollte das Problem lösen

**Comment by 4358haltern** [comment]
wohin mit den daten???

**Comment by VBen** [comment]
> wohin mit den daten???

ich weiß leider nicht was du meinst

**Comment by 4358haltern** [comment]
ich weiss nicht wie das mit dem converter machen soll..:(

**Comment by VBen** [comment]
Ich denke dann ist abwarten die einfachste Lösung, es wird halt etwas dauern bis der Change public ist und als Adapter Update zur Verfügung steht

**Comment by asgothian** [comment]
Die aktuelle GitHub Version des Adapters sollte dieses Gerät inzwischen unterstützen.

A.

**Comment by 4358haltern** [comment]
Ja das habe ich gesehen aber ein händischer Abgleich oder andere via npm (Eingabe ssh) hat nichts gebracht

**Comment by VBen** [comment]
@asgothian  Bei mir funktioniert es.
@4358haltern Vielleicht magst du die[Github Anleitung](https://www.iobroker.net/docu/index-23.htm?page_id=8511&lang=de#DieInstallation_von_Github_nur_fuer_Experten) ausprobieren.

**Comment by 4358haltern** [comment]
Hab ich gemacht... werde gleich mal den den Debug online stellen 

Gleich := später

**Comment by 4358haltern** [comment]
> 
> 
> @asgothian Bei mir funktioniert es.
> @4358haltern Vielleicht magst du die[Github Anleitung](https://www.iobroker.net/docu/index-23.htm?page_id=8511&lang=de#DieInstallation_von_Github_nur_fuer_Experten) ausprobieren.

das hat es gebracht! danke dir!
