### ISSUE TITLE
zusätzlicher Datenpunkt unter Zigbee Geräten -> letzte Aktivität

### ISSUE THREAD

**Issue by atifan** [ioBroker/ioBroker.zigbee#1112]
Hi.
Ich würde gerne meine Zigbee-Sensoren über ein Blockly-Script überwachen, wann sie sich das letzte mal gemeldet haben bzw. aktiv waren. Wenn es zu lange her ist (ca. 2 Tage), dann möchte ich ne E-Mail gesendet bekommen.
Was mir fehlt um das so umzusetzen ist ein Datenpunkt, wann die letzte Aktivität her war. 
Diesen Datenpunkt würde ich dann über ein Script überwachen.

Der Zigbee Adapter erfasst das schon irgendwie, da er es ja im jeweiligen Gerät anzeigt, wann es sich das letzte mal gemeldet hat. Wäre super wenn diese Information auch noch in einen Datenpunkt geschrieben würde, damit man sie abgreifen und weiterverarbeiten kann. Beispiel was gemeint ist siehe Bild in der Anlage. Wäre echt super wenn das umgesetzt würde :)

![Zigbee_last_activity](https://user-images.githubusercontent.com/58658412/119690296-d62b8b00-be49-11eb-8bf9-a1bdb4a447bc.png)

**Comment by asgothian** [comment]
This time is available when checking the timestamp of the "available" state. The "available" state is updated whenever the device sends a message to the coordinator. This includes responses to any attempt to control the device. I do not consider a separate state sensible / required, as this state would only contain the same data as the timestamp of the state which was updated last.

As shown on the iobroker documentation (https://www.iobroker.net/docu/index-81.htm?page_id=5809&lang=en#getState), the function getState returns the required information:

`getState('zigbee.0.ieeeaddress.available) `will return the data in the form `{val: value, ack: true/false, ts: timestamp, lc: lastchanged, from: origin}` .

A.

**Comment by atifan** [comment]
Hi, ok thx for the information. I will try it in iobroker :) thx :)
