### ISSUE TITLE
Device 0x00124b001fff0cdd "PRS3CH1_00.00.05.11TC" not described in statesMapping.

### ISSUE THREAD

**Issue by marsmaennchen** [ioBroker/ioBroker.zigbee#1113]
Is it possible to integrate PRS3CH1_00.00.05.11TC (Lupusec 12126, 1-Kanal Relais) to the Adapter?
Im also using a Hue Button which works very well.
In "supported devices" the Lupusec 12126 PRS3CH1_00.00.05.**10**TC is mentioned.
Maybe they changed the firmware?
Greetings
Patrick
(edit: And its not possible anymore to Remove Device from the Instance. 

> Failed to remove Error: waiting for response TIMEOUT at DeconzAdapter. (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:798:23) at Generator.throw () at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:25:65) at runNextTicks (internal/process/task_queues.js:62:5) at processTimers (internal/timers.js:494:9)

**Comment by asgothian** [comment]
- Which adapter Version are you using ?
- Did you check the "force remove for lost devices" checkbox when trying to remove the device ?
- How does the tile from the config for this adapter look like ?
A.

**Comment by marsmaennchen** [comment]
Thanks for the reply.

Adapter Version 1.5.6 from GitHub after i used the 1.4.4.
I thought maybe the new Version works with the Device.
"Force remove for lost devices" doesn`t work either in 1.5.6. In 1.4.4 it worked.

Adapter tile? Do you mean this:
![AdapterTile](https://user-images.githubusercontent.com/33393715/119848319-020f4500-bf0c-11eb-9492-8be3af10ed8c.PNG)

MfG
Patrick

**Comment by asgothian** [comment]
No, i mean the tile for the device on the "geräte" tab.

Note that you may have to click on the name of the device to trurn the tile over to the information, and please also post the content of the information display which is shown when clicking on the little i icon on the tile.

A.

**Comment by marsmaennchen** [comment]
Oh,sorry, i see.
Here it is:
![tile1](https://user-images.githubusercontent.com/33393715/119863806-3ee23880-bf1a-11eb-9b3b-30f974dac8f1.PNG)
![tile2](https://user-images.githubusercontent.com/33393715/119863818-4275bf80-bf1a-11eb-905e-238b0df5da09.PNG)
![tile3](https://user-images.githubusercontent.com/33393715/119863826-4570b000-bf1a-11eb-8c6a-d7c2e4c765c3.PNG)

Additional Information: The removal of the Device worked this time. No idea why. Did the same steps like before.

**Comment by marsmaennchen** [comment]
Do i need to do anything else with this "Zigbee-Herdsman-Converter issue"?
How does it go on?
Thanks
Patrick

**Comment by asgothian** [comment]
Need and need. In order to integrate this device into the zigbee Adapter it needs to be integrated into said library.
This usually requires physical access to the device. There is a [document in the wiki](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device) which explains what to do and how to go about integrating it. Alternatively, you can make a device support request at the zigbee-herdsman-converters project.


A note of warning - they will most likely write what i wrote above.

**Comment by marsmaennchen** [comment]
And when the zigbee-herdsman-converter project inserted the device? Do I have to update anything?

**Comment by asgothian** [comment]
Once it is properly implemented in the herdsman, it will eventually be supported by the zigbee adapter too. It may take a bit of time as we need to make sure that there are no breaking changes from the herdsman side.
