### ISSUE TITLE
Zigbee not starting after update to 1.5.5

### ISSUE THREAD

**Issue by fg0003** [ioBroker/ioBroker.zigbee#1116]
Coordinator is a CC26X2R1

error in log:
zigbee.0	2021-05-29 09:59:32.030	error	(31703) Cannot read property 'getEntries' of null
zigbee.0	2021-05-29 09:59:32.029	error	at processTicksAndRejections (internal/process/task_queues.js:97:5)
zigbee.0	2021-05-29 09:59:32.029	error	at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:696:41)
zigbee.0	2021-05-29 09:59:32.029	error	at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:368:20)
zigbee.0	2021-05-29 09:59:32.029	error	at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:196:42)
zigbee.0	2021-05-29 09:59:32.029	error	at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:222:43)
zigbee.0	2021-05-29 09:59:32.029	error	at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:210:49)
zigbee.0	2021-05-29 09:59:32.029	error	at Controller.getDevices (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:303:31)
zigbee.0	2021-05-29 09:59:32.029	error	at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:240:16)
zigbee.0	2021-05-29 09:59:32.029	error	at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55)
zigbee.0	2021-05-29 09:59:32.029	error	(31703) TypeError: Cannot read property 'getEntries' of null
zigbee.0	2021-05-29 09:59:32.025	error	(31703) unhandled promise rejection: Cannot read property 'getEntries' of null
zigbee.0	2021-05-29 09:59:32.024	error	(31703) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0	2021-05-29 09:59:32.023	info	(31703) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.0	2021-05-29 09:59:32.021	info	(31703) terminating
zigbee.0	2021-05-29 09:59:32.020	warn	(31703) Failed to stop zigbee during startup
zigbee.0	2021-05-29 09:59:32.019	info	(31703) Zigbee: disabling joining new devices.
zigbee.0	2021-05-29 09:59:32.014	info	(31703) cleaned everything up...
zigbee.0	2021-05-29 09:59:32.012	info	(31703) Got terminate signal TERMINATE_YOURSELF
zigbee.0	2021-05-29 09:58:03.189	error	(31703) getGroups: caught error: TypeError: Cannot read property 'getGroups' of undefined
zigbee.0	2021-05-29 09:56:44.233	error	(31703) getGroups: caught error: TypeError: Cannot read property 'getGroups' of undefined

**Comment by Shadesh** [comment]
Try to install the latest 1.5.6 from GitHub.

**Comment by fg0003** [comment]
Sorry, can not find a version 1.5.6

**Comment by Shadesh** [comment]
Read [here](http://www.stueben.de/iobroker-adapter-per-github-laden/) how to install from GitHub. Just replace "shelly" with "zigbee" in the adapter field shown in this example on the website.

**Comment by fg0003** [comment]
Install for 1.5.6 is done. It is working now. 
Here is the log:

zigbee.0	2021-05-29 13:49:05.039	info	(5714) Zigbee started
zigbee.0	2021-05-29 13:49:05.038	info	(5714) 0x00158d0002bf9654 (addr 21620): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2021-05-29 13:49:05.037	info	(5714) 0x00158d0002bf532b (addr 22243): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2021-05-29 13:49:05.036	info	(5714) 0x00158d00040c178d (addr 8912): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2021-05-29 13:49:05.035	info	(5714) 0x00158d000275008a (addr 32599): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2021-05-29 13:49:05.033	info	(5714) 0x00158d0002e9b448 (addr 45894): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0	2021-05-29 13:49:05.032	info	(5714) 0x00124b001d3aa354 (addr 11049): ptvo.switch - Custom devices (DiY) [Multi-channel relay switch](https://ptvo.info/zigbee-switch-configurable-firmware-router-199/) (Router)
zigbee.0	2021-05-29 13:49:05.027	info	(5714) 0x00124b001d3aceed (addr 11845): ptvo.switch - Custom devices (DiY) [Multi-channel relay switch](https://ptvo.info/zigbee-switch-configurable-firmware-router-199/) (Router)
zigbee.0	2021-05-29 13:49:04.992	info	(5714) Currently 7 devices are joined:
zigbee.0	2021-05-29 13:49:04.984	info	(5714) --> transmitPower : high
zigbee.0	2021-05-29 13:49:04.984	info	(5714) Unable to disable LED, unsupported function.
zigbee.0	2021-05-29 13:49:04.983	info	(5714) Disable LED
zigbee.0	2021-05-29 13:49:04.976	info	(5714) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210120}}
zigbee.0	2021-05-29 13:49:04.846	warn	(5714) Extended PAN ID is reversed (expected=dfdddddddddddddd, actual=dddddddddddddddf)
zigbee.0	2021-05-29 13:49:03.123	info	(5714) Installed Version: ioBroker/ioBroker.zigbee#master
zigbee.0	2021-05-29 13:49:02.825	info	(5714) Starting Zigbee npm ...
zigbee.0	2021-05-29 13:49:02.708	info	(5714) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.0, js-controller: 3.2.16
zigbee.0	2021-05-29 13:48:54.740	info	(3239) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.0	2021-05-29 13:48:54.739	info	(3239) terminating
zigbee.0	2021-05-29 13:48:54.357	info	(3239) Zigbee: disabling joining new devices.
zigbee.0	2021-05-29 13:48:54.355	info	(3239) cleaned everything up...
zigbee.0	2021-05-29 13:48:54.353	info	(3239) Got terminate signal TERMINATE_YOURSELF

Should I change the PAN ID ?  I modified is during installation of the CC26X2R1
Do I have to pair then all devices again??

**Comment by Shadesh** [comment]
You can change it to "**dfdddddddddddddd**" and you should be good, no re-pairing required.
If you're interested, [here](https://github.com/ioBroker/ioBroker.zigbee/issues/1105) is a long issue thread about the "reversed EPID".

**Comment by fg0003** [comment]
Thanks a lot for your help!!
