### ISSUE TITLE
improvement: export already paired devices

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.zigbee#112]
Hi there,

I would really appreciate a feature to export/import somehow the already paired devices to not repeat the whole pairing method for all my devices (20+) at different locations (like outside on the roof)

Because of signal strength issues i'm currently planning to move only the CC2531 stick to an "multihost" iobroker pi which i can locate in the middle of the house. Main iobroker host is running on synology nas which is located in the office room.

Or is there already any possibility for this?

**Comment by arteck** [comment]
you can copy the DB to other Device.. but the all devices are linked with the stick exclusive
