### ISSUE TITLE
Pairing nicht mehr möglich

### ISSUE THREAD

**Issue by emddummi** [ioBroker/ioBroker.zigbee#1121]
Hallo,

ich habe auch momentan die neuste Version (1.5.6) installiert und die lief für mich problemlos. Alles funktioniert wie immer, bis ich heute ein neues Gerät anlernen wollte. Da kam folgendes in dem Fenster was beim pairen auf geht:

`Error: Failed to open the network: Error: SRSP - UTIL - ledControl after 6000ms
    at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7). undefined
Pairing started `

Zigbee Modul: CC2538 + CC2592

**Comment by asgothian** [comment]
Please open an issue with this information at [this project](https://github.com/Koenkk/zigbee-herdsman)

**Comment by emddummi** [comment]
Done!

**Comment by emddummi** [comment]
Wurde geschlossen mit fix. Kann das hier dann auch zu? Also wird das bei euch automatisch übernommen?

MfG
eMd

**Comment by asgothian** [comment]
It will take a bit but it will get integrated into iobroker.zigbee

**Comment by asgothian** [comment]
I set up a test branch which uses the latest zigbee-herdsman (which does include this fix).

It is available for install here: https://github.com/asgothian/ioBroker.zigbee/tarball/LatestHerdsman

Proceed with caution. Use of this branch may reveal additional issues.

This issue will be closed when the official adapter moves on to this herdsman version.

A.

**Comment by ChaotenKurt** [comment]
Hallo, wollte einmal generell fragen, wie ich meinen Sonoff-Zigbee-Brigde in den Adapter Einpflege. Auf der Bridge läuft bereits Tasmota-Zigbee und habe alles entsprechend der Anleitung geflachst. Im IOBroker im Zigbee Adapter habe ich auch Silicon Labs EZSP/EFR32 ausgewählt, jedoch müsste ich ihm doch nach meiner Logik noch die IP Adresse nennen, welcher meine Bridge hat, oder?

Ich hoffe mir kann jemand kurz weiterhelfen.[
<img width="1859" alt="Bildschirmfoto 2021-06-12 um 10 16 35" src="https://user-images.githubusercontent.com/80848243/121770043-57cc2a00-cb67-11eb-85ab-7a705ff5989f.png">
](url)

**Comment by asgothian** [comment]
> Auf der Bridge läuft bereits Tasmota-Zigbee und habe alles entsprechend der Anleitung geflachst

Nach der Beschreibung schwer zu sagen ob das reicht.


Anleitung siehe hier:
https://forum.iobroker.net/topic/43446/zigbee-adapter-mit-sonoff-zigbee-bridge

**Comment by Diggi3** [comment]
> I set up a test branch which uses the latest zigbee-herdsman (which does include this fix).
> 
> It is available for install here: https://github.com/asgothian/ioBroker.zigbee/tarball/LatestHerdsman
> 
> Proceed with caution. Use of this branch may reveal additional issues.
> 
> This issue will be closed when the official adapter moves on to this herdsman version.
> 
> A.

How can I update my version with this files?
