### ISSUE TITLE
ios and safari problem 

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#1122]
![grafik](https://user-images.githubusercontent.com/6681528/120652671-49ec1a00-c480-11eb-9d5a-5808b94c5a55.png)

**Comment by Shadesh** [comment]
I have a similar problem for a long time now.
Can you try to click in the "invisible" header of an empty device tile? It should flip and give you the normal view.
I tried to debug but didn't find a lot only a few missing .js files. Maybe this helps?

<img width="1449" alt="notfound" src="https://user-images.githubusercontent.com/8633307/120669995-4496cb80-c490-11eb-8cc0-2bf88ca61eec.png">

**Comment by austrogaucho** [comment]
Same issue here, if you click on the green-check-icon of a device, the tile flips over, but the backside appears as a white tile with no icons visible, if you move the mouse over the white tile you can discover the areas where the icons should be and you can click to start the action. Issue is with safari only
