### ISSUE TITLE
TuYa Plug wird falsch erkannt

### ISSUE THREAD

**Issue by kulibulli** [ioBroker/ioBroker.zigbee#1124]
Hallo, 
ich hoffe das hier die richtige Stelle ist. Ich habe einen ZigBee Plug bekommen, dieser heißt BSD34Z der Hersteller ist 99% TuYa der Plug ist nich gelabelt aber er soll mit der TuYa App funktionieren.
Der Plug soll auch Strom messen können und ist die ZigBee version vom WLAN gesteuerten BSD34.

In der Liste der unterstützten Geräte ist der TS011F_plug , dieser hier meldet sich aber als Model TS011F an, wovon es aber mehrere Varianten gibt.
 
Ich nutze Vers. 1.5.6

Hier mehr Details:

![plug 4](https://user-images.githubusercontent.com/85399902/120893478-daa72f00-c613-11eb-88a4-d4fe6c801f90.jpg)
![plug 3](https://user-images.githubusercontent.com/85399902/120893479-db3fc580-c613-11eb-972e-fc67761e2702.jpg)
![plug 2](https://user-images.githubusercontent.com/85399902/120893480-db3fc580-c613-11eb-8bdb-14d73c557f29.jpg)
![plug 1](https://user-images.githubusercontent.com/85399902/120893481-dbd85c00-c613-11eb-9be7-5bcb12dcb642.jpg)

**Comment by asgothian** [comment]
Please test with 1.6.12 (current GitHub version)
