### ISSUE TITLE
Receiving warnings regarding the maximum value for link quality

### ISSUE THREAD

**Issue by MiGoller** [ioBroker/ioBroker.zigbee#1126]
Hey,

since upgrading the zigbee adapter to version I receive such warnings for some of my Eurotronic Spirit temperature controllers:

`State value to set for "zigbee.0.xxxx.link_quality" has value "255" greater than max "254"`

The temperature controllers' link quality is really set to 255.

Any ideas?

Kr, 
MiGoller

**Comment by StefCGN** [comment]
Hello,
i have the same problem with Zigbee 1.5.6.

Is there any solution available?

**Comment by asgothian** [comment]
- Attaching a question to a closed issue makes it unlikely that anyone answers.
- Which device exactly is generating the message you post of ?
- which error exactly do you have with zigbee 1.5.6 ? The link_quality issue has been fixed a while ago.

**Comment by StefCGN** [comment]
> 
> 
>     * Attaching a question to a closed issue makes it unlikely that anyone answers.
Sorry, didnt see, that the issue was closed.
>     * Which device exactly is generating the message you post of ?
All Xiamoi Body motion sensors are producing the message with "no_motion"
>     * which error exactly do you have with zigbee 1.5.6 ? The link_quality issue has been fixed a while ago.
Great, but why is not available through the Repo?
