### ISSUE TITLE
Adapter crashing after latest update

### ISSUE THREAD

**Issue by StrathCole** [ioBroker/ioBroker.zigbee#1127]
Hello,

I have updated the adapter to 1.5.6 recently but am not totally shure which version it was before (1.5.x for sure).
Now the adapter fails to start and it seems it has a problem with the stick recognition suddenly.

```
2021-06-09 11:44:14.733  - error: zigbee.0 (7220) Configuration is not consistent with adapter state/backup!
2021-06-09 11:44:14.734  - error: zigbee.0 (7220) - PAN ID: configured=6754, adapter=65535
2021-06-09 11:44:14.735  - error: zigbee.0 (7220) - Extended PAN ID: configured=00124b001940c032, adapter=0000000000000000
2021-06-09 11:44:14.736  - error: zigbee.0 (7220) - Network Key: configured=<configuredkey>, adapter=<configuredkey>
2021-06-09 11:44:14.736  - error: zigbee.0 (7220) - Channel List: configured=11, adapter=
2021-06-09 11:44:14.737  - error: zigbee.0 (7220) Please update configuration to prevent further issues.
2021-06-09 11:44:14.738  - error: zigbee.0 (7220) If you wish to re-commission your network, please remove coordinator backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.
2021-06-09 11:44:14.738  - error: zigbee.0 (7220) Re-commissioning your network will require re-pairing of all devices!
2021-06-09 11:44:14.740  - error: zigbee.0 (7220) Starting zigbee-herdsman problem : "startup failed - configuration-adapter mismatch - see logs above for more information"
2021-06-09 11:44:14.741  - error: zigbee.0 (7220) Failed to start Zigbee
2021-06-09 11:44:14.741  - error: zigbee.0 (7220) Error herdsman start
```

In the adapter instance config the Ext PAN is set to DDDDDDDDDDDDDDDD since the beginning.

What I tried to far:
Unplugging / replugging the stick in all variations (with reboot, with adapter stop etc.), also tried different USB port.

Stick is recognized by the OS:
```
Bus 001 Device 002: ID 0451:16c8 Texas Instruments, Inc. 

[    4.536423] usb 1-4: new full-speed USB device number 2 using xhci_hcd
[    4.686328] usb 1-4: New USB device found, idVendor=0451, idProduct=16c8, bcdDevice= 1.00
[    4.686334] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    4.686337] usb 1-4: Product: CC2538 USB CDC
[    4.686339] usb 1-4: Manufacturer: Texas Instruments
```

After everything failed I also tried using the previous 1.5.3 adapter version, but it then simply fails with
```
2021-06-09 09:26:18.817  - error: zigbee.0 (3786) TypeError: Cannot read property 'error' of undefined
    at ZnpAdapterManager.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/manager.js:193:41)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/manager.js:24:58)
```

I also tried to delete the nvbackup.json as stated (just for testing) but it does not help.

Hope someone is able to enlighten me :smile: 

Thank you

**Comment by asgothian** [comment]
Please attempt to update to my test branch at
https://github.com/asgothian/ioBroker.zigbee/tarball/LatestHerdsman

And see if that helps.

A.

**Comment by StrathCole** [comment]
Sadly not. Exactly the same log lines.

**Comment by asgothian** [comment]
That is not good. You are the second person providing this kind of log. Can you please provide more information on your coordinator and firmware, as well as try to download the nv-memory from your coordinator following the  instruction @castorw has linked in another issue:

> This seems to be a very interesting state of adapter's NV and this is the second case I see. Could you provide information on device/firmware being used and a NV dump would be extremely useful (use https://github.com/zigpy/zigpy-znp/blob/dev/zigpy_znp/tools/nvram_read.py). By very interesting state I mean - it shouldn't work as coordinator at all.

A.

**Comment by StrathCole** [comment]
It should be this one from the ioBroker forums: https://forum.iobroker.net/topic/28994/verkaufe-cc2538-cc2592-zigbee-stick

Are there any sensitive information inside the nvdump? Or is it safe to attach it here?

**Comment by AgentP2** [comment]
I have the same Problem/Messages/Zigbee-Stick

**Comment by n00b31** [comment]
Hi, 
I had the same issue, in the meantime I tried to uninstall/reinstall the zigbee adapter. The result is that I'm not able to install the adapter anymore. Attached you'll find the installation log, I'm thankful for every hint.

```
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/bin/npm',
0 verbose cli   'install',
0 verbose cli   'asgothian/ioBroker.zigbee#LatestHerdsman',
0 verbose cli   '--loglevel',
0 verbose cli   'error',
0 verbose cli   '--prefix',
0 verbose cli   '/opt/iobroker'
0 verbose cli ]
1 info using npm@7.17.0
2 info using node@v12.22.1
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 8ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/opt/iobroker/.npmrc Completed in 3ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/home/iobroker/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/opt/iobroker/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 4ms
17 timing config:load:setEnvs Completed in 4ms
18 timing config:load Completed in 35ms
19 timing npm:load:configload Completed in 35ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 2ms
22 timing npm:load:cleanupLog Completed in 8ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 2ms
25 timing npm:load Completed in 53ms
26 timing config:load:flatten Completed in 10ms
27 timing arborist:ctor Completed in 2ms
28 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
29 timing idealTree:init Completed in 1646ms
30 timing idealTree:userRequests Completed in 6041ms
31 silly idealTree buildDeps
32 silly fetch manifest iobroker.zigbee@asgothian/ioBroker.zigbee#LatestHerdsman
33 silly placeDep ROOT iobroker.zigbee@1.5.6 OK for: iobroker.inst@2.0.3 want: asgothian/ioBroker.zigbee#LatestHerdsman
34 silly fetch manifest zigbee-herdsman@^0.13.110
35 silly fetch manifest zigbee-herdsman-converters@^14.0.162
36 silly fetch manifest tar@^6.0.5
37 http fetch GET 200 https://registry.npmjs.org/tar 326ms (cache revalidated)
38 http fetch GET 200 https://registry.npmjs.org/zigbee-herdsman-converters 353ms (cache revalidated)
39 http fetch GET 200 https://registry.npmjs.org/zigbee-herdsman 388ms (cache revalidated)
40 timing idealTree:#root Completed in 4630ms
41 silly placeDep ROOT tar@6.1.0 OK for: iobroker.zigbee@1.5.6 want: ^6.0.5
42 silly placeDep ROOT zigbee-herdsman@0.13.115 OK for: iobroker.zigbee@1.5.6 want: ^0.13.110
43 silly placeDep ROOT zigbee-herdsman-converters@14.0.176 OK for: iobroker.zigbee@1.5.6 want: ^14.0.162
44 silly fetch manifest chownr@^2.0.0
45 silly fetch manifest mkdirp@^1.0.3
46 silly fetch manifest debounce@^1.2.0
47 silly fetch manifest debug@^4.3.1
48 silly fetch manifest mixin-deep@^2.0.1
49 silly fetch manifest @serialport/bindings@9.0.4
50 silly fetch manifest mz@^2.7.0
51 silly fetch manifest serialport@9.0.6
52 silly fetch manifest slip@^1.0.2
53 silly fetch manifest buffer-crc32@^0.2.13
54 silly fetch manifest tar-stream@^2.2.0
55 http fetch GET 200 https://registry.npmjs.org/mixin-deep 130ms (cache revalidated)
56 http fetch GET 200 https://registry.npmjs.org/debug 134ms (cache revalidated)
57 http fetch GET 200 https://registry.npmjs.org/chownr 143ms (cache revalidated)
58 http fetch GET 200 https://registry.npmjs.org/slip 210ms (cache revalidated)
59 http fetch GET 200 https://registry.npmjs.org/mz 233ms (cache revalidated)
60 http fetch GET 200 https://registry.npmjs.org/tar-stream 227ms (cache revalidated)
61 http fetch GET 200 https://registry.npmjs.org/debounce 272ms (cache revalidated)
62 http fetch GET 200 https://registry.npmjs.org/mkdirp 275ms (cache revalidated)
63 http fetch GET 200 https://registry.npmjs.org/buffer-crc32 262ms (cache revalidated)
64 http fetch GET 200 https://registry.npmjs.org/@serialport%2fbindings 287ms (cache revalidated)
65 http fetch GET 200 https://registry.npmjs.org/serialport 299ms (cache revalidated)
66 timing idealTree:node_modules/iobroker.zigbee Completed in 379ms
67 silly placeDep node_modules/tar chownr@2.0.0 OK for: tar@6.1.0 want: ^2.0.0
68 silly placeDep node_modules/tar mkdirp@1.0.4 OK for: tar@6.1.0 want: ^1.0.3
69 timing idealTree:node_modules/tar Completed in 7ms
70 timing idealTree:node_modules/tar/node_modules/chownr Completed in 0ms
71 timing idealTree:node_modules/tar/node_modules/mkdirp Completed in 0ms
72 timing idealTree:buildDeps Completed in 5023ms
73 timing idealTree:fixDepFlags Completed in 35ms
74 timing idealTree Completed in 12782ms
75 timing reify:loadTrees Completed in 12785ms
76 timing reify:diffTrees Completed in 108ms
77 silly reify mark retired [ '/opt/iobroker/node_modules/iobroker.lovelace/node_modules/mime' ]
78 silly reify mark retired [ '/opt/iobroker/node_modules/iobroker.zigbee' ]
79 silly reify mark retired [ '/opt/iobroker/node_modules/tar' ]
80 silly reify mark retired [ '/opt/iobroker/node_modules/zigbee-herdsman-converters' ]
81 silly reify mark retired [ '/opt/iobroker/node_modules/zigbee-herdsman' ]
82 silly reify moves {
82 silly reify   '/opt/iobroker/node_modules/iobroker.lovelace/node_modules/mime': '/opt/iobroker/node_modules/iobroker.lovelace/node_modules/.mime-n5p3xWB9',
82 silly reify   '/opt/iobroker/node_modules/iobroker.zigbee': '/opt/iobroker/node_modules/.iobroker.zigbee-1JQaSLfT',
82 silly reify   '/opt/iobroker/node_modules/tar': '/opt/iobroker/node_modules/.tar-NeTPgzH9',
82 silly reify   '/opt/iobroker/node_modules/zigbee-herdsman-converters': '/opt/iobroker/node_modules/.zigbee-herdsman-converters-DzgWyYTV',
82 silly reify   '/opt/iobroker/node_modules/zigbee-herdsman': '/opt/iobroker/node_modules/.zigbee-herdsman-KZGHBvfL'
82 silly reify }
83 timing reify:rollback:retireShallow Completed in 2ms
84 timing command:install Completed in 12930ms
85 verbose stack Error: ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/tar' -> '/opt/iobroker/node_modules/.tar-NeTPgzH9'
86 verbose cwd /opt/iobroker
87 verbose Linux 5.4.0-1036-raspi
88 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "asgothian/ioBroker.zigbee#LatestHerdsman" "--loglevel" "error" "--prefix" "/opt/iobroker"
89 verbose node v12.22.1
90 verbose npm  v7.17.0
91 error code ENOTEMPTY
92 error syscall rename
93 error path /opt/iobroker/node_modules/tar
94 error dest /opt/iobroker/node_modules/.tar-NeTPgzH9
95 error errno -39
96 error ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/tar' -> '/opt/iobroker/node_modules/.tar-NeTPgzH9'
97 verbose exit -3985 verbose stack Error: ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/tar' -> '/opt/iobroker/node_modules/.tar-NeTPgzH9'
86 verbose cwd /opt/iobroker
87 verbose Linux 5.4.0-1036-raspi
88 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "asgothian/ioBroker.zigbee#LatestHerdsman" "--loglevel" "error" "--prefix" "/opt/iobroker"
89 verbose node v12.22.1
90 verbose npm  v7.17.0
91 error code ENOTEMPTY
92 error syscall rename
93 error path /opt/iobroker/node_modules/tar
94 error dest /opt/iobroker/node_modules/.tar-NeTPgzH9
95 error errno -39
96 error ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/tar' -> '/opt/iobroker/node_modules/.tar-NeTPgzH9'
97 verbose exit -39

```

**Comment by asgothian** [comment]
> I have the same Problem/Messages/Zigbee-Stick

Are you certain that you had the identical issue ? Key points are
- cc2538 Coordinator
- Log messages with illegal data from the configuration. Note the 65535 as PAN ID (that is illegal) or the 0000000000000000 as Extended PAN ID

```
2021-06-09 11:44:14.734  - error: zigbee.0 (7220) - PAN ID: configured=6754, adapter=65535
2021-06-09 11:44:14.735  - error: zigbee.0 (7220) - Extended PAN ID: configured=00124b001940c032, adapter=0000000000000000
2021-06-09 11:44:14.736  - error: zigbee.0 (7220) - Network Key: configured=<configuredkey>, adapter=<configuredkey>
2021-06-09 11:44:14.736  - error: zigbee.0 (7220) - Channel List: configured=11, adapter=

```

If you do have those messages, please also mention the exact source of stick and firmware as well as dumping the nv memory as @StrathCole did.

A.

**Comment by asgothian** [comment]
> Hi,
> I had the same issue, in the meantime I tried to uninstall/reinstall the zigbee adapter. The result is that I'm not able to install the adapter anymore. Attached you'll find the installation log, I'm thankful for every hint.

- As i asked of @AgentP2: Are you certain you had the identical issue ? If so, please follow the same request.
- Either case, to fix your install issue please open a thread on the iobroker forum or a new issue, so we do not poison this issue with unrelated posts.
A.

**Comment by StrathCole** [comment]
@asgothian would it be possible to set the package.js of the zigbee adapter to use an older herdsman adapter version to work around the issue?

**Comment by asgothian** [comment]
Yes. Unfortunately, it is not so easy to find a working pair, especially as all my installations (i am currently running 5 zigbee installation with different coordinators just do get closer to the issues) do not show this particular issue. Please have a look at this issue:

https://github.com/ioBroker/ioBroker.zigbee/issues/1119

The final comment outlines the safest path to get to the result you need.

**Comment by craysee** [comment]
Hi,

i have the same problems as StrathCole, and i have the same Stick (see the link, i am the first :-)

CC2538
The Messages are the same and PanID and channel errors also.

This is the data of my coordinator: 
type:zStack30x
 version:2-2.2.7.2.
 revision:20190523
 port:/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
 channel:11

Best regards

Cray

**Comment by fabwal** [comment]
Hi, I have the same problem:

- Stick: CC2538
- PAN ID is the same, Extended PAN ID is different.
- Coordinator firmware version: {"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200211}}
- Port:/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
- Channel: 11

Thanks,
Fabian

**Comment by castorw** [comment]
@StrathCole I have examined the NV dump you provided - unfortunately this is the very interesting case where the adapter NV is in state in which it shouldn't run as coordinator at all. Or at least the NV dump does not seem to represent adapter with correctly formed network. The PAN ID is 65535 and Extended PAN ID is nulled. We have seen several cases like this, but I cannot yet tell how these adapters were working properly before. I also see that the other NV items related to this issue (PAN ID and Extended PAN ID) are configured properly, however are not reflected in NIB - which is super weird. I am afraid this might be related to the firmware build (version).

**Comment by castorw** [comment]
@fabwal I think your problem is much simpler. It's standard EPID collision, so entering the Extended PAN ID reported as `adapter=` into configuration should fix your issue.

**Comment by StrathCole** [comment]
> We have seen several cases like this, but I cannot yet tell how these adapters were working properly before.

That exactly is the question. The adapter worked fine for months before the last update of the adapter I made. I have not yet been able to try rolling back the herdsman packages because it seems complicated.

**Comment by castorw** [comment]
@StrathCole Can you provide me with exact firmware source and version? I will try to take a look at the diffs and check if I see anything out of the ordinary.

**Comment by StrathCole** [comment]
> @StrathCole Can you provide me with exact firmware source and version? I will try to take a look at the diffs and check if I see anything out of the ordinary.

If you tell me how. The stick was bought as is from the link provided.

**Comment by castorw** [comment]
Okay so it most likely contains stock Z-Stack firmware which may be configured in many ways differently from which is required by ZH to work properly. Early in the startup log you should see firmware version/revision. Can you please check and provide that information?

Anyway, it is always a good idea to update to the latest firmware provided by Z2M/ioBroker community to make sure you have firmware properly configured for the job.

**Comment by StrathCole** [comment]
Sadly not.

```
2021-06-28 15:25:22.788  - info: zigbee.0 (31303) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.3.12
2021-06-28 15:25:22.962  - info: zigbee.0 (31303) Starting Zigbee  npm ...
2021-06-28 15:25:23.419  - info: zigbee.0 (31303) Installed Version: asgothian/ioBroker.zigbee#LatestHerdsman
2021-06-28 15:25:25.229  - error: zigbee.0 (31303) Configuration is not consistent with adapter state/backup!
2021-06-28 15:25:25.231  - error: zigbee.0 (31303) - PAN ID: configured=xxxx, adapter=65535
2021-06-28 15:25:25.232  - error: zigbee.0 (31303) - Extended PAN ID: configured=xxxxxxxxxxxx, adapter=0000000000000000
2021-06-28 15:25:25.233  - error: zigbee.0 (31303) - Network Key: configured=xxxxxxxxx, adapter=xxxxxxxxxxx
2021-06-28 15:25:25.234  - error: zigbee.0 (31303) - Channel List: configured=11, adapter=
2021-06-28 15:25:25.234  - error: zigbee.0 (31303) Please update configuration to prevent further issues.
2021-06-28 15:25:25.235  - error: zigbee.0 (31303) If you wish to re-commission your network, please remove coordinator backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.
2021-06-28 15:25:25.236  - error: zigbee.0 (31303) Re-commissioning your network will require re-pairing of all devices!
2021-06-28 15:25:25.237  - error: zigbee.0 (31303) Starting zigbee-herdsman problem : "startup failed - configuration-adapter mismatch - see logs above for more information"
2021-06-28 15:25:25.238  - error: zigbee.0 (31303) Failed to start Zigbee
2021-06-28 15:25:25.239  - error: zigbee.0 (31303) Error herdsman start
```

**Comment by StrathCole** [comment]
From the herdsman debug log: 
```
2021-06-28 16:15:34.157  - debug: zigbee.0 (778) zigbee-herdsman:adapter:zStack:adapter Detected znp version 'zStack30x' ({"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20190523})
```

**Comment by fabwal** [comment]
@castorw Thanks for the quick reply. If I change the EPID I need to reconnect 56 Devices, so there has to be another way ;) Updates were working fine so far, why now the problems?

**Comment by castorw** [comment]
@StrathCole Well unfortunately since its stock firmware I cannot really tell you much about it. Just recommend to use community-provided firmwares which are compiled to be compatible with ZH.

**Comment by castorw** [comment]
@fabwal You will only be updating configuration to match the adapter state. Not changing the actual EPID - just the other way around. Making your configuration to conform to reality.

**Comment by StrathCole** [comment]
> @StrathCole Well unfortunately since its stock firmware I cannot really tell you much about it. Just recommend to use community-provided firmwares which are compiled to be compatible with ZH.

So I'll have to try to find a working older herdsman combination that worked. Think it was the one that was initially used with the adapter 1.5.3.

**Comment by fabwal** [comment]
@castorw Sorry, never did that. Is nvbackup.json the right place to change?

**Comment by StrathCole** [comment]
@castorw @asgothian 

I have now managed to get my zigbee (partly) working again. I have uninstalled all instances of herdsman and herdsman-converters.
```bash
find /opt/iobroker -type d -name "*herdsman*"
```
I removed all instances (had one in /opt/iobroker, one in iobroker.zigbee).

and then installed:
```bash
cd /opt/iobroker
npm install zigbee-herdsman@0.13.92 --production
npm install zigbee-herdsman-converters@14.0.128 --production
```
Then I made sure that those versions were the only ones left (the converters package installed 0.13.91, too, but that seems okay).

Currently my xiaomi devices are still missing, but the Hue devices are back.

**Comment by StrathCole** [comment]
Have to correct myself. The devices are all missing, only the groups are there. Weird, but controlling the groups does work even though there are no(!) devices shown or in log.

**Comment by StrathCole** [comment]
Devices are now back, too. Have restored an old (February) shepherd.db to the iobroker-data directory and also downgraded adapter version to 1.5.3

**Comment by asgothian** [comment]
Thank you for picking out the version numbers. I will host a GitHub installable version with these exact numbers at

https://github.com/asgothian/ioBroker.zigbee/tarball/Zigbee153

**Comment by StrathCole** [comment]
Thank you @asgothian I hope there will be any "real" solution in the future to make long-term updates possible.

**Comment by asgothian** [comment]
> Thank you @asgothian I hope there will be any "real" solution in the future to make long-term updates possible.

I am working on a final solution, although in your specific case, a firmware update for the cc2538 may be unavoidable

Also: Anyone who has installed the temp fix from my GitHub should reinstall it - the 1.5.6 adapter does not fully play nice with the older herdsman, so i fixed the issue causing error messages from the device configuration.

**Comment by StrathCole** [comment]
> I am working on a final solution, although in your specific case, a firmware update for the cc2538 may be unavoidable

I fear that will not be possible for me. I have so many devices that are not recognized on pairing due to the distance to the coordinator. I had to pair them before installing in place and will not simply be able to re-pair them.

**Comment by asgothian** [comment]
> Thank you for picking out the version numbers. I will host a GitHub installable version of the 1.5.6 adapter (under 1.5.6p with these exact numbers at
> 
> https://github.com/asgothian/ioBroker.zigbee/tarball/Zigbee153

Unfortunately, there was another issue with my 1.5.6p fork.

Anyone using it please reinstall.

**Comment by asgothian** [comment]
> > I am working on a final solution, although in your specific case, a firmware update for the cc2538 may be unavoidable
> 
> I fear that will not be possible for me. I have so many devices that are not recognized on pairing due to the distance to the coordinator. I had to pair them before installing in place and will not simply be able to re-pair them.

Are you certain that a firmware update will require repairing ? Most Coordinators will nowadays retain their devices when the firmware is updated.

A.

**Comment by StrathCole** [comment]
> Are you certain that a firmware update will require repairing ?

At least that's what the seller told me. I'd rather not risk loosing all connections.

**Comment by StrathCole** [comment]
@asgothian is there any information about if the problem will be fixed in the main repo/branch? I try to avoid accidently clicking on the update button in ioBroker that now proposes 1.6 for install.

**Comment by fabwal** [comment]
@castorw @asgothian
Is this already fixed? Can I safely update my adapter to latest version. I am on 1.5.6p now.

**Comment by asgothian** [comment]
This has not been fixed and indeed cannot be fixed - a fix requires a firmware update on the coordinator.

A workaround exists in 1.6.6 and newer, allowing you to force the zigbee adapter to ignore any configuration discrepancies between nvram and adapter configuration. Wether this will remain possible in the future is hard to say.

I would strongly suggest for everyone to update the firmware.

A.

**Comment by asgothian** [comment]
I am glad things are working now. Fortunately, the new firmware will allow updates without having to pair again.

A.
