### ISSUE TITLE
PARKSIDE® Smarter Bewässerungscomputer

### ISSUE THREAD

**Issue by 1rfsNet** [ioBroker/ioBroker.zigbee#1130]
Leider wird der Smarte Bewässerungscomputer von PARKSIDE (LIDL) nicht erkannt. Installierte Version: 1.5.6

Link: https://www.lidl.de/de/parkside-smarter-bewaesserungscomputer-zigbee-smart-home/p375570
Wird erkannt als TS0601

> modelZigbee:TS0601
> type:EndDevice
> nwk:58959
> manuf id:4098
> manufacturer:_TZE200_htnnfasr
> power:Battery
> app version:86
> hard version:1
> zcl version:3
> stack version:0
> date code:
> interviewed:true
> configured:false
> endpoint:1
> profile:260
> input clusters:genBasic (0)
> genGroups (4)
> genScenes (5)
> genOnOff (6)
> genIdentify (3)
> manuSpecificTuya (61184)
> output clusters:genOta (25)
> genTime (10)

![Capture210611](https://user-images.githubusercontent.com/48516961/121679743-fb123600-cab8-11eb-9911-4fe15bc6463f.PNG)

Bild:
![image](https://user-images.githubusercontent.com/48516961/121679789-06fdf800-cab9-11eb-870a-09cc5d418c20.png)

Ich hoffe ich habe nichts vergessen. Falls ich sonst unterstützen kann, immer gerne!

**Comment by ThreeCO** [comment]
It may be switched on/off manually via expert tab
> Cluster-ID: genOnOff (6)
> Functional
> on (1)
> Attribute-ID onOff (0, Type 16)

Unfortunately it closes itself after 60 seconds (default of the device). 

It also does not seem to send back its current state automatically. 

If it would at least be known as switch one could turn it off/on manually. 

Really looking forward to the implementation!

**Comment by asgothian** [comment]
Please see [here](https://forum.iobroker.net/topic/45486/parkside-zigbee-bewässerung-an-cc25x2r1/45?_=1623647671416) for a temporary implementation. If you place that file in /opt/iobroker/iobroker.data and enter the file name as "external converter" in the iobroker configuration the device should be controllable by iobroker.

Note that this is only temporary as it only exposes the on/off function but does not generate any means of reporting.

A.

**Comment by 1rfsNet** [comment]
> Additionally, i would ask for you to test if the attribute onOff can be read using the expert tab.

Reading is working: SUCCESS {"onOff":0}
But I cannot write: READ_ONLY "Zigbee error 136 received!"

**Comment by asgothian** [comment]
Does the device offer a "device query" state ? If so, can you activate it and check if the state will be updated if the device query is triggered ?

A.

**Comment by 1rfsNet** [comment]
How do I check this?

**Comment by asgothian** [comment]
🤦🏾 Admin5:
<img width="1157" alt="Screen Shot 2021-06-16 at 15 30 27 " src="https://user-images.githubusercontent.com/45667167/122228059-c7b81880-ceb7-11eb-91a7-d0e35101f0e0.png">
If you don't have Admin5, try in Admin 3:
<img width="957" alt="Screen Shot 2021-06-16 at 15 31 36 " src="https://user-images.githubusercontent.com/45667167/122228240-f1713f80-ceb7-11eb-85b1-6532a795f9cd.png">

Activate the highlighted state and check the 'last updated' timer on the on state.

**Comment by 1rfsNet** [comment]
But how do I get the device in objects? As its not recognized its not visible in objects.

**Comment by asgothian** [comment]
Please read this comment (and the linked thread)


> Please see [here](https://forum.iobroker.net/topic/45486/parkside-zigbee-bew%C3%A4sserung-an-cc25x2r1/45?_=1623647671416) for a temporary implementation. If you place that file in /opt/iobroker/iobroker.data and enter the file name as "external converter" in the iobroker configuration the device should be controllable by iobroker.
> 
> Note that this is only temporary as it only exposes the on/off function but does not generate any means of reporting.
> 
> Additionally, i would ask for you to test if the attribute onOff can be read using the expert tab.
> 
> A.

**Comment by 1rfsNet** [comment]
I tried the instruction in the linked thread but there is nothing about /opt/iobroker/iobroker.data (which I don't even have in my iobroker installation).
I tried the workaround with the tuya.js and woox.js (not at the same time) but both are not working for me. Don't know why.

**Comment by ThreeCO** [comment]
> I tried the instruction in the linked thread but there is nothing about /opt/iobroker/iobroker.data (which I don't even have in my iobroker installation).
> 
> I tried the workaround with the tuya.js and woox.js (not at the same time) but both are not working for me. Don't know why. 

The woox.js workaround in combination with a repeating node-red flow definitely works. As far as I can see it even makes it possible to update status with a push of a button. But that I still need to verify. 

Please remember to restart your zigbee-adapter after adding the respective line to woox.js 

After that it worked without the need to repair.

**Comment by 1rfsNet** [comment]
I know I must seem like a complete idiot to you here, but it just doesn't work. I have edited the Woox file, even tried to copy the Woox file completely (the file from the board). Have completely restarted iobroker each time, paired the device dozens of times, no chance. It is still only displayed as TS0601 with the nice question mark image. Accordingly, it does not appear in objects.

I honestly don't know any further. Actually there is nothing that can be done wrong.

**Comment by ThreeCO** [comment]
> I know I must seem like a complete idiot to you here, but it just doesn't work. I have edited the Woox file, even tried to copy the Woox file completely (the file from the board). Have completely restarted iobroker each time, paired the device dozens of times, no chance. It is still only displayed as TS0601 with the nice question mark image. Accordingly, it does not appear in objects.
> 
> 
> 
> I honestly don't know any further. Actually there is nothing that can be done wrong.

Have you checked whether your device has the name you entered in woox.js?

**Comment by 1rfsNet** [comment]
Jup, I did: manufacturer:_TZE200_htnnfasr

fingerprint: [
            {modelID: 'TS0101', manufacturerName: '_TZ3210_eymunffl'},
            {modelID: 'TS0601', manufacturerName: '**_TZE200_htnnfasr**'},
        ],

**Comment by ThreeCO** [comment]
Theoretically:
If I bought the Lidl-Gateway. 
• Where would I get the also needed zigbee sniffer from and 
• how is it operated?
• What are the needed results?

**Comment by asgothian** [comment]
see [here](https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html)

**Comment by andre1974** [comment]
Any news on this?

**Comment by AndreGl** [comment]
Im also interested for a solution. Should I try to provide something to implement whats required?

**Comment by asgothian** [comment]
No news. The device is implemented in the latest herdsman-converters, but due to compatibility issues between the latest herdsman and a number of coordinators in use we are wary to update the dependencies. 

Fixing the herdsman issue will take at least 2 weeks, if not more and depends on the willingness of the zigbee-herdsman developers to integrate the fix we need into their code base.

A temporary solution can be found [here](https://forum.iobroker.net/topic/45486/parkside-zigbee-bewässerung-an-cc25x2r1/177?_=1626430333298). (German language proficiency required)

**Use at your own risk !**

**Comment by asgothian** [comment]
Fixed in 1.6.1
