### ISSUE TITLE
Zigbee Adapter 1.5.6 lässt sich nicht lauffähig installieren

### ISSUE THREAD

**Issue by Totalausfall** [ioBroker/ioBroker.zigbee#1132]
Hallo Leute,

ich bin komplett verzweifelt :(

Vorab muss ich sagen, dass ich im Grunde keinen Plan von Linux bzw. Programmierung im Allgemeinen habe und alles nach Anleitung mache. Lerne immer mehr dazu aber bin immer noch blutiger Anfänger. Sollten weitere Infos gebraucht werden, würde ich euch bitten den entsprechenden Befehl dazu zu schreiben. 

Ich weiß übrigens, dass die Formatierung meiner Logs furchtbar ist aber hab keine Ahnung wie ich das vernünftig hinbekomme ._.

Zum Problem:

Ich hab gestern den iobroker komplett neu aufgesetzt und seit dem bekomme ich Zigbee nicht mehr zum laufen. Die 1.4.1 lief in einem Versuch sofort ohne Probleme aber die 1.5.6 funktioniert überhaupt nicht.

Habe jetzt ein komplett jungfräuliches System vor mir, nur Zigbee installiert und nach der Installation gibt er beim aufrufen des Adapters direkt "Error You need save and run adapter before pairing!" aus und beim Versuch die Einstellungen zu speichern kommt "Bitte bestätigen Einige Daten wurden nicht gespeichert. Verwerfen?".

Im Vorfeld habe ich noch den Remote-Desktop installiert und den Host-Name auf ioBroker geändert aber das dürfte ha sicher nicht stören.

Bei der Installation von iobroker wurden einige Warnungen angezeigt, evtl. liegt da das Problem?

## Install-log Iobroker:

`login as: pi
pi@192.168.178.100's password:
Linux ioBroker 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Jun 13 09:56:00 2021

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.

pi@ioBroker:~ $ node -v
v12.22.1
pi@ioBroker:~ $ nodejs -v
v12.22.1
pi@ioBroker:~ $ npm -v
6.14.12
pi@ioBroker:~ $ sudo curl -sLf https://iobroker.net/install.sh | bash -
library: loaded
Library version=2021-04-07

==========================================================================

    Welcome to the ioBroker installer!
    Installer version: 2021-04-07

    You might need to enter your password a couple of times.

==========================================================================

==========================================================================
    Installing prerequisites (1/4)
==========================================================================

Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 https://deb.nodesource.com/node_12.x buster InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Changing npm registry to https://registry.npmjs.org
Installed gcc-c++
Installed libavahi-compat-libdnssd-dev
Installed libudev-dev
Installed libpam0g-dev
Installed libcairo2-dev
Installed libpango1.0-dev
Installed libjpeg-dev
Installed libgif-dev
Installed librsvg2-dev

==========================================================================
    Creating ioBroker user and directory (2/4)
==========================================================================

User iobroker created
Created /etc/sudoers.d/iobroker
Directory /opt/iobroker created

==========================================================================
    Installing ioBroker (3/4)
==========================================================================

In file included from ../../nan/nan.h:56,
                 from ../src/main.cpp:3:
/home/pi/.cache/node-gyp/12.22.1/include/node/node.h:736:43: warning: cast betwe                                                                                                                     en incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::                                                                                                                     addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>,                                                                                                                      void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/12.22.1/include/node/node.h:770:3: note: in expansion o                                                                                                                     f macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/main.cpp:42:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(diskusage, Init)
 ^~~~~~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../src/unix_dgram.cc:5:
/home/pi/.cache/node-gyp/12.22.1/include/node/node.h:736:43: warning: cast betwe                                                                                                                     en incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::                                                                                                                     addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>,                                                                                                                      void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/12.22.1/include/node/node.h:770:3: note: in expansion o                                                                                                                     f macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/unix_dgram.cc:404:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(unix_dgram, Initialize)
 ^~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_ME                                                                                                                     THOD_ARGS_TYPE)’:
../src/serialport.cpp:78:69: warning: cast between incompatible function types f                                                                                                                     rom ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {a                                                                                                                     ka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOp                                                                                                                     en);
                                                                     ^~~~~~~~~~~                                                                                                                     ~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_                                                                                                                     METHOD_ARGS_TYPE)’:
../src/serialport.cpp:135:71: warning: cast between incompatible function types                                                                                                                      from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                     aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_After                                                                                                                     Update);
                                                                       ^~~~~~~~~                                                                                                                     ~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_M                                                                                                                     ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:175:70: warning: cast between incompatible function types                                                                                                                      from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                     aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterC                                                                                                                     lose);
                                                                      ^~~~~~~~~~                                                                                                                     ~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_M                                                                                                                     ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:215:70: warning: cast between incompatible function types                                                                                                                      from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                     aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterF                                                                                                                     lush);
                                                                      ^~~~~~~~~~                                                                                                                     ~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_MET                                                                                                                     HOD_ARGS_TYPE)’:
../src/serialport.cpp:271:68: warning: cast between incompatible function types                                                                                                                      from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                     aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet                                                                                                                     );
                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_MET                                                                                                                     HOD_ARGS_TYPE)’:
../src/serialport.cpp:316:68: warning: cast between incompatible function types                                                                                                                      from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                     aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet                                                                                                                     );
                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan:                                                                                                                     :NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:366:76: warning: cast between incompatible function types                                                                                                                      from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                     aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_                                                                                                                     AfterGetBaudRate);
                                                                            ^~~~                                                                                                                     ~~~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_M                                                                                                                     ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:412:70: warning: cast between incompatible function types                                                                                                                      from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                     aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterD                                                                                                                     rain);
                                                                      ^~~~~~~~~~                                                                                                                     ~~~~
../src/serialport.cpp: At global scope:
../src/serialport.cpp:433:28: warning: unnecessary parentheses in declaration of                                                                                                                      ‘ToParityEnum’ [-Wparentheses]
 SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {
                            ^
../src/serialport.cpp:452:30: warning: unnecessary parentheses in declaration of                                                                                                                      ‘ToStopBitEnum’ [-Wparentheses]
 SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {
                              ^
In file included from ../../../nan/nan.h:56,
                 from ../src/./serialport.h:13,
                 from ../src/serialport.cpp:1:
/home/pi/.cache/node-gyp/12.22.1/include/node/node.h:736:43: warning: cast betwe                                                                                                                     en incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_                                                                                                                     TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {a                                                                                                                     ka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-funct                                                                                                                     ion-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/12.22.1/include/node/node.h:770:3: note: in expansion o                                                                                                                     f macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/serialport.cpp:486:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(serialport, init);
 ^~~~~~~~~~~
../src/serialport_unix.cpp: In function ‘int setup(int, OpenBaton*)’:
../src/serialport_unix.cpp:176:60: warning: ‘%s’ directive output may be truncat                                                                                                                     ed writing up to 1023 bytes into a region of size 1005 [-Wformat-truncation=]
     snprintf(data->errorString, sizeof(data->errorString), "Error %s Cannot ope                                                                                                                     n %s", strerror(errno), data->path);
                                                            ^~~~~~~~~~~~~~~~~~~~                                                                                                                     ~~~~~
../src/serialport_unix.cpp:176:13: note: ‘snprintf’ output 20 or more bytes (ass                                                                                                                     uming 1043) into a destination of size 1024
     snprintf(data->errorString, sizeof(data->errorString), "Error %s Cannot ope                                                                                                                     n %s", strerror(errno), data->path);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/serialport_unix.cpp: In function ‘void EIO_Open(uv_work_t*)’:
../src/serialport_unix.cpp:86:60: warning: ‘%s’ directive output may be truncate                                                                                                                     d writing up to 1023 bytes into a region of size 1003 [-Wformat-truncation=]
     snprintf(data->errorString, sizeof(data->errorString), "Error: %s, cannot o                                                                                                                     pen %s", strerror(errno), data->path);
                                                            ^~~~~~~~~~~~~~~~~~~~                                                                                                                     ~~~~~~~
../src/serialport_unix.cpp:86:13: note: ‘snprintf’ output 22 or more bytes (assu                                                                                                                     ming 1045) into a destination of size 1024
     snprintf(data->errorString, sizeof(data->errorString), "Error: %s, cannot o                                                                                                                     pen %s", strerror(errno), data->path);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ATTENTION: Error reporting via Sentry will be activated on next start of ioBroker

ioBroker wants to make sure to deliver the most stable smart home system.
To allow this we decided to implement an automatic error and crash reporting solution into the js-controller and also into adapters.

THIS REPORTING WILL BE ENABLED WITH THE NEXT START OF YOUR IOBROKER!

For any error that leads to the crash of the js-controller or one of the relevant adapters the error details are send to a server. For the js-controller and core adapters this server is located and operated in germany. For community adapters please check the Github Readme of the affected adapter for details which Sentry server is used.

If you want to disable the error reporting you can use the command
'iobroker plugin disable sentry'
This command will also make sure that no adapter that runs on this host will send crash reporting data to sentry.



==========================================================================
    Finalizing installation (4/4)
==========================================================================

Enabling autostart...
Created symlink /etc/systemd/system/multi-user.target.wants/iobroker.service → /lib/systemd/system/iobroker.service.
Autostart enabled!
Fixing directory permissions...

==========================================================================

    ioBroker was installed successfully
    Open http://192.168.178.100:8081 in a browser and start configuring!

==========================================================================


You need to re-login before doing anything else on the console!

pi@ioBroker:~ $
`

## Install-log Zigbee:

[iobroker.current.log](https://github.com/ioBroker/ioBroker.zigbee/files/6643670/iobroker.current.log)

Es wäre super, wenn ihr einem unfähigen Typen helfen könntet ^^'

Vielen Dank schonmal!

**Comment by asgothian** [comment]
- The compilation warning messages during zigbee adapter installation are caused by the serialport library. This is something we have to live with for the time being.
- The posted log is unreadable, as it was copied from the admin interface or some other web interface.
- Please do the following:
-- stop the zigbee adapter
-- go to the log panel on the iobroker and delete the current log
-- start the zigbee adapter
-- wait 30 seconds
-- stop the zigbee adapter
-- go to the log panel and use the "download log" button to obtain the complete log
-- post said log.

A.

**Comment by Totalausfall** [comment]
Hey, thanks for your answer.

I've downgraded the Adapter last night to 1.4.1, this runs very well.
I wait untill there is a new version and try it again.
