### ISSUE TITLE
QS-Zigbee-C01 Zigbee Curtain Module - stop command for fine-grained tilt control

### ISSUE THREAD

**Issue by HansBorjes** [ioBroker/ioBroker.zigbee#1134]
I have installed one of those modules as a prototype-like test setup at our construction site.

With the parameters that have write permissions I can move in 1% steps, but I cannot find a method to stop a venetian blind at the desired position. Those 1% steps can achieve rotation from vertical to horizontal in best case.

Question: is this a limitation by the device itself or would there be a way to add a stop feature in zigbee/koenkk?

Thanks for sharing your thoughts! 

I need to make a decision which devices to order and my wife demands this feaure... ;-)

**Comment by asgothian** [comment]
Without more details this question cannot be answered.

- how does the device identify in ioBroker
- Which adapter version are you using
- Which herdsman version are you using ?
- which states does the device expose (show in the states db)

A.

**Comment by HansBorjes** [comment]
- Device identifies as "QS-Zigbee-C01 - Lonsonho Curtain/blind motor controller (Router)" in ioBroker.
- Installed Version: iobroker.zigbee@1.5.6
- Is that the herdsman version? Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210320}}
- Exposes: [cover (state, position), moving, calibration, motor_reversal, linkquality](https://www.zigbee2mqtt.io/devices/QS-Zigbee-C01.html)

Another device (ROB_200-010-0 - ROBB Zigbee curtain motor controller (Router)) exposes [less](https://www.zigbee2mqtt.io/devices/ROB_200-010-0.html) but has "Channel 1 switch state" and "Channel 1 switch state" as object IDs. Perhaps that could to the trick?

**Comment by asgothian** [comment]
Please test the following script stub:


Note that the <DEVICEID> must be the IEEE address of your curtain module (without the leading 0x), while <VAL> needs to be replaced with the value you want to set the blinds to (0 to 100)
Check the log for any result.

```
sendTo("zigbee.0", "SendToDevice", {
   "device": '<DEVICEID>',
   "payload": {"position":<VAL>}},
  function (res) {
     console.log(JSON.stringify(res));
  });

```

**Comment by HansBorjes** [comment]
zigbee.0 | 2021-06-16 11:32:13.465 | debug | (28940) convert result {"state":{"position":90}}
-- | -- | -- | --
zigbee.0 | 2021-06-16 11:32:13.438 | debug | (28940) Publish {} to "cc86ecfffebd48bc"
zigbee.0 | 2021-06-16 11:32:13.436 | debug | (28940) Publish {"position":90} to "cc86ecfffebd48bc"
zigbee.0 | 2021-06-16 11:32:13.428 | debug | (28940) Type attributeReport device {"type":"device","device":{"ID":3,"_type":"Router","_ieeeAddr":"0xcc86ecfffebd48bc","_networkAddress":20869,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID
zigbee.0 | 2021-06-16 11:32:13.427 | debug | (28940) Received Zigbee message from '0xcc86ecfffebd48bc', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":90}' from endpoint 1 with groupID 0
zigbee.0 | 2021-06-16 11:32:13.426 | debug | (28940) handleMessage. {"type":"attributeReport","device":{"ID":3,"_type":"Router","_ieeeAddr":"0xcc86ecfffebd48bc","_networkAddress":20869,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID":26
javascript.0 | 2021-06-16 11:32:13.384 | info | (5293) script.js.Blind_test: {"success":true}
zigbee.0 | 2021-06-16 11:32:13.382 | debug | (28940) sendTo "SendToDevice" to system.adapter.javascript.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-16 11:32:13.378 | debug | (28940) target: {"ID":1,"profileID":260,"deviceID":514,"inputClusters":[0,4,5,258],"outputClusters":[25,10],"deviceNetworkAddress":20869,"deviceIeeeAddress":"0xcc86ecfffebd48bc","clusters":{"genBasic
zigbee.0 | 2021-06-16 11:32:13.377 | debug | (28940) convert position, 90, {}
zigbee.0 | 2021-06-16 11:32:13.376 | debug | (28940) Mapped Model: {"fingerprint":[{"modelID":"TS130F","manufacturerName":"_TZ3000_vd43bbfq"}],"model":"QS-Zigbee-C01","vendor":"Lonsonho","description":"Curtain/blind motor controller","fromZigbe
zigbee.0 | 2021-06-16 11:32:13.375 | debug | (28940) entity: {"type":"device","device":{"ID":3,"_type":"Router","_ieeeAddr":"0xcc86ecfffebd48bc","_networkAddress":20869,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID":260,"deviceID":514
zigbee.0 | 2021-06-16 11:32:13.373 | debug | (28940) Calling publish to state for "cc86ecfffebd48bc" with [{"stateDesc":{"id":"position","prop":"position","role":"state","type":"number"},"value":90,"index":0,"timeout":0}]
zigbee.0 | 2021-06-16 11:32:13.370 | warn | (28940) A cc86ecfffebd48bc 0xcc86ecfffebd48bc
zigbee.0 | 2021-06-16 11:32:13.369 | debug | (28940) publishToDevice called with {"device":"cc86ecfffebd48bc","payload":{"position":90}}
javascript.0 | 2021-06-16 11:32:13.366 | info | (5293) script.js.Blind_test: registered 0 subscriptions and 0 schedules
javascript.0 | 2021-06-16 11:32:13.326 | info | (5293) Start javascript script.js.Blind_test

**Comment by asgothian** [comment]
OK.. log says the data is sent successfully. What the log does not say - does the device react to these tests in any way ?

A.

**Comment by HansBorjes** [comment]
Sure, the device moves to the desired position. Does this log tell you anything about the capability of the device to receive a "stop" command or other options to achieve a desired rotation of the lamellas? The position parameter is fine, I am looking for an option to adjust tilt.

**Comment by asgothian** [comment]
Reading the link you sent, the motor does not support a stop command.

A.
