### ISSUE TITLE
Tuya Smart Door Sensor

### ISSUE THREAD

**Issue by Lonelywolf010** [ioBroker/ioBroker.zigbee#1138]
ich habe mir 4 Door sensoren von Tuya gekauft leider werden sie Im Iobroker nicht erkant bzw. als undefined
ich benutze am iobroker den cc2531 mit der zStack30x

![Zigbee Smart Door Sensor ](https://user-images.githubusercontent.com/39695426/122807085-6d5df400-d2cb-11eb-95f9-9a870b2b32a3.png)

![20210621_195200](https://user-images.githubusercontent.com/39695426/122807247-a007ec80-d2cb-11eb-9220-017546189386.jpg)

**Comment by asgothian** [comment]
- Which adapter are you using ?
- Which zigbee-herdsman-converters version does you have installed ?
- Is the sensor listed as supported on zigbee2mqtt.io ?

A.

**Comment by Lonelywolf010** [comment]
Installiert ist die Zigbee Version 1.5.6
bei zigbee2mqtt.io habe ich ihn nicht gefunden

**Comment by asgothian** [comment]
The device needs to be supported in the zigbee-herdsman-converters project first.

What you can do:

Follow [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised) to see if you can obtain the necessary information in order to get the device implemented.

A.
