### ISSUE TITLE
Tuya Smart air box Link Quality to 255

### ISSUE THREAD

**Issue by tobst96** [ioBroker/ioBroker.zigbee#1140]
The sensor TS0601 air quality sensor is recognized. However, it is a Tuya air quality sensor. The quality reaches 255 there. Manually changing the config to max 255 is overwritten again directly. The spam is now my log full.

Warn:
`State value to set for "zigbee.0.cc86ecfffe5b8066.link_quality" has value "255" greater than max "254"`

Deutsch:
Es wird der Sensor TS0601 air quality sensor erkennt. Allerdings ist es ein Luftqualitätssensor von Tuya. Die Qualität erreicht da 255. Manuelles ändern der Config auf max 255 wird direkt wieder überschrieben. Das Spamt nun mein Protokoll voll.

**Comment by asgothian** [comment]
The error is fixed in the latest adapter version.
