### ISSUE TITLE
zigbee Probleme

### ISSUE THREAD

**Issue by JogiBarbarski** [ioBroker/ioBroker.zigbee#1142]
System Raspberry Pi 4, 8GB
ioBroker.admin 5.1.9
Node.js: v12.22.1
NPM: 6.14.6
js-controller
JS controller Installiert: 3.3.14
OS: linux
Problem mit Zigbee Adapter zigbee 1.5.6
ERROR: Process exited with code 22
weniger

mehr
$ iobroker upgrade zigbee@1.5.6
No connection to databases possible ...
ERROR: Process exited with code [22]

**Comment by asgothian** [comment]
?

**Comment by JogiBarbarski** [comment]
habe ein Adapter Update auf 1.5.6 versucht . Danach ging nichts mehr. CC26X2R1 nicht mehr erreichbar. Dann Adapter gelöscht und er ließ sich nicht mehr installieren . Backup wieder herstellen war auch nicht von Erfolg gekrönt .

**Comment by JogiBarbarski** [comment]
> habe ein Adapter Update auf 1.5.6 versucht . Danach ging nichts mehr. CC26X2R1 nicht mehr erreichbar. Dann Adapter gelöscht und er ließ sich nicht mehr installieren . Backup wieder herstellen war auch nicht von Erfolg gekrönt .

Befehl ausführen ERROR: Prozess mit Code 29 beendet weniger mehr $ iobroker upgrade zigbee@1.5.0@undefined Update zigbee von @1.5.6 auf @1.5.0 host.raspberrypi Adapter "system.adapter.zigbee.0" wird gestoppt.  NPM-Version: 6.14.6 npm install iobroker.zigbee@1.5.0 --loglevel error --prefix "/opt/iobroker" (Systemaufruf) Kann io-package.json in /opt/iobroker/node_modules/iobroker.zigbee nicht finden  lopt/iobroker/node_modules/iobroker.zigbee/io-package.json kann nicht geparst werden:SyntaxError: lopt/iobroker/node_modules/iobroker.zigbee/io-package.json: Unerwartetes Token } in JSON an Position 167 Kann io-Paket nicht finden.  json in /opt/iobroker/node_modules/iobroker.zigbee Adapter "zigbee" aktualisiert host.raspberrypi Adapter "system.adapter.zigbee.0" wird gestartet Datei zigbee.svg kann nicht geschrieben werden: Verbindung wird geschlossen.  Datei zigbee.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei words.js kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei vis-network.min.js kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei vis-network.min.css kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei tab_m.html kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei shuffle.min.js kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei moment.min.js kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei index_m.html kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei index.html kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/zemismart_sw2.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/zbt_smart_switch.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/zbt_remote.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/zbt_led_panel.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/zbt_e27_rgbw.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/zbt_e27.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/xiaomi_wireless_switch.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/xiaomi_plug_eu.png kann nicht geschrieben werden: Verbindung ist geschlossen.  Datei img/wemo.png kann nicht geschrieben werden: Verbindung ist geschlossen.  FEHLER: Vorgang mit Code 29 beendet Schließen wenn fertig A IM HINTERGRUND X SCHLIESSEN

**Comment by asgothian** [comment]
This issue is not zigbee related. There is an issue with your filesystem and/or network connection.

As a side note - posting those walls of text without any formatting is stupid. Please use the code tags (<>) or other formatting to make them more reasonable.

A.
