### ISSUE TITLE
Proposal: to exclude package-lock.json from the code tree

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.zigbee#1143]
Hi.

Is it possible?
It bring additional problem fro the PR  creation, when I do local 
```
npm install
npm test
```
Is it really needed to share `package-lock.json` via git, as it updated every such turn?

**Comment by kirovilya** [comment]
it was used earlier when travis-ci was used. now everything is launched through github-action and I don't know if it is needed for this or not ...

**Comment by Apollon77** [comment]
Having package-lock in repo mainly makes sens if you want to have Dependabot seeing and updating all deps and sub-deps. If you leave it out then dependabot will concentrate onkly on direct deps if you want that he is doing that

**Comment by PeterVoronov** [comment]
> it was used earlier when travis-ci was used. now everything is launched through github-action and I don't know if it is needed for this or not ...

It's really needed for the `npm ci`. I checked it ;-)
But, after reading the documentation, I found an alternative - `npm-shrinkwrap.json` 
It's simple generated - by `npm shrinkwrap`.
`npm ci` is excellent work with it - [see log of my action](https://github.com/PeterVoronov/ioBroker.zigbee/actions/runs/993059673)
And it is not changed by `npm install` when I doing any local test and checks.

Can I propose appropriate PR?
Or can somebody test my branch - to clone it an made 'npm install` and check the code after by `git diff --word-diff` ?

Looks like work as a charm ;-)

**Comment by Apollon77** [comment]
Yes, if you remove package-lock you need to adjust "npm ci" to "npm install" ... in fact "The same but install needs longer" and npm ci make sure that all deps are exactly as specified in the package-lock and not "dynamically resolved differently by npm install"

**Comment by PeterVoronov** [comment]
> Yes, if you remove package-lock you need to adjust "npm ci" to "npm install" ... in fact "The same but install needs longer" and npm ci make sure that all deps are exactly as specified in the package-lock and not "dynamically resolved differently by npm install"

Or, as I propose - to generate `npm-shrinkwrap.json`. It's not updated by `npm install`, and simplifying the PR preparation.
Or, for PR test we have to use `npm ci` instead `npm install`
