### ISSUE TITLE
BlitzWolf BW-SHP15 smartplugs with power and voltage monitoring

### ISSUE THREAD

**Issue by elzershark** [ioBroker/ioBroker.zigbee#1144]
https://github.com/Koenkk/zigbee2mqtt/issues/7860?fbclid=IwAR0go0vIm3JdrURJyKSqwLguZeYlUI9nMkSTw-z-7iGb8GnNcwq57jsEKJU

Die integration wäre nice.

**Comment by asgothian** [comment]
These will automagically be supported **if** the implementation in the zigbee-herdman-converters correctly exposes the states.

A.
