### ISSUE TITLE
Heiman Combustible Gas Sensor HS1CG-E

### ISSUE THREAD

**Issue by sir0drake** [ioBroker/ioBroker.zigbee#1146]
Hello,
I bought one from Heiman Gas Sensor - HS1CG-E. Unfortunately, the GAS Detected trigger is not set to True when the test switch on the device is triggered. 

**Can I somehow help** (logs etc) to map this functionality in iobroker?

The device itself is implemented in the adapter.
the node "GAS" is also available but it does not change to True.
I assume that he will not do it in an emergency Situation either.

brgds

**Comment by asgothian** [comment]
Please add the IEEE Address of the sensor to the state zigbee.0.info.debugmessages (without the leading 0x) and check if any warn messages appear with the text ELEVATED in it, Especially when the test switch is fired.

A.

**Comment by sir0drake** [comment]
Hello,
as requested here the log-warn when test-button is pressed:
brgds

zigbee.0 | 2021-07-07 18:29:04.120 | warn | (3566) ELEVATED publishToState: value generated 'false' from device 000d6f00161f7495 for 'Is tampered'
-- | -- | -- | --
zigbee.0 | 2021-07-07 18:29:04.120 | warn | (3566) ELEVATED publishToState: value generated 'false' from device 000d6f00161f7495 for 'Battery Status Low'
zigbee.0 | 2021-07-07 18:29:04.119 | warn | (3566) ELEVATED publishToState: value generated 'false' from device 000d6f00161f7495 for 'Indicates whether the device detected gas'
zigbee.0 | 2021-07-07 18:29:04.118 | warn | (3566) ELEVATED publishToState: message received '{"gas":false,"tamper":false,"battery_low":false}' from device 000d6f00161f7495 type 'HS1CG-E'
zigbee.0 | 2021-07-07 18:29:04.116 | warn | (3566) ELEVATED publishToState: value generated '18' from device 000d6f00161f7495 for 'Link quality'
zigbee.0 | 2021-07-07 18:29:04.115 | warn | (3566) ELEVATED publishToState: message received '{"linkquality":18}' from device 000d6f00161f7495 type 'HS1CG-E'
zigbee.0 | 2021-07-07 18:29:02.722 | warn | (3566) ELEVATED publishToState: value generated 'false' from device 000d6f00161f7495 for 'Is tampered'
zigbee.0 | 2021-07-07 18:29:02.721 | warn | (3566) ELEVATED publishToState: value generated 'false' from device 000d6f00161f7495 for 'Battery Status Low'
zigbee.0 | 2021-07-07 18:29:02.721 | warn | (3566) ELEVATED publishToState: value generated 'false' from device 000d6f00161f7495 for 'Indicates whether the device detected gas'
zigbee.0 | 2021-07-07 18:29:02.720 | warn | (3566) ELEVATED publishToState: message received '{"gas":false,"tamper":false,"battery_low":false}' from device 000d6f00161f7495 type 'HS1CG-E'
zigbee.0 | 2021-07-07 18:29:02.717 | warn | (3566) ELEVATED publishToState: value generated '7' from device 000d6f00161f7495 for 'Link quality'
zigbee.0 | 2021-07-07 18:29:02.716 | warn | (3566) ELEVATED publishToState: message received '{"linkquality":7}' from device 000d6f00161f7495 type 'HS1CG-E'

**Comment by asgothian** [comment]
The log shows that the device does send gas detected status, so it can be assumed that it will change it when a gas leak is detected. Check the message 

`message received '{"gas":false,"tamper":false,"battery_low":false}' from device 000d6f00161f7495 type 'HS1CG-E'`

You can see if that message changes when you press the test button. If it doesn't, it is the device not sending the alarm via zigbee.

A.
