### ISSUE TITLE
Device disconnected after Node Update

### ISSUE THREAD

**Issue by nostrom0o** [ioBroker/ioBroker.zigbee#1147]
Hello,

I have updated Node to version 12 and then to version 14.17.2, since then Zigbee no longer works correctly. The adapter starts but no devices are found. What can I do?

![2021-07-06 22_33_28-Window](https://user-images.githubusercontent.com/87041362/124663608-9d4fee80-deaa-11eb-8fd8-bfca8180e6a1.png)

```
zigbee.0 | 2021-07-06 22:09:59.900 | info | (3269) Zigbee started
-- | -- | -- | --
zigbee.0 | 2021-07-06 22:09:59.899 | info | (3269) Currently no devices.
zigbee.0 | 2021-07-06 22:09:59.892 | info | (3269)   --> transmitPower : normal
zigbee.0 | 2021-07-06 22:09:59.887 | info | (3269) Disable LED
zigbee.0 | 2021-07-06 22:09:59.881 | info | (3269) Coordinator firmware version:  {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20180507}}
zigbee.0 | 2021-07-06 22:09:57.884 | info | (3269) Installed Version: ioBroker/ioBroker.zigbee#master
zigbee.0 | 2021-07-06 22:09:57.563 | info | (3269) Starting Zigbee  npm ...
zigbee.0 | 2021-07-06 22:09:57.447 | info | (3269) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.17.2, js-controller: 3.2.16
host.Pi4-iobroker | 2021-07-06 22:09:54.498 | info | instance system.adapter.zigbee.0 started with pid 3269
host.Pi4-iobroker | 2021-07-06 22:09:52.301 | info | instance system.adapter.zigbee.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
zigbee.0 | 2021-07-06 22:09:51.665 | info | (2264) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.0 | 2021-07-06 22:09:51.664 | info | (2264) terminating
zigbee.0 | 2021-07-06 22:09:51.423 | info | (2264) Zigbee: disabling joining new devices.
zigbee.0 | 2021-07-06 22:09:51.421 | info | (2264) cleaned everything up...
zigbee.0 | 2021-07-06 22:09:51.417 | info | (2264) Got terminate signal TERMINATE_YOURSELF
host.Pi4-iobroker | 2021-07-06 22:09:51.419 | info | stopInstance system.adapter.zigbee.0 send kill signal
```

Edit: changed code tags to multiline code. (A)

**Comment by asgothian** [comment]
- Please describe the steps you took to update node.
- Please check the folder /opt/iobroker/iobroker-data/zigbee_0 for files and print what is here

A.

**Comment by nostrom0o** [comment]
Hey asgothian,

- I have used the following guide:
https://forum.iobroker.net/topic/44566/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten-2021-edition/2
- many backups (do with backitup):
![image](https://user-images.githubusercontent.com/87041362/124810880-1fe7b500-df62-11eb-9132-4c8c2cf5b555.png)

**Comment by asgothian** [comment]
Please check the content of your shepherd.db. It should contain all your devices. If it does not, check the backup tgz files for one which does.

Also - when posting text from a console, please post it as text, never as image.

A.

**Comment by nostrom0o** [comment]
The shepherd.db file was not empty but I replaced it with a backup. Now all devices are displayed again. But under "Network card" they are still "disconected".
![2021-07-07 21_54_38-GMSG](https://user-images.githubusercontent.com/87041362/124821150-a4d8cb80-df6e-11eb-9bb5-b5ea5d544166.png)

**Comment by asgothian** [comment]
try to trigger the devices to send a message (open a window contact, etc) to see if the state changes.

**Comment by nostrom0o** [comment]
I have already tried but unfortunately does not work

**Comment by asgothian** [comment]
I think you will be better off just opening the network and triggering them again. With 7 devices, you can just extend the timer to 240 seconds and are done in 3 minutes.

**Comment by nostrom0o** [comment]
In pairing mode, it does not find any devices, or what do you mean?

**Comment by asgothian** [comment]
- Activate pairing mode
- trigger the devices to ensure that they send messages
- watch the log if "device announced itself" messages are shown.

**Comment by nostrom0o** [comment]
The pairing mode does not work anymore. 
Can it be that the Zigbee cc2531 stick has shot up during the update? Is there anything I can do to check?


`<html><body>


zigbee.0 | 2021-07-15 21:59:09.455 | info | (22311) Zigbee: stop joining
-- | -- | -- | --
zigbee.0 | 2021-07-15 21:58:08.147 | info | (22311) Zigbee: allowing new devices to join.
zigbee.0 | 2021-07-15 21:57:47.962 | info | (22311) Zigbee started
zigbee.0 | 2021-07-15 21:57:47.961 | info | (22311) 0xbc33acfffe35a9e9 (addr 12739): HG06335 - Lidl Silvercrest smart motion sensor (EndDevice)
zigbee.0 | 2021-07-15 21:57:47.959 | info | (22311) 0x00158d000273584c (addr 33493): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2021-07-15 21:57:47.958 | info | (22311) 0x00158d0002750a14 (addr 13039): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2021-07-15 21:57:47.946 | info | (22311) 0x00158d0004a03552 (addr 34644): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2021-07-15 21:57:47.943 | info | (22311) DeviceConfigure successful 0x00158d00027867a2 lumi.weather
zigbee.0 | 2021-07-15 21:57:47.942 | info | (22311) 0x00158d00047d3a92 (addr 31180): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2021-07-15 21:57:47.940 | info | (22311) Configuring 0x00158d00027867a2 lumi.weather
zigbee.0 | 2021-07-15 21:57:47.939 | info | (22311) 0x00158d00027867a2 (addr 15006): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2021-07-15 21:57:47.935 | info | (22311) DeviceConfigure successful 0x00158d000272cd65 lumi.weather
zigbee.0 | 2021-07-15 21:57:47.933 | info | (22311) 0x00158d000272cd65 (addr 18527): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2021-07-15 21:57:47.926 | info | (22311) Configuring 0x00158d000272cd65 lumi.weather
zigbee.0 | 2021-07-15 21:57:47.885 | info | (22311) Currently 7 devices are joined:
zigbee.0 | 2021-07-15 21:57:47.876 | info | (22311)   --> transmitPower : normal
zigbee.0 | 2021-07-15 21:57:47.870 | info | (22311) Disable LED
zigbee.0 | 2021-07-15 21:57:47.865 | info | (22311) Coordinator firmware version:  {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20180507}}
zigbee.0 | 2021-07-15 21:57:45.872 | info | (22311) Installed Version: iobroker.zigbee@1.5.6
zigbee.0 | 2021-07-15 21:57:45.558 | info | (22311) Starting Zigbee  npm ...
zigbee.0 | 2021-07-15 21:57:45.453 | info | (22311) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.17.2, js-controller: 3.2.16


</body>
</html>`

**Comment by asgothian** [comment]
What makes you think that the pairing mode does not work anymore ?
From the log, the network was open for 90 seconds.

If you want to repair the devices, you may have to reset the device to get it to pairing mode too.

A.
