### ISSUE TITLE
Can not install Zigbee

### ISSUE THREAD

**Issue by Chuckwallas** [ioBroker/ioBroker.zigbee#1151]
Hi, after latest update my adapter turned red. i tried to reinstall it but I can't install it anymore.
It crashes with following error:

![image](https://user-images.githubusercontent.com/62941295/125092627-cef6ce80-e0d1-11eb-8450-43af6c246e30.png)

I have node v14.7.3
nodejs v12.19.0
npm 6.14.13 (edit: i updated to 7.19.1 - but no changes)

Does anyone know this problem?

**Comment by Jensilein** [comment]
Same here. Please help.

**Comment by asgothian** [comment]
- Go back to npm 6.14.x (7.x does NOT work)
- navigate to the folder /opt/iobroker/node-modules and then execute rm -rf iobroker.zigbee 
- before attempting to install the adapter again.

**Comment by Chuckwallas** [comment]
OK, I try after holiday and give feedback :)

**Comment by Jensilein** [comment]
> * Go back to npm 6.14.x (7.x does NOT work)
> * navigate to the folder /opt/iobroker/node-modules and then execute rm -rf iobroker.zigbee
> * before attempting to install the adapter again.

Worked for me. Thanks for your support.

**Comment by Chuckwallas** [comment]
> * Go back to npm 6.14.x (7.x does NOT work)
> * navigate to the folder /opt/iobroker/node-modules and then execute rm -rf iobroker.zigbee
> * before attempting to install the adapter again.

Worked for me as well! Thank you, can be closed!
