### ISSUE TITLE
Wrong link for Tradfri E1603/E1702, E1524/E1810 and LED1537R6/LED1739R5

### ISSUE THREAD

**Issue by luieiob** [ioBroker/ioBroker.zigbee#1158]
Tradfri E1603/E1702
![E1603_E1702](https://user-images.githubusercontent.com/87542227/126037040-37abdab1-f842-4423-aee7-641cec5c2521.jpg)
![E1603_E1702_02](https://user-images.githubusercontent.com/87542227/126037041-2f437d2d-fd36-486b-8593-ea592855edda.jpg)
Wrong link:
https://www.zigbee2mqtt.io/devices/E1603/E1702.html

Right:
https://www.zigbee2mqtt.io/devices/E1603_E1702_E1708.html

Tradfri E1524/E1810
![grafik](https://user-images.githubusercontent.com/87542227/126037208-a6b02e4a-bfb4-4396-80a8-7cb9c3987811.png)
Wrong link:
https://www.zigbee2mqtt.io/devices/E1524/E1810.html

Right:
https://www.zigbee2mqtt.io/devices/E1524_E1810.html

Tradfri LED1537R6/LED1739R5
![LED1537R6LED1739R5](https://user-images.githubusercontent.com/87542227/126037381-f9ede02b-51b9-45f3-9807-f0404a487c7c.jpg)
Wrong link:
https://www.zigbee2mqtt.io/devices/LED1537R6/LED1739R5.html

Right:
https://www.zigbee2mqtt.io/devices/LED1537R6_LED1739R5.html

**Comment by asgothian** [comment]
which adapter are you finding those links in ? These should have been fixed a while ago.

A.

**Comment by luieiob** [comment]
zigbee v1.5.6

**Comment by luieiob** [comment]
Tradfri E1603/E1702
![E1603_E1702_E1708](https://user-images.githubusercontent.com/87542227/134966867-74e7ae7a-1e21-4f9f-a04c-b2556e6b305a.jpg)
![E1603_E1702_E1708_02](https://user-images.githubusercontent.com/87542227/134966908-5643378a-5771-49f3-8b27-c7c0f47b486c.jpg)

Wrong link:
https://www.zigbee2mqtt.io/devices/E1603_E1702/E1708.html

Right:
https://www.zigbee2mqtt.io/devices/E1603_E1702_E1708.html

zigbee v1.6.3

**Comment by kirovilya** [comment]
sorry. try to update from github, now

**Comment by luieiob** [comment]
it's working fine. thank you
