### ISSUE TITLE
All Xiaomi-Devices report warnings

### ISSUE THREAD

**Issue by Diet1976** [ioBroker/ioBroker.zigbee#1160]
Hello,
since a few days my Xiaomi-Sensors report warnings because the link quality is greater than 254.
I'm using the latest Zigbee-Adapter (1.5.6)
Is there anything I can do?

Greets, Dietmar

**Comment by asgothian** [comment]
Warten.

das ganze ist auf GitHub gefixed, kann aber noch nicht ins latest wegen Problemen mit dem Herdsman.

A.
P.s. das ist der 4. Oder 5 issue deswegen. Liest keiner die bestehenden bevor ein neuer aufgemacht wird “

**Comment by Diet1976** [comment]
Hallo und danke für die Antwort.
Hatte diesen Issue dazu gefunden:
https://github.com/ioBroker/ioBroker.zigbee/issues/1126

Leider kommentarlos geclosed, also wusste ich nicht, was damit ist. Stand ich aber laut der Kommentare nicht ganz alleine da...

Schönen Abend,
Dietmar
