### ISSUE TITLE
Button Statt not resetting

### ISSUE THREAD

**Issue by Chrisblueeyes83** [ioBroker/ioBroker.zigbee#1166]
the Aqara Button State "Hold" is always active and does not reset.

**Comment by asgothian** [comment]
More info please:
- which adapter version
- which nodeJS version
- does not reset where (object tree or dashboard)
- exactly which device is affected
- what zigbee hardware is used
- which messages are generated when the Address of the device is entered into the zigbee.x.debugmessages state

**Comment by Chrisblueeyes83** [comment]
which adapter version - _1.5.6_
which nodeJS version - _12.22.2_
does not reset where (object tree or dashboard) - _both_
exactly which device is affected - _Aqara double key wireless wall switch and Aqara single key wireless wall switch_
what zigbee hardware is used - _conbee II Stick_
which messages are generated when the Address of the device is entered into the zigbee.x.debugmessages state - _dont know how to do this_

**Comment by asgothian** [comment]
> which messages are generated when the Address of the device is entered into the zigbee.x.debugmessages state - _dont know how to do this_

- Identify the device in the object tree and copy the device ID (16 digit hex number)
- go to zigbee.x.info.debugmessages and enter the device ID into the state (with multiple ID's they need to be split by ,) Note that x is your adapters instance number
- Check the log for warning messages with the keyword "ELEVATED". Any communication with the device will generate such messages. Any state change from the adapter side should generate one message for the state change and one message for the respective notice that something was sent to the device. Any state change from the device side should likewise generate 2 messages, one for the message received from the device, one for the state change as a result of this message.
A.

**Comment by Chrisblueeyes83** [comment]
there comes no message in the log

**Comment by asgothian** [comment]
Then you did not enter the value correctly. Please share a screenshot from your object tree of one of the devices and what you entered in the debugmessages state.

**Comment by Chrisblueeyes83** [comment]
now i got it. (had to remove 0x before the Number)

<html>
<body>


zigbee.0 | 2021-07-30 20:30:49.976 | warn | ELEVATED publishToState: value generated 'true' from device 00158d000283d192 for 'Hold'
-- | -- | -- | --
zigbee.0 | 2021-07-30 20:30:49.976 | warn | ELEVATED publishToState: message received '{"action":"hold"}' from device 00158d000283d192 type 'WXKG03LM_rev2'
zigbee.0 | 2021-07-30 20:30:49.974 | warn | ELEVATED publishToState: value generated '207' from device 00158d000283d192 for 'Link quality'
zigbee.0 | 2021-07-30 20:30:49.969 | warn | ELEVATED publishToState: message received '{"linkquality":207}' from device 00158d000283d192 type 'WXKG03LM_rev2'


</body>
</html>

**Comment by DocGame69** [comment]
Ist bei meinen "WXKG02LM" und "WXKG03LM" auch der fall. Ist mir nur nicht aufgefallen, da bei denen, die ich am Zigbee-Adapter hängen habe kein Hold im Script ist. Andere dieser Schalter, bei denen ich hold verwende hängen an Xiaomi Hubs. Da geht alles.
Am Zigbee-Adapter habe ich jede Menge Opple (1,2 und 3-fach) hängen bei denen ich auch hold abfrage. Bei diesen geht es.
Ob dieses Verhalten sich erst seit einem Update eingeschlichen hat weiß ich nicht. Bevor ich vor einem Jahr die Opples angeschaft habe ging der Hold auf jeden Fall bei den Aqaras.
