### ISSUE TITLE
Firmware Update

### ISSUE THREAD

**Issue by tobst96** [ioBroker/ioBroker.zigbee#1167]
v 1.5.6

zigbee.0 | 23101 | 2021-07-31 15:34:35.774 | info | Failed to check if update available for '0x00178801021be3f3' (Device didn't respond to OTA request)
-- | -- | -- | -- | --
zigbee.0 | 23101 | 2021-07-31 15:34:35.772 | info | Failed to check if update available for '0x847127fffeb3ab98' (Device didn't respond to OTA request)
zigbee.0 | 23101 | 2021-07-31 15:34:35.770 | info | Failed to check if update available for '0x000b57fffec0196b' (Device didn't respond to OTA request)
zigbee.0 | 23101 | 2021-07-31 15:34:35.759 | info | Failed to check if update available for '0x842e14fffe4b7e49' (Device didn't respond to OTA request)
zigbee.0 | 23101 | 2021-07-31 15:34:35.757 | info | Failed to check if update available for '0x0017880102c1b93c' (Device didn't respond to OTA request)
zigbee.0 | 23101 | 2021-07-31 15:34:35.743 | info | Failed to check if update available for '0x0017880102c1ba23' (Device didn't respond to OTA request)
zigbee.0 | 23101 | 2021-07-31 15:34:35.735 | info | Failed to check if update available for '0x60a423fffecef04a' (Device didn't respond to OTA request)
zigbee.0 | 23101 | 2021-07-31 15:34:35.730 | info | Failed to check if update available for '0x842e14fffe88819c' (Device didn't respond to OTA request)
zigbee.0 | 23101 | 2021-07-31 15:34:35.709 | info | Failed to check if update available for '0x847127fffe25f6df' (Device didn't respond to OTA request)
zigbee.0 | 23101 | 2021-07-31 15:34:29.836 | error | Update of '0x5c0272fffe58f47b' failed (Image is truncated: not long enough to contain a valid tag)
zigbee.0 | 23101 | 2021-07-31 15:34:28.730 | error | Update of '0x60a423fffee3ac9a' failed (Image is truncated: not long enough to contain a valid tag)
zigbee.0 | 23101 | 2021-07-31 15:34:26.931 | info | Start firmware update for 0x5c0272fffe58f47b
zigbee.0 | 23101 | 2021-07-31 15:34:25.722 | info | Start firmware update for 0x60a423fffee3ac9a
zigbee.0 | 23101 | 2021-07-31 15:34:18.987 | error | Update of '0x5c0272fffe6c57e5' failed (Image is truncated: not long enough to contain a valid tag)
zigbee.0 | 23101 | 2021-07-31 15:34:18.198 | info | Start firmware update for 0x5c0272fffe6c57e5
zigbee.0 | 23101 | 2021-07-31 15:33:48.837 | info | Zigbee started

**Comment by asgothian** [comment]
?

**Comment by asgothian** [comment]
@tobst96 

It seems my response wasn't clear enough. So in more detail
- What is the issue you are reporting ?
- What do you expect to happen ?
- What kind of device(s) is/are affected ?

A.

**Comment by asgothian** [comment]
Closed due to lack of information
