### ISSUE TITLE
MOES Scene Switch 4button 

### ISSUE THREAD

**Issue by chrineuh** [ioBroker/ioBroker.zigbee#1168]
Hello, 

I have bougth an Scenen Remote Controller like the Oapple from Aquara but mine are form MOES. 

The problem is i dont get the sates for dubble and hold for the buttons : 

![image](https://user-images.githubusercontent.com/60777681/128363231-e6383542-1457-4d37-bb3a-08adcacc5a76.png)

I only have this sates. 

under the link you can see the buttons i have: 
https://de.aliexpress.com/item/1005001490468150.html?spm=a2g0o.detail.1000014.2.37d04da8Eu02RE&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.33416.213724.0&scm_id=1007.33416.213724.0&scm-url=1007.33416.213724.0&pvid=f7559ad0-90fc-4f28-a5ee-d38158c737a9&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.33416.213724.0,pvid:f7559ad0-90fc-4f28-a5ee-d38158c737a9,tpp_buckets:668%230%23131923%2322_668%23888%233325%239_23416%230%23213724%230_23416%236336%2330489%235_23416%234721%2321967%23870_23416%234722%2321972%233_668%232846%238107%231934_668%235811%2327174%2320_668%236421%2330830%23817_668%232717%237563%23519_668%231000022185%231000066059%230_668%233422%2315392%23113_4452%230%23226710%230_4452%233474%2316498%23787_4452%234862%2324463%23161_4452%233098%239624%23984_4452%235108%2323442%23133_4452%233564%2316062%23799&pdp_ext_f=%7B%22scene%22:%2223416%22%7D

in the produkt informatin you can see that te device have the dubbl press and hold feature. 

Please help 

![image](https://user-images.githubusercontent.com/60777681/128363571-fd609370-b216-4d3f-beec-daff73d62cea.png)

**Comment by chrineuh** [comment]
And now there is anoter Problem with this thing. 

now all aqura switches will be switch on an off by the scene button without any configuration in iobroker. 

Also if i stop the zigbee adater it looks like that the swiches have an bind on the divice. 

I have done an repair with the sceen button but the same fault.

**Comment by asgothian** [comment]
Please do the following:

- enter the Address of the device into the `zigbee.1.info.debugmessages` state. The address is the 16 digit hex number naming the device in the state tree. (i.e. zigbee.1.**abcdeffedcba1234** => Address is abcdeffedcba1234
- perform all desired actions on the device, recording the order in which you perform these actions.
- record the result of each action 
- check the log for warning messages with the keyword "ELEVATED". You should find 2 entries for each action, one listing the incoming message from the device ,one listing the action the iobroker.zigbee adapter takes based on that message.
- Post the results here. Please note:
-- Post the complete log (not a screenshot, not copying text from the admin window
-- Post the log in "complete" code tags (the <> button) by first pasting the log in, then selecting all messages and hitting said button.

A.

p.s. 

> And now there is anoter Problem with this thing.

Welcome to TuYa Zigbee ;)

**Comment by chrineuh** [comment]
Button 1 : 


zigbee.1 | 2021-08-08 10:51:39.232 | warn | State value to set for "zigbee.1.60a423fffed5d0ab.link_quality" has value "255" greater than max "254"
-- | -- | -- | --
zigbee.1 | 2021-08-08 10:51:39.224 | warn | ELEVATED publishToState: value generated 'true' from device 60a423fffed5d0ab for 'on'
zigbee.1 | 2021-08-08 10:51:39.224 | warn | ELEVATED publishToState: message received '{"action":"on"}' from device 60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:51:39.223 | warn | ELEVATED publishToState: value generated '255' from device 60a423fffed5d0ab for 'Link quality'
zigbee.1 | 2021-08-08 10:51:39.223 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 60a423fffed5d0ab type 'TS004F'

Button 2 : 

zigbee.1 | 2021-08-08 10:55:49.011 | warn | State value to set for "zigbee.1.60a423fffed5d0ab.link_quality" has value "255" greater than max "254"
-- | -- | -- | --
zigbee.1 | 2021-08-08 10:55:49.004 | warn | ELEVATED publishToState: value generated 'true' from device 60a423fffed5d0ab for 'on'
zigbee.1 | 2021-08-08 10:55:49.004 | warn | ELEVATED publishToState: message received '{"action":"on"}' from device 60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:55:49.002 | warn | ELEVATED publishToState: value generated '255' from device 60a423fffed5d0ab for 'Link quality'
zigbee.1 | 2021-08-08 10:55:49.002 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 60a423fffed5d0ab type 'TS004F'

Button 3 : 

zigbee.1 | 2021-08-08 10:56:22.181 | warn | State value to set for "zigbee.1.60a423fffed5d0ab.link_quality" has value "255" greater than max "254"
-- | -- | -- | --
zigbee.1 | 2021-08-08 10:56:22.166 | warn | ELEVATED publishToState: value generated 'true' from device 60a423fffed5d0ab for 'brightness_step_down'
zigbee.1 | 2021-08-08 10:56:22.166 | warn | ELEVATED  publishToState: message received  '{"action":"brightness_step_down","action_step_size":51,"action_transition_time":0.1}'  from device 60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:56:22.164 | warn | ELEVATED publishToState: value generated '255' from device 60a423fffed5d0ab for 'Link quality'
zigbee.1 | 2021-08-08 10:56:22.164 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 60a423fffed5d0ab type 'TS004F'

Button 3 long press : 


zigbee.1 | 2021-08-08 10:57:05.412 | warn | State value to set for "zigbee.1.60a423fffed5d0ab.link_quality" has value "255" greater than max "254"
-- | -- | -- | --
zigbee.1 | 2021-08-08 10:57:05.405 | warn | ELEVATED publishToState: value generated 'true' from device 60a423fffed5d0ab for 'brightness_stop'
zigbee.1 | 2021-08-08 10:57:05.405 | warn | ELEVATED publishToState: message received '{"action":"brightness_stop"}' from device 60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:57:05.404 | warn | ELEVATED publishToState: value generated '255' from device 60a423fffed5d0ab for 'Link quality'
zigbee.1 | 2021-08-08 10:57:05.403 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:57:04.417 | warn | State value to set for "zigbee.1.60a423fffed5d0ab.link_quality" has value "255" greater than max "254"
zigbee.1 | 2021-08-08 10:57:04.393 | warn | ELEVATED publishToState: value generated 'true' from device 60a423fffed5d0ab for 'brightness_move_down'
zigbee.1 | 2021-08-08 10:57:04.393 | warn | ELEVATED  publishToState: message received  '{"action":"brightness_move_down","action_rate":51}' from device  60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:57:04.390 | warn | ELEVATED publishToState: value generated '255' from device 60a423fffed5d0ab for 'Link quality'
zigbee.1 | 2021-08-08 10:57:04.389 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 60a423fffed5d0ab type 'TS004F'

Button 4  : 


zigbee.1 | 2021-08-08 10:57:32.269 | warn | State value to set for "zigbee.1.60a423fffed5d0ab.link_quality" has value "255" greater than max "254"
-- | -- | -- | --
zigbee.1 | 2021-08-08 10:57:32.264 | warn | ELEVATED publishToState: value generated 'true' from device 60a423fffed5d0ab for 'brightness_step_up'
zigbee.1 | 2021-08-08 10:57:32.263 | warn | ELEVATED  publishToState: message received  '{"action":"brightness_step_up","action_step_size":51,"action_transition_time":0.1}'  from device 60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:57:32.262 | warn | ELEVATED publishToState: value generated '255' from device 60a423fffed5d0ab for 'Link quality'
zigbee.1 | 2021-08-08 10:57:32.262 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 60a423fffed5d0ab type 'TS004F'


Button 4 long press : 

zigbee.1 | 2021-08-08 10:57:52.346 | warn | State value to set for "zigbee.1.60a423fffed5d0ab.link_quality" has value "255" greater than max "254"
-- | -- | -- | --
zigbee.1 | 2021-08-08 10:57:52.339 | warn | ELEVATED publishToState: value generated 'true' from device 60a423fffed5d0ab for 'brightness_stop'
zigbee.1 | 2021-08-08 10:57:52.339 | warn | ELEVATED publishToState: message received '{"action":"brightness_stop"}' from device 60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:57:52.337 | warn | ELEVATED publishToState: value generated '255' from device 60a423fffed5d0ab for 'Link quality'
zigbee.1 | 2021-08-08 10:57:52.336 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:57:51.454 | warn | State value to set for "zigbee.1.60a423fffed5d0ab.link_quality" has value "255" greater than max "254"
zigbee.1 | 2021-08-08 10:57:51.449 | warn | ELEVATED publishToState: value generated 'true' from device 60a423fffed5d0ab for 'brightness_move_up'
zigbee.1 | 2021-08-08 10:57:51.449 | warn | ELEVATED  publishToState: message received  '{"action":"brightness_move_up","action_rate":51}' from device  60a423fffed5d0ab type 'TS004F'
zigbee.1 | 2021-08-08 10:57:51.448 | warn | ELEVATED publishToState: value generated '255' from device 60a423fffed5d0ab for 'Link quality'
zigbee.1 | 2021-08-08 10:57:51.447 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 60a423fffed5d0ab type 'TS004F'


If I make an double press it comes no message. 

and what can I do for the problem that the device with the button 1 switches all aqura in wall switsches on and with the button 2 off? 
without any script behind. 

Thanks

**Comment by asgothian** [comment]
Bad news. Most of what needs fixing is in the zigbee-herdsman-converters. It does not generate the correct messages for what you need.

A.

**Comment by chrineuh** [comment]
Oke and what can i do now to get it run?

**Comment by kirovilya** [comment]
Tuya-devices have never supported binding with other devices, so you shouldn't used on it. just by writing the action handlers
