### ISSUE TITLE
Missing Settings Button

### ISSUE THREAD

**Issue by Shadesh** [ioBroker/ioBroker.zigbee#1171]
After updating to latest zigbee from GitHub, running the new admin v5 interface, there seems to be no settings button on the zigbee instance. Attached a screenshot of the current instance in German language. Do I miss something here or is it really vanished?

<img width="1280" alt="zigbee" src="https://user-images.githubusercontent.com/8633307/128597316-237b1e12-191e-4b5e-8092-8e9ea39eb5a5.png">

**Comment by kirovilya** [comment]
you are looking for settings on the page that opens in the tab - there is not even a "save" button. go to the adapter settings - everything is there
