### ISSUE TITLE
after update no picture on the card

### ISSUE THREAD

**Issue by luieiob** [ioBroker/ioBroker.zigbee#1174]
after an update to version 1.5.7 no picture is shown on the card

v 1.5.6
![E1603_E1702](https://user-images.githubusercontent.com/87542227/128719412-756185ab-160d-4840-bb14-233ff13815d7.jpg)

v 1.5.7
![E1603_E1702_03](https://user-images.githubusercontent.com/87542227/128719433-003d7064-b058-4474-a2b1-89eda6b38810.jpg)

I also deleted the device and re-paired it

**Comment by kirovilya** [comment]
try to update from github now

**Comment by luieiob** [comment]
fixed
thanks for your great job
