### ISSUE TITLE
State value to set for "zigbee.0.00158d00067xxxxx.no_motion" has to be type "number" but received type "string" 

### ISSUE THREAD

**Issue by StefCGN** [ioBroker/ioBroker.zigbee#1175]
This was the error in 1.5.6 already and now it continuous in version 1.6.

It is a Xiaomi Motion sensor.

Please fix this.

Thank you!

**Comment by asgothian** [comment]
Did you try to delete the state and restart the adapter ? 

A.

**Comment by StefCGN** [comment]
> Did you try to delete the state and restart the adapter ?
> 
> A.

Sure. I stopped the adapter, updated the adapter, deleted the objects and restarted the adapter.
The objects were recreated but the message is the same.

**Comment by StefCGN** [comment]
Some news here?

**Comment by kirovilya** [comment]
I checked on my sensor - there is no such error. how to repeat it?

**Comment by StefCGN** [comment]
![2021-08-13 15_14_15-logs - ioBroker](https://user-images.githubusercontent.com/58603329/129362468-ce9c7ee1-3be6-4e78-be8c-7b012078ac9a.png)

Here is the error.

**Comment by kirovilya** [comment]
I see this, but how can I repeat this error with me? do you have any value in occupancy_timeout state? does it happen at what moment? when the sensor is triggered or after?

**Comment by StefCGN** [comment]
As you can see in the Log, this is happening every 10 minutes without any motion.

**Comment by arteck** [comment]
fixed

**Comment by StefCGN** [comment]
Fixed means? How can i get rid of that?
Thanks!
