### ISSUE TITLE
Where is the configuration stored?

### ISSUE THREAD

**Issue by stephan1827** [ioBroker/ioBroker.zigbee#1176]
I am trying to restore the settings from a previous configuration but I cant find the place where all the settings for the adapter are stored. Can somebody point me to the correct folder and file?

**Comment by Apollon77** [comment]
normally thre is a zigbee instance directory in /opt/iobroker/iobroker-data/ where the files are in

**Comment by stephan1827** [comment]
Thx for the quick reply, I restored the file shepherd.db but it does not seem to affect the data on the settings page. When change data in iobroker this files changes but it does not seem to hold the information like device string. Is that stored somewhere else?

Stephan
