### ISSUE TITLE
Warn-Meldung

### ISSUE THREAD

**Issue by Kusi-Schweiz** [ioBroker/ioBroker.zigbee#1179]
Seit dem Update des Admin-Adapter auf Version 5.x zeigt es mir 2 Warn-Meldung an:

State value to set for "zigbee.0.bc33acfffe28ba60.link_quality" has value "255" greater than max "254"

Dabei handelt es sich um folgendes Gerät:
![image](https://user-images.githubusercontent.com/71840093/129474094-364ddb98-35cd-449d-90ee-ea3d9d78eb34.png)

State value to set for "zigbee.0.00158d00047b8ebd.link_quality" has value "255" greater than max "254"

Dabei handelt es sich um folgendes Gerät:
![image](https://user-images.githubusercontent.com/71840093/129474142-1d7ad9da-44cd-4d72-b925-78846e7b3646.png)

Ändere ich in den Objektdaten den max-Wert auf 255, dann wechselt sich der Wert automatisch nach einer gewissen Zeit wieder auf 254.

**Comment by Kusi-Schweiz** [comment]
Soeben gesehen, dass auch die Tür-/Fenstersensoren dieselbe Warnmeldung anzeigen:

![image](https://user-images.githubusercontent.com/71840093/129474294-bb8783f4-680a-4f1f-a7ec-d306ac82dfdd.png)

**Comment by kirovilya** [comment]
use the latest adapter version - 1.6.0
delete the link_quality state - it will recreate it with the correct settings

**Comment by Kusi-Schweiz** [comment]
I see only the version 1.5.6

**Comment by kirovilya** [comment]
switch to beta repository for update

**Comment by Kusi-Schweiz** [comment]
> Verwenden Sie die neueste Adapterversion - 1.6.0
> löschen Sie den link_quality Status - es wird mit den richtigen Einstellungen neu erstellt

it works, thank you
