### ISSUE TITLE
"not described in statesMapping" for supported device TS011F ?

### ISSUE THREAD

**Issue by bockwurstimtopf** [ioBroker/ioBroker.zigbee#1180]
https://www.zigbee2mqtt.io/devices/TS011F_plug.html

Error: Device 0x84fd27fffedaf937 "TS011F" not described in statesMapping.. undefined
New device joined '0x84fd27fffedaf937' model TS011F
Interview successful: [object Object]
Interview started: 0x84fd27fffedaf937

![image](https://user-images.githubusercontent.com/75392292/129934190-139a2bfc-92b3-436a-af5c-eb27c6ce8dd8.png)

What am I doing wrong?

**Comment by asgothian** [comment]
You most likely got a “new tuya variant”. 

A.

**Comment by Schmetterfliege** [comment]
![image](https://user-images.githubusercontent.com/76066402/146234682-524edf77-ffdc-425e-9c62-00d668162691.png)
Same issue :( Just today I received my 10 SHP-15 -.-

@asgothian anything info I can provide that will help solve this issue?
![image](https://user-images.githubusercontent.com/76066402/146234889-d13db20b-63ef-468f-8a16-c0c172aad4a0.png)
![image](https://user-images.githubusercontent.com/76066402/146235003-3f7cf823-4b35-41aa-aadb-2c7077c7e6fd.png)
![image](https://user-images.githubusercontent.com/76066402/146235051-3a950508-7dd3-4f13-af07-a46b94260268.png)
![image](https://user-images.githubusercontent.com/76066402/146235600-36142e55-419f-4ef4-8878-bd54783c0f0e.png)

**Comment by bockwurstimtopf** [comment]
After the last update of the iob ZigBee adapter TS011F is recognized properly.

**Comment by Schmetterfliege** [comment]
So you updated from 1.6.6 to 1.6.8? How? My IOB doesn't offer 1.6.8

**Comment by Schmetterfliege** [comment]
I update my adapter to 1.6.9, removed the device and paired it again, but got the same issue:
![image](https://user-images.githubusercontent.com/76066402/146247555-4cc92473-a190-4250-92e4-6e4499b1f335.png)

**Comment by asgothian** [comment]
> I update my adapter to 1.6.9, removed the device and paired it again, but got the same issue:
 You do not have the same TS011F as the original poster. You have a different TuYa Variant.

**Comment by Schmetterfliege** [comment]
> > I update my adapter to 1.6.9, removed the device and paired it again, but got the same issue:
> > You do not have the same TS011F as the original poster. You have a different TuYa Variant.

Oh, okay!
Should I create a new issue for mine? If so, should I create it in this adapter or in the herdsman-converters? (since you added its label)

**Comment by asgothian** [comment]
after Checking the PR/s and changes on zigbee-herdsman-converters: The current zigbee-herdsman-converters support this variant of the plug. If you reinstall the adapter from Github, the plug should be supported.

A.

**Comment by Schmetterfliege** [comment]
@asgothian I updated it from Github, but still the same issue.
 Do I need to uninstall the zigbee adapter first? Is there any way to save all my devices that are already paired?
