### ISSUE TITLE
not working device 9290019758 (SML002) Hue motion outdoor sensor (undefined)

### ISSUE THREAD

**Issue by kamikazemimmi** [ioBroker/ioBroker.zigbee#1183]
Dear all, 
we have had some problems with zigbee but after we use conbee usb stick the devices seems to work stable. 
But the Hue motion outdoor sensor is connected, but we cannot read values. 
We have zigbee adapter 1.5.6 - but installed about the main menu. I am not quite sure, whether it is the same version here ? 
Shall I install zigbee with github as well ? Could this solve my problem ?
in log there is eg :
`2021-08-02 13:23:59.750 - ^[[33mwarn^[[39m: zigbee.0 (8575) Failed to read state '"occupancy_timeout"'of '0x001788010647d97c' after query with '{}' `

Thanks and best regards
Melanie

**Comment by asgothian** [comment]
Hello Melanie,

the fact that the hue motion sensor, does not respond to a read request can have one of 3 causes:
- it is battery driven, and the request comes when it is idle.
- it is not in range of the coordinator (or a router it accepts)
- It is not part of the network.


On its own this message does not allow to distinguish between these cases.

a.

**Comment by kamikazemimmi** [comment]
Thanks for answer. 
So - it seems for me, that the device has connection in general, but it doesn't deliver necessary values. I attached a picture of the object. So in that way, we cannot work with the device. Any ideas how we could get the values ? That's why I asked, whether the device in general works with that version. 

Thanks and best regards

![Unbenannt](https://user-images.githubusercontent.com/78010992/131813015-491616c6-0734-495e-ac1f-5220fa1dda1b.png)

**Comment by a-i-ks** [comment]
@kamikazemimmi Have you been able to solve the problem in the meantime? I have exactly the same problem: Conbee2 stick. Pairing works without problems, but only null values arrive. Link_quality is good.
