### ISSUE TITLE
Farbe ändern von LED-Leuchte

### ISSUE THREAD

**Issue by Kusi-Schweiz** [ioBroker/ioBroker.zigbee#1185]
Seit dem neusten Update auf die Version 1.6.0 lässt sich die Farbe von folgender LED-Leuchte nicht mehr ändern.
![image](https://user-images.githubusercontent.com/71840093/130337208-d2cfd9fc-09ad-420b-8af9-8c22a7ef1cb8.png)

Bis vor dem Update des Adapters konnte ich beim Datenpunkt **zigbee.0.00124b0019c1d4ba.color** die gewünschte Farbe eingeben (blue, green, usw.), dann wurde diese einwandfrei übernommen.
Folgender Fehler erscheint jetzt:
![image](https://user-images.githubusercontent.com/71840093/130337233-dffece48-4d7e-4792-8334-3db7d673f52f.png)

**Comment by asgothian** [comment]
Please do this:
Add the ieee address to “zigbee.0.info.debugmessages
Attempt to change the color
Check the log for warn messages with the keyword “ELEVATED” and post these.

**Comment by Kusi-Schweiz** [comment]
Kannst du mir bitte sagen wo ich diese ieee Adresse finde?

**Comment by asgothian** [comment]
Ja, nur ohne 0x

**Comment by Kusi-Schweiz** [comment]
<html>
<body>


zigbee.0 | 2021-08-23 22:34:56.425 | error | Send command to 0x00124b0019c1d4ba failed with no error code (undefined)
-- | -- | -- | --
zigbee.0 | 2021-08-23 22:34:56.423 | warn | ELEVATED Change state 'color' at device 0x00124b0019c1d4ba type 'YSR-MINI-01_rgbcct'
zigbee.0 | 2021-08-23 22:34:56.378 | warn | ELEVATED: User stateChange zigbee.0.00124b0019c1d4ba.color {"val":"red","ack":false,"ts":1629750896376,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1629750896376}
web.0 | 2021-08-23 22:34:56.375 | warn | Read-only state "zigbee.0.00124b0019c1d4ba.color" has been written without ack-flag with value "red"


</body>
</html>

**Comment by Kusi-Schweiz** [comment]
Folgende Meldungen erhalte ich jetzt alle 5 Minuten im Log:

<html>
<body>


zigbee.0 | 2021-08-24 06:52:03.264 | warn | ELEVATED publishToState: value generated 'false' from device 00124b0019c1d4ba for 'Switch state'
-- | -- | -- | --
zigbee.0 | 2021-08-24 06:52:03.264 | warn | ELEVATED publishToState: message received '{"state":"OFF"}' from device 00124b0019c1d4ba type 'YSR-MINI-01_rgbcct'
zigbee.0 | 2021-08-24 06:52:03.256 | warn | ELEVATED publishToState: value generated '"{\"type\":\"readResponse\",\"data\":{\"onOff\":0},\"linkquality\":191,\"groupID\":null,\"cluster\":\"genOnOff\",\"meta\":{\"zclTransactionSequenceNumber\":26,\"manufacturerCode\":null,\"frameControl\":{\"frameType\":0,\"manufacturerSpecific\":false,\"direction\":1,\"disableDefaultResponse\":true,\"reservedBits\":0}},\"endpoint_id\":11}"' from device 00124b0019c1d4ba for 'Message from Zigbee'
zigbee.0 | 2021-08-24 06:52:03.256 | warn | ELEVATED publishToState: message received '{"msg_from_zigbee":"{\"type\":\"readResponse\",\"data\":{\"onOff\":0},\"linkquality\":191,\"groupID\":null,\"cluster\":\"genOnOff\",\"meta\":{\"zclTransactionSequenceNumber\":26,\"manufacturerCode\":null,\"frameControl\":{\"frameType\":0,\"manufacturerSpecific\":false,\"direction\":1,\"disableDefaultResponse\":true,\"reservedBits\":0}},\"endpoint_id\":11}"}' from device 00124b0019c1d4ba type 'YSR-MINI-01_rgbcct'
zigbee.0 | 2021-08-24 06:52:03.256 | warn | ELEVATED publishToState: value generated '191' from device 00124b0019c1d4ba for 'Link quality'
zigbee.0 | 2021-08-24 06:52:03.256 | warn | ELEVATED publishToState: message received '{"linkquality":191}' from device 00124b0019c1d4ba type 'YSR-MINI-01_rgbcct'


</body>
</html>

**Comment by tabledevil** [comment]
Ich habe das gleiche Problem mit eine IKEA-Lampe.
Seit dem letzten Update scheint das setzen der Farbe überhaupt keine Auswirkung zu haben.

<html><body>


zigbee.0 | 2021-08-24 21:49:27.199 | error | Send command to 0xec1bbdfffec8e7f2 failed with no error code (undefined)
-- | -- | -- | --
zigbee.0 | 2021-08-24 21:49:27.196 | warn | ELEVATED Change state 'color' at device 0xec1bbdfffec8e7f2 type 'LED1924G9'
zigbee.0 | 2021-08-24 21:49:27.191 | warn | ELEVATED:  User stateChange zigbee.0.ec1bbdfffec8e7f2.color  {"val":"ffff00","ack":false,"ts":1629834567189,"q":0,"from":"system.adapter.node-red.0","user":"system.user.admin","lc":1629834567189}
zigbee.0 | 2021-08-24 21:49:25.951 | error | Send command to 0xec1bbdfffec8e7f2 failed with no error code (undefined)
zigbee.0 | 2021-08-24 21:49:25.950 | warn | ELEVATED Change state 'color' at device 0xec1bbdfffec8e7f2 type 'LED1924G9'
zigbee.0 | 2021-08-24 21:49:25.948 | warn | ELEVATED:  User stateChange zigbee.0.ec1bbdfffec8e7f2.color  {"val":"ff00ff","ack":false,"ts":1629834565947,"q":0,"from":"system.adapter.node-red.0","user":"system.user.admin","lc":1629834565947}


</body>
</html>

**Comment by Kusi-Schweiz** [comment]
@asgothian Reichen dir obigen Meldungen, oder brauchst du noch weitere Infos für die Fehlerbehebung? Vielen Dank im Voraus für eure tolle Arbeit...

**Comment by Voodoo2man** [comment]
Habe das gleiche Problem mit Hue Lampen und 1.6.0. bin wieder auf 1.5.6 und habe damit keine Probleme mehr.

**Comment by Kusi-Schweiz** [comment]
> 1.5.6 und habe damit keine Probleme mehr

Kann ich so bestätigen. Mit der Zigbee-Version 1.5.6 funktioniert der Farbwechsel einwandfrei.

**Comment by asgothian** [comment]
Bitte testen:
was passiert wenn ihr die Farbe in der Form #rrggbb sendet (Incl. # wobei rr 2 digit hex für rot, gg 2 digit für Grund, und bb 2 digit hex für blau ist.

A.

**Comment by Kusi-Schweiz** [comment]
> Farbe in der Form #rrggbb sendet

Dann funktioniert der Farbwechsel einwandfrei. Folgende Farben, welche ich getestet habe, funktionieren einwandfrei:

#0000ff für Blau
#ff8800 für Orange
#ff0000 für Rot
#00FF00 für Grün
#FFFFFF für Weiss

**Comment by asgothian** [comment]
This is a second effect caused by the same issue. The #123456 entry is just a workaround which evades one of the effects.
Still - it is good that it works. Now all I need to figure out is who modifies the color state after creation to
- remove the writable flag
- remove the setter

A.

**Comment by Voodoo2man** [comment]
> Bitte testen: was passiert wenn ihr die Farbe in der Form #rrggbb sendet (Incl. # wobei rr 2 digit hex für rot, gg 2 digit für Grund, und bb 2 digit hex für blau ist.
> 
> A.

Ich verwende auch HomeKit. Kommt Homekit über Yahka mit dieser Art der Farbangabe klar.
Wieso wurde die Eingabe von Farben geändert? Jetzt müssen wieder alle Scripts angepasst werden.

**Comment by asgothian** [comment]
Abwarten. Das ist ein bug und soll so nicht bleiben/\.

a.

**Comment by asgothian** [comment]
I have a quick fix available for people who are eager to have the old functions back. Note that this is a beta version which may or may not have additional side effects. I have tested it to the best of my abilities.

To use the fix, please install from here:
(Translation: Es gibt einen Fix für das Farbproblem, er kann vom folgenden Link installiert werden. Installation auf eigene Gefahr - ich habe nach bestem Wissen und Gewissen getestet, kann aber nicht alles testen.)

https://github.com/asgothian/ioBroker.zigbee

@arteck 
@kirovilya 
We have a bigger issue at this point, which is why i am not offering my fix as PR at this time:
- States which are exposed with multiple features (color_xy, color_hs) are sometimes added as single state in ioBroker (color)
- These states do not have their own access definition, access is defined for each feature separately, which is why the states generated were neither readable nor writable. This is what my fix addresses by granting all states full access if the expose itself does NOT have an access property
- Exposed access values are applied to states even if the exposes are not actually used to generate the states with the risk of causing all kinds of interesting effects if the iobroker state definition and the exposed state definition does not match.

We should decide how we want to deal with this.

A.

**Comment by kirovilya** [comment]
@asgothian These are Composite fields, inside them are other fields with separate parameters.
We had a case for them https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/exposes.js#L709
Their peculiarity is that nested fields are sent simultaneously, in one object.  So several of our states should be grouped and sent together.

**Comment by asgothian** [comment]
> Their peculiarity is that nested fields are sent simultaneously, in one object. So several of our states should be grouped and sent together.

Unfortunately, it seems that there are some composite fields which are not handled in this way in the current expose structure.:
The expose color_xy  is translated into the state color which is interpreted as RGB
The expose color_hs  is translated into a large number of states (hue, saturation, hue_move, saturation_move, hue_calibration

Note that i do not want to change how this is done, i am more interested in correcting the way those are handled without changing the state definitions. More important in my eyes is the third item.

I was working off the assumption that exposes were ignored for any device the define explicitly in devices.js. This is not the case. Based on a matching expose access setting, the read and write flag are modified, as well as any given setter or getter functions. In the case of the light, this lead to not only the states being read only, but also the actual intelligence added to the setter being removed.

I have not completed the analysis here, but as far as i see it, the situation should be as follows:
if an expose exists which leads to a state "state1", the access values from that expose will be applied to an existing "state1", even if the function behind it has nothing to do with the expose itself.

A.

**Comment by asgothian** [comment]
> Is this related to this bug? I think so because of @asgothian's [comment](https://github.com/ioBroker/ioBroker.zigbee/issues/1185#issuecomment-932973547).

Yes. You can run a test and install from the github link above to see if this fixes the issue you found as well. It should.

A.

**Comment by agross** [comment]
@asgothian Setting colors works with your version of the adapter.

**Comment by asgothian** [comment]
should be fixed with 1.6.7
