### ISSUE TITLE
Aqara H1 Wall Switch Double Rocker with Neutral - WS-EUK04

### ISSUE THREAD

**Issue by ThomasL1973** [ioBroker/ioBroker.zigbee#1186]
Help needed.

IOBROKER.ZIGBEE reports it as unknown.

Followed Tutorial to add unsupported Devices. It gets recognized. But I am not able to get any events or actions.

https://zigbee.blakadder.com/switches.html says its compatible and working with IOBROKER.

**Comment by kirovilya** [comment]
what version of the adapter are you using? should be 1.6.0

**Comment by ThomasL1973** [comment]
Using 1.5.6. Admin says there is no 1.6

Just discovered the zigbee-herdsmen-converter already has support. So just pulled zigbee-herdsmen-converter from github an it is working as expected.
