### ISSUE TITLE
Warn-Meldung seit Admin v5

### ISSUE THREAD

**Issue by Kusi-Schweiz** [ioBroker/ioBroker.zigbee#1187]
<html>
<body>

zigbee.0 | 2021-08-23 07:16:47.598 | warn | Device '0xbc33acfffe28ba60' announced itself
-- | -- | -- | --

</body>
</html>

Obige Fehlermeldung erscheint am Tag mehrmals und stammt von folgendem Schalter:
![image](https://user-images.githubusercontent.com/71840093/130394497-aa0a63fd-9f3d-40ee-9631-28786b6c4bbd.png)

**Comment by andre1974** [comment]
Das bedeutet nur dass sich der Schalter im Netzwerk gemeldet hat.
Der kann ja nicht aktiv angepingt werden.

Kannst du ignorieren.


Gruß
