### ISSUE TITLE
0x11: BUFFER_FULL

### ISSUE THREAD

**Issue by andre1974** [ioBroker/ioBroker.zigbee#1188]
Hello,

after I have set up the instance again, I often get the following error message

Send command to 4 failed with no error code (SREQ '--> AF - dataRequestExt - {"dstaddrmode":1,"dstaddr":"0x0000000000000004","destendpoint":255,"dstpanid":0,"srcendpoint":1,"clusterid":768,"transid":41,"options":0,"radius":30,"len":7,"data":{"type":"Buffer","data":[17,35,10,114,1,5,0]}}' failed with status '(0x11: BUFFER_FULL)

how can i fix this?

**Comment by asgothian** [comment]
- what hardware are you using ?
- which Adapter Version are you using ?
- how “full” is the 2.4 gHz band at your location ?


A.

**Comment by andre1974** [comment]
Hello.

1. Raspberry Pi 4 with 4GB Ram and a CC2538 + CC2592
2. 1.5.6
3. according to the adapter scan i use channel a channel which is "empty". i live in a house where only three wlan-routers are active.
4. often when i switch something in a group of lamps using a remote control.

hope this helps

**Comment by asgothian** [comment]
> 4\. often when i switch something in a group of lamps using a remote control

Please elaborate.

**Comment by andre1974** [comment]
I switch a group with two lamps using a zigbee remote control.
This applies to brightness, color, color temperature.
When I switch with the remote control, the error often occurs.
The switching processes are then also delayed.

**Comment by asgothian** [comment]
- do you use bindings or scripts to address the lamps ?
- Do you use zigbee groups or direct commands ?
- Is it limited to specific lamps ?
- Please add the iD’s of the lamps in question to zigbee.0.info.debugmessages (separated by a comma) and post the generated warn messages with the keyword “ELEVATED”

**Comment by andre1974** [comment]
1. scripts
2. zigbee groups
3. no, it happens in several groups with different lamps
4. i can only add one lamp to debugmessages... with more than one i get no "elevated" messages

<html><body>


2021-08-24 18:54:39.550  - warn:  zigbee.0 (12903) ELEVATED publishToState: message received  '{"linkquality":63}' from device d0cf5efffe423e2f type  '404000/404005/404012'
--
2021-08-24 18:54:39.550  - warn: zigbee.0 (12903) ELEVATED publishToState: value generated '63' from device d0cf5efffe423e2f for 'Link quality'
2021-08-24 18:54:39.557  - warn:  zigbee.0 (12903) ELEVATED publishToState: message received  '{"state":"OFF"}' from device d0cf5efffe423e2f type  '404000/404005/404012'
2021-08-24 18:54:39.558  - warn: zigbee.0 (12903) ELEVATED publishToState: value generated 'false' from device d0cf5efffe423e2f for 'Switch state'


</body>
</html>

**Comment by asgothian** [comment]
Does the message appear more often when trying to dim up or down using a remote, or is it independent of this ?

a.

**Comment by andre1974** [comment]
It has nothing to do with it.
Even if i use IOT and Alexa to turn the lights on or off it does happen.

If you want i can post the script tomorrow.

**Comment by mremedi2023** [comment]
Same problem here with SLZB-06 adapter
