### ISSUE TITLE
iobroker lost connection with cc2531 after a few minutes

### ISSUE THREAD

**Issue by DaBlubber** [ioBroker/ioBroker.zigbee#1189]
After restarting iobroker and adapter everything work fine and i can the device in zigbee adapter.
After a while the device disconnecting and dont come back.

Proxmox 7.0.11
iobroker 5.1.23
zigbee adapter 1.5.6
TI CC2531 USB CDC
![ZigbeeWorking](https://user-images.githubusercontent.com/89444310/130569429-aa739938-4c23-48a3-bea1-09b6c6ae0101.png)

In eventlog i always got this message.
The log in debug mode can find in attachment
[ZigbeeAdapterError.txt](https://github.com/ioBroker/ioBroker.zigbee/files/7036974/ZigbeeAdapterError.txt)

I also added a screenshot with the view in iobroker when it works.

I have no idea what could cause this problem.

Thank you for help

**Comment by arteck** [comment]
TI cc2541 ????????

**Comment by DaBlubber** [comment]
Thanks for your productiv question.
It was a mistake from my site.
The correct device model is in subject.
TI CC2531 USB CDC

Thanks

**Comment by arteck** [comment]
ahhh.. ok then.. you firmware ist very old its from 20190109
the last is from 20201128 can you check this after reflash ..

**Comment by DaBlubber** [comment]
Thank you. I will flash the stick and recheck this.

Thank you
