### ISSUE TITLE
Can you add the Aquara E27 tunable lightbulb?

### ISSUE THREAD

**Issue by jankir123** [ioBroker/ioBroker.zigbee#119]
Hi, I can pair it, but it shows as unknown device with a question mark. If you need any information from me let me know.
Thanks!
Jan

**Comment by kirovilya** [comment]
@jankir123 Start the adapter in debig mode and record the lamp pairing log.
Then attach the log file here and you can still attach shepherd.db file from iobroker-data/zigbee.0 folder.

**Comment by jankir123** [comment]
Hi, i had to rename the file, can you use that?

[shepherd.txt](https://github.com/ioBroker/ioBroker.zigbee/files/2648319/shepherd.txt)

**Comment by kirovilya** [comment]
@jankir123 yes. lumi.light.aqcn02 - is your lamp :)

**Comment by kirovilya** [comment]
will waiting https://github.com/Koenkk/zigbee2mqtt/issues/621

**Comment by jankir123** [comment]
Hi, it status is now "Bulb is supported in the dev branch. thanks all!" in that other thread, how can I pair it with the adapter?

**Comment by has-sTeaLth** [comment]
Any news on this? Is it possible to manually add it?

**Comment by has-sTeaLth** [comment]
Any Update?
Got it working by adding the following to "zigbee-shepherd-converters/devices.js"
```
    {
        zigbeeModel: ['lumi.light.aqcn02'],
        model: 'ZNLDP12LM',
        vendor: 'Xiaomi',
        description: 'Aqara smart LED bulb',
        supports: generic.light_onoff_brightness_colortemp().supports,
        fromZigbee: generic.light_onoff_brightness_colortemp().fromZigbee,
        toZigbee: generic.light_onoff_brightness_colortemp().toZigbee,
    },
```
and  this to "iobroker.zigbee/lib/devstates.js"
```
        {
        vendor: 'Xiaomi',
        models: ['lumi.light.aqcn02'],
        icon: 'img/sengled.png',
        states: lightStatesWithColortemp,
        linkedStates: [comb.brightnessAndState],
    },
```

**Comment by kirovilya** [comment]
Added in 0.9.0
