### ISSUE TITLE
Unclear Status

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1190]
Hi .. on the one hand it seems the sockes are connected (switch states shown .. and switching works) but on the other hand the signal icon (the icon most right9 .. shows a disconnection. It confuses me .. could somebody explain?

![grafik](https://user-images.githubusercontent.com/4311558/130646850-2409197f-5a20-4d8c-a161-7aca971ef434.png)

**Comment by daniel-lo** [comment]
I assume this is related:
![grafik](https://user-images.githubusercontent.com/4311558/130651363-353a3d1e-b7e7-4b99-a812-1b78d1ab9efa.png)

**Comment by asgothian** [comment]
You assume correctly.

The icon is generated based on a number of factors. Mains powered Devices which do not respond to ping requests and do not send status updates will be set as unavailable.

osram plugs are often affected.

the warning messages show that the devices refuse to respond to ping requests.

A.

**Comment by daniel-lo** [comment]
So maybe the icon is misleading since functionality is not effected. With the look of those icons one would think that something is broken.
