### ISSUE TITLE
Pairing count potentially too short

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1191]
Hi, formerly the count was to 100 .. now it stops at 15 .. which may be a little short. Could this be made configurable?

Currently I am trying to pair an IKEA Tradfri Repeater .. to no avail.

Cheers

**Comment by asgothian** [comment]
The pairing counter is configurable. I have mine set to 5 minutes when I add new devices.

**Comment by daniel-lo** [comment]
Thanks .. but where/how? I cannot find a corresponding field.
