### ISSUE TITLE
serial port error 1.5.6 -> 1.6.0

### ISSUE THREAD

**Issue by vaaarg** [ioBroker/ioBroker.zigbee#1197]
just wanted to know if these entries occured while upgrading can be ignored

type:zStack30x
version:2-2.2.7.2.
revision:20200211
port:/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
channel:15

`
<html>
<body>

zigbee.0 | 2021-08-28 06:44:43.194 | info | (24020) Coordinator firmware version: {"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200211}}
-- | -- | -- | --
zigbee.0 | 2021-08-28 06:44:41.608 | info | (24020) Installed Version: iobroker.zigbee@1.6.0
zigbee.0 | 2021-08-28 06:44:41.125 | info | (24020) Starting Zigbee npm ...
zigbee.0 | 2021-08-28 06:44:41.024 | info | (24020) starting. Version 1.6.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.5, js-controller: 3.3.15

</body>
</html>`

`pio4gb
Plattform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
3.75 GB
System-Betriebszeit
23:43:55
Node.js
v12.22.5
NPM
6.14.14
Datenträgergröße
58.29 GB
freier Festplattenspeicher
54.84 GB
Anzahl der Adapter
438
Betriebszeit
23:43:48
Aktive Instanzen
22
location
/opt/iobroker/
Hostname
pio4gb
`

`
This upgrade of "zigbee" will introduce the following changes:
==========================================================================
-> 1.6.0:
Improvements and new devices
==========================================================================

Would you like to upgrade zigbee from @1.5.6 to @1.6.0 now? [(y)es, (n)o]: y
Update zigbee from @1.5.6 to @1.6.0
host.pio4gb Adapter "system.adapter.zigbee.0" is stopped.
NPM version: 6.14.14
npm install iobroker.zigbee@1.6.0 --loglevel error --prefix "/opt/iobroker" (Sys                                                                                                                                                             tem call)
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_ME                                                                                                                                                             THOD_ARGS_TYPE)’:
../src/serialport.cpp:78:69: warning: cast between incompatible function types f                                                                                                                                                             rom ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {a                                                                                                                                                             ka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOp                                                                                                                                                             en);
                                                                     ^~~~~~~~~~~                                                                                                                                                             ~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_                                                                                                                                                             METHOD_ARGS_TYPE)’:
../src/serialport.cpp:135:71: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_After                                                                                                                                                             Update);
                                                                       ^~~~~~~~~                                                                                                                                                             ~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_M                                                                                                                                                             ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:175:70: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterC                                                                                                                                                             lose);
                                                                      ^~~~~~~~~~                                                                                                                                                             ~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_M                                                                                                                                                             ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:215:70: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterF                                                                                                                                                             lush);
                                                                      ^~~~~~~~~~                                                                                                                                                             ~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_MET                                                                                                                                                             HOD_ARGS_TYPE)’:
../src/serialport.cpp:271:68: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet                                                                                                                                                             );
                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_MET                                                                                                                                                             HOD_ARGS_TYPE)’:
../src/serialport.cpp:316:68: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet                                                                                                                                                             );
                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan:                                                                                                                                                             :NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:366:76: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_                                                                                                                                                             AfterGetBaudRate);
                                                                            ^~~~                                                                                                                                                             ~~~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_M                                                                                                                                                             ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:412:70: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterD                                                                                                                                                             rain);
                                                                      ^~~~~~~~~~                                                                                                                                                             ~~~~
../src/serialport.cpp: At global scope:
../src/serialport.cpp:433:28: warning: unnecessary parentheses in declaration of                                                                                                                                                              ‘ToParityEnum’ [-Wparentheses]
 SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {
                            ^
../src/serialport.cpp:452:30: warning: unnecessary parentheses in declaration of                                                                                                                                                              ‘ToStopBitEnum’ [-Wparentheses]
 SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {
                              ^
In file included from ../../../nan/nan.h:56,
                 from ../src/./serialport.h:13,
                 from ../src/serialport.cpp:1:
/home/iobroker/.cache/node-gyp/12.22.5/include/node/node.h:736:43: warning: cast                                                                                                                                                              between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION                                                                                                                                                             _ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_fu                                                                                                                                                             nc’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast                                                                                                                                                             -function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/iobroker/.cache/node-gyp/12.22.5/include/node/node.h:770:3: note: in expan                                                                                                                                                             sion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/serialport.cpp:486:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(serialport, init);
 ^~~~~~~~~~~
../src/serialport_unix.cpp: In function ‘int setup(int, OpenBaton*)’:
../src/serialport_unix.cpp:176:60: warning: ‘%s’ directive output may be truncat                                                                                                                                                             ed writing up to 1023 bytes into a region of size 1005 [-Wformat-truncation=]
     snprintf(data->errorString, sizeof(data->errorString), "Error %s Cannot ope                                                                                                                                                             n %s", strerror(errno), data->path);
                                                            ^~~~~~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~~
../src/serialport_unix.cpp:176:13: note: ‘snprintf’ output 20 or more bytes (ass                                                                                                                                                             uming 1043) into a destination of size 1024
     snprintf(data->errorString, sizeof(data->errorString), "Error %s Cannot ope                                                                                                                                                             n %s", strerror(errno), data->path);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/serialport_unix.cpp: In function ‘void EIO_Open(uv_work_t*)’:
../src/serialport_unix.cpp:86:60: warning: ‘%s’ directive output may be truncate                                                                                                                                                             d writing up to 1023 bytes into a region of size 1003 [-Wformat-truncation=]
     snprintf(data->errorString, sizeof(data->errorString), "Error: %s, cannot o                                                                                                                                                             pen %s", strerror(errno), data->path);
                                                            ^~~~~~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~~~~
../src/serialport_unix.cpp:86:13: note: ‘snprintf’ output 22 or more bytes (assu                                                                                                                                                             ming 1045) into a destination of size 1024
     snprintf(data->errorString, sizeof(data->errorString), "Error: %s, cannot o                                                                                                                                                             pen %s", strerror(errno), data->path);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_ME                                                                                                                                                             THOD_ARGS_TYPE)’:
../src/serialport.cpp:78:69: warning: cast between incompatible function types f                                                                                                                                                             rom ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {a                                                                                                                                                             ka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOp                                                                                                                                                             en);
                                                                     ^~~~~~~~~~~                                                                                                                                                             ~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_                                                                                                                                                             METHOD_ARGS_TYPE)’:
../src/serialport.cpp:135:71: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_After                                                                                                                                                             Update);
                                                                       ^~~~~~~~~                                                                                                                                                             ~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_M                                                                                                                                                             ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:175:70: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterC                                                                                                                                                             lose);
                                                                      ^~~~~~~~~~                                                                                                                                                             ~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_M                                                                                                                                                             ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:215:70: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterF                                                                                                                                                             lush);
                                                                      ^~~~~~~~~~                                                                                                                                                             ~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_MET                                                                                                                                                             HOD_ARGS_TYPE)’:
../src/serialport.cpp:271:68: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet                                                                                                                                                             );
                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_MET                                                                                                                                                             HOD_ARGS_TYPE)’:
../src/serialport.cpp:316:68: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet                                                                                                                                                             );
                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan:                                                                                                                                                             :NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:366:76: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_                                                                                                                                                             AfterGetBaudRate);
                                                                            ^~~~                                                                                                                                                             ~~~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_M                                                                                                                                                             ETHOD_ARGS_TYPE)’:
../src/serialport.cpp:412:70: warning: cast between incompatible function types                                                                                                                                                              from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {                                                                                                                                                             aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterD                                                                                                                                                             rain);
                                                                      ^~~~~~~~~~                                                                                                                                                             ~~~~
../src/serialport.cpp: At global scope:
../src/serialport.cpp:433:28: warning: unnecessary parentheses in declaration of                                                                                                                                                              ‘ToParityEnum’ [-Wparentheses]
 SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {
                            ^
../src/serialport.cpp:452:30: warning: unnecessary parentheses in declaration of                                                                                                                                                              ‘ToStopBitEnum’ [-Wparentheses]
 SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {
                              ^
In file included from ../../../nan/nan.h:56,
                 from ../src/./serialport.h:13,
                 from ../src/serialport.cpp:1:
/home/iobroker/.cache/node-gyp/12.22.5/include/node/node.h:736:43: warning: cast                                                                                                                                                              between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION                                                                                                                                                             _ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_fu                                                                                                                                                             nc’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast                                                                                                                                                             -function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/iobroker/.cache/node-gyp/12.22.5/include/node/node.h:770:3: note: in expan                                                                                                                                                             sion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/serialport.cpp:486:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(serialport, init);
 ^~~~~~~~~~~
../src/serialport_unix.cpp: In function ‘int setup(int, OpenBaton*)’:
../src/serialport_unix.cpp:176:60: warning: ‘%s’ directive output may be truncat                                                                                                                                                             ed writing up to 1023 bytes into a region of size 1005 [-Wformat-truncation=]
     snprintf(data->errorString, sizeof(data->errorString), "Error %s Cannot ope                                                                                                                                                             n %s", strerror(errno), data->path);
                                                            ^~~~~~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~~
../src/serialport_unix.cpp:176:13: note: ‘snprintf’ output 20 or more bytes (ass                                                                                                                                                             uming 1043) into a destination of size 1024
     snprintf(data->errorString, sizeof(data->errorString), "Error %s Cannot ope                                                                                                                                                             n %s", strerror(errno), data->path);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/serialport_unix.cpp: In function ‘void EIO_Open(uv_work_t*)’:
../src/serialport_unix.cpp:86:60: warning: ‘%s’ directive output may be truncate                                                                                                                                                             d writing up to 1023 bytes into a region of size 1003 [-Wformat-truncation=]
     snprintf(data->errorString, sizeof(data->errorString), "Error: %s, cannot o                                                                                                                                                             pen %s", strerror(errno), data->path);
                                                            ^~~~~~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~~~~
../src/serialport_unix.cpp:86:13: note: ‘snprintf’ output 22 or more bytes (assu                                                                                                                                                             ming 1045) into a destination of size 1024
     snprintf(data->errorString, sizeof(data->errorString), "Error: %s, cannot o                                                                                                                                                             pen %s", strerror(errno), data->path);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Update "system.adapter.zigbee.0"
upload [300] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/vis-network.min.css vis-network.min.css text/css
upload [250] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/s                                                                                                                                                             ensor_ht.png img/sensor_ht.png image/png
upload [200] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/p                                                                                                                                                             aulmann_rgbw_globe.png img/paulmann_rgbw_globe.png image/png
upload [150] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/l                                                                                                                                                             amp_01.png img/lamp_01.png image/png
upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/g                                                                                                                                                             roup_6.png img/group_6.png image/png
upload [90] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/gl                                                                                                                                                             edopto_gu10.png img/gledopto_gu10.png image/png
upload [80] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/fl                                                                                                                                                             air_viyu_e14_candle.png img/flair_viyu_e14_candle.png image/png
upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/di                                                                                                                                                             y.png img/diy.png image/png
upload [60] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/cr                                                                                                                                                             ts0111.PNG img/crts0111.PNG image/png
upload [50] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ba                                                                                                                                                             ttery_v.png img/battery_v.png image/png
upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ZH                                                                                                                                                             S15.png img/ZHS15.png image/png
upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Pa                                                                                                                                                             ulmann_50067.png img/Paulmann_50067.png image/png
upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/HG                                                                                                                                                             06104A.png img/HG06104A.png image/png
upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/FL                                                                                                                                                             OALT.panel.WS.png img/FLOALT.panel.WS.png image/png
upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Eu                                                                                                                                                             rotronic_Spirit_04.png img/Eurotronic_Spirit_04.png image/png
upload [17] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DI                                                                                                                                                             YRuZ_R8_8.png img/DIYRuZ_R8_8.png image/png
upload [16] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DI                                                                                                                                                             YRuZ_Geiger.png img/DIYRuZ_Geiger.png image/png
upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DI                                                                                                                                                             YRuZ_FreePad_LeTV_8.png img/DIYRuZ_FreePad_LeTV_8.png image/png
upload [14] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DI                                                                                                                                                             YRuZ_FreePad.png img/DIYRuZ_FreePad.png image/png
upload [13] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DI                                                                                                                                                             YRuZ_Flower.png img/DIYRuZ_Flower.png image/png
upload [12] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DI                                                                                                                                                             YRuZ_CO2.png img/DIYRuZ_CO2.png image/png
upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DI                                                                                                                                                             YRuZ.png img/DIYRuZ.png image/png
upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DG                                                                                                                                                             NWG05LM.png img/DGNWG05LM.png image/png
upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Bit                                                                                                                                                             ron_AV201021A.png img/Bitron_AV201021A.png image/png
upload [8] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/BW-                                                                                                                                                             IS5.png img/BW-IS5.png image/png
upload [7] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/BW-                                                                                                                                                             IS3.png img/BW-IS3.png image/png
upload [6] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/AV2                                                                                                                                                             010_32.png img/AV2010_32.png image/png
upload [5] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86s                                                                                                                                                             w2.png img/86sw2.png image/png
upload [4] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86s                                                                                                                                                             w1.png img/86sw1.png image/png
upload [3] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86p                                                                                                                                                             lug.png img/86plug.png image/png
upload [2] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/141                                                                                                                                                             47206L.png img/14147206L.png image/png
upload [1] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/admin.j                                                                                                                                                             s admin.js application/javascript
upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/adapter                                                                                                                                                             -settings.js adapter-settings.js application/javascript
Adapter "zigbee" updated
host.pio4gb Adapter "system.adapter.zigbee.0" is started
pi@pio4gb:~ $
`

**Comment by arteck** [comment]
short answer : YES
