### ISSUE TITLE
IKEA Motion Sensors not work

### ISSUE THREAD

**Issue by Peter1980FFM** [ioBroker/ioBroker.zigbee#1198]
IKEA Motion Sensors have Wrong states pleas FIX
![image](https://user-images.githubusercontent.com/45266139/131207568-675e6273-479d-43eb-9014-450cc7c2b32a.png)
![image](https://user-images.githubusercontent.com/45266139/131207673-ea7a7993-d413-46fc-aee2-465426dd8c7d.png)
![image](https://user-images.githubusercontent.com/45266139/131207688-fa8d3dd2-e264-4c85-bd4d-c17668036714.png)
![image](https://user-images.githubusercontent.com/45266139/131207717-ecf52108-4b74-44be-ad11-83662bf032bb.png)

**Comment by asgothian** [comment]
Please elaborate.

What do you think is wrong on said states ?

A.

**Comment by Peter1980FFM** [comment]
Hello,
In the Screenshots you See that Motion and time after Motion ist null so i
dont dan See If There ist a Motion or Not
In logfiles Ar No entrY



asgothian ***@***.***> schrieb am Fr., 3. Sept. 2021, 09:59:

**Comment by Marty56** [comment]
Could be coordinator related. 
Using the Sonoff Zigbee Plus Stick (type:zStack3x,version:2-1.2.7.1.,revision:20210708) I have full functionality

**Comment by gaudes** [comment]
@Marty56 : Can you show the objects written for the Motion Sensor ?

I use a Conbee 2 and see only the following states:

![image](https://user-images.githubusercontent.com/34286177/152677662-386a410c-e003-4a70-bb13-31d8dc97c664.png)

As described here: https://www.zigbee2mqtt.io/devices/E1525_E1745.html there should be some more states.

Some users also report that there is a boolean value "dark" with true and false.

Thanks, Ralf
