### ISSUE TITLE
Problem bei verbindung mit Stick 

### ISSUE THREAD

**Issue by Dome2075** [ioBroker/ioBroker.zigbee#1199]
Hallo,

ich habe meinen IObroker VM auf QNAP neu aufgesetzt und habe jetzt Probleme mit der Verbindung zum CC26xR1 Stick

Ich habe die Recht aufgebohrt und den Comport /dev/ttyACM0 sowie /dev/serial/by-id/..... ausprobiert
immer das gleiche Resultat.

Was mach ich falsch, oder gibt es noch ein Problem vom Adapter?

Danke

Admin 5.1.23
![image](https://user-images.githubusercontent.com/37158961/131212901-b6d88ba5-2e4d-41a0-abef-7bb21ae6d37e.png)
![image](https://user-images.githubusercontent.com/37158961/131212944-f8fdf215-3c90-4ab5-ad89-15edff494d17.png)
![image](https://user-images.githubusercontent.com/37158961/131212981-1a5e3eb0-ab74-4419-9fef-a778c24f22d3.png)

**Comment by Apollon77** [comment]
Diese Meldung bedeutet an sich das der Port von einem anderen prozess belegt ist. Bitte das prüfen. ODer er ist ggf doch nicht zugreifbar für den iobroker user in der VM oder so? "iobroekr fix" versucht?

**Comment by asgothian** [comment]
- Please post logs as text, not screenshots.
- Same with console output.
- Your error is hidden in the last line of the log: `Starting zigbee-herdsam problem: "All table entries need to be the same length"` This indicates that either the shepherd.db or nvbackup.json file from your backup has format errors and prevents the herdsman from starting. For testing purposes, rename both files to see if the Adapter starts. If it does, see if you have older, clean backups for those files. If not, you will need to re-pair all your devices.

A.

**Comment by Dome2075** [comment]
Hallo again,

ich muss mich entschuldigen, da ich bis jetzt verhindert war weiter zu testen.

ich habe das ganze an einem frisch aufgesetztem iobroker in einer VM mit Debian und Ubuntu probiert.
Leider habe ich diesbezüglich keine erfolge gehabt..

muss ich vielleicht noch irgendwelche Treiber installieren?

(BLE.Adapter mit BLE-Stick funktioniert)


Danke

**Comment by asgothian** [comment]
No drivers are needed. Did you run the test I requested, and if so, can you post the Startup log from the zigbee adapter ?

**Comment by Dome2075** [comment]
Hallo,

nach ein paar neuen versuchen immer noch das gleich:
diesmal mit js-controller: 3.3.17

ich verzweifle langsam :(

<html>
<body>


zigbee.4 | 2021-09-11 10:16:18.015 | error | Error herdsman start
-- | -- | -- | --
zigbee.4 | 2021-09-11 10:16:18.014 | error | Failed to start Zigbee
zigbee.4 | 2021-09-11 10:16:18.013 | error | Starting zigbee-herdsman problem : "All table entries need to be the same length"
zigbee.4 | 2021-09-11 10:16:05.397 | info | Installed Version: iobroker.zigbee@1.6.0
zigbee.4 | 2021-09-11 10:16:03.745 | debug | Starting zigbee-herdsman...
zigbee.4 | 2021-09-11 10:16:03.742 | info | Starting Zigbee npm ...
zigbee.4 | 2021-09-11 10:16:03.731 | debug | Using zigbee-herdsman with settings: {"network":{"panID":6754,"channelList":[12],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"extenedPanID":[22,100,103,20,102,84,22,101]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_4/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_4/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"},"adapter":{"forceStartWithInconsistentAdapterConfiguration":false}}
zigbee.4 | 2021-09-11 10:16:03.627 | info | starting. Version 1.6.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.5, js-controller: 3.3.17
zigbee.4 | 2021-09-11 10:16:02.917 | debug | Plugin sentry Initialize Plugin (enabled=true)
host.iobroker | 2021-09-11 10:15:56.326 | info | instance system.adapter.zigbee.4 started with pid 1414
host.iobroker | 2021-09-11 10:15:54.320 | info | instance system.adapter.zigbee.4 terminated with code null ()
host.iobroker | 2021-09-11 10:15:54.319 | warn | instance system.adapter.zigbee.4 terminated due to SIGTERM
host.iobroker | 2021-09-11 10:15:54.273 | info | stopInstance system.adapter.zigbee.4 killing pid 1407
host.iobroker | 2021-09-11 10:15:53.265 | info | stopInstance system.adapter.zigbee.4 send kill signal
host.iobroker | 2021-09-11 10:15:53.214 | info | stopInstance system.adapter.zigbee.4 (force=false, process=true)
host.iobroker | 2021-09-11 10:15:52.709 | info | instance system.adapter.zigbee.4 started with pid 1407
host.iobroker | 2021-09-11 10:15:50.781 | info | instance system.adapter.zigbee.4 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.iobroker | 2021-09-11 10:15:50.677 | info | stopInstance system.adapter.zigbee.4 killing pid 1389
zigbee.4 | 2021-09-11 10:15:50.105 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.4 | 2021-09-11 10:15:50.102 | info | terminating
zigbee.4 | 2021-09-11 10:15:50.100 | warn | Failed to stop zigbee during startup
zigbee.4 | 2021-09-11 10:15:49.674 | info | Zigbee: disabling joining new devices.
zigbee.4 | 2021-09-11 10:15:49.642 | info | cleaned everything up...
host.iobroker | 2021-09-11 10:15:49.662 | info | stopInstance system.adapter.zigbee.4 send kill signal
zigbee.4 | 2021-09-11 10:15:49.625 | info | Got terminate signal TERMINATE_YOURSELF
host.iobroker | 2021-09-11 10:15:49.592 | info | stopInstance system.adapter.zigbee.4 (force=false, process=true)


</body>
</html>

![image](https://user-images.githubusercontent.com/37158961/132941448-b97f851c-2c15-4867-88a9-891bc9ad7b3f.png)

**Comment by asgothian** [comment]
Did you ensure that the two files i mentioned above were not present ?

If no - please remove the files, run the adapter again and post the log of that startup - and please in proper code tags not as HTML inset.

If yes it would indicate that there is an error in your coordinator firmware, or even a damaged coordinator. Please attempt to flash the stick with a new firmware (can be the same that is on there)

A.
