### ISSUE TITLE
CC2652P Adapter not reachable any more

### ISSUE THREAD

**Issue by mhl66** [ioBroker/ioBroker.zigbee#1200]
Adapter: EBYTE E72 2G4M20S1E (CC2652P) (newest Firmware, of course...)

Version 1.5.6 works with the known issues (IKEA STYRBAR etc. etc.), but 1.6.1 does not any more:

> zigbee.0 | 2021-08-28 19:18:04.939 | error | Error herdsman start
> -- | -- | -- | --
> zigbee.0 | 2021-08-28 19:18:04.938 | error | Failed to start Zigbee
> zigbee.0 | 2021-08-28 19:18:04.938 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
> zigbee.0 | 2021-08-28 19:18:04.724 | info | Installed Version: ioBroker/ioBroker.zigbee#master
> zigbee.0 | 2021-08-28 19:18:04.696 | info | Starting Zigbee npm ...
> zigbee.0 | 2021-08-28 19:18:04.694 | info | Try to reconnect. 1 attempts left
> zigbee.0 | 2021-08-28 19:17:54.691 | error | Error herdsman start
> zigbee.0 | 2021-08-28 19:17:54.691 | error | Failed to start Zigbee
> zigbee.0 | 2021-08-28 19:17:54.690 | error | Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"

Please HELP!

**Comment by Apollon77** [comment]
Try to restart the system and check that the device is there in /dev/tty... can not lock port norally means that an other process already uses it

**Comment by mhl66** [comment]
Thanks, but I did this. Port is /dev/ttyUSB0. 
Alternative Zigbee adapter "CONBEE II" is working perfectly (but is only rudimentarily supported ("experimental support"). Thus, the serial ports are working.

**Comment by Apollon77** [comment]
And conbe is clearly ended when you start iobroker zigbee process?  Try also "iobroker fix"

**Comment by mhl66** [comment]
No, CONBEE (deconz) is running, but has another PAN and another serial port. But I tried the CC... adapter alone, too (without success).

**Comment by mhl66** [comment]
That there is an error in 1.6.1 is evident, since the log shows: often those entries:

host.raspberrypi | 2021-08-29 14:37:01.989 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.raspberrypi | 2021-08-29 14:37:01.989 | error | Caught by controller[1]: at processTimers (internal/timers.js:497:7)
host.raspberrypi | 2021-08-29 14:37:01.989 | error | Caught by controller[1]: at listOnTimeout (internal/timers.js:554:17)
host.raspberrypi | 2021-08-29 14:37:01.988 | error | Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
host.raspberrypi | 2021-08-29 14:37:01.988 | error | Caught by controller[1]: Error: SRSP - SYS - osalNvRead after 0,2ms
host.raspberrypi | 2021-08-29 14:37:01.987 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2021-08-29 14:37:01.409 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-08-29 14:37:01.408 | info | terminating

**Comment by 1N4148** [comment]
Got something similar in an older version (was discussed here). Solution was to start the adapter with a different extended pan id and pan id. After sucessful start of the adapter the values can be reverted to the original values to get the network back.

**Comment by mhl66** [comment]
No, did this (i.e. ExtPAN = DDDDDDDDDDDD1234, PanID = 0x0001, switched back afterwards) does not help at all.

**Comment by mhl66** [comment]
Many reinstalls later...New Raspi, new OS (DietPi / Debian 11), firmware current: MANY warnings on adapter install with 1.6.1, and everytime similar errors when starting the adapter:

host.DietPi | 2021-09-01 00:43:25.331 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.DietPi | 2021-09-01 00:43:25.330 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.DietPi | 2021-09-01 00:43:25.329 | error | Caught by controller[1]: at processTimers (internal/timers.js:497:7)
host.DietPi | 2021-09-01 00:43:25.329 | error | Caught by controller[1]: at listOnTimeout (internal/timers.js:554:17)
host.DietPi | 2021-09-01 00:43:25.328 | error | Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
host.DietPi | 2021-09-01 00:43:25.328 | error | Caught by controller[1]: Error: SRSP - SYS - osalNvRead after 0,2ms
host.DietPi | 2021-09-01 00:43:25.327 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2021-09-01 00:43:24.738 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-09-01 00:43:24.735 | info | terminating
zigbee.0 | 2021-09-01 00:43:24.235 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2021-09-01 00:43:24.233 | info | cleaned everything up...
zigbee.0 | 2021-09-01 00:43:24.221 | error | SRSP - SYS - osalNvRead after 0,2ms
zigbee.0 | 2021-09-01 00:43:24.221 | error | Error: SRSP - SYS - osalNvRead after 0,2ms at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7)
zigbee.0 | 2021-09-01 00:43:24.214 | error | unhandled promise rejection: SRSP - SYS - osalNvRead after 0,2ms
zigbee.0 | 2021-09-01 00:43:24.214 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-09-01 00:43:24.210 | info | Zigbee started
zigbee.0 | 2021-09-01 00:43:24.208 | info | Currently no devices.
zigbee.0 | 2021-09-01 00:43:24.144 | info | --> transmitPower : high
zigbee.0 | 2021-09-01 00:43:24.013 | info | Unable to disable LED, unsupported function.
zigbee.0 | 2021-09-01 00:43:24.001 | info | Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210319}}
zigbee.0 | 2021-09-01 00:43:22.160 | info | Installed Version: ioBroker/ioBroker.zigbee#master
zigbee.0 | 2021-09-01 00:43:21.722 | info | Starting Zigbee npm ...
zigbee.0 | 2021-09-01 00:43:21.598 | info | starting. Version 1.6.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.6, js-controller: 3.3.15
host.DietPi | 2021-09-01 00:43:18.829 | info | instance system.adapter.zigbee.0 started with pid 13846

**Comment by 1N4148** [comment]
This happend also with an empty/fresh/new zigbee database?  A symptom of my fault was, that the adapter didn't come up with the current config/database but could be started with a fresh config/new database.

**Comment by mhl66** [comment]
Yes, thus I wrote "New Raspi, new OS (DietPi / Debian 11)" (see above): exactly the same errors!

**Comment by 1N4148** [comment]
Ok I thought so but I didn't know if you have restored a backup after fresh installation.

**Comment by Z18Aplha** [comment]
Same errors here.
adapter Version 1.6.0 and 1.6.1 
Zigbee Board: CC2652R

i use a docker container to run iobroker, but this should not be the problem. A zigbee2mqtt docker container runs perfect without any problems.

**Comment by Dome2075** [comment]
Same Problem.
Zigbee Board: CC2652R

<html>
<body>


zigbee.0 | 2021-12-06 20:18:02.360 | error | Error herdsman start
-- | -- | -- | --
zigbee.0 | 2021-12-06 20:18:02.359 | error | Failed to start Zigbee
zigbee.0 | 2021-12-06 20:18:02.359 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2021-12-06 20:18:02.036 | info | Installed Version: iobroker.zigbee@1.6.8
zigbee.0 | 2021-12-06 20:18:02.012 | info | Starting Zigbee npm ...
zigbee.0 | 2021-12-06 20:18:02.011 | info | Try to reconnect. 1 attempts left
zigbee.0 | 2021-12-06 20:17:52.007 | error | Error herdsman start
zigbee.0 | 2021-12-06 20:17:52.007 | error | Failed to start Zigbee
zigbee.0 | 2021-12-06 20:17:52.006 | error | Starting zigbee-herdsman problem : "All table entries need to be the same length"
zigbee.0 | 2021-12-06 20:17:44.988 | info | Installed Version: iobroker.zigbee@1.6.8
zigbee.0 | 2021-12-06 20:17:44.432 | info | Starting Zigbee npm ...
zigbee.0 | 2021-12-06 20:17:44.325 | info | starting. Version 1.6.8 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.18.2, js-controller: 3.3.21
host.IOBroker | 2021-12-06 20:17:41.255 | info | instance system.adapter.zigbee.0 started with pid 337
host.IOBroker | 2021-12-06 20:17:39.250 | info | instance system.adapter.zigbee.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)


</body>
</html>

**Comment by asgothian** [comment]
Note that this is not the same issue as the original posters issue. 

It seems that there is an issue with either the firmware on the stick, the nvram backup or the shepherd.db. Please test:

- stop the zigbee adapter
- remove the files shepherd.db and nvbackup.json from /opt/iobroker/iobroker-data/zigbee_0 (do keep a copy so you can restore them afterwards or you may have to pair all devices again.)
- change the zigbee channel and/or the pan ID (keep note of the old settings so you can restore them)
- start the adapter
- check if this message reappears: `error | Starting zigbee-herdsman problem : "All table entries need to be the same length"`


If it does, chances are one or more entries from the following list are correct
- your firmware is defunct - the board needs to be flashed with new firmware
- your USB connection is defunct - use a different USB cable, connect to a different USB port (not USB3), disconnect USB3 devices if possible

If the adapter does start, please
- stop the adapter
- restore the original settings (channel, pan ID, ...)
- restore the shepherd.db file. 
- do **not** restore the nvbackup.json file
- start the adapter

If the adapter runs, you are done. If it does not, the shepherd.db file may be defect - please try to restore an older shepherd.db from the backups present in the folder and repeat the test.

A.

**Comment by wjaschenkov** [comment]
I have the same problem.
Zigbee hardware: sonoff zigbee 3.0 usb dongle plus. It is tested on the two different boards(raspberry, odroid) and with two firmware(CC1352P2_CC2652P_launchpad_coordinator_20210708.zip, CC1352P2_CC2652P_launchpad_coordinator_20211114.zip)

**Comment by asgothian** [comment]
> I have the same problem.

You have the same problem only in so far as (in an analogy from another field) your car won't start.


In your case, the stick does not respond to communication from the adapter, i.e. either the stick, the USB connection or the firmware are broken.

Please ensure that
- the Stick not plugged into a USB3 port
- no USB3 Harddrives / SSD are in use when attempting to contact the stick

If the problem remains despite these conditions the stick / firmware are likely not functional.

A.

**Comment by wjaschenkov** [comment]
Thanks for the tips.
None of the boards have USB3. Also when connecting the stick is detected by the kernel. I have had the cc2531 stick on the board for years with no problem. After trying the CC2652P stick without success, I wanted to go back to the cc2531. I had to uninstall and reinstall the adapter, otherwise I had the same error messages with the cc2531 stick even after rebooting the board.

I am thankful for every help.

**Comment by Dome2075** [comment]
Hi,

i solved problem by reflashing the CC26xx.

importent is this option:
![image](https://user-images.githubusercontent.com/37158961/146973653-6c78e2e8-241a-4059-b5e2-85c0eb65d7d3.png)

**Comment by wjaschenkov** [comment]
I have solved my problem. So far I used only "Flash Programmer 2" for the firmware update. These attempts were all successful, but the stick did not work. When I tried Uniflash, the firmware for the debugger boards was also updated. Now the stick works. Thanks for the tips.
