### ISSUE TITLE
Tuya TS0601 radiator valve update issue

### ISSUE THREAD

**Issue by rassel2000** [ioBroker/ioBroker.zigbee#1201]
Hi, I can't update the firmware of my Tuya radiator valve. The adapter doesnt even search for an update, it immediately shows the error "Failed to check if update available for "XXXX" (No image available for imageType '5634").
(I have removed the device ID, just to be sure)

Model: TS0601_thermostat
Adapter version: 1.6.0
JS-controller: 3.2.16
Node: 12.22.4

I have also tried updating the device with the adapter version 1.5.6 but got the same error message.

What could be the problem?
Thanks

**Comment by asgothian** [comment]
The problem is that the TuYa Server does not offer an upgrade image for the type of radiator valve you have.

A.
