### ISSUE TITLE
1.6.1: multiple errors (warnings) during install

### ISSUE THREAD

**Issue by mhl66** [ioBroker/ioBroker.zigbee#1202]
Many of these (could it be that 1.6.1 is not yet mature):

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen); ^~~~~~~~~~~~~../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE

This is presumably an indication for the root cause of this: https://github.com/ioBroker/ioBroker.zigbee/issues/1200

**Comment by Apollon77** [comment]
No thats just normal serialport warning stuff deending on your nodejs version
