### ISSUE TITLE
When mesh is drawn and when not?

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1204]
I wonder .. why is the mesh sometimes visible and sometimes not. The adapter has been running over a day now .. and I still don't see a mesh (only circled device symbols)  .. would just like to understand.

**Comment by asgothian** [comment]
Interesting question. Did you keep your browser on the network page for the network map to be fully generated ? 

Also - More info on Questions like this will aid a lot in actually getting an answer which helps.

**Comment by daniel-lo** [comment]
been like that for days now:

![grafik](https://user-images.githubusercontent.com/4311558/131993955-c39bf915-8b3d-43b0-9ed0-c9dac03835d1.png)

The devices do show activity now and then

**Comment by daniel-lo** [comment]
@asgothian 

Thank you .. I probably had wrong expectations. I remember times where the mesh was immediately visibile .. but I cannot recall if I was on the page longer or not. Now you seem to have to wait on that page until the mesh builds up (as you said above).

"disconnected" for un-pingable is confusing .. since the devices do their job. And I wonder why the names change once the mesh is in place (above my custom names .. below the device names).

![grafik](https://user-images.githubusercontent.com/4311558/132163567-5011d39e-3a58-4737-9007-b0a3884e2e03.png)
