### ISSUE TITLE
Zigbee Adapter läuft nur mit default Einstellungen mit CC1352P-2 Adapter 

### ISSUE THREAD

**Issue by Mistaluna** [ioBroker/ioBroker.zigbee#1205]
Hallo,

ich habe heute den CC1352P-2 an meinen iobroker angeschlossen und den Zigbee Adapter in der Version 1.5.6 direkt über iobroker installiert. Die Zigbee Instanz habe ich in den Einstellungen so konfiguriert wie ich es in einem Youtube Tutorial gesehen habe. Also COM-Anschluss eingetragen, sowie Erweiterte PAN ID, Pan ID und Transportschlüssel geändert. Alles andere auf default.

Direkt danach ist die Zigbee Instanz rot geblieben und zwar bei allen drei Statusmeldungen. Iobroker und raspberry neuzustarten hat nichts geändert. Ich habe dann die Zigbee Instanz gelöscht und neu installiert. Dann habe ich in den Instanzeinstellungen nur dem COM-Anschluss eingetragen und ansonsten alles auf default gelassen. So funktioniert die Instanz sofort. Dann habe ich Erweiterte PAN ID und Transportschlüssel wieder geändert, wodurch die Instanz wieder nicht korrekt gestartet ist. Diesmal waren jedoch Verbunden mit Host und Lebenszeichen grün. Verbunden mit Gerät und Dienst blieb jedoch rot. Im Log habe ich dann folgende Fehlermeldung:

```
zigbee.0 | 2021-09-02 14:54:48.343 | error | Error herdsman start
-- | -- | -- | --
zigbee.0 | 2021-09-02 14:54:48.343 | error | Failed to start Zigbee
zigbee.0 | 2021-09-02 14:54:48.341 | error | Starting  zigbee-herdsman problem : "Error while opening serialport 'Error: Error  Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2021-09-02 14:54:48.137 | info | Installed Version: iobroker.zigbee@1.5.6
zigbee.0 | 2021-09-02 14:54:48.117 | info | Starting Zigbee  npm ...
zigbee.0 | 2021-09-02 14:54:48.116 | info | Try to reconnect. 1 attempts left
zigbee.0 | 2021-09-02 14:54:38.115 | error | Error herdsman start
zigbee.0 | 2021-09-02 14:54:38.115 | error | Failed to start Zigbee
zigbee.0 | 2021-09-02 14:54:38.114 | error | Starting zigbee-herdsman problem : "startup failed - configuration-adapter mismatch - see logs above for more information"
zigbee.0 | 2021-09-02 14:54:38.113 | error | Re-commissioning your network will require re-pairing of all devices!
zigbee.0 | 2021-09-02 14:54:38.113 | error | If  you wish to re-commission your network, please remove coordinator  backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.
zigbee.0 | 2021-09-02 14:54:38.112 | error | Please update configuration to prevent further issues.

```

Ich habe dann probehalber Erweiterte PAN ID, Pan ID und Transportschlüssel jeweils getrennt von einander zu ändern, wodurch die Instanz wieder nicht korrekt startet.

Auf den CC1352P-2 habe ich mit Uniflash folgende Firmware geflasht:
Flash-Datei und Quelle: CC1352P2_CC2652P_launchpad_coordinator_20210708.zip

Hat jemand eine Idee wo das Problem ist und wie ich Erweiterte PAN ID und Transportschlüssel ändern kann?

Mod-Edit: Code tags. Dann kann man das auch lesen.

**Comment by Mistaluna** [comment]
Version v1.6.0o hat mein Problem gelöst.

**Comment by asgothian** [comment]
Nur um hier noch einmal klar zu machen was Ursache des Problems war:

- Der Adapter wurde mit den Standard-Einstellungen gestartet, und hat damit ein entsprechendes Backup der Konfiguration des Zigbee Netzes abgelegt (nvbackup.json)
- Nach dem Anpassen der Einstellungen hat die Zigbee Bibliothek davor gewarnt das die Parameter geändert wurden und nicht mehr zu dem abgelegten Backup passen:

`Starting zigbee-herdsman problem : "startup failed - configuration-adapter mismatch - see logs above for more information"`

In der Folge wurde im Log sogar darauf hin gewiesen was zu tun ist wenn diese Anpassung beabsichtigt war:
```
zigbee.0 | 2021-09-02 14:54:38.113 | error | Re-commissioning your network will require re-pairing of all devices!
zigbee.0 | 2021-09-02 14:54:38.113 | error | If  you wish to re-commission your network, please remove coordinator  backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.

```

Letztendlich hätte bei genau der hier beschriebenen Konstellation ein Löschen der nvbackup.json Datei das gewünschte Ergebnis erzeugt.

A.
