### ISSUE TITLE
Heiman HS2WD-E - Strobe only

### ISSUE THREAD

**Issue by Streit187** [ioBroker/ioBroker.zigbee#1206]
Hi, 
the device is integrated and states are visible. 
Siren: Execute warning (input: duration in sec) is written but on every number siren is on and does not turn off. input 0 is off. 
Strobe: nearly the same. Every number turns on the light for 1 or 2 seconds without flashing and turns of. 
BR

**Comment by asgothian** [comment]
This is an issue for the zigbee implementation at zigbee-herdsman-converters. The iobroker only exposes the states generated by that project. There is no internal functionality for this device.

**Comment by Streit187** [comment]
Since last adapter update the flah is not working anymore

**Comment by asgothian** [comment]
> Since last adapter update the flah is not working anymore

This is also an issue for the [Zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters/issues) project. No changes were made to the ioBroker.Zigbee side.

**Comment by olix74** [comment]
@Streit187 if you are able to use Javascript the following may help/ be at least a workaround. The following command will turn on the siren only. See my comments below for other modes:
```
sendTo("zigbee.0", "sendToZigbee", { 
    "id": 'ccccccfffedc1bfc', 
    "ep": "1", 
    "cid": "ssIasWd", 
    "cmd": "startWarning", 
    "cmdType": "functional", 
    "zclData": {
        "startwarninginfo": 4,
        "warningduration": 4,
        "strobedutycycle":100,
        "strobelevel": 4
    } 
});
```
For setting the values please the zigbee spec https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf in chapter 8.4.2.3.1.1. As such startwarninginfo as a on byte entry with 3 entries:
4 bit warning mode (all modes sound same on this device)
2 bit strobe (on and off)
2 bit siren level (seems not to be used with this device)
as such startwarninginfo 
"4" means strobe only --> warning mode =0 --> no siren --> strobe=1 --> strobe on --> siren level=0
"16" means siren  only--> warning moder=1 --> siren --> strobe = 0 --> no strobe --> siren level = 0 
"20" means sirean and strobe 

other fields mean:
warningduration in seconds
Duty cylce should be between 0 and 100 in steps of 10, duty cycle 0 will turn off strobe, 100 will make a constant light
strobelevel between 0 to 3, but does not seem to have an impact at this device
 
Best regards,
Oliver

**Comment by olix74** [comment]
sorry, "strobelevel" should be "3" in above example
