### ISSUE TITLE
BW-SHP15 shows no watt at low load

### ISSUE THREAD

**Issue by andre1974** [ioBroker/ioBroker.zigbee#1207]
Hello,

i integrated the Blitzwolf plug successfully but at low load it does not show me any watt usage.

![05-09-_2021_19-58-48](https://user-images.githubusercontent.com/11474126/132136779-e5046f10-c674-44da-9fae-df94deb607da.jpg)

At this picture is a load of 9 watt. But nothing shows up.

I am on adapter version 1.61 on a Raspberry Pi 4.

**Comment by arteck** [comment]
10 watt is min...
