### ISSUE TITLE
Silvercrest Garden Plug is not correct recognized

### ISSUE THREAD

**Issue by BigDi** [ioBroker/ioBroker.zigbee#1208]
Bought this device
[Silvercrest Garden Plug](https://zigbeealliance.org/de/zigbee_products/garden-spike-with-2-sockets-smart-home-4/) 
and it is recognized as TuYa TS0101
Switching is not working.

**Comment by arteck** [comment]
also not in exclude tab ?

**Comment by BigDi** [comment]
what do you mean with "exclute tab"?

**Comment by asgothian** [comment]
> Bought this device
> [Silvercrest Garden Plug](https://www.lidl.de/p/silvercrest-gartenspiess-mit-2-steckdosen-zigbee-smart-home/p100329849)
> and it is recognized as TuYa TS0101
> Switching is not working.

- Is the plug listed as Supported at https://www.zigbee2mqtt.io/information/supported_devices.html ?

If it is not then additional work is in the zigbee herdsman converters project is required to correctly identify this additional variant of a TuYa TS0101 object.

A.

**Comment by BigDi** [comment]
I have no idea how to get the information I need from the device. I set up a clean environment (new Zigbee2MQTT) and create a Tuya converter. It looks like it's working because the device list shows the entries that I created. But I don't get the debug.txt file. What I have done wrong?

**Comment by asgothian** [comment]
Which debug.txt file ? Shouldn't you get a data/tuya.dump.txt file ?

Which documentation did you follow for the tuya test implementation ?

**Comment by BigDi** [comment]
I used this guide
https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html#instructions
But I didn't get the data/tuya.dump.txt. But I also read that there is a fixed bug. I also create a bug at zigbee2mqtt. I changed and edited "everything" and I got a strange situation that I get updated from the plug, eg. I press the button and I got the updated state but I can set the state...

**Comment by asgothian** [comment]
The same reason may be behind this issue:

the TuYa dummy connector will only generate data for messages which are sent with connection to the manufacturerSpecificTuYa Cluster. It seems that the plug operates on the more standard genOnOff cluster, rather than the manufacturer specific one. Can you check the information display on the paired plug to see which clusters are listed as input and output clusters ?

**Comment by BigDi** [comment]
Hope this screenshot will helps
![grafik](https://user-images.githubusercontent.com/11903065/143212242-53a14930-72a8-4a3a-8cec-637342ad3133.png)

**Comment by asgothian** [comment]
Try to modify the tuya.js file by copying this device and changing the definitions to match yours

   ```
 {
        fingerprint: [{modelID: 'TS011F', manufacturerName: '_TZ3000_1hwjutgo'}, {modelID: 'TS011F', manufacturerName: '_TZ3000_lnggrqqi'}],
        model: 'TS011F_circuit_breaker',
        vendor: 'TuYa',
        description: 'Circuit breaker',
        extend: extend.switch(),
        whiteLabel: [{vendor: 'Mumubiz', model: 'ZJSB9-80Z'}],
    },

```

It might work for control, not sure it will generate additional data.

A.

**Comment by BigDi** [comment]
@asgothian Many thanks! I added the lines to lidl.js in the devices at node_modules/zigbee-herdsman-converters/devices.
The icon is wrong, but I can switch the plug now!

	{
     fingerprint: [{modelID: 'TS0101', manufacturerName: '_TZ3000_br3laukf'}, 
	 {modelID: 'TS0101', manufacturerName: '_TZ3000_br3laukf'}],
     model: 'TS011F_circuit_breaker',
     vendor: 'Lidl',
     description: 'Garden Spike with 2 sockets Smart Home',
     extend: extend.switch(),
     whiteLabel: [{vendor: 'Lidl', model: 'HG06620'}],
 }

**Comment by asgothian** [comment]
Please post this to the zigbee-herdsman-converters project and - if you can - generate a pull request so that other users may benefit from this as well.

Also, you might want to change the model ID to better match what this model actually is. This will break the image, but will allow for the zigbee-herdsman-converters people to add a proper image.

A.
