### ISSUE TITLE
Blitzwolf BW-IS9 water leak sensor working?

### ISSUE THREAD

**Issue by consoleman** [ioBroker/ioBroker.zigbee#1212]
Hi...
Can anyone confirm this device working with this adapter?

**Comment by asgothian** [comment]
- Is the sensor listed under https://www.zigbee2mqtt.io/information/supported_devices.html ?
- does the listing contain proper exposes ?

If the answer is yes to both, it should work fine.

That said - i cannot confirm that it works as i do not have it.

A.
