### ISSUE TITLE
Develco ZHEMI101

### ISSUE THREAD

**Issue by Lassebroker** [ioBroker/ioBroker.zigbee#1214]
Hi,

is it possible to add "Develco ZHEMI101"? As far as I can see, it is already supported by zigbee2mqtt [https://www.zigbee2mqtt.io/devices/ZHEMI101.html](url). How can I help?

Thx, Lasse

**Comment by asgothian** [comment]
If you run the current GitHub version of the adapter, the develco device should be supported. There may be detail adjustments required these won't show up until this test is made.

A.

**Comment by Lassebroker** [comment]
> current GitHub version

Oh, Mist, ich brauch die 1.4.1 wegen der zigbee-herdsman Problematik. Muss ich dann nächste Woche mal in meinem Test-System ausprobieren. Und die PIN-Nr. von den Stadtwerken brauche ich auch noch. Wenn das alles läuft, geb ich wieder Feedback...

**Comment by daniel-finger** [comment]
Works perfectly with the current version from github incl. setting the pulse rate
