### ISSUE TITLE
Conbee II + Ikea Tradfri Button

### ISSUE THREAD

**Issue by ruvnax** [ioBroker/ioBroker.zigbee#1215]
I have added my conbee 2 stick to the IObroker to get rid of Deconz. I have noticed the Stick ist working better and all sensors working fine even my routers in the zigbee network. i only have an issue with the tradfri button E1766 Open/Close.

Issue:
When press Open or Close the zigbee adapter itself shows the button is pressed in the device list
![grafik](https://user-images.githubusercontent.com/54140560/133774431-64a008dd-eed5-4a43-a590-5aa0a2fa50c2.png)

but the Objects dont show any true value while pressing 

![grafik](https://user-images.githubusercontent.com/54140560/133774723-cb57a54e-0f6c-457f-92cb-7549c7b4fd9f.png)
the only change is the timestamp.

System is
![grafik](https://user-images.githubusercontent.com/54140560/133774964-befc702d-7ba0-48aa-b456-f899b1994006.png)
+ Conbee2 Stick with newest Firmware
I tried different version of the zigbee.adapte incl 1.6.1

**Comment by asgothian** [comment]
Please ent4r 842e14fffe6cbb7b to the state zigbee.0.info.debugmessages, use the button and check the log for warn messages with the keyword “ELEVATED”.

A.

**Comment by ruvnax** [comment]
Sorry for the late Answer,  here ist what the log look like.

![grafik](https://user-images.githubusercontent.com/54140560/133940321-6e22b298-1e11-4b83-beef-42204028b37e.png)

**Comment by asgothian** [comment]
The log clearly shows that the values are set to true when an event is triggered. It seems that your admin is buffering the states in the browser.

please set a script with a trigger to catch the change to “true”, as the state will only be true for about 500 ms.

a.

**Comment by ruvnax** [comment]
Seems to be an issue with the 500ms or less what ever the value is. 
I made a new install updated everything , it works!!
 now i can do my skript even if the state is not realy visible in the objects.

 sorry for the stupid question. and thanks a lot for the help.

RGDS
Ruvi
