### ISSUE TITLE
Problem with Aqara D1 Single Key 

### ISSUE THREAD

**Issue by Vitalize27** [ioBroker/ioBroker.zigbee#1218]
Hi there,

I have a problem with the Aqara D1 single key. Unfortunately, he does not recognize the simple click event. This problem does not exist with the Aqara D1 double key.
The log says:
State value to set for "zigbee.0.7cb03eaa00af4759.link_quality" has value "255" greater than max "254"
Is this a known adapter problem?
Thanks for help

**Comment by asgothian** [comment]
- Which adapter version are you running ?
- Please post the warning messages containing the word "ELEVATED" after entering 7cb03eaa00af4759 into zigbee.0.info.debugmessages
- In order to remove the link quality issue: update to at least 1.6.0, Stop the zigbee Adapter, delete all states for zigbee.0.7cb03eaa00af4759 and restart the adapter.

**Comment by asgothian** [comment]
Addition: Please add the device type to the exclude list and restart the adapter to see if the exposed states work as intended.

A.

**Comment by BigMike71** [comment]
i have tested with 1.6.2, with exclude it will work, without only double click and hold. no errors and warnings in my log...

**Comment by Vitalize27** [comment]
I updated the adapter to 1.6 and deleted states. After reactivation, however, there was no difference in comparison to before. Where can I set "Exclude" for this device? Thanks very much

**Comment by asgothian** [comment]
It is in the adapter configuration interface. There is an entire tab for the exclude list (in german; Ausschlussliste)

A.

**Comment by asgothian** [comment]
> i have tested with 1.6.2, with exclude it will work, without only double click and hold. no errors and warnings in my log...

Do i understand you correctly that
- All expected reactions (click, hold, double_click) work as desired
- No warnings are generated ?

If that is the case, please run the device in exposed mode as you did for the test. A future update may remove the device from the adapters own list of devices to use the exposes as default.

A.
