### ISSUE TITLE
Deconz stick publishes Link Quality when a group is switched

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.zigbee#1219]
A test with the iobroker user rotamint has shown that the current herdsman sends a link quality message when a group is controlled via the zigbee adapter.

```
Device 0x00212effff05b783 "undefined" not described in statesMapping.
ELEVATED publishToState: value generated '229' from device 00212effff05b783 for 'Link quality'
ELEVATED publishToState: value generated '"{\"type\":\"commandOn\",\"data\":{},\"linkquality\":229,\"groupID\":5,\"cluster\":\"genOnOff\",\"meta\":{\"zclTransactionSequenceNumber\":100,\"manufacturerCode\":null,\"frameControl\":{\"frameType\":1,\"manufacturerSpecific\":false,\"direction\":0,\"disableDefaultResponse\":true,\"reservedBits\":0}},\"endpoint_id\":1}"' from device 00212effff05b783 for 'Message from Zigbee'

```

The device 0x00212effff05b783 is a conbee II stick, and the messages coincide with switching a group of 2 lamps on and off.

A.

**Comment by mickym2** [comment]
Is there any solution meanwhile - each time a group is addessed with the conbee2 stick generates theses errors - or is it possible to suppress these errors ?

**Comment by asgothian** [comment]
A fix is being worked on, but it is not yet integrated.

**Comment by asgothian** [comment]
A fix to mitigate the effect is present in the current 1.6.9 version. You will get one error message per Adapter start, all further messages are caught and suppressed.

note that this does not fix the underlying issue but masks it. There should be no negative effects on group use and stability.

A

**Comment by mickym2** [comment]
Ok many thanks - this works and cleans up the log. One thing, which I should mentioned but does not bother me as in 99 % I change settings in the objects - when you change brightness in the tile of the group in the adapters GUI, it sends a string instead of a number - at least the log complains about that. But as I said it is only a problem in the GUI of the adapter.

**Comment by asgothian** [comment]
> - when you change brightness in the tile of the group in the adapters GUI, it sends a string instead of a number -

Thank you for letting us know. i will have a look at attempting to enforce correct formats when writing to states. Not sure if that will be feasible or breaking things.

A.
