### ISSUE TITLE
Beim Update viele "Infos"

### ISSUE THREAD

**Issue by Schimi1983** [ioBroker/ioBroker.zigbee#1223]
Hi,

habe gerade von 1.6.0 auf 1.6.3 nen update gemacht... dabei hat er als Info nen paar meldungen ausgegeben... Scheint aber alles zu funktionieren...

`
<html>
<body>

zigbee.0 | 2021-09-28 11:08:31.981 | info | Currently 25 devices are joined:
-- | -- | -- | --
zigbee.0 | 2021-09-28 11:08:31.972 | info | --> transmitPower : normal
zigbee.0 | 2021-09-28 11:08:31.963 | info | Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210708}}
zigbee.0 | 2021-09-28 11:08:31.687 | info | Installed Version: iobroker.zigbee@1.6.3
zigbee.0 | 2021-09-28 11:08:31.427 | info | Starting Zigbee npm ...
zigbee.0 | 2021-09-28 11:08:31.381 | info | starting. Version 1.6.3 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.17.6, js-controller: 3.3.18
host.smarthome | 2021-09-28 11:08:30.953 | info | iobroker exit 0
host.smarthome | 2021-09-28 11:08:29.973 | info | instance system.adapter.zigbee.0 started with pid 222333
host.smarthome | 2021-09-28 11:08:29.935 | info | "system.adapter.zigbee.0" enabled
host.smarthome | 2021-09-28 11:08:29.922 | info | iobroker host.smarthome Adapter "system.adapter.zigbee.0" is started
host.smarthome | 2021-09-28 11:08:29.921 | info | iobroker Adapter "zigbee" updated
host.smarthome | 2021-09-28 11:08:29.866 | info | iobroker upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/adapter-settings.js adapter-settings.js application/javascript
host.smarthome | 2021-09-28 11:08:29.812 | info | iobroker upload [1] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/admin.js admin.js application/javascript
host.smarthome | 2021-09-28 11:08:29.759 | info | iobroker upload [2] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/14147206L.png img/14147206L.png image/png
host.smarthome | 2021-09-28 11:08:29.705 | info | iobroker upload [3] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86plug.png img/86plug.png image/png
host.smarthome | 2021-09-28 11:08:29.651 | info | iobroker upload [4] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw1.png img/86sw1.png image/png
host.smarthome | 2021-09-28 11:08:29.593 | info | iobroker upload [5] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw2.png img/86sw2.png image/png
host.smarthome | 2021-09-28 11:08:29.540 | info | iobroker upload [6] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/AV2010_32.png img/AV2010_32.png image/png
host.smarthome | 2021-09-28 11:08:29.486 | info | iobroker upload [7] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/BW-IS3.png img/BW-IS3.png image/png
host.smarthome | 2021-09-28 11:08:29.433 | info | iobroker upload [8] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/BW-IS5.png img/BW-IS5.png image/png
host.smarthome | 2021-09-28 11:08:29.379 | info | iobroker upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Bitron_AV201021A.png img/Bitron_AV201021A.png image/png
host.smarthome | 2021-09-28 11:08:29.326 | info | iobroker upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DGNWG05LM.png img/DGNWG05LM.png image/png
host.smarthome | 2021-09-28 11:08:29.269 | info | iobroker upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ.png img/DIYRuZ.png image/png
host.smarthome | 2021-09-28 11:08:29.215 | info | iobroker upload [12] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ_CO2.png img/DIYRuZ_CO2.png image/png
host.smarthome | 2021-09-28 11:08:29.161 | info | iobroker upload [13] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ_Flower.png img/DIYRuZ_Flower.png image/png
host.smarthome | 2021-09-28 11:08:29.108 | info | iobroker upload [14] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ_FreePad.png img/DIYRuZ_FreePad.png image/png
host.smarthome | 2021-09-28 11:08:29.054 | info | iobroker upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ_FreePad_LeTV_8.png img/DIYRuZ_FreePad_LeTV_8.png image/png
host.smarthome | 2021-09-28 11:08:29.000 | info | iobroker upload [16] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ_Geiger.png img/DIYRuZ_Geiger.png image/png
host.smarthome | 2021-09-28 11:08:28.946 | info | iobroker upload [17] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ_R8_8.png img/DIYRuZ_R8_8.png image/png
host.smarthome | 2021-09-28 11:08:28.893 | info | iobroker upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Eurotronic_Spirit_04.png img/Eurotronic_Spirit_04.png image/png
host.smarthome | 2021-09-28 11:08:28.836 | info | iobroker upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/FLOALT.panel.WS.png img/FLOALT.panel.WS.png image/png
host.smarthome | 2021-09-28 11:08:28.782 | info | iobroker upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/HG06104A.png img/HG06104A.png image/png
host.smarthome | 2021-09-28 11:08:28.249 | info | iobroker upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Paulmann_50067.png img/Paulmann_50067.png image/png
host.smarthome | 2021-09-28 11:08:27.713 | info | iobroker upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ZHS15.png img/ZHS15.png image/png
host.smarthome | 2021-09-28 11:08:27.177 | info | iobroker upload [50] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/battery_v.png img/battery_v.png image/png
host.smarthome | 2021-09-28 11:08:26.641 | info | iobroker upload [60] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/crts0111.PNG img/crts0111.PNG image/png
host.smarthome | 2021-09-28 11:08:26.108 | info | iobroker upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/diy.png img/diy.png image/png
host.smarthome | 2021-09-28 11:08:25.574 | info | iobroker upload [80] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/flair_viyu_e14_candle.png img/flair_viyu_e14_candle.png image/png
host.smarthome | 2021-09-28 11:08:25.038 | info | iobroker upload [90] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/gledopto_gu10.png img/gledopto_gu10.png image/png
host.smarthome | 2021-09-28 11:08:24.500 | info | iobroker upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/group_6.png img/group_6.png image/png
host.smarthome | 2021-09-28 11:08:21.833 | info | iobroker upload [150] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/lamp_01.png img/lamp_01.png image/png
host.smarthome | 2021-09-28 11:08:18.358 | info | iobroker upload [200] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/paulmann_rgbw_globe.png img/paulmann_rgbw_globe.png image/png
host.smarthome | 2021-09-28 11:08:15.547 | info | iobroker upload [250] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/sensor_ht.png img/sensor_ht.png image/png
host.smarthome | 2021-09-28 11:08:11.572 | info | iobroker upload [300] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/vis-network.min.css vis-network.min.css text/css
host.smarthome | 2021-09-28 11:08:11.262 | info | iobroker Update "system.adapter.zigbee.0"
host.smarthome | 2021-09-28 11:07:59.712 | info | iobroker ../src/serialport_unix.cpp: In function ‘void EIO_Open(uv_work_t*)’:../src/serialport_unix.cpp:86:84: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size 1003 [-Wformat-truncation=] 86 \| snprintf(data->errorString, sizeof(data->errorString), "Error: %s, cannot open %s", strerror(errno), data->path); \| ^~In file included from /usr/include/stdio.h:867, from ../src/serialport.h:10, from ../src/serialport_unix.cpp:2:/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 22 or more bytes (assuming 1045) into a destination of size 1024 67 \| return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1, \| ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 68 \| __bos (__s), __fmt, __va_arg_pack ()); \| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
host.smarthome | 2021-09-28 11:07:59.689 | info | iobroker ../src/serialport_unix.cpp: In function ‘int setup(int, OpenBaton*)’:../src/serialport_unix.cpp:176:82: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size 1005 [-Wformat-truncation=] 176 \| snprintf(data->errorString, sizeof(data->errorString), "Error %s Cannot open %s", strerror(errno), data->path); \| ^~In file included from /usr/include/stdio.h:867, from ../src/serialport.h:10, from ../src/serialport_unix.cpp:2:/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 20 or more bytes (assuming 1043) into a destination of size 1024 67 \| return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1, \| ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 68 \| __bos (__s), __fmt, __va_arg_pack ()); \| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
host.smarthome | 2021-09-28 11:07:57.299 | info | iobroker ../src/serialport.cpp: At global scope:../src/serialport.cpp:433:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses] 433 \| SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) { \| ^../src/serialport.cpp:452:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses] 452 \| SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) { \| ^In file included from ../../../nan/nan.h:58, from ../src/./serialport.h:13, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.6/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type] 758 \| (node::addon_register_func) (regfunc), \ \| ^/home/iobroker/.cache/node-gyp/14.17.6/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’ 792 \| NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage) \| ^~~~~~~~~~~~~../src/serialport.cpp:486:1: note: in expansion of macro ‘NODE_MODULE’ 486 \| NODE_MODULE(serialport, init); \| ^~~~~~~~~~~
host.smarthome | 2021-09-28 11:07:57.296 | info | iobroker ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:366:76: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 366 \| uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate); \| ^~~~~~~~~~~~~~~~~~~~../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:412:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 412 \| uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain); \| ^~~~~~~~~~~~~~
host.smarthome | 2021-09-28 11:07:57.292 | info | iobroker ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:316:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 316 \| uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet); \| ^~~~~~~~~~~~
host.smarthome | 2021-09-28 11:07:57.289 | info | iobroker ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:175:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 175 \| uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose); \| ^~~~~~~~~~~~~~../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:215:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 215 \| uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush); \| ^~~~~~~~~~~~~~../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:271:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 271 \| uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet); \| ^~~~~~~~~~~~
host.smarthome | 2021-09-28 11:07:57.285 | info | iobroker ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:135:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 135 \| uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate); \| ^~~~~~~~~~~~~~~
host.smarthome | 2021-09-28 11:07:57.282 | info | iobroker ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 78 \| uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen); \| ^~~~~~~~~~~~~
host.smarthome | 2021-09-28 11:07:15.726 | info | instance system.adapter.zigbee.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
zigbee.0 | 2021-09-28 11:07:15.047 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.0 | 2021-09-28 11:07:15.046 | info | terminating
host.smarthome | 2021-09-28 11:07:14.953 | info | iobroker npm install iobroker.zigbee@1.6.3 --loglevel error --prefix "/opt/iobroker" (System call)
host.smarthome | 2021-09-28 11:07:14.952 | info | iobroker NPM version: 6.14.15
host.smarthome | 2021-09-28 11:07:14.700 | info | stopInstance system.adapter.zigbee.0 send kill signal
zigbee.0 | 2021-09-28 11:07:14.550 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2021-09-28 11:07:14.545 | info | cleaned everything up...
zigbee.0 | 2021-09-28 11:07:14.539 | info | Got terminate signal TERMINATE_YOURSELF
host.smarthome | 2021-09-28 11:07:14.535 | info | stopInstance system.adapter.zigbee.0 (force=false, process=true)
host.smarthome | 2021-09-28 11:07:14.533 | info | "system.adapter.zigbee.0" disabled
host.smarthome | 2021-09-28 11:07:14.515 | info | iobroker host.smarthome Adapter "system.adapter.zigbee.0" is stopped.
host.smarthome | 2021-09-28 11:07:14.487 | info | iobroker Update zigbee from @1.6.0 to @1.6.3
host.smarthome | 2021-09-28 11:07:13.138 | info | iobroker upgrade zigbee

</body>
</html>`

**Comment by asgothian** [comment]
This is normal, and cannot be affected by the zigbee adapter. The messages have 2 general sources:
- the normal 'update and upload' process which reports most files which are "uploaded" into the correct location for use in the administrative panel
- warning messages generated when compiling the serial port Library for the given nodeJS environment.
A.
