### ISSUE TITLE
Request: remember names when objects are deleted

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1224]
With the latest update I wanted to refresh the objects .. now all names are gone that I had edited. Maybe it could be facilitated that the names don't need to be redone when you renew the object tree?

**Comment by asgothian** [comment]
This is a tricky request, as the objects in the tree are removed when a device is removed from the zigbee network. As such, there is no place to store this kind of information in the current system.

A.

**Comment by asgothian** [comment]
A test for this is available at https://github.com/asgothian/ioBroker.zigbee

note that this fork also contains modified group functionality.

A.

**Comment by daniel-lo** [comment]
Good news!
Bit it's not clear what happens if I try this .. will I mess up my installation .. will I have problems using the standard version afterwards?

Cheers

**Comment by asgothian** [comment]
It should not. A function to remove group related data is not active at this point, so going back to the standard version should be no problem. As a safeguard, you might want to copy the content of the state zigbee.0.info.groups (if you use zigbee groups), in case it gets lost along the way

A.

**Comment by daniel-lo** [comment]
1.6.13 .. removed complete object tree and restarted adapter .. all names reset to default.

**Comment by asgothian** [comment]
Did you read the read the read me before testing ? Only names changed through the zigbee interface **with this version installed** will be retained.

any current changed names in the object tree are not recorded.

A.

**Comment by daniel-lo** [comment]
Nope .. didn't read that .. just restored my backup .. so I need to touch every name I understand

**Comment by asgothian** [comment]
Let me know if it works,for you and/or if you have odd things happening. If not I can make a PR to the main adapter

**Comment by daniel-lo** [comment]
installed new from git .. manually added a ".z" to all device names .. paused the adapter .. delted the object tree .. all names lost

**Comment by asgothian** [comment]
Please check if a file named dev_names.JSON exists.

also - did you install with the link I posted above or from the official GitHub repo ?

**Comment by daniel-lo** [comment]
:-(

No .. I used github installation .. my mistake .. didn't know where to put the URL .. but now I used it in the "user defined" section.

I see this in the log file:
<html><body>


warn | config   :{"port":"/dev/ttyACM0","panID":"6754","extPanID":"<snip>","channel":"11","disableLed":false,"precfgkey":"<snip>","countDown":"360","adapterType":"deconz","debugHerdsman":true,"transmitPower":null,"extPanIdFix":true,"disablePing":false,"external":"","startWithInconsistent":false}
-- | --

</body>
</html>

**Comment by daniel-lo** [comment]
Now it worked .. names are rebuilt correctly

**Comment by asgothian** [comment]
aside that warn message - any odd behavior ? Anything not working as expected so far ?

A.

**Comment by daniel-lo** [comment]
nope .. very straight forward .. I do have a new default group icon in my device overview .. which I don't know about .. but other than that nothing strange

**Comment by asgothian** [comment]
A new default group icon ? Can you describe it a bit better or post a screenshot ?

A.

**Comment by daniel-lo** [comment]
ignore ".z"
![grafik](https://user-images.githubusercontent.com/4311558/150410260-49a52732-9dc5-4625-8225-a8014b4aea92.png)

**Comment by asgothian** [comment]
Ah - that one. When adding Ikea remotes they will publish a group which is then created in the zigbee Database. The new group functionality shows these groups. You can delete it with no ill effect.

A.

**Comment by daniel-lo** [comment]
:-)

**Comment by asgothian** [comment]
PR is active. Should be merged into the official GitHub repo reasonably soon

**Comment by asgothian** [comment]
Merged.
