### ISSUE TITLE
New Device Smart Emergency Button SOS-EF-3.0

### ISSUE THREAD

**Issue by mulche3** [ioBroker/ioBroker.zigbee#1226]
Pairing ok with "?" but no funktions
https://de.aliexpress.com/item/4000075282903.html?spm=a2g0s.9042311.0.0.dcd44c4dhlDQdi

endpoint:1
profile:260
input clusters:genBasic (0)
genPowerCfg (1)
genIdentify (3)
ssIasZone (1280)
haDiagnostic (2821)
output clusters:genOta (25)
modelZigbee:SOS-EF-3.0
type:EndDevice
nwk:15452
manuf id:4619
manufacturer:HEIMAN
power:Battery
app version:17
hard version:16
zcl version:2
stack version:2
date code:2019.9.6
interviewed:true
configured:false

**Comment by mulche3** [comment]
Zigbee Adapter Version 1.6.3

CC2652P Zigbee Stick

Firmware is type:zStack3x0
version:2-1.2.7.1.
revision:20210708

https://www.zigbee2mqtt.io/devices/HS1EB_HS1EB-E.html

**Comment by asgothian** [comment]
That is a device which may look the same, but it is not the same. Yours identifies as SOS-EF-3.0, the one implemented identifies as HS1EB.

Please make a Device support request at the zigbee-herdsman-converters project.

A.
