### ISSUE TITLE
Ikea Tradfri Repeater doesnt work with aqara Sensors

### ISSUE THREAD

**Issue by kursepe** [ioBroker/ioBroker.zigbee#1228]
Hi, i have a
 - conbee ii stick
 - some ikea tradfri sensors,
 - the ikea tradfri repeater
 - some aquara sensors (door and temp, waterleak)

The tradfri sensors works fine with the repeater, the aquara sensors doesnt find the tradfri repeater, they find only the conbee ii stick.

Do you know how to teach the aqara sensors to the tradfri repeater? The system has been running for about 1 week

Thanks a lot!

![grafik](https://user-images.githubusercontent.com/91819646/135742773-6509c547-89e7-445d-b131-5f48268fd283.png)

**Comment by asgothian** [comment]
The zigbee network is a mesh network. There is no option to force specific devices to connect via specific other devices. Some devices may choose to connect via a router device if it offers better signal than the coordinator, but that is not required in the zigbee specification. The aqara sensors are known to prefer direct coordinator connections over router connections.

A.
