### ISSUE TITLE
Lidl Silvercrest Außensteckdose 2-fach mit Erdspieß

### ISSUE THREAD

**Issue by mblass** [ioBroker/ioBroker.zigbee#1232]
When trying to pair the Lidl Outdoor Plug (should be similar to https://www.zigbee2mqtt.io/devices/HG06619.html) the zigbee adapter restarts by sending this log:
zigbee.0 | 2021-10-04 15:15:06.049 | info | terminating with timeout
zigbee.0 | 2021-10-04 15:15:05.022 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-10-04 15:15:05.020 | info | terminating
zigbee.0 | 2021-10-04 15:15:04.523 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2021-10-04 15:15:04.519 | info | cleaned everything up...
zigbee.0 | 2021-10-04 15:15:04.516 | error | Cannot read property 'toZigbee' of null
zigbee.0 | 2021-10-04 15:15:04.515 | error | TypeError: Cannot read property 'toZigbee' of null at /opt/iobroker/node_modules/iobroker.zigbee/main.js:494:43 at Array.forEach () at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:452:19)
zigbee.0 | 2021-10-04 15:15:04.514 | error | unhandled promise rejection: Cannot read property 'toZigbee' of null
zigbee.0 | 2021-10-04 15:15:04.513 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-10-04 15:14:08.767 | info | Successfully interviewed '0x60a423fffe154b0d', device has succesfully been paired
zigbee.0 | 2021-10-04 15:13:54.440 | info | Starting interview of '0x60a423fffe154b0d'
zigbee.0 | 2021-10-04 15:13:53.197 | info | Zigbee: allowing new devices to join.

The device is recognized as TS0101 and can be switched. Availability and link quality is not sent.
I did the pairing twice, same restart of adapter, same missing data objects.

Unfortunately I'm not very skilled in programming so "How to support new devices" doesn't work for me.

**Comment by kirovilya** [comment]
try to install latest version from github

**Comment by mblass** [comment]
Same result. I installed 1.6.3, device was paired, still no availability and link quality value  and then 
host.RasPi4 | 2021-10-04 19:36:47.291 | error | Caught by controller[1]: TypeError: Cannot read property 'toZigbee' of null
host.RasPi4 | 2021-10-04 19:36:47.283 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2021-10-04 19:36:45.918 | info | terminating with timeout
zigbee.0 | 2021-10-04 19:36:44.916 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-10-04 19:36:44.915 | info | terminating
zigbee.0 | 2021-10-04 19:36:44.386 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2021-10-04 19:36:44.383 | info | cleaned everything up...
zigbee.0 | 2021-10-04 19:36:44.373 | error | Cannot read property 'toZigbee' of null
zigbee.0 | 2021-10-04 19:36:44.372 | error | TypeError: Cannot read property 'toZigbee' of null at /opt/iobroker/node_modules/iobroker.zigbee/main.js:544:43 at Array.forEach (<anonymous>) at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:502:19)
zigbee.0 | 2021-10-04 19:36:44.370 | error | unhandled promise rejection: Cannot read property 'toZigbee' of null
zigbee.0 | 2021-10-04 19:36:44.369 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-10-04 19:36:24.388 | info | Zigbee: stop joining
zigbee.0 | 2021-10-04 19:35:17.906 | info | Successfully interviewed '0x60a423fffe154b0d', device has succesfully been paired

**Comment by mblass** [comment]
Link quality is now available but "Available" is still empty and, as mentioned, restart of adapter.
Even after pressing device query no further data.
![image](https://user-images.githubusercontent.com/91893325/135898504-ae3925f9-37a6-44df-9191-e1adb5e26866.png)
Changing state of plug leads to another crash of the adapter.

**Comment by kirovilya** [comment]
I see. try update from github again :) I think, fixed

**Comment by mblass** [comment]
Just to be sure: https://github.com/ioBroker/ioBroker.zigbee.git ?

**Comment by kirovilya** [comment]
yes. or from admin
![image](https://user-images.githubusercontent.com/8360230/135900338-038279c7-240d-4f5c-bc9d-9b341058e353.png)

**Comment by mblass** [comment]
1.6.4 installed
No adapter crash !
But still no "available" and "link quality".
Plug can be switched, this is shown in Objects.

**Comment by kirovilya** [comment]
brrr... refresh objects page

**Comment by mblass** [comment]
I already did ;-) It is not shown in the Zigbee overview as well
![image](https://user-images.githubusercontent.com/91893325/135901972-e5ff44d4-314d-4cce-b194-3f9fdda5baf7.png)

**Comment by kirovilya** [comment]
wait a bit...

**Comment by mblass** [comment]
After restart link quality has now a value. Available is still (null).

**Comment by kirovilya** [comment]
we need to rewrite the setting of the "available" state ... yet I can not help with it

**Comment by mblass** [comment]
ok. Many thanks so far. If I can provide you somehow with device data or sth else, please let me know.

**Comment by asgothian** [comment]
Closed.
