### ISSUE TITLE
Support Linkind Keypad "ZS130000078"

### ISSUE THREAD

**Issue by Jaschster** [ioBroker/ioBroker.zigbee#1234]
Hello together,

Could you please include the "Linkind" keypad in your next update? It is already included in zigbee2mqtt:
[https://www.zigbee2mqtt.io/devices/ZS130000078.html](https://www.zigbee2mqtt.io/devices/ZS130000078.html) 

That would be great.

Thank you very much for that.
With kind regards
Jaschster

**Comment by asgothian** [comment]
Which adapter version are you running ?

If it is supported by the herdsman it should be supported by the latest GitHub version of the zigbee adapter too.

A.

**Comment by Jaschster** [comment]
Hello,

I am using the ioBroker zigbee adapter in version 1.6.3.
Isn't this the latest version?


Best Regards,

Jaschster

**Comment by asgothian** [comment]
Depends.. if you installed it through the beta channel, then no.

The latest version is 1.6.4 off GitHub.

A.

**Comment by Jaschster** [comment]
Hello,

thank you very much for the hint! After some initial difficulties, the device is now finally working. Unfortunately, it is still not possible to integrate the device in a usable way. Only a few basic functionalities are working...
If I understood correctly, the Linkind keypad has to be somehow "unlocked" every time at the the start in order to be fully functional.
Since I am not an expert in integrating Zigbee devices, I would be very happy if someone with experience could address this issue.
The problem is already addressed in the context of z2m, but unfortunately I personally do not know how to approach it in the environment of the ioBroker zigbee adapter.
Here is the link to the discussion: [https://github.com/Koenkk/zigbee2mqtt/issues/6242#issuecomment-932633849](url)

I would really appreciate if someone could make it work!
Thanks!


Best Regards,

Jaschster

**Comment by austrogaucho** [comment]
@Jaschster how did you manage to pair it, I have received the same device today and I would like to "play" with it

**Comment by Jaschster** [comment]
Hello @austrogaucho,

one thing in advance, it was already difficult to make it, probably made even more difficult by the fact that I had already connected the device once before it was supported by the Zigbee adapter in ioBroker. Finally, I was able to successfully integrate the device, which was initially still incompletely configured and displayed as an unknown device, by trying to delete the device several times in the adapter settings, as well as restarting the Docker container in which ioBroker is running, I was able to complete the deletion of the device. The keypad was only properly recognized in conjunction with the Zigbee adapter in GitHub version 1.6.4. Furthermore, when adding the device, I changed the duration of the "device search" from the default 60 seconds to 90 seconds.
The device was then integrated.
But as already described previously, not everything works and I would be very happy if you or someone else could get it functioning!

Good luck with the integration and thanks in advance!

Jaschster

**Comment by dj-stelzer** [comment]
Hello Has anyone already managed to integrate the Linkind Keypad, I have the same problems

**Comment by dj-stelzer** [comment]
> Hello together,
> 
> Could you please include the "Linkind" keypad in your next update? It is already included in zigbee2mqtt: https://www.zigbee2mqtt.io/devices/ZS130000078.html
> 
> That would be great.
> 
> Thank you very much for that. With kind regards Jaschster

Hello Has anyone already managed to integrate the Linkind Keypad, I have the same problems
