### ISSUE TITLE
Problem nach Anlernen von Aqara Wireless Remote Switch / Problem after learning the Aqara Wireless Remote Switch

### ISSUE THREAD

**Issue by tottiMG** [ioBroker/ioBroker.zigbee#1237]
Ich habe heute 2 Stück Aqara Wireless Remote Switch H1 Double Rocker angelernt. Ich habe einen Conbee2 als Coordinator.

Ich habe beide Schalter nur angelernt, sonst nichts gemacht!
1 Schalter funktioniert problemlos.

Der 2. Schalter schaltet bei jedem Tastendruck (egal welcher von beiden) alle(!) Zigbee Lampen und Steckdosen Ein und Aus.

Hier mal ein paar Screenshots

.
.
.
.
.
Today I trained 2 pieces of Aqara Wireless Remote Switch H1 Double Rocker. I have a Conbee2 as a coordinator.

I only trained both switches, did nothing else!
1 switch works fine.

The 2nd switch switches all (!) Zigbee lamps and sockets on and off each time a button is pressed (regardless of which one).

Here are a few screenshots

Beim "Problem"-Taster fehlen die Objektdaten
![zigbee4](https://user-images.githubusercontent.com/64850243/137183590-3b2f73da-1506-4746-beae-16d38639a656.JPG)
Der "Gute"
![zigbee5](https://user-images.githubusercontent.com/64850243/137183593-6d731ef3-c9f3-4144-9b55-05ef71a3f0c8.JPG)
Der "Problem"-Taster
![zigbee6](https://user-images.githubusercontent.com/64850243/137183596-95c46561-2139-4698-9094-ed253ec16ec8.JPG)

Hier ein paar Log-Meldungen:

Die Meldungen kommen regelmäßig:
![zigbee8](https://user-images.githubusercontent.com/64850243/137183600-4b890a1c-cf72-45c1-9c16-e5c85faf8ed9.JPG)

**Comment by arteck** [comment]
lerne den einen ncohmal an ohne den zu löschen.. der hat kein configure bekommen.. deshalb schaltet der auf gruppe an/aus

**Comment by tottiMG** [comment]
Ich habe es jetzt nochmal versucht und nach den 10sek. den Taster mehrfach betätigt. Während dieser Zeit gingen auch alle Zigbee Geräte an und aus.
Der Einzige unterschied, siehe Screenshot
![zigbee9](https://user-images.githubusercontent.com/64850243/137203310-a6761fde-979d-4661-9d16-798ccc18cab1.JPG)

Das Gerät was hier angegeben ist, existiert nicht. Die ID trat auch schon bei einem anderen Problem auf:

[https://forum.iobroker.net/topic/48185/zigbee-device-0x00212effff06d273-undefined-meldung?_=1634154591204](https://forum.iobroker.net/topic/48185/zigbee-device-0x00212effff06d273-undefined-meldung?_=1634154591204)

**Comment by tottiMG** [comment]
Habe das Gerät jetzt zurück geschickt.
