### ISSUE TITLE
No converter available for '6735/6736/6737' with key 'rm01_row_2'

### ISSUE THREAD

**Issue by Newan** [ioBroker/ioBroker.zigbee#1238]
Hello,

I have the RM01 with 2 rockers. Rocker 1 works with state and rocker 2 with rm01_row_2.
The buttons work and also setting by script or admin GUI.
Problem when setting from GUI or script of 'rm01_row_2' I get following error message. But function is given:

Errormessage:
`2021-10-14 14:53:11.048 | error | No converter available for '6735/6736/6737' with key 'rm01_row_2'`

Here the info from the device:

![image](https://user-images.githubusercontent.com/3693094/137322151-37b90ea9-f8ec-42d2-9d43-84a5f4b80df8.png)
![image](https://user-images.githubusercontent.com/3693094/137322309-4fed623f-dcf6-43fa-870d-e8bef375749b.png)
![image](https://user-images.githubusercontent.com/3693094/137322360-ad125231-9c96-46b0-b60c-211c63113339.png)

If something is missing, I will gladly give more info
Edit:
<html>
<body>

2021-12-30 13:08:26.569 | warn | Read-only state "zigbee.0.d85def11a10046b1.rm01_row_2" has been written without ack-flag with value "false"
-- | -- | --

</body>
</html>
Ist wohl auch nur als Readonly eingetragen

**Comment by asgothian** [comment]
Which adapter version are you running ?

A.

**Comment by Newan** [comment]
v1.6.10

**Comment by Newan** [comment]
Add in zigbee-herdsman-converters an then the file toZigbee.js:

```
    rm01_row_button: {
        key: ['rm01_row_2', 'rm01_row_3', 'rm01_row_4'],
        convertSet: async (entity, key, value, meta) => {
            return;
        },

    },
```

and in devices/busch-jaeger.js:

`        toZigbee: [tz.RM01_light_onoff_brightness, tz.RM01_light_brightness_step, tz.RM01_light_brightness_move, tz.rm01_row_button],
`
