### ISSUE TITLE
Paulmann 500.65

### ISSUE THREAD

**Issue by Jacc87** [ioBroker/ioBroker.zigbee#124]
Hallo Mein zigbee Adapter erkennt im iobrocker die Paulmann 500.65 als RGBW Light und fügt es hinzu leider lassen sich die Lampen nicht steuern. Im Iobroker log ist folgendes zu finden 

zigbee.0 | 2018-12-15 22:53:29.125 | error | Unknown device model RGBW light

Bitte implimentieren

**Comment by arteck** [comment]
es gibt ein Thread im Forum 
https://forum.iobroker.net/viewtopic.php?f=24&t=18214
schon gelesen ??
