### ISSUE TITLE
Aqara E1 Door & Window Sensor (MCCGQ14LM)

### ISSUE THREAD

**Issue by Voodoo2man** [ioBroker/ioBroker.zigbee#1245]
Hallo,

ich habe heute die neue Generation der Aqara E1 Tür/Fenster Sensoren mit Zigbee 3.0 geliefert bekommen.
Beim Versuch diesen im Zigbee Adapter anzulernen bekomme ich folgende Fehlermeldung:

Error: Device 0x54ef44100027e282 "lumi.magnet.acn001" not described in statesMapping.. undefined
New device joined '0x54ef44100027e282' model lumi.magnet.acn001
Device '0x54ef44100027e282' announced itself

Welche Möglichkeiten gibt es den Sensor einzubinden?

Typ des Sensors ist: MCCGQ14LM

Ich verwende iobroker auf einem RaspberryPi 4 mit CC26X2R1
CC26X2R1 Firmware: Z-Stack 3.x.0 20210708
Node.js: v12.22.7
Zigbee Adapter: v 1.6.3
Alles weitere auf "Latest" Stand

**Comment by julien100** [comment]
I was able to make to make the sensor work with the current version of zigbee2mqtt and a Conbee II stick with the  latest firmware (deCONZ_ConBeeII_0x26720700.bin.GCF). I only added the following definition to node_modules/zigbee-herdsman-converters/devices/xiaomi.js:

`
    zigbeeModel: ['lumi.magnet.acn001'],
    model: 'MCCGQ14LM',
    vendor: 'Xiaomi',
    description: 'Aqara E1 door & window contact sensor',
    fromZigbee: [fz.ias_contact_alarm_1, fz.battery],
    toZigbee: [],
    exposes: [e.contact(), e.battery(), e.battery_voltage()],
    configure: async (device, coordinatorEndpoint, logger) => {
      await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['ssIasZone']);
    }
`

Does that somehow help to make it work for the ioBroker adapter?

**Comment by sPzAbt** [comment]
Yes its working with this modification in iobroker zigbee adapter, except it doesnt report battery but open/close is working:

![image](https://user-images.githubusercontent.com/17520358/139927330-7d3eef67-d989-4bbd-b74b-635fab6e3cd0.png)

**Comment by bastiaux** [comment]
I tried to add the code like this:
![2021-11-03 09_42_24-RPI4 - 192 168 178 44 - Remotedesktopverbindung](https://user-images.githubusercontent.com/93095227/140030633-b73cf7f8-a891-45a9-8d63-e314086b1d50.png)

in /opt/iobroker/node_modules/zigbee-herdsman-converters/devices/xiaomi.js

But after that I can't restart the iobroker zigbee adapter anymore.

Log:
![2021-11-03 09_54_47-logs - raspberrypi4-iob](https://user-images.githubusercontent.com/93095227/140032158-b7867a95-928b-464d-9841-ee4582634ee0.png)


![2021-11-03 09_56_08-Infobericht_Trace_V4_0 doc  -  Kompatibilitätsmodus - Word](https://user-images.githubusercontent.com/93095227/140032263-d0e05836-a0ff-4278-a50f-f9091595fc7a.png)

**Comment by joelfriesecke** [comment]
You also have to close the element with "}". That was forgotten in the code above.

**Comment by bastiaux** [comment]
With the code above (including the closed element ;-)) I can pair and connect, but with the SONOFF Zigbee 3.0 USB Dongle Plus I don't get values for the datapoints except "available" and "link_quality".

![2021-11-03 12_10_21-zigbee-0 - raspberrypi4-iob](https://user-images.githubusercontent.com/93095227/140050384-83f32250-e254-4c53-805b-8c8d73eaa650.png)
![2021-11-03 12_10_55-objects - raspberrypi4-iob](https://user-images.githubusercontent.com/93095227/140050391-93614b30-2f1c-47e5-8d3f-23150492b674.png)

**Comment by sPzAbt** [comment]
@bastiaux 
its only working with patched firmware for this stick from Koenkk:
https://github.com/Koenkk/zigbee2mqtt/issues/9274#issuecomment-958146099

i tested it first with a patched ConbeeII but then also with this Sonoff ZIGBEE 3.0 USB DONGLE PLUS
![139961748-9db128b4-ff88-4f76-9bfb-d721502cdb21](https://user-images.githubusercontent.com/17520358/140081804-c8ef2e3d-e40a-4a59-99b2-bf373f3e0411.png)

**Comment by sPzAbt** [comment]
with last tip from Koenkk i changed the entry in node_modules/zigbee-herdsman-converters/devices/xiaomi.js to:
               { 
		zigbeeModel: ['lumi.magnet.acn001'],
		model: 'MCCGQ14LM',
		vendor: 'Xiaomi',
		description: 'Aqara E1 door & window contact sensor',
		fromZigbee: [fz.ias_contact_alarm_1, fz.aqara_opple_report],
		toZigbee: [],
		exposes: [e.contact(), e.battery(), e.battery_voltage()],
		configure: async (device, coordinatorEndpoint, logger) => { 
			await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['ssIasZone']);
		},
now also battery is (probably) working but its reporting only 2.953 Volt while its battery is measured at 3.03 volt:

![image](https://user-images.githubusercontent.com/17520358/140170104-71828f82-e310-451d-a937-2477d9c01ec9.png)

**Comment by sPzAbt** [comment]
its marked as solved now in Koenkk/zigbee2mqtt:
https://github.com/Koenkk/zigbee2mqtt/issues/9274#issuecomment-959824220

**Comment by Kawaiito** [comment]
so updated my conbee so 1x i paired succesfull but my first one i tryed never get confugiered

![grafik](https://user-images.githubusercontent.com/66477532/140245815-6f05c30d-0c2e-48f6-990f-ab1973d1f671.png)

whats this same devices whats this?

![grafik](https://user-images.githubusercontent.com/66477532/140245963-b308ee37-4cdc-4735-a502-6bf64d69c844.png)

**Comment by sPzAbt** [comment]
@Kawaiito have you tried to delete and pair it again ?

which code did you enter to get these on off and hold events ?

**Comment by asgothian** [comment]
@Kawaiito the device does not allow configuration as it is not “active”. This is a common behavior of battery powered devices. You can try to set it active by repeatedly pressing the button used for triggering pairing mode - just short presses though.

if this does not help you will have to delete and re-pair the device.

a.

**Comment by Kawaiito** [comment]
have the same ... i put the  battery out .. press the button 5 sec by blinking.. remove the device .. same yet on the other repairing works

**Comment by Kawaiito** [comment]
a new one can configurated but no states 
![grafik](https://user-images.githubusercontent.com/66477532/140328679-be2cf80a-6283-48b9-b90a-16d75d61b464.png)

**Comment by Kawaiito** [comment]
> 
> 
> @Kawaiito the device does not allow configuration as it is not “active”. This is a common behavior of battery powered devices. You can try to set it active by repeatedly pressing the button used for triggering pairing mode - just short presses though.
> 
> if this does not help you will have to delete and re-pair the device.
> 
> a.

i cleard my db and all devices and press all the time the button and it dont  works  @asgothian

**Comment by Kawaiito** [comment]
so i changed from conbee 2 too th sonoff 3.0  + Plus  dongle with custom firmware  from koennk. 2 from 4 Sensors  works 2 blinking always  and i cant pair .. i press 5 sec the button ..no  action  .. remove the battery and wait ... no action  there blinking the same as before. 

![grafik](https://user-images.githubusercontent.com/66477532/140658131-7e811768-0310-4281-b479-4cf2b592735d.png)

Its special than i the only  one that has problems. its a mystery...

**Comment by asgothian** [comment]
Please do not post error messages as screenshot. I can't read those.

A.

**Comment by fraggle-iw** [comment]
Hi,

@kirovilya told me to update to the latet version from github, which solved my issues.

https://github.com/Koenkk/zigbee2mqtt/issues/9274#issuecomment-963480598

But be aware that this ist not a stable release. (Afaik).

Good luck!

**Comment by G3KK094** [comment]
After updating to the newest github version i could pair the devices but "contact event" and "is open" dont change.

**Comment by amg666** [comment]
> 
> 
> After updating to the newest github version i could pair the devices but "contact event" and "is open" dont change.

same here, it is pairing but "is open" "contact event" and "voltage" are empty and do not change. I am using a cc2531 stick.
I installed latest github version (1.6.7)

**Comment by thomasklein1975** [comment]
hi,

are there updates about that issue?

I have got same issues with new aqara door sensor. some weeks ago i was able to pair 3 devices from other order. maybe othe charge/firmware of product)

Error: Device 0x54ef441000282918 "lumi.magnet.acn001" not described in statesMapping.. undefined
New device joined '0x54ef441000282918' model lumi.magnet.acn001
Interview successful: [object Object]

Error: Device 0x54ef441000282328 "lumi.magnet.acn001" not described in statesMapping.. undefined
New device joined '0x54ef441000282328' model lumi.magnet.acn001
Interview successful: [object Object]


ieee:0x54ef441000282918
nwk:35275 (0x89cb)
model:lumi.magnet.acn001


ieee:0x54ef441000282328
nwk:22919 (0x5987)
model:lumi.magnet.acn001

**Comment by thomasklein1975** [comment]
after update by usage of github no change of states have been detected. No data. 
After deleting and aftr pairing they are undefined.

ieee:0x0x54ef441000282918
nwk:43247 (0xa8ef)
model:unknown

what does ieee and nwk mean exactly?

**Comment by asgothian** [comment]
ieee is the hardware address of the device, like a MAC Address of a network device
nwk is the network internal ID, and part of the encryption between coordinator and the device.

Please ensure that the latest zigbee-herdsman-converters have been installed with the adapter.

A.

**Comment by thomasklein1975** [comment]
thx, how can i get info about converters infos?

in ../zigbee-herdsman-converters/devices/xiaomi.js

`module.exports = [
    {
        zigbeeModel: ['lumi.magnet.acn001'],
        model: 'MCCGQ14LM',
        vendor: 'Xiaomi',
        description: 'Aqara E1 door & window contact sensor',
        fromZigbee: [fz.ias_contact_alarm_1, fz.aqara_opple_report],
        toZigbee: [],
        exposes: [e.contact(), e.battery(), e.battery_voltage()],
    },`

can be found. Should I change to

`{
    zigbeeModel: ['lumi.magnet.acn001'],
    model: 'MCCGQ14LM',
    vendor: 'Xiaomi',
    description: 'Aqara E1 door & window contact sensor',
    fromZigbee: [fz.ias_contact_alarm_1, fz.battery],
    toZigbee: [],
    exposes: [e.contact(), e.battery()],
    configure: async (device, coordinatorEndpoint, logger) => {
      await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genPowerCfg']);
    }`

**Comment by thomasklein1975** [comment]
i did update in file like written above. now after pairing they are back as undefined without any states.
what can i do to use my nes sensors?

**Comment by ninja-warrior** [comment]
Finally, I also figured it out how to enable the new Aqara Window Sensors for my Zigbee Gateway CC1352P-2.

1. Update Zigbee Adapter to lastest version (at least 1.6.8 or 1.6.9 [Fix Aqara Opple Battery Bug])
2. Update Zigbee Gateway CC1352P-2 to latest firmware ([Tool ](https://www.ti.com/tool/download/UNIFLASH) and [Firmware](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin))
3. In my case: Update the "/dev/serial/by-id/..." path in zigbee adapter settings (check out "ls -la /dev/serial/by-id" in cli)
4. In my case: Remove already paired Aqara Window Sensors (only MCCGQ14LM) in zigbee adapter
5. Start pairing process in zigbee adapter (don't forget to press small button on sensors for at least 5 seconds)

Enjoy!

**Comment by Zwitsch** [comment]
> Finally, I also figured it out how to enable the new Aqara Window Sensors for my Zigbee Gateway CC1352P-2.
> 

In my case this doesn't work. I've followed your instructions, but nothing changed. The devices can be paired, but without contact event and battery status.

**Comment by amg666** [comment]
Today I flashed the new version of the FW on my cc2531. Seems that everything works now, I can pair the new sensors and datapoints are updated.
Minor issue: The decimal point of the battery voltage is missing:
![grafik](https://user-images.githubusercontent.com/45561610/147417198-28603034-109a-4df8-ae84-65f9899443a1.png)
At a MCCGQ11LM it is for instance 2.945 v, the new MCCGQ14LM shows 2919 v...

**Comment by asgothian** [comment]
Unit requires latest zigbee firmware on coordinator.

**Comment by amg666** [comment]
I think the FW is actual:
`Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20211115}}`
