### ISSUE TITLE
TS011F not recognized in IOBroker

### ISSUE THREAD

**Issue by tomschlde** [ioBroker/ioBroker.zigbee#1247]
Hi all, conncted a PLUG to Zigbee in IObroker Zigbee  Version 1.56.

`zigbee.0 | 2021-10-29 19:30:18.750 | error | Device 0x0c4314fffe5d94ed "TS011F" not described in statesMapping.`

The device should be supported - it's in the list.
![TS011F](https://user-images.githubusercontent.com/59179041/139479623-a407975e-f761-4a9f-84cf-f573fb48d030.png)

can someone please help.

TIA
Thomas

**Comment by kirovilya** [comment]
update adapter from github

**Comment by tomschlde** [comment]
Works fine after update - thanks.
