### ISSUE TITLE
New Device: TS0601 (Moes_MS-105Z)

### ISSUE THREAD

**Issue by anno171986** [ioBroker/ioBroker.zigbee#1249]
Could you please add the following Device:

https://zigbee.blakadder.com/Moes_MS-105Z.html

Thank you

**Comment by asgothian** [comment]
Did you check if this works ?

if yes - with which adapter version ?

**Comment by anno171986** [comment]
I use the Zigbee Adapter 1.5.6 and the device is connecting as unknown.

Device Information: 
    modelZigbee:TS0601
    type:Router
    nwk:46382
    manuf id:4098
    manufacturer:_TZE200_la2c2uo9
    power:Mains (single phase)
    app version:68
    hard version:1
    zcl version:3
    stack version:0
    date code:
    interviewed:true
    configured:false
    endpoint:1
    profile:260
    input clusters:
    genBasic (0)
    genGroups (4)
    genScenes (5)
    manuSpecificTuya (61184)
    output clusters:
    genOta (25)
    genTime (10)

**Comment by asgothian** [comment]
Please update to the latest GitHub version - it should then be supported.

A.

**Comment by anno171986** [comment]
Thanks, it works
