### ISSUE TITLE
Please add support or fix the problem with TRV from Tuya TS0601 _TZE200_hue3yfsn

### ISSUE THREAD

**Issue by tyros5a** [ioBroker/ioBroker.zigbee#1250]
I'm not sure, is it a problem with zigbee adapter or with other with zigbee-herdsmann-converter.. Thefore I would place my problem here too.

A new model from Tuya Smart Thermostat Radiator Valva does not work in iobroker. It was paired /connected with error messages:
"TS0601" not described in statesMapping.
(18839) Device 0x2c11xxx "TS0601" not described in statesMapping.

modelZigbee:TS0601
type:EndDevice
nwk:51249
manuf id:4098
manufacturer:_TZE200_hue3yfsn
power:Battery
app version:69
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
<img width="1047" alt="Screenshot 2021-10-31 183543" src="https://user-images.githubusercontent.com/92177502/139595428-ee720052-e4c6-45e9-8fda-7e1710412514.png">
![photo_2021-10-31_18-41-21](https://user-images.githubusercontent.com/92177502/139595472-f9d7fcb5-c8c8-443a-bd75-7db93e0fd290.jpg)
![photo_2021-10-31_18-41-27](https://user-images.githubusercontent.com/92177502/139595474-72d04ab7-2768-42f2-bca0-c9c13a2fcaf3.jpg)

Thank you in advance!

**Comment by asgothian** [comment]
Please read here:
https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised

**Comment by asgothian** [comment]
Fixed.
