### ISSUE TITLE
Essentials Smart Radiator Thermostat TS0601 

### ISSUE THREAD

**Issue by THX1183** [ioBroker/ioBroker.zigbee#1259]
Hi, 
I purchased two Radiator Thermostats from "Essentials Smart Home Solutions". I thougt there're different labeled Tuya devices and would work with the Zigbee Adapter in ioBroker. Semms like i was wrong. Can the device be added to the Zigbee adapter?
At the moment, i only get the device connected, but with an error: Device 0x847127fffe10fa0b "TS0601" not described in statesMapping. It is connected but without the needed datapoints. 

Currently installed Zigbee Adapter Version is 1.5.6

Zibee coordinator (CC2531): 
type:zStack30x
version:2-2.2.7.2.
revision:20190425

[Link to the Thermostat](https://www.amazon.de/gp/product/B0816X9ZDF/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)

 Device Infos:
> modelZigbee:TS0601
    type:EndDevice
    nwk:40653
    manuf id:4098
    manufacturer:_TZE200_jeaxp72v
    power:Battery
    app version:83
    hard version:1
    zcl version:3
    stack version:0
    date code:
    interviewed:true
    configured:false

  > endpoint:1
    profile:260
    input clusters:genBasic (0)
    genGroups (4)
    genScenes (5)
    manuSpecificTuya (61184)
    output clusters:genOta (25)
    genTime (10)

thank you!

**Comment by asgothian** [comment]
Please use [this](https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised) cheat sheet to see if they are already supported.

A.

**Comment by Ricox1975** [comment]
Hey, ich habe das T mit Version 1.6.8 gepairt. Nur sind da jede Menge Datenpunkte ohne Funktion.
![T_Esse](https://user-images.githubusercontent.com/52467622/146518191-df32847e-1d53-489c-8ecc-2eb30546aff2.JPG)
