### ISSUE TITLE
Ikea Tradfri Funksteckdose E1603/E1702/E1708, kein Bild

### ISSUE THREAD

**Issue by Kusi-Schweiz** [ioBroker/ioBroker.zigbee#1262]
Seit dem Update auf v1.6.3 wird von der Ikea Tradfri Funksteckdose kein Bild mehr angezeigt in den Einstellungen des Adapters.

![image](https://user-images.githubusercontent.com/71840093/140983435-16b8c68a-e702-4d07-adf5-5c4a0c617233.png)

**Comment by asgothian** [comment]
Please check the link used for the device. The Adapter attempts to generate the link dynamically from the model description, but there may be mismatch between image file name and model description.

A.

**Comment by Kusi-Schweiz** [comment]
Wo sehe ich den Link?

**Comment by Kusi-Schweiz** [comment]
Habe wegen dem Issue #1263 den Adapter vom Link [Zigbee Adapter](https://github.com/asgothian/ioBroker.zigbee) installiert. Nun werden die Bilder angezeigt.

![image](https://user-images.githubusercontent.com/71840093/141659078-c840a627-05fb-45c0-8712-636798611e4d.png)
