### ISSUE TITLE
Gledopto GL-MC-001P

### ISSUE THREAD

**Issue by Kusi-Schweiz** [ioBroker/ioBroker.zigbee#1263]
Untenstehender LED-Leiste lässt sich ein-/ausschalten, jedoch kann man nicht die Farbe ändern.

![image](https://user-images.githubusercontent.com/71840093/140989866-995ae352-0770-450c-87ba-4830b72b0c9d.png)

![image](https://user-images.githubusercontent.com/71840093/140990264-4c1afc19-ccb7-463d-880a-eab0a80cef2a.png)

**Comment by asgothian** [comment]
- Which adapter version ?
- What did you test the color change with (what kind of entry)
- What is the result
- Can you try the intermediate solution presented in issue #1185 thread ?
A.

**Comment by Kusi-Schweiz** [comment]
- Adapterversion ist v1.6.3

Der Datenpunkt *.color lässt sich standardmässig nicht beschreiben.
![image](https://user-images.githubusercontent.com/71840093/141658862-7de2d68b-9db2-4848-8b38-5ca893ac2e08.png)

Ich habe nun "write" auf true gesetzt.
Setze ich den DP auf "blue", ändert sich nichts.
Setze ich den DP auf "#FFFFFF", ändert sich die Farbe einwandfrei.

Mit einem Adapterupdate aus dem Link [Zigbee Adapter](![image](https://user-images.githubusercontent.com/71840093/141659092-2e101f91-d3e1-4f9b-9f0a-65753ab6fdab.png)) lässt sich nun die Farbe mit "blue", "yellow" usw. ändern.

**Comment by asgothian** [comment]
> Mit einem Adapterupdate aus dem Link Zigbee Adapter lässt sich nun die Farbe mit "blue", "yellow" usw. ändern.

Das bedeutet das mit der Testversion das Objekt auch beschreibbar ist ?

A.

**Comment by Kusi-Schweiz** [comment]
Ich würde sage  ja, weil ich habe 2 Leuchten des obigen Typs und bin der Meinung die Attribute "write" nur bei einer manuell geändert zu haben, es funktionieren mit der Testversion jedoch beide.

**Comment by asgothian** [comment]
Should be fixed with current 1.6.7
