### ISSUE TITLE
Error loading settings

### ISSUE THREAD

**Issue by jobe451** [ioBroker/ioBroker.zigbee#1269]
I get the error below:
![Bildschirmfoto vom 2021-11-12 01-24-28](https://user-images.githubusercontent.com/910027/141388187-89f0f748-0951-4872-88c5-fcd577b82050.png)

There was a similar error reported in #1100. However that issue was resolved by a newer admin version. The error I observe is not related to an admin update. It began yesterday. I today upgraded to admin 5.1.28 (from I guess 5.1.25). That did not help. I also restored the iobroker backup from 2 days ago. That did also not work. How can I get to the bottom of this?

**Comment by jobe451** [comment]
The alert happens at this point
![Bildschirmfoto vom 2021-11-12 01-50-42](https://user-images.githubusercontent.com/910027/141390268-2e77393b-47fd-4f2a-ab86-26ba34e8de56.png)

After this response:
![Bildschirmfoto vom 2021-11-12 01-54-11](https://user-images.githubusercontent.com/910027/141390300-124dc06a-18a4-461e-b2e2-5e35a7d1d452.png)

**Comment by asgothian** [comment]
- Which Adapter version did you try this with ?
- Can you please try with the current GitHub version ? A similar error was fixed noon yesterday.
A.

**Comment by jobe451** [comment]
It was this adapter, that is not yet available on the current latest published iobroker.zigbee version on npm:
[ba77234](https://github.com/Koenkk/zigbee-herdsman-converters/commit/ba77234b5dc312313d969c2d77c10d33dc088c3c)

Installing the latest version from github actually resolved the problem! Thanks a lot for the hint!!!
