### ISSUE TITLE
Xiaomi lumi.weather - sensor data are not updated

### ISSUE THREAD

**Issue by Kandy84** [ioBroker/ioBroker.zigbee#127]
Dear Community,
I have CC2531 USB Stick as zigbee coordinator, and several other Xiaomi sensors in my network.

The issue I have is that after reboot of my RPI 3 the lumi.weather sensor data is not updated any more.
As far as I know the sensor data in iobroker will be updated each time when the sensor sends its data.
The lumi.weather should send data if e.g. a temperatur change is detected.
Fore sure between the freezer and my office there is a temperture difference :-) but all the iobroker object data for lumi.weather are still the same

Could anyone help me out here?
Thanks in advance
*----------------------------------------
iobroker zigbee adapter v0.8.0

**Comment by renepauli** [comment]
Same here. No updates anymore....
