### ISSUE TITLE
Wie kann ich eine IAS ACE "Get Panel Status Response" über JS versenden?

### ISSUE THREAD

**Issue by olix74** [ioBroker/ioBroker.zigbee#1272]
Hallo, 
ich habe ein Linkind ZS130000078 Security Key Pad.
Dieses schickt ein "Panel Status Request" auf das ich gerne per JS Script mit einer "Get Panel Status Response" aus dem IAS ACE Cluster antworten würde.
Das Script ist auf die "msg_from_zigbee" registriert und wird getriggered.

Der Panel Status Reuest sieht wie folgt aus:
{"type":"commandGetPanelStatus","data":{},"linkquality":255,"groupID":null,"cluster":"ssIasAce","meta":{"zclTransactionSequenceNumber":4,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}

Jetzt würde ich die Response gerne mit
sendTo("zigbee.0", "sendToZigbee", {...}); oder einer Alternative(?) verschicken.

Leider verstehe ich die Syntax für die Payload nicht und weiß auch nicht, wie ich die zclTransactionSequenceNumber bei der Response angeben kann? Kann mir jemand helfen?

Dem Zigbee Standard habe ich folgende "Fragmente" für die Response entnommen und mal versucht sie zu mappen:  
"cid": "ssIasAce", 
"cmd": "readRsp", 
"cmdType": "foundation", 
"zclData": { "getPanelStatusRsp": {"panelstatus": "0","secondsremain": "10","audiblenotif":"1","alarmstatus":"0"}} 

Danke für Eure Hilfe.
Oliver

**Comment by asgothian** [comment]
A few questions to this: 
- Does this response have to be sent triggered by a message from the keypad or in regular intervals ? 
- What  are the conditions which need to be met to send such a response ?
- Do you see a situation where this response could be automated and sent directly ?

This issue is related to #1234

**Comment by asgothian** [comment]
Possible in latest version (see PR #1283 )
