### ISSUE TITLE
Ikea E1525/E1745 - fehlende exposes

### ISSUE THREAD

**Issue by Butz86** [ioBroker/ioBroker.zigbee#1273]
Hi,
laut dem Projekt zigbee2mqtt können die Bewegungsmelder auch die Werte für die Helligkeit übertragen. Kann man das ergänzen?

https://www.zigbee2mqtt.io/devices/E1525_E1745.html

Requested_brightness_level (numeric)
Requested_brightness_percent (numeric)
Illuminance_above_threshold (binary)

Gruß
Butz

**Comment by asgothian** [comment]
Das kannst du ganz einfach selber ergänzen. Dazu musst du nur den Gerätetyp in die Ausschlussliste (Exclude List) übernehmen, den Adapter neu starten und den State-Cleanup durchführen.

Sobald du das getan hast bekommst du alle Datenpunkte für dieses Gerät ausschliesslich über die Exposes.

A.

**Comment by Butz86** [comment]
Danke. Hat geklappt.

**Comment by schwatter** [comment]
@asgothian 
Wie führe ich den ein State-Cleanup durch?

**Comment by asgothian** [comment]
der rote Knopf :
![Screenshot 2024-07-27 at 17 24 47](https://github.com/user-attachments/assets/7a198c5a-e09d-4141-8acd-b94544bd9922)

**Comment by schwatter** [comment]
Oh sorry, sehe jetzt erst ich bin ioBroker gelandet...
Kämpfe mit dem Sensor + z2m + conbee1. Da die Exposes fehlen.
Bin unzählige Beiträge durch und ausversehen hier gelandet. Habe kein ioBroker.

Gruß

**Comment by asgothian** [comment]
alles gut - wie das bei z2m geht kann ich Dir leider nicht sagen.

A.
