### ISSUE TITLE
Tuya TS0505B unsupported device

### ISSUE THREAD

**Issue by GithubJen** [ioBroker/ioBroker.zigbee#1277]
Hi,
I am trying to connect a Tuya TS0505B via ConBee2 Zigbee Stick to my IOBroker and get the following message when pairing: "0xa4c1381f57fd8203 (addr 10783): Not supported (model TS0505B)(Router)". The device itself was recognized during the pairing process. If I am pairing it via a Hue Bridge the device works fine.

Some extra information:
Installed Version: iobroker.zigbee@1.5.6

Would appreciate your support.

**Comment by asgothian** [comment]
Please install the latest adapter version.

A.
