### ISSUE TITLE
Wrong role value.lux

### ISSUE THREAD

**Issue by nisiode** [ioBroker/ioBroker.zigbee#128]
https://github.com/ioBroker/ioBroker.zigbee/blob/28ea0304f7bbdf422ee2149d2d501babbc7c147e/lib/devstates.js#L312

Shouldn't this better be 'value.brightness' according to the official list of roles: https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md#values-numbers-read-only

**Comment by arteck** [comment]
done
