### ISSUE TITLE
Aqara MCCGQ14LM, Batteriespannung wird nicht korrekt angezeigt.

### ISSUE THREAD

**Issue by e-i-k-e** [ioBroker/ioBroker.zigbee#1280]
Guten Abend,

ich habe zum testen die Adapter Version 1.6.7 installiert um den MCCGQ14LM einzubinden.
Die Spannung wird nicht korrekt angezeigt, hier schein einfach ein Punkt zu fehlen.

![image](https://user-images.githubusercontent.com/83473829/143298446-409f5d92-663a-441d-8938-bab906622013.png)
![image](https://user-images.githubusercontent.com/83473829/143298515-c7e9a2d6-4f3c-4165-9831-b2e2ce50484b.png)
![image](https://user-images.githubusercontent.com/83473829/143298541-0bc805a8-c79c-4a8c-93f8-5dc88b2f161f.png)

**Comment by weindler** [comment]
genau, selbe Problem, habe 4 über banggood gekauft und bei allen 4 ist es so wie oben geschrieben, daß wahrscheinlich der punkt fehlt, so hat man dann 2980V als Beispiel.

**Comment by asgothian** [comment]
Please update to 1.6.11 and verify this is still the case.

A.

**Comment by e-i-k-e** [comment]
Hello A.,

I just updated to the current github version.

The problem is still there.

Regards
![image](https://user-images.githubusercontent.com/83473829/148272866-0d664174-5914-4bd7-9511-2281d751e30c.png)

![image](https://user-images.githubusercontent.com/83473829/148272792-35bb31ed-5465-4f97-98be-c3e6b6b714ab.png)

![image](https://user-images.githubusercontent.com/83473829/148272975-ae276ee3-4eb7-415e-9ea2-7ca417144086.png)

**Comment by weindler** [comment]
ok, dann brauch ich wohl nicht updaten, wenn es in der 1.6.11 Version das selbe ist dann warte ich auf die Stable.

**Comment by asgothian** [comment]
@e-i-k-e Did you verify that the value has been updated by the adapter ? The sensors are known for being slow in updating the value - sometimes an update can take up to 24 hrs.

A.
p.s. I am asking as i cannot verify the behavior - i don't have any of these devices.

**Comment by e-i-k-e** [comment]
@asgothian  Yes i have manuel. But even today, after more than 24 hours, the values ​​are not correct.
It is the case with all 4 sensors of the type

**Comment by Heini1985** [comment]
ich habe das selbe Problem mit der Batterieanzeige.
siehe Bilder:
![image](https://user-images.githubusercontent.com/76739980/148615283-9f9fbf17-5c2c-4b85-a800-858ae89ca3b8.png)
![image](https://user-images.githubusercontent.com/76739980/148615355-af7fdd42-f242-4392-9a69-3cf8ba46d73a.png)

Gruß Heini1985

**Comment by weindler** [comment]
Das Problem ist aber leider noch nicht gelöst und immer noch da, anstatt 2.93V haben diese Sensoren 2931V
