### ISSUE TITLE
null Error in admin 5.1.28

### ISSUE THREAD

**Issue by Tscheurgen** [ioBroker/ioBroker.zigbee#1281]
Hello all!
I'm quite new to iobroker and I'm sorry if this issue was already addressed. But with admin@5.1.28 I receive a null error message when opening the Zigbee Tab. 
I use cc2531 and with admin@5.1.25 everything works fine. I can't downgrade to 5.1.25 because then, my Alexa2 adapter will fail.
Thank you very much for any support!

**Comment by asgothian** [comment]
Which zigbee adapter version are you running ?

**Comment by Tscheurgen** [comment]
I've tried 1.5.6, 1.6.3 and 1.6.6 none is working with admin@5.1.28

**Comment by Tscheurgen** [comment]
Damn... All my problems are gone with the adapter conntected directly to the PC. Before I had connected it to an USB 3.0 Hub. So I close this issue.
