### ISSUE TITLE
Philips Hue WHITE AND COLOR 1100/ LCA006" not described in statesMapping.. undefined

### ISSUE THREAD

**Issue by rmp63526** [ioBroker/ioBroker.zigbee#1288]
Hello, i try to pair the Philips Hue WHITE AND COLOR 1100 bulb without success.

i running zigbee 1.6.6 on a raspberry pi 4, 8gb, with a Texas Instruments board
system fully updated

when pushing the button in zigbee "touchlink zurücksetzten und koppeln" i receive this message  : 

Error: Failed to touchlinkReset Error: SRSP - AF - interPanCtl after 6000ms
    at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7). undefined
Touchlink reset started 

Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
New device joined '0x001788010b1d7bc6' model LCA006
Interview successful: [object Object]
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Pairing time left: 53
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Error: Device 0x001788010b1d7bc6 "LCA006" not described in statesMapping.. undefined
Pairing time left: 54
Device '0x001788010b1d7bc6' announced itself
Interview started: 0x001788010b1d7bc6
Pairing time left: 55
Pairing time left: 56
Pairing time left: 57
Pairing time left: 58
Pairing time left: 59
Pairing time left: 60
Pairing started

**Comment by arteck** [comment]
check new version plz

**Comment by rmp63526** [comment]
@arteck
works Perfect with 1.6.8

thanks a lot for your effort
