### ISSUE TITLE
E1603 IKEA TRADFRI control outlet Support?

### ISSUE THREAD

**Issue by sippi90** [ioBroker/ioBroker.zigbee#129]
Hi there,

I just wanted to ask if the E1603 IKEA TRADFRI control outlet is already supported with this adapter?
The zigbee2mqtt Project implemented this in v 0.1.7 on the 15th of October.
In the supported device List of this project this device doesn't show up.
Has anyone successfully tried paring this plug with ioBroker.zigbee adapter?

Thanks!

**Comment by Michaelnorge** [comment]
+1

**Comment by kirovilya** [comment]
will be in 0.9.0
