### ISSUE TITLE
vesion 1.6.8

### ISSUE THREAD

**Issue by exitus27** [ioBroker/ioBroker.zigbee#1290]
nach update auf 1.6.8 startet iobroker nicht mehr kann es damit zusammen hängen ich habe nur ein update gemacht.

**Comment by Apollon77** [comment]
Was sagen denn die Logs?

**Comment by exitus27** [comment]
Ich komme nicht weiter habe alles gelöscht und neu installiert. Gehört zwar nicht hier hin werden die neuen Aqars Sensoren bei 1.6.8 funktionieren, deswegen habe ich das Update gemacht. Habe sonoff 3.0 usb dongle Firmware 07.2021

**Comment by asgothian** [comment]
Was sagen die Logs. Ohne weitere Informationen wird niemand helfen können.

**Comment by exitus27** [comment]
Ich glaube mittlerweile das es mit sonoff 3.0 Stick zusammen hängt , nach dem Backup aufspielen wieder sonoff Stick eingestellt lief zwar mit alten Datenbank aber Befehle kamen langsam an, nach dem einstecken vom alten zigbee Stick wieder das gleiche Problem. Es könnte damit was Zutun haben.

**Comment by asgothian** [comment]
Closing this. No information, No action.
