### ISSUE TITLE
Gruppen funktionieren nicht ordentlich

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.zigbee#1291]
Ich hatte in der Vergangenheit mal irgendwo gelesen, dass Gruppen noch nicht funktionieren. Ist das immer noch so?
Ich habe eine Gruppe mit 9 Lampen. On/Off funktioniert tadellos, jedoch wird die Helligkeit nicht an die Lampen gesendet.
Was auffällt ist, wenn der `state` der Gruppe auf `false` steht, wird über den `brightness` Datenpunkt die Helligkeit nicht an die Lampen gesendet. Wenn jedoch der `state` der Gruppe auf `true` steht, dann wird die Helligkeit gesendet.

Wiederum wenn ich `brightness` einer einzelnen Lampe von 0 auf 100 verändere, dann geht die Lampe sofort an und der `state` geht auf `true` wie es sein soll.

Adapter v1.6.6

**Comment by asgothian** [comment]
Dieses ist eine zigbee interne Funktion.
- Die Gruppe sendet die Befehle direkt an das Zigbee Netzwerk - nicht im Adapter an jedes einzelne Gerät.
- Ob die Geräte die Änderung von Status (on/off) und Heiligkeit (brightness) an den ioBroker melden hängt vom angeschlossenen Gerät ab. 
- auch ein explizites Abfragen der Helligkeit vom Gerät wenn die Gruppenhelligkeit verändert wurde um die Helligkeit im ioBroker zu aktualisieren wird nicht von allen Leuchtmitteln unterstützt, weswegen diese Funktion nicht eingebaut wurde.


> Was auffällt ist, wenn der `state` der Gruppe auf `false` steht, wird über den `brightness` Datenpunkt die Helligkeit nicht an die Lampen gesendet. Wenn jedoch der `state` der Gruppe auf `true` steht, dann wird die Helligkeit gesendet.

Dieses kann ich weder nachvollziehen noch verstehen. Wenn ich bei meiner Gruppe die Helligkeit anpasse während die Lampe aus ist dann geht die Lampe an. Die Aussage lässt sich auf zweierlei Arten lesen:
- du passt die Gruppenhelligkeit an, die Lampe bleibt aus, der Status der Lampe im ioBroker bleibt "off" - Dieses wäre ein Verhalten der benutzten Leuchtmittel.
- du passt die Gruppenhelligkeit an, die Lampe geht an, der Status der Lampe im ioBroker bleibt "off" - Dieses ist im Moment explizit so implementiert.
Bei einzelnen Lampen gibt es eine künstliche Verbindung zwischen "brightness" und "on", so das bei den Lampen die das benötigen ein Verändern der Helligkeit von 0 weg die Lampe einschaltet (und umgekehrt). Da nicht klar ist ob die Leuchtmittel in einer Gruppe dieses Verhalten benötigen wurde es in der Gruppe nicht umgesetzt.

A.

**Comment by Schmakus** [comment]
Danke für die ausführliche Antwort. Ich werde das mal testen und Rückmelden.
