### ISSUE TITLE
Version 1.6.8 Bug Battery Percent Aqara Opple 0%

### ISSUE THREAD

**Issue by railin** [ioBroker/ioBroker.zigbee#1293]
Nach dem Update des Zigbee Adapters im ioBroker von Version 1.6.6 auf 1.6.8 das Problem, dass beim Schalter Aqara Opple der Datenpunkt Battery Percent nur noch mit 0% angegeben wird. Vorher 100% mit neuer Batterie. Alle anderen Aqara Produkte OK.
Wenn ich zurück gehe auf 1.6.6 Anzeige wieder auf 100%. Problem bestätigt von einem weiteren Nutzer.

**Comment by Frank795** [comment]
Kann ich bestätigen mit dem Opple 6-fach Taster

**Comment by asgothian** [comment]
Please run the following tests (on either adapter version)

- add the device to the exclude list (Ausschliessen Tab)
- restart the zigbee adapter
- run the "state cleanup" (blue button with two arched arrows) to remove non-connected states
- check if / how battery data is being presented.

Also - please verify which zigbee-herdsman-converters versions are installed when running with 1.6.6 and 1.6.8. I am not aware of any changes which should show this effect.
(you can find the respective version information either in `/opt/iobroker/node_modules/zigbee-herdsman-converters/package.json` or `/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/package.json`

A.

**Comment by railin** [comment]
> Please run the following tests (on either adapter version)
> 
> * add the device to the exclude list (Ausschliessen Tab)
> * restart the zigbee adapter
> * run the "state cleanup" (blue button with two arched arrows) to remove non-connected states
> * check if / how battery data is being presented.
> 
> Also - please verify which zigbee-herdsman-converters versions are installed when running with 1.6.6 and 1.6.8. I am not aware of any changes which should show this effect. (you can find the respective version information either in `/opt/iobroker/node_modules/zigbee-herdsman-converters/package.json` or `/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/package.json`
> 
> A.

Version 1.6.6
- version zigbee-herdsman-converter:14.0.316
Under objects: zigbee.0.04cf8cdf3c77bfe6.battery: 100%
Card for Opple under Zigbee shows Icon for Battery Level with 100 %
- device excluded, zigbee adapter restartet etc: 
Everything ok. Same things are shown as described above, no changes.

Version 1.6.8
- version zigbee-herdsman-converter:14.0.339
Under objects: zigbee.0.04cf8cdf3c77bfe6.battery: 0%
Card for Opple under Zigbee shows no Icon for Battery Level and no number
- device excluded, zigbee adapter restartet etc: 
Same errors as described above, no changes

**Comment by arteck** [comment]
1.6.9 works
