### ISSUE TITLE
OSRAM Lightify - AC03641-DIM (NOT AC03641) unsupported

### ISSUE THREAD

**Issue by MrTweek1987** [ioBroker/ioBroker.zigbee#1294]
When i try to Pair a OSRAM Lightify bulb AC03641-DIM it will fail... afaik its basicaly a 03641 as far i can remember...
Error: Device 0x7cb03eaa0a0433d5 "undefined" not described in statesMapping.. undefined

**Comment by MrTweek1987** [comment]
After editing osram.js and add 'AC036-DIM' as copy of AC03641

it works...
Pairing time left: 47
```
New device joined '0x7cb03eaa0a0433d5' model AC03641
Interview successful: {"friendly_name":"0x7cb03eaa0a0433d5","model":"AC03641","vendor":"OSRAM","description":"LIGHTIFY LED Classic A60 clear","supported":true}
Pairing time left: 48
Pairing time left: 49
Pairing time left: 50
Device '0x7cb03eaa0a0433d5' announced itself
Interview started: 0x7cb03eaa0a0433d5```

**Comment by asgothian** [comment]
Please post this at the [zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters) project and/or make a PR so that other people can benefit from your work.

A.

**Comment by MrTweek1987** [comment]
I added a Pull Request for this [PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3507)

**Comment by asgothian** [comment]
Thank you. Closing this.

**Comment by bastian1607** [comment]
Hi,
just bought also AC03641-DIM from Ledvance, but do not get this going after editing your code to osram.js. 
Any recommendations, @MrTweek1987 ? Still getting the error.

**Comment by bastian1607** [comment]
Managed now with blanks 

{
    zigbeeModel: ['Classic A60 W clear - LIGHTIFY'],
    model: 'AC03641 - DIM',
    vendor: 'OSRAM',
    description: 'LIGHTIFY LED Classic A60 clear',
    extend: extend.ledvance.light_onoff_brightness(),
    ota: ota.ledvance,
}
