### ISSUE TITLE
Xiaomi Aqara DJT11LM

### ISSUE THREAD

**Issue by cimba007** [ioBroker/ioBroker.zigbee#130]
Hello,

i just set up my park of aqara sensors and noticed that the DJT11LM sensor has a sensitivity setting. Is it possible to change this trough iobroker?

https://koenkk.github.io/zigbee2mqtt/information/mqtt_topics_and_message_structure.html#xiaomi-aqara-vibration-sensor-djt11lm

https://github.com/Koenkk/zigbee2mqtt/issues/295

**Comment by emddummi** [comment]
Possible with new developer options?

**Comment by tiagofreire-pt** [comment]
@emddummi and @cimba007, check this: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#xiaomi-aqara-vibration-sensor-djt11lm
