### ISSUE TITLE
zigbee.0.84fd27fffe813be7.color nicht beschreibbar

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/ioBroker.zigbee#1300]
Hi ich benutze ein script was HSV in Hex umwandelt, und jedes mal wenn ich zb mit Yahka die Lampe steuern will kommt diese Fehlermeldung.
![Bildschirmfoto 2021-12-17 um 15 08 26](https://user-images.githubusercontent.com/62701386/146556557-97e92a69-ddda-4a1c-b2e2-b861f9b0c834.png)

Wieso ist der Datenpunkt read-only und was kann man da machen?

**Comment by asgothian** [comment]
Welche Adapter Version setzt du ein ?

A.

**Comment by Trunks1982** [comment]
Hatte 1.6.6 draufhatte gerade mal auf 1.6.9 upgedatet und ich meine da war es auch.
Das Device ist es, wenn es weiter hilft
![Bildschirmfoto 2021-12-17 um 16 06 50](https://user-images.githubusercontent.com/62701386/146564924-66498f8c-3696-486d-8089-6fe4a4ae4e95.png)

**Comment by M1cS0w** [comment]
Schließe mich an. Mit Version 1.5.6. ging es noch. Laut eines Beitrages hier, hieß es ab 1.6.7 soll es wieder gehen. Aber mit 1.6.9 ist es wohl immernoch nicht gefixt? Sind da Pläne oder gibt es einen Lösungsansatz? Ich hab rgb(255,255,255) sowie #FFFFFF probiert, nichts geht mehr :(

**Comment by Trunks1982** [comment]
Fürs erste geht es wenn due unter raw daten write auf true setzt.

**Comment by M1cS0w** [comment]
> Fürs erste geht es wenn due unter raw daten write auf true setzt.

Das war mein erster Versuch, als ich nämlich die Infos gesehen habe, hab ich in den RAW Daten auf true gesetzt, und es änderte leider nichts. War ja solch eine Verwunderung, aber auch beim Update auf 1.6.6 gibt es zich Errors und Warnings

**Comment by asgothian** [comment]
@M1cS0w These messages are "normal" - they are warnings generated by compilation of the serialport library which is used to access the hardware.

While it is not good that they are present  there is nothing we can do.

- Is the affected lamp the same one as with @Trunks1982 ?
- what happens if you add the lamp to the exclude list (adapter configuration, exclude tab (ausschließen), add the device type, restart the adapter.

The fix for the issue which originally caused this is still in place and working.

A.

**Comment by M1cS0w** [comment]
> @M1cS0w These messages are "normal" - they are warnings generated by compilation of the serialport library which is used to access the hardware.
> 
> While it is not good that they are present there is nothing we can do.
> 
> * Is the affected lamp the same one as with @Trunks1982 ?
> * what happens if you add the lamp to the exclude list (adapter configuration, exclude tab (ausschließen), add the device type, restart the adapter.
> 
> The fix for the issue which originally caused this is still in place and working.
> 
> A.

Hi, I got this problem with GL-C-008P.
When I add the LED Controller to the exclude list, and after checking that write is also true, the same issue is still there.

**Comment by M1cS0w** [comment]
Update:

I have now installed the version 1.6.8 and it now works, installation was without any warnings and errors, like normal ;)
