### ISSUE TITLE
Batteriestand bei Aqara Opple wird nicht mehr angezeigt V1.6.8 

### ISSUE THREAD

**Issue by janwilke** [ioBroker/ioBroker.zigbee#1304]
Hallo zusammen,

zum testen habe ich mal die V1.6.8 installiert.
Damit wird leider der Batteriestand beim Aqara Opple 6-fach Taster) nicht mehr angezeigt.

Was wird benötigt, um hier ins Detail einzusteigen? Welche Logs etc?
Als Anfang habe ich mal das silly Zigbee-Log hochgeladen...
https://pastebin.com/j19AMbnb

Danke und viele Grüße
Jan

**Comment by MMeinhardt1** [comment]
Hi, hier bei mir das gleiche. Nach heutigem Update des Adapters stehen die Werte auf 0%. 

Danke

**Comment by ninja-warrior** [comment]
Fixed with 1.6.9

**Comment by janwilke** [comment]
Fixed with 1.6.9 - Retest successful
