### ISSUE TITLE
List CC2530 and CC2531 under "Legacy support" and comment them with "not recommended"?

### ISSUE THREAD

**Issue by Hedda** [ioBroker/ioBroker.zigbee#1305]
Suggest to list CC2530 and CC2531 in a "Legacy support" subsection under compatible hardware and comment them with a "not recommended" explanation.

https://github.com/ioBroker/ioBroker.zigbee/blob/master/README.md

https://www.iobroker.net/#en/adapters/adapterref/iobroker.zigbee/README.md

https://www.iobroker.net/#de/adapters/adapterref/iobroker.zigbee/README.md

Zigbee2MQTT community have recently added such recommendations with arguments that while CC2530 and CC2531 based Zigbee coordinator adapters still work in many scenarios they are no longer recommended by the Zigbee2MQTT community at all since they use outdated chips and older firmware. 

https://github.com/zigpy/zigpy-znp/blob/dev/README.md#hardware-requirements

https://www.home-assistant.io/integrations/zha#known-working-zigbee-radio-modules

The point here is to discourage new users from going out and buying CC2530 and CC2531 based adapters, (which they continue to do, presumably because they remain the most inexpensive and most readily available Zigbee coordinator adapters out there).

Thus might be a good idea for ioBroker to update compatibility lists in documentation by adding a clear recommendation that  CC2530 and CC2531 are not recommended in a "production" environment (since not powerful enough and firmware upgrades or bug-fixes had no longer been provided by the manufacturer for a long time now). Hopefully, this will encourage new users and beginners to instead buy newer CC26x2 and CC13x2 based adapters instead.

References:

https://www.zigbee2mqtt.io/guide/adapters/#not-recommended

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/README.md#im-using-a-cc2530-or-cc2531-which-firmware-should-i-use

Note that Zigbee2MQTT community is now even listing CC2538 as "not recommended" in favour of newer CC26x2 and CC13x2 based adapters instead in order so that new users do not go out and blindly buy old CC2538 hardware as their first Zigbee coordinator just because it is listed as compatible hardware. The last Z-Stack update for CC2538 was released more than three years ago and it will not support the newer route discovery features that improve network stability because the version of Z-Stack that it is stuck with supposedly has glitches.

**Comment by asgothian** [comment]
Merged.
