### ISSUE TITLE
Lidl HG06106C Color Bulb  - ColorMode

### ISSUE THREAD

**Issue by sir0drake** [ioBroker/ioBroker.zigbee#1306]
Hello,
just bought a couple of lights identified as **HG06106C**.

So far all fine.
**I am missing the current color-mode-status of the device.**
it is available from developer-page.

device = as descriped above
endpoint = 1
ClusterID = lightingColorCtrl (768)
command = read (0)
Attribute ID = colorMode (8, type 48)

Log-Shows following results

SUCCESS {"colorMode":1}      if a color-value (Hex) was set  = ColorMode
SUCCESS {"colorMode":2}      if a colortemp-value was set    = WhiteMode

found following code in lidl.js
but dont know what and how to modify to get the above new status,
to know finally the current "color-mode"   ( ct or white maybe ).

    {
        fingerprint: [{modelID: 'TS0505A', manufacturerName: '_TZ3000_dbou1ap4'}],
        model: 'HG06106C',
        vendor: 'Lidl',
        description: 'Livarno Lux E27 bulb RGB',
        ...extend.light_onoff_brightness_colortemp_color({disableColorTempStartup: true}),
        meta: {applyRedFix: true, enhancedHue: false},
        configure: async (device, coordinatorEndpoint, logger) => {
            device.getEndpoint(1).saveClusterAttributeKeyValue('lightingColorCtrl', {colorCapabilities: 29}
			);
        },
    },

thanks in advance
drake

**Comment by asgothian** [comment]
The color mode is not commonly exposed to the adapter on any of the devices. Can you please elaborate as to what to use this setting for ?

**Comment by sir0drake** [comment]
hello, the simplest scenario is when the zigbee instance restarts. Only the lamp itself knows which light is currently emitting if the lamp was in state=true before ( enabled ). Since it is a pure read-only mode and only applies to devices that emit color and white, I would be grateful for a reflection on the state level.

**Comment by sir0drake** [comment]
any suggestion?

**Comment by asgothian** [comment]
Not yet - this is a reasonably major change in the zigbee-herdsman-converters, and potentially affects all color lightbulbs implemented there. I did not have sufficient time to check this.

A.

**Comment by sir0drake** [comment]
thank's for your feedback !

**Comment by asgothian** [comment]
Which of the three following statements is a correct interpretation of you closing this issue ?
- you will follow this up at the zigbee-herdsman-converters yourself
- you will shelve this for the time being
- you will try to find a different solution 

A.
Note that i do see the benefit of such a state, but with the current issues regarding type casting, groups and polling blocking my time it will take some time to make any headway.

**Comment by sir0drake** [comment]
Dear asgothian,
"will shelve this for the time being."

i also see the benefit, but i am not able to develop/modify it by myself.
I will keep an eye on it.

i understand your point, that it will have effect to all color lightbulbs from this company
and this mean a lot of testing etc....

pls give me a hint, once you notice some progress into this issue.

best regards

**Comment by asgothian** [comment]
Will do.

As a side note: Introducing this state would not only affect Lidl Lightbulbs but **any** zigbee Light which supports more than one color mode. Once this option is available for a set of Lights people will want to have this for as many as possible. 

best regards

A.
