### ISSUE TITLE
"not described in statesMapping" for supported device QS-Zigbee-C01? 

### ISSUE THREAD

**Issue by e-i-k-e** [ioBroker/ioBroker.zigbee#1310]
Hallo zusammen,
mir ist bereits bei der letzten Lieferung von zwei QS-Zigbee-C01 aufgefallen, dass ich beim anlernen erst immer folgendes erhalte. 
"...not described in states mapping.. undefined", die gleiche Meldung erhalte ich bei der heute eingetroffenen Geräten auch.

![1](https://user-images.githubusercontent.com/83473829/147274253-a22fb01e-8c4b-45b1-8e5f-451b276d915f.JPG)
![2](https://user-images.githubusercontent.com/83473829/147274263-cbc0230b-09d5-4315-9bde-59c0014c31c0.JPG)
![image](https://user-images.githubusercontent.com/83473829/147274296-a0f80be3-538f-4285-aac0-3841277bea97.png)
![image](https://user-images.githubusercontent.com/83473829/147274361-270bca32-5f9e-49a4-8e76-fea2bfea3011.png)

Ich verwenden die aktuelle Zigbee Version 1.6.9.

Bin mir nicht sicher, was genau diese Meldung bedeutet. Habe aber das Problem, dass diese Geräte sporadisch nicht mehr verbunden sind - obwohl die Netzabdeckung in dem Bereich sehr gut ist!

Viele Grüße

**Comment by asgothian** [comment]
Die Meldung kommt bei der initialen Kommunikation unter bestimmten Randbedingungen wenn eine Nachricht an den ioBroker weitergereicht wird bevor das Gerät vollständig angebunden ist. Sie sollte mit dem sporadischen Disconnect nichts zu tun haben.

A.

**Comment by e-i-k-e** [comment]
Hallo,
meine Tochter hat versehentlich eine Ikea TRADFRI E27 (Typ weiß ich gerade nicht) zurück gesetzt, diese ist schon seit Ewigkeiten in meinem Besitz und hat nie Probleme gemacht. 

Diese wollte ich somit neu anlernen, hier erhalte ich auch plötzlich einen Fehler. 
Hat das auch etwas damit zutun? 
![image](https://user-images.githubusercontent.com/83473829/147474217-3b9430bc-81a9-4cc3-b1b3-430d89441c20.png)

**Comment by asgothian** [comment]
Erneut versuchen - irgendwie antwortet die Lampe nicht auf alle Anfragen beim Interview.

A.

**Comment by e-i-k-e** [comment]
Okay. Hatte tatsächlich nichts mit dem oben beschrieben Fehler zutun.

Ich kann über den "moving" Datenpunkt, den Aktor (QS-Zigbee-C01) nicht steuern und erhalte folgende Meldungen im log.
`<html>
<body>


zigbee.0 | 2021-12-29 17:30:20.076 | error | (53336) No converter available for 'QS-Zigbee-C01' with key 'moving'
-- | -- | -- | --
zigbee.0 | 2021-12-29 17:29:53.860 | warn | (53336) A 60a423fffe7ddd1d 0x60a423fffe7ddd1d
zigbee.0 | 2021-12-29 17:29:05.151 | error | (53336) No converter available for 'QS-Zigbee-C01' with key 'moving'
zigbee.0 | 2021-12-29 17:28:56.095 | error | (53336) No converter available for 'QS-Zigbee-C01' with key 'msg_from_zigbee'
zigbee.0 | 2021-12-29 17:28:52.379 | error | (53336) No converter available for 'QS-Zigbee-C01' with key 'moving'


</body>
</html>`

Über "position" ist es aber weiterhin möglich. 

Ich verwende die aktuelle Version aus github und es hat definitiv "früher" über den Datenpunkt funktioniert.

**Comment by arteck** [comment]
es MUSS immer ein Gerät kommen.. kein UNDEFINED
