### ISSUE TITLE
Osram LIGHTIFY Surface Light TW not detected correctly

### ISSUE THREAD

**Issue by smoki3** [ioBroker/ioBroker.zigbee#1311]
Hi,

my OSRAM LIGHTIFY Surface Light TW ist not detected as model 4052899926158. It is detected as Model ZLO-CeilingTW-OS.

![image](https://user-images.githubusercontent.com/9723729/147403091-bb058f4b-2a95-4735-95d5-e5b62fe8171f.png)

**Comment by asgothian** [comment]
Looking at the data, it seems you bought a chinese knockoff, rather than a genuine Osram light. The posted data clearly shows that it is not an osram device. None of the reported data matches that of a genuine Osram device.

A

**Comment by smoki3** [comment]
It's definitely a genuine device. And also it was working fine with the Osram gateway and phoscon

**Comment by smoki3** [comment]
the device is also listed here in firmware section

https://www.osram.de/cb/lightify/lightify-home/lightify-home-faq/lightify_home_faqs.jsp

**Comment by asgothian** [comment]
the data you posted does not match an osram device. Either you posted the wrong data or it is not a genuine device. Note that the device working with osram and/or phoscon says little towards it being genuine.

No device reporting the data you posted exists in the zigbee2mqtt device definition.

A.

**Comment by smoki3** [comment]
![image](https://user-images.githubusercontent.com/9723729/147416335-254e44bc-3d50-4697-9142-1a85f8775538.png)

this is the data from the OSRAM website. Dont know if my device have the latest firmware. Maybe the changed something later.

I am able to control the device via the dev tab.

**Comment by asgothian** [comment]
Makes it an issue for the zigbee-herdsman-converters project.

A.

**Comment by asgothian** [comment]
Supported with 1.6.11
