### ISSUE TITLE
Tradfri Dimmer "state" state not triggered, if same key pressed again

### ISSUE THREAD

**Issue by tarikweiss** [ioBroker/ioBroker.zigbee#1313]
Bug:
Tradfri "state" state is not triggering any event. This means, if you press "on" or "off" key twice, then it wouldn't be written on the second time.

Steps to reproduce:
- Take a tradfri dimmer (as described in the link)
- Press "on" ("I") key on the remote
- State "state" is lighting "green" in iob objects list (so event is getting triggered) and value is set to "true"
- Press "on" ("I") key on the remote again
- Then msg_from_zigbee is triggered, but value is not written into "state" again.

https://www.ikea.com/de/de/p/tradfri-kabelloser-dimmer-weiss-70408595/

**Comment by asgothian** [comment]
- Which adapter version are you using ?
- what messages are generated if the IEEE of the device is entered into the state `zigbee.0.info.debugmessages`
- did you verify with a trigger that the state is not being updated ? The admin display alone is a weak indicator if a value was updated.
A.

**Comment by tarikweiss** [comment]
Hey,

- I'm using v. 1.6.8,
- What do I need to do, to get this state?
- I verified it using a script and the function "on". I added a listener for the "state" state and the on function has not been triggered. I got aware of this issue, as I had a script which should trigger lights

Thx

**Comment by asgothian** [comment]
You already have this state. It is a state in your object tree.

Once you enter the correct information into the object tree, warn messages with the keyword "ELEVATED" should appear for every message sent by the Device.

A.

**Comment by tarikweiss** [comment]
Hey,
The debugmessage state is always null. What do I need to configure?
I added a listener for state changes in the scripts adapter using the method "on".

**Comment by tarikweiss** [comment]
Btw, that's my script I use for switching the light:

`
var zigbeeInstance = 'zigbee.0.';

var lightDeviceMac = zigbeeInstance + '7cb03eaa0a050efb';
var remoteDeviceMac = zigbeeInstance + 'b4e3f9fffe890cd3';

on(remoteDeviceMac + ".state", function(obj) {
    var stateNodeName = lightDeviceMac + '.state';
    setState(stateNodeName, obj.state.val);
    
    return;
});
`

**Comment by tarikweiss** [comment]
Bounce.

**Comment by Apollon77** [comment]
Bounce back ... ???

**Comment by Apollon77** [comment]
PS: YOu know that this style of "subscription" only triggers on changeof the value?? So IF the state is retriggered with "True" on next press (and here I have no idea if it is that way) then the reason is your subscription.

Maybe try

```
on({id: myId, change: 'any}, ...)
```

**Comment by tarikweiss** [comment]
Okay, I will try that. Thank you. Sorry for that inappropriate comment. I was a bit frustrated, because  no one answered and explained what I should provide furthermore. Thank you @Apollon77

**Comment by Apollon77** [comment]
In the future admin is the best place to check if there is an update - because then the value shows green short ... ELse it is a script support question :-)
