### ISSUE TITLE
Blitzwolf BW SHP13 - keine Messwerte

### ISSUE THREAD

**Issue by Ricox1975** [ioBroker/ioBroker.zigbee#1314]
Seit dem Sprung auf 1.6.10 liefern die Plugs keine aktuellen Messwerte mehr. Laufenden Messwerte sind seit dem upgrade eingefroren. auf 1.6.8 alles i.O.

**Comment by asgothian** [comment]
Please install the 1.6.10 again. This issue should be fixed.

A.
