### ISSUE TITLE
Busch Jäger - RM01 -> brightness" has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by Newan** [ioBroker/ioBroker.zigbee#1315]
Habe den Schalter Busch Jäger hinzugefügt zum Adapter v1.6.10
brightness funktioniert aber die Meldungen im LOG. Was noch auffällt ist, wenn man den Dimmlevel anhebt gehen die Lichter an aber der Schalter für die erste Wippe bleibt auf false?

```
zigbee.0 | 2021-12-29 14:10:19.583 | info | Zigbee: stop joining
zigbee.0 | 2021-12-29 14:09:59.321 | info | State value to set for "zigbee.0.d85def11a10046b1.brightness" has to be type "number" but received type "string"
zigbee.0 | 2021-12-29 14:09:59.283 | info | State value to set for "zigbee.0.d85def11a10046b1.brightness" has to be type "number" but received type "string"
zigbee.0 | 2021-12-29 14:09:52.253 | error | Send command to 0xd85def11a10046b1 failed with no error code (undefined)
zigbee.0 | 2021-12-29 14:09:52.243 | info | State value to set for "zigbee.0.d85def11a10046b1.brightness" has to be type "number" but received type "string"
zigbee.0 | 2021-12-29 14:08:55.165 | info | DeviceConfigure successful 0xd85def11a10046b1 RM01
zigbee.0 | 2021-12-29 14:08:53.211 | info | Configuring 0xd85def11a10046b1 RM01
zigbee.0 | 2021-12-29 14:08:53.211 | info | Device '0xd85def11a10046b1' is supported, identified as: Busch-Jaeger Zigbee Light Link power supply/relay/dimmer (6735/6736/6737)
zigbee.0 | 2021-12-29 14:08:53.210 | info | Successfully interviewed '0xd85def11a10046b1', device has succesfully been paired
zigbee.0 | 2021-12-29 14:08:39.533 | warn | Device '0xd85def11a10046b1' announced itself

```

**Comment by arteck** [comment]
stoppe den adapter
lösche das object und
starte den adapter

der Datenpunkt sollte jetzt neu und richtig angelegt werden

**Comment by Newan** [comment]
Ja Datenpunkte wurden neu angelegt.

Wenn ich aber state = false habe und setze das Dimmlevel auf > 0 beispielsweise 40.. müsste eigentlich state auf true wechseln, da das Licht angeht. Macht es aber nicht.
Andersrum auch nicht state=true und DImmlevel auf 0 .> müsste state auf false gehen.

![image](https://user-images.githubusercontent.com/3693094/147928062-d7d7a6cd-c1d1-4661-afca-fa7afbc997de.png)

Was auch nicht aktualisiert wird ist Brightness, wenn man am Taster den Wert verändert. DEr WErt kommt aber aus Zigbee, siehe:
![image](https://user-images.githubusercontent.com/3693094/147929492-c09c150c-b94b-4648-b296-93f1c75ac06a.png)

254 ist 99%, beliebt aber bei 30 % stehen und wird nicht aktualisiert.

Helfe gerne, aber ist das ioBroker logik oder herdsman?

**Comment by asgothian** [comment]
Um das heraus zu bekommen musst du die IEEE des Gerätes (ohne führendes 0x) in den State `zigbee.0.info.debugmessages` eintragen.  Dann bekommst Du die vom Herdsman gemeldeten Events als Warnmeldungen im ioBroker Log mit (Schlüsselwort ist "ELEVATED"). Es ist denkbar das der Herdsman die ReadResponse Meldungen ignoriert und daraus keine Datenpunktänderungen auslöst.

A.

**Comment by Newan** [comment]
Hier der LOG:
<html>
<body>


zigbee.0 | 2022-01-05 21:52:28.943 | warn | ELEVATED publishToState: message received '{"brightness_relay":51}' from device d85def11a10046b1 type '6735/6736/6737'
-- | -- | -- | --
zigbee.0 | 2022-01-05 21:52:28.940 | warn | ELEVATED publishToState: value generated '127' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:28.939 | warn | ELEVATED publishToState: message received '{"linkquality":127}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:28.880 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:28.878 | warn | ELEVATED publishToState: value generated '127' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:28.877 | warn | ELEVATED publishToState: message received '{"linkquality":127}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:23.938 | warn | ELEVATED publishToState: message received '{"brightness_relay":51}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:23.935 | warn | ELEVATED publishToState: value generated '123' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:23.935 | warn | ELEVATED publishToState: message received '{"linkquality":123}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:23.896 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:23.892 | warn | ELEVATED publishToState: value generated '123' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:23.892 | warn | ELEVATED publishToState: message received '{"linkquality":123}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:18.954 | warn | ELEVATED publishToState: message received '{"brightness_relay":181}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:18.951 | warn | ELEVATED publishToState: value generated '127' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:18.951 | warn | ELEVATED publishToState: message received '{"linkquality":127}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:18.876 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:18.873 | warn | ELEVATED publishToState: value generated '123' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:18.873 | warn | ELEVATED publishToState: message received '{"linkquality":123}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:13.945 | warn | ELEVATED publishToState: message received '{"brightness_relay":211}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:13.941 | warn | ELEVATED publishToState: value generated '120' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:13.939 | warn | ELEVATED publishToState: message received '{"linkquality":120}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:13.898 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:13.897 | warn | ELEVATED publishToState: value generated '116' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:13.897 | warn | ELEVATED publishToState: message received '{"linkquality":116}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:08.957 | warn | ELEVATED publishToState: message received '{"brightness_relay":211}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:08.951 | warn | ELEVATED publishToState: value generated '116' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:08.951 | warn | ELEVATED publishToState: message received '{"linkquality":116}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:08.881 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:08.878 | warn | ELEVATED publishToState: value generated '112' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:08.878 | warn | ELEVATED publishToState: message received '{"linkquality":112}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:03.934 | warn | ELEVATED publishToState: message received '{"brightness_relay":211}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:03.931 | warn | ELEVATED publishToState: value generated '120' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:03.930 | warn | ELEVATED publishToState: message received '{"linkquality":120}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:03.875 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:52:03.873 | warn | ELEVATED publishToState: value generated '116' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:52:03.872 | warn | ELEVATED publishToState: message received '{"linkquality":116}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:58.934 | warn | ELEVATED publishToState: message received '{"brightness_relay":211}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:58.932 | warn | ELEVATED publishToState: value generated '116' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:51:58.932 | warn | ELEVATED publishToState: message received '{"linkquality":116}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:58.882 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:58.879 | warn | ELEVATED publishToState: value generated '116' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:51:58.879 | warn | ELEVATED publishToState: message received '{"linkquality":116}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:53.951 | warn | ELEVATED publishToState: message received '{"brightness_relay":211}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:53.946 | warn | ELEVATED publishToState: value generated '116' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:51:53.946 | warn | ELEVATED publishToState: message received '{"linkquality":116}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:53.878 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:53.875 | warn | ELEVATED publishToState: value generated '116' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:51:53.874 | warn | ELEVATED publishToState: message received '{"linkquality":116}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:48.932 | warn | ELEVATED publishToState: message received '{"brightness_relay":211}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:48.928 | warn | ELEVATED publishToState: value generated '116' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:51:48.928 | warn | ELEVATED publishToState: message received '{"linkquality":116}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:48.879 | warn | ELEVATED publishToState: message received '{"state_relay":"ON"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-05 21:51:48.878 | warn | ELEVATED publishToState: value generated '112' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-05 21:51:48.876 | warn | ELEVATED publishToState: message received '{"linkquality":112}' from device d85def11a10046b1 type '6735/6736/6737'

</body>
</html>

Nach dem letzte '{"brightness_relay":51}'  sollte der Wert ja relativ weit unten sein. Ist aber bei 90%:

![image](https://user-images.githubusercontent.com/3693094/148287977-a78a9fa1-8426-40e8-a895-6dfae511f1e6.png)

**Comment by asgothian** [comment]
Note that neither the "state_relay":"ON" message nor the "brigthness_relay" :"xx" generate any `value generated 'xx' from device d85def11a10046b1` message, i.e. there doesn't seem to be a state linked to them.
Please check the state definition for these states that they match the "state_relay" and "brightness_relay" property.

A.

**Comment by Newan** [comment]
ok it is so, any changes on the device not send to ioBroker:

state_relay -> state (in ioBroker)
brigthness_relay -> (100/255) * brigthness_relay -> brightness (in ioBroker)

Where i can change it, in herdsmann?

**Comment by Newan** [comment]
ok if i use something like this:

rm01_brightness: {
        id: 'brightness_relay',
        name: 'Brightness',
        icon: undefined,
        role: 'level.dimmer',
        write: true,
        read: true,
        type: 'number',
        unit: '',
        min: 0,
        max: 100,
        getter: payload => {
            return utils.bulbLevelToAdapterLevel(payload.brightness_relay);
        },
}
i get the value in an objekt "brightness_relay". But if i change the value, nothing on the dimmer (hardware) chnage. Only the brightness object chnage the light level (set value from iobroker)
Is it possbile to write an getter function in brightness for the rm01 device?

![image](https://user-images.githubusercontent.com/3693094/148297885-a1028433-477c-4a60-9b54-039e26e5a9fa.png)

**Comment by asgothian** [comment]
Please test:

- add the RM01 device to the list of excluded devices (There is a tab "exclude" or "Ausschliessen" in german - click the plus to add the device to this list)
- restart the zigbee adapter
- use the state cleanup button to remove unlinked states in the zigbee namespace
- check if the state changes are now updated correctly.

A.

**Comment by Newan** [comment]
Test Result:

<html><body>


zigbee.0 | 2022-01-07 14:03:10.360 | warn | ELEVATED publishToState: message received '{"brightness_relay":254}' from device d85def11a10046b1 type '6735/6736/6737'
-- | -- | -- | --
zigbee.0 | 2022-01-07 14:03:10.359 | warn | ELEVATED publishToState: value generated '109' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-07 14:03:10.359 | warn | ELEVATED publishToState: message received '{"linkquality":109}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:10.291 | warn | ELEVATED publishToState: message received '{"state_relay":"OFF"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:10.290 | warn | ELEVATED publishToState: value generated '109' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-07 14:03:10.289 | warn | ELEVATED publishToState: message received '{"linkquality":109}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:05.342 | warn | ELEVATED publishToState: message received '{"brightness_relay":254}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:05.341 | warn | ELEVATED publishToState: value generated '109' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-07 14:03:05.340 | warn | ELEVATED publishToState: message received '{"linkquality":109}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:05.306 | warn | ELEVATED publishToState: message received '{"state_relay":"OFF"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:05.305 | warn | ELEVATED publishToState: value generated '109' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-07 14:03:05.305 | warn | ELEVATED publishToState: message received '{"linkquality":109}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:00.330 | warn | ELEVATED publishToState: message received '{"brightness_relay":254}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:00.328 | warn | ELEVATED publishToState: value generated '105' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-07 14:03:00.328 | warn | ELEVATED publishToState: message received '{"linkquality":105}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:00.277 | warn | ELEVATED publishToState: message received '{"state_relay":"OFF"}' from device d85def11a10046b1 type '6735/6736/6737'
zigbee.0 | 2022-01-07 14:03:00.276 | warn | ELEVATED publishToState: value generated '109' from device d85def11a10046b1 for 'Link quality'
zigbee.0 | 2022-01-07 14:03:00.276 | warn | ELEVATED publishToState: message received '{"linkquality":109}' from device d85def11a10046b1 type '6735/6736/6737'


</body>
</html>
![image](https://user-images.githubusercontent.com/3693094/148547844-96ec5e5f-059d-46c7-8792-d2ba57297c33.png)
reboot an cleanup also done.

Ok if i write an extra state in lib/states.js, then it it deprecated an is better to use oder recreate the  zigbee-herdsman-converters?

**Comment by Newan** [comment]
i fixed it, but i dont now if it the best way?

in "zigbee-herdsman-converters": "14.0.373"

Edit lib/legacy.js an add:

```
rm01_brightness: {
        cluster: 'genLevelCtrl',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            if (msg.data.hasOwnProperty('currentLevel')) {
                //const property = postfixWithEndpointName('brightness', msg, model);
                return {['brightness']: msg.data['currentLevel']};
            }
        },
    },
    rm01_on_off: {
        cluster: 'genOnOff',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            if (msg.data.hasOwnProperty('onOff')) {
                //const property = postfixWithEndpointName('state', msg, model);
                return {['state']: msg.data['onOff'] === 1 ? 'ON' : 'OFF'};
            }
        },
    },
```

Change devices/busch-jaeger.js, and change fromZigbee to (important ' fz.legacy.rm01_on_off, fz.legacy.rm01_brightness'):
```

        fromZigbee: [fz.ignore_basic_report, fz.legacy.rm01_on_off, fz.legacy.rm01_brightness, fz.legacy.RM01_on_click, fz.legacy.RM01_off_click,
            fz.legacy.RM01_up_hold, fz.legacy.RM01_down_hold, fz.legacy.RM01_stop],
```

Now the log logs like:

<html>
<body>


zigbee.0 | 2022-01-07 23:11:12.799 | warn | ELEVATED publishToState: value generated '100' from device d85def11a10049ce for 'Brightness'
-- | -- | -- | --
zigbee.0 | 2022-01-07 23:11:12.798 | warn | ELEVATED publishToState: message received '{"brightness":254}' from device d85def11a10049ce type '6735/6736/6737'
zigbee.0 | 2022-01-07 23:11:12.793 | warn | ELEVATED publishToState: value generated '255' from device d85def11a10049ce for 'Link quality'
zigbee.0 | 2022-01-07 23:11:12.792 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device d85def11a10049ce type '6735/6736/6737'
zigbee.0 | 2022-01-07 23:11:12.712 | warn | ELEVATED publishToState: value generated 'false' from device d85def11a10049ce for 'Switch state'
zigbee.0 | 2022-01-07 23:11:12.711 | warn | ELEVATED publishToState: message received '{"state":"OFF"}' from device d85def11a10049ce type '6735/6736/6737'
zigbee.0 | 2022-01-07 23:11:12.706 | warn | ELEVATED publishToState: value generated '255' from device d85def11a10049ce for 'Link quality'
zigbee.0 | 2022-01-07 23:11:12.706 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device d85def11a10049ce type '6735/6736/6737'
zigbee.0 | 2022-01-07 23:11:07.739 | warn | ELEVATED publishToState: value generated '100' from device d85def11a10049ce for 'Brightness'


</body>
</html>
