### ISSUE TITLE
No converter available for 'QS-Zigbee-C01' with key 'moving'

### ISSUE THREAD

**Issue by e-i-k-e** [ioBroker/ioBroker.zigbee#1316]
Hi

I cannot control the actuator (QS-Zigbee-C01) via the "moving" data point and get the following messages in the log.
<html>
<body>

zigbee.0 | 2021-12-29 17:30:20.076 | error | (53336) No converter available for 'QS-Zigbee-C01' with key 'moving'
-- | -- | -- | --
zigbee.0 | 2021-12-29 17:29:53.860 | warn | (53336) A 60a423fffe7ddd1d 0x60a423fffe7ddd1d
zigbee.0 | 2021-12-29 17:29:05.151 | error | (53336) No converter available for 'QS-Zigbee-C01' with key 'moving'
zigbee.0 | 2021-12-29 17:28:56.095 | error | (53336) No converter available for 'QS-Zigbee-C01' with key 'msg_from_zigbee'
zigbee.0 | 2021-12-29 17:28:52.379 | error | (53336) No converter available for 'QS-Zigbee-C01' with key 'moving'

</body>
</html>

But it is still possible via "position".

I'm using the current version from github and it definitely worked on an "earlier" version via the data point.

**Comment by LPTR72** [comment]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/96550014/147704239-71987747-e93b-4ba9-adc5-0643235c4642.png">

The 'moving' data point shows the current action of the QS-Zigbee-C01. Its read only.
You can controll via 'state' with open, stop, close or 'position'

**Comment by e-i-k-e** [comment]
Oh that's right! I have provided myself with a swm data point. :)
Please close.
