### ISSUE TITLE
Smartes Heizkörperthermostat ZigBee3.0, AWOW

### ISSUE THREAD

**Issue by fuxx-consulting** [ioBroker/ioBroker.zigbee#1319]
Hallo, 
nachfolgendes Thermostat bekomme ich mit dem CC26X2R1 nicht gepairt. 

https://www.amazon.de/gp/product/B09H6MB39X/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Ist es möglich den in die Liste mit aufzunehmen so dass man dieses Thermostat nutzen kann?

Danke

Andreas

**Comment by asgothian** [comment]
Möglich ist es, muss aber im Zigbee-Herdsman-Converters Projekt passieren.

Wobei es schwierig wird wenn der Thermostat schon beim Pairing nicht auftaucht - er müsste zumindest als unbekanntes Gerät erkannt werden.

A.

**Comment by fuxx-consulting** [comment]
Lassen sich pairen. War ein Bedienfehler meinerseits aufgrund schlechter Beschreibung.

**Comment by asgothian** [comment]
Wird es auch erkannt und funktioniert, oder ist es ein “neues” ?

**Comment by fuxx-consulting** [comment]
Es werden alle Datenpunkte korrekt erkannt. Ein Hinterlegtes Bild gibt es nicht als Pictogramm. Änderungen per Script funktionieren. Kann also rein theoretisch in die unterstützen mit aufgenommen werden. Nutze den CC26x2r1

**Comment by fuxx-consulting** [comment]
Heute abend ist auch das passende Pictogramm drin
