### ISSUE TITLE
Innr Sp120 liefert keine Leistungswerte (load_power)

### ISSUE THREAD

**Issue by mblass** [ioBroker/ioBroker.zigbee#1320]
Hi, seit dem Update von 1.5.6 auf 1.6.6 (welches ich wegen neuer Geräte benötigt habe), bekomme ich keine Leistungswerte (load_power) von innr sp 120. Availability, Link quality und state werden korrekt angezeigt.
![image](https://user-images.githubusercontent.com/91893325/148103441-66f710f3-6331-4d1f-a23d-ff790b94f838.png)
Gerät wurde mehrfach gepairt, ohne Erfolg. Mit dem Herdsman-Converter kenne ich mich leider nicht aus, um evtl. dort Werte manuell herzubekommen.

**Comment by mblass** [comment]
Habe nun die SP120 auf die Ausschlussliste getan und im Reiter "Entwickler" die Werte einmalig auslesen können. Sie wurden einmalig in die Datenpunkte geschrieben, aber werden nicht aktualisiert.
![image](https://user-images.githubusercontent.com/91893325/148113113-1c3dc2ac-cedb-44f6-987a-f50119aea482.png)
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/91893325/148113178-51ed5754-1988-4ae4-9515-06af9aee8ee4.png">

**Comment by asgothian** [comment]
Bitte auf 1.6.10 von Github aktualisieren. Wenn ich das korrekt erinnere gab es einen Bug in der Zwischenzeit der die Aktualisierung der Werte unterbunden hat.

A.

**Comment by mblass** [comment]
Danke für die schnelle Antwort. Hast Du den passenden Link? Ich komme bei Latest, Katze, Github use immer durcheinander.

**Comment by asgothian** [comment]
<img width="54" alt="Screen Shot 2022-01-04 at 22 01 03 " src="https://user-images.githubusercontent.com/45667167/148123425-f4aae4c1-afd6-4eff-ac9e-6723b241c62c.png">
Dieses icon in der Adapterliste, Expertenansicht. Dann zigbee adapter aussuchen.

A.

**Comment by mblass** [comment]
Leider keine Besserung. Habe 1.6.11 installiert, Instanz neu gestartet, die SP120 von der Ausschlußliste genommen, das Gerät gelöscht, neu verbunden, weiterhin kein load_power-Wert
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/91893325/148124392-58af2d27-aaa5-45d0-9e79-2d562733e579.png">
Dann SP120 wieder auf die Liste, Instanz neu gestartet, wieder kein Wert
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/91893325/148124586-c426e2b6-67e1-4e92-9d33-f892bf635422.png">

**Comment by mblass** [comment]
Jetzt sind die Werte da. Großartig. Vielen, vielen Dank !!

**Comment by HerbertJoos** [comment]
Ich habe das selbe Problem. Aber die Version 1.6.12 installiert. Muss ich da jetzt auch die v1.6.11 installieren? Hab schon X mal herausgeschmissen und neu verbunden. Immer nur Watt als Wert vorhanden (außer state usw...).

**Comment by mblass** [comment]
Habe 1.6.11, die Steckdose gelöscht, Adapter neu gestartet, Steckdose neu verbunden und das erste Mal, wo ein Verbraucher in der Steckdose "Strom gezogen" hat, kamen die Werte. Wie das mit 1.6.12 ist, weiß ich nicht.
