### ISSUE TITLE
Hama Thermostat window_detected immer imme true

### ISSUE THREAD

**Issue by mariatschi0815** [ioBroker/ioBroker.zigbee#1321]
Hallo,

laut Hama müsste die Funktion der Fenstererkennung einstellbar sein. window_detected steht aber immer auf "true". Somit regelt die Heizung automatisch runter... müsste hier statt dem value nicht ein state rein?

```
{
  "type": "state",
  "common": {
    "name": "Window detected",
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "value"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1641330428571,
  "_id": "zigbee.0.cc86ecfffea100f2.window_detected",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

und beim Running_Mode war ein Tippfehler im state stand "idle;idle" statt "idle:idle" zumindest vermute ich, dass es so heißen sollte.

```
{
  "type": "state",
  "common": {
    "name": "Running Mode",
    "type": "string",
    "states": "idle:idle;heat:heat",
    "read": true,
    "write": true,
    "role": "state"
  },
  "native": {},
  "_id": "zigbee.0.cc86ecfffea100f2.running_state",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1641331845038
}
```

Mod Edit: Correct code tags for readability

**Comment by asgothian** [comment]
- Which adapter version are you using ?
- What is the exact device ID (Seen on the info page of the units tile
- what messages are generated by the system if you enter `cc86ecfffea100f2` into `zigbee.0.info.debugmessages` (Enter the value, change states and use the Thermostat while recording your actions. Afterwards, check the log for warn messages with the keyword "ELEVATED"

A.

**Comment by mariatschi0815** [comment]
The Version is: v1.6.6
i have another problem yet and can't run the adapter... if this is solved I'll get you the rest of the infos

**Comment by asgothian** [comment]
Please add the device to the "ausschliessen" liste to ensure use of exposes and try again. If the situation remains, please update to the current git version. Some of the effects you describe should be fixed already.

Note that no mention is made of the state window_detected, i.e. the thermostat does not seem to report this, while the change to running_state is not accepted by the zigbee-herdsman-converters.

A.

**Comment by mariatschi0815** [comment]
At first it worked with v1.6.8, but there were some values missing (null) so I decied to delete the device and pair it again... after the pairing I'm back where it started

**Comment by asgothian** [comment]
- The current GitHub version is 1.6.11, not 1.6.8
- Did you check the "ausschliessen" tab ?
- Did you give it time to report the values (up to 6 hrs) ?

**Comment by mariatschi0815** [comment]
oh okay, I just updated via ioBroker there was the 1.6.8 the latest version... and I have to say, i have no idea how to install the version 1.6.11...

I checked it with "ausschliessen" with the same results.

Obviously I didn't wait long enough... should I try it with .8 or should I update anyway?

**Comment by asgothian** [comment]
Looking in more detail at the implementation and the zigbee2mqtt.io description:

- the device does not support a window open detection.
- Several states are not reported when changed on the Thermostat and cannot be read directly. Instead, they need to be read via writing an empty payload. I was unable to determine if this is the case in the current zigbee adapter code.
- The zigbee adapter code is implementing several states which are not actually referenced in the zigbee-herdsman-converters implementation.

Unfortunately, this will not be an easy fix and will be near impossible without physical access to the device.

I suggest you take a closer look at:
- the Hama thermostat description at zigbee2mqtt.io. Take special care to check which states can be read by "setting" them with an empty value. You can use local scripts using the sendTo function to trigger a read of the state . See this post on the iobroker forum for a short explanation (https://forum.iobroker.net/topic/50560/ikea-e1525-e1745-parameter-support/2?_=1641300767872)
- The implementation of the device in /opt/ioBroker/node_modules/zigbee-herdsman-converters/devices/saeswell.js
- The implementation of the device in /opt/ioBroker/node_modules/iobroker.zigbee/lib/devices.js

In the end, i would suggest that you add the device to the "Ausschliessen" tab and then perform a state cleanup to get rid of unsupported states (which should include the window detection). This can be done using the button with the circular arrows on the device view of the adapter.

A.

**Comment by mariatschi0815** [comment]
So, I tried another way. I paired the device with zigbee2mqtt and now it's working. i.e. I can set the window detection off and the away mode, etc.. Maybe there's just a "translation problem" from zigbee2mqtt to the zigbee-adapter?

**Comment by mariatschi0815** [comment]
How can I have a look at them?
> The implementation of the device in /opt/ioBroker/node_modules/zigbee-herdsman-converters/devices/saeswell.js
> The implementation of the device in /opt/ioBroker/node_modules/iobroker.zigbee/lib/devices.js

**Comment by arteck** [comment]
> How can I have a look at them?
> 
> > The implementation of the device in /opt/ioBroker/node_modules/zigbee-herdsman-converters/devices/saeswell.js
> > The implementation of the device in /opt/ioBroker/node_modules/iobroker.zigbee/lib/devices.js

?? vi or nano.. the path to the file is in your post
