### ISSUE TITLE
Device 0x0017880109c708d0 "440400982842" not described in statesMapping. Philips Hue Lightbar

### ISSUE THREAD

**Issue by Zoidborga** [ioBroker/ioBroker.zigbee#1322]
Hallo, ich wollte heute meine Philips Hue Lightbar anlernen, leider wird diese nicht erkannt. Da sich scheinbar die Modelnummer geändert hat. Bisher wird die Modelnummer 44040098284**1** als kompatibel gelistet. Meine haben nun aber die Modelnummer 44040098284**2**.
![image](https://user-images.githubusercontent.com/97158071/148189952-138b45f9-5b92-4009-9877-4d5116fb25c5.png)

Leider weiß ich nicht wie ich in der devices.js die Modellnummer hinzufügen kann bzw. sollte das Modell natürlich allgemein zum Adapter hinzugefügt werden.

**Comment by asgothian** [comment]
- Which adapter version are you using ?
- The device should be supported in the current GitHub version (1.6.11)

**Comment by Zoidborga** [comment]
I´m using the latest stable Version 1.6.6.
I installed 1.6.11 from GitHub now. This solved the problem.
Thank you.
