### ISSUE TITLE
Innr RS 226 Gu10 aus dem nichts keine verbindung mehr 

### ISSUE THREAD

**Issue by ManuelKlimek** [ioBroker/ioBroker.zigbee#1323]
Morgen
Ich habe jetzt zum 2ten mal das Phänomen das ein teil meiner GU10 Leuchtmittel (Innr RS 226) aus dem nichts die verbindung verlieren.
Sobald ich sie Stromlos mache und wieder Strom drauf gebe funktioniert es für eine weile. (Aktuell war es jetzt ca 2 wochen ohne ausfall). Im Protokoll erscheint nichts.

System:
Raspberry Pi 4 Modell B 4 GB
ZigBee Gateway CC26x2R1
Leuchtmittel Innr RS 226 Gu10

**Comment by arteck** [comment]
welche adapter version ?

**Comment by ManuelKlimek** [comment]
v1.6.11
nein steht nichts im Log verschwindet einfach ohne was zu sagen

**Comment by asgothian** [comment]
Wenn nichts im log steht - verschwinden die Leuchtmittel wirklich, i.e. melden sie sich aus dem System ab und werden als Objekte entfernt oder findet nur keine weitere Kommunikation mit den Leuchten statt ?

A.

**Comment by ManuelKlimek** [comment]
keine kommunikation werden im Adapter aber noch angezeigt.

**Comment by asgothian** [comment]
Es gibt 3 mögliche Gründe für dieses Verhalten:
- Funkstörungen durch automatisch wechselnde WLan Kanäle (WLan Router)
- Kritische Empfangssituation der Leuchten am Einbauort (Metallfassung,etc.)
- Probleme mit dem mesh routing.

Bitte verifiziere über die Map direkt nachdem die Birnen wieder hinzugefügt wurden ob diese sich über bestimmte Router mit dem Koordinator verbinden und ob der betroffene Router ggf. gegen einen anderen ausgetauscht werden kann.

A.

**Comment by arteck** [comment]
funktionieren die noch... kann sein das es nur ein Darstellungsfehler ist..

**Comment by ManuelKlimek** [comment]
>     * Funkstörungen durch automatisch wechselnde WLan Kanäle (WLan Router)
>        Das Wifi läuft auf 11 Zigbee auf 25 fest zugewiesen
>     * Kritische Empfangssituation der Leuchten am Einbauort (Metallfassung,etc.)
>       Empfang behaupte ich jetzt mal ist ok zumal sich alles im selben Raum befindet, keine Metallfassungen
>     * Probleme mit dem mesh routing.
 **<a href="https://ibb.co/Y3PVhNF"><img src="https://i.ibb.co/SP5ZB64/Unbenannt.png" alt="Unbenannt" border="0"></a>**

**Comment by ManuelKlimek** [comment]
> nochmal..
> 
> schreibe die ieee nummer in zigbee.0.info.debugmessages für lampe die verschwindet.. dann suche im log nach "ELEVATED".. steht da was .. nachdem die Lampe sich verabschiedet hat ?

alle Lampen ? es verschwinden immer mal 2-3-4-5 auf einmal aber immer unterschiedliche es sind gesammt 23 Verbaut

**Comment by asgothian** [comment]
> > nochmal..
> > schreibe die ieee nummer in zigbee.0.info.debugmessages für lampe die verschwindet.. dann suche im log nach "ELEVATED".. steht da was .. nachdem die Lampe sich verabschiedet hat ?
> 
> alle Lampen ? es verschwinden immer mal 2-3-4-5 auf einmal aber immer unterschiedliche es sind gesammt 23 Verbaut

Such Dir 2 aus.

Zum Thema Network map: Nimm mal den Haken bei "show siblings" (2. Haken von Oben wenn du auf die Einstellungen der Netzwerkkarte gehst) heraus - dann siehst du nur die Verbindung zum Router, nicht zu den Nachbarn.

A.
