### ISSUE TITLE
"Transport Key Text" - missing translation

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.zigbee#1325]
<img width="746" alt="Screenshot 2022-01-07 at 10 19 31" src="https://user-images.githubusercontent.com/1959049/148521803-6e1d28fe-b4f9-4d1b-80b1-80d07729052c.png">

Reason: Typo in `index_m.html`:

https://github.com/ioBroker/ioBroker.zigbee/blob/502535243dcdb0a03f462a168c1985e19d4e7eef/admin/index_m.html#L540

**Comment by arteck** [comment]
corr

**Comment by klein0r** [comment]
@arteck ```index_m.html``` still contains ```Tranport`` instead of ``Transport`` (missing ``s```)

https://github.com/ioBroker/ioBroker.zigbee/blob/75338967341879e396d4fcc898722c5687ff3219/admin/index_m.html#L540
