### ISSUE TITLE
Aqara RTCGQ11LM, Batteriespannung und Temperatur werden nicht angezeigt in der Adapter ver. 1.6.11.

### ISSUE THREAD

**Issue by Heini1985** [ioBroker/ioBroker.zigbee#1326]
Ich habe die Adapter version1.6.11installiert
benutze einen conbee2 stick. Bei dem bewegungsmelden von Aqara RTCGQ11LM wird mir kein Batterie Status und Temperatur angezeigt.
![image](https://user-images.githubusercontent.com/76739980/148615858-338a7e3e-5872-41c3-80bf-5d4fa7a86722.png)
![image](https://user-images.githubusercontent.com/76739980/148615897-10d20e7e-f2d4-4561-8f17-096e17ee222a.png)
![image](https://user-images.githubusercontent.com/76739980/148615967-3d73e84f-686b-4571-b129-34a53a4e304a.png)

Bei Phoscon wurde er immer angezeigt. Ich will aber auf den Zigbee Adapter wechseln de mehr Geräte unterstützt werden.

ich hoffe da eine die Lösung kennt.

Viele Grüße

Heini1985

**Comment by MMeinhardt1** [comment]
Guten Morgen,
ich weiß das dir diese Info kaum hilft, aber in V1.6.10 funktioniert es noch.

**Comment by e-i-k-e** [comment]
Hallo,
bei mir funktionieren diese mit der 1.6.11.
![image](https://user-images.githubusercontent.com/83473829/148691800-e2151372-83d6-4148-a523-72c11e45fdd7.png)

Ich würde den BWM löschen und neu anlernen.

**Comment by Heini1985** [comment]
Danke bei mir gehts jetzt auch 
Wir können es schließen.
