### ISSUE TITLE
NAS-AB02B0 seems to send string for temperature

### ISSUE THREAD

**Issue by mzander** [ioBroker/ioBroker.zigbee#1328]
The alarm device NAS-AB02B0 seems to send an string instead a number for the temperature value.
This ends in spamming the log with

zigbee.0 | 2022-01-10 09:23:32.673 | info | State value to set for "zigbee.0.842e14fffedb852e.temperature" has to be type "number" but received type "string"
-- | -- | -- | --
zigbee.0 | 2022-01-10 09:21:49.809 | info | State value to set for "zigbee.0.842e14fffedb852e.temperature" has to be type "number" but received type "string"
zigbee.0 | 2022-01-10 09:21:48.575 | info | State value to set for "zigbee.0.842e14fffedb852e.temperature" has to be type "number" but received type "string"
zigbee.0 | 2022-01-10 09:20:04.381 | info | State value to set for "zigbee.0.842e14fffedb852e.temperature" has to be type "number" but received type "string"
zigbee.0 | 2022-01-10 09:16:36.109 | info | State value to set for "zigbee.0.842e14fffedb852e.temperature" has to be type "number" but received type "string"

I manuelly changes the type of the field by the adapter seems to change it back.

**Comment by mzander** [comment]
stopping the adapter, deleting the datapoint and starting the adapter seems to help.
Can anybody explain why that happens?

**Comment by asgothian** [comment]
This is fixed with the current GitHub version (1.6.11)
