### ISSUE TITLE
IKEA Starkvind: Missing data

### ISSUE THREAD

**Issue by br-edward** [ioBroker/ioBroker.zigbee#1331]
Hello,

I used zigbee2mqtt before and all data was present, if use ioBroker.zigbee only very limited data is available:

![image](https://user-images.githubusercontent.com/87302944/149333275-6c44aafb-5ec3-410e-b076-5a0d17efea05.png)
![image](https://user-images.githubusercontent.com/87302944/149333317-9f1f089c-11ca-46a8-81b0-77dc921a92c6.png)

The data that is present, when using zigbee2mqtt, is written down here:

https://www.zigbee2mqtt.io/devices/E2007.html

What needs to be done?

Thanks,

Brian

**Comment by asgothian** [comment]
Please update to the current GitHub version (1.6.12) and check the states.

also: which states do you consider missing exactly ?

A.

**Comment by br-edward** [comment]
Yes, i updated to the latest for `zigbee-herdsman-converters` and `zigbee-herdsman` (npm update) inside `/opt/iobroker/node_modules/iobroker.zigbee/node_modules` and it works now !
