### ISSUE TITLE
WXKG06LM Device  "undefined" not described in statesMapping.

### ISSUE THREAD

**Issue by freizeitbastler** [ioBroker/ioBroker.zigbee#1332]
Single click is not working. After excluding the device single click is working, but it is still throwing the error "Device xxx "undefined" not described in statesMapping."

I have seen this issue was closed months before, but it's still not working with v1.6.8 (or I did not get the workaround)

**Comment by asgothian** [comment]
Please 
- update to 1.6.12 from GitHub
- Keep the device „excluded“

and all should work.

A.
