### ISSUE TITLE
Xenon steckdosenleiste zigbee (New?) 

### ISSUE THREAD

**Issue by Day1983** [ioBroker/ioBroker.zigbee#1333]
Hallo,

Habt ihr diese Steckdose bereits im Adapter? Könntet ihr diese ergänzen?
Finde sonst keine Infos zu der Dose.

Hab sie mal bestellt, und hoffe, dass diese mit dem Adapter funktioniert.

https://www.amazon.de/dp/B09NXZ774M/ref=cm_sw_r_apan_glt_i_FANNS8GWXHGYCJPEY99R

**Comment by asgothian** [comment]
Sollte gehen, aber braucht wahrscheinlich die Version 1.6.10 oder neuer

A.
