### ISSUE TITLE
Plötzlich Verbindungsabbruch zu allen Ledvance plugs

### ISSUE THREAD

**Issue by misave** [ioBroker/ioBroker.zigbee#1337]
Hallo,

heute Mittag hat der Conbee2 Stick im Iobroker alle Verbindungen zu Ledvance Plugs verloren. Die Verbindungen zu Xiaomi Temperatursensoren und zu diesen Xiaomi Würfeln funktionieren weiterhin problemlos. Die Lage des Raspi mit dem Stick sowie die aller Geräte wurde nicht geändert. Ich habe daraufhin den Adapter neu gestartet, einzelne Ledvance Plugs neu angelernt (was problemlos geht), den raspi neu gebootet, den conbee Stick abgezogen und wieder reingesteckt, die USB-Verlängerung des Conbee Stick mal weggelassen und wieder dazugestellt. Jedesmal findet er die Ledvance plugs kurz wieder, die Netzwerkkarte wird schön mit grünen Linien. Dann kann man auch ein bis zweimal Schalten bevor die Geräte nicht mehr reagieren und als entkoppelt dargestellt werden. Zusätzlich habe ich den Zigbee Adapter aus dem Beta repository installiert, hat auch nichts gebracht.

Raspi pi2, alle Adapter aktuell, js-Controller neu, node.js noch 12.22…

der conbee versucht immer die Ledvance zu erreichen, vergeblich, wenn ich schalten will erscheint im Protokoll dass es keine Antwort gab. Zusätzlich meldet der Stick dass er nach n Ping-Versuchen quasi aufhört, nach dem jeweiligen Ledvance Plug zu suchen. Vier der sieben Plugs sind weniger als 5 Meter Luftlinie ohne Mauern vom Stick entfernt. Der vom conbee genutzte Kanal ist 11 ist nicht besonders voll mit anderen Netzen.

Welche Infos soll ich noch liefern, wer weiß Rat? Ich könnte den Conbee auch zur Probe an einen anderen Raspi4 neu installieren, wenn man dabei etwas erkennen kann.

danke für eure Hilfe

michael

**Comment by asgothian** [comment]
- Was genau hast du heute Mittag getan / geändert ?
- wie ist die funkabdeckung der zigbee Kanäle ?
- Was ist an weiteren Geräten im Netz ?
- Gibt es Meldungen wenn die Plugs nicht mehr erreichbar sind ?
- Funktioniert das Anlernen da wo die Plugs sich befinden ?

die Ledvance plugs sind bekannt dafür schlechte Antennen zu haben.

A.

**Comment by misave** [comment]
Hallo,

ich habe heute Mittag selber gar nichts gemacht, ich habe nur gemerkt, dass ich meine Kaffeemaschine nicht über Alexa und iobroker und Schalten über den Zigbee-Adapter einschalten konnte. Dann habe ich im iobroker die Protokolle angesehen und da standen seit einiger zeit immer wieder die zig Ping-versuche vom Conbee 2 die Ledvance zu erreichen. heute morgen um 6 Uhr wurde die Kaffeemaschine noch ganz normal automatisiert eingeschaltet. 

Die Funkabdeckung war bis heute mittag immer tadellos, Ich habe wie gesagt nichts an der Anordnung im Haus geändert.

Es sind wie gesagt zwei Xiaomi-Würfel und drei Temperatursensorgen im Zigbee Netz. die funktionieren weiterhin. 

Zusätzlich eine Lidl-Steckdosenleiste, die auch bis heute Mittag problemlos funktionierte und die ist sogar am weitesten vom Conbee Stick entfernt. Die Leiste ist auch schon Wochen in Betrieb.

es gibt wie gesagt nur Warnungen vom Adapter im Protokoll, dass er die Geräte anpingt und irgendwann damit aufhört. und wenn ich einen Schaltbefehl über den iobroker zigbee adapter an die LEDvance schicke bringt er einen Error-Meldung, weil das Gerät grundlos nicht antwortet. 

ich habe probeweise einen LEDVANCE am Einbauort angelernt, das klappte problemlos. Aber nach gefühlt ein bis zwei Minuten ließ er sich nicht mehr schalten.

ich finde es komisch, dass alle 6 LEDVANCE Zeitgleich dasselbe Problem haben nachdem sie 1,5 Jahre ohne jedes Problem laufen. ich habe geprüft, ob vielleicht ein Nachbar plötzlich den Kanal 11 im 2.4 gHz extrem nutzt, aber das war nicht.

Es mag sein, dass die LEDVANCE schlechte Antennen haben, aber bis heute mittag habe ich davon hier nichts gemerkt

Übrigens danke für Deine Reaktion.

da auf meinem Raspi der deconz Dienst nicht installiert ist, kann ich auch nicht mal eben die Firmware vom Conbee 2 Stick updaten. und die Phoscon App habe ich auch nicht in Benutzung. Der Conbee lässt sich ja sehr gut ohne all diese Dinge im iobroker betreiben.

**Comment by misave** [comment]
Hier mal die Meldungen nach einem Neustart des Adapters. er findet sofort alle Geräte und nach einigen Minuten sind die LEDVANCE nicht mehr steuerbar

zigbee.0 | 2022-01-19 23:10:23.276 | info | Zigbee started
-- | -- | -- | --
zigbee.0 | 2022-01-19 23:10:23.272 | info | 0xbc33acfffec7e7d0 (addr 38551): HG06338 - Lidl Silvercrest 3 gang switch, with 4 USB (EU, FR, CZ, BS) (Router)
zigbee.0 | 2022-01-19 23:10:23.265 | info | 0x00158d00048809f6 (addr 64460): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
zigbee.0 | 2022-01-19 23:10:23.258 | info | 0x00158d0004880aad (addr 42685): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
zigbee.0 | 2022-01-19 23:10:23.251 | info | 0x7cb03eaa0a0b7ad0 (addr 19058): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2022-01-19 23:10:23.247 | info | 0x7cb03eaa0a0b92c4 (addr 13173): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2022-01-19 23:10:23.241 | info | 0x7cb03eaa0a0b861d (addr 15683): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2022-01-19 23:10:23.236 | info | 0x00158d000549d6da (addr 49007): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
zigbee.0 | 2022-01-19 23:10:23.228 | info | 0xf0d1b80000152021 (addr 48082): AC10691 - OSRAM Smart+ plug (Router)
zigbee.0 | 2022-01-19 23:10:23.223 | info | 0xf0d1b80000155b5e (addr 17799): AC10691 - OSRAM Smart+ plug (Router)
zigbee.0 | 2022-01-19 23:10:23.216 | info | 0x00158d000530d797 (addr 39827): MFKZQ01LM - Xiaomi Mi/Aqara smart home cube (EndDevice)
zigbee.0 | 2022-01-19 23:10:23.209 | info | 0x00158d000530d7e2 (addr 26362): MFKZQ01LM - Xiaomi Mi/Aqara smart home cube (EndDevice)
zigbee.0 | 2022-01-19 23:10:23.195 | info | 0xf0d1b8000015133d (addr 62980): AC10691 - OSRAM Smart+ plug (Router)
zigbee.0 | 2022-01-19 23:10:23.033 | info | Currently 12 devices are joined:
zigbee.0 | 2022-01-19 23:10:23.017 | info | Unable to set transmit power, unsupported function.
zigbee.0 | 2022-01-19 23:10:22.336 | info | --> transmitPower : high
zigbee.0 | 2022-01-19 23:10:22.298 | info | Unable to disable LED, unsupported function.
zigbee.0 | 2022-01-19 23:10:22.265 | info | Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":88,"maintrel":0,"revision":"0x26580700"}}
zigbee.0 | 2022-01-19 23:10:22.167 | info | Installed Version: iobroker.zigbee@1.6.8
zigbee.0 | 2022-01-19 23:10:20.394 | info | Starting Zigbee npm ...
zigbee.0 | 2022-01-19 23:10:20.082 | info | starting. Version 1.6.8 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.9, js-controller: 3.3.22


</body>
</html>`

**Comment by misave** [comment]
`<html>
<body>


zigbee.0 | 2022-01-19 23:19:49.889 | warn | Stopping to ping 0xf0d1b8000015133d Plug Z3 after 6 ping attempts
-- | -- | -- | --



</body>
</html>`

10 Minuten später merkt der Conbee, dass er die ersten Geräte nicht mehr anpingen kann.

**Comment by asgothian** [comment]
Das ist nicht korrekt. 6 versuche heißt die plugs Antworten von Anfang an nicht.

 Auch werden am Anfang die Geräte aufgelistet die dem Adapter bekannt sind, nicht die die er erreichen kann.

bist du sicher das nichts geändert wurde ? Kein neues dect Telefon oder Änderungen am WLAN ?

Ansonsten kannst du den Adapter im debug laufen lassen um zu sehen ob etwas gemeldet wird.

A.

**Comment by misave** [comment]
Also echt, ich habe gestern zwischen morgens als die LEDVANCE die Kaffeemaschine korrekt eingeschaltet haben und mittags als nichts mehr ging selber nichts gemacht, ich saß schön im Homeoffice in einer telko.

ich würde mal den WLAN-Kanal des Zigbee-Adapters auf einen anderen Kanal legen. Derzeit ist er bei mir der Einzige der 11 nutzt, zusätzlich drei Geräte des Nachbarn funken auf Kanal 11, dies jedoch schon immer, also nicht erst seit gestern Mittag. 

ich gehe ja auch davon aus, dass es etwas mit der Erreichbarkeit der LEDVANCE ist, aber mir ist es unlogisch, warum da alle LEDVANCE seitgleich von betroffen sind. Die Lidl-Leiste werde ich mal näher an den Conbee Stick holen und gucken was passiert.

Conbee Firmware update. das geht ja entweder über die Phoscon app oder eben direkt in der raspi Console. Da ich auf dem raspi aber kein deConz installiert habe könnte ich den Conbee Stick doch auch einfach an einen Windowsrechner installieren und dort dann die Firmware updaten und später wieder in den raspi stecken. Oder?

Michael

**Comment by Ilovegym66** [comment]
Hi, die LEDVANCE sind leider bekannt dafuer, dass sie zicken. Hatte auch 6 Stueck, sind nach 2 Wochen wieder rausgeflogen und habe auf Xiami MiPower und Gosund SHP13 gewechselt, seitdem alles stabil. 195 Devices im Adapter mit einem CC26X2R1.
Ich betreibe alles auf Kanal 25, da der 11er leider auch vom Wifi beeinflusst wird. 
Moechte damit sagen, es liegt nicht am Adapter, sondern an der Hardware.

**Comment by misave** [comment]
@Ilovegym66 
Na ja, es lief ja mehr als zwei Jahre stabil mit den LEDVANCE, nicht bloß ein paar Tage. Waren bis gestern Mittag immer erreichbar, es gab nie ein Problem. Ich wechsle aber mal den Kanal des Conbee Sticks und muss halt alle Geräte neu anlernen.

**Comment by misave** [comment]
So ich habe den Stick mit neuer Firmware bestückt und den Funkkanal von 11 auf 20 verschoben. Jetzt geht es wieder wie vorher.

**Comment by blue-kaleidoscope** [comment]
This issue just started to happen on my system as well. 2 Ledvance plugs lost twice the connection within 24 hours. They worked without issues the last 3 weeks since I installed them. I use Phoscon 2.15.00 / 16.3.2022 with firmware 26720700. Phscon says the Ledvance plugs have version 00203045. I switched to channel 20 yesterday and the plugs reconnected immediately again. Today I switched to channel 25. misave, did it occur again on your system?
