### ISSUE TITLE
TRADFRI LED1733G7; Update of '0x804b50fffec23099' failed (Image is truncated: not long enough to contain a valid tag)

### ISSUE THREAD

**Issue by e-i-k-e** [ioBroker/ioBroker.zigbee#1339]
Hi there,

I've updated some of my Zigbee the last few days. Unfortunately, it always fails with this device.

What can I do?

<html>
<body>

  |   |   |  
-- | -- | -- | --
zigbee.0 | 2022-01-21 16:32:00.153 | error | (113299) Update of '0x804b50fffec23099' failed (Image is truncated: not long enough to contain a valid tag)
zigbee.0 | 2022-01-21 16:31:59.228 | info | (113299) Start firmware update for 0x804b50fffec23099

</body>
</html>

![image](https://user-images.githubusercontent.com/83473829/150554280-851734bb-30a6-4d45-b223-5a6c5c109b0c.png)
![image](https://user-images.githubusercontent.com/83473829/150554332-e8c90e6d-e732-46df-ad56-316561b97cac.png)
![image](https://user-images.githubusercontent.com/83473829/150554398-0d58bd03-d0fe-420a-a953-5ea46359499d.png)
![image](https://user-images.githubusercontent.com/83473829/150554795-7b99b54a-fd98-4cb3-a4d9-d013fabc5fdd.png)

**Comment by arteck** [comment]
good question..
try disconnect the lamp from the power.. and start the update process again.
maybe was the server not available

**Comment by e-i-k-e** [comment]
> good question.. try disconnect the lamp from the power.. and start the update process again. maybe was the server not available

I've tried that several times.  Unfortunately it still doesn't work.

**Comment by e-i-k-e** [comment]
I just upgraded the Zigbee adapter to the current beta and took the light bulb off the grid again for a while. I keep getting the same message.
For example, I was able to update an Ikea socket recently.

<html>
<body>


zigbee.0 | 2022-01-24 19:06:44.191 | error | (19767) Update of '0x804b50fffec23099' failed (Image is truncated: not long enough to contain a valid tag)
-- | -- | -- | --
zigbee.0 | 2022-01-24 19:06:43.162 | info | (19767) Start firmware update for 0x804b50fffec23099


</body>
</html>

**Comment by asgothian** [comment]
This seems to be an issue with the ikea update server. Not sure we can do much about it.

A.

**Comment by e-i-k-e** [comment]
OK. Can I test/try anything for you?

**Comment by e-i-k-e** [comment]
I had to do some restarts of the TI board and ioBroker today.
Suddenly it worked

<html>
<body>


zigbee.0 | 2022-02-15 21:49:06.700 | info | Update of '0x804b50fffec23099' at 2.12%, +- 30 minutes remaining
-- | -- | -- | --
zigbee.0 | 2022-02-15 21:48:36.596 | info | Update of '0x804b50fffec23099' at 0%
zigbee.0 | 2022-02-15 21:48:27.044 | info | Start firmware update for 0x804b50fffec23099


</body>
</html>
