### ISSUE TITLE
Ikea Tradfri Shortcut Button, keine Klicks nach FW-Update auf 2.3.080 

### ISSUE THREAD

**Issue by Epstone** [ioBroker/ioBroker.zigbee#1340]
Hallo,
danke erstmal für die viele Arbeit, die ihr hier investiert. Ich hab einen Tadfri Shortcut Button E1812 aktualisiert, weil ich mit dem Ikea Gateway experimentieren wollte. Nun wurde der Button auf die neuste FW aktualisiert (2.3.080) und ich sehe nach erfolgreichem Pairing und Interview mit dem ioBroker keine "clicks" mehr. 
![grafik](https://user-images.githubusercontent.com/1425860/150581087-e8a13478-47b1-4457-a23a-d103ba204b91.png)

Ohne es selbst richtig diagnostizieren zu können, klingt folgendes Issue recht passend:
Nach https://github.com/Koenkk/zigbee2mqtt/issues/9551#issuecomment-963399960 könnte man ein Binding zum Coordinator herstellen als Workaround. Geht das mit ioBroker.zigbee Plugin auch, falls ja wie?

Plugin Version: 1.6.6
Coordinator: CC2652RB
type:zStack3x0
version:2-1.2.7.1.
revision:20210708

**Comment by asgothian** [comment]
Mit der Adapter Version 1.6.12 oder neuer ist das Problem behoben. Installation am besten von Github.

**Comment by Epstone** [comment]
Danke, nach dem Update auf die 1.6.14 und Löschen und erneutem Pairing des Shortcut Buttons läuft es wieder :)
