### ISSUE TITLE
Issue with 1.6.14 - malformed `dev_names.json`

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.zigbee#1346]
Hi,

I faced with strange issue - yesterday I installed version 1.6.14 without a problems, but, after the restart the whole iobroker I faced with impossibility to start ZigBee adapter ...
Appropriate log is below ....

After reading a log I fount an issue root cause - wrong json file format of `dev_names.json`
```
{
  "bc33acfffe655d74": "TS0001",
  "00158d00047eb0ea": "RTCGQ11LM",
  "04cf8cdf3c764daa": "ZNCZ04LM",
  "00158d00056c1d1e": "WSDCGQ11LM",
  "04cf8cdf3c763a6f": "ZNCZ04LM",
  "60a423fffe9f5a53": "BHT-002-GCLZB",
  "04cf8cdf3c866e2f": "ZNCZ04LM",
  "00158d0003cd2205": "WSDCGQ11LM",
  "00158d00047d09fb": "MCCGQ11LM",
  "00158d0003973ec8": "MCCGQ01LM",
  "00158d0003cd2226": "WSDCGQ11LM",
  "00158d00049fca02": "MCCGQ11LM",
  "00158d0004146846": "WSDCGQ11LM",
  "00158d0003968e5c": "MCCGQ01LM",
  "00158d000477240f": "MCCGQ11LM",
  "00158d0001d72a60": "WSDCGQ11LM",
  "00124b001ed1ce12": "DIYRuZ_Geiger",
  "00158d0003230500": "WSDCGQ11LM",
  "00158d0003a4e901": "RTCGQ01LM",
  "00158d84e6a79a26": "WSDCGQ11LM",
  "00158d00045ef5a7": "JTYJ-GD-01LM/BW",
  "60a423fffeff95f4": "TS0121_plug",
  "00158d3af28d1ea3": "WSDCGQ11LM",
  "00158d00047c6281": "MCCGQ11LM"
}  "00158d0003cc1635": "MCCGQ11LM"
}
```

Most interesting thing - I did nothing with these two devices ....

After fixing the `dev_names.json` everything is work good

> 2022-01-28 00:04:52.246  - error: zigbee.0 (4164589) uncaught exception: Unexpected string in JSON at position 862
> 2022-01-28 00:04:52.248  - error: zigbee.0 (4164589) SyntaxError: Unexpected string in JSON at position 862
>     at JSON.parse (<anonymous>)
>     at /opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:23:37
>     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:71:3)
> 2022-01-28 00:04:52.249  - error: zigbee.0 (4164589) Unexpected string in JSON at position 862
> 2022-01-28 00:04:52.250  - error: zigbee.0 (4164589) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> 2022-01-28 00:04:52.251  - error: zigbee.0 (4164589) unhandled promise rejection: Cannot read property 'error' of undefined
> 2022-01-28 00:04:52.252  - error: zigbee.0 (4164589) TypeError: Cannot read property 'error' of undefined
>     at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:764:26)
>     at Zigbee.emit (events.js:400:28)
>     at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8749:22)
>     at exceptionHandler (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8818:13)
>     at process.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8830:44)
>     at process.emit (events.js:400:28)
>     at process._fatalException (internal/process/execution.js:167:25)
> 2022-01-28 00:04:52.253  - error: zigbee.0 (4164589) Cannot read property 'error' of undefined
> (node:4164589) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:4164589) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
> (node:4164589) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
> (node:4164589) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
> 2022-01-28 00:04:52.645  - error: zigbee.0 (4164589) adapter disabled
> 2022-01-28 00:04:52.651  - info: zigbee.0 (4164589) starting. Version 1.6.14 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.18.2, js-controller: 3.3.22
> 2022-01-28 00:04:52.693  - info: zigbee.0 (4164589) Starting Zigbee  npm ...
> 2022-01-28 00:04:52.769  - info: zigbee.0 (4164589) terminating
> 2022-01-28 00:04:52.771  - warn: zigbee.0 (4164589) Terminated (UNCAUGHT_EXCEPTION): Without reason
> 2022-01-28 00:04:52.835  - info: zigbee.0 (4164589) Installed Version: iobroker.zigbee@1.6.14

**Comment by PeterVoronov** [comment]
I looked into the code, and can't understand, how it can happened ...
By result it's like a writing to the file without truncate of it ...

**Comment by arteck** [comment]
edit the file with
{
  "bc33acfffe655d74": "TS0001",
  "00158d00047eb0ea": "RTCGQ11LM",
  "04cf8cdf3c764daa": "ZNCZ04LM",
  "00158d00056c1d1e": "WSDCGQ11LM",
  "04cf8cdf3c763a6f": "ZNCZ04LM",
  "60a423fffe9f5a53": "BHT-002-GCLZB",
  "04cf8cdf3c866e2f": "ZNCZ04LM",
  "00158d0003cd2205": "WSDCGQ11LM",
  "00158d00047d09fb": "MCCGQ11LM",
  "00158d0003973ec8": "MCCGQ01LM",
  "00158d0003cd2226": "WSDCGQ11LM",
  "00158d00049fca02": "MCCGQ11LM",
  "00158d0004146846": "WSDCGQ11LM",
  "00158d0003968e5c": "MCCGQ01LM",
  "00158d000477240f": "MCCGQ11LM",
  "00158d0001d72a60": "WSDCGQ11LM",
  "00124b001ed1ce12": "DIYRuZ_Geiger",
  "00158d0003230500": "WSDCGQ11LM",
  "00158d0003a4e901": "RTCGQ01LM",
  "00158d84e6a79a26": "WSDCGQ11LM",
  "00158d00045ef5a7": "JTYJ-GD-01LM/BW",
  "60a423fffeff95f4": "TS0121_plug",
  "00158d3af28d1ea3": "WSDCGQ11LM",
  "00158d00047c6281": "MCCGQ11LM",
  "00158d0003cc1635": "MCCGQ11LM"
}

**Comment by PeterVoronov** [comment]
> edit the file with...

I fixed it already, as it was stated in my initial message ...

What I can propose - to do not write to file on every change of "savedDeviceNames" object, but do it only on adapter unload event, one time ...

**Comment by asgothian** [comment]
I will review this. It is my assumption that a race condition triggers a conflicting file access. I will safeguard this this weekend.

**Comment by asgothian** [comment]
A test solution is available here:
https://github.com/asgothian/ioBroker.zigbee

Note that i was not able to test this myself yet, so installation is a bit risky. I will run the test tonight and make a PR when it goes through.

Changes are:
- try/catch when reading the data to ensure that malformed data will not cause the adapter to crash
- block the writing with a timeout of 5 seconds so name changes in quick succession will be written in one go after the last change was done.
This keeps the safeguard against an adapter crash while reducing the disk writes when a lot of new names are added.

A.

**Comment by PeterVoronov** [comment]
Thanks.
It hard to test, due to it hard to reproduce ...
Last days I made several reboots of adapter - without any issues ...
But I still think - the best place for file writing - in the o[nUnload](https://github.com/ioBroker/ioBroker.zigbee/blob/7c3bd98226155fb70242ddb0f96626ec0eabb0a0/main.js#L748) event.
Not to make it on every change...

**Comment by asgothian** [comment]
Test should be simple:

- stop the adapter
- remove the file
- start the adapter.

The malformed JSON is generated when the system verifies all devices at startup and the "write" command is slower than the devices are quarried. I did not catch this on implementation due to the low number of devices in my test system. The fact that you did experience the issue leads me to believe that it will reappear if you start the adapter fresh with no file.


To reiterate: The reason not to do it at the onUnload event is that an adapter crash will bypass the onUnload event and as such not save the data. In my experience, it is rather common for the adapter to run for several days / weeks without restart, which would have the data remain unsaved and in memory only for a long time. As people cannot be relied on manually restarting the adapter after renaming devices this would potentially have us receive reports of "lost" device name changes which are hard to track and verify.
Writing on every change is an issue only when a large number of devices are added to the dev_names within a short period of time, i.e. When starting the adapter with an empty names list.

Note that removing a device from the adapter will **not** remove it from the names list. Adding the same device back therefore does not trigger a write either.
