### ISSUE TITLE
OTA Updates?

### ISSUE THREAD

**Issue by Cumulus7** [ioBroker/ioBroker.zigbee#1347]
Hi, 

sorry for the dumb (?) question: how do i initiate OTA updates?
I have no firmware-check buttons in my device-widgets.

![image](https://user-images.githubusercontent.com/45620107/151662903-5324b4ad-0fc5-41bc-a25f-ab86a0dfaa72.png)

Do i need to configure OTA-Updates somehow?

In another post i saw a hint that the folder /opt/iobroker/node_modules/zigbee-herdsman-converters/ota should exist. However there is no "ota" folder there...

THX for any advice,
Markus

**Comment by e-i-k-e** [comment]
Hi,

you have to start the update search via 1. (this takes a moment). An update will then be displayed under 2. on some devices.

![image](https://user-images.githubusercontent.com/83473829/151663198-47fdf48d-effb-4645-ab9c-860ac5d0a2a0.png)

**Comment by Cumulus7** [comment]
Danke ;-)
