### ISSUE TITLE
Siterwell GS361A-H04 config seems not right

### ISSUE THREAD

**Issue by DJ3vil** [ioBroker/ioBroker.zigbee#1349]
Siterwell GS361A-H04 seems not to work (Maby not supported rn ?)
Its using other Modes (Eco, Boost etc) thats not supported by the device. 
It also using the mode manual, but heat is the right one. 
its working with zigbee2mqtt.

**Comment by asgothian** [comment]
- Which adapter version are you using ?
- what is the "manufacturer info" from the info gained through the adapter ?
- what happens if you add the device to the list of excluded devices (Exclude tab)

A.

**Comment by DJ3vil** [comment]
Sry for my late answer. i was not at home.

Version from Adapter is 1.6.6 

ieee:0x804b50fffee7b197
nwk:2156 (0x86c)
model:[GS361A-H04](https://www.zigbee2mqtt.io/devices/GS361A-H04.html)

3. i can't tell anymore bec i dont the Device anymore. 
4. 
It seems, software or Hardware related, sometimes the value from the target temp got not updated through an daily routine.
Some comments unter the productpage says the same so its maby an hardware issue.

The Link from the product is https://www.amazon.de/gp/product/B0816X9ZDF/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

**Comment by asgothian** [comment]
Cannot be verified without the device. Closing this.
