### ISSUE TITLE
Read/Write-able attributes are not read

### ISSUE THREAD

**Issue by allofmex** [ioBroker/ioBroker.zigbee#135]
Seems, toZigbee.js attributes from shepherd-converter are never read by ioBroker.zigbee.

I implemented [https://github.com/ioBroker/ioBroker.zigbee/pull/134](https://github.com/ioBroker/ioBroker.zigbee/pull/134), and it works for writing (type 'set'). The issue is that the value **never gets read** from device ('get').

It looks like it is not implemented yet:
(the "->>" lines should be changed as shown (key and error, resp arguments where missing))

              adapter.log.debug(`Read timeout for cmd '${message.cmd}' is ${readTimeout}`);
                  setTimeout(()=>{
    ->>           const readMessage = converter.convert(key, preparedValue, preparedOptions, 'get');
                      if (readMessage) {
                          adapter.log.debug('read message: '+safeJsonStringify(readMessage));
                          // adapter.log.info(`3 before read publish. time: ${new Date() - start}`);
                          zbControl.publish(deviceId, readMessage.cid, readMessage.cmd, readMessage.zclData, ep, 
     ->>                          readMessage.cmdType, (error, resp)=>{
                              // adapter.log.info(`6 read publish success. ${stateDesc.id} time: ${new Date() - start}`);
                               ->> response ignored!  <<-
                          });
                          // adapter.log.info(`4 after read publish. time: ${new Date() - start}`);
                      }
                  }, readTimeout || 0);

I tried to submit this as pull request, but git always shows the whole file as changed. Don't know why!?

Please implement the 'get' type too. Else we don't see current attribute value and if written values got accepted.

**Comment by arteck** [comment]
it's already in mine PR 
https://github.com/arteck/ioBroker.zigbee/commit/6b26ff6095f64f98f6aa6c1fc701952f16e539e2

**Comment by arteck** [comment]
> But the read result is still ignored right? (callback empty)...

Yes you are right.. we send ON and the published state is also ON.. 
why should I read the state again ??

**Comment by allofmex** [comment]
1. The write may have failed or we wrote a illegal value. As of now the wrong value keeps showing in object and we don't get any feedback.
2. In case we never write anything, the Object should be read at least once to see current (default) setting

This is more needed for device settings that we not configure reporting for (timeouts,... [https://github.com/Koenkk/zigbee-shepherd-converters/pull/185](https://github.com/Koenkk/zigbee-shepherd-converters/pull/185)), I guess it's not a good idea to add fromZigbee and reporting for all this rarely changed attributes...

**Comment by modmax** [comment]
I think this issue can be closed now.
With the definition of readAfterWriteStates this should be possible.

**Comment by allofmex** [comment]
Just one point: Would be nice to read all readAfterWrite states once after adapter start. Then we also see the device setting if we did not write anything. (maybe earliest 2 minutes after adapter start to limit the load right at startup. And right after device send something to be sure it is not sleeping)
