### ISSUE TITLE
Error mit zigbee adapter 1.6.14 und Conbee II

### ISSUE THREAD

**Issue by Heini1985** [ioBroker/ioBroker.zigbee#1350]
Hallo ich habe einen Conbee II  mit Zigbee Adapter 1.6.14 im Einsatz. Der adapter meldet immer Error in den Logs(siehe bild).

![image](https://user-images.githubusercontent.com/76739980/151958984-ae64eaa0-0ef8-4479-9f0e-59a16f7b28d5.png)
Habe auch schon andere Versionen versucht selber Fehler.
Außerdem stürzt der Adapter öfter ab. Und ich bekomme kein netzwerkkarte.

So sehen meine Geräte aus:
![image](https://user-images.githubusercontent.com/76739980/151959223-e504125f-eb44-465b-bd18-f8d091949a7a.png)
 
Und so meine Netzwerkkarte:

![image](https://user-images.githubusercontent.com/76739980/151959332-1cbea2f2-0dda-42ac-bf59-cc2a936c3882.png)

Gibt es eine Abstellmöglichkeit?
nach den Neustart zeigt die fensterkontakte folgendes an:
![image](https://user-images.githubusercontent.com/76739980/151959594-0e5e8914-7a23-452e-a617-cb2ed1fcfc4c.png)
Der Empfangszeiger ist rot. Es wird nur dann richtig angezeigt wenn der Sensor betätig worden ist.

Was kann ich da tun?

Viele Grüße

**Comment by asgothian** [comment]
Empfangszeiger ist rot. Es wird nur dann richtig angezeigt wenn der Sensor betätig worden ist.
> 
> Was kann ich da tun?
> 
> Viele Grüße

Du musst schauen warum das Netzwerk belastet ist. Ich gehe aktuell davon aus das es Störungen im Funkbereich gibt die dein Netzwerk stören. Dazu die vorhandenen anderen 2.4 GHz Netzwerke untersuchen (WLan, Bluetooth, Funk-Kopfhörer, etc.)

Zum Thema Link Qualität - bei Start des Adapters wird diese auf 10 gesetzt. Bei batteriebetriebenen Geräten ist der Adapter darauf angewiesen das die Geräte die LQ übermitteln, was sie üblicherweise erst bei einer Übertragung von Werten tun. Das ist also geplantes Verhalten und nicht zu ändern.

A.

**Comment by Heini1985** [comment]
Danke für die info @asgothian 

Ich habe aber mindestens ein mal am Tag die folgende Meldung.

![image](https://user-images.githubusercontent.com/76739980/152478909-b32e0310-fc9b-47f7-9e84-128ca96e6df9.png)

womit kann das zusammenhängen?

Viele Grüße

Heini1985

**Comment by Apollon77** [comment]
Bitte im Log schauen, da sollten zeitlich passende Fehler Logs sein

**Comment by Xerxes55** [comment]
Habe ähnliche Probleme seit heute Morgen
![image](https://user-images.githubusercontent.com/99069661/152633790-ded46771-905f-4b7b-a230-69715cc284fc.png)

**Comment by asgothian** [comment]
- Logs immer als Text, nie als Screenshot posten
- Darauf achten das die vollständigen Informationen gepostet werden, nicht (wie in diesem Fall) nur 80%
- @Xerxes55 : Was macht Deine Probleme "ähnlich" zu denen des OP ? Das auch du Fehlermeldungen im Zusammenhang mit dem Zigbee Adapter hast ? Ob da eine nur ansatzweise vergleichbare Ursache hinter steht ist Fraglich.

A.

**Comment by Xerxes55** [comment]
@asgothian 
Überschrift „ Error mit zigbee adapter 1.6.14 und Conbee II“ und meine Errors kommen von Host raspi, das passt nicht zusammen? Die Fehler kommen doch von Zigbee Adapter. Dachte nur, das kann euch interessieren. 
Logs werde ich in Zukunft komplett posten.

**Comment by asgothian** [comment]
> Überschrift „ Error mit zigbee adapter 1.6.14 und Conbee II“ und meine Errors kommen von Host raspi, das passt nicht zusammen? Die Fehler kommen doch von Zigbee Adapter. Dachte nur, das kann euch interessieren.
> Logs werde ich in Zukunft komplett posten.

You have a specific error, i.e. that the conbee receives an zigbee packet which the library cannot parse. This causes the adapter to crash. This is most likely caused by one of the devices in your zigbee network.

If that is similar or the same as @Heini1985 has is doubtful at best - considering your error seems to come from a trust PIR sensor which the OP does not have listed in his devices.

A.
