### ISSUE TITLE
Ikea E1812 and E1743 show no "Clicks"

### ISSUE THREAD

**Issue by hytrek** [ioBroker/ioBroker.zigbee#1352]
Hi there
I am using the Zigbee Adapter in Version 1.6.14 and added these two devices. Unfortunately there are no Clicks available....

Is there a bug and will it be changed so I can use like an excample 1003 or so once clicked?

Thanks

**Comment by hytrek** [comment]
![image](https://user-images.githubusercontent.com/77238148/152068642-6c079bb3-0a57-46e4-b074-99d9f95566ef.png)

**Comment by asgothian** [comment]
Please verify that the event states are working. These are
`brightness_move_up`,
`brightness_stop`,
`on`,
`off`,
`up_button`,
`down_button`,
`state`

Note that the button event you are mentioning is a function of the phoscon app, and as such not available in the zigbee Adapter.

A.

**Comment by hytrek** [comment]
Hi there
thx for your feedback.
The E1812 does update on every click regulary ".msg_from_zigbee" only. 
Occassionally every 5th to 7th click the "on" changes. Nothing else.

On the E1743 state changes when clicking "0" or "1". Also when holding "1" or "0" down or up works. But I would expect single short click on"0" could be used for turn off and "1" button to turn on. But short click on either of them results in "true" "false" toggle only. 

Thanks

**Comment by zer-flag** [comment]
Hi Hytrek,
I'm having the same problems with those Ikea-Buttons. The shortcut-button only has a single function: The object "on" changes to true for a very short time, when the button is pressed. I use this to switch on my coffee-machine in the morning. The other objects don't have any functions in my opinion.
The dimmer isn't dimming with the iobroker zigbee adapter yet. The only thing I got it working was as a two way button.

**Comment by KenADev** [comment]
I experience the same Issue.
The `brightness_move_up`, `brightness_stop`, and `on` states are only updated sometimes, not on every click for some reason (unreliable).
The `msg_from_zigbee` state with the JSON-Array _is_ updated every click, and also contains the right value, e.g. `"type":"commandStopWithOnOff"`

ioBroker.zigbee Adapter Version: v1.6.16

Device Info:
model: E1812
description:TRADFRI shortcut button
build:2.3.015

**Comment by asgothian** [comment]
Please verify this by entering the ieee (without 0x) in the state zigbee.0.info.debugmessages and checking the log for messages with the keyword “elevated”

the display of state changes in any browser is delayed.

A.

**Comment by zer-flag** [comment]
There are a lot of elevated massages after that!
![grafik](https://user-images.githubusercontent.com/3885957/159172222-c8e8f6ad-e656-4ace-a36f-fcafca35913f.png)

**Comment by asgothian** [comment]
Please do the following with the log:
- post it as text, in code tags (<>)
- pair the messages with the actions you did on the ikea device.

Each action on the device should lead to at least 2 elevated messages, possibly 4

A.

**Comment by zer-flag** [comment]
This is the protocoll of one click on the 0-side of the button:
<
<html><body>


zigbee.0 | 2022-03-20 20:04:50.417 | warn | ELEVATED publishToState: value generated 'false' from device 0c4314fffeae1bb9 for 'Switch event'
-- | -- | -- | --
zigbee.0 | 2022-03-20 20:04:50.417 | warn | ELEVATED publishToState: message received '{"click":"off"}' from device 0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:04:50.416 | warn | ELEVATED publishToState: message received '{"action":"off"}' from device 0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:04:50.408 | warn | ELEVATED publishToState: value generated '255' from device 0c4314fffeae1bb9 for 'Link quality'
zigbee.0 | 2022-03-20 20:04:50.407 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 0c4314fffeae1bb9 type 'E1743'

</body>
</html>
>

**Comment by zer-flag** [comment]
... and this is one click on the 1-side:
<
<html><body>


zigbee.0 | 2022-03-20 20:06:18.575 | warn | ELEVATED publishToState: value generated 'true' from device 0c4314fffeae1bb9 for 'Switch event'
-- | -- | -- | --
zigbee.0 | 2022-03-20 20:06:18.575 | warn | ELEVATED publishToState: message received '{"click":"on"}' from device 0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:06:18.575 | warn | ELEVATED publishToState: message received '{"action":"on"}' from device 0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:06:18.571 | warn | ELEVATED publishToState: value generated '255' from device 0c4314fffeae1bb9 for 'Link quality'
zigbee.0 | 2022-03-20 20:06:18.570 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 0c4314fffeae1bb9 type 'E1743'


</body>
</html>
>

**Comment by zer-flag** [comment]
This is a longer press on the 1-side. The first 5 messages appear when starting to press, the other six when releasing the button.
<
<html><body>


zigbee.0 | 2022-03-20 20:08:45.213 | warn | ELEVATED publishToState: value generated 'false' from device 0c4314fffeae1bb9 for 'Down button pressed'
-- | -- | -- | --
zigbee.0 | 2022-03-20 20:08:45.213 | warn | ELEVATED publishToState: value generated 'false' from device 0c4314fffeae1bb9 for 'Up button pressed'
zigbee.0 | 2022-03-20 20:08:45.213 | warn | ELEVATED publishToState: message received '{"click":"brightness_stop"}' from device 0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:08:45.212 | warn | ELEVATED publishToState: message received '{"action":"brightness_stop"}' from device 0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:08:45.209 | warn | ELEVATED publishToState: value generated '255' from device 0c4314fffeae1bb9 for 'Link quality'
zigbee.0 | 2022-03-20 20:08:45.208 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:08:41.459 | warn | ELEVATED publishToState: value generated 'true' from device 0c4314fffeae1bb9 for 'Up button pressed'
zigbee.0 | 2022-03-20 20:08:41.459 | warn | ELEVATED publishToState: message received '{"click":"brightness_up"}' from device 0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:08:41.458 | warn | ELEVATED  publishToState: message received  '{"action":"brightness_move_up","action_rate":83}' from device  0c4314fffeae1bb9 type 'E1743'
zigbee.0 | 2022-03-20 20:08:41.448 | warn | ELEVATED publishToState: value generated '255' from device 0c4314fffeae1bb9 for 'Link quality'
zigbee.0 | 2022-03-20 20:08:41.447 | warn | ELEVATED publishToState: message received '{"linkquality":255}' from device 0c4314fffeae1bb9 type 'E1743'


</body>
</html>
>

**Comment by asgothian** [comment]
The logs show clearly that the states for the buttons are being updated as they should.

The messages with
`value generated  <value> frrom <device> for <state>`
are generated when the state is updated.

A.
