### ISSUE TITLE
Tab GROUPS mising

### ISSUE THREAD

**Issue by sir0drake** [ioBroker/ioBroker.zigbee#1355]
Hello,

updated from 1.6.6 -> 1.6.14 and the tab GROUPS is missing.
Also after restart iob.

a new group 901 was automatically created but empty.

is there any trigger i have to activate to got the GROUP-Tab?

brgds
drake

![image](https://user-images.githubusercontent.com/77205165/152640405-bdcdcff7-ab0e-41d8-8270-4b226435be35.png)

**Comment by asgothian** [comment]
The groups tab is gone. Your groups are managed using the group/device tiles (add devices from device tiles, see members / rename / delete groups from the group tile)

the group 901 has existed before too but was not accessible through the zigbee adapter. You can use it or delete it.

a.
