### ISSUE TITLE
Fehlende Paramter in Gruppen (Hue Color lamps)

### ISSUE THREAD

**Issue by schluff81** [ioBroker/ioBroker.zigbee#1356]
Hi,

Hue white and color ambiance E26/E27/E14 Lampen haben ein einzelnes Gerät Paramter, wie z.B. "Hue" oder auch "Saturation". Damit ist es möglich z.B. via iot-Adapter über Alexa Ansagen zu machen "Alexa, mache das Licht der Lampe XYZ blau". 

Auch kann so z.B. in iqcontrol die Farbe einer einzelnen Lampe einfach geändert werden. 

<img width="1037" alt="Screenshot 2022-02-05 124802" src="https://user-images.githubusercontent.com/94967852/152640803-69ef2e48-41e6-44f8-86aa-c422c45bcb59.png">

In Gruppen geht das leider nicht:

<img width="1040" alt="wohn" src="https://user-images.githubusercontent.com/94967852/152640847-bc00b287-3a2e-4d84-9bde-89cb59a1a87e.png">

Wobei, RGB gibt es - da können hues nur nichts sinvoll ohne viel Aufwand mit anfangen ;)

**Comment by asgothian** [comment]
This requires some testing. I am not sure that Hue and Sat can be set in groups, and it is not certain how to deal with groups with different devices in:

- Outlets, which only offer on/off
- Lights or dimmers, which offer on/off/brightness
- Lights which offer on/off/brightness/colortemp
- Lights which offer on/off/color_rgb
- Lights which offer on/off/brightness/colortemp/color_rgb
- Lights which offer on/off/brightness/colortemp/color_hs

A.

**Comment by schluff81** [comment]
I'm coming from the DeCONZ adapter. Here, it is possbile to set Hue ant Sat in groups. 

Regarding different devices I would suggest to keep things easy (at least for mix of hue supporting light and those only able to change brightness and colortemp): 

- If Hue and or Sat are changed, only change the correspoding lamps. Keep the other ones untouched
- If e.g. Brightess is changed: Change the brightness of all lamps

Not sure how to deal with a mix of RGB and Hue in combination. Maybe, this szenario needs be exkluded in a first shot. 

Daniel

**Comment by asgothian** [comment]
> I'm coming from the DeCONZ adapter. Here, it is possbile to set Hue ant Sat in groups.
> 
> Regarding different devices I would suggest to keep things easy (at least for mix of hue supporting light and those only able to change brightness and colortemp):
> 
> * If Hue and or Sat are changed, only change the correspoding lamps. Keep the other ones untouched
> * If e.g. Brightess is changed: Change the brightness of all lamps
> 
> Not sure how to deal with a mix of RGB and Hue in combination. Maybe, this szenario needs be exkluded in a first shot.
> 
> Daniel

I am afraid you are missing the way the groups work:

The command is not sent to every device by the zigbee adapter, but **to the group**. As such, the adapter cannot exclude devices from a command, and i do not know how the devices will react if they receive an unsupported command through the group. I would expect to see error messages from the devices to appear.

A.

**Comment by schluff81** [comment]
Ok, I see. I wonder how deconz handels this

**Comment by asgothian** [comment]
I think the question shouldn't be how Deconz handles this, but how the iobroker adapter should handle this. There are 4 options:

1. Each group also has states for color (Hue, Saturation, RGB, xy), independent of wether the group supports this and with no logic to prevent sending messages to the group. In this case, the adapter would need to suppress possible error messages from trying to set characteristics which do not exist, but the states for each group would be the same. This would add approx. 10 states per group to the states.
2. Each group also has states for color (Hue, Saturation, RGB, xy) plus a state which describes the known abilities of the group members. This state would have to be bitcodes to code in "on/off", "brightness", "colortemp", "RGB", Hue/Sat", "XY". It would be set whenever the group is modified but could be overridden by the user. Messages to the group would only be generated if the state in question is linked to one of the supported functions. The adapter would in this case not suppress any error messages generated when controlling the group. This would lead to a large number of states which can be changed but would not have any effect, as most groups will consists of lights with no color options.
3. Each group only has states for the functions at least one member offers. In this case, each group modification would modify the available states. This could lead to issues if a group is changed and the groups states are used in scripts / visualisations as these would attempt to write to states which no longer exist.
4. No change - the group states stay as they are and color cannot be controlled by the group.

I am curious to hear what people think about this.

A.
