### ISSUE TITLE
Xiaomi GZCGQ01LM Lichtsensor - Wert "illuminance" bleibt Null

### ISSUE THREAD

**Issue by Lassebroker** [ioBroker/ioBroker.zigbee#1357]
Der Lichtsensor lief 2 Jahre problemlos. Seit dem 24.12. sendet er plötzlich gar keinen Wert. Er ist aber available und die link-quality ändert sich auch, je nach Standort.

Habe nun mal einen neuen bestellt, weil ja vielleicht der Sensor kaputt ist. Aber hier ist das gleiche! Der Wert ist und bleibt (null).

Hier mal ein die History vom 23.12./24.12. (weiß nicht, was ich sonst posten könnte):
![Lichtsensor](https://user-images.githubusercontent.com/59196904/152650770-127ec294-d968-47a9-aede-33d45456c0a3.jpg)
 
Hat jemand eine Idee???

Vielen Dank!

**Comment by asgothian** [comment]
Versuch mal folgendes:

- Sensor wach halten (ca. alle 3 Sekunden die Taste drücken
- Auf der umgedrehten Kachel des Sensors eine reconfiguration auslösen

A.

**Comment by Lassebroker** [comment]
Sensor wach halten hat leider nichts gebracht. 

> * Auf der umgedrehten Kachel des Sensors eine reconfiguration auslösen

Hab ich nicht gefunden (bitte einmal Info, wo das auf der umgedrehten Kachel zu finden ist). 

Daher (nochmal) gelöscht, neu gepairt und dann den Kopf immer mal wieder lang gedrückt halten. Der Punkt "zigbee.0.***.msg_from_zigbee" hat nun einen anderen Wert als vorher bekommen. Und einer der beiden funktioniert nun?!? Hoffe, das bleibt so. 

Danke!

**Comment by asgothian** [comment]
- Du musst schon beides Tun. 
- Welche Adapter version nutzt du ? Das Reconfigure gibt es erst ab 1.6.12
- Das sich der msg_from_zigbee ändert bedeutet nur das der Sensor "irgendetwas" meldet. das kann auch nur seine LQI sein. Das bedeutet nicht das die Helligkeitswerte aktualisiert werden.

A.

**Comment by Lassebroker** [comment]
Ok, ich nutze nur 1.6.6 (stable). Da jetzt wenigstens einer wieder geht, kann ich hier schließen.
