### ISSUE TITLE
Support Aubess Zigbee Steckdose

### ISSUE THREAD

**Issue by Stoertebek3r** [ioBroker/ioBroker.zigbee#1360]
Hi ist es möglich die Steckdose in die supported Geräteliste aufzunehmen? 

https://de.aliexpress.com/item/1005003749369777.html?gatewayAdapt=glo2deu&spm=a2g0o.9042311.0.0.213b4c4dOpwBDd

Wäre echt cool. Sind günstig und funktionieren super. Würde sie gerne mit ioBroker nutzen...

**Comment by asgothian** [comment]
- Hast du versucht sie im Adapter einzubinden ?
- Wenn ja, mit welcher Adapter-Version ? Mit welchem Ergebnis ? Mit welcher (i) Kachel ?

A.

**Comment by Stoertebek3r** [comment]
Moin, ja, ich habe sie versucht einzubinden. Adapter Version ist 1.6.6 ! Gerät wurde gefunden als TS011F. Bild ist ein Fragezeichen... Was meinst du mit Kachel?
<img width="836" alt="TS011F" src="https://user-images.githubusercontent.com/99180519/153275979-3ea72ff9-21cc-45e6-8402-302150a85725.PNG">

**Comment by asgothian** [comment]
- Thema Kachel: Siehe Adapter Readme auf Github - die Darstellung der Geräte im Adapter.
- Thema "Info" Kachel - das was angezeigt wird wenn Du auf das blaue (i) auf der entsprechenden Kachel drückst.
- Thema neue Geräte: die Version 1.6.6 ist ca. 3 Monate alt. Wenn du sehen willst ob die Steckdose geht solltest du zunächst auf eine neuere Version hoch gehen (1.6.12 aus latest oder 1.6.14 aus GitHub). Vielleicht geht die Dose schon, vielleicht nicht.
A.

**Comment by Harry7123** [comment]
Gibt es bereits eine Lösung für die Aubess Steckdose.

**Comment by asgothian** [comment]
Musst du ausprobieren. Ich kenne (außer dem OP) niemand der das Gerät besitzt.

Entweder sie geht oder nicht.
