### ISSUE TITLE
Version 1.6.14 - Lamp with no Group selector

### ISSUE THREAD

**Issue by UweLoyal** [ioBroker/ioBroker.zigbee#1362]
After Upgrade to Version 1.6.14, one Lamp/Device of five has no group dropdown.
How can i fix that problem, to get ther also group dropdown.
Also the device info is difference.

![Bild_1A](https://user-images.githubusercontent.com/5464553/152852801-f7a9d96e-82b8-437c-9d60-104c678f2e63.jpg)
![Bild_1B](https://user-images.githubusercontent.com/5464553/152852813-cc37c199-9285-4b2d-b65d-550a88d75134.jpg)
![Bild_2A](https://user-images.githubusercontent.com/5464553/152852849-e0ef736b-8810-4b13-a7fd-ab81d2095684.jpg)
![Bild_2B](https://user-images.githubusercontent.com/5464553/152852866-d9ea6237-31b4-4a8b-88a9-c0a6d1a32f0c.jpg)

Rgds
   Uwe

**Comment by asgothian** [comment]
Remove the device from the network and pair it again. It did not report the supported clusters and as such is considered "not groupable". If the error persists, the Firmware may be defective.

A.

**Comment by UweLoyal** [comment]
Device had to be paired many times until it worked!
Now I have a goup dropdown and also the lamp works.

Thank's

Rgds
   Uwe
