### ISSUE TITLE
This object will not be created in future versions. Please report this to the developer,  TS011F_plug_3

### ISSUE THREAD

**Issue by e-i-k-e** [ioBroker/ioBroker.zigbee#1367]
Hi there,
after update from 1.6.14 to 1.6.15.

For info:

<html>
<body>

zigbee.0 | 2022-02-10 22:14:55.139 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2022-02-10 22:14:55.139 | warn | Object zigbee.0.540f57fffefdda6b.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-10 22:14:55.138 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-10 22:14:55.138 | warn | Object zigbee.0.540f57fffefdcb10.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-10 22:14:55.137 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-10 22:14:55.136 | warn | Object zigbee.0.84ba20fffe77b85e.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-10 22:14:55.103 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-10 22:14:55.103 | warn | Object 540f57fffefdda6b.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-10 22:14:55.102 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-10 22:14:55.101 | warn | Object 540f57fffefdcb10.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-10 22:14:55.100 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-10 22:14:55.099 | warn | Object 84ba20fffe77b85e.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-10 22:14:54.501 | info | deregister device Ping for deactivated device "0x680ae2fffe6e8dc0"
zigbee.0 | 2022-02-10 22:14:54.492 | info | debug devices set to []
zigbee.0 | 2022-02-10 22:14:54.284 | info | Zigbee started

</body>
</html>

Device: _84ba20fffe77b85e_ , _540f57fffefdcb10_ , _540f57fffefdda6b_
![image](https://user-images.githubusercontent.com/83473829/153498460-06d7bfd5-dcc0-4feb-aba5-6611d6df0011.png)

![image](https://user-images.githubusercontent.com/83473829/153499173-cc76409f-099b-4d50-8ce4-3d8e3ab21b6c.png)

**Comment by e-i-k-e** [comment]
```
{
  "type": "state",
  "common": {
    "name": "Plug LED indicator mode",
    "type": "string",
    "states": "off:off;off/on:off/on;on/off:on/off;on:on",
    "read": true,
    "write": true,
    "role": "state"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1644527695138,
  "_id": "zigbee.0.540f57fffefdcb10.indicator_mode",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by e-i-k-e** [comment]
Im use 4.0.8.

**Comment by asgothian** [comment]
Please downgrade to 3.3 and verify if the warning occurs there too.

A.

**Comment by arteck** [comment]
stop the adapter
del only this object
start adapter 

and now ?

**Comment by e-i-k-e** [comment]
Hello, unfortunately no improvement. The data points were recreated. However, the error is still available.

I haven't tested the downgrade of the js.controller yet.

<html>
<body>


zigbee.0 | 2022-02-14 10:43:46.365 | warn | (71919) DeviceAvailability:Failed to ping 0x680ae2fffe818deb TRADFRI bulb E14 WS 470lm
-- | -- | -- | --
zigbee.0 | 2022-02-14 10:43:29.370 | warn | (71919) This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-14 10:43:29.370 | warn | (71919) Object zigbee.0.540f57fffefdcb10.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-14 10:43:29.369 | warn | (71919) This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-14 10:43:29.369 | warn | (71919) Object zigbee.0.84ba20fffe77b85e.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-14 10:43:29.300 | warn | (71919) This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-14 10:43:29.300 | warn | (71919) Object 540f57fffefdcb10.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-14 10:43:29.299 | warn | (71919) This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-02-14 10:43:29.298 | warn | (71919) Object 84ba20fffe77b85e.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-02-14 10:43:28.129 | info | (71919) debug devices set to []
zigbee.0 | 2022-02-14 10:43:27.925 | info | (71919) Zigbee started


</body>
</html>
