### ISSUE TITLE
Some missing images

### ISSUE THREAD

**Issue by DcFamas** [ioBroker/ioBroker.zigbee#1369]
Hey there,
for a long time I have the cosmetic problem, that some pictures are wrong or missing:

Missing:
![grafik](https://user-images.githubusercontent.com/35306967/153747422-d8fabc8b-e4d1-4487-a769-09492faafea4.png)
Device:
https://www.zigbee2mqtt.io/devices/HG06335_HG07310.html

Background not transparent:
![grafik](https://user-images.githubusercontent.com/35306967/153747443-68f22ebd-32ce-45a1-ae9d-e7dba5dfbba1.png)
Device:
https://www.zigbee2mqtt.io/devices/ZBMINI.html

Picture doesn't fit to the whole design:
![grafik](https://user-images.githubusercontent.com/35306967/153747470-a2662928-1557-43aa-a833-f1514640ac33.png)
Device: 
https://www.zigbee2mqtt.io/devices/HG06467.html
(Same here)

Maybe the original picture is better:
https://www.lidl.de/p/melinera-lichterkette-zigbee-smart-home/p100312329

Maybe it would be great if you can implement them. :)
Best regards

**Comment by asgothian** [comment]
Images are no longer part of the adapter code. They are taken from zigbee2mqtt.io.

A.
