### ISSUE TITLE
Update failing from 1.614-.14 to 1.6.15

### ISSUE THREAD

**Issue by COMHOME** [ioBroker/ioBroker.zigbee#1371]
$ ./iobroker upgrade zigbee
ERROR: Cannot check dependencies: Required dependency "admin" not found on this host.
process exited with code 0

Admin-Adapter is not installed on that host, because it's running just as client.
After creating an instance onnmy client-ioBroker, update works without problems.

But the main problem is, that till now, i didn't need an extra admin-instance running.
Why is there now a dependency to the admin adapter?

**Comment by wendy2702** [comment]
You are not alone:

Check here: https://forum.iobroker.net/topic/52551/zigbee-adapter-nach-update-rot?_=1644947983055

**Comment by arteck** [comment]
fixed
