### ISSUE TITLE
Datenpunkt "name" mit erstellen

### ISSUE THREAD

**Issue by DerDoubleD** [ioBroker/ioBroker.zigbee#1372]
Hallo

Ist es möglich einen zusätzlichen Datenpunkt pro Device zu erstellen in der entweder selbst definierbar ist oder noch besser den "friendly_name" enthält?

**Comment by asgothian** [comment]
Please explain the reasoning behind this.

A.

**Comment by asgothian** [comment]
Wieso kommst du nicht an die Namen der Sensoren ?
Welche Logik-Engine nutzt du ?

**Comment by DerDoubleD** [comment]
@asgothian

Ich glaube wir reden aneinander vorbei.
Ich versuche es besser zu erklären.

Wie komme ich den an den Namen Haustür in Blockly oder Javascript ran?
![image](https://user-images.githubusercontent.com/47006370/154443617-5555c24a-5059-46a6-9030-587629246701.png)

Wenn es eine Datenpunkt mit name = Haustür geben würde wäre es einfach!

Der Datenpunkt name könnt entweder von User selbst belegt werden oder durch den Adapter.
Der Adapter muss ja auch irgendwo das Haustür her haben.

**Comment by asgothian** [comment]
In JS:

```
const obj1 = getObject('zigbee.0.000b57fffe8f487d');
console.warn(obj1.common.name);

on('zigbee.0.000b57fffe8f487d.state', function(obj) {
    console.warn(obj.channelName)
});
```

In Blockly kommt man da nur Über den Trigger ran, da es da kein 'getObject' gibt.
<img width="380" alt="Screen Shot 2022-02-17 at 18 36 01 " src="https://user-images.githubusercontent.com/45667167/154538627-9024757d-1151-46e0-afe2-3ac8d72b0a81.png">

**Comment by DerDoubleD** [comment]
@asgothian

Danke für das Beispiel!
Damit funktioniert es.
Macht es zwar etwas aufwendiger aber ich kann damit leben!

**Comment by asgothian** [comment]
Closing this since
- there is a workable solution for the OP
- there seems to be no additional interest.
