### ISSUE TITLE
Update Stable 1.6.16, alle batteriebetriebenen geräte geht batterieleistung nahe 0

### ISSUE THREAD

**Issue by weindler** [ioBroker/ioBroker.zigbee#1374]
Hallo,

mir wurde heute das update 1.6.16 des Zigbee Adapters in der Stable Version angeboten, lief auch durch im Protokoll waren keine Fehler zu finden. Doch seitdem wird die Batterieleistung der batteriebetriebenen Zigbeegeräte minütlich weniger, siehe screen
![Screen_Batterie_160222](https://user-images.githubusercontent.com/41335851/154314247-d64b6a4a-cd40-449d-8bdc-13fd4b447057.jpg)
.
Die waren vor dem Update alle auf ca. 80 - 95%

Bei den neuen Fenstersensoren [MCCGQ14LM](https://www.zigbee2mqtt.io/devices/MCCGQ14LM.html) stimmt die Batterie anzeige nicht, hier scheint wie wenn ein Komma oder Punkt vergessen worden wäre, hierzu gibt es aber bereits ein Issue.

https://github.com/ioBroker/ioBroker.zigbee/issues/1280

Node.js
    v14.19.0
NPM
    6.14.16
js-controller
3.3.22

**Comment by DcFamas** [comment]
Selbes Problem bei mir.

**Comment by asgothian** [comment]
Duplicate of #1370

**Comment by asgothian** [comment]
Duplicate of #1370
