### ISSUE TITLE
Power on behavior Ikea Tradfri Float

### ISSUE THREAD

**Issue by DcFamas** [ioBroker/ioBroker.zigbee#1375]
Hey there,
for a long time I've set a delay to trigger off my Ikea Devices after a power failure. Now I've seen that Ikea made it possible to change the behavior after a power failure. Koenkk also implemented this in zigbee2mqtt. I checked my objects in ioBroker, I cannot spot a attribut for this setting. Would it possible to implement this?

https://www.zigbee2mqtt.io/devices/L1527.html#power-on-behavior-enum

Personally I'm using the [L1527](https://www.zigbee2mqtt.io/devices/L1527.html), [L1528](https://www.zigbee2mqtt.io/devices/L1528.html), [ICPSHC24-30EU-IL-1](https://www.zigbee2mqtt.io/devices/ICPSHC24-30EU-IL-1.html) and [ICPSHC24-10EU-IL-1](https://www.zigbee2mqtt.io/devices/ICPSHC24-10EU-IL-1.html).

Best regards! :)

**Comment by asgothian** [comment]
The plan for the adapter is to go towards purely using the exposes given from the zigbee-herdsman-converters. I consider this addition to be unlikely as you can already use it by using the "SendToDevice" functionality.

There will be a state where you can directly script the payload for a sendtodevice in a future adapter version, though.


```
sendTo('zigbee.0', 'SendToDevice', {'device':'00158d0007558553', 'payload':{ 'power_on_behavior ':  'on '}}, function(res) {
    if (res.success)
    console.log("success")
    else
    console.log(res.error);
});
```

**Comment by DcFamas** [comment]
Haven't heard of this possibillity before.
In my case this is works for me, 'cause you never (hopefully) have to change the power_on_behaviour again.

The log said:
`javascript.0 | 2022-02-16 23:10:28.277 | info | script.js.Float: success`

When I tried to shut the power off, everything worked like a charme.
Thank you for your quick response and hopefully have a quiet night without a missing roof tile tomorrow morning. 👍

**Comment by asgothian** [comment]
This can now be done without resorting to the sendTo function. 

With the latest 1.6.16 version, each device gains a 'send to device' state which can be filled with the desired payload to perform device specific configurations.

A.

**Comment by DcFamas** [comment]
Hey @asgothian wo kann ich die entsprechenden Punkte finden? Hab ein Objekt schon neu anlegen lassen, irgendwie bin ich blind:

![grafik](https://user-images.githubusercontent.com/35306967/157447810-ab4abc49-70ac-4a89-b394-5014293c96ee.png)

1.6.16 ist installiert. Danke auf jeden Fall, dass du hier noch nachgearbeitet hast!

**Comment by asgothian** [comment]
I am afraid that the current latest version was pulled before i added it. In order to get the state you will have to install the current GitHub version

**Comment by DcFamas** [comment]
Worked! :)
