### ISSUE TITLE
Neuerdings Probleme mit Rauchmelder AV2010/24 und Außensirene AV2010/29

### ISSUE THREAD

**Issue by kptkip** [ioBroker/ioBroker.zigbee#1376]
Seit einigen Versionen des Adapters funktioniert der Alarm-Trigger meiner [AV2010/24](https://www.zigbee2mqtt.io/devices/AV2010_24.html) Rauchmelder nicht.

Ich habe auch die baugleiche Version [AV2010/24A](https://www.zigbee2mqtt.io/devices/AV2010_24A.html) im Einsatz. Bei diesen kann der Alarm nach wie vor super gesetzt werden.

BTW: meine Außensirene [AV2010/29](https://www.zigbee2mqtt.io/devices/AV2010_29.html) hat seither das gleiche Problem.

Was sich softwareseitig ebenfalls verändert hat, ist der komplette Aufbau der Datenpunkte (s. Anhang).

Hat das Problem jemand anderes auch und hat mir einen Tipp?

<img width="325" alt="Bildschirmfoto 2022-02-17 um 10 32 32" src="https://user-images.githubusercontent.com/16083703/154448871-5d46005a-1077-45c7-bfed-2622410e7c03.png">
<img width="318" alt="Bildschirmfoto 2022-02-17 um 10 32 51" src="https://user-images.githubusercontent.com/16083703/154448875-618dfce0-715d-472e-b6eb-2ca31ec6c5c8.png">
<img width="1248" alt="Bildschirmfoto 2022-02-17 um 10 33 46" src="https://user-images.githubusercontent.com/16083703/154448878-e7522eb8-d91d-429c-be7e-156bc74f7d70.png">
<img width="1238" alt="Bildschirmfoto 2022-02-17 um 10 33 59" src="https://user-images.githubusercontent.com/16083703/154448883-d87cb177-d670-43a8-b9a6-5866d23e7720.png">

**Comment by arteck** [comment]
doppelpost
