### ISSUE TITLE
JTYJ-GD-01LM/BW wird nicht vollständig erkannt.

### ISSUE THREAD

**Issue by DerDoubleD** [ioBroker/ioBroker.zigbee#1378]
Hallo

Der Rauchmelder _"MiJia Honeywell smoke detector"_ wird nicht komplett erkannt.

![image](https://user-images.githubusercontent.com/47006370/154548655-2772ac50-9ec5-41b5-8738-e18daab56901.png)
![image](https://user-images.githubusercontent.com/47006370/154548743-25c14fe3-310a-4bf0-ac65-df3c4038ec9b.png)

**Comment by DcFamas** [comment]
Nochmal pairen, hab das auch öfter gehabt beim einrichten.
Setze von den Dingern acht ein.

**Comment by kptkip** [comment]
kann man bei den Geräten die Sirene per Befehl aktivieren?
