### ISSUE TITLE
Homa1001 unknown

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.zigbee#1381]
![image](https://user-images.githubusercontent.com/8565847/154794306-b41494f4-b5a4-473f-961c-26b4cc536b8c.png)

I recently switched from deconz to this adapter. However, one of my dimmers does not want to. It always shows up as unknown. Does anyone have any ideas?

**Comment by asgothian** [comment]
- which adapter version are you running ?
- Is the device listed as supported on zigbee2mqtt.io ?

A

**Comment by n3roGit** [comment]
![image](https://user-images.githubusercontent.com/8565847/155172356-b534d84f-f1d4-42c6-9c2e-a4beb69acdfd.png)


I'm not sure exactly which controller this is. I suspect this one:
https://www.zigbee2mqtt.io/devices/HLC610-Z.html

**Comment by arteck** [comment]
try repair the device..

**Comment by n3roGit** [comment]
> try repair the device..

How to do that?

**Comment by asgothian** [comment]
Please flip the tile and click on the blue (i) icon to show the device details. it seems that this device is unknown in the zigbee-herdsman-converters.

A.
