### ISSUE TITLE
Unable to bind Ikea E1524/E1810 to group

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.zigbee#1382]
Hi,

I'm trying to make a binding from Ikea E1524/E1810 to a group of two Ikea Tradfri bulbs.

In the binding dialog, I can't select a target endpoint from the group, so the binding is not working:

![image](https://user-images.githubusercontent.com/34286177/154821273-41c7e5a6-ff3b-4fad-b1c5-fd4efacfefbc.png)

There are no values behind the dropdown for target endpoint.

There are two message in Log when creating the binding:

```
zigbee.0 | 2022-02-19 23:29:40.941 | warn | Object of state "zigbee.0.info.bind_ccccccfffe30c5a4_1_4_undefined" is missing the required property "common.type"
zigbee.0 | 2022-02-19 23:29:37.275 | warn | getBindEp called with illegal ep: undefined
```

Any ideas ?

Thanks and kind regards, Ralf

**Comment by kptkip** [comment]
Hallo Ralf,

Hast du es schon über die Zuordnung zur Gruppe probiert, anstatt es über ein Bin ding zu probieren?
Gruß Alex

**Comment by gaudes** [comment]
@kptkip : Schalter können nicht einer Gruppe zugeordnet werden.

**Comment by kptkip** [comment]
@gaudes 
Ah, du willst den Schalter mit der Gruppe "binden". Hatte ich falsch verstanden.

Bin leider kein Binding-Profi, aber kann es sein, dass Bindings nur auf Geräte-Ebene funktionieren?

**Comment by gaudes** [comment]
@asgothian : Any ideas ? Thanks and regards, Ralf

**Comment by gaudes** [comment]
Someone any ideas ?
Thanks and regards, Ralf

**Comment by BenjaminHae** [comment]
More or less the same here. I'm trying to bind a tradfri ON/OFF Switch E1743 to a TRADFRI control outlet E1703.
This is shown in the logs:

zigbee.0 | 2023-11-18 17:15:03.125 | warn | Object of state "zigbee.0.info.bind_804b50fffe04e9f9_1_804b50fffe5f91b4_1" is missing the required property "common.type"
-- | -- | -- | --
zigbee.0 | 2023-11-18 17:15:03.112 | info | Successfully bound cluster 'genLevelCtrl' from '0x804b50fffe04e9f9' to '0x804b50fffe5f91b4'
zigbee.0 | 2023-11-18 17:15:02.098 | info | Successfully bound cluster 'genOnOff' from '0x804b50fffe04e9f9' to '0x804b50fffe5f91b4'

The binding is shown in the UI afterwards. Adapter version is 1.8.24.
