### ISSUE TITLE
AnyOn datapoint for using groups with scenes

### ISSUE THREAD

**Issue by ScumbagSteve** [ioBroker/ioBroker.zigbee#1389]
I have a group for every single room.
Most of the times however I control my lights via scenes. My scenes turn every single light to it's desired state (brightness, color, on/off). Right now, the group remains turned off, when I control the individual lights via scenes (even though in the end all members of the group are "on"). This however gives me no possibility to see the "real" on / off state of the room in my visualization.

I would like to propose two possible solutions, based on what I saw in the hue-extended adapter:
1. Intoduce a data-point "AnyOn" for groups, which show for each group if a member is turned on.
2. Change the behavior of the "state" for groups. When a member is on, change state for the group to "on" as well.

**Comment by ScumbagSteve** [comment]
This is still up-to-date and would be an useful improvement.

**Comment by asgothian** [comment]
Closing due to lack of interest / implementable ideas.
