### ISSUE TITLE
Please support GLEDOPTO GL-S-007Z (GU10) - still doesn't work

### ISSUE THREAD

**Issue by joerghildering** [ioBroker/ioBroker.zigbee#139]
Please support GLEDOPTO GL-S-007Z (GU10)
https://de.aliexpress.com/item/GLEDOPTO-fabrik-ZIGBEE-ZLL-5-watt-RGBWW-CW-GU10-LED-RGB-dual-wei-scheinwerfer-AC100-240V/32918206788.html?spm=a2g0x.search0104.3.2.ac8f7ad6cn67KI&ws_ab_test=searchweb0_0%2Csearchweb201602_4_10320_10065_10068_10890_10547_319_10546_317_10548_10696_453_10084_454_10083_10618_431_10304_10307_10820_537_536_10843_10059_10884_10887_100031_321_322_10103%2Csearchweb201603_1%2CppcSwitch_0&algo_pvid=3fbd2eee-554d-4ce5-bd73-02b908794832&algo_expid=3fbd2eee-554d-4ce5-bd73-02b908794832-0

**Comment by arteck** [comment]
done

**Comment by joerghildering** [comment]
> done

Sorry, but I'm new at this. How can I integrate this?

**Comment by joerghildering** [comment]
> done

I installed 0.8.2a but it still says: "undefined 00124b001ad77224"

**Comment by joerghildering** [comment]
Still says "undefined 00124b001ad77224" with 0.9.0. Did someone has a working sollution for it?

**Comment by kirovilya** [comment]
After upgrading to version 0.9.0, try removing the device and re-pairing

**Comment by joerghildering** [comment]
I allready tried this.

**Comment by kirovilya** [comment]
send me your the shepherd.db database
it is in iobroker-data/zigbee_0

**Comment by joerghildering** [comment]
@kirovilya I sent it to your gmail address.

**Comment by plubi** [comment]
Version 0.10.2 and the lamp still does not work :-(
