### ISSUE TITLE
Tint power strip, no information in the adapter

### ISSUE THREAD

**Issue by zakuma666** [ioBroker/ioBroker.zigbee#1392]
Hey,

I just bought the "Müller Licht" Smart power Strip outlets.
I can add them to my Adapter, but he has just standard data points like available/Link quality but nothing like state for the button.

What can I do to add it? Also there is no Icon for this device, even its in the list for supported devices.

Thank you for your help!

**Comment by asgothian** [comment]
- which version are you using ?
- is it listed as supported on [this page](https://www.zigbee2mqtt.io/supported-devices/)
- can you post the tile for the device as well as the info dialog (flip the tile, press the little blue (i)
A.
