### ISSUE TITLE
Lidl HG06106A undefined

### ISSUE THREAD

**Issue by e-i-k-e** [ioBroker/ioBroker.zigbee#1395]
Hi,

I have integrated a newly purchased Lidl HG06106A. But the device is always shown as undefined.
I've deleted, reset, and retrained the device multiple times. I also positioned the device next to the coordinator as a test.
No improvement.
Use Zigbee version 1.6.16 and the Coordianator TI cc26x2r1 with version 2-1.2.7.1.

![image](https://user-images.githubusercontent.com/83473829/158033579-beccc94c-a7ea-442e-bd10-9f8c018ac297.png)

![image](https://user-images.githubusercontent.com/83473829/158033569-0b25687d-d364-444a-a4a8-56150e874c39.png)

```
Pairing time left: 147
Interview successful: {"friendly_name":"0x842e14fffe669db4","model":"HG06106A","vendor":"Lidl","description":"Livarno Lux GU10 spot RGB","supported":true}
Pairing time left: 148
Device '0x842e14fffe669db4' announced itself
Interview started: 0x842e14fffe669db4

Pairing time left: 184
Pairing time left: 185
Interview successful: {"friendly_name":"0x842e14fffe669db4","model":"HG06106A","vendor":"Lidl","description":"Livarno Lux GU10 spot RGB","supported":true}
Pairing time left: 186

Pairing time left: 196
Device '0x842e14fffe669db4' announced itself
Pairing time left: 197
Pairing time left: 199
Interview started: 0x842e14fffe669db4
Pairing time left: 200
Pairing started 
```

Now may have nothing directly to do with the device.
Then I installed the current version via Github as a test.
This causes my Zigbee adapter to crash after a while.

I noticed this behavior several times, even after a complete restart.

<html>
<body>

host.ioBroker-Rock | 2022-03-12 19:25:57.982 | warn | Do not restart adapter system.adapter.zigbee.0 because restart loop detected
-- | -- | -- | --
host.ioBroker-Rock | 2022-03-12 19:25:57.981 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.ioBroker-Rock | 2022-03-12 19:25:57.981 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker-Rock | 2022-03-12 19:25:57.981 | error | Caught by controller[0]: at processImmediate (internal/timers.js:466:21)
host.ioBroker-Rock | 2022-03-12 19:25:57.980 | error | Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:175:25)
host.ioBroker-Rock | 2022-03-12 19:25:57.980 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:463:43
host.ioBroker-Rock | 2022-03-12 19:25:57.979 | error | Caught by controller[0]: at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:5299:36)
host.ioBroker-Rock | 2022-03-12 19:25:57.979 | error | Caught by controller[0]: at Object.numericAttributes2Payload (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:140:32)
host.ioBroker-Rock | 2022-03-12 19:25:57.978 | error | Caught by controller[0]: at Array.forEach (<anonymous>)
host.ioBroker-Rock | 2022-03-12 19:25:57.978 | error | Caught by controller[0]: at /opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:288:39
host.ioBroker-Rock | 2022-03-12 19:25:57.978 | error | Caught by controller[0]: at buffer2DataObject (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:132:97)
host.ioBroker-Rock | 2022-03-12 19:25:57.977 | error | Caught by controller[0]: at JSON.stringify (<anonymous>)
host.ioBroker-Rock | 2022-03-12 19:25:57.976 | error | Caught by controller[0]: TypeError: Do not know how to serialize a BigInt
zigbee.0 | 2022-03-12 19:25:56.158 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2022-03-12 19:25:56.156 | info | terminating
zigbee.0 | 2022-03-12 19:25:55.888 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2022-03-12 19:25:55.559 | info | cleaned everything up...
zigbee.0 | 2022-03-12 19:25:55.541 | error | Do not know how to serialize a BigInt
zigbee.0 | 2022-03-12 19:25:55.540 | error | TypeError: Do not know how to serialize a BigInt at JSON.stringify (<anonymous>) at buffer2DataObject (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:132:97) at /opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:288:39 at Array.forEach (<anonymous>) at Object.numericAttributes2Payload (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:140:32) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:5299:36) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:463:43 at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:175:25) at processImmediate (internal/timers.js:466:21)
zigbee.0 | 2022-03-12 19:25:55.539 | error | uncaught exception: Do not know how to serialize a BigInt

</body>
</html>

**Comment by asgothian** [comment]
Please install the current GitHub version - there was a bug with the device description.

The error `Do not know how to serialize a BigInt` is linked to the Issue #1394 

A.

**Comment by e-i-k-e** [comment]
> Please install the current GitHub version - there was a bug with the device description.
> 
> The error `Do not know how to serialize a BigInt` is linked to the Issue #1394
> 
> A.

Hello and many thanks.

Unfortunately the problem persists.

![image](https://user-images.githubusercontent.com/83473829/158125565-3388920c-873a-4486-b39c-7de75d674c5f.png)

![image](https://user-images.githubusercontent.com/83473829/158125584-ff194c72-7f0f-46d3-853d-b2a85519a74a.png)

![image](https://user-images.githubusercontent.com/83473829/158125626-bc43e65b-d928-4367-9d32-4bfe2d70cd5e.png)

**Comment by e-i-k-e** [comment]
Thanks. Has worked now
