### ISSUE TITLE
BlitzWolf SHP-13 are not regoniced correctly

### ISSUE THREAD

**Issue by smarteshome2020** [ioBroker/ioBroker.zigbee#1396]
Hi, i use iobroker with ZigBee Adapter V1.6.16 in combination with Conbee2 (latest Firmware). Today i get four new BW-SHP13 and all not working. The Adapter regoniced the Devices as TS011F and not as TS0121_plug as before. https://www.zigbee2mqtt.io/devices/TS0121_plug.html

existing SHP13:
![image](https://user-images.githubusercontent.com/97242825/158645475-bc492e26-a47a-4763-ac09-66469ddb6098.png)
 
new SHP13
![image](https://user-images.githubusercontent.com/97242825/158645626-cef98417-418e-4ea7-a5fd-7e8fe493a48a.png)

Error Log from iobroker:
zigbee.0 | 2022-03-16 17:30:08.862 | info | (77745) Zigbee: stop joining
zigbee.0 | 2022-03-16 17:28:34.097 | error | at async Commands.reconfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:483:21))
zigbee.0 | 2022-03-16 17:28:34.097 | error | at async Promise.all (index 0)
zigbee.0 | 2022-03-16 17:28:34.097 | error | at processTicksAndRejections (internal/process/task_queues.js:95:5)
zigbee.0 | 2022-03-16 17:28:34.097 | error | at runMicrotasks (<anonymous>)
zigbee.0 | 2022-03-16 17:28:34.097 | error | at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:145:28)
zigbee.0 | 2022-03-16 17:28:34.097 | error | (77745) Reconfigure failed 0xa4c13811be1598c2 TS011F, (TypeError: Cannot read property 'configure' of null
zigbee.0 | 2022-03-16 17:28:34.096 | info | (77745) Configuring 0xa4c13811be1598c2 TS011F
zigbee.0 | 2022-03-16 17:26:56.654 | info | (77745) Successfully interviewed '0xa4c13811be1598c2', device has succesfully been paired
zigbee.0 | 2022-03-16 17:26:00.235 | error | (77745) Device 0xa4c13811be1598c2 "undefined" not described in statesMapping.
zigbee.0 | 2022-03-16 17:25:55.666 | info | (77745) Starting interview of '0xa4c13811be1598c2'
zigbee.0 | 2022-03-16 17:25:51.505 | info | (77745) Zigbee: allowing new devices to join.

**Comment by smarteshome2020** [comment]
Update: I install the Zigbee again and now it look better but not perfect. 
I also delete the two SHP-13 and pairing again. 
Same error in Log.

![image](https://user-images.githubusercontent.com/97242825/158669109-0a97fb6a-164b-4cc5-b319-b1beba61a0ce.png)

But now the Datapoints exist. The SHP13 are stored as TS0101_plug 

`<html>
<body>


zigbee.0 | 2022-03-16 20:19:48.831 | info | (1389) DeviceConfigure successful 0xa4c13811be1598c2 TS011F
-- | -- | -- | --
zigbee.0 | 2022-03-16 20:19:48.324 | warn | (1389) This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-03-16 20:19:48.323 | warn | (1389) Object zigbee.0.a4c13811be1598c2.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-03-16 20:19:48.321 | warn | (1389) This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-03-16 20:19:48.321 | warn | (1389) Object zigbee.0.a4c13811be1598c2.power_outage_memory is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-03-16 20:19:48.319 | warn | (1389) This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-03-16 20:19:48.319 | warn | (1389) Object a4c13811be1598c2.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-03-16 20:19:48.319 | warn | (1389) This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-03-16 20:19:48.318 | warn | (1389) Object a4c13811be1598c2.power_outage_memory is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-03-16 20:19:48.303 | info | (1389) Configuring 0xa4c13811be1598c2 TS011F
zigbee.0 | 2022-03-16 20:19:48.302 | info | (1389) Device '0xa4c13811be1598c2' is supported, identified as: TuYa Smart plug (with power monitoring) (TS011F_plug_1)
zigbee.0 | 2022-03-16 20:19:48.302 | info | (1389) Successfully interviewed '0xa4c13811be1598c2', device has succesfully been paired
zigbee.0 | 2022-03-16 20:18:47.039 | info | (1389) Starting interview of '0xa4c13811be1598c2'
zigbee.0 | 2022-03-16 20:18:32.704 | info | (1389) Zigbee: allowing new devices to join.


</body>
</html>`

**Comment by asgothian** [comment]
Update to the current latest from GitHub, then they should work.

A.

**Comment by smarteshome2020** [comment]
I use 1.6.16 witch is the newest, or?

**Comment by asgothian** [comment]
- Installed from stable or GitHub ?
- If installed from GitHub, installed when ?
A.

**Comment by smarteshome2020** [comment]
I stopped the Adapter V1.6.16 und install again from GitHub. (without deinstall)
The SHP-13 can join, but at first a error, after this error the SHP13 a joinded as TS011_plug1

It looks good and Work, but always with error before.

Error:
![image](https://user-images.githubusercontent.com/97242825/159008058-602f196d-e6a2-41fc-b5dc-ee3f85df7dea.png)

Joined SHP13
![image](https://user-images.githubusercontent.com/97242825/159008325-23728c21-1490-4c63-9e4f-41a6cb041d67.png)

Hyperlink to ts0111_plug (there are only SHP15 listed)
https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html

**Comment by asgothian** [comment]
The error message while pairing can be ignored - it is a relic from when we would only accept devices we explicitly contained in our own states. Now, that is no longer a requirement.

A.

**Comment by smarteshome2020** [comment]
Thanks 👍
