### ISSUE TITLE
Livarno LED LIDL not work

### ISSUE THREAD

**Issue by M1cS0w** [ioBroker/ioBroker.zigbee#1398]
Hello,

I have bought a new LIDL lamp, it was found with zigbee adapter in iobroker, but is not able to use.
It was found as TS0502B Tuya, but is not usable. The lamp called: https://www.lidl.de/p/livarno-home-deckenleuchte-mit-lichtfarbensteuerung-zigbee-smart-home/p100339376?mktc=shopping_shop&gclid=Cj0KCQjw5-WRBhCKARIsAAId9Fnc4Kw8GOfhOUmzdOANAPi8aEPmQT0Nn8Zs26xnyjNDTiijRK_MkHUaAmESEALw_wcB

**Comment by asgothian** [comment]
- Which adapter version
- Installed from ?
- Is it listed at zigbee2mqtt.io as supported ?
- how does the device tile look (backside, with the device description)?
- how does the info tile look (you get this when clicking the blue i on the back of the device tile

A.

**Comment by M1cS0w** [comment]
Hello,

- Adapter version: 1.6.16
- installed from iobroker directly stable repository
- I have only found this informations: https://www.zigbee2mqtt.io/devices/TS0502B.html
- ieee:0x2c1165fffe610dc8 | nwk:47529 (0xb9a9) | model:[TS0502B](https://www.zigbee2mqtt.io/devices/TS0502B.html) |groups:
- 
![image](https://user-images.githubusercontent.com/51213428/159686889-42053cb6-dc19-426f-bbf1-12153755fd08.png)

Regards

**Comment by asgothian** [comment]
Welcome to the madness which is TuYa. The image shows clearly that this is not the device you have. The device you have needs to be added to the zigbee-herdsman-converters.

As it is a TuYa device, this can only be done with access to the device.

A.
