### ISSUE TITLE
many entry in shepherd.db

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#14]
![image](https://user-images.githubusercontent.com/6681528/42417754-2f5b0828-8292-11e8-831d-8f2b435c6a1c.png)

i see same entry in shepherd.db for one and the same device ... why ?

**Comment by kirovilya** [comment]
I think it is this issue https://github.com/zigbeer/zigbee-shepherd/issues/39
and I do not known how to fix it... need research...

**Comment by kirovilya** [comment]
It is not critical - will waiting new zigbee-shepherd implementation :)
