### ISSUE TITLE
essentials Smart Home Thermostat | Model: ESS-HK-TRV-6102

### ISSUE THREAD

**Issue by Heuggi90** [ioBroker/ioBroker.zigbee#1400]
Guten Abend zusammen!

Ich habe hier ein Thermostat von essentials Smart Home / Wesmartify (https://www.wesmartify.de/heizung/heizkoerperradiator/333/essentials-smart-home-heizkoerperthermostat/), welches vermutlich baugleich mit dem beliebten LIDL Silvercrest Zigbee Thermostat ist. Es lässt sich pairen, wird dann allerdings als "TS0601" erkannt.

![image](https://user-images.githubusercontent.com/102488792/160302040-67339432-ea0c-462e-9c8a-1bf6b38475e9.png)

In Iobroker habe ich die neuste Zigbee Adapter Verison 1.6.16 installiert.
Das LIDL Gerät gibt es bei Zigbee2MQTT: https://www.zigbee2mqtt.io/devices/368308_2010.html

Meine Hoffnung ist, dass das Gerät relativ einfach vom bestehenden LIDL Gerät kopiert und integriert werden kann. Könnte das funktionieren?

Wenn mehr Infos benötigt werden, bitte Bescheid geben!

**Comment by asgothian** [comment]
Bitte die Geräteinformation (erreichbar über das kleine (i) in der gepusteten Kachel) posten.

Zum Thema Baugleich:
- Es ist ein TuYa Gerät.
- Es mag elektrisch ähnlich sein wie das von Silvercrest
- Es kann (muss aber nicht) eine vergleichbare Firmware nutzen
- Schon die Bezeichnung TS0601 zeigt deutlich was das bedeuten kann : https://www.zigbee2mqtt.io/supported-devices/#s=TS0601 

Was du versuchen kannst:

- Auf der oben angesprochenen Info-Seite den Eintrag bei "manufacturer" ablesen (sollte irgendwas mit '_TZE200_abscdefg' sein)
- Die Datei lidl.js der Zigbee-Herdsman-Converters identifizieren (zumeist unter /opt/iobroker/node_modules/zigbee-herdsman-converters/devices zu finden
- Darin den Lidl Thermostat finden (so ab Zeile 700ff)
- Die Zeile fingerprint: `[{modelID: 'TS0601', manufacturerName: '_TZE200_chyvmhay'}],` erweitern  auf fingerprint: `[{modelID: 'TS0601', manufacturerName: '_TZE200_chyvmhay'},{modelID: 'TS0601', manufacturerName: '_TZE200_abscdefg'}],` (statt _TZE200_abscdefg natürlich das eintragen was Dein Thermostat meldet)
- Adapter neu starten
- Beten  

 
A.

**Comment by Heuggi90** [comment]
@asgothian Danke für die schnelle Antwort!

Hier die Informationen:
![image](https://user-images.githubusercontent.com/102488792/160396710-0ff9913f-976d-4e92-804b-c48bd997d82d.png)

Es hat funktioniert! 

Wie du geschrieben hast, habe ich die Daten editiert und jetzt wird es entsprechend erkannt und ich empfange die Temperaturen / Modi etc. Daten wie Temperatur konnte ich ebenfalls im iobroker setzen und diese haben sich am Gerät synchronisiert! Ich werde das jetzt mal testen, ob das alles soweit funktioniert. 

Die einzige Auffälligkeit bisher wäre folgender Protokolleintrag:
![image](https://user-images.githubusercontent.com/102488792/160397115-ea685114-efb0-4160-8b46-4dfc82136f52.png)

Weißt du, was das zu bedeuten hat?

**Comment by asgothian** [comment]
Die Meldung bedeutet das der Thermostat nicht baugleich zu dem Silvercrest Thermostat ist - es werden Informationen vom Thermostat gesendet die der Converter nicht kennt.

A.

**Comment by Heuggi90** [comment]
Alles klar, danke. 

Dann muss ich mal schauen, ob ich das rausfiltern / blacklisten kann, die Meldung kommt teilweise schon sehr oft. Wie das genau getriggert wird, konnte ich bisher nicht herausfinden. Es ist mal mehr (ganzes Log voll davon), mal weniger.

Einen direkten Vergleich zu den LIDL Thermostaten habe ich nicht. Ich kann nur vermuten, dass es ähnlich funktioniert. Die meisten Werte lassen sich eintragen und werden akzeptiert. Manchmal gibt es einen "NoConnectionError" wenn ich zB die Temperatur setzen will, dann lädt die Seite neu und danach geht es (stört mich jetzt nicht). Die Schedule Funktion muss ich noch besser austesten (da resettet sich meine Temperatur morgens und nachts immer - ich denke aber das ist normal).

Wird die Änderung an der "lidl.js" bei einem Update des Adapters (o.ä.) eigentlich überschrieben werden?

**Comment by asgothian** [comment]
> Alles klar, danke.
> 
> Dann muss ich mal schauen, ob ich das rausfiltern / blacklisten kann, die Meldung kommt teilweise schon sehr oft. Wie das genau getriggert wird, konnte ich bisher nicht herausfinden. Es ist mal mehr (ganzes Log voll davon), mal weniger.
> 

Herausfiltern kannst du das nicht - du musst dafür sorgen das der Entsprechende "DP" vom Konverter für den Thermostat ausgewertet wird. Dazu musst du weitere Änderungen an den Zigbee-Herdsman-Converters durchführen.


> Wird die Änderung an der "lidl.js" bei einem Update des Adapters (o.ä.) eigentlich überschrieben werden?

Ja, wird sie. Du hast prinzipiell 3 Optionen:
- heraus bekommen wie der Thermostat richtig funktioniert und ihn sauber in den Zigbee-Herdsman-Converters integrieren (dieses ist die beste Variante, erfordert aber auch den tiefsten Einstieg in die Problematik)
- Deine Anpassungen nach jedem update wiederholen
- Mit einem "externen Converter" arbeiten. In diesem Fall liegen Deine Code-Änderungen an einer Stelle wo ein Anpassen des Adapters keine Anpassungen vornimmt. Dazu musst du
-- die Datei Lidl.js kopieren (am besten nach /opt/iobroker/iobroker-data/zigbee_0)
-- die Datei so reduzieren das nur der Thermostat über diese Datei definiert wird.
-- die Pfade bei den "Require" befehlen so anpassen das die geforderten Dateien gefunden werden
-- die Datei (mit Pfad) in der Adapter-Konfiguration als 'externer konverter' eintragen.
Dieser Weg wird mit einem kommenden Update noch etwas weniger steinig

A.

**Comment by Heuggi90** [comment]
Hey ich melde mich mal wieder nach einiger Zeit - ist leider so schnell vergangen. Danke erstmal für deine ausführliche Antwort!

> du musst dafür sorgen das der Entsprechende "DP" vom Konverter für den Thermostat ausgewertet wird. Dazu musst du weitere Änderungen an den Zigbee-Herdsman-Converters durchführen.

Oh, okay schade. Ergibt jedoch Sinn.

Ich muss mal schauen wie die Zukunft mit mir und diesem Gerät weiter geht. Ich bin zwar selbst auch Programmierer, aber hatte bisher nur in der Webentwicklung mal hin und wieder Berührungspunkte mit JS. Punkt 3 deiner Vorschläge erscheint mir der beste Weg für mich. Punkt 1 wäre generell natürlich optimal.

Jetzt im Sommer ist es auch nicht gerade die beste Zeit, um die Thermostate ausgiebig zu testen. 
Meine bisherigen Erkenntnisse mit dem Gerät sind leider etwas durchwachsen: Anfangs hatte es sich ordnungsgemäß bedienen lassen und die einzige Auffälligkeit, war der Spam in den Logs. 

Mittlerweile (ca 2 Monate her) verhält es sich allerdings etwas... merkwürdig. Beispielsweise ignoriert das Gerät (scheinbar) den eigenen Temperatursensor und heizt fröhlich weiter. Auch wenn das Fenster geöffnet wird, erkennt er es nicht und hatte dann aufgrund der kälteren Luft angefangen zu heizen, dann jedoch auch nicht mehr aufgehört (wohl gleiche Ursache wie oberes Problem). Seitdem habe ich es auch ausgeschaltet - da es ja auch warm genug ist.

Ein Update habe ich dabei nicht mal gemacht - und trotzdem hat das Gerät angefangen sich so unterschiedlich zu verhalten. Wenn es mal wieder kälter wird, kann ich das Gerät mal versuchen zu löschen und neu zu pairen, ob das dieses Verhalten ändert.

**Comment by Longlife4ever** [comment]
Gibts an dieser Stelle was neues? Habe das gleiche Thermostat und bekomme es zwar gepaired, jedoch nicht vollständig in den iobroker.
