### ISSUE TITLE
IKEA Tradfri Batterie Statusanzeige

### ISSUE THREAD

**Issue by hoepps2802** [ioBroker/ioBroker.zigbee#1401]
Hallo,

ich habe das Problem das bei meinen IKEA Switch E1743 nach einen Batteriewechsel nicht 100% angezeigt werden, sondern meist nur 60%. Die alte Batterie hatte 0% angezeigt - gemessen hab ich 2,95 V

Hat hier wer auch solche Probleme?

Gruß

Matthias aus Kiel

**Comment by arteck** [comment]
die prozentanzeige wird laut Spannung aus dem converter übernommen.. ob die früher richtig oder falsch war.. ist was anderes..
ob die jetzt richtiger ist.. 
es ist wie es ist..

**Comment by hoepps2802** [comment]
für die Meldung das es Zeit wird die Batterien zu wechseln ist es besser, wenn der Wert auch stimmt.
Jetzt bekomme ich die Meldung das ich wechseln soll, obwohl die Geräte noch funktionieren.

**Comment by arteck** [comment]
wenn die Batterie alle ist... was soll dann das Gerät senden ohne Spannung.. überleg doch mal.. der Adapter weiss es nicht ob das Gerät ausser reichweite ist oder die Batterie alle
