### ISSUE TITLE
Gledopto RGB-CCT controler state are not updated 

### ISSUE THREAD

**Issue by EtzeSte13** [ioBroker/ioBroker.zigbee#1405]
I want to use the Gledopto GL-C-008P Led-Strip Conroller to be controlled via ZigBee Adapter from Iobroker and also to be controlled by a MiLight-MiBoxer remote control FUT089.

It works to pair the Gledopto GL-C-008P with the ZigBee-Adapter AND the FUT089 remote control at the same time. AND the GL-C-008P reacts as well on changes sent via ZigBee as well as from the FUT089 -->  **So far so fine**, 

**BUT** if I change some settings via the FUT089 the states in IoBroker are not changed in the same way. e.g. when I switch of the strip by the FUT089 the state in IoBroker remains still aktive/true. 

Is there a possibility to get changes sent via the FUT089 synchroized in IoBroker states? 

System:

Zigbee-Adapter Verision:1.6.16
Gateway: CC2531 Zigbee USB Gateway runing on a RasPi 3B+ IoBroker Slave

**Comment by EtzeSte13** [comment]
Thank you for your good descripted answer and sorry for my late reply. 
I check the the trigger `device_query` which is stated as a "button". I can receive here some updates of states like 
- state,
- color_state_sturtup
- brightness
- link_quality
- msg_from_zigbee

but not the important ones like 
- color
-  colortemp
-  effect
- ...

is there a possibility to ask via script regarding the missing states? 

br 
E

**Comment by asgothian** [comment]
If you install the latest version from Github you should have a chance of getting at least the color and colortemp ones.

effect cannot be read

**Comment by EtzeSte13** [comment]
Hello asgothian,

sorry for the delay in reply but I was busy with other topics...

I loaded the asapter from Github on Monday I guess and testet it now. 
Now I can see that following states are updated when I make `device_query `:

-) state,
-) color_state_sturtup
-) brightness
-) link_quality
-) msg_from_zigbee
-) **AND colortemp**

but **color** is still not updated. Is it possible to add also that.... the I think it would be OK to use it for my application.

I also recognized that colortemp changes only in a range of 180(warm white) until 495 (cold white) This is not a big issue, but I want only to document it since it is different from the standard that color temrature is shown in Kelvin (avou 2000-6000).

Furthermore I contacted the developer to ask f it is possible to send a updated states to ZigBee as soon there was a change via MiBoxer remote control. For the moment they declined that since the fear to create to much trafic on ZigBee if every change is sent. I will ask them once more to send max. every 1or 2 seconds the latest status  -> only if ther was a change in that time ,then traffic is limited and stops automatically. 

This as update from my side. Maybe you can check what is the problem with updating the color.  That would be fine. 

my best regards 
Etze

**Comment by asgothian** [comment]
Colortemp is provided by the device in mired rather than kelvin. This should be true for 99% of the devices in the zigbee-herdsman-converters. The ioBroker adapter does allow setting ct in Kelvin, but will revert to the value provided by the converter upon read. This cannot be changed.

A similar situation exists with the color state, which is why this one is generally not readable.

A.

**Comment by EtzeSte13** [comment]
Hello,

thanks fo  feedback. I did not know that mired exists but after gogle it it is clear for me how it works and easy to use for me. 

I´m not sure if I understood your answer correct regarding the color: 
does that mean there is no possibility to geht the color state from the controller by query? Is it not possible to send a dedicated request via script to get all the states, especially also color? Color is the only state which is missing to be to be synchronized...and would be important for my use...


In the meanwhile I got the feedback that the controller will not send a trigger if states are changes from MiBoxer. So the only possibility is to ask via script for current status, do you have a example here?
