### ISSUE TITLE
[Feature] monitor channel usage / log warning if load to high

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.zigbee#1406]
I had the problem, that suddenly all my zigbee devices were unreachable. Reason was that zibee is using channel 11 and my wlan router decided to switch to channel 1. Together with heavy wlan usage (running backups) zigbee had no chance to communicate.

Please evaluate the following improment possibility:

At least at startup of the adapter and eventually at regular intervalls check the usage of the selected channel. If the usage of the selected channel is (too) high log an warning or an info.

The functionality to evaluate the channel usage is already available at the configuration panel. So getting the current usage of the selected channel should not be to complicated. The "plus" variant would be to scan whenever a device gets lost / gets unreachable.

I - and for sure others too - was not knowing the possibility of WLAN destroying zigbee this way.

**Comment by asgothian** [comment]
Note that scanning the wireless frequencies will interrupt the zigbee network. A regular scan at random intervals will cause issues with the zigbee network performance.


> I - and for sure others too - was not knowing the possibility of WLAN destroying zigbee this way.

You must not have read much documentation then. It is well documented that WLan and Zigbee share the 2.4 GHz Network, and there are numerous comments on it on various forums on the network.

A.

**Comment by asgothian** [comment]
Closed due to lack of further interest.

**Comment by mcm1957** [comment]
OK, I accept that a technical solution is not possible as scanning would interrupt operation and this is not really desired. And I accept that no one has upvoted - so I see tha lack of intereest too.

But you should rethink your statement about reading to few documentation. For the user perspective it should not be required to scan the internet before using io broker. At least the fact that such questions / problems with WLAN are discussed often ist not known to the majority of users - at least this is my oppinion. And as far as I see the complete ioBroker community ist not the target to create ioBroker for a group of technical freaks only.

Said that, I want to say THANK YOU and all other contributors to this good adapter.

McM
