### ISSUE TITLE
Value not sent to device if set from NodeRed

### ISSUE THREAD

**Issue by easybeat** [ioBroker/ioBroker.zigbee#1407]
Hi

I have a simple NodeRed Node:

![image](https://user-images.githubusercontent.com/37217887/161293246-a6bf3b4b-92c7-4b1d-8aa0-25597db2f555.png)

This does set a state of a device to true.

I can see the value has been entered in the object in ioBroker:

![image](https://user-images.githubusercontent.com/37217887/161293437-64dbcb23-af81-41cb-b0f9-074f743a1e16.png)

but it is not send to the device.

If I do it manually on the object in ioBroker but not through NodeRed.

Any idea what the problem could be?

Thanks for help.

**Comment by asgothian** [comment]
Please verify that you set the value with "control", not "update", i.e. set the value with the "acknowledge" parameter set to false.

A.

**Comment by easybeat** [comment]
Hmmm....sorry where can I set this:

![image](https://user-images.githubusercontent.com/37217887/161304097-bace5c55-2c46-4c36-a04e-8bfcd46a1c79.png)

In NodeRed is no setting for this.

I also created a blockly script to test:

![image](https://user-images.githubusercontent.com/37217887/161304232-767f5b56-414e-416c-a7cb-477af37250be.png)

same issue

**Comment by asgothian** [comment]
I do not use Node Red, but your blockly script is using the wrong block. you need to use the "steuere" block, not "aktualisiere". This is a node-red issue, closing it here.

A.

**Comment by asgothian** [comment]
no need to apologize - it is a valid concern that the adapter doesn't work. I am glad that i was able to help you fix the issue.

A.
