### ISSUE TITLE
obj.common.states has an invalid type! Expected "object", received "string"

### ISSUE THREAD

**Issue by NDoerr** [ioBroker/ioBroker.zigbee#1411]
Hey, 

have paired an Radiator valve with thermostat (GS361A-H04) and get this warnings.

This object will not be created in future versions. Please report this to the developer.
--
zigbee.0 | 2022-04-06 19:24:45.119 | warn | Object zigbee.0.847127fffe056db4.mode_force is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-04-06 19:24:45.116 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-04-06 19:24:45.115 | warn | Object zigbee.0.847127fffe056db4.mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-04-06 19:24:45.102 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-04-06 19:24:45.102 | warn | Object 847127fffe056db4.mode_force is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-04-06 19:24:45.102 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-04-06 19:24:45.102 | warn | Object 847127fffe056db4.mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-04-06 19:24:45.023 | info | Device '0x847127fffe056db4' is supported, identified as: Siterwell Radiator valve with thermostat (GS361A-H04)

**Comment by asgothian** [comment]
- which adapter version ?
- what messages do you get when you enter '056db4' into the state zigbee.0.info.debugmessages (interesting messages are warn messages with the keyword "elevated")
- post logs in code tags, not unformatted.


A.

**Comment by NDoerr** [comment]
Adapter Version: 1.6.16

`

igbee.0 | 18268 | 2022-04-07 11:53:25.308 | warn | ELEVATED publishToState: value generated '22' from device 847127fffe056db4 for 'Local Temperature'
-- | -- | -- | -- | --
zigbee.0 | 18268 | 2022-04-07 11:53:25.307 | warn | ELEVATED publishToState: message received '{"local_temperature":22}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:25.303 | warn | ELEVATED publishToState: value generated '151' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:25.302 | warn | ELEVATED publishToState: message received '{"linkquality":151}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:25.093 | warn | ELEVATED publishToState: value generated '151' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:25.092 | warn | ELEVATED publishToState: message received '{"linkquality":151}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.873 | warn | ELEVATED publishToState: value generated '151' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:24.873 | warn | ELEVATED publishToState: message received '{"linkquality":151}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.670 | warn | ELEVATED publishToState: value generated 'false' from device 847127fffe056db4 for 'Locked'
zigbee.0 | 18268 | 2022-04-07 11:53:24.669 | warn | ELEVATED publishToState: message received '{"child_lock":"UNLOCK"}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.667 | warn | ELEVATED publishToState: value generated '151' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:24.666 | warn | ELEVATED publishToState: message received '{"linkquality":151}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.457 | warn | ELEVATED publishToState: value generated 'true' from device 847127fffe056db4 for 'Valve detected'
zigbee.0 | 18268 | 2022-04-07 11:53:24.456 | warn | ELEVATED publishToState: message received '{"valve_detection":"ON"}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.454 | warn | ELEVATED publishToState: value generated '151' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:24.453 | warn | ELEVATED publishToState: message received '{"linkquality":151}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.266 | warn | ELEVATED publishToState: value generated 'true' from device 847127fffe056db4 for 'Window detected'
zigbee.0 | 18268 | 2022-04-07 11:53:24.265 | warn | ELEVATED publishToState: message received '{"window_detection":"ON"}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.260 | warn | ELEVATED publishToState: value generated '159' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:24.259 | warn | ELEVATED publishToState: message received '{"linkquality":159}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.049 | warn | ELEVATED publishToState: value generated '22' from device 847127fffe056db4 for 'Current Target Temperature'
zigbee.0 | 18268 | 2022-04-07 11:53:24.048 | warn | ELEVATED publishToState: message received '{"current_heating_setpoint":22}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:24.044 | warn | ELEVATED publishToState: value generated '159' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:24.043 | warn | ELEVATED publishToState: message received '{"linkquality":159}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:23.845 | warn | ELEVATED publishToState: value generated '"heat"' from device 847127fffe056db4 for 'Mode'
zigbee.0 | 18268 | 2022-04-07 11:53:23.844 | warn | ELEVATED publishToState: message received '{"preset":"manual","away_mode":"OFF","system_mode":"heat"}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:23.838 | warn | ELEVATED publishToState: value generated '159' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:23.837 | warn | ELEVATED publishToState: message received '{"linkquality":159}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 11:53:20.508 | warn | ELEVATED publishToState: value generated '159' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 11:53:20.508 | warn | ELEVATED publishToState: message received '{"linkquality":159}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 10:53:16.294 | warn | ELEVATED publishToState: value generated '151' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 10:53:16.293 | warn | ELEVATED publishToState: message received '{"linkquality":151}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 10:53:14.266 | warn | ELEVATED publishToState: value generated '10' from device 847127fffe056db4 for 'Link quality'
zigbee.0 | 18268 | 2022-04-07 10:53:14.265 | warn | ELEVATED publishToState: message received '{"linkquality":10}' from device 847127fffe056db4 type 'GS361A-H04'
zigbee.0 | 18268 | 2022-04-07 10:53:14.264 | warn | ELEVATED publishToState: value generated 'true' from device 847127fffe056db4 for 'Available'
zigbee.0 | 18268 | 2022-04-07 10:53:14.263 | warn | ELEVATED publishToState: message received '{"available":true}' from device 847127fffe056db4 type 'GS361A-H04'`

**Comment by NDoerr** [comment]
What I have to do, log is everytime the same.

**Comment by asgothian** [comment]
- keep the log running
- wait for the message `Object zigbee.0.847127fffe056db4.mode_force is invalid: obj.common.states has an invalid type! Expected "object", received "string"` to be present in the log
- wait another few minutes
- post 20 log messages from zigbee.0 before and after the above message appears.

A>

**Comment by arteck** [comment]
too old
