### ISSUE TITLE
Implement the zigbee-herdsman-converters 'meta' information storage

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.zigbee#1412]
The zigbee-herdsman-converters support the use of a "meta" object for a number of converters to store configurable data for single devices. Unfortunately, this is not used in a concise manner across all converters.

If memory serves correctly, a meta property did exist at some time but was at least partially removed.

There are a number of converters (including the one for Aqara P1 Motion Sensor (Device luminous.motion.ac2, see issue #1402)

A review is required to decide if to support the "meta" object globally as it will be supported in the converters in the future or to not support it and wait to see what alternative will be used in the future.

A.

**Comment by asgothian** [comment]
A further review has shown that the adapter does use the meta parameter in the converters to provide data to the converters, but the meta parameter does not link into any kind of permanent or semi-permanent storage, so changes to the meta parameter are not retained.

This requires further investigation to ensure that
- required data is provided in the meta information
- only data which requires persistence is actually stored explicitly after being changed by the converter.

**Comment by backlink-market** [comment]
Does this also affect the motion_sensitivity? I can change it, but is it respected by the sensor?
