### ISSUE TITLE
Missing objects for Aqara Smart Plug SP-EUC01

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.zigbee#1413]
Hi,

I've just bought a Aqara Smart Plug SP-EUC01, see also here:
https://www.zigbee2mqtt.io/devices/SP-EUC01.html

I use current version of the adapter with a ConBee II.

I only see the following objects:

![image](https://user-images.githubusercontent.com/34286177/162284225-cf9c8570-44d7-43dc-a0b2-df72145fb1d1.png)

There should be more objects, as desribed above and here:

![image](https://user-images.githubusercontent.com/34286177/162284307-e316d27e-52d1-4c57-83a7-15ba7d21f5e6.png)

I can execute for example the following command:

![image](https://user-images.githubusercontent.com/34286177/162284529-d52188cd-49e5-4be8-afeb-e2cc565de493.png)

Energy would be interesting with kWh.

Thanks and regards, Ralf

**Comment by asgothian** [comment]
please add the device to the exclude list.
![Screen Shot 2022-04-07 at 22 14 25 ](https://user-images.githubusercontent.com/45667167/162289468-8db0d451-7f7f-446b-895d-72cae7516169.png)

**Comment by gaudes** [comment]
Thanks for your very fast response :-)

Seems to be working now:

![image](https://user-images.githubusercontent.com/34286177/162303302-f78839a2-5ee8-4c0e-8111-fa827cadb1e7.png)

One more question: You've excluded the Aqara Door-/Window-Sensor MCCGQ11LM in your screenshot. I have them also, but not excluded. Why did you exclude them ?

Thanks and regards, Ralf

**Comment by asgothian** [comment]
I'd have to check. Some of the devices are excluded for testing purposes.
