### ISSUE TITLE
Request: Add Livaro Lux LED Bar

### ISSUE THREAD

**Issue by px51** [ioBroker/ioBroker.zigbee#1414]
Hallo zusammen,

v1.6.16 vom ioboker repo
supported: https://www.zigbee2mqtt.io/devices/14149505L_14149506L.html 
ieee:0xb4e3f9fffeba8357
nwk:2823 (0xb07)
model:[TS0505B](https://www.zigbee2mqtt.io/devices/TS0505B.html)

![image](https://user-images.githubusercontent.com/74839878/162432196-685a6fb8-220e-430f-9cee-af5f001ff04d.png)

Wird irgendwie erkannt, kann aber scheinbar nicht kommunizieren: 

![image](https://user-images.githubusercontent.com/74839878/162432419-8e866c33-8a9b-4436-986f-9403ab20f595.png)

Wenn Gerät bei Gelegenheit hinzugefügt werden könnte, wäre das super! 

Vielen Dank schon mal

**Comment by danielthoene** [comment]
Moin!

Habe hier das gleiche Problem - mit diversen Lampen von Livarno (aus dem Lidl-Sortiment).
Die LED-Lichtleiste und die GU10-Strahler werden als TS0505B erkannt. Gerät pairt problemlos - erscheint aber als disconnected. Bei Änderung einzelner States erscheint im Debug-Log `No mapped model for TS0505B`

Bei Bedarf kann ich hier natürlich auch das vollständige Debug-Log posten...

Gruß,
Daniel

**Comment by 2Moon4** [comment]
Hallo,
Könntest du beschreiben, was du genau in der lidl.js Datei geändert hast? Die Anleitung ist ja leider für ein anderes Produkt und mir ist nicht klar, wie man auf die entsprechenden Strings bei DIESEM Produkt kommt: TS0505B.
Speziell meine ich den Teil des Strings: "_TZ3000_c2iwpxf1" Was trägt man da für diese smart led bar (TS0505B) ein?

> locating the following code: fingerprint: [{modelID: 'TS0502A', manufacturerName: '_TZ3000_rylaozuc'}],
> replaceing the with this code: fingerprint: [{modelID: 'TS0502A', manufacturerName: '_TZ3000_rylaozuc'},{modelID: 'TS0502A', manufacturerName: '_TZ3000_c2iwpxf1'}]

Ich bin mir ja relativ sicher, dass dieser Teil gemeint wäre, aber was ich da ergänzen soll......?
   _{
        **fingerprint: [{modelID: 'TS0505B', manufacturerName: '_TZ3210_r0xgkft5'}],**
        model: '14156506L',
        vendor: 'Lidl',
        description: 'Livarno Lux smart LED mood light',
        ...extend.light_onoff_brightness_colortemp_color({disableColorTempStartup: true, colorTempRange: [153, 500]}),
        meta: {applyRedFix: true, enhancedHue: false},
        configure: async (device, coordinatorEndpoint, logger) => {
            device.getEndpoint(1).saveClusterAttributeKeyValue('lightingColorCtrl', {colorCapabilities: 29});
        },
    },_


Viele Grüße

**Comment by danielthoene** [comment]
Hi!
Da ich nicht weiß auf welchem Stand du bist beschreibe ich mal meine Vorgehensweise...

1. Gerät pairen
2. In den Geräteinformationen den Wert von "modelZigbee" und "manufacturer" nachschauen
3. In der lidl.js den Bereich für das Gerät "Livarno Lux light bar RGB+CCT (black/white)" suchen
4. In diesen Bereich unter "fingerprint" einen Eintrag a la "{modelID: 'hier-die-modelZigbee-eintragen', manufacturerName: 'hier-manufacturer-eintragen'} ergänzen. Dabei darauf achten, dass die "eckige Klammern" alle Einträge einschließen...

Beispiel vorher:
` fingerprint: [{modelID: 'TS0505A', manufacturerName: '_TZ3000_gek6snaj'}],`

Beispiel nachher:
` fingerprint: [{modelID: 'TS0505A', manufacturerName: '_TZ3000_gek6snaj'},
            {modelID: 'TS0505B', manufacturerName: '_TZ3210_iystcadi'}],`

5. ZigBee-Adapter neu starten

Falls der ZigBee-Adapter nach der Änderung nicht startet, ist der Eintrag in der lidl.js fehlerhaft (Leerzeichen zuviel, Komma vergessen etc pp.)

Wie bereits gesagt: Bei mir funktioniert die LED-Bar nicht korrekt auf diese Art und Weise - bzw. funktioniert alles bis auf die RGB-Farben... Dabei ist mir auch aufgefallen, dass in der ursprünglichen lidl.js der fingerprint bei der LED-Bar die modelID "TS0505A" aufgeführt ist. Mein Adapter erkennt die LED-Bar aber als modelID "TS0505B"...

Viel Spaß beim Ausprobieren ;-)

Gruß,
Daniel

**Comment by xmace** [comment]
Hi, habe auch das Problem, dass die Light Bar (https://www.zigbee2mqtt.io/devices/14149505L_14149506L.html) zwar erkannt wird aber die Farbumschaltung nicht funktioniert.
Die Livarno LUX (https://www.zigbee2mqtt.io/devices/14156506L.html) wird korrekt erkannt und funktioniert top.

Kann man hier was offizielles machen? Ich denke die Lightbar wird auf Grund des guten Preises weit verbreitet sein.

Danke

**Comment by asgothian** [comment]
> Kann man hier was offizielles machen?

What do you call "something official" ? The patch above already notes why the color settings do not work as the definition given does not match the device. TS0505A and TS0505B are devices which require different state definitions.

Since this is a TuYa device, implementation will need to rely on physical access to the device.

A.

**Comment by MarkStephan89** [comment]
Habe  den HG08010 Strahler (https://www.zigbee2mqtt.io/devices/HG08010.html) dieser wird auch als TS0505B erkannt. ( #1534 )

**Comment by sebaboehm** [comment]
Ich habe auch den LED Strahler, der wird als TS0505B erkannt und ist nicht steuerbar

**Comment by asgothian** [comment]
Please install the current GitHub version - with this the device works. (At least the 2 I have)

‘A.

**Comment by asgothian** [comment]
Closing after 6 months
