### ISSUE TITLE
Extended PAN ID is reversed

### ISSUE THREAD

**Issue by JuniperChris929** [ioBroker/ioBroker.zigbee#1415]
Hi all,

I'm getting a Warning in my Zigbee Setup:
Extended PAN ID is reversed (expected=2929292929292929, actual=2929292929292929)

Is there anything wrong? This showed up all of a sudden (was working fine for the last 4 weeks) and so far does not seem to have any impact but is classified as "warn"

Just a Test-System - nothing seriously impacted

**Comment by JuniperChris929** [comment]
Glad to hear that :)
Why is it a "warn" though? Shouldn't it be "info" then?

**Comment by Grothesk242** [comment]
A 'Warning' is something that is not completely correct but does not lead to errors or malfunctions for the time being. 
Nevertheless it should be adressed, as it can become a problem in the future.

**Comment by JuniperChris929** [comment]
Just checking: Did I miss a commit or new version? This isn't "fixed" yet, and even in the BETA-Repo the adapters don't want to fetch a new version so I'm wondering how / when this was fixed / completed?
