### ISSUE TITLE
Calling toZigbee Functions with JSON Object

### ISSUE THREAD

**Issue by theimo1221** [ioBroker/ioBroker.zigbee#1417]
Hi team,

installing some Ubisys J1 I needed to use developer mode and sending multiple commands (some manufacturer specific some general) to calibrate the device within ioBroker interface.

But as there is a toZigbee Endpoint within herdsman converter this could potentially be much easier:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/677e5c95e527e7ecce6c5c259bea653d254c4b97/converters/toZigbee.js#L4206

[The configuration object definition](https://www.zigbee2mqtt.io/devices/J1.html#configuration-of-device-attributes) 

My question is, can and if so how can we call those "set-Endpoints" from within ioBroker?

Thanks and best regards 

Thiemo

**Comment by asgothian** [comment]
The key question is - are the respective functions
- declared as ‘setable’ in the device description on zigbee2mqtt.io\
- Documented at that location ?


If so, there are two option sod using that:
- you can call the SendToDevice function using sendTo with {device:’ieee’, payload:{…}} as parameter
- You can install from my repository to get access to the ‘send_payload’ state where you can place a stringified  JSON to be sent to the device.
 

A.
P.s. a pr should be coming soon to get those changes into the official github version.
