### ISSUE TITLE
Xiaomi Wireless round switch WXKG01LM not recognized

### ISSUE THREAD

**Issue by Alwiz79** [ioBroker/ioBroker.zigbee#142]
The round Mijia switch WXKG01LM is not recognised by the adapter (iobroker on raspberry).
Should it work ?
Error Message is:
Error: Cannot get the Node Descriptor of the Device: 0x

**Comment by kirovilya** [comment]
Most MiJia devices: press and hold the reset button on the device for +- 5 seconds (until the blue light starts blinking). IMPORTANT: Release and start pressing the reset button every second. This keeps the device awake, otherwise pairing will fail!.

**Comment by cwaldi2010** [comment]
I also have one question regarding Xiaomi QBKG04LM Aqara Switch.
I get the failure code,... no Converter available for QBKG04LM with key Click 

Thank you very much
