### ISSUE TITLE
"Available" Object of Aqara devices does not update.

### ISSUE THREAD

**Issue by jenbenn** [ioBroker/ioBroker.zigbee#1421]
For test purpose I have removed the battery from an Aqara water sensor, to see how fast the device is recognized as unavailable.  It appears the answer is never. 24 hours later (battery is still removed) the "available" object still displays "true". Presssing the button "device query" does not change anything.  Only the signal strength was downgraded from 140 to 10. Same goes for restarting the zigbee adapter, the device remains always available. Only the signal strength was downgraded from 140 to 10. Zigbee stick ist sonoff 2652p .Anyone knows  if this  correct behavior.? Under what  conditions will the object "available"  change to false?

**Comment by asgothian** [comment]
this is the correct behaviour. The device will be marked as not available after at least 25 hrs without a signal from the device.
I am not certain how restarts play into this - it is possible that a restart of the zigbee adapter also restarts the 25hr window.

A,

**Comment by jenbenn** [comment]
Thanks! I will wait a little longer then :)
