### ISSUE TITLE
wrong Device ID

### ISSUE THREAD

**Issue by larryxxl2** [ioBroker/ioBroker.zigbee#1424]
Zigbee v1.6.17
device is QS-Zigbee-S05-LN (⭐EXP) (QS-Zigbee-S05-LN) with neutral

wrong Device displayed in iobroker Zigbee TS0001

TS0001
type:Router
nwk:58265
manuf id:4417
manufacturer:_TZ3000_yl3zuyaw
power:Mains (single phase)
app version:66
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:true
endpoint:1
profile:260
input clusters:genScenes (5)
genGroups (4)
genOnOff (6)
manuSpecificTuya_3 (57345)
57344
genBasic (0)
output clusters:genOta (25)
genTime (10)
endpoint:242
profile:41440
output clusters:greenPower (33)

**Comment by larryxxl2** [comment]
Work well . Problem after Zigbee restart.  The Device is not accessible while only outgoing connections.

**Comment by asgothian** [comment]
Please attempt the following:
- stop the zigbee adapter
- delete the object for the device under zigbee.0 (the entire object with all states)
- update the adapter to 1.6.18

A.

**Comment by larryxxl2** [comment]
nothing changed. 1.6.18.
![IMG_20220422_194732](https://user-images.githubusercontent.com/96195330/164768677-084353f2-11ea-4b1f-8019-a3dbaf78075c.jpg)
