### ISSUE TITLE
Silvercrest Zwischenstecker HG06337 - Power LED deaktivieren

### ISSUE THREAD

**Issue by mbausm** [ioBroker/ioBroker.zigbee#1427]
Hallo,

könnt Ihr einen Datenpunkt zur Deaktivierung der Power LED der Silvercrest Steckdose im Adapter integrieren?

Ich wollte die Steckdose im Schlafzimmer einsetzen, die LED leuchtet allerdings sehr hell.
Zur Zeit habe ich diese über die Entwicklerfunktionen deaktiviert:

Endpunkt 1
Cluster-ID: genOnOff
Befehlstyp: Foundation
Attribut: tuyaBacklightMode

Es wäre komfortabler diese direkt über einen Datenpunkt deaktivieren zu können.

Viele Grüße!

**Comment by asgothian** [comment]
This needs to be done in the zigbee-herdsman-converters project. 
A separate state can only be generated if the respective function is added to the converter of the device.

A.

**Comment by mbausm** [comment]
Hallo Mark,

du öffnest die Instanz des Zigbee Adapters und öffnest den "Entwickler" Tab.

Dann wählst du dein Zigbee Gerät (Lidl Steckdose) aus

Endpunkt: 1
Cluster-ID: genOnOff
Befehlstyp: Foundation
Befehl: write (2)
Attribut: tuyaBacklightMode
Haken setzten bei "Ein Wert wird benötigt"
Value: 0

Dann denn Button "Ausführen" drücken

Im Log erscheint eine Meldung: **SUCCESS undefined**

Mit dem Befehl:

Endpunkt: 1
Cluster-ID: genOnOff
Befehlstyp: Foundation
Befehl: read (0)
Attribut: tuyaBacklightMode
Haken entfernen bei "Ein Wert wird benötigt"
Value: 0

kannst du den Status des Backlight Modus prüfen.

Bei deaktiviertem Backlight erscheint: **SUCCESS {"tuyaBacklightMode":0}**

Gruß,

Michael
