### ISSUE TITLE
Network Map freezes

### ISSUE THREAD

**Issue by theimo1221** [ioBroker/ioBroker.zigbee#1428]
Good evening,

as I have quite a few Zigbee Devices in my network the map freezes on changes of the map configuration for several seconds.

As a first step I might try to simply update our version of visjs, as it is quite some years behind the current version.

Best regards

Thiemo

**Comment by theimo1221** [comment]
Updating to the newest version the map still get´s created and changing map configuration now takes 400ms before it was 2500ms.
I wasn't able to spot any visual or functional downsides in regards to the updated library version

**Comment by arteck** [comment]
thx
