### ISSUE TITLE
Color temperature min and max values are not set for "excluded" devices

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.zigbee#1432]
Hello,

I've paired [a light](https://www.zigbee2mqtt.io/devices/1743130P7.html) to Zigbee instance which I also "excluded" so the device features are taken from the "exposes".

As you can see below the "exposes" has a `value_min=150` and `value_max=500` value for the light's `color_temp`. Those values are *not* copied to the respective ioBroker state object `zigbee.0.<some id>.colortemp`:

```json
{
  "type": "state",
  "common": {
    "name": "Color temperature",
    "type": "number",
    "read": true,
    "write": true,
    "role": "level.color.temperature"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1651241570729,
  "_id": "zigbee.0.0017880109c3ba2b.colortemp",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.agross",
    "ownerGroup": "system.group.administrator"
  }
}
```

This causes two problems for me:

* The color temperature slider on the Zigbee adapters' "Devices" tab sets values between `200` and `9000`
* The Lovelace adapter (the UI I use) uses its hard-coded default range of `153..450`

Interestingly, `color_temp_startup` does include `min` and `max` as per the exposes:

```json
{
  "type": "state",
  "common": {
    "name": "Color temperature after cold power on of this light",
    "type": "number",
    "unit": "mired",
    "read": true,
    "write": true,
    "role": "state",
    "min": 150,
    "max": 500
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1651241461220,
  "_id": "zigbee.0.0017880109c3ba2b.color_temp_startup",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.agross",
    "ownerGroup": "system.group.administrator"
  }
}
```

The "exposes" reports the following:

```json
{
    "type": "light",
    "features": [
        {
            "type": "binary",
            "name": "state",
            "property": "state",
            "access": 7,
            "value_on": "ON",
            "value_off": "OFF",
            "value_toggle": "TOGGLE",
            "description": "On/off state of this light"
        },
        {
            "type": "numeric",
            "name": "brightness",
            "property": "brightness",
            "access": 7,
            "value_min": 0,
            "value_max": 254,
            "description": "Brightness of this light"
        },
        {
            "type": "numeric",
            "name": "color_temp",
            "property": "color_temp",
            "access": 7,
            "unit": "mired",
            "value_min": 150,
            "value_max": 500,
            "description": "Color temperature of this light",
            "presets": [
                {
                    "name": "coolest",
                    "value": 150,
                    "description": "Coolest temperature supported"
                },
                {
                    "name": "cool",
                    "value": 250,
                    "description": "Cool temperature (250 mireds / 4000 Kelvin)"
                },
                {
                    "name": "neutral",
                    "value": 370,
                    "description": "Neutral temperature (370 mireds / 2700 Kelvin)"
                },
                {
                    "name": "warm",
                    "value": 454,
                    "description": "Warm temperature (454 mireds / 2200 Kelvin)"
                },
                {
                    "name": "warmest",
                    "value": 500,
                    "description": "Warmest temperature supported"
                }
            ]
        },
        {
            "type": "numeric",
            "name": "color_temp_startup",
            "property": "color_temp_startup",
            "access": 7,
            "unit": "mired",
            "value_min": 150,
            "value_max": 500,
            "description": "Color temperature after cold power on of this light",
            "presets": [
                {
                    "name": "coolest",
                    "value": 150,
                    "description": "Coolest temperature supported"
                },
                {
                    "name": "cool",
                    "value": 250,
                    "description": "Cool temperature (250 mireds / 4000 Kelvin)"
                },
                {
                    "name": "neutral",
                    "value": 370,
                    "description": "Neutral temperature (370 mireds / 2700 Kelvin)"
                },
                {
                    "name": "warm",
                    "value": 454,
                    "description": "Warm temperature (454 mireds / 2200 Kelvin)"
                },
                {
                    "name": "warmest",
                    "value": 500,
                    "description": "Warmest temperature supported"
                },
                {
                    "name": "previous",
                    "value": 65535,
                    "description": "Restore previous color_temp on cold power on"
                }
            ]
        },
        {
            "type": "composite",
            "property": "color",
            "name": "color_xy",
            "features": [
                {
                    "type": "numeric",
                    "name": "x",
                    "property": "x",
                    "access": 7
                },
                {
                    "type": "numeric",
                    "name": "y",
                    "property": "y",
                    "access": 7
                }
            ],
            "description": "Color of this light in the CIE 1931 color space (x/y)"
        },
        {
            "type": "composite",
            "property": "color",
            "name": "color_hs",
            "features": [
                {
                    "type": "numeric",
                    "name": "hue",
                    "property": "hue",
                    "access": 7
                },
                {
                    "type": "numeric",
                    "name": "saturation",
                    "property": "saturation",
                    "access": 7
                }
            ],
            "description": "Color of this light expressed as hue/saturation"
        }
    ]
}
```

**Comment by asgothian** [comment]
This is done intentionally, as the state in question does an automatic conversion between colortemp in mired (150 to 500) and Kelvin (2000 to 6500)

A.

**Comment by asgothian** [comment]
> Should this really happen if there is any automatic conversation happening? And if so, why does the 9000 value not correspond to an warm white (visually)?

9000K is cold white light. Since the value is converted from kelvin to Mired and then clamped between 150 and 500, entering 9000 will lead to a setting of 150, i.e. cold white. See: https://en.wikipedia.org/wiki/Color_temperature

**Comment by agross** [comment]
Cold light, yes.

What you describe does not work with the slider on the devices tab. I believe the automatic conversion accepts values between 150 and 500 (to be interpreted as mired) as well as 501..9000 (K) where conversation and clamping happen.

The slider for some reason has a value range of 200..9000. So you slide from cold (200 mired) to warm (in the range of 500 mired to ~3000K) and then later to cold (6000 K range). As a user, it feels like the slider is broken.

**Comment by agross** [comment]
The code that I changed in #1433 looks like`value_min` and `value_max` *should* be taken from z2m, the error is taking them from the wrong object (`expose` instead of `prop`). So it's just *by chance* undefined in most cases and won't be copied to the ioB state. This, in my humble opinion, does not communicate intent. [A couple of lines above](https://github.com/ioBroker/ioBroker.zigbee/blob/ab4f09bf97bdd8fc899e8bd01624e0ac23ff0d5f/lib/exposes.js#L255) a similar omission was made explicit with a comment (albeit one that does not explain the reasons).

**Comment by asgothian** [comment]
> The code that I changed in #1433 looks like`value_min` and `value_max` _should_ be taken from z2m, the error is taking them from the wrong object (`expose` instead of `prop`). So it's just _by chance_ undefined in most if not all cases and won't be copied to the ioB state. This, in my humble opinion, does not communicate intent. [A couple of lines above](https://github.com/ioBroker/ioBroker.zigbee/blob/ab4f09bf97bdd8fc899e8bd01624e0ac23ff0d5f/lib/exposes.js#L255) a similar omission was made explicit with a comment (albeit one that does not explain the reasons).

It is possible that whoever implemented the colortemp expose made an error when generating it. If this error had been noticed beforehand - by removing the ability to control the color temperature with kelvin values -  this would have been corrected to match the min/max values to the min/max values defined in states.js, i.e. no min and no max value. I cannot say where the slider on the device tile gets its value from.

My opinion with regards to the current behavior stands.

There may be an option to generate a better solution, but the linked PR is **not** a better solution in my eyes.

A.

**Comment by agross** [comment]
> I cannot say where the slider on the device tile gets its value from.

It is hardcoded in 770df4ae by @kirovilya. The range does not make sense to me. 

* `153..450` would be the mireds supported by my older Hue lights
* `150..500` would be the mireds supported by my newer Hue lights
* `>500..9000` could be interpreted as K to be converted (though I haven't looked at how the auto-conversion works)

**Comment by asgothian** [comment]
If the slider is what you want fixed, i would suggest an edit which changes the hard coded limits the values to 150 to 500.

A.

**Comment by agross** [comment]
> i would suggest an edit which changes the hard coded limits the values to 150 to 500

Perhaps @kirovilya can explain why he chose that range before we change things.

**Comment by kirovilya** [comment]
I don't remember where I got it from. you can change as you want
