### ISSUE TITLE
Allow use of external icons for "excluded" devices and Lovelace UI

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.zigbee#1434]
Hi @kirovilya,

I found your commit 900d3ac1511401ac6c6e9e125d4606f06cd55c25 where the use of external icons is disabled.

Some of my devices need to use the "to exclude" feature (mostly lights) and I want to control them using ioBroker.lovelace. Since the exposes feature determines the device icon from zigbee2mqtt.io I wonder why it should be later disregarded (as per the commit above).

It might be due to security concerns (external HTTP requests when using the ioBroker.admin) or because ioBroker.admin cannot handle URLs that are not relative to `./adapter/zigbee` and will show a broken image icon instead (i.e. `./adapter/zigbee/https://zigbee2mqtt.io/...`).

I suggest the following to get the best of both worlds - working icons in both ioBroker.admin and in ioBroker.lovelace for "excluded" devices without icons shipped by ioBroker.zigbee:

- Keep the "remove external images" code as-is
- If the "to exclude" feature determines an icon from zigbee2mqtt.io, download it and convert it to the `data:` scheme (base-64 encoded images)

The result will look like this:

```json
{
  "type": "device",
  "common": {
    "name": "1743130P7",
    "type": "1743130P7",
    "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="
  }
  // ...
}
```

The image above is a red dot and will look like this:

Admin:
<img width="61" alt="2022-04-29_18-26-25" src="https://user-images.githubusercontent.com/16245/165985189-e6f4a90e-7d52-4400-aa63-ace99481c87e.png">

Lovelace:

<img width="93" alt="2022-04-29_18-26-54" src="https://user-images.githubusercontent.com/16245/165985247-61e811e1-8863-4707-bf62-b1fb462978d1.png">

Of course, you would normally see the device there.

**Comment by arteck** [comment]
check https://github.com/ioBroker/ioBroker.zigbee/tarball/img Repo..

**Comment by agross** [comment]
@arteck Not sure what you mean. Since devices no longer need to be added to zhc and this repo, image are missing.

In the meantime, I fixed up my devices using a script: https://github.com/agross/iobroker-scripts/commit/b9c6636cb97e078df5dc6b8c0f856cdfe4d44977

Perhaps the adapter can do this on its own in the future, probably at pairing time.

**Comment by arteck** [comment]
the new method for your problem with the icons is in this repo.
plz del the object and restart the adapter.

**Comment by agross** [comment]
@arteck Thanks! I left some comments on your commit.

**Comment by arteck** [comment]
so it works for my and my devices .. @asgothian can you check it with yours system plz

**Comment by asgothian** [comment]
Will do - but not before Tuesday evening

**Comment by arteck** [comment]
@agross
i have bad message for you.. the core team is against .. object size is then very big.. depending on filesize in z2m project.

**Comment by agross** [comment]
I can live with that. I have my own script to download the icon once I added a new device. Close this issue as you see fit.

**Comment by asgothian** [comment]
@arteck - i am considering to increase the amount of data stored in the dev_names.json file. I could imagine to include a base64 encoded image from z2m as well as device specific configuration options. This we could automate, while offering the option of selecting user defined images per device / device type.

I am also looking into options to do an automatic resize to a specific size for another project, so the combination may be worth looking into.

A.

**Comment by arteck** [comment]
so new try.. install this branch
https://github.com/ioBroker/ioBroker.zigbee/tree/nobackups

**Comment by agross** [comment]
@arteck 

The latest adapter update set the images to be served locally, but actually downloaded no images.

```json
{
  "type": "device",
  "common": {
    "name": "Kitchen #3",
    "type": "5062331P7",
    "icon": "img/5062331P7.png",
// ...
```

I also still would argue that the images downloaded from zigbee2mqtt are *not* PNGs but JPEGs.

<img width="290" alt="2022-05-29_07-28-28" src="https://user-images.githubusercontent.com/16245/170853748-5fee030a-49ff-411a-a747-d23a1c2bcb83.png">

```bash
root@iobroker:/opt/iobroker# find iobroker-data/files/zigbee.admin/img -type  f -name 5062331P7.png
root@iobroker:/opt/iobroker#
```

**Comment by agross** [comment]
```
2022-05-29 07:32:00.831  - warn: zigbee.0 (1352) download icon from https://www.zigbee2mqtt.io/images/devices/WS-EUK04.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/WS-EUK04.png
```

Aha, the download target directory is the adapter's admin. Not the admin directory that is actually used to display stuff on the admin UI.

**Comment by arteck** [comment]
correct..

**Comment by agross** [comment]
What happens after the adapter is updated again? Do downloaded icons survive this?

**Comment by Apollon77** [comment]
> What happens after the adapter is updated again?

When they were uploded before the upload they should survive (until an iobroker restore)
