### ISSUE TITLE
Version 1.6.18 Batterie wird mit 100% angezeigt 

### ISSUE THREAD

**Issue by railin** [ioBroker/ioBroker.zigbee#1437]
Bei vorherigen Versionen realistische Angaben Prozent Batterie, jetzt alle 100%, was definitiv nicht sein kann. Könnte sein, dass es nur bei Xiaomi-Geräten der Fall ist. Ich glaube da gab es vor ein paar Versionen bezüglich dieses Fehlers schon einmal einen Beitrag von Arteck.

**Comment by arteck** [comment]
es ist so wie es ist..wir bekommen die Werte von herdsman.. da ändern wir nix dran.. und werden es auch nicht.. 
in der Vergangenheit passten die Werte auch nicht immer.. ist nur keinem aufgefallen..
