### ISSUE TITLE
Müller Licht Tint LED Stripe, color, opal white (44435) 

### ISSUE THREAD

**Issue by gehtnixx** [ioBroker/ioBroker.zigbee#1438]
Hi,
folgendes Gerät wird erkannt ist auch über Objekte (ohne Name) in vollem Umfang bedienbar,
es wird aber im Adapter als "undefined" angezeigt und ist darüber nicht bedienbar.

zigbee.0 2022-04-30 14:41:41.911	info	Device '0xb4e3f9fffeb297c5' is supported, identified as: Müller Licht Tint LED Stripe, color, opal white (44435)  zigbee.0 
2022-04-30 14:41:41.910	info	Successfully interviewed '0xb4e3f9fffeb297c5', device has succesfully been paired

Grüße

**Comment by gehtnixx** [comment]
Aktuelle 1.6.18 ist installiert

**Comment by asgothian** [comment]
Please clear the browser cache and reload the zigbee adapter page.

A.

**Comment by gehtnixx** [comment]
Hi,

done, nothing happens same problem

**Comment by asgothian** [comment]
Please show the tile of the device in the zigbee adapter (both sides). There may be a bug which only affects the internal display.

A.

**Comment by gehtnixx** [comment]
Von: asgothian ***@***.***> 
Gesendet: Mittwoch, 4. Mai 2022 10:00
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: gehtnixx ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] Müller Licht Tint LED Stripe, color, opal white (44435) (Issue #1438)

 

Please show the tile of the device in the zigbee adapter (both sides). There may be a bug which only affects the internal display.

A.

**Comment by asgothian** [comment]
???

**Comment by gehtnixx** [comment]
Sorry, i put the pictures into the mail. i try it here again....
![image](https://user-images.githubusercontent.com/104681809/166646375-34bf1cd8-2a6d-4738-84a7-6e838cbdcbf2.png)
![image](https://user-images.githubusercontent.com/104681809/166646468-4ab73f1f-17b4-41ab-97ad-794b62eb3f9b.png)

**Comment by asgothian** [comment]
This seems to be a non-device specific bug as it has been reported for other devices as well.

Closing this here - tracking will continue on #1443
