### ISSUE TITLE
Error on upgrade to 0.8.0

### ISSUE THREAD

**Issue by der-eine** [ioBroker/ioBroker.zigbee#144]
Hi, I'm trying to dangle the adapter from 0.7.7 to 0.8.0. Unfortunately, this error comes. Looks like the program does not have permission to access the folder. But have no idea what I have to do.
Can someone help me please?
Thx

[code]$ ./iobroker upgrade zigbee
Update zigbee from @0.7.7 to @0.8.0
NPM version: 6.4.1
npm install iobroker.zigbee@0.8.0 --production --save --prefix "/opt/iobroker" (System call)
npm
 WARN checkPermissions Missing write access to /opt/iobroker/node_modules/zigbee-shepherd-convertersnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.zigbee

npm ERR! path /opt/iobroker/node_modules/zigbee-shepherd-convertersnpm ERR! code EACCES

npm ERR! errno -13npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/zigbee-shepherd-converters'npm ERR!  { Error: EACCES: permission denied, access '/opt/iobroker/node_modules/zigbee-shepherd-converters'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/zigbee-shepherd-converters\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/opt/iobroker/node_modules/zigbee-shepherd-converters' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm
 ERR!
 A complete log of this run can be found in:npm
 ERR!
     /home/iobroker/.npm/_logs/2019-01-09T15_18_29_064Z-debug.log
ERROR: host.ioBroker-neu Cannot install iobroker.zigbee@0.8.0: 243
ERROR: process exited with code 25[/code]

**Comment by arteck** [comment]
'Error: EACCES: permission denied,

not a adapter problem...

**Comment by der-eine** [comment]
OK thank you for the info. do you have a solution?

**Comment by kirovilya** [comment]
try 
```
sudo su
./iobroker upgrade zigbee
```

**Comment by der-eine** [comment]
Hallo @kirovilya ,
Thank you for your feedback signal. Unfortunately I get the same error message. How can iobroker not have permission to install? It was installed with root and had no problems updating ...
Do you have any idea how it could work or if I should contact?
Thank you for your time

**Comment by kirovilya** [comment]
`sudo chmod -R 777 /opt/iobroker`

**Comment by der-eine** [comment]
Still can not install iobroker.zigbee

**Comment by kirovilya** [comment]
Is also a problem with the permission?
Update adapter from admin.
Or install from github by specifying https://github.com/ioBroker/ioBroker.zigbee
![image](https://user-images.githubusercontent.com/8360230/50973624-6aeff100-14fa-11e9-99ef-c79c3afbde78.png)

**Comment by der-eine** [comment]
Good Morning @kirovilya 
Now I completely deleted the adapter and reinstalled via Github. Now I could install 0.8.0! Thank you for your help!!

**Comment by kirovilya** [comment]
manually

**Comment by der-eine** [comment]
Ok, trank you 👍🏻
