### ISSUE TITLE
cannot install the zigbee adapter

### ISSUE THREAD

**Issue by ChrisVonFrosta** [ioBroker/ioBroker.zigbee#1441]
tried via admin page. failed.
tried via ssh, failed.
 in former times i was able to use this adapter.

What could be the reason?
![grafik](https://user-images.githubusercontent.com/16272493/166146839-6b25bc5d-71f7-4a53-9c36-7029914506bf.png)

**Comment by asgothian** [comment]
- post logs as text in code tags (<>), not screenshots.
- post more information about your system
- attempt to install from the admin and enable debug output
- post the install logs from npm.

A.

**Comment by ChrisVonFrosta** [comment]
after installing another adapter i was able to install this one.
