### ISSUE TITLE
Please implement the following device RTX ZVG1 - TS0601

### ISSUE THREAD

**Issue by yogiflop** [ioBroker/ioBroker.zigbee#1442]
Hello,

it is possible to implement the following device:
Info from zigbee2mqtt

https://www.zigbee2mqtt.io/devices/ZVG1.html

regards

**Comment by asgothian** [comment]
This device should already be supported in the current GitHub version as it is listed as supported in zigbee2mqtt.io.

A.

**Comment by yogiflop** [comment]
update done. it is in.
thanks
