### ISSUE TITLE
Device tile broken on new devices

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.zigbee#1443]
There have been a number of reports of people who attempt to pair devices which are shown in the zigbee Adapter as "undefined" with a ? icon and a malformed IEEE if the tile is flipped.

The Device(s) in question will show an iEEE in the form of `0x0xabcdef0123456789` rather than the expected `0xabcdef0123456789`. As far as i could track this, the devices work without issue when controlled from the object tree but no information / control is available from the zigbee tab / zigbee adapter configuration.

Known cases:
- issue #1438 
- ioBroker forum [Post](https://forum.iobroker.net/topic/53979/zigbee-adapter/30?_=1651555633301)
- ioBroker forum [Post](https://forum.iobroker.net/topic/54628/tardfri-led-treiber-zigbee-pairing-undefined/10?_=1651555633306)

**Comment by ScumbagSteve** [comment]
I got the same issue

**Comment by asgothian** [comment]
> I got the same issue

The same as in
- the device can be controlled using the states in the object tree and updates its states without issue
- the device shows a double 0x on the back of the device tile in the Zigbee tab / Adapter configuration

?
