### ISSUE TITLE
Bitte um Implementierung von Tuya Rauchmelder TS0601

### ISSUE THREAD

**Issue by Heini1985** [ioBroker/ioBroker.zigbee#1444]
Hallo ich habe mir bei Alixpress einen Tuya Rauchmelder gekauft und wollte ihn in Zigbee einbinden aber der Adapter kennt ihn nicht.
Ich habe folgenden Rauchmelder gekauft siehe link:

https://de.aliexpress.com/item/1005004069686574.html?spm=a2g0o.productlist.0.0.5085733fNEa41j&algo_pvid=20924028-0fda-4dd5-8edc-c46c9d1ae0f2&algo_exp_id=20924028-0fda-4dd5-8edc-c46c9d1ae0f2-17&pdp_ext_f=%7B%22sku_id%22%3A%2212000027936385855%22%7D&pdp_npi=1%40dis%7CEUR%7C%7C17.95%7C%7C%7C%7C%7C%400b0a01f816516914569738215eb0f8%7C12000027936385855%7Csea

im Adapter sieht es so aus:

![image](https://user-images.githubusercontent.com/76739980/166809645-72129970-4c0f-4f2a-aea1-29cc6b7a9536.png)

![image](https://user-images.githubusercontent.com/76739980/166809745-f1fead44-d1e8-4ba6-809a-ecfc7fe132c8.png)

![image](https://user-images.githubusercontent.com/76739980/166812224-4444f047-2e33-4e37-ac5b-55ded4aebef5.png)

Vielleicht kann mir einer von euch weiter helfen?

Danke im vorraus.

Viele Grüße

Heini1985

**Comment by asgothian** [comment]
Please check this document:
https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised

Since it is a TuYa Device, implementation will be difficult without physical access to the device.

A.

**Comment by tololi** [comment]
Hallo @Heini1985 , ich habe das Gerät ebenfalls erworben und mein IOBROKER will es nicht so richtig erkennen.
Hast Du schon eine Lösung gefunden?

**Comment by Heini1985** [comment]
> Hallo @Heini1985 , ich habe das Gerät ebenfalls erworben und mein IOBROKER will es nicht so richtig erkennen.
> 
> Hast Du schon eine Lösung gefunden?

Nein leider hatte ich noch nicht die Zeit dazu gefunden mir die Anleitung durchzuarbeiten. Wenn ich etwas neues habe dann poste ich es hier. Vielleicht hast du mehr Erfolg. 

Wir können ja parallel arbeiten.
