### ISSUE TITLE
Icons of devices "to exclude" are assigned regardless

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.zigbee#1446]
Hello, 

I added a device "to exclude", replaced its icon and restarted the adapter. After the adapter restarted, ioBroker.zigbee reassigned the icon that is included in this repo. From my understanding, the "to exclude" feature exists to prevent taking any information ioBroker.zigbee has about the device and only use information from zigbee2mqtt.

You might wonder why I tried that: The icon of Hue Ensis looks nasty in ioBroker.lovelace and I want to use a different one.

**Comment by asgothian** [comment]
Your understanding of the goal for the "exclude list" is not correct.

The exclude list changes the states of a device from those defined in the iobroker.zigbee adapter to those exposed by the zigbee-herdsman-converters. If no device icon is present in the device configuration, the system will attempt to use the icon from zigbee2mqtt.io.

As such, the described behavior is as intended.
