### ISSUE TITLE
Aqara P1 - Motion Sensor

### ISSUE THREAD

**Issue by SteveWi-291** [ioBroker/ioBroker.zigbee#1448]
Die Einbindung des Bewegungssensors funktioniert ohne große Probleme. 
Was mir aufgefallen ist: Es wird bei den Objekten kein Icon dargestellt.

Zudem kann ich das "detection_interval" nicht ändern. Also ändern des DP geht schon, hat aber keinerlei Auswirkung. "Occupancy" wird erst nach 30 sekunden von True auf False zurückgestellt.

System:
RP4 - 4GB
Node.js:          v14.19.2
JSController:   4.0.23
Admin:            5.4.9
ZigBee:            1.6.18

**Comment by arteck** [comment]
icon ist erstmal egal.. das ist so..

wenn der BWM hardwareseitig nix unter 30 unterstützt dann ist das so.. für die älteren gabs mal ein hack.. obs für den auch gibt weiss ich nicht.. aber wie gesagt wenn der BWM hardwareseitig als min 30 sec. hat dann kannst du nur werte dadrüber eingeben

**Comment by SteveWi-291** [comment]
Hallo arteck,

die neuen P1 Sensoren von Xiaomi können zwischen 1s und 200s eingestellt werden (softwareseitig), d.h es ist kein Hardware Hack notwendig. Bei den alten musste man was löten,....
