### ISSUE TITLE
iobroker backup contains older (compressed) zigbee backups

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.zigbee#1449]
When running ``iob backup`` the folder ``/opt/iobroker/iobroker-data/zigbee_0`` will be added to the backup, because of the specified ``dataFolder`` in ``io-package.json``. So far so good.

https://github.com/ioBroker/ioBroker.zigbee/blob/80c3577c049bd0c39187aebdde756a6bab647ee8/io-package.json#L218

But: The zigbee adapter also creates backups to ``/opt/iobroker/iobroker-data/zigbee_0``.

The result is, that the iobroker backup contains a lot of other compressed zigbee backups. I've extracted the latest backup and it contains the following:

```
./zigbee_0
./zigbee_0/backup_2022_04_20-12_06_31.tar.gz
./zigbee_0/backup_2022_04_18-12_12_02.tar.gz
./zigbee_0/backup_2022_05_17-15_17_34.tar.gz
./zigbee_0/backup_2022_02_25-22_16_05.tar.gz
./zigbee_0/backup_2022_05_17-15_15_58.tar.gz
./zigbee_0/backup_2022_04_20-12_04_19.tar.gz
./zigbee_0/backup_2022_02_15-14_39_22.tar.gz
./zigbee_0/backup_2022_01_10-15_46_53.tar.gz
./zigbee_0/shepherd.db
./zigbee_0/dev_names.json
./zigbee_0/backup_2022_05_17-15_09_21.tar.gz
./zigbee_0/backup_2022_04_13-15_56_02.tar.gz
./zigbee_0/nvbackup.json
./zigbee_0/backup_2022_02_18-09_22_40.tar.gz
./zigbee_0/backup_2022_04_20-12_04_56.tar.gz
./zigbee_0/backup_2022_04_20-12_02_54.tar.gz
./backup.json
./files
./files/0_userdata.0
./files/admin.0
```

I think this is not the intended behaviour?

See also https://github.com/simatec/ioBroker.backitup/issues/695

-------

Expected result:

```
./zigbee_0
./zigbee_0/shepherd.db
./zigbee_0/dev_names.json
./zigbee_0/nvbackup.json
./backup.json
./files
./files/0_userdata.0
./files/admin.0
```

**Comment by arteck** [comment]
> I think this is not the intended behaviour?

nope its correct... we have a separated backup only for our files.. only the randomized function is missed...

is on my list

**Comment by klein0r** [comment]
>  we have a separated backup only for our files.. only the randomized function is missed...

In that case it would be great if the adapter allows to disable it's own backup process.
I don't need backups inside of other backups.

**Comment by arteck** [comment]
check this branch
https://github.com/ioBroker/ioBroker.zigbee/tarball/nobackups
