### ISSUE TITLE
Please implement LIVOLO Motorized Blinds drive VL-XJ001

### ISSUE THREAD

**Issue by Stoertebek3r** [ioBroker/ioBroker.zigbee#1451]
Hi,

i have ordered the VL-XJ001 Zigbee motorized blinds drive and i cannot pair it with the adapter. Nothing happens when i try to couple it. Is it possible to add this device to the iobroker adapter? I have no HUB for this device. I have Zigbee Adapter 1.6.18.

**Comment by asgothian** [comment]
Please read [this document.](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device)

Anything outside that document will require physical access to the device.

A.
