### ISSUE TITLE
Move from zigbee2mqtt

### ISSUE THREAD

**Issue by Tyraenor** [ioBroker/ioBroker.zigbee#1452]
Hi,

is it possible to "import" all paired devices from zigbee2mqtt somehow?

I currently use zigbee2mqtt and I found no easy way to use this with ioBoker. And as I read - or maybe thought I read - this adapter is based on zigbee2mqtt, so I hope it possible to switch to this adapter without the need of pair everything again.

Thank you for your help.

**Comment by asgothian** [comment]
Depending on the coordinator you use, you can try:

- locate the shepherd.db file
- locate the nvbackup.json file
- identify the settings (PANID, ExtPanID, Channel, etc)
- install the zigbee adapter, but do not start it
- open the adapter settings and enter the settings from zigbee2mqtt.io
- copy the shepherd.db file and nvbackup.json file to /opt/iobroker/iobroker-data/zigbee_0 
- start the adapter
- check the log for error messages.

A.

**Comment by Tyraenor** [comment]
I do not have any of these files.

I have the following:
* configuration.yaml
* database.db
* secret.yaml
* state.json

Can I assume that "database.db" is "shepherd.db" and "state.json" is "nvbackup.json"?

The settings should not be an issue at all.

**Comment by asgothian** [comment]
that is worth a try. Nothing bad should happen to your zigbee2mqtt stuff if you use copies of these files.

A.

**Comment by Tyraenor** [comment]
I will try it. Thanks for your help, I will report in a bit.

**Comment by Tyraenor** [comment]
It seems to work. :)

If I want to switch back, do I need to use the files from ioBroker then? Or can I just use the files which are still in zigbee2mqtt?

**Comment by asgothian** [comment]
no idea.. not using zigbee2mqtt.io

A.

**Comment by Tyraenor** [comment]
Switching back was not a problem at all.

I get a lot undefined entries in the device area of the adapter, saying these devices are not connected, but in fact if I trigger them the objects in ioBroker are getting updated.

Do you see a way the get this straight without repairing them?

**Comment by asgothian** [comment]
check the back of the tile to see if the ieee is listed as 0x..... or 0x0x...

there is a bug i am trying to catch which sends illegal information to the admin interface

**Comment by Tyraenor** [comment]
The devices worked after a reinstall until some stopped working partially for no reason.

After several tries to get them to work again, I stopped to try to give ioBroker a chance. I will return to Node-RED and Homebridge with zigbee2mqtt...

But thank you very much for your help!

It was highly appreciated.
