### ISSUE TITLE
Berechnung Battery falsch

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.zigbee#1454]
Version 1.16.18 und heute Morgen nach Hinweis nochmals von Github aktualisiert.

![image](https://user-images.githubusercontent.com/35106961/169767094-f32815f3-a93c-4463-8599-d0900c34f8d8.png)
![image](https://user-images.githubusercontent.com/35106961/169767211-3244fcff-b0b8-411e-ba4d-96676b001f7c.png)
![image](https://user-images.githubusercontent.com/35106961/169767243-55b77f3f-788c-49d7-a052-ab27702c68e3.png)
![image](https://user-images.githubusercontent.com/35106961/169767295-3a6e4de4-5c48-4841-a530-9e0447e4f02a.png)

Es sind aber auch andere Xiaomi Geräte betroffen.

**Comment by arteck** [comment]
nochmal WIR BERECHNEN NIX..ergo wenn dann musst du den issue auf herdsman seite erstellen 

https://github.com/Koenkk/zigbee-herdsman-converters/

**Comment by asgothian** [comment]
Es hat mehrere Diskussionen darüber gegeben welche Umrechnung für die Xiaomi Geräte "korrekt" ist. Da die Umrechnung nicht durch den Zigbee Adapter vorgenommen wird werden wir an dieser Stelle nicht eingreifen und die Berechnung seitens der Zigbee-Herdsman-Converters übernehmen.

Siehe auch:

https://github.com/Koenkk/zigbee-herdsman-converters/commit/67fb2d191d0a4683026635373ccd31192533c9bc
https://github.com/Koenkk/zigbee2mqtt/issues/8499
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3921
