### ISSUE TITLE
pairing problems Ikea TRADFRI schalter

### ISSUE THREAD

**Issue by rmp63526** [ioBroker/ioBroker.zigbee#1459]
Hallo, leider lässt sich der kleine Ikea Schalter nicht koppeln.
Es steht zwar im Zigbee Log,
Interview started: 0x94deb8fffe6e26e0
Device '0x94deb8fffe6e26e0' announced itself
Interview successful: {"friendly_name":"0x94deb8fffe6e26e0","model":"E1743","vendor":"IKEA","description":"TRADFRI ON/OFF switch","supported":true}

aber er legt mir das Gerät nicht ordnungsgemäß an.
In der Geräteübersicht steht nur: ? undefined

Adapter und CC1352P1 Board habe ich neu gestartet.

Folgendes habe ich bei mir installiert.
-CC1352P1 Board
-Zigbee version 1.6.18
-Node.js: v12.22.12

**Comment by arteck** [comment]
upadate auf 1.7.2 bitte. 

>aber er legt mir das Gerät nicht ordnungsgemäß an.

was heisst das

**Comment by tony63526** [comment]
Das update teste ich später und berichte nochmal.
Bin gerade arbeiten.

Mit "nicht ordnungsgemäß anlegen" meine ich dass er zwar das Gerät in die Liste hinzufügt, aber man sieht nur ein großes Fragezeichen. 


Ein beispiel Bild: 
![1578947837449-ikea_led1736g9](https://user-images.githubusercontent.com/61117869/170952307-620b6f55-85ce-446d-8223-05f63fe59243.jpg)

**Comment by rmp63526** [comment]
Jetzt wird es richtig interessant.
Zigbee hat mir ein Update 1.7.4 angezeigt, das habe ich natürlich installiert.

Zigbee startet immer neu (Loop) und bricht immer wieder ab.
Im Host steht "Eine Adapterinstanz stürzt beim Start häufig ab und wurde aus diesem Grund gestoppt".

Habe das Board mal abgeklemmt und wieder angesteckt & das System neu gestartet. Leider kein Erfolg. 
Bin dann mal auf die Version 1.7.2, da hab ich das gleiche Problem.

Hab jetzt die 1.6.18 Version wieder installiert, die ich vorher die ganze Zeit installiert hatte und der Adapter laüft wieder stabil.
Hab den Tradfri Schalter unter den Objekten gesucht und auch gefunden, dort zeigt er auch ein Fragezeichen.
Aber wenn ich den Schalter betätige aktualisiert er den Wert von true auf false, also scheint zu funktionieren.

Weis jetzt leider nicht wie ich Zigbee aktualisieren kann ohne das es abstürzt.

![Unbenannt](https://user-images.githubusercontent.com/65367883/171037254-51750508-cb7f-4ad8-b896-48f8d64fa2ac.PNG)

![Zigbee](https://user-images.githubusercontent.com/65367883/171037264-e29b3d25-567d-42b5-98ef-253838adf7ff.PNG)

**Comment by arteck** [comment]
@rmp63526 check new version

**Comment by arteck** [comment]
zeig mal das RAW object

**Comment by rmp63526** [comment]
ehmmm meinst du dass?


{
  "common": {
    "color": null,
    "type": "E1743",
    "icon": "img/ikea_on-off-switch.png",
    "statusStates": {
      "onlineId": "zigbee.0.94deb8fffe6e26e0.available"
    }
  },
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1654103753195,
  "_id": "zigbee.0.94deb8fffe6e26e0",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by rmp63526** [comment]
Top....hat geklappt! 
Vielen dank.
Muss ich das bei jedem Schalter machen oder kommt es mit dem neuen update

**Comment by arteck** [comment]
es war nur ein alter fehler
