### ISSUE TITLE
Bitte um Implementierung von Tuya Temperatur und Feuchtemelder TS0601

### ISSUE THREAD

**Issue by poppelehegau** [ioBroker/ioBroker.zigbee#1462]
Hallo ich habe mir bei Alixpress einen Tuya Temperatur und Feuchtemelder gekauft und wollte ihn in Zigbee einbinden aber der Adapter kennt ihn nicht.
Ich habe folgenden Sensor gekauft siehe link:

https://de.aliexpress.com/item/1005003634353180.html?spm=a2g0o.order_list.0.0.4dd55c5faF2sBz&gatewayAdapt=glo2deu
![image](https://user-images.githubusercontent.com/106538074/171003437-20d6ab9f-2f8a-4934-86f8-8717204ecfd6.png)

 
Vielleicht kann mir einer von euch weiter helfen?
Danke im voraus.
Viele Grüße

**Comment by arteck** [comment]
new devices see here 
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
