### ISSUE TITLE
Bei dunklen ioBroker Theme "Triggers an effect on the light (e.g. make light blink for a few seconds)" nicht lesbar.

### ISSUE THREAD

**Issue by Snatch2001** [ioBroker/ioBroker.zigbee#1466]
Wenn man ein dunkles ioBroker Theme hat, dann ist bei Geräten, welche z.B. das Effekte DropDown haben, die Schrift nicht lesbar, da das Dropdown weis und die Schrift hellgrau ist.
![1](https://user-images.githubusercontent.com/1833577/171802986-45e82197-7dd8-4728-8e21-5622055fe86f.png)

**Comment by arteck** [comment]
na wenn man keine anderen probleme hat :-)

**Comment by Snatch2001** [comment]
Soll man Fehler melden die einem Auffallen oder nicht? Ich habe nichts von "Problem" geschrieben. Wollte helfen! Aber gut, scheint nicht erwünscht zu sein.
