### ISSUE TITLE
Philips Hue White & Color - No Symbol / No Icon 

### ISSUE THREAD

**Issue by gregx77** [ioBroker/ioBroker.zigbee#1467]
I have two Philips Hue Lamps, they are found by zigbee connecter, but seem to be not supported. They are shown with the question mark "?". Technical pairing data is provided, see attachment. 
Can you help? 
Models are:
1) Hue White & Color Ambiance Surimu square rectangle
2) Hue White and Color Ambiance Surimu rectangle pane
[Philips Hue.txt](https://github.com/ioBroker/ioBroker.zigbee/files/8842531/Philips.Hue.txt)

**Comment by arteck** [comment]
can you find the lams here 

https://www.zigbee2mqtt.io/supported-devices/
