### ISSUE TITLE
Anpassung des Textes (Timer in Einstellungen) für bessere Verständlichkeit

### ISSUE THREAD

**Issue by Maschine20** [ioBroker/ioBroker.zigbee#1468]
Hallo,

unter den Einstellungen des Zigbee Adapters gibt es einen Timer. Darüber steht "Timer zwischen 0 und 255 Sek".

![image](https://user-images.githubusercontent.com/89000090/172442686-95b6e843-fe9a-4f7c-bdbb-d329c4d3a9ae.png)

Folgender Text wäre besser zu verstehen. "Countdown zwischen 0 und 255 Sek während der Kopplung neuer Zigbeekomponenten mit dem Koordinator".

Grüße M20

**Comment by arteck** [comment]
na klar
