### ISSUE TITLE
Philips Hue Lily 1741530P7 - Brightness does not change the state

### ISSUE THREAD

**Issue by Sascha79** [ioBroker/ioBroker.zigbee#1471]
Hello,

when changing the "brightness" value, whether via the corresponding object or directly in the surface of the Zigbee adapter, the [Philips Hue Lily](https://www.zigbee2mqtt.io/devices/1741530P7.html) is switched on. This is ok. However, the value of the "state" object does not change to "true".
The same behaviour occurs when the Hue Lily is switched on via a group. The "state" of the group changes, but the "state" of the individual lamps does not.

The [Philips Hue LightStrip plus 915005106701](https://www.zigbee2mqtt.io/devices/915005106701.html) behaves differently. Here, when the "brightness" is changed, the strip is switched on and the "state" is automatically changed to "true".

Due to the behaviour of the adapter with the Hue Lily, one has no control over the actual switching state of the lamp.

Would it be possible to adjust the switch-on behaviour of the Hue Lily to the behaviour of the strip?

**Comment by asgothian** [comment]
For the brightness, this may be fixed. For the group, this cannot be fixed, as it is caused by the hue device not reporting the changed state back to the adapter.

A.
