### ISSUE TITLE
Pairing devices always uses the Router near to it

### ISSUE THREAD

**Issue by aortmannm** [ioBroker/ioBroker.zigbee#1473]
Is it intionally that when I pair a new device it always connects to the nearest Router?

I thought I can decide which Coordinater/Router I use for pairing and the device uses this.

Because I always want to use the coordinator and just if the quality is not good enough I want to pair to a Router.

Now when I change a Router all the devices that are connected are not working anymore.

![image](https://user-images.githubusercontent.com/3414298/173240400-93968af3-748b-4c78-bb66-6d03ed2b82f3.png)

**Comment by asgothian** [comment]
It is part of the design of the zigbee network that you can **not** control the network setup. The devices choose the best means to route the signal. The zigbee network does not like it when routers are randomly disconnected.

A.
