### ISSUE TITLE
Lidl HG08164 not supported

### ISSUE THREAD

**Issue by spottich** [ioBroker/ioBroker.zigbee#1476]
Hello, is it possible to integrate the following button?

https://www.zigbee2mqtt.io/devices/HG08164.html

THX for your work

help for other with an shopping spree this week @ lidl 
https://forum.iobroker.net/topic/54405/gel%C3%B6st-zigbee-lidl-smart-button/27

**Comment by asgothian** [comment]
Which adapter version did you test the support with ?

A.

**Comment by Tobi-BPi** [comment]
Hello. 
Can I help you in this case? 
I also have this button switch, and I can see the device in the overview, but I can not get this work. 
Tobi

**Comment by Tobi-BPi** [comment]
Thx, I will try if I got enough time

Tobi
