### ISSUE TITLE
Device name in log file

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1477]
Hi .. would it not be useful to have the device name here too?

DeviceAvailability:Stopping to ping 0x84182600000d314b Plug 01 after 4 ping attempts

**Comment by asgothian** [comment]
Which device name are you referring to ?

**Comment by daniel-lo** [comment]
![grafik](https://user-images.githubusercontent.com/4311558/175779071-abe397c4-4413-4880-8ecb-31e55d734b5d.png)

**Comment by Pendora2017** [comment]
upvote
