### ISSUE TITLE
zigbee UI

### ISSUE THREAD

**Issue by dp20eic** [ioBroker/ioBroker.zigbee#1479]
Hi,

My entire system is up to date, I am on the Beta Repo.

I am not sure when the user interface has been broken. I think that it came with the IoBroker.admin > 5 or 6?
I used different browsers with the same result.

The non -modal windows are large, but the content is cut off.
Example:
![Unbenannt 1](https://user-images.githubusercontent.com/71387331/175524252-6b80ae6b-01f1-417f-8822-bda9326efe2a.png)
![image](https://user-images.githubusercontent.com/71387331/175524540-f7a96d9c-ef15-4711-a441-15efbd28ab04.png)

Or the dialog to select the group(s):
![image](https://user-images.githubusercontent.com/71387331/175525027-addefd0d-b28b-46b6-9694-0ae715136bdf.png)

with kind regards
Bernd

**Comment by arteck** [comment]
check new version

**Comment by dp20eic** [comment]
Moin,

I install the latest version from GIT
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/71387331/9dfa1f66-1b93-421f-bc20-28783babcf1d)

The first line is as before, the second looks good

VG

**Comment by arteck** [comment]
next try

**Comment by dp20eic** [comment]
> next try

Moin,

die Konfiguration der Gruppe sieht aktuell so aus:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/71387331/04ae9606-62bc-4cb8-af40-88cedfbc5542)

Die Konfiguration eines Gerätes
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/71387331/b850f318-e38c-4928-aec4-f6dcedcf74bc)

Aktuell habe ich per Katze -> Benutzerdefiniert -> URL den Adapter aktualisiert, ca. 25 Minuten her
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/71387331/e444d90f-a760-4d43-adb1-a82c04382bdb)

VG
