### ISSUE TITLE
QS-Zigbee-D02-TRIAC-LN -- Model TS110E -- Manufacturer Name _TZ3210_ngqk6jia - brightness fixed on zigbee2mqtt - please fix also

### ISSUE THREAD

**Issue by Elluminatus** [ioBroker/ioBroker.zigbee#1484]
Hi,

I´ve noticed that at zigbee2mqtt there is a fix for the RTX QS-Zigbee-D02-TRIAC-LN -- Model TS110E -- also available under Lonsonho QS-Zigbee-D02-TRIAC-LN -- Model TS110E --  (Dimmer Module 1 Gang with neutral). The brightness is not setable. So it would be great if you can fix it both also in the zigbee adapter.

The issue number in zigbee2mqtt was #11853 here is the link: https://github.com/Koenkk/zigbee2mqtt/issues/11853

Here is the zip File: [QS-Zigbee-D002-TRIAC-L.zip](https://github.com/Koenkk/zigbee2mqtt/files/8544229/QS-Zigbee-D002-TRIAC-L.zip)

And here is the text of the [converter](https://github.com/Koenkk/zigbee2mqtt/issues/11853#issuecomment-1106803448)

Thank you very much. 
Greetings Elluminatus

**Comment by arteck** [comment]
if it fixed in converter..we use also this function..
