### ISSUE TITLE
Future request: firmware update of the devices individually for each device

### ISSUE THREAD

**Issue by dp20eic** [ioBroker/ioBroker.zigbee#1485]
**Current:** There is a central option to query all devices to new firmware, with a larger network, some devices lead to the query during the query and with some devices there is not the function to renew the firmware.

**Desire:** In addition to the central query for new firmware, a query for every device where the possibility of renewing the firmware is available.

With kind regards
Bernd

**Comment by Wannseesprinter** [comment]
Dieses Feature ist extrem nützlich! Bin mit rund >50 Devices unterwegs und irgendwann macht der Adapter (oder ein Teil davon) bei der Suche nach FW Updates einfach die Grätsche ;) 

![1667402527037-7f071e96-dff1-468f-8113-914f24e0245e-grafik](https://user-images.githubusercontent.com/101293779/199605887-568ceac2-3f3c-4d3e-9d7a-c73c5a203a53.png)

**Comment by arteck** [comment]
check plz the GIT version..

**Comment by thohoj** [comment]
Is it actually possible to find out whether a new feature (e.g. this one...) is now included in the current release? How?

I'm currently trying to query individual devices and can't find out how to do this. Querying all of them and then only updating individual ones works. However, some devices do not respond to "query all", and it is always different devices that respond in this way. In a large network, it takes quite a long time to get through this.  

ConbeeII, current firmware.
Devices: Hue GU10 White Ambience
zigbee adapter v1.8.24
