### ISSUE TITLE
Aqara curtain motor ZNCLDJ11LM resets position to 255 after any movement

### ISSUE THREAD

**Issue by Dmitrii-1969** [ioBroker/ioBroker.zigbee#1489]
Hi all!
I have the same ZNCLDJ11LM motor for curtains. After any movement position resets to 255%, and it works endlessly while he gives the Stop command.
ZNCLDJ11LM firmware: 01-25-2022 (I tried to roll back to the previous one and dropped it to red LED)
Completely reinstalled Zigbee2MQTT + Broker MQTT, I tried with another of the same engine - the situation does not change.
**State:**
_{
    "device_temperature": 34,
    "last_seen": "2022-07-04T11:56:01.403Z",
    "linkquality": 80,
    "motor_state": "stopped",
    "options": {
        "hand_open": true,
        "reverse_direction": false
    },
    "position": 255,
    "power_outage_count": 59,
    "running": false,
    "state": "OFF"
}_

**command sequence with topic zigbee2mqtt/curtain/set:**
    _{ "options": { "reset_limits": true } }_
sets the Position value to 0%, but after any commander drive the engine in motion the Position is again resets a non -correct value of 255%

Home Assistant Core: 2022.6.7
Home Assistant Supervisor: 2022.05.3 
Zigbee2MQTT version: 1.26.0-1 
Broker MQTT: 6.1.2
Coordinator zigbee: SONOFF Zigbee 3.0 USB Dongle Plus; firmware 20211217.

**Comment by arteck** [comment]
check new version ?
