### ISSUE TITLE
Networkmap not updating

### ISSUE THREAD

**Issue by cimba007** [ioBroker/ioBroker.zigbee#149]
My network map does only show new devices and does not refresh the connections for older devices.
It looks this way now for like 1-2 weeks. The WallSwitch was added today.

I am on 0.8.0 - is there an easy way to update to the latest dev-branch?

![image](https://user-images.githubusercontent.com/3453121/51203701-fe159600-1901-11e9-8caa-6644252963bb.png)

PS: I already uninstalled the instace and even reinstalled zigbee adapter all together.

**Comment by arteck** [comment]
look forum

**Comment by cimba007** [comment]
Can you provide a Link?

**Comment by modmax** [comment]
https://forum.iobroker.net/viewtopic.php?f=36&t=21515
But it's in german ...
