### ISSUE TITLE
MCCGQ11LM - temperature missing

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.zigbee#1491]
Good day,

I noticed that I am missing the temperature value for the door and window sensors.
When I exclude this device type in the adapter it is displayed as "device_temperature".

Could you please correct this in the adapter?

There is also a forum post about this:

https://forum.iobroker.net/topic/56053/zigbee-magnetsensor-temperatur/19?_=1657091404658

![image](https://user-images.githubusercontent.com/8565847/177491146-bd652636-d222-4a07-aa62-5f1de60a52d9.png)
![image](https://user-images.githubusercontent.com/8565847/177491218-248204b5-790b-42ef-9c0e-ca018195a6f1.png)
![image](https://user-images.githubusercontent.com/8565847/177491362-ba90858e-10ca-41e9-87bd-8e0c6f04b9d5.png)
![image](https://user-images.githubusercontent.com/8565847/177491287-82fbb344-05a8-491b-9c6c-018cca66c812.png)

**Comment by arteck** [comment]
use exlude tab

**Comment by n3roGit** [comment]
Why should I do that? This is a bug that should be fixed!
If I use Exclude, the datapoint is also displayed incorrectly. I don't have the DP "temperature" with the corresponding type. In addition, I get then data like the volt number also RAW without ".".

**Comment by n3roGit** [comment]
@arteck please reopen it.

**Comment by arteck** [comment]
the exlude tab use exposes directly from converter. 
i see no bug here ??

**Comment by n3roGit** [comment]
Yes that is correct.  But then the data points are not correctly defined as with the other aqara sensors.  I just want to have everything the same so that I can work with it automatically.  It's definitely a quick fix
