### ISSUE TITLE
Woox R7060 - no battery

### ISSUE THREAD

**Issue by skvarel** [ioBroker/ioBroker.zigbee#1497]
I'm missing the value of the battery on the **Woox R7060**

Adapterversion:  1.7.6

![image](https://user-images.githubusercontent.com/1114419/180971949-b2611a40-cc83-467d-8b1d-1ffd6c689976.png)

![image](https://user-images.githubusercontent.com/1114419/180972796-ba4f7113-ef91-42b3-a4dc-b97d8bfc2399.png)

**Comment by asgothian** [comment]
Please enter the IEEE of the device (50325fffe3623e3) into the state 'zigbee.0.info.debugmessages' and run the device for 1 day, taking heed of all 'warn' messages with the keyword 'ELEVATED' in the log.

Check if any of these messages contain any battery related information.

A.

**Comment by skvarel** [comment]
@asgothian 

Irgendwas mache ich etwas falsch. Es kommt nichts im Log zu dem Device.

**Comment by asgothian** [comment]
Bitte poste mal was du im state `zigbee.0.Info.debugmessages` Drin stehen hast

**Comment by skvarel** [comment]
> Bitte poste mal was du im state `zigbee.0.Info.debugmessages` Drin stehen hast

Ahhh, mein Fehler!

Ich hatte die ID aus Deiner Antwort kopiert, da fehlt aber ein Buchstabe!

50325ffffe3623e3 (mit vier 'f')

Ich setzte jetzt die richtige ID ein und melde mich dann wieder.

![image](https://user-images.githubusercontent.com/1114419/182279472-2c16276a-0332-4b2f-8567-219e2a79c600.png)

**Comment by skvarel** [comment]
![image](https://user-images.githubusercontent.com/1114419/182279738-2cfa1af4-3e8b-4ff2-a1ed-aa9e786ce8fd.png)

**Comment by skvarel** [comment]
Beim Neustart des Adapters:

![image](https://user-images.githubusercontent.com/1114419/182291520-814c4d08-a323-4c3b-a1b2-9c118af5394d.png)

**Comment by skvarel** [comment]
![image](https://user-images.githubusercontent.com/1114419/182680184-39c6a93c-d044-4450-8ce9-d6519ee15a3a.png)

**Comment by arteck** [comment]
da scheint irgendwas nicht zu passen
ich hab zwar den Datenpunkt wurde aber vor 6 Monaten zuletzt aktualisiert
![grafik](https://user-images.githubusercontent.com/6681528/183706267-89e7bcfb-8bb0-486b-b9fd-5d2e7afd2975.png)

**Comment by skvarel** [comment]
Bei kommt nichts. Es bleibt bei 'NULL'

**Comment by arteck** [comment]
works in GIT version

**Comment by skvarel** [comment]
> works in GIT version

Great !! Thanks !!

![image](https://user-images.githubusercontent.com/1114419/188094726-2bf9644d-31cb-408b-b868-ea7a333f6440.png)

**Comment by alexanderwerbungen** [comment]
> works in GIT version

Ich habe die aktuelle Version (v1.7.6) installiert, jedoch zeigt es mir kein Batterie Symbol an.
Was fehlt mir da noch?

**Comment by arteck** [comment]
> > works in GIT version
> 
> Ich habe die aktuelle Version (v1.7.6) installiert, jedoch zeigt es mir kein Batterie Symbol an. Was fehlt mir da noch?

wann installiert ??? mach bitte JETZT

**Comment by alexanderwerbungen** [comment]
> > > works in GIT version
> > 
> > 
> > Ich habe die aktuelle Version (v1.7.6) installiert, jedoch zeigt es mir kein Batterie Symbol an. Was fehlt mir da noch?
> 
> wann installiert ??? mach bitte JETZT

Vor 2 Wochen.
Habs jetzt nochmal installiert, funktioniert! Herzlichen Dank.
