### ISSUE TITLE
Woox R7060 - On/off state of the switch unreliable

### ISSUE THREAD

**Issue by HansBorjes** [ioBroker/ioBroker.zigbee#1498]
After pairing the device works as expected for a while.

However, after some days it becomes unresponsive. Even the worst happens: switching on succeeds, switching off fails. Very critical when not at home!

First workaround was to re-pair the device. But this doesn't work for long.

Better workaround seems to be to press the "trigger device query" button. Now, the device reacts to being switched on. Unfortunately, 20 minutes later it is stale again and refuses to being switched off.

But pressing the query button as a workaround seems to work here as well.

I have incorporated this into my script and will see whether it does the trick for now.

Could this be solved on driver level?

**Comment by asgothian** [comment]
Please check the log for messages when the device does not switch. Note that you need to perform this test without your workaround being active to see what the response from the device is.

A.

**Comment by HansBorjes** [comment]
There is no log entry in my ioBroker installation on "debug" level related to Woox switching.

**Comment by asgothian** [comment]
so the device accepts the command to switch off but ignores it ?

**Comment by HansBorjes** [comment]
No matter whether switching on or off, the valve frequently remains in its current state. In ioBroker it appears as if the state change was successful.

**Comment by asgothian** [comment]
does the device confirm the state change (i.e. does the value turn green in admin) ?

**Comment by HansBorjes** [comment]
Yes, without the workaround the state becomes green in admin.Objects panel although the device doesn't react.

**Comment by asgothian** [comment]
This is an error in the device Firmware then. If the device confirms receipt of the message it should switch. I do not see how this can be fixed in the adapter.

A.

**Comment by HansBorjes** [comment]
Now it becomes interesting. I have spent some time on my workaround.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1429215/182811193-a3a28a00-cee5-403f-a25c-93faeb09ac56.png">

What happens is this (shows my attempt to switch irrigation OFF).

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1429215/182811363-3cbd4ee2-c4b7-415c-9c1b-b925aafd8aec.png">

Looks to me like a SW failure either in the device itself or the driver. Does anyone have the same behaviour?

**Comment by rewegit** [comment]
I have only been using the device for 3 days. So far it has switched without problems.
However, the states battery and voltage are not operated.
The link_quality is  approx. 140 
If I also have dropouts I will inform you about it.

**Comment by fornax76-git** [comment]
I noticed the same behaviour here.
You can set true/false but the device doesn't react.
I also use the device trigger in my script and set to true after 10 seconds.

I bought a new device, because I thought it is a hardware failure.
After pairing the new device I received a log message.
![Screenshot 2022-07-11 112002](https://user-images.githubusercontent.com/88478863/183286709-5d20dc94-9050-4369-861a-2e0f8833c110.png)

**Comment by asgothian** [comment]
> 

Welcome to the Madness which is TuYa. Seems that the firmware of the device has been updated to use previously unknown data codes, i.e. the code 106 and 107.

- Can you link these messages to any specific actions of the device ? 
- Does the data sent change if the device has a different status ?

A.

**Comment by fornax76-git** [comment]
> > 
> 
> Welcome to the Madness which is TuYa. Seems that the firmware of the device has been updated to use previously unknown data codes, i.e. the code 106 and 107.
> 
> * Can you link these messages to any specific actions of the device ?
> * Does the data sent change if the device has a different status ?
> 
> A.

Unfortunately, I only got this message after pairing the device.
I can not see any changes.
Probably this data is linked to the battery status or the battery voltage.
I don't think that there is more data, because it is a pretty "stupid" device.

Can I do something to support you with necessary data?

**Comment by asgothian** [comment]
You will need to watch the log for additional messages with that content. The value sent seems to be 0 in either case, so there is no meaningful content sent. If you can match messages to specific events, something can be done.

A.

**Comment by arteck** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/12163

**Comment by arteck** [comment]
check new GIT version plz for battery state
