### ISSUE TITLE
This object will not be created in future versions. Please report this to the developer.

### ISSUE THREAD

**Issue by Flux3PO** [ioBroker/ioBroker.zigbee#1499]
```
<!--StartFragment-->

zigbee.0 | 2022-07-30 19:36:57.157 | info | DeviceConfigure successful 0x9035eafffed51bc1 TRADFRIbulbE14WScandleopal470lm
-- | -- | -- | --
zigbee.0 | 2022-07-30 19:36:57.038 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-07-30 19:36:57.037 | warn | Object  zigbee.0.9035eafffed51bc1.power_on_behavior is invalid:  obj.common.states has an invalid type! Expected "object", received  "string"
zigbee.0 | 2022-07-30 19:36:57.023 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-07-30 19:36:57.022 | warn | Object zigbee.0.9035eafffed51bc1.effect is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-07-30 19:36:57.015 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-07-30 19:36:57.015 | warn | Object  9035eafffed51bc1.power_on_behavior is invalid: obj.common.states has an  invalid type! Expected "object", received "string"
zigbee.0 | 2022-07-30 19:36:57.015 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2022-07-30 19:36:57.014 | warn | Object 9035eafffed51bc1.effect is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2022-07-30 19:36:56.962 | warn | download  icon from https://www.zigbee2mqtt.io/images/devices/LED1949C5.jpg saved  into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/LED1949C5.png
zigbee.0 | 2022-07-30 19:36:56.946 | info | Configuring 0x9035eafffed51bc1 TRADFRIbulbE14WScandleopal470lm
zigbee.0 | 2022-07-30 19:36:56.942 | info | Device  '0x9035eafffed51bc1' is supported, identified as: IKEA TRADFRI LED bulb  E12/E14 450/470 lumen, wireless dimmable white spectrum/chandelier opal  white (LED1949C5)
zigbee.0 | 2022-07-30 19:36:56.941 | info | Successfully interviewed '0x9035eafffed51bc1', device has succesfully been paired
zigbee.0 | 2022-07-30 19:36:55.669 | info | Starting interview of '0x9035eafffed51bc1'
zigbee.0 | 2022-07-30 19:36:39.643 | info | Zigbee: allowing new devices to join.

<!--EndFragment-->
</body>
</html>

```

The Image is not shown as the error above has reported:
![grafik](https://user-images.githubusercontent.com/11157007/181946093-21d075d6-8ae0-449f-abf0-c5d215fa72a7.png)

Is there anything else I can do top help ?

mod edit: code tags around error messages

**Comment by asgothian** [comment]
Please post the expert view of the objects listed in the error message.

A.

**Comment by Flux3PO** [comment]
Hi, thanks for taking a look at this, will do if you tell me how I do this. Sorry I'm a noob

**Comment by asgothian** [comment]
Click here to open the data (the little pen icon to the right near the tooltip)

![Screen Shot 2022-08-01 at 22 48 34 ](https://user-images.githubusercontent.com/45667167/182244147-26c61777-a4f4-440e-9aa2-eee122097ca0.png)

copy the text from this window and paste it.

Please ensure to put it in code tags (<>)

![Screen Shot 2022-08-01 at 22 49 12 ](https://user-images.githubusercontent.com/45667167/182244234-a8513b00-30bb-48f5-a8d8-0e1338b17063.png)

**Comment by Flux3PO** [comment]
`{
  "type": "state",
  "common": {
    "name": "Message from Zigbee",
    "type": "string",
    "read": true,
    "write": false,
    "role": "state"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1659202617018,
  "_id": "zigbee.0.9035eafffed51bc1.msg_from_zigbee",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Let me know if you need anything else ?

**Comment by asgothian** [comment]
Please read what I wrote. I need the information from the states listed in your log file, not the sample state I posted.

**Comment by Flux3PO** [comment]
> Please read what I wrote. I need the information from the states listed in your log file, not the sample state I posted.

Sorry misunderstood this. here you go:

effect:

`{
  "type": "state",
  "common": {
    "name": "Triggers an effect on the light (e.g. make light blink for a few seconds)",
    "type": "string",
    "states": "blink:blink;breathe:breathe;okay:okay;channel_change:channel_change;finish_effect:finish_effect;stop_effect:stop_effect",
    "read": true,
    "write": true,
    "role": "state"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1659202617022,
  "_id": "zigbee.0.9035eafffed51bc1.effect",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

power_on_behavior:

`{
  "type": "state",
  "common": {
    "name": "Controls the behavior when the device is powered on",
    "type": "string",
    "states": "off:off;previous:previous;on:on",
    "read": true,
    "write": true,
    "role": "state"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1659202617037,
  "_id": "zigbee.0.9035eafffed51bc1.power_on_behavior",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Are you looking into the picture issue too or is there anything I can do to fix this ?

**Comment by asgothian** [comment]
Thank you. I will review the information. As it looks now, there is no issue for you using the devices so you can safely ignore the warnings for now.

**Comment by Flux3PO** [comment]
> Thank you. I will review the information. As it looks now, there is no issue for you using the devices so you can safely ignore the warnings for now.

Thanks and what about the icon ?

**Comment by arteck** [comment]
> 

adapter version ??

**Comment by Flux3PO** [comment]
> > Thanks and what about the icon ?
> 
> sry but.. RTFM https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update
You are correct, I should have read it.
Thanks you very much !
