### ISSUE TITLE
communication problems

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#15]
after update to ver 0.6 and raspi restart i have communications problem to many devices
first..its ok
```

zigbee.0 | 2018-07-08 22:00:55.717 | info | (0x0017880102f054a7): TODO - Philips Hue white GU10 (Router)
-- | -- | -- | --
zigbee.0 | 2018-07-08 22:00:55.716 | info | (0x84182600000b911f): AB32840 - OSRAM LIGHTIFY LED Classic B40 tunable white (Router)
zigbee.0 | 2018-07-08 22:00:55.716 | info | (0x00158d0001052cc5): WXKG01LM - Xiaomi MiJia wireless switch (EndDevice)
zigbee.0 | 2018-07-08 22:00:55.716 | info | (0x00158d0001573a56): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
zigbee.0 | 2018-07-08 22:00:55.715 | info | (0x84182600000e4d12): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2018-07-08 22:00:55.715 | info | (0x00158d0001de760b): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2018-07-08 22:00:55.714 | info | (0x0017880102e251de): unkown - undefined unknown (EndDevice)
zigbee.0 | 2018-07-08 22:00:55.713 | info | (0x00158d00018b3ed8): WXKG01LM - Xiaomi MiJia wireless switch (EndDevice)
zigbee.0 | 2018-07-08 22:00:55.713 | info | (0x00158d0001f5621b): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2018-07-08 22:00:55.712 | info | (0x0017880103648612): 915005106701 - Philips Hue white and color ambiance LightStrip plus (Router)
zigbee.0 | 2018-07-08 22:00:55.712 | info | (0x0017880103dcc9d2): TODO - Philips Hue white GU10 (Router)
zigbee.0 | 2018-07-08 22:00:55.711 | info | (0x0017880102de40ac): TODO - Philips Hue white and color ambiance GU10 (Router)
zigbee.0 | 2018-07-08 22:00:55.710 | info | (0x00178801026e5c91): 8718696449691 - Philips Hue White Single bulb B22 (Router)
zigbee.0 | 2018-07-08 22:00:55.710 | info | (0x00158d0001e4508f): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
```
but after state change

`Failed to configure 0x84182600000e4d12`

from here i have no control ..

after restart adapter only 

```
zigbee.0 | 2018-07-08 22:07:08.900 | error | Error while starting zigbee-shepherd!. Error: request timeout
zigbee.0 | 2018-07-08 22:07:00.851 | info | Starting zigbee-shepherd

```

**Comment by kirovilya** [comment]
"Error: request timeout" - it is problem with serialport (it busy by other process or somthing else). Try to reboot.

**Comment by arteck** [comment]
:-) same problem.. after reboot..

**Comment by kirovilya** [comment]
hmmm... it is not ver 0.6 issue of cause. 
may be try to change usb port?

**Comment by arteck** [comment]
> may be try to change usb port?

good idea, but I had the same.... i think the problem is the routing. when you pair battery devices first ..

**Comment by kirovilya** [comment]
Hmm... Look at this https://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/t/665893?CC2530-What-is-the-maximum-number-of-Routers-can-connect-with-the-Coordinator-
It may be cause of your problem. By default only 6 router is able to connect. 
You need follow https://github.com/Koenkk/Z-Stack-firmware and try to build your own firmware with many routers.
Or to learn how connect other devices throught the routers (I do not known how yet).

**Comment by arteck** [comment]
hmm what is with manual switch a Router to EndDevice.. is it possible ??

**Comment by kirovilya** [comment]
I think there is no such manual...  
I was told that it is possible to pair devices to a router, not to a coordinator. And as a result, there is free memory in the coordinator.
But I do not know exactly how to do it, there is no such experience.

**Comment by arteck** [comment]
ok but what can i do with a lot of routers here..  when I count through, I come up 15.. plugs, bulbs, gu10, stripes ..
