### ISSUE TITLE
Probleme mit Tint LED Stripe

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.zigbee#1500]
Hallo,

ich habe einen Tint LED Stripe von Müller Licht.

Zuerst wird dieser nicht korrekt erkannt, sondern als dieses Gerät:

https://www.zigbee2mqtt.io/devices/404028.html

Dann habe ich drei Datenpunkte: Color, ColorTemp und Brightness

ColorTemp kann ich wohl auf Werte zwischen 150 und 550 setzen, z.B. auf 150 (kaltweiß) oder (warmweiß) und via Brightness mit Prozent-Werten die Helligkeit steuern.

Auch eine Farbe kann ich via Color setzen, z.B. ff0000 für rot oder 0000ff für blau oder ffffff für weiß.

Beim Setzen der Farbe geht die Helligkeit aber drastisch runter, auch bei Brightness=100, auch bei erneutem Setzen von Brightness.

Selbst bei fffff (weiß) ist die Helligkeit nur ca. 25% wie wenn ich Colortemp setze.

Ist das jetzt einfach so oder funktioniert da etwas nicht korrekt ?

Danke und viele Grüße Ralf

**Comment by asgothian** [comment]
- is the exact device listed as supported on zigbee2mqtt.io ?
- is it a 3 or a 4 LED stripe (RGB or RGBW ?)
- what happens if you set a color and then change the brightness ?

**Comment by gaudes** [comment]
I own a older one which is integrated:

https://www.zigbee2mqtt.io/devices/44435.html

I've just ordered a second one, seems they've done some little changes.

It's a RGBW stripe

When setting color I can change the brightness, but 100% then seems to be 25% when using colortemp instead of color.

**Comment by asgothian** [comment]
If you own an older one, please check the info page of both devices and post the respective information:
- modelZigbee
- type
- manuf if:
- manufacturer:
- app version
- hard version
- xcl version
- stack version
- date code
- build:

(As far as they are present)

**Comment by gaudes** [comment]
Older version (detected as correct model 44435):

modelZigbee: RGBW Lighting
type: Router
manuf if: 4635
manufacturer: MLI
app version: 40
hard version: 0
zcl version: 3
stack version: 0
date code: NULL
build: 2.5.3_r44

New version (detected as wrong model 404028):

modelZigbee: RGB-CCT
type: Router
manuf if: 4635
manufacturer: MLI
app version: 40
hard version: 0
zcl version: 3
stack version: 0
date code: NULL
build: 2.5.3_r47

**Comment by asgothian** [comment]
Do you have a Model 404028 ? (A real one?) It seems that MLI has messed up with the zigbee reference. Without being able to check possible differences that will be hard to fix.

A.

**Comment by gaudes** [comment]
No, sorry.

The zigbee receiver is an extra "box". One side a power supply is connected, on the other side there is a 5 pin connector to the LED stripe. Maybe they use just the same "box" in the real 404028 also ?

Do you think the wrong device results in my problems with color and brightness ?

**Comment by asgothian** [comment]
After checking the implementation I can safely say that this is not the case. Both devices lead to different names and Images but are treated identically internally.

If the devices behave differently a change must have been made on the MLI side. Debugging this will be more difficult.

**Comment by asgothian** [comment]
You can attempt to set the values via the developer tab.
- Open the zigbee adapter configuration (not the tab)
- Select the developer tab
- select the correct device
- select the correct endpoint (or leave it unselected)
- select the correct cluster (You should review the list of supported clusters on the info page for the device)
- Use the "Foundation/read" command to see which values can be read.
- use the "Functional/moveto" command to see if you can change the values.

I can provide a detailed list of clusters and attributes which are of interest in a few days.

A.

**Comment by gaudes** [comment]
I've done a little bit testing.

The stripe is a RGBW stripe. It looks like it has three different LEDs per unit. One warm-white (WW), one white (W) and one for color (RGB). 

IMHO it seems that when using color that the entered value is created using the RGB-LED, independent wether the "color" could also be created from the white or warm-white LEDs or not.
When using ColorTemp the entered value is created using the white and warm-white LEDs.

This seems to explain the different brightness, because different LEDs are used.

Is this possible ?

I use Yahka for control of the lights, so probably I will create two devices in Yahka, one for ColorMode (setting the color and brightness attributes) and one for "White"-Mode (setting ColorTemp and Brightness).

**Comment by asgothian** [comment]
That is not only possible but likely.
