### ISSUE TITLE
device looses connection

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1501]
I have a door sensor outside which supposedly doesn't get enough signal. When I take in indoors and press the button the connection is recovered and then it works at its destination (postbox) outside .. until something happens (adapter restart maybe). there is an outdoor repeater but the sensor never connects to that .. I have no idea why .. if it connects it rather connects to repeaters that are indoors an farther away. So signal and mesh seem to be an issue.

I have no idea if possible but the Deconz support pointed me to this:

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Source-Routing

And afaik they are in favor of also providing code.

Maybe this is something for a future update?

**Comment by asgothian** [comment]
This is not something we can deal with. It must be implemented in the zigbee-herdsman or zigbee-herdsman-converters.

**Comment by daniel-lo** [comment]
Thanks .. but who is responsible for those?
