### ISSUE TITLE
CC2530 Development Board with 8-Channel 12Bit ADC

### ISSUE THREAD

**Issue by apla2016** [ioBroker/ioBroker.zigbee#1503]
I found a development board based on CC2530 with 8-channel 12bit ADC for DIY projects. Wondering what would it take to adapt it as ZigBee Sensor node to read 8 channels of voltage.

https://www.aliexpress.com/item/3256801808428844.html?spm=a2g0o.productlist.0.0.5e423604YNGgCZ&algo_pvid=256e0691-da36-4c33-a48c-c8eb80015606&algo_exp_id=256e0691-da36-4c33-a48c-c8eb80015606-5&pdp_ext_f=%7B%22sku_id%22%3A%2212000018351946358%22%7D&pdp_npi=2%40dis%21USD%219.8%219.8%21%21%21%21%21%402101e9ce16600762948798086e6f8c%2112000018351946358%21sea&curPageLogUid=8bXaAjdZDZoh

**Comment by asgothian** [comment]
You would need to write a custom firmware for the board.

You might want to check at PTVO.info if this firmware supports said board.

A.

**Comment by apla2016** [comment]
Thank you, I will look into it.

**Comment by apla2016** [comment]
Actually PTVO recommends exactly the CC2530F256 chip that is board I found is based on. How difficult would be to adapt his firmware to work with IoBroker?

**Comment by asgothian** [comment]
Not at all. It is already supported.

A.

**Comment by apla2016** [comment]
Thank you, I ordered a few, will try
