### ISSUE TITLE
[SOLVED] FP1 Presence Sensor "statesMapping.. undefined"

### ISSUE THREAD

**Issue by daes10** [ioBroker/ioBroker.zigbee#1504]
Can anyone help me with the integration of the FP1 Presence Sensor from Aqara?

I cannot implement it to iobroker...

The Log says:
`
Error: Device 0x54ef44100053d7be "lumi.motion.ac01" not described in statesMapping.. undefined
New device joined '0x54ef44100053d7be' model lumi.motion.ac01
Interview successful: [object Object]`

I don't know what statesMapping is, but it doesn't worked. There is a unknown Device listed, but without a Datapoint.

The device is officially supported by Zigbee2MQTT and i have the newest firmware on my zigbee coordinator.

Has anyone the same problems with it? Or have it worked?

Thanks for any help.

**Comment by arteck** [comment]
adapter version ???

**Comment by daes10** [comment]
My ioBroker Adapter had a installation problem. Therefore i reinstalled the adapter and my Problem was solved!
