### ISSUE TITLE
Lidl Lovarno Outdoor LED Stripe

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/ioBroker.zigbee#1506]
Hi ich hab eine Frage kann das Device Lidl Lovarno Outdoor LED Stripe in den Adapter aufgenommen werden anscheinend wird er noch nicht richtig erkannt.

![Bildschirmfoto 2022-08-15 um 10 12 23](https://user-images.githubusercontent.com/62701386/184599971-4de66636-3945-4573-b39a-65bafa07b770.png)
.

**Comment by arteck** [comment]
zeigmal die Info seite

**Comment by Trunks1982** [comment]
![Bildschirmfoto 2022-08-15 um 11 16 51](https://user-images.githubusercontent.com/62701386/184609481-ad5d291f-7e40-4f87-8b50-4fac6a159cc2.png)

**Comment by asgothian** [comment]
- Lässt sich der Strip (ein, aus) schalten ?
- Lassen sich Farbe und/oder Helligkeit steuern ?

Zeig mal die Objekte die für das Gerät angelegt werden.

Ansonsten:
https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update

Deine Info Seite zeigt deutlich das das Gerät durchaus korrekt erkannt wird.

**Comment by Trunks1982** [comment]
Ja geht.
