### ISSUE TITLE
Tuya Steckdose TS011F Probleme beim pairing

### ISSUE THREAD

**Issue by cherberg** [ioBroker/ioBroker.zigbee#1507]
Zigbee Adapter Version 1.7.6 (beta)

Hallo,,

auf der Suche nach einer günstigen Zigbee Steckdose mit Messfunktion stiess ich auf das Modell TS01F bei Aliexpress:
https://de.aliexpress.com/item/1005004199086766.html?spm=a2g0o.order_detail.0.0.129163686qaWNH&gatewayAdapt=glo2deu

Der Adapter lässt sich paaren aber im Protokoll gibt es entweder den folgenden Fehler (Instanz mit Conbee 2 Stick)

` zigbee.0 2022-08-18 16:19:29.098	info	Successfully interviewed '0xa4c138dad9ead9a5', device has succesfully been paired
zigbee.0 2022-08-18 16:19:28.594	error	Device 0xa4c138dad9ead9a5 "TS011F" not described in statesMapping.
zigbee.0 2022-08-18 16:19:28.259	info	Starting interview of '0xa4c138dad9ead9a5'`

oder diesen bei einer anderen iobroker Instanz mit einem Raspbee 1:
`
zigbee.0 | 2022-08-19 10:17:11.200 | info | Successfully interviewed '0xa4c138d78e488df3', device has succesfully been paired
zigbee.0 | 2022-08-19 10:16:44.907 | info | Zigbee: stop joining
zigbee.0 | 2022-08-19 10:15:13.733 | error | Device 0xa4c138d78e488df3 "undefined" not described in statesMapping.
zigbee.0 | 2022-08-19 10:15:08.159 | info | Starting interview of '0xa4c138d78e488df3'
`

Der Adapter erscheint in der Übersicht mit einem Fragezeichen und lässt sich leider nicht steuern:
![image](https://user-images.githubusercontent.com/8701752/185589698-1cfb22e5-2e25-48e2-9964-b95338cb7210.png)

Ich habe gelesen, dass der TS011F eigentlich funktionieren sollte, es aber wohl viele verschiedene Versionen / Hersteller gibt 

Gibt es die Möglichkeit diese Dosen zu integrieren?

Danke für jegliche Hilfe.

**Comment by cherberg** [comment]
UPDATE: 

I added the vendor code 
'_TZ3000_gznh2xla'

at the very beginning of file
/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/tuya.js

under 
const TS011Fplugs =

after a restart of the zigbee adapter the plug is fully functional including power monitoring

**Comment by arteck** [comment]
or install GIT version
