### ISSUE TITLE
Ikea Styrbar - No Buttonevent like 1002, 2002

### ISSUE THREAD

**Issue by hytrek** [ioBroker/ioBroker.zigbee#1509]
Hi there
I am not a programmer and relatively unused with Zigbee / ioBroker... could you kindly help with this?

I have added the Ikea Styrbar into ioBroker connected to the TI Board. The Zigbee adapter version I am using is: 1.7.5
A friend of mine, using Deconz, finds "buttonevents" in his ioBroker installation. Those are for excample: 1002, 2002, 1001 etc.
I don't find no buttonevents... Just the timestamps changes, when pressing a button. Am I am missing something? I know. in a script I could trigger to the timestamp, but "buttonevents" are charming I find...

Thanks
Peter

**Comment by asgothian** [comment]
There is not, and will not be a button event as in deconz.
There are states which switch from `false` to `true` and back to `false` within approx 100 to 500 ms. You can trigger on those with "is greater than before"
