### ISSUE TITLE
Wrong/outdated names in dev_names.json

### ISSUE THREAD

**Issue by theimo1221** [ioBroker/ioBroker.zigbee#1510]
Hello team,

Checking the backup file I noticed that most of the device names are missing:
![image](https://user-images.githubusercontent.com/20605452/185917673-d3ba87d2-02c9-495c-ad54-da646b3f94a3.png)

Now I fear that in case of a crash, the names will not be recovered.

Just pressing edit name and save without changes doesn't update the `dev_names.json`. Only changing combined with changing back does indeed update the file, with than a correct name.

Is there any way I can let ioBroker recreate the whole file with correct names? I can't do it manually as there are over 200 devices in the file.

Best regards 

Thiemo

**Comment by arteck** [comment]
@asgothian dev_names.json is yours product  :-)

**Comment by asgothian** [comment]
yep, but it will have to wait to next weekend - i am off to vienna :)

I'll check for a sollution inside the adapter.

**Comment by arteck** [comment]
check version 1.9.2 .. iyou can rebuild it with this button
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/a825e7d0-a430-487e-af8a-d7e4f7106e7d)
