### ISSUE TITLE
HAMA Thermostat - local_temp_calibration only accepts integer values / decimal would be nicer,

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.zigbee#1511]
... if possible!

Thanx!

**Comment by asgothian** [comment]
More information please ?
- exact device (Info page from the adapter config)
- adapter version you tried this with
- logs from attempting to set the value (add the last 6 digits from the IEEE of the device to the state zigbee.0.info.debugmessages, then attempt to set the value and check the log file for messages with the keyword 'ELEVATED'

**Comment by Haifeif** [comment]
Sorry, I thought the integer / decimal for local_temp_calibration was enough. My fault.

 

Deviceinfo:

 

*	model: <https://www.zigbee2mqtt.io/devices/SEA801-Zigbee_SEA802-Zigbee.html> SEA801-Zigbee/SEA802-Zigbee
*	description:Thermostatic radiator valve

*	modelZigbee:TS0601
*	type:EndDevice
*	nwk:14214
*	manuf id:4098
*	manufacturer:_TZE200_yw7cahqs
*	power:Battery
*	app version:85
*	hard version:1
*	zcl version:3
*	stack version:0
*	date code:
*	interviewed:true

*	configured:true
*	endpoint:1
*	profile:260
*	input clusters:genBasic (0)
*	genGroups (4)
*	genScenes (5)
*	manuSpecificTuya (61184)
*	output clusters:genOta (25)
*	genTime (10)

Zigbee Adapter Version v1.7.5

 

Log: (with 2,25)

 




zigbee.0

2022-08-25 21:32:33.888

debug

convert result undefined




zigbee.0

2022-08-25 21:32:33.887

debug

zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []




zigbee.0

2022-08-25 21:32:33.886

debug

zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":34}




zigbee.0

2022-08-25 21:32:33.885

debug

zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,34] - 228




zigbee.0

2022-08-25 21:32:33.883

debug

zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,34,228]




zigbee.0

2022-08-25 21:32:33.882

debug

zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,34,228]




zigbee.0

2022-08-25 21:32:33.877

debug

zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []




zigbee.0

2022-08-25 21:32:33.875

debug

zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}




zigbee.0

2022-08-25 21:32:33.874

debug

zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100




zigbee.0

2022-08-25 21:32:33.873

debug

zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]




zigbee.0

2022-08-25 21:32:33.872

debug

zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]




zigbee.0

2022-08-25 21:32:33.861

debug

zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,23,36,1,134,55,1,1,0,239,34,0,30,13,17,21,0,3,0,27,2,0,4,0,0,2,0,69]




zigbee.0

2022-08-25 21:32:33.852

debug

zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":14214,"destendpoint":1,"srcendpoint":1,"clusterid":61184,"transid":34,"options":0,"radius":30,"len":13,"data":{"type":"Buffer","data":[17,21,0,3,0,27,2,0,4,0,0,2,0]}}




zigbee.0

2022-08-25 21:32:33.851

debug

zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0xcc86ecfffea50cb0:14214/1 (0,0,1)




zigbee.0

2022-08-25 21:32:33.850

debug

zigbee-herdsman:controller:endpoint Command 0xcc86ecfffea50cb0/1 manuSpecificTuya.dataRequest({"seq":3,"dpValues":[{"dp":27,"datatype":2,"data":[0,0,2,null]}]}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})




zigbee.0

2022-08-25 21:32:33.848

debug

target: {"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,4,5,61184],"outputClusters":[25,10],"deviceNetworkAddress":14214,"deviceIeeeAddress":"0xcc86ecfffea50cb0","clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_yw7cahqs","powerSource":3,"zclVersion":3,"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"_binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b00219fc338","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]}




zigbee.0

2022-08-25 21:32:33.847

debug

convert local_temperature_calibration, 2.25, {}




zigbee.0

2022-08-25 21:32:33.846

debug

Mapped Model: {"fingerprint":[{"modelID":"GbxAXL2\u0000","manufacturerName":"_TYST11_KGbxAXL2"},{"modelID":"uhszj9s\u0000","manufacturerName":"_TYST11_zuhszj9s"},{"modelID":"88teujp\u0000","manufacturerName":"_TYST11_c88teujp"},{"modelID":"w7cahqs\u0000","manufacturerName":"_TYST11_yw7cahqs"},{"modelID":"w7cahqs","manufacturerName":"_TYST11_yw7cahqs"},{"modelID":"TS0601","manufacturerName":"_TZE200_c88teujp"},{"modelID":"TS0601","manufacturerName":"_TZE200_yw7cahqs"},{"modelID":"TS0601","manufacturerName":"_TZE200_azqp6ssj"},{"modelID":"TS0601","manufacturerName":"_TZE200_bvu2wnxz"},{"modelID":"TS0601","manufacturerName":"_TZE200_zuhszj9s"},{"modelID":"TS0601","manufacturerName":"_TZE200_9gvruqf5"},{"modelID":"TS0601","manufacturerName":"_TZE200_zr9c0day"}],"model":"SEA801-Zigbee/SEA802-Zigbee","vendor":"Saswell","description":"Thermostatic radiator valve","whiteLabel":[{"vendor":"HiHome","model":"WZB-TRVL"},{"vendor":"Hama","model":"00176592"},{"vendor":"RTX","model":"ZB-RT1"}],"fromZigbee":[{"cluster":"manuSpecificTuya","type":["commandDataResponse","commandDataReport"]},{"cluster":"manuSpecificTuya","type":["commandMcuSyncTime"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]},{"cluster":"manuSpecificTuya","type":["commandDataResponse","commandDataReport"],"options":[{"type":"binary","name":"legacy","property":"legacy","access":2,"value_on":true,"value_off":false,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true)."}]}],"toZigbee":[{"key":["current_heating_setpoint"]},{"key":["system_mode"]},{"key":["away_mode"]},{"key":["child_lock"]},{"key":["window_detection"]},{"key":["frost_detection"]},{"key":["local_temperature_calibration"]},{"key":["anti_scaling"]},{"key":["weekly_schedule"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]}],"meta":{"thermostat":{"weeklyScheduleMaxTransitions":4,"weeklyScheduleSupportedModes":[1],"weeklyScheduleConversion":"saswell"}},"exposes":[{"type":"binary","name":"battery_low","property":"battery_low","access":1,"value_on":true,"value_off":false,"description":"Indicates if the battery of this device is almost empty"},{"type":"switch","features":[{"type":"binary","name":"state","property":"window_detection","access":3,"value_on":"ON","value_off":"OFF","description":"Enables/disables window detection on the device","value_toggle":"TOGGLE"}]},{"type":"lock","features":[{"type":"binary","name":"state","property":"child_lock","access":3,"value_on":"LOCK","value_off":"UNLOCK","description":"Enables/disables physical input on the device"}]},{"type":"binary","name":"heating","property":"heating","access":1,"value_on":"ON","value_off":"OFF","description":"Device valve is open or closed (heating or not)"},{"type":"climate","features":[{"type":"numeric","name":"current_heating_setpoint","property":"current_heating_setpoint","access":3,"value_min":5,"value_max":30,"value_step":0.5,"unit":"°C","description":"Temperature setpoint"},{"type":"numeric","name":"local_temperature","property":"local_temperature","access":1,"unit":"°C","description":"Current temperature measured on the device"},{"type":"enum","name":"system_mode","property":"system_mode","access":3,"values":["off","heat","auto"],"description":"Mode of this device"},{"type":"numeric","name":"local_temperature_calibration","property":"local_temperature_calibration","access":3,"value_min":-6,"value_max":6,"value_step":1,"unit":"°C","description":"Offset to be used in the local_temperature"},{"type":"binary","name":"away_mode","property":"away_mode","access":3,"value_on":"ON","value_off":"OFF","description":"Away mode"}]},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"options":[{"type":"binary","name":"legacy","property":"legacy","access":2,"value_on":true,"value_off":false,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true)."}]}




zigbee.0

2022-08-25 21:32:33.843

debug

entity: {"type":"device","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":52,"_type":"EndDevice","_ieeeAddr":"0xcc86ecfffea50cb0","_networkAddress":14214,"_manufacturerID":4098,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,4,5,61184],"outputClusters":[25,10],"deviceNetworkAddress":14214,"deviceIeeeAddress":"0xcc86ecfffea50cb0","clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_yw7cahqs","powerSource":3,"zclVersion":3,"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"_binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b00219fc338","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"_TZE200_yw7cahqs","_powerSource":"Battery","_modelID":"TS0601","_applicationVersion":85,"_stackVersion":0,"_zclVersion":3,"_hardwareVersion":1,"_dateCode":"","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":1},"_lastSeen":1661455776177,"_defaultSendRequestWhen":"immediate","_linkquality":178},"mapped":{"fingerprint":[{"modelID":"GbxAXL2\u0000","manufacturerName":"_TYST11_KGbxAXL2"},{"modelID":"uhszj9s\u0000","manufacturerName":"_TYST11_zuhszj9s"},{"modelID":"88teujp\u0000","manufacturerName":"_TYST11_c88teujp"},{"modelID":"w7cahqs\u0000","manufacturerName":"_TYST11_yw7cahqs"},{"modelID":"w7cahqs","manufacturerName":"_TYST11_yw7cahqs"},{"modelID":"TS0601","manufacturerName":"_TZE200_c88teujp"},{"modelID":"TS0601","manufacturerName":"_TZE200_yw7cahqs"},{"modelID":"TS0601","manufacturerName":"_TZE200_azqp6ssj"},{"modelID":"TS0601","manufacturerName":"_TZE200_bvu2wnxz"},{"modelID":"TS0601","manufacturerName":"_TZE200_zuhszj9s"},{"modelID":"TS0601","manufacturerName":"_TZE200_9gvruqf5"},{"modelID":"TS0601","manufacturerName":"_TZE200_zr9c0day"}],"model":"SEA801-Zigbee/SEA802-Zigbee","vendor":"Saswell","description":"Thermostatic radiator valve","whiteLabel":[{"vendor":"HiHome","model":"WZB-TRVL"},{"vendor":"Hama","model":"00176592"},{"vendor":"RTX","model":"ZB-RT1"}],"fromZigbee":[{"cluster":"manuSpecificTuya","type":["commandDataResponse","commandDataReport"]},{"cluster":"manuSpecificTuya","type":["commandMcuSyncTime"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]},{"cluster":"manuSpecificTuya","type":["commandDataResponse","commandDataReport"],"options":[{"type":"binary","name":"legacy","property":"legacy","access":2,"value_on":true,"value_off":false,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true)."}]}],"toZigbee":[{"key":["current_heating_setpoint"]},{"key":["system_mode"]},{"key":["away_mode"]},{"key":["child_lock"]},{"key":["window_detection"]},{"key":["frost_detection"]},{"key":["local_temperature_calibration"]},{"key":["anti_scaling"]},{"key":["weekly_schedule"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]}],"meta":{"thermostat":{"weeklyScheduleMaxTransitions":4,"weeklyScheduleSupportedModes":[1],"weeklyScheduleConversion":"saswell"}},"exposes":[{"type":"binary","name":"battery_low","property":"battery_low","access":1,"value_on":true,"value_off":false,"description":"Indicates if the battery of this device is almost empty"},{"type":"switch","features":[{"type":"binary","name":"state","property":"window_detection","access":3,"value_on":"ON","value_off":"OFF","description":"Enables/disables window detection on the device","value_toggle":"TOGGLE"}]},{"type":"lock","features":[{"type":"binary","name":"state","property":"child_lock","access":3,"value_on":"LOCK","value_off":"UNLOCK","description":"Enables/disables physical input on the device"}]},{"type":"binary","name":"heating","property":"heating","access":1,"value_on":"ON","value_off":"OFF","description":"Device valve is open or closed (heating or not)"},{"type":"climate","features":[{"type":"numeric","name":"current_heating_setpoint","property":"current_heating_setpoint","access":3,"value_min":5,"value_max":30,"value_step":0.5,"unit":"°C","description":"Temperature setpoint"},{"type":"numeric","name":"local_temperature","property":"local_temperature","access":1,"unit":"°C","description":"Current temperature measured on the device"},{"type":"enum","name":"system_mode","property":"system_mode","access":3,"values":["off","heat","auto"],"description":"Mode of this device"},{"type":"numeric","name":"local_temperature_calibration","property":"local_temperature_calibration","access":3,"value_min":-6,"value_max":6,"value_step":1,"unit":"°C","description":"Offset to be used in the local_temperature"},{"type":"binary","name":"away_mode","property":"away_mode","access":3,"value_on":"ON","value_off":"OFF","description":"Away mode"}]},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"options":["[Circular]"]},"endpoint":"[Circular]","endpoints":"[Circular]","name":"0xcc86ecfffea50cb0"}




zigbee.0

2022-08-25 21:32:33.836

debug

Change state 'local_temp_calibration' at device 0xcc86ecfffea50cb0 type 'SEA801-Zigbee/SEA802-Zigbee'




zigbee.0

2022-08-25 21:32:33.818

debug

User stateChange zigbee.0.cc86ecfffea50cb0.local_temp_calibration {"val":2.25,"ack":false,"ts":1661455953809,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1661455953809}

 

Is that what you are looking for?

 

Rgds, Uwe

 

 

Von: asgothian ***@***.***> 
Gesendet: Dienstag, 23. August 2022 18:08
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: Haifeif ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] HAMA Thermostat - local_temp_calibration only accepts integer values / decimal would be nicer, (Issue #1511)

 

More information please ?

*	exact device (Info page from the adapter config)
*	adapter version you tried this with
*	logs from attempting to set the value (add the last 6 digits from the IEEE of the device to the state zigbee.0.info.debugmessages, then attempt to set the value and check the log file for messages with the keyword 'ELEVATED'

**Comment by Haifeif** [comment]
… ELEVATED did not appear at all

 

Rgds Uwe

 

Von: asgothian ***@***.***> 
Gesendet: Dienstag, 23. August 2022 18:08
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: Haifeif ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] HAMA Thermostat - local_temp_calibration only accepts integer values / decimal would be nicer, (Issue #1511)

 

More information please ?

*	exact device (Info page from the adapter config)
*	adapter version you tried this with
*	logs from attempting to set the value (add the last 6 digits from the IEEE of the device to the state zigbee.0.info.debugmessages, then attempt to set the value and check the log file for messages with the keyword 'ELEVATED'

**Comment by asgothian** [comment]
No, it is not:
- no-one requested you to run the adapter in debug with the herdsman debug
- the post you made is unreadable. No code tags, no nothing. The information I seek may be in there, may be not. I can't tell
- in order to get what is needed you need to:

1. run the adapter in "normal" mode. No debug mode, no zigbee-herdsman-debug info.
2. enter `fffea50cb0` into the state `zigbee.0.info.debugmessages`
3. change the local_temp_calibration state (assuming it is a state)
4. watch for the log for ELEVATED messages. If you don't get any, you have either not entered the data above correctly, or the value you are trying to set is not set via a state.

A.

**Comment by Haifeif** [comment]
Sorry to bother you. 

 

I try to do my very best. As soon, as I have the info, I’ll send it.

 

Rgds, Uwe

 

Von: asgothian ***@***.***> 
Gesendet: Donnerstag, 25. August 2022 23:49
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: Haifeif ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] HAMA Thermostat - local_temp_calibration only accepts integer values / decimal would be nicer, (Issue #1511)

 

No, it is not:

*	no-one requested you to run the adapter in debug with the herdsman debug
*	the post you made is unreadable. No code tags, no nothing. The information I seek may be in there, may be not. I can't tell
*	in order to get what is needed you need to:

1.	run the adapter in "normal" mode. No debug mode, no zigbee-herdsman-debug info.
2.	enter fffea50cb0 into the state zigbee.0.info.debugmessages
3.	change the local_temp_calibration state (assuming it is a state)
4.	watch for the log for ELEVATED messages. If you don't get any, you have either not entered the data above correctly, or the value you are trying to set is not set via a state.

A.

**Comment by Haifeif** [comment]
Sorry, I don't have the needed knowledge.

1. run adapter in "normal" mode ...

When I select <Instanzen> and open zigbee.0, I can change the <Protokollebene>. 
But there are only
- Alles
- Debug
- info
- Warnung
- Fehler
but no "normal" mode. I guess, you mean -info?

2. enter fff... into the state zigbee.0.info.debugmessages

I have no idea, where to do that.

3. change ...

OK

4. watch for the log  for ELEVATED ...

As soon as I can handle 1 + 2

Maybe you can tell me where to find the needed background info, you are asking for. I'm willing to learn ...

Thx for your patience,

Rgds Uwe

**Comment by Haifeif** [comment]
Great! That helps a lot!

 

I’ll be back!

 

Rgds Uwe

 

Von: asgothian ***@***.***> 
Gesendet: Montag, 12. September 2022 18:04
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: Haifeif ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] HAMA Thermostat - local_temp_calibration only accepts integer values / decimal would be nicer, (Issue #1511)

 

*	"normal" mode is "info" which gives info, warning and error messages
*	If you check the objects, you should find the state zigbee.0.info.debugmessages. A click on the value allows you to edit the value, and confirming the dialog will enter this.

 <https://user-images.githubusercontent.com/45667167/189701842-951fe61e-8d1f-424e-ac08-8b327a0456e0.png> 

 <https://user-images.githubusercontent.com/45667167/189701890-8e6104b7-f324-492c-8c96-553d1a47f3da.png>

**Comment by Haifeif** [comment]
Asgothian, I don’t get it.

 

Forget, I will live with it.

 

Rgds, Uwe

 

Von: asgothian ***@***.***> 
Gesendet: Montag, 12. September 2022 18:04
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: Haifeif ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] HAMA Thermostat - local_temp_calibration only accepts integer values / decimal would be nicer, (Issue #1511)

 

*	"normal" mode is "info" which gives info, warning and error messages
*	If you check the objects, you should find the state zigbee.0.info.debugmessages. A click on the value allows you to edit the value, and confirming the dialog will enter this.

 <https://user-images.githubusercontent.com/45667167/189701842-951fe61e-8d1f-424e-ac08-8b327a0456e0.png> 

 <https://user-images.githubusercontent.com/45667167/189701890-8e6104b7-f324-492c-8c96-553d1a47f3da.png>
