### ISSUE TITLE
enable pairing mode / Touchlink with dp

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.zigbee#1512]
In the zigbee objects there is an state called "pairingMode".
It would be nice to enble the pairing mode with set this state to true. (actual state is not writable)
After the countdown (maybe also writable) the state will fallback to false.

![image](https://user-images.githubusercontent.com/92173565/186990676-7217c1bd-e451-42e1-9ab0-792765388a3b.png)

maybe it is also possible for the "Touchlink" function?

**Comment by asgothian** [comment]
This has been requested before. As opening the network is a security risk this is not something which will be implemented at this time.

**Comment by BenAhrdt** [comment]
a pity
