### ISSUE TITLE
different link quality values

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.zigbee#1514]
![image](https://user-images.githubusercontent.com/39678667/187136910-e33462cf-9027-47ca-87b0-a91c2090a297.png)
value 72

![image](https://user-images.githubusercontent.com/39678667/187136884-1464dba1-b456-4dfe-a817-bb138f25dbcb.png)
value 67

zigbee 1.7.6
admin 6.2.18
js-controller 4.0.23
nodejs 16.17.0

**Comment by asgothian** [comment]
This is due to the way the values are requested and reported. The values given are not identical, hence the different numbers.

**Comment by Diginix** [comment]
Ok, but why there are two ways for "one" value?
