### ISSUE TITLE
Adapter crashes and is not able to connect to CC26X2 anymore

### ISSUE THREAD

**Issue by MeierAlex** [ioBroker/ioBroker.zigbee#1521]
HAllo,

sometimes my adopter crashes and it can not connect to the usb device anymore. I need to unplug and plug the device again before I can reconnect. This leads to large potential downtimes and a lot on manual maintanence. I am using version 1.7.5. Find attached the log:

```
zigbee.0 | 2022-09-09 08:39:55.053 | warn | Device query for '0x804b50fffe8f7799' blocked
zigbee.0 | 2022-09-09 08:39:54.471 | warn | Device query for '0x804b50fffe8f7799' blocked
zigbee.0 | 2022-09-09 08:39:53.746 | warn | Device query for '0x804b50fffe8f7799' blocked
zigbee.0 | 2022-09-09 08:39:52.643 | warn | Device query for '0x804b50fffe8f7799' blocked
zigbee.0 | 2022-09-09 08:39:51.364 | warn | Device '0x0c4314fffeaee1b8' announced itself
zigbee.0 | 2022-09-09 08:39:27.583 | info | Zigbee started
zigbee.0 | 2022-09-09 08:39:27.582 | info | 0xec1bbdfffe783af6 (addr 13878): HG06336 - Lidl Silvercrest smart window and door sensor (EndDevice)
zigbee.0 | 2022-09-09 08:39:27.581 | info | 0x60a423fffe0550f4 (addr 40076): HG06337 - Lidl Silvercrest smart plug (EU, CH, FR, BS, DK) (Router)
zigbee.0 | 2022-09-09 08:39:27.580 | info | 0xec1bbdfffeac646d (addr 64414): HG06336 - Lidl Silvercrest smart window and door sensor (EndDevice)
zigbee.0 | 2022-09-09 08:39:27.579 | info | 0xec1bbdfffeaebc3c (addr 40938): HG06336 - Lidl Silvercrest smart window and door sensor (EndDevice)
zigbee.0 | 2022-09-09 08:39:27.578 | info | 0xec1bbdfffe946bcf (addr 47250): HG06336 - Lidl Silvercrest smart window and door sensor (EndDevice)
zigbee.0 | 2022-09-09 08:39:27.577 | info | 0xec1bbdfffeaebc35 (addr 24990): HG06336 - Lidl Silvercrest smart window and door sensor (EndDevice)
zigbee.0 | 2022-09-09 08:39:27.576 | info | 0x680ae2fffe0b5340 (addr 5634): HG06336 - Lidl Silvercrest smart window and door sensor (EndDevice)
zigbee.0 | 2022-09-09 08:39:27.575 | info | 0xcc86ecfffe921704 (addr 7912): E1746 - IKEA TRADFRI signal repeater (Router)
zigbee.0 | 2022-09-09 08:39:27.575 | info | 0x0c4314fffeae47b2 (addr 36768): E1525/E1745 - IKEA TRADFRI motion sensor (EndDevice)
zigbee.0 | 2022-09-09 08:39:27.573 | info | 0x804b50fffe8f7799 (addr 25053): E1603/E1702/E1708 - IKEA TRADFRI control outlet (Router)
zigbee.0 | 2022-09-09 08:39:27.547 | info | 0x0c4314fffeaee1b8 (addr 32275): E1812 - IKEA TRADFRI shortcut button (EndDevice)
zigbee.0 | 2022-09-09 08:39:27.427 | info | Currently 11 devices are joined:
zigbee.0 | 2022-09-09 08:39:27.404 | info | --> transmitPower : high
zigbee.0 | 2022-09-09 08:39:27.345 | info | Unable to disable LED, unsupported function.
zigbee.0 | 2022-09-09 08:39:27.297 | info | Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210708}}
zigbee.0 | 2022-09-09 08:39:23.865 | warn | Extended PAN ID is reversed (expected=3cc5f414004b1200, actual=00124b0014f4c53c)
zigbee.0 | 2022-09-09 08:39:23.527 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:39:22.659 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:39:22.657 | info | delete old Backup files. keep only last 10
zigbee.0 | 2022-09-09 08:39:22.562 | info | starting. Version 1.7.5 in /opt/iobroker/node_modules/iobroker.zigbee, node: v16.16.0, js-controller: 4.0.23
zigbee.0 | 2022-09-09 08:39:10.128 | warn | get state error: Connection is closed.
zigbee.0 | 2022-09-09 08:39:09.599 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.0 | 2022-09-09 08:39:09.598 | info | terminating
zigbee.0 | 2022-09-09 08:39:09.596 | warn | Failed to stop zigbee during startup
zigbee.0 | 2022-09-09 08:39:09.572 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2022-09-09 08:39:09.446 | info | cleaned everything up...
zigbee.0 | 2022-09-09 08:39:09.444 | info | Got terminate signal TERMINATE_YOURSELF
zigbee.0 | 2022-09-09 08:35:58.284 | error | Error herdsman start
zigbee.0 | 2022-09-09 08:35:58.284 | error | Failed to start Zigbee
zigbee.0 | 2022-09-09 08:35:58.283 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2022-09-09 08:35:58.019 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:35:57.954 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:35:57.953 | info | Try to reconnect. 0 attempts left
zigbee.0 | 2022-09-09 08:35:57.947 | error | Error herdsman start
zigbee.0 | 2022-09-09 08:35:57.947 | error | Failed to start Zigbee
zigbee.0 | 2022-09-09 08:35:57.928 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2022-09-09 08:35:57.612 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:35:57.564 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:35:57.562 | info | Try to reconnect. 1 attempts left
zigbee.0 | 2022-09-09 08:35:47.935 | error | Error herdsman start
zigbee.0 | 2022-09-09 08:35:47.931 | error | Failed to start Zigbee
zigbee.0 | 2022-09-09 08:35:47.924 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2022-09-09 08:35:47.560 | error | Error herdsman start
zigbee.0 | 2022-09-09 08:35:47.560 | error | Failed to start Zigbee
zigbee.0 | 2022-09-09 08:35:47.559 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2022-09-09 08:35:47.501 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:35:47.451 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:35:47.450 | info | Try to reconnect. 2 attempts left
zigbee.0 | 2022-09-09 08:35:47.198 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:35:47.159 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:35:47.158 | info | Try to reconnect. 3 attempts left
zigbee.0 | 2022-09-09 08:35:37.442 | error | Error herdsman start
zigbee.0 | 2022-09-09 08:35:37.442 | error | Failed to start Zigbee
zigbee.0 | 2022-09-09 08:35:37.441 | error | Starting zigbee-herdsman problem : "Cannot read properties of undefined (reading 'execute')"
zigbee.0 | 2022-09-09 08:35:37.327 | warn | Extended PAN ID is reversed (expected=3cc5f414004b1200, actual=00124b0014f4c53c)
zigbee.0 | 2022-09-09 08:35:37.154 | error | Error herdsman start
zigbee.0 | 2022-09-09 08:35:37.153 | error | Failed to start Zigbee
zigbee.0 | 2022-09-09 08:35:37.151 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2022-09-09 08:35:36.488 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:35:36.468 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:35:36.377 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:35:36.375 | info | Try to reconnect. 4 attempts left
zigbee.0 | 2022-09-09 08:35:36.339 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:35:36.337 | info | Try to reconnect. 5 attempts left
zigbee.0 | 2022-09-09 08:32:38.622 | error | Adapter disconnected, stopping
zigbee.0 | 2022-09-09 08:32:38.585 | error | Adapter disconnected, stopping

```
Here you can see that everything seems to srat with "Adapter disconnected, stopping" and from this point on the USB serial port seems to be occupied and can not be aquired anymore.

I will set the logging level of the adapter to debug and post further logs if desired.

Best regards
Alex

mod edit: code tags for log

**Comment by asgothian** [comment]
Please test:

When the adapter does not restart, stop the adapter, wait 30 seconds, attempt a restart.

Also: please verify that the zigbee adapter is not running in background in parallel. The logs seem to indicate that the adapter is running twice:

```
zigbee.0 | 2022-09-09 08:35:36.488 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:35:36.468 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-09-09 08:35:36.377 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:35:36.375 | info | Try to reconnect. 4 attempts left
zigbee.0 | 2022-09-09 08:35:36.339 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-09 08:35:36.337 | info | Try to reconnect. 5 attempts left
zigbee.0 | 2022-09-09 08:32:38.622 | error | Adapter disconnected, stopping
zigbee.0 | 2022-09-09 08:32:38.585 | error | Adapter disconnected, stopping

```

**Comment by MeierAlex** [comment]
Thank you for your answer. I now got the debug information from a crash of the adapter which shows what is going on and why it is crashing. I am using the version from github because in an other thread you suggested to use this version in case of unexpected crashes. See the log attached:

<html>
<body>


zigbee.0 | 2022-09-14 08:29:01.889 | error | Error herdsman start
-- | -- | -- | --
zigbee.0 | 2022-09-14 08:29:01.889 | error | Failed to start Zigbee
zigbee.0 | 2022-09-14 08:29:01.888 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2022-09-14 08:28:51.396 | error | Error herdsman start
zigbee.0 | 2022-09-14 08:28:51.396 | error | Failed to start Zigbee
zigbee.0 | 2022-09-14 08:28:51.395 | error | Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
host.iobroker | 2022-09-14 08:27:54.964 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2022-09-14 08:27:54.964 | error | Caught by controller[1]: at Controller.backup (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:316:47)
host.iobroker | 2022-09-14 08:27:54.964 | error | Caught by controller[1]: at ZStackAdapter.backup (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:837:36)
host.iobroker | 2022-09-14 08:27:54.964 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'backup')
host.iobroker | 2022-09-14 08:27:54.950 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2022-09-14 08:27:54.117 | error | Cannot read properties of undefined (reading 'backup')
zigbee.0 | 2022-09-14 08:27:54.117 | error | TypeError: Cannot read properties of undefined (reading 'backup') at ZStackAdapter.backup (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:837:36) at Controller.backup (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:316:47)
zigbee.0 | 2022-09-14 08:27:54.116 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'backup')
zigbee.0 | 2022-09-14 08:27:54.116 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>

**Comment by asgothian** [comment]
The log is incomplete. There must be additional entries before 08:27:54 (possibly as warn or info)

A.

**Comment by MeierAlex** [comment]
I have gone trough the log and just found these lines:

2022-09-14 07:46:53.953  - [34mdebug[39m: zigbee.0 (1470) zigbee-herdsman:adapter:zStack:znp:log Port closed
2022-09-14 07:46:53.966  - [34mdebug[39m: zigbee.0 (1470) zigbee-herdsman:controller:log Adapter disconnected'
2022-09-14 07:46:53.973  - [31merror[39m: zigbee.0 (1470) Adapter disconnected, stopping
2022-09-14 07:46:53.978  - [31merror[39m: zigbee.0 (1470) Adapter disconnected, stopping

Does this help you to identify the problem or should I upload the whole log for the day (which is really, really long) ?

**Comment by asgothian** [comment]
It does pinpoint the issue - it seems as if the serial port to the hardware device has been closed. If I remember right you are running it on Proxxmox or some other virtualisation service ?

A.

**Comment by MeierAlex** [comment]
Hallo,

problem solved - sorry for bothering you! Your adapter works perfectly fine. The problem was my OS which tried in a daylie cronjob to update my virtualization software which caused some services to stop leading to a disconnect of USB devices. Problem now fixed by excluding virtualization software from automatic updates. Thank you very much !

**Comment by asgothian** [comment]
No reason to apologize. I am glad that i could help pinpointing the issue, even if it was not within the adapter, and that you were able to fix it.

A.
