### ISSUE TITLE
CC2531 crashes befor send anything

### ISSUE THREAD

**Issue by tomthomson1992** [ioBroker/ioBroker.zigbee#1522]
Proxmox with USB passthrough to the LXC Container. The adapter reaches the Stick and is green. By telling Alexa or try to switch any lightbulbs the adapter turns red and the log tells just 
<html>
<body>

zigbee.0 | 2022-09-15 22:59:01.774 | info | Zigbee started
-- | -- | -- | --
zigbee.0 | 2022-09-15 22:59:01.774 | info | Currently no devices.
zigbee.0 | 2022-09-15 22:59:01.729 | info | --> transmitPower : normal
zigbee.0 | 2022-09-15 22:59:01.724 | info | Unable to disable LED, unsupported function.
zigbee.0 | 2022-09-15 22:59:01.719 | info | Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20181024}}
zigbee.0 | 2022-09-15 22:59:01.329 | info | Installed Version: ioBroker/ioBroker.zigbee#c901b43be5761b6c80b31292c791b1f849115625
zigbee.0 | 2022-09-15 22:59:01.123 | info | Starting Zigbee npm ...
zigbee.0 | 2022-09-15 22:59:01.122 | info | delete old Backup files. keep only last 10
zigbee.0 | 2022-09-15 22:59:01.085 | info | starting. Version 1.7.6 (non-npm: ioBroker/ioBroker.zigbee#c901b43be5761b6c80b31292c791b1f849115625) in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.9.0, js-controller: 4.0.23

</body>
</html>``

Also tried to up- or downgrade the adapter by Cat, or using another USB connector, many restart of everything....
Thank you for helping....

**Comment by arteck** [comment]
> Currently no devices.

whitch bulbs  ?? you have no devices
