### ISSUE TITLE
Need to replug CC26X2 when ZigBee adapter gets restarted

### ISSUE THREAD

**Issue by MeierAlex** [ioBroker/ioBroker.zigbee#1523]
Hallo,

whenever I restart my zigbee instance I am not able to connect to the CC26X2 launchpad again and get the following errors:

<html>
<body>

zigbee.0 | 2022-09-16 09:12:34.281 | error | Error herdsman start
-- | -- | -- | --
zigbee.0 | 2022-09-16 09:12:34.281 | error | Failed to start Zigbee
zigbee.0 | 2022-09-16 09:12:34.280 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2022-09-16 09:12:23.809 | error | Error herdsman start
zigbee.0 | 2022-09-16 09:12:23.808 | error | Failed to start Zigbee
zigbee.0 | 2022-09-16 09:12:23.805 | error | Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
zigbee.0 | 2022-09-16 09:08:59.414 | error | Error herdsman start
zigbee.0 | 2022-09-16 09:08:59.414 | error | Failed to start Zigbee
zigbee.0 | 2022-09-16 09:08:59.412 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2022-09-16 09:08:48.995 | error | Error herdsman start
zigbee.0 | 2022-09-16 09:08:48.995 | error | Failed to start Zigbee
zigbee.0 | 2022-09-16 09:08:48.994 | error | Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"

</body>
</html>

If i manually unplug the USB connection of the CC26X2 launchpad everything wokes fine again until I do the next restart of the zigbee instance. I am using Version 1.7.5 and the current firmware (see https://github.com/Koenkk/Z-Stack-firmware)

**Comment by MarkoP2507** [comment]
Ich habe leider das gleiche Problem.

Ich habe die Zigbee Bridge Pro mit Tasmota 12.1.1.2 mit der Aktuellen MCU firmware vom 19.02.2022

LOG
`14:59:34.826 TCP: Got connection from 192.168.0.50
14:59:34.834 TCP: to MCU/1: EF
14:59:35.974 TCP: to MCU/1: FE00210120
14:59:40.287 WIF: Checking connection...
14:59:41.883 TCP: to MCU/1: FE00210120
14:59:47.941 TCP: to MCU/1: FE00210120
15:00:00.261 WIF: Checking connection...
15:00:04.059 TCP: Got connection from 192.168.0.50
15:00:04.064 TCP: to MCU/2: EF
15:00:05.202 TCP: to MCU/2: FE00210120
15:00:11.072 TCP: to MCU/2: FE00210120
15:00:17.130 TCP: to MCU/2: FE00210120
15:00:20.285 WIF: Checking connection...`

**Comment by arteck** [comment]
its not a adapter problem.. and you are not alone

**Comment by MeierAlex** [comment]
@arteck do you know what's the root cause of this problem ?

**Comment by MarkoP2507** [comment]
Moin,

Ich habe heut den Home Assistant ausprobiert dort kann ich mich ohne Probleme verbinden.
Da der adapter bei Home Assistant auch auf das Projekt "herdsman" basiert kann es ja nur noch am ioBroker Adapter liegen

**Comment by arteck** [comment]
> Da der adapter bei Home Assistant auch auf das Projekt "herdsman" basiert kann es ja nur noch am ioBroker Adapter liegen

na klar.. nicht an der installierten herdsman version

ohh man.. das thema wurde schon zig mal behandelt
