### ISSUE TITLE
No status from Aqara window sensor with Sonoff Dongle E Version EFR32MG21 + CH9102F Coordinator

### ISSUE THREAD

**Issue by nowi967** [ioBroker/ioBroker.zigbee#1524]
Hello all,

I have the same problem with the Aqara window sensors.
These are fresh from China. 😲
I just don't get any status back.
However, teach-in works.

Zigbee adapter version 1.7.5
Sonoff Dongle the E version EFR32MG21 + CH9102F Coordinator

Do you have any idea?

![](https://forum.iobroker.net/assets/uploads/files/1663335980320-dee435a9-5e48-499e-81ac-88972b700549-image.png)

![](https://forum.iobroker.net/assets/uploads/files/1663336020743-7df3cefe-4acc-4b2f-8802-9a1ecaebda9a-image.png)

**Comment by asgothian** [comment]
please do the following:
flip the card for the device
wake the device by pressing the little button for a moment
then hit the "reconfigure" icon on the back of the card and check the log for messages.

A.

**Comment by nowi967** [comment]
After 24 hours everything was working fine when the sensor reported to the coordinator.

**Comment by nowi967** [comment]
I will test my other door and window sensors. 

But i close the problem here.
