### ISSUE TITLE
Nedis Zigbee Radiator Control ZBHTR10WT

### ISSUE THREAD

**Issue by Mitch187** [ioBroker/ioBroker.zigbee#1526]
Hi,

i have a Nedis Zigbee Radiator Control ZBHTR10WT and i have connected to the zigbee adapter:

![Screenshot 2022-09-23 122658](https://user-images.githubusercontent.com/70914017/191941894-4b178530-7e36-414a-907b-544b70de1be5.png)

It shows like a Siterwell GS361A-H04 and on the website, it is a whitelabel product:
https://www.zigbee2mqtt.io/devices/GS361A-H04.html

i get many data from the device to iobroker:
![bbbScreenshot 2022-09-23 125301](https://user-images.githubusercontent.com/70914017/191945801-18e759fd-4faf-40d1-81ad-de378c0ea247.png)

I want to set target temperature, but it does not work from iobroker. Only on the device i can set it.

What can i do? How can i see, what data can i write from zigbee.adapter to the device?

EDIT: When i set the target temperature to 19, the ibroker show me that the devicve has the 19. But it does not show on the display...it is possible, that it is the normal behavior?

**Comment by Asdoos** [comment]
I Have the same issue. Is there a way I can help?

**Comment by boriswerner** [comment]
I have the same valve and I can set the target temperature from iobroker without a problem. Maybe it has been fixed meanwhile? I run version 1.7.5 of the adapter.
