### ISSUE TITLE
New Tint

### ISSUE THREAD

**Issue by Bacado** [ioBroker/ioBroker.zigbee#1529]
Hello togther,

i buy the new Tint (MüllerLicht) by Aldi, if i want to pair it, i got the error: Device  0xa4c13800ac490396 "GU10 Withe+Color" not described in StatesMapping.. undefined

v1.7.5

Tint Produkt spez.: https://tool.mueller-licht.net/web/pdf/404005C.pdf

**Comment by arteck** [comment]
more infos plz

**Comment by Bacado** [comment]
Prod. Spez are on the PDF file!
