### ISSUE TITLE
Test before release 0.9.0

### ISSUE THREAD

**Issue by kirovilya** [ioBroker/ioBroker.zigbee#153]
Hi guys. @Apollon77 @arteck @allofmex @modmax 
You are the advanced users of this adapter.
Before the release of version 0.9.0, I am very concerned about the stability of the adapter. I do not have so many devices to test its operation, therefore, check on your test systems.
Also, the last of our changes mixed up and now it’s difficult for me to make sure that what you made was not lost among other changes.

Please see the current dev-branch. If critical problems are not revealed until Monday, we will be released.
Thank you!

**Comment by allofmex** [comment]
Device Info tab and Developer Tab currently not working, [https://github.com/ioBroker/ioBroker.zigbee/pull/154](https://github.com/ioBroker/ioBroker.zigbee/pull/154) should fix it.
Groups looks nice. Thanks.

**Comment by kirovilya** [comment]
@allofmex merged

**Comment by modmax** [comment]
Just installed it and the Zigbee devices still works as expected. I will watch this from now on.

Remarks:
1.) The label "Groups" is not translated; neither in the overview, nor if you edit a device.
2.) Firfox-Browser: The network map is not displayed full size, if you open it; just a part of it is shown.
See attachment. If you refresh the network map with the button in the right lower corner, then the network map is displayed. In Chrome its okay.
3.) Internet Explorer is completly out of scope; no devices and no network map is shown. Okay; it's not my favorite browser; just to be complete.  Also no tested with Opera or Safaru Browser.

![networkmap](https://user-images.githubusercontent.com/3912027/51341607-056ba980-1a92-11e9-9182-35af332cedb2.jpg)

**Comment by Apollon77** [comment]
Sorry I will be out beginning tomorrow morning till Sunday. I can not promise much testing time :-( will try Sunday evening.

**Comment by Apollon77** [comment]
BTW: I saw that group support is added now? How I can bring threee hue lamps together and define one group? Is this described somewhere?

**Comment by allofmex** [comment]
@Apollon77 
Groups is simple. Click Edit on device card and you will see. Is self explaining.

**Comment by kirovilya** [comment]
@Apollon77 https://www.youtube.com/watch?v=Jdioavy2ppQ Groups preview

**Comment by kirovilya** [comment]
@modmax Thank you for test.
1. Fixed by @allofmex
2. Fixed
3. I think iob not work with ie/edge :(

**Comment by modmax** [comment]
Next tests with groups, but at the moment I just have an OSRAM plug.

1.) Create and Delete a group
Creation works; but on delete the group is not deleted in objects.

2.) Create Group and assign to a device without storage
I create a Group "Test" with ID 1 on the group tab, but didn't store this via store button on buttom of adapter settings page. Then I added the group "Test" to the plug; activated it and stored the device. The device has now group "Test". But then I did not save the adapter settings. I close the zigbe adapter page; a confirmation pops up to discard changed and I choosed OK.
The result is, that the group is not created, but the device has a group; you can see it in the objects view, that the plug has group 1, but it's not displayed on the device page. Also the group is not stored in iobroker objects.

3.) Created Group Test2 with id 2, stored the adapter adapter and the instance will be restated. Then I set group of plug to 2 "Test2" and stored the device. Group is present in object and also device has group with id 2.
Then I changed "state" of group_2 to "true"; but the plug didn't switch. No error in logs
Or do groups only work for lamps?

4.) Now deleted group 2 (named "Test2" again). Now group is still present in objects view; also group is still present in objects view of plug. So I deleted the group_2 in objects view. 
Also I have to go to the device info page of plug; edit the plug and stored it without change. Then the groups was emptied and in objects view for groups is now an empty array (--> []) and not undefined or unset.

At least I can see 2 errors:
a.) If a group is created, then i's not enough just to store the group. You also must press the button on the bottom of the adapter page to really store the added groups.
b.) Groups are just deleted from adapter page; but not in iobroker objects (group and devices which have this group).

Best regards
Markus

**Comment by modmax** [comment]
Additionaly:
All zigbee devices now have a "groups" entry (objects view). 
I think groups make only sense for Router devices and no end devices. 

So end devices should not become such an object property; also the assignment of groups during editing of a device (where you can change the name) should not be possible.
Also some router device shouldn't have a groups property or the ability to set a group for; like a lumi router or perhaps OSRAM plug ... :-)

**Comment by modmax** [comment]
Last test for this evening; after deletimng all groups and association zo devices,
5.) Create a group named "Test" with ID 1; save it and the complete adapter settings.
Then create a new group and name it "Schalter" and set the same ID 1 for that group. Then the group will be renamed in the groupos view. Also the device has now the ne group name.
But in the objects view the group_1 sill has the name "Test".

**Comment by kirovilya** [comment]
@modmax I wanted to be able to change the groups and device names without restarting the adapter - so they change without saving the settings.
I can do so that a set of groups is also formed without confirming and restarting the adapter. then everything will well :)

I'm not sure yet, but for now the groups are supported only by lamps, but it seems to me that plugs/switches should also support them (I can't check).
Yes, it is necessary to make groups available only for routers (they can accept commands)

**Comment by allofmex** [comment]
Groups should be available for all end devices, because non-router may have writable attributes too. Example: Someone may want to set the timeouts on all motion sensors to a shorter value between  midnight and 6am than for the rest of the day.

**Comment by Apollon77** [comment]
Are groups realized via res zigbee groups or are they handled by the adapter and control the devices then sequential? I ask because i still saw delay in your group demo video. I was hoping that with real zigbee groups they are controlled more synchronously ;-)

**Comment by kirovilya** [comment]
@Apollon77 Groups are implemented using a zigby, not an adapter. One team is sent to the group! The fact that the lamps in the video light up is not synchronous, I blame the lamp manufacturers :) - they are all different.

**Comment by Apollon77** [comment]
Ok Great. This is exactly what I wanted to hear ;-)) great job. Will try to test 0.9 tonight (>22pm) and give feedback

**Comment by modmax** [comment]
@kirovilya 
I mentioned, that the newly created groups are just stored, if the adapter settings are stored and not independent.

@allofmex 
I'm not inside the internals of Zigbee; but I think that groups make only sense for routers; cause that is where you can group (i.e. lamps) together. Groups are implemented by using Zigbee groups, and is not a self made implementation by sending the same value to several devices (one write request for each device), where groups for end devices maybe make sense.
Have you tested grouping for end devices? I just have just Xiaomi sensors (weather, door, buttons) where I even cannot read any values with your developer tab, cause they are in sleep modus and just wakeup for sending.

**Comment by allofmex** [comment]
@modmax 
You are right, I didn't fully understood the groups.

If I try to read group info from hue motion sensor, I get `unsupClusterCmd` response. Could not manage to read group info from my router devices, but at least they respond with `notFound {"msg":{"status":139,"groupid":0,"groupname":""}}`

@kirovilya 
Plugs/switches should work out-of-the-box in current dev branch if they support groups right? I tested a osram plug, but it does not respond to changes on groups state object. It works for my bulbs. 

How must the raw zigbee request look like to, for example, read the group id from a device?
 `{"cid": "genGroups", "cmd": "view", "cmdType": "functional", ??? groupid ???}`

**Comment by modmax** [comment]
@kirovilya 
Tested now with latest changes.

1.) It seems that OSRAM lamps are not supporting this, even if this are Zigbee standards. Perhaps they only support it with ZLL. Create a new group 1 and added a a lamp to the group 1. Then the states occur in the group_1 section. But no command works and no errors in logs. It's just a group with one device; perhaps a groups must consist of 2 devices or more? Who knows ...

2.) Creating a group leads now to an immediate creating of the group. That's fixed.

3.) When deleting the group (in my example 1), then it will be delete on the adapter settings page. BUT the group ist still in the iobroker objects (zigbee.0.group_1 object still exists). Also the "groups" of the lamp still contains the id 1 of the group.

5.) What I saw, was also that creating a group, changing name of a device or using the developer tab (now called Analyse) leads to a marker to the adapter to store changes. Even if all changes are done immediatly. Perhaps there is something missing to tell the adapter that everything is fine and nothing has to be save, cause it has already been saved.

Best regards
Markus

**Comment by modmax** [comment]
@allofmex 
For reading values the request must always be "foundation". Functioning is fpr writing values.
If you choose foundation in your developer tab then you can choose the read attribute for your purposes.

**Comment by arteck** [comment]
Hi guys.... not had no time this weekend...i check this tonight..

**Comment by allofmex** [comment]
Ok, found the solution. Had to fix something in developer tabs routines. (inlcuded in next PR)
```
{"devId": x,
    "ep": y,
    "cid": "4", // genGroups
    "cmd": "0", // view
    "cmdType": "functional",
    "zclData": {
        "groupid": "2",
        "groupname": ""
    }}
```
I added device to group No 2 and tested view command with "groupid": 1-3:
```
notFound {"msg":{"status":139,"groupid":1,"groupname":""}}
success {"msg":{"status":0,"groupid":2,"groupname":""}}
notFound {"msg":{"status":139,"groupid":3,"groupname":""}}
```

Command = 0 //add, "groupid": 3
`success {"msg":{"status":0,"groupid":3,"groupname":""}}`
If I write to a groups object, the device that was manually added/removed to/from group responds. Very simple.

Tested the same on a OSRAM plug, group add/remove works.
The Hue motion sensor says `unsupClusterCmd`, so seems you where right, groups only on router (incl. plugs)

**Comment by kirovilya** [comment]
@allofmex I do not understand ... I do not correctly add the device to the group? Something needs to be corrected in the code for managing devices and groups?

**Comment by Apollon77** [comment]
I noted one thing. I enabled a lamp group by setting brightness. this also turns the device on. In the group the brightness value is updated, but state stays "false" ...

**Comment by kirovilya** [comment]
@arteck I added routers polling - now they will be polled every minute (so they won't fall asleep). This was necessary mainly for xiaomi plug - they behaved badly.
Therefore, sometimes there is a re-pairing of routers at restart.
I still have nothing to say about OSRAM - I do not know what is wrong with them.
The map displays the numbers obtained during the request of the map, and in the states of the objects numbers when receiving a signal from the device. They may differ, but should not be so drastically. Try to rebuild the map or wait until some signal comes.

**Comment by kirovilya** [comment]
@Apollon77 Yes, this is a problem that devices do not communicate their attributes when managing them through groups. Here you either need to force to request them, or learn how to configure them to send a report.

**Comment by Apollon77** [comment]
K, but should go into documentation for groups

**Comment by modmax** [comment]
@kirovilya 
1.) At the moment I would say, that it's under inspection, when OSRAM lamps in groups are not working.
If OSRAM plugs are not working it's also an issue, but I think that's no real problem and can be solved individually without groups. Further investigations are needed for that.

2,) Reading of devices values could be done. For #157 i've implemented a simple mechanism to read the response for a read request, when no event is emitted from the lamp; included in PR #162. That could be used perhaps.
But this has to be done for every device in the group. Also this should only be done if queuing is activated.

**Comment by modmax** [comment]
Also tested changes with latest release.
Groups are now not in end devices and end device cannot be in a group. OK. But I think some routers should also not have a groups states; like the LUMI.ROUTER ... could be perhaps set via a "groups: false" property in the device section of the LUMI.router in devstates.js.
Could also be used for OSRAM plugs ... :-)

**Comment by kirovilya** [comment]
@modmax Is your last experiment with the band really not working with OSRAM?
I thought that the parameters themselves are converted to the desired type when sending. If this is not the case, then here you can add a transformation to the whole and that's it. https://github.com/ioBroker/ioBroker.zigbee/blob/dev/lib/zigbeecontroller.js#L555

**Comment by kirovilya** [comment]
> LUMI.ROUTER ... could be perhaps set via a "groups: false" property in the device section of the LUMI.router in devstates.js.

The correct way is to analyze the clusters of the device and looking at them to understand whether it supports groups or not :)
But perhaps lumi.router is based on Samplelight firmware and it means it has the same clusters as a light bulb :)))
So even if he has the possibility of groups, he still will not be able to process the on / off command.

**Comment by kirovilya** [comment]
> Also I woul be glad if someone could explain me, how to merge changes in the iobroker.zigbee repo back into my repository. Until now I create pull request from iobroker.zigbee to me repository; but I think that there may be a better way ... :-)

https://help.github.com/articles/syncing-a-fork/

**Comment by Apollon77** [comment]
Re Offtopic syncing a fork: I'm more the rebase fan ;-)
https://de.atlassian.com/git/articles/git-team-workflows-merge-or-rebase
In fact comparable: 
```
                git fetch upstream
                git rebase upstream/master
                git push
```

**Comment by arteck** [comment]
from here is also allright OK. but i tested the groups only on dev system..
osram problem is known..
hmm..maybe we'll wait until the weekend..

**Comment by arteck** [comment]
double goups works also
but here a example with 3 hue bulbs
![grafik](https://user-images.githubusercontent.com/6681528/51593243-fd789300-1ef1-11e9-86c8-d2957584d09e.png)
the state is not synch

**Comment by allofmex** [comment]
Am updating the developer tab to support groups too.
Here one suggest:
Shouldn't the groupList be more organized like deviceList since the usage of groups is very similar to a device? (only difference is publish to 0x0000000000000005 (=groupId) instead of 0x90fd9ffffeda1234 (deviceId))

Currently:
Groups:
`{"4":"Bath","5":"test-light"}`

Devices:
```
[ {
    "type": "device",
    "_id": "zigbee.0.90fd9ffffeda1234",
    "info": {      "ieeeAddr": "0x90fd9ffffeda1234"    },
    "groups": [      "5"    ],
    "groupNames": "test-light"
  },
  {
    "type": "device",
    "_id": "zigbee.0.7cb03eaa00b21234",
    "info": {      "ieeeAddr": "0x7cb03eaa00b21234"    },
    "groups": [      "3"    ],
    "groupNames": ""
  } ]
```

I suggest that adapters groups object should look more like this:
```
[ {
    "type": "group",
    "groupid":"4",
    "groupName:"Bath",
},
{
   "type": "group",
   "groupid":"5",
   "groupName:"test-light",
} ]
```

**Comment by modmax** [comment]
@kirovilya 
Tested around with OSRAM plugs and bulbs; but those devices are not working with groups ... :-(
Even with changes that the groupId will be parsed as integer on every request, where a groupId is contained, changed nothing.
Ther must be a solution ... somewhere ... but right now I don't find it. Perhaps if @allofmex has built in the groups in the developer tab ... bu that may take a while ...

So in my opinion the V0.9 may start at the weekend; with the restriction to OSRAM devices (and perhaps other devices also) are not working together with groups ...
The groups, the developer tab, a more stable adapter are reasons enough for the next version ... and I think that arteck also has several enhancements to new devices if the dev branch has been merged to the master branch.

**Comment by kirovilya** [comment]
@modmax Can you chat with a user who has working groups with OSRAM? https://github.com/Koenkk/zigbee2mqtt/issues/764#issuecomment-456809689

**Comment by modmax** [comment]
Perhaps my error:
I think I have flashed the wrong firmware to my cc2530+cc2591 coordinator ... that was the one from ZStack master and not ZStack dev ... omg ...
I will reflash the coordinator now with the version vom 27.12.2018, do pairing ... again .. and see what happens ....

**Comment by kirovilya** [comment]
@modmax I think nothing will change :)

**Comment by Michaelnorge** [comment]
How to get v.0.9.0 ?

**Comment by modmax** [comment]
@kirovilya 
You we're completly wrong ... :-)
OSRAM bulbs  (must still test plugs) are working with groups. 2 changes had to be done: 

1.) parse the group id as integer; otherwise some OSRAM devices didn't recognize it correctly and answer with a "NO ACK". That's solved with PR #166.

2.) The big part is: The coordinator must be flashed with the latest DEV-version of the ZStack firmware from Koenkk:
https://github.com/Koenkk/Z-Stack-firmware/tree/dev

And it's really time wasting to flash the coordinator, cause this also means that you have to pair each device again. Also now you cannot delete router devices from the coordinator, cause they will be readded immediatly due changes according to the zigbee plug; so I had to reset the bulbs and plugs manually via an ioBroker skript and a Sonoff S20.
So if someone want's to use groups with OSRAM lamps, then there seems to be no other way right now.

**Comment by arteck** [comment]
@modmax 
we can flash the coordinator with software solution or not ?
@kirovilya I think we do not have to pair all devices with it.. right ??

**Comment by modmax** [comment]
I flashed the hex file from KoenkK from the dev branch. But for me I had to pair each device again; perhaps I made a mistake cause I always erase the cc2530 before programming. Also the paired devices are stored in the coordinator/router and I think flashing a new hex file will erase those bindings.

**Comment by kirovilya** [comment]
@modmax
1) approx. maybe that was the reason, but I'm not sure :)
2) and this is my mistake, I overlooked the changes in the firmware (I thought there they concerned only minor parameters), it turned out that the main parameter is:
```
// Disabling MULTICAST is required in order for proper group support.
// If MULTICAST is not disabled, the group adress is not included in the APS header
#define MULTICAST_ENABLED FALSE
```
I am saddened. This means everyone users should reflash the sticks: (

Will have to build the bin-file for firmware via serialboottool and write instructions for reflashing ...

**Comment by kirovilya** [comment]
@arteck After flash the firmware - you need to bind again: (

**Comment by Apollon77** [comment]
I use the dev version from 3 days ago already in production at home. works well with Hue devices and groups

**Comment by modmax** [comment]
@arteck 
The firmware version (dev fom koenkk) should be for all versions; but I think that this depends on the vendors if that works with or nor without that modification. Thats then call "vendor specific zigbee adjustments" ... :-)

So if your groups work, then there is no need for re-flashing. If they does not work (that was my case with Osram lamps), then reflashing is needed with the dev version from koenkk or any other firmware where the multicast is disabled.

**Comment by arteck** [comment]
@kirovilya 
 I'll have a look... it would be great.. without new pairing

**Comment by arteck** [comment]
fuxx it WORKS.. very very nice.. all Routers and Enddevices....

**Comment by kirovilya** [comment]
@arteck and groups with OSRAM?

**Comment by arteck** [comment]
with plugs nope

**Comment by kirovilya** [comment]
@arteck yes

**Comment by kirovilya** [comment]
@modmax @allofmex  can you check the attached firmware above to work with OSRAM?

**Comment by arteck** [comment]
groups for enddevices (temp or switch) do not make sense....
![grafik](https://user-images.githubusercontent.com/6681528/51750570-b8e82580-20b2-11e9-9039-d5af6165de16.png)

**Comment by kirovilya** [comment]
@arteck these states are left from the previous version, you can delete them

**Comment by arteck** [comment]
ahh ok

**Comment by modmax** [comment]
@kirovilya 
Tested it right now withj an OSRAM plug. It works, but with confusion.

1.) Added the plug to a group
Request done, but failed. BUT: The group is shown as added for the device.
Error was:
`
2019-01-25 15:56:51.893  - error:  zigbee.0 Zigbee publish to '0x84182600000f3511', genGroups - add -  {"groupid":1,"groupname":""} - 3 failed with error Error: AF data  request fails, status code: 233. MAC no ack.
--
2019-01-25 15:56:51.894  - error: zigbee.0 Failed to add device 0x84182600000f3511 to group 1. Error: AF data request fails, status code: 233. MAC no ack.
`

Needed to delete group from device and then added device to group again. This time no error occured.
And now the plugs works within groups (of course state only).
I think @arteck there was also an error in the log, so that the group has not been added.

I think something should be changed:
If the "group addition" leads to an error, then the group should not be added to the device in device list and object. Otherwise it can confuse the users, when the group is added and shown up in device, but does not work.

But on the other side with a NO ACK it's no guaranteed, that the device didn't process the request. I.e. for changing color on a lamp or switching the plug the request has been executed, but then a NO ACK occured for that device; even if everything went okay.

**Comment by arteck** [comment]
@modmax  you're right
![grafik](https://user-images.githubusercontent.com/6681528/51754460-a5da5300-20bc-11e9-88c5-b178c5d13b99.png)

**Comment by modmax** [comment]
@arteck
And when you delete and add the device again to the group?

**Comment by arteck** [comment]
groupe deleted from device
group deleted also
create new group 
add to device

nope not wroks

**Comment by modmax** [comment]
And this time there has been no error?

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/51754724-56e0ed80-20bd-11e9-8f0e-e1d70a1e50b3.png)

**Comment by modmax** [comment]
Confusing ... but i'm using the DEV firmware from Koenkk.

@kirovilya 
Are there any changes between those firmware and your firmware for the SerialBootTool?
I have no test setupo right now ... so that I cannot test at the moment the flashing with serial boot tool, from old firmware to new firmware.

**Comment by arteck** [comment]
next test 
del device 
del group

add device 
create new group
add device to group
![grafik](https://user-images.githubusercontent.com/6681528/51755939-146ce000-20c0-11e9-93c2-73b5edadd85f.png)

**Comment by modmax** [comment]
Group name is optional ...
Are you using the latest DEV version from the Zigbee Adapter?
Tested addition of device to group without deleting the group before?

**Comment by arteck** [comment]
> Group name is optional ...    
i know and i have a group name

> Are you using the latest DEV version from the Zigbee Adapter?
yes

> Tested addition of device to group without deleting the group befor
yes..

**Comment by kirovilya** [comment]
@modmax 
> Are there any changes between those firmware and your firmware for the SerialBootTool?

I think no. I got last dev firmware patch and build firmware for SBL

**Comment by modmax** [comment]
Only thing it could perhaps be is the firmware of the plug itself ...

**Comment by kirovilya** [comment]
Or the firmware via SBT does not completely replace the existing firmware :)
Another assumption:
Adding groups occurs until the device is re-pairing, so messages may not reach.
Groups are synchronized when the adapter starts. If @arteck add a group after a successful launch without restarting the adapter, will there be an error?

**Comment by allofmex** [comment]
Updated firmware to 2.6.3 rev 20181224 and zigbee adapter to dev version of today. Adapter upload/restart.

Bulbs (ikea, osram, philips), Eurotronics Thermostat and osram plug worked without re-pair. Only hue motion sensor needed a setup-button push (but no full reset), before "status code: 183. APS no ack".

But said to say, the **groups still don't work for osram**. Exact same behavior as older version (20180815). Group is set/deleted but no response to commands.

**Comment by modmax** [comment]
@allofmex 
You have used the SBT for flashing right?
In opposite I dif a full reflash of the firmware with complete erasing the coordinator and therefore also my cc2530 router ... bulbs and lamps reset manually per script (5x on/off) .. and then paired each device again. Took about 2 hours for 15 devices ...,
But now groups are working ... and that all for OSRAM devices ... :hankey:

**Comment by arteck** [comment]
i have tommorow many errors here.. nothing work
![grafik](https://user-images.githubusercontent.com/6681528/51785263-69a70100-2155-11e9-8c21-3b0d42f7d710.png)

**Comment by arteck** [comment]
2 hours later all my devices are offline..

**Comment by kirovilya** [comment]
@arteck :( restart adapter not help?
internal buffers may be filled. only full reflash...

**Comment by arteck** [comment]
Adapter restart not.. but reboot.. then is the buffer empty.. and run 2 hours...
fuXX 
also new flash and receonnct all devices... lets go...

**Comment by arteck** [comment]
done.. all devices are connect with new firmware..

**Comment by kirovilya** [comment]
@arteck This is bad news... 
I do not know if it will help, but you can try the coordinator’s soft reset. if it helps, then add regular execution. https://github.com/ioBroker/ioBroker.zigbee/blob/dev/lib/zigbeecontroller.js#L103

**Comment by arteck** [comment]
i check this .. how long the coordinator works.. without reset..  the last stand is 2 hours.. this is not acceptable..

**Comment by kirovilya** [comment]
You can also test previous version 0.8.0 of adapter...

**Comment by allofmex** [comment]
Added reset button to adapter interface. [https://github.com/ioBroker/ioBroker.zigbee/pull/170](https://github.com/ioBroker/ioBroker.zigbee/pull/170) Hope it helps.

Hard reset left all my devices as unpaired (icon in device tabs). So far as expected. But I just had to start pairing mode in adapter and they all paired themselfs (after simple power reset). No device reset or even pairing button press on device needed. Is this correct behavior? Or is shepherds hard reset not a real/full reset!

**Comment by allofmex** [comment]
Sadly the hard reset does not change anything for OSRAM groups

> You have used the SBT for flashing right?

Yes, updated via SerialBootTool. I do not have a debugger for flashing manually. Is there any way to fully reset the CC2531 without debugger and without erasing the firmware itself?

**Comment by modmax** [comment]
@arteck 
have you erased the cc2531 and flashed the DEV firmware via CC debugger?
I've done so and it works since 6 days. No problems with it.

On first start of zigbee adapter after flashing new firmware there was also a request timeout for shepherd, but after a restart of the instance it worked. Deleted the shepherd.db in zigbee_0 directory before restart; shouldn't have an impact but just mentioned to be complete.

@allofmex 
Sorry, I've no idea how that could be done.

**Comment by arteck** [comment]
24 hours works... after first day problem... strange very strange... 
but it is running now... :-)

**Comment by arteck** [comment]
so far publish 0.0.9 ??

**Comment by allofmex** [comment]
No serious issues on my side anymore. Go for 0.9.0...

**Comment by kirovilya** [comment]
@arteck Do you have any added devices that are not included in 0.9.0 devstates.js, but which you can transfer there?

Okay guys, we'll be released tonight

**Comment by kirovilya** [comment]
Who can describe new features in the readme? I have weak English :)

**Comment by allofmex** [comment]
> Who can describe new features in the readme

I can do it. 

- Groups
- DeveloperTab

Anything else?

**Comment by Apollon77** [comment]
All the new devices from @arteck?

**Comment by kirovilya** [comment]
build failed :(

**Comment by arteck** [comment]
i can add the new devices manually .. if that helps you..

**Comment by kirovilya** [comment]
I found

**Comment by kirovilya** [comment]
fixed

**Comment by kirovilya** [comment]
Thanks guys, version 0.9 is published.
I hope that we will continue next time.
Thanks again!

Now it's time to catch bugs from the user :)
