### ISSUE TITLE
NEW Aqara Thermostat E1...is not recognized correctly in iobroker

### ISSUE THREAD

**Issue by rmp63526** [ioBroker/ioBroker.zigbee#1531]
Hello, I can pair the Aqara E1 thermostat in iobroker with no problems. However, it is recognized correctly and the objects are not created. Is there something i can do?

Thanks

![1Unbenannt](https://user-images.githubusercontent.com/65367883/193096839-008960ed-f8de-4215-aec0-a6ea2665a45f.PNG)
![6Unbenannt](https://user-images.githubusercontent.com/65367883/193096955-3855c224-1211-4415-8437-667cfba7a9ee.PNG)

![4Unbenannt](https://user-images.githubusercontent.com/65367883/193096978-d9ebc9cb-f955-4147-a89a-9c1673be24b4.PNG)

![5Unbenannt](https://user-images.githubusercontent.com/65367883/193097162-c2e2e9c6-6b14-4d48-940b-ff9bd0a6abf9.PNG)

**Comment by asgothian** [comment]
Please read here:
https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised

**Comment by rmp63526** [comment]
Okay thank you.
I only understand Bahnhof :-)
Am i correct, i have to insert the device myself? Because i am pretty sure the device is compatible with iobroker.zigbee. According the zigbee blakadder homepage.

**Comment by asgothian** [comment]
No, you are not required to import the device yourself. You are, however, advised to follow the procedure outlined under the cheat sheet - go through this as far as you are comfortable to do and fill out the cheat sheet while you do so. The results may help with getting the device to run.

It is common that devices get new device identifiers which need to be added to the software. This is done on a regular basis, so it is not unlikely that you are currently running an older version of the software.

**Comment by rmp63526** [comment]
Sorry, that is to high for me :-)
I have read the "How to use the cheat sheet" but i dont know where to start.

**Comment by Floh22964** [comment]
rmp63526  hatte das gleiche Problem, update da Adapter auf 1.76 dann funktioniert alles

**Comment by rmp63526** [comment]
Danke, gut zu wissen.
Wird bei mir noch nicht im stable angezeigt.
Gruß

**Comment by duejo46** [comment]
@Floh22964 
Habe das cheat von @asgothian gelesen. Danach von V1.7.5 aus stable repo auf V1.7.6 aus iob beta repo 
Dev wird weiterhin nicht korrekt erkannt, Verhalten wie oben beschrieben
zhc ist 14.0.655 bei mir
Welche Version zhc hast Du? Aktuell gibt es wohl 14.0.660. Kann das die Ursache sein?
Danke.

**Comment by Floh22964** [comment]
Ich habe keinen blassen Schimmer was zhc sein soll.

Ich habe einfach über die Katze den GITHUB Pfad genommen und Zigbee auf 1.7.6 geupdatet und dann hat es sofort funktioniert.
Natürlich musst Du einmal das Device löschen und neu pairen, dann ging es sofort

**Comment by duejo46** [comment]
Danke für Deinen Kommentar, zhc ist der zigbee-herdsman-converter
Ich hatte V1.7.6 aus den iob beta repo installiert, das Thermostat wurde nicht korrekt erkannt.
Nach Deiner Info habe ich das Device gelöscht und die Instanz durchgestartet, danach über Github V1.7.6 drüberinstalliert (was ich eigentlich nicht tun wollte...) und erneut durchgestartet
Device gepairt und siehe da...erkannt und Datenpunkte angelegt, wie Du sagtest!!
Ich vermute, dass es in der V1.7.6 unterschiedliche Entwicklungsstände gibt, auf github aktueller als auf beta-repo. Dies könnte mit der Version des zhc zusammenhängen. Dies ist aber wirklich nur meine Vermutung, da habe ich definitiv viel zu wenig Ahnung von der Sache. Vielleicht erklärt uns das ja noch ein Experte.
Morgen schau ich mir mal die Funktionalitäten an. Danke nochmal und gute Nacht.

**Comment by rmp63526** [comment]
Bei mir funktioniert das Gerät weiterhin nicht, auch unter Version 1.7.6.

Habe das gerät aus zigbee gelöscht und anschließen neu angelernt. Habe nachdem er das Gerät wieder erkannt hat auf Upload gedrückt wie es einer in #1557 beschrieben hatte , aber weiter ohne Erfolg! Schade!
