### ISSUE TITLE
OSram Steckdosen 

### ISSUE THREAD

**Issue by mymeyer** [ioBroker/ioBroker.zigbee#1533]
Hallo, bekomme beim Start von dem Adapter diese Meldung. 

zigbee.0 | 2022-10-03 19:02:40.343 | warn | DeviceAvailability:Failed to ping 0x7cb03eaa0a0882f0 Plug 01
-- | -- | -- | --
zigbee.0 | 2022-10-03 19:02:27.447 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x0017880108653d40 SML001 (Error: Bind 0x0017880108653d40/2 genPowerCfg from '0x00124b0025c520c7/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7))

Die Steckdose lief tagelang und nun kommt diese Meldung obwohl ich nicht geändert habe. Was ist hier das Problem ?
OSRAM Model: AB3257001NJ

Gruß
MyMeyer

**Comment by arteck** [comment]
> Was ist hier das Problem ?

der plug ist das Problem.. die dinger taugen nix .. würde dir empfehlen auf andere zu wechseln ikea, blitzwolf, aqara oder oder

nur nicht Ledvance oder Osram die machen probleme
