### ISSUE TITLE
can´t connect IKEA TRADFRI remote control E1524_E1810

### ISSUE THREAD

**Issue by AliBabaBinLaden** [ioBroker/ioBroker.zigbee#1536]
i have an issue with the tradfri remote control.
If i try to pair it always only find a unknow device. But in the past it works perfektly. I dont know if its about the newest adapter version.

`Interview started: 0x84fd27fffe246c2e`
`Error: Failed to interview '0x84fd27fffe246c2e', device has not succesfully been paired. undefined. undefined`

on the undefines device i can read:

![image](https://user-images.githubusercontent.com/45460440/194392993-9ef4ddfb-8995-4a84-80a7-9b67619522e9.png)

type:Unknown
nwk:36425
interviewed:false
configured:false

In my IoBroker installation all adapters ar in the newest version.

**Comment by AliBabaBinLaden** [comment]
could no one help me with this issue?

**Comment by Wannseesprinter** [comment]
I also have a few devices from Ikea in use and can say that Ikea devices are sometimes not so comfortable to integrate here. Often it brings something to completely delete the device from the Zigbee adapter and perform the pairing very close to the next device to the zigbee network. With my Ikea Shortcut Buttons this path has led me to my goal.

**Comment by AliBabaBinLaden** [comment]
I've tried that many times without success. I also got a second switch, but I don't want it either. It's just funny that it worked before.

**Comment by AliBabaBinLaden** [comment]
a friend of me tried ms switch on his own iobroker system without problems. So the problem must be in my instellation. What can i do? Can i find some old files they i have to delete?
