### ISSUE TITLE
Develco SPLZB-131 Plug (Steckdose)

### ISSUE THREAD

**Issue by HerbertJoos** [ioBroker/ioBroker.zigbee#1538]
Hallo, 
ich habe oben genannte Steckdose verbunden. Alles schien super zu funktionieren. Alle 5 Sekunden kommen Daten am ioBroker an (ZigBee Adapter). Bis ich festgestellt habe dass der Wert "energy" (kWh) nicht ankommt. Da kann man Strom verbrauchen wie man will, da kommt keine Aktualisierung. Erst wenn ich den Ein/Aus Schalter an der Steckdose betätige kann es sein, dass der aktuelle Wert übertragen wird. Oder wenn die Steckdose neu eingesteckt wird und wieder verbunden ist. Danach ist aber wieder nichts los mit "energy". Dann habe ich sie durch eine neue ausgetauscht. Leider dasselbe Spiel. Obwohl dieser Stecker mit dem Adapter (via ConBee II Stick) kompatibel sein soll. 
Hat jemand ebenfalls dieses Gerät oder kennt eine Lösung? Gehts es mit einem anderen Adapter (MQTT)? 
Gibt eine andere gute Steckdose mit Strommessung (Erfahrung)?

https://www.zigbee2mqtt.io/devices/SPLZB-131.html
https://zigbee.blakadder.com/Develco_SPLZB-131.html

**Comment by arteck** [comment]
das ist ein converter problem..wir bekommen die Daten und zeigen die nur

welche adapterversion ?
