### ISSUE TITLE
Bosch Smart Home Thermostat II

### ISSUE THREAD

**Issue by n3ucr0n** [ioBroker/ioBroker.zigbee#1540]
Hallo,

Ich versuche das Bosch Smart Home Thermostat II welches über Zigbee 3.0 verfügt mittels des Zigbee Adapters und dem Ti-Board zu koppeln.

Das Thermostat wird im Pairingmode auch erkannt und das Interview startet.
Nach einigen Sekunden kommt jedoch immer die Meldung, dass das Koppeln fehlgeschlagen sei.

Kann das da dran liegen, dass der Adapter dieses Gerät noch nicht beherrscht?

gibt es eine Möglichkeit, das Thermostat in Betrieb zu nehmen?

Danke und liebe Grüße

**Comment by arteck** [comment]
> Kann das da dran liegen, dass der Adapter dieses Gerät noch nicht beherrscht?

nö zigbee ist zigbee... das Gerät muss sich falls es den standart beherrscht anmelden ..ob man es dann steuern kann ist was anderes

**Comment by Garfonso** [comment]
Es scheint bei den Bosch Geräten eine Besonderheit zu geben: https://github.com/Koenkk/zigbee2mqtt/issues/13069
https://github.com/Koenkk/zigbee2mqtt/issues/13520

Irgendwie wurde da wohl was für implementiert in zigbee2mqtt / HomeAssistant... https://github.com/Koenkk/zigbee2mqtt/issues/13520#issuecomment-1230662569

Das scheint Teil des zigbee Standards zu sein... install codes für bestimmte Geräte, womit die Verbindung zu denen verschlüsselt ist. :-/

**Comment by Garfonso** [comment]
This is still an issue.

**Comment by Garfonso** [comment]
Ok, hab den Knopf gefunden. Wenn man da den komischen Code reinkopiert scheint es zu gehen (aber vorher das undefined Gerät löschen, sonst passieren komische Dinge... hm)

![Screenshot_1](https://github.com/ioBroker/ioBroker.zigbee/assets/620860/4a7a42c5-7c17-4499-a10d-947e5106cc35)

**Comment by austrogaucho** [comment]
geht wunderbar, kann ich auch bestätigen, hab grad mein erstes Bosch Thermostat eingebunden - endlich ein zigbee-Thermostat dass sich wirklich wunderbar einbinden und auch steuern lässt @arteck grosses Kompliment für deinen Einsatz!
