### ISSUE TITLE
ConBeeII & GL-MC-001 not succesfully paired

### ISSUE THREAD

**Issue by Pendora2017** [ioBroker/ioBroker.zigbee#1541]
Hallo liebe Leute, ich habe ein Problem beim Verbinden zwischen einem ConBeeII Stick und einem Gledopto GL-MC-001 LED Streifen.

Wenn ich das über den ConBeeII Stick pairen möchte, kommt immer folgende Meldung:
2022-10-08 17:44:57.218  - [31merror[39m: zigbee.1 (2158) Failed to interview '0x00124b0023a4bc67', device has not succesfully been paired. undefined

Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":88,"maintrel":0,"revision":"0x26580700"}}

Bei Verbindung über einen älteren CC2531 Stick funktioniert es sofort:
<html><body>

zigbee.0 | 2022-10-08 19:24:27.010 | info | Zigbee: stop joining
-- | -- | -- | --
zigbee.0 | 2022-10-08 19:24:24.377 | info | DeviceConfigure successful 0x00124b0023a4bc67 GL-MC-001
zigbee.0 | 2022-10-08 19:24:23.273 | info | Configuring 0x00124b0023a4bc67 GL-MC-001
zigbee.0 | 2022-10-08 19:24:23.269 | info | Device '0x00124b0023a4bc67' is supported, identified as: Gledopto Zigbee USB Mini LED Controller RGB+CCT (Gledopto)
zigbee.0 | 2022-10-08 19:24:23.268 | info | Successfully interviewed '0x00124b0023a4bc67', device has succesfully been paired
zigbee.0 | 2022-10-08 19:23:39.738 | warn | Device '0x00124b0023a4bc67' announced itself
zigbee.0 | 2022-10-08 19:23:39.722 | warn | Device '0x00124b0023a4bc67' announced itself
zigbee.0 | 2022-10-08 19:23:39.095 | info | Starting interview of '0x00124b0023a4bc67'
zigbee.0 | 2022-10-08 19:23:25.730 | info | Zigbee: allowing new devices to join.

</body>
</html>

Ich vermute, dass der ConBeeII und der Gledopto nicht kompatibel sind.
Hat hier vielleicht jemand Erfahrungen mit?

**Comment by arteck** [comment]
> Ich vermute, dass der ConBeeII und der Gledopto nicht kompatibel sind.

eher nicht..

check mal die firmwareversion von ConBee..evtl die updaten

**Comment by Pendora2017** [comment]
Leider nicht kompatibel. 
Sehr schade, da doch eine Menge günstigere LED Streifen mit genau diesem Adapter auf dem Markt sind.
