### ISSUE TITLE
IKEA ICPSHC24-30EU-IL-1 is marked as unsupported device

### ISSUE THREAD

**Issue by danickel** [ioBroker/ioBroker.zigbee#1542]
IKEA IKEA ICPSHC24-30EU-IL-1 is marked as unsupported device. 

Following error message appears when trying to pair: 
"Failed to interview '0xb4e3f9fffe8eb6f5', device has not succesfully been paired. undefined"

Also this message:
"0xb4e3f9fffe8eb6f5 (addr 29600): Not supported (model undefined)(Unknown)"

Zigbee2MQTT project supports the device:
https://www.zigbee2mqtt.io/devices/ICPSHC24-30EU-IL-1.html#ota-updates
https://github.com/Koenkk/zigbee2mqtt/issues/10550#issuecomment-1272590845

Used zigbee adapter version 1.7.6.

**Comment by arteck** [comment]
undefined is you problem not the device..

try again.. wehen not..try again.. you must see the name of the device

**Comment by danickel** [comment]
Can you explain that in more detail? Before I created this issue I tried it around 10 times. Everytime the same result...
Other devices like Aqara Door Sensors or IKEA plugs are working properly and are detected normally and directly.

So what should be wrong here from my side?
