### ISSUE TITLE
add TuYa TS0601 human presence sensor

### ISSUE THREAD

**Issue by jniclas** [ioBroker/ioBroker.zigbee#1543]
Can we add the tuya mmWave human presence sensor?
It is supported by zigbee2mqtt https://www.zigbee2mqtt.io/devices/TS0601_human_presence_sensor.html
Found the configuration here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/9379ccbad81a2087097ca3141ef572f6660f9487/devices/tuya.js#L3390
Was added there on 26. Aug 2022 with the commit https://github.com/Koenkk/zigbee-herdsman-converters/commit/35caf089d0b7abfa939319fe2883e64fceff25c3

**Comment by arteck** [comment]
install git version
