### ISSUE TITLE
Add new device from Zigbee2MQTT DEV branch

### ISSUE THREAD

**Issue by niceddes** [ioBroker/ioBroker.zigbee#1546]
Hi, can anybody help me(give advice) to add this device that i can use it with zigbee in iobroker? 

It was already added to the zigbee2mqtt DEV branch but i don´t know how ich can use it with iobroker?

See here...
https://github.com/Koenkk/zigbee2mqtt/issues/14415

Thank you very much in advance. BR

**Comment by arteck** [comment]
done
