### ISSUE TITLE
Switch a group but not a single device

### ISSUE THREAD

**Issue by zoulhh** [ioBroker/ioBroker.zigbee#1547]
Hi,

I have some light spots which I definded a group for. I can switch the group on and off but not the single spots. Also I get lots of error for a spot.

```
gbee.0 | 2216 | 2022-10-18 05:54:35.851 | error | Send command to 0xc498860000069a76 failed with no error code (no response received)
zigbee.0 | 2216 | 2022-10-18 05:54:33.850 | error | Send command to 0xc498860000069a76 failed with no error code (no response received)
zigbee.0 | 2216 | 2022-10-18 05:54:30.849 | error | Send command to 0xc498860000069a76 failed with no error code (no response received)
zigbee.0 | 2216 | 2022-10-18 05:54:26.848 | error | Send command to 0xc498860000069a76 failed with no error code (no response received)
```

I wonder, why it works fine with the group but not "Stand alone".

Pi 4, 8GB
Zigbee 1.7.6 (and 1.7.5, I installed the beta hoping that helps but didn't)
spot is INNR GU10 RS 227 T Spot. Dimmable no colors.

mod edit: code tags

**Comment by zoulhh** [comment]
"Synchronisationsversuch der Device-States mit dem Gruppen-State wenn von der Gruppe aus geschaltet wird."

sollte funktionieren. Tut es aber nicht. Warum?

**Comment by arteck** [comment]
which coordinator ?
and check.. del the group, create new one, add the device.. and check now

**Comment by asgothian** [comment]
> "Synchronisationsversuch der Device-States mit dem Gruppen-State wenn von der Gruppe aus geschaltet wird."
> 
> sollte funktionieren. Tut es aber nicht. Warum?

Das steht oben in deinen Fehlermeldungen. Die Leuchte schafft es nicht eine Antwort zu senden (no response received). Es scheint also so zu sein das dein Funknetzwerk zwar (ggf. so gerade) stark genug ist einen Befehl zur Lampe zu senden, das aber die Antwort der Lampe wegen mangelnder Sendeleistung nicht wieder beim Koordinator ankommt. Das ist im Übrigen auch der Grund warum das einschalten per Gruppe geht - dieses findet vom Koordinator aus via Broadcast statt und findet immer ohne Rückmeldung der Geräte statt.

Sofern du ein stabiles Mesh hast kann es von Vorteil sein die Sendeleistung des Koordinators zu verringern, damit die Lampen sauber auf Mesh-Routing umstellen, anstatt zu versuchen den Koordinator direkt anzufunken.

A.

**Comment by zoulhh** [comment]
> Sofern du ein stabiles Mesh hast kann es von Vorteil sein die Sendeleistung des Koordinators zu verringern, damit die Lampen sauber auf Mesh-Routing umstellen, anstatt zu versuchen den Koordinator direkt anzufunken.

Danke für Deine ausführliche Erklärung. Nachdem ich nun noch mehr Zigbee Geräte habe und der Pi zentraler steht, scheint alles gut zu laufen. Danke nochmals.

LGM
