### ISSUE TITLE
[QUESTION] Transfer an already existing network from Zigbee2MQTT to ioBroker.zigbee

### ISSUE THREAD

**Issue by Z18Aplha** [ioBroker/ioBroker.zigbee#1552]
I have an already running zigbee network with zigbee2mqtt but i would like to use this adapter because its much better integrated than the mqtt protocol (always JSON.parse to get value etc.).

Is there a way to use the adapter without pairing all my devices again. It would be painful because i have 70 devices.

What I've already done:
- The adapter Settings (PAN ID, Transport Key etc.) already match the settings i made in zigbee2mqtt
- Dongle connected

The error message from the adapter is 
```
Starting zigbee-herdsman problem : "network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby"
```
This means, that the dongle is accepted (no discrepancies between adapter config and coordinator config), right? 
At least the coordinator tries to deploy the network and of course a _'network with the same panId or extendedPanId already exists nearby_', because my routers are online.
It would be possible to shut off all my routers but for my understanding this does not solve the problem, because i would expect, the adapter does not complain about an "already existing network", because this is the network i want to keep!

Zigbee2mqtt provides a "coordinator_backup" and a database backup. Is it possible (and if yes, how) to transfer my already existing zigbee network to this adapter?

**Comment by Apollon77** [comment]
There is also brand new https://github.com/o0shojo0o/ioBroker.zigbee2mqtt ... maybe an easier migration path?

**Comment by Z18Aplha** [comment]
Thank you @Apollon77. This is exactly what i was searching for. I don't know how i could miss this adapter.
