### ISSUE TITLE
TuYa TS0505B E27 Lamp

### ISSUE THREAD

**Issue by larryxxl2** [ioBroker/ioBroker.zigbee#1554]
no configuration. no on /off . No Color Temp.

TuYa TS0505B](https://www.zigbee2mqtt.io/devices/TS0505B.html)

![Unbenannt](https://user-images.githubusercontent.com/96195330/198363421-acacd3e8-3b77-4ad8-8af4-7dbc97632179.jpg)

**Comment by arteck** [comment]
????????????????????????????????????

**Comment by larryxxl2** [comment]
![1](https://user-images.githubusercontent.com/96195330/204528084-6794418c-e6b5-4862-b9fe-f06e8276816f.jpg)
![2](https://user-images.githubusercontent.com/96195330/204528139-ff079163-bdee-4596-88ba-136e1dc86778.jpg)

**Comment by larryxxl2** [comment]
![3](https://user-images.githubusercontent.com/96195330/204529452-b99051f9-b234-4894-ae03-3a39b4a3b83f.jpg)
