### ISSUE TITLE
(ger) Sanfter Farbübergang bei Farbwechsel

### ISSUE THREAD

**Issue by Troox73** [ioBroker/ioBroker.zigbee#1555]
Hallo, erstmal danke für den Zigbee Adapter :) Ich arbeite mich gerade ein in dieses Umfeld. Mein ioBroker ist vom Pi4 auf einen x64 Proxmox Server umgezogen mit einem ConbeeII Stick im LXC Container. Läuft!
Nun zur Frage... Die Datenpunkte gestalten sich ein wenig anders, somit mußte ich meine Scripts anpassen.

#994 

hier wurde meine Frage zum Farbwechsel beantwortet. Mit SendToDevice {"color":{"x":0.5085, "y":0.4152}} erreiche ich das gewünschte Ergebniss. Nur eins "stört" mich, der farbwechsel ist hart (direkte umschaltung zur gewünschten Farbe) - nicht so "sanft" wie ich es von der Deconz Ansteuerung kenne. Gibt es eine möglichkeit den Farbwechsel smooth zu gestalten? Danke!

**Comment by arteck** [comment]
was steht in der transition_time ??
