### ISSUE TITLE
New Type Radiator Thermostat Aqara E1 (announced as lumi.airrtc.agl001 in iobroker)

### ISSUE THREAD

**Issue by jocjan** [ioBroker/ioBroker.zigbee#1557]
I've got a new zigbee device wich is called "Aqara smart Radiator Thermostat E1"

Message in Logs

zigbee.0 | 2022-10-31 14:48:32.544 | warn | Device '0x54ef4410005bb92b' announced itself
zigbee.0 | 2022-10-31 14:48:23.493 | error | Device 0x54ef4410005bb92b "lumi.airrtc.agl001" not described in statesMapping.
zigbee.0 | 2022-10-31 14:48:23.397 | info | 0x54ef4410005bb92b (addr 5086): Not supported (model lumi.airrtc.agl001)(EndDevice)

**Comment by Floh22964** [comment]
jocjan Du musst auf die 1.76 updaten dann funktioniert das Thermostat

**Comment by jocjan** [comment]
1.7.6 per npm installiert
Adaptern zeigt an
Installierte Instanzen: 1
Verfügbare Version: 1.7.5
Installierte Version: 1.7.6

Zigbee Adapter sagt mir in den Einstellungen weiter 1.7.5

Log
zigbee.0 | 2022-11-04 15:23:57.647 | info | Installed Version: iobroker.zigbee@1.7.5
zigbee.0 | 2022-11-04 15:23:57.491 | info | Starting Zigbee npm ...
zigbee.0 | 2022-11-04 15:23:57.490 | info | delete old Backup files. keep only last 10
zigbee.0 | 2022-11-04 15:23:57.463 | info | starting. Version 1.7.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.21.0, js-controller: 4.0.23
zigbee.0 | 2022-11-04 15:23:57.405 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

Thermostat wird weiter nicht angezeigt
zigbee.0 | 2022-11-04 15:23:58.095 | error | Device 0x54ef4410005bb92b "lumi.airrtc.agl001" not described in statesMapping.

Danke für die Hilfe.

**Comment by jocjan** [comment]
Nach einem iobroker upload zigbee folgende Anzeigen:
Installierte Instanzen: 1
Verfügbare Version: 1.7.5
Installierte Version: 1.7.6

Zigbee Adapter sagt mir in den Einstellungen nun  1.7.6

Log
Log
zigbee.0 | 2022-11-04 15:23:57.647 | info | Installed Version: undefined
zigbee.0 | 2022-11-04 15:23:57.491 | info | Starting Zigbee npm ...
zigbee.0 | 2022-11-04 15:23:57.490 | info | delete old Backup files. keep only last 10
zigbee.0 | 2022-11-04 15:23:57.463 | info | starting. Version 1.7.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.21.0, js-controller: 4.0.23

zigbee.0 | 2022-11-04 16:18:14.827 | error | Device 0x54ef4410005bb92b "lumi.airrtc.agl001" not described in statesMapping.




</body>
</html>

**Comment by duejo46** [comment]
I´ve installed V1.7.6 from iob beta repo
Dev "lumi.airrtc.agl001" has paired, but not correctly recognized
Log:
DeviceConfigure:Failed to DeviceConfigure.configure 0x54ef44100057b8dc lumi.airrtc.agl001 (TypeError: Cannot read properties of null (reading 'configure') at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:146:32) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Promise.all (index 0) at Commands.reconfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:483:21))
Can anybody help?
Thx in advance

**Comment by Floh22964** [comment]
Ich habe nicht per NPM installiert, sondern über den GITHUB Pfad, danach hat es sofort funktioniert bei mir.

**Comment by duejo46** [comment]
Es funktioniert mit V1.7.6 aus github, nicht aus beta repo, siehe auch #1531
