### ISSUE TITLE
929003054601 Phillip Hue Ceiling light not working

### ISSUE THREAD

**Issue by lombardi-zz** [ioBroker/ioBroker.zigbee#1559]
After adjust the devices.js the I'm able to add the device but there is no working.

**Comment by arteck** [comment]
with whitch adapter version ? new 1.8.7 also not ?

**Comment by lombardi-zz** [comment]
Of course, the latest one. I got it work. My issue was to enhance the wrong device.js.

**Comment by asgothian** [comment]
Please provide more information:

- how was the light acting / reacting before you changed the file
- Which file did you change (full path, not just name)
- what exactly did you change
- how does the change improve the support of the device

A.
