### ISSUE TITLE
Tradfri Dimmer on 0.8/0.9

### ISSUE THREAD

**Issue by thps1990** [ioBroker/ioBroker.zigbee#156]
Hello folks,

i tryed to add a TRADFRI Wireless Dimmer. The pairing suceeds, the device is recognized as 
TRADFRI wireless dimmer, but the icon is just the "?" and  no usefull objekt is created.

i tested it on 0.8 and 0.9 but theres no chance to get it work.

Are there any ideas, how to fix it?

greetz

**Comment by kirovilya** [comment]
Hi. You can try the dev-version from https://github.com/ioBroker/ioBroker.zigbee/tarball/dev
but make a backup just in case :)

**Comment by thps1990** [comment]
i already tested the dev version. the same issue, but the pairing is faster

Am 18.01.2019 19:57 schrieb Илья Киров <notifications@github.com>:

Hi. You can try the dev-version from https://github.com/ioBroker/ioBroker.zigbee/tarball/dev
but make a backup just in case :)

**Comment by kirovilya** [comment]
I am add this device today. And do upload after install from GitHub.

**Comment by thps1990** [comment]
Ah wow today 😁. I will try later and give you a response.
Thanks a lot

Am 18.01.2019 20:35 schrieb Илья Киров <notifications@github.com>:

I am add this device today. And do upload after install from GitHub.

**Comment by kirovilya** [comment]
@thps1990 I do not see the pictures
Have you do an **upload** after installing from a github?

**Comment by thps1990** [comment]
Mmh what do you mean with Upload?
I Just installed  it from github and restart the instance

Am 20.01.2019 08:59 schrieb Илья Киров <notifications@github.com>:

@thps1990<https://github.com/thps1990> I do not see the pictures
Have you do an upload after installing from a github?

**Comment by kirovilya** [comment]
I mean this button (available in expert mode)
![image](https://user-images.githubusercontent.com/8360230/51436911-c6627180-1ca6-11e9-8b8e-c49e2ce4a3b0.png)

**Comment by thps1990** [comment]
Ah ok, i never pushed this before :)

now i get this dimmer working, but its not usable. I dont  think that you could do anything for me at this point. This dimmer just seems to be crap. The response time is very bad and so the WAF (woman acceptance factor) is very bad.

thanks a lot for your help!

**Comment by kirovilya** [comment]
Can you show on the video what delays you have? I tried the TRADFRI remote control - I have no serious delays.

**Comment by thps1990** [comment]
i´ve tryed to show this on a video:
https://photos.app.goo.gl/A9odV38FE1NeyiAF7

maybe zigbee isn´t the right protocol for such a use case?
i expect, that the brightness goes from time to time to different values...

No i dont tryed the remote yet. I have about 30 zigbee devices in my network and another 10 on my xiaomi gateway. This is the only device wich wont work as expected.
________________________________
Von: Илья Киров <notifications@github.com>
Gesendet: Montag, 21. Januar 2019 14:35
An: ioBroker/ioBroker.zigbee
Cc: thps1990; Mention
Betreff: Re: [ioBroker/ioBroker.zigbee] Tradfri Dimmer on 0.8/0.9 (#156)


Can you show on the video what delays you have? I tried the TRADFRI remote control - I have no serious delays.

**Comment by thps1990** [comment]
i think thats the problem. If i rotate the dimmer maybe form 80% to 20% i don´t get the Values  79,78,77,76....23,22,21,20 - only something like 43,20...
So thats not useable. Connecting the Lamps direktly to the dimmer isnt possible, the lamp uses Milight 😉.

Ok, thats how it is maybe i try the TRADFRI Remote one day.
Thanks a lot for your help!

________________________________
Von: Илья Киров <notifications@github.com>
Gesendet: Dienstag, 22. Januar 2019 07:28
An: ioBroker/ioBroker.zigbee
Cc: thps1990; Mention
Betreff: Re: [ioBroker/ioBroker.zigbee] Tradfri Dimmer on 0.8/0.9 (#156)


I do not see big delays (for me these are not big delays) :)
I think the problem here is a bit different. Dimmer sends changes instantly, but the coordinator does not so often notify us about these events. Maybe this is the fault of the coordinator, and maybe the adapter. I can not say exactly.
Perhaps everything will change if we teach the dimmer to control the lamps directly.

**Comment by kirovilya** [comment]
For Remote please read first https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/getting_started/pairing_devices.md#ikea-tradfri

**Comment by noexperiance** [comment]
Hey Kirovolya, thanks for your great work. ;)
I experiance another problem:
Paring works smooth, but when dimmer is paired, I do not receive any values or value changes when turning the knob.
Is this a known issue?
