### ISSUE TITLE
(GER) Werte und Status über Kachel nach einiger Zeit nicht mehr veränderbar

### ISSUE THREAD

**Issue by Wannseesprinter** [ioBroker/ioBroker.zigbee#1560]
Hallo liebes Zigbee Adapter Team! ;)

Ich beobachte eigentlich seit einigen Monaten, seitdem ich mit dem Zigbee Adapter im ioBroker dabei bin, folgendes Phänomen:

Habe ich ein neues Device gekoppelt, kann ich auch einige Minuten lang über die "Kachel" im Adapter selbst die States oder andere Werte ändern und zudem z.B. bei Türsensoren sehen, ob diese geöffnet oder geschlossen sind. Aber wehe, ich gehe einen Tag später noch mal in die "Kachelansicht": Dann sehe ich zwar quasi die Dinge, die ich am Device verändern (Beschriftung) kann, zum eigentlichen Verändern der States muss ich dann aber nach "Objekte" im ioBroker wechseln. Die GUI Switches in allen Devices fehlen. Finde ich leider etwas ungünstig, zumal ich den Adapter in seiner GUI einfach ansprechende finde ;)

Hoffe darauf, dass ich damit kein Einzelfall bin.

![Screenshot_20221102-223902_Firefox~2](https://user-images.githubusercontent.com/101293779/199609232-6c8833be-08d0-49c2-b89e-4d36e89eed82.jpg)

**Comment by arteck** [comment]
kann ich so nicht bestätigen
hast du mal F5 gedrückt damit sich die Seite aktualisiert ...
