### ISSUE TITLE
Bitte um Implementierung von ROBB ROB_200-035-0

### ISSUE THREAD

**Issue by Holgip** [ioBroker/ioBroker.zigbee#1563]
Hallo ich habe mir in den NL den ROBB ROB_200-035-0 gekauft und wollte ihn in Zigbee einbinden aber der Adapter kennt ihn nicht.

![grafik](https://user-images.githubusercontent.com/76516473/200123727-c882929b-649c-46d2-b9e1-8142cb56ad5a.png)
![grafik](https://user-images.githubusercontent.com/76516473/200123797-4fbb612a-66bd-41d5-b45e-a9f6964c060e.png)

Ich wäre euch sehr dankbar, wenn Ihr den Switch mit aufnehmen könntet.
Besten Dank

**Comment by arteck** [comment]
wir könenn nur die Geräte die zigbee2mqtt kennt. ist es da gelistet ??

**Comment by Holgip** [comment]
Hallo arteck,
ja ist da gelistet:
https://www.zigbee2mqtt.io/devices/ROB_200-035-0.html

besten Dank

**Comment by asgothian** [comment]
bitte die aktuelle Version des Adapters von GitHub installieren, dann sollte das Gerät gehen.
