### ISSUE TITLE
Please implement "TuYa TS0601_smart_human_presense_sensor" and "TuYa MIR-HE200-TY"

### ISSUE THREAD

**Issue by Sascha79** [ioBroker/ioBroker.zigbee#1566]
Hello, everyone,

I would like to ask for the implementation of the following Tuya presence detectors.
Both devices are already included in the Zigbee2MQTT project.

TuYa MIR-HE200-TY (https://www.zigbee2mqtt.io/devices/MIR-HE200-TY.html)
TuYa TS0601_smart_human_presense_sensor (https://www.zigbee2mqtt.io/devices/TS0601_smart_human_presense_sensor.html)

Many thanks in advance.

Best regards,
Sascha

**Comment by arteck** [comment]
install GIT version and check again

**Comment by Surripio** [comment]
Is there any news about the TuYa MIR-HE200-TY implement. I see it as a humansensor in the zigbee adapter but in objects is nothing usefull.

**Comment by Surripio** [comment]
I have den newest Git Version (1.8.10) but the MIR-HE200-TY dont work, after peering i see the device as a human presence sensor, but without any usefull object. Pls can anyone help me?
