### ISSUE TITLE
Moes Schalter ZTS-EU wird im Adapter falsch erkannt

### ISSUE THREAD

**Issue by Chris0680** [ioBroker/ioBroker.zigbee#1567]
Hallo zusammen,
hab mir vor ca. einem Jahr Zigbee Schalter von MOES gekauft - Model ZTS-EU. Diese wurden sofort mit dem Zigbee Adapter im Iobroker erkannt und ich war bis jetzt mit den zusätzlichen Einstellungen, Kontrollicht oder Orientierungslicht, sehr zufrieden. Aktuell habe ich mir wieder genau die gleichen Schalter bestellt, jedoch musste ich feststellen, dass die Schalter nicht richtig im Adapter erkannt werden - Model TS0011. Schalter funktionieren, aber keine zusätlichen Einstellungen für Orientierungslicht oder Kontrollicht vorhanden.
Kennt jemand das Problem bzw. könnnte in nächster Zeit ein Zigbee Adapter Update Abhilfe verschaffen?
LG Chris
![grafik](https://user-images.githubusercontent.com/118127835/201536320-15886e2f-da64-4032-84ea-c4ee2a4a480b.png)
![grafik](https://user-images.githubusercontent.com/118127835/201536336-aa12a3f6-687c-4820-bf17-0203e1325ea5.png)

**Comment by arteck** [comment]
wilkommen in der Tuya Welt

das sind 2 unterschiedliche Schalter..das siehst du am manufactrer ..

**Comment by Chris0680** [comment]
> wilkommen in der Tuya Welt
> 
> das sind 2 unterschiedliche Schalter..das siehst du am manufactrer ..

Ich glaube ich wurde falsch verstanden. Die Schalter sehen genau gleich aus und auf der Verpackung ist als Model ZTS-EU angegeben. Darum verstehe ich nicht warum im Zigbee Adapter ein TS0011 erkannt wird und vielleicht könnte dieser neue Typ ergänzt werden.
LG Chris

**Comment by asgothian** [comment]
Willkommen in der Welt von TuYa. 
Die Identifikation der beiden Schalter auf der Zigbee-Seite ist unterschiedlich. Das beide das gleiche äussere Aussehen und die gleiche (äussere) Bezeichnung haben ist dabei nicht relevant. Es gibt da 3 Optionen:
- Du hast bei einem der beiden eine (billige?) Kopie des Gerätes erhalten
- Du hast bei einem der beiden ein Gerät erhalten bei dem der Hersteller aus versehen die falsche Zigbee-ID programmiert hat.
- Der Hersteller hat ein internes Update seiner Fertigungsanlagen durchgeführt und setzt nun systematisch andere Steuerplatinen ein.

Unterm Strich kann da im Adapter wenig bis nichts getan werden. Das Eine Gerät identifiziert sich als `TS0601` vom Hersteller `4098` mit der Benennung `_TZE200_amp6tsvy`, das zweite Gerät identifiziert sich als `TS0011` vom Hersteller `4417` mit der Benennung `_TZ3000_hhiodade`

Wenn wir da etwas im Adapter anpassen geht es schief.

Was du tun kannst (sofern du dich hinreichend mit JS auskennst und dir das zutraust):
- such im Verzeichnis \opt\iobroker\node_modules\zigbee-herdsman-converters\devices nach der Datei die die Hersteller Benennung des "falschen" Gerätes beinhaltet.
- such im Verzeichnis \opt\iobroker\node_modules\zigbee-herdsman-converters\devices nach der Datei die die Hersteller Benennung des "richtigen" Gerätes beinhaltet.
- Kopiere die Definition (alles ausser `fingerprint:` und `model:` vom richtigen in den Falschen.
- Starte den Adapter neu.
- Hoffe das die neue Platine die Befehle der alten weiterhin unterstützt.

Wichtig - wenn das klappt musst du das nach jedem update des Zigbee-Adapters wiederholen. Diese Anpassung wird es nicht in die zigbee-herdsman-converters schaffen, da sie die Unterstützung für andere Geräte möglicherweise stört - was bei Dir ggf. uninteressant ist.

Eine etwas elegantere Lösung dazu ist in Arbeit - muss aber noch final getestet werden.

A.

**Comment by asgothian** [comment]
Nachtrag: wenn du Interesse hast diese "elegantere" Lösung zu testen sag bescheid, dann poste ich was zu tun ist. Ansonsten würde ich diesen issue schliessen wollen

A.

**Comment by asgothian** [comment]
- Die 1.8.10 von Github installieren
- Die Gerätedefiniton vom korrekt erkannten Gerät heraus suchen (wie oben) (code Schnipsel 1)
- Die Gerätedefiniton vom nicht korrekt erkannten Gerät heraus suchen (wie open)
- unter /opt/iobroker/iobroker-data/zigbee_0 eine Datei Moes_override.js anlegen. Da den Code-Schnipsel 1 hinein kopieren
- In der Datei die Werte für fingerprint und model durch die des falsch erkannten Gerätes ersetzen
- Sicherstellen das aus der Originaldatei die "Require" Statements für die benötigten Strukturen mit an den Anfang der Moes_override.js geschrieben werden. 

Auf diese Art und Weise entsteht ein s.g. externer Konverter. 

Als letztes den Dateinamen Moes_override.js im Zigbee-Adapter in der Konfiguration als externen Konverter angegeben, den Adapter neu starten und schauen ob es Warn/Fehlermeldungen gibt. Solange wie Fehler in der Datei sind wird der externe Konverter nicht geladen, der Adapter läuft aber weiter. Sobald die Struktur entsprechend fertig zusammengebaut ist und alles passt sollte das Gerät dann über den externen Konverter definiert angelegt werden.
