### ISSUE TITLE
Support for Brennstuhl HT CZ 01

### ISSUE THREAD

**Issue by DLieb** [ioBroker/ioBroker.zigbee#1568]
Hi, it would be greatly appreciated if you could add support for this device (https://www.brennenstuhl.com/de-DE/produkte/smart-home/brennenstuhl-connect-zigbee-heizkorperthermostat-ht-cz-01).
the Zigbee2MQTT project seems to support the device already (https://www.zigbee2mqtt.io/devices/GS361A-H04.html) and as stated in your readme i hope you can transfer the functionality.

![Screenshot from 2022-11-22 17-21-31](https://user-images.githubusercontent.com/18535165/203366887-bc413f7a-c9ed-46d1-b49f-90392472fc78.png)

**Comment by arteck** [comment]
install the GIT version

**Comment by exaware** [comment]
I have installed the git version and now I can see more states. But I can only read the states but it doesn't take over my inputs. For example, if I set the target temperatue, nothing happens. I can't see the new target temperature on the device display. But if I turn the wheel I can see the target temperature in the datapoint. Do I have to do anything else for successfully writing?

**Comment by arteck** [comment]
show me the objects

**Comment by exaware** [comment]
![image](https://user-images.githubusercontent.com/55593493/205221926-d39ea4d3-bb3c-4f8e-b11e-1c883552b729.png)

**Comment by exaware** [comment]
For your information, I don't use the Brennenstuhl Zigbee Gateway but a Phoscon ConBee II USB-Stick.

**Comment by exaware** [comment]
@arteck do I have to use the send_payload channel to write to the therostat? If yes, what I have to fill in to set the target tempetature?

**Comment by asgothian** [comment]
Please enter the value `fffec8079c` into the state `zigbee.0.info.debugmessages`, then change one of the values you expect to be able to change and check the log for resulting messages with the keyword "ELEVATED"

You should be able to change the `comfort_temperature` and `eco_temperature` values, as well as the `mode`, `mode_force` and `target_temperature` states.

Please also trigger the `device_query` to verify that the device updates its states.

Use of the send_payload may be possible but is not advised for standard operation.

A.

**Comment by DLieb** [comment]
Hi, after installing the GIT version everything worked for me, thanks again. 
@exaware : I think you have to set the mode to "auto" for you to set the target temperature via iobroker, at least that worked for me.

**Comment by exaware** [comment]
Here the log:
![image](https://user-images.githubusercontent.com/55593493/205711525-23e609a1-c883-486e-9019-a85bcbc4e851.png)

The Device query was blocked, but why?

**Comment by exaware** [comment]
Hi @DLieb,
I really don't need a target temperature. I only want switch off when my window sensor goes false and switch on when sensor goes true. But no matter I do, nothing works.

**Comment by exaware** [comment]
After I pressed the upload button athe zigee adapter, value writing workes. Can somebody explain me this behavior please?

**Comment by asgothian** [comment]
> Here the log: ![image](https://user-images.githubusercontent.com/55593493/205711525-23e609a1-c883-486e-9019-a85bcbc4e851.png)
> 
> The Device query was blocked, but why?

Because you activated it multiple times within too little time.

**Comment by asgothian** [comment]
> Hi @DLieb,
> I really don't need a target temperature. I only want switch off when my window sensor goes false and switch on when sensor goes true. But no matter I do, nothing works.
> 

Did you try to set the device into automatic mode ?
If so, what messages are generated from the zigbee adapter (not just the elevated warn messages) within 30 seconds of you setting that value ? Please post the messages as text in code tags (the button < > on the GitHub editor) - i cannot read the text in your screenshots.

A.
