### ISSUE TITLE
(GER) GUI - Pair Button nicht erreichbar in Firefox Mobile

### ISSUE THREAD

**Issue by Wannseesprinter** [ioBroker/ioBroker.zigbee#1569]
Öffnet man mit dem Firefox Mobile den Zigbee Adapter des ioBroker, ist der Pair Button zwar irgendwie sichtbar, aber dann auch wiederum nicht erreichbar. Ist das ein hoher Aufwand, es zu fixen? Danke schon mal :)

![grafik](https://user-images.githubusercontent.com/101293779/203628924-4dcefff8-3ee2-456f-8979-df2a3b367a69.png)

![grafik](https://user-images.githubusercontent.com/101293779/203629135-c49a4dfd-ab20-4776-8a25-8ff322ffa4a5.png)

**Comment by arteck** [comment]
das problem bitte im Admin plazieren.. wir nutzen nur die gegebenen Möglichkeiten
