### ISSUE TITLE
Please add LEDVANCE SMART+ Compact Outdoor Plug EU 4058075729322 from zigbee2mqtt

### ISSUE THREAD

**Issue by dpkfllrerk3** [ioBroker/ioBroker.zigbee#1571]
[1.28.0]
(https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.28.0)

**Comment by dpkfllrerk3** [comment]
zigbee.0 | 2022-11-24 19:01:53.125 | error | 
Device 0xf0d1b8be24082aa6 "PLUG COMPACT EU T" not described in statesMapping.

**Comment by arteck** [comment]
install the GIT version
