### ISSUE TITLE
HEIMAN HS1CA-E Co Alarm is not working

### ISSUE THREAD

**Issue by menkej** [ioBroker/ioBroker.zigbee#1572]
According to the DB this device should work https://www.zigbee2mqtt.io/devices/HS1CA-E.html

Device label states HS1CA-EF if that makes a difference... It is shown as unknown device. If I can provide additional info, please let me know.

It would be great if you could add/fix this. Thanks!

**Comment by arteck** [comment]
please show the tile

**Comment by menkej** [comment]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/12273047/204244760-0b1ea2c9-7fe6-47e1-953c-61fa0cc25403.png">

**Comment by arteck** [comment]
undefined is no device.. plz repair new.. the device must send a typenumber

**Comment by menkej** [comment]
Hi @arteck ! I did not really understand your last comment. Anyways, I tried to add the device again and tada! it works now. Maybe the initial handshake was interrupted somehow? That one minute time box is sometimes quite short... So this ticket can be closed.
