### ISSUE TITLE
New Device

### ISSUE THREAD

**Issue by rabifu** [ioBroker/ioBroker.zigbee#1573]
Hello I have a flying Zigbee device (see attachment) which is not supported by the Zigbee adapter.
Is there any way to get the support? Please help me, I'm a newbie and a beginner.
Thanks very much!

![Zigbee Circut Breaker](https://user-images.githubusercontent.com/119059783/204025536-f1037abf-b566-412d-94df-f55e810eb223.png)
![Zigbee Circut Breaker_1](https://user-images.githubusercontent.com/119059783/204025541-15ce9334-292d-4a5d-a3b4-06369c66c414.png)
![Zigbee Circut Breaker_2](https://user-images.githubusercontent.com/119059783/204025543-8e21be2e-a74c-49c4-a16d-b2381a140ac9.png)
![Zigbee Circut Breaker_3](https://user-images.githubusercontent.com/119059783/204025545-20055cb6-6727-4fb9-b55a-3798ea7a9759.png)

**Comment by arteck** [comment]
is it supported by zigbee2mqtt project ?
