### ISSUE TITLE
BatteryLevel don't update IKEA FYRTUR Window Cover

### ISSUE THREAD

**Issue by McP4nth3r** [ioBroker/ioBroker.zigbee#1575]
The battery level of my Window Cover don't update since I have installed it last Year. I dont know the actual batterylevel of my window cover because it's on place since one year and some days

![f8DZeqw](https://user-images.githubusercontent.com/6289573/204063065-126f2be4-72e9-4365-9cce-44bdd0f747a8.png)

Current Version: `1.7.6`

**Comment by arteck** [comment]
battery is a function from converter or zigbee2mqtt project

**Comment by McP4nth3r** [comment]
Ok, does that mean I should open an issue there or will that be forwarded?

**Comment by McP4nth3r** [comment]
It’s a FYRTUR Window Cover 120cm breitHere is a link to the article https://www.ikea.com/de/de/p/fyrtur-verdunklungsrollo-smart-kabellos-batteriebetrieben-grau-40408196/Von meinem iPhone gesendetAm 01.12.2022 um 19:34 schrieb arteck ***@***.***>:﻿
which device is it

**Comment by McP4nth3r** [comment]
with the last update it works now fine i dont know why but it works
