### ISSUE TITLE
change object value via blockly script does not get pushed to devices

### ISSUE THREAD

**Issue by Bobmorton-TX** [ioBroker/ioBroker.zigbee#1577]
Hello! 
I am fairly new to Zigbee, so i think it is possible I am just overlooking something simple ;)

If I change zigbee.8.000b57fffe152f5a.brightness value directly in iobroker (enter value) this change gets pushed to the device. 
Controlling this value via lovelace UI also gets pushed to device.

When I use a blockly script to change the value I can see the changed value in the objects backend but it does not get pushed to device.

I use a blockly script to change zigbee.8.group_2.state and this works as intended.

**Comment by arteck** [comment]
its blockly problem..
