### ISSUE TITLE
Logstuffe

### ISSUE THREAD

**Issue by Homezecke** [ioBroker/ioBroker.zigbee#1578]
Ich würde mir wünschen, wenn nicht erreichbare Geräte nicht mehr mit ERROR geloggt werden. Besser wäre WARN oder INFO.

Meiner Meinung nach wäre Warn genug bei nicht erreichbaren geräten, da es Szenarios gibt, bei denen ja vom Anwender gewünscht  Geräte vom Stromnetz genommen werden.

**Comment by arteck** [comment]
das ist schön aber.. die anderen sehen es anders.. ergo .sry. musst du mit leben..

**Comment by Homezecke** [comment]
Ah, toll! Aber wer sind die "anderen" Bis jetzt nur Du? Hast ja sofort of **closed** gesetzt, bevor irgendjemand sonst seinen Senf dazugegeben hat ob sinnvoll oder nicht!
