### ISSUE TITLE
Aqara Motion Sensor P1 (RTCGQ14LM) did not overtake timeout

### ISSUE THREAD

**Issue by Duese123** [ioBroker/ioBroker.zigbee#1580]
The new P1 motion sensor did not overtake the value for occupancy timeout. Changing makes no difference

According to this [LINK](https://www.zigbee2mqtt.io/devices/RTCGQ14LM.html) right before changing the value the button has to be pressed. But it is not working. The P1 has every time the default 30s settings. 

![image](https://user-images.githubusercontent.com/95966691/204387436-4526ef5f-426e-4097-87b9-d5f91d2ddc58.png)

according to the site there should be normally also more options 
![image](https://user-images.githubusercontent.com/95966691/204387878-63751192-1d68-4b2c-a107-38905ee631f4.png)

**Comment by arteck** [comment]
add the device to exclude site .. and check again

**Comment by Duese123** [comment]
Okay i can See that if iam not Pressung the Button before the number will be overwritten to the old value. With Button clicking it will not be overwritten. But it is still using the 30 sek default time...

**Comment by arteck** [comment]
i dont know function from sensor..plz check infos from zigbee2mqtt project

**Comment by asgothian** [comment]
Unfortunately, this functionality is not part of the zigbee-herdsman-converters but is instead handled by a global data storage within zigbee2mqtt.io. Access to this functionality is being worked at but the structure is not easily accessed, so this functionality is not currently supported in ioBroker.
