### ISSUE TITLE
UI elements too big 

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.zigbee#1581]
After updating from 1.7.6 to 1.8.1 the UI elements on the Zigbee tab (not instance settings!) are too big to be usable.

![image](https://user-images.githubusercontent.com/16245/204476753-b36adda2-2215-4875-a269-a3c2e3e78498.png)

**Comment by Ilovegym66** [comment]
Same here with Version 1.8.1 / go back to 1.7.7 and it looks better. 
Browser Chrome and Firefox.
Additional in 1.8.1 is the assigned Device wrong, some devices are with the faulty icon and faulty functions assigend.(but this in a different issue).

**Comment by agross** [comment]
@Ilovegym66 See #1582

**Comment by agross** [comment]
Works for me 👍
