### ISSUE TITLE
Device icons broken on 1.8.1

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.zigbee#1582]
After updating vom 1.7.6 to 1.8.1 the device icons are all off.

Some examples:

![image](https://user-images.githubusercontent.com/16245/204477284-6115ef7e-190a-4884-9fe2-084dd0e9bbb2.png)
https://www.zigbee2mqtt.io/devices/4080248P9.html

![image](https://user-images.githubusercontent.com/16245/204477402-67f81ae2-b89b-42bc-9b41-7bf219789ba2.png)
https://www.zigbee2mqtt.io/devices/9290022166.html

![image](https://user-images.githubusercontent.com/16245/204477514-bf447606-7f88-4246-b5ea-2ab3efc9e435.png)
https://www.zigbee2mqtt.io/devices/5062431P7.html

**Comment by agross** [comment]
Downgrading did not help as these are persisted.

```json
{
  "type": "device",
  "common": {
    "name": "Kitchen #1",
    "type": "5062431P7",
    "icon": "img/Paulmann_50067.png",
    "color": null,
    "statusStates": {
      "onlineId": "zigbee.0.0017880108488e90.available"
    }
  },
  "native": {
    "id": "0017880108488e90"
  },
  "_id": "zigbee.0.0017880108488e90",
  "acl": {
    "object": 1636,
    "owner": "system.user.agross",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1669710581043
}
```

(The above is https://www.zigbee2mqtt.io/devices/5062431P7.html)

**Comment by fu-zhou** [comment]
same here, IKEA remotes are now some black dots and Blitzwolf Sockets are displayed as a light red device

**Comment by m-s-b** [comment]
Same here for some devices:
-LIDL/Silvercrest socket     "type": "HG06337",    "icon": "img/HG06338.png",
-Osram bulb "type": "AC03642",    "icon": "img/osram_sensorA.png",

But my IKEA remotes work fine (the pictures)
- Ikea Tradfri 5 button "type": "E1524/E1810",    "icon": "img/ikea_remote_control1.png", -> ok
- Ikea Styrbar 4 button "type": "E2001/E2002",   "icon": "img/E2001-E2002.png", -> ok

But i get some wrong datapoints for them. air_quality and fan_mode are not useful for a remote.

**Comment by Duese123** [comment]
Same here...
download icon from 

https://www.zigbee2mqtt.io/images/devices/E2007.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/E2001-E2002.png

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update

and check again

**Comment by agross** [comment]
@arteck How would that help with missing or wrong states?

**Comment by Duese123** [comment]
it does not help...
![image](https://user-images.githubusercontent.com/95966691/204793123-074c970c-7dcb-4361-8410-1e080e1d6e82.png)

**Comment by fzoellne** [comment]
> https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update
> 
> and check again
<img width="307" alt="Bildschirm­foto 2022-11-30 um 13 18 38" src="https://user-images.githubusercontent.com/46757067/204794543-81f96046-b71a-4636-a7a4-b150d6c01ce4.png">

do not have the manual upload button anymore in the adapter ....

**Comment by Duese123** [comment]
> Downgrading did not help as these are persisted.
> 
> ```json
> {
>   "type": "device",
>   "common": {
>     "name": "Kitchen #1",
>     "type": "5062431P7",
>     "icon": "img/Paulmann_50067.png",
>     "color": null,
>     "statusStates": {
>       "onlineId": "zigbee.0.0017880108488e90.available"
>     }
>   },
>   "native": {
>     "id": "0017880108488e90"
>   },
>   "_id": "zigbee.0.0017880108488e90",
>   "acl": {
>     "object": 1636,
>     "owner": "system.user.agross",
>     "ownerGroup": "system.group.administrator"
>   },
>   "from": "system.adapter.zigbee.0",
>   "user": "system.user.admin",
>   "ts": 1669710581043
> }
> ```
> 
> (The above is https://www.zigbee2mqtt.io/devices/5062431P7.html)

yes indeed it did not help




> > https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update
> > and check again
> 
> <img alt="Bildschirm­foto 2022-11-30 um 13 18 38" width="307" src="https://user-images.githubusercontent.com/46757067/204794543-81f96046-b71a-4636-a7a4-b150d6c01ce4.png">
> 
> do not have the manual upload button anymore in the adapter ....

activate developer view
![image](https://user-images.githubusercontent.com/95966691/204795167-ba9f0034-8595-4ca5-a617-bf4a5be0bf9d.png)

**Comment by fzoellne** [comment]
my bad but it does not install the correct icon files either

**Comment by arteck** [comment]
so install new version 1.8.3

**Comment by Duese123** [comment]
1.8.3 working fine! 1.8.5 is not working again (Show questionmark... configuration falls EG for ikea device)
