### ISSUE TITLE
Hue Motion Sensors lost after 1.8.1 Update

### ISSUE THREAD

**Issue by Voodoo2man** [ioBroker/ioBroker.zigbee#1585]
My Philips Hue motion sensors are not working anymore after update from 1.7.6 to 1.8.1.
They disappeared also from Zigbee Tab.
Tried installing twice. The problem appears every time.
Reinstalling 1.7.6 and they work again.

Node.js 16.18.1
NPM 8.19.2

**Comment by Psycho0verload** [comment]
For me too.

This is actually the motion sensor from hue.
<img width="331" alt="Bildschirm­foto 2022-11-30 um 05 58 53" src="https://user-images.githubusercontent.com/29304143/204711583-29468063-d44d-4a5e-b521-9a4062235496.png">
<img width="329" alt="Bildschirm­foto 2022-11-30 um 05 59 07" src="https://user-images.githubusercontent.com/29304143/204711591-5dbd8220-32af-4904-b207-f71e67c95b37.png">
<img width="328" alt="Bildschirm­foto 2022-11-30 um 05 59 17" src="https://user-images.githubusercontent.com/29304143/204711593-602e7a6b-12b1-4eab-b0b5-298fdc48cb19.png">

**Comment by arteck** [comment]
check plz GIT version

**Comment by Psycho0verload** [comment]
Okay, i try this.

The wrong icon is not even the main problem. The main problem is that data points are created that are not present in a Hue Motion Sensor such as "Switch State, Brightness, Color temperature and more".

The actual function of dedecting motion does not work.

<img width="918" alt="Bildschirm­foto 2022-11-30 um 10 08 47" src="https://user-images.githubusercontent.com/29304143/204754268-6f0bcd20-802c-4a95-a629-6656c43fa7c5.png">

I'll try a downgrade of the adapter and post the view again

**Comment by Ilovegym66** [comment]
exactly, version 1.8.1 crashs the complete structure, because the assignment of the devices are wrong. It's not alone a faulty icon, the complete device is wrong assigned...

**Comment by Psycho0verload** [comment]
Another affected device is "Hue smart plug - EU". Again, it is not so much the icon that is the problem as the data points that do not belong to the device.

<img width="923" alt="Bildschirm­foto 2022-11-30 um 11 21 34" src="https://user-images.githubusercontent.com/29304143/204771228-034d962f-f4b0-415f-b06e-62c6cb7219a1.png">

**Comment by Psycho0verload** [comment]
Downgrade to version 1.7.6 has also worked successfully for me. The superfluous data points are unfortunately still present and must be deleted manually.
