### ISSUE TITLE
Xiaomi Switch WXKG01LM

### ISSUE THREAD

**Issue by ingod68** [ioBroker/ioBroker.zigbee#1586]
Recognized wrong in 1.8.1 with states (left click, right click, both click)
1.7.5 works

**Comment by ingod68** [comment]
1.8.3 is working. ;-)

Close

**Comment by ingod68** [comment]
Same Problem in 1.8.23. 1.8.20 works.

**Comment by asutpshnik** [comment]
In adapter 1.8.23 version Xiaomi Switch WXKG01LM don't work!

**Comment by schneiderst** [comment]
Didn't find any working version for QBKG41LM. Should I open a new issue or should it be tracked here?

**Comment by Pittini** [comment]
Same here, I have three of those WXKG01LM buttons working for years, after zigbee update to   1.8.25 no more button function, but LinkQuality is updated after button press.

**Comment by ingod68** [comment]
I'm still using 1.8.20. The newer versions doesn't work with WXKG01LM.

**Comment by Pittini** [comment]
> I'm still using 1.8.20. The newer versions doesn't work with WXKG01LM.

I found the exposes hint on the update info, gave it a try and it works (also with 1.8.25). Description is here: https://github.com/ioBroker/ioBroker.zigbee/wiki/Exposes-for-device-integration

**Comment by arteck** [comment]
check 1.9.1 and also new DP..

**Comment by Pittini** [comment]
Voltage is still wrong.
![Screenshot 2023-12-24 200453](https://github.com/ioBroker/ioBroker.zigbee/assets/51408942/d9e9a387-8b10-4a62-b504-90c8fb150382)
