### ISSUE TITLE
Device/Gateway Request - Ikea Dirigera

### ISSUE THREAD

**Issue by LarsTh3Lars** [ioBroker/ioBroker.zigbee#1588]
Hey there,
couldn't find any Device/Feature Request.

I would like to use the new Ikea Dirigera Gateway with my iobroker.
I'm rly new to this  github - I don't know how to add the correct label :(
Let me know if you need further informations.

Here is the productlink ->
[https://www.ikea.com/nl/en/p/dirigera-hub-for-smart-products-white-smart-10503406/](url)

**Comment by Apollon77** [comment]
That Gateway can be integrated via homekit-controller already and will be in 2023 availableble hopefully via Matter. I do not see any option to sdupport that in zigbee adapter because it is not zigbe compatible in my eyes

**Comment by LarsTh3Lars** [comment]
@Apollon77 
Thanks for your reply.

If I get you right I should use homekit-controller adapter in iobroker to operate the Dirigera.
My ZigBee Devices will get coordinated by the Dirigera, show up in the homekit-controller adapter - I don't need to use the zigbee Adapter anymore?

**Comment by Apollon77** [comment]
If you replaced the zigbee coordinator you used with the zigbee adater so far then yes ... The ikea systemn is a closed system from my knowledege and can only be operated with their app normally. Because it also supports HomeKit the homekit-controller adapter should work fine  - and matter will come

**Comment by LarsTh3Lars** [comment]
Dirigera = closed system but open for homekit

Thanks - Now I got it ;)
