### ISSUE TITLE
error starting iobroker.zigbee with dev-server

### ISSUE THREAD

**Issue by clausinwi** [ioBroker/ioBroker.zigbee#1589]
If I start the dev-server in iobroker.zigbee I get an error message:
`2022-11-30 21:49:52.326  - error: zigbee.0 (8991) Cannot create directory /opt/iobroker/node_modules/iobroker_zigbee/.dev-server/default/iobroker-data/zigbee.0: Error: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker_zigbee/.dev-server/default/iobroker-data/zigbee.0'`

The reason for this error is that the path of the adapter was changed to iobroker_zigbee.
And this is caused by 
`getZigbeeOptions() {`
`        // file path for db`
`        let dbDir = path.join(utils.getAbsoluteInstanceDataDir(this), '');`
`        dbDir = dbDir.replace('.', '_');`
in main.js. 
For the dev-server this code replaces the wrong occurence of  '.'. 
It should only replace the last one. 

Please fix this.

**Comment by Apollon77** [comment]
The other question is: why you run dv server in an installed module in an iobroker installation? The dev-server is meaned to be executed ina "git developmenrt directory" and then installs an mini-iobroker inside that directory ... SO the location where you use it is mega weird and unexpected too. The problem is that this codeplace can not be changed without having a potential huge breaking change.

This is never an issue if iobroker is normally installed. Yes there might be also cases but they never happened so far

So the issue is more that you run it in a complete unexpected environment

**Comment by clausinwi** [comment]
Please excuse my ignorance. I'm new to to node.js and iobroker development and just want to debug the zigbee adapter. 
And I thought I just did what is written in the dev-server manual:
_Set up dev-server in the current directory. This should always be called in the directory where the io-package.json file of your adapter is located._ 
I found the json in the installation folder. Btw. this is not my productive server. It's a Debian Live just for testing. 
I will try your suggestion on the weekend. 
On the other hand: According to the javascript doumentation replace will replace the **first** occurence. In my eyes dbDir.replace('.', '_') is a very poor implementation for the requirement to replace the **last** occurence and to transform zigbee.x to zigbee_x. imho this should be corrected for the sake of quality. In 99.99% it will give the same result, and in the remaining 0.01% it will give the correct result. And no breaking changes.

**Comment by Apollon77** [comment]
> Set up dev-server in the current directory. 

Yes normally a git close directory is meaned with this :-)

**Comment by clausinwi** [comment]
I have cloned the iobroker.zigbee adapter to /home/user/Github.
The path to the project is therefore /home/user/Github/iobroker.zigbee.
I have setup dev-server in this folder.
And when I start the dev-server i get the same error:
`2022-12-03 20:47:25.529  - info: zigbee.0 (5592) starting. Version 1.8.7 in /home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee, node: v16.18.1, js-controller: 4.0.23

2022-12-03 20:47:25.548  - error: zigbee.0 (5592) Cannot create directory /home/user/Github/ioBroker_zigbee/.dev-server/default/iobroker-data/zigbee.0: Error: ENOENT: no such file or directory, mkdir '/home/user/Github/ioBroker_zigbee/.dev-server/default/iobroker-data/zigbee.0'
2`
I'm really at a loss. What's wrong in my setup?

**Comment by Apollon77** [comment]
In fact this is now exactly the replace you found above ... so it seems the zigbee adapter devs do not use dev-server for development. With this in mind I would propose to change the relevant code to

 let dbDir = path.join(utils.getAbsoluteDataDir(), adapter.namspace.replace('.', '_'));

which should do the same as the otehr sbut "right" :-)

@arteck

**Comment by arteck** [comment]
pr plz

**Comment by clausinwi** [comment]
@Apollon77 
I have now found time to try the solution. Now I get another error starting the dev-server:
`2022-12-16 14:44:59.682  - error: zigbee.0 (6885) adapter disabled`
`2022-12-16 14:44:59.722  - info: zigbee.0 (6885) starting. Version 1.8.10 in /home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee, node: v16.18.1, js-controller: 4.0.23`
`2022-12-16 14:44:59.742  - error: zigbee.0 (6885) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`
`2022-12-16 14:44:59.742  - error: zigbee.0 (6885) unhandled promise rejection: utils.getAbsoluteDataDir is not a function`
`2022-12-16 14:44:59.743  - error: zigbee.0 (6885) TypeError: utils.getAbsoluteDataDir is not a function`
`    at Zigbee.getZigbeeOptions (/home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee/main.js:867:37)`
`    at Zigbee.onReady (/home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee/main.js:195:36)`
`    at Zigbee.<anonymous> (/home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee/main.js:67:37)`
`    at Zigbee.emit (node:events:513:28)`
`    at /home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8226:26`
`2022-12-16 14:44:59.744  - error: zigbee.0 (6885) utils.getAbsoluteDataDir is not a function`

Is there a 'require' needed? 
Or a typo?

**Comment by clausinwi** [comment]
@Apollon77 One step further...
I suppose that you meant adapter.nam**e**space.replace
But adapter is not defined:
`2022-12-16 17:10:59.154  - info: zigbee.0 (10472) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system`
`2022-12-16 17:10:59.198  - error: zigbee.0 (10472) adapter disabled`
`2022-12-16 17:10:59.269  - info: zigbee.0 (10472) starting. Version 1.8.10 in /home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee, node: v16.18.1, js-controller: 4.0.23`
`2022-12-16 17:10:59.286  - error: zigbee.0 (10472) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`
`2022-12-16 17:10:59.287  - error: zigbee.0 (10472) unhandled promise rejection: adapter is not defined`
`2022-12-16 17:10:59.288  - error: zigbee.0 (10472) ReferenceError: adapter is not defined`
`    at Zigbee.getZigbeeOptions (/home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee/main.js:869:66)`
`    at Zigbee.onReady (/home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee/main.js:195:36)`
`    at Zigbee.<anonymous> (/home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/iobroker.zigbee/main.js:67:37)`
`    at Zigbee.emit (node:events:513:28)`
`    at /home/user/Github/ioBroker.zigbee/.dev-server/default/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8226:26`
`2022-12-16 17:10:59.288  - error: zigbee.0 (10472) adapter is not defined`

We could perhaps abbreviate this analysis if you give me a hint how to debug a running instance of iobroker.zigbee without dev-server. I have another problem (see [https://forum.iobroker.net/topic/60132/fehler-beim-starten-des-dev-servers-parcel-not-found](url) with the configuration of iobroker.zigbee, and i have the impression that no one is using 
dev-server.

**Comment by clausinwi** [comment]
I have found a way to debug the zigbee adapter in my running test instance. 
Therefore there is no need for the fix.
