### ISSUE TITLE
Tradfri Motion Sensor

### ISSUE THREAD

**Issue by mistermaster2punkt0** [ioBroker/ioBroker.zigbee#159]
Is it possible to add the Tradfri Motion Sensor to the supported devices list? This would help me a lot!

I would be very happy about your message!

**Comment by GoGitl** [comment]
It would be nice if someone could put that in.

**Comment by gitbreiti** [comment]
It would be really great if it was supported.

**Comment by VBen** [comment]
it seems that the tradfri motion sensor is now included in https://github.com/Koenkk/zigbee2mqtt
with the commit: https://github.com/Koenkk/zigbee-shepherd-converters/commit/f2950303fbf8d6bd0e51d8aab0a78a05842b27f1
perhaps somebody can port it to this repository
