### ISSUE TITLE
TS0044 stoped working after update

### ISSUE THREAD

**Issue by tobasium** [ioBroker/ioBroker.zigbee#1592]
Hi,

after Update my switch stoped working.

model: [TS0044](https://www.zigbee2mqtt.io/devices/TS0044.html)
description:Wireless switch with 4 buttons

i tried to repair the switch but functions are lost after that

![image](https://user-images.githubusercontent.com/23247891/205003908-49c11abe-9f3a-4327-9efd-7b11857d5e0f.png)

new paired:
![image](https://user-images.githubusercontent.com/23247891/205003315-6215be3e-aa12-4143-981f-88b74cf962b1.png)

old one:
![image](https://user-images.githubusercontent.com/23247891/205003500-d88d3971-67da-461b-bbde-0e607cc825c7.png)

**Comment by arteck** [comment]
i know.. use 1.8.3

**Comment by tobasium** [comment]
Thanks, waiting for Feedback to test newer Version.

**Comment by arteck** [comment]
ok i find it.. new try 1.8.7

**Comment by tobasium** [comment]
Hi Arteck. It works again.
