### ISSUE TITLE
Ikea Styrbar E2001/E2002 not described in statesMapping since V1.7.7

### ISSUE THREAD

**Issue by spoeh-man** [ioBroker/ioBroker.zigbee#1593]
The Ikea Styrbar is not working Properly since V1.7.7.

error | Device 0x04cd15fffe75bf85 "E2001/E2002" not described in statesMapping.

**Comment by arteck** [comment]
install the GIT version and check again

**Comment by spoeh-man** [comment]
Git Version is working Fine
