### ISSUE TITLE
Missing switch states

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.zigbee#1594]
I have the following device: https://www.zigbee2mqtt.io/devices/TS0004.html
It is correctly recognized by the adapter:
Device '0xa4c138808e2611c7' is supported, identified as: TuYa Smart light switch - 4 gang with neutral wire (TS0004)

But the device has only 1 switch created, it should be 4 as it has 4 separate switches.
![Bildschirmfoto 2022-12-01 um 18 49 26](https://user-images.githubusercontent.com/839480/205124516-9f3c591b-fc0e-4bad-b06b-b9f5696b3614.png)

Version: 1.7.7

**Comment by arteck** [comment]
add this device to exclude tab

**Comment by cburghardt** [comment]
Now it looks like this:

![Bildschirmfoto 2022-12-01 um 19 12 50](https://user-images.githubusercontent.com/839480/205128991-1420d072-1150-4d6f-a873-8fcda4748a02.png)

**Comment by arteck** [comment]
ok install the new version from GIT and check again

**Comment by cburghardt** [comment]
Cool stuff

![Bildschirmfoto 2022-12-01 um 19 44 26](https://user-images.githubusercontent.com/839480/205134949-59370596-dfa9-4828-b96e-bc9cb6c5838d.png)
