### ISSUE TITLE
Silvercrest Power Strip HG06338 broken in 1.8.7

### ISSUE THREAD

**Issue by technyon** [ioBroker/ioBroker.zigbee#1595]
Upgrading from 1.8.5 to 1.8.7 breaks my Silvercrest powerstrips.

- The image shown is from some other device
- States state_l1, state_l2, state_3 don't work at all
- state works and toggles all 3 sockets

![front](https://user-images.githubusercontent.com/14868793/205247483-99d73804-a7eb-4ab4-8a32-0049e004dec6.png)
![back](https://user-images.githubusercontent.com/14868793/205247488-c7b30c71-9e7b-4247-b2fe-6074326cea80.jpg)

**Comment by technyon** [comment]
P.S.:

1.8.3 list the model correctly as HG06338, while 1.8.7 shows TS011F_plug_3 as seen in the picture above.

**Comment by arteck** [comment]
check now the GIT version

**Comment by technyon** [comment]
Fixed
