### ISSUE TITLE
Device zigfred uno nicht mehr erkannt

### ISSUE THREAD

**Issue by tango17b** [ioBroker/ioBroker.zigbee#1596]
Logfile:
2022-12-04 15:18:45.377 | debug | No converter available for 'ZFU-1D-CH' with cluster 'genOnOff' and type 'read'

Zigbee2MQTT
https://www.zigbee2mqtt.io/devices/ZFU-1D-CH.html

**Comment by arteck** [comment]
was heisst nicht mehr erkannt ??

**Comment by tango17b** [comment]
Im iobroker wird eine leere Kachel dargestellt und die zur Verfügung stehenden Endpunkte nicht angelegt, siehe Details im pdf

[screenshot.pdf](https://github.com/ioBroker/ioBroker.zigbee/files/10155349/screenshot.pdf)

vollständiger Log Auszug mit der Meldung vom Device:
Type read device {"type":"device","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":2,"_type":"Router","_ieeeAddr":"0xf4ce36637f60cd49","_networkAddress":6934,"_manufacturerID":4764,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":5,"profileID":260,"deviceID":258,"inputClusters":[0,3,4,5,6,8,768,64578],"outputClusters":[],"deviceNetworkAddress":6934,"deviceIeeeAddress":"0xf4ce36637f60cd49","clusters":{"genBasic":{"attributes":{"modelId":"zigfred uno","manufacturerName":"Siglis","powerSource":4,"zclVersion":3,"appVersion":1,"stackVersion":10,"hwVersion":1,"dateCode":"20210603","swBuildId":"","deviceEnabled":1}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"manuSpecificSiglisZigfred":{"attributes":{"buttonEvent":393472}},"lightingColorCtrl":{"attributes":{"colorMode":1,"options":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1},{"cluster":64578,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1}],"_configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":6,"profileID":260,"deviceID":256,"inputClusters":[0,3,4,5,6],"outputClusters":[],"deviceNetworkAddress":6934,"deviceIeeeAddress":"0xf4ce36637f60cd49","clusters":{"genBasic":{"attributes":{"swBuildId":"","deviceEnabled":1}},"genOnOff":{"attributes":{"onOff":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1}],"_configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":7,"profileID":260,"deviceID":257,"inputClusters":[0,3,5,4,6,8],"outputClusters":[],"deviceNetworkAddress":6934,"deviceIeeeAddress":"0xf4ce36637f60cd49","clusters":{"genBasic":{"attributes":{"swBuildId":"","deviceEnabled":1}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":24}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1}],"_configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":242,"profileID":41440,"deviceID":97,"inputClusters":[],"outputClusters":[33],"deviceNetworkAddress":6934,"deviceIeeeAddress":"0xf4ce36637f60cd49","clusters":{},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"Siglis","_powerSource":"DC Source","_modelID":"zigfred uno","_applicationVersion":1,"_stackVersion":10,"_zclVersion":3,"_hardwareVersion":1,"_dateCode":"20210603","_softwareBuildID":"","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"front_surface_enabled":1,"relay_enabled":1,"dimmer_enabled":1,"dimmer_dimming_enabled":true,"configured":514527292},"_lastSeen":1670253207437,"_defaultSendRequestWhen":"immediate","_linkquality":108,"_lastDefaultResponseSequenceNumber":146},"mapped":{"zigbeeModel":["zigfred uno"],"model":"ZFU-1D-CH","vendor":"Siglis","description":"zigfred uno smart in-wall switch","options":[{"type":"enum","name":"front_surface_enabled","property":"front_surface_enabled","access":2,"values":["auto","true","false"],"description":"Front Surface LED enabled"},{"type":"enum","name":"relay_enabled","property":"relay_enabled","access":2,"values":["auto","true","false"],"description":"Relay enabled"},{"type":"enum","name":"dimmer_enabled","property":"dimmer_enabled","access":2,"values":["auto","true","false"],"description":"Dimmer enabled"},{"type":"enum","name":"dimmer_dimming_enabled","property":"dimmer_dimming_enabled","access":2,"values":["auto","true","false"],"description":"Dimmer dimmable"},{"type":"numeric","name":"transition","property":"transition","access":2,"value_min":0,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition)."},{"type":"binary","name":"color_sync","property":"color_sync","access":2,"value_on":true,"value_off":false,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true)."}],"fromZigbee":[{"cluster":"manuSpecificSiglisZigfred","type":["commandSiglisZigfredButtonEvent"]},{"cluster":"lightingColorCtrl","type":["attributeReport","readResponse"],"options":[{"type":"binary","name":"color_sync","property":"color_sync","access":2,"value_on":true,"value_off":false,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true)."}]},{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"genLevelCtrl","type":["attributeReport","readResponse"]},{"cluster":"genLevelCtrl","type":["attributeReport","readResponse"]},{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["state","brightness","brightness_percent","on_time"],"options":["[Circular]"]},{"key":["color"],"options":["[Circular]",{"type":"numeric","name":"transition","property":"transition","access":2,"value_min":0,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition)."}]},{"key":["transition"],"attr":[]},{"key":["rate"],"attr":[]},{"key":["brightness_move","brightness_move_onoff"]},{"key":["brightness_step","brightness_step_onoff"],"options":[{"type":"numeric","name":"transition","property":"transition","access":2,"value_min":0,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition)."}]},{"key":["level_config"]},{"key":["power_on_behavior"]},{"key":["hue_move","saturation_move"]},{"key":["hue_step","saturation_step"],"options":[{"type":"numeric","name":"transition","property":"transition","access":2,"value_min":0,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition)."}]},{"key":["color_options"]},{"key":["color_mode"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]}],"meta":{"multiEndpoint":true}},"name":"0xf4ce36637f60cd49"} incoming event: {"type":"read","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":2,"_type":"Router","_ieeeAddr":"0xf4ce36637f60cd49","_networkAddress":6934,"_manufacturerID":4764,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":5,"profileID":260,"deviceID":258,"inputClusters":[0,3,4,5,6,8,768,64578],"outputClusters":[],"deviceNetworkAddress":6934,"deviceIeeeAddress":"0xf4ce36637f60cd49","clusters":{"genBasic":{"attributes":{"modelId":"zigfred uno","manufacturerName":"Siglis","powerSource":4,"zclVersion":3,"appVersion":1,"stackVersion":10,"hwVersion":1,"dateCode":"20210603","swBuildId":"","deviceEnabled":1}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"manuSpecificSiglisZigfred":{"attributes":{"buttonEvent":393472}},"lightingColorCtrl":{"attributes":{"colorMode":1,"options":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1},{"cluster":64578,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1}],"_configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":6,"profileID":260,"deviceID":256,"inputClusters":[0,3,4,5,6],"outputClusters":[],"deviceNetworkAddress":6934,"deviceIeeeAddress":"0xf4ce36637f60cd49","clusters":{"genBasic":{"attributes":{"swBuildId":"","deviceEnabled":1}},"genOnOff":{"attributes":{"onOff":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1}],"_configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":7,"profileID":260,"deviceID":257,"inputClusters":[0,3,5,4,6,8],"outputClusters":[],"deviceNetworkAddress":6934,"deviceIeeeAddress":"0xf4ce36637f60cd49","clusters":{"genBasic":{"attributes":{"swBuildId":"","deviceEnabled":1}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":24}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00212effff087155","endpointID":1}],"_configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":242,"profileID":41440,"deviceID":97,"inputClusters":[],"outputClusters":[33],"deviceNetworkAddress":6934,"deviceIeeeAddress":"0xf4ce36637f60cd49","clusters":{},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"Siglis","_powerSource":"DC Source","_modelID":"zigfred uno","_applicationVersion":1,"_stackVersion":10,"_zclVersion":3,"_hardwareVersion":1,"_dateCode":"20210603","_softwareBuildID":"","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"front_surface_enabled":1,"relay_enabled":1,"dimmer_enabled":1,"dimmer_dimming_enabled":true,"configured":514527292},"_lastSeen":1670253207437,"_defaultSendRequestWhen":"immediate","_linkquality":108,"_lastDefaultResponseSequenceNumber":146},"endpoint":"[Circular]","data":["onOff"],"linkquality":108,"groupID":null,"cluster":"genOnOff","meta":{"zclTransactionSequenceNumber":130,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0}}}

Hoffe das hilft
