### ISSUE TITLE
Daten werden nicht an Aqara Thermostat E1 gesendet (1.8.7)

### ISSUE THREAD

**Issue by konertm** [ioBroker/ioBroker.zigbee#1598]
Die Daten vom Aqara Thermostat E1 werden alle empfangen und sauber angezeigt. Ändert man nun die Temperatur im Datenpunkt, wird diese auch im Zigbee Adapter richtig angezeigt, aber nicht an das Thermostat gesendet. Der Modus heat;auto;off wird ohne Probleme an das Thermostat gesendet.

**Comment by asgothian** [comment]
Bitte Prüfen:
- Ist der Wert im Zigbee Adapter "Bestätigt" ?
- Gibt es log Meldungen wenn der Wert im Zigbee Adapter geändert wird (+- 30 Sekunden)
- Welche Meldungen kommen wenn Du die Adresse des Gerätes in den Datenpunkt `zigbee.0.info.debugmessages` einträgst ?

A.
