### ISSUE TITLE
Philips Hue Tap Dial Switch

### ISSUE THREAD

**Issue by matze19999** [ioBroker/ioBroker.zigbee#1599]
Are there any plans to support the hue tap dial switch?

I own one and can provide logs / debug files.

Thanks in advance!

**Comment by arteck** [comment]
?????????????

**Comment by matze19999** [comment]
> ?????????????

Can't u write a normal question instead of 20 question marks?

I have no idea what you want to say

**Comment by asgothian** [comment]
He gave you about as much information as you gave us. When asking about specific devices, we need a lot more information than just a name to identify the device itself.

Please read [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device) to support the device. 

Note that we will generally only implement devices which we actually have access to. Supporting additional devices requires people who actually have them do the work. Providing debug information is often not enough to properly support a new device.

A.
