### ISSUE TITLE
Lidl Steckdosenleiste wird falsch zugewiesen

### ISSUE THREAD

**Issue by Mistaluna** [ioBroker/ioBroker.zigbee#1603]
Hallo,

eine Lidl Steckdosenleiste 3-fach Steckdosenleiste wird aktuell als Einfachsteckdose  erkannt. Das Problem tritt auf seit ich mein System neu aufgesetzt habe und über BackitUp ein altes backup eingespielt wurde. Dabei wurde mein Adapter von 1.7.6 auf 1.8.7 (EDIT) aktualisiert ([siehe dieser Beitrag im iobroker forum](https://forum.iobroker.net/topic/60700/kann-zigbee-adapter-nicht-upgraden)).

Direkt nach dem Upgrade wurde diese Steckdosenleiste falsch erkannt als Vierfachsteckdose und liess sich nicht mehr korrekt schalten. Daraufhin habe ich auf der Geräteseite im Zigbee Adapter auf "Reconfigure" geklickt, woraufhin die Mehrfachsteckdose als diese Einfachsteckdose erkannt wurde:
![grafik](https://user-images.githubusercontent.com/85135468/205889845-33fca128-af3b-4d0a-8486-eb3a883bdf70.png)

Löschen des Geräts und Neukopplung führt immer zur gleichen falschen Zuordnung als Einfachsteckdose.

Ich habe unter /opt/iobroker/node_modules/zigbee-herdsman-converters nachgesehen. Der manufacturer `_TZ3000_1obwwnmq` wird nur in lidl.js verwendet und verweist dort auch zum korrekten Gerät wie mir scheint:

`
        fingerprint: [
            {modelID: 'TS011F', manufacturerName: '_TZ3000_wzauvbcs'}, // EU
            {modelID: 'TS011F', manufacturerName: '_TZ3000_1obwwnmq'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_4uf3d0ax'}, // FR
            {modelID: 'TS011F', manufacturerName: '_TZ3000_vzopcetz'}, // CZ
            {modelID: 'TS011F', manufacturerName: '_TZ3000_vmpbygs5'}, // BS
        ],
        model: 'HG06338',
        vendor: 'Lidl',
        description: 'Silvercrest 3 gang switch, with 4 USB (EU, FR, CZ, BS)',
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.switch().withEndpoint('l3')],
        extend: extend.switch(),
        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            for (const ID of [1, 2, 3]) {
                await reporting.bind(device.getEndpoint(ID), coordinatorEndpoint, ['genOnOff']);
            }
        },
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2, 'l3': 3};
        },
`

Was kann ich tun?

**Comment by Mistaluna** [comment]
Eben kam es während der Neukopplung vor, dass sie für ein paar Sekunden richtig angezeigt wurde. Also drei Hebel für jede Steckdose, das Bild stimmte, die bezeichnung war korrekt.

**Comment by arteck** [comment]
> Sorry, habe oben einen Fehler gemacht. Habe bereits die 1.8.7.

dann hast du die Falsche gezogen..

installier JETZT bitte nochmal von GIt

**Comment by bench-marc** [comment]
Ich habe das gleiche Problem mit Version 1.8.10.
Ich habe die Steckdosenleiste heute zum ersten mal gepaired und sie wurde als TuYa TS011F_plug_3 erkannt.
Muss ich auf eine bestimmte Version up- oder downgraden?

**Comment by bench-marc** [comment]
Wird wahrscheinlich mit dem nächsten update von zigbee-herdsman-converters gefixt: https://github.com/Koenkk/zigbee-herdsman-converters/pull/5509
