### ISSUE TITLE
Tuya IH-K009 Temperature Sensor shows 3000 V instead of 3.000 V

### ISSUE THREAD

**Issue by MichaelUray** [ioBroker/ioBroker.zigbee#1605]
The sensor shows 3000 V, not sure if that number is correct in general even with the decimal place corrected, since the battery has probably not exactly 3.000 V.

![2022-12-08_09-33-35_zigbee-0_-_iob_–_Mozilla_Firefox](https://user-images.githubusercontent.com/25169478/206398366-a7a00c53-ca0d-4fdc-912c-9dd189388b08.png)

It also would be good to name it "Battery voltage" and not "Load voltage" to have the naming consistent with the other sensors.

![2022-12-08_09-34-25_zigbee-0_-_iob_–_Mozilla_Firefox](https://user-images.githubusercontent.com/25169478/206398665-1690d2fe-32b2-4e47-be73-df3aa0d0f64f.png)

Is this actually the way how it should be, that it shows there a TS0201 as `modelZigbee` even it is a IH-K009 sensor?
The picture it shows is correct, it fits to the sensor.

    model:[IH-K009](https://www.zigbee2mqtt.io/devices/IH-K009.html)
    description:Temperature & humidity sensor

    modelZigbee:TS0201
    type:EndDevice
    nwk:21256
    manuf id:4417
    manufacturer:_TZ3000_dowj6gyi
    power:Battery
    app version:70
    hard version:1
    zcl version:3
    stack version:0
    date code:
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genPowerCfg (1)
    genIdentify (3)
    msTemperatureMeasurement (1026)
    msRelativeHumidity (1029)
    genBasic (0)
    output clusters:genIdentify (3)
    genOta (25)
    genTime (10)

**Comment by asgothian** [comment]
Which adapter version are you running ?

As to the question - the device reports the model as TS0201 from Manufacturer _TZE3000_dowj6gyi. The zigbee-herdsman-converters translate this to the model IH-K009

As the states are also generated from the zigbee-herdsman-converters, they are responsible for naming (Load voltage) and scaling (3000 over 3.0 V).

A.

**Comment by MichaelUray** [comment]
> Which adapter version are you running ?

Adapter: v1.8.7
type:zStack3x0
version:2-1.2.7.1.
revision:20220219



> As the states are also generated from the zigbee-herdsman-converters, they are responsible for naming (Load voltage) and scaling (3000 over 3.0 V).

So is it then better to open an issue there?
https://github.com/Koenkk/zigbee-herdsman-converters

**Comment by PeterVoronov** [comment]
> Which adapter version are you running ?
> 
> As to the question - the device reports the model as TS0201 from Manufacturer _TZE3000_dowj6gyi. The zigbee-herdsman-converters translate this to the model IH-K009
> 
> As the states are also generated from the zigbee-herdsman-converters, they are responsible for naming (Load voltage) and scaling (3000 over 3.0 V).
> 
> A.

Disagree.

In exposes battery_voltage for any device in mV...
battery_voltage: () => new Numeric('voltage', access.STATE).withUnit('mV').withDescription('Voltage of the battery in millivolts'),
