### ISSUE TITLE
Aqara Cube Controller T1 pro

### ISSUE THREAD

**Issue by Doener92** [ioBroker/ioBroker.zigbee#1607]
Hello. Does anyone know when the new controller will be supported?

Product name: Aqara Cube Controller T1 Pro
Manufacturer: LUMI
Model identifier: lumi.remote.cagl02 /MFCZQ12LM
Device type : Magic Cube

**Comment by asgothian** [comment]
It will be supported after one or more of the following has happened:
- one of the zigbee developers has one and integrates it into the zigbee-herdsman-converters
- the zigbee adapter is updated to use the version of the zigbee-herdsman-converters which contains support for the device
- you take the time to integrate the device into zigbee-herdsman-converters, using [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device) as a starting point to do this
- someone unrelated to ioBroker adds the support to the zigbee-herdsman-converters

I know this is not the answer you are looking for, but it is the best answer which can be given to your question.

A.

**Comment by Doener92** [comment]
Thank you for your prompt reply. Of course I was hoping that someone was already working on it. Maybe I understand how I can integrate the device into the zigbee-herdsman-converter.
