### ISSUE TITLE
Aqara Devices only connect to the Coordinator

### ISSUE THREAD

**Issue by nmehnert73** [ioBroker/ioBroker.zigbee#1608]
I'm using the Sonoff-Stick in my NAS as coordinator. Because some of the senors are disconnected I've installed one Sonoff-Zigbee-Plug on each floor. Nevertheless the sensors don't connect to the repeaters. I wanted to configure the bindings, but the list of source devices is empty. The target list includes my plugs. Anyone with a helping idea?
![image](https://user-images.githubusercontent.com/112388389/206640432-6ec2b344-0df2-4f67-a5b6-233f330c2bc3.png)
![image](https://user-images.githubusercontent.com/112388389/206640526-392387a1-246e-446f-8370-6321321ef532.png)
![image](https://user-images.githubusercontent.com/112388389/206640628-4a23dd5d-8be4-453f-acf6-36d619252260.png)

**Comment by asgothian** [comment]
Bindings do not allow to force the mesh structure. If you succeed to bind a sensor to a device it will *only* send its values to that device. As routers do not support the cluster required for binding, the are not eligible for accepting bindings.

The Arara sensors will only use the mesh for communication if they cannot connect to the coordinator *at any time*.  As such, you may have success if you pair the sensors at their location with the wireless communication to the coordinator being impossible to force them to go through a router.

A.

**Comment by nmehnert73** [comment]
@asgothian , is this a typical behaviour for the Aqaras or for any ZigBee-device? Any advice what I should do, when my Coordinator is on the 1st floor and I want to connect to a Aquara-humidity-sensor in the cellar? The three Sonoff-Plugs don't help ;-)

**Comment by DEV2DEV-DE** [comment]
> is this a typical behaviour for the Aqaras or for any ZigBee-device?

No!

![image](https://user-images.githubusercontent.com/95883579/214516214-31a8fc99-b7c4-4bcf-aaa7-2d935668634f.png)
