### ISSUE TITLE
Supporting Install Code 

### ISSUE THREAD

**Issue by Gornung** [ioBroker/ioBroker.zigbee#1609]
Hey together, 

i've done some research and want to connect my [Bosch radiatorthermostat II](https://www.bosch-smarthome.com/de/de/produkte/geraete/heizkoerper-thermostat/) to pair this device i need to support the Install-Code which is inside the packaging. 

The Zigbee2mqtt does support this since August this [PR](https://github.com/Koenkk/zigbee2mqtt.io/pull/1540)

I'm pretty new to this we can try to pair-programm it and have a look together how we can embedd it. 

German is welcome too :D 

[Forum-Conversation](https://forum.iobroker.net/topic/60840/zigbee-adapter-kopplung-mit-bosch-heizk%C3%B6rper-thermostat-ii/10)

**Comment by asgothian** [comment]
If you are up to try help integrate it, you should make a fork of the adapter on GitHub. I would suggest to make another UI icon for pairing with a code, and then generate a UI interface to query the code before opening the network for the device.

I can prepare both over the weekend, but i cannot test it without a device requiring a code

**Comment by Gornung** [comment]
Of course, if our times matches we can pair-programmm - maybe today in the afternoon.

yes sure, i have the device and can test it 👍

**Comment by Gornung** [comment]
Shouldn't be that hard, i can try it out how is the project structured wherr should i add it?

Ive done mostly the ui with react and bootstraps components.

**Comment by asgothian** [comment]
I actually got it set up, do you can test with your code, if you install the adapter from

https://github.com/asgothian/ioBroker.zigbee

**Comment by Gornung** [comment]
Ah great i will be in about an hour a home thanks 😊 

I give you asap feedback

**Comment by Gornung** [comment]
Okay, i would like to test it now, but i acually dont know how to install first of all install this one though the cli, and i cant see the changes, are the changes pushed to your master branch?

**Comment by asgothian** [comment]
the iobroker discord: https://discord.gg/Wr7EQvhy

**Comment by asgothian** [comment]
test is successful, merge will need a few day due to cleanup

**Comment by asgothian** [comment]
Fixed in 1.8.10

**Comment by breiflo** [comment]
How should the install code be added? What part of the QR code is it?

**Comment by breiflo** [comment]
@asgothian or @Gornung can you help how to add the installation code?

**Comment by Gornung** [comment]
Hey @breiflo 

can you send me your QR code string?

**Comment by breiflo** [comment]
I am using a CC2351 stick and the QR code sting is RB01SG0D8310182648008000000000000000000018FC260000037813DLKA0F5F1B96F35E6E8844CA9D07D7BB7A84484

**Comment by asgothian** [comment]
Ich bin nicht sicher ob der cc2531 den install code überhaupt unterstützt
