### ISSUE TITLE
Tuya TS0601 -> _TZE200_9yapgbuv -> ZTH02_V1.1 -> temp/hum/battery Sensor

### ISSUE THREAD

**Issue by rolsch** [ioBroker/ioBroker.zigbee#1612]
Adapter Version 1.8.7

Dieser Sensor zeigt nach dem Pairing leider keine Sensordaten.
Auf der Platine sind folgende Bezeichnungen:
ZTH02_V1.1
2022-10-24
=> also eine sehr aktuelle Produktion :-)

Hier die Daten aus der Device-Info:

Das Picture WS500A passt nicht, das Device ist etwas kleiner mit anderem Temp-Aufdruck.

ieee:0xa4c138dc68e74553
nwk:26467 (0x6763)
model:[WSD500A](https://www.zigbee2mqtt.io/devices/WSD500A.html)
groups:

model:[WSD500A](https://www.zigbee2mqtt.io/devices/WSD500A.html)
description:Temperature & humidity sensor
modelZigbee:TS0601
type:EndDevice
nwk:49329
manuf id:4417
manufacturer:**_TZE200_9yapgbuv**
power:Battery
app version:72
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false

endpoint:1
profile:260
input clusters:genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
genBasic (0)
output clusters:genOta (25)
genTime (10)

Entwickler-Tab
manuSpecificTuya (61184) meldet undefined "Cluster 'manuSpecificTuya' has no attribute 'null'"
- es ist kein attribute auswählbar

Welche Daten werden-wie ggf. noch benötigt?

**Comment by asgothian** [comment]
Wenn es da gelöst ist passt es auch bei uns.

**Comment by rolsch** [comment]
> 

Ok,
https://github.com/Koenkk/zigbee2mqtt/issues/15128
ist closed mit dem Kommentar:

_TZE200_9yapgbuv is supported now in z2m 1.28.4

Wann wird dies Anpassung hier verfügbar sein?

**Comment by asgothian** [comment]
Give it a few days.

**Comment by rolsch** [comment]
Yes,
no problem,
fantastic support and project!!!

**Comment by rolsch** [comment]
Hi, soeben nochmal die GIT Version (master, zhc .21) installiert.

Das Device wird zwar erkannt aber weiterhin werden keine Werte für Temp/Hum/Batt angezeigt.

Innerhalb IOBroker sehe ich diese Log-Meldung:
`<html>
<body>


zigbee.0 | 2023-01-15 22:41:54.085 | warn | Device '0xa4c138dc68e74553' announced itself
-- | -- | -- | --
zigbee.0 | 2023-01-15 22:39:49.551 | warn | Device '0xa4c138dc68e74553' announced itself
zigbee.0 | 2023-01-15 22:37:59.731 | info | DeviceConfigure successful 0xa4c138dc68e74553 TS0601
zigbee.0 | 2023-01-15 22:37:45.034 | warn | Device '0xa4c138dc68e74553' announced itself
zigbee.0 | 2023-01-15 22:37:20.174 | info | Configuring 0xa4c138dc68e74553 TS0601
zigbee.0 | 2023-01-15 22:36:26.861 | info | Zigbee: stop joining
zigbee.0 | 2023-01-15 22:35:57.432 | info | DeviceConfigure successful 0xa4c138dc68e74553 TS0601
zigbee.0 | 2023-01-15 22:35:57.035 | info | Configuring 0xa4c138dc68e74553 TS0601
zigbee.0 | 2023-01-15 22:35:57.033 | info | Device '0xa4c138dc68e74553' is supported, identified as: TuYa Temperature & humidity sensor (WSD500A)
zigbee.0 | 2023-01-15 22:35:57.032 | info | Successfully interviewed '0xa4c138dc68e74553', device has successfully been paired
zigbee.0 | 2023-01-15 22:35:54.689 | error | Device 0xa4c138dc68e74553 "TS0601" not described in statesMapping.
zigbee.0 | 2023-01-15 22:35:53.934 | warn | Device '0xa4c138dc68e74553' announced itself


</body>
</html>`

**Comment by Oli-BY** [comment]
Is there a solution for this problem available?
Home Assistant and Sky Connect Stick -> this sensor but no data. 3 entities I have.
Thank you

**Comment by alex-meyus** [comment]
Same situation here - the device is paired, but no values are visible... 
Does somebody have an idea or workaround (except buy other sensors)?
Thanks :-)

**Comment by rolsch** [comment]
Hmm, no news for this device?
In the meantime the device changed from name TS0601 to SD500A

Adapter 1.8.11 - master branch

In the detail now the reading is:

ieee:0xa4c138dc68e74553
nwk:62111 (0xf29f)
model:[ZTH02](https://www.zigbee2mqtt.io/devices/ZTH02.html)
groups:

model:[ZTH02](https://www.zigbee2mqtt.io/devices/ZTH02.html)
description:Temperature and humidity sensor
modelZigbee:TS0601
type:EndDevice
nwk:62111
manuf id:4417
manufacturer:_TZE200_9yapgbuv
power:Battery
app version:72
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false

endpoint:1
profile:260
input clusters:genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
genBasic (0)
output clusters:genOta (25)
genTime (10)

**Comment by rolsch** [comment]
any hints?

**Comment by iNDeX999** [comment]
Same Problem here, would like to know how to use the adapter in iobroker

**Comment by arteck** [comment]
check new adapter version

**Comment by iNDeX999** [comment]
Hallo,

auch ein Update auf die 1.8.12 hat keine Besserung gebracht:

Es werden keine Daten angezeigt:

`{
  "zigbee.0.a4c138c95298a1b7": {
    "type": "device",
    "common": {
      "name": "WSD500A-T",
      "type": "ZTH02",
      "icon": "img/unknown.png",
      "color": null,
      "statusStates": {
        "onlineId": "zigbee.0.a4c138c95298a1b7.available"
      }
    },
    "native": {
      "id": "a4c138c95298a1b7"
    },
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1688387640264,
    "_id": "zigbee.0.a4c138c95298a1b7",
    "acl": {
      "object": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.available": {
    "type": "state",
    "common": {
      "name": "Available",
      "type": "boolean",
      "read": true,
      "write": false,
      "role": "state"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1688387641265,
    "_id": "zigbee.0.a4c138c95298a1b7.available",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.device_query": {
    "type": "state",
    "common": {
      "name": "Trigger device query",
      "type": "boolean",
      "read": false,
      "write": true,
      "role": "button"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1688387640277,
    "_id": "zigbee.0.a4c138c95298a1b7.device_query",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.link_quality": {
    "type": "state",
    "common": {
      "name": "Link quality",
      "type": "number",
      "read": true,
      "write": false,
      "role": "state",
      "min": 0,
      "max": 255
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1688387640277,
    "_id": "zigbee.0.a4c138c95298a1b7.link_quality",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.msg_from_zigbee": {
    "type": "state",
    "common": {
      "name": "Message from Zigbee",
      "type": "string",
      "read": true,
      "write": false,
      "role": "state"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1688387640277,
    "_id": "zigbee.0.a4c138c95298a1b7.msg_from_zigbee",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.send_payload": {
    "type": "state",
    "common": {
      "name": "Send to Device",
      "type": "string",
      "read": true,
      "write": true,
      "role": "state"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1688387640277,
    "_id": "zigbee.0.a4c138c95298a1b7.send_payload",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  }
}`

**Comment by arteck** [comment]
new try .. install new GIT version

**Comment by rolsch** [comment]
Hi arteck.

 

Wow, my device works now 😊

 



 



 



 

Regards

Roland

 

Von: arteck ***@***.***> 
Gesendet: Dienstag, 11. Juli 2023 07:03
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: rolsch ***@***.***>; State change ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] Tuya TS0601 -> _TZE200_9yapgbuv -> ZTH02_V1.1 -> temp/hum/battery Sensor (Issue #1612)

 

new try .. install new GIT version

**Comment by iNDeX999** [comment]
Good morning,

I installed the .14 Version, deleted the Device, repaired ... no Data

`{
  "zigbee.0.a4c138c95298a1b7": {
    "type": "device",
    "common": {
      "name": "WSD500A-T",
      "type": "ZTH02",
      "icon": "img/ZTH02.png",
      "color": null,
      "statusStates": {
        "onlineId": "zigbee.0.a4c138c95298a1b7.available"
      }
    },
    "native": {
      "id": "a4c138c95298a1b7"
    },
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244412,
    "_id": "zigbee.0.a4c138c95298a1b7",
    "acl": {
      "object": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.available": {
    "type": "state",
    "common": {
      "name": "Available",
      "type": "boolean",
      "read": true,
      "write": false,
      "role": "state"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140245363,
    "_id": "zigbee.0.a4c138c95298a1b7.available",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.battery_low": {
    "type": "state",
    "common": {
      "name": "Battery Status Low",
      "type": "boolean",
      "read": true,
      "write": false,
      "role": "indicator.lowbat"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244432,
    "_id": "zigbee.0.a4c138c95298a1b7.battery_low",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.battery_state": {
    "type": "state",
    "common": {
      "name": "State of the battery",
      "type": "string",
      "states": {
        "low": "low",
        "medium": "medium",
        "high": "high"
      },
      "read": true,
      "write": false,
      "role": "state"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244432,
    "_id": "zigbee.0.a4c138c95298a1b7.battery_state",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.device_query": {
    "type": "state",
    "common": {
      "name": "Trigger device query",
      "type": "boolean",
      "read": false,
      "write": true,
      "role": "button"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244432,
    "_id": "zigbee.0.a4c138c95298a1b7.device_query",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.humidity": {
    "type": "state",
    "common": {
      "name": "Humidity",
      "type": "number",
      "unit": "%",
      "read": true,
      "write": false,
      "role": "value.humidity",
      "min": 0,
      "max": 100
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244432,
    "_id": "zigbee.0.a4c138c95298a1b7.humidity",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.link_quality": {
    "type": "state",
    "common": {
      "name": "Link quality",
      "type": "number",
      "read": true,
      "write": false,
      "role": "state",
      "min": 0,
      "max": 255
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244429,
    "_id": "zigbee.0.a4c138c95298a1b7.link_quality",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.msg_from_zigbee": {
    "type": "state",
    "common": {
      "name": "Message from Zigbee",
      "type": "string",
      "read": true,
      "write": false,
      "role": "state"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244432,
    "_id": "zigbee.0.a4c138c95298a1b7.msg_from_zigbee",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.send_payload": {
    "type": "state",
    "common": {
      "name": "Send to Device",
      "type": "string",
      "read": true,
      "write": true,
      "role": "state"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244432,
    "_id": "zigbee.0.a4c138c95298a1b7.send_payload",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "zigbee.0.a4c138c95298a1b7.temperature": {
    "type": "state",
    "common": {
      "name": "Temperature",
      "type": "number",
      "unit": "°C",
      "read": true,
      "write": false,
      "role": "value.temperature"
    },
    "native": {},
    "from": "system.adapter.zigbee.0",
    "user": "system.user.admin",
    "ts": 1689140244432,
    "_id": "zigbee.0.a4c138c95298a1b7.temperature",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  }
}`

**Comment by rolsch** [comment]
See my screen shoot. I think i have a higher version!

I installed over expert option and use GIT, not the custom option with
url...

iNDeX999 ***@***.***> schrieb am Mi., 12. Juli 2023, 07:42:

**Comment by iNDeX999** [comment]
Moin, 
habe jetzt die zigbee.0 v1.8.16 installiert. Device gelöscht und neu verbunden:

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/53600396/f4cf46ae-fc82-43a9-8189-6f7aa1988912)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/53600396/17f524cf-9c1f-46a2-b00c-1a13139add3d)

leider keine Änderung

**Comment by rolsch** [comment]
iNDeX999, zeig mal deine Geräteinformation zum Device. Meine habe ich oben verlinkt.

**Comment by iNDeX999** [comment]
Moin, 

update heute auf 1.8.18 und das Teil zeigt jetzt Daten an! 

WSD500A-T
    Temperature 21.5 °C
    Humidity 69 %
    State of the battery high
    
Vielen Dank!
