### ISSUE TITLE
Add Tuya TS0601 temp & humidity sensor _TZE200_yjjdcqsq

### ISSUE THREAD

**Issue by boriswerner** [ioBroker/ioBroker.zigbee#1616]
Hi, would it be possible to add the sensor _TZE200_yjjdcqsq based on the external converter provided in this issue:
https://github.com/Koenkk/zigbee2mqtt/issues/14819
If not I am happy to provide further input.
Thank you very much for the great work with this adapter :-)

**Comment by asgothian** [comment]
You can test this yourself:

- Install the current test branch from my repository (https://github.com/asgothian/ioBroker.zigbee)
- generate a file  `_TZE200_yjjdcqsq.js` in your current zigbee adapters data folder (/opt/iobroker/iobroker-data/zigbee_0
- enter the filename `_TZE200_yjjdcqsq.js` as external converter
- restart the adapter
- watch the log to see if a message pops up in the log file that the external converter was applied

If it works as planned you should be able to use the device until the external converter is implemented. It should survive an update of the adapter / the zigbee-herdsman-converters library without issues, unless code changes in the zigbee-herdsman-converters invalidate the external converter.

A.

Implementing the device in the zigbee-herdsman-converters needs to be done in that project and will migrate to the zigbee adapter with a delay of 2 to 4 weeks when the library is updated.

**Comment by boriswerner** [comment]
Thanks for the fast response.
After restart of the instance the log showed:
`Apply converter from module: /opt/iobroker/iobroker-data/zigbee_0/_TZE200_yjjdcqsq.js`

Unfortunately there are no values shown. But I think I meanwhile somehow crashed the device itself. I played around adding _TZE200_yjjdcqsq to /opt/iobroker/node_modules/zigbee-herdsman-converters/devices/tuya.js to models where the code was equal to the external converter (found that process in some other thread). At one time I also received humidity and temp values in the tuya data-format in the msg_from_zigbee datapoint. Then I tested some other things and guess I broke something.

Currently I can't remove the device:
`Failed to remove Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)`
And the LED on the device is constantly on when not in pairing mode (I tried repairing but it only announces itself).

I currently only receive the following messages in msg_from_zigbee:

```
No converter available for 'TS0601_temperature_humidity_sensor' with cluster 'genTime' and type 'read'
{"type":"read","data":["localTime"],"linkquality":27,"groupID":0,"cluster":"genTime","meta":{"zclTransactionSequenceNumber":133,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}

```
```
No converter available for 'TS0601_temperature_humidity_sensor' with cluster 'genBasic' and type 'attributeReport'
{"type":"attributeReport","data":{"65506":56,"65508":1,"appVersion":72},"linkquality":27,"groupID":0,"cluster":"genBasic","meta":{"zclTransactionSequenceNumber":134,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}
```
Do I have to reinstall the regular version from the stable repository to switch back from your branch?

**Comment by Burki24** [comment]
hopefully solved with this PR: https://github.com/Koenkk/zigbee-herdsman-converters/pull/5234
