### ISSUE TITLE
YSR-MINI-01_dimmer does not update "State" value

### ISSUE THREAD

**Issue by Guest124** [ioBroker/ioBroker.zigbee#1617]
YSR-MINI-01_dimmer does not update all states value. Manually changing state correctly switches the state of the device.
Button "device_query" successfully updates device state with warning (15986) Failed to read state '"power_on_behavior"'of '0x....' after query with '{"code":134}'

**Comment by asgothian** [comment]
Code 134 is "Not supported", i.e. the converter for this device from the zigbee-herdsma-converters does not match the capability of the device
