### ISSUE TITLE
Questions about bindings and groups

### ISSUE THREAD

**Issue by ThorstenDtk** [ioBroker/ioBroker.zigbee#1621]
I have created different groups containing Hue E14 White Ambiance bulbs. Controlling the bulbs using the groups works fine. I also have Hue and Ikea Dimmer Switches. 
When I create a binding between a switch and a bulb I can control the bulb using the switch. No matter if it's a Hue or Tradfri switch.
But when I create a binding between a switch and a group nothing happens when I use the switch.
According to https://www.zigbee2mqtt.io/guide/usage/binding.html#devices:

![grafik](https://user-images.githubusercontent.com/35042154/208268496-6ad553a2-29d6-45f7-9a6e-09feebf3e61f.png)

What I don't get what device means in this context. Must the switch support it, or the bulbs contained in the group, or both?
And how do I figure out if the device supports this feature?

_Check the device specific page for more info_ - for none of the devices I found info about whether binding to group is supported.

**Comment by arteck** [comment]
the bulb is you problem.. not all support this

**Comment by ThorstenDtk** [comment]
If this was the case - then why does it work with DeConz?

**Comment by arteck** [comment]
we use directly the function from zigbee network.. i dont know how works it in deconz software
