### ISSUE TITLE
Error message after pairing of THS317-ET

### ISSUE THREAD

**Issue by woessmich** [ioBroker/ioBroker.zigbee#1622]
Hallo

Ich erhalte nach dem theoretisch erfolgreichen Pairing eines THS317-ET Thermometers folgende Fehlermeldung, verstehe aber nicht, was sie mir sagen will:

`Error: DeviceConfigure:Failed to DeviceConfigure.configure 0x3c6a2cfffed2f7b8 THS317-ET (TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.bind (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:24)
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/owon.js:185:29)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:146:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:124:17)). undefined
Interview successful: {"friendly_name":"0x3c6a2cfffed2f7b8","model":"THS317-ET","vendor":"OWON","description":"Temperature sensor","supported":true}`

Der Sensor wird angezeigt, überträgt aber keine Daten.
Ich habe noch einen zweiten gleichen Typs, dort werden Daten angezeigt.

Was könnte das Problem sein?
Danke

**Comment by asgothian** [comment]
Bitte den Sensor rauswerfen, neu paaren und dann während des Pairings sauber wach halten bis die Konfiguration durch ist.

A.

**Comment by woessmich** [comment]
Ich habe jetzt mehrmals beim Pairing versucht, durch sehr häufiges, etwas häufiges und weniger häufiges Drücken des Tasters den Sensor wachzuhalten... bis jeweils die Fehlermeldung kam. Kann es sein, dass der Sensor nicht konfiguriert werden "will"?

**Comment by asgothian** [comment]
Denkbar ist es. er muss aber konfiguriert werden - wie du an den fehlenden Daten des Sensors erkennst

**Comment by woessmich** [comment]
Nun ist es aber doch so, dass viele Sensoren den Parameter configured als false anzeigen.
So auch der andere funktionierende THS317-ET.
Den habe ich gerade nochmals ab- und wieder angelernt. Er bringt nach dem announcing nur Interview successful ohne die restliche Fehlermeldung.
Irgendwas passt nicht.

**Comment by asgothian** [comment]
Wie hast du den "Abgelernt" ? im ioBroker gelöscht ?

Die Anzeige "configured" ist meiner Meinung nach noch buggy - da würde ich erst einmal wenig drauf geben

A.

**Comment by woessmich** [comment]
Ja, im Adapter, mit der Mülltonne. Wobei mir nicht ganz klar ist, ob ich dazu das Gerät aufwecken muss (ich habe mal die Taster gedrückt), ob es eine andere Möglichkeit gibt und was anders wäre, wenn ich das Löschen erzwinge. Ablernen wie bei Z-Wave am Gerät scheint es ja nicht zu geben. Oder vielleicht nicht bei allen Geräten.

**Comment by woessmich** [comment]
Ich habe noch etwas herausgefunden, was mich glauben lässt, dass das Problem nicht am Sensor liegt. Meine Alexa Echo Kugel koppelt den Sensor einwandfrei und die App zeigt such eine Temperatur.
Das Problem muss also irgendwie auf der anderen Seite liegen.

**Comment by asgothian** [comment]
Kannst du bitte versuchen das gerät über den ioBroker neu zu konfigurieren ?

- Gerät wach halten
- diesen Knopf auf der Gerätekachel nutzen
<img width="162" alt="Screen Shot 2022-12-22 at 19 30 23 " src="https://user-images.githubusercontent.com/45667167/209202874-bc509b42-9932-4765-82b4-6497d88c2b75.png">

- Schauen was im Log auftaucht und ob sich das Verhalten ändert.
A.

**Comment by woessmich** [comment]
Hi, Danke fürs dranbleiben. Sieht folgendermassen aus:

`DeviceConfigure:Failed to DeviceConfigure.configure 0x3c6a2cfffed2f7b8 THS317-ET (TypeError: Cannot read properties of undefined (reading 'bind') at Object.bind (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:24) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/owon.js:185:29) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:146:32) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Promise.all (index 0) at Commands.reconfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:483:21)) `

Zweimal durchgeführt, beides Mal gleiche Meldung.

Mir ist schon bewusst, dass das ganze superkomplex ist, aber der Zigbee Adapter funktioniert um Welten besser als der Deconz, den ich vorher im Einsatz hatte. Nicht mehr mit diesem Sensor, leider, daher kein Vergleich. Vielleicht fahre ich ihn nochmal hoch, wenn es dem Erkenntnisgewinn dient. 
Ich bin nur verblüfft, dass zweimal das gleiche Gerät (Ungleiche Firmware, ok) unterschiedlich reagiert und ausgerechnet Alexa damit klar kommt.
Ausser, dass es bei mir funktioniert, habe ich ein wenig die Hoffnung, dass wir insgesamt stetig Fortschritte damit machen.

**Comment by chris299** [comment]
@asgothian  ich habe das auch gemacht und sehe exakt das gleiche im Log:
```
DeviceConfigure:Failed to DeviceConfigure.configure 0x3c6a2cfffed2f74b THS317-ET (TypeError: Cannot read properties of undefined (reading 'bind') at Object.bind (/usr/local/iobroker/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:24) at Object.configure (/usr/local/iobroker/node_modules/zigbee-herdsman-converters/devices/owon.js:185:29) at DeviceConfigure.doConfigure (/usr/local/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:146:32) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Promise.all (index 0) at Commands.reconfigure (/usr/local/iobroker/node_modules/iobroker.zigbee/lib/commands.js:483:21))
```

**Comment by woessmich** [comment]
@asgothian Da ich zwei solche Sensoren habe, einer der geht und einer der nicht geht: Kann ich irgendwie die Antworten der Sensoren loggen, damit man die Unterschiede bei den Antworten der Geräte beim Konfigurieren ansehen kann?

**Comment by asgothian** [comment]
> @asgothian Da ich zwei solche Sensoren habe, einer der geht und einer der nicht geht: Kann ich irgendwie die Antworten der Sensoren loggen, damit man die Unterschiede bei den Antworten der Geräte beim Konfigurieren ansehen kann?

Meines Wissens nur wenn du tief einsteigst. (Debug und Zigbee-Herdsman-Debug aktiv und dann in dem Log die entsprechenden Meldungen isolieren.



> Ich glaube nicht, dass es am "wach bleiben" hängt, weil ich den den Fehler im Pairing direkt nach der "announced itself" message sehe.

Du hast an der Stelle durch den Code einen Delay von bis zu 2 Sekunden. Beim Thema Stromsparen etc. sind das Welten.

**Comment by woessmich** [comment]
Hallo
Ich habe den Zigbee Adapter gerade auf die neueste Version 1.8.9 aktualisiert. Nach dem Ab- und wieder Anlernen des Sensors war das interviewen ohne die Fehlermeldung und jetzt erhalte ich auch die Temperaturen.
Danke für's fixen, was auch immer der Hintergrund war.

**Comment by chris299** [comment]
@asgothian bei mir funktioniert es mit Adapter Version 1.8.9 ebenfalls einwandfrei.
