### ISSUE TITLE
Zigbee connections lost after several hours/days - coordinator CC2530 with tcp connection

### ISSUE THREAD

**Issue by FillyderErste** [ioBroker/ioBroker.zigbee#1624]
Hi guys I kindly ask for help to get rid of the disconnections in my Zigbee network. 
All of a sudden, all Zigbee connections get lost and the adapter shows no connection. 
![grafik](https://user-images.githubusercontent.com/104793346/208988861-67bd7d75-88c0-4f50-a8e8-a18ff4cb819d.png)
![grafik](https://user-images.githubusercontent.com/104793346/208995163-cf0e5681-fc42-4e76-8ecb-0a7eb53f7afa.png)
Sometimes the connection is lost after few hours, sometimes the network is working for 1 week.
I have to do the following steps as mentioned in another issue to re-connect the adapter/coordinator --> https://github.com/ioBroker/ioBroker.zigbee/issues/1035#issuecomment-802308736
1.     stop the zigbee adapter
2.     Unplug the coordinator
3.     Wait 30 seconds
4.     Plug in the coordinator
5.     Start the zigbee adapter
But then the restored connection get lost again after few hours/days.
The error in the log is always the same. The Log file from start up (new container/adapter) until errors occure is attached, a simple restart of the adapter is also shown at the end of the log, perhaps it is helpfull.

My set-up:
iobroker Docker Container "buanet" on Synology DiskStation - Since I have trouble with Zigbee I use a separate container only for Zigbee-Network. It was created new for each trial (see below).
Zigbee coordinator hardware = CC2530 board, connected via TCP (ESP8266 with Tasmota zbbridge)
Zigbee devices = 2 plugs, 1 bulb (will be increased, of course, if the netweork would be stable)

I tried until today 
- 2 CC2530 borads with 2 different WEMOS D1 mini as wifi bridge with different tasmota zbbridge software revisions
- latest Z-Stack versions 1.2 + 3.0.x  for CC2530 from koenkk https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator
- Flashing the CC2530 with CCloader and CCDebugger
- Several Zigbee Adapter versions in iobroker
- pairing of 1/3 devices to see, if there is any problem with the plugs or bulb

[Log_Zigbee.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10280747/Log_Zigbee.txt)

**Comment by asgothian** [comment]
There is nothing we can do from the zigbee adapter. You may open an issue at the zigbee-herdsman project, but i suspect you will be pointed towards a coordinator firmware bug on the cc2530/cc2531 boards which causes them to block connection.

Also - if the network connection is via WiFi it is not unlikely that packet loss on the wifi connection is making this issue worse. For this reason, the guys at zigbee2mqtt.io discourage use of wifi connected coordinators.
