### ISSUE TITLE
TS0505B: has only brightness from 0 to 100 but should have 0 to 254

### ISSUE THREAD

**Issue by disaster123** [ioBroker/ioBroker.zigbee#1625]
see https://www.zigbee2mqtt.io/devices/TS0505B.html - it has brightness control 0 to 254 but in iobroker it only supports 0 to 100. My 18W tuya lamps only consumes 5-6W and are not bright enough.

Thanks!

**Comment by asgothian** [comment]
This seems to be an error with the converter. Brightness in the converter is always between 0 and 100% and is internally converted to %

Please add the IEEE of the device to the state zigbee.0.info.debugmessages, change the brightness and check the log for Messages with the keyword "ELEVATED"

Please also test the following:
- turn on the lamp
- set the brightness to 10
- set the brightness_move value to 50
- wait 30 seconds and check the power consumption of the lamp

A.

**Comment by disaster123** [comment]
OK i did that - power consumption stays at 5-6W.

Log Messages:
![image](https://user-images.githubusercontent.com/861558/209185612-9e6bd83f-f630-4733-a702-7c09523b84a0.png)

**Comment by asgothian** [comment]
- please dont post log entries as pictures.
- Please post the complete entries. Take out the filter for the IEEE and add one for ELEVATED to see all of them.
- You should see the value the lamp reports internally and which value is generated for the state in turn.

A.
P.S. it wouldn't be the first time that a TuYa device does something funky and requires a special converter to actually work as desired by the manufacturer. Welcome to the Hell that is TuYa.

**Comment by disaster123** [comment]
```

zigbee.1
2022-12-22 20:07:00.331	warn	ELEVATED Change state 'brightness_move' at device 0xa4c1383329cc30db type 'TS0505B'

zigbee.1
2022-12-22 20:06:52.274	warn	ELEVATED Change state 'brightness' at device 0xa4c1383329cc30db type 'TS0505B'
```

here copy and paste the entries - only filter was ELEVATED.

No i don't see any value the lamp internally reports.

@tuya - sadly no other options for high lumen devies except hue which is 50 € per device...

**Comment by disaster123** [comment]
even a filter on "zigbee.1" does not sure more...

**Comment by disaster123** [comment]
I was able to get those as well:
```


zigbee.1 | 2022-12-22 20:09:55.632 | warn | ELEVATED Change state 'brightness_move' at device 0xa4c1383329cc30db type 'TS0505B'
-- | -- | -- | --
zigbee.1 | 2022-12-22 20:09:55.629 | warn | ELEVATED: User stateChange zigbee.1.a4c1383329cc30db.brightness_move {"val":50,"ack":false,"ts":1671736195628,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1671727514371}
zigbee.1 | 2022-12-22 20:09:42.185 | warn | ELEVATED Change state 'brightness' at device 0xa4c1383329cc30db type 'TS0505B'
zigbee.1 | 2022-12-22 20:09:42.183 | warn | ELEVATED: User stateChange zigbee.1.a4c1383329cc30db.brightness {"val":10,"ack":false,"ts":1671736182182,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1671736012271}


```

**Comment by asgothian** [comment]
you should get a few more if you set brightness_move back to 0

**Comment by disaster123** [comment]
OK i get a message:
```
ELEVATED publishToState: message received '{"brightness":254}' from device a4c1383329cc30db type 'TS0505B'
```

so the conversion works fine... no idea why a 18W bulb uses only 5-6w and far too low.

**Comment by asgothian** [comment]
That should be a device issue. As I wrote above - not uncommon.

I use two high lumen bulbs, one Ikea, one Philips, if I remember correctly. The Philips is more expensive but works better than the Ikea.

none the less - closing this.
