### ISSUE TITLE
Probleme mit MOSZB-140 

### ISSUE THREAD

**Issue by hakelgg** [ioBroker/ioBroker.zigbee#1627]
MOSZB-140 ist bis Zigbee 1.7.6 gut erkannt worden.
mit Update auf 1.8.6 und Höher wird er nicht mehr erkannt

**Comment by asgothian** [comment]
Bitte mehr details:
- Info-Seite des Gerätes (Kachel umdrehen, blaues i klicken)
- was genau passiert mit einem Gerät welches angelernt ist (unter 1.7.6) nach einem update auf 1.8.6
- was genau passiert wenn unter 1.8.6 oder höher das Gerät angelernt werden soll

A.

**Comment by hakelgg** [comment]
Hallo
vielen Dank für die schnelle Reaktion.
Ich habe von den Bewegungsmeldern MOSZB-140  5 Stück im Einsatz.
Welche dann nach dem Update auf 1.8.9 nicht mehr ihren Dienst versahen.
Das Bild in den Kacheln war nach dem Update nur noch ein Fragezeichen.
Ich habe einen der fünf Bewegungsmelder gelöscht und versucht neu anzulernen.
Beim Anlernen wurde der MOSZB-140 erkannt, konnte aber nicht richtig zugeordnet werden
(anscheinend ein Fehler in der Datenbank).
Ähnliches Verhalten hatte ich schon einmal beim Update von 1.7.5 auf 1.7.6 Beta beobachtet.
In der stabilen Version 1.7.6 trat der Fehler nicht mehr auf
Für eine genaue Fehleranalyse hatte ich leider keine Zeit, denn es war ja Weinachten. 
Ich habe schnell ein Backup der letzten Woche wieder eingespielt. 
Das Backup im Iobroker wollte leider auch nicht so richtig.
Ein Bewegungsmelder aus der gleichen Baureihe ein MOSZB-141 ist von dem Fehler nicht betroffen.
Eine gewisse Professionalität meinerseits ist hier nicht zu erkennen aber ich werde mich bessern.
VG
Günter

**Comment by asgothian** [comment]
Fehlt: Bild der Info-Seite der betroffenen BWM.

**Comment by hakelgg** [comment]
![image](https://user-images.githubusercontent.com/120252980/209645924-225ec42c-5a2b-4095-974e-692a77a86612.png)

**Comment by hakelgg** [comment]
Info unter 1.7.6

**Comment by asgothian** [comment]
Danke für das Bild - leider müsstest du noch einmal eine genaue Analyse machen:

- NodeJS Version, Admin Version und JS Controller version aufschreiben
- von GitHub die 1.8.10 installieren
- Einen BWM Ablernen und neu anlernen
- Log posten (Als Text in Code tags, nicht als Bild)

A

**Comment by hakelgg** [comment]
Hast Du Hoffnung, das es mit 1.8.10 schon klappen könnte?
Traue meinen Backups noch nicht so über den Weg

**Comment by asgothian** [comment]
Nein. Es muss heraus gefunden werden an welcher Stelle es schief geht. Das es zufällig in der 1.8.10 geht und in der 1.8.9 nicht halte ich für extrem unwahrscheinlich, insbesondere da die meisten Unterschiede zwischen den Versionen von mir stammen.

Allerdings kannst du über den Experten Modus im Admin durchaus gezielt die 1.7.6 installieren, auch wenn du bereits eine neuere Version hast - du musst also nicht unbedingt per Backup zurückstellen

A.

**Comment by hakelgg** [comment]
Hoffentlich ist was brauchbares dabei


Admin: 6.3.5
Node.js: v14.21.1
js-controller: 4.024
NPM: v6.14.17



Pairing time left
Pairing time left: 1
Pairing time left: 2
Pairing time left: 3
Pairing time left: 4
Pairing time left: 5
Pairing time left: 6
Pairing time left: 7
Pairing time left: 8
Pairing time left: 9
Pairing time left: 10
Pairing time left: 11
Pairing time left: 12
Pairing time left: 13
Pairing time left: 14
Pairing time left: 15
Pairing time left: 16
Pairing time left: 17
Pairing time left: 18
Pairing time left: 19
Pairing time left: 20
Pairing time left: 21
Pairing time left: 22
Pairing time left: 23
Interview failed: 0x0015bc001a0239b4
Error: Failed to interview '0x0015bc001a0239b4', device has not successfully been paired. undefined. undefined
Pairing time left: 24
Pairing time left: 25
Pairing time left: 26
Pairing time left: 27
Pairing time left: 28
Pairing time left: 29
Pairing time left: 30
Pairing time left: 31
Pairing time left: 32
Pairing time left: 33
New device joined '0x0015bc001a0239b4' model MOSZB-140
Device '0x0015bc001a0239b4' announced itself
Interview started: 0x0015bc001a0239b4
Pairing time left: 34
Pairing time left: 35
Pairing time left: 36
Pairing time left: 37
Pairing time left: 38
Pairing time left: 39
Pairing time left: 40
Pairing time left: 41
Pairing time left: 42
Pairing time left: 43
Pairing time left: 44
Pairing time left: 45
Pairing time left: 46
Pairing time left: 47
Pairing time left: 48
Pairing time left: 49
Pairing time left: 50
Pairing time left: 51
Pairing time left: 52
Pairing time left: 53
Pairing time left: 54
Pairing time left: 55
Pairing time left: 56
Pairing time left: 57
Pairing time left: 58
Pairing time left: 59
Pairing time left: 60
Pairing started 


model:MOSZB-140
description:Motion sensor
modelZigbee:MOSZB-140
type:EndDevice
nwk:54980
manuf id:4117
manufacturer:frient A/S
power:Battery
zcl version:1
date code:20220305 06:23
interviewed:false
configured:false
endpoint:1
profile:49353
input clusters:genIdentify (3)
genScenes (5)
genOnOff (6)
endpoint:34
profile:260
input clusters:genBasic (0)
genIdentify (3)
msOccupancySensing (1030)
endpoint:35
profile:260
input clusters:genBasic (0)
genPowerCfg (1)
genIdentify (3)
genBinaryInput (15)
genPollCtrl (32)
ssIasZone (1280)
output clusters:genIdentify (3)
genTime (10)
genOta (25)
endpoint:38
profile:260
input clusters:genBasic (0)
genIdentify (3)
msTemperatureMeasurement (1026)
endpoint:39
profile:260
input clusters:genBasic (0)
genIdentify (3)
msIlluminanceMeasurement (1024)
endpoint:40
profile:260
input clusters:genBasic (0)
genIdentify (3)
msOccupancySensing (1030)
endpoint:41
profile:260
input clusters:genBasic (0)
genIdentify (3)
msOccupancySensing (1030)

**Comment by asgothian** [comment]
Jein - du hast einen Fehler beim Einbinden. Er sagt 

`Error: Failed to interview '0x0015bc001a0239b4', device has not successfully been paired. undefined. undefined`

Das deutet darauf hin das das Gerät beim Interview die Kommunikation eingestellt hat. Bitte mal wach halten während des Pairings.

A.

**Comment by hakelgg** [comment]
Das würde bedeuten, das nach dem Software Update von 1.7.6 --> 1.8.3.... alle Bewegungsmelder erneut angelernt (paaring) werden müssen. Alle 5 BWM sind nicht mehr aktiv.

**Comment by asgothian** [comment]
Nicht mehr aktiv = dargestellt mit ?, oder nur keine Aktualisierung an den Objekten ?

**Comment by hakelgg** [comment]
Das Bild in den Kacheln war nach dem Update nur noch ein Fragezeichen.
Die Informationen
Occupancy
Temperature
Illuminancy
.....
waren nicht mehr aktiv.
Die letzte Änderungen in den Objekten waren vor dem Update

**Comment by asgothian** [comment]
Fangen wir mal Scheibenweise an.

Kannst du mal einen versuchen neu anzumelden und ihn dabei wach zu halten um zu schauen ob es dann passt oder nicht (Datenpunkte da, Aktualisierung auch) ?

A.

**Comment by hakelgg** [comment]
ist es möglich für den BWM MOSZB-140 den Quellcode aus dem Stand 1.7.6 oder 1.7.5 mit dem Quellcode von 1.8.9 zu vergleichen.
Beim Update von 1.7.6 auf 1.8.3.... werden ja die vor her erkannten MOSZB- 140 nicht mehr akzeptiert.

**Comment by asgothian** [comment]
Ist es, ist aber nicht ganz einfach:
Du musst 
- von der 1.7.6 aus der package.json heraussuchen welche exakte Version der zigbee-herdsman-converters genutzt werden
- im Zigbee-Herdsman-converters projekt den Code Stand für genau diese Version heraus finden
- Im Zigbee-Herdsman-converters Projekt heraus finden was sich zwischen diesem Stand und heute geändert hat (Einschätzung: Reichlich)
- Bewerten was davon realistisch ist.

**Comment by hakelgg** [comment]
Klingt nach Arbeit.
- die Änderung der Softwarestände beim Zigbee Adapter mache ich immer mit Bauchschmerzen. 
- Irgendetwas geht immer schief.
- Um aber den Adapter auf den aktuellen Stand zu halten sollte eine Lösung her.

" Kannst du mal einen versuchen neu anzumelden und ihn dabei wach zu halten um zu schauen ob es dann passt oder nicht (Datenpunkte da, Aktualisierung auch) ?"
- das hatte ich auch schon versucht, aber keine Lösung
- welche Möglichkeiten habe ich noch?

**Comment by asgothian** [comment]
> Klingt nach Arbeit.
> 
> * die Änderung der Softwarestände beim Zigbee Adapter mache ich immer mit Bauchschmerzen.
> * Irgendetwas geht immer schief.
> * Um aber den Adapter auf den aktuellen Stand zu halten sollte eine Lösung her.
> 
> " Kannst du mal einen versuchen neu anzumelden und ihn dabei wach zu halten um zu schauen ob es dann passt oder nicht (Datenpunkte da, Aktualisierung auch) ?"
> 
> * das hatte ich auch schon versucht, aber keine Lösung
> * welche Möglichkeiten habe ich noch?

Zum Thema wachhalten - ist es dir gelungen den BWM zu pairen ohne das die weiter oben erkennbare Fehlermeldung kommt ?

A.

**Comment by hakelgg** [comment]
Leider nein, bekomme den BWM nicht gepairt.
Das gleiche Verhalten hatte ich schon einmal beim Softwarestand 1.7.6 Beta.
Bin dann aber wieder auf 1.7.5 zurückgegangen.
Als 1.7.6 stable freigegeben war, gab es dieses Problem nicht mehr.

**Comment by hakelgg** [comment]
Hallo
habe noch einen raspberrypi liegen.
Werde mir noch einen SONOFF Zigbee 3.0 USB Dongle Plus zulegen.
Auf dem System können wir dann testen.
Könntest Du mir eine sinnvolle Testanleitung zukommen lassen?

**Comment by hakelgg** [comment]
SONOFF Zigbee 3.0 USB Dongle Plus ist eingetroffen
Habe auf zweitem System von 1.7.6 auf 1.8.9 geupdatet

$ iobroker upgrade zigbee@1.8.9 --debug

Update zigbee from @1.7.6 to @1.8.9

host.70-iobroker-pi Adapter "system.adapter.zigbee.0" is stopped.

NPM version: 6.14.17

Installing iobroker.zigbee@1.8.9... (System call)

> @serialport/bindings-cpp@10.8.0 install /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings-cpp> node-gyp-build

> @serialport/bindings-cpp@10.8.0 install /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/bindings-cpp> node-gyp-build

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ iobroker.zigbee@1.8.9

added 22 packages from 92 contributors, removed 24 packages, updated 6 packages and moved 2 packages in 43.169s

73 packages are looking for funding run `npm fund` for details

Update "system.adapter.zigbee.0"

upload [322] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/adapter-settings.js adapter-settings.js application/javascript

upload [300] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Bitron_AV201021A.png img/Bitron_AV201021A.png image/png

upload [250] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/bitron_motion.png img/bitron_motion.png image/png

upload [200] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/hive.png img/hive.png image/png

upload [150] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/lh_32Zb.png img/lh_32Zb.png image/png

upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_amaze.png img/philips_amaze.png image/png

upload [90] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_ambiance.png img/philips_hue_ambiance.png image/png

upload [80] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_e27_ambiance.png img/philips_hue_e27_ambiance.png image/png

upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_ltc021.png img/philips_hue_ltc021.png image/png

upload [60] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/plug.png img/plug.png image/png

upload [50] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/sensor_philipshue.png img/sensor_philipshue.png image/png

upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/smartthings_motion.png img/smartthings_motion.png image/png

upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ts0203.png img/ts0203.png image/png

upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/tuya_tyzs1l.png img/tuya_tyzs1l.png image/png

upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/unavailable.png img/unavailable.png image/png

upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/unknown.png img/unknown.png image/png

upload [17] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/wemo.png img/wemo.png image/png

upload [16] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/xiaomi_plug_eu.png img/xiaomi_plug_eu.png image/png

upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/xiaomi_wireless_switch.png img/xiaomi_wireless_switch.png image/png

upload [14] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_e27.png img/zbt_e27.png image/png

upload [13] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_e27_rgbw.png img/zbt_e27_rgbw.png image/png

upload [12] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_led_panel.png img/zbt_led_panel.png image/png

upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_smart_switch.png img/zbt_smart_switch.png image/png

upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zemismart_sw2.png img/zemismart_sw2.png image/png

upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/index.html index.html text/html

upload [8] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/index_m.html index_m.html text/html

upload [7] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/moment.min.js moment.min.js application/javascript

upload [6] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/shuffle.min.js shuffle.min.js application/javascript

upload [5] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/tab_m.html tab_m.html text/html

upload [4] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/vis-network.min.css vis-network.min.css text/css

upload [3] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/vis-network.min.js vis-network.min.js application/javascript

upload [2] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/words.js words.js application/javascript

upload [1] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/zigbee.png zigbee.png image/png

upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/zigbee.svg zigbee.svg image/svg+xml

host.70-iobroker-pi Adapter "system.adapter.zigbee.0" is started

Process exited with code 0

Schließen wenn fertig

??????????????????????????????
Geräteinformation von einem anderem Sensor gleichen Typs 
aber  nicht mehr erkannten Sensor

model:MOSZB-140
description:Motion sensor
modelZigbee:MOSZB-140
type:EndDevice
nwk:25235
manuf id:4117
manufacturer:frient A/S
power:Battery
zcl version:1
date code:20220305 05:57
interviewed:true
configured:true
endpoint:1
profile:49353
input clusters:genIdentify (3)
genScenes (5)
genOnOff (6)
endpoint:34
profile:260
input clusters:genBasic (0)
genIdentify (3)
msOccupancySensing (1030)
endpoint:35
profile:260
input clusters:genBasic (0)
genPowerCfg (1)
genIdentify (3)
genBinaryInput (15)
genPollCtrl (32)
ssIasZone (1280)
output clusters:genIdentify (3)
genTime (10)
genOta (25)
endpoint:38
profile:260
input clusters:genBasic (0)
genIdentify (3)
msTemperatureMeasurement (1026)
endpoint:39
profile:260
input clusters:genBasic (0)
genIdentify (3)
msIlluminanceMeasurement (1024)
endpoint:40
profile:260
input clusters:genBasic (0)
genIdentify (3)
msOccupancySensing (1030)
endpoint:41
profile:260
input clusters:genBasic (0)
genIdentify (3)
msOccupancySensing (1030)


Kopplungsversuch mit wach halten
Pairing time left
Pairing time left: 1
Pairing time left: 2
Pairing time left: 3
Pairing time left: 4
Pairing time left: 5
Pairing time left: 6
Pairing time left: 7
Pairing time left: 8
Interview failed: 0x0015bc001a0239b4
Error: Failed to interview '0x0015bc001a0239b4', device has not successfully been paired. undefined. undefined
Pairing time left: 9
Pairing time left: 10
Pairing time left: 11
Pairing time left: 12
Pairing time left: 13
Pairing time left: 14
Pairing time left: 15
Pairing time left: 16
Pairing time left: 17
Pairing time left: 18
Pairing time left: 19
Pairing time left: 20
Pairing time left: 21
Pairing time left: 22
Pairing time left: 23
Pairing time left: 24
Pairing time left: 25
Pairing time left: 26
Pairing time left: 27
Device '0x0015bc001a0239b4' announced itself
Pairing time left: 28
Interview started: 0x0015bc001a0239b4
Pairing time left: 29
Pairing time left: 30
Pairing time left: 31
Pairing time left: 32
Pairing time left: 33
Pairing time left: 34
Pairing time left: 35
Pairing time left: 36
Pairing time left: 37
Pairing time left: 38
Pairing time left: 39
Pairing time left: 40
Pairing time left: 41
Pairing time left: 42
Pairing time left: 43
Pairing time left: 44
Pairing time left: 45
Pairing time left: 46
Pairing time left: 47
Pairing time left: 48
Pairing time left: 49
Pairing time left: 50
Pairing time left: 51
Device '0x0015bc001a0239b4' announced itself
Pairing time left: 52
Pairing time left: 53
Pairing time left: 54
Pairing time left: 55
Pairing time left: 56
Pairing time left: 57
Pairing time left: 58
Pairing time left: 59
Pairing time left: 60
Pairing time left: 61
Pairing time left: 62
Pairing time left: 63
Pairing time left: 64
Pairing time left: 65
Pairing time left: 66
Pairing time left: 67
Pairing time left: 68
Pairing time left: 69
Pairing time left: 70
Pairing time left: 71
Pairing time left: 72
Pairing time left: 73
Pairing time left: 74
Pairing time left: 75
Pairing time left: 76
Pairing time left: 77
Pairing time left: 78
Pairing time left: 79
Pairing time left: 80
Pairing time left: 81
Pairing time left: 82
Pairing time left: 83
Pairing time left: 84
Pairing time left: 85
Pairing time left: 86
Pairing time left: 87
Pairing time left: 88
Pairing time left: 89
Pairing time left: 90
Pairing time left: 91
Interview failed: 0x0015bc001a0239b4
Error: Failed to interview '0x0015bc001a0239b4', device has not successfully been paired. undefined. undefined
Pairing time left: 92
Pairing time left: 93
Pairing time left: 94
Pairing time left: 95
Pairing time left: 96
Pairing time left: 97
Pairing time left: 98
Pairing time left: 99
Pairing time left: 100
Pairing time left: 101
Pairing time left: 102
Pairing time left: 103
Pairing time left: 104
Pairing time left: 105
Pairing time left: 106
Pairing time left: 107
Pairing time left: 108
Pairing time left: 109
Pairing time left: 110
Pairing time left: 111
Pairing time left: 112
Pairing time left: 113
Interview started: 0x0015bc001a0239b4
Device '0x0015bc001a0239b4' announced itself
Pairing time left: 114
Pairing time left: 115
Pairing time left: 116
Pairing time left: 117
Pairing time left: 118
Pairing time left: 119
Pairing time left: 120
Pairing started 

Wünsch Allen ein gesundes neues Jahr
Guenter

**Comment by DeVesen** [comment]
Hallo,

bei mir habe ich auch das Problem das der BWM, selbes Model, nicht richtig erkannt wird.

![383C9503-0BA9-4C95-A8B4-CC759C2B0159](https://user-images.githubusercontent.com/16238591/210184637-5c5a0db4-d90b-4925-ad2e-99c4508dcea4.jpeg)
![DDF06A5C-A818-40BF-BCA8-C5613546C4C5](https://user-images.githubusercontent.com/16238591/210184731-a8a0449a-8fdf-46aa-ae30-8dddaea3596f.jpeg)
![9D549320-7158-4A2A-9476-4499F7322EAE](https://user-images.githubusercontent.com/16238591/210184733-3ded7f7e-6106-49dd-8cf6-8f9c6a475b0d.jpeg)
![AB1BCCBA-891F-42EA-BF48-EC23516CD774](https://user-images.githubusercontent.com/16238591/210184734-fa1a2cac-3c21-4e90-bb3d-afbf27b1c6a6.jpeg)
![C2986D87-0D0F-41C1-8C53-FCB843B5FD7E](https://user-images.githubusercontent.com/16238591/210184737-5f95557c-e466-4243-97da-7af9f05fbd3d.jpeg)


 **ConBee II Firmware:** 26780700

![766E7689-A184-453E-A992-C7F462EE849D](https://user-images.githubusercontent.com/16238591/210184753-2882fc33-5d57-463b-b1a1-292e80cc81a4.jpeg)
![DF053120-E49A-4819-8605-3259C409FA7A](https://user-images.githubusercontent.com/16238591/210184754-86f8e7fd-4cb3-4087-880b-00fc1163ead3.jpeg)
![0EAFB020-6F35-4A31-A1BA-03C078A25692](https://user-images.githubusercontent.com/16238591/210184808-09356cb7-9f98-42d9-8430-b359765922d0.jpeg)


**Meldung wenn Adapter neu gestartet ist:**
![AA515209-9B43-4A92-9508-500A1D32047E](https://user-images.githubusercontent.com/16238591/210185671-a0e9e7cb-1fcc-42bc-82c1-61ee01ae21e9.jpeg)


**Kopplungsversuch:**
Pairing time left
Pairing time left: 1
Pairing time left: 2
Pairing time left: 3
Pairing time left: 4
Pairing time left: 5
Pairing time left: 6
Pairing time left: 7
Pairing time left: 8
Pairing time left: 9
Pairing time left: 10
Pairing time left: 11
Pairing time left: 12
Pairing time left: 13
Pairing time left: 14
Pairing time left: 15
Pairing time left: 16
Pairing time left: 17
Pairing time left: 18
Pairing time left: 19
Pairing time left: 20
New device joined '0x0015bc001a0238e4' model MOSZB-140
Pairing time left: 21
Interview successful: {"friendly_name":"0x0015bc001a0238e4","model":"MOSZB-140","vendor":"Develco","description":"Motion sensor","supported":true}
Pairing time left: 22
Pairing time left: 23
Pairing time left: 24
Pairing time left: 25
Pairing time left: 26
Pairing time left: 27
Pairing time left: 28
Pairing time left: 29
Pairing time left: 30
Pairing time left: 31
Pairing time left: 32
Pairing time left: 33
Pairing time left: 34
Pairing time left: 35
Error: Device 0x0015bc001a0238e4 "undefined" not described in statesMapping.. undefined
Interview started: 0x0015bc001a0238e4
Pairing time left: 36
Pairing time left: 37
Pairing time left: 38
Pairing time left: 39
Pairing time left: 40
Pairing time left: 41
Pairing time left: 42
Pairing time left: 43
Pairing time left: 44
Pairing time left: 45
Pairing time left: 46
Pairing time left: 47
Pairing time left: 48
Pairing time left: 49
Pairing time left: 50
Pairing time left: 51
Pairing time left: 52
Pairing time left: 53
Pairing time left: 54
Pairing time left: 55
Pairing time left: 56
Pairing time left: 57
Pairing time left: 58
Pairing time left: 59
Pairing time left: 60
Pairing started

**Meldung nach Koppelungsversuch:**
Error: Failed to touchlinkReset Error: Touchlink operation already in progress
    at Touchlink.lock (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/touchlink.ts:20:19)
    at Touchlink.factoryResetFirst (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/touchlink.ts:110:14)
    at Controller.touchlinkFactoryResetFirst (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:211:31)
    at ZigbeeController.touchlinkReset (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:923:33)
    at Commands.touchlinkReset (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:155:31)
    at Commands.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:56:30)
    at Zigbee.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:14:48)
    at Zigbee.emit (node:events:525:35)
    at Zigbee.emit (node:domain:489:12)
    at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5824:34). undefined
Touchlink reset started 

Gruß und ein frohes Neues 😀

**Comment by asgothian** [comment]
du musst es auch schon richtig machen. Du hast sowohl Touchlinkreset als auch das Netz aufgemacht. Das passt nicht.
Entweder- Oder. Nicht beides.

A.

**Comment by arteck** [comment]
@DeVesen bitte npm und nodejs richtig ziehen.. 

@hakelgg bitte version 1.8.10 installieren .. sollte es immer noch nicht gehen neues issue biite

**Comment by JorinL** [comment]
Hilft das hier eventuell?

https://github.com/Koenkk/zigbee2mqtt/issues/14277#issuecomment-1288183169

Bei denen geht es wieder ;-)
