### ISSUE TITLE
Up/down position swapped at TS130F Curtain/blind switch

### ISSUE THREAD

**Issue by mdiether** [ioBroker/ioBroker.zigbee#1628]
Hello, after the update to version 1.8.9, the positions for up and down are reversed on the TS130F curtain/blind switch. The shutter goes up at 100 and down at 0. Can you change that? Or do I have the possibility to change the behavior?

Many greetings

Mario

**Comment by asgothian** [comment]
Duplicate Issue of #1610. Analysis needed.
