### ISSUE TITLE
UseeLink SM-0306E-2W: Failed to DeviceConfigure.configure

### ISSUE THREAD

**Issue by thps1990** [ioBroker/ioBroker.zigbee#1629]
Hi there,

i recently bought a UseeLink SM-0306E-2W and it works fine with my iobroker instance and TI Launch CC26X2R1 board.

The only thing is, that this device spams my iobroker log with these messages:

Error: DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145ff TS011F (TypeError: Cannot read properties of undefined (reading 'debug')
    at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1183:20)
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17)). undefined

Everything works and the zigbee adapter recognizes the Uselink as the right device. 

Is there a chance to get rid of these messages?

Thanks a lot.

Greetz THPS

**Comment by asgothian** [comment]
Update to the current GitHub stable version and check if that changes anything.

A.

**Comment by lindi200000** [comment]
Hello i have the same Problem.

I have installed version 1.8.10, but the error is still present.
`DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b60016803 TS011F (TypeError: Cannot read property 'debug' of undefined at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20) at async Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13) at async DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at async DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
`

**Comment by asgothian** [comment]
please try to patch line 1188 in `/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js` from

`logger.debug('TuYa configureMagicPacket failed, ignoring...');`

to 

`if (logger) logger.debug('TuYa configureMagicPacket failed, ignoring...');`

and then restart the adapter to see if the message is gone.

A.

**Comment by Kruemel1211** [comment]
Hallo,
hatte gleiche Warnmeldung ohne Funktionseinschränkung beim "Device UseeLink SM-0306E-2W".
Nach Änderung der Zeile - 1188 /opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js
und Neustart des Adapter. Keine Fehlermeldung mehr im Log.
Ebenso die Änderung der Zeile - 134  /opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js
mit Neustart. Sauberer Start und nach 20 Minuten keine Fehlermeldung im Log.

Zigbee Adapter v1.8.10
ConBee2 USB Stick an einer Synology DS220+ mit DSM 7.1.1-42963 Update3
mit ioBroker im Docker Container

Vielen Dank. Das Problem wurde in meiner config behoben.

`<html>
<body>


zigbee.0 | 2023-01-02 22:02:02.703 | info | List of port: []
-- | -- | -- | --
zigbee.0 | 2023-01-02 22:01:40.789 | info | Zigbee started
zigbee.0 | 2023-01-02 22:01:40.789 | info | 0x00158d00056d6af1 (addr 60698): 10011723 - HORNBACH FLAIR Viyu Smart LED bulb CCT E27 (Router)
zigbee.0 | 2023-01-02 22:01:40.788 | info | 0x00158d000854aff7 (addr 26233): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2023-01-02 22:01:40.787 | info | 0x00158d000894f08a (addr 22711): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2023-01-02 22:01:40.786 | info | 0x00158d0008366f88 (addr 30142): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2023-01-02 22:01:40.785 | info | 0x00158d0008066860 (addr 6164): WXKG11LM - Xiaomi Aqara wireless switch (EndDevice)
zigbee.0 | 2023-01-02 22:01:40.785 | info | 0x00158d0003a64bb1 (addr 7926): 10011723 - HORNBACH FLAIR Viyu Smart LED bulb CCT E27 (Router)
zigbee.0 | 2023-01-02 22:01:40.783 | info | 0x54ef441000510191 (addr 29319): SP-EUC01 - Xiaomi Aqara EU smart plug (Router)
zigbee.0 | 2023-01-02 22:01:40.782 | info | 0x54ef4410005feb26 (addr 4413): SP-EUC01 - Xiaomi Aqara EU smart plug (Router)
zigbee.0 | 2023-01-02 22:01:40.779 | info | 0x70b3d52b60012026 (addr 23147): SM-0306E-2W - UseeLink 4 gang switch, with USB (Router)
zigbee.0 | 2023-01-02 22:01:40.774 | info | 0x00158d00083a1a45 (addr 58300): WXKG11LM - Xiaomi Aqara wireless switch (EndDevice)
zigbee.0 | 2023-01-02 22:01:40.722 | info | Currently 10 devices are joined:
zigbee.0 | 2023-01-02 22:01:40.718 | info | Unable to set transmit power, unsupported function.
zigbee.0 | 2023-01-02 22:01:40.636 | info | --> transmitPower : high+
zigbee.0 | 2023-01-02 22:01:40.622 | info | Unable to disable LED, unsupported function.
zigbee.0 | 2023-01-02 22:01:40.600 | info | Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":120,"maintrel":0,"revision":"0x26780700"}}
zigbee.0 | 2023-01-02 22:01:40.578 | info | Installed Version: ioBroker/ioBroker.zigbee#dd230e2592402b3ca77dc6946091b84cf00e02a6
zigbee.0 | 2023-01-02 22:01:40.017 | info | Starting Zigbee npm ...
zigbee.0 | 2023-01-02 22:01:40.016 | info | delete old Backup files. keep only last 10
zigbee.0 | 2023-01-02 22:01:39.954 | info | starting. Version 1.8.10 (non-npm: ioBroker/ioBroker.zigbee#dd230e2592402b3ca77dc6946091b84cf00e02a6) in /opt/iobroker/node_modules/iobroker.zigbee, node: v16.15.1, js-controller: 4.0.24


</body>
</html>`

**Comment by asgothian** [comment]
> Vielen Dank. Das Problem wurde in meiner config behoben.

Hast du vor der Anpassung im ioBroker selber die Änderung in Tuya.js rückgängig gemacht ? Wenn nein, kannst du das noch testen ? Sprich das alleine durch die Anpassung im ioBroker das Problem behoben ist ?

Danke.

A.

**Comment by Kruemel1211** [comment]
Nein, die Änderung in Tuya.js habe ich nicht rückgängig gemacht. Könnte ich heute Abend noch Mal prüfen

**Comment by asgothian** [comment]
Es gibt bei der Nachfrage ob du die wirklich löschen willst einen Haken für "force". Nebenbei bedeutet die Meldung das der Koordinator die besagte Steckdosenleiste nicht erreichen kann - ist sie überhaupt eingesteckt ?

A.

**Comment by thps1990** [comment]
> Es gibt bei der Nachfrage ob du die wirklich löschen willst einen Haken für "force". Nebenbei bedeutet die Meldung das der Koordinator die besagte Steckdosenleiste nicht erreichen kann - ist sie überhaupt eingesteckt ?
> 
> A.


haha, wer lesen kann ist klar im Vorteil :) . Die Steckdose ist leider elektrisch kaputt gegangen, deshalb ist sie auch nicht erreichbar. 

Der Fehler tritt nicht mehr auf, die Anpassung in der zbDeviceConfigure.js ist ausreichend. Vielen Dank für die Unterstützung!

**Comment by asgothian** [comment]
Closed ist das nicht - die Anpassung muss noch in den Adapter so das nicht von Hand gepatched werden muss.

**Comment by thps1990** [comment]
Ok, sorry stimmt...

**Comment by Day1983** [comment]
Hallo zusammen,
hab das gleiche Problem. Hab den Adapter in V 1.8.10 installiert 

Jetzt die doofe Frage: wie ändere ich den die .ja ab? Muss ich über SSH auf den Host und mit nano die Datei öffnen? Oder mit filezilla über Windows?

Danke euch.

**Comment by Day1983** [comment]
Hier die Fehlermeldung:
![FB_IMG_1673471413819](https://user-images.githubusercontent.com/77491820/211918667-92751444-6b0c-4ce0-ad27-69fc4dbb3294.jpg)

**Comment by PastCoder** [comment]
Wenn ich Zeile 134 anpassen bekomme ich auch den Fehler, der in https://github.com/ioBroker/ioBroker.zigbee/issues/1629#issuecomment-1379489404 genannt ist. Welcher Fehler ist jetzt besser!? Oder muss ich noch zusätzlich etwas machen?

**Comment by asgothian** [comment]
Bitte die Fehlermeldung mit Kontext als Text, nicht als Screenshot posten. Das kann ich nicht lesen.

A.

**Comment by PastCoder** [comment]
Hier die verspätete Antwort, da ich in den letzten Tagen unterwegs war:

Die Meldung vor der Änderung (ca. alle 5-6 Minuten):

- `error	DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b6001bd5d TS011F (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1183:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/tuya.js:2431:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))`

Hier die Meldung nach der Änderung (Zeile 134 + "this") und Neustart des Zigbee-Adapters:

- Direkt nach Neustart: `error	DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b6001bd5d TS011F (Error: ConfigureReporting 0x70b3d52b6001bd5d/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE') at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.configureReporting (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:694:22) at Object.rmsVoltage (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/reporting.js:211:9) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/tuya.js:2434:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17) at DeviceConfigure.onZigbeeStarted (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:54:21) at async Promise.all (index 1))`

- Danach wieder alle 5-6 Minuten: `error	DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b6001bd5d TS011F (Error: ConfigureReporting 0x70b3d52b6001bd5d/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE') at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.configureReporting (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:694:22) at Object.rmsVoltage (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/reporting.js:211:9) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/tuya.js:2434:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))`

Ich habe die Änderung jetzt erstmal wieder rückgängig gemacht.

**Comment by asgothian** [comment]
Die Fehlermeldung "UNREPORTABLE_ATTRIBUTE" deutet darauf hin das die Implementation in den Zigbee-Herdsman-Converters  nicht zu Deiner Hardware passt. Sie hängt nicht mit der weiter oben angesprochenen Anpassung zusammen.

A.

**Comment by PastCoder** [comment]
Seit dem Update auf aktuellen Stand vom Masterbranch am 25.2.2023 sind die Fehlermeldungen verschwunden.
