### ISSUE TITLE
Ikea motion detectors pairing

### ISSUE THREAD

**Issue by apla2016** [ioBroker/ioBroker.zigbee#1630]
I am trying to pair two Ikea motion detectors. First, press pair button 4 times within 5 sec, red light blinks and goes away. Wait for red light to reappear the initiate pairing. But IoBroker reports device announcing only on about 50th second of pairing time. It sound like default 60 sec is not enough for this device. What am I doing wrong? Is there way to increase pairing interval?

At one point I've seen device announcing itself on 10th second, then again on 45th second, bud does not finish pairing.

Device is within few centimeters from the Zigbee USB hub. I have total of 26 devices registered and Sonoff USB Hub.

**Comment by asgothian** [comment]
- Increase the timing delay from 60 to 180 seconds
- It is possible that the Sonoff USB hub has reached its limit of direct children.

A.

**Comment by apla2016** [comment]
It is unlikely that I reached the limit of direct children since I can add another device (switch instead of motion detector) and also, they say that 32 is a maximum direct children for Sonoff USB hub.
Please point me where to adjust the timing delay, I don't see it. Thanks
Can I use two Sonoff hubs hubs if need fore than 32 children?

**Comment by asgothian** [comment]
It is prominent in the adapter configuration page. I have no access currently, so I can't post a screenshot

**Comment by apla2016** [comment]
Thank you, found it, increased to 120sec - did not help. The device pairing time interval is about 60 seconds (red light on), so even 120 sec of adapter pairing does not complete the connection.
