### ISSUE TITLE
OTA Update von Geräte über iobroker.zigbee

### ISSUE THREAD

**Issue by fred2261** [ioBroker/ioBroker.zigbee#1631]
Hallo zusammen,
zuerst möchte ich mich bei den Entwicklern für die tolle Leistung bedanken!
Ich habe ein neues zigbee-Netzwerk mit 4 Koordinatoren (4 Stockwerke), mehrere Thermostaten, Rauchmelder und Sensoren aufgebaut und letztendlich funktioniert alles sehr stabil und wie geplant.
Die Thermostaten und die Rauchmelder sind "OTA Update"-fähig und die Updates dafür sind im Koenkk-URL vorhanden.
Ich finde aber nirgendwo im ioBroker/zigbee-Adapter die Möglichkeit einen OTA-Update zu prüfen und zu starten. 
Könnte mir jemand einen Tipp geben, ob und wie das geht?

In den iobroker.zigbee-Adapter Releasenotes findet man schon Spuren von OTA-Updates :

_"StrunzdesignFixed the mapping between bulb levels and adapter levels* (kirovilya) Fix ota for unavailable devices"_

_"asgothianchange in how RGB color is parsed. Incomplete colors will now be parsed successfully. #FFF will result in R 0, G 15, B 255* (asgothian) change in OTA: Message that a device does not respond for OTA query downgraded to "info" from "error"_

_"asgothianchange in how RGB color is parsed. Incomplete colors will now be parsed successfully. #FFF will result in R 0, G 15, B 255* (asgothian) change in OTA: Message that a device does not respond for OTA query downgraded to "info" from "error""_
. . .
und noch weitere.

Viele Grüße
Fred

**Comment by BigMike71** [comment]
In Iobroker auf Zigbee und dann hier mal drücken!
![zigfirm](https://user-images.githubusercontent.com/50262344/209974788-4d4cd511-21cf-4114-9632-c97ff8153299.jpg)

Geräte die sich updaten lassen bekommen dann einen pfeil!
![zigfirm1](https://user-images.githubusercontent.com/50262344/209974838-2a5289b7-0ca9-47e9-8358-b6229a27695e.jpg)

**Comment by fred2261** [comment]
Tatsächlich, so einfach :-)
Habe das völlig übersehen.
Vielen Dank und einen guten Rutsch ins Neue Jahr!

Vile Grüße
Fred

**Comment by fred2261** [comment]
Doch eine zusätzliche Frage :-)
Hat jemand den Update mit einem Thermostat (in meinem Fall Danfoss Ally) getestet - wie reagiert der Thermostat während des Updates?
Ich befürchte, dass er den Ventil völlig aufmacht und nicht mehr kontrolliert werden kann.
Man schreibt aber, dass so ein Update mehrere Stunden dauern kann.

Viele Grüße
Fred

**Comment by BigMike71** [comment]
dazu kann ich nichts sagen, habe aber mal den IKEA Repeater und auch mal eine Philips Hue upgedatet, das hat ca. 45min pro Gerät gedauert.... denke man sollte lieber nur ein oder zwei auf einmal anstossen...
