### ISSUE TITLE
Xiaomi Motion Time from last motion funktioniert nicht mehr richtig

### ISSUE THREAD

**Issue by Prince3k** [ioBroker/ioBroker.zigbee#1633]
Seit einigen Tagen / Wochen ist mir aufgefallen, dass vereinzelte Motionsensoren ( 8 Stück habe ich ) auf einmal die Zeit für NoMotion nicht mehr wiedergeben.

Folgendes steht in der Log:

`<html><body>

javascript.0 | 2022-12-29 23:45:36.083 | warn | at processTimers (node:internal/timers:502:7)
-- | -- | -- | --
javascript.0 | 2022-12-29 23:45:36.082 | warn | at listOnTimeout (node:internal/timers:559:17)
javascript.0 | 2022-12-29 23:45:36.082 | warn | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2360:34)
javascript.0 | 2022-12-29 23:45:36.082 | warn | at Object.<anonymous> (script.js.Lampen-Schalter.EG.Schlafraum:27:9)
javascript.0 | 2022-12-29 23:45:36.080 | warn | getState "zigbee.0.00158d000836b288.no_motion" not found (3)

</body>
</html>`

Wenn ich das Gerät entferne und wieder hinzufüge, dann geht es irgendwann mal ( klappt nicht immer beim 1. Versuch ).

**Comment by asgothian** [comment]
Gibt es den Datenpunkt zigbee.0.00158d000836b288.no_motion ?

**Comment by Prince3k** [comment]
Den Datenpunkt gibt es überall und auch hier steht ständig 0 Sekunden.
Ich habe jetzt die Batterien ausgetauscht, die Motions gelöscht und wieder angelernt und bis dato scheint es wieder zu laufen.
Sollte es daran liegen, wäre es ärgerlich, da der Ladestand der Batterien >40 % anzeigte.
Ich werde das mal weiter beobachten.

**Comment by asgothian** [comment]
Die Anzeige does Batteriestand ist bei den Zigbee Geräten immer kritisch. Insbesondere der Fall das sie den Batteriestand ja nur aktualisieren können solange sie laufen. Der letzte Wert ist also aus Prinzip immer einer bei dem noch alles in Ordnung war.

A.
