### ISSUE TITLE
MOSZB 140 Zigbee 1.8.10

### ISSUE THREAD

**Issue by hakelgg** [ioBroker/ioBroker.zigbee#1640]
Wünsche ein gesundes neues Jahr

zigbee 1.8.10 brachte bei mir auch nicht den gewünschten Erfolg
20230102
Log der Installation
```
$ iobroker url iobroker.zigbee@1.8.10 --host 70-iobroker-pi --debug
install iobroker.zigbee@1.8.10
NPM version: 6.14.17Installing iobroker.zigbee@1.8.10... (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.zigbee@1.8.10.
npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-01-02T08_55_09_479Z-debug.log
upload [325] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/adapter-settings.js adapter-settings.js application/javascript
upload [300] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ.png img/DIYRuZ.png image/png
upload [250] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/bitron_motion.png img/bitron_motion.png image/png
upload [200] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/hive.png img/hive.png image/png
upload [150] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/lh_32Zb.png img/lh_32Zb.png image/png
upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_amaze.png img/philips_amaze.png image/png
upload [90] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_ambiance.png img/philips_hue_ambiance.png image/png
upload [80] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_e27_ambiance.png img/philips_hue_e27_ambiance.png image/png
upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_ltc021.png img/philips_hue_ltc021.png image/png
upload [60] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/plug.png img/plug.png image/png
upload [50] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/sensor_philipshue.png img/sensor_philipshue.png image/png
upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/smartthings_motion.png img/smartthings_motion.png image/png
upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ts0203.png img/ts0203.png image/png
upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/tuya_tyzs1l.png img/tuya_tyzs1l.png image/png
upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/unavailable.png img/unavailable.png image/png
upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/unknown.png img/unknown.png image/png
upload [17] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/wemo.png img/wemo.png image/png
upload [16] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/xiaomi_plug_eu.png img/xiaomi_plug_eu.png image/png
upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/xiaomi_wireless_switch.png img/xiaomi_wireless_switch.png image/png
upload [14] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_e27.png img/zbt_e27.png image/png
upload [13] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_e27_rgbw.png img/zbt_e27_rgbw.png image/png
upload [12] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_led_panel.png img/zbt_led_panel.png image/png
upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_smart_switch.png img/zbt_smart_switch.png image/png
upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zemismart_sw2.png img/zemismart_sw2.png image/png
upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/index.html index.html text/html
upload [8] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/index_m.html index_m.html text/html
upload [7] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/moment.min.js moment.min.js application/javascript
upload [6] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/shuffle.min.js shuffle.min.js application/javascript
upload [5] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/tab_m.html tab_m.html text/html
upload [4] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/vis-network.min.css vis-network.min.css text/css
upload [3] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/vis-network.min.js vis-network.min.js application/javascript
upload [2] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/words.js words.js application/javascript
upload [1] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/zigbee.png zigbee.png image/png
upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/zigbee.svg zigbee.svg image/svg+xml
Update "system.adapter.zigbee.0"
Process exited with code 0
```

Schließen wenn fertig

Pairing log
```
Pairing time left
Pairing time left: 1
Pairing time left: 15 .. Wiederholt bis time left:1
Interview failed: 0x0015bc001a0239b4
Error: Failed to interview '0x0015bc001a0239b4', device has not successfully been paired. undefined. undefined
Pairing time left: 16 
Pairing time left: 61 .. Wiederholt bis 16
Interview failed: 0x0015bc001a0239b4
Error: Failed to interview '0x0015bc001a0239b4', device has not successfully been paired. undefined. undefined
Pairing time left: 62
Pairing time left: 63
Pairing time left: 64
Pairing time left: 65
Pairing time left: 66
Pairing time left: 67
Pairing time left: 68
Device '0x0015bc001a0239b4' announced itself
Pairing time left: 69 
Pairing time left: 115 Wiederholt bis 69
Device '0x0015bc001a0239b4' announced itself
Pairing time left: 116
Pairing time left: 117
Pairing time left: 118
Pairing time left: 119
Pairing time left: 120
Pairing started 
```

Mod Edit: Gepostete Logs so aufgearbeitet das diese besser gelesen werden können.

**Comment by asgothian** [comment]
- du musst auch die 1.8.10 installieren. Die gibt es aktuell nur auf GitHub, nicht auf npm. Steht auch in deinem log drin.

`npm ERR! notarget No matching version found for iobroker.zigbee@1.8.10.`

- logs gehören in code tags
- Warum postest du ca. 120 Zeilen ohne Info (das herunter zählen des Countdown?), nicht aber das log vom Start des Adapters (ach ja, da hätte ja gestanden das du noch die Version 1.8.9 laufen hast)

A.

**Comment by hakelgg** [comment]
`Hallo
wie Ihr sicher bemerkt habt bin ich neu hier. Werde noch viele Fehler machen.
Will auch auf keinen Fall Euch Eure Zeit stehlen.
Etwas Unterstützung bräuchte ich schon, da helfen keine Zweizeiler mit 5 Abkürzungen, wie oft üblich.
Habe jahrelang Maschinensteuerungen Siemens, Heidenhain ..... programmiert.
Ich denke mit Eurer Hilfe bekomme ich das hier auch hin.
Eine Anleitung für die richtige Vorgehensweise, wie in meinem Fall liegt sicher irgenwo herum, habe leider noch nichts gefunden.
Anbei Log der Installation und des Paaringversuches 

[iobroker.current.log](https://github.com/ioBroker/ioBroker.zigbee/files/10335993/iobroker.current.log)
`

**Comment by asgothian** [comment]
Installation von GitHub:

- Admin auf die Adapter Seite gehen.
- Expertenmodus einschalten
- Über das "Katzen" Icon Installation aus benutzerdefinierter Quelle starten
- Als Quelle "GitHub" auswählen
- Zigbee Adapter auswählen
- Installieren

Damit bekommst du die aktuelle Version von GitHub.

Zum Thema logs posten:

Du musst schon (mit etwas Logik) die Logs auf die Einträge kürzen die relevant sind. Keiner hat Zeit und Lust aus ein paar hundert Zeilen die Zeilen zu extrahieren die relevant sind. Dabei sollte das auch kein grösseres Problem darstellen. Im Bezug auf das allgemeine Log ist als tip:
- Log löschen
- Aktion starten die man geloggt haben will
- Log herunterladen
- erst einmal alles herausfiltern was von anderen Adaptern stammt
- dann "standard" Nachrichten die nichts mit dem Problem zu tun haben löschen, ggf. durch ein bisschen Text ersetzen (Beispiel: Du hast oben 120 mal "Pairing time left ..." Stehen. Die kann man einkürzen - ich hab das mal als Beispiel als Mod-Edit bei deinem Log oben getan)
- Dann posten. Dabei erst den Text bei Github hinein kopieren, dann den Log teil markieren und auf den button <> im Github editor drücken - dann bekommt man schön lesbare Logs.

A.

**Comment by hakelgg** [comment]
bei der Installation erscheinen dies Meldungen:
host.70-iobroker-pi iobroker npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):                                                                                                                                                              

host.70-iobroker-pi iobroker npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})+ iobroker.zigbee@1.8.10added 13 packages from 10 contributors and updated 4 packages in 317.777s 

Der MOSZB-141 wird nach dem Update weiterhin erkannt  (nur occupancy und Batterie-Sensor)
Der MOSZB-140 wird nach dem Update nicht mehr erkannt (zusätzlich mit (tampered, Temperatur u. Illuminanz - Sensor)

![MOSZB-140 MOSZB-141](https://user-images.githubusercontent.com/120252980/210371311-af402533-e5ae-4575-8dc7-cc55a91af111.JPG)
![MOSZB-140 MOSZB-141_2](https://user-images.githubusercontent.com/120252980/210372900-8b03905c-fe58-44b4-9a68-f692876bf7b4.JPG)

Die Geräteinfo nach Paarung mit Zigbee 1.7.5
[Geräteinfo MOSZB 140 gepaart mit 1.7.5.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10337244/Gerateinfo.MOSZB.140.gepaart.mit.1.7.5.txt)
[Geräteinfo MOSZB 141 gepaart mit 1.7.5.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10337248/Gerateinfo.MOSZB.141.gepaart.mit.1.7.5.txt)

Die Geräteinfo nach Paarungsversuch mit MOSZB-140 mit Zigbee 1.8.10
[Geräteinfo MOSZB 140 Paaringversuch mit 1.8.10.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10337246/Gerateinfo.MOSZB.140.Paaringversuch.mit.1.8.10.txt)

**Comment by asgothian** [comment]
Das Problem bleibt weiterhin die Tatsache das das Interview nicht erfolgreich ist. Kannst du das Pairing weiter versuchen und während des Pairings den Sensor auf verschiednene Arten versuchen wach zu halten ?

**Comment by asgothian** [comment]
> bei der Installation erscheinen dies Meldungen: host.70-iobroker-pi iobroker npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):
> host.70-iobroker-pi iobroker npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})+ [iobroker.zigbee@1.8.10added](mailto:iobroker.zigbee@1.8.10added) 13 packages from 10 contributors and updated 4 packages in 317.777s

Das ist unproblematisch: Es ist eine optionale Abhängigkeit die nur auf MacOS Systemen (wanted {"os":"darwin","arch":"any"}) genutzt wird.

**Comment by hakelgg** [comment]
beim Pairing habe ich schon alles mögliche versucht.
Start:
- Batterie einsetzen,  Reaktion 
Pairing time left: 115
Device '0x0015bc001a0239b4' announced itself
Pairing time left: 116
Interview started: 0x0015bc001a0239b4
Pairing time left: 117
Pairing time left: 91
Interview failed: 0x0015bc001a0239b4
Error: Failed to interview '0x0015bc001a0239b4', device has not successfully been paired. undefined. undefined
Pairing time left: 92

- Reset Taste 10 s drücken
  warten bis LED 1x blinkt, 2x blinkt , dann dauer blinken
Interview failed: 0x0015bc001a0239b4
Error: Failed to interview '0x0015bc001a0239b4', device has not successfully been paired. undefined. undefined
Pairing time left: 65
Pairing time left: 75
Device '0x0015bc001a0239b4' announced itself
Interview started: 0x0015bc001a0239b4
Pairing time left: 76

Reset Taste oder tampered Schalter oft betätigt
alles ohne Erfolg

**Comment by DeVesen** [comment]
Hallo und guten Morgen,

ich habe auf meinem System auch die Version 1.8.10 probiert.
[Install-Output.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10342594/Install-Output.txt)
[Install-Protokoll.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10342596/Install-Protokoll.txt)

Während der Koppelung klicke ich abwechselnd, im 1-2 Sekunden tackt, auf den Reset-Taster oder Tampered-Schalter.
[Pairing-Output.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10342600/Pairing-Output.txt)
[Pairing-Protokoll.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10342602/Pairing-Protokoll.txt)

Das Ergebnis ist aber weiterhin, ein anscheinend nicht richtig erkanntes Gerät:
![Item01](https://user-images.githubusercontent.com/16238591/210516659-69e468e8-2805-4388-bd28-ce971f04839b.png)
![Item02](https://user-images.githubusercontent.com/16238591/210516679-c607d6a9-3258-4a38-8bd3-b43420a28664.png)
![Item03](https://user-images.githubusercontent.com/16238591/210516690-62549b78-01fb-4dd2-9159-60f888d5e2e6.png)

Gruß Sven

**Comment by asgothian** [comment]
Die Meldung deutet darauf hin das ich das Gerät nicht gemeldet hat als du es (das erste mal) entfernen wolltest.
Beim 2. Mal war das Gerät dann wach und hat die Anfrage bestätigt.

A.

**Comment by hakelgg** [comment]
Habe das Pairing von Zigbee 1.7.6 mit 1.8.10 im Vergleich dargestellt und angehängt.
Ich weiß nicht ob es hilft.
[Vergleich pairing 1.7.6 - 1.8.10.txt](https://github.com/ioBroker/ioBroker.zigbee/files/10351490/Vergleich.pairing.1.7.6.-.1.8.10.txt)

**Comment by hakelgg** [comment]
Frage
- besteht noch die Chance das die BWM MOSZB 140 in einer zukünftigen  Zigbeeadapterversion mit berücksichtigt sind?
- oder sind die MOSZB140 ein Auslaufmodell
- oder ist deren Software nicht kompatible mit dem  Zigbee Standard
Ich möchte noch einige BWM zum Einsatz bringen und natürlich zukünftig immer mit den aktuellen Softwareständen arbeiten.
Vielen Dank an alle die mit Herz und Akribie viel Arbeit in die verschieden Projekte stecken.
Und wenn ich mich von den MOSZB140...... trennen muß, dann ist das halt so.
VG
hakelgg

**Comment by Haititei** [comment]
Eine Frage die ich mir auch stelle.
Du bist nicht alleine mit dem Problem. Auch ich musste ein Downgrade machen, weil identische Probleme aufgetaucht sind.

**Comment by hakelgg** [comment]
Bin komplett umgestiegen 
habe die BW MOSZB 140 eingemottet und auf IKEA E1525_E1745 umgestiegen.

**Comment by DJ3vil** [comment]
Ive got the same Problem.
Failed to interview '0x0015bc001a023921', device has not successfully been paired. undefined

Its with the Version 1.8.10 and Node.js: v19.6.0.
Sometimes i get the paired but theres no states.

**Comment by hakelgg** [comment]
Hallo
Gute Nachrichten
mit ZigBee 1.9.5 arbeiten auch wieder die MOSZB-140
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/120252980/2aa88de0-d889-440f-8a49-eb84ee961545)

Vielen Dank für die Arbeit.
Wäre interessant zu wissen woran es lag.

Ich wünsche allen 
Gesundes Neues Jahr
Günter
