### ISSUE TITLE
Zigbee adapter ignores all devices

### ISSUE THREAD

**Issue by Bens0n68** [ioBroker/ioBroker.zigbee#1641]
Hi,
first thanks a lot for this great adapter!!

I am using it for more than a year - very stable and reliable - with two Sonoff ZBBridges.
After updating to 1.8.9 everything worked well.
After a few days the first Instance forgot all devices ("currently no devices") - even all devices have been displayed in the adapter - but somehow not connected anymore. After re-binding they worked again - for a couple of hours or days
The 2nd (identical) Bridge worked without problems for 2 weeks.

Tonight both instances disconnected ALL devices :-(

Any idea what happened or how to re-connect them?

thanks a lot!
Best
Ben

here is the log

zigbee.0 | 2023-01-02 11:25:09.622 | info | Zigbee started
zigbee.0 | 2023-01-02 11:25:09.619 | info | Currently no devices.
zigbee.0 | 2023-01-02 11:25:09.576 | info | --> transmitPower : normal
zigbee.0 | 2023-01-02 11:25:09.574 | info | Unable to disable LED, unsupported function.
zigbee.0 | 2023-01-02 11:25:09.570 | info | Coordinator firmware version: {"type":"EZSP v8","meta":{"product":8,"majorrel":"6","minorrel":"7","maintrel":"8 ","revision":"6.7.8.0 build 373"}}
zigbee.2 | 2023-01-02 11:25:07.740 | info | Installed Version: iobroker.zigbee@1.8.9
zigbee.2 | 2023-01-02 11:25:07.163 | info | Starting Zigbee npm ...
zigbee.2 | 2023-01-02 11:25:07.161 | info | delete old Backup files. keep only last 10
zigbee.2 | 2023-01-02 11:25:07.013 | info | starting. Version 1.8.9 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.21.1, js-controller: 4.0.24
zigbee.0 | 2023-01-02 11:25:03.981 | info | Installed Version: iobroker.zigbee@1.8.9
zigbee.0 | 2023-01-02 11:25:03.457 | info | Starting Zigbee npm ...
zigbee.0 | 2023-01-02 11:25:03.455 | info | delete old Backup files. keep only last 10
zigbee.0 | 2023-01-02 11:25:03.294 | info | starting. Version 1.8.9 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.21.1, js-controller: 4.0.24

zigbee.2 | 2023-01-02 11:25:14.695 | info | Zigbee started
-- | -- | -- | --
zigbee.2 | 2023-01-02 11:25:14.692 | info | Currently no devices.
zigbee.2 | 2023-01-02 11:25:14.545 | info | --> transmitPower : normal
zigbee.2 | 2023-01-02 11:25:14.512 | info | Unable to disable LED, unsupported function.
zigbee.2 | 2023-01-02 11:25:14.508 | info | Coordinator firmware version: {"type":"EZSP v8","meta":{"product":8,"majorrel":"6","minorrel":"7","maintrel":"8 ","revision":"6.7.8.0 build 373"}}

**Comment by asgothian** [comment]
If the adapter says “currently no devices” there is an issue with the shepherd.db file in /opt/iobroker/iobroker-data/zigbee_2

as long as the adapter says that no devices are connected, all the states still present in iobroker are disconnected from the hardware.

You need to check what happens to that file.

**Comment by Bens0n68** [comment]
Thanks a lot - very helpful.

This file is only 768 bytes - in the backup it has more than 12k.
Replacing this file with the backup versions works partially - but instance is quite unstable then.

Should I step back to the old version? Worked very stable or is this another problem?
When reinstalling - can I just copy back the shepherd.db and dev_names.json.
Will I loose my history from the db-objects then?

Thanks for your great help!

**Comment by asgothian** [comment]
You need to check what causes the shepherd.db to be overwritten. I have trouble seeing that as a function of the zigbee adapter - we would get a lot more issues about it, given the install base. I assume that your filesystem is about to die.

Reinstalling will not remove your history, but you may have to add the history settings to the desired states. Also - if you just do a "downgrade" by going to the expert mode and selecting a previous adapter version, the states won't be removed and the shepherd db will remain as well.

if you reinstall the entire system, you can set it up without loosing the history as long as you create a complete backup with the backitup adapter, including zigbee and your history database. (Done that several times)

A.
