### ISSUE TITLE
Zigbee Adapter 1.8.10 crashes

### ISSUE THREAD

**Issue by fzoellne** [ioBroker/ioBroker.zigbee#1646]
Hi,

der Adapter crasht immer:

```

{"address":51564,"clusterId":32817,"sequence":105} after 10000ms
--
zigbee.0 | 2023-01-06 10:26:16.044 | error | Error: {"address":51564,"clusterId":32817,"sequence":105} after 10000ms at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
zigbee.0 | 2023-01-06 10:26:16.043 | error | unhandled promise rejection: {"address":51564,"clusterId":32817,"sequence":105} after 10000ms
zigbee.0 | 2023-01-06 10:26:16.043 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2023-01-06 10:26:16.040 | error | {"address":60139,"clusterId":32817,"sequence":104} after 10000ms
zigbee.0 | 2023-01-06 10:26:16.039 | error | Error: {"address":60139,"clusterId":32817,"sequence":104} after 10000ms at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
zigbee.0 | 2023-01-06 10:26:16.038 | error | unhandled promise rejection: {"address":60139,"clusterId":32817,"sequence":104} after 10000ms
zigbee.0 | 2023-01-06 10:26:16.037 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2023-01-06 10:26:15.578 | error | {"address":0,"clusterId":32817,"sequence":103} after 10000ms
zigbee.0 | 2023-01-06 10:26:15.578 | error | Error: {"address":0,"clusterId":32817,"sequence":103} after 10000ms at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
zigbee.0 | 2023-01-06 10:26:15.577 | error | unhandled promise rejection: {"address":0,"clusterId":32817,"sequence":103} after 10000ms
zigbee.0 | 2023-01-06 10:26:15.576 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

```

Das steht im Log...

mod Edit: Correct code tags

**Comment by Apollon77** [comment]
Ich seh in dem Log aber keinen Crash? Oder Loggt der das nur, läuft aber sonst? Ist das Gerät online? Weil es gibt scheinbar einen timeout bei der Kommunikation

**Comment by fzoellne** [comment]
ah sorry falsches ausgeschnitten...

 `

2023-01-06 10:43:04.386 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | --
host.1ebc1d909e69 | 2023-01-06 10:43:04.386 | error | Caught by controller[0]: at processTimers (node:internal/timers:502:7)
host.1ebc1d909e69 | 2023-01-06 10:43:04.386 | error | Caught by controller[0]: at listOnTimeout (node:internal/timers:559:17)
host.1ebc1d909e69 | 2023-01-06 10:43:04.385 | error | Caught by controller[0]: at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
host.1ebc1d909e69 | 2023-01-06 10:43:04.385 | error | Caught by controller[0]: Error: {"address":32222,"clusterId":32817,"sequence":50} after 10000ms
host.1ebc1d909e69 | 2023-01-06 10:43:04.385 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-01-06 10:43:04.219 | error | Failed to stop zigbee (TypeError: Cannot read properties of undefined (reading 'version') at EZSPAdapterBackup.createBackup (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/backup.ts:21:56) at EZSPAdapter.backup (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:589:31) at Controller.backup (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:328:47) at Controller.stop (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:308:9) at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:455:13) at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:853:17))
zigbee.0 | 2023-01-06 10:43:03.720 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2023-01-06 10:43:03.720 | info | terminating
zigbee.0 | 2023-01-06 10:43:03.126 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-01-06 10:43:03.060 | info | cleaned everything up...
admin.0 | 2023-01-06 10:43:02.183 | info | <== Disconnect system.user.admin from ::ffff:192.168.30.172
admin.0 | 2023-01-06 10:43:02.183 | info | <== Disconnect system.user.admin from ::ffff:192.168.30.172
zigbee.0 | 2023-01-06 10:42:56.587 | error | {"address":32222,"clusterId":32817,"sequence":50} after 10000ms
zigbee.0 | 2023-01-06 10:42:56.587 | error | Error: {"address":32222,"clusterId":32817,"sequence":50} after 10000ms at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
zigbee.0 | 2023-01-06 10:42:56.587 | error | unhandled promise rejection: {"address":32222,"clusterId":32817,"sequence":50} after 10000ms

zigbee.0 | 2023-01-06 10:42:56.586 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

zigbee.0 | 2023-01-06 10:42:32.942 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c138a9abc18bfa TS0601 (Error: Bind 0xa4c138a9abc18bfa/1 genBasic from '0x84b4dbfffef814d1/1' failed ({"address":49658,"clusterId":32801,"sequence":36} after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7))

`

**Comment by asgothian** [comment]
Der crash kommt tief aus dem Code des zigbee-herdsman, und ist in Verbindung mit einem als experimentell anzusehenden Koordinator (EZSP Chipsatz)

Du musst heraus finden welches Gerät für diesen Absturz verantwortlich ist, und was zu dem Zeitpunkt mit dem Gerät kommuniziert wurde.

Der Log-Eintrag oben weist auf vergleichbare Probleme mit anderen Geräten hin, jeweils mit der gleichen Fehlermeldung auf dem gleichen Cluster.

des Weiteren solltest du mehr Informationen über dein System posten.

**Comment by fzoellne** [comment]
Sehr spannend wenn man nur den Adapter geupdated hat und sonst keine neuen Geräte im Netz sind...




Von: asgothian ***@***.***>
Antworten an: "ioBroker/ioBroker.zigbee" ***@***.***>
Datum: Freitag, 6. Januar 2023 um 15:54
An: "ioBroker/ioBroker.zigbee" ***@***.***>
Cc: Frank Zoellner ***@***.***>, Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] Zigbee Adapter 1.8.10 crashes (Issue #1646)


Der crash kommt tief aus dem Code des zigbee-herdsman, und ist in Verbindung mit einem als experimentell anzusehenden Koordinator (EZSP Chipsatz)

Du musst heraus finden welches Gerät für diesen Absturz verantwortlich ist, und was zu dem Zeitpunkt mit dem Gerät kommuniziert wurde.

Der Log-Eintrag oben weist auf vergleichbare Probleme mit anderen Geräten hin, jeweils mit der gleichen Fehlermeldung auf dem gleichen Cluster.

des Weiteren solltest du mehr Informationen über dein System posten.

**Comment by asgothian** [comment]
> Sehr spannend wenn man nur den Adapter geupdated hat und sonst keine neuen Geräte im Netz sind...

Sehr spannend wenn man Hardware benutzt deren Unterstützung als "experimentell" bezeichnet wird.

Im Übrigen hast Du jetzt 4 Möglichkeiten:
- Downgrade to 1.8.9
- Austausch des Koordinators zu einem der nicht experimentell ist
- Abwarten ob das Problem sich von alleine Löst
- Aktiv an der Lösung des Problems mitarbeiten.

Kommentare wie der oben verlinkte führen dazu das mein Interesse hier Zeit hinein zu versenken massiv sinkt.

A.

**Comment by fzoellne** [comment]
> > Sehr spannend wenn man nur den Adapter geupdated hat und sonst keine neuen Geräte im Netz sind...
> 
> Sehr spannend wenn man Hardware benutzt deren Unterstützung als "experimentell" bezeichnet wird.
> 
> Im Übrigen hast Du jetzt 4 Möglichkeiten:
> 
> * Downgrade to 1.8.9

das habe ich schon gemacht, aber ich vermute jetzt ist das System etwas durcheinander, denke werde den Adapter mal löschen und dann frisch aufsetzen...
> * Austausch des Koordinators zu einem der nicht experimentell ist

hm mal schauen, vielleicht hole ich einen anderen mal schauen...
> * Abwarten ob das Problem sich von alleine Löst

dann läuft hier aber einiges nicht, nicht so die option..
> * Aktiv an der Lösung des Problems mitarbeiten.

was für infos müsste ich denn loggen und wie ? 
> 
> Kommentare wie der oben verlinkte führen dazu das mein Interesse hier Zeit hinein zu versenken massiv sinkt.
> 
> A. Nachtrag: Anbei der Link zu den verschiedenen Koordinatoren und deren Status. Einen Link auf unser eigenes Readme wo darauf hin gewiesen wird das der EZSP support experimentell ist spare ich mir. https://www.zigbee2mqtt.io/guide/adapters/#not-recommended

ja das habe ich auch gelesen aber es ging ja bisher eigentlich ohne Probleme, das es da zwei Versionen des Knoff usb stick gab habe ich auch erst gesehen als ich den hier ans system gebraucht habe...

**Comment by asgothian** [comment]
> was für infos müsste ich denn loggen und wie ?

Die notwendigen Aktionen sind in meinem 1. Post aufgelistet.

wenn du die Geräte identifiziert hast reicht es erst einmal die ieee der Geräte (mit ;getrennt) unter zigbee.0.Info.debugmessages einzutragen und die dadurch entstehenden Warnmeldungen zu posten.

An Informationen brauchen wir
- Adapter Version
- NodeJS Version
- Art des Koordinators
- Wie angeschlossen
- Version der zigbee-herdsman Bibliothek
- Version der Zigbee-Herdsman-converters Bibliothek
- Version der Serialport bibliothek


A.
