### ISSUE TITLE
Tuya WSD500A - Setting reporting interval

### ISSUE THREAD

**Issue by OneCreek** [ioBroker/ioBroker.zigbee#1649]
Hello together, 

I have been searching for quite some time now but don't find a way to set the reporting intervall with the [ioBroker.zigbee](https://github.com/ioBroker/ioBroker.zigbee) for the apparently supported [Tuya WSD500A](https://www.zigbee2mqtt.io/devices/WSD500A.html) by the [Koenkk zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters ) as performed in the [zigbee2mqtt ticket 13279: Setting reporting interval](https://github.com/Koenkk/zigbee2mqtt/discussions/13279). 
I also get the Objects list as in the [tuya.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/0b9531698e2436b94bf798d50554b7798d93d1b7/devices/tuya.js#L1673) of the zigbee-herdsman-converters.

Litte excursion:
I tried various SendPayload commands, that should work apparently. From sending the commands via the Objects tab by SendPayload and also via JS. 
Later I tried to use some device that can actually turn something on and off, the [Lidl HG06338](https://www.zigbee2mqtt.io/devices/HG06338.html) that should be supported as well. My try was the Payload `{"state_l1": "ON"}` in the ioBroker Objects or my JS skript... What also didn't work... `No converter available for " with key 'state_I3'`. Anyway... back to the topic...

I'm using Sonoff Zigbee 3 Plus CC2652P with [Z-Stack_3.x.0 20220219](https://github.com/Koenkk/Z-Stack-firmware/commit/6e3b68404136c8cf87979212665e6505bd9a0e3b)
Node.js    v16.19.0
NPM    	8.19.3
Host	4.0.24
zigbee.0	v1.8.10

Values show correct (except the voltage, that should be in mV according to [Tuya WSD500A](https://www.zigbee2mqtt.io/devices/WSD500A.html))
![grafik](https://user-images.githubusercontent.com/107502675/211342427-389cb5f4-dd77-4860-8ed4-7c3f97aa743b.png)
Also the [Developer-tab](https://github.com/ioBroker/ioBroker.zigbee#developer-tab) in the ioBroker zigbee adapter works fine (tested with [hue remote switch RWL021](https://www.zigbee2mqtt.io/devices/324131092621.html)). 
But I am uncertain, how to set the [Reporting Tab](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device) ![grafik](https://user-images.githubusercontent.com/20387030/180675098-be58f033-7868-46dc-ad62-572369bc80dc.png) analog to zigbee2mqtt in https://github.com/Koenkk/zigbee2mqtt/discussions/13279...

Any help is more than welcome! Thanks!

**Comment by asgothian** [comment]
- The reporting interval is not set as configurable, as Tuya Devices do not use the standard reporting methods. It may be possible to rebind the reports with a different interval, but that is not currently supported by ioBroker.Zigbee
- The send Payload you posted does not match: Payload was supposed to be `{"state_l1": "ON"}`, but the error message is for `state_I3` (note that in once case you enter a small L with the number one, in the other case a capital I with the number 3)
- Why do you not use the separate states for the 3 plugs in case of the Lidl Plug ?

**Comment by OneCreek** [comment]
> * The reporting interval is not set as configurable, as Tuya Devices do not use the standard reporting methods. It may be possible to rebind the reports with a different interval, but that is not currently supported by ioBroker.Zigbee

Sorry to hear. So the [oBroker.zigbee Development Tab](https://github.com/ioBroker/ioBroker.zigbee#developer-tab) is capable of doing some but not all commands of the [zigbee2mqtt Reporting Tab](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device)? 
Hoped it would be the same because both are based on [Koenkk zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters) I read.
So I only can wait or switch to something like https://github.com/o0shojo0o/ioBroker.zigbee2mqtt or https://github.com/Koenkk/zigbee2mqtt, correct?
>     * The send Payload you posted does not match: Payload was supposed to be `{"state_l1": "ON"}`, but the error message is for `state_I3` (note that in once case you enter a small L with the number one, in the other case a capital I with the number 3)
>     * Why do you not use the separate states for the 3 plugs in case of the Lidl Plug ?
Sorry by mistake. `No converter available for '' with key 'state_l3'` was the error message, I put `{"state_l3": "ON"}` into the `zigbee.0.bc33axxxd41.send_payload`. Just tried again.

**Comment by asgothian** [comment]
The development tab can do everything which is supported directly by the devices. But you have to build the JS yourself, which requires quite a bit of knowledge of the zigbee command structure.

**Comment by OneCreek** [comment]
> The development tab can do everything which is supported directly by the devices. But you have to build the JS yourself, which requires quite a bit of knowledge of the zigbee command structure.

but that would mean I could execute probably the same command as [https://github.com/Koenkk/zigbee2mqtt/discussions/13279](https://github.com/Koenkk/zigbee2mqtt/discussions/13279) was doing... just that I don't have the assistance of the [Reporting Tab](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device) of zigbee2mqtt...

I by now accepted it as it is. What makes it a little bit more _standable_ is the recent discovery, that the [Tuya WSD500A](https://www.zigbee2mqtt.io/devices/WSD500A.html) updates more frequently (like every 5 min instead of 30 min) during the time the moisture is in an higher range.

**Comment by lennon101** [comment]
Just to add further information to this thread, I believe the "update interval" is not time based but instead is controlled by the device itself. When no change is measured, no data is sent. When a change in temp/rh is detected, it sends a measurement. 

From Tuya:
> Upon successful net pairing, the sensor reports its status. It then takes samples of the environment every five minutes. When the ambient temperature exceeds the preset value of the sensor by 0.6°C or the humidity exceeds the preset value by 6%, the sensor will send an alarm to TuyaSmart. Regardless of whether the temperature or humidity exceeds the preset thresholds, data will be synchronized to TuyaSmart every 30 minutes. 

More info here:

https://support.tuya.com/en/help/_detail/K9hw4fohmnwuw
