### ISSUE TITLE
Aqara MCCGQ14LM, Batteriespannung wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by weindler** [ioBroker/ioBroker.zigbee#1653]
Bitte nicht vergessen, ist leider immer noch so.

Originalissue #1280

**Comment by chris299** [comment]
@arteck is this problem solved? I have the same issue with XIAOMI [SJCGQ11LM](https://www.zigbee2mqtt.io/devices/SJCGQ11LM.html) ... (using stable adapter Version 1.8.10

**Comment by arteck** [comment]
battery is herdsman. we are consumer

**Comment by chris299** [comment]
@arteck I understand, but is herdsman really delivering the wrong unit? or does the IOBAdapter only ignores, that mV is provided instead of V?
I'm wondering, because https://www.zigbee2mqtt.io/devices/SJCGQ11LM.html states, it provides a value in mV which it actually is....
