### ISSUE TITLE
Silvercrest Taster meldet dauernd Warnung

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.zigbee#1654]
Einer meiner Taster meldet ca. 10-20 mal am Tag diese Fehlermeldung. (Neu gepairt   und gelöscht wurde er schon)
![image](https://user-images.githubusercontent.com/92173565/212485092-fa647e7c-7109-4e40-b7f4-2d15954b5b0b.png)

Es handelt sich um diesen Taster:
![image](https://user-images.githubusercontent.com/92173565/212485232-5c0652b5-0971-4409-bf19-e0b657515df0.png)

Er wird meistens mit 10% angezeigt. (Obwohl daneben ei Teilnehmer deutlich mehr hat)

Was kann man machen?

**Comment by asgothian** [comment]
Wenig bis nichts. Es scheint das der Taster regelmässig der Meinung ist das er sich vom Netzwerk abgemeldet hat / abgemeldet wurde und eine "Neuanmeldung" sendet. Der Adapter gibt das nur weiter.
