### ISSUE TITLE
WSD500A - wrong voltage value

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.zigbee#1655]
Hello,

i have installed zigbee adapter version 1.8.9 and installed a WSD500A.
All is working good but under "voltage" I get the value = 3000V which be I assume 3V or ? 

Also under iobroker under Objects the icon is missing for this WSD500A

Here a screenshot
![image](https://user-images.githubusercontent.com/40624961/212495431-68fa2262-6f8f-42a5-bf75-0170ff199833.png)

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update
