### ISSUE TITLE
 obj.common.states has an invalid type! Expected "object", received "string"

### ISSUE THREAD

**Issue by wschiro** [ioBroker/ioBroker.zigbee#1656]
it comes the warnings: this and some more

his object will not be created in future versions. Please report this to the developer.
--
zigbee.0 | 26882 | 2023-01-15 11:50:08.382 | warn | Object zigbee.0.0c4314fffe73ac3c.week_day is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 26882 | 2023-01-15 11:50:08.380 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 26882 | 2023-01-15 11:50:08.364 | warn | Object zigbee.0.0c4314fffe73ac3c.working_day is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 26882 | 2023-01-15 11:50:08.253 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 26882 | 2023-01-15 11:50:08.246 | warn | Object zigbee.0.0c4314fffe73ac3c.mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 26882 | 2023-01-15 11:50:08.218 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 26882 | 2023-01-15 11:50:08.213 | warn | Object zigbee.0.0c4314fffe73ac3c.preset is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 26882 | 2023-01-15 11:50:08.184 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 26882 | 2023-01-15 11:50:08.182 | warn | Object 0c4314fffe73ac3c.week_day is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 26882 | 2023-01-15 11:50:08.178 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 26882 | 2023-01-15 11:50:08.175 | warn | Object 0c4314fffe73ac3c.working_day is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 26882 | 2023-01-15 11:50:08.172 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 26882 | 2023-01-15 11:50:08.168 | warn | Object 0c4314fffe73ac3c.mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 26882 | 2023-01-15 11:50:08.126 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 26882 | 2023-01-15 11:50:08.120

**Comment by arteck** [comment]
which device ??

**Comment by wschiro** [comment]
Tuya ZigBee 3,0 Kühler Antrieb Ventil Smart Thermostat Temperatur Controller Externe Sensor TRV Voice Control mit Alexa
