### ISSUE TITLE
Issue w/ Tradfi LED2003G10 & LED2004G8

### ISSUE THREAD

**Issue by Nachhall** [ioBroker/ioBroker.zigbee#1657]
Liebe Community,

ich betreibe, neben weiteren Tradfri-Leuchtmitteln, 3 Stück LED2003G10 und eine LED2004G8 an einem ConBee II mit dem Zigbee-Adapter unter ioBroker. Diese Typen sind nicht in der Liste der unterstützen Geräte aufgeführten, funktionieren aber bis auf den folgenden Fehler einwandfrei. 
- Level und State sind nicht verknüpft. Das führt dazu, dass eine Leveländerung die ausgeschaltete Lampe einschaltet, aber state auf false bleibt.

Alle anderen Leuchtmittel funktionieren einwandfrei.
Kennt jemand dieses Problem und hat vielleicht eine Lösung?

VG
Jörn

**Comment by arteck** [comment]
bitte im converter einstellen..
