### ISSUE TITLE
TS011F Socket - ioBroker Log erros

### ISSUE THREAD

**Issue by smalltower1** [ioBroker/ioBroker.zigbee#1660]
Good day, 
I have added a TS011F socket to my ioBroker Zigbee instance and it seems to be working ok, besides the fact that the update of the power consumed only updates every 30 seconds or so. The problem is every 60 seconds I get the following errors in my ioBroker logfile: 
DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b60019054 TS011F (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/tuya.js:2529:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17)). 

These errors also show up in the pairing window when trying to pair with Zigbee devices. What can I do to solve this problem?

**Comment by smalltower1** [comment]
PS: I am using an EZSP V8 coordinator from SONOFF.

**Comment by asgothian** [comment]
See Issue #1629 for a temp fix. Final fix is being worked on.

**Comment by smalltower1** [comment]
Thank you, editing the zbDeviceConfigure.js file solved the issue. Should I close this issue?

**Comment by asgothian** [comment]
not yet - i will close it when the patch is in

**Comment by smalltower1** [comment]
Ok, thanks. 
Another issue I have, is that the firmware update check over the instance fails for this device. Is this a known issue? 
At the moment the update of the consumed power is set to around 60 seconds. Can this be changed to less, maybe 5 seconds or so?
