### ISSUE TITLE
Not able to add a binding

### ISSUE THREAD

**Issue by crosenbe** [ioBroker/ioBroker.zigbee#1661]
I'm not able to add a binding because no source device is listed. Target devices are available.

**Comment by asgothian** [comment]
Details please ?

**Comment by crosenbe** [comment]
Conbee II Stick as organisator and a couple of Nous A1Z as relay. Idea was to work with static bindings because it take a longer time after a restart until all devices are reachable.

**Comment by asgothian** [comment]
More details please.
- Which devices do you want to use for binding ?
- Which Enpoints/ clusters/ attributes do you want to bind to which other endpoint/cluster/attribute ?
- Be Specific. Provide the device information, not just the device name.
A.

**Comment by crosenbe** [comment]
I think i didn't understand what are bindings used for. I though originally i can improve the building of the mesh network but it's more for create some kind of interaction which will mean i have probably no source available with is able to control other devices (i.e. switch or dimmer). 

Please just close the issue.
