### ISSUE TITLE
Write Data to the device Moes TV 02

### ISSUE THREAD

**Issue by wschiro** [ioBroker/ioBroker.zigbee#1663]
The Adapter works and I have stable connections, quality more then 70 %.
All the settings which I do in the device are visible in the Objecttree. It works fine. The temperature_set_point I can write from a script or from a vis to the adapter and the adapter send it to the device. It works too.  But the most of the settings I cannot send to the device.
If I do that from a script, the adapter receive the data and the data change is to see in the object tree, but in a red color and the data change are not received from the device.
For instance if change the schedule with a script, it comes to the object in the right format, but not to the device. Otherwise  If I change the schedule in the device, it comes to the adapter and to the objects.
I want send changes of the program from iobroker to device. Is that possible ??

**Comment by asgothian** [comment]
More details:

- are there log entries within 30 seconds of changing a state in the object tree ?
- are you changing the state with the "ack" flag set or not set ? 
- are the changes in the object tree acknowledged by the Adapter ?
- are the states listed as "writable" to begin with, i.e. does the implementation of the device list these as settable in the descriptor page at zigbee2mqtt.io ?
A.
