### ISSUE TITLE
Livarno Lux GU10 HG06492A

### ISSUE THREAD

**Issue by chrgachrga** [ioBroker/ioBroker.zigbee#1664]
I am running latest zigbee adapter on IOBroker.
I am using the above spots HG06492A and they work fine with a conbee II on latest firmware.
I see the datapoint send_payload.
According to this page: https://www.zigbee2mqtt.io/devices/HG06492A.html
I should be able to set the power_on_behavior via the send_payload datapoint.
(this actually works fine for other spots in my setup from IKEA)

But for the HG06492A it does not work. Maybe that is something that is not implemented yet?

**Comment by asgothian** [comment]
Details please:
- Are there any log entries when using the send_payload state
- Does this change if you add the IEEE of the device to the state zigbee.x.info.debugmessages ?

Also - if something is not implemented yet, then this is within the zigbee-herdsman-converters project, as the payload entered in send_payload is directly pushed towards the device itself - the zigbee Adapter does NOTHING with it.

A.
