### ISSUE TITLE
Siterwell GS361A-H04 config seems not right - continued

### ISSUE THREAD

**Issue by devdev42** [ioBroker/ioBroker.zigbee#1667]
**What happened so far:**

> Cannot be verified without the device. Closing this.

_Originally posted by @asgothian in https://github.com/ioBroker/ioBroker.zigbee/issues/1349#issuecomment-1039139433_

**Today:**

Hi, one year later and I might be able to help out. Got 6 of these and notice that not all variables work. For example, I can't turn off the window-detection mode (option seems to be missing, but you can configure it through the Tuya app (which I don't have)) and many parameters seem to not be set correctly on the device itself (e.g. local_temp_calibration, max_temperature, local_temp_calibration, boost_time and others) which are marked as red values on the ioBroker objects tab.

To answer your previous questions:

> * Which adapter version are you using ?
> * what is the "manufacturer info" from the info gained through the adapter ?
> * what happens if you add the device to the list of excluded devices (Exclude tab)

_Originally posted by @asgothian in https://github.com/ioBroker/ioBroker.zigbee/issues/1349#issuecomment-1026515589_

My Adapter Version is 1.8.10
0x84ba20fffe0231ee (addr 42833): GS361A-H04 - Siterwell Radiator valve with thermostat (EndDevice)
what should happen / what is the purpose of this test? :)

**Comment by asgothian** [comment]
The purpose of the test is to determine if there is any code within the iobroker.zigbee adapter which affects the generated states. With the device placed in the list of excluded devices, any device specific code within the zigbee adapter is excluded.

This is the desired mode of operation - newer devices use this by default.

Note that you need to restart the adapter after adding the device, and you may need to run state cleanup to eliminate states which are no longer connected.

Once that is done, add the ieee of one of your 6 devices to `zigbee.0.info.debugmessages` to generate warning messages for every state change. Check these for strange behaviour.

A.

**Comment by heiko3967** [comment]
Hi, maybe i can join the game? I also have some of these devices running and noticed that local_temp_calibration does not get acknowleged. Log below.
```
<html>
<body>
<!--StartFragment-->

zigbee.0 | 2023-02-06 12:53:08.120 | warn | ELEVATED Change state 'local_temp_calibration' at device 0x84ba20fffe566f85 type 'GS361A-H04'
-- | -- | -- | --
zigbee.0 | 2023-02-06 12:53:08.109 | warn | ELEVATED: User stateChange zigbee.0.84ba20fffe566f85.local_temp_calibration {"val":-6,"ack":false,"ts":1675684388105,"q":0,"from":"system.adapter.node-red.0","user":"system.user.admin","lc":1675684388105}

<!--EndFragment-->
</body>
</html>
```
ack stays false forever (at least a couple of hours).

Feel free to kick me out here, as I'm not 100% sure that I got the topic right.

**Comment by asgothian** [comment]
> Feel free to kick me out here, as I'm not 100% sure that I got the topic right.

No Kicking. But in this case, the warning messages are not the relevant information. If a state is set (and it clearly is), the adapter should do one of 2 things within 30 seconds:
- provide a warning or error message with a reason why the value was not acknowledged
- acknowledge the value.


Can you check your log for error messages between 5 and 30 seconds after the posted warning ?

Note that this acknowledgement is not currently included in the elevated messages (but may be in the future)

**Comment by heiko3967** [comment]
OK, I tried two scenarios:

In the 1st, the device was not excluded in the Zigbee adapter (of which I am using 1.8.10). Apart from the warnings already posted, there was just silence in the log during the time requested. No info|warn|error.

Then I excluded the device type and restarted (complete iob restart). Now I'm getting plenty errors "No state available ... with key..." See log below.
Since it is now even claiming that it doesn't know "target_temperature", I will include in in the adapter again for now. "Cold house anxiety."

Hope this make any sense to you...

```

zigbee.0
	2023-02-06 22:51:26.775	error	No state available for 'GS361A-H04' with key 'target_temperature'
zigbee.0
	2023-02-06 22:51:26.771	warn	ELEVATED Change state 'target_temperature' at device 0x84ba20fffe566f85 type 'GS361A-H04'
zigbee.0
	2023-02-06 22:51:26.765	warn	ELEVATED: User stateChange zigbee.0.84ba20fffe566f85.target_temperature {"val":15,"ack":false,"ts":1675720286757,"q":0,"from":"system.adapter.node-red.0","user":"system.user.admin","lc":1675717210356}
node-red.0
	2023-02-06 22:51:26.748	info	6 Feb 22:51:26 - [info] [debug:log_ack_false] { device: 'zigbee.0.84ba20fffe566f85.target_temperature', T_Soll: 15, ack: false, room: 'Wohnzimmer' }
zigbee.0
	2023-02-06 22:51:26.704	error	No state available for 'GS361A-H04' with key 'target_temperature'
node-red.0
	2023-02-06 22:51:26.670	info	6 Feb 22:51:26 - [info] [debug:log_ack_false] { device: 'zigbee.0.84ba20fffe505301.target_temperature', T_Soll: 15, ack: false, room: 'Esszimmer' }
zigbee.0
	2023-02-06 22:51:21.115	error	No state available for 'GS361A-H04' with key 'local_temp_calibration'
node-red.0
	2023-02-06 22:51:21.097	info	6 Feb 22:51:21 - [info] [debug:TRV Calibration EZ] -3
zigbee.0
	2023-02-06 22:51:12.611	error	No state available for 'GS361A-H04' with key 'local_temp_calibration'
zigbee.0
	2023-02-06 22:51:12.600	warn	ELEVATED Change state 'local_temp_calibration' at device 0x84ba20fffe566f85 type 'GS361A-H04'
zigbee.0
	2023-02-06 22:51:12.588	warn	ELEVATED: User stateChange zigbee.0.84ba20fffe566f85.local_temp_calibration {"val":-6,"ack":false,"ts":1675720272582,"q":0,"from":"system.adapter.node-red.0","user":"system.user.admin","lc":1675719663629}
node-red.0
	2023-02-06 22:51:12.572	info	6 Feb 22:51:12 - [info] [debug:TRV Calibration WZ] -6 
```

**Comment by asgothian** [comment]
> Then I excluded the device type and restarted (complete iob restart). Now I'm getting plenty errors "No state available ... with key..." See log below.
> Since it is now even claiming that it doesn't know "target_temperature", I will include in in the adapter again for now. "Cold house anxiety."

Did you run the state cleanup after excluding the device ? It seems that you were accessing states which were no longer available through the exposes.

A.

**Comment by heiko3967** [comment]
Double checked. Apparently I screwed up the cleaning, you're right. Now the object looks like this:

![grafik](https://user-images.githubusercontent.com/121965060/217106850-6447c208-20ad-4490-9a8d-842cf67f8dbd.png)

No target_temperature anymore, indeed. I was assuming that current_heating_setpoint might be the "new name" and set a value there. No ack. Quiet log apart from

```
zigbee.0 | 2023-02-06 23:59:13.483 | warn | ELEVATED Change state 'current_heating_setpoint' at device 0x84ba20fffe566f85 type 'GS361A-H04'
zigbee.0 | 2023-02-06 23:59:13.472 | warn | ELEVATED:  User stateChange zigbee.0.84ba20fffe566f85.current_heating_setpoint  {"val":18,"ack":false,"ts":1675724353463,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1675724353463}
```
If I change the heating point at the device, it is reflected in the dp. And I can change it sending payload ""current_heating_setpoint": 20". So, that's OK.
But unfortunately there is nothing that looks like a temperature calibration setting. Is it simply not supported by the device, or is hiding somewhere?

**Comment by asgothian** [comment]
[This page](https://www.zigbee2mqtt.io/devices/GS361A-H04.html) makes no mention of a temperature calibration setting. As such I would assume that it does not exist.

**Comment by heiko3967** [comment]
OK, so it seems I was simply mislead by the data points iob shows by default. Well, at least I learned something. 
Thanks!

**Comment by devdev42** [comment]
> The purpose of the test is to determine if there is any code within the iobroker.zigbee adapter which affects the generated states. With the device placed in the list of excluded devices, any device specific code within the zigbee adapter is excluded.
> 
> This is the desired mode of operation - newer devices use this by default.
> 
> Note that you need to restart the adapter after adding the device, and you may need to run state cleanup to eliminate states which are no longer connected.
> 
> Once that is done, add the ieee of one of your 6 devices to `zigbee.0.info.debugmessages` to generate warning messages for every state change. Check these for strange behaviour.
> 
> A.

FINALLY had time to follow your instruction. Will keep an eye on it and inform you when strange behavior comes up.

**Comment by devdev42** [comment]
So far the only apparent behavior is that none of the other adapters can read (or write) any values of my excluded thermostat objects. 

When I inspect one of the thermostats the following values are list as null after state cleanup: 
* child_lock
* position _(read-only)_
* running_state _(read-only)_
* send_payload
* valve_detection
* window_detection

Manually manipulating _writable_ attributes (also those which where initially null) works and is logged with 
`ELEVATED Change state …`

Changing those attributes by different adapters (namely yahka and heating control) has no effect on the object and is logged with
`warn | ELEVATED Change state 'target_temperature' at device 0x84ba20fffe0231ee type 'GS361A-H04'`
`error | No state available for 'GS361A-H04' with key 'target_temperature'`

What's the next step @asgothian ?

**Comment by asgothian** [comment]
the next step is to analyse the elevated messages. They consist of 2 messages for each state change - one describing the change and one the value which is sent to device.
