### ISSUE TITLE
Object will not be reported in future

### ISSUE THREAD

**Issue by cb1000r** [ioBroker/ioBroker.zigbee#1669]
am I right to give feedback this way? I'm using a silver crest (in germany supplied by lidl) smart plug. It reports following issue:

This object will not be created in future versions. Please report this to the developer.
--
zigbee.0 | 2023-01-29 11:41:32.041 | warn | Object zigbee.0.5c0272fffe942c03.power_on_behavior is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-01-29 11:41:32.023 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-01-29 11:41:32.022 | warn | Object 5c0272fffe942c03.power_on_behavior is invalid: obj.common.states has an invalid type! Expected "object", received "string"

**Comment by asgothian** [comment]
Context please.

- what adapter version
- what coordinator
- when exactly do you get the message ?

A.

**Comment by cb1000r** [comment]
It's a smart plug from lidl in germany (picture enclosed). Connected to a cc2531 controller. I get the message in ioBroker protocol, after binding smart plug to ioBroker.
![logfile](https://user-images.githubusercontent.com/123869696/215599802-4942c219-10f9-4eea-b01f-4a85f48e8558.jpg)
![IMG_6791](https://user-images.githubusercontent.com/123869696/215599832-9e2a88b3-938f-40ef-9c69-2d28e33a6adf.jpg)
Adapter is Zigbee Version 1.8.10

**Comment by asgothian** [comment]
If this occurs on Adding the plug only, this is known and under review.

Thank you
