### ISSUE TITLE
Networkmap not working in ioBroker

### ISSUE THREAD

**Issue by gemo-bi** [ioBroker/ioBroker.zigbee#1670]
get no Parent-Info in the networkmap.
![image](https://user-images.githubusercontent.com/62117738/215332419-f57b240a-16b8-4d3e-9279-f4820b317604.png)

**Comment by asgothian** [comment]
Give it time. Depending on your coordinator, setting up the map can take up to 240 seconds.

**Comment by gemo-bi** [comment]
thx. is working, after 4 minutes the map was displayed.
