### ISSUE TITLE
Please implement TuYa MIR-HE200-TY *NEWS*

### ISSUE THREAD

**Issue by Surripio** [ioBroker/ioBroker.zigbee#1672]
Hi,

i have the newest GIT Version 1.8.10 of the zigbee adapter.
I can see the MIR-HE200-ty but without functions.

More Informations:
TuYa MIR-HE200-TY (https://www.zigbee2mqtt.io/devices/MIR-HE200-TY.html)

pls help

**Comment by asgothian** [comment]
> pls help

Instructions what do do are [here](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device).

Implementation is impossible without physical access to the device. Plus it's a TuYa Device.

A.

**Comment by Surripio** [comment]
Hi,

i hope this informations a the right:

0x0c4314fffef9f534
genBasic (0)
genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
genOta (25)
genTime (10)

LOG:
SUCCESS {"hwVersion":1}
SUCCESS {"zclVersion":3}
SUCCESS {"appVersion":65}
SUCCESS {"stackVersion":0}
SUCCESS {"hwVersion":1}
SUCCESS {"manufacturerName":"_TZE200_jkbljri7"}
SUCCESS {"modelId":"TS0601"}
SUCCESS {"dateCode":""}
SUCCESS {"powerSource":1}
SUCCESS {"nameSupport":0}
SUCCESS {"count":0}
SUCCESS {"currentScene":0}
SUCCESS {"currentGroup":0}
SUCCESS {"sceneValid":0}
SUCCESS {"nameSupport":0}

anyone can help me out, whats the next steps?
