### ISSUE TITLE
Erstellte Gruppe schaltet alle Zigbee Leuchtmittel 

### ISSUE THREAD

**Issue by Hohenbostler** [ioBroker/ioBroker.zigbee#1678]
Ich habe mir heute 2 Stimmungslichter vom Lidl geholt. beide angelernt und in eine Gruppe geworfen und einfach mal die Gruppe von false auf true gewechselt. 

Und zack gehen alle Zigbee Lampen mit an. Lampen die gar nicht in dieser Gruppe sind. 

Die anderen lampen die mit angehen sind sowohl auch vom Lidl als auch von Ikea.

**Comment by asgothian** [comment]
Mehr Details bitte
- zigbee Adapter version
- Koordinator version
- betroffene Leuchtmittel (genau)

**Comment by Hohenbostler** [comment]
Hi, klar

Zigbee Adapter Version: 1.8.10

Koordinator Version: 
type:ConBee2/RaspBee2
version:0-0.38.120.0.
revision:0x26780700
port:/dev/ttyACM0
channel:11

Betroffene Lampen: 

model:[HG07834A]
model:[LED2005R5]
model:[14156506L]

**Comment by asgothian** [comment]
Bitte mal eine neue Gruppe anlegen. Keine Geräte hinzufügen, Gruppe schalten.

Danach die Lampen in die Gruppe hinzufügen, Gruppe schalten.

A.
