### ISSUE TITLE
Blitzwolf SHP-15 (power_outage_memory invaild)

### ISSUE THREAD

**Issue by Day1983** [ioBroker/ioBroker.zigbee#1679]
HAllo,

ich hab bei meinen Plug probleme - insbesondere beim stage "Power"... wird gehen die Dinger (egal ob Blitzwolf, oder andere) oft auf "0" runter, obwohl der Backofen noch läuft. 
Da haut es mit den Devices-reminder Adapter natürlich durcheinander  ;-)

Zudem werden Plug vom Gleichen Typ unterschiedlich im Adapter dargestellt?!? (Schönheitssache? Oder unterschiedlich erkannt?)

Beim einrichten/paring kommt diese Meldung im LOG:

`<html>
<body>

zigbee.0 | 2023-02-04 08:18:53.605 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2023-02-04 08:18:53.604 | warn | Object zigbee.0.84ba20fffe6e71a9.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-02-04 08:18:53.604 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-02-04 08:18:53.604 | warn | Object zigbee.0.84ba20fffe6e71a9.power_outage_memory is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-02-04 08:18:53.601 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-02-04 08:18:53.600 | warn | Object 84ba20fffe6e71a9.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-02-04 08:18:53.600 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-02-04 08:18:53.600 | warn | Object 84ba20fffe6e71a9.power_outage_memory is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-02-04 08:18:53.524 | info | DeviceConfigure successful 0x84ba20fffe6e71a9 TS011F
zigbee.0 | 2023-02-04 08:18:53.410 | info | Configuring 0x84ba20fffe6e71a9 TS011F

</body>
</html>`

![image](https://user-images.githubusercontent.com/77491820/216755623-fb6c567b-8622-4b40-a9b5-187562e3474e.png)

![image](https://user-images.githubusercontent.com/77491820/216755755-4f60831e-4170-4012-99e3-e31875d7f2d0.png)

**Comment by Sascha8** [comment]
Hi,
das trifft auch auf meine Tuya Clones zu. 2 aus China geben auch mehr oder weniger regelmäßig 0 Watt zurück, obwohl die den laufenden PC versorgen. Dagegen hab ich eine in DE gekauft, wo das bisher nicht auftrat. Die Daten sind bei beiden nahezu gleich. Anbei die Unterschiede der Daten.


`Fehlerhaft:                                                       Ohne Problem:`
```
model:TS011F_plug_1                           
description:Smart plug (with power monitoring)
modelZigbee:TS011F
type:Router
nwk:26108                                                      nwk:59821
manuf id:4417
manufacturer:_TZ3000_typdpbpg                                manufacturer:_TZ3000_gjnozsaz
power:Mains (single phase)
app version:192
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
seMetering (1794)
haElectricalMeasurement (2820)
manuSpecificBosch (57344)
manuSpecificTuya_3 (57345)
genBasic (0)
output clusters:genOta (25)
genTime (10)
endpoint:242
profile:41440
output clusters:greenPower (33)
```

**Comment by asgothian** [comment]
Willkommen in der Welt von TuYa.

Da lässt sich leider wenig tun. Die Warnmeldung beim Hinzufügen wird noch untersucht - hat aber mit Deinem Problem nichts zu tun. Wenn du wissen willst ob der Wert wirklich von der Steckdose kommt solltest du die IEEE der Steckdose in den Datenpunkt `zigbee.x.info.debugmessages` eintragen (An stelle des x die Instanznummer). Dann bekommst du für jede Aktualisierung die die Steckdose sendet 2 Warn-Meldungen mit dem Schlüsselwort "ELEVATED" im Log wo du sehen kannst was die Dose meldet und was der Adapter daraus macht.

Ansonsten macht der Adapter das was er soll - er zeigt die Daten der Steckdose an.
