### ISSUE TITLE
Luminea Home Control ZX-5240-675 (CCT Filament Lampe von Pearl) 

### ISSUE THREAD

**Issue by Peet1985** [ioBroker/ioBroker.zigbee#1680]
Hallo,

Ich habe versucht das oben erwähnte Leuchtmittel in ioBroker einzulernen aber es kommt nur:

Error: Device 0xa4c13877b292dbd6 "TS0502B" not described in statesMapping.. undefined
New device joined '0xa4c13877b292dbd6' model TS0502B
Interview successful: [object Object]
Interview started: 0xa4c13877b292dbd6

Ist es möglich das Leuchtmittel doch zu verwenden?

Vielen Dank
Peet

**Comment by asgothian** [comment]
Ist es auf zigbee2mqtt.io als "supported" gelistet ?

**Comment by Peet1985** [comment]
das Leuchtmittel an sich nicht aber der TuYa-Controller der erkannt wird schon. 
[https://www.zigbee2mqtt.io/devices/TS0502B.html](url)

**Comment by asgothian** [comment]
Hast du einen dedizierten Controller oder ist das eine Lampe mit eingebautem Controller ?

Im ersten Fall sollte es so gehen, im 2. Fall muss die Lampe bei zigbee2mqtt.io eingebunden werden - das geht nicht ohne Lampe.  Eine Anleitung dazu was zu tun ist findest Du hier: https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device

A.

**Comment by Peet1985** [comment]
Das ist ein in der Lampe verbaute Controller. Die Lampen dürften aber die selben Funktionen wie der Controller haben.

Ich habe das mal versucht was in dem link steht aber irgendwie werde ich nicht schlau. Gibt es keine möglichkeit dem Adapter zu sagen, dass er die Lampen wie den Controller behandeln soll?

**Comment by asgothian** [comment]
Das versucht er automatisch. Es scheint nicht zu funktionieren.

A.

**Comment by Peet1985** [comment]
Achso ok, also habe ich keine Chance? 

Zur Not muss ich sie halt zurück schicken. Bei den Dingern war der Preis halt genial für eine CCT Filamentlampe.

**Comment by asgothian** [comment]
Du hast 3 Optionen:
- Zurück schicken 
- Warten 
- issue am Zigbee-herdsman-converters project aufmachen damit das Device da integriert wird.


Ohne zugriff auf das Device ist eine Integration schwierig, insbesondere bei TuYa Devices.

A.

**Comment by Peet1985** [comment]
Ich könnte eine Lampe zur verfügung stellen, habe ja jetzt welche über. :)

**Comment by asgothian** [comment]
Aktualisier mal bitte den Adapter mit der Version von GitHub - es gab da Probleme bei der unterliegenden Bibliothek. 
Danach einfach nur den Adapter neu starten und schauen wie die Geräte im Objektbaum auftauchen bzw. einmal Infoanzeige (Rückseite der Sache, das i) zeigen.

A.

**Comment by Peet1985** [comment]
Ich habe das Problem gefunden. Ich betreibe ioBroker auf einem Proxmox-Server im Keller und Zigbee mache ich über einen Raspberry Pi als Host. Wenn ich den Zigbee-Adapter aktualiert habe, wurde der nicht auf dem Host aktualisiert. Das Aktualisieren über Konsole klappte auch nicht da der Adapter sich nicht höher als v1.5.6 updaten ließ. Node.js ließ sich auch nicht aktualisieren also habe ich den Host neu aufgesetzt und habe jetzt v1.8.10 installiert. Jetzt werden die Gledopto und sogar auch die Luminea problemlos erkannt.

Vielen Dank für den Support.

**Comment by asgothian** [comment]
Da bin ich doch froh das es eine so einfache Lösung war.
