### ISSUE TITLE
Lidl Plug - warning messages

### ISSUE THREAD

**Issue by c-hum** [ioBroker/ioBroker.zigbee#1681]
Withe the actual Github version (updated 20 minutes ago) I get the following warnings for the two following devices:
https://www.zigbee2mqtt.io/devices/HG06338.html
https://www.zigbee2mqtt.io/devices/HG06337.html

<html>
<body>

zigbee.0 | 2023-02-09 17:38:12.165 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2023-02-09 17:38:12.165 | warn | Object xxx.power_on_behavior is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-02-09 17:38:12.130 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-02-09 17:38:12.129 | warn | Object xxx.power_on_behavior is invalid: obj.common.states has an invalid type! Expected "object", received "string"

</body>
</html>

**Comment by asgothian** [comment]
- when exactly do you get the message ?
- do the devices work afterwards >

A.

**Comment by c-hum** [comment]
It appeared after the zigbee adapter restarted after the update. I restarted the adapter again and did not get this massage again. The devices work. So maybe the issue can be closed.
