### ISSUE TITLE
Error 240 on send command

### ISSUE THREAD

**Issue by StefanTR96** [ioBroker/ioBroker.zigbee#1684]
Hi,

I'm running iobroker on a Proxmox server and using a CC2531 and the Zigbee Adapter to connect with my Zigbee devices. The System worked well for a few days but now I get following errors every few Seconds. 

`Error 240 on send command to 0x84ba20fffe28b5c0. Error: Error: Command 0x84ba20fffe28b5c0/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":47,"datatype":2,"data":[0,0,0,3]}]}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240)) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)`

The problem is for several installed Radiator Valves of the type Ketotek KTF0177
Has anyone an Idea whats the reason for this error? 

Regards

Stefan

**Comment by asgothian** [comment]
I would point this towards either wireless issues (the coordinator does not receive a response from the device) or coordinator based issues (the cc2531 is a very weak coordinator.)

Please verify the load on the 2.4 GHz band, in use by
Zigbee
WLan (2.4 GHz)
Bluetooth
Dect
a large number of off the shelf wireless accessories (Keyboards, Headphones, Remote Controls)

A

**Comment by StefanTR96** [comment]
How can I verify the load on 2,4g?
I still changed the channel of the WIFI manually to channel 6, The Zigbee runs on Channel 11. I tried changing Zigbe to chanel 24 but after doing this, the adapter doesn't connect with device or service and stays yellow. 

Which Coordinator would you suggest? 

S

**Comment by asgothian** [comment]
- Most Wifi routers offer the ability to scan channel loads. You can use this feature to get an idea of the wifi channel occupation
- when you change the zigbee Adapter channel, you need to re-pair every device.
- Note that wifi channels and zigbee Channels do not follow the same numbering scheme. A search (on the web) should provide you with an image - I don't have one here right now.
- Any of the recommended coordinators on this page (https://www.zigbee2mqtt.io/guide/adapters/) are decent choices. I personally would opt for one with the TI chipset - this will allow for migration without having to re-pair all devices.
A.
