### ISSUE TITLE
Swap coordinator conbee to conbee2

### ISSUE THREAD

**Issue by Paalap** [ioBroker/ioBroker.zigbee#1685]
Hi, is there a way to swap/change the coordinator (in my case conbee to conbee2)without reconnecting all devices? (Which would be quite painfully for me as there are 12 inwall switches)

Or is the general recommendation to go with a different coordinator?

Thanks

**Comment by asgothian** [comment]
No.

With the conbee type coordinator, there is no guaranteed way to swap them without having to rebuild the zigbee network.

If you want to be able to change coordinator, i would select one of the ti based coordinators listed as 'recommended' at zigbee2mqtt.io

A.

**Comment by Paalap** [comment]
No guaranteed way sounds like there is a way I could try?

**Comment by asgothian** [comment]
- stop the zigbee adapter
- Shut down all routers on the network
- remove old conbee
- add conbee2
- start instance
- wait 120 seconds
- start turning on the routers one by one
- pray.

A.
