### ISSUE TITLE
This object will not be created in future versions. Please report this to the developer.

### ISSUE THREAD

**Issue by UweLm** [ioBroker/ioBroker.zigbee#1686]
ZigBee: 1.8.10
Admin 6.3.5
Plattform: linux
Node.js: v16.19.0(16.19.1)
NPM: 8.19.3

Got several messages about objects which will not be created in future versions.
I've paired two thermostatic valves:
SEA801-Zigbee/SEA802-Zigbee
tuya_TS0601

Is there anything I can do to fix this myself (config)?

Thank you for any information about this warning.

KR Uwe

**Comment by asgothian** [comment]
As long as they appear only when pairing, things are ok for now. The issue is being worked on.

A.

**Comment by UweLm** [comment]
Thanks for the quick reply.
KR Uwe
