### ISSUE TITLE
No converter available for 'xxxxxx' with cluster 'genOta' and type 'commandQueryNextImageRequest'

### ISSUE THREAD

**Issue by MischaI** [ioBroker/ioBroker.zigbee#1689]
Zigbee-Adapter -> check ota updates -> klick auf dem gerät auf start ota update -> finished, see logs ->
```
<html>
<body>
<!--StartFragment-->

zigbee.0 | 2023-02-24 11:03:31.345 | error | Update of '0x0000000000000000' failed (No new image available)
-- | -- | -- | --
zigbee.0 | 2023-02-24 11:03:31.343 | debug | getNewImage for '0x0000000000000000', meta {"fileVersion":65554,"url":"http://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.046/bin/10076692-zingo_lds_bulb_hwpwmcs_ws-1.0.012.ota.ota.signed"}
zigbee.0 | 2023-02-24 11:03:30.804 | debug | No converter available for 'LED1936G5' with cluster 'genOta' and type 'commandQueryNextImageRequest'
zigbee.0 | 2023-02-24 11:03:30.725 | debug | Got OTA request '{"fieldControl":1,"manufacturerCode":4476,"imageType":8709,"fileVersion":65554}'

<!--EndFragment-->
</body>
</html>
```
ieee vom gerät getausch auf 0x0000000000000000, damit ich hier posten kann

betroffen:
https://www.zigbee2mqtt.io/devices/LED1936G5.html 
https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html

Mod Edit: Code Tags.

**Comment by asgothian** [comment]
- Welche Adapter Version ?
- Installiert von ?
- Bitte Aktuelle Version von Github installieren - testen ob der Fehler noch da ist.

A

**Comment by MischaI** [comment]
v1.8.10
installiert von Adapter.
wenn ich aktuelle Version aus Github installiere, muss ich dann alle Geräte neu anlernen, und alle Stellen, Scripte und Adapter, wo ich Zigbee Objekte/States benutze auch anpassen?

**Comment by asgothian** [comment]
Nein. Du musst nichts neu anlernen. Selbst wenn du das müsstest - die State-Namen sind hardwareabhängig - deine Skripte und so weiter bleiben also erhalten.

A.

**Comment by MischaI** [comment]
aktualisiert auf v1.8.11-> bei der betroffenen Geräten  jetzt keine neue firmware updates verfügbar.

**Comment by arteck** [comment]
installer die 1.8.13 von GIT
