### ISSUE TITLE
 link_quality is always 255 or 10

### ISSUE THREAD

**Issue by gemo-bi** [ioBroker/ioBroker.zigbee#1692]
Hello, the link_quality of my devices are 255 or 10
Zigbee-Adapter 1.8.10
Nodejs: v18.14.2

thx, for your help

![2023-02-27 19_29_47](https://user-images.githubusercontent.com/62117738/221653716-85d938c3-792f-40ad-a070-31d3deb384a0.png)
![Screenshot 2023-02-27 194136](https://user-images.githubusercontent.com/62117738/221654036-968566c3-f0ae-472d-91ea-ce7e0e47cebd.png)

**Comment by asgothian** [comment]
Please add the last 4 digits of any of the devices to the state zigbee.0.info.debugmessages, and check the log for ELEVATED messages coming with the link quality.

I assume those will contain the value 255.

This is a common issue with Conbee / Conbee 2 networks.

A.

**Comment by gemo-bi** [comment]
You're right
interesting, a few days ago it still worked. Is it related to a firmware update from the Conbee2 stick?

zigbee.0 | 2023-02-28 18:55:13.671 | warn | ELEVATED publishToState: value generated '255' from device a4c13804e80ab84a for 'Link quality'

**Comment by arteck** [comment]
10 is a start value direct after adapter start .. but 255 is strange

**Comment by gemo-bi** [comment]
I have now installed deConz on my PC and connected the Conbee Stick. I think link quality and LQI is the same. Here the LQI looks correct and plausible. 255 is a correct value,  but that each connected device has a value of 255 is not OK

 https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/LQI-explained

these are my devices via deconz:
![Screenshot 2023-03-05 090012](https://user-images.githubusercontent.com/62117738/222949166-89f3660a-20bc-41c5-8689-d918388ab761.png)

**Comment by asgothian** [comment]
This is an issue with the implementation of the deconz hardware in the zigbee-herdsman. There is nothing the zigbee adapter can do to fix this.

A.
