### ISSUE TITLE
Please implement "Iluminize 5110.40"

### ISSUE THREAD

**Issue by mofi107** [ioBroker/ioBroker.zigbee#1699]
I tried to connect my Iluminize 5110.40 Zigbee 3.0 LED Controller Multi 5 - 4A.
Unfortunately, he is recognized as Iluminize 5112.80.

I found the device already in the Zigbee2MQTT device list:
https://www.zigbee2mqtt.io/devices/5110.40.html

I would be very happy if this device is supported in the Zigbee Adapter soon.

Regards 
Mo

**Comment by asgothian** [comment]
Please install the latest version from GitHub. It should support the device

A.
