### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#17]
after new flash the device cc2531 the knows devices should work direktly or after re-pairing??

**Comment by kirovilya** [comment]
I think they will work right away, without re-pairing.

**Comment by arteck** [comment]
no no....is only a question :-)

**Comment by kirovilya** [comment]
> where is the ieee adress (offset length) in the db of cc2531 stick ??

I don not known... when you flash, you must preserve ieee address (by default in Flash Programmer).

> it is possible pairing a bulb or what ever with 2 or more cc2531?? or is it only 1 to 1

pairing only 1 to 1. each zigbee-device must be in only one zigbee-network.

**Comment by arteck** [comment]
>     it is possible pairing a bulb or what ever with 2 or more cc2531?? or is it only 1 to 1
> 
> pairing only 1 to 1. each zigbee-device must be in only one zigbee-network.

i know but i can flash 2 sticks with the same ieee adress..  hardware backup as example

**Comment by kirovilya** [comment]
You will try it and tell what is happend :))

**Comment by arteck** [comment]
:-)
