### ISSUE TITLE
Tuya ZG-227ZL (Zigbee Thermometer/Hygrometer) - calibration with negative number not working

### ISSUE THREAD

**Issue by JorinL** [ioBroker/ioBroker.zigbee#1702]
Hey there,

the Tuya ZG-227ZL offers 2 data points for calibration:
- temperature_calibration range from -2 to 2
- humidity_calibration range from -30 to 30
Both work with positive number but any negative value is not working correctly for me.

I tried sending a payload and using the calibration data points.
```
{
  "humidity_calibration": "-2",
}
```
Brings out a 254 at the datapoint humidity_calibration - changes nothing on humidity at all.

```
{
  "temperature_calibration": "-2",
}
```
Brings out a 2 at the datapoint temperature_calibration - calculates this 2 on top of temperature (22 will get to 24).

So for me currently no negative values can be transported to the Unit at all.

Am I making something wrong?
In general I need to wake the device with a press on the button which changes between "F" and "C°". After that it receives the calibration values.

I tried with send payload and directly on the datapoint:

- -2
-  -2.0
-  "-2"
- "-2.0"

No success yet.

Zigbee Adapter Version installed: v1.8.10

**Comment by arteck** [comment]
and with new version ??
