### ISSUE TITLE
Update Bosch Thermostat II nicht möglich, no Converter available

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.zigbee#1703]
Hi,

könnt ihr bitte bei Gelegenheit den Adapter erweitern damit das Update für Bosch Thermostat II auch funktioniert. Es gibt hier seit kurzem ein Update, https://github.com/Koenkk/zigbee-OTA/pull/279

Im Log kommt folgende Meldung bei Suche nach Updates,

zigbee.0 | 2023-03-12 07:28:36.447 | info | Failed to check if update available for '0x18fc2600000ae5c1' (this.warning is not a function)
-- | -- | -- | --

Vielen Dank

**Comment by MMeinhardt1** [comment]
Hier noch eine Debug-Ausgabe in der Hoffnung dass diese hilfreich ist.

Adapter | Zeit | Loglevel | Ausgabe
-- | -- | -- | --
zigbee.0 | 2023-03-12 07:52:19.787 | info | Failed to check if update available for '0x18fc2600000ae5c1' (this.warning is not a function)
zigbee.0 | 2023-03-12 07:52:19.785 | debug | Update available for '0x18fc2600000ae5c1': YES
zigbee.0 | 2023-03-12 07:52:19.785 | debug | Is new image available for '0x18fc2600000ae5c1', current '{"fieldControl":1,"manufacturerCode":4617,"imageType":12298,"fileVersion":839193876}', latest meta '{"fileVersion":872682772,"fileSize":165875,"url":"https://github.com/Koenkk/zigbee-OTA/raw/master/images/Bosch/0x1209_0x300a_0x34041514.ota","sha512":"f298dcb46a62a09d5206128704d6df86b2bcc9ef48e2498518a856bebdd9196c67a8e0445cdbe1e837077afea5d9d291f5be3709ac018aeb93a8b68e12608a87"}'
zigbee.0 | 2023-03-12 07:52:19.783 | debug | ZigbeeOTA: downloaded main index
zigbee.0 | 2023-03-12 07:52:19.703 | debug | No converter available for 'BTH-RA' with cluster 'genOta' and type 'commandQueryNextImageRequest'
zigbee.0 | 2023-03-12 07:52:19.687 | debug | Got OTA request '{"fieldControl":1,"manufacturerCode":4617,"imageType":12298,"fileVersion":839193876}'
zigbee.0 | 2023-03-12 07:52:19.686 | debug | Type commandQueryNextImageRequest device {"type":"device","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":30,"_type":"EndDevice","_ieeeAddr":"0x18fc2600000ae5c1","_networkAddress":22561,"_manufacturerID":4617,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":1,"profileID":260,"deviceID":769,"inputClusters":[0,1,3,4,32,513,516,2821],"outputClusters":[10,25],"deviceNetworkAddress":22561,"deviceIeeeAddress":"0x18fc2600000ae5c1","clusters":{"genBasic":{"attributes":{"modelId":"RBSH-TRV0-ZB-EU","manufacturerName":"BOSCH","powerSource":3,"zclVersion":8,"appVersion":1,"stackVersion":5,"hwVersion":1,"dateCode":"20220627","swBuildId":"3.02.05"}},"genPollCtrl":{"attributes":{"checkinInterval":6480}},"hvacThermostat":{"attributes":{"16391":1,"16416":100,"16450":0,"16451":0,"20496":0,"occupiedHeatingSetpoint":2100,"localTemp":2100,"localTemperatureCalibration":0}},"hvacUserInterfaceCfg":{"attributes":{"16395":0,"16442":10,"16443":7,"keypadLockout":0}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"_binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":513,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":516,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1}],"_configuredReportings":[{"cluster":513,"attrId":18,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":516,"attrId":1,"minRepIntval":10,"maxRepIntval":3600,"repChange":null},{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":513,"attrId":16391,"minRepIntval":0,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16416,"minRepIntval":0,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16450,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{},"pendingRequests":[]}],"_manufacturerName":"BOSCH","_powerSource":"Battery","_modelID":"RBSH-TRV0-ZB-EU","_applicationVersion":1,"_stackVersion":5,"_zclVersion":8,"_hardwareVersion":1,"_dateCode":"20220627","_softwareBuildID":"3.02.05","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":-2029614503},"_lastSeen":1678603939684,"_defaultSendRequestWhen":"active","_linkquality":63,"_lastDefaultResponseSequenceNumber":53},"mapped":{"zigbeeModel":["RBSH-TRV0-ZB-EU"],"model":"BTH-RA","vendor":"Bosch","description":"Radiator thermostat II","ota":{},"fromZigbee":[{"cluster":"hvacThermostat","type":["attributeReport","readResponse"]},{"cluster":"genPowerCfg","type":["attributeReport","readResponse"]},{"cluster":"hvacThermostat","type":["attributeReport","readResponse"]},{"cluster":"hvacUserInterfaceCfg","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["occupied_heating_setpoint"],"options":[{"type":"enum","name":"thermostat_unit","property":"thermostat_unit","access":2,"values":["celsius","fahrenheit"],"description":"Controls the temperature unit of the thermostat (default celsius)."}]},{"key":["local_temperature_calibration"]},{"key":["keypad_lockout"]},{"key":["window_open","boost","system_mode"]},{"key":["display_orientation","display_ontime","display_brightness","child_lock"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]},{"key":["reset"]}],"exposes":[{"type":"climate","features":[{"type":"numeric","name":"local_temperature","property":"local_temperature","access":1,"unit":"°C","description":"Current temperature measured on the device"},{"type":"numeric","name":"occupied_heating_setpoint","property":"occupied_heating_setpoint","access":7,"value_min":5,"value_max":30,"value_step":0.5,"unit":"°C","description":"Temperature setpoint"},{"type":"numeric","name":"local_temperature_calibration","property":"local_temperature_calibration","access":7,"value_min":-5,"value_max":5,"value_step":0.1,"unit":"°C","description":"Offset to be used in the local_temperature"},{"type":"enum","name":"system_mode","property":"system_mode","access":7,"values":["off","heat","auto"],"description":"Mode of this device"},{"type":"numeric","name":"pi_heating_demand","property":"pi_heating_demand","access":1,"value_min":0,"value_max":100,"unit":"%","description":"Position of the valve (= demanded heat) where 0% is fully closed and 100% is fully open"}]},{"type":"binary","name":"boost","property":"boost","access":7,"value_on":"ON","value_off":"OFF","description":"Activate Boost heating"},{"type":"binary","name":"window_open","property":"window_open","access":7,"value_on":"ON","value_off":"OFF","description":"Window open"},{"type":"enum","name":"display_orientation","property":"display_orientation","access":7,"values":["normal","flipped"],"description":"Display orientation"},{"type":"numeric","name":"display_ontime","property":"display_ontime","access":7,"value_min":5,"value_max":30,"description":"Specifies the diplay On-time"},{"type":"numeric","name":"display_brightness","property":"display_brightness","access":7,"value_min":0,"value_max":10,"description":"Specifies the brightness value of the display"},{"type":"lock","features":[{"type":"binary","name":"state","property":"child_lock","access":7,"value_on":"LOCK","value_off":"UNLOCK","description":"Enables/disables physical input on the device"}]},{"type":"numeric","name":"battery","property":"battery","access":1,"unit":"%","description":"Remaining battery in %, can take up to 24 hours before reported.","value_min":0,"value_max":100},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"options":["[Circular]"]},"name":"0x18fc2600000ae5c1"} incoming event: {"type":"commandQueryNextImageRequest","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":30,"_type":"EndDevice","_ieeeAddr":"0x18fc2600000ae5c1","_networkAddress":22561,"_manufacturerID":4617,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":1,"profileID":260,"deviceID":769,"inputClusters":[0,1,3,4,32,513,516,2821],"outputClusters":[10,25],"deviceNetworkAddress":22561,"deviceIeeeAddress":"0x18fc2600000ae5c1","clusters":{"genBasic":{"attributes":{"modelId":"RBSH-TRV0-ZB-EU","manufacturerName":"BOSCH","powerSource":3,"zclVersion":8,"appVersion":1,"stackVersion":5,"hwVersion":1,"dateCode":"20220627","swBuildId":"3.02.05"}},"genPollCtrl":{"attributes":{"checkinInterval":6480}},"hvacThermostat":{"attributes":{"16391":1,"16416":100,"16450":0,"16451":0,"20496":0,"occupiedHeatingSetpoint":2100,"localTemp":2100,"localTemperatureCalibration":0}},"hvacUserInterfaceCfg":{"attributes":{"16395":0,"16442":10,"16443":7,"keypadLockout":0}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"_binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":513,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":516,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1}],"_configuredReportings":[{"cluster":513,"attrId":18,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":516,"attrId":1,"minRepIntval":10,"maxRepIntval":3600,"repChange":null},{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":513,"attrId":16391,"minRepIntval":0,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16416,"minRepIntval":0,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16450,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{},"pendingRequests":[]}],"_manufacturerName":"BOSCH","_powerSource":"Battery","_modelID":"RBSH-TRV0-ZB-EU","_applicationVersion":1,"_stackVersion":5,"_zclVersion":8,"_hardwareVersion":1,"_dateCode":"20220627","_softwareBuildID":"3.02.05","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":-2029614503},"_lastSeen":1678603939684,"_defaultSendRequestWhen":"active","_linkquality":63,"_lastDefaultResponseSequenceNumber":53},"endpoint":"[Circular]","data":{"fieldControl":1,"manufacturerCode":4617,"imageType":12298,"fileVersion":839193876},"linkquality":63,"groupID":0,"cluster":"genOta","meta":{"zclTransactionSequenceNumber":56,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0}}}
zigbee.0 | 2023-03-12 07:52:19.685 | debug | Received Zigbee message from '0x18fc2600000ae5c1', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"manufacturerCode":4617,"imageType":12298,"fileVersion":839193876}' from endpoint 1 with groupID 0
zigbee.0 | 2023-03-12 07:52:19.685 | debug | handleMessage. {"type":"commandQueryNextImageRequest","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":30,"_type":"EndDevice","_ieeeAddr":"0x18fc2600000ae5c1","_networkAddress":22561,"_manufacturerID":4617,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":1,"profileID":260,"deviceID":769,"inputClusters":[0,1,3,4,32,513,516,2821],"outputClusters":[10,25],"deviceNetworkAddress":22561,"deviceIeeeAddress":"0x18fc2600000ae5c1","clusters":{"genBasic":{"attributes":{"modelId":"RBSH-TRV0-ZB-EU","manufacturerName":"BOSCH","powerSource":3,"zclVersion":8,"appVersion":1,"stackVersion":5,"hwVersion":1,"dateCode":"20220627","swBuildId":"3.02.05"}},"genPollCtrl":{"attributes":{"checkinInterval":6480}},"hvacThermostat":{"attributes":{"16391":1,"16416":100,"16450":0,"16451":0,"20496":0,"occupiedHeatingSetpoint":2100,"localTemp":2100,"localTemperatureCalibration":0}},"hvacUserInterfaceCfg":{"attributes":{"16395":0,"16442":10,"16443":7,"keypadLockout":0}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"_binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":513,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1},{"cluster":516,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b56805","endpointID":1}],"_configuredReportings":[{"cluster":513,"attrId":18,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":516,"attrId":1,"minRepIntval":10,"maxRepIntval":3600,"repChange":null},{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":513,"attrId":16391,"minRepIntval":0,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16416,"minRepIntval":0,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16450,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{},"pendingRequests":[]}],"_manufacturerName":"BOSCH","_powerSource":"Battery","_modelID":"RBSH-TRV0-ZB-EU","_applicationVersion":1,"_stackVersion":5,"_zclVersion":8,"_hardwareVersion":1,"_dateCode":"20220627","_softwareBuildID":"3.02.05","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":-2029614503},"_lastSeen":1678603939684,"_defaultSendRequestWhen":"active","_linkquality":63,"_lastDefaultResponseSequenceNumber":53},"endpoint":"[Circular]","data":{"fieldControl":1,"manufacturerCode":4617,"imageType":12298,"fileVersion":839193876},"linkquality":63,"groupID":0,"cluster":"genOta","meta":{"zclTransactionSequenceNumber":56,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0}}}
zigbee.0 | 2023-03-12 07:52:17.398 | debug | Using endpoint '1'
zigbee.0 | 2023-03-12 07:52:17.397 | debug | Check if update available for '0x18fc2600000ae5c1' (RBSH-TRV0-ZB-EU

**Comment by MMeinhardt1** [comment]
Hallo @arteck und @asgothian,

sehr ihr hier eine Chance der Implementierung?

Vielen Dank und einen schönen Sonntag noch. 

Michael

**Comment by arteck** [comment]
das liegt im converter nicht bei uns

**Comment by MMeinhardt1** [comment]
Hmm, wenn Koenkk das in den Converter übernimmt und dieser dann auch im Adapter aktualisiert wird, sollte klappen? Bislang scheint es nur im Zigbee2mqtt drin zu sein. 

Vielen Dank

**Comment by arteck** [comment]
installier mal die GIT version..kommt es immer noch ?

**Comment by MMeinhardt1** [comment]
Guten Morgen,
es erscheint immer noch die gleiche Fehlermeldung auch wenn ich das device "ausschließe".

**Comment by MMeinhardt1** [comment]
Hi @arteck,
auch nach einem gerade eben durchgeführten Update über git bekomme ich weiterhin die Fehlermeldung. Kann ich irgendwas tun um zu unterstützen?

vielen Dank

**Comment by arteck** [comment]
schick mir die shepherd.db per email bitte

**Comment by MMeinhardt1** [comment]
@arteck 
Ist die email angekommen?

**Comment by arteck** [comment]
ja schau ich mir an

**Comment by MMeinhardt1** [comment]
Hi @arteck,
hast du schon Zeit gefunden schauen zu können?

Danke

**Comment by arteck** [comment]
installier von GIT und schau nochmal

**Comment by MMeinhardt1** [comment]
Hi @arteck 
es funktioniert leider immer noch nicht ☹️
Kann ich irgendwo sehen welche Version vom herdsman und welche vom converter geladen wird?
Konntest du in der shepherd.db etwas erkennen?

danke

**Comment by arteck** [comment]
wenn du heute von GIT installiert hast dann hast du die neuste Version.. hab die vorhin aktualisiert .es hab noch ein Problem mit dem Bosch

**Comment by MMeinhardt1** [comment]
Das dort die neueste Version drin ist habe ich gesehen, ich dachte nur es wäre praktisch sehen zu können welche Version im Adapter enthalten sind. Lässt sich dies einbinden so dass man es beim starten des Adapters sehen könnte. 
Hmm, warum klappt es denn mit dem Update noch nicht? Kann ich noch irgendwas zum Lösungsversuch beitragen?

**Comment by arteck** [comment]
du kannst es im intallationsordner sehen

**Comment by MMeinhardt1** [comment]
Gibt es denn sonst noch weitere Lösungsansätze zum OTA für den Thermostaten? Ich würde das Update wirklich gerne durchführen, da mit dem Update ein mögliches Fehlerbild behoben sein soll. 

Was sagt denn die Meldung aus meinem ersten Post aus?
Und ist der Debug-Ausschnitt aus meinem zweiten Post irgendwie hilfreich?


Dankeschön

**Comment by MMeinhardt1** [comment]
Hi @arteck und @asgothian,

gibt es denn noch irgendwelche Lösungsansätze um das OTA Problem lösen zu können?

Vielen Dank

**Comment by MMeinhardt1** [comment]
@arteck 
Kann es an der Firmware des Koordinators liegen? Ich habe die Platine im März 2022 über das Forum bei dir erworben, anbei ein Bild.

 ![image](https://user-images.githubusercontent.com/56205459/228944435-aadaa30d-413f-4367-ab75-a77ff233f859.jpeg)


Vielen Dank

**Comment by MMeinhardt1** [comment]
@arteck,
meinst du es könnte eventuell an der FW liegen und ein Update auf dem Koordinator könnte helfen?

Dankeschön

**Comment by MMeinhardt1** [comment]
Nach dem hier vorerst nichts mehr passiert ist, habe ich mir nen Sonoff Stick besorgt und diesen mit Zigbee2Mqtt von koenkk installiert und nach einigem hin und her konnte ich das Update auf dem Heizkörperthermostat  durchführen und das obwohl der ioBroker Zigbee Adapter und Zigbee2Mqtt gleich sein sollen, irgendwie merkwürdiges Zeugs dieses Zigbee.
Habe mir das ganze jetzt auch auf meinem Pi installiert und eingerichtet und bin erstmal auf den Zigbee2Mqtt Adapter für den ioBroker umgestiegen. Mal schauen ob das irgendiwe anders ist.

Schöne Ostertage!
