### ISSUE TITLE
Text in devices tap unreadable

### ISSUE THREAD

**Issue by OneCreek** [ioBroker/ioBroker.zigbee#1706]
More of a nice to have, but maybe it is doable without too much effort.

In some devices, the text shortened Exposes-Information from zigbee2mqtt is not readable and ends with "..." since the text is too long/big. Also hovering over it doesn't help. 
![grafik](https://user-images.githubusercontent.com/107502675/225688562-cb9d66b9-a8d9-40d9-992f-881010c83a62.png)

**Comment by arteck** [comment]
this info come direct from converter.... sry
