### ISSUE TITLE
Xiaomi SJCGQ11LM water sensor also has a temperature sensor

### ISSUE THREAD

**Issue by myssv** [ioBroker/ioBroker.zigbee#1707]
The Xiaomi SJCGQ11LM water sensor also has a temperature sensor, which is not shown at the moment.

https://www.zigbee2mqtt.io/devices/SJCGQ11LM.html

**Comment by arteck** [comment]
its only device temperature not air

**Comment by myssv** [comment]
The bottom line is that I don't care if it's the temperature inside the unit or outside the unit.

There are various cases where it is very helpful to know this temperature. Especially in the topic "frost warning".

As an example: I have an open/close sensor on the garage door and store certain things in the garage that are sensitive to frost. There it would be great if there is a frost warning.
Or I have a water sensor on my garden pump to be warned of leaks. Here, too, a frost warning would be super useful.

The sensor is there, so why not display the values?

Translated with www.DeepL.com/Translator (free version)
