### ISSUE TITLE
Probleme mit MOSZB-140 - no pairing.

### ISSUE THREAD

**Issue by JorinL** [ioBroker/ioBroker.zigbee#1710]
Dann hake ich mich mal rein.

Die Kopplung war leider nicht erfolgreich - ich dachte erst schon... aber ne er will einfach gar nicht erfolgreich koppeln.

```
Interview failed: 0x0015bc001a02976f
Error: Failed to interview '0x0015bc001a02976f', device has not successfully been paired. undefined. undefined
Pairing time left: 157
Pairing time left: 158
Pairing time left: 159
New device joined '0x0015bc001a02976f' model MOSZB-140
Device '0x0015bc001a02976f' announced itself
Pairing time left: 167
Interview started: 0x0015bc001a02976f
Pairing time left: 168
```

![image](https://user-images.githubusercontent.com/33031729/228940991-2b28b593-607b-4f06-b30c-355ac6ec2209.png)

![image](https://user-images.githubusercontent.com/33031729/228941040-38ad5c0f-2c42-47a2-b50a-8f0cb576a1c9.png)

![image](https://user-images.githubusercontent.com/33031729/228940833-ec12a279-9e2b-4168-b1de-2d848603022f.png)

![image](https://user-images.githubusercontent.com/33031729/228941133-6be1dd3f-f528-4f0f-994c-68da8ed5029c.png)

![image](https://user-images.githubusercontent.com/33031729/228941639-e7af0e93-d6a9-4135-925c-1acc0f2e3638.png)

Was kann ich tun?

Ich hab das Gerät jetzt erst ganz neu :-) und wäre hart Happy, wenn es funktioniert.
Machen wir den hier wieder auf - oder soll ich einen neuen Issue erstellen?

Hilft das hier eventuell?

https://github.com/Koenkk/zigbee2mqtt/issues/14277#issuecomment-1288183169

Bei denen geht es wieder ;-)

**Comment by DJ3vil** [comment]
+1 
It worked with v1.7.6!!!

**Comment by Streit187** [comment]
Pairing is working for me but no configure. 

`DeviceConfigure:Failed to DeviceConfigure.configure 0x0015bc001a0296dc MOSZB-140 (Error: Bind 0x0015bc001a0296dc/39 msIlluminanceMeasurement from '0x00212effff06c5f1/1' failed (waiting for response TIMEOUT) at DeconzAdapter.bind (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:678:19) at async Endpoint.bind (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:461:13) at async Object.bind (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:9) at async Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/develco.js:608:13) at async DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at async Promise.all (index 0) at async Commands.reconfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:517:21))`

**Comment by arteck** [comment]
you can send reconfigure with a button

**Comment by JorinL** [comment]
@arteck that is correct:

![image](https://user-images.githubusercontent.com/33031729/235307800-db73f572-912b-42ac-8678-be925f150dec.png)


But it changes nothing at all :-)

![image](https://user-images.githubusercontent.com/33031729/235307813-6e1189a2-d0f8-40ef-ad41-0638280bac14.png)

**Comment by Streit187** [comment]
Not completed.

**Comment by Streit187** [comment]
Please follow up on https://github.com/ioBroker/ioBroker.zigbee/issues/1770
