### ISSUE TITLE
New Device - IKEA E2112 - Vindstyrka air quality and humidity sensor

### ISSUE THREAD

**Issue by Peter1980FFM** [ioBroker/ioBroker.zigbee#1718]
Hello,
in Ikea i buy 2 of the Vindstyrka air quality and humidity sensors.
Now i see it doesn´t work with the Zigbee Adapter ;-(

I have found out that zibgee2mqtt have Implement it.
https://www.zigbee2mqtt.io/devices/E2112.html

https://github.com/Koenkk/zigbee2mqtt/issues/16717

Can someon Implement it?

**Comment by 777Timo** [comment]
Yeah, this would be great, if someone can implemet this sensor. Thanks in advance.

**Comment by BrotherEstapol** [comment]
I've got mine working, but only with Temp and Humidity, no other sensors yet.
To pair it, you need to press the button sync button x4 times and it'll appear.

**Comment by achimmm** [comment]
Hi, I got mine to connect but no blaues for temp and the other stuff. Error says that there is some states mapping missing.
Would be great if someone could add this sensor (zigbee2mqtt seams to support it already)

**Comment by arteck** [comment]
check new GIT version

**Comment by Peter1980FFM** [comment]
> check new GIT version

Thank you this is Working fine for me :-)

**Comment by achimmm** [comment]
👍. Thanks, works.

Am 09.07.2023 um 10:47 schrieb arteck ***@***.***>:

﻿

check new GIT version
