### ISSUE TITLE
EcoDim 8-button switch ED-10014 shows battery 200%

### ISSUE THREAD

**Issue by alex00fly** [ioBroker/ioBroker.zigbee#1722]
I have one of this button installed and it works just fine. The problem is that i get lots of log entries because of battery value is more than max value of 100.

![26983CC8-06A3-48E3-A836-7AA522DD87C2](https://user-images.githubusercontent.com/73775304/232277303-abe90528-bd15-433e-b30e-a3e437d5bbd5.jpeg)

![0415A3C2-296B-4CA3-8981-7ACF05F6DADE](https://user-images.githubusercontent.com/73775304/232277541-280e8932-cf8e-40e9-8333-07b1209523c2.jpeg)

What can I do to fix that behaviour?
Thanks a lot Alex

**Comment by arteck** [comment]
hmm ..strange.. 
stop the adapter
and del only this one device from object tree 
then start the adapter

**Comment by arteck** [comment]
check this https://github.com/ioBroker/ioBroker.zigbee/tarball/testBattery

**Comment by alex00fly** [comment]
The Problem is not solved at all. Now there are messages, the battery is 120 percent.
