### ISSUE TITLE
Please add new device "TuYa TS0601_smart_air_house_keeper"

### ISSUE THREAD

**Issue by exaware** [ioBroker/ioBroker.zigbee#1723]
Ich halte die Werte nicht für realistisch. Mein CO2-Wert liegt immer etwa um die 360ppm, auch morgens im Schlafzimmer vor dem Lüften. Das kann doch nicht sein oder? Ich vermute, dass die Umrechnung fehlerhaft ist, da im Datenblatt andere Messbereiche angegeben sind.

![image](https://user-images.githubusercontent.com/55593493/233576510-2ef4ab01-8e1b-4f95-94a9-76b12d8ffe40.png)

**Comment by exaware** [comment]
Ich halte die Werte nicht für realistisch. Mein CO2-Wert liegt immer etwa um die 360ppm, auch morgens im Schlafzimmer vor dem Lüften. Das kann doch nicht sein oder? Ich vermute, dass hier bei der Umrechnung falsch ist, da im Datenblatt andere Messbereiche angegeben sind.

![image](https://user-images.githubusercontent.com/55593493/233576510-2ef4ab01-8e1b-4f95-94a9-76b12d8ffe40.png)

**Comment by arteck** [comment]
die Werte bekommen wir so vom converter.. wenn du der meinung bist das da was nicht stimmt musst du da dein issue platzieren
