### ISSUE TITLE
zigbee adapter crashing very often

### ISSUE THREAD

**Issue by astrakid** [ioBroker/ioBroker.zigbee#1725]
hi,
zigbee adapter is crashing very often. i was using 1.8.10, but also tested 1.8.11 as well as 1.8.9. same result.

1st error message:
Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

any idea how to solve it?

**Comment by arteck** [comment]
really... with 1 line from LOG ..
