### ISSUE TITLE
Betrifft den Hue Wall Switch

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/ioBroker.zigbee#1732]
![Bildschirmfoto 2023-05-01 um 11 42 21](https://user-images.githubusercontent.com/62701386/235436444-0802e2de-b93e-43a1-9ec2-7dbb7c5c92fb.png)
![Bildschirmfoto 2023-05-01 um 11 43 06](https://user-images.githubusercontent.com/62701386/235436523-409b1f6b-763d-47fe-bd44-426f4cf28b82.png)

Problem bei dem Gerät ist das Left hold immer auf true stehen bleibt.Es wechselt nicht mehr zurück auf false.
Ich benutze den mit einem Taster.
Ist dieser Fehler bekannt oder gibts eine Möglichkeit das man es so ans laufen bekommt?

Gruss Christoph

**Comment by arteck** [comment]
ist der right_hold ok..oder bleibt der auch auf true

**Comment by Trunks1982** [comment]
Hi ich benutze den als einfach Taster und kann dir das nicht beantworten.Aber der Rechte steht seid damals immer noch auf true.

**Comment by Trunks1982** [comment]
ja jetzt gerade.Bleibt alles beim alten.
![Bildschirmfoto 2023-07-11 um 10 36 50](https://github.com/ioBroker/ioBroker.zigbee/assets/62701386/a04ac970-d1cf-4aee-b106-3295fc2e5297)

**Comment by arteck** [comment]
machmal 

https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages

und poste das Ergebniss

einmal mit left_hold dann mit right_hold
ich will mal sehen was da gesendet wird

**Comment by Trunks1982** [comment]
![Bildschirmfoto 2023-08-10 um 21 15 08](https://github.com/ioBroker/ioBroker.zigbee/assets/62701386/031499e6-7514-4f05-ba00-2cf948dd991c)
hi ich hoffe du kannst es lesen.Die Meldung ist nur für den rechten Button weil der linke nicht angeschlossen ist.

**Comment by arteck** [comment]
also erstens.. kein screenshots.. soll ich jetzt mir die Message abtippen ??
und 2. tens das sit nicht das was ich haben wollte

**Comment by Trunks1982** [comment]
Konnte ich leider nicht wissen das du es in reiner Textform brauchst.Und ich hab das so verstanden das du den Abschnitt so brauchst wie es beschrieben wurde.

**Comment by Trunks1982** [comment]
[zigbeelog.txt](https://github.com/ioBroker/ioBroker.zigbee/files/12333753/zigbeelog.txt)

Hoffe das ich jetzt das richtige habe.

**Comment by Trunks1982** [comment]
[zigbeelog.txt](https://github.com/ioBroker/ioBroker.zigbee/files/12333779/zigbeelog.txt)


Hoffe das es diesmal richtig ist.

**Comment by arteck** [comment]
ok ich sags nochmal

LESEN dann MACHEN
https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages

dann das was da raus kommt POSTEN..

**Comment by Trunks1982** [comment]
> ok ich sags nochmal
> 
> LESEN dann MACHEN https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages
> 
> dann das was da raus kommt POSTEN..

Weiß nicht was ich anders mache.Mache es doch so wie es da steht.

**Comment by arteck** [comment]
zeigmal 
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/4ab08db0-d89d-443e-84a9-2626790ef3ac)
