### ISSUE TITLE
 Sonoff SNZB-02D error on reading properties

### ISSUE THREAD

**Issue by Newan** [ioBroker/ioBroker.zigbee#1733]
Add new Sonoff SNZB-02D to iobroker

Adapter Version: 1.8.10

<html>
<body>

zigbee.0 | 2023-05-03 23:18:43.489 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe77dcb1 SNZB-02D (TypeError: Cannot read properties of undefined (reading 'error') at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:193:24) at processTicksAndRejections (node:internal/process/task_queues:95:5) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
-- | -- | -- | --
zigbee.0 | 2023-05-03 23:18:39.748 | info | Configuring 0x30fb10fffe77dcb1 SNZB-02D
zigbee.0 | 2023-05-03 23:16:23.217 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe77dcb1 SNZB-02D (TypeError: Cannot read properties of undefined (reading 'error') at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:193:24) at processTicksAndRejections (node:internal/process/task_queues:95:5) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
zigbee.0 | 2023-05-03 23:16:19.470 | info | Configuring 0x30fb10fffe77dcb1 SNZB-02D
zigbee.0 | 2023-05-03 23:15:45.671 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe77dcb1 SNZB-02D (TypeError: Cannot read properties of undefined (reading 'error') at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:193:24) at processTicksAndRejections (node:internal/process/task_queues:95:5) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
zigbee.0 | 2023-05-03 23:15:42.258 | info | Configuring 0x30fb10fffe77dcb1 SNZB-02D
zigbee.0 | 2023-05-03 23:15:39.723 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe77dcb1 SNZB-02D (TypeError: Cannot read properties of undefined (reading 'error') at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:193:24) at processTicksAndRejections (node:internal/process/task_queues:95:5) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
zigbee.0 | 2023-05-03 23:15:36.287 | info | Configuring 0x30fb10fffe77dcb1 SNZB-02D

</body>
</html>

**Comment by arteck** [comment]
check with git version plz

**Comment by Newan** [comment]
zigbee.0 | 2023-05-14 08:23:42.548 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe77dcb1 SNZB-02D (Error: Bind 0x30fb10fffe77dcb1/1 msTemperatureMeasurement from '0x00124b0025791f48/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
-- | -- | -- | --

Update over github:
`   "zigbee-herdsman": "0.14.115",
    "zigbee-herdsman-converters": "15.0.110"`

**Comment by arteck** [comment]
ist das so ein Feuchtigkeit Temperatur gedönz ??
da scheint was nicht rüber zu kommen ...

**Comment by Newan** [comment]
Ja feuchte und Temperatur mit Display. Sehr schönes Gerät optisch

**Comment by Newan** [comment]
> ist das so ein Feuchtigkeit Temperatur gedönz ?? da scheint was nicht rüber zu kommen ... kannst das Ding nochmal anlernen ..aber lösche es vorher nicht

Ohne löschen hat es sich nzwar verbunden aber es kamen keine Werte mehr. Habe es nun gelöscht und ganz neu angeleernt.
Sieht sauber aus:



zigbee.0 | 2023-05-26 09:12:33.669 | info | DeviceConfigure successful 0x30fb10fffe77dcb1 SNZB-02D
-- | -- | -- | --
zigbee.0 | 2023-05-26 09:11:51.512 | info | Configuring 0x30fb10fffe77dcb1 SNZB-02D
zigbee.0 | 2023-05-26 09:11:51.512 | info | Device '0x30fb10fffe77dcb1' is supported, identified as: SONOFF Temperature and humidity sensor with screen (SNZB-02D)
zigbee.0 | 2023-05-26 09:11:51.512 | info | Successfully interviewed '0x30fb10fffe77dcb1', device has successfully been paired
zigbee.0 | 2023-05-26 09:11:41.101 | warn | Device '0x30fb10fffe77dcb1' announced itself
zigbee.0 | 2023-05-26 09:11:38.766 | info | Starting interview of '0x30fb10fffe77dcb1'
zigbee.0 | 2023-05-26 09:11:36.431 | info | Zigbee: allowing new devices to join.
