### ISSUE TITLE
DAC2161C TuYa Einphasenzähler mit Zigbee CC2652P2 TCP Ethernet Coordinator

### ISSUE THREAD

**Issue by Guenter-1953** [ioBroker/ioBroker.zigbee#1734]
Hallo,

ich habe mir 2 TUYA Einphasenzähler gekauft und habe die heute mittag im ioBroker im ZIGBEE Modul eingebunden. Das Ganze mittels Zigbee CC2652P2 TCP Ethernet Coordinator von cod.m nach einer Idee von Matthias Kleine von haus-automatisierung.com . 

Bei einem hat es sofort funktioniert und er wird im ioBroker.zigbee angezeigt als [TS0601_din_2](https://www.zigbee2mqtt.io/devices/TS0601_din_2.html) . Dort auf den Link gedrückt kommt man auf die TuYa TS10601_din_2 Seite. In den Objekten steht er auf available und zeigt auch Daten an. 

Bei dem Anderen hat die Verbindung zwar funktioniert, jedoch kennt ioBroker.zigbee das Gerat nicht komplett und es wird auch nur als  [TS0601](https://www.zigbee2mqtt.io/devices/TS0601.html) angezeigt. Hier gibt es zwar auch einen Link, der führt aber auf eine 404 Seite. 

**Mein Problem nun: Wie bekomme ich den zweiten auch als Energiezähler TS0601_din_2 in den ioBroker.zigbee rein.** 
 
Hier die Gerätebeschreibung: 

[Tuya Zigbee Einphasenzähler.pdf](https://github.com/ioBroker/ioBroker.zigbee/files/11408253/Tuya.Zigbee.Einphasenzahler.pdf)

Wäre super wenn mir jemand helfen könnte. Im Voraus besten Dank. Viele Grüße Günter

![2023-05-05 (2)](https://user-images.githubusercontent.com/75438387/236507985-f97ce0d0-a135-4464-9114-b1c5c463ae35.png)

![2023-05-05 (3)](https://user-images.githubusercontent.com/75438387/236508014-8613b68c-91a7-458d-834b-4be3e7512ebc.png)

![hat_nicht_funktioniert](https://user-images.githubusercontent.com/75438387/236506284-5138253c-2a69-4ddb-a1df-c809d171040b.png)

![hat_funktioniert](https://user-images.githubusercontent.com/75438387/236506356-b4deb1e2-4f43-481d-b9d5-83618630eff5.png)
![2023-05-05 (4)](https://user-images.githubusercontent.com/75438387/236511260-416db518-ccb8-4c12-a452-d26161efba44.png)

**Comment by arteck** [comment]
lerne es neu an.. dann sollte er auch kommen

**Comment by Guenter-1953** [comment]
Vielen Dank für die Antwort. Ich gehe davon aus, dass dies 2 identische Geräte sind. Bei beiden steht bei modelZigbee als Gerätetyp: TS0601. Was unterschiedlich ist der manufacturer: Da stehen die tze200 und die tze204. 

Jedenfalls geht es mit einem Original TuYa Adapter einwandfrei. 

Ich suche daher immer noch das Problem. Bei dem TZE200 kommt der Link mit dem Namen: "TS0601_din_2" und der wird auch erkannt. Bei dem anderen wird TZE204 geschrieben und der Link zu der Geräteliste als "TS0601" Und da kommt die 404 als Ergebnis. Da ich die Schnittstelle des Adapters nicht kenne denke ich rein hypothetisch, dass es bei dem zweiten auch einen Verweis gibt, der da auch ins Leere geht.
 
![2023-06-15](https://github.com/ioBroker/ioBroker.zigbee/assets/75438387/0641f0f6-2961-4561-8245-2ea0a3098f04)

**Comment by Guenter-1953** [comment]
So ich habe nochmals alles durchprobiert und möchte kurz zusammen fassen:

Der energy-meter TS0601 TZE200 hat die Zigbee-Modul-Version V1.0.7 und das MCU-Modul V1.0.0 und funktioniert einwandfrei.   
Der energy-meter TS0601 TZE204 hat die Zigbee-Modul-Version V1.0.10 und das MCU-Modul V1.0.0 und funktioniert nicht.

Bei der Zigbee-Modul-Version sagen beide in der TyUa IOS APP es wäre die neueste Version. Beide Geräte funktionieren auf der IOS APP einwandfrei mit einem MoesGo Tuya ZigBee Smart Gateway Hub (kein affiliate: https://www.amazon.de/gp/product/B08DKKSCLP)

Auf den beiden Verpackungen stehen komplett die gleichen Daten. Energy Meter Model No. DAC2161C. Manufacturer Dongguan Pinja Technology Co. Itd.

Ich bestelle mir jetzt einen neuen und hoffe der läuft mit diesem Adapter hier im ioBroker. Wenn ich soweit bin und es funktioniert kann ich diesen nicht lauffähigen dem Entwicklerteam als Leihgabe zum Testen senden. Bitte daher melden.
-------------------------------------------------------------------------------------------------------
So I tried everything again and like to give a summary here:

The energy-meter TS0601 TZE200 has Zigbee module version V1.0.7 and MCU module V1.0.0 and works perfectly.
The energy-meter TS0601 TZE204 has Zigbee module version V1.0.10 and MCU module V1.0.0 and does not work.

For the Zigbee module version, both in the TyUa IOS APP said that this is the newest version. Both devices work fine in the IOS APP with the Tyua Smart Modul V.5.1.2 and the tested MoesGo Tuya ZigBee Smart Gateway Hub here (no affiliate link: https://www.amazon.de/gp/product/B08DKKSCLP)

The two packages contain the same data. Energy meter model no. DAC2161C. Manufacturer Dongguan Pinja Technology Co.Itd.

I will order a new one now and I hope it works with this adapter here in ioBroker. When I'm ready and it works, I can send this non-executable item to the development team for testing. So please report me if this is ok

**Comment by arteck** [comment]
probier mal mit neuer adapter version
