### ISSUE TITLE
TI CC26X2R1 lässt sich nicht einbinden.

### ISSUE THREAD

**Issue by JogiBarbarski** [ioBroker/ioBroker.zigbee#1737]
Hallo , das TI CC26X2R1 lässt sich auf dem Raspberry Pi 4, 8 GB mit 64 Bit und Bullseye unter ls -l /dev/serial/by-id nicht mehr finden und einbinden. Somit sind alle Zigbee Geräte unbrauchbar. Weiß man wann eine Lösung in Sicht ist? 
Ist bestimmt viel Arbeit und nicht leicht. Oder liegt es an Debian Bullseye
ioBroker.admin v6.4.3
Node.js: v18.16.0
NPM: 9.5.1
js-controller
JS controller Installiert: 4.0.24
OS: linux
Latest
auf SSD 1 TB
Herzlichen Dank für eure Arbeit.

**Comment by Grothesk242** [comment]
Liegt an udev: 

https://forum.iobroker.net/topic/65017/zigbee-conbee2-funktioniert-nach-update-nicht-mehr-udev?_=1684524468402
