### ISSUE TITLE
Missing Device graphics

### ISSUE THREAD

**Issue by dp20eic** [ioBroker/ioBroker.zigbee#1738]
Hi,

I did update the adapter from GIT today, and after I check it I saw, that some graphics missing. I did upload again, but graphics not shown.
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/71387331/75605c00-9854-4410-a214-623f49bf1c45)

```
model: [HG06492B]
description:Livarno Lux E14 candle CCT
(https://www.zigbee2mqtt.io/devices/HG06492B.html)
```

Adapter Version 1.8.11

With kind regards
Bernd

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update

**Comment by dp20eic** [comment]
> https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update

Moin,

sorry forgot to say, that I always did uploads, and in the actual 1.8.12 it is the same, this image is missing, I did upload several times, with no luck.

VG
Bernd

**Comment by dp20eic** [comment]
Moin,

die aktuelle Version V 1.8.13 von Github behebt dieses Problem

VG
Bernd
