### ISSUE TITLE
Devices cannot be pinged

### ISSUE THREAD

**Issue by iobroker-nutzer** [ioBroker/ioBroker.zigbee#1739]
Since around two weeks, my Zigbee Adapter is not able to ping devices, or communicate with them. I cannot add new devices and in the log are multiple warnings like these:
DeviceAvailability:Failed to ping 0xb4c138e3021c1cc0 TS011F
DeviceAvailability:Stopping to ping 0xa4f148d89c4ct634 TS011F after 89 ping attempts

The Adapter still receives values like temperature and power consumption of plugs
I am running ioBrooker in a LXC Container on Proxmox; 
nodejs: 18.16.0, 
npm: 9.5.1
Zigbee: 1.8.11

**Comment by arteck** [comment]
we stopped ping when the device are not available.. check link_quality for this device
