### ISSUE TITLE
New Device INNR RB 279 T

### ISSUE THREAD

**Issue by ccabek** [ioBroker/ioBroker.zigbee#1740]
Hi,
there is a new variant of the INNR LED. RB 279 T is the follower of RB 278 T.
It has the same function.
Can you please add it to the device.js ?

 line 1576       models: ['RB 178 T', 'RB 278 T'], -->         models: ['RB 178 T', 'RB 278 T', 'RB 279 T'],

Thank you

**Comment by arteck** [comment]
check new adapter version

**Comment by ccabek** [comment]
In the current master branch I don't find a match for RB 279 in the device.js. I will not install the new adapter.
