### ISSUE TITLE
Device SONOFZBMINI has an invalid type

### ISSUE THREAD

**Issue by lykane1337** [ioBroker/ioBroker.zigbee#1742]
Dear zigbee-Team,

thank you a lot for your great work. Your adapter makes my (and my familys) life so much better.

Since a few days i have an unsupported device. My Sonoff mini disappears after a few minutes form the devicelist. When i am pairing again, the device connects but after a few minutes it is not availible anymore. In my logs are the following entries.

zigbee.0 | 2023-05-27 00:19:58.654 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2023-05-27 00:19:58.653 | warn | Object 8cf681fffe2a5616.power_on_behavior is invalid: obj.common.states has an invalid type! Expected "object", received "string"`

I have changed the object type in the object browser to object and reinstalled the adapter. I tried an old version from the stable repository, but it still did not work continuously.

Version: 1.8.10
Plattform: linux - Raspberry Pi 4
RAM: 1.8 GB
Node.js: v16.20.0(18.16.0)
NPM: 8.19.4(9.5.1)
Device: https://www.zigbee2mqtt.io/devices/ZBMINI.html

Do you need any further informations? Did i do something wrong? Can you help me?

Thanks a lot in advance
lykane

btw: Issue #1737 helped me already with an other problem. THX

**Comment by lykane1337** [comment]
Hello,

now i have reseted my device a few times via the button (press button 10 sek.) and powered off the device before. Since 24h it does not desappear anymore.

But if I change the "power on behavior" in the logs the following entry shows up 
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/64777033/38104148-d9eb-42d4-846d-a54d2d69d65c)

zigbee.0 | 2023-05-31 11:23:44.223 | warn | Send command to 0x00124b0024c7bfc6 failed with: Code 134 (Unsupported Attribute)

Best regards

**Comment by arteck** [comment]
check new version from GIT

**Comment by lykane1337** [comment]
Thank you!!
