### ISSUE TITLE
TS0601_temperature_humidity_sensor not working

### ISSUE THREAD

**Issue by gemo-bi** [ioBroker/ioBroker.zigbee#1747]
Hello, same problem as  #1683 "TS0601_temperature_humidity_sensor not working". After new Installation on raspbian bullseye. I get no temperatur and humidity.
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/62117738/3d5a787d-c270-41bd-862e-4095b29d7caa)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/62117738/f344833d-1f85-4a25-9eb4-c15b2c654c46)

if i set the debugmessages, i can see the elevated logs.
if i use the ts0601_a.js-file and the external converter, i get an error in the iob-log:

zigbee.0 | 2023-06-08 18:56:46.364 | error | error applying external converters
@asgothian you solved this in feb maybe you can help me again

With Zigbee1.8.10 and the external converter it is working.

Zigbee Ver: 1.8.11
Node.js v18.16.0
npm 9.5.1
js-controller: 4.0.24

**Comment by arteck** [comment]
show me this information
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/1e2bd3fd-cad9-4850-9e65-ed394ac57132)

**Comment by gemo-bi** [comment]
model:[TS0601_temperature_humidity_sensor_1](https://www.zigbee2mqtt.io/devices/TS0601_temperature_humidity_sensor_1.html)
description:Temperature & humidity sensor
modelZigbee:TS0601
type:EndDevice
nwk:23877
manuf id:4417
manufacturer:_TZE200_bjawzodf
power:Battery
app version:70
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
genBasic (0)
output clusters:genOta (25)
genTime (10)
