### ISSUE TITLE
Incomplete information for ZM-CSW032-D 

### ISSUE THREAD

**Issue by PastCoder** [ioBroker/ioBroker.zigbee#1748]
I recently installed [ZM-CSW032-D](https://www.zigbee2mqtt.io/devices/ZM-CSW032-D.html). It is recognized and I can set state for open/close. 
But besides that some information seems to be not updated correctly (e.g. position). When moving the blind on the device (touch the buttons), then even the stop state is not set correctly.
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/23421026/09d76afe-13a1-4f32-97b4-b315efcec6e8)

**Comment by arteck** [comment]
check new adapter version
