### ISSUE TITLE
Zigbee adapter problems with Nous A1Z and Vindstyrka

### ISSUE THREAD

**Issue by Llouvin** [ioBroker/ioBroker.zigbee#1749]
Good morning,
I have the ConBee II running on a Raspi 4. So far everything ok.
The Zigbee adapter runs version 1.8.10.
I have four Nous A1Z running. Also OK.
The Vindstyrka air quality sensor was already running, but was thrown out during an update. I can't say where because I didn't notice. Now the question mark "unknown device" is displayed.
If I update the Zigbee adapter to Beta 1.8.11, then I have the Vindstyrka again as an active and working device in the system. However, the Nous A1Z are then displayed as unknown devices and can no longer be operated.
After downgrading the Zigbee adapter to 1.8.10, the Nous A1Z work again, but the Vindstyrka no longer works.

Anyone have an idea or advice?

Thanks very much.
Olli

**Comment by arteck** [comment]
i know .. the converter has a issue wit Nous A1Z..

**Comment by arteck** [comment]
check now from GIT
