### ISSUE TITLE
Insatalationsprobleme vom Sonoff Temperatursensor (error)

### ISSUE THREAD

**Issue by Duffy987** [ioBroker/ioBroker.zigbee#1750]
Hallo,
bei der Kopplung des Sonoff SNZB-02D kommt folgende Meldung:
Hello,
When pairing the Sonoff SNZB-02D, the following message appears:

`Pairing time left
Pairing time left: 1
Pairing time left: 2
Pairing time left: 3
Pairing time left: 4
Pairing time left: 5
Pairing time left: 6
Pairing time left: 7
Error: DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe6ec573 SNZB-02D (TypeError: Cannot read properties of undefined (reading 'error')
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:193:24)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17)). undefined
Pairing time left: 8
Pairing time left: 9
Pairing time left: 10
Error: DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe6ed0d5 SNZB-02D (TypeError: Cannot read properties of undefined (reading 'error')
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:193:24)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17)). undefined
Pairing time left: 11
Pairing time left: 12
Pairing time left: 13
Pairing time left: 14
Pairing time left: 15
Pairing time left: 16
Pairing time left: 17
Pairing time left: 18
Pairing time left: 19
Pairing time left: 20
Pairing time left: 21
Pairing time left: 22
Error: DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe6ed0d5 SNZB-02D (TypeError: Cannot read properties of undefined (reading 'error')
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:193:24)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17)). undefined
Pairing time left: 23
New device joined '0x30fb10fffe6ed0d5' model SNZB-02D
Interview successful: {"friendly_name":"0x30fb10fffe6ed0d5","model":"SNZB-02D","vendor":"SONOFF","description":"Temperature and humidity sensor with screen","supported":true}
Pairing time left: 24
Pairing time left: 25
Pairing time left: 26
Pairing time left: 27
Pairing time left: 28
Pairing time left: 29
Pairing time left: 30
Pairing time left: 31
Pairing time left: 32
Pairing time left: 33
Pairing time left: 34
Pairing time left: 35
Pairing time left: 36
Pairing time left: 37
Pairing time left: 38
Pairing time left: 39
Pairing time left: 40
Device '0x30fb10fffe6ed0d5' announced itself
Pairing time left: 41
Pairing time left: 42
Pairing time left: 43
Pairing time left: 44
Pairing time left: 45
Pairing time left: 46
Pairing time left: 47
Device '0x30fb10fffe6ed0d5' announced itself
Pairing time left: 48
Pairing time left: 49
Pairing time left: 50
Interview started: 0x30fb10fffe6ed0d5
Pairing time left: 51
Pairing time left: 52
Pairing time left: 53
Pairing time left: 54
Pairing time left: 55
Pairing time left: 56
Pairing time left: 57
Pairing time left: 58
Pairing time left: 59
Pairing time left: 60
Pairing started `

Nach dem Koppeln kommt dann im Protokoll folgender Fehler:
After pairing, the following error appears in the log:

`DeviceConfigure:Failed to DeviceConfigure.configure 0x30fb10fffe6ed0d5 SNZB-02D (TypeError: Cannot read properties of undefined (reading 'error') at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:193:24) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))`

Gibt es eine Möglichkeit den Sensor fehlerfrei zu koppeln?
Is there a way to pair the sensor correctly?

Regards Duffy

**Comment by arteck** [comment]
adapterversion ??

**Comment by Duffy987** [comment]
Zigbee Adapter 1.8.10

Viele Grüße

**Comment by ali86x** [comment]
Hier auch nochmal. 
Selber Gerät, selber Problem. 
Adapter und Firmware aktuell.

**Comment by Duffy987** [comment]
Kurze Rückmeldung meinerseits:

Seit dem der Zigbee Adapter 1.8.12 (stable) erschienen ist gehören die Probleme mit dem SonofSNZB-02D der Vergangenheit an. Er wird nun sauber erkannt und es erscheinen keine Fehler mehr im Protokoll.

Danke für das einpflegen der für die Funktion nötigen Daten.

Gruß Duffy
