### ISSUE TITLE
Geräte umbenennen nicht mehr möglich

### ISSUE THREAD

**Issue by skipperkm** [ioBroker/ioBroker.zigbee#1751]
Im Adapter lassen sich die Geräte nicht mehr umbenennen. Die komplette Icon-Leiste im Gerät läßt sich nicht mehr bedienen.

Gruß

**Comment by arteck** [comment]
????????????????????????????
aha.. und was soll ich jetzt mit dier Information

welche Adapter version 
welche Admin verison 

welche iconliste ??

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1726
