### ISSUE TITLE
Unknown Device

### ISSUE THREAD

**Issue by Jacke87** [ioBroker/ioBroker.zigbee#1752]
Hallo ich habe ein Zigbee Smart Switch von earu erworben EAYCBM-T-1P . Dieser wird mir leider nur als TS0601 angezeigt. Ich habe den Debug Modus im Adapter eingestellt um ihn evtl. selber anzulernen. dort sehe ich aber nur das er sich angemeldet hat und ich bekomme Meldungen wenn ich versuche im etwas zu senden. Ich habe leider keine Ahnung wie ich ihn anlernen soll.
Für Hilfe wäre ich sehr dankbar

Hello I have purchased a Zigbee Smart Switch from earu EAYCBM-T-1P . Unfortunately, this is only displayed to me as TS0601. I have set the debug mode in the adapter to learn it myself. there I only see that he has registered and I get messages when I try to send something. Unfortunately I have no idea how to train it.
I would be very thankful for help

[https://de.aliexpress.com/item/1005004894129906.html?spm=a2g0o.detail.1000014.17.77768451h3etm0&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.40050.281175.0&scm_id=1007.40050.281175.0&scm-url=1007.40050.281175.0&pvid=5bcc80a0-63b2-4e51-9f9e-e3596fcfde0a&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.40050.281175.0,pvid:5bcc80a0-63b2-4e51-9f9e-e3596fcfde0a,tpp_buckets:668%232846%238107%231934&pdp_npi=3%40dis%21EUR%2133.66%2118.18%21%21%21%21%21%40211b5e2016873519066688263e66b1%2112000030925261845%21rec%21DE%21](url)

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/blob/master/docs/de/readme.md

**Comment by Jacke87** [comment]
Oh sorry i didn't see this.
Should i Opened a new Issue

modelZigbee:TS0601
type:Router
nwk:47995
manuf id:4098
manufacturer:_TZE204_davzgqq0
power:Mains (single phase)
app version:70
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
output clusters:genOta (25)
genTime (10)

It is a zigbee Smart Switch for DinRail with Power Meter
Thanks

**Comment by Jacke87** [comment]
Hi i followed the instruction under your link, but the Power meter still has no functions.
Need it a little mor time
`Nach Anpassung der relevanten Dateien muss der ZigBee-Adapter neugestartet und dann das ZigBee-Gerät vom Koordinator entkoppelt werden (unpair): 
Danach kann das Pairing wiederholt werden. Sollzustand nach dem Pairing:


Bei manchen ZigBee-Geräten ist es erforderlich alle Softwareschnittstellen ("exposes") des neuen ZigBee-Gerätes in den ioBroker-Objekten anzuzeigen, um alle Funktionen des ZigBee-Gerätes nutzen zu können. In solchen Fällen muss das neue ZigBee-Gerät in die "Ausschliessen"-Gruppe aufgenommen werden.



 ->  ->  -> ZigBee-Gerät (z.B. HOMA1001) auswählen -> 
Nach einem Neustart des ZigBee-Adapters sollte das neue ZigBee-Gerät nun uneingeschränkt funktionieren.`

these ar the Steps i followed
