### ISSUE TITLE
zigbee instance frequent crashes

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1755]
At first it looks like the instance starts and then it stops. Host alarms me that the adapter keeps on crashing. Could it have to do with the latest hosts version 5.0.5?

<html><body>

host.iobroker | 2023-06-25 11:56:17.672 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught by controller[1]:     at processTimers (node:internal/timers:499:9)
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught by controller[1]:     at runNextTicks (node:internal/process/task_queues:61:5)
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:699:22
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught by controller[1]:     at Zigbee.filterError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:142:18)
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught by controller[1]:     at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught  by controller[1]:     at Object.configureScope  (/opt/iobroker/node_modules/@iobroker/plugin-sentry/node_modules/@sentry/src/exports.ts:76:1)
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught  by controller[1]:     at Hub.configureScope  (/opt/iobroker/node_modules/@iobroker/plugin-sentry/node_modules/@sentry/src/hub.ts:340:1)
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
host.iobroker | 2023-06-25 11:56:17.672 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'Error')
host.iobroker | 2023-06-25 11:56:17.671 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-06-25 11:56:16.569 | error | Cannot read properties of undefined (reading 'Error')
zigbee.0 | 2023-06-25 11:56:16.568 | error | TypeError:  Cannot read properties of undefined (reading 'Error')    at  /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56    at  Hub.configureScope  (/opt/iobroker/node_modules/@iobroker/plugin-sentry/node_modules/@sentry/src/hub.ts:340:1)     at Object.configureScope  (/opt/iobroker/node_modules/@iobroker/plugin-sentry/node_modules/@sentry/src/exports.ts:76:1)     at Zigbee.sendError  (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)    at  Zigbee.filterError  (/opt/iobroker/node_modules/iobroker.zigbee/main.js:142:18)    at  /opt/iobroker/node_modules/iobroker.zigbee/main.js:699:22    at  runNextTicks (node:internal/process/task_queues:61:5)    at  processTimers (node:internal/timers:499:9)
zigbee.0 | 2023-06-25 11:56:16.555 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'Error')
zigbee.0 | 2023-06-25 11:56:16.554 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
zigbee.0 | 2023-06-25 11:56:16.545 | error | Send command to 0x84182600000fb538 failed with no error code (no response received (15)

</body>
</html>

**Comment by arteck** [comment]
switch sentry off.. and check new version from GIT

**Comment by daniel-lo** [comment]
Removing 0x84182600000fb538 had already helped. I did follow the instructions though - the more stable the better.
Thanks
