### ISSUE TITLE
Cannot Connect IKEA Tradfri Shortcut Button E1812

### ISSUE THREAD

**Issue by cherberg** [ioBroker/ioBroker.zigbee#1756]
Dear Developer,

I am using quite a few IKEA Shortcut buttons in my main iobroker installation using your plugin without any problems for years now. 

However on a new iobroker installation with Version 1.8.10 of your adapter the adding of these buttons fails. I have tried multiple times with different devices, all fail. Same applies to E1743 switches. Most of the times I get nothing during pairing. In some cases I get "Interview started" but then later "Failed to interview". In some rare cases I get an undefined device in the device overview.

`zigbee.0 | 2023-06-25 22:12:42.395 | info | Zigbee: stop joining
-- | -- | -- | --
zigbee.0 | 2023-06-25 22:12:10.631 | error | Failed to interview '0xb4e3f9fffe88ed7c', device has not successfully been paired. undefined
zigbee.0 | 2023-06-25 22:09:52.246 | info | Starting interview of '0xb4e3f9fffe88ed7c'
zigbee.0 | 2023-06-25 22:08:40.909 | info | Zigbee: allowing new devices to join.
`

I would appreciate if you could look into this.

NPM 9.5.1
Node.js 18.16.0

**Comment by arteck** [comment]
which chanel number you have ?? which coordinator ?? and firmware ?
