### ISSUE TITLE
Sonoff ZBMINIL2 Logdatei voller errors

### ISSUE THREAD

**Issue by Xerxes55** [ioBroker/ioBroker.zigbee#1766]
<html>
<body>

Schalter funktioniert einwandfrei, trotzdem erscheint in der Logdatei alle paar Minuten ein ERROR.

zigbee.0 | 2023-07-01 11:35:46.892 | info | Configuring 0x9035eafffe0d8d9c ZBMINIL2
-- | -- | -- | --
zigbee.0 | 2023-07-01 11:35:44.355 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x9035eafffe0d8d9c ZBMINIL2 (Error: Unbind 0x9035eafffe0d8d9c/1 genPollCtrl from '0x00212effff059d03/1' failed (Error: status: 136) at DeconzAdapter.unbind (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:820:19) at Endpoint.unbind (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:596:13) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/sonoff.js:72:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))

</body>
</html>

**Comment by arteck** [comment]
der kann das configure nicht empfangen.. warum auch immer

**Comment by Xerxes55** [comment]
Hi, wie kann ich die Meldung unterbinden?Am 04.07.2023 um 07:52 schrieb arteck ***@***.***>:﻿
der kann das configure nicht empfangen.. warum auch immer

**Comment by arteck** [comment]
error garnicht..versuch den nochmal anzulernen
