### ISSUE TITLE
Plug  _TZ3000_okaz9tjs not working anymore (aka B29, aka TS011F)

### ISSUE THREAD

**Issue by PastCoder** [ioBroker/ioBroker.zigbee#1769]
Hi,
I have two plug, which appear as follows:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/23421026/597b5461-0deb-493d-b3e0-083cf9bc41a2)

They did already work in the past, but stopped working a few weeks ago.
Now I get the following log message, when I try to change the state:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/23421026/fb206199-0b5d-4e9a-8ffd-e916cbeede88)

**Comment by m-s-b** [comment]
Same for Nous A1Z, also TS011F
`Device 0xa4c138db19fc6f09 "A1Z" not described in statesMapping.`
I´ve upgraded from 1.8.11 to 1.8.12 and all A1Z are not workinig any more. Downgraded to 1.8.10 and they are fine again. 
By the way, downgrade to 1.8.11 was not possible.

**Comment by arteck** [comment]
check now from GIT

**Comment by PastCoder** [comment]
With latest version from GitHub it works. 
Thanks!
