### ISSUE TITLE
WXKG02LM not working anymore

### ISSUE THREAD

**Issue by killakaktus** [ioBroker/ioBroker.zigbee#177]
Just updated to 0.9.0 and all of my WXKG02LM-switches no longer recognized. Also pairing fails.

**Comment by dimaiv7** [comment]
I have the same problem

**Comment by kirovilya** [comment]
I found bug... will fix

**Comment by kirovilya** [comment]
Check out 0.9.1

**Comment by dimaiv7** [comment]
works fine

**Comment by killakaktus** [comment]
yes, works fine. thanks!!
