### ISSUE TITLE
MOSZB-140 not working - undefined device

### ISSUE THREAD

**Issue by Streit187** [ioBroker/ioBroker.zigbee#1770]
modelZigbee:MOSZB-140
type:EndDevice
nwk:36342
manuf id:4117
manufacturer:frient A/S
power:Battery
hard version:2.2.0
zcl version:1
date code:20220810 19:32
build:4.0.3
interviewed:true
configured:false

Zigbee: v1.8.11

Pushing reconfigure does not solve the issue. 

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/78914691/2a4c628e-b405-41da-a982-9ef96b4fc5ea)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/78914691/5cbca7b9-25b2-482c-86be-1abc3cbf922c)

**Comment by arteck** [comment]
also with 1.8.12 from GIT ??

**Comment by Streit187** [comment]
Yes. Exactly the same. Adapter upodated, device deleted, adapter restart, device added with the same result.

**Comment by arteck** [comment]
check 1.8.13 plz

**Comment by DJ3vil** [comment]
Version: 1.8.13

model:[MOSZB-140](https://www.zigbee2mqtt.io/devices/MOSZB-140.html)
description:Motion sensor
modelZigbee:MOSZB-140
type:EndDevice
nwk:59477
manuf id:4117
manufacturer:frient A/S
power:Battery
hard version:2.2.0
zcl version:1
date code:20220305 14:59
build:4.0.3
**interviewed:true
configured:false**

**Comment by Streit187** [comment]
Yes, the same with 1.8.13. Device removed, device reset, adapter update, device added with the result.

**Comment by Streit187** [comment]
@arteck FYI: Since 1.8.12 at least Aqara MCCGQ11LM (Door & Window) is not getting any battery data like percentage and voltage. Downgrade to 1.8.10 and data are coming in.

**Comment by arteck** [comment]
new try ..check 1.8.15 from GIT

**Comment by Streit187** [comment]
Same result. 
interviewed:true
configured:false

<html>
<body>


zigbee.0 | 2023-07-11 18:06:52.538 | info | DeviceConfigure successful 0x0015bc001xxx MOSZB-140
-- | -- | -- | --
zigbee.0 | 2023-07-11 18:06:43.818 | info | Configuring 0x0015bc001xxx MOSZB-140
zigbee.0 | 2023-07-11 18:06:43.816 | info | Device '0x0015bc001xxx' is supported, identified as: Develco Motion sensor (MOSZB-140)
zigbee.0 | 2023-07-11 18:06:43.816 | info | Successfully interviewed '0x0015bc001xxx', device has successfully been paired
zigbee.0 | 2023-07-11 18:06:33.628 | info | Starting interview of '0x0015bc001xxx'


</body>
</html>

**Comment by Streit187** [comment]
@arteck Why closed? It is not solved and still the same problem.

**Comment by arteck** [comment]
DeviceConfigure successful 0x0015bc001xxx MOSZB-140 this is you old problem..and its solved

Device 0x0015bc001xxx "undefined" not described in statesMapping.

'undefined' is not a device...

**Comment by Streit187** [comment]
@arteck No. It is not solved. It is still the old problem. In the log is configured but on the information panel from device is 
interviewed:true
configured:false
This is exactly the situation from the beginning and it never changed.

**Comment by arteck** [comment]
configured parameter is not for all devices.
its only for devices with special params. like.. lumi sensor or hue dimmer ..

**Comment by Streit187** [comment]
Ok. But what is with the missing states for motion, occupancy aso?

**Comment by Streit187** [comment]
It looks like the same from the beginning. Nothing have changed since the issue was opened.

**Comment by Streit187** [comment]
@arteck So would you please be so kind and reopen the issue for further investigation.

**Comment by arteck** [comment]
really... ok here

**Comment by Streit187** [comment]
Perfect. Thank you. So if I can do anything to assist just let me know.

**Comment by DJ3vil** [comment]
any update here ?

**Comment by Streit187** [comment]
Unfortunately not.

**Comment by arteck** [comment]
> any update here ?

what's you problem ??

**Comment by Streit187** [comment]
I am quite sure it is the same problem. He would like to use the device but it is still undefined in the adapter.
