### ISSUE TITLE
Adapter läuft nach Update auf 1.8.12 nicht mehr

### ISSUE THREAD

**Issue by Matzebhv** [ioBroker/ioBroker.zigbee#1771]
Moin,

ich habe nach dem Update das folgende Problem:

`<html>
<body>

host.iOBroker | 2023-07-03 18:33:23.746 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.iOBroker | 2023-07-03 18:33:23.746 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iOBroker | 2023-07-03 18:33:23.746 | error | Caught by controller[0]: at processImmediate (node:internal/timers:447:9)
host.iOBroker | 2023-07-03 18:33:23.746 | error | Caught by controller[0]: at runNextTicks (node:internal/process/task_queues:60:5)
host.iOBroker | 2023-07-03 18:33:23.746 | error | Caught by controller[0]: at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:167:41)
host.iOBroker | 2023-07-03 18:33:23.746 | error | Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'filter')
host.iOBroker | 2023-07-03 18:33:23.746 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-07-03 18:33:22.815 | info | terminating
zigbee.0 | 2023-07-03 18:33:22.714 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2023-07-03 18:33:22.713 | info | terminating
zigbee.0 | 2023-07-03 18:33:22.618 | warn | DeviceAvailability:Failed to ping 0x842e14fffe5c0140 TS011F
zigbee.0 | 2023-07-03 18:33:22.261 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-07-03 18:33:22.213 | info | cleaned everything up...
zigbee.0 | 2023-07-03 18:33:22.211 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-07-03 18:33:22.211 | warn | Object 60a423fffe137ec1.power_on_behavior is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-07-03 18:33:22.211 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-07-03 18:33:22.211 | warn | Object 842e14fffe00d8cb.power_on_behavior is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-07-03 18:33:22.177 | error | Cannot read properties of undefined (reading 'filter')
zigbee.0 | 2023-07-03 18:33:22.176 | error | TypeError: Cannot read properties of undefined (reading 'filter') at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:167:41) at runNextTicks (node:internal/process/task_queues:60:5) at processImmediate (node:internal/timers:447:9)
zigbee.0 | 2023-07-03 18:33:22.176 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'filter')
zigbee.0 | 2023-07-03 18:33:22.176 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2023-07-03 18:33:22.161 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-07-03 18:33:22.160 | warn | Object ec1bbdfffeb4eba4.power_on_behavior is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-07-03 18:33:21.658 | warn | DeviceAvailability:Failed to ping 0xec1bbdfffeb4eba4 TS011F
zigbee.0 | 2023-07-03 18:33:21.581 | error | syncDevStates: Illegal state in {"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":14,"_type":"Router","_ieeeAddr":"0x84fd27fffece7167","_networkAddress":9492,"_manufacturerID":4098,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":1,"profileID":260,"deviceID":268,"inputClusters":[0,3,4,5,6,8,768,4096],"outputClusters":[25,10],"deviceNetworkAddress":9492,"deviceIeeeAddress":"0x84fd27fffece7167","clusters":{"genBasic":{"attributes":{"modelId":"TS0502A","manufacturerName":"_TZ3000_8uaoilu9","powerSource":1,"zclVersion":3,"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorMode":2,"colorTemperature":153,"options":2}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":255,"options":0}}},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":{},"sendInProgress":false},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":242,"profileID":41440,"deviceID":97,"inputClusters":[],"outputClusters":[33],"deviceNetworkAddress":9492,"deviceIeeeAddress":"0x84fd27fffece7167","clusters":{},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":{},"sendInProgress":false}],"_manufacturerName":"_TZ3000_8uaoilu9","_powerSource":"Mains (single phase)","_modelID":"TS0502A","_applicationVersion":80,"_stackVersion":0,"_zclVersion":3,"_hardwareVersion":1,"_dateCode":"","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":1811148075},"_lastSeen":1688401827815,"_defaultSendRequestWhen":"immediate","_pendingRequestTimeout":0} - "5"
zigbee.0 | 2023-07-03 18:33:21.401 | warn | setObject info.debugmessages (type=state) property common.role missing!
zigbee.0 | 2023-07-03 18:33:21.372 | warn | download icon from https://www.zigbee2mqtt.io/images/devices/HG08164.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/HG08164.png
zigbee.0 | 2023-07-03 18:33:21.366 | warn | download icon from https://www.zigbee2mqtt.io/images/devices/HG06335-HG07310.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/HG06335-HG07310.png
zigbee.0 | 2023-07-03 18:33:21.364 | warn | download icon from https://www.zigbee2mqtt.io/images/devices/HG06620.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/HG06620.png
zigbee.0 | 2023-07-03 18:33:21.363 | warn | download icon from https://www.zigbee2mqtt.io/images/devices/HG06619.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/HG06619.png
zigbee.0 | 2023-07-03 18:33:21.357 | warn | download icon from https://www.zigbee2mqtt.io/images/devices/HG06337.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/HG06337.png
zigbee.0 | 2023-07-03 18:33:21.352 | warn | download icon from https://www.zigbee2mqtt.io/images/devices/HG08164.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/HG08164.png
zigbee.0 | 2023-07-03 18:33:21.350 | info | Zigbee started
zigbee.0 | 2023-07-03 18:33:21.350 | info | 0x003c84fffe0dee70 (addr 64976): R7060 - Woox Smart garden irrigation control (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.349 | info | 0x540f57fffe8d6936 (addr 26691): R7060 - Woox Smart garden irrigation control (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.349 | info | 0x84ba20fffe2b33cc (addr 26358): R7060 - Woox Smart garden irrigation control (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.349 | info | 0x2c1165fffe5195b4 (addr 32718): HG08164 - Lidl Silvercrest smart button (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.348 | info | 0x00158d000836e900 (addr 48364): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.348 | info | 0x00158d0008303b5e (addr 37680): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.348 | info | 0x00158d0008378b87 (addr 5806): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.348 | info | 0x00158d0008329038 (addr 18034): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.347 | info | 0x00158d0008303cdd (addr 9860): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.347 | info | 0x00158d000832918a (addr 21162): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.347 | info | 0x00158d000832a2f3 (addr 46742): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.347 | info | 0x00158d000836e943 (addr 23294): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.346 | info | 0xec1bbdfffea13b15 (addr 24297): HG06335/HG07310 - Lidl Silvercrest smart motion sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.346 | info | 0x842e14fffe5c0140 (addr 29696): HG06338 - Lidl Silvercrest 3 gang switch, with 4 USB (EU, FR, CZ, BS) (Router)
zigbee.0 | 2023-07-03 18:33:21.346 | info | 0x60a423fffe137ec1 (addr 56678): HG06620 - Lidl Silvercrest garden spike with 2 sockets (Router)
zigbee.0 | 2023-07-03 18:33:21.345 | info | 0x842e14fffe00d8cb (addr 56636): HG06619 - Lidl Silvercrest outdoor plug (Router)
zigbee.0 | 2023-07-03 18:33:21.345 | info | 0x84fd27fffece7167 (addr 9492): 14153905L - Lidl Livarno Home LED floor lamp (Router)
zigbee.0 | 2023-07-03 18:33:21.345 | info | 0x00158d0002583b59 (addr 42602): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.344 | info | 0x00158d000257f6e6 (addr 8509): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.344 | info | 0x00158d000257e9e1 (addr 46069): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.343 | info | 0x00158d000257f636 (addr 57958): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.343 | info | 0x00158d0002c08835 (addr 60631): RTCGQ01LM - Xiaomi MiJia human body movement sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.343 | info | 0x00158d0002c9ffca (addr 34462): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.342 | info | 0x00158d0002c7d66a (addr 26773): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.342 | info | 0x00158d0002c18377 (addr 48582): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.341 | warn | setObject info.undefinedDevices (type=state) property common.role missing!
zigbee.0 | 2023-07-03 18:33:21.341 | info | 0xec1bbdfffeb4eba4 (addr 50915): HG06337 - Lidl Silvercrest smart plug (EU, CH, FR, BS, DK) (Router)
zigbee.0 | 2023-07-03 18:33:21.340 | info | 0x2c1165fffe390644 (addr 55244): HG08164 - Lidl Silvercrest smart button (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.338 | info | 0x00158d0002bfbf7c (addr 20671): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2023-07-03 18:33:21.306 | info | Currently 28 devices are joined:
zigbee.0 | 2023-07-03 18:33:21.204 | info | --> transmitPower : high+
zigbee.0 | 2023-07-03 18:33:21.197 | info | Unable to disable LED, unsupported function.
zigbee.0 | 2023-07-03 18:33:21.193 | info | Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20211116}}
zigbee.0 | 2023-07-03 18:33:20.602 | info | Installed Version: iobroker.zigbee@1.8.12
zigbee.0 | 2023-07-03 18:33:20.504 | info | Starting Zigbee npm ...
zigbee.0 | 2023-07-03 18:33:20.503 | info | delete old Backup files. keep only last 10
zigbee.0 | 2023-07-03 18:33:20.448 | info | starting. Version 1.8.12 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.16.1, js-controller: 5.0.6

</body>
</html>`

Der Adapter startet ein paar mal neu, bis er vom Host gekillt wird. Ein downgrade auf die 1.8.10 behebt das Problem.
Aktuelles Debian Bookworm
Nodejs 18.16.1
NPM 9.5.1

Gruß
Matze

**Comment by arteck** [comment]
installier mal die GIT version ..

**Comment by Matzebhv** [comment]
Moin, habe ich probiert, keine Änderung.

**Comment by kollabo89** [comment]
ich habe das selbe problem. hab schon version 1.8.13 drauf aber leider stürzt es bei mir auch immer ab. das passiert immer wenn einige geräte nicht erreichbar sind weil sie ausgeschaltet sind. wenn alle geräte erreichbar sind scheint alles zu funktionieren.

**Comment by arteck** [comment]
ich brauch die shepherd.db

**Comment by kollabo89** [comment]
Kann ich dir die datei irgendwie schicken oder soll ich sie als text hier einfügen?

**Comment by kollabo89** [comment]
bei mir ist folgende situation. ich habe eine steckdose die schaltet eine leiste mit 2 anderen steckdosen ab. anschließend habe ich die beiden abgeschalteten immer auf aus gestellt damit sie beim nächsten mal an machen der steckdosenleiste auch als aus erkannt werden. dieser befehl hat wohl immer dafür gesorgt das der adapter abstürzt. ich habe den befehl jetzt raus genommen und jetzt bleibt der adapter auch aktiv.

**Comment by Matzebhv** [comment]
Grade die aktuelle Version 1.8.14 installiert. Hier scheint das Problem behoben zu sein,
