### ISSUE TITLE
Developer report JS Controller 5.0.6

### ISSUE THREAD

**Issue by ToTXR4Y** [ioBroker/ioBroker.zigbee#1772]
<html><body>

zigbee.0 | 2023-07-03 21:47:07.510 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2023-07-03 21:47:07.510 | warn | Object  ec1bbdfffed4e8e0.power_on_behavior is invalid: obj.common.states has an  invalid type! Expected "object", received "string"
zigbee.0 | 2023-07-03 21:47:07.509 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-07-03 21:47:07.508 | warn | Object  ec1bbdfffefd3069.power_on_behavior is invalid: obj.common.states has an  invalid type! Expected "object", received "string"
zigbee.0 | 2023-07-03 21:47:07.486 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-07-03 21:47:07.485 | warn | Object  842e14fffe6278b2.power_on_behavior is invalid: obj.common.states has an  invalid type! Expected "object", received "string"
zigbee.0 | 2023-07-03 21:47:06.929 | warn | setObject info.debugmessages (type=state) property common.role missing!

</body>
</html>

**Comment by arteck** [comment]
which device ??

**Comment by ToTXR4Y** [comment]
> which device ??

Silvercrest Plugs HG06337

**Comment by arteck** [comment]
check with GIT version
