### ISSUE TITLE
Lidl LED Device HG08131C wir nach Adapter Upgrade nicht mehr erkannt.

### ISSUE THREAD

**Issue by Menne01** [ioBroker/ioBroker.zigbee#1774]
Hi,
beim Adapter Ugrade von 1.8.10  zu 1.8.12 wird die LED Device Lidl  HG08131C nicht mehr erkannt
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/89869516/dc7b20ef-9994-4ccc-85f7-d1b8080719af)
und kann nicht mehr gesteuert werden. Available ist sie aber und erscheint in der Tafel als Fragezeichen, sowohl auch im Zigbee Netz.

Grüße

**Comment by arteck** [comment]
zeigmal die kachel mit der infoseite

**Comment by RP70DP** [comment]
Ebenfalls werden durch v1.8.12 nicht mehr erkannt, bzw. sind nicht mehr zu pairen, weitere Lidl-Geräte:
![Livarno Mood Light](https://github.com/ioBroker/ioBroker.zigbee/assets/62850183/d7997b5c-996d-4e5b-a4ef-f99100cd1aa8)
![Livarno Outdoor Spotlight](https://github.com/ioBroker/ioBroker.zigbee/assets/62850183/a6b86ec0-e42e-47c6-b0e1-f6eda9241b20)
![TS0505B](https://github.com/ioBroker/ioBroker.zigbee/assets/62850183/5d558157-ef5e-48de-b1f0-168a1e95f0cf)

**Comment by Menne01** [comment]
@arteck ,
1.8.10
 ![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/89869516/b88f4705-96ea-4d4d-b783-b38c43df456b)
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/89869516/0f261165-362a-4b59-b10a-034957d1358e)

1.8.12
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/89869516/746fcf8c-4def-45fe-bacc-33d8fea8c7e4)
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/89869516/fcebcdf3-07df-4246-a506-85ff9ca06d9e)

Grüße

**Comment by arteck** [comment]
ja ich weiss.. der converter hat sich ein wenig geändert..

**Comment by arteck** [comment]
installier mal von GIT

**Comment by RP70DP** [comment]
Läuft wieder!

**Comment by Menne01** [comment]
Ich schließ mich an....läuft.

Grüße
