### ISSUE TITLE
Version 1.8.12 Fehler in Ikea Light Bull

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.zigbee#1775]
Das Schreiben der Farbe auf den Ikea Light Bulb erzeugt eine Fehlermeldung mit V.1.8.12 des Zigbee Adapters.
```
Send command to 0x8cf681fffe019a3c failed with no error code (undefined)
```

![Bildschirmfoto 2023-07-04 um 09 39 58](https://github.com/ioBroker/ioBroker.zigbee/assets/8623789/270896ed-45ca-49b9-a75d-2d0153c3eca0)

Schreiben auf den rot eingekreisten Datenpunkt erzeugt den Fehler.

**Comment by arteck** [comment]
was ist wenn du da ein hex wert rein schreibst ... #ff0000

**Comment by Marty56** [comment]
Ja, funktioniert genau so wenig.
ich habe noch ein LED Streifen mit analogen Datenpunkten, da funktioniert die Farbe ohne Probleme
