### ISSUE TITLE
IKEA E2001/E2002 Styrbar not working

### ISSUE THREAD

**Issue by nromming** [ioBroker/ioBroker.zigbee#1776]
Hi, I'm new to github and this is the first issue I am posting as I could not find an answer to my problem.
I have been able to pair the Styrbar remote but not receiving any events.
Zigbee Version 1.8.10
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/138571581/3cb0922f-883f-46ea-9f70-624fbf06122a)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/138571581/56c40f81-f5bc-45da-9545-62f364a77d9a)
I set a trigger to any input:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/138571581/bb0bf8bb-f522-4558-8bd7-357c79779a97)

Any ideas?

**Comment by chris299** [comment]
@nromming do you see any check marks appear here on clicking the remote?
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/33319001/a0975dca-fc38-427c-b740-3d0ae705f795)

maybe update the coordinator firmware to a more current version....

**Comment by nromming** [comment]
> @nromming do you see any check marks appear here on clicking the remote? ![image](https://user-images.githubusercontent.com/33319001/250825798-a0975dca-fc38-427c-b740-3d0ae705f795.png)
> 
> maybe update the coordinator firmware to a more current version....

I don't see check marks appearing.
Could you give me a link how I best update the coordinator firmware for my iobroker.zigbee adapter?
