### ISSUE TITLE
no more battery values come from the sensors

### ISSUE THREAD

**Issue by rewegit** [ioBroker/ioBroker.zigbee#1777]
Set V18.11 apparently no more battery values come from the sensors. See https://forum.iobroker.net/topic/66692/keine-batterieanzeige-mehr-bei-zigbee-geräten.

Reiner

**Comment by RoboCop0815** [comment]
habe das gleiche Problem, seit gestern morgen ca. 10:00Uhr keine änderung der Battery Werte. Bin zurück auf  V18.10 und ich bekomme wieder aktuelle Werte. 
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/42671266/3a0a9633-8088-4cbc-b124-3c3f1c741070)

**Comment by arteck** [comment]
check https://github.com/ioBroker/ioBroker.zigbee/tarball/testBattery
