### ISSUE TITLE
How can i find configuration.yaml file :(

### ISSUE THREAD

**Issue by Blacksoul87** [ioBroker/ioBroker.zigbee#178]
Hello,
how can i find the configuration.yaml file for edit the groupadress for my ikea remote control?

**Comment by kirovilya** [comment]
no file. simple add group with the desired number in admin adapter page

**Comment by kirovilya** [comment]
simple on tab Groups add group with your coordinator_group number (in decimal)

**Comment by Blacksoul87** [comment]
ok, but i can not add the group to my ikea remote device.
I can edit the name.

**Comment by kirovilya** [comment]
you not need add group to remote control... only add to common groups
![image](https://user-images.githubusercontent.com/8360230/52001368-4b802e80-24d0-11e9-8a10-8a88ef7af21b.png)

**Comment by Thomas1305** [comment]
OK, 
Thx for that.
But i still have the problem to find out my group_id.
Wireshark, zboss and cc2531 is working an flashed.
But i can find out network_key, because i have no configuration.yaml.
I guess i have the standard trust_ center_link_key.

And if i'm right, i have to convert the group_id from hex to dezimal for adding the group in zigbee Adapter?

**Comment by kirovilya** [comment]
@Thomas1305 yes

**Comment by Thomas1305** [comment]
OK
Now i still have the problem finding out my group_id.

Can it be the Problem, that i use a Raspberry with the usb coordinator and using the usb sniffer on my Windows pc?

**Comment by kirovilya** [comment]
To find a group, you must sniff the process of pairing the remote with the coordinator

**Comment by Thomas1305** [comment]
OK
So i have to go with my Windows pc and sniffer in the basment where the iobroker and coordinator is.
Then paring the remote again and have a look

**Comment by Thomas1305** [comment]
Thx
Works perfectly now.
