### ISSUE TITLE
Installation from GitHub not working

### ISSUE THREAD

**Issue by dereme12** [ioBroker/ioBroker.zigbee#1784]
When I try to install from GitHub everything seems to work. The adapter is not appearing in the instances menu though.

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/138617912/d2946306-9c9c-4441-a086-9f18fb904030)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/138617912/fffd65d2-e861-4c2b-958d-439a955285c5)

Does anybody have an idea where this is coming from?

**Comment by Apollon77** [comment]
Yes, a github install do not create a new instance automatically ... this needs to be die manually via the "+" in the relevant adaptert row in "Adapters". This was always needed that way.
