### ISSUE TITLE
nach update auf 1.8.12 senden meine aqara fp1 Bewegungsmelder keine daten mehr 

### ISSUE THREAD

**Issue by motugozu** [ioBroker/ioBroker.zigbee#1785]
nach dem Update auf 1.8.12  werden die daten punkte Presence und Erreichbarkeit aktualisiert  . beim Downgrade auf 1.8.10 funktioniert alles ohne Probleme

**Comment by arteck** [comment]
auch mit der neuen GIT version ?

**Comment by motugozu** [comment]
Mit 1.8.13 die selben Probleme 

Mein System  

npm 9.5.1
nodejs  18.16.1
node   18.6.1

**Comment by arteck** [comment]
check https://github.com/ioBroker/ioBroker.zigbee/tarball/testBattery

**Comment by motugozu** [comment]
Läuft jetzt wieder einwandfrei danke dir    für die schnelle Anpassung
