### ISSUE TITLE
Xiaomi WSDCGQ01LM Werte werden ab 1.8.12 nicht mehr aktualisiert

### ISSUE THREAD

**Issue by latzi0710** [ioBroker/ioBroker.zigbee#1786]
Seit dem update auf 1.8.12 (und auch github 1.8.13) werden die Xiaomi-Temperatursensoren (WSDCGQ01LM) nicht mehr aktualisiert, bei Rückkehr zu 1.8.10 läuft alles wie gewohnt.
Sensoren:
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/59318512/bf8f5e99-afd3-4efc-8d4c-209c534cafe9)
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/59318512/4067acc3-2616-4745-976a-d16ae1714f88)

Mein System:
Node.js: v18.16.1
NPM: v9.5.1
Admin: v6.6.0
js-controller: v4.0.24

falls du weitere Info´s brauchst einfach melden ;-)

Vielen Dank! 👍

**Comment by arteck** [comment]
der Batteriestand wird nicht aktualisiert..der rest schon

**Comment by latzi0710** [comment]
Kann ich so nicht bestätigen :-(

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/59318512/5bd6847c-0212-4cff-b6fe-931810174ea7)
