### ISSUE TITLE
Latest update make HG06492B & HG06492C not usable

### ISSUE THREAD

**Issue by M1cS0w** [ioBroker/ioBroker.zigbee#1787]
Hello, after the update from 1.8.9 to 1.8.12, the bulks do not have the normal picture, get only the ? symbol.
And is not usable for change brightness and so on in version 1.8.12
On version 1.8.9 back, it works again.

I use:
npm version 9.5.1
nodejs 18.16.1
admin version 6.3.5

For testing i have tried to reset the bulks and learn as new device:
in the log:
- New device joined "ID", model HG06492B
- Interview successful: {friendly_name":"ID",model":"HG06492B","vendor":"Lidl","description":"Livarno Lux E14 candle CCT","supported":true}
- Error: Device "ID" "HG06492B" not described in statesMapping.. undefined

Only latest updates. Maybe someone get the same issue?

**Comment by arteck** [comment]
check new GIT version
