### ISSUE TITLE
Please add Immax Neo Bulbs

### ISSUE THREAD

**Issue by killakaktus** [ioBroker/ioBroker.zigbee#179]
There products have a good value. Would be amazing if [THESE ](https://www.immaxneo.cz/produkty/led-e14-230v-c35-5w-tb-440lm-zigbee-dim/)Bulbs could be implemented.

**Comment by kirovilya** [comment]
Sorry, but I do not have these lamps and there is no code to add them.
Run the adapter in debug-mode, try to pair these lamps and send me a shepherd.db file from iobroker-data/zigbee_0

**Comment by killakaktus** [comment]
Thanks for your support Ilya. Here is the shepherd.db file. Hope this helps.
[shepherd.zip](https://github.com/ioBroker/ioBroker.zigbee/files/2838372/shepherd.zip)

**Comment by kirovilya** [comment]
Good! In your db i found model 'IM-Z3.0-DIM'
So, make backup iobroker directory :)
Then, locate the devices.js file in the directory /iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd-converters/devices.js or  /iobroker/node_modules/zigbee-shepherd-converters/devices.js
Need to add next block to this file like other devices in it:
```
    {
        zigbeeModel: ['IM-Z3.0-DIM'],
        model: 'IM-Z3.0-DIM',
        vendor: 'Immax',
        description: 'LED E14/230V C35 5W TB 440LM ZIGBEE DIM',
        extend: generic.light_onoff_brightness,
    },
```
Then, locate the devstates.js file in the directory /iobroker/node_modules/iobroker.zigbee/lib/devstates.js 
and add next block to this file:
```
    {
        vendor: 'Immax',
        models: ['IM-Z3.0-DIM'],
        icon: 'img/philips_hue_e14_ambiance.png',
        states: lightStatesWithColor,
        linkedStates: [comb.brightnessAndState],
    },
```
Restart adapter and check out your lamp.
If all ok, I make changes to code.

**Comment by killakaktus** [comment]
Thanks for that! Works flawlessly. You are the best.
![bildschirmfoto 2019-02-07 um 10 39 18](https://user-images.githubusercontent.com/43897083/52402681-348b9e80-2ac5-11e9-9657-9d90f9efaa98.png)

color and colortemp not needed - not supported.
