### ISSUE TITLE
Problem mit 'HG06106B' nach Update auf 1.8.12 - Livarno Lux E14 candle RGB - Lidl

### ISSUE THREAD

**Issue by UweLoyal** [ioBroker/ioBroker.zigbee#1790]
Lampe läßt sich nicht mehr ansteuern nach Update auf V 1.8.12

https://www.zigbee2mqtt.io/devices/HG06106B.html

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/5464553/a113532c-c79c-4496-b06a-c89f96384426)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/5464553/7732e487-8648-4978-9877-39ebf61f2e9e)

**Comment by arteck** [comment]
V 1.8.12 ist veraltert
