### ISSUE TITLE
TS011F Socket - No longer working after adapter udate 1.8.12

### ISSUE THREAD

**Issue by smalltower1** [ioBroker/ioBroker.zigbee#1791]
Good day,
today I updated the zigbee adapter to version 1.8.12. After that realized that although correctly displayed, I couldn't swith the socket on or off. Re-paired the socket and from then on it was no longer displayed correctly and no settings are possible any longer.
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/112553098/75e6ec05-e2eb-4e28-aaad-346b7f0db138)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/112553098/1b6ed74a-bdb2-4d1d-861b-55489a8b9311)

Is this a known issue? Before the Socket used to work correctly and all settings, readings and on/off used to work in my current setup. Not sure if it stopped working because of the update.

**Comment by smalltower1** [comment]
Just tried downgrading to 1.8.10 and it works in this version:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/112553098/d4dcd50c-2bf3-492b-afe7-ca4d660a6363)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/112553098/e0cb92a6-f106-432a-9fff-9d8c9b8f06dd)

**Comment by arteck** [comment]
yes i know.. install GIT version.. and it works again

**Comment by smalltower1** [comment]
Sorry, but what is the GIT Version and where do I find it? Or is the bug being fixed, if so I can wait till the next update.

**Comment by arteck** [comment]
ok install new version 1.8.16
