### ISSUE TITLE
TS0202 Motion Sensor no longer working since 1.8.16

### ISSUE THREAD

**Issue by dobmeierr** [ioBroker/ioBroker.zigbee#1793]
`2023-07-12 11:32:42.313 - error: zigbee.0 (188034) DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c138376d2accb8 TS0202 (Error: Bind 0xa4c138376d2accb8/1 genPowerCfg from '0x00124b0022981a42/1' failed (AREQ - ZDO - bindRsp after 10000ms)`

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/70376186/eded2998-38dc-44e6-b632-a31ef262ffa9)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/70376186/992008ea-dc3c-4fd0-b9bc-18db6e378ffd)

**Comment by arteck** [comment]
repair plz

**Comment by dobmeierr** [comment]
Sorry.

Could you please fix it

:-)

**Comment by arteck** [comment]
you have a DeviceConfigure error... plz pair again this device..

**Comment by dobmeierr** [comment]
ok.
i will try it 
thank you

**Comment by dobmeierr** [comment]
thank you arteck,

everything works fine again
