### ISSUE TITLE
Nous A1Z plugs do not work anymore after update to 1.8.12

### ISSUE THREAD

**Issue by jevylux** [ioBroker/ioBroker.zigbee#1794]
Since the upgrade, i noticed to problems: 
1) when adding a new Plug, there are no more metering objects ( power, enerrgy etc)
2) existing plugs cannot be switched on/off via iobroker
logs shows : No state available for 'A1Z' with key 'state'. message

**Comment by arteck** [comment]
which version ?

**Comment by jevylux** [comment]
this is the latest version available within iobroker

<img width="453" alt="image" src="https://github.com/ioBroker/ioBroker.zigbee/assets/198311/c6b0b8c0-a7d0-4975-be3a-9f138c471c09">

<img width="314" alt="image" src="https://github.com/ioBroker/ioBroker.zigbee/assets/198311/511ef441-56c4-4149-a22d-0e58eb75970f">

plug added before upgrading

<img width="810" alt="image" src="https://github.com/ioBroker/ioBroker.zigbee/assets/198311/07623738-e7f3-4100-bc0e-290e8ed4b3d2">

plug added with this version  
<img width="768" alt="image" src="https://github.com/ioBroker/ioBroker.zigbee/assets/198311/95035650-18c8-448d-983b-45dc31d2e5ae">

**Comment by arteck** [comment]
stable yes.... wait to tomorrow
