### ISSUE TITLE
New Device

### ISSUE THREAD

**Issue by rpsVerni** [ioBroker/ioBroker.zigbee#1798]
Elivco Zigbee
https://de.aliexpress.com/item/1005005665327210.html?spm=a2g0o.cart.0.0.69444ae4Wb4XC3&mp=1&gatewayAdapt=glo2deu

error: zigbee.0 (15549) DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600291f0 TS011F (TypeError: Cannot read properties of undefined (reading 'debug')

Interview successful: {"friendly_name":"0x70b3d52b600291f0","model":"BSD29","vendor":"TuYa","description":"Smart plug (with power monitoring by polling)","supported":true}

New device joined '0x70b3d52b600291f0' model BSD29
Device '0x70b3d52b600291f0' announced itself
Interview started: 0x70b3d52b600291f0

ieee:0x70b3d52b600291f0
nwk:4163 (0x1043)
model:[BSD29](https://www.zigbee2mqtt.io/devices/BSD29.html)
groups:

1.) Power Button works (on/off)
2.) Button light works (Light on/off)
3.) restore power work
4.) V (Missing)
5.) W (Missing)
6.) kWh (Missing)
7.) A (Missing)

On Tuya Zigbee hub works very well 1W starts the Power measurement
Voltage accuracy is well +- 1V
Consumption is on standby is 0,2W and 0,5w actuated

same function item
Blitzwolf Zigbee sh15

**Comment by arteck** [comment]
[RTFM](https://github.com/ioBroker/ioBroker.zigbee/blob/master/docs/en/readme.md#pairing-of-unknown-zigbee-devices-so-far)
