### ISSUE TITLE
GLEDOPTO GL-B-008Z still not working

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.zigbee#180]
https://de.aliexpress.com/item/GLEDOPTO-ZIGBEE-Led-Controller-RGB-CCT-WW-CW-zigbee-controller-LED-DC12-24V-LED-streifen-controller/32858603964.html

![image](https://user-images.githubusercontent.com/35403739/52047016-6ee6c000-2548-11e9-97e0-e12193a5ee0c.png)

![image](https://user-images.githubusercontent.com/35403739/52047138-ad7c7a80-2548-11e9-8aa6-cfa92bfe9bd7.png)

![image](https://user-images.githubusercontent.com/35403739/52047298-fd5b4180-2548-11e9-9209-1a09977f4609.png)

**Comment by arteck** [comment]
adapter version ??

**Comment by obodeldog** [comment]
For me: 0.9.1. I just updated it again from git. No changes. I use the adapter over a "Slave Raspberry" in a multi host environment.

**Comment by kirovilya** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/751

**Comment by kirovilya** [comment]
https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/getting_started/pairing_devices.md#gledopto

**Comment by joerghildering** [comment]
Tryed to add `manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-S-007Z"` and change the devId for EP12 and EP13. But this does not solved it. :-( Used 0.9.1, too.

**Comment by kirovilya** [comment]
Share your shepherd.db file from iobroker-data/zigbee_0

**Comment by arteck** [comment]
i think GLEDOPTO has a special char..

**Comment by obodeldog** [comment]
Can this be solved?

**Comment by kirovilya** [comment]
@obodeldog Share your shepherd.db file from iobroker-data/zigbee_0

**Comment by obodeldog** [comment]
It is strange that I can integrate the lamp into a "single ioBroker" (i.e. no multihost). I once built it as a test system. In my production system the Zigbee is on a "slave" of a multihost system. It doesn't work here. Does this seem to have something to do with Multihost?

Both files in the appendix. The file with "master" is the one without multihost. "Slave" is the system with multihost in slave mode. Here it does not work.

[master_shepherd.zip](https://github.com/ioBroker/ioBroker.zigbee/files/2850825/master_shepherd.zip)
[slave_shepherd.zip](https://github.com/ioBroker/ioBroker.zigbee/files/2850826/slave_shepherd.zip)

**Comment by kirovilya** [comment]
There is a very strange situation on your "slave" - there are several records in the database with the same ID but different devices. 
Make a backup of the database on the "slave" (just in case). Remove all paired devices and base. Pair the devices again.

**Comment by joerghildering** [comment]
I tried it many times with diverent Adapter Versions and new shepherd.db

[shepherd.zip](https://github.com/ioBroker/ioBroker.zigbee/files/2852161/shepherd.zip)

**Comment by kirovilya** [comment]
@obodeldog shepherd.zip - there are no GLEDOPTO :(

**Comment by obodeldog** [comment]
In my both are GLEDOPTO. You mean in joerghildering is no GLEDOPTO?!

**Comment by obodeldog** [comment]
Done. In attach the new file
[shepherd.zip](https://github.com/ioBroker/ioBroker.zigbee/files/2852565/shepherd.zip)

**Comment by kirovilya** [comment]
Ok. i see.
Now you can see the bulb in admin page?
If not, then the old version of the adapter, cause since version 0.9.0 these lamps are there.

**Comment by obodeldog** [comment]
No, I can't. You mean I should try 0.9.0?

**Comment by kirovilya** [comment]
@obodeldog of course!

**Comment by obodeldog** [comment]
Ok, sorry. Yes. 0.9.0 is online :-).
But same thing. I can not see device folder. 
[shepherd.zip](https://github.com/ioBroker/ioBroker.zigbee/files/2852676/shepherd.zip)

**Comment by kirovilya** [comment]
Current version is 0.9.1! and did you restart adapter?

**Comment by obodeldog** [comment]
Sorry, not working. 
In summary: Not working when I used it in "multihost slave mode".:

![image](https://user-images.githubusercontent.com/35403739/52588767-8756b480-2e3d-11e9-8311-e55f5564448b.png)

![image](https://user-images.githubusercontent.com/35403739/52588797-9c334800-2e3d-11e9-884d-8465ecd14df5.png)

![image](https://user-images.githubusercontent.com/35403739/52588824-ad7c5480-2e3d-11e9-83e6-b15229b13a6e.png)

[shepherd.zip](https://github.com/ioBroker/ioBroker.zigbee/files/2852768/shepherd.zip)

**Comment by kirovilya** [comment]
your model GL-B-008Z already in adapter https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devstates.js#L2040
you need install last version - 0.9.1
that is all!

**Comment by obodeldog** [comment]
As I showed you in last post:

![image](https://user-images.githubusercontent.com/35403739/52588824-ad7c5480-2e3d-11e9-83e6-b15229b13a6e.png)

I used already 0.9.1.

**Comment by kirovilya** [comment]
on slave?

**Comment by obodeldog** [comment]
Yes
![image](https://user-images.githubusercontent.com/35403739/52591003-0d292e80-2e43-11e9-9f51-fe5a11d81bb6.png)

**Comment by kirovilya** [comment]
show your zigbee adapter start log
i can not believe...

**Comment by obodeldog** [comment]
In attach

[zigbee.zip](https://github.com/ioBroker/ioBroker.zigbee/files/2852930/zigbee.zip)

**Comment by kirovilya** [comment]
empty

**Comment by obodeldog** [comment]
[zigbee_1.txt](https://github.com/ioBroker/ioBroker.zigbee/files/2852933/zigbee_1.txt)

**Comment by kirovilya** [comment]
last line:
> starting. Version 0.8.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v8.14.0

0.8.0!!!! You need 0.9.0 at least

**Comment by kirovilya** [comment]
So you have:

> Device 00124b001b4ff6d6 "GL-B-008Z" not described in statesMapping.

**Comment by obodeldog** [comment]
Oh, my God. Oh, my God. I believe you. But I guess I was too stupid about the master slave thing. I thought if I update a zigbee, it will be updated in the right adapter. But that doesn't seem to be the case.
I'm sorry.

![image](https://user-images.githubusercontent.com/35403739/52591753-f8e63100-2e44-11e9-9b68-e1a925b1074f.png)

![image](https://user-images.githubusercontent.com/35403739/52591780-0a2f3d80-2e45-11e9-99d1-6eb6f6921d9c.png)

**Comment by kirovilya** [comment]
and what next? :)

**Comment by obodeldog** [comment]
Working fine now :-) Thank you very much

**Comment by kirovilya** [comment]
![image](https://user-images.githubusercontent.com/8360230/52592328-318f0600-2e57-11e9-8b96-5f18aa738def.png)
Good luck in other matters!

**Comment by snador1977** [comment]
Bei mir funktioniert das Pairing der GLEDOPTO GL-B-008Z (RGBW) nicht. Der Prozess läuft druch und nichts passiert. Ich habe 2 dieser Bulps getestet. Den neuesten Adapter von GIT hab ich auch getestet. Im Pairing blinkt die Bulp grün / Kaltweiss und wenn der Pairing Prozesse beendet ist steht sie auf kaltweiss. Es tauch nicht mal ein Fragezeichen unter Geräte auf...
