### ISSUE TITLE
nach Update auf v1.8.17 keine Verbindung zum Host

### ISSUE THREAD

**Issue by Huskerdu24** [ioBroker/ioBroker.zigbee#1804]
zigbee 1.8.17
Node.js v18.16.1
NPM  9.5.1
Host js 5.0.8
Linux bullseye 6.2.16-3-pve

Nach Update von 1.8.16 auf 1.8.17 unterbricht der Adapter die Verbindung zum Host. Downgrade zurück auf 1.8.16 behebt den Fehler, der Adapter läuft dann wieder ohne Probleme.

`<html><body>

host.PI4 | 2023-07-16 11:55:43.804 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.PI4 | 2023-07-16 11:55:43.803 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]: Node.js v18.16.1
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]:     at node:internal/main/run_main_module:23:47
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:960:12)
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1220:27)
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]:     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
host.PI4 | 2023-07-16 11:55:43.803 | error | Caught by controller[0]:     at internalCompileFunction (node:internal/vm:73:18)
host.PI4 | 2023-07-16 11:55:43.802 | error | Caught by controller[0]: SyntaxError: missing ) after argument list
host.PI4 | 2023-07-16 11:55:43.802 | error | Caught  by controller[0]:                                                                                                                                                                                   ^^^^^
host.PI4 | 2023-07-16 11:55:43.802 | error | Caught  by controller[0]:                     this.log.error(`Error  ${error.code} on send command to ${payload.device}.` + ` Error:  ${error.stack} ` + `Send command to ${payload.device} failed with ` +  error;
host.PI4 | 2023-07-16 11:55:43.802 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.zigbee/main.js:791
host.PI4 | 2023-07-16 11:55:43.563 | info | instance system.adapter.zigbee.0 started with pid 41560

</body>
</html>`

**Comment by Madaraxa** [comment]
Hier dasselbe mit

Host 5.0.7 (ansonsten identische Konfiguration zu Huskerdu)

**Comment by arteck** [comment]
nimm die 1.8.18
