### ISSUE TITLE
New IKEA Rodret Device

### ISSUE THREAD

**Issue by Fichte79** [ioBroker/ioBroker.zigbee#1809]
Hello everyone

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/107550931/7bb84a1a-74f6-4ec6-bbcc-b64a379ff005)

This is the information from the new device "IKEA Rodret". I hope I could help.

Best regards

**Comment by ChristianPB** [comment]
It is possible to pair, but no reaction in the Objects when pushing the buttons

**Comment by asgothian** [comment]
Please test with the current GitHub version

**Comment by funchenry** [comment]
1.10.4 zigbee.adapter on conbee2 . It is possible to pair, but no reaction in the Objects when pushing the buttons.

**Comment by asgothian** [comment]
- How did you verify this ?
- does the info tile list the device as configured ?
- Does it stay when updating to the current GitHub version ?
- does the msg_from_zigbee DP get updated ?
- 
a.

**Comment by funchenry** [comment]
1 day later. after delete and new pairing it works on 1.10.4 zigbee.adapteron conbee2. ty for helping .
