### ISSUE TITLE
Trådfri Steckdosen laufen nicht als Router/Koordinator?

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.zigbee#181]
Nach erfolgreicher Implementierung von insgesamt 6 Trådfri Steckdosenschaltern und einigen Xiaomi-Sensoren ist mir auf der Netzwerkkarte in der Adapter-Einstellung des Zigbee-Instanz aufgefallen, daß alle Trådfri lediglich als ZED/Endgerät laufen, aber nicht als Router oder Koordinator?!

Ich benutze die Version 0.9.0.

Kann das jemand bestätigen?

Somit ist meines Wissens die Anzahl der Endgeräte weiterhin auf 15 beschränkt, richtig?

![tradfri](https://user-images.githubusercontent.com/42386692/52076482-0d960f80-258f-11e9-80af-78c487767af9.jpg)

Edit: Habe soeben gesehen, daß die Steckdosen in der Log sehr wohl als Router aufgeführt sind - wird das evtl. nur von der Netzwerkkarte falsch interpretiert?

**Comment by modmax** [comment]
Kommt drauf an, wo Du die Endgeräte anlernst. Jeder Roter hat ja selber so nen gelben Button, den man zum Pairen nutzen kann. Dann wird nur auf diesem Roter gepaired; beim Button oben rechts startet Pairing bei allen Routern im System.
Solange aber der direkte Weg zum Coordinator der kürzestes und beste ist, wird das auch so in der Netzwerkkarte angezeigt. Auf das MESH hat der Adapter keine Auswirkung; und so aussagekräftig ist es wie gesagt auch nicht ...

**Comment by arteck** [comment]
die Geräte switchen ehh ab und an die Route ..
