### ISSUE TITLE
Mi Light Detection Sensor does not report battery status

### ISSUE THREAD

**Issue by apla2016** [ioBroker/ioBroker.zigbee#1810]
Mi Light Detection Sensor GZCGQ01LM does not report battery status
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/19657413/48393609-eb9d-45a8-8edc-6c3af453c749)

**Comment by arteck** [comment]
check GIT version

**Comment by apla2016** [comment]
GIT version of ioBroker Zigbee adapter?

**Comment by de-ro** [comment]
Same Problem with button and humidity sensor. Version v1.8.16

**Comment by de-ro** [comment]
I have the same problem with a Xiaomi WXKG01LM (MiJia wireless switch)
Version v1.8.16

**Comment by apla2016** [comment]
> check GIT version

How to load GIT version?

**Comment by arteck** [comment]
works with new GIT version
https://github.com/ioBroker/ioBroker.zigbee/wiki/GIT-install
