### ISSUE TITLE
Missing Device INNR RS 232 c

### ISSUE THREAD

**Issue by Bastler24** [ioBroker/ioBroker.zigbee#1812]
Can you help me to integrate this device.
![RS232C](https://github.com/ioBroker/ioBroker.zigbee/assets/140942318/80fd8167-c290-4077-92fc-54d03783a7a7)
Thanks

**Comment by arteck** [comment]
check new GIT version

**Comment by Bastler24** [comment]
Can you please explain to me how to do this
