### ISSUE TITLE
v1.8.16: deactivate, reconfigure, config & delete device buttons not working in Apple Safari Browser

### ISSUE THREAD

**Issue by W0w3** [ioBroker/ioBroker.zigbee#1818]
The device buttons are not clickable on MacOS and iOS using the standard Safari browser.
I can only use them in Chrome. Also CSS formatting is broken compared to Chrome.

Safari (mouseover on Reconfigure Button, nothing happens, also not clickable):
<img width="333" alt="image" src="https://github.com/ioBroker/ioBroker.zigbee/assets/40882059/c300c0b2-5ea9-4e07-816b-b9942d179848">

Chrome (works as desired):
<img width="332" alt="image" src="https://github.com/ioBroker/ioBroker.zigbee/assets/40882059/212f655d-6360-49a2-ab15-92515cf04b4b">

**Comment by arteck** [comment]
Safari is here the problem

https://github.com/ioBroker/ioBroker.zigbee/issues/1726
