### ISSUE TITLE
Events from IKEA Tradfri Buttons E1812 and E1743 not recknognized

### ISSUE THREAD

**Issue by cherberg** [ioBroker/ioBroker.zigbee#1821]
Dear Developer,

I have an issue with a fresh installation of iobroker running the latest version of your addon 18.8.16. 

I am able to pair the devices (was unsusessful with Channel 11) but after that any event / click on the device is not recknized properly. 

The two switch E1743 recknognizes an update in datapoint msg_from_zigbee and sets datapoint "state" to "True" when clicking the "I" button and to "False" when clicking the "O" button

The single button E1812 only records an update to the datapoint msg_from_zigbee, nothing else is recorded.

More information

System Information:
NPM 9.6.7
Node.js 18.17.0
js controler 4.0.24

Stick information:
type: zStack12
version: 2-0.2.6.3.
revision: 20201127
port:/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDD491C-if00
channel: 23

would be happy to provide more information if needed. 
unfortunately I do not know how to extract the "Herdsman logs" so I would need some help with that if these are needed, thanx for looking into this.

**Comment by Ilovegym66** [comment]
Problem is solved in 1.8.21

**Comment by cherberg** [comment]
Thanx for the swift response. I updated to 1.8.21 from Github and I can confirm that this is solving the issue for me.

P.S.: I tried to donate to to Kirov Ilya https://www.paypal.me/goofyk for the continued great work on this adapter but was informed by Paypal that the account is blocked and I cannot send any money.
