### ISSUE TITLE
Synchronisierung der Gruppen mit Gerätezustand

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#1824]
Es wäre schön, wenn der Zustand einer Gruppe synchronisiert würde, wenn man Geräte einzel bedient. Mir geht es eher um dem Zustand und nicht um die Farben und so. Wenn alle Geräte einer Gruppe ausgeschaltet worden sind, dann sollte die Gruppe auch ausgeschaltet werden. Das gleiche gilt wenn alle Geräte, die in eine Gruppe sind, eingeschaltet werden. Dann wäre es cool, wenn die ganze Gruppe auch eingeschaltet wird. Zur Zeit mache ich das per Skript, damit es zu keine Inkonsistenzen im System kommt.

**Comment by arteck** [comment]
das geht nicht.. wurde schon mehrfach gewünscht.. das liefert das Netzwerk nicht.. 
ausserdem sind mehrere Geräte in der Gruppe möglich die nicht alle den gleichen Status haben
