### ISSUE TITLE
Aqara fp1 Bewegungsmelder ändert den Datenpunkt Presence nicht mehr

### ISSUE THREAD

**Issue by motugozu** [ioBroker/ioBroker.zigbee#1826]
Hallo  Hatte die Version von 3.16 auf 3.21  geupdatet seit dem ändert sich der Daten Punkt Presence von meinen Aqara fp1  Bewegungsmelder nicht mehr  , ich hatte dieses problem schon einmal in einer früheren Version , nach einem Fix Update von euch ging es wieder  aber seid 3.21  habe ich das Problem schon wieder 

Adapter Version 3.21
Node 18.17.0
Node JS 18.17.0
NPM 9.6.7

**Comment by arteck** [comment]
was ist den eine Version 3.21 ???? nicht von dem zigbee adapter

**Comment by motugozu** [comment]
Sorry ich meinte vom Zigbee Adapter das Update von Version 1.8.16 auf 1.8.21

**Comment by GrayTheZebra** [comment]
Ich habe das gleiche Problem und auch mit der Version von Git ändert es sich nicht.

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages

dann aus dem LOG die Zeilen mit dem ELEVATED Posten
der BWM sollte auslösen..ich muss sehen was der sendet

**Comment by GrayTheZebra** [comment]
Nachdem ich den Log-Level auf "Debug" gestellt hatte funktioniert es nun. Auch nach dem zurückstellen auf "info" funktioniert es noch. Die Version ist weiterhin 1.8.22.

**Comment by arteck** [comment]
verstehe ich nicht ??

**Comment by a-i-ks** [comment]
Das Problem habe ich auch gelegentlich. Es scheint eher an dem Aqara FP1 zu liegen. Siehe auch [hier](https://community.home-assistant.io/t/aqara-fp1-stuck-on-detected-occupancy/438350),
