### ISSUE TITLE
Absturz des Adapters Version: 1.8.21 bei Benutzung von Gruppen

### ISSUE THREAD

**Issue by Cokie0088** [ioBroker/ioBroker.zigbee#1829]
Hallo,

sobald ich eine Gruppe Verwende stützt der Adapter ab.
Heist wenn ich eine Gruppe anlege und dann bei dieser Gruppe etwas ausführen will z.B. on/off dann Schmiert der Adapter ab.

Das Protokoll sagt folgendes:

getGroupMembersFromController: error is {} "Error: \n at Groups.getGroupMembersFromController (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:88:119)\n at Groups.queryGroupMemberState (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:170:36)\n at Zigbee.callPluginMethod (/opt/iobroker/node_modules/iobroker.zigbee/main.js:863:45)\n at /opt/iobroker/node_modules/iobroker.zigbee/main.js:729:40"

Dabei ist es egal ob der Gruppe etwas zugewiesen wurde oder nicht.
Auch eine "leere" Gruppe Stürzt ab, sobald die bedient wird.

Ich bin auf Version 1.8.13 zurück gegangen dort funktionieren die Gruppen wieder.

Update:

Auch bei Version 1.8.13 Tritt der Fehler auf. Diesesmal mit einer anderen Meldung.

zigbee.0 | 2023-08-05 19:10:48.073 | error | TypeError: Cannot read properties of undefined (reading 'Error') at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56 at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1) at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1) at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32) at Zigbee.filterError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:142:18) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:707:26 at runNextTicks (node:internal/process/task_queues:60:5) at processTimers (node:internal/timers:504:9)

zigbee.0 | 2023-08-05 19:10:48.037 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'Error')
zigbee.0 | 2023-08-05 19:10:48.036 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2023-08-05 19:10:48.035 | error | Send command to 0xa4c138ff7ff1623e failed with no error code (no response received (48)

Grüße

**Comment by vogi13** [comment]
Exactly the same issue here..

**Comment by schniddsel** [comment]
Same issue. Had to roll back to v1.7.6 to make it work again

**Comment by ThoHolit** [comment]
Same Issue, since i updatet yesterday.

**Comment by Cokie0088** [comment]
Mit Version 1.8.22 ist die das Problem behoben (Beta Repo)!
