### ISSUE TITLE
States of grouped devices are not updated

### ISSUE THREAD

**Issue by denzel1994** [ioBroker/ioBroker.zigbee#183]
When controlling lightbulbs, which are grouped together, via the group states the states of the individual lightbulbs are not updated.

<img width="1479" alt="bildschirmfoto 2019-02-03 um 02 57 58" src="https://user-images.githubusercontent.com/36551243/52171585-8ba91080-275f-11e9-9093-8d7b18c8d827.png">

For example: Stehlampe "Oben" "Mitte" "Unten" are gathered in group 2. If I set the switch state of group 2 to "false" all three lightbulbs turn off as expected, but the switch state of each individual lightbulb still shows "true.
Same goes for changing brightness or colortemp.

**Comment by denzel1994** [comment]
Can this be implemented in the next update?

**Comment by Garfonso** [comment]
I hope this gets fixed. 
One might write a js script for that.. but it would be more easy to fix in the adapter itself.
