### ISSUE TITLE
Unknown device: Paulmann ZigBee Controller-RGBW (371000002)

### ISSUE THREAD

**Issue by LifeSkyleApps** [ioBroker/ioBroker.zigbee#1830]
Hello all,
can you integrate the Paulmann ZigBee Controller-RGBW (371000002) so that the LED ceiling lamp can be controlled with it? This would be nice. :-)
Enclosed you'll find the backside of the device tile. If you need any more information, please contact me.

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/46595818/fa8b92c5-d30a-4eda-8957-5d761750c50a)

![PXL_20230806_172359993](https://github.com/ioBroker/ioBroker.zigbee/assets/46595818/7addb295-2099-47b7-9cb6-28f1b94ef308)

**Comment by arteck** [comment]
thx
