### ISSUE TITLE
Ikea light bulb LED2003G10 disconnects after a few seconds

### ISSUE THREAD

**Issue by Heenne** [ioBroker/ioBroker.zigbee#1833]
Hello,

I just baught the Ikea light bulb LED2003G10. I installed it in the socket and tried to pair it with the zigbee adapter.
First it did not work but after resetting the light bulb with toggling it off and on six times it got recognized.
The light bulb was added in the zigbee device overview and I was able to contol it for approximatly 10 seconds. Then it blinked two times and disappeared from the zigbee device overview.
During that time I was on the beta-version in iobroker (1.8.8 I think) and the following was written to the log:

> zigbee.0 | 2023-08-07 22:40:15.338 | info | Zigbee: stop joining
zigbee.0 | 2023-08-07 22:39:39.109 | info | DeviceConfigure successful 0x94deb8fffe52e4db 
TRADFRIbulbE27WSglobeopal1055lm
zigbee.0 | 2023-08-07 22:39:38.905 | info | Configuring 0x94deb8fffe52e4db TRADFRIbulbE27WSglobeopal1055lm
zigbee.0 | 2023-08-07 22:39:38.903 | info | Device  '0x94deb8fffe52e4db' is supported, identified as: IKEA TRADFRI LED bulb  E26/27 1100/1055/1160 lumen, dimmable, white spectrum, opal white  (LED2003G10)
zigbee.0 | 2023-08-07 22:39:38.902 | info | Successfully interviewed '0x94deb8fffe52e4db', device has successfully been paired
zigbee.0 | 2023-08-07 22:39:38.879 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-08-07 22:39:38.878 | warn | Object  zigbee.0.94deb8fffe52e4db.power_on_behavior is invalid:  obj.common.states has an invalid type! Expected "object", received  "string"
zigbee.0 | 2023-08-07 22:39:38.859 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-08-07 22:39:38.858 | warn | Object zigbee.0.94deb8fffe52e4db.effect is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-08-07 22:39:38.836 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-08-07 22:39:38.836 | warn | Object  94deb8fffe52e4db.power_on_behavior is invalid: obj.common.states has an  invalid type! Expected "object", received "string"
zigbee.0 | 2023-08-07 22:39:38.814 | warn | This object will not be created in future versions. Please report this to the developer.
zigbee.0 | 2023-08-07 22:39:38.813 | warn | Object 94deb8fffe52e4db.effect is invalid: obj.common.states has an invalid type! Expected "object", received "string"
zigbee.0 | 2023-08-07 22:39:38.673 | warn | Device '0x94deb8fffe52e4db' announced itself
zigbee.0 | 2023-08-07 22:39:38.599 | info | Starting interview of '0x94deb8fffe52e4db'
zigbee.0 | 2023-08-07 22:39:14.101 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2023-08-07 22:39:08.881 | info | List of port: [{"path":"/dev/ttyUSB0"},{"path":"/dev/ttyS0"}]

I then red a few other issues and saw the advice of using the latest git version. So I update to 1.8.22 and tried again.
Pressed pairing. Reset the light bulb by toggling it six times.
The light bulb was added but after 10 seconds it was removed again and blinked two times.
This was printed in the log:

> zigbee.0 | 2023-08-07 23:19:36.150 | info | Zigbee: stop joining
zigbee.0 | 2023-08-07 23:19:27.866 | info | DeviceConfigure successful 0x94deb8fffe52e4db TRADFRIbulbE27WSglobeopal1055lm
zigbee.0 | 2023-08-07 23:19:27.642 | warn | download  icon from https://www.zigbee2mqtt.io/images/devices/LED2003G10.jpg  saved into  /opt/iobroker/node_modules/iobroker.zigbee/admin/img/LED2003G10.png
zigbee.0 | 2023-08-07 23:19:27.619 | info | Configuring 0x94deb8fffe52e4db TRADFRIbulbE27WSglobeopal1055lm
zigbee.0 | 2023-08-07 23:19:27.615 | info | Device  '0x94deb8fffe52e4db' is supported, identified as: IKEA TRADFRI LED bulb  E26/27 1100/1055/1160 lumen, dimmable, white spectrum, opal white  (LED2003G10)
zigbee.0 | 2023-08-07 23:19:27.614 | info | Successfully interviewed '0x94deb8fffe52e4db', device has successfully been paired
zigbee.0 | 2023-08-07 23:19:26.447 | warn | Device '0x94deb8fffe52e4db' announced itself
zigbee.0 | 2023-08-07 23:19:26.400 | info | Starting interview of '0x94deb8fffe52e4db'
zigbee.0 | 2023-08-07 23:18:34.879 | info | Zigbee: allowing new devices to join.

I am not sure what I am doing wrong or what I can search for debugging.
Thanks in advance for any tips on how to fix this

Best regards
Heenne

**Comment by Heenne** [comment]
Update: After trying for the whole afternoon I tried one last thing before going to bed. 
My thought: If I turn it off before it can disconnect, maybe it will just stay connected.
Result: It worked. No idea why.

If somebody wants to investigate further I will try to help, otherwise this issue can be closed

**Comment by arteck** [comment]
it works ..nice
