### ISSUE TITLE
check https://github.com/ioBroker/ioBroker.zigbee/tarball/testBattery

### ISSUE THREAD

**Issue by MartinSchlender** [ioBroker/ioBroker.zigbee#1834]
check https://github.com/ioBroker/ioBroker.zigbee/tarball/testBattery

_Originally posted by @arteck in https://github.com/ioBroker/ioBroker.zigbee/issues/1788#issuecomment-1628730092_

Good morning,
the bug is back in 1.8.21 
Thanks
Martin

**Comment by arteck** [comment]
nice 1.8.22 is now
