### ISSUE TITLE
Sonoff ZBMINIL2 causes Adapter to crash when pairing

### ISSUE THREAD

**Issue by rug1024** [ioBroker/ioBroker.zigbee#1837]
I have a Sonoff ZBMINIL2, when I try to pair it the ioBroker Zigbee Adapter v1.8.21 crashes right after "...announced itself".
After restarting Instance the device is show as unknown, not working, must be deleted.

**EDIT: I downgraded the Zigbee-Adapter to 1.8.20, everything works fine now! :-)**

**EDIT 2: When I tried to pair another ZBMINIL2 I ran into the same problem. I upgraded to v1.8.21 again -> crash
Then I downgraded to v1.8.20 again, then I was able to pair the second MINIL2 just like the first.**

**Logs:**
`Pairing time left: 42Device '0x003c84fffed8bca9' announced itself
Interview started: 0x003c84fffed8bca9
Pairing time left: 43`

`zigbee.0 | 2023-08-10 20:43:47.645 | error | Device 0x003c84fffed8bca9 "undefined" not described in statesMapping.
-- | -- | -- | --
zigbee.0 | 2023-08-10 20:43:47.598 | info | debug devices set to []
zigbee.0 | 2023-08-10 20:43:47.595 | warn | download icon undefined for undefined Device not available. Check your devices.
zigbee.0 | 2023-08-10 20:43:47.587 | info | Zigbee started
zigbee.0 | 2023-08-10 20:43:47.587 | info | 0x003c84fffed8bca9 (addr 42254): Not supported (model undefined)(Unknown)
(EndDevice)
zigbee.0 | 2023-08-10 20:43:47.564 | info | Currently 23 devices are joined:
zigbee.0 | 2023-08-10 20:43:47.558 | info | --> transmitPower : high
zigbee.0 | 2023-08-10 20:43:47.558 | info | Unable to disable LED, unsupported function.
zigbee.0 | 2023-08-10 20:43:47.550 | info | Coordinator  firmware version:  {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20221226}}
zigbee.0 | 2023-08-10 20:43:47.270 | info | Installed Version: iobroker.zigbee@1.8.21
zigbee.0 | 2023-08-10 20:43:47.082 | info | Starting Zigbee  npm ...
zigbee.0 | 2023-08-10 20:43:47.081 | info | delete old Backup files. keep only last 10
zigbee.0 | 2023-08-10 20:43:47.055 | info | starting. Version 1.8.21 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.17.0, js-controller: 4.0.24
zigbee.0 | 2023-08-10 20:43:46.962 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
zigbee.0 | 2023-08-10 20:43:19.088 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2023-08-10 20:43:19.088 | info | terminating
zigbee.0 | 2023-08-10 20:43:18.607 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-08-10 20:43:18.588 | info | cleaned everything up...
zigbee.0 | 2023-08-10 20:43:18.587 | error | Cannot read properties of null (reading 'meta')
zigbee.0 | 2023-08-10 20:43:18.587 | error | TypeError:  Cannot read properties of null (reading 'meta')    at  Zigbee.onZigbeeEvent  (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)
zigbee.0 | 2023-08-10 20:43:18.586 | error | unhandled promise rejection: Cannot read properties of null (reading 'meta')
zigbee.0 | 2023-08-10 20:43:18.586 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
zigbee.0 | 2023-08-10 20:43:17.757 | warn | Device '0x003c84fffed8bca9' announced itself
zigbee.0 | 2023-08-10 20:43:17.604 | info | Starting interview of '0x003c84fffed8bca9'
zigbee.0 | 2023-08-10 20:42:58.797 | info | Zigbee: allowing new devices to join.

`

**Comment by arteck** [comment]
install GIT version
