### ISSUE TITLE
Zigbee 1.8.23 Problem mit Switch WXKG01LM

### ISSUE THREAD

**Issue by RasputinBerry** [ioBroker/ioBroker.zigbee#1838]
... "plötzlich und unerwartet" wurden die Tastendrücke von o.g. Xiaomi Schalter nicht mehr verarbeitet. 
Ich habe 2 dieser Schalter, einer im Einsatz (CLICK Auswertung in Blockly), einer als Reserve. 
Beide zeigten dasselbe Verhalten. 
Das Update 1.8.23 ist wohl der Auslöser. Ein Downgrade auf 1.8.21 hat das Problem beseitigt ...

Ich habe den Adapter auf DEBUG gestellt. Da kommen soviel Meldungen rein, dass ich nicht weis was ich hier reinstellen soll ...

**Comment by Czarno13** [comment]
Gleiches Problem habe ich auch, bei allen dieser Schalter. Problem liegt an der Version 1.8.23, ein downgrade auf 1.8.22 hat das Problem gehoben

**Comment by arteck** [comment]
nutzt diese Funktion
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/171b1028-2a4b-4355-bfac-615a87fe0f90)

es werden dann neue Datenpunkte erzeugt

**Comment by RasputinBerry** [comment]
... ich nehme mal so, oder ?
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/56359831/e8bf9879-77e5-4bd7-acc6-600a64e062e8)
Egal ob 1.8.23 oder 1.8.21 ... damit leider keine Problemlösung.

Ich bin wieder auf 1.8.21 OHNE dieses "AUSSCHLIESSEN" und es funktioniert.

**Comment by gitbreiti** [comment]
Es werden dann neue Datenpunkte erzeugt, z.B Single Statt Click, schau es dir nochmal an. Es funktioniert :)

**Comment by Czarno13** [comment]
Naja, wenn neue Datenpunkte erzeugt werden, würde das ja bedeuten, das man alles ändern muss....kann nicht gewollt sein, oder?

**Comment by gitbreiti** [comment]
@Czarno13 
Ich habe mich ebenfalls darüber gewundert und hoffe, dass es in Zukunft wieder ohne diesen Umweg funktioniert. Es wäre auch interessant zu wissen, wie sich ein neu angelernter WXKG01LM jetzt verhält. Dazu müsste sich @arteck äußern. Mit dem vorherigen Post wollte ich nur sagen, dass es mit den neuen Datenpunkten wieder funktioniert. 

Bei mir waren auch nicht viele Skripte davon betroffen.

**Comment by arteck** [comment]
im Converter werden gerade Sachen umgestellt.die ich nicht nachziehen werde. es ist kein Umweg sondern die richtige Nutzung des converter. wir haben die alte Lösung drin gelassen da es funktioniert hat.

die neue Methode ist die von mir erwähnte

**Comment by RasputinBerry** [comment]
OK, es funktioniert, die neuen Datenpunkte hatte ich übersehen ...

**Comment by i-am-magoo** [comment]
> nutzt diese Funktion ![grafik](https://user-images.githubusercontent.com/6681528/260226705-171b1028-2a4b-4355-bfac-615a87fe0f90.png)
> 
> es werden dann neue Datenpunkte erzeugt

Ich häng mich hier mal dran: Ursprünglich hatte ich das selbe Problem. Nach dem Downgrade bekomm ich "click" wieder. Der Vollständigkeit halber wollte ich das Ausschliessen auch testen, dieses gibt mir im neuen Datenpunkt "single".

Leider bekomme ich aber nach wie vor nur Daten auf "link_quality" und "click" (bzw. jetzt "single"), keinerlei Daten jedoch auf alle anderen Datenpunkte (z.B. bekomme ich nichts auf "battery") 😕

**Comment by Equarri** [comment]
Alle Scripte ändern. Klasse. Diese ganze halbgare ioBroker Kacke nervt nur noch. Die kriegen doch nichts geregelt.

**Comment by arteck** [comment]
> Alle Scripte ändern. Klasse. Diese ganze halbgare ioBroker Kacke nervt nur noch. Die kriegen doch nichts geregelt.

dann lösch die Kacke und geh woanders hin..so einfach ist das

**Comment by Equarri** [comment]
Da hast du nicht Unrecht. Besser ist das wohl, denn du bekommst ja eh nichts geregelt. Mach dir nichts vor, du hast es halt nicht drauf.

**Comment by arteck** [comment]
> Da hast du nicht Unrecht. Besser ist das wohl, denn du bekommst ja eh nichts geregelt. Mach dir nichts vor, du hast es halt nicht drauf.

du scheinst ja nur grosse Töne zu spucken.. 
nicht eine code zeile Programmieren aber gross hier rummoppern.. so mag ich das.. genau mein Humor

**Comment by Equarri** [comment]
Ich kann nicht programmieren, das ist richtig, aber scheinbar kannst du es eben auch nicht. Durch deine Programmierkünste stiehlst du anderen Menschen bloß ihre Zeit. Arteck legt Hand an und zig Leute wundern sich warum bei ihnen nichts mehr richtig funktioniert uns suchen stundenlang Fehler. Bravo. Weiter so. Wir sind stolz auf dich.

**Comment by Ilovegym66** [comment]
> Ich kann nicht programmieren, das ist richtig, aber scheinbar kannst du es eben auch nicht. Durch deine Programmierkünste stiehlst du anderen Menschen bloß ihre Zeit. Arteck legt Hand an und zig Leute wundern sich warum bei ihnen nichts mehr richtig funktioniert uns suchen stundenlang Fehler. Bravo. Weiter so. Wir sind stolz auf dich.
> 
> 
Wir sind hier auf GitHub und daher entweder Fehler melden mit logfiles, Versionen etc oder Pull requests erstellen.
Alles andere gehört hier nicht hin. 
Default language is English, please!

**Comment by bortpasc** [comment]
Bei mir werden die neuen Datenpunkte wohl angezeit, jedoch ändern diese nicht bei einer Aktion am Aktor.
Die Datenpunkte werdewn nicht agefüllt...
Was mache ich falsch oder wie kann ich das korrigieren? Jemand eine Idee?
