### ISSUE TITLE
Xiaomi\Aqara Button\Sensor click\press events or states not working with adapter version 1.8.23!

### ISSUE THREAD

**Issue by Kiamer** [ioBroker/ioBroker.zigbee#1839]
Hello everyone,
on adapter version 1.8.23 the click\press events on the Xiaomi Button WXKG01LM and contact events\states on Xiaomi\Aqara Door Sensor MCCGQ11LM are no longer working.
In version 1.8.22 everything looks ok. 
Even deleting\resetting the devices, and re-teaching does not change anything.

Adapter Sonoff ZBDongle-E (EZSP v8)
Adapter Version x-8.6.10.3
Adapter Revision 6.10.3.0 build 297

Node.js: v18.17.1
NPM: v9.6.7

**Comment by DocGame69** [comment]
Bei mir das gleiche...
Zurück auf 1.8.22 und alles geht wieder

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1838

**Comment by Kiamer** [comment]
@arteck Sorry aber das löst bei mir leider nicht das Problem oder ich mach was falsch. 
Ich hab jetzt zum Beispiel den WXKG01LM wie beschrieben ausgeschlossen. Es werden zwar neue Datenpunkte erstellt aber diese reagieren genau sowenig wie vorher die alten. Auch das löschen des Buttons und wieder hinzufügen hat nichts gebracht außer das ich nur noch die neuen Datenpunkte habe. Funktionieren tun sie weiterhin nicht.
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/78258241/5c4187f5-4e9e-4110-a8c5-5aeffa1d5dd8)

**Comment by arteck** [comment]
dann machst du weas falsch oder übersiehst was..
