### ISSUE TITLE
Xiaomi Mijia Switch ab 1.8.23 keine Funktion mehr

### ISSUE THREAD

**Issue by funky4t** [ioBroker/ioBroker.zigbee#1841]
Hi Zusammen,

nach Update des Adapters auf 1.8.23 sind meine Mijia Switches nicht mehr funktionsfähig.

Hier mal das Device zur Identifikation:
<img width="471" alt="Bildschirmfoto 2023-08-14 um 09 19 07" src="https://github.com/ioBroker/ioBroker.zigbee/assets/57875762/2f45d592-87bf-42fd-acee-ff43881853da">

Die Taster funktionierten überhaupt nicht mehr. Der DP long press war interessanterweise permanent auf True: 
<img width="282" alt="Bildschirmfoto 2023-08-14 um 09 19 30" src="https://github.com/ioBroker/ioBroker.zigbee/assets/57875762/2f068811-ee5f-4acd-953c-e4f3e5a229f2">

Betätigen des Tasters, Entfernen Batterie, Neustart Adapter und iob fix blieben alle ohne erhofften Erfolg. Das Log war frei von Fehlermeldungen des Adapters. Auch blieb der DP longpress immer noch auf True. Bei jedem Klick wurden jedoch Sendeleistung und last activity time zuverlässig aktualisiert. 

Daraufhin mal nen Downgrade auf 1.8.22 getestet und dieses lief reibungslos durch und e voila alle betroffenen Taster funktionierten wieder.

Dann nochmal auf 1.8.23 hoch und sie waren leider wieder ohne Funktion. Bin jetzt zurück auf die 1.8.22 da laufen die Taster für mich erstmal wieder. Vielleicht findet ihr einen Fix - und meldet euch, wenn ich noch mit was helfen kann.

BG funky4t

**Comment by DocGame69** [comment]
War auch schon am fluchen...
Du musst das Gerät ausschließen und neu einlernen. Dann werden neue Datenpunke angelegt. Mit diesen musst du deine Scripts usw. anpassen.
[#1883](https://github.com/ioBroker/ioBroker.zigbee/issues/1838)

**Comment by funky4t** [comment]
Danke @DocGame69 das war doch sehr hilfreich. Bin eher der User-Type und verstehe nicht so ganz, warum da nach Update des Adapters neue Datenpunkte in den Scripts eingebaut werden müssen.... Aber zum Glück hab ich beim 2. Setup fast alles über Aliases laufen, ergo war die Arbeit jetzt überschaubar. Dennoch für den Laien nicht ganz klar weil er ja doch hier issues eröffnet...

Aber Danke nun rennt alles wieder und Frauchen ist happy again! :)
