### ISSUE TITLE
INNR 232 C lassen sich nach Update nicht mehr steuern

### ISSUE THREAD

**Issue by Bastler24** [ioBroker/ioBroker.zigbee#1843]
Hallo,

nachdem ich das Update auf die Version 1.8.23 gemacht habe lassen sich meine Lampen nicht mehr schalten. Das pairen läuft 
ohne Probleme durch aber weiter passiert nichts. Des weiteren wollte ich einen Fensterkontakt vom Typ Sonoff [SNZB-04] pairen was nicht funktionierte. Das 2. Problem konnte ich mit einem Downgrade auf die Version 1.8.22 lösen aber die Lampen ließen sich weiterhin
nicht steuern.. Vorher funktionierte es unter der Version 1.8.22.
Was mache ich falsch?

**Comment by arteck** [comment]
> Was mache ich falsch?

versetze dich jetzt in meine Lage und sag mir was ich mit deiner Aussage machen soll.. ausser RATEN


welche Lampe ?? wie steuerst du es.. ?? was passiert wenn du das machst 
https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages

kommen da Werte raus ?

**Comment by Bastler24** [comment]
Sorry für meine dürftigen Angaben.
Also meit steuern meinte ich über die Kachel im Zigbee-Adapter bzw. direkt über den Datenpunkt. Also keine VIS oder kein Script.
 link_quality wird mir keine angezeigt.
Die Debugmessages sehen wie folgt aus:

![Fehlermeldung_RS232C](https://github.com/ioBroker/ioBroker.zigbee/assets/140942318/810b1ae7-9aaf-4b99-b769-77ee57f747fa)
Ich hoffe dir jetzt alle Fragen beantwortet zu haben.

**Comment by arteck** [comment]
welcher Browser Safari ??

**Comment by Bastler24** [comment]
Lampe war ca. 5 Stunden vom Strom getrennt (aus der Fassung entfernt). Folgende Debugmessages wurden geliefert:

 
![nach_einschalten](https://github.com/ioBroker/ioBroker.zigbee/assets/140942318/e7a1fe6f-7e6d-42d1-a97a-3eef32f5cfca)

Ein schalten der Lampe ist nicht möglich. Aber wenn ich das richtig sehe sendet die Lampe doch gewisse Daten oder irre ich da?

**Comment by Bastler24** [comment]
Browser ist Chome.

**Comment by arteck** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/17374

**Comment by arteck** [comment]
solltest den Titel demnächst besser wählen.. du hast ein update des Adapter gemacht und nicht der Lampe.. dein Titel suggeriert das OTA nicht geht für die Lampe

zeigmal die Info kachel
