### ISSUE TITLE
Xiaomi Switch geht nach update 1.8.23 nicht mehr

### ISSUE THREAD

**Issue by saeft2003** [ioBroker/ioBroker.zigbee#1844]
Ich habe mehrere Switche dieser Art die alle mit 1.8.23 nicht mehr funktionieren. Der Link wird übermittelt aber click nicht. Nach downgrade auf 1.8.20 funktioniert wieder alles. 

![4792DC1D-8213-4174-A962-B97A250B88F0](https://github.com/ioBroker/ioBroker.zigbee/assets/66335778/d4a9ca53-0d42-4563-8d7c-a3d5e93f4eef)

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1838
