### ISSUE TITLE
Xiaomi WXKG01LM aktualisiert keine DP 

### ISSUE THREAD

**Issue by torsten-git222** [ioBroker/ioBroker.zigbee#1845]
ich habe drei gepairte Taster bei denen die DP 1x / 2x / 3x click nicht aktualisiert werden. Einzig der DP zigbee.0.xxx.msg_from_zigbee aktualisiert sich.

war zu schnell und hab das issue übersehen: https://github.com/ioBroker/ioBroker.zigbee/issues/1838

Lösung dort hilft, ist aber nicht soo schön

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1838
