### ISSUE TITLE
In 1.8.22 and 1.8.23 all my Xiaomi Switched stopped working

### ISSUE THREAD

**Issue by MartinSchlender** [ioBroker/ioBroker.zigbee#1847]
When clicking a switch the "click", "double" click ect. events don´t fire. But I see that the switches are connected because the msg_from_zigbee and link_quality become highlighted in green (screenshot)

If I downgrade to 1.8.21 everything works fine again.
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/69381774/eb8f09eb-0ee2-4704-8150-fc26e1ad614e)

Versions:

Adapter version: 1.8.23
JS-Controller version: 4.0.24
Node version: v18.17.0
Operating system: raspi mit linux

**Comment by hilde0407** [comment]
Ich habe das selbe Problem! Mein Xiaomi WXKG01LM Schalter funktioniert nicht mehr!

**Comment by Flyor** [comment]
Same here.
Allerdings **nur mit 1.8.23** - mit 1.8.22 funktioniert alles bestens

JS 4.0.24
Node v18.17.0
Ubuntu

**Comment by Ilovegym66** [comment]
Device in Ausschliessen aktivieren. Adapter stoppen, 1 minute warten, neu starten. Dann den Schalter loeschen und neu anlernen, die Datenpunkte sind jetzt anders, Scripte anpassen.

**Comment by nachon77** [comment]
> Device in Ausschliessen aktivieren. Adapter stoppen, 1 minute warten, neu starten. Dann den Schalter loeschen und neu anlernen, die Datenpunkte sind jetzt anders, Scripte anpassen.

Vielen Dank. Habe auch die Probleme wie oben angegeben seit dem Update. Ist der erste Schritt notwendig, oder reicht es auch den Schalter zu löschen und neu anzulernen? (Mir ist nicht ganz klar, wozu der erste Schritt ist, daher die Frage).

**Comment by nachon77** [comment]
> https://github.com/ioBroker/ioBroker.zigbee/wiki
> 
> :-)

Vielen Dank. Habe es so gemacht. Klappt bei mir speziell leider nicht. Schalter reagiert inzwischen zwar wieder, aber ich bekomme die Steckdose dazu nicht geschaltet. Vielleicht liegt es noch an irgendwas. Werde es nochmal probieren. Ggf. kann es wer anders nochmal testen.

Danke.

**Comment by Flyor** [comment]
> 

Ist das als Workaround oder als BugFix zu sehen? Wären bei mir echt viele Schalter - wenn das in der nächsten Version "behoben" ist, fang ich doch damit wieder von vorne an. Sollte als Breaking Change markiert werden.

**Comment by slimline33** [comment]
Würde mich auch interessieren ob das nur ein temporäre workaround ist oder ob man nur eine neue version abwarten muss...

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1838
