### ISSUE TITLE
Re-pairing again and again Tradfri plus

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.zigbee#185]
The IKEA plugs losing its connection after a while and the sensors who are connected to the plugs are not working anymore.
It´s just helping to restart the plugin/iobroker, but then  the log showing these plugs like a new device again.
It takes about 10 minutes until the MESH is rebuilded again. After some ours iobroker is losing the connection again.

- 2019-02-03 19:25:12.525 - error: zigbee.0 Zigbee publish to '0xd0cf5efffe43bd8c', genOnOff - off - {} - 1 failed with error Error: AF data request fails, status code: 233. MAC no ack.
- --
- 
- 2019-02-03 20:10:32.652 - info: zigbee.0 States connected to redis: 127.0.0.1:6379
- --
- 2019-02-03 20:10:32.825 - info: zigbee.0 starting. Version 0.9.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v8.11.1
- 2019-02-03 20:10:32.833 - info: zigbee.0 Start on port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E1A7B8-if00 with panID 6754 channel 11
- 2019-02-03 20:10:32.833 - info: zigbee.0 Queue is: true
- 2019-02-03 20:10:33.891 - info: zigbee.0 zigbee-shepherd started!
- 2019-02-03 20:10:33.917 - info: zigbee.0 zigbee-shepherd ready. version: 2.6.3 rev 20180507
- 2019-02-03 20:10:33.973 - info: zigbee.0 1 (0xd0cf5efffe43bd8c): E1603 - IKEA TRADFRI control outlet (Router)
- 2019-02-03 20:10:33.995 - info: zigbee.0 2 (0x00158d000239fd39): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
- 2019-02-03 20:10:33.996 - info: zigbee.0 3 (0x00158d0002b71f29): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
- 2019-02-03 20:10:33.997 - info: zigbee.0 4 (0xd0cf5efffe305f51): E1603 - IKEA TRADFRI control outlet (Router)
- 2019-02-03 20:10:34.012 - info: zigbee.0 5 (0x00158d0002374c32): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
- 2019-02-03 20:10:34.013 - info: zigbee.0 6 (0x00158d00028b876a): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
- 2019-02-03 20:10:34.013 - info: zigbee.0 7 (0xd0cf5efffe426ab1): E1603 - IKEA TRADFRI control outlet (Router)
- 2019-02-03 20:10:34.031 - info: zigbee.0 8 (0x00158d000239fcc2): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
- 2019-02-03 20:10:34.031 - info: zigbee.0 9 (0x00158d00028b8802): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
- 2019-02-03 20:10:34.032 - info: zigbee.0 10 (0xd0cf5efffe2fb7d4): E1603 - IKEA TRADFRI control outlet (Router)
- 2019-02-03 20:10:34.048 - info: zigbee.0 11 (0x00158d0002720eb7): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
- 2019-02-03 20:10:34.048 - info: zigbee.0 12 (0x00158d000239fd25): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
- 2019-02-03 20:10:34.049 - info: zigbee.0 13 (0x00158d000275d87f): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
- 2019-02-03 20:10:34.049 - info: zigbee.0 14 (0x00158d0002766852): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
- 2019-02-03 20:10:34.049 - info: zigbee.0 15 (0x00158d000236a4ba): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
- 2019-02-03 20:10:34.049 - info: zigbee.0 16 (0x00158d0002b70eb5): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
- 2019-02-03 20:10:34.050 - info: zigbee.0 17 (0xd0cf5efffeef3ebd): E1603 - IKEA TRADFRI control outlet (Router)
- 2019-02-03 20:10:34.064 - info: zigbee.0 18 (0xd0cf5efffe7acfec): E1603 - IKEA TRADFRI control outlet (Router)
- 2019-02-03 20:10:34.079 - info: zigbee.0 19 (0x00158d0002437ba4): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
- 2019-02-03 20:10:34.079 - info: zigbee.0 20 (0x00158d0002720f2f): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
- 2019-02-03 20:10:34.080 - info: zigbee.0 21 (0x00158d00020d7f41): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
- 2019-02-03 20:10:34.080 - info: zigbee.0 22 (0x00158d0002109d9a): WXKG01LM - Xiaomi MiJia wireless switch (EndDevice)
- 2019-02-03 20:10:35.503 - info: zigbee.0 Succesfully configured 0xd0cf5efffe43bd8c
- 2019-02-03 20:10:35.834 - info: zigbee.0 Succesfully configured 0xd0cf5efffe305f51
- 2019-02-03 20:10:36.196 - info: zigbee.0 Succesfully configured 0xd0cf5efffe2fb7d4
- 2019-02-03 20:10:36.198 - info: zigbee.0 Succesfully configured 0xd0cf5efffe426ab1
- 2019-02-03 20:10:36.473 - info: zigbee.0 Succesfully configured 0xd0cf5efffeef3ebd
- 2019-02-03 20:10:38.189 - info: zigbee.0 Succesfully configured 0xd0cf5efffe7acfec
- 2019-02-03 20:12:09.440 - info: zigbee.0 new dev 0xd0cf5efffe43bd8c 51925 TRADFRI control outlet
- 2019-02-03 20:12:43.219 - info: zigbee.0 new dev 0xd0cf5efffe426ab1 55078 TRADFRI control outlet
- 2019-02-03 20:13:46.677 - info: zigbee.0 new dev 0xd0cf5efffeef3ebd 58018 TRADFRI control outlet
- 2019-02-03 20:15:02.214 - info: zigbee.0 new dev 0xd0cf5efffe7acfec 31867 TRADFRI control outlet
- 2019-02-03 20:15:38.651 - info: zigbee.0 new dev 0xd0cf5efffe305f51 52900 TRADFRI control outlet
- 2019-02-03 20:15:59.839 - error: zigbee.0 Cannot get the Node Descriptor of the Device: 0xd0cf5efffe2fb7d4 (Error: Timed out after 10000 ms)
- 2019-02-03 20:17:14.083 - info: zigbee.0 new dev 0xd0cf5efffe2fb7d4 17859 TRADFRI control outlet
- 
- 
- 
- 
-

**Comment by nicoh88** [comment]
@Michaelnorge Short question: Can the outlet also measure the power consumption?
