### ISSUE TITLE
Sorry, aber mein Problem ist nicht gelöst!

### ISSUE THREAD

**Issue by UweLoyal** [ioBroker/ioBroker.zigbee#1850]
Sorry, aber mein Problem ist nicht gelöst!
Ich verwende eine Standard Installation von ioBroker, damit muss auch der Standard ZigBee Adapter laufen!

Siehe auch hier:

2. Wer sollte updaten?

Aktuell empfehlen wir, bei ioBroker-Neuinstallationen mindestens Node.js 10, besser noch 12.x. zu verwenden. Es sind wenige Adapter bekannt, die nicht mit Node 10/12 funktionieren: Details dazu in https://forum.iobroker.net/topic/30561/status-iobroker-und-node-js-12-x

@Apollon77
Ist es hier zielführend, node.js V16 als Voraussetzung für ZigBee Adapter V1.8.23 zu setzen, wenn eine Standard ioBroker Installation nur node.js V14.21.3 hat?
Ich würde erwarten, dass die Standard Adapterversion von ZigBee auch mit der Standard ioBroker Version läuft!

LG
UweLoyal

_Originally posted by @UweLoyal in https://github.com/ioBroker/ioBroker.zigbee/issues/1846#issuecomment-1689949221_

**Comment by arteck** [comment]
ach komm der Post von dir ist 3 JAhre alt....
der Adapter benötigt min nodejs 18... alles drunter wird nicht unterstützt..aber ach schon vom js-controller nicht

**Comment by arteck** [comment]
was ist Standard... wo hast du das her ??

**Comment by Ilovegym66** [comment]
Never ever wird bei einem aktuellen System so eine alte Node Version installiert, da sind alte Repos verwendet worden oder per Hand ne alte Version..

Hier aus der Doku von iobroker:

https://www.iobroker.net/#de/documentation/install/nodejs.md


Hier weiter lesen bitte

https://forum.iobroker.net/topic/64032/update-nodejs-best-practise-supported-16-und-18

**Comment by UweLoyal** [comment]
Das ist der Stand aus meiner Standard ioBroker Version.
Der Raspberry wird immer mit "sudo apt-get update" und "sudo apt-get full-upgrade" auf den neusten Stand gehalten.
ioBroker zeigt die Updates immer an, bei node.js und js-controller sollte das unter Hosts sein, wenn ich noch recht erinnere

Momentan ist alles auf den neusten stand!

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/5464553/ac607424-d8c9-4410-8b9f-404f98b5f2b0)

Ggf. mal mit @Apollon77 kontakt aufnehmen.

Gruß
UweLoyal

**Comment by Ilovegym66** [comment]
Layer 8 Problem

**Comment by UweLoyal** [comment]
Bei wem? 
;-)
