### ISSUE TITLE
Aqara p1 (RTCGQ11LM) reagiert nicht

### ISSUE THREAD

**Issue by schekurt** [ioBroker/ioBroker.zigbee#1851]
Hallo,

Ich habe zwei neue Aqara p1 (RTCGQ11LM) bekommen, die ich zwar erfolgreich mit dem Zigbee Adapter koppeln konnte, jedoch nicht wirklich funktioniert.
Er erkennt nach dem anlernen keinerlei Bewegungen mehr. 
Die Helligkeit scheint auch nicht wirklich plausibel zu sein.
Batteriestatus sowie Spannung liefert er nicht.
debugmessages bleibt leer.

Laut Support von AqaraShop:
Die Geräte sind in Ordnung. Das Hauptproblem ist das Gateway. Der Hersteller von Aqara empfiehlt ,die Verbindung nicht über einen USB-Zigbee-Dongle zu verwenden, sondern über das Gateway von Mijia oder Aqara.

Habt ihr eine Idee warum diese nicht oder nicht mehr kompatibel sein sollten oder wie man diese Bewegungsmelder erfolgreich einbinden kann?

Systemdata:
Raspi 4	(Master)
	Arbeitsspeicher: 	8 GB
	Festplattenart: 	SSD (256GB)
	Betriebssystem: 	iobroker image (debian)
	Nodejs-Version: 	v18.17.1
	NPM-Version: 		V9.6.7
	Installationsart: 	Skript/Manuell
	Image genutzt: 		Ja
	Ort/Name der Imagedatei: 	Link

Raspi 3b+ (Slave mit Zigbee-Dongle)
	Arbeitsspeicher: 	1GB
	Festplattenart: 	SD-Karte
	Betriebssystem: 	iobroker image (debian)
	Nodejs-Version: 	v18.17.1
	NPM-Version: 		V9.6.7
	Installationsart: 	Skript/Manuell
	Image genutzt: 		Ja
	Ort/Name der Imagedatei: 	Link

Adapter:
	IOBroker Admin: V. 6.8.0
	ZigBee V. 1.8.23
	Zigbee Coordinator:
		type:zStack3x0
		version:2-1.2.7.1.
		revision:20210708
		port:/dev/ttyUSB0
		channel:11
	RTCGQ11LM (Aqara p1)
		ieee:0x00158d00073c9b65
		nwk:46372 (0xb524)
		model:RTCGQ11LM
		groups:

Datenpunkte: 
RTCGQ11LM: (Aqara p1)
	Available: true
	Battery percent: (null)
	Trigger device query: Button
	Illuminance: 193
	Link quality: 93
	Message from Zigbee: {"type":"attributeReport","data": {"modelId":"lumi.sensor_motion.aq2"},"linkquality":93,"groupID":0,"cluster":"genBasic","meta":{"zclTransactionSequenceNumber":32,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0}},"endpoint_id":1}
	Time from last motion: 1810
	Occupancy: false
	Occupancy timeout: (null)
	Send to Device: (null)
	Temperature: (null)
	Battery voltage: (null)

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1845

**Comment by schekurt** [comment]
Vielen Dank für den Verweiß.
Ich habe ein Downgrade des Adapters auf V.1.8.21 gemacht.
Anschließend im Adapter das Model ausgeschlossen.
Hierbei wurden neue Datenpunkte angelegt.
Jedoch reagieren beide Bewegungsmelder so gut wie gar nicht.
Bei starker Einwirkung bekomme ich nur sehr selten eine Bewegung detektiert. 
Fehlermeldungen gibt es leider nicht.

Ich bin recht ratlos. Gibt es noch weitere Ansätze, die ich probieren könnte?

**Comment by arteck** [comment]
was ist mit der neuen Version 1.9.6.. ??
