### ISSUE TITLE
Aqara Vibrationssensoren

### ISSUE THREAD

**Issue by Stefan-CH-87** [ioBroker/ioBroker.zigbee#1852]
Meine Aqara Vibrationssensoren verbinden sich mit dem Zigbee aber es werden keine Informationen übertragen.
Adapter Version 1.8.23

Fehler im Log: 
2023-08-25 16:45:08.537 - warn: zigbee.0 (55185) Object 0015XY000XXb6058.sensitivity is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2023-08-25 16:45:08.537 - warn: zigbee.0 (55185) This object will not be created in future versions. Please report this to the developer.
2023-08-25 16:45:08.559 - warn: zigbee.0 (55185) Object zigbee.0.0015XY000XXb6058.sensitivity is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2023-08-25 16:45:08.560 - warn: zigbee.0 (55185) This object will not be created in future versions. Please report this to the developer.

Kommunikation läuft über einen Sonoff Zigbee 3.0 USB

**Comment by arteck** [comment]
wo ist da ein Fehler ????
ich lese nur warnings

**Comment by arteck** [comment]
eingebunden bekommst du den schon.. nur sensitivity ist jetzt anders deklariert
zeigmal das RAW object von 
0015XY000XXb6058.sensitivity

**Comment by Stefan-CH-87** [comment]
Das Problem war, da er mir auf keine Art von Vibrationen reagiert hatte, auch nicht aus schütteln. Was mir auch fehlte war der Batteriestand. Jetzt zeigt er mir zum Beispiel 37% an, obwohl eine komplett neue Knopfzelle drin ist. 
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/100514436/beb33632-9417-4a28-9169-40488a8a44f5)

**Comment by arteck** [comment]
batterie ist ein anderes Thema
..zeigmal das hier
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/13b1b806-aecd-4d2d-9883-60dfd5cc03d4)

**Comment by Stefan-CH-87** [comment]
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/100514436/7b46a879-800a-4984-860a-c6d04ef8bf63)

**Comment by rug1024** [comment]
Habe auch so einen Aqara DJT11LM. 
"Drop Event" und "Tilt Event" werden übermittelt, aber immer nur sehr kurz.
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/96115731/91d1c218-9e39-4f1f-a077-e8728862ee76)
"Vibration Event" kann man nur schwer nachvollziehen, hab den Haken dort aber auch mal kurz gesehen.
Grundsätzlich meldet das Teil aber wenn es irgendwie bewegt wird, danach braucht es eine kurze Pause bis erneut Daten übermittelt werden können.

**Comment by arteck** [comment]
die checkboxen sind nur so zur kontrolle... die objecte sind wichtig und da sollst du auch schauen.. 
da läuft auch der trigger drüber
