### ISSUE TITLE
Device 'Lighting Switch' Dresden Elektronik not supported

### ISSUE THREAD

**Issue by kBrausew** [ioBroker/ioBroker.zigbee#1854]
Is it possible to get the wall switch from Dresden-Electronics to run with ioBroker.Zigbee.
Reason for the request: The almost seamless optical integration in many flush-mounted product ranges (Jung, Gira,...)

unfortunately I don't own one yet, but I've been able to watch it live with Jung CD500 AS500 and A500. Optically really fine thing

Product: [https://www.dresden-elektronik.de/produkt/lighting-switch.html](url)

Prio: nice-to-have

**Comment by chris299** [comment]
@kBrausew I think it needs to be added here: https://www.zigbee2mqtt.io/supported-devices/
