### ISSUE TITLE
Opple 6 fach WXCJKG11LM

### ISSUE THREAD

**Issue by ossisp1** [ioBroker/ioBroker.zigbee#1860]
Hallo,
ich habe hier 3 WXCJKG11LM 6 fach Taster.
Die Signale werden im Adapter auch IMMER erkannt.
Nur der Longpress wird auch immer in den Objekten registriert.
Single, double und triple nicht zuverlässig.
So sind keine zuverlässigen Automationen möglich. 
Sehr niedriger WAF.

**Comment by Ilovegym66** [comment]
Infos zum System, logfile etc sehr niedriger DAF
( Developer Acceptence Factor )

**Comment by ossisp1** [comment]
Welche Infos sind denn relevant?
Software ist auf dem aktuellen Stand. 
Raspberry 4b
Das Problem gibt's bei mir schon seit dem ich die Teile habe. Hatte nur noch nicht die Muße das aufzuschreiben.
In den logfiles gibt keinen Anhaltspunkt.
Von meinem Laien Standpunkt aus sieht es aus wenn die Signale zu kurz anstehen und dann nicht immer weitergereicht werden. Beim Longpress funktionierts ja immer weil es ja in der Natur der Sache liegt das der länger ansteht.

**Comment by arteck** [comment]
und was soll ich da jetzt machen ??? deiner meinung nach.. eine Schulung wie du die Knöppe drücken sollst ??

**Comment by ossisp1** [comment]
Es hätte ja sein können das es da eine Möglichkeit für mich gibt den Fehler selbst rauszufinden. Knopp drücken bekomme ich hin.

**Comment by ossisp1** [comment]
Moin nochmal,
anbei ein Video das meine Problematik zeigt.
Ich möchte doch nur wissen obs an mir liegt.
https://github.com/ioBroker/ioBroker.zigbee/assets/60512944/1857603b-6329-4718-ac43-cf9b37c2d87d

**Comment by arteck** [comment]
> Ich möchte doch nur wissen obs an mir liegt.

ich würde sagen JA..

**Comment by ossisp1** [comment]
Es kann nicht an meinem Finger liegen, nicht an meinem Netzwerk, nicht an der Fernbedienung nicht an der Batterie. Ich sehe JEDE Aktion in dem Adapter aber NICHT in den Objekten. Das Signal kommt also am Raspberry an. Wird komischerweise aber nicht immer in den Objekten weiterverarbeitet. Wenn es nicht nachvollziehbar ist muß ich anderswo fragen.

**Comment by arteck** [comment]
ach jetzt weiss ich was du meinst.... 
setzt da mal ein history drauf und du wirst sehen das es schaltet... 
manchmal geht das so schnell das man es nicht sieht..

**Comment by ossisp1** [comment]
Ja jetzt kann ich die Änderungen sehen. 
Danke für den Klaps auf den Hinterkopf.
