### ISSUE TITLE
Values is NULL in wxkg01lm

### ISSUE THREAD

**Issue by tsiura** [ioBroker/ioBroker.zigbee#1861]
All values ***_click are null in wxkg01lm switch at version 1.8.23. Tried with 3 different devices, paired 5-10 times each - always same issue. Devices interviewed successfully - Interview successful: {"friendly_name":"0xHIDDEN","model":"WXKG01LM","vendor":"Xiaomi","description":"MiJia wireless switch","supported":true}
After rollback to 1.8.22 all devices worked perfect!

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1845
