### ISSUE TITLE
1.8.23 Letzte Erreichbarkeit wird nicht mehr aktualisiert / last reachable is no longer updated

### ISSUE THREAD

**Issue by MartinSchlender** [ioBroker/ioBroker.zigbee#1862]
#1788 

The problem is back in 1.8.23.

`
2023-09-04 09:16:00.175 - warn: javascript.0 (5524) getState "zigbee.0.00158d00041b4295.battery" not found (3)
`

The warnings are from the devices I had to delete and re-learn (Xiaomi Switches) because those were changed in 1.8.22/23
But all the other devices have the same problem. I have their battery states in my SQL history to check in intervals if they are still alive - but the updates are no longer coming. You fixed this bug with the test branche in 1788

**Comment by arteck** [comment]
show me the tree from 00158d00041b4295

**Comment by MartinSchlender** [comment]
> show me the tree from 00158d00041b4295

Thanks,
but not necessary - it seems to work now. The device you wanted the tree was a new one (Xiaomi Switch I had to delete and re-learn). After one hour the battery status arrived.
