### ISSUE TITLE
Farbe nach erneuter Aktivierung stimmt nicht

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.zigbee#1863]
Hallo,
ich hatte bisher eine LED Kugel von Lidl.
Gestern haben wir und noch eine geholt und noch eine Lichterkette dazu.
Seit da an passiert folgendes:
1. Die Lichterkette passt farblich absolut nicht zu dem farbcode der anderen Kugeln. (OK könnte ja noch ma Hersteller liegen.
Haupzproblem:
Wenn man die LEDs mit dem state = true aktiviert, leuchten sie immer grün.
Ich habe schon versucht das behavior auf previous oder customized zu stellen. keine Änderung.
Stellt man dann die Farbe um und wieder auf die gewollte, passt es.
Gibt es da vielleicht einen Bug, oder etwas, was ich zum debuggen liefern kann?

**Comment by arteck** [comment]
fangen wir mal an mit

welche LED Kugel von Lidl...  ich brauch die Kachel

was heist die leuchtet immer Grün ?? auch wenn du nur die brightness setzt ?? auch wenn du die in Rot abschaltest ?

was passiert wenn du die auf Rot umstellst dan brightess auf 0 machst .. und dann wieder auf 100.. leuchtet die Grün oder Rot ?

**Comment by BenAhrdt** [comment]
Es sind die oberen hier:
![2E1A1F2A-2D57-4CAE-80B2-833342DD7AA3](https://github.com/ioBroker/ioBroker.zigbee/assets/92173565/ac98061b-2193-4c90-bda3-b48f448989f3)

Ich schalte die in gelb aus mit state = false und bei einem State = true sind sie grün.

Ich glaube das ist erst so, seit ich die unteren dabei habe und die zweite der oberen Kachel. Alleine hat es wohl funktioniert.

**Comment by BenAhrdt** [comment]
Also ich habe mal eine Kugel und die Lichterkette aus der Steckdose gezogen.
Auch eine wurde beim aktivieren „grün“ bzw. Leuchtete in Grün.
Ich habe zur Abhilfe aktuell die Farbe nach aktivieren geändert und wieder zurück gestellt.
So geht es erst mal, aber ist natürlich nur ne Notlösung.

**Comment by BenAhrdt** [comment]
@arteck also ich habe es jetzt in einem Script so lösen müssen, weil die Lampen immer wieder in der Farbe "Grün" aktiviert werden.

`// Zuweisen der Ids (Vorrübergehend)
const ids = [idLedKugel,idLedKugel2,idLedBodenlichterkette];

// Abbonieren der states beim Einschalten und ändern der Farbe
on({id:ids,val:true},(dp)=>{
    const searchstring = ".zustand";
    const replacestring = ".farbe";
    // Prüfen, ob ".state" vorhanden ist
    if(dp.id.indexOf(searchstring) !== -1){
        const newId = dp.id.replace(searchstring,replacestring);
        // Prüfen, ob der neue String auch existiert
        if(existsState(newId)){
            const actVal = getState(newId).val;
            if(typeof actVal === "string"){ // Nur bei Werten durchführen, die vom Typ String sind (Farben)
                setStateDelayed(newId,actVal.substring(0,actVal.length-2) + "FF",4000);
                setStateDelayed(newId,actVal,8000,false);
            }
        }
    }
});`

**Comment by BenAhrdt** [comment]
Solved?

**Comment by BenAhrdt** [comment]
Das Problem besteht weiterhin.
Ich konnte aber jetzt beobachten, dass wenn die Lampe ausgeschaltet wird, diese noch kurz auf Grün wechselt.

**Comment by arteck** [comment]
was soll ich da machen deiner Meinung nach.. ?? wenn das die reaktion der Birne so ist dass diese immer auf Grün geht.. dann musst d die nach dem einschalten halt auf die gewünschte Farbe setzten
der Adapter macht da nix automatisch

**Comment by BenAhrdt** [comment]
Ok. Habe ich ja gemacht… Schreibe nach jeden einschalten folgende Logik:
Ich lese die soll Farbe, schreibe auf einen anderen wert, dann wieder 2s später zurück auf soll.
Das komische ist, dass es erst seit einem Update so war/ist?
