### ISSUE TITLE
Zigbeedevice Temperatur/Luftfeuchtigkeitssensor wird erkannt aber nicht als korrekter Typ eingebunden

### ISSUE THREAD

**Issue by losossos** [ioBroker/ioBroker.zigbee#1865]
modelZigbee:TS0601
    type:EndDevice
    nwk:47313
    manuf id:4417
    manufacturer:_TZE200_vvmbj46n
    power:Battery
    app version:72
    hard version:1
    zcl version:3
    stack version:0
    date code:
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genGroups (4)
    genScenes (5)
    manuSpecificTuya (61184)
    genBasic (0)
    output clusters:genOta (25)
    genTime (10)

![20230906_173703](https://github.com/ioBroker/ioBroker.zigbee/assets/140890050/32179ac6-6002-438d-b389-7d683eb4cbe9)

**Comment by arteck** [comment]
was ist denn falsch und was richtig ???

**Comment by losossos** [comment]
Moinsen,

naja, also ich arbeite mit einem QinHeng Electronics SONOFF Zigbee 3.0 USB Dongle Plus V2 (Typ E) als Coordinator.
Bei diesem kann ich den Sensor koppeln, aber er wird nicht mit den Parametern Temperatur und Luftfeuchtigkeit angelegt.
Lediglich der Empfangslevel und der Modeltyp wird angezeigt. Ansonsten nur das Fragezeichen.
(ich habe auch noch einen Sonoff Temp/LF-Sensor im Einsatz, der alle erwarteten Werte korrekt liefert.)

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/140890050/0fb2c697-bccd-4e20-a81a-40a6274fb505)

**Comment by c-hum** [comment]
As far as I know, this was solved in the "[friendly project](https://github.com/koenkk/zigbee2mqtt) with similar functionality": https://github.com/Koenkk/zigbee2mqtt/discussions/18827 Maybe this can help and makes it easier to integrate.

**Comment by c-hum** [comment]
Is anyone going to include this device? Thanks in advance.

**Comment by losossos** [comment]
> Is anyone going to include this device? Thanks in advance.

No, unfortunately not, because i dont use the m2z-adaper. 
And in the standard zigbeea dapter I dont find no possibility to integrate the (debug)-file.
Where should I do it there?

**Comment by c-hum** [comment]
Device is now working correct with the latest adapter version v1.9.2 from Github. Task can be closed.

**Comment by losossos** [comment]
yes, it works. great job. 
thx @ all
