### ISSUE TITLE
Zigbee Adapter Conbee2 does not find new devices

### ISSUE THREAD

**Issue by AdminGithubAxiansAT** [ioBroker/ioBroker.zigbee#1867]
Hi!
I have a iobroker docker instance running. I'm using the zigbee-adapter for zigbee devices like window sensors and temperature sensors. To extend the network I'm using hue plugs.
So, everything worked fine until I tried to attach a sonoff sensor. This failed. I only got a ? object. I removed that object. Then the issues started. The hue plug was not manageable any more. Sometimes it worked but most of the time it doesn't. So I also removed the hue plug. But now I cannot pair any new devices any more. I tried to stop and start the adapter, hat a look in the protokoll, but there are no errors. Only that most of the sensors are not reachable because of the missing hue plug.
I also had a look in the shepherd.db file. Looks also good. No devices that should not be in the file.
Does anyone has a hint for me, what I can do?
kr
Christian

**Comment by arteck** [comment]
which sonoff sensor ??

**Comment by AdminGithubAxiansAT** [comment]
it was the sonoff snzb-04.
But on last weekend ít seems to be that the stick repaired itself. Now a deleted device appeared  again in the gui without any doing from my side. Now the stick finds devices again. But it seems, that the stick wireless range is now under a meter. It only works with a powered device next to the conbee stick. Very strange. So, I'm now thinking about, if I should try to pair the window contact again. Maybe I break the system again...
