### ISSUE TITLE
Add device Energy Monitor

### ISSUE THREAD

**Issue by MarkStephan89** [ioBroker/ioBroker.zigbee#1868]
Hi, can you add the these device?
https://www.zigbee2mqtt.io/devices/PJ-1203A.html

Thanks

**Comment by arteck** [comment]
done

**Comment by MarkStephan89** [comment]
thanks, sorry for the (bad) question: 
I need to wait for the next release to use the device? right?

**Comment by arteck** [comment]
you can install the GIT version
