### ISSUE TITLE
Nach Zigbee Adapter Update sind neu verbundende Tradfri E1743 nach ca. 2 Tagen leer

### ISSUE THREAD

**Issue by Heenne** [ioBroker/ioBroker.zigbee#1870]
Hallo Zusammen,

ich habe letztens meinen Zigbee Adapter in iobroker geupdated und bin aktuell auf der Version 1.8.24.
Ich habe seit dem zwei Tradfri E1743 zum ersten Mal mit dem iobroker verbunden.
Leider gehen genau diese Tradfri Geräte nach spätestens 2 Tagen nicht mehr, weil die Batterie leer ist.
Ein anderer Tradfri E1743 Schalter geht bereits seit Monaten problemlos.
Aufgefallen sind mir hierbei, dass die neu verbundenden Geräte andere Datenpunkte haben als das alte Gerät.
Alt:
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/50292612/555ecf83-f099-4a68-8042-bcdc0f791343)
Neu:
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/50292612/8d1681df-e77e-4249-a573-828baceee3b6)

Der neu hinzugefügte Schalter wurde zuvor noch von Node-Red verwendet, aber auch das habe ich raus genommen. 
Der Tradfri Schalter ist also nur mit Zigbee verbunden und hat keine Funktion.
Bis gestern Abend konnte ich noch die Wertänderung bei "switch event" sehen, seit heute morgen ist die Batterie wieder leer.
Auch ein Reset (fünf mal schnell drücken) lässt die rote LED nicht leuchten. Erst wenn ich eine neue Batterie einsetze.

Die Infografiken der beiden sehen wie folgt aus:
Alt:
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/50292612/f9411a1f-e58f-4962-a903-d7bd15b7339e)
Neu:
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/50292612/fb02d3bc-1803-42cd-b831-3c8788562814)

Falls weitere Informationen zur Fehlerdiagnose benötigt werden, gerne Bescheid sagen.
Ich tue was ich kann, damit ich die Tradfri-Schalter demnächst nutzen kann :-)

**Comment by arteck** [comment]
und was soll ich da jetzt machen.. das ist ein und das selbe Gerät.. das siehst du an der Model und manf id.

**Comment by Heenne** [comment]
Danke erstmal für die Rückmeldung.

> und was soll ich da jetzt machen.. das ist ein und das selbe Gerät..
Das ist mir auch schon aufgefallen, trotzdem wollte ich es aufführen weil genau das ja das komische ist an der ganzen Geschichte.

Beide Button liegen unmittelbar nebeneinander. Die WLAN Signale die ich am Laptop sehe sind nicht neu.  Der WLAN-Router ist mehrere Meter entfernt. Weiter als der Zigbee-Stick.
Dadurch das beide nebeneinander liegen, warum sollte der eine gestört werden und der andere nicht?

Ich habe mittlerweile drei neu ausgepackte Buttons getestet. Neu connected usw., bei allen das gleiche Verhalten. Ich habe zwei Batteriehersteller verwendet, auch das gleiche Verhalten. Lediglich der bereits verbundene Knopf funktioniert tadelos, ohne das seine Batterie nach 1 1/2 Tagen leer ist. 

Falls du hier kein Problem siehst, mach das Issue gerne zu. Aber ich finde es schon komisch, dass neue Button plötzlich nach keinen zwei Tagen leer sind.

**Comment by arteck** [comment]
mach das mal 
https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages

somit siehst du im Adapter ob was empfangen wird
