### ISSUE TITLE
Please Add LS Emotion Home Base 

### ISSUE THREAD

**Issue by Maxiking0** [ioBroker/ioBroker.zigbee#1871]
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/86614406/9e31473b-1888-4d24-b847-069da82c844a)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/86614406/ad490471-ee3f-42b1-ab8d-fba1e726b047)

Hello!
Could you add this item please?
It is a Zigbee Adapter from "LS Emotion" (LS Emotion Home Base), which can handle 1-4 light channels. They translate their own radio signals (from their lights) to Zigbee so that Zigbeebridges like Phillips Hue can control them. They are used in lots of furniture like our kitchen.
The Bridge works acceptable with Phillips Hue Bridge, but I dont want to run one Bridge only for this LS Emotion Home Base...

**Comment by Maxiking0** [comment]
When you pair it with the Philips Hue Bridge, it is like you add 1 lamp with only colortempreture and brightness as variables.

**Comment by arteck** [comment]
works in 1.9.1
