### ISSUE TITLE
Aldi (Maginon) Thermostat WT-1

### ISSUE THREAD

**Issue by BassT23** [ioBroker/ioBroker.zigbee#1878]
https://www.aldi-onlineshop.de/p/smartes-heizkoerperthermostat-1025849/

Daten vom zibgee adapter:

modelZigbee:TS0601
type:EndDevice
nwk:24249
manuf id:4417
manufacturer:_TZE200_7p8ugv8d
power:Battery
app version:67
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
genBasic (0)
output clusters:genOta (25)
genTime (10)

**Comment by Nordmann1961** [comment]
Hallo BassT23,
wie hast du denn den Thermostat in ioBroker eingebunden?
Über den Zigbee adapter bekomme ich nur rudimetäre informationen!
Vielleicht mache ich auch was beim pairen falsch, oder verwende den falschen Adapter?

Hello BassT23,
how did you integrate the thermostat into ioBroker?
I only get rudimentary information via the Zigbee adapter!
Maybe I'm doing something wrong when pairing, or am I using the wrong adapter?

**Comment by BassT23** [comment]
Ich hatt den Thermostat per Zigbee Adapter eingebunden.
Die Infos, welche ich bekam habe ich hier gepostet.

Hier wurde es zwar gefixed, aber bis es im iobroker funktioniert wird es wohl noch dauern.

Daher habe ich meine auch wieder zurückgeschickt und die Lidl Zigbee Thermostate gekauft

**Comment by egoclinch** [comment]
> Ich hatt den Thermostat per Zigbee Adapter eingebunden. Die Infos, welche ich bekam habe ich hier gepostet.
> 
> Hier wurde es zwar gefixed, aber bis es im iobroker funktioniert wird es wohl noch dauern.
> 
> Daher habe ich meine auch wieder zurückgeschickt und die Lidl Zigbee Thermostate gekauft

hast du die LIDL Magnion (2er Pack) zum laufen gebracht???

**Comment by BassT23** [comment]
> hast du die LIDL Magnion (2er Pack) zum laufen gebracht???

Nein, habe jetzt 6x Hama (176592) (https://amzn.eu/d/6xqxmIS)
Diese funktionieren prächtig mit ioBroker
