### ISSUE TITLE
MI-Button (WXKG01LM) clicks not working in Version 1.8.23

### ISSUE THREAD

**Issue by Wurchi** [ioBroker/ioBroker.zigbee#1881]
After upgrade the adapter to 1.8.23 my MI-Buttons dosen`t work anymore.
All Information about battery, etc. are fine, only the click events will not recognized. 

I downgrade the Adapter to 1.8.22 and everything works fine again.

**Comment by ulimanaio** [comment]
I have the same problem with 2 buttons. Paired them again, which is working but new clicks are not recognised by iobroker.
https://www.zigbee2mqtt.io/devices/WXKG01LM.html

**Comment by ulimanaio** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1828#issuecomment-1672542571

Nachdem ich die Buttons ausgeschlossen habe, klappt es wieder. Gibt jedoch neue Datenpunkte (ggf. im Script anpassen). Die Buttons sind teilweise so schnell, dass man es im Objekte Tab nicht sieht.

**Comment by afischi** [comment]
I have the same issue after updateing the driver all the click events are no longer working.
I tried with 1.8.23 and 1.8.24 of the Zigbee Adapter
nodejs 18.18.0
js-controler 5.0.12

Any suggestions or do you need help for debugging let me know.

**Comment by csplkiller** [comment]
I have the same problem with buttons.
Adapter version v1.8.23
Node.js: v19.9.0
javascript v7.1.4

**Comment by Rudi-Ment** [comment]
Same Problem here.
Version 1.8.22 is working well with the buttons.
Version 1.8.23 and 24 take up the command of the button like "single, double or triple" but the datapoint in the objects is not updated.
It looks like the command is not passing the adapter

**Comment by arteck** [comment]
work in 1.9.1 and exclude tab... check after added new DP in tree
