### ISSUE TITLE
Unbekanntes zigbee Gerät

### ISSUE THREAD

**Issue by wiese-computer** [ioBroker/ioBroker.zigbee#1887]
Hallo ich habe mir bei Alixpress einen Tuya Energy Meter gekauft und wollte ihn in Zigbee einbinden aber der Adapter kennt ihn nicht.
Ich habe folgenden Energy Meter gekauft siehe link: https://de.aliexpress.com/item/1005005679887461.html?spm=a2g0o.order_list.order_list_main.4.567f5c5fremyXc&gatewayAdapt=glo2deu

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/143525522/7ff4db43-3bdb-4a43-92a8-08705a6e427f)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/143525522/8e3ae932-ae36-471a-8c20-478cc0fa2ebe)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/34134334/ac7a1430-005b-4b28-b5e0-ba082197d6c9)

**Comment by arteck** [comment]
ist es im zigbee2mqtt gelistet ?
