### ISSUE TITLE
Hue Smart Button - dimming?

### ISSUE THREAD

**Issue by ulimanaio** [ioBroker/ioBroker.zigbee#1889]
Hi there,
I just bought the [Hue Smart Button](https://www.amazon.de/dp/B09C3MJR24?psc=1&ref=ppx_yo2ov_dt_b_product_details). 
I expected it to show rotation for dimming in the states "button_skip_back" and "button_skip_foward". How do those work?
Also state "button_press" is always true for me, not sure how to change it.
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/95037770/ef2a045f-0a62-4006-9052-b23d48951dcb)

Thanks

**Comment by arteck** [comment]
no comment
