### ISSUE TITLE
IKEA Audio-Dimmer E1744 doesn't work

### ISSUE THREAD

**Issue by kptkip** [ioBroker/ioBroker.zigbee#1891]
The device E1744 doesn't work anymore in my system. The device can be paired but no interaction data (vol-up/down, button,...) are recognized.

Phenomenon:

- no interaction data (vol-up/down, button,...) are transmitted
- while interacting the DP `msg_from_zigbee` and `link_quality` are updated

content of msg_from_zigbee:
`{"type":"commandStop","data":{},"linkquality":81,"groupID":0,"cluster":"genLevelCtrl","meta":{"zclTransactionSequenceNumber":18,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0}},"endpoint_id":1}`

`{"type":"commandStop","data":{},"linkquality":78,"groupID":0,"cluster":"genLevelCtrl","meta":{"zclTransactionSequenceNumber":20,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0}},"endpoint_id":1}`

Here you can see the branch of the zigbee-device:
<img width="1288" alt="1696487724071-bildschirmfoto-2023-10-05-um-08 28 31" src="https://github.com/ioBroker/ioBroker.zigbee/assets/16083703/fe4bde7c-dce4-4735-a050-5c1580d922aa">

I've tried to delete the device several times and also put in on the "exclude"-list and rebooted the adapter.

Unfortunately I cannot delete the device-type from the "exclude"-list anymore - also weired.
<img width="930" alt="1696495806155-bildschirmfoto-2023-10-05-um-10 49 02" src="https://github.com/ioBroker/ioBroker.zigbee/assets/16083703/47353b2b-45fd-4917-8478-9f9a1ab19ccd">

**Comment by ulimanaio** [comment]
I have the same issue with all my new devices recently. Ikea Symfonsk (gen 2), Hue dimmer, .. 
Maybe this is a general issue?

**Comment by kptkip** [comment]
What do we learn? How to successfully downgrade to earlier versions

**Comment by chris299** [comment]
@kptkip i am clearly hesitant to upgrade to 1.8.23, but i think i have to because of the new controller version). how would i potentially get back to 1.8.10 (which works great for me)? in iob expert mode i can only select versions up to 1.8.17....

**Comment by kptkip** [comment]
Backporting to 1.8.20 solved my problem

**Comment by cherberg** [comment]
> Backporting to 1.8.20 solved my problem
> 
> Backporting to oder Versions could be possible Done on the shell: `Iob Upgrade Package-with-version`

the behaviour is identical to my issue #1821 which was solved for me with 1.8.21

**Comment by cherberg** [comment]
More and more of my IKEA Devices are „dying“ all of a sudden they stop working, maybe due to battery depletion but I cannot confirm that. After that it is not possible to use them anymore. I can delete and pair them successfully but no actions are recorded by the adapter.

**Comment by kptkip** [comment]
Which Version do you use?

**Comment by cherberg** [comment]
> Which Version do you use?

I am on 1.8.23. Downgrading to 1.8.20 does not help.

**Comment by kptkip** [comment]
> > Which Version do you use?
> I am on 1.8.23. Downgrading to 1.8.20 does not help.
Sorry to hear this.

**Comment by cherberg** [comment]
Any hope for a solution to this? I now have 5 dead IKEA switches 🥲

**Comment by arteck** [comment]
check GIT verion

**Comment by kptkip** [comment]
> check GIT verion

Which Version number?
