### ISSUE TITLE
exception: EIO: i/o error, write

### ISSUE THREAD

**Issue by PastCoder** [ioBroker/ioBroker.zigbee#1893]
Since I few days I get the following error: 
2023-10-07 09:46:04.112  - [31merror[39m: zigbee.0 (2657) uncaught exception: EIO: i/o error, write
2023-10-07 09:46:04.264  - [31merror[39m: host.XXXXXXXX instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

As a result also the host reports an error:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/23421026/c4481dc5-a0ab-4869-aadc-bef855761258)

It may be since I updated to Node.js v18.18.0 / NPM 9.8.1.

I did already run a filesystem check and had a look into the SMART status of the SSD, but there evything looked good.
I also updated to the latest version of the zigbee adapter today to be sure that I am not hunting for an already fixed problem. But it also appeared again after that.
I am using Conbee 2.

Does anybody have a proposal how to locate or fix the problem?

**Comment by mava76** [comment]
Same issue here, also with Conbee 2 and Node 18.18.0 and NPM 9.8.1.

**Comment by PastCoder** [comment]
I updated to Node.js: v18.18.1.
Since then I did not observe the error again.

**Comment by Grothesk242** [comment]
Can you do a check if this issue comes up with nodes@20 or 21?
Please setup 
```
iob nodejs-update 20
```

**Comment by mava76** [comment]
Will do so on the weekend.

----
Malte Vahlenkamp
Allensteiner Weg 24
37130 Gleichen
eMail: ***@***.***
Mobil: +49 171 1229110
Am 31. Okt. 2023, 13:45 +0100 schrieb Grothesk242 ***@***.***>:

**Comment by Grothesk242** [comment]
That's what I expected.

**Comment by th4git** [comment]
Same here:
iobroker on Raspberry PI 4 / Raspbian GNU/Linux 11 (bullseye) / v11.7
Node.js: **v20.8.0**
jscontroller:  5.0.16
zigbee-Adapter: v1.8.24 using Conbee II
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/61181368/9858df7a-fe71-4150-b89d-d36620bb9fb3)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/61181368/e6c59eb7-69f0-40d9-a798-fe894b0291aa)

**Comment by Grothesk242** [comment]
Does it work with nodes 18.18.2?

**Comment by th4git** [comment]
Sorry, I cannot check node v18 as I just upgraded from v16 (with same io-error) and its quite some action to handle that.
(need to keep my complex iobroker setup running - not too much testing).

**Comment by astrakid** [comment]
Of possible Test with another USB device. 8n my Case the Stick was defect, which cazsed the i/o Errors.

**Comment by th4git** [comment]
The io-error comes up around once every 2 weeks - so not easy to check what helps anyway: either software or hardware updates.
But is came up after an update of the zigbee adapter within the last 3 month. I can not point out exactly at which version, as the error is quiete rare. So might be fixed at the adapter iself...

**Comment by Grothesk242** [comment]
Sorry, I cannot check node v18 as I just upgraded from v16 (with same io-error) and its quite some action to handle that.

Manage nodejs with 
iob nodejs-update 20
iob nodejs-update 18
It will install the given major version.

**Comment by th4git** [comment]
```
$ sudo iob nodejs-update 18
iobroker nodejs-update [<major-version>]

Upgrade the Node.JS installation to the current LTS

Options:
  --help  Show help  [boolean]
```
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/61181368/e0734889-4452-4813-a400-613d2b9e7a95)

**Comment by Grothesk242** [comment]
Never, never, never use sudo in combination with iobroker.

iob stop
iob fix

After that iob nodejs-update will work

**Comment by th4git** [comment]
Ok: Now nodejs v18.18.2 running at my iobroker.pi4 instance with zigbee adapter.
Main instance (at docker/synology) still using nodejs v20.8.0.
I need to observe for a longer time if crashes still occur and will come back.

Many thanks for advise & support!
