### ISSUE TITLE
Error when setting schedule on thermostat Vale TV05-ZG

### ISSUE THREAD

**Issue by real-iceman** [ioBroker/ioBroker.zigbee#1898]
I try to set up a heating schedule on a Vale TV05-ZG device (recognized as TV02-Zigbee / TS0601 / _TZE200_mudxchsu) using ioBroker Zigbee adapter version 1.8.23.

`working_day` is set to `mon_sun`, according to Z2M documentation it should therefore be sufficient to define the Monday schedule. I am trying to configure the schedule using "send_payload" with value

`{
  "schedule": {
    "week_day": "monday",
    "schedule": "06:00/20 22:00/19 24:00/18"
  }
}`

This fails with error

> Send command to 0xb4e3f9fffec73251 failed with no error code (undefined)

and a correlated debug message:

> Stack trace for null: Error: Invalid "working_day" property, need to set it before at Object.to (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:574:23) at Object.convertSet (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:824:57) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:735:52

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/67663410/6eea52d6-4cee-44be-9051-71cbff9c1a13)

According to the sources this error occurs if `working_day` is not set to one of the allowed values (`mon_sun`, `mon_fri+sat+sun`, `separate`).

Is my approach incorrect or is this a bug?

**Comment by bruno4712** [comment]
Does it help when you send message with actual working_day first?

**Comment by real-iceman** [comment]
Unfortunately not. I tried it manually in the objects tree and with this blockly script:

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/67663410/210cf14b-17ad-4db4-9201-da20b8dd8b67)

**Comment by bruno4712** [comment]
The field working_day is used to control for which days in the week the schedule will be processed. The format {"schedule": {"week_day": VALUE, "schedule": VALUE}} seems fine so far. I found it in the description here. https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html

You can also fill the working_day object value with a send_payload message like this {"working_day": mon_sun} !

I used the object view for filling the field send_payload.

I have an other problem with my thermostat TV02-Zigbee model Zigbee: TS0601 manufacturer: _TZE200_hue3yfsn.
Fairly all objects field can be filled with a send_payload message. In these cases the thermostat answers with a message in the field msg_from_zigbee. Also all respective object fieIds will be filled with the sended values. I don't understand the format of the message but I can see an new timestamp for it. That is fine so far and you can try this too. I have installed the same Zigbee version too and zigbee-herdsman-converters v15.55.3

You log told me that the working_day field ist not defined in zigbee-herdsman-converters.

Unfortunately the zigbee-herdsman-converters will not updated automatically. Updating it can help in many cases.

I have here the problem that all my schedules will not acknowledged in that manner. I have tried too use different formats for the schedule but nothing will work here. Maybe I have to open an issue for it https://github.com/Koenkk/zigbee-herdsman-converters

**Comment by real-iceman** [comment]
I have updated zigbee-herdsman from 0.17.2 to 0.19.2 and zigbee-herdsman-converters from 15.55.3 to 15.94.2 using `npm install` (as described here: https://forum.iobroker.net/topic/41046/gel%C3%B6st-zigbee-herdsmann-converters-wie-manuell-updaten/5?lang=de).

Unfortunately, the problem still occurs.

**Comment by real-iceman** [comment]
Meanwhile, I found that the converter requires the property `meta.state.working_day` to process the schedule, but the `state` property is an empty object when `convertSet` is called in main.js.

When I set `meta.state.working_day = 'mon_sun'` in the debugger, then the schedule is successfully processed and reflected in all read-only `schedule_monday`, `schedule_tuesday`, ... properties of the device.

Is it possible to fix the missing state in the converter call?

**Comment by real-iceman** [comment]
The convertSet call is in main.js:
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/67663410/bfa8cd59-e716-4573-8002-89b19156af06)

My JS skills are also very basic.  And I have zero knowledge about the inner workings of the Zigbee adapter and how the required state is supposed to be obtained for schedule configuration. :cry:

**Comment by ch90045** [comment]
If you find any solution, please update here as well - thanks!

**Comment by bruno4712** [comment]
> Meanwhile, I found that the converter requires the property `meta.state.working_day` to process the schedule, but the `state` property is an empty object when `convertSet` is called in main.js.
> 
> ![grafik](https://user-images.githubusercontent.com/67663410/276177538-ccdf0a7a-6a54-4b39-aa1c-2e33067f5575.png)
> 
> When I set `meta.state.working_day = 'mon_sun'` in the debugger, then the schedule is successfully processed and reflected in all read-only `schedule_monday`, `schedule_tuesday`, ... properties of the device.
> 
> ![grafik](https://user-images.githubusercontent.com/67663410/276177628-84b4f1c2-a269-4eec-a5a8-50890a6b4131.png)
> 
> Is it possible to fix the missing state in the converter call?

How can I start the debugger? What is needed to use the debugger?

**Comment by real-iceman** [comment]
You need to stop the Zigbee adapter instance and restart it in debug mode (`iobroker debug ...`). Then, you can attach a Node.js debugger to the debugging port (e.g., Chrome DevTools, VSCode). See [Node.js Debugging Guide](https://nodejs.org/en/docs/guides/debugging-getting-started).

**Comment by bruno4712** [comment]
> You need to stop the Zigbee adapter instance and restart it in debug mode (`iobroker debug ...`). Then, you can attach a Node.js debugger to the debugging port (e.g., Chrome DevTools, VSCode). See [Node.js Debugging Guide](https://nodejs.org/en/docs/guides/debugging-getting-started).

I have started it. Now a big log will be shown in my putty. How can I debug with the suggested WS address?

iobroker@iobrokertc:/opt/iobroker$ iobroker debug zigbee
Debugger listening on ws://127.0.0.1:9229/ffed7fd1-add1-485f-ada7-5b18cab1a7e9
For help, see: https://nodejs.org/en/docs/inspector
2023-10-27 17:32:54.690  - debug: zigbee.0 (11860) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-10-27 17:32:54.748  - debug: zigbee.0 (11860) Objects client ready ... initialize now
2023-10-27 17:32:54.754  - debug: zigbee.0 (11860) Objects create System PubSub Client
2023-10-27 17:32:54.757  - debug: zigbee.0 (11860) Objects create User PubSub Client
2023-10-27 17:32:54.789  - debug: zigbee.0 (11860) Objects client initialize lua scripts
2023-10-27 17:32:54.803  - debug: zigbee.0 (11860) Objects connected to redis: 127.0.0.1:9001
2023-10-27 17:32:54.837  - debug: zigbee.0 (11860) Redis States: Use Redis connection: 127.0.0.1:9000
2023-10-27 17:32:54.850  - debug: zigbee.0 (11860) States create System PubSub Client
2023-10-27 17:32:54.852  - debug: zigbee.0 (11860) States create User PubSub Client
2023-10-27 17:32:54.914  - debug: zigbee.0 (11860) States connected to redis: 127.0.0.1:9000
2023-10-27 17:32:54.983  - debug: zigbee.0 (11860) Plugin sentry Initialize Plugin (enabled=true)
2023-10-27 17:32:55.484  - error: zigbee.0 (11860) adapter disabled
2023-10-27 17:32:55.784  - info: zigbee.0 (11860) starting. Version 1.8.23 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.17.1, js-controller: 5.0.12
2023-10-27 17:32:55.861  - debug: zigbee.0 (11860) Using zigbee-herdsman with settings: {"network":{"panID":6738,"extendedPanID":[173,221,223,221,221,220,219,218],"channelList":[14],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6e2e601f6445ed11a178cf8f0a86e0b4-if00-port0","adapter":"zstack"},"adapter":{"forceStartWithInconsistentAdapterConfiguration":false}}
2023-10-27 17:32:55.991  - info: zigbee.0 (11860) delete old Backup files. keep only last 10
2023-10-27 17:32:55.995  - info: zigbee.0 (11860) Starting Zigbee  npm ...
2023-10-27 17:32:56.068  - debug: zigbee.0 (11860) Starting zigbee-herdsman...
2023-10-27 17:32:56.544  - info: zigbee.0 (11860) Installed Version: iobroker.zigbee@1.8.23

**Comment by bruno4712** [comment]
I can start the chrome debugger remotely with port 9229 like this: https://forum.iobroker.net/topic/4201/adapter-debuggen-mit-chrome

node --inspect-brk=<ip-adresse iobroker>:9229 iobroker.zigbee/main.js --force --logs

But I have no idea how to test it. I'd like to send a message via field field send_payload and want to check out how it will be proceed...

**Comment by bruno4712** [comment]
I have the same problem with my thermostat TV02-Zigbee model Zigbee: TS0601 manufacturer: _TZE200_hue3yfsn. The "working_day" property can not be read from object list. Therefore is it not possible to set the schedule. Patching the value in the debugger makes it possible to fill the schedule objects for each day of the week.

Stack trace for null: Error: Invalid "working_day" property, need to set it before at Object.to (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:574:23) at Object.convertSet (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:824:57) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:735:52

![tuya js weekScheduleType](https://github.com/ioBroker/ioBroker.zigbee/assets/127872559/26aa65cc-ea11-429d-9f21-f809481ccdbc)
Sending {"working_day": "mon_sun"}  with send_payload object will not help here. Other fields from object list can be set in this way.

The processing of "working_day" property has to be fixed in zigbee-herdsman-converters.

Zigbee v1.8.23

**Comment by bruno4712** [comment]
> If you find any solution, please update here as well - thanks!

This has to be fixed in zigbee-herdsman-converters.
