### ISSUE TITLE
How to update Ikea SYMFONISK sound remote gen2?

### ISSUE THREAD

**Issue by ulimanaio** [ioBroker/ioBroker.zigbee#1899]
Hi there, I would like to update my Ikea SYMFONISK sound remote gen2 (https://www.zigbee2mqtt.io/devices/E2123.html) because some of the button presses are not working for me. 
Those states are not working:
Toogle:
`{
  "type": "commandToggle",
  "data": {},
  "linkquality": 111,
  "groupID": 0,
  "cluster": "genOnOff",
  "meta": {
    "zclTransactionSequenceNumber": 93,
    "manufacturerCode": null,
    "frameControl": {
      "frameType": 1,
      "manufacturerSpecific": false,
      "direction": 0,
      "disableDefaultResponse": true,
      "reservedBits": 0
    }
  },
  "endpoint_id": 1
}`
volume_up_hold & volume_down_hold stay true forever:
`{
  "type": "commandMove",
  "data": {
    "movemode": 1,
    "rate": 255
  },
  "linkquality": 111,
  "groupID": 0,
  "cluster": "genLevelCtrl",
  "meta": {
    "zclTransactionSequenceNumber": 112,
    "manufacturerCode": null,
    "frameControl": {
      "frameType": 1,
      "manufacturerSpecific": false,
      "direction": 0,
      "disableDefaultResponse": true,
      "reservedBits": 0
    }
  },
  "endpoint_id": 1
}`

Also better logic for the initial presses would be amazing. Currently:  dots_1_initial_press & dots_2_initial_press is always true when trying for dots_1_long_press & dots_2_long_press & dots_1_double_press & dots_2_double_press.

I have added the device to "Ausschliessen" in the Adapter as it was not working at all.

Thank you very much

Version: v1.8.23

**Comment by a-i-ks** [comment]
See [1724](https://github.com/ioBroker/ioBroker.zigbee/issues/1724)

**Comment by ulimanaio** [comment]
Thanks @a-i-ks
