### ISSUE TITLE
New IKEA Device TRADFRI bulb E27 WW globe 806lm

### ISSUE THREAD

**Issue by kirk6210** [ioBroker/ioBroker.zigbee#1902]
Hello,

there's a new device from IKEA Tradfri

LED bulb Warm White dimmable

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/76783038/61e21d09-e19a-4ca7-b53f-9c971e04def9)

**Comment by LeStef101** [comment]
I was just trying to pair this with my zigbee interface in iobroker. Is this a new product by ikea which issnt supported yet?
Should i return the lightbulb or is it planned to add support for those anytime soon?

Greetings, Stef

**Comment by arteck** [comment]
also not in GIT version ??

**Comment by LeStef101** [comment]
I kinda feel stupid for asking, but im not sure what the git version is and what issnt :/
I believe i installed the zigbee adapter just via iobroker if you're refering to that.

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/wiki/GIT-install

**Comment by LeStef101** [comment]
Thanks for your help!
If you got the time, please answer me just one more question: What is the difference between both zigbee adapter installations (and therefor why is this commit only available with the git install)?
