### ISSUE TITLE
Version as of Oct 25, 2024 - 18-30 keeps crashing

### ISSUE THREAD

**Issue by daNick73** [ioBroker/ioBroker.zigbee#1903]
I had to update to newest from GitHub since 1.8.23 doesnt have converters for newest IKEA Tradfri LED2106R3
(https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-345-lm-smart-kabellos-dimmbar-weissspektrum-50547413/)

That version keeps crashing with this note

Any advice appreciatedf

`

zigbee.0 | 2023-10-25 18:32:01.942 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
host.raspberrypi | 2023-10-25 18:32:03.355 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.raspberrypi | 2023-10-25 18:32:03.360 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'color_options')
host.raspberrypi | 2023-10-25 18:32:03.361 | error | Caught by controller[1]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
host.raspberrypi | 2023-10-25 18:32:03.362 | error | Caught by controller[1]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
host.raspberrypi | 2023-10-25 18:32:03.363 | error | Caught by controller[1]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
host.raspberrypi | 2023-10-25 18:32:03.363 | error | Caught by controller[1]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:244:54)
host.raspberrypi | 2023-10-25 18:32:03.364 | error | Caught by controller[1]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:591:22)
host.raspberrypi | 2023-10-25 18:32:03.365 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

`

**Comment by arteck** [comment]
Why are you separating the bulb from the power ?? this is you Problem,..sry

**Comment by lug-gh** [comment]
@arteck 

This is quite normal behavior, e.g. during a firmware upgrade or when carrying a lamp from a to b, and there are countless other reasons why a device can rejoin the network. I think the adapter even crashes when pairing a new light bulb.

Surely it's a software problem that must be solvable?
Saying that the device must never lose its connection to the network is not a realistic solution.

Of course, you are not obliged to fix this error, but it is still a mistake to simply close an error message even though the error really exists and has not been fixed.

**Comment by daNick73** [comment]
@arteck 

It is all my problem, and I am grateful you spend time to work on this adapter.

Just to say since I apparently annoyed you.

On the matter:

1. I only got "permission at home" to change bulbs to Zigbee if they can be used with normal, not smart switches. I was not aware that scenario is outside this adapters parameters, sorry if I missed it.

2. Using 1.8.22, the problem of crashes does not exist, that one is solid.

Only reason for me to update are new converters for new devices. Otherwise, I wouldn't have raised an issue


Again, @arteck please excuse if I annoyed you. I know your work is a gift and you define your limits and if my usecase is just not included in your path, that is MY problem.

**Comment by daNick73** [comment]
@lug-gh 

If anyone ever finds this:
Newer versions (from 1.9.6) apparently fixed it
https://github.com/ioBroker/ioBroker.zigbee/issues/2017 

@arteck thx :)
