### ISSUE TITLE
Innr SP200: Keine Leistungswerte

### ISSUE THREAD

**Issue by PG248** [ioBroker/ioBroker.zigbee#1908]
Ich habe 3 davon im Einsatz. Bei allen zeigt Datenpunkt load_power (null)W, auch wenn ein Verbraucher dran hängt.

Im Forum gabs zu demselben Problem Anfang 2022 mal einen Thread. Angeblich wurde das Problem damals mit der Version 1.6.12 gefixt. Ich habe aber die aktuelle 1.8.23 im Einsatz. Ist der Fehler irgendwann wieder reingekommen?

**Comment by PG248** [comment]
Sind natürlich SP220. Kann den Titel leider nicht mehr ändern.

**Comment by arteck** [comment]
auch nicht wenn du device_query triggerst
