### ISSUE TITLE
npm ERR! Invalid: lock file's zigbee-herdsman-converters@15.101.0 

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.zigbee#1909]
Tests fail with :

npm ERR! Invalid: lock file's zigbee-herdsman-converters@15.101.0 does not satisfy zigbee-herdsman-converters@15.102.0

Eventually theres a problem with the dep ?

**Comment by arteck** [comment]
ignore it

**Comment by mcm1957** [comment]
Standard githib tedt are blocked bycthis
