### ISSUE TITLE
update of zigbee2mqtt to v1.33.1 (zigbee-herdsman-converters) for new IKEA TRADFRI LED bulb LED2104R3

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.zigbee#1913]
I would like to see an update to v1.33.1 for supporting of new model IKEA LED2104R3  
https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.33.1  
https://github.com/Koenkk/zigbee-herdsman-converters/pull/6147  

For me it works now after manually adding following lines in /opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js
```
{
    zigbeeModel: ['\u001aTRADFRI bulb GU10 WW 345lm8'],
    model: 'LED2104R3',
    vendor: 'IKEA',
    description: 'TRADFRI LED bulb GU10 WW 345 lumen, dimmable',
    extend: tradfriExtend.light_onoff_brightness(),
}
```

**Comment by cataclisma** [comment]
Have the same issue.

My old bulb died and I had to buy a new one LED2103G5. zigbee-herdsman-converters addes support for them, but I can't add them to the zigbee adapter, because it needs to be updated.

**Comment by Diginix** [comment]
@cataclisma You can help yourself by patching the ikea.js file with the quoted lines in my comment.
Or use my attached patched one and place it here: opt/iobroker/node_modules/zigbee-herdsman-converters/devices/
[ikea.zip](https://github.com/ioBroker/ioBroker.zigbee/files/13253639/ikea.zip)

**Comment by cataclisma** [comment]
> {
>     zigbeeModel: ['TRADFRI bulb E27 WW globe 806lm'],
>     model: 'LED2103G5',
>     vendor: 'IKEA',
>     description: 'TRADFRI LED bulb E27 806 lumen, wireless dimmable warm white',
>     extend: tradfriExtend.light_onoff_brightness(),
> }

Thank you! It works as it should now :)
