### ISSUE TITLE
Write "alive" state of router device to iobroker

### ISSUE THREAD

**Issue by sonntam** [ioBroker/ioBroker.zigbee#192]
In issue #31 it was stated that a router ping would occur every 60 seconds. However, there is no "device alive" state in iobroker so we can use that information.

Can this be implemented within the current framework?

It would be very convenient to use this e.g. within the yahka adapter as we can configure a device to be shown disconnected if it cannot be reached on the network.

**Comment by allofmex** [comment]
I would like to see this too.
May be extended for end-devices with configured reporting too (if last-update older than 3 times max importing interval then deviceAlive=false)

**Comment by kirovilya** [comment]
Only routers can be pinged, but with end-devices this will not work.
But each device now has a link_quality state.
By the time changes of this state can be understood when the last time was interaction with the device

**Comment by sonntam** [comment]
@kirovilya True, but it does not seem to work when using groups. I might try to implement the functionality myself and provide a PR. But, be warned! I hardly have any experience in writing node.js code :wink:

**Comment by sonntam** [comment]
Here is a small status update: So far, with minor modifications I got it working. I will do more testing before I provide a PR.

**Comment by sonntam** [comment]
Functionality has been merged upstream - closing the issue. Thank you!
