### ISSUE TITLE
Support for  SONOFF TRVZB

### ISSUE THREAD

**Issue by cthomaidis** [ioBroker/ioBroker.zigbee#1920]
Please add support for device SONOFF TRVZB

https://www.zigbee2mqtt.io/devices/TRVZB.html

Current Adapter Version 1.8.23 is not recognizing the device.

**Comment by UserRS232** [comment]
that would be wonderful. I could use it too, the thermostats are cheap and of good quality.

**Comment by arteck** [comment]
install GIT version

**Comment by AidenAtSonoff** [comment]
This is SONOFF FAE team. Are you satisfied with the current platform adaptation on ioBroker?
