### ISSUE TITLE
Adapter can't handle the temperature/humidity sensor TY0201

### ISSUE THREAD

**Issue by maggo5** [ioBroker/ioBroker.zigbee#1924]
Hello,
I recently bought a temperature/humidity adpter via aliexpress. 

https://de.aliexpress.com/item/1005005454107609.html?spm=a2g0o.productlist.main.1.221753546Iu4Ne&algo_pvid=b80f90da-05ba-4f24-b3c0-7979a3853ffa&algo_exp_id=b80f90da-05ba-4f24-b3c0-7979a3853ffa-0&pdp_npi=4%40dis%21EUR%2117.68%217.07%21%21%2118.34%21%21%40211b801516990048661691819eece9%2112000033145077179%21sea%21DE%21700550976%21&curPageLogUid=YIui6HC2BzZ2

But it didn't recognized from the zigbee adapter.
Here is the information:

coupling dialogue:
New device joined '0xa4c1382ca1077fcd' model TY0201
Device '0xa4c1382ca1077fcd' announced itself
Interview started: 0xa4c1382ca1077fcd

device information:
modelZigbee:   TY0201
type:                 EndDevice
nwk:                  23534
manuf id:          4417
manufacturer:  _TZ3000_zl1kmjqx
power:             Battery
app version:    211
hard version:  1
zcl version:     3
stack version: 2
interviewed:   false
configured:    false
endpoint:      1
profile:          260
input clusters:genBasic (0)
                    genPowerCfg (1)
                    genIdentify (3)
                    msTemperatureMeasurement (1026)
                    msRelativeHumidity (1029)
output clusters:genOta (25)

I am new at github, but can I add this device by myself ?
What can I do ?

Best regards
Alex

**Comment by maggo5** [comment]
Hello,
now I received the second temperature/humidity sensor which isn't supported too:

https://de.aliexpress.com/item/1005005627336725.html?spm=a2g0o.productlist.main.5.d80f5378o7Lnzc&algo_pvid=76564170-bda1-4e97-a118-f53aea850952&algo_exp_id=76564170-bda1-4e97-a118-f53aea850952-2&pdp_npi=4%40dis%21EUR%216.81%214.77%21%21%217.07%21%21%40210386d116990141257765181e2787%2112000034841851844%21sea%21DE%21700550976%21&curPageLogUid=K8V5w2mbWVhn

from coupling dialogue:
New device joined '0xa4c1386c797deaeb' model TS0601
Interview successful: [object Object]
Error: Device 0xa4c1386c797deaeb "TS0601" not described in statesMapping.. undefined
Device '0xa4c1386c797deaeb' announced itself
Interview started: 0xa4c1386c797deaeb

device information:
modelZigbee:TS0601
type:EndDevice
nwk:20208
manuf id:4417
manufacturer:_TZE204_upagmta9
power:Battery
app version:73
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
genBasic (0)
output clusters:genOta (25)
genTime (10)

**Comment by zeromancer1972** [comment]
Same here, please add the TY0201 :-) Thank you :-)

**Comment by arteck** [comment]
works in 1.10.0
