### ISSUE TITLE
Aqara Smart Radiator Thermostat E1 SRTS-A01

### ISSUE THREAD

**Issue by chrineuh** [ioBroker/ioBroker.zigbee#1925]
There is no way to use the device with an external sensor.
How can I solve this in Iobroker?

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/60777681/7ed2aff2-e31c-4f48-965a-5b8d0ac8e002)

What did you expect to happen?
I want to set the temperature of the device to an external temperature sensor, but there is no option to set the value to this device. All values are like:
zigbee.1.54ef44100073b6e3.device_temperature
zigbee.1.54ef44100073b6e3.local_temperature
are read only.

**Comment by arteck** [comment]
write a blockly or script ...
