### ISSUE TITLE
Can not add members to group

### ISSUE THREAD

**Issue by stheinen** [ioBroker/ioBroker.zigbee#1926]
Hello,
I have installed the zigbee adapter version 1.8.23 using a SonOFF USB Zigbee dongle.
I have added devices and created a "Group 01".
Unfortunately I am not able to edit the group and add menbers. (see screenshot)
I have flashed the newest firmware to the SONOFF dongle. 
Is there anything else that I can try to get it work? 
Or is it a know issue?
Best Regards
Stefan

<img width="1031" alt="Screenshot 2023-11-05 180321" src="https://github.com/ioBroker/ioBroker.zigbee/assets/62441676/c16c8abc-ea7a-4100-bdeb-385401502cbc">

**Comment by arteck** [comment]
i see only the group... on your screenshot
you can select the group under Device

**Comment by Schmakus** [comment]
Hi, 
I have the problem, that some groups are not visible in the drop-down menu. 
The groups exist and work. 
Any idea?
