### ISSUE TITLE
Add Avatto tuya zigbee 3,0 trv (ME167) device to the adapter

### ISSUE THREAD

**Issue by stvae** [ioBroker/ioBroker.zigbee#1928]
Hello, I have bourght a tuya zigbee thermostat on Alixpress. I connect it with iobroker but it got the wrong device and values TS601 and in the object values there were no temp values. 
link:  https://de.aliexpress.com/item/1005003952150617.html?spm=a2g0o.productlist.main.9.188cCnynCnynkc&algo_pvid=2805692b-101f-46b6-9209-e8c7cd8a768e&aem_p4p_detail=202311070907551708790747523840001908743&algo_exp_id=2805692b-101f-46b6-9209-e8c7cd8a768e-4&pdp_npi=4%40dis%21EUR%2144.87%2126.93%21%21%2146.93%21%21%40211b5e2516993768749673876e1c3a%2112000027550116432%21sea%21DE%213434058241%21&curPageLogUid=KrV6JduOi7C1&search_p4p_id=202311070907551708790747523840001908743_5

Avatto tuya zigbee 3,0 trv

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/150173666/f93f2ee8-0c31-47e6-b5ad-fe8e45fa9919)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/150173666/cfb1b108-a4e8-48e5-9609-a1011b47c4f7)

Could you please add the thermostat to the device to the zigbee adapter.

**Comment by arteck** [comment]
is it supported by zgbee2mqtt ??

**Comment by stvae** [comment]
I think so. At list it is listed in this list.
https://zigbee.blakadder.com/Avatto_TRV06.html

**Comment by hohmannc85** [comment]
something new here?

**Comment by asgothian** [comment]
Should work with current version, as long as the device from Baliexpress matches the one listed on Blackadder.
