### ISSUE TITLE
neues Gerät hinzufügen -> Xiaomi LYWSD03MMC Zigbee Temperatur/Luftfeuchtigkeitssensor.

### ISSUE THREAD

**Issue by atifan** [ioBroker/ioBroker.zigbee#1929]
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/58658412/2e272667-40db-4a71-9989-743cd9c179c8)

Die Xiaomi Bluetooth-Sensoren LYWSD03MMC können mit einer Custom Firmware von Bluetooth auf Zigbee umgeflasht werden.
Eine Anleitung wie das ganze Funktioniert findet man unter folgendem Link: https://smarthomescene.com/guides/convert-xiaomi-lywsd03mmc-from-bluetooth-to-zigbee/

Nach dem Flashen der Zigbee Firmware kann das Gerät dann im IoBroker Zigbee-Adapter über die Pairing Funktion hinzugefügt werden. Das Gerät wird auch erkannt und hinzugefügt, es fehlen aber die Daten des Sensors (Temperatur, Luftfeuchtigkeit, Batteriestand usw.).

Wäre super wenn dieser Sensor integriert werden könnte. Finde Zigbee viel besser als Bluetooth.

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/58658412/2aaad4aa-31cd-4356-9eca-23d2e809a646)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/58658412/5550c9bc-e04d-4ee4-aaae-364f073bca2b)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/58658412/c3de5a2f-f47b-4d84-954a-aa5e32332232)

**Comment by atifan** [comment]
Hallo, ja bei zigbee2mqtt ist es schon integriert.
Hier der Link: https://www.zigbee2mqtt.io/devices/LYWSD03MMC.html

**Comment by JamesTheEagle** [comment]
Hi, @arteck super Adapter! Ich hätte auch großes Interesse an der Einbindung des Devices.
[Hilft das irgendwie weiter?](https://smarthomescene.com/guides/convert-xiaomi-lywsd03mmc-from-bluetooth-to-zigbee/)

Pairing the LYWSD03MMC to Zigbee2MQTT
The Xiaomi LYWSD03MMC was added to Zigbee2MQTT with version 1.33.2, so if you do not want to use an external converter make sure you update. Here’s how to use the external converter in case the device is unrecognized:

Create a new file in zigbee2mqtt folder (next to configuration.yaml)
Name it lywsd03mmc.js (make sure it ends with .js)
Open the file and copy the contents from bellow:
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;

const definition = {
    zigbeeModel: ['LYWSD03MMC'],
    model: 'LYWSD03MMC',
    vendor: 'Xiaomi',
    description: 'Temperature & humidity sensor',
    fromZigbee: [fz.temperature, fz.humidity, fz.battery],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const bindClusters = ['msTemperatureMeasurement', 'msRelativeHumidity', 'genPowerCfg'];
        await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
        await reporting.temperature(endpoint, {min: 10, max: 300, change: 10});
        await reporting.humidity(endpoint, {min: 10, max: 300, change: 50});
        await reporting.batteryVoltage(endpoint);
        await reporting.batteryPercentageRemaining(endpoint);
    },
    exposes: [e.temperature(), e.humidity(), e.battery()],
    ota: ota.zigbeeOTA,
};

module.exports = definition;
YAML
Save the File
Open Zigbee2MQTT’s configuration.yaml file (NOT Home Assistant’s)
Location of the file is zigbee2mqtt/configuration.yaml
Enable the external converter by adding the following lines:
Restart Zigbee2MQTT and pair the LYWSD03MMC
external_converters:
  - lywsd03mmc.js

**Comment by Death111** [comment]
From the [How to support a new device](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device#:~:text=in%20node%2Dmodules/-,zigbee%2Dherdsman%2Dconverters,-/devices.js.%20) instructions it seems the device was already added to the [zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters).
See https://github.com/Koenkk/zigbee-herdsman-converters/pull/6301 and it was released with version [zigbee-herdsman-converters v15.96.0](https://github.com/Koenkk/zigbee-herdsman-converters/releases/tag/v15.96.0) 

So what is missing from my understanging is to reference the new version of the repo and it should be working.

**Comment by Schwemm** [comment]
@Death111 Nice to hear that it works.
Could you explain what you exactly did to "bump the dependencies to..."?

**Comment by Death111** [comment]
Not sure if I should share it, as it may break your installation. So own risk: In my io-broker installation I went to the node_modules/ioBroker.zigbee folder and in package-lock.json set the version of 'zigbee-herdsman-converters' to the '15.112.0'. then I ran 'npm install' which will update the package and I restarted iobroker. That was all.

But I would not do this without making a backup first.

The master branch of this repo already references 15.125.0 of the zigbee-herdsman-converters https://github.com/ioBroker/ioBroker.zigbee/blob/master/package-lock.json - So with the next release it will work. Not sure how the release cycle is.

**Comment by Schwemm** [comment]
Thanks for your response. I will give it a try - of course after a backup ;-)

**Comment by Schwemm** [comment]
It worked exactly as described. Thanks a lot!

**Comment by thomycc** [comment]
it it possible to create a step-by-step howto? would help many users alot.
thanks!

**Comment by thomycc** [comment]
> What about the step by step guide provided by @Death111 ?
> 
> 1. In my io-broker installation I went to the node_modules/ioBroker.zigbee folder and in package-lock.json set the version of 'zigbee-herdsman-converters' to the '15.112.0'
> 2. then I ran 'npm install'
> 3. restart iobroker

sorry, missed that. works fine, thanks!

**Comment by arteck** [comment]
works in 1.9.1

**Comment by MaZchen** [comment]
@xtraxion maybe wrong firmware. I had the same issue.

On another sensor I followed the steps described here "https://github.com/devbis/z03mmc/?tab=readme-ov-file" it works without any fiddling.

I downloaded the two firmware files from the links provided i the tutorial and loaded them into the Telink flasher.
