### ISSUE TITLE
cc2531 timeout

### ISSUE THREAD

**Issue by curryhoden** [ioBroker/ioBroker.zigbee#193]
Hey community,

we build up da setup of Raspv2 with flashed cc2531

latest stable image for raspberry
update iobroker and system (apt-get upgrade)

install your adapter from the iobroker webinterface

Plugged in the cc2531

sudo chmod 777 /dev/ttyACM0

sudo ls -l /dev/serial/by-id/
/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936B43B-if00 

Copy and paste link to adaptersettings.

Start the adapter but i always got an Timeout for the stick.

`

2019-02-10 12:40:25.382 - info: zigbee.0 States connected to redis: 127.0.0.1:6379
--
2019-02-10 12:40:25.673 - info: zigbee.0 starting. Version 0.9.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v8.15.0
2019-02-10 12:40:25.691 - info: zigbee.0 Start on port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936B43B-if00 with panID 6754 channel 11
2019-02-10 12:40:25.692 - info: zigbee.0 Queue is: true
2019-02-10 12:40:25.842 - info: zigbee.0 Reset coordinator
2019-02-10 12:40:25.897 - info: zigbee.0 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)

after 60seconds

2019-02-10 12:41:29.005 - error: zigbee.0 Error while starting zigbee-shepherd!. Error: request timeout
--

`

reflashed with newest firmware.

Same problem...

Any ideas?

**Comment by kirovilya** [comment]
Try running the adapter a minute after plugging in the stick.
Firmware stick done correctly?

**Comment by curryhoden** [comment]
Firmware of cc2531 is flashed correctly
cc2531 worked last week for a couple hours
Stopped working after reboot of RaspberryPi

I tried every combination of:
-unplug/reboot/plugin
-unplug/plugin the stick
-unplug/wait 30min/plugin 
-unplug/plugin/press button (near usb)
-stop zigbee instance/unplug/plugin/start zigbee instance
-stop zigbee instance/unplug/wait 30min/plugin/start zigbee service
-stop zigbee instance/unplug/wait 30min/plugin/press button(near usb)/start zigbee service

tried all of this with:
-the newest image of iobroker (expermental)
-the last stable image from 2018 (the smaller one, not the ppv one)
-debian with iobroker manually installed in VM Workstation
-set /dev/ttyACM0 OR /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936B43B-if00


ALL devices/set-ups give me the following feedback:
-cc2531 LED turns green after plugin
- ls -l /dev/serial/by-id/ shows me :  
"lrwxrwxrwx 1 root root 13 Feb 11 13:24 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936B43B-if00 -> ../../ttyACM0"

But everything results in the log entry shown in post 1

BUT!!! the stick does his job greatfully last week

AND its flashed with the newest firmware after a thousands of github issues tells me

**Comment by kirovilya** [comment]
I don't understand what's going on with your cc2531

**Comment by curryhoden** [comment]
Shit ...

Bought everything
build everything up
20mins of fun
end of project ...

let me know if there is any idea in your head....you are the last hope

**Comment by kirovilya** [comment]
what port are you put in settings? /dev/ttyACM0 ?

**Comment by curryhoden** [comment]
/dev/ttyACM0 
OR 
/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936B43B-if00

/dev/ttyAMA0 doenst work of cource

and there are no others like ttyUSB0 

OUTPUT OF: ls -l /dev/serial/by-id/

/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936B43B-if00 -> ttyACM0

**Comment by kirovilya** [comment]
as described in main page - you need /dev/ttyACM0 port in common case

**Comment by curryhoden** [comment]
i tried a couple of times with every differnt entry in the Settings Tab
/dev/ttyACM0
/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936B43B-if00

Nothing changed

**Comment by kirovilya** [comment]
try to run adapter in debug mode and show your log

**Comment by curryhoden** [comment]
how can i start in debug?

**Comment by kirovilya** [comment]
![image](https://user-images.githubusercontent.com/8360230/52592930-b7f81780-2e58-11e9-9557-30aa6291c40a.png)
Step 1 and 2

**Comment by curryhoden** [comment]
[log.txt](https://github.com/ioBroker/ioBroker.zigbee/files/2853307/log.txt)

Done

**Comment by kirovilya** [comment]
From log I do not see that can be changed except for the port name. As I said, it's better to specify the port /dev/ttyACM0. Some kind of problem with the port or stick itself.
I don't know what else to do. Try checking the stick on another machine.

**Comment by curryhoden** [comment]
I really tried both of them (ttyACM0 / serial/by-id/Texas....)

Stick doesnt work on a raspv2 and a x86 computer with iobroker

I have no idea why

**Comment by kirovilya** [comment]
my log from windows 
![image](https://user-images.githubusercontent.com/8360230/52657875-ac652900-2f0a-11e9-8fc3-bc1d7178bcb8.png)

nothing works for the first minute - then it’s ok

**Comment by curryhoden** [comment]
Nothing new here...

still having this issue..

its was build up for 3 days now....cc2531 still not online...

/dev/ttyACM0 is selected...newest firmware on it

**Comment by k2dp2k** [comment]
I ran into the same problem on a rock64, the same lines in the log. Reinstall a several times with no effect. Up and downgrade npm and also the Shepherd Version. On Adapter Version 0.5 steh Stick was Running, After the Update to 0.9.1 it is impossible to get it working again, Even After a complete reinstall of the system. It seems like the Adapter is crashing when executing a command done by the stick. For now i have no idears anymore...

**Comment by kirovilya** [comment]
hm... maybe this is a problem with the "serialport" module. In the latest versions, the version "6.2.0" was used, and in 0.5 was still 4.0.1

**Comment by mullischlumpf** [comment]
Hi, i have the same problem with my cc2531 stick.
iobroker runs on a container in my synology NAS. It worked for a few hours without any problems and after i had added most of my zigbee devices it stops working. Till now i found no way to get it working again. I updated / downgraded the zigbee adapter and the npm version.  I will try to downgrade the serialport version and check if this will help.

**Comment by kirovilya** [comment]
@mullischlumpf you can still try to raise serialport to version 7

**Comment by mullischlumpf** [comment]
@kirovilya I upgraded the serialport module to version 7.1.4 and now it works again 👍 thanks for this hint. I hope it will not timeout again after a few hours.

**Comment by mullischlumpf** [comment]
unfortunately it timed out again :-( and it stops working. It happens after i added more and more devices... then i downgraded serialport to version 4.01 but this does not help.  After that i tried a npm rebuild but i get still a timeout. So for now i don´t find any solution.

**Comment by arteck** [comment]
i do not know which NAS it is, but one of QNAP or Synology disconnect the USB port automatically.. i think here is the issue

**Comment by mullischlumpf** [comment]
@arteck I use a zwave stick on the same NAS and the zwave stick works without any problems. But i will check that

**Comment by wossix** [comment]
Hey,
I don't know if it is useful but - last weekend I had some equal issues with my CC2531. I wanted to analyse later - but I had no time, yet. Therefore, sharing my findings with you.

The stick was 24x7 in use with no issue.

Last weekend I updated the stick with the firmware "CC2531ZNP-Prod.hex" (20190217)[DEV] and moved the iobroker instance to a virtual environment.

Stick worked for the while of adding some/most of my devices (Osram, Philips); Suddently the stick stopped to operate... "timeouts in the log"; Removing and adding, re-flashing (same firmware) didn't helped. It worked partly for a short time... sometimes the adapter (iobroker.zigbee (0.9.1)) kept crashing... (sorry - but I have no logs to share, yet.)
 
My solution was downgrading to "CC2531ZNP-Prod.hex" (20181024).

I don't know if it was a coincident; But last thing what I did, was setting up two zigbee groups. One with two Philips bulbs and one with one Osram and one Philips bulb. I knew that it would most likely not work with Osram... But wanted to test it any how.

Cheers

**Comment by mullischlumpf** [comment]
hm i could not test this because i have no flashing tools here... I have the CC2531ZNP-Prod_20190109 Version on my stick.
Can someone confirm that it works with an older firmware?

**Comment by mullischlumpf** [comment]
I checked my dmesg when i start the zigbee adapter and i think here is the problem.... It really seems that the usb stick gets disconnected / reconnected loop when starting the zigbee adapter... 
The question is why...

[ 2370.369113] cdc_acm 1-3:1.0: ttyACM1: USB ACM device
[ 2370.375182] usbcore: registered new interface driver cdc_acm
[ 2370.382042] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[ 2519.414638] usb 1-3: USB disconnect, device number 29
[ 2519.420318] cdc_acm 1-3:1.0: acm_ctrl_irq - usb_submit_urb failed: -19
[ 2519.427797] cdc_acm 1-3:1.0: failed to set dtr/rts
[ 2519.688015] usb 1-3: new full-speed USB device number 30 using xhci_hcd
[ 2524.818327] usb 1-3: device descriptor read/64, error -110
[ 2540.050134] usb 1-3: device descriptor read/64, error -110
[ 2540.280126] usb 1-3: new full-speed USB device number 31 using xhci_hcd
[ 2545.410432] usb 1-3: device descriptor read/64, error -110
[ 2560.641241] usb 1-3: device descriptor read/64, error -110

**Comment by arteck** [comment]
i have also a old version of Firmware.. from 20181224.. ok i used it on raspi...

is this your issue 
https://forum.iobroker.net/topic/19695/cc2531-in-container-erkennt-keine-ger%C3%A4te/6
i think this is done...

ansonsten schreib mich mal an in Forum

**Comment by arteck** [comment]
@kirovilya 
we have 2 users with same Problem with new Firmware .. 20190217..

**Comment by kirovilya** [comment]
About 20190217 firmware need create issue to https://github.com/Koenkk/Z-Stack-firmware

**Comment by kirovilya** [comment]
https://github.com/Koenkk/Z-Stack-firmware/issues/46

**Comment by arteck** [comment]
we are back to serialport 6
