### ISSUE TITLE
Nous A1Z load_power/activePower won't refresh

### ISSUE THREAD

**Issue by Chiller2019** [ioBroker/ioBroker.zigbee#1933]
Hey,

NodeJS-Version: v18.17.1
ZigBee-Stick: Conbee II (newest FW)
Zigbee-Adapter: v.1.8.24

The socket works (for example as a router, I don't know why).
However, the load_power status is not updated.
Only using the developer tool can I update the power consumption.

Can the time to read out "activePower" be reduced? Currently he communicates differently... sometimes after 5 minutes, sometimes after 30 minutes or after two hours.

Or is there a way that I can query the whole thing manually in Blockly?

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/50303399/ead6f51a-e232-4bb7-91ab-4d414b6955de)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/50303399/07c7e015-ed1a-4774-a436-696957bda7da)

Kind regards

**Comment by arteck** [comment]
use device_query with a script for poll the device

**Comment by Dickschieder** [comment]
@Chiller2019 I've the same question. Did you solve the problem?
