### ISSUE TITLE
 DeviceConfigure:Failed error in log after correcting Extended Pan ID

### ISSUE THREAD

**Issue by cobra98** [ioBroker/ioBroker.zigbee#1934]
After an Updat of Node 16 to 18.17.1 and Update of Zigbee Adapter 1.8.24 i got 
`Extended PAN ID is reversed (expected=51b8a11c004b1200, actual=00124b001ca1b851)`
in the log so i change it to the expected.
Worked so far but now i get a message additional
`DeviceConfigure:Failed to DeviceConfigure.configure 0x003c84fffeb3dbf7 TS0044 (Error: Read 0x003c84fffeb3dbf7/1 genBasic(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240)) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32))`
Besides all seems to work

Also i have to mention i excluded "WXKG01LM" as requested after 1.8.23 don`t know if this an important for solving this.

output from lsusb if needed

`Bus 002 Device 002: ID 152d:0580 JMicron Technology Corp. / JMicron USA Technology Corp. External
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 006: ID 0451:bef3 Texas Instruments, Inc. CC1352R1 Launchpad
Bus 001 Device 003: ID 03eb:2013 Atmel Corp. iAQ Stick
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`

**Comment by arteck** [comment]
MAC transaction expired dont know why
