### ISSUE TITLE
Neues Gerät hinzufügen -> Sonoff Presence Sensor SNZB-06P

### ISSUE THREAD

**Issue by viper-666** [ioBroker/ioBroker.zigbee#1935]
Hallo,
es wäre klasse wenn dieser Sensor hinzugefügt werden könnte. Er wird zur Zeit als unbekanntes Gerät erkannt.
![1699810420833-sonoff1](https://github.com/ioBroker/ioBroker.zigbee/assets/13709294/a95f1419-9193-4ea1-87f0-b3af3f2bf6c6)
![1699810488063-sonoff2](https://github.com/ioBroker/ioBroker.zigbee/assets/13709294/cce4c457-c557-4e9a-8c55-320618b49d93)
![1699812517076-sonoff3](https://github.com/ioBroker/ioBroker.zigbee/assets/13709294/e8c40538-0f32-44e2-aeb3-3b67fed0bd80)

Und unter "msg_from_zigbee" unter Objekte wird abwechselnd folgendes JSON? Objekt angezeigt:
`{"type":"commandQueryNextImageRequest","data":{"fieldControl":0,"manufacturerCode":4742,"imageType":2060,"fileVersion":4099},"linkquality":69,"groupID":0,"cluster":"genOta","meta":{"zclTransactionSequenceNumber":11,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0}},"endpoint_id":1}
 
{"type":"readResponse","data":{"zclVersion":3},"linkquality":72,"groupID":0,"cluster":"genBasic","meta":{"zclTransactionSequenceNumber":121,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}`
Der Sensor ist unter Zigbee2MQTT schon gelistet:

[https://www.zigbee2mqtt.io/devices/SNZB-06P.html](url)

So wie es aussieht ist der "occupancy" and "no_occupancy_since" Wert wichtig. 
Wenn ich im Zigbee Adapter unter Enrwicklungsoptionen den occupancy Wert lese bekomme ich 0 und 1 zurück.

Ich weiß aber nicht wie ich den Adapter "beibringe" diesen Wert zu lesen und unter Objekten anzuzeigen.

**Comment by JHD47804** [comment]
Das würde mich auch interessieren, habe vor den Sensor zu kaufen...

**Comment by denjo1982** [comment]
habe heute auch den sensor bekommen und das selbe problem

**Comment by arteck** [comment]
install GIT Version

**Comment by denjo1982** [comment]
leider ändert sich der wert von Occupancy nicht auf false
