### ISSUE TITLE
BUG: Ausgeschlossene Geräte können nicht mehr von der Ausschluss Seite gelöscht werden

### ISSUE THREAD

**Issue by viper-666** [ioBroker/ioBroker.zigbee#1937]
Adapter Version: v1.8.24
Ich habe zum Testen zwei Zigbee Geräte unter dem Reiter Ausschließen hinzugefügt.
Nun bekomme ich diese nicht mehr von der Liste gelöscht.
Ich klicke auf dem Abfalleimer, es erscheint die Abfrage " Löschen bestätigen Do you really want to delete exclude?".
Ich klicke auf ja starte den Adapter neu und das Gerät ist immer noch in dort.
Erst wenn ich den Adapter unter dem Reiter Geräte mit "Löschen erzwingen (für verlorene Geräte) lösche bleibt es unter Ausschließen so stehen.
![Zigbee_Fehler](https://github.com/ioBroker/ioBroker.zigbee/assets/13709294/e04343a9-5461-4828-8572-1d224116f3c1)
Und nach dem neuen Koppeln ist das Gerät immer noch ausgeschlossen.

**Comment by Alex71w** [comment]
Ich hatte das ebenfalls und mir damit beholfen, dass ich das Gerät an der entsprechenden Stelle (unter "exclude") im Objektbaum gelöscht habe.

**Comment by arteck** [comment]
works in 1.9.1
