### ISSUE TITLE
SONOFF Smart Heizkörperthermostat TRVZB

### ISSUE THREAD

**Issue by AHahne64** [ioBroker/ioBroker.zigbee#1938]
Hallo,

ich habe mir den neuen SONOFF Smart Heizkörperthermostat TRVZB gekauft. Leider wird er zwar unter ioBroker erkannt aber es wird nur ein Fragezeichen angezeigt und es gibt keine Datenpunkte mit denen man das Thermostat steuern könnte. Gibt es eine Möglichkeit die Geräte im ioBroker so einzubinden das man sie auch steuern kann.

Gruß Andreas

**Comment by AHahne64** [comment]
selbes Problem wie unter #1936

**Comment by arteck** [comment]
doppelt
