### ISSUE TITLE
Problem with Xiaomi Mi Wireless Switch WXKG01LM -> No Actions reckognized by the Adapter, only msg_from_zigbee is updated

### ISSUE THREAD

**Issue by cherberg** [ioBroker/ioBroker.zigbee#1939]
Dear Developer,

same issue as #1894 but now with a brandnew Xiaomi Mi Wireless Switch. I can sucessfully pair the device but no button actions are reckognized by the adapter. 

In the Objects I can see that the TransactionSequenceNumber in msg_from_zigbee is updated is counting when I press the button, all other fields are filled with (null).

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/8701752/7a3a694b-4a3f-4efb-a904-9304c60c71f5)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/8701752/be566fa2-e282-4854-ac6c-b475d48770ab)

Adapter Version is latest 1.8.24

Thanx for looking into this.

**Comment by viper-666** [comment]
I think you have to put the device under exposes tab (Ausgeschlossene Geräte). Than the messages were directly from the zigbee-herdsman-converter. You have also take then a other datapoint what will then created.

**Comment by cherberg** [comment]
I will try the workaround to this issue suggested by Viper.

Was this issue closed by mistake or will there not be a fix for this?

**Comment by Seele737** [comment]
Are there any new findings about this? Unfortunately I haven't found a solution for this yet.
