### ISSUE TITLE
Implement Philips hue Motion Outdoor Sensor

### ISSUE THREAD

**Issue by braindead1** [ioBroker/ioBroker.zigbee#194]
Philips hue motion outdoor sensor SML002 can be paired, but is not recognized,

**Output in log after pairing:**
new dev 0x0017880104bc0258 34695 SML002

**Modelnumber:**
9290019758

**Functions:**
Motion sensor

**Link to hue website:**
https://www2.meethue.com/de-de/p/hue-outdoor-bewegungsmelder/8718699625474

**Comment by DevilDesire** [comment]
Same is with SML001 (indoor sensor)
All what i get is the link quality :/
