### ISSUE TITLE
Sonoff Thermostat SNZB-02

### ISSUE THREAD

**Issue by Dom0359** [ioBroker/ioBroker.zigbee#1940]
Ich habe hier 2 Sonoff-Thermostate vom Typ SNZB-02. 
Beide lassen zwar mit dem Sonoff-Adapter verbinden - liefern aber keine Werte zurück. 

Die Software ist auf dem aktuellen Stand. 

Kann sich das bitte jemand anschauen???  - Danke

**Comment by Dickschieder** [comment]
hallo
ich habe die gleichen Sensoren. Sie funktionieren meistens. Von 8 Sensoren fallen aber immer mal wieder zwei Stück aus. Löschen und wieder verbinden, dann gehts mal wieder ein paar Tage. Scheint aber generell bei den Sensoren zu passieren. Nach dem verbinden habe ich das Verhalten von dir aber auch schon gehabt. Bei mir hilft nochmal raus löschen und neu anlernen.

**Comment by haahne** [comment]
Habe auch diese Probleme. 2 Steigen ab und zu mal aus und müssen dann neu Gepairt werden.
