### ISSUE TITLE
support Tuya water leak detector 

### ISSUE THREAD

**Issue by chrfen** [ioBroker/ioBroker.zigbee#1942]
Team,
is there any chance to support the Tuya water leak detector ? and the Tuya Zigbee Smart Home Natural Gas Sensor
please help me :-)

https://de.aliexpress.com/item/1005005873013472.html?spm=a2g0o.order_list.order_list_main.17.2b765c5fHHyqC9&gatewayAdapt=glo2deu

https://www.aliexpress.us/item/1005005936314298.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt

My zigbee adapter version is v1.8.24

Geräteinformation

model:[TS0207_water_leak_detector_1](https://www.zigbee2mqtt.io/devices/TS0207_water_leak_detector_1.html)
description:Zigbee water flood sensor + 1m probe cable
modelZigbee:TS0207
type:EndDevice
nwk:51921
manuf id:4417
manufacturer:_TZ3000_ocjlo4ea
power:Battery
app version:66
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genPowerCfg (1)
genIdentify (3)
ssIasZone (1280)
genBasic (0)
output clusters:genOta (25)
genTime (10)

Pairing time left: 49
New device joined '0xa4c13868c99b1f4d' model TS0207_water_leak_detector_1
Pairing time left: 50
Interview successful: {"friendly_name":"0xa4c13868c99b1f4d","model":"TS0207_water_leak_detector_1","vendor":"TuYa","description":"Zigbee water flood sensor + 1m probe cable","supported":true}
Pairing time left: 51
Interview started: 0xa4c13868c99b1f4d
Pairing time left: 52
Pairing started 

![water](https://github.com/ioBroker/ioBroker.zigbee/assets/118547323/9d4d48fb-c8b0-4746-b9b1-4094c88b5e97)

![tuya2](https://github.com/ioBroker/ioBroker.zigbee/assets/118547323/70c8f61f-aa41-4456-9f17-a4e9c36cbba9)

![gas1](https://github.com/ioBroker/ioBroker.zigbee/assets/118547323/5e783fd0-2672-4ed0-b5bf-b871ca981e68)

![gas2](https://github.com/ioBroker/ioBroker.zigbee/assets/118547323/78355727-c70e-4343-bcd4-60533733f4d7)

**Comment by arteck** [comment]
works in 1.9.1
