### ISSUE TITLE
Support von innr FL 122 C (LED-Strip)

### ISSUE THREAD

**Issue by Alex71w** [ioBroker/ioBroker.zigbee#1943]
Könntet Ihr bitte den anscheinend recht neuen LED-Strip von innr integrieren: FL 122 C.
In Zigbee2MQTT ist er bereits enthalten --> [Link](https://www.zigbee2mqtt.io/devices/FL_122_C.html)

Vielen Dank! :-) & Viele Grüße, Alex

PS. Die Meldung aus dem Log beim Pairing:
Device 0x00158d00041b799e "FL 122 C" not described in statesMapping.

Detailinfos:

modelZigbee:FL 122 C
type:Router
nwk:60428
manuf id:4454
manufacturer:innr
power:Mains (single phase)
app version:48
hard version:2
zcl version:2
stack version:33
date code:20221010
build:3.0.1
interviewed:true
configured:false
endpoint:1
profile:49246
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
lightingColorCtrl (768)
output clusters:genOta (25)
endpoint:2
profile:49246
input clusters:touchlink (4096)

**Comment by arteck** [comment]
install GIT version

**Comment by Alex71w** [comment]
Funktioniert! Ganz herzlichen Dank!!
