### ISSUE TITLE
Send command to *************** failed with no error code

### ISSUE THREAD

**Issue by haahne** [ioBroker/ioBroker.zigbee#1944]
Hallo, 
seit längerem bekomme ich die ganze Zeit im Log Folgende Error Code's: 

Send command to 0x00158d00013bccc8 failed with no error code

Beim Device handelt es sich um eine Lampe die Permanent am Strom hängt. 
Reichweite kann auch nicht das Problem sein , ist ca. 5m vom Coordinator entfernt.

Wenn ich diese Lampe vom Strom trenne , wandert der Fehler zu einem anderen Gerät im Netzwerk. 

Habe einen Screenshot  gemacht und mal den Log angehängt. Fall's "Debug" Log erwünscht ist bitte sagen.
![zigbee](https://github.com/ioBroker/ioBroker.zigbee/assets/120421080/69df39ea-c72e-495a-adfd-b9e262f20770)
[log zigbee.txt](https://github.com/ioBroker/ioBroker.zigbee/files/13401450/log.zigbee.txt)

**Comment by roadsterdriver** [comment]
Ich habe seit ca. 3 Tagen das gleiche Problem, bei mir ist der  Conbee II Stick im Einsatz

**Comment by haahne** [comment]
Um ein Reichweitenproblem wirklich auszuschließen habe ich die Lampe 2 Meter vom Coordinator angeschlossen. Selbe Fehlermeldung. 
Ist nen Sonoff Zigbee 3.0 Stick
type:zStack3x0
version:2-1.2.7.1.
revision:20230507

**Comment by thohoj** [comment]
Das gleiche hier.

conbee2, Firmware 0x26580700
Zigbee Adapter 1.8.24

Besonders wenn man mehrere Lampen (Hue gu10 white ambiance) schaltet, dann reagieren ein paar sporadisch nicht. Immer andere.

**Comment by protree** [comment]
Ich möchte mich hier einmal einklinken, habe mit dem Conbee II Stick und dem Biobroker Zigbee Adapter dasselbe Problem. Der Fehler tritt sporadisch auf, lässt sich jedoch auch provozieren, wenn man in dem Szenen Adapter eine große Anzahl (bei mir z.B. 20) an Zigbee Geräten gleichzeitig steuert. Als Workaround habe ich ein Intervall von 100ms im Szenenadapter eingestellt, damit tritt der Fehler weitaus seltener auf (Aber er tritt weiter sporadisch auf). Reichweitenprobleme kann ich bei mir ausschließen, da auch manchmal Geräte im selben Raum des ConBee Sticks betroffen sind.

**Comment by Schattenruf** [comment]
Selbes Problem hier beim Schalten von 3 EGLO Lampen mit Farbwechsel (1 Wechsel dauert 10s).
Ebenfalls den Conbee Stick 2 im Einsatz.
2 Lampen funktionieren ohne Probleme nur die Dritte will nicht so wie ich ;)
