### ISSUE TITLE
[New Device] SONOFF Thermostatic Radiator Valve TRVZB

### ISSUE THREAD

**Issue by moetom280** [ioBroker/ioBroker.zigbee#1948]
Hi,
got this [Sonoff Radiator](https://sonoff.tech/product/home-appliances/trvzb/)
it is already integrated in [zigbee2mqtt](https://www.zigbee2mqtt.io/devices/TRVZB.html)

would be really great to have it also interated in ioBroker.

![sonoffTRVZB](https://github.com/ioBroker/ioBroker.zigbee/assets/132597712/b66e2f0c-e003-456b-8ef3-a9998ca00ba7)

```
modelZigbee:TRVZB
type:EndDevice
nwk:34905
manuf id:4742
manufacturer:SONOFF
power:Battery
app version:0
zcl version:8
date code:20230811
build:1.1.1
interviewed:true
configured:false

endpoint:1
profile:260

input clusters:
genBasic (0)
genPowerCfg (1)
genIdentify (3)
genOnOff (6)
genPollCtrl (32)
hvacThermostat (513)
64599
64529

output clusters:
genTime (10)
genOta (25)
```
If you need any further information, let me know please.

thanks a lot

**Comment by moetom280** [comment]
Same device as in #1938

**Comment by AidenAtSonoff** [comment]
This is SONOFF FAE team. Are you satisfied with the current platform adaptation on ioBroker?
