### ISSUE TITLE
Implementation Bitron AV2010/25 possible?

### ISSUE THREAD

**Issue by lostall2** [ioBroker/ioBroker.zigbee#195]
Hallo,
In the „Friendly Project“ zigbee2mqtt there is already the Adapter called Bitron AV2010/25. Can you also transfer this to ioBroker.zigbee?

https://www.zigbee2mqtt.io/information/supported_devices.html

Thank you

**Comment by asgothian** [comment]
Should be done in pull request #198

**Comment by lostall2** [comment]
Thank you @asgothian , works fine
