### ISSUE TITLE
Sonoff Curtain motor

### ISSUE THREAD

**Issue by SushyB** [ioBroker/ioBroker.zigbee#1950]
I got the curtain motor from Sonoff. But unfortunately this is not yet supported. Maybe someone can take care of it. Thank you very much and greetings from Germany.

modelZigbee:ZBCurtain
type:EndDevice
nwk:21227
manuf id:4742
manufacturer:SONOFF
power:Mains (single phase)
hard version:0
zcl version:3
date code:20221110
build:2.0.7
interviewed:false
configured:false

endpoint:1
profile:260
input clusters:genBasic (0)
genPowerCfg (1)
genIdentify (3)
genGroups (4)
genOnOff (6)
genLevelCtrl (8)
closuresWindowCovering (258)
genPollCtrl (32)
64599
output clusters:genIdentify (3)
genOta (25)

**Comment by arteck** [comment]
works in 1.9.1
