### ISSUE TITLE
New Device INNR SP 240-2 , smart switch

### ISSUE THREAD

**Issue by SpecWing** [ioBroker/ioBroker.zigbee#1951]
Hallo, 
vielen Dank für die ganze Arbeit, der Adapter läuft super!
Könnte bitte noch ein Smart Switch von INNR dazugefügt werden? 
Vielen Dank!
![INNR SP240-2](https://github.com/ioBroker/ioBroker.zigbee/assets/59529428/bb4472c6-5a92-4d85-a00a-2b1ba04e2cf5)

**Comment by ECP-Black** [comment]
Würde mich da auch anschließen ;)

**Comment by KL1801** [comment]
Hallo,

Ich schließe mich da auch an... Habe gerade 2 Steckdosen geliefert bekommen, aber ich kann sie leider noch nicht richtig einbinden...

**Comment by KQuitscho** [comment]
Hallo, 
Ich habe auch 2 gekauft und würde mich ebenfalls freuen

**Comment by arteck** [comment]
work in 1.9.1
