### ISSUE TITLE
IKEA LED2104R3 TRADFRI bulb GU10 WW 345lm8

### ISSUE THREAD

**Issue by martassi** [ioBroker/ioBroker.zigbee#1952]
Please add the IKEA TRADFRI bulb GU10    LED2104R3:

    modelZigbee: TRADFRI bulb GU10 WW 345lm8
    type:Router
    nwk:18663
    manuf id:4476
    manufacturer:IKEA of Sweden
    power:Mains (single phase)
    app version:1
    hard version:1
    zcl version:8
    stack version:113
    date code:20230406
    build:1.0.25
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    touchlink (4096)
    64636
    output clusters:genOta (25)

    endpoint:242
    profile:41440
    input clusters:greenPower (33)
    output clusters:greenPower (33)

**Comment by martassi** [comment]
I've found a solution in #1913 . Please update the adapter

**Comment by arteck** [comment]
works in 1.9.1
