### ISSUE TITLE
innr zigbee led stripe error

### ISSUE THREAD

**Issue by denjo1982** [ioBroker/ioBroker.zigbee#1953]
Hallo bekomme immer diesen error bei den LED stripe

innr Zigbee LED Strip, 4m, Color, Kompatibel mit Philips Hue, Alexa, Hey Google (Bridge erforderlich) Smart LED Strip 4m, RGB Lightstrip, Dimmbar, FL 142

`<html>
<body>

DeviceConfigure:Failed to DeviceConfigure.configure 0x00158d0004ae481d FL 142 C (TypeError: Cannot read properties of undefined (reading 'configure') at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:37) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:113:21))
--

</body>
</html>`

**Comment by arteck** [comment]
so lange pairen bis der sich meldet. und kein undefined im log steht
