### ISSUE TITLE
Error Configure - Mi Lichtsensor

### ISSUE THREAD

**Issue by Day1983** [ioBroker/ioBroker.zigbee#1955]
Hallo,

kann leider den Lichtsensor nicht mehr pairen... 
Pairing startet, new devices wird gefunden - erst steht beim Pairing alles okay, dann kommt das:

<DeviceConfigure:Failed to DeviceConfigure.configure 0x04cf8cdf3c7cf4d0 lumi.sen_ill.mgl01 (Error: Bind 0x04cf8cdf3c7cf4d0/1 msIlluminanceMeasurement from '0x00124b00219fbf5d/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))>

![Screenshot 2023-11-25 192322](https://github.com/ioBroker/ioBroker.zigbee/assets/77491820/58f70bc3-9fdc-486d-ad43-896198940bab)

**Comment by arteck** [comment]
check 19.1
