### ISSUE TITLE
PIR ZP01 fehlerhaft

### ISSUE THREAD

**Issue by Flash7813** [ioBroker/ioBroker.zigbee#1957]
Hallo, 
Dieser PIR wird falsch eingebunden. 
Es ist dieses Gerät: 
https://www.zigbee2mqtt.io/devices/ZP01.html

wird folgendermaßen erkannt: 

    modelZigbee:TS0202
    type:EndDevice
    nwk:27279
    manuf id:4417
    manufacturer:_TZ3000_lf56vpxj
    power:Battery
    app version:70
    hard version:1
    zcl version:3
    stack version:0
    date code:
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genPowerCfg (1)
    ssIasZone (1280)
    genIdentify (3)
    genBasic (0)
    output clusters:touchlink (4096)
    genOnOff (6)
    genOta (25)
    genTime (10)

jedoch wird nur die Signalstärke übermittelt: 
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/152064792/5cb2ea81-642b-45f2-9d91-0e5c4cb18455)
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/152064792/ef6aeff6-464b-4797-912b-6e19ac04de1c)

Ich hoffe, diese Infos passen soweit. 

VG

**Comment by arteck** [comment]
das Bild ist doich egal.. es Meldet sich als lf56vpxj ..hauptsache es funktioniert
