### ISSUE TITLE
[New Device] innr OSP 210

### ISSUE THREAD

**Issue by unclebob1st** [ioBroker/ioBroker.zigbee#1959]
Hi,

having support for the "innr OSP 210" would be great.
(listed in [Zigbee2MQTT](https://www.zigbee2mqtt.io/devices/OSP_210.html))

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/37108983/2c511265-1557-4e15-8516-9d8460bca85b)

here as text:

    modelZigbee:OSP 210
    type:Router
    nwk:54171
    manuf id:4454
    manufacturer:innr
    power:Mains (single phase)
    app version:17
    hard version:1
    zcl version:8
    stack version:54
    date code:20230615
    build:1.1.0
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    touchlink (4096)
    genLevelCtrl (8)
    output clusters:genTime (10)
    genOta (25)

    endpoint:242
    profile:41440
    output clusters:greenPower (33)

**Comment by arteck** [comment]
install GIT version
