### ISSUE TITLE
No connection to host after kernel update

### ISSUE THREAD

**Issue by maxpd1** [ioBroker/ioBroker.zigbee#196]
Hi,

I use this adapter on a Pi3+

`sudo apt update && sudo apt upgrade
sudo rpi-update`

After an update of the kernel, I don't get a connection to the host anymore. Also not with the newest version of this adapter.

**Comment by maxpd1** [comment]
Error in log:


host.raspberrypi | 2019-02-15 22:06:39.186 | error | instance system.adapter.zigbee.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-02-15 22:06:39.186 | error | by controller[0]: at Object.Module._extensions..js (module.js:663:10)
Caught | 2019-02-15 22:06:39.186 | error | by controller[0]: at Module._compile (module.js:652:30)
Caught | 2019-02-15 22:06:39.186 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
Caught | 2019-02-15 22:06:39.186 | error | by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
Caught | 2019-02-15 22:06:39.186 | error | by controller[0]: at require (internal/module.js:11:18)
Caught | 2019-02-15 22:06:39.185 | error | by controller[0]: at Module.require (module.js:596:17)
Caught | 2019-02-15 22:06:39.185 | error | by controller[0]: at Function.Module._load (module.js:497:3)
Caught | 2019-02-15 22:06:39.185 | error | by controller[0]: at tryModuleLoad (module.js:505:12)
Caught | 2019-02-15 22:06:39.185 | error | by controller[0]: at Module.load (module.js:565:32)
Caught | 2019-02-15 22:06:39.185 | error | by controller[0]: at Object.Module._extensions..node (module.js:681:18)
Caught | 2019-02-15 22:06:39.185 | error | by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
Caught | 2019-02-15 22:06:39.184 | error | by controller[0]: NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
Caught | 2019-02-15 22:06:39.184 | error | by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
Caught | 2019-02-15 22:06:39.184 | error | by controller[0]: was compiled against a different Node.js version using
Caught | 2019-02-15 22:06:39.184 | error | by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
Caught | 2019-02-15 22:06:39.184 | error | by controller[0]: ^
Caught | 2019-02-15 22:06:39.184 | error | by controller[0]: throw e
Caught | 2019-02-15 22:06:39.183 | error | by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88

**Comment by kirovilya** [comment]
You need do `npm rebuild` in adapter folder

**Comment by maxpd1** [comment]
thank you kirovilya. "in adapter folder" was the keyword. 
npm rebuild didn't work but npm install in /iobroker.zigbee was the solution.
