### ISSUE TITLE
Unterschiedliche Handhabung der Werte/Eigenschaft zwischen Phoscon und Zigbee

### ISSUE THREAD

**Issue by Backes89** [ioBroker/ioBroker.zigbee#1961]
Guten Morgen,

da ich von Phoscon komme wollte ich den nativen Zigbee Adapter in ioBroker ausprobieren welcher mir auf Anhieb gut gefällt. Allerdings wurden die Werte über den deconz-Adapter aus Phoscon immer ohne die Eigenschaft gelesen was beim zigbee Adapter nicht so ist.

Bsp.:
Luftfeuchtigkeit Aquara Sensor
Phoscon: "44.78"
ioBroker.zigbee: "44.78 %"

Temperatur Aqara Sensor
Phoscon: "21"
ioBroker.zigbee: "21 °C"

Im zigbee Adapter sind immer die Eigenschaften der Werte um was es sich handelt mit im value. Unschön wenn man auf nullwerte prüfen will im history-Adapter und er dies nicht erkennt weil die Eigenschaft im value dahinter steht.

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/31594459/c7bc7f16-8cb5-438b-b23f-ffad438d87dd)

Ist dies ein Bug? Gibt es eine Einstellungsmöglichkeit hierfür die Eigenschaft abzuschalten im zigbee-Adapter?

**Comment by arteck** [comment]
es ist kein BUG ..der DP wird so angelegt da hast du kein Einfluss drauf.. ausserdem sole Fragen bitte im Forum...
