### ISSUE TITLE
[New Device] IKEA LED2106R3 TRADFRI bulb GU10 345lm

### ISSUE THREAD

**Issue by KBNSX** [ioBroker/ioBroker.zigbee#1962]
Please add the IKEA TRADFRI bulb GU10 LED2106R3:

modelZigbee:TRADFRI bulb GU10 WS 345lm
type:Router
nwk:37336
manuf id:4476
manufacturer:IKEA of Sweden
power:Mains (single phase)
app version:17
hard version:1
zcl version:8
stack version:106
date code:20230425
build:1.1.20
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
lightingColorCtrl (768)
touchlink (4096)
64599
64636
output clusters:genOta (25)
endpoint:242
profile:41440
input clusters:greenPower (33)
output clusters:greenPower (33)

**Comment by KBNSX** [comment]
works fine with follwing changes in 

- device.js:
    {
        models: ['LED2106R3'],
        icon: 'img/ikea_gu10.png',
        states: lightStatesWithColortemp,
        linkedStates: [comb.brightnessAndState],
    },
- ikea.js:
    {
        zigbeeModel: ['TRADFRI bulb GU10 WS 345lm'],
        model: 'LED2106R3',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum',
        extend: tradfriExtend.light_onoff_brightness_colortemp(),
    },

**Comment by arteck** [comment]
works in 1.9.1
