### ISSUE TITLE
[New Device] Flair Viyu E27 (VIYU_A60_806_CCT_10454469)

### ISSUE THREAD

**Issue by KBNSX** [ioBroker/ioBroker.zigbee#1963]
Please add this device (sold by Hornbach):

modelZigbee:VIYU_A60_806_CCT_10454469
type:Router
nwk:31320
manuf id:4709
manufacturer:HORNBACH Baumarkt AG
power:Mains (single phase)
app version:2
hard version:1
zcl version:8
stack version:1
date code:20221114
build:2.04.00
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
lightingColorCtrl (768)
touchlink (4096)
64599
heimanSpecificInfraRedRemote (64642)
output clusters:genOta (25)
endpoint:242
profile:41440
output clusters:greenPower (33)

**Comment by KBNSX** [comment]
Works fine with following changes in 

- device.js:
    {
        models: ['10454469'],
        icon: 'img/flair_viyu_e14_candle.png',
        states: lightStatesWithColortemp,
        syncStates: [sync.brightness],
    },

- hornbach.js:
    {
        zigbeeModel: ['VIYU_A60_806_CCT_10454469'],
        model: '10454469',
        vendor: 'HORNBACH',
        description: 'FLAIR Viyu Smart LED bulb E27',
        extend: extend_1.default.light_onoff_brightness_colortemp({ colorTempRange: [153, 370] }),
    },

**Comment by arteck** [comment]
works in 1.9.1
