### ISSUE TITLE
[New Device] Linptech Presence Sensor ES1 (TS0225__TZ3218_awarhusb)

### ISSUE THREAD

**Issue by Bibo13** [ioBroker/ioBroker.zigbee#1964]
My zigbee adapter version is 1.8.24. 

Please add the new Device. The Sensor is already contained in zigbee2mqtt device index.
I try`d it several times but it seems he is not in the zigbee definitions. Maybe to new.

Successfully interviewed '0xb43522fffe122488', device has successfully been paired

Device 0xb43522fffe122488 "TS0225" not described in statesMapping.
Device '0xb43522fffe122488' announced itself
 Starting interview of '0xb43522fffe122488'

Geräteinformation

 modelZigbee:TS0225
    type:Router
    nwk:53206
    manuf id:4098
    manufacturer:_TZ3218_awarhusb
    power:Mains (single phase)
    app version:69
    hard version:1
    zcl version:3
    stack version:1
    date code:
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genScenes (5)
    manuSpecificTuya_2 (57346)
    16384
    manuSpecificTuya (61184)
    ssIasZone (1280)
    output clusters:genTime (10)
    genOta (25)

Thanks

**Comment by arteck** [comment]
works in 1.9.1
