### ISSUE TITLE
Xiaomi  Converting the LYWSD03MMC to Zigbee 3.0

### ISSUE THREAD

**Issue by bear1180** [ioBroker/ioBroker.zigbee#1971]
Hi i flashed one of my  Xiaomi Bluetooth LYWSD03MMC to Zigbee 3.0 but why does it Not work with the zigbee Adapter. It seems that the zigbee2mqtt Adapter ist able to handle the Hardware. But i do Not what to use an other Adapter. Is my Installation the Problem?
![Screenshot_2023-12-03-20-39-53-024_com android chrome~2](https://github.com/ioBroker/ioBroker.zigbee/assets/38736100/f3019a74-eb7c-4a07-a37f-6a9962213431)

**Comment by Schwemm** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/1929

**Comment by bear1180** [comment]
But how can i use it with the zigbee Adapter. I dont want to use the zigbee2mqtt Adapter.

**Comment by Schwemm** [comment]
We have to wait for an official update of the zigbee adapter in which the new repo of the zigbee-herdsman-converter is referenced.
