### ISSUE TITLE
[Nous A1Z] Possible to increase update frequency for power measurement?

### ISSUE THREAD

**Issue by Fumanshu183** [ioBroker/ioBroker.zigbee#1974]
Hello,
I have purchased several smart plugs of type "A1Z" from vendor "Nous" and successfully added them to the Zigbee adapter.
Everything is working, but unfortunately there is a big delay for the updates of ioBroker object values for the power measurement.

Is there a way to adapt the update frequency for the power measurement?

Thanks and best regards

**Comment by arteck** [comment]
> Is there a way to adapt the update frequency for the power measurement?

use device_query DP for measurement request
