### ISSUE TITLE
QBKG41LM - lumi.switch.b2nc01 - Xiaomi Aqara Wall Switch - Objects are not updated

### ISSUE THREAD

**Issue by schneiderst** [ioBroker/ioBroker.zigbee#1976]
My new wall switch does not send any object update (pressing left or right button) besides signal "link quality" and "presence".

I've tried different versions of ziegbee adapter, no change.
I've tried to exclude in adapter settings, no change.
I've tried to reset the switch, no change.
I've tried to restart the adapter, no change.

Using Developer tab I can manually read the status of the relays:
{
    "devId": "zigbee.0.54ef4410007f1d42",
    "ep": "1",
    "cid": "genOnOff",
    "cmd": "read",
    "cmdType": "foundation",
    "zclData": {
        "onOff": {}
    },
    "cfg": null
} 

"single_left", "double_left", etc. don't update ever "(NULL)"

_Originally posted by @schneiderst in https://github.com/ioBroker/ioBroker.zigbee/issues/1586#issuecomment-1839474064_

**Comment by arteck** [comment]
check 1.9.1 and also new DP in tree

**Comment by schneiderst** [comment]
Thank you very much!! Working now!! 

PS: For visitors - I hat to update my controller with latest update of firmware, too!
