### ISSUE TITLE
Verliert Netzwerkverbindung

### ISSUE THREAD

**Issue by wschiro** [ioBroker/ioBroker.zigbee#1978]
Ich nutze seit 10 Monaten den zigbee-adapter für meine MoesHK-Ventile.
Installation pairing alles ohne Probleme. Steuern der Geräte funktioniert auch einwandfrei.
Nur: nach einiger Zeit verliert irgendeine Komponente die Verbindung.
Neustart des Adapters: kein Effekt
Neustart IOB: kein Effekt
Neustart raspi: alles wieder ok
Hat jemand eine Idee?
Hab einen cronjob angelegt, der täglich einen Neustart des Raspi 4 macht. Damit komme ich erstmal über die Runden

**Comment by Ilovegym66** [comment]
Verbindung verlieren kommt meist von schlechten Batterien oder Stoerungen des Signals, also dann mal schauen, dass man den Kanal wechselt (entweder Wifi oder Zigbee)..

**Comment by wschiro** [comment]
Bei  der Installation hab ich schon aufgepasst, zigbeekanal ist 25 WLAN 11. Ein adapterproblem ist es sicher nicht.  Ich habe den zigbeeconzentrator mit Antenne in Einsatz und noch den Router wg001. Die Signalstärke ist überall min 70 %.
Manchmal wird die Temperaturübermittlung mit einem Fehler im Protokoll quittiert. Aber wenn die Temperaturübermittlung ohne Fehler quittiert wird, heisst das nicht, dass diese auch am HK angekommen ist. 
Ich habe den CC2531 im Verdacht, denn nur nach einem Neustart des raspi funktioniert wieder alles, ohne erneutes pairing.
Zwischen einem HK und dem conzentrator ist ein Abstand von 1m, da läuft der Signalpfad auch nicht über den Router, sondern direkt. Also scheidet m.E. der Router als Fehlerquelle aus.
Welcher Hersteller von CC2531 wäre denn zu empfehlen?

**Comment by arteck** [comment]
schau im Forum bitte nach
