### ISSUE TITLE
[New Device] Onenuo ZigBee Motion Sensor 808EZ

### ISSUE THREAD

**Issue by Backes89** [ioBroker/ioBroker.zigbee#1981]
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/31594459/bbe25659-741f-4d80-9d8a-a6cda479c6c5)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/31594459/961fcbaf-b243-4b9f-b3cc-5e1cc217e19c)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/31594459/44b30b57-a73b-4dd7-b456-6dfe6d0c7354)

Device is not round. It is rectengular.

**Comment by arteck** [comment]
works in 1.9.1
