### ISSUE TITLE
Load power missing with Aqara Single Switch Module T1 (With Neutral)

### ISSUE THREAD

**Issue by 4n3tcqCkckaRFn** [ioBroker/ioBroker.zigbee#1982]
Hi guys,

I have an issue with the Aqara Single Switch Module T1 (With Neutral), I don't get the measurements from the device. 
Device is also added into the exclusions.

Can someone help me?
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/38347117/b528b0b1-171e-4e82-ab05-75bfb333a281)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/38347117/dc70f3b9-8a71-4e57-bb4f-e53d847ddee1)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/38347117/6233581c-ba85-43a5-ac2f-b673a61aa5b9)

Cheers
psy_k

**Comment by arteck** [comment]
click DP device_query
