### ISSUE TITLE
new device Ikea Ormanäs

### ISSUE THREAD

**Issue by KBNSX** [ioBroker/ioBroker.zigbee#1984]
modelZigbee:ORMANAS LED Strip
    type:Router
    nwk:13915
    manuf id:4476
    manufacturer:IKEA of Sweden
    power:Mains (single phase)
    app version:17
    hard version:1
    zcl version:8
    stack version:106
    date code:20230512
    build:1.1.10
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    lightingColorCtrl (768)
    touchlink (4096)
    64599
    output clusters:genOta (25)

    endpoint:242
    profile:41440
    input clusters:greenPower (33)
    output clusters:greenPower (33)

**Comment by KBNSX** [comment]
I didn't find any solution I could make in device.js and ikea.js to make it work somehow.

**Comment by arteck** [comment]
works in 1.9.1
