### ISSUE TITLE
Zigbee New Human precence Sensor Model YXZBRB58

### ISSUE THREAD

**Issue by Axklein** [ioBroker/ioBroker.zigbee#1985]
I bought a human precense sensor with the same model number from ALI-Express about 5 weeks ago. I was also able to train the sensor on the Zigbee stick without any problems.
Then I ordered the same sensor again. Externally the packaging is identical to the data. However, when learning the stick, a model TS0601 is displayed. But that doesn't work.
I'm not sure if this is a software problem or a hardware problem.
![Unbenannt](https://github.com/ioBroker/ioBroker.zigbee/assets/47086339/41043362-60d3-45cb-834b-e7487619b8e7)

Geräteinformation

modelZigbee:TS0601
type:Router
nwk:15083
manuf id:4417
manufacturer:_TZE204_oqtpvx51
power:Mains (single phase)
app version:74
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
genBasic (0)
output clusters:genOta (25)
genTime (10)
endpoint:242
profile:41440
output clusters:greenPower (33)

**Comment by arteck** [comment]
works in 1.9.1

**Comment by Axklein** [comment]
Thank you very much for feedback

**Comment by Axklein** [comment]
After I updated to Zigbee version v1.9.7, the sensor was recognized and apparently worked. There is only a cyclical error message:

**2024-01-12 08:59:57.214 error Error while processing converters DEVICE_ID: 'a4c1383bc1bf7aba' cluster 'manuSpecificTuya' type 'commandDataReport'**

The object values will probably be written and updated anyway.
