### ISSUE TITLE
Question: Is there a way to switch coordinator hardware = zigbee stick?

### ISSUE THREAD

**Issue by easybeat** [ioBroker/ioBroker.zigbee#1989]
Hi

I'm just wondering what happens if my zigbee stick stops working? How do I move to another stick within the adapter?

I think it would be very helpful if there is some information about this in the WIKI. Could you please add this?

Kind regards

**Comment by arteck** [comment]
see iobroker forum

**Comment by easybeat** [comment]
Thanks @arteck but I think this is something which should be described in here as it is fundamental!

I've found the link: https://forum.iobroker.net/topic/68719/zigbee-vorgehen-beim-wechsel-der-kompletten-hardware/4?_=1702801515843&lang=de

So the steps are:

1. Flash the new stick with the firmware
2. shutdown zigbee adpater in ioBroker
3. remove old stick, put new stick in
4. restart adapter and wait...

I will do some tests about this and will post it here.

**Comment by easybeat** [comment]
OK I did some tests and very important is to understand that the restore function does only work with sticks of the same chipset and as I understand only with the CC2652P chipset. 

So you can't use a stick with a different chipset.
