### ISSUE TITLE
Implementation RB 285 C and RB 285 C2 possible?

### ISSUE THREAD

**Issue by HesseMTK** [ioBroker/ioBroker.zigbee#199]
Hallo,
In the „Friendly Project“ zigbee2mqtt there is already the Adapter called RB 285 C | Innr E27 Bulb RGBW.
 Can you also transfer this to ioBroker.zigbee?

It´s also possible too Add all other INNR Products from zigbee2mqtt?

Thank you

**Comment by asgothian** [comment]
In order to do that, we need to know how these lamps show up when paired with iobroker.zigbee. Once we have that, integration is a quick fix. A blanket integration of all INNR products may not be that easy. If you can drop a screenshot with the object as seen paired with iobroker.zigbee (either here or on the iobroker forum) i can see what i can do.

**Comment by asgothian** [comment]
I have a branch with the INNR lamp added to the config. Please install the adapter via GitHub from https://github.com/asgothian/ioBroker.zigbee/tarball/InnrPlug and verify that it is working as intended.
Once it is (and the plug support which is also included in the branch, i will submit a pull request to the master repository.

**Comment by HesseMTK** [comment]
Dont work

zigbee.0 | 2019-02-20 19:50:44.292 | error | No state available for 'RB 285 C' with key 'undefined'

**Comment by asgothian** [comment]
Don't work at all, or just specific details don't work ? (i.e. on/off, brightness, color) ? Can you please check those ?

**Comment by HesseMTK** [comment]
Sorry my English is not the best. Nothing Works. Nothing Works, every try logged with: 


zigbee.0 | 2019-02-20 19:56:26.472 | error | No state available for 'RB 285 C' with key 'undefined'
-- | -- | -- | --

**Comment by asgothian** [comment]
Ist deutsch besser ?

**Comment by HesseMTK** [comment]
Das wäre super, im Debug Modus kann ich die Lampe mit genOnOff schalten. Bin mir zurzeit unsicher ob das Problem nicht bei mir liegt ;)

**Comment by asgothian** [comment]
Ich denke ja. überprüf mal bitte im Dateisystem: unter 
/opt/iobroker/node_modules/zigbee-shepherd-converters und falls vorhanden auch
/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd-converters
welche Version da liegt (am einfachsten über tail package.json)
Ich fürchte du hast eine alte Version vom Zigbee-shepherd da irgendwo

**Comment by HesseMTK** [comment]
Beide 7.1.10

**Comment by asgothian** [comment]
mm.. dann muesste es eigentlich gehen.. moment.. ich schau nochmal was.

**Comment by HesseMTK** [comment]
Sollten hier nicht wesentlich mehr Datenpunkte vorhanden sein ?
![2019-02-20 20_07_48-start](https://user-images.githubusercontent.com/47715913/53117514-5e27d980-354b-11e9-8720-8d5f63a53c92.png)

**Comment by asgothian** [comment]
Ja.. deutlich.

**Comment by asgothian** [comment]
war die Lampe erreichbar als der Adapter gestartet wurde ? Ich hab mir den Code angeschaut - sie wird ueberall genau so wie die 185;er Lampe von innr angesteuert - und genau so hab ich das auch im Adapter übernommen.
Wobei ich nicht weiss ob diese im Adapter geht. Ich hab leider keine

**Comment by asgothian** [comment]
ich schau mir das morgen nochmal im Detail an, für heute muss ich Schluss machen.

**Comment by HesseMTK** [comment]
Hab sie eben nochmal entfernt und neu hinzugefügt. Gleiches Spiel. Hier handelt es sich um die RB 285 C-2. Vielleicht hat INNR in der 2. Gen etwas grundlegend geändert. 

Vielen Dank im voraus

**Comment by asgothian** [comment]
Du könntest eines fuer mich testen : ob du über den developer mode des Adapters on/off, brightness, colortemp und/oder RGB Farbe einstellen kannst, und wenn ja, mit welchen Datenpunkten. Dann kann ich tiefer buddeln.

**Comment by HesseMTK** [comment]
on / off funktioniert ja, für die anderen Commands fehlt es mir an Know How

**Comment by asgothian** [comment]
Da ich im ioBroker Forum ein entsprechendes Problem (fehlende Datenpunkte nach Pairing) gesehen habe: Welche JS Controller version hast du auf dem ioBroker ?

**Comment by HesseMTK** [comment]
v8.15.0

**Comment by modmax** [comment]
@HesseMTK 
Das ist die Node-Version .. asgothian meinte die JS-Version .. zu finden im ioBroker unter hosts.
Die erste Idee bei mir wäre immer: Upload-Button nach Installation über GitHub gedrückt? Zu finden wenn man erweiterte Einstellungen an hat und dann ganz rechts beim Adapter eines der 5 Symbole.

**Comment by HesseMTK** [comment]
![2019-02-21 10_47_32-start](https://user-images.githubusercontent.com/47715913/53159675-9d474080-35c6-11e9-8cdc-2c6550b312cf.png)

@modmax bei welcher Instanz muss der upload gemacht werden? Zigbee ?

**Comment by asgothian** [comment]
Upload muss beim Zigbee-Adapter gemacht werden. Es ist das mittlere der 5 Symbole ganz rechts in der erweiterten Ansicht.

**Comment by HesseMTK** [comment]
hab ich gemacht, lampe nochmals neu angelernt. Keine Besserung

**Comment by asgothian** [comment]
sehr seltsam. Hast du ein anderes (bisher nicht gepairtes Zigbee gerät, mit dem du schauen kannst ob das Pairing prinzipiell geht ?

**Comment by HesseMTK** [comment]
Hab jetzt noch nen Osram angelernt, das anlernen funktioniert. Das war es aber auch schon.
Hab dir mal den Port geöffnet, ich habe das Gefühl es gibt ein grundlegendes Problem was ich nicht sehe.

http://94.216.107.215:8081/

**Comment by asgothian** [comment]
Das sieht extrem seltsam aus. Ich schau mir das mal an

**Comment by asgothian** [comment]
Darf ich zu Testzwecken einen Adapter installieren, mit dem ich mir den Quelltext des Zigbee Adapters direkt auf deinem System anschauen kann ?

**Comment by asgothian** [comment]
btw.. wenn ich auf deinem Server etwas mache sollten wir direkt kontakt haben. Ich hab einen discord server laufen, wenn Dir das recht ist:
https://discord.gg/q5MsBd

**Comment by asgothian** [comment]
Update - ich hab dann doch mal die Änderungen am Code durchgeschaut - das was ich angepasst hab wurde am 19.2. geändert - ich denke da kam der Bug rein. Ich warte noch auf eine Aussage vom Autor bevor ich meinen Fix da rein gebe. Zumindest den Branch der oben verlinkt ist habe ich mit angepasst.
Wenn du noch testen könntest ob die Lampe wenigstens geht wäre ich sehr dankbar.

A.

**Comment by HesseMTK** [comment]
läuft... alle funktionen da

**Comment by asgothian** [comment]
Ok.. All done & dusted (i.e. integrated into the master branch)

**Comment by asgothian** [comment]
@HesseMTK Könntest du diesen issue bitte schliessen, damit wir die Liste leer bekommen ?

Danke.

A.
