### ISSUE TITLE
ZigBee Adapter crashes 2-3 times a day

### ISSUE THREAD

**Issue by LittleNo** [ioBroker/ioBroker.zigbee#1991]
I'm using this hardware: https://zig-star.com/projects/zigbee-gw-lan/ CC2652P over TCP. Everything worked fine for over a year, until I added two innr devices (power sockets). Since that point, the adapter crashes 2-3 times a day. When this happens, my ioBroker VM is running on 100% CPU&RAM (it's running on ESXI with 4 CPUs and 8GB of RAM) and it's flooding the log:

[iobroker.2023-12-17.log](https://github.com/ioBroker/ioBroker.zigbee/files/13695800/iobroker.2023-12-17.log)

Restarting the ZigBee-Adapter brings it back to life, until the next crash.

From the log I can see different problems, however, nothing that gives me a hint for the reason.

**Comment by arteck** [comment]
` Starting zigbee-herdsman problem : "Error while opening socket"`

here is you problem.... i think the lan device is offline..

**Comment by LittleNo** [comment]
I don't think so. For testing, I gave the VM 16GB of RAM, it didn't crash since then. That wouldn't have helped if the LAN Device is the culprit.

And even if the LAN Device is down for a second, why can't the ZigBee-Adapter just re-connect when it's back available?
