### ISSUE TITLE
Philips HUe white lässt sich nicht Dimmen

### ISSUE THREAD

**Issue by MaJaWe1975** [ioBroker/ioBroker.zigbee#1993]
zigbee 1.8.24
NPM 10.2.3
Node.js v18.19.0
js-controller 5.0.17

Philips Hue white & color lässt sich nicht mehr dimmen. In der Version 1.8.10 funktionierte es noch !!!

**Comment by MaJaWe1975** [comment]
![zigbee](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/9e1fea12-8d56-437a-bb71-de31843c54ee)

error: failed with no error code (undefined)

**Comment by arteck** [comment]
check GIT version

**Comment by MaJaWe1975** [comment]
das gleiche Problem mit 1.9.0

**Comment by MaJaWe1975** [comment]
gleiche Problem mit der 1.9.1

obwohl etwas anders, er versucht im einschaltmoment auf z.B. 100% zu dimmen fällt dann aber wieder zurück auf den wert der zuvor eingestellt war......

kein dimmen möglich !!!

**Comment by arteck** [comment]
zeigmal die info Kachel

**Comment by MaJaWe1975** [comment]
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/ebaa4eff-0b7a-4ab4-93af-a280d79c27fb)

**Comment by arteck** [comment]
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/a08b4e45-3ec9-4e69-9ccd-862bba9d3999)
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/ae00d756-5296-458c-b06b-82e9ff153d9c)

die 2 gehen..

**Comment by arteck** [comment]
also was geht genau NICHT

wenn du über Objekte state setzt oder wenn du brightness setzt
zeigmal den Obejkt Baum für die erste Lampe

**Comment by MaJaWe1975** [comment]
state funktioniert bei allen 3, aber brightness nicht, bei der 1.8.10 lief noch alles......

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/5686d630-8339-41e8-bf11-9a489947b5ef)

**Comment by arteck** [comment]
setz transtion_time auf 0

**Comment by MaJaWe1975** [comment]
das wars, D A N K E
