### ISSUE TITLE
New device support IKEA PARASOLL Door/Window Sensor

### ISSUE THREAD

**Issue by uwe5** [ioBroker/ioBroker.zigbee#1995]
Please support new IKEA PARASOLL Door/Window Sensor:

Error: Device 0x048727fffeb7e605 "PARASOLL Door/Window Sensor" not described in statesMapping.. undefined

Geräteinformation

modelZigbee:PARASOLL Door/Window Sensor
type:EndDevice
nwk:50576
manuf id:4476
manufacturer:IKEA of Sweden
power:Battery
app version:1
hard version:1
zcl version:8
stack version:113
date code:20230516
build:1.0.19
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genPowerCfg (1)
genIdentify (3)
genPollCtrl (32)
haDiagnostic (2821)
touchlink (4096)
64636
heimanSpecificAirQuality (64641)
output clusters:genIdentify (3)
genGroups (4)
genOnOff (6)
genOta (25)
touchlink (4096)
endpoint:2
profile:260
input clusters:genBasic (0)
genIdentify (3)
ssIasZone (1280)
output clusters:genIdentify (3)

Link
Koenkk [https://github.com/Koenkk/zigbee2mqtt/issues/20007](url)
info [https://www.ikea.com/se/sv/p/parasoll-doerr--foenstersensor-smart-vit-80504308/](url)

Thanks

**Comment by arteck** [comment]
works in 1.9.1

**Comment by Triox85** [comment]
Bei mir wird er auch nicht angezeigt im iOBroker (Installiert js-controller:7.0.6/Node.js: v20.18.3/NPM: 10.8.2) Zigbee-Adapter v1.10.14

model:[E2013](https://www.zigbee2mqtt.io/devices/E2013.html)
description:PARASOLL door/window sensor
modelZigbee:PARASOLL Door/Window Sensor
type:EndDevice
nwk:8861
manuf id:4476
manufacturer:IKEA of Sweden
power:Battery
app version:1
hard version:1
zcl version:8
stack version:113
date code:20230516
build:1.0.19
interviewed:true
configured:false
