### ISSUE TITLE
New device support: IKEA SOMRIG shortcut button E2211

### ISSUE THREAD

**Issue by uwe5** [ioBroker/ioBroker.zigbee#1996]
Please add new IKEA device SOMRIG shortcut button E2211
see [https://github.com/Koenkk/zigbee2mqtt/issues/20030](url)

**Comment by throstenk** [comment]
Das würde ich auch benötigen  - Danke Lg...

modelZigbee:SOMRIG shortcut button
type:EndDevice
nwk:10407
manuf id:4476
manufacturer:IKEA of Sweden
power:Battery
app version:1
hard version:1
zcl version:8
stack version:113
date code:20230308
build:1.0.20
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genPowerCfg (1)
genIdentify (3)
genGroups (4)
genPollCtrl (32)
touchlink (4096)
64636
heimanSpecificScenes (64640)
output clusters:genIdentify (3)
genGroups (4)
genOnOff (6)
genLevelCtrl (8)
genOta (25)
touchlink (4096)
heimanSpecificScenes (64640)
endpoint:2
profile:260
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
heimanSpecificScenes (64640)
output clusters:genIdentify (3)
genGroups (4)
genOnOff (6)
genLevelCtrl (8)
heimanSpecificScenes (64640)

**Comment by arteck** [comment]
works in 1.9.1

**Comment by throstenk** [comment]
Hallo Danke, der Taster wird jetzt erkannt aber ohne Funktion
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/80670170/5bfe8527-53d6-4bd3-8c8c-a39f7b5e0ffa)

**Comment by Meckiilino** [comment]
Habe hier seit ca. 1 Woche das selbe Problem...
Im Moment parse ich das json in msg_from_zigbee mit einem Blockly. Ist aber keine elegante Lösung ;-)

**Comment by arteck** [comment]
kannst die msg mal posten bitte

**Comment by Meckiilino** [comment]
Sehr gerne.

Aufgefallen ist mir noch dass bei einem langen Druck zuerst commanAction1 übertragen wird und dann commandAction2.
Das heißt die Übertragung beginnt sofort mit "commandAction1" und bei einem langen Druck wird auf "commandAction2" umentschieden...

`commandAction1 kurzer Druck
commandAction2 langer Druck
commandAction3 loslassen kurzer Druck
commandAction4 loslassen langer Druck

{"type":"commandAction1","data":{"data":0},"linkquality":204,"groupID":0,"cluster":"tradfriButton","meta":{"zclTransactionSequenceNumber":82,"manufacturerCode":4476,"frameControl":{"frameType":1,"manufacturerSpecific":true,"direction":0,"disableDefaultResponse":true,"reservedBits":0}},"endpoint_id":1}
{"type":"commandAction2","data":{"data":0},"linkquality":172,"groupID":0,"cluster":"tradfriButton","meta":{"zclTransactionSequenceNumber":77,"manufacturerCode":4476,"frameControl":{"frameType":1,"manufacturerSpecific":true,"direction":0,"disableDefaultResponse":true,"reservedBits":0}},"endpoint_id":1}
{"type":"commandAction1","data":{"data":0},"linkquality":176,"groupID":0,"cluster":"tradfriButton","meta":{"zclTransactionSequenceNumber":84,"manufacturerCode":4476,"frameControl":{"frameType":1,"manufacturerSpecific":true,"direction":0,"disableDefaultResponse":true,"reservedBits":0}},"endpoint_id":2}
{"type":"commandAction2","data":{"data":0},"linkquality":132,"groupID":0,"cluster":"tradfriButton","meta":{"zclTransactionSequenceNumber":80,"manufacturerCode":4476,"frameControl":{"frameType":1,"manufacturerSpecific":true,"direction":0,"disableDefaultResponse":true,"reservedBits":0}},"endpoint_id":2}
`

**Comment by Meckiilino** [comment]
I updated to 1.9.6 - Bug will still exist.

**Comment by mariopinayripke** [comment]
Hi!

The same here with the SOMRIG and RODRET switches. I´ve updated all switches with the IKEA gateway to the latest firmware. With the latest firmware I´ve noticed some improvements in the old TRADFRI switches.

![grafik](https://github.com/user-attachments/assets/99cb3068-5a28-4762-a7c4-39dfab9208d6)
![grafik](https://github.com/user-attachments/assets/a587b0aa-e8bd-4e93-9337-2c4561ca8887)

**Comment by vaaarg** [comment]
still does not work with 2.0.5
