### ISSUE TITLE
Gruppen werden nicht immer angezeigt

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.zigbee#1997]
Ich habe des Öfteren das Problem, dass angelegte Gruppen nicht im Dropdown beim Editieren des Geräts erscheinen.
Das Problem tritt eher sporadisch auf.

Ebenfalls gibt es die Gruppen "Kind 1 - West" und "Badezimmer Spots" gar nicht. Wieso werden diese im Dropdown angezeigt?

![Xnip2023-12-20_11-02-49](https://github.com/ioBroker/ioBroker.zigbee/assets/8231359/08e6e18f-b14d-4a98-b220-1c34906457d1)

Adapter: v1.8.24
js-controller: 5.0.14
node: 18.19.0

**Comment by arteck** [comment]
findest du die in der Auflistung ??
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/1dc0efdd-dc6a-41b3-ac28-c45e86b69b48)

**Comment by Schmakus** [comment]
Ja, dort ist die Gruppe vorhanden.

**Comment by Schmakus** [comment]
Ebenfalls zählt die Gruppennummer nicht automatisch hoch, wenn ich eine neue Gruppe erstelle.
![add group](https://github.com/ioBroker/ioBroker.zigbee/assets/8231359/7cb229c2-713a-470b-9981-423bfdb50fd2)
![groups](https://github.com/ioBroker/ioBroker.zigbee/assets/8231359/45d86d33-a04c-40e3-af4f-6da2781cf89c)

**Comment by arteck** [comment]
wenn die Gruppe nach anlgene nicht da ist dann drück F5 ..manchmal aktualisert der Browser nicht

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/b29409ee-14a4-4eee-bb65-08c4ebdae32b)

**Comment by Schmakus** [comment]
Wieso geschlossen? Das Problem ist nicht gelöst. Auch ein Aktualisieren des Browsers oder ein anderer Browser schaffen keine Abhilfe.

**Comment by Schmakus** [comment]
z.B. wir die Gruppe "Buero" nicht in den Kacheln angezeigt, obwohl diese im Objektbau vorhanden ist. Diese Gruppe kann ich für eine Lampe auch nicht auswählen.

**Comment by Schmakus** [comment]
nach Update auf 1.8.25 keine Abhilfe. Gruppe wird immer noch nicht im DropDown angezeigt.
