### ISSUE TITLE
tuya 2 gang TS0002_switch_module not working since update to 1.8.25

### ISSUE THREAD

**Issue by creativtransfer** [ioBroker/ioBroker.zigbee#1998]
Dear Developer, 

please note that something is broken in v 1.8.25 with the Tuya 2 gang Zigbee Switch.
My module identifies itself as this one:    tuya.whitelabel('Nous', 'L13Z', '2 gang switch', ['_TZ3000_ruxexjfz']),
and since the update it does not work:

> error: zigbee.0 (929103) Send command to 0xa4c138bxxxxxxxxx failed with no error code (undefined)

Downgrading to the previous version (.24) solved the issue for now. 

Best Regards, 

dk

**Comment by Guest124** [comment]
The same behavior with the Xiaomi LLKZMK11LM relay. The command is not sent, the same error is displayed. The channel state comes and is processed without problems

**Comment by arteck** [comment]
check GIT version

**Comment by creativtransfer** [comment]
Dear artek, 
thank you very much. I just installed the latest version 1.9 from git and the issue with these 2 gang switches is solved.
On the other hand, I am getting these errors in the log now and have no idea where they are coming from:
`...
zigbee.0
	2023-12-22 15:22:25.676	error	Error while processing converters: 'TypeError: Cannot read properties of undefined (reading 'state')'
zigbee.0
	2023-12-22 15:22:14.365	error	Error while processing converters: 'TypeError: Cannot read properties of undefined (reading 'state')'
...`


Best Regards, 

dk

**Comment by creativtransfer** [comment]
Jetzt behoben in v1.91 

Vielen lieben Dank!
