### ISSUE TITLE
Nach Update auf neueste Beta ...

### ISSUE THREAD

**Issue by vaaarg** [ioBroker/ioBroker.zigbee#1999]
Nach Upgrade auf die neueste Beta gingen die Probleme los. Alle nicht batteriebetriebenen Geräte offline.
Nach Downgrade gibts immernoch massive lags und immer wieder Fehlermeldungen.

Bin recht ratlos wie ich das fixen könnte.

type:zStack30x
version:2-2.2.7.2.
revision:20200211
port:/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00

`Error: Failed to open the network: Error: SREQ '--> AF - dataRequestExt - {"dstaddrmode":2,"dstaddr":"0x000000000000fffd","destendpoint":242,"dstpanid":0,"srcendpoint":242,"clusterid":33,"transid":242,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[25,80,2,11,254,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)')
    at Object.func (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27)
    at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32). undefined
Pairing started 

`<html>
<body>

zigbee.0 | 2023-12-21 05:45:25.065 | error | Failed to open the network: Error: SREQ '--> AF - dataRequestExt - {"dstaddrmode":2,"dstaddr":"0x000000000000fffd","destendpoint":242,"dstpanid":0,"srcendpoint":242,"clusterid":33,"transid":242,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[25,80,2,11,254,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)') at Object.func (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
-- | -- | -- | --
zigbee.0 | 2023-12-21 05:45:25.045 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2023-12-21 05:45:23.874 | info | List of port: [{"path":"/dev/ttyACM0","manufacturer":"Texas Instruments","pnpId":"usb-Texas_Instruments_CC2538_USB_CDC-if00","vendorId":"0451","productId":"16c8"},{"path":"/dev/ttyS0"},{"path":"/dev/ttyAMA0"}]
zigbee.0 | 2023-12-21 05:38:50.456 | error | Send command to 0xa4c1384cb03e7989 failed with no error code (SREQ '--> AF - dataRequest - {"dstaddr":47184,"destendpoint":1,"srcendpoint":1,"clusterid":6,"transid":209,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,76,1]}}' failed with status '(0x10: MEM_ERROR)
zigbee.0 | 2023-12-21 05:38:48.450 | error | Error 26 on send command to 0xa4c1384cb03e7989. Error: Error: Command 0xa4c1384cb03e7989/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no resources' (26)) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
zigbee.0 | 2023-12-21 05:38:40.301 | error | Send command to 0x00178801031179a4 failed with no error code (Timeout - 39720 - 11 - 74 - 6 - 11 after 10000ms)
zigbee.0 | 2023-12-21 05:38:12.372 | error | Error 26 on send command to 0x00178801031179a4. Error: Error: Command 0x00178801031179a4/11 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no resources' (26)) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
zigbee.0 | 2023-12-21 05:30:26.595 | warn | unread brightness change for group members ["0x00158d0002eea789"]
zigbee.0 | 2023-12-21 05:30:23.269 | error | Send command to 0xa4c1384cb03e7989 failed with no error code (SREQ '--> AF - dataRequest - {"dstaddr":47184,"destendpoint":1,"srcendpoint":1,"clusterid":6,"transid":155,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,55,1]}}' failed with status '(0x10: MEM_ERROR)
zigbee.0 | 2023-12-21 04:48:25.025 | error | Error 26 on send command to 0x00178801031179a4. Error: Error: Command 0x00178801031179a4/11 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no resources' (26)) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
zigbee.0 | 2023-12-21 04:47:57.371 | warn | DeviceAvailability:Stopping to ping 0x84fd27fffe3b3357 01MINIZB after 16 ping attempts
zigbee.0 | 2023-12-21 04:42:30.999 | warn | DeviceAvailability:Failed to ping 0x04cf8cdf3c7b19cc lumi.plug.mmeu01
zigbee.0 | 2023-12-21 04:39:22.394 | warn | DeviceAvailability:Stopping to ping 0x84fd27fffe3b1606 01MINIZB after 30 ping attempts
zigbee.0 | 2023-12-21 03:07:16.094 | error | Error 26 on send command to 0x00178801031179a4. Error: Error: Command 0x00178801031179a4/11 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no resources' (26)) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

</body>
</html>`

**Comment by arteck** [comment]
` failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)')`

das ist dein Problem... 
nimm den mal vom strom ..

**Comment by arteck** [comment]
und installier 1.9.1

**Comment by vaaarg** [comment]
Alles klar danke ich musste ein älteres Backup einspielen und hatte dann noch einiges an Problemen heute morgen war aber auch wieder irgendeine error Meldung...ich muss das nach den feiertagen mal anschauen.
