### ISSUE TITLE
bulb auto on when brightness value > 1

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#2]
auto switch the bulb to on when brightness value > 1

we can use with this setting iobroker widgets

**Comment by kirovilya** [comment]
this is possible. will code later

**Comment by kirovilya** [comment]
Try update from this repo.
If it working - will release version.

**Comment by arteck** [comment]
with hue bulb level.dimmer dont work..sry

**Comment by kirovilya** [comment]
hmm... what's wrong...
run adapter in debug log level and put logs here

**Comment by arteck** [comment]
now works.... hmm..after restart..
