### ISSUE TITLE
battery stat from xiaomi

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#20]
can you check the xiaomi battery handling. my sensoers and switsches has wrong batt percent
![grafik](https://user-images.githubusercontent.com/6681528/42489434-3dcc3894-840b-11e8-9129-7f2239857ae5.png)

battery was removed and replaced.. same result

**Comment by kirovilya** [comment]
It come from min/max interval https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L12
and linear conversion of the current voltage https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L19
Look at the sensor voltage and understand how the percentage depends.

The question about the min and max value has already been discussed and so far we have stopped on this interval.

**Comment by arteck** [comment]
i think the problem is a different value from xiaomi and other devices
here 

const battery3V = {
    min: 2700,
    max: 3000,
};

all my devices has a percentage value 100 .. this is wrong..

**Comment by arteck** [comment]
my problem is not the voltage .. the percentage is wrong

**Comment by GermanBluefox** [comment]
I understand, but what the voltage deliver YOUR devices, if you think the percentage is wrong?

**Comment by arteck** [comment]
3012

**Comment by GermanBluefox** [comment]
And why you think that 100% is wrong? 
Elsewise can you suggest your formula? I have done long time ago the percent calculation and it was devil complex, because the ratio of the voltage and percents is not constant.

**Comment by arteck** [comment]
check this : connect one battery device with a xioami gateway .... look for percentage battery..
now disconnect this and connect it with USB-Stick.. what can you see ??
