### ISSUE TITLE
Conbee III v1.8.25 Xiaomi WXKG01LM

### ISSUE THREAD

**Issue by NinjaTurtle85** [ioBroker/ioBroker.zigbee#2003]
Hallo zusammen,
Ich hab mir den neuen Conbee3 zugelegt, mit einer Test Instanz v1.8.25 auf zum laufen bekommen.
Nur bekomme ich die alten Taster von Xiaomi WXKG01LM [https://www.zigbee2mqtt.io/devices/WXKG01LM.html](url) zwar verbunden aber ich bekomme keine rückmeldungen für die klicks. 
Man sieht in den Objekten das das er die Link quality aktualliesiert aber der rest bleibt auf NULL. Ich habs auch schon mit ausschließen versucht aber ohne erfolg.

**Comment by arteck** [comment]
wird noch nicht unterstützt
