### ISSUE TITLE
Seit Update 1.9.1 Fehlermeldung "not described in statesMapping" bei mehreren Geräten

### ISSUE THREAD

**Issue by DerDom2010** [ioBroker/ioBroker.zigbee#2004]
Hallo,

seit dem 1.9.1 Update ( ich war vorher auf der Version 1.8.4 ) kommt beim Start des Zigbee Adapters folgende Fehlermeldung:

`Device 0xa4c138c7a6b7815f "809WZT" not described in statesMapping.
Device 0xa4c1388e3c4aa50a "809WZT" not described in statesMapping.
Device 0xa4c1382b778d6c1c "809WZT" not described in statesMapping.
Device 0xa4c13899a7258bda "TS0207_water_leak_detector" not described in statesMapping.
Device 0xa4c138709229a432 "TS0207_water_leak_detector_2" not described in statesMapping.`

Außerdem werden die oben stehenden Geräte in der Übersicht mit einem Fragezeichen angezeigt.
In der Version 1.8.4 passierte dieses nicht.

Dieses ist einer der Sensoren als Beispiel

`model:[809WZT](https://www.zigbee2mqtt.io/devices/809WZT.html)
description:Motion sensor
modelZigbee:TS0202
type:EndDevice
nwk:23352
manuf id:4417
manufacturer:_TZ3040_bb6xaihh
power:Battery
app version:72
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false`

Viele Grüße und schöne Feiertage aus dem Sauerland

**Comment by arteck** [comment]
da scheiunt es ein bug im Converter zu geben... geh erstmal auf die alte Version zurück

**Comment by DerDom2010** [comment]
Alles Klar, danke für die Info.

Falls weitere Daten benötigt werden, einfach melden.

Schöne Weihnachten

**Comment by arteck** [comment]
schaumal die GIT version jetzt

**Comment by DerDom2010** [comment]
Sieht gut aus mit der 1.9.2
Keine Fehlermeldung mehr und die "?" sind auch in der Übersicht verschwunden.

Ich werde die nächsten Tage teste.

Schon mal vielen Dank für Deine Arbeit trotz der Feuertage
