### ISSUE TITLE
Adapter stürzt ab wenn angemeldete Lampe Strom bekommt

### ISSUE THREAD

**Issue by Homezecke** [ioBroker/ioBroker.zigbee#2005]
Seit Version 1.8.25 stürzt der Adapter ab, sobald ein Gerät, wenn es stromlos war sich nach Stromzufuhr wieder anmeldet. Jedenfalls kann ich dies bei Ikea Tradfri Lampen beobachten.

zStack3x0, Zigbee 3.0 CC2652P Dongle Plus

**Comment by arteck** [comment]
ist bekannt
