### ISSUE TITLE
Seit stable Version 1.8.25 ............ not described in statesMapping.

### ISSUE THREAD

**Issue by weindler** [ioBroker/ioBroker.zigbee#2007]
Hi, heute kam das Update von 1.8.24 auf 1.8.25

Ein Gerät wurde nicht erkannt und blieb dann als Fragezeichen zurück.

`<html><body>

  | Device 0xa4c13847256ad37c "TS0207_water_leak_detector" not described in statesMapping.
-- | --

</body>
</html>`

Node.js: v18.19.0
NPM: 10.2.3
js controller 5.0.17

Bin wieder auf die 1.8.24 zurück, da wird das gerät erkannt.

Gerät:

https://www.zigbee2mqtt.io/devices/TS0207_water_leak_detector.html

Wenn du weitere Logs brauchst bitte melden. Danke

**Comment by skroob** [comment]
Bei mir was änliches mit folgendem Gerät:

![2023-12-25_092106](https://github.com/ioBroker/ioBroker.zigbee/assets/17686871/7a99d03e-f331-4549-b3df-88cddee2af10)

Es wird erkannt aber funktioniert nicht. Switches werden nicht ans Gerät gemeldet. Keine Error-Meldung im Log gefunden.

Node.js: v18.19.0
NPM: 10.2.3
js Controller: 5.0.17

Auch wieder auf die 1.8.24 zurück, alles wieder fein.

**Comment by arteck** [comment]
installier mal die GIT version

**Comment by skroob** [comment]
Alles klar und wurde erledigt.
![2023-12-25_105350](https://github.com/ioBroker/ioBroker.zigbee/assets/17686871/826cf0f6-2d7b-4505-b5fd-15552ff21065)

Der TS0112 funktioniert mit dieser Version wieder. Alles andere im Momen auch. Sehe ausser der Warnung: 
| warn | Extended PAN ID is reversed
die ich aber bereits seit einigen Versionen schon habe, keine anderen Meldungen im Log. 

Ich belasse die Version mal und melde mich wieder wenn ich bisl mit rumgespielt habe. 

Dankeschön und fröhliche Rest-Weihnachten!
