### ISSUE TITLE
HG06338 doesn't working after last update

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.zigbee#2010]
After last update HG06338 isn't working. Step back to 1.8.24 it is working again

**Comment by miriammichael** [comment]
Same by me, with Step back to 1.8.24 it works

**Comment by ahnungsbefreit** [comment]
Dupe, see https://github.com/ioBroker/ioBroker.zigbee/issues/2015

**Comment by RudiXXL** [comment]
the same for LELLKI WP30-EU. after downgrade it is working again

**Comment by arteck** [comment]
works in 1.9.5
