### ISSUE TITLE
getstate battery not found

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#2012]
Hi, I noticed this after I updated my base image and restored an iobroker backup. Not sure if this error is caused by this adapter:

<html><body>

javascript.0 | 2023-12-27 12:00:00.062 | warn | at processTimers (node:internal/timers:512:7)
-- | -- | -- | --
javascript.0 | 2023-12-27 12:00:00.062 | warn | at listOnTimeout (node:internal/timers:569:17)
javascript.0 | 2023-12-27 12:00:00.061 | warn | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:228:7)
javascript.0 | 2023-12-27 12:00:00.061 | warn | at /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:268:28
javascript.0 | 2023-12-27 12:00:00.061 | warn | at Job.invoke (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Job.js:171:15)
javascript.0 | 2023-12-27 12:00:00.060 | warn | at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1617:34)
javascript.0 | 2023-12-27 12:00:00.059 | warn | at Object.<anonymous> (script.js.common.Status.Akkustände:57:374)
javascript.0 | 2023-12-27 12:00:00.057 | warn | getState "zigbee.0.00158d0002ead66e.battery" not found (3) states[id]=null
javascript.0 | 2023-12-27 12:00:00.057 | warn | at processTimers (node:internal/timers:512:7)
javascript.0 | 2023-12-27 12:00:00.056 | warn | at listOnTimeout (node:internal/timers:569:17)
javascript.0 | 2023-12-27 12:00:00.056 | warn | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:228:7)
javascript.0 | 2023-12-27 12:00:00.055 | warn | at /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:268:28
javascript.0 | 2023-12-27 12:00:00.052 | warn | at Job.invoke (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Job.js:171:15)
javascript.0 | 2023-12-27 12:00:00.051 | warn | at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1617:34)
javascript.0 | 2023-12-27 12:00:00.051 | warn | at Object.<anonymous> (script.js.common.Status.Akkustände:57:283)
javascript.0 | 2023-12-27 12:00:00.050 | warn | getState "zigbee.0.00158d0002f8e5d5.battery" not found (3) states[id]=null
javascript.0 | 2023-12-27 12:00:00.050 | warn | at processTimers (node:internal/timers:512:7)
javascript.0 | 2023-12-27 12:00:00.049 | warn | at listOnTimeout (node:internal/timers:569:17)
javascript.0 | 2023-12-27 12:00:00.049 | warn | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:228:7)
javascript.0 | 2023-12-27 12:00:00.048 | warn | at /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:268:28
javascript.0 | 2023-12-27 12:00:00.048 | warn | at Job.invoke (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Job.js:171:15)
javascript.0 | 2023-12-27 12:00:00.047 | warn | at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1617:34)
javascript.0 | 2023-12-27 12:00:00.046 | warn | at Object.<anonymous> (script.js.common.Status.Akkustände:57:201)
javascript.0 | 2023-12-27 12:00:00.044 | warn | getState "zigbee.0.00158d0002c6b004.battery" not found (3) states[id]=null
javascript.0 | 2023-12-27 12:00:00.043 | warn | at processTimers (node:internal/timers:512:7)
javascript.0 | 2023-12-27 12:00:00.043 | warn | at listOnTimeout (node:internal/timers:569:17)
javascript.0 | 2023-12-27 12:00:00.043 | warn | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:228:7)
javascript.0 | 2023-12-27 12:00:00.043 | warn | at /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:268:28
javascript.0 | 2023-12-27 12:00:00.043 | warn | at Job.invoke (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Job.js:171:15)
javascript.0 | 2023-12-27 12:00:00.042 | warn | at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1617:34)
javascript.0 | 2023-12-27 12:00:00.042 | warn | at Object.<anonymous> (script.js.common.Status.Akkustände:57:121)
javascript.0 | 2023-12-27 12:00:00.040 | warn | getState "zigbee.0.00158d000278e743.battery" not found (3) states[id]=null

</body>
</html>

**Comment by arteck** [comment]
javascript adapter ..really
