### ISSUE TITLE
Feature Request: SyncBox Hue/Govee UDP Streaming and Sync Service

### ISSUE THREAD

**Issue by LipkeGu** [ioBroker/ioBroker.zigbee#2013]
It would be nice to have an "Sync Box" Streaming Service Running on this Adapter.

When we activate the Sync Mode, the box will begin to stream the Color informations to the corresponding ID of the lamp
Setting the Colors and other Attributes is done by the hue bridge itself.

**So we need:**
* An frontend to position the Lights in iobroker.Zigbee (virtual cinema with TV as like in the hue app)
* A Service Listening on port (UDP) 2100 on ZigBee-Adapter with access to an device group where the lamps are listed.
* Option to start/stop Sync, set Coordinates and attributes.

The Project (hueplusplus) shows us how to parse, construct and interpret such a Lightdata packet:
https://github.com/enwi/hueplusplus/blob/06ec4330d9dc943946dc90e8512bb0e7eec7f571/src/EntertainmentMode.cpp#L1

**Comment by arteck** [comment]
this is not available... hue is specialized on connections with light.. and here is the problem
we can add all Devices.. 
an sync box causes too much traffic in network.. 

sry
