### ISSUE TITLE
OTA of own compiled firmware

### ISSUE THREAD

**Issue by Mark31415** [ioBroker/ioBroker.zigbee#2014]
Hello,

first of all this adapter is really great, thanksalot!

I'm using the latest version 1.9.1 and it works great with my new [LYWSD03MMC Thermometer](https://github.com/ioBroker/ioBroker.zigbee/issues/1929).

Now I would like to update the custom firmware to the latest version [pvvx/ZigbeeTLc](https://github.com/pvvx/ZigbeeTLc)
but I have no clue how to upload a .zigbee file with the adapter instead of loading the firmware from a url.
Is this even possible?
Thanksalot for your help!

**Comment by arteck** [comment]
> Is this even possible? 

nope..
