### ISSUE TITLE
Lidl HG06338  not working after update

### ISSUE THREAD

**Issue by MDeeApp** [ioBroker/ioBroker.zigbee#2015]
After the update to 1.8.25 I can't toggle the switches any longer and the following error shows up in log:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/6595194/310d4a34-043e-4fd4-898e-f7fe1bb38344)

After downgrading to 1.8.24 it works again.

**Comment by ahnungsbefreit** [comment]
same here

**Comment by MDeeApp** [comment]
@ahnungsbefreit #2010 
Works in new update v1.9.5
