### ISSUE TITLE
Firmware update fails: Update of '0x001788010d9a6605' failed (Cannot read properties of undefined (reading 'data'))

### ISSUE THREAD

**Issue by thohoj** [ioBroker/ioBroker.zigbee#2020]
After checking for new firmwares, I cannot start the update.

```
Start firmware update for 0x001788010d9a6605
Update of '0x001788010d9a6605' failed (Cannot read properties of undefined (reading 'data'))
```

![IMG_1725](https://github.com/ioBroker/ioBroker.zigbee/assets/18330536/ca8586b3-2f7b-4f45-9f20-90b58fbd0e4a)

Zigbee Adapter v1.8.25
Js-Controller v5.0.17
Nodejs v18.19.0

**Comment by arteck** [comment]
Check GIT version

**Comment by thohoj** [comment]
[v1.9.7](https://github.com/ioBroker/ioBroker.zigbee/releases/tag/v1.9.7) works
