### ISSUE TITLE
New Ikea E2213 Shortcut Button no working

### ISSUE THREAD

**Issue by chris0one** [ioBroker/ioBroker.zigbee#2021]
Hello,

IoBroker found and added this as a new device  but the Buttons are not working. The Datapoints show as well no change.

Thank you so much.
![Screenshot_20231230_085859_Chrome](https://github.com/ioBroker/ioBroker.zigbee/assets/155222941/c9bda5ac-825e-4940-be33-7bebb5be226a)
![Screenshot_20231230_090000_Chrome](https://github.com/ioBroker/ioBroker.zigbee/assets/155222941/b3b4e54c-c13b-4bb5-a019-7cfd1770eb37)

model:E2213description:SOMRIG shortcut button

modelZigbee:SOMRIG shortcut buttontype:EndDevicenwk:13923manuf id:4476manufacturer:IKEA of Swedenpower:Batteryapp version:1hard version:1zcl version:8stack version:113date code:20230308build:1.0.20interviewed:trueconfigured:false

endpoint:1profile:260input clusters:genBasic (0)genPowerCfg (1)genIdentify (3)genGroups (4)genPollCtrl (32)touchlink (4096)64636heimanSpecificScenes (64640)output clusters:genIdentify (3)genGroups (4)genOnOff (6)genLevelCtrl (8)genOta (25)touchlink (4096)heimanSpecificScenes (64640)

endpoint:2profile:260input clusters:genBasic (0)genIdentify (3)genGroups (4)heimanSpecificScenes (64640)output clusters:genIdentify (3)genGroups (4)genOnOff (6)genLevelCtrl (8)heimanSpecificScenes (64640)

**Comment by Meckiilino** [comment]
Same problem here. Issue is already open..
I found this yesterday: https://github.com/ioBroker/ioBroker.zigbee/issues/1996

**Comment by Meckiilino** [comment]
@arteck 
Doofe Frage: Sollte das seit dem Update auf Version 1.9.6 (2024-01-01) funktionieren?
<img width="231" alt="Screenshot 2024-01-03 195621" src="https://github.com/ioBroker/ioBroker.zigbee/assets/50295889/97eadf66-cc38-489d-a6c5-63f82c353b8f">
Ich bekomme es leider nicht hin...

**Comment by Meckiilino** [comment]
Button will work now... Thanks

**Comment by arteck** [comment]
done in 1.01.0
