### ISSUE TITLE
Aqara Opple WXCJKG13LM  - no double/triple click

### ISSUE THREAD

**Issue by Coalado** [ioBroker/ioBroker.zigbee#2022]
I have 3 Aqara Opple  6-Keys, and all of them worked fine -  until I did some  iobroker updates. 

I now get single clicks, and hold events, but

double/triple/holds clicks are now registered as single clicks,

Maybe this is somehow related to the operating mode? (https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html)

JS Controller 5.0.12
ZigBee Adapter v1.8.24

The events (logs) look almost the same for double/single click.

How can I get my double/Triple hold events back?

I attached logs for a single and a double click
[logs_opple_single_click.txt](https://github.com/ioBroker/ioBroker.zigbee/files/13797872/logs_opple_single_click.txt)
[logs_opple_double_click.txt](https://github.com/ioBroker/ioBroker.zigbee/files/13797873/logs_opple_double_click.txt)

**Comment by arteck** [comment]
check version 1.9.6

**Comment by Coalado** [comment]
I tried v1.9.6 - same issues :(

**Comment by Coalado** [comment]
I cannot even find the part of the code that triggers double/triple clicks. Maybe this has been removed by accident?

**Comment by arteck** [comment]
add the device into the exlude Tab ..and check again

**Comment by Coalado** [comment]
Some issues with WXCJKG13LM on exclude list (v. 1.9.7)

**Comment by arteck** [comment]
check Version 1.10.0 here works
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/a4bcf7bd-c062-48d6-bfae-058431e4cd24)

**Comment by Coalado** [comment]
Stil does not work for me. Which operation_mode are you in?  WXCJKG13LM  Excluded or not?
