### ISSUE TITLE
Aqara / xiaomi Light sensor - no comunication (Zigbee Ver 1.9.5)

### ISSUE THREAD

**Issue by Day1983** [ioBroker/ioBroker.zigbee#2023]
Hallo,

mit der neuen Ver 1.9.5 funktioniert das pairing der sensoren von Aqara/xiaomi wieder, aberdie daten werden nicht gesendet.

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/77491820/1afc294f-187c-482d-bbda-3716907d046b)

`DeviceConfigure:Failed to DeviceConfigure.configure 0x54ef441000a1fc8f lumi.sen_ill.agl01 (Error: Write 0x54ef441000a1fc8f/1 aqaraOpple({"mode":1}, {"sendWhen":"immediate","timeout":10000,"disableResponse":true,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240)) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32))`

**Comment by arteck** [comment]
> 'MAC transaction expired'

das ist dein Problem..

**Comment by chris299** [comment]
@arteck was bedeutet diese Meldung denn? Und wie löst man dieses Problem?

**Comment by Day1983** [comment]
> @arteck was bedeutet diese Meldung denn? Und wie löst man dieses Problem?

@arteck, ohhh. Ja bitte. Ein Tip wäre super. Die Channels von WiFi und zigbee sind bei mir weit auseinander (WiFi kanal 11 // zigbee Kanal 18)


Einen guten Rutsch wünsch ich euch...

**Comment by Day1983** [comment]
Hallo @arteck und ein gesundes neues Jahr !!!

ich hatte meinen Coordinator (CC26Rx2...) an eine andere Position gesetzt.

jetzt hab ich bei den Sensoren (xiaomi light T1) folgende Fehlermeldung:


![image](https://github.com/ioBroker/ioBroker.zigbee/assets/77491820/599f732c-7b7b-451e-b161-3e48880ca726)

Interview wird gestartet, und und erfolgreich beendet.... Dann kommt 20sec später die o.g. Fehler... Timeout.


Die Steckdose 4-fach aus #2024 funzt leider immer noch nicht.
