### ISSUE TITLE
EMIZB-141 zeigt keine Batterie, Leistung, Energiewerte

### ISSUE THREAD

**Issue by Tol94** [ioBroker/ioBroker.zigbee#2032]
EMIZB-141 zeigt nur state und availability und liefert Null für die Objekte battery, energy und load_power.
![EMIZB_Info](https://github.com/ioBroker/ioBroker.zigbee/assets/58086842/8e8745e5-12f4-416a-bdbe-23f98585e821)
![EMIZB_Objekte](https://github.com/ioBroker/ioBroker.zigbee/assets/58086842/121c8c66-145a-44cf-971b-02f07f9baf68)

**Comment by arteck** [comment]
jetzt immer noch... ?? bis die Werte kommen dauert ca 24 stunden

**Comment by Tol94** [comment]
Leider immer noch der gleiche Zustand. Das Gerät ist seit ein Paar Tagen in Betrieb. Wenn "battery" Wert gelesen wäre, hätte ich auf nicht richtig montierten Sensor getippt.

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages

und poste das Ergebniss

**Comment by Tol94** [comment]
`2024-01-02 13:51:51.577 - info: admin.0 (1030) <== Disconnect system.user.admin from 192.168.2.40
2024-01-02 13:59:30.238 - warn: zigbee.0 (4239) ELEVATED publishToState: message received '{"linkquality":7}' from device 0015bc001b1006c0 type 'EMIZB-141'
2024-01-02 13:59:30.239 - warn: zigbee.0 (4239) ELEVATED publishToState: value generated '7' from device 0015bc001b1006c0 for 'Link quality'
2024-01-02 14:00:00.803 - info: swiss-weather-api.0 (2009) update current hour...`

**Comment by arteck** [comment]
das musst du schon paar stunden laufen lassen..

**Comment by Tol94** [comment]
Also, von gestern, den ganzen Tag. Das Gerät ist seit tagen in Betrieb. Liefert nur link_quality
[2024-01-03.txt](https://github.com/ioBroker/ioBroker.zigbee/files/13831933/2024-01-03.txt)

**Comment by Tol94** [comment]
Ich habe eine neue SD Karte von Grund auf neu (inkl. OS) eingerichtet und das letzte Backup darauf eingespielt. Siehe da! die Werte werden nun gelesen.
