### ISSUE TITLE
Failed to configure ZBMINIL2

### ISSUE THREAD

**Issue by ChrisSmartHome** [ioBroker/ioBroker.zigbee#2036]
Hallo,

das log der Adapters quillt über durch die failed to configure messages.
Ein bereits erstellter issue besagt, man solle das gerät neu anlernen: dies hab ich versucht, leider ergibt sich dabei keine Veränderung.

Anbei der Fehler:

DeviceConfigure:Failed to DeviceConfigure.configure 0x70ac08fffe4987d1 ZBMINIL2 (Error: Unbind 0x70ac08fffe4987d1/1 genPollCtrl from '0x00212effff09860d/1' failed (Error: status: 136) at DeconzAdapter.unbind (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:828:19) at Endpoint.unbind (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:574:13) at configure (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/src/devices/sonoff.ts:63:13) at Object.configure (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/src/index.ts:139:25) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21))
--
 

<br class="Apple-interchange-newline">

VG

**Comment by Frank1604** [comment]
Gleiches Problem mit ZB-SW01.
`DeviceConfigure:Failed to DeviceConfigure.configure 0x00124b0023adcade ZB-SW01 (Error: ConfigureReporting 0x00124b0023adcade/1 genOnOff([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 30650 - 1 - 59 - 6 - 7 after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7))`

**Comment by arteck** [comment]
> Gleiches Problem mit ZB-SW01. `DeviceConfigure:Failed to DeviceConfigure.configure 0x00124b0023adcade ZB-SW01 (Error: ConfigureReporting 0x00124b0023adcade/1 genOnOff([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 30650 - 1 - 59 - 6 - 7 after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7))`

nö nicht gleiches Problem.. dein Gerät antwortet nicht.. und läuft auf timeout

**Comment by Frank1604** [comment]
Interessant. Ist erst seit dem letzten Update so. Gerät funktioniert auch einwandfrei, lässt sich steuern.

**Comment by ChrisSmartHome** [comment]
neue version installiert: error kommt beim neu anlernen einmalig, danach nichts mehr :)
