### ISSUE TITLE
Hue White 1600 wird nicht erkannt

### ISSUE THREAD

**Issue by doc305** [ioBroker/ioBroker.zigbee#2037]
Hallo zusammen,

ich habe zwei Hue White 1600 gekauft. Die erste wird als LWA009 einwandfrei erkannt, die zweite wird erkannt als LWA031 und wird als "not supported" angezeigt.
Meine Adapter Version ist die 1.9.6 beta, aber auch die letzte stable hat nicht geholfen.
Auf beiden Lampen steht die gleiche Modellnummer 9290023349.
Im Log steht "Device 0xdc8e95fffe08a78f "undefined" not described in statesMapping".

Mach ich da was falsch?

Zigbee: 1.9.6
NPM: 10.2.3
NodeJS: 18.19.0
JS-Controller: 7.1.6
Admin: 6.12.0

**Comment by arteck** [comment]
done in 1.10.0
