### ISSUE TITLE
"Tuya TS0601" Tuya Zigbee Human Presence Sensor,  "Gleco" Model: GS200 wird im Zigbee-Adapter nicht erkannt

### ISSUE THREAD

**Issue by Klarie2** [ioBroker/ioBroker.zigbee#2038]
_deutsch   (English below)_

Hallo liebes Team,
Ich habe mir einen Radar-Sensor bei Ali bestellt. 
https://de.aliexpress.com/item/1005005965982781.html?spm=a2g0o.order_list.order_list_main.11.72735c5f73cOhO&gatewayAdapt=glo2deu

Dieser wird jedoch im Zigbee-Adapter (noch) nicht erkannt. Das Pairing läuft problemlos.

Hier die Infos zum Sensor:
![Bildschirmfoto vom 2023-12-30 16-48-06](https://github.com/ioBroker/ioBroker.zigbee/assets/105676048/7762b69a-7d84-45b4-a420-97d9d5df8a44)

Solltet Ihr noch weitere Infos zu dem Sensor benötigen, werde ich diese schnellstmöglich nachliefern.

Liebe Grüße - und vielen Dank
Klaus

_English:_

Hello dear team,
I ordered a radar sensor from AliExpress.
https://de.aliexpress.com/item/1005005965982781.html?spm=a2g0o.order_list.order_list_main.11.72735c5f73cOhO&gatewayAdapt=glo2deu

However, it is currently not recognized in the Zigbee adapter. The pairing process runs smoothly.

Here is the information about the sensor:
(Screenshot above)

If you need any further information about the sensor, I will provide it as soon as possible.

Best regards - and thank you very much,
Klaus

**Comment by Klarie2** [comment]
![20240103_224437](https://github.com/ioBroker/ioBroker.zigbee/assets/105676048/6db0b3fd-0033-4269-b84f-30b8b430dc9a)
![20240103_224502](https://github.com/ioBroker/ioBroker.zigbee/assets/105676048/a6e26ec8-9df9-499d-ba58-0c2304070fd4)

**Comment by arteck** [comment]
done in 1.10.0

**Comment by Klarie2** [comment]
Thank you so much, arteck!
