### ISSUE TITLE
Starting zigbee-herdsman problem : undefined   mit der Version 1.9.6 

### ISSUE THREAD

**Issue by AlfredSch** [ioBroker/ioBroker.zigbee#2039]
Hallo zusammen 
Nach dem upgrade von 1.8.24 auf 1.9.6 läuft der Adapter nicht mehr. Wieder zurück auf 1.8.24 ist wieder alles ok.
Iobroker lauft auf einem Raspi.

Gruss und Danke
Fred

Fehlermeldung:
2024-01-05 10:02:45.647	debug	zigbee-herdsman:deconz:driver Opening with /dev/ttyS0
zigbee.0
2024-01-05 10:02:45.647	debug	zigbee-herdsman:deconz:driver too many timeouts - restart serial connecion
zigbee.0
2024-01-05 10:02:45.646	debug	zigbee-herdsman:deconz:driver Timeout for request - CMD: 0x7 seqNr: 106
zigbee.0
2024-01-05 10:02:40.329	debug	zigbee-herdsman:deconz:driver Timeout for aps request CMD: 0x12 seq: 209
zigbee.0
2024-01-05 10:02:35.642	debug	zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 106
zigbee.0
2024-01-05 10:02:35.639	debug	zigbee-herdsman:deconz:driver Timeout for request - CMD: 0x7 seqNr: 102
zigbee.0
2024-01-05 10:02:30.746	debug	zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x0 EP:0 SeqNr. 208 request id: 30
zigbee.0
2024-01-05 10:02:30.743	debug	zigbee-herdsman:deconz:adapter checking coordinator simple descriptor
zigbee.0
2024-01-05 10:02:30.737	debug	zigbee-herdsman:deconz:adapter RECEIVING SIMPLE_DESCRIPTOR FAILED - addr: 0x0 waiting for response TIMEOUT
zigbee.0
2024-01-05 10:02:25.637	debug	zigbee-herdsman:deconz:driver Promise was caught with reason: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
zigbee.0
2024-01-05 10:02:25.635	debug	zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 102
zigbee.0
2024-01-05 10:02:25.633	debug	zigbee-herdsman:deconz:driver Opening with /dev/ttyS0
zigbee.0
2024-01-05 10:02:25.632	debug	zigbee-herdsman:deconz:driver too many timeouts - restart serial connecion
zigbee.0
2024-01-05 10:02:25.631	debug	zigbee-herdsman:deconz:driver Timeout for request - CMD: 0x7 seqNr: 105

**Comment by micw421** [comment]
Ich habe exakt das gleiche Problem nach Update auf 1.9.x!
Und ich kann leider nicht zurück, da ich node.js hochgezogen habe.
Mit Bitte um schnelle Fehlerbehebung, da mein ganzes zigbee-Netzwerk nicht mehr läuft ...

**Comment by micw421** [comment]
@AlfredSch, wie bist du denn zurück auf 1.8? Müsstest ja auch das node.js-Problem gehabt haben.

**Comment by AlfredSch** [comment]
Hallo micw421

 

Ich habe den alten Adapter wieder installiert mit  «  iobroker upgrade ***@***.*** ***@***.***>   « danach lief wieder alles wie gehabt.

Grüsse

Fred

 

Von: micw421 ***@***.***> 
Gesendet: Samstag, 6. Januar 2024 13:40
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: Fred ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] Starting zigbee-herdsman problem : undefined mit der Version 1.9.6 (Issue #2039)

 

Ich habe exakt das gleiche Problem nach Update auf 1.9.x!
Und ich kann leider nicht zurück, da ich node.js hochgezogen habe.
Mit Bitte um schnelle Fehlerbehebung, da mein ganzes zigbee-Netzwerk nicht mehr läuft ...

**Comment by micw421** [comment]
Danke!
Auch ich kann bestätigen, dass es mit 1.8.24 (RaspBee II auf /dev/ttyS0) wieder funktioniert.

**Comment by micw421** [comment]
1.8.27 bekomme ich übrigens nicht installiert:

48 verbose stack iobroker.zigbee: No matching version found for iobroker.zigbee@1.8.27.
48 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
48 verbose stack     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
48 verbose stack     at async #nodeFromEdge (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1049:19)
48 verbose stack     at async #buildDepStep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
48 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
48 verbose stack     at async Promise.all (index 1)
48 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
48 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:152:5)
48 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:61:5)

**Comment by arteck** [comment]
1.9.7 ist draussen

**Comment by micw421** [comment]
1.9.7 hat bei mir das gleiche Problem.

**Comment by arteck** [comment]
version 1.10 ist draussen

**Comment by micw421** [comment]
Hallo @arteck,

leider funktioniert 1.10.0 auch nicht, immer noch das gleiche Problem:
Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'

Zurück zu 1.8.24.

Kann ich noch irgendwas tun, um die Ursache zu finden?

**Comment by micw421** [comment]
Das Problem wird wohl auch hier beschrieben:
https://github.com/Koenkk/zigbee-herdsman/issues/870

**Comment by Sombornus** [comment]
Habe ebenfalls das gleiche Problem und nutze dieselbe Konfiguration wie „micw421“. Den  RaspBee II und /dev/ttyS0 als COM- Anschluss. 
Adapter Version 1.8.24 funktioniert hervorragend. Die Version 1.9.7 oder auch 1.10 funktioniert bei mir nicht. Nach rücksetzten auf Version 1.8.24 funktioniert der Adapter wieder. 
Was kann ich machen?

**Comment by AlfredSch** [comment]
Auch bei mir funktioniert der Adapter mit der Version 1.10 nicht. Gleicher fehler in der Logdatei. Alles ok mit Version 1.8.24 !

**Comment by Apollon77** [comment]
Did yo tried to power off the USB strick (disconnect) and reconnect? I also had such an effect and I just needed to really take out the usb stick and stick it in again

**Comment by micw421** [comment]
Es geht hier ja um den seriellen Port, nicht USB.
Und es hat wohl u.a. was mit node zu tun: https://github.com/serialport/node-serialport/issues/2735

Ich habe übrigens 18.19.0.

**Comment by Sombornus** [comment]
@Apollon77 
Thanks for this hint. I use a non USB based solution. It is the Phoscon „RaspBee II“ Zigbee Interface, which use the IO-pins of a Raspberry Pi.  
And „yes“, I did several reboots and repowering without any success.

**Comment by arteck** [comment]
schaumal

https://github.com/ioBroker/ioBroker.zigbee/tarball/serialport_old

da ist ne alter version drin... gehts damit

**Comment by Sombornus** [comment]
Habe die Test Version gemäß Link installiert. Führt leider zur gleichen Fehlermeldung.
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/156587001/b6ad275c-0e09-4d8c-b566-57d151acc271)

Zurück auf 1.8.24 geht wieder alles.
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/156587001/17427334-0dcc-47e3-9b34-32c479d6e08f)

**Comment by micw421** [comment]
https://github.com/zwave-js/node-red-contrib-zwave-js/issues/288#issuecomment-1849100364

Da dort steht, dass es mit node 18.17.1 gehen soll, habe ich das gerade mal versucht, aber auch das brachte keinen Erfolg 👎

**Comment by AlfredSch** [comment]
@khnz 
Danke genau die Anpassung von main.js mit der Baudrate auf 38400 hat das Problem auch bei mir gelöst.
Der Adaper 1.10.0 startet jetzt ohne Problemen .
Danke

**Comment by khnz** [comment]
Version 1.8.24 verwendet zigbee-herdsman 0.18.7. In dieser Version wird im deCONZ Treiber der baudrate-Parameter aus der main.js nicht verwendet (statt dessen fest 38400 gesetzt). Die Auswertung des Parameters wurde erst mit zigbee-herdsman 0.22 eingebaut.

**Comment by micw421** [comment]
Ok, alles klar, habe ich mir mal angesehen.
Wurde wohl wg. ConBee III gemacht. Also müsste man hier auch zwischen den Versionen unterscheiden und die Baudrate entsprechend setzen.

**Comment by arteck** [comment]
ich mach die mal konfigurierbar

**Comment by micw421** [comment]
Leider nicht: Starting zigbee-herdsman problem : "\"baudRate\" must be a number: 38400"

**Comment by arteck** [comment]
guckmal jetzt

**Comment by micw421** [comment]
Ja, jetzt läuft es!

**Comment by khnz** [comment]
Die Version von Github funktioniert nach Konfiguration der Baudrate ohne Problem. Vielen Dank.
