### ISSUE TITLE
Support a CO detektor (kohlenmonoxid-sensor)

### ISSUE THREAD

**Issue by joerghildering** [ioBroker/ioBroker.zigbee#204]
Is there a supported CO detekto?

**Comment by arteck** [comment]
which device ?

**Comment by joerghildering** [comment]
https://de.aliexpress.com/item/Smart-Home-CO-Metallerfassungssystem-Batterie-Betrieben-Zigbee-HA1-2-Allianz-Intelligente-Kohlenmonoxid-detektor-Sensor/32890788689.html?spm=a2g0x.search0204.3.3.4cea5f87SYiSBY&ws_ab_test=searchweb0_0%2Csearchweb201602_7_10065_10068_10890_10547_319_10546_317_10548_10696_10084_453_454_10083_10618_10304_10307_10820_537_536_10902_10843_10059_10884_10887_321_322_10103%2Csearchweb201603_51%2CppcSwitch_0&algo_pvid=e8789fc3-d2de-4352-8994-c7cd5798a7b2&algo_expid=e8789fc3-d2de-4352-8994-c7cd5798a7b2-0

**Comment by joerghildering** [comment]
I’m still searching for a supported CO detector.
