### ISSUE TITLE
Xiaomi / Aqara light sensor - Paring error /Time error

### ISSUE THREAD

**Issue by Day1983** [ioBroker/ioBroker.zigbee#2041]
Hallo,

hab bei den Sensoren noch den ERROR beim paring... 
Das Interview wird gestartet, und erfolgreich beendet. nach 20sec. kommt diese Fehlermeldung.

`DeviceConfigure:Failed to DeviceConfigure.configure 0x54ef441000a1fc8f lumi.sen_ill.agl01 (Error: Read 0x54ef441000a1fc8f/1 aqaraOpple([0], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 58200 - 1 - 152 - 64704 - 1 after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))`

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/77491820/1d2a2ada-b4e5-4ce3-8c49-484f4fbd0f71)

**Comment by Day1983** [comment]
getestet mit Vers 1.9.7 - die Fehlermeldung ist weg, aber Paring kann nach 2min nich abgeschlossen werden.
Die Sensoren senden keine Daten...


![image](https://github.com/ioBroker/ioBroker.zigbee/assets/77491820/476313c7-ce51-486c-81f5-307d3a12606b)

**Comment by arteck** [comment]
dann erhöhe den Timer

**Comment by Day1983** [comment]
Hallo @arteck ,

der Timer ist auf max mit 255sec gestellt.
Beide Sensoren, nach ca. 3min.

Helfe gern, wenn Du noch log benötigst oder ä.

Vielen Dank für Deine Hilfe.

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/77491820/ebedd1b6-31cd-4380-a113-e5bc5504b3b0)

**Comment by Day1983** [comment]
Auch mit der Version 1.10. und 1.10.1 gehen die beiden Lichtsensoren nicht.

@arteck
