### ISSUE TITLE
Zigbee Repeater Marmitek Link SE nicht richtig erkannt --> Water leak detector

### ISSUE THREAD

**Issue by KL1801** [ioBroker/ioBroker.zigbee#2042]
Hallo,

Ich habe mir 2 Marmitek Link SE Zigbee Repeater gekauft. An sich machen die einen guten Dienst. Nur die Verknüpfung im Zigbee Adapter scheint verkehrt zu sein. Die beiden Repeater werden als "Water leak detector" erkannt. Dadurch gibt es auch immer und immer wieder Fehlermeldungen im Protokoll.

Können diese richtig konfiguriert werden?

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/18719162/49a57ecb-83e8-44b8-bc9d-4f6d10ca98f9)

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/18719162/800f4ba0-02de-4198-b8b1-9f0eea816d45)

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/18719162/506a6f64-a9fd-4e37-acfc-f5778e7e0a58)

Vielen vielen Dank schon einmal!!

**Comment by arteck** [comment]
wilkommen in der Tuya Welt.. wir haben da kein Einfluss drauf
