### ISSUE TITLE
Add support for a new devices iAQ2 and iAQ3 from EFEKTA

### ISSUE THREAD

**Issue by asutpshnik** [ioBroker/ioBroker.zigbee#2043]
Please help to add iAQ2 and iAQ3 devices to IoBroker via the ZigBee driver (native support).
Vendor:
1. shop on Ali - [link](https://aliexpress.ru/store/1102156845)
2. telegram channel - [link](https://t.me/diy_devices)

The author of the devices sends converters for the devices, attached EFEKTA_iAQ2_R3.js and EFEKTA_iAQ3_R6.js files.
[EFEKTA_iAQ2_R3.txt](https://github.com/ioBroker/ioBroker.zigbee/files/13850596/EFEKTA_iAQ2_R3.txt)
[EFEKTA_iAQ3_R6.txt](https://github.com/ioBroker/ioBroker.zigbee/files/13850597/EFEKTA_iAQ3_R6.txt)

The converters definitely work via zigbee2mqtt, but ioBroker ZigBee driver does not receive all the data from the sensors.
ioBroker objects of iAQ2 device (all done):
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/60661789/95ce375f-413f-4231-aba9-ee78573dc72c)
ioBroker objects of iAQ3 device (problem device):
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/60661789/cad4f9cc-ed6a-48b0-9bf1-44fd0af48c89)

**Comment by arteck** [comment]
check version 1.10.0

**Comment by asutpshnik** [comment]
> check version 1.10.0

I updated the driver to version 1.10.1, problems found:
1. in the logs there are errors loading converters
2. data stopped coming from devices
3. icons and information about devices disappeared
Attached log file with info level
You can make a log with the debug level if it helps fix the problem!
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/60661789/c4adcfa5-505e-41c3-adc9-bb1cb8646c88)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/60661789/8f2cce75-be97-45d0-888b-9bff6719f19d)
[iobroker.log](https://github.com/ioBroker/ioBroker.zigbee/files/14028366/iobroker.log)
