### ISSUE TITLE
Steckdosenleiste LELLKI WP33-EU schaltet immer alle 4 Switches gemeinsam

### ISSUE THREAD

**Issue by Erwin40** [ioBroker/ioBroker.zigbee#2045]
Hallo erst mal.

Folgende Steckdosenleiste: https://www.zigbee2mqtt.io/devices/WP33-EU_WP34-EU.html
wird bei mir korrekt und fehlerfrei erkannt und eingebunden.
Bei den ersten Versuchen diese zu steuern, hatte ich das Problem, dass das Schalten über den Adapter zwar funktionierte, aber nicht über die Datenpunkte (true/false)
Anschließend habe ich die Steckdosenleiste mit einem Tuya-Gatewas connected und über die Tuya-App geschaltet -> funktionierte einwandfrei.
Ich habe sonst nichts verändert und gleich wieder entfernt.
Jetzt am Sonntag wollte ich es noch mal am ioBroker testen und siehe da, im Adapter heißen alles 5 Switches gleiche und schalten auch gemeinsam :-(
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/138704484/531b9e90-a50d-4efa-ab64-849419e11430)

Alle Rücksetz-Versuche, Neustarts und auch tests mit älteren Versionen (ZigBee-Adapter) ohne Ergebnis.
Ich bin mit allem auf dem aktuellsten Stand. RaspberryPi, ioBroker und alle Adapter. Der ZigBee Adapter hat auch schon die 1.9.7
Meine Hardware ist ein RaspberryPi4 4GB und ein Sonoff ZigBee 3.0 USB Dongle Plus zbdongle-p mit der aktuellen Firmware 20230507
Ich hätte das Debug-Protokoll vom Join Process zur Verfügung, falls es benötigt würde.

Um Hilfe wäre ich sehr dankbar, da es die die z.Z. einizige Steckdosenleiste auf dem Markt ist, die mit Einzeltaster an der Leiste selbst ausgestattet ist.

MfG

**Comment by arteck** [comment]
es gibt auch eine von Lidl allerdings mit 3 Steckdosen
https://templates.blakadder.com/lidl_HG06338.html

zeigmal die Datenpunkte die angelegt werden

**Comment by Erwin40** [comment]
Hi.
Sorry, die sind aber manuell nicht einzeln schaltbar und das war auch nicht die Frage ;-)
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/138704484/1bb0459b-084b-44db-aca5-4fd50bd9d559)

MfG

**Comment by arteck** [comment]
> Sorry, die sind aber manuell nicht einzeln schaltbar 

doch das geht.. die USB kann man nur schicht schalten die sind dauer an


schalte bitte den state_l1 auf true und poste die msg_from_zigbee

**Comment by Erwin40** [comment]
Nö :-) An der Leiste selbst kannst du nur alle 3 Steckdosen ein-/ausschalten. Ist ja auch nur ein Taster da ;-)
Ich bin etwas weiter gekommen.
Wenn ich mit die Leiste entferne und unter der 1.8.10 / 1.8.27 anlerne und dann auf die 1.9.7 gehe, funktioniert alles super.
Es muss also am Anlern-Vorgang liegen.
Was jedoch bei allen drei Versionen auffällt ist, das ich das Gerät nicht mehr umbenennen kann. Das ging aber mal.
Ok, ich kann es aber auch über den Datenpunkt ändern, das passt.

Das ist die msg_from_zigbee wenn es funktioniert:
{
  "type": "attributeReport",
  "data": {
    "65506": 48,
    "65508": 0,
    "appVersion": 67
  },
  "linkquality": 7,
  "groupID": 0,
  "cluster": "genBasic",
  "meta": {
    "zclTransactionSequenceNumber": 136,
    "manufacturerCode": null,
    "frameControl": {
      "frameType": 0,
      "manufacturerSpecific": false,
      "direction": 1,
      "disableDefaultResponse": false,
      "reservedBits": 0
    }
  },
  "endpoint_id": 1
}

Und das wenn das Gerät unter der 1.9.7 angelernt wurde:
{
  "type": "attributeReport",
  "data": {
    "onOff": 1
  },
  "linkquality": 21,
  "groupID": 0,
  "cluster": "genOnOff",
  "meta": {
    "zclTransactionSequenceNumber": 184,
    "manufacturerCode": null,
    "frameControl": {
      "frameType": 0,
      "manufacturerSpecific": false,
      "direction": 1,
      "disableDefaultResponse": true,
      "reservedBits": 0
    }
  },
  "endpoint_id": 5
}

**Comment by Erwin40** [comment]
Nachtrag:
Ich habe jetzt den Sonoff USB Stick zbdongle-E am Start.
Leider völlig identisches Verhalten.
Und ich habe noch etwas weiter herum experementiert und die verschiedenen ZigBee Versionen getestet.
Das Fehlverhalten kam definitiv mit der 1.9.* rein.
Diese funktionieren: 1.8.10, 1.8.12, 1.8.18, 1.8.19, 1.8.20, 1.8.21, 1.8.22, 1.8.23, 1.8.24
Bei dieser schaltet garnix: 1.8.25
Alle anderen Versionen (unter 1.9.*) startete der Adapter nicht erfolgreich.
Da gab es auch Fehlermeldungen im Log.

Vielleicht hilft das ja weiter.

**Comment by arteck** [comment]
version 1.10.0 ist draussen

**Comment by Erwin40** [comment]
Hurra, es funktioniert.
1.10.0 installiert, Gerät entfernt und neu angelernt.
Jetzt funktionieren die Switches einwandfrei als einzelne Schalter.
Vielen, vielen Dank!

Nur noch ein Frage, oder soll ich dafür einen eigenen Case aufmachen?
In der Objekt-Ansicht fehlen mir die Icons. Nur die Lichtsensoren (wurden als erstes vor langer Zeit hinzugefügt) werden angezeigt.
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/138704484/aec7936b-99d8-48df-b656-f4eb6a014251)

**Comment by arteck** [comment]
lesen Bildet

https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update

wozu schreib ich die Doku
