### ISSUE TITLE
You need save and run adapter before pairing! ERROR

### ISSUE THREAD

**Issue by LukasVFL99** [ioBroker/ioBroker.zigbee#2046]
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/62470796/85d21fa1-71fd-4266-8b27-b4e0f143b9de)
 
Hey after updating the nodejs adapter to 19x I ran in to this issue.
Is there a solution for this problem?

**Comment by arteck** [comment]
nodejs 19.x is not supported
