### ISSUE TITLE
Sort Adapters from A-Z by default in Overview

### ISSUE THREAD

**Issue by rug1024** [ioBroker/ioBroker.zigbee#2055]
When Zigbee-Adapter-Overview is opened, please sort Adapters by default "From A-Z".
Nothing else makes sense.

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/96115731/e3402076-5365-49c4-bb74-28e97d8fdaed)

**Comment by arteck** [comment]
and the next nedd sorted by room .. and the next need sorted by manufacturer..or anything alse...

nope .. sry
