### ISSUE TITLE
BUG: Zigbee-Adapter (v1.9.7) fügt einfach entfernte Geräte wieder hinzu?!?!

### ISSUE THREAD

**Issue by AdamK-DE** [ioBroker/ioBroker.zigbee#2056]
Ich tauschte kürzlich einen PIR aus. Der alte kann (wie irgendwie immer) nicht in der Zigbee Übersicht gelöscht werden sondern ich muss dort immer auf "Gerät verloren" klicken das er verschwindet.

Dies ist locker eine Woche her.. Und nun schaue ich in die Geräte Liste und der alte ist einfach wieder da.. Hääää????????
Er liegt inkl. Batterie drinn noch hier herum aber das kann doch nicht wahr sein?! Wieso pairt der Zigbee-Adapter ihm einfach wieder selbst obwohl händisch gelöscht ???????

Wie soll man da dann Geräte löschen??? Wenn man die Batterie nicht entfernen will.........

**Comment by arteck** [comment]
du löscht den PIR (nehme mal an Batteriebetrieben) hardcore.. also bleibt dieser am coordinator dran. 
deshalb steht da auch "Gerät verloren".. bekommt dieser wieder Strom da doch nicht verloren wird er dirket wieder ins Netz geschoben. 

bei löschen musst du IMMER Batteriebetriebene Geräte kurz wecken..... 

also nochmal für DICH.. wenn Verloren dann ist der WEG.. WEG..WEG .. nicht in der Schublade sondern WEG.

**Comment by AdamK-DE** [comment]
dann sollte der zigbee adapter aber auch eine info dazu rausgeben. das normale löschen klappt ja mit irgendeiner seltsamen meldung nicht. denke da wählen dann alle "gerät verloren" da es nur damit dann klappt. das das gerät vor dem ersten geweckt werden muss weiss ja niemand?! ich zumindestens wusste nichts davon.. aber macht sinn.
