### ISSUE TITLE
LEDVance Switch contact bounce since update 1.9.7

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.zigbee#2061]
Seit > 2 Jahren verwende ich folgendes Skript:

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/59795191/0b79b32a-f0ec-4696-89aa-2d0f306118ee)

Mit einer LEDVance 4 Tasten Fernbedienung toggle ich ein Licht. Seit dem Update auf Zigbee 1.9.7 prellt jetzt scheinbar der Adapter. Das Licht geht ganz kurz an und sofort wieder aus. Habe versucht, den Release statt dem Click zu verwenden - kein Unterschied! 

Einen Debug habe ich in den Trigger eingesetzt, der mir den Status des Trigger anzeigt. Hier kommt 3x true, wenn eine der Tasten betätigt wird. Ich würde gerne einen Log schicken, weiß aber nicht welchen und wo ich den finden kann!

LG Uwe

PS: Der Zigbee Adapter ist der wichtigste in meiner Installation! Ich habe 61 Geräte per Zigbee verbunden.

**Comment by asgothian** [comment]
Bitte versuche den Trigger nachdem du von "ist wahr" auf "ist grösser als vorher" umgestellt hast. Das kann das Problem bereits lösen.

A.

**Comment by Haifeif** [comment]
Probier ich, danke für den Tipp. Aber warum hat es vorher 2 Jahre problemlos funktioniert?
