### ISSUE TITLE
Strange behavior 1.9.7 

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.zigbee#2062]
Hallo!

Ein weiteres Zigbee Device macht Ärger: Ein Fensterkontakt, dessen Datenpunkte suggerieren, alles sei in Ordnung, eine LED am Gerät selbst, die aufleuchtet, wenn das Fenster geöffnet/geschlossen wird. Es wird aber kein Status geändert. Beim Versuch, die Einheit neu zu pairen, scheitert. Ähnlich wie bei Issue #2061 prellt der Zigbee Adapter beim pairing, 
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/59795191/7521fe48-5a15-4ae4-becf-d9d09598dec4)
und das pairing wird nicht abgeschlossen! Ich weiß nicht, welche Logdatei hier helfen kann, werde sie aber sofort schicken, wenn ich erfahre was / wo ich sie finden kann.

LG Uwe

**Comment by arteck** [comment]
es auch kann kaputt sein...

**Comment by Haifeif** [comment]
Aber wenn von mehr als 60 Zigbee Geräten plötzlich alle möglichen "verrückt" spielen - Ikea Leuchtmittel, SilverCrest Kontaktsensoren, LEDVance Fernbedienung ... dann wird der Defekt eines Gerätes unwahrscheinlich. Zumal das erst nach empfohlenen Update auf die 1.9.7 passierte.

**Comment by arteck** [comment]
wenn ein Gerät im Netz spinnt..dann kann es zu unterschiedlichen Fehlern kommen

machmal bitte

https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages
