### ISSUE TITLE
Illuminance and Motion Sensor P1 / RTCGQ14LM not fully implemented?

### ISSUE THREAD

**Issue by ltsalvatore** [ioBroker/ioBroker.zigbee#2063]
Hi folks, 

just wondering if the Aqara Illuminance and Motion Sensor P1 (RTCGQ14LM) is not jet fully supported by the zigbee.adapter on iobroker.

i am running two motion detector at the moment: 
an older RTCGQ11LM which i would like to replace with the newest RTCGQ11LM

The older motion sensor has a value called "no_motion" which i need to run some automated processes via script
on the newer model i am missing this value or it is not generated where i would have expected it to be.

old device:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/45215717/fe314501-70c2-4185-ba7e-1544f17a62e6)

new device:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/45215717/2b0cbb91-0ff0-453a-8481-842dfa5d46b7)

beside that, what is the main difference between those two versions of motion sensors?

thx in advance for your help

**Comment by arteck** [comment]
RTCGQ14LM is not RTCGQ11LM

is correct.. new device has also motion_sensivity and old not ..

**Comment by ltsalvatore** [comment]
is this the wrong place to ask for having it fully integrated with the zigbee.adapter?

as for now a lot of useful values are not updated or usable.
