### ISSUE TITLE
LIDL LED PANEL "14153806L" reagiert nicht auf Colortemp

### ISSUE THREAD

**Issue by Hifly89** [ioBroker/ioBroker.zigbee#2065]
Hallo,
ich hab mit dem LIDL LED PANEL (https://www.zigbee2mqtt.io/devices/14153806L.html) das Problem, dass die Colortemp nicht angenommen wird mit Außnahme von Wert "0", der die Leuchte auf sehr helles weißes Licht einstellt. Andere Werte wie 500 werden von der Lampe ignoriert. Im Log gibt es auch keine Meldung.

Aktuelle Version: 1.9.7 bzw. 1.8.24 (hier bestand das Problem auch)

**Comment by arteck** [comment]
du postest den link zu der Lampe ..liest aber nicht was es macht

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/49357f86-dab6-46e7-b6b6-d6c49efdeb2d)
