### ISSUE TITLE
Add "send_payload" state to groups

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.zigbee#2066]
all groups does not contain a state for ```send_payload```
What's the reason and would it be possible to include?

**Comment by arteck** [comment]
for what you need this function?

**Comment by asgothian** [comment]
The reason for the groups not containing a send_payload state is that groups inherently do not publish states. The list of states for the groups is generated by the zigbee adapter off a template list within the adapter.

the send_payload state is aimed at providing direct access to converters available in the zigbee-herdsman-converters, and attempts to link the given JSON to one or more converters published by the device-type. This is not feasible for groups.

an adaptation may be possible but will never work the same as the send_payload does for standard zigbee devices. As such - I currently do not see this being implemented.

A.
