### ISSUE TITLE
Onenuo tuya smart zigbee wassers sensor

### ISSUE THREAD

**Issue by throstenk** [ioBroker/ioBroker.zigbee#2072]
Hallo mein Zigbee Sensor wird nicht erkannt kann mir hier jemand helfen? 

![image](https://github.com/ioBroker/AdapterRequests/assets/80670170/e582b642-b41b-4d9a-a381-3ed29ead34a3)

![image](https://github.com/ioBroker/AdapterRequests/assets/80670170/f43ecc0b-f2c5-41f1-98f4-5d3d8968d89f)

Danke Lg. THorsten

**Comment by arteck** [comment]
ach kommm.. das ist doch ein undefined Device... nochmal pairen bis da was kommt.
steht auch im LOG
