### ISSUE TITLE
[send_payload] Transition not working

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.zigbee#2074]
Adapter: v1.9.7

If I use the ```send_payload``` state with the following command, the transition time will be ignored:
```{ "state": "ON", "transition": 5 }```

If I set the single state ```transition_time``` with ```5``` and then switch on, then the light turns on with transition.

If I use another cmd as transition, like transition_time or something else, then I get an error from the adapter.

**Comment by asgothian** [comment]
Try to set the values in reverse order.

**Comment by Schmakus** [comment]
nothing changed. transition is only working, if I set single states.

**Comment by asgothian** [comment]
I have taken a closer look at the internal system - transition time is not set as a state with its own converter but as an option when setting specific light related zigbee commands. As such, it does not conform the the syntax used in send_payload. I currently see no means of implementing it without rewriting a lot of code and adding ZCL specific handling code to a generic function - which I am not willing to do.

A.
