### ISSUE TITLE
Raspberry Pi 5 8GB Texas instrument  CC1352P-2

### ISSUE THREAD

**Issue by rmp63526** [ioBroker/ioBroker.zigbee#2075]
Hello, 
I have a Pi 4 8gb and the Zigbee adapter works very well with the CC1352P-2. I have now removed the CC1352P-2 from my Pi4 and shut it down.
Now I wanted to test the CC1352P-2 with the Zigbee adapter on my freshly installed Pi 5 (SD card-Pi OS 64 Bockworm) before switching to the Pi 5.
After a while I get the adapter working, but when I reboot the Pi it turns orange again and does not go to green.
I then have to connect to WinScp and go into the Zigbee folder and delete the backup files to get it working again.
But even that doesn't always work to get the adapter working. 
Now I'm wondering if anyone has got the CC1352P-2 working with the Pi5 or if it's a bug.

![Unbenannt](https://github.com/ioBroker/ioBroker.zigbee/assets/65367883/7347253d-d608-4da7-b1bf-625ab2e6c3a6)

![Unbenannt1](https://github.com/ioBroker/ioBroker.zigbee/assets/65367883/7c537403-4b5b-4d97-b045-6fcc2b556b29)

If everything fits, the adapter will turn green.

![Unbenannt2](https://github.com/ioBroker/ioBroker.zigbee/assets/65367883/f167b7f5-2090-45d9-8d7c-76f82686d4d5)

After rebooting, I get these error messages and nothing works.

![Unbenannt3](https://github.com/ioBroker/ioBroker.zigbee/assets/65367883/2caa9c9f-e991-4308-8fc1-8850d71929b8)

**Comment by asgothian** [comment]
Please attempt to start the zigbee adapter in debug once the reboot occurs and paste the log entries as text. Screenshots are hard to navigate.

A.

**Comment by asgothian** [comment]
It shouldn’t . Just reboot when you feel safe to do so.

A.

**Comment by rmp63526** [comment]
Unfortunately, the adapter does not turn green after a reboot..
I have now restarted the adapter manually - without success. disconnected the CC1352P-2 from the usb, waited 30 seconds and reconnected it - without success. I also have this phenomenon when I install the adapter without first importing the backup.

[iobroker.current.log](https://github.com/ioBroker/ioBroker.zigbee/files/14171303/iobroker.current.log)


![Unbenannt3](https://github.com/ioBroker/ioBroker.zigbee/assets/65367883/10b50c39-7e1f-4613-8d99-e823eaeaa8a1)

**Comment by asgothian** [comment]
I have been trying to your log - please (if you can) run two more test, with the log active

- restore the zigbee data again
- Start it so it runs
- Delete the log
- Stop the zigbee adapter
- Reboot (just from the OS)
- Start the zigbee adapter
- 
post as log a

repeat but disconnect and reconnect the coordinator 

post as log b

it looks as if the firmware on the stick remains active during reboots and thus accepts no communication

I can parse the logs over the weekend - possibly

**Comment by rmp63526** [comment]
Of course I do several tests, that's no problem :-)

**Test 1**
1. i deleted the adapter in iobroker, then deleted the zigbee.0 folder using WinScp.

2. Did a reboot with Putty, sudo reboot.

3. installed the zigbee adapter and then imported the backup via backitup. Started the adapter and waited 3-4 minutes for everything to load, Zigbee is now green and the devices can be switched on and off.

4. deleted the log and stopped the Zigbee adapter

5. Did a reboot with Putty, sudo reboot.

6. start the Zigbee adapter & wait 2 min. Log file saved via Win SCP, /opt/iobroker/log.
 Adapter light is now orange again 
[iobroker.current.log](https://github.com/ioBroker/ioBroker.zigbee/files/14178162/iobroker.current.log)

**Test 2**
1. i deleted the adapter in iobroker, then deleted the zigbee.0 folder using WinScp.

2. Did a reboot with Putty, sudo reboot.

3. installed the zigbee adapter and then imported the backup via backitup. Started the adapter and waited 3-4 minutes for everything to load, Zigbee is now green and the devices can be switched on and off.

4. cleared the log and stopped the Zigbee adapter
5. remove the CC1352P-2 board from the Pi5
6. restarted the zigbee adapter and plugged the usb cable back in. zigbee adapter remains orange
[iobroker.current.log](https://github.com/ioBroker/ioBroker.zigbee/files/14178447/iobroker.current.log)

I have observed the following. I have noticed that the LED on the CC1352P-2 board goes out briefly when restarting and then lights up again. Shouldn't the firmware then also be restarted?

**Comment by rmp63526** [comment]
@asgothian  any news on this?

**Comment by asgothian** [comment]
I am afraid I had a bit of a problem and was out of order for the last 4 months. Does the problem still persist, or is the situation stable currently ?

**Comment by rmp63526** [comment]
i have just tested it and the errors from back then no longer occur. i can restart the adapter without any problems. unfortunately i don't know what has been changed in the meantime. i have only installed the latest operating system bookworm, as a lot of time has passed in the meantime.

**Comment by rmp63526** [comment]
nehme alles wieder zurück.. Adapter ist wieder nur orange und wird nicht grün

**Comment by rmp63526** [comment]
Hab es endlich gelöst. 
Der Homematic CuxD add on hat sich steandig die USB ports geschnappt. Sobald ich den CuxD deaktiviere gibt er wohl die Ports frei.
So viel Zeit verschwendet wegen so nem .....
