### ISSUE TITLE
New Device already available with zigbee2mqtt.io

### ISSUE THREAD

**Issue by tn1112** [ioBroker/ioBroker.zigbee#2076]
Dear all,

I have a remote control of Paul Neuhaus which is not known in the zigbee adapter. But searching at zigbee2mqtt.io gets the result, that the remote control is already implemented with them. 
So please can you tranfer this item also to your zigbee adapter:
https://www.zigbee2mqtt.io/devices/E0040006.html

Best regards,
Torsten

**Comment by arteck** [comment]
install GIT version and check again
