### ISSUE TITLE
Ikea Tradfri Repeater E1746

### ISSUE THREAD

**Issue by smarti2019** [ioBroker/ioBroker.zigbee#208]
I bought today the Tradfri signal amplifier / repeater E1746. Can I use this adapter as a Zigbee repeater under iobroker?

**Comment by asgothian** [comment]
what happens if you try to pair it ? Does it show up as router in your zigbee network ?

**Comment by smarti2019** [comment]
The pairing  does not work as expected. Under IKEA Tradfri, the repeater is paired with the Tradfri remote control and then the remote control paired devices   An attachment to the coordinator I have not yet succeeded.

**Comment by asgothian** [comment]
Hab da noch was gesehen: anscheinend kann man den repeater mit dem Stick pairen, er ist dann 
„Stiller“ Teilnehmer im Netz, sprich taucht nicht als Objekt auf arbeitet aber sauber als repeater. Siehe auch [hier](url
https://github.com/Koenkk/zigbee2mqtt/issues/1119)

**Comment by smarti2019** [comment]
ok, i have susseccfully paired the Tradfri-Signal-Repeater. Here are the logdate
![grafik](https://user-images.githubusercontent.com/47259711/53289911-f799fa00-379c-11e9-9633-5b48fe1449f3.png)
 info: zigbee.0 26 (0x000d6ffffe9e1219): E1746 - IKEA TRADFRI signal repeater (Router)

**Comment by asgothian** [comment]
Neat.. i'll try to get that one in tomorrow morning.

**Comment by smarti2019** [comment]
where can i find the iobroker.zigbee adapter version of the converter?

**Comment by asgothian** [comment]
its either under /opt/iobroker/node_modules/zigbee-shepherd-converters or under /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd-converters.. best do a tail package.json to see the version

**Comment by smarti2019** [comment]
root@iobroker:/opt/iobroker/node_modules/zigbee-shepherd-converters# tail package.json
  
...    
  "version": "7.1.10"
...

**Comment by asgothian** [comment]
I have integrated the repeater. Please download the repository from 
https://github.com/asgothian/ioBroker.zigbee/tarball/InnrPlug
and check.

**Comment by Smarti15** [comment]
Hello, with me it is unfortunately also indicated. Have the latest version installed 0.9.2

**Comment by smarti2019** [comment]
In the current version 0.9.2 the Tradfri Repeater is again as unknown device with question marks.
I have a raspi completely fresh with iobroker installed because of test of cc2531 and zigbee.

**Comment by smarti2019** [comment]
@asgothian with the branch from you https://github.com/asgothian/ioBroker.zigbee/tarball/InnrPlug all where fine, the repeater works as repeater/router and a logo was OK!

**Comment by asgothian** [comment]
Ok, that is important information. I will double check what happened to the device integration.

A.

**Comment by asgothian** [comment]
Ok.. this does not make sense. I crosschecked all changes. All edits i had done in the above branch were merged into the main 0.9.2 version.
Can you please change back to this version, do an upload and verify that it does / does not work ?

**Comment by smarti2019** [comment]
ok, i just updated again the zigbee github version und make a upload. Now the Tradfri Repeater is normal integrated with logo and states

**Comment by asgothian** [comment]
Perfect. Would you mind closing this issue so that the list gets a bit shorter ?

A.
