### ISSUE TITLE
Upgrade io-package

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.zigbee#2080]
Deprecated:

https://github.com/ioBroker/ioBroker.zigbee/blob/ac216d66a7c0ad590fdf47cf991135724b6c97db/io-package.json#L147

https://github.com/ioBroker/ioBroker.zigbee/blob/ac216d66a7c0ad590fdf47cf991135724b6c97db/io-package.json#L155

Use `adminUI` instead:

```
    "adminUI": {
      "config": "materialize",
      "tab": "materialize"
    },
```

**Comment by arteck** [comment]
hättest uach ein PR machen können

**Comment by arteck** [comment]
done thx
