### ISSUE TITLE
Zigbee Adapter - Instanz löschen und anschließend neu installieren

### ISSUE THREAD

**Issue by StefanHild** [ioBroker/ioBroker.zigbee#2081]
Hallo, ich habe noch so meine Problem mit dem Zigbee-Adapter in der Version v1.10.1.

Betreibe den Adapter an einem Conbee 2 an meinem Raspberry Pi 4.

Hatte lange Zeit lediglich einen Xiaomi Light detection Sensor angeschlossen. Dieser lief bisher ohne Problem und hatte eine gute und stabile Verbindung, obwohl er im Aussenbereich in der Nähe des Raspi wasserdicht angebracht war.

Da man aktuell keinen Xiaomi Light detection sensor mehr kaufen kann, habe ich mir nun noch 2 Aqara T1 Helligkeitssensoren zugelegt und diese beim Adapter angemeldet. Zunächst waren diese während der Installation in der Nähe des Raspi platziert und hatten zunächst eine gute Verbindung.

Habe die beiden Aqara Sensoren  anschliessend auch in den Außenbereich verbracht. Als am Abend meine Rolländen geschlossen wurden, hatte die beiden Aqara Sensoren, die etwas entfernter vom Raspi angebracht sind, nur noch eine Verbindungsqualität von 10%.

Ich hätte erwartet, dass sich dies wieder verbessert, wenn die Rolläden am Morgen geöffnete würden. Dies war allerdings nichtder Fall. Abwohl alle Sensoren Helligkeitswerte anzeigen, wurden Sie im Adapter unter dem Punkt Geräte wechselseitig immer wieder mal mit 100 % und anschließend wieder mit 10% angezeigt, selbst mein Xiaomi Sensor in der Nähe des Raspi. Ausserdem fehlten nun In der Netzwerkanzeige sämtliche Verbindungslinien zum Conbee 2, sowie für die beiden Aquara Sensoren die Bilder/Symbole der Geräte.

Ich habe alle Sensoren nun wieder in die Nähe meines Raspi verbracht, ohne dass eine Besserung eingetreten ist. Alle Geräte zeigen noch 100% Batteriestatus und einen Wert von über 3 Volt an, aber die Verbindung wird bei allen Sensoren weiterhin wechselseitig mit 10% oder 100% angezeigt.

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/36371402/f61b65c8-42b2-4287-a1c7-8f074a5cb468)

Weder ein Neustart des Adapters, des IOBroker oder des Rapi's konnte hier Abhillfe schaffen.

Als letztes habe ich dann versucht, die Zigbee-Instanz zu löschen und neu zu installieren. Die Neuinstallation läuft auch ohne Fehler durch, aber im Raspi taucht nun keine neue Instanz auf weder in der Übersicht links, noch unter den Instanzen selbst.

Zum Glück hatte ich vorher die SD-Karte geclont, sodass ich wieder zurück konnte.

Ich habe auch im Adapter keine Möglichkeit gefunden ein Gerät komplett zu entfernen und neu anzulernen.

Wenn ich das Papierkorb-Symbol auf der Kachel eines Gerätes verwende um ein Sensor zu löschen, wird dieser nicht wirklich entfernt, sondern die Kachel des Gerätes erscheint nun ausgegraut und das Gerät ist lediglich deaktiviert und  man es lässt sich wieder über eine Funktion auf der Kachel aktivieren.

Gruß Stefan

**Comment by arteck** [comment]
und jetzt nochmal .. was willst du mir mitteilen ??
für das Löschen musst du das Geräte aufwecken..  punkt 1
punkt 2. wenn sich der Sensor abmeldet weil der Coordinator nicht mehr erreichbar ist und du keine Router im Netz hast .. was soll der Adapter da machen ?? vor allem wenn die Rolles (bestimmt Alu) das Signal blockieren..

**Comment by StefanHild** [comment]
Danke für deine Rückmeldung,

ich finde, wir können auch mit weniger Polemik und ohne Emotionen mit einander korrespondieren.

Bitte meine Ausführungen nochmals genau lesen, ich habe dort geschrieben:

Alle Sensoren sind nun wieder in der Nähe des Coordinators (Conbee 2). Habe auch die Taste an den Sensoren gerückt, um diese aufzuwecken. Das hat aber leider alles nichts gebracht.

Alu-Rolläden gibt es bei mir nicht, sondern normel Kunstoffrolläden.

Aber die gute Nachricht, nach 2 Tagen und nachdem ich alles mögliche, wie Batterien entfernen und wieder einsetzen, State Cleanup und vielens mehr versucht habe, waren plötzlich wieder alle 3 Sensoren online.

Sieht nun so aus:

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/36371402/36741688-4331-4642-a5aa-e888717c647e)

Ich muss also nun auch nicht, wie vielfach empfohlen auf eine ältere Version des Adapters zurück.

Gruß Stefan
