### ISSUE TITLE
Im Zigbee Adapter bei Einstellungen abspeichern nicht möglich.

### ISSUE THREAD

**Issue by JogiBarbarski** [ioBroker/ioBroker.zigbee#2082]
zigbee.0 2024-02-14 17:51:53.655	 Fehler	 Fehler Hirtenstartv
  zigbee.0 2024-02-14 17:51:53.655	 Fehler	 Zigbee konnte nicht gestartet werden  zigbee.0 2024-02-14 17:51:53.653	 Fehler	 Start des Ziggobee-herdsman-Problems: "Fehler beim Öffnen des Serialports 'Fehler: Fehler Ressource vorübergehend nicht verfügbar Port kann nicht gesperrt werden"  zigbee.0 2024-02-14 17:51:43.271	 Fehler	 Fehler Hirtenstart  zigbee.0 2024-02-14 17:51:43.271	 Fehler	 Zigbee konnte nicht gestartet werden  zigbee.0 2024-02-14 17:51:43.270	 Fehler	 Start-Zigbee-Herdsman-Problem: "Start fehlgeschlagen - Konfigurationsadapter-Nichtpass - siehe Protokolle oben für weitere Informationen"  zigbee.0 2024-02-14 17:51:43.156	 Fehler	 Für die Wiederberennung Ihres Netzwerks ist eine Neukopplung aller Geräte erforderlich!  zigbee.0 2024-02-14 17:51:43.156	 Fehler	 Wenn Sie Ihr Netzwerk erneut in Betrieb nehmen möchten, entfernen Sie bitte das Koordinator-Backup unter /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.  zigbee.0 2024-02-14 17:51:43.156	 Fehler	 Bitte aktualisieren Sie die Konfiguration, um weitere Probleme zu vermeiden. Himbeere PI 4 Händler-ID:	 Debian Beschreibung:	 Debian GNU/Linux 12 (Bücherwurm) Veröffentlichung:	 12 Codename:	 Bücherwurm 6.6.16-v8+ ioBroker.admin v6.13.20 Node.js: v18.19.0 NPM: 10.2.3 js-Controller JS-Controller Installiert: 5.0.19 Betriebssystem: Linux NEUESTE Zigbee Adapter wird nach iob reboot nicht mehr grün. Einstellungen lassen sich nicht abspeichern im Zigbee Adapter.
zigbee.0 2024-02-14 17:51:43.156	 Fehler	 - Kanalliste: configured=13, adapter=13  zigbee.0 2024-02-14 17:51:43.155	 Fehler	 - Netzwerkschlüssel: konfiguriert=01030507090b0d0f00020406080a0c0d, Adapter=01030507090b0d0f00020406080a0c0d  zigbee.0 2024-02-14 17:51:43.154	 Fehler	 - Erweiterte PAN-ID: konfiguriert=00124b00219fb49f, Adapter=00124b00219fb49f  zigbee.0 2024-02-14 17:51:43.153	 Fehler	 - PAN-ID: konfiguriert=6754, Adapter=6754  zigbee.0 2024-02-14 17:51:43.151	 Fehler	 Die Konfiguration stimmt nicht mit dem Adapterstatus/Backup überein!

**Comment by arteck** [comment]
Fehler - Erweiterte PAN-ID: konfiguriert=00124b00219fb49f, Adapter=00124b00219fb49f zigbee.0 2024-02-14 17:51:43.153 Fehler - PAN-ID: konfiguriert=6754, Adapter=6754 zigbee.0 2024-02-14 17:51:43.151 Fehler Die Konfiguration stimmt nicht mit dem Adapterstatus/Backup überein!

das ist dein Fehler

**Comment by JogiBarbarski** [comment]
Ok, und warum ist der Zigbee Adapter jetzt grün und läuft? Nur wenn ich den Raspberry Pi neu starte, wird er nicht mehr grün und dann kann ich im Adapter die Einstellungen nicht mehr speichern. 🤷🏼‍♂️🤷🏼‍♂️
