### ISSUE TITLE
Aqara WXKG02LM_rev2 "Click long event" funktioniert nicht

### ISSUE THREAD

**Issue by surfer-09** [ioBroker/ioBroker.zigbee#2083]
Hallo zusammen,
ich habe festgestellt, dass beim Aqara Doppelschalter (WXKG02LM_rev2) das "Click long event" für rechte und linke Taste nicht funktioniert. Unter Deconz reichten 3 Sekunden aus, damit es auslöste, unter dem Zigbee Adapter passiert gar nichts.

Gruß Dennis

**Comment by arteck** [comment]
zeigmal die Objekte

**Comment by surfer-09** [comment]
Hi,

hat sich jetzt irgendwie doch erledigt - kein Fehler! Bei mir funktioniert es jetzt auch.

![firefox_eXWsEVL8wu](https://github.com/ioBroker/ioBroker.zigbee/assets/106930606/79856567-194f-4dbe-96da-1de6d32e315c)
