### ISSUE TITLE
IKEA Tradfri Shortcut Button -  Firmware downgrade from 24.4.6  possible ?

### ISSUE THREAD

**Issue by Gregor1980** [ioBroker/ioBroker.zigbee#2084]
Is there any possibility to downgrade the firmware of Ikea Tradfri Button from the latest version 24.4.6 to 2.3.079 or 2.3.080? 
If so, how can it be done? 
Unfortunately, Firmware 24.4.6 is causing delays in the response of the buttons.

**Comment by asgothian** [comment]
None that I know of. You might pose the question at zigbee2mqtt.io, as we use their code for the firmware update process.

A.

**Comment by arteck** [comment]
downgrade nope...
