### ISSUE TITLE
Add Aqara Cube T1 pro

### ISSUE THREAD

**Issue by Black-Death-HH** [ioBroker/ioBroker.zigbee#2085]
Hey there, 

is it possible to add the Aqara Cube T1 pro?

https://www.aqara.com/en/product/cube-t1-pro/

Here some data i get:

ieee:0x0x54ef44100093d51d
nwk:53771 (0xd20b)
type:EndDevice
manuf id:4447
interviewed:false
configured:false

Thanks

**Comment by asgothian** [comment]
This should be included in the latest adapter version, unless aqara changed the device ID (again)
See https://www.zigbee2mqtt.io/supported-devices/#v=Aqara&s=Cube
