### ISSUE TITLE
Xiaomi Honeywell Gas Leakage Sensor JTQJ-BF-01LM/BW

### ISSUE THREAD

**Issue by ericsboro** [ioBroker/ioBroker.zigbee#209]
Is there a way to add support of Xiaomi Honeywell Gas Leakage Sensor JTQJ-BF-01LM/BW?

Sensor successfully connected via CC2531 as router, but it was not identified properly: it appeared as "lumi.sensor_natgas", but without Sensor icon in Zigbee adapter. In Objects it appeared as one string without "state" options.

**Comment by ericsboro** [comment]
<img width="288" alt="screen shot 2019-02-22 at 12 48 09" src="https://user-images.githubusercontent.com/4315411/53237779-3eee9080-36a0-11e9-810d-58e46c3108e2.png">
<img width="596" alt="screen shot 2019-02-22 at 12 48 23" src="https://user-images.githubusercontent.com/4315411/53237790-444bdb00-36a0-11e9-9533-e478cf4b224b.png">

**Comment by asgothian** [comment]
Please install my dvlp branch from https://github.com/asgothian/ioBroker.zigbee/tarball/InnrPlug
It should contain the necessary fixes to enable the sensor.

**Comment by ericsboro** [comment]
> Please install my dvlp branch from https://github.com/asgothian/ioBroker.zigbee/tarball/InnrPlug
> It should contain the necessary fixes to enable the sensor.

Hi @asgothian 
Thanks for advise, but it seems that I'm doing something wrong :(
I installed your dvlp branch via UI (Adapters -> Install from custom URL), but it's breaking all my zigbee network (hopefully I have backup for fast restore) and CC2531 stick stops working. 
Please explain how to install your branch if I'm doing it wrong.

Many thanks in advance

**Comment by asgothian** [comment]
Hello,

due to the merge of my branch, you no longer need to install from my branch, but you can install the main tree instead. Keep in mind that an upload is needed after installation.

Should this also cause errors, i would appreciate if you could provide the relevant log information so i can debug what happened and if needed fix it.

A.

**Comment by ericsboro** [comment]
> Hello,
> 
> due to the merge of my branch, you no longer need to install from my branch, but you can install the main tree instead. Keep in mind that an upload is needed after installation.
> 
> Should this also cause errors, i would appreciate if you could provide the relevant log information so i can debug what happened and if needed fix it.
> 
> A.

@asgothian 
thanks for update!
I reinstalled zigbee adapter and now after pairing i see "Device 00158d0001c148c9 "lumi.sensor_natgas" not described in statesMapping." in Log.
Did I do something wrong again? 
I'm not so experienced with iobroker — so would really appreciate some help :)

**Comment by ericsboro** [comment]
@asgothian 
also after iobroker restart I see "13 (0x00158d0001c148c9): JTQJ-BF-01LM/BW - Xiaomi MiJia gas leak detector (Router)" info Log.

**Comment by ericsboro** [comment]
I manager to fix an issue!
Installed zigbee adapter 0.9.2 from github branch and device appeared in the list with all details!
