### ISSUE TITLE
Zigbee Geräte nehmen nur noch on/off an

### ISSUE THREAD

**Issue by Nachtfalke49** [ioBroker/ioBroker.zigbee#2099]
Hallo zusammen,

ich habe seit ein paar Monaten keine Adapter Updates mehr durchgeführt. Als ich mir einen Überblick verschafft hatte, ist mir aufgefallen, dass die Zigbee Geräte zwar noch auf on/off reagieren aber keine Color, Brightness oder Temperature Befehle mehr annehmen. Betroffen sind alle Zigbee Geräte, ob TRADFRI oder Hue Lightsripe.

Im Log ist bei allen Color, Brightness oder Temperature Befehlen immer folgendes zu sehen:

zigbee.0 2024-03-03 19:09:00.634	 error	Send command to 0x680ae2fffed196a4 failed with no error code (undefined)

Als ich einen Zigbee Adapter Update durchführen wollte, ging das nicht, da ich noch nicht auf node.js 18 war. Also habe Ich danach einen kompletten iokroker update einschließlich node.js 18 durchgeführt. 

iobroker info
Platform       : linux
os             : linux
Architecture   : arm64
CPUs           : 4
Speed          : 0 MHz
Model          : Cortex-A72
RAM            : 2.8 GB
System uptime  : 20:43:26
Node.js        : v18.19.1
time           : 1709489807943
timeOffset     : -60
NPM            : 10.2.4
adapters count : 624
Disk size      : 22.9 GiB
Disk free      : 12.9 GiB

Ich verwende den zigbee cc2531 Stick.

Weiß jemand was da mit dem Zigbee Adapter los ist? Vor ein paar Monaten hat es noch ohne Probleme funktioniert.

Gruß

Andi

**Comment by arteck** [comment]
> Ich verwende den zigbee cc2531 Stick.

bitte eine neuere Hardware besorgen.. der cc2531 ist sehr alt und kann zur Problemen führen

**Comment by Nachtfalke49** [comment]
Hallo arteck,

danke für die Info. Das ist für mich neu, dass der CC2531 zu alt ist. Bis vor 3 - 4 Monaten hat er noch funktioniert. Das heißt doch, dass der Zigbee Adapter so aktualisiert wurde, dass der CC2531 nicht mehr im vollen Funktionsumfang verwendet werden kann. Ich bin mit Sicherheit nicht der Einzige der noch den CC2531 verwendet.

Welcher soll des dann werden? Der CC2652  oder SONOFF ZB oder ConBee II oder Zig-zig-ah! oder ZigStar Stick v4 oder Slaesh’s CC2652RB Stick oder Smartlight CC2652P oder Egony Stick v4

Ich habe gerade folgendes gelesen: 

Obwohl ein CC2652 einige relevante Vorteile hat, spricht natürlich nichts gegen die Weiternutzung deines CC2531 oder ConBee II. Wenn du nicht das Gefühl hast, in deinen Ansprüchen limitiert zu sein, sind beides zwar etwas überholte, aber trotzdem noch voll funktionale Gateways.

Der Conbee II fällt dann wohl auch raus und überholt sind dann wohl beide, da der Zigbee Adapter sie nicht mehr voll unterstützt.

Die Limitierung besteht wohl nur in der Anzahl der anlernbaren Geräte. Beim CC2531 sind es wohl 30 und beim CC2652 50 Geräte und die Antenne hat sich von PCB auf SMA geändert. #

Dann wird es wohl der SONOFF ZB werden. Den bekommt man für ca 5 €

Gruß

Andi

**Comment by Nachtfalke49** [comment]
Wie sieht es mit dem EFR32MG21 aus?

**Comment by arteck** [comment]
wenn du hardware Beratung brauchst  dann schau bitte im Forum nach
