### ISSUE TITLE
Flashing cc2530/cc2591 with Arduino

### ISSUE THREAD

**Issue by rocklobster42195** [ioBroker/ioBroker.zigbee#21]
Hi.
I tried to flash a cc2530/cc2591 with an Arduino Uno. It seems that the connection is ok:
```
INFO: Found a CC2530 chip on COM5

Chip information:
      Chip ID : 0xa524
   Flash size : 16 Kb
    Page size : 2 Kb
    SRAM size : 1 Kb
          USB : No

Device information:
 IEEE Address : 000000000000
           PC : 0000

Debug status:
 [ ] CHIP_ERASE_BUSY
 [ ] PCON_IDLE
 [X] CPU_HALTED
 [ ] PM_ACTIVE
 [ ] HALT_STATUS
 [X] DEBUG_LOCKED
 [X] OSCILLATOR_STABLE
 [ ] STACK_OVERFLOW

Debug config:
 [ ] SOFT_POWER_MODE
 [ ] TIMERS_OFF
 [ ] DMA_PAUSE
 [ ] TIMER_SUSPEND
```
But when I tried to flash the `CC2530ZNP-Test_for_CC2591.hex` I got the following error:
`IOError: Line 1: Source file is not in HEX format!` Do I need a special version for an arduino-flash?

Thanks for your help.
Boris

**Comment by kirovilya** [comment]
You need to download the firmware file in raw format https://github.com/kirovilya/files/blob/master/CC2530ZNP-Test_for_CC2591.hex

**Comment by kirovilya** [comment]
Or download zip-archive of all repo and extract one file from it

**Comment by kirovilya** [comment]
RAW https://raw.githubusercontent.com/kirovilya/files/master/CC2530ZNP-Test_for_CC2591.hex

**Comment by rocklobster42195** [comment]
Thanks. Now I get this error:
```
INFO: Found a CC2530 chip on COM5

Chip information:
      Chip ID : 0xa524
   Flash size : 16 Kb
    Page size : 2 Kb
    SRAM size : 1 Kb
          USB : No
Traceback (most recent call last):
  File "cc_write_flash.py", line 48, in <module>
    hexFile.load()
  File "D:\temp\CCLib\Python\cclib\cchex.py", line 128, in load
    self._loadHex()
  File "D:\temp\CCLib\Python\cclib\cchex.py", line 367, in _loadHex
    raise IOError("Line %i: Unknown record type %02x" % (i, bType))
IOError: Line 14140: Unknown record type 05
```

**Comment by kirovilya** [comment]
Oh! I forgot... For Arduino you need modify firmware by removing second line from the end of file.

**Comment by rocklobster42195** [comment]
I did that.
```
Chip information:
      Chip ID : 0xa524
   Flash size : 16 Kb
    Page size : 2 Kb
    SRAM size : 1 Kb
          USB : No
Sections in CC2530ZNP-Test_for_CC2591.hex:

 Addr.    Size
-------- -------------
 0x0000   6 B
 0x002b   3 B
 0x0043   3 B
 0x0053   3 B
 0x006b   3 B
 0x0083   32626 B
 0x7ff8   7 B
 0x8000   32762 B
 0x10000   32762 B
 0x18000   32739 B
 0x20000   32751 B
 0x28000   32702 B
 0x30000   29675 B

ERROR: Data too bit to fit in chip's memory!
```

**Comment by kirovilya** [comment]
Hmm...  Strange... Sorry, I never flash cc2530/cc2591 from Arduino, only cc2530 and cc2531.
I try to find solution...

**Comment by rocklobster42195** [comment]
Thank you very much! No need to hurry!

**Comment by kirovilya** [comment]
Try to comment lines 67, 68, 69 in cc_write_flash.py:
```
# if maxMem > (dbg.chipInfo['flash'] * 1024):
# 	print("ERROR: Data too bit to fit in chip's memory!")
# 	sys.exit(4)
```

**Comment by rocklobster42195** [comment]
It is flashing!
Now we have to wait...

**Comment by kirovilya** [comment]
If flashing is success, before using you need connect P04, P06, P20 to GND

**Comment by rocklobster42195** [comment]
Unfortunately I only have a bad manual for my device. The pins are only labeled P1_2, P1_4...etc. 
![unbenannt](https://user-images.githubusercontent.com/13438315/42705927-4bac70e2-86d5-11e8-86b2-1a4525a81c72.PNG)

Is there a common assignment?

**Comment by kirovilya** [comment]
Yes. You need connect P0_4 and P0_6 and P2_0 to GND

**Comment by rocklobster42195** [comment]
Aaaaah. Stupid me! :-D
IT'S WORKING!
Thank you.
