### ISSUE TITLE
No support for Xiaomi Vima Smart Lock device .

### ISSUE THREAD

**Issue by Swat79** [ioBroker/ioBroker.zigbee#210]
Hello,
actually there is no support for the Xiaomi Vima Smart Lock device.
In Zigbee2MQTT it seems to be supported. Its possible to add this device too?
Regards Sören

**Comment by GermanBluefox** [comment]
I want to add the debug output: 
```
Device 00158d00028e2e08 "lumi.lock.v1" not described in statesMapping.
User stateChange zigbee.0.info.pairingMessage {"val":"New device joined 0x00158d00028e2e18 model lumi.lock.v1","ack":false,"ts":1550838290258,"q":0,"from":"system.adapter.zigbee.0","lc":1550838290258}
User stateChange zigbee.0.info.pairingMessage {"val":"Interview state: step 1/1. progress: 100%","ack":false,"ts":1550838290252,"q":0,"from":"system.adapter.zigbee.0","lc":1550838290252}
2019-02-22T12:24:50.261Z zigbee-shepherd Device: 0x00158d00028e2e18 already in network
Message without data cluster!
2019-02-22T12:24:50.260Z zigbee:controller debug Message without data cluster! undefined
handleMessage. {"type":"devStatus","endpoints":[{"device":{"_id":32,"type":"Router","ieeeAddr":"0x00158d00028e2e08","nwkAddr":5543,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"
2019-02-22T12:24:50.258Z zigbee:controller debug handleMessage { type: 'devStatus', endpoints: [ Endpoint { isLocal: [Function], device: [Object], profId: 260, epId: 1,
new dev 0x00158d00028e2e18 5543 lumi.lock.v1
```

**Comment by asgothian** [comment]
As far as i see it in zigbee-shepherd-converters, the lock can be integrated to detect key use, but cannot be used to lock or unlock the door, nor to program the lock. It can only detect which keys are being used.

See here: 
    {
        zigbeeModel: ['lumi.lock.v1'],
        model: 'A6121',
        vendor: 'Xiaomi',
        description: 'Vima Smart Lock',
        supports: 'inserted, forgotten, key error',
        fromZigbee: [fz.xiaomi_lock_report, fz.ignore_basic_change],
        toZigbee: [],
    },

Due to the limited use of this information (and the fact that i do not have said lock), i will hold off on working on the integration into ioBroker.zigbee until more of the functions of the lock are supported within the zigbee-shepherd.

**Comment by GermanBluefox** [comment]
I have been implemented anyway this lock :)

**Comment by ingod68** [comment]
Is it possible to lock/unlock it from ioBroker ?

**Comment by kirovilya** [comment]
@ingod68 Vima Smart Lock does not support lock/unlock
