### ISSUE TITLE
New IKEA Device Smart Plug TRETAKT

### ISSUE THREAD

**Issue by Interflexus** [ioBroker/ioBroker.zigbee#2102]
Pls add the Device,

![Screenshot 2024-03-09 172644](https://github.com/ioBroker/ioBroker.zigbee/assets/123006550/d22cb94a-49a3-4fb9-8187-60d002cbf31f)

**Comment by bluefish007** [comment]
You can install the Zigbee adapter from github. With this version you get "zigbee-herdsman-converters": "18.43.0". The Tretakt is already supported since zigbee-herdsman-converter v18.29.0 ;)
Only the preview image is still missing, but you can already control it!

**Comment by Interflexus** [comment]
OK. Thx, it works fine.
  

  

  

  
  
  
  
  
>
