### ISSUE TITLE
Bewässerungsuhr

### ISSUE THREAD

**Issue by KL1801** [ioBroker/ioBroker.zigbee#2103]
Hallo,

Ich habe folgende Bewässerungsuhr von iex-perience bestellt.

https://de.aliexpress.com/item/1005006549008401.html?spm=a2g0o.order_list.order_list_main.4.50115c5foaS9ry&gatewayAdapt=glo2deu

Wollte gerade hinzufügen, aber ich bekomme nur die Link quality etc., aber nichts zum steuern.

Kann es hinzugefügt werden?

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/18719162/7dc8b63c-06e3-479f-9c67-69824cc1c59e)

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/18719162/0ca046c6-715b-4fbb-af22-b50be55c83f6)

Das wäre echt klasse! :) Die Gartensaison geht bald los :D

Viele Grüße!

**Comment by christhanksu** [comment]
Ich wäre auch sehr daran interessiert. Unter Home Assistant läuft es bereits unter Z2M. Kann gerne den entsprechenden Link posten wenn das hilft?!

**Comment by christhanksu** [comment]
Hier gibt es auch eine Anleitung für die Integration in Home Assistant. Hoffe das hilft auch für eine mögliche Lösung für IB:
[https://antrow.de/company/blog/blog.aspx](url)

**Comment by KL1801** [comment]
> Hier gibt es auch eine Anleitung für die Integration in Home Assistant. Hoffe das hilft auch für eine mögliche Lösung für IB: [https://antrow.de/company/blog/blog.aspx](url)

Hi,
Also die Entwickler waren schon fleißig!
Ich habe vor ca. 2-3 Wochen ein Update des zugebe Adapters gemacht und seitdem funktioniert die bewässerungsuhr bei mir!

Vielen Dank an die Entwickler! 👍 :)

**Comment by christhanksu** [comment]
Top, super dann kann ich ja endlich bestellen!

**Comment by asgothian** [comment]
Kann einer von euch beiden bestätigen das das Gerät funktioniert, dann können wir den Issue hier schliessen

**Comment by christhanksu** [comment]
Funktioniert…vielen Dank nochmal!
