### ISSUE TITLE
New Device IKEA LED2109G6

### ISSUE THREAD

**Issue by Tobi4** [ioBroker/ioBroker.zigbee#2116]
New Ikea Device. LED 800lm Bulb
![Screenshot 2024-04-12 221312](https://github.com/ioBroker/ioBroker.zigbee/assets/50216483/404607aa-f4ab-473f-ba01-cdd17c1c8bf1)

**Comment by asgothian** [comment]
Please test with the current GitHub version

**Comment by asgothian** [comment]
Supported now
