### ISSUE TITLE
Xiaomi LYWSD03MMC Zigbee Tempsensor - please add

### ISSUE THREAD

**Issue by MaZchen** [ioBroker/ioBroker.zigbee#2120]
I followed the instructions in issue https://github.com/ioBroker/ioBroker.zigbee/issues/1929

After flashing and pairing it got identified as LYWSD03MMC-z with the error message explained at the bottom of issue #1929. 

I followed then @xtraxion explanations (creating a file "lywsd03mmc.js"). After restarting the instance it threw an error "the code does not run: TypeError: batteryPercentage is not a function"

I then removed all instances of "batteryPercentage" in the file, restarted the instance and the error was gone.

After re-pairing the sensor got identified correctly! (w/o battery status of course)

Still, it would be easier if the adapter could support the device natively. PLEASE.

Adapter v1.10.3
Conbee 2

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/93379596/2268b6d8-86a8-4b61-ae65-a317114801af)

**Comment by MaZchen** [comment]
Seems, I got the wrong firmware.

With the steps discribed here "https://github.com/devbis/z03mmc/?tab=readme-ov-file" it works without any fiddling.
https://github.com/devbis/z03mmc/?tab=readme-ov-file

**Comment by MarkStephan89** [comment]
hi, 
sorry activate these....
I flashed the firmware from  https://github.com/pvvx/ATC_MiThermometer

But it do not work: (iobroker.zigbee v1.10.9 / git)
![image](https://github.com/user-attachments/assets/34109b4c-c82a-47ac-8145-d17734cc8dc0)
![image](https://github.com/user-attachments/assets/2fb3df29-dd9a-44be-b099-715553169edd)

any chance to get these to work?

I think I must use these firmware?: https://github.com/devbis/z03mmc

Many Thanks!
