### ISSUE TITLE
New Device Xiaomi Thermometer LYWSD03MMC

### ISSUE THREAD

**Issue by Knoddel** [ioBroker/ioBroker.zigbee#2121]
This is actually a Bluetooth temperature sensor with custom firmware that now uses Zigbee.
https://github.com/atc1441/ATC_MiThermometer?tab=readme-ov-file
![Screenshot 2024-04-22 134251](https://github.com/ioBroker/ioBroker.zigbee/assets/53978522/cccb2e38-561c-458b-a8dd-9d405aeb91ad)

**Comment by dimaiv7** [comment]
> This is actually a Bluetooth temperature sensor with custom firmware that now uses Zigbee. https://github.com/atc1441/ATC_MiThermometer?tab=readme-ov-file ![Screenshot 2024-04-22 134251](https://private-user-images.githubusercontent.com/53978522/324447570-cccb2e38-561c-458b-a8dd-9d405aeb91ad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTI0OTksIm5iZiI6MTcxMzc5MjE5OSwicGF0aCI6Ii81Mzk3ODUyMi8zMjQ0NDc1NzAtY2NjYjJlMzgtNTYxYy00NThiLWE4ZGQtOWQ0MDVhZWI5MWFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEzMjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNTIwZmJiMzAwYTYzNzk2NzNmOGMxZDNkOGYyOTVjNzI1NzFjOTUzNWEyMTI5NzJjOWVlNWNjZjkyZTE5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QMyuROwn2r2CCXLt7EP4JM2mpgmGRqSWB2TG5memt7s)

Wenn man eine richtige Firmware drauf macht dann funktioniert es.
guck hier:
[Iobroker Forum](https://forum.iobroker.net/post/1150569)
