### ISSUE TITLE
Group brightness does not effect the switch state

### ISSUE THREAD

**Issue by Domepo** [ioBroker/ioBroker.zigbee#2123]
I've found a bug in the group handling.
If you change the brightness of a group that is in an off state, the lamps will turn on but the switch state will remain off.

# Assets
1. Lamp group is off
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/36802235/ed447579-20ba-444c-8e8d-2d18c7ff77ad)
2. Changing brightness -> lamps turn on  (switch state stays off)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/36802235/27270658-745f-4478-ac9c-74163ff761cd)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/36802235/083765e0-e33f-401c-b2df-7ee1c8cea30d)
# Versions
Zigbee: 1.10.3
Node: v18.13.0
NPM: 9.2.0

**Comment by arteck** [comment]
this is normal.. 
when you have 5 bulbs in the group but only 3 is on.. is the group then on ?? or not ...
