### ISSUE TITLE
New Device: Xiaomi Mi Temperature-and Humiditymonitor 2

### ISSUE THREAD

**Issue by Hans-JR** [ioBroker/ioBroker.zigbee#2124]
![Thermometer_Zigbee](https://github.com/ioBroker/ioBroker.zigbee/assets/37930673/be67ded9-40bd-4db8-bafb-ec3c5290178d)
This unit is already available in Zigbee2Mqtt
![Zigbee2Mqtt](https://github.com/ioBroker/ioBroker.zigbee/assets/37930673/ff458bca-a601-4034-ad7f-f5cb9d465cb6)
Stefan from "verdrahtet" explaines how to convert the original unit to a Zigbee device. 
https://www.youtube.com/watch?v=X2H0RRtA5nI&t=119s

**Comment by Voodoo2man** [comment]
Got the same delivered today. Would be great if it could be supported in iobroker.

**Comment by benbensimpson** [comment]
falsche software für iobroker geflasht mit der z03mmc läuft es bei mir 
hier auch zum nachlesen 
[https://forum.iobroker.net/topic/71438/zigbee-neue-version-1-9-x/95?_=1714208514765](url)

**Comment by Voodoo2man** [comment]
Komme von der Firmware nicht mehr weg. Daher wäre es super, wenn die Version unterstützt werden würde.

**Comment by Hans-JR** [comment]
Also, ich habe auch mehrmals versucht, eine andere Software zu laden, allerdings ohne Erfolg. Ich habe es über den Unix Programmer und via Windows per TTL-USB Adapter gemacht. Als Software habe ich die Version 1.1.0 vom 4. Feb. genommen (z03mmc.bin).  Jetzt bekomme ich das Gerät nícht einmal mehr gekoppelt.

**Comment by dimaiv7** [comment]
Hallo Leute.
Hier geht es um Zigbee Adapter. Nicht um die Sensoren Umbau/Umprogrammierung.
Der o.g. Sensor funktioniert schon lange mit der richtige Firmware und Zigbee Adapter einwandfrei.
Danke für Verständnis.
