### ISSUE TITLE
New Device: Innr E14 LED RB 243

### ISSUE THREAD

**Issue by Fette-Hexe** [ioBroker/ioBroker.zigbee#2135]
Guten Morgen,
bitte die Innr E14 hinzufügen
![Screenshot 2024-05-23 091804](https://github.com/ioBroker/ioBroker.zigbee/assets/170607070/6c5ad9f8-3eaa-4321-b752-1b413b0dff26)

Danke für eure Arbeit.

**Comment by asgothian** [comment]
Please test with the current GitHub Version.

**Comment by asgothian** [comment]
should be supported now
