### ISSUE TITLE
Failed to check if update available

### ISSUE THREAD

**Issue by vaaarg** [ioBroker/ioBroker.zigbee#2136]
As soon as i check for firmware updates i get these logs.

`Zigbee: 1.10.3
Plattform:
linux
RAM:
7.8 GB
Node.js:
v18.20.3
time:
1716868746086
NPM:
10.7.0
Aktive Instanzen:
17
Pfad:
/opt/iobroker/
Betriebszeit:
5 T. 07:54:22`

`<html>
<body>

zigbee.0 | 2024-05-28 06:17:20.583 | info | Failed to check if update available for '0xa4c1381a6180a02a' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
-- | -- | -- | --
zigbee.0 | 2024-05-28 06:17:20.582 | info | Failed to check if update available for '0xa4c13832d89335c4' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.582 | info | Failed to check if update available for '0x30e8e40000d2d758' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.541 | info | Failed to check if update available for '0x18fc2600000d8ff5' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.540 | info | Failed to check if update available for '0x0017880104f6c956' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.539 | info | Failed to check if update available for '0x84fd27fffe03e9b3' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.538 | info | Failed to check if update available for '0x04cf8cdf3c7b1b26' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.536 | info | Failed to check if update available for '0x0017880103e54b5a' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.509 | info | Device zigbee.0.00158d0009cf85bc is marked unavailable, skipping...
zigbee.0 | 2024-05-28 06:17:20.507 | info | Failed to check if update available for '0x04cf8cdf3c7b19cc' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.507 | info | Failed to check if update available for '0x00178801031179a4' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.506 | info | Failed to check if update available for '0x0017880103798347' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.504 | info | Failed to check if update available for '0xa4c138d8c30dc828' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.503 | info | Failed to check if update available for '0x04cf8cdf3c7b2b5f' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.498 | info | Failed to check if update available for '0xa4c1380d9eb32217' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.494 | info | Failed to check if update available for '0x04cf8cdf3c7e551a' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.493 | info | Failed to check if update available for '0x0017880103119b76' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.486 | info | Failed to check if update available for '0xa4c1384cb03e7989' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:20.481 | info | Failed to check if update available for '0xa4c138b5084aa5c3' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
zigbee.0 | 2024-05-28 06:17:18.158 | info | List of port: [{"path":"/dev/ttyAMA0"},{"path":"/dev/ttyACM0","manufacturer":"Texas Instruments","pnpId":"usb-Texas_Instruments_CC2538_USB_CDC-if00","vendorId":"0451","productId":"16c8"},{"path":"/dev/ttyAMA10"},{"path":"/dev/ttyS0"}]

</body>
</html>`

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/2115
