### ISSUE TITLE
Tradfri Plugs new device each time after reboot

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.zigbee#214]
Each time after reboot raspberry (and even while running) the tradfri plugs shown in the log like new devices, but they are known units.

Can somebody tell me why?

The screenshot shows just the tradfri plugs, my other units (mostly from Xiaomi) works perfect.

![zigbee](https://user-images.githubusercontent.com/42386692/53362291-197cb380-393a-11e9-948d-7bfd4ed448d6.jpg)

**Comment by kirovilya** [comment]
It is "norma" for routers

**Comment by Michaelnorge** [comment]
Really? 
Ok, thank you!
