### ISSUE TITLE
Ikea VINDSTYRKA E2112

### ISSUE THREAD

**Issue by Sascha8** [ioBroker/ioBroker.zigbee#2145]
Hi,
with 1.10.2 the Ikea VINDSTYRKA works fine. With 1.10.3 and 1.10.4 the state "pm25" will not be refreshed anymore. But in state "msg_from_zigbee" I receive every 2 minutes the right telegram with the correct value:

{"type":"attributeReport","data":{"measuredValue":11},"linkquality":163,"groupID":0,"cluster":"pm25Measurement","meta":{"zclTransactionSequenceNumber":122,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}

Please fix. Thx!

**Comment by mark77-DE** [comment]
same here.

**Comment by SeniorCatweazle** [comment]
Hello everyone,

I can confirm the error. In version 1.10.2 the value pm25 is displayed in version 1.10.4 no longer.

**Comment by asgothian** [comment]
Please test with the current GitHub version.

**Comment by OneCreek** [comment]
> Please test with the current GitHub version.

Works for me now:)
