### ISSUE TITLE
Added TuYa TS0601_soil sensor

### ISSUE THREAD

**Issue by DEHTIRE** [ioBroker/ioBroker.zigbee#2148]
Can you please add the following Tuya TS0601 sensor?

if that helps: https://www.zigbee2mqtt.io/devices/TS0601_soil.html

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/143749314/62605c56-a6f8-4135-8f18-6fcf7cb7c1f2)

**Comment by mblass** [comment]
Yes, please do so.
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/91893325/f2dfcb91-2638-405c-a1e4-e8d08a0ca99f)

**Comment by asgothian** [comment]
Please install the current version from GitHub - it should support the sensor.

A.

**Comment by mblass** [comment]
I've installed 1.10.4 from Github. In advance I deleted my old exclusion of TS0601. I deleted the existing devices "Feucht Rosenbogen" and "Feucht "Garten". Then I paired them again. Log said "Interview successful".
After waiting >30 min, I got
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/91893325/e2837dfb-4590-4425-a3e3-62afa3682beb)
and
<img width="662" alt="image" src="https://github.com/ioBroker/ioBroker.zigbee/assets/91893325/f25674d4-2d4d-4513-b297-5997808cb07b">
So both temp are zero and only one moisture is more than zero !?
How to proceed?

**Comment by asgothian** [comment]
you need to verify which values are published by the device. the easiest method is to enter `aabcef2;a7c0802` into the state  `zigbee.0.info.debugmessages`, then wait for a while and check the log for warn messages with the keyword "ELEVATED". There should be 2 messages for every value the sensor publishes to ioBroker.

A.

**Comment by mblass** [comment]
[ELEVATED.docx](https://github.com/user-attachments/files/15858741/ELEVATED.docx)
Datapoints are still 0 / 0 and 0 / 29

**Comment by asgothian** [comment]
Please post the log into the comment, not as a proprietary document (which I cannot open).
If there is no entry for aabcef2, then the coordinator does not receive any data from the device. This can have any number of reasons. I would attempt to reconfigure the device from the device tile.

For the second device, if you read the text of the messages, you should be able to tell if the 0 values for the temperature are sent from the device or not.

A.

**Comment by mblass** [comment]
Ok, thanks.
It seems that temperature was sent, but 0 is of course wrong (Germany, Berlin, summer ;-))
There is a third device of this type which works fine.
What should I do in detail to delete the two "wrong" devices completely and re-pair them?

zigbee.0	2024-06-16 16:08:30.078	warn	ELEVATED publishToState: value generated '"high"' from device a4c13815fa7c0802 for 'State of the battery'
zigbee.0	2024-06-16 16:08:30.078	warn	ELEVATED publishToState: message received '{"battery_state":"high"}' from device a4c13815fa7c0802 type 'TS0601_soil'
zigbee.0	2024-06-16 16:08:30.076	warn	ELEVATED publishToState: value generated '134' from device a4c13815fa7c0802 for 'Link quality'
zigbee.0	2024-06-16 16:08:30.076	warn	ELEVATED publishToState: message received '{"linkquality":134}' from device a4c13815fa7c0802 type 'TS0601_soil'
zigbee.0	2024-06-16 16:08:29.964	warn	ELEVATED publishToState: value generated '100' from device a4c13815fa7c0802 for 'Battery percent'
zigbee.0	2024-06-16 16:08:29.964	warn	ELEVATED publishToState: message received '{"battery":100}' from device a4c13815fa7c0802 type 'TS0601_soil'
zigbee.0	2024-06-16 16:08:29.842	warn	ELEVATED publishToState: value generated '29' from device a4c13815fa7c0802 for 'Measured soil moisture value'
zigbee.0	2024-06-16 16:08:29.842	warn	ELEVATED publishToState: message received '{"soil_moisture":29}' from device a4c13815fa7c0802 type 'TS0601_soil'
zigbee.0	2024-06-16 16:08:29.756	warn	ELEVATED publishToState: value generated '0' from device a4c13815fa7c0802 for 'Temperature'
zigbee.0	2024-06-16 16:08:29.755	warn	ELEVATED publishToState: message received '{"temperature":0}' from device a4c13815fa7c0802 type 'TS0601_soil'
zigbee.0	2024-06-16 16:33:54.442	warn	ELEVATED publishToState: value generated '29' from device a4c13815fa7c0802 for 'Measured soil moisture value'

**Comment by asgothian** [comment]
Deleting and re-pairing the device will do nothing for the ..a7c0802 Device, as it actively reports 0 Degrees as temperature. This is no software issue. I would assume that you have a device with a broken temperature sensor. You can attempt to enter the value `{"temperature_calibration" : 2}` into the send_payload and see if the reported temperature changes. Similarly, you can modify the precision for the temperature by sending `{"temperature_precision":3}`

For the ..aabcef2 device, it may make a difference to attempt to reconfigure the device using this button: (note - different device, I don't have any of those)
<img width="312" alt="Screenshot 2024-06-16 at 19 02 57" src="https://github.com/ioBroker/ioBroker.zigbee/assets/45667167/f85e016a-f76e-4759-9ea3-0cda7b46e3dc">

**Comment by mblass** [comment]
I'll check and try to delete. Thanks a lot for your effort.
