### ISSUE TITLE
Aktualisiert keine Werte mehr

### ISSUE THREAD

**Issue by soRailicious** [ioBroker/ioBroker.zigbee#215]
Leider aktualisieren sich seit X Tagen keine Werte mehr. Gestern Geräte neu angelernt und nahe hingestellt. Es funktioniert maximal 1x und danach aktualisiert sich überhaupt nichts mehr. Liegt dies an diesem Plugin oder dem CC2531? Wie kann ich das testen? Ich verwende hauptsächlich Xiaomi devices.

**Comment by arteck** [comment]
und was soll ich mit dieser Information anfangen ?? 

Version von 
system ??
js-controller ??
adapter ??

und vor allem genau WAS LÄUFT NICHT..und was wurde gemacht
