### ISSUE TITLE
TuYa 0601 mmWave Präsenzmelder PIR & 24G Radar

### ISSUE THREAD

**Issue by morhartphilipp** [ioBroker/ioBroker.zigbee#2150]
Hallo liebes Entwicklerteam,

ich habe mir folgenden mmWave Präsenzmelder mit PIR und 24G Radar auf AliExpress gekauft. 

https://de.aliexpress.com/item/1005006903667665.html?spm=a2g0o.order_list.order_list_main.10.11eb5c5f7myPOw&gatewayAdapt=glo2deu

Integration mit dem Zigbee Adapter hat auch funktioniert und die Lichtstärke kann schon ausgelesen werden ;)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/46656648/316ac3ea-6cb7-4d94-8d48-a60365160c22)

Leider bleibt der Status der Präsenzerkennung immer auf "true" stehen.

Handelt es sich dabei um einen Bug oder ist der Sensor einfach noch nicht integriert?

Besten Dank vorab & viele Grüße
Philipp

**Comment by asgothian** [comment]
Ich konnte das Gerät nicht bei zigbee2mqtt.io als "supported" finden. Dementsprechend ist davon auszugehen das die Integration zumindestens unvollständig ist und da erst vervollständigt werden muss.

A.

**Comment by asgothian** [comment]
Please test with the current Github Version if the device is supported.

A.

**Comment by asgothian** [comment]
should be supported

**Comment by morhartphilipp** [comment]
Tested with v.1.10.5 and still "presence" is not changing.
![image](https://github.com/user-attachments/assets/df49530d-9aa7-412e-8d4f-f92c6b3675ba)

But now it is possible to choose between pir, pir and radar or radar only.

**Comment by asgothian** [comment]
Please verify that the device received its "configuration" after pairing. If need be, trigger a configuration by using the configure button on the device tile
<img width="277" alt="Screenshot 2024-07-18 at 06 35 02" src="https://github.com/user-attachments/assets/c61754c6-94b4-47d2-85c0-024e2fa478d1">
Keep in mind that you may need to keep the device awake during reconfiguration.

**Comment by morhartphilipp** [comment]
Thanks for the information. I think the configuration is not working because if I click on the "?" box the configured option is on false:

![image](https://github.com/user-attachments/assets/5986072b-5181-407e-aabf-c7d6e2de033f)

I tried to keep the device awake but it does not change.

In the object tree I see the chaging of the mode, for example from pir to pir and radar:
![image](https://github.com/user-attachments/assets/1e4955cc-b18c-47c1-839b-dddd3b42e603)

Also the new adding and afterwards configuration does not work.

Any other idea to try?
