### ISSUE TITLE
Xiaomi Mi Temperatur-und Feuchtigkeitsmonitor

### ISSUE THREAD

**Issue by Duffy987** [ioBroker/ioBroker.zigbee#2152]
Hallo geschätzte Entwickler,

ich habe mir das Xiaomi Mi Temperatur-und Feuchtigkeitsmonitor 2, Kunststoff,, Weiß, 43 mm bei Amazon gekauft:

https://www.amazon.de/dp/B08C7KVDJW?psc=1&ref=ppx_yo2ov_dt_b_product_details

Dieses habe ich über diese Anleitung für Zigbee umgeflasht:

https://www.youtube.com/watch?v=X2H0RRtA5nI&ab_channel=verdrahtet

Im Zigbee Adapter wurde das Gerät nun auch erkannt aber es sind wohl noch keine weiteren Daten dafür hinterlegt.

![Thermometer](https://github.com/ioBroker/ioBroker.zigbee/assets/120317770/923010d2-39ac-4435-9b7a-729ea773dae0)

Wäre es wohl möglich auch dieses Thermometer zu hinterlegen?

Danke schon jetzt für eure Bemühung. 

Duffy987

**Comment by Duffy987** [comment]
https://www.zigbee2mqtt.io/devices/LYWSD03MMC-z.html

**Comment by asgothian** [comment]
Please test if the current GitHub version supports this device.

A.

**Comment by Duffy987** [comment]
Klasse funktioniert.
Danke.

Gruß Duffy987
