### ISSUE TITLE
Add unreachable filter

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#2162]
It would be cool to have a filter in the frontend that hides all accessible devices so that you can quickly get an overview of the ones that don't work.

**Comment by asgothian** [comment]
Please be more specific. What do you call "inaccessible". What is the characteristic to be used for this filter ?

A.

**Comment by ldittmar81** [comment]
A filter to show only devices with available false to be easier to see when something is wrong.

**Comment by asgothian** [comment]
I am not sure I follow your line of thought.
If you keep the zigbee-tab open, it will not update when the availability of a device changes, as the filter requires user intervention.
If you open the zigbee-tab, a filter like this should be possible, though. It would still require manual checking if a device is available.

What I can imagine integrating:
a state `offlinedevices` under `zigbee.x.info` which contains a JSON array (stringified) of the ID's of all devices which are currently listed as offline.

A.

**Comment by ldittmar81** [comment]
My point is that when I open the overview and have around 200 devices, I can immediately see which devices are not available and, if necessary, get them working again.
The offline device thing at zigbee.x.info is also a cool idea. I use a script that runs every 5 minutes `state[role=indicator.maintenance.unreach][id='alias.0.*']` which gives me all the devices that are not available.

**Comment by asgothian** [comment]
Sounds good. I just wanted to make sure that it is clear  what can be implemented and what can’t. I’ll have a look and see how far I get on the weekend.

**Comment by asgothian** [comment]
Please install and test from my test fork
https://github.com/asgothian/ioBroker.zigbee/tarball/master

Note - the sorting by kind and status is still WiP - it is not working (yet)

A.

**Comment by asgothian** [comment]
Any chance for you to test this ? As it stands now, the sorting by kind and status will be removed - I cannot seem to find an easy way to get it to work.

A.
