### ISSUE TITLE
Add support for for EmberZNet v8.0.0

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#2163]
Support for EmberZNet v8.0.0 was added with zigbee-herdsman v0.51.0

**Comment by asgothian** [comment]
So ?

Why is this important / sensible ?
Do we need EmberZNet v8.0.0 ?

A.

**Comment by ldittmar81** [comment]
We need it to be able to use the new firmware for silicon labs coordinator.

**Comment by asgothian** [comment]
Please fork, patch and test the adapter. If it runs on your side, feel free to give me a link so I can crosscheck with other coordinators for effects. If not, point me to where I can have a look at the bugs so we can see if they can easily be squashed.

Once that is done successfully, you can generate a PR from the fork and we can pass that through.

I do not have a device to check this, so I am very hesitant to bump the herdsman randomly without additional checks.

A.

**Comment by asgothian** [comment]
Please test with the current GitHub version - zigbee-herdsman dependency was bumped up.

A.

**Comment by ldittmarNGDA** [comment]
Test done. It works fine. I tested with my SMLIGHT SLZB-07 coordinator based on the efr32mg21 from Silicon Labs. Both previously paired devices and new pairings worked fine.

**Comment by ldittmar81** [comment]
Test done. It works fine. I tested with my SMLIGHT SLZB-07 coordinator based on the efr32mg21 from Silicon Labs. Both previously paired devices and new pairings worked fine.

**Comment by asgothian** [comment]
Did you use the v8.0.0 firmware on the coordinator ?

**Comment by ldittmar81** [comment]
Sorry... no... I will try it this weekend. I tested it with v7.4.1.

**Comment by asgothian** [comment]
Complete
