### ISSUE TITLE
ZG-205Z/A will detect as TS0601

### ISSUE THREAD

**Issue by BassT23** [ioBroker/ioBroker.zigbee#2164]
Hi,

after sucsessfully use an ZG-205Z/A, I baught 2 more.
But now these two devices will detect in iobroker as TS0601???

How to fix this?

This:
![Screenshot_20240711_190900_Chrome.jpg](https://github.com/ioBroker/ioBroker.zigbee/assets/30832786/52722df6-a58f-4bcf-a799-9a81ba34a1a6)

should be this:

![Screenshot_20240711_190840_Chrome.jpg](https://github.com/ioBroker/ioBroker.zigbee/assets/30832786/95d97118-f109-4d33-89dd-fd276f305c06)

iobroker.zigbee Adapter is on latest v1.10.5

**Comment by BassT23** [comment]
Searched a bit deeper; the first device was an ZG205Z

The 2 new one - seems to be a cheep copy. The Device Number is: RTCZ05Z

This device seems not supported in zigbee2mqtt. It is not listed there

**Comment by asgothian** [comment]
Welcome to the Mess that is TuYa.

This needs to be fixed on the zigbee-herdsman-converters. We can't do much without a device.

A.

**Comment by BassT23** [comment]
I send the two "fake" sensors back and baught correct ZG-205Z :)

**Comment by dfsx1** [comment]
Support for `RTCZ05Z` (`_TZE204_dapwryy7`) 5.8 GHz human presence sensor is added last week: 
https://github.com/Koenkk/zigbee-herdsman-converters/commit/23336fec5e7b15d9eb20f97ba0225c54e9095934
You need at least `v19.68.0`:
https://github.com/Koenkk/zigbee-herdsman-converters/releases/tag/v19.68.0
It's not yet merged to `zigbee2mqtt` `master` but you can use `dev` branch until next release:
https://github.com/Koenkk/zigbee2mqtt/tree/dev
