### ISSUE TITLE
GLEDOPTO GL-B-001Z please add

### ISSUE THREAD

**Issue by SroBu** [ioBroker/ioBroker.zigbee#217]
Hi,

is the GL-B-001Z included too?
zigbee Version 0.9.2 (installed from github, Version is shown on start-log by starting zigbee adapter).

Log: Unknown device model GL-B-001Z emit event devChange with data:{"cid":"genBasic","data":{"swBuildId":"1.0.6","hwVersion":1}}

**Comment by SroBu** [comment]
... seems not.
Please insert Gledopto GL-B-001Z
Smart 4W E14 RGB / CW LED bulb (on/off, brightness, color temperature, color xy)
Thank you!

**Comment by marck479** [comment]
Same problem here.
Could you please add this device?
GLEDOPTO GL-B-001Z
