### ISSUE TITLE
SONOFF Smart Bewässerungscomputer, some data points remain empty.

### ISSUE THREAD

**Issue by RaviniZib** [ioBroker/ioBroker.zigbee#2177]
Datapoint not working:

Irrigation_capacity
Irrigation_duration
Irrigation_interval

These data points remain empty and do not fill with the values.

```
{
  "type": "device",
  "common": {
    "name": "Bewässerung",
    "type": "SWV",
    "icon": "img/SWV.png",
    "color": "#00ffff",
    "statusStates": {
      "onlineId": "zigbee.0.842712fffe1ad7d1.available"
    },
    "role": "Bewässerung"
  },
  "native": {
    "id": "842712fffe1ad7d1"
  },
  "_id": "zigbee.0.842712fffe1ad7d1",
  "acl": {
    "object": 1638,
    "owner": "system.user.homeassist",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1722954755529
}
```

Mod edit - code tags

**Comment by asgothian** [comment]
The provided information does not contain any of the required information:
- Link to the zigbee2mqtt.io device page for the device it _should_ be
- which device type exactly (Info-Tile of the device) so we can see which device it _reports_ to be. 
- which states exactly, including information on if they are readable and/or writable

Please note - since the influx of TuYa devices, there have been multiple instances of
- devices which look the same reporting as different devices and operating differently from each other
- devices which look different reporting as the same device and operating differently
- devices which look different reporting as the same device and operating in the same way too.

A.

**Comment by RaviniZib** [comment]
Sorry,

Is the first time I try to  tell an issue.
Here are the info-title information

  *   modelZigbee:TS0601
  *   type:EndDevice
  *   nwk:36655
  *   manuf id:4417
  *   manufacturer:_TZE200_9cqcpkgb
  *   power:Battery
  *   app version:72
  *   hard version:1
  *   zcl version:3
  *   stack version:0
  *   date code:
  *   interviewed:true
  *   configured:false

  *   endpoint:1
  *   profile:260
  *   input clusters:genGroups (4)
  *   genScenes (5)
  *   manuSpecificTuya (61184)
  *   genBasic (0)
  *   output clusters:genOta (25)
  *   genTime (10)
And here a link. The model, that I have looks a little bit different but the modelname are the same.

I hope this is the information that was missing.

Greatings Frank.
Von: asgothian ***@***.***>
Datum: Dienstag, 6. August 2024 um 18:12
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: RaviniZib ***@***.***>, Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] SONOFF Smart Bewässerungscomputer, some data points remain empty. (Issue #2177)

The provided information does not contain any of the required information:
·         Link to the zigbee2mqtt.io device page for the device it should be
·         which device type exactly (Info-Tile of the device) so we can see which device it reports to be.
·         which states exactly, including information on if they are readable and/or writable

Please note - since the influx of TuYa devices, there have been multiple instances of
·         devices which look the same reporting as different devices and operating differently from each other
·         devices which look different reporting as the same device and operating differently
·         devices which look different reporting as the same device and operating in the same way too.

A.

**Comment by asgothian** [comment]
I see no link.

Also - the model name being the same means nothing with Tuya. If you check the different variants for TS0601 :)

A.

**Comment by RaviniZib** [comment]
It's solved. I updatet the Firmare on the device to 1.0.3 and now are all datapoints are filled.

**Comment by RaviniZib** [comment]
Solved.
