### ISSUE TITLE
Actual zigbee shepherd converters leads to always setting brightness to zero

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.zigbee#218]
The zigbee shepherd converters has changed:
https://github.com/Koenkk/zigbee-shepherd-converters/blob/6cfafa33fb37dac2ab5f51031b7277b516b6b45c/converters/toZigbee.js#L186
Naughty change to split up "moveToLevel" and "moveToLevelWithOnOff" ...

This leads to always setting brightness to zero if state or brightness is triggered;
cause the message (which are the preparedOptions) in iobroker.zigbee adapter
wiill be parsed for state and brightness also. Right now the transitions is set by the adapter.

To solve this, also the brightness should be set in preparedOptions, if the 
brightness shopuld be changed.

**Comment by nob0dy80** [comment]
can confirm!

i think this is related to this:
https://github.com/ioBroker/ioBroker.zigbee/issues/220
and
https://github.com/Koenkk/Z-Stack-firmware/issues/49

**Comment by nob0dy80** [comment]
@modmax do you know what the last working version was? there were 5 Updates in a day !

**Comment by nob0dy80** [comment]
fix bis der adapter repariert ist:
adapter beenden
cd /opt/iobroker && sudo npm install zigbee-shepherd-converters@7.1.13 --production
adapter starten

**Comment by dimaiv7** [comment]
> 
> 
> fix bis der adapter repariert ist:
> adapter beenden
> cd /opt/iobroker && sudo npm install zigbee-shepherd-converters@7.1.13 --production
> adapter starten

That did not help me

**Comment by nob0dy80** [comment]
your comment doesnt help too.
check if the version was really installed 
Open  the package json in the converter directory and check the version.
if version matches 7.1.13 do a debug log.

**Comment by modmax** [comment]
@nob0dy80
I've just investigated it at saturday afternoon, when I installed the newest zigbee adapter.
Due to package.json where zigbee-shephered-converters is not a fixed version (like 7.1.13) instead it's a "use at least version" (denoted by leading ^in front of version) the latest version will be used, which is now the master from zigbee-shepherd-converters.

It's indeed a zigbee adapter problem which can be solved with your fixed, but something must be implemented to put the brightness value into the preparedOptions which are passed to the converter to get the zcl data object.

Right now I'm not at home so that I cannot fix the problem; perhaps from thursday on, if I find the time for it.

**Comment by nob0dy80** [comment]
@modmox
sounds nice .. would be find if you can help with this issue. the iobroker developers are very busy people :-)

Well, as we know now what the problem causes and we know how to fix it temporarily, we arent really in a hurry :-)

**Comment by modmax** [comment]
Solved, when pull request #229 is merged.

**Comment by nob0dy80** [comment]
@modmox thanks for your work!

**Comment by modmax** [comment]
I now also added the "state" to the prepared options so that state on/off will work again.

The reason for the false behaviour was, that the zigbee-shepherd-converters has been changed, so that the same method for state and brightness was used. But in case of state the message didn't contain the state value, so the brightness was used (which has not been set) so that a movement to brightness 0 was triggered, which cannot work.

No switching the state to true or false is the same as before.
Note: If brightness is set to 0 before, then an internal brightness of 1 will be set in the bulb. When then the state is set to true, then those brightness will be used.

**Comment by nob0dy80** [comment]
@modmox 
i'm not that good with github .. how can i see if its fixed before i reinstall? 
normaly i thought the version of an adapter must change when to commited changes are in the main code.
so when there are no more pull requests and i completely reinstall the adapter, i will still get 0.9.2 but with all commited changes ?
