### ISSUE TITLE
Aqara FP1E sendet keine Daten

### ISSUE THREAD

**Issue by reihd** [ioBroker/ioBroker.zigbee#2180]
Hallo,

wird der Aqara FP1E noch implementiert? ich weiß, der Sensor ist neu. Er sendet soweit aber leider keine wichtigen Daten. Der läuft auch über Zigbee.

**Comment by asgothian** [comment]
Was meinst du mit 


> Er sendet soweit aber leider keine wichtigen Daten.


Details bitte.
- welche Datenpunkte hast du
- wird das Device als "configured" angezeigt
- ändert sich etwas wenn du versuchst das Device neu zu "konfigurieren" (Dafür gibts einen Button auf der Kachel)

A.

**Comment by reihd** [comment]
ich habe nur

+ device_query
+ link_quality
+ msg_from_zigbee
+ send_payload

Auch ein Reload oder neu anlernen bringt nichts, die Frage ist sowieso, wird dieses Gerät überhaupt funktionieren? Es ist neu und wohl bisher nur am Aqara Hub lauffähig, aber es ist zigbee, daher war meine Hoffnung, dass es über den Adapter gehen wird.

configured ist es laut Adapter nicht

**Comment by mymeyer** [comment]
Hallo , habe das selber Thema. Hier ein paar Daten vom FP1E. Bei mir sendet er überhaupt nichts im iObroker.

modelZigbee:lumi.sensor_occupy.agl1
type:EndDevice
nwk:17711
manuf id:4660
manufacturer:aqara
power:DC Source
app version:26
hard version:1
zcl version:3
stack version:2
date code:20240520
build:
interviewed:true
configured:false

endpoint:1
profile:260
input clusters:genBasic (0)
genIdentify (3)
manuSpecificLumi (64704)
output clusters:genIdentify (3)
genOta (25)

**Comment by asgothian** [comment]
- welche Adapter version nutzt ihr für den test ?
- was passiert wenn ihr die aktuelle Github version nutzt ?


A

**Comment by mymeyer** [comment]
Hi, ich nutzt die aktuelle Version 1.10.3.

**Comment by mymeyer** [comment]
Hier weitere Info:
Pairing time left: 106
Interview successful: {"friendly_name":"0x54ef441000db3332","supported":false}
New device joined '0x54ef441000db3332' model lumi.sensor_occupy.agl1
Device '0x54ef441000db3332' announced itself
Pairing time left: 107
Interview started: 0x54ef441000db3332
Pairing time left: 108

**Comment by asgothian** [comment]
da steht doch: supported: false.
also nicht unterstützt. Bitte die 1.10.9 von GitHub installieren und neu schauen.

**Comment by mymeyer** [comment]
Hatte bereits 1.10.9 installiert. Selbe Meldung: Supported: false.

**Comment by asgothian** [comment]
dann gibt es 2 Optionen: entweder schauen ob die 1.10.10 aus issue #2211 geht oder abwarten.

Wichtig: bevor die 1.10.10 wie in dem Issue beschrieben ist installiert wird solltest du eine extra Kopie des data-verzeichnesses des Zigbee Adapters machen - anscheinend gibt es einen breaking change beim Wechsel der Bibliothek. Ich bin noch dabei dem nachzugehen.

A.,

**Comment by reihd** [comment]
wenn ich Version 1.10.10 installiere und vorher den Data Ordner sichere, was soll ich damit machen? Falls es schief geht, diesen dann wieder rein kopieren?

**Comment by asgothian** [comment]
es kann sein das du den Order zurück kopieren musst bevor du auf die release oder 1.10.9 zurück willst. Sicher ist das nicht - bei mir ging es ohne.

**Comment by asgothian** [comment]
1.10.10 ist jetzt die aktuelle offizielle Github version

**Comment by mymeyer** [comment]
> 1.10.10 ist jetzt die aktuelle offizielle Github version

Perfekt. Wird nun im iob erkannt und meldet Werte. Thanks. :-)

**Comment by reihd** [comment]
Stimmt, es kommen Werte, zumindest presence kommt an, die target_distance bleibt leer, dass ist auch kein Problem, dass einzige was etwas stört, ich kann kein Delay einstellen, aber das kann man mit Blockly machen
