### ISSUE TITLE
Please add device "Zigbee solar light and rain sensor"

### ISSUE THREAD

**Issue by c-hum** [ioBroker/ioBroker.zigbee#2187]
I use the latest adapter version 1.10.5 from Github, but the device is only recognized as "TS0207_water_leak_detector" and does not contain any objects relating to the light sensors.

A converter seems to be available: https://github.com/Koenkk/zigbee2mqtt/issues/23532

Thanks.

**Comment by asgothian** [comment]
Please test if it is available in the GitHub versions 1.10.5 (current GitHub version) or 1.10.6 (current test branch[ here](https://github.com/asgothian/ioBroker.zigbee/tarball/NewHerdsmanTest))

**Comment by c-hum** [comment]
Thanks, with the version 1.10.5 that I already had installed, it was not working but with the 1.10.6 test branch you referred. Thanks.
