### ISSUE TITLE
Osram Schalter + Motion Sensor

### ISSUE THREAD

**Issue by Buhu91** [ioBroker/ioBroker.zigbee#219]
Hey, ist es möglich den Osram Bewegungsmelder, den switch mini sowie den 4 Tasten Schalter hinzuzufügen? 
Die ersten beiden sind ja beim Zigbee2mqtt Projekt schon drin. 
Hab alle Teile da, muss ich irgendwelche Daten zur Verfügung stellen?
bei den Produkten handelt es sich um Folgende:
[switch mini](https://www.amazon.de/dp/B074PYT9R4/ref=twister_B07FXW8BWB?_encoding=UTF8&psc=1)

[4 Tasten schalter](https://www.amazon.de/Osram-Switch-Lichtschalter-Fernbedienung-Erweiterung/dp/B074PZLX2Y/ref=dp_ob_title_light)

[Bewegungssensor](https://www.amazon.de/dp/B074KHZZ6B/ref=twister_B07FXW8BWB?_encoding=UTF8&psc=1)

Gruß

**Comment by sonntam** [comment]
Siehe #82. Es könnte teilweise machbar sein. Ich kann nächstes Wochenende mal reinschauen.

Welche Gerätenamen werden im Adapter nach dem Pairing angezeigt? Aktuell unterstützt werden

- Motion Sensor-A
- Lightify Switch Mini

Den Dimmerschalter (ArtNr. 4058075816459) scheint es in [zigbee-shepherd-converters](https://github.com/Koenkk/zigbee-shepherd-converters) noch nicht zu geben.

Ansonsten wird da anscheinend bei zigbee2mqtt noch dran gearbeitet: Koenkk/zigbee2mqtt#532

**Comment by arteck** [comment]
Lightify Switch Mini ist drin in meinem Repo zum testen

**Comment by sonntam** [comment]
@arteck: Prima! Ist PR #224 die dazu passende Änderung?

**Comment by Buhu91** [comment]
Hey, danke schon mal für die Integration vom Switch mini. 
Hab nur leider zwei Probleme mit diesem wenn ich ihn einbinde. 
Zum einem schaltet er meine Osram Steckdose welche auch mit dem stick gekoppelt ist. 
Und zum anderen bekomme ich keinen State bei der mittleren Taste. 
Hat jemand auch so ein Problem oder ist das nur bei mir so?

**Comment by chmaryniok** [comment]
> Hey, danke schon mal für die Integration vom Switch mini.
> Hab nur leider zwei Probleme mit diesem wenn ich ihn einbinde.
> Zum einem schaltet er meine Osram Steckdose welche auch mit dem stick gekoppelt ist.
> Und zum anderen bekomme ich keinen State bei der mittleren Taste.
> Hat jemand auch so ein Problem oder ist das nur bei mir so?

Kann das gleiche Verhalten bestätigen.
- Koppeln klappt (frag aber nicht mehr wie genau) und Gerät wird erkannt
- Es werden bei mir alle Osram Plugs geschaltet (mitte = AN Pfeil runter = AUS)
- Mitte aktualisiert zwar den "State" aber mit der letzten aktivität, also wenn zuletzt "down" aktiv war, wird wieder down gesetzt.
- "Circle State"(was ist das?) bleibt leer


Dazu diverse Fehlermeldungen nach dem Schalten:

Zigbee publish to '0x7cb03eaa0a0272bd', genOnOff - off - {} - 3 failed with error Error: AF data request fails, status code: 233. MAC no ack.
---

Zigbee publish to '0x7cb03eaa0a026b69', genOnOff - on - {} - 3 failed with error Error: Timed out after 30000 ms
---

Zigbee publish to '0x7cb03eaa0a026b69', genOnOff - on - {} - 3 failed with error Error: AF data request fails, status code: 233. MAC no ack.
--

**Comment by obakuhl** [comment]
> > Zum einem schaltet er meine Osram Steckdose welche auch mit dem stick gekoppelt ist.
> > Und zum anderen bekomme ich keinen State bei der mittleren Taste.
> > Hat jemand auch so ein Problem oder ist das nur bei mir so?
> 
> Kann das gleiche Verhalten bestätigen.
> 

Kann ich ebenfalls bestätigen. 
Beim Drücken des Pfeils nach unten wird der state auf "down" geändert/aktualisiert & die link quality ebenfalls einmal geändert/aktualisiert. Ebenfalls werden dadurch meine Osram Plugs angeschaltet.

Beim Drücken auf den die mittlere Taste wird link quality zwei mal aktualisert, keine Änderung/Aktualisierung des states. Dadurch werde aber meine Osram Plugs wieder ausgeschaltet.

Beim Drücken auf den Pfeil nach oben passiert nichts.

Bezeichnung meines Switch Mini: AC0251**4**00NJ

**Comment by fademirci** [comment]
Hallo zusammen,
das mit dem Switch Mini kann ich ebenfalls bestätigen. Aber ich habe zusätzlich Probleme mit dem Motion Sensor, bekomme diesen nicht gepaired....
 Cannot get the Node Descriptor of the Device: 0x000d6f000f710f5c (Error: Timed out after 10000 ms) 

Was mache ich falsch ?

**Comment by allofmex** [comment]
> Motion Sensor, bekomme diesen nicht gepaired

Ich war leider auch erfolglos. Hab meinen zurückgeschickt. Manche scheinen Erfolg gehabt zu haben
(https://github.com/Koenkk/zigbee2mqtt/issues/507#issuecomment-473724719) aber es klingt alles nach viel Frust...

**Comment by obakuhl** [comment]
Da bei mehreren das Problem besteht habe ich dazu einen Thread im ioBroker Forum erstellt:
https://forum.iobroker.net/topic/21381/problem-osram-smart-mini-switch-schaltet-am-zigbee-coordinator-vorbei-fehlende-werte-bei-objekten

**Comment by maverickmu** [comment]
Könntet ihr bitte den Motion Sensor noch hinzufügen, oder wurde der schon hinzugefügt?
Beim pairen bekomme ich folgende Meldung:
"Cannot get the Node Descriptor of the Device:" deshalb schätze ich ist der noch nicht drin, oder? Danke

**Comment by allofmex** [comment]
@maverickmu 
Das Problem ist, das sich der Sensor nicht zuverlässig pairen lässt (daher der "Cannot get the Node Descriptor" Fehler).
Auch wenn ein Gerät noch nicht in iobroker hinzugefügt sein sollte, würde pairen normalerweise trotzdem gehen. Das Gerät wird dann halt als "Unbekanntes Gerät" oder so ähnlich angezeigt.

Der Osram Sensor zickt aus unbekannten Gründen. Falls du heraus bekommst wie sich der Sensor pairen lässt (Tastenkombination usw.) wäre der Rest kein Problem mehr.
