### ISSUE TITLE
New Device: Directsigns DS-Z-001DE Zigbee 3.0 Controller

### ISSUE THREAD

**Issue by wolfganghuse** [ioBroker/ioBroker.zigbee#2190]
Directsigns Zigbee 3.0 Controller, often sold by Baushaus.info
PDF: https://www.directsigns.cz/web/content/4784?unique=50c2521e1aa8aa4f5b534ef1cb6c17edf8cc77e8&download=true

modelZigbee:DS-Z-001DE
type:Router
nwk:38719
manuf id:4687
manufacturer:DIRECTSIGNS
power:Mains (single phase)
app version:1
hard version:2
zcl version:3
stack version:2
date code:20230911
build:20451203
interviewed:false
configured:false
endpoint:11
profile:260
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
lightingColorCtrl (768)
touchlink (4096)
output clusters:genOta (25)
endpoint:242

**Comment by asgothian** [comment]
Is this device listed as supported at zigbee2mqtt.io ?
If yes - please test the current test fork from [Here](https://github.com/asgothian/ioBroker.zigbee/tarball/NewHerdsmanTest)
If no - please follow the directions on zigbee2mqtt.io for getting a new device supported. Once it is supported in the library, the support in the ioBroker adapter is as easy as updating the required library to the respective version.

A.

**Comment by asgothian** [comment]
No response for 6 weeks, closing this
