### ISSUE TITLE
Tuya 2 in 1 Sonnenlicht und regensensor wird nur als water detected erkannt

### ISSUE THREAD

**Issue by Day1983** [ioBroker/ioBroker.zigbee#2191]
Hallo,

Ich hab den oben genannten sensor bei Ali erworben.
Er wird aber nur als ts0207 water leak detected erkannt.

Er soll aber noch einen Sonnenlicht sensor haben (lux)

Könntet ihr diesen bitte integrieren?

Adapter Version 1.10.5

![Screenshot_20240829_122439_com alibaba aliexpresshd](https://github.com/user-attachments/assets/3c2ee14a-f2a1-42c3-9995-d49d23566e26)

**Comment by asgothian** [comment]
Ist der Sensor bei zigbee2mqtt.io gelistet ?

Wenn ja - Bitte die aktuelle Testversion (1.10.6) von [hier](https://github.com/asgothian/ioBroker.zigbee/tree/NewHerdsmanTest) installieren.
Wenn nein - Bitte der Doku auf zigbee2mqtt.io folgen um die Integration vorwärts zu treiben

A.

**Comment by asgothian** [comment]
No response for 6 weeks - closing this
