### ISSUE TITLE
Zigbee Gateway is no longer recognized - Zigbee Gateway wird nicht mehr erkannt

### ISSUE THREAD

**Issue by xnetworker** [ioBroker/ioBroker.zigbee#2199]
I had to put the iobroker completely new. This runs on a ThinClient from HP under Proxmox in a container. Iobroker was set up and the backup played back. Unfortunately, the ZigBee Gateway CC1352P-2 is no longer detected under Debian.
What can be the cause. It went until I had to reset the system. Anyone an idea or solution?

Ich musste den iobroker komplett neu aufsetzen. Dieser läuft auf einem ThinClient von HP unter Proxmox in einem Container. Iobroker wurde eingerichtet und das backup zurückgespielt. Leider wird das ZigBee Gateway CC1352P-2 unter Debian nicht mehr erkannt.
Was kann die Ursache sein. Es lief bis ich das System neu aufsetzen musste. Jemand eine Idee oder Lösungsansatz?

**Comment by asgothian** [comment]
bitte testen ob das Gateway erkannt wird wenn du ohne es Proxxmoxx auf einer nativen Debian installation benutzt.

A.

**Comment by asgothian** [comment]
Lösung im ioBroker Forum

**Comment by xnetworker** [comment]
Ich musste es noch an den Container durchreichen. jetzt klappt es
