### ISSUE TITLE
Wrong unit for Xiaomi Aqara Temperature Humidity Pressure Sensor

### ISSUE THREAD

**Issue by DoraDeu** [ioBroker/ioBroker.zigbee#22]
This is just about the unit of the air pressure that is used for this device.
Currently the unit is shown as "Pa" but the value shows the air pressure in mbar or "hPa". 
I hope this can be fixed to "hPa" or "mbar" in one of the next releases.

**Comment by kirovilya** [comment]
Thank you, corrected. Will be in the next release
