### ISSUE TITLE
adapter crashed wenn hue dimmer switch hinzugefügt ist

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.zigbee#220]
Hallo,
musste leider iobroker komplett neu aufsetzen und habe jetzt massive probleme mit dem zigbee adapter.

problem1: adapter crashed sobald ein Hue Dimmer Switch hinzugefügt wird:

host.iobroker2 | 2019-03-03 18:11:00.893 | error | instance system.adapter.zigbee.1 terminated with code 0 (OK)
-- | -- | -- | --
host.iobroker2 | 2019-03-03 18:11:00.893 | error | Caught by controller[0]: at Timer.listOnTimeout (timers.js:290:5)
host.iobroker2 | 2019-03-03 18:11:00.893 | error | Caught by controller[0]: at tryOnTimeout (timers.js:323:5)
host.iobroker2 | 2019-03-03 18:11:00.893 | error | Caught by controller[0]: at ontimeout (timers.js:502:15)
host.iobroker2 | 2019-03-03 18:11:00.892 | error | Caught by controller[0]: at Timeout.actions [as _onTimeout] (/opt/iobroker/node_modules/zigbee-shepherd-converters/devices.js:838:29)
host.iobroker2 | 2019-03-03 18:11:00.892 | error | Caught by controller[0]: at Endpoint.ep.bind (/opt/iobroker/node_modules/zigbee-shepherd/lib/shepherd.js:571:36)
host.iobroker2 | 2019-03-03 18:11:00.892 | error | Caught by controller[0]: at Controller.bind (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/controller.js:445:23)
host.iobroker2 | 2019-03-03 18:11:00.892 | error | Caught by controller[0]: at Object.query.setBindingEntry (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/query.js:136:13)
host.iobroker2 | 2019-03-03 18:11:00.891 | error | Caught by controller[0]: at Object.proving.defined (/opt/iobroker/node_modules/proving/index.js:41:15)
host.iobroker2 | 2019-03-03 18:11:00.890 | error | Caught by controller[0]: TypeError: Invalid cluster id: manuSpecificPhilips.
zigbee.1 | 2019-03-03 18:11:00.463 | info | 1 (0x0017880103a540fc): 324131092621 - Philips Hue dimmer switch (EndDevice)

2. hue lampen lassen sich nicht anschalten über den state datenpunkt. aus klappt dafür aber wunderbar.

root@iobroker2:~# node -v
v8.15.1
root@iobroker2:~# npm -v
6.4.1
root@iobroker2:~#

letzte version des zigbee adapters.

**Comment by nob0dy80** [comment]
Vermutlich abhängig von https://github.com/ioBroker/ioBroker.zigbee/issues/218

**Comment by modmax** [comment]
Welche JS-Controller Version hast Du installiert?
Zu finden auf der Admin-seite unter dem Punkt "Hosts" ...

**Comment by modmax** [comment]
1.) Übrprüfe mal den JS_Controller. Welche Version ist das? Zu finden auf der Adminseite unter dem Punkt "Hosts".
2.) Im Zigbee-Adapter die Analys anwerfen und dort mal für den Hue Dimmer-Switch die Felder auflisten. Bei der CID sollte irgendwie die "manuSpecificPhilips" auftauchen. Wenn nicht wäre zu klären, ob es unterschiedliche Versionen des Switches gibt.

**Comment by nob0dy80** [comment]
@modmax 
nein wie vermutet hängt es mit meinem genannten issue zusammen. es lief ja vorher schon. zurück zu alten converters und alles geht wieder

**Comment by arteck** [comment]
done
