### ISSUE TITLE
network diagram mark "deactivated" devices

### ISSUE THREAD

**Issue by averlon** [ioBroker/ioBroker.zigbee#2207]
Hi,
within the zigbee-adapter for iobroker you can deactivate a device, e.g. if it is temporarily not in use. Very fine feature!

In the network diagram the device is shown als "disconnected".

I would like you to think about to 
a) either not show the devices that are deactivated at all or
b) show them als "deactivated" instead "disconnected"!

Thanks
Kallewirsch

**Comment by asgothian** [comment]
I'll have a look into wether that's easily done

**Comment by asgothian** [comment]
Please test by installing from my test branch at
```
https://github.com/asgothian/ioBroker.zigbee/tarball/MapTest
```
In this branch, deactivated devices will not show up on the map at all.

**Comment by asgothian** [comment]
That's easy:
- Go to the "adapters" Page
![Screenshot 2024-09-22 at 17 33 00](https://github.com/user-attachments/assets/1189a4da-e413-42bb-9535-1633bb8b0d2e)

- activate expert mode
![Screenshot 2024-09-22 at 17 33 32](https://github.com/user-attachments/assets/10122d43-b6ef-4d35-a27e-894e779e42a6)

- By selecting the "cat" icon, acrtivate "install from custom url" 
![Screenshot 2024-09-22 at 17 34 37](https://github.com/user-attachments/assets/283f8b0a-3979-4664-93af-e31e5ecbae7e)

- paste in the URL, install
![Screenshot 2024-09-22 at 17 35 24](https://github.com/user-attachments/assets/cb77bfe0-eea8-48fc-a33b-8bd4d6a891df)

- Perform an adapter upload (for safety) by going to the adapters tile, clicking the 3. vertical dots and then selecting the arrow pointing up 
![Screenshot 2024-09-22 at 17 36 35](https://github.com/user-attachments/assets/ef9f6d8d-7b72-451f-846a-5d60010fb8bb)


Done.

A.

**Comment by asgothian** [comment]
> 
> But the map has already a filter function. But only you can decide if this could be extended or not!
> 
It actually does not. All the nodes are generated when swapping to the map view. I can easily remove nodes at that point, especially nodes which do not carry any connections, which deactivated devices don't by design. Once the map is displayed, there is no filter function for the nodes, just for connections, which are being redrawn on a regular basis anyhow.

A.
