### ISSUE TITLE
Adding support for tint Remote

### ISSUE THREAD

**Issue by sonntam** [ioBroker/ioBroker.zigbee#221]
I'm currently working on fully supporting the tint 404011 remote . So far I was able to add all the states for the buttons.

Now the problem I have is that the zigbee-shepherd version is too old. In zigbee-shepherd's file `af.js` at line 689 I need all the new command ids for it to work:

```
const cmdIDs = ['on', 'offWithEffect', 'step', 'stop', 'hueNotification', //Philips-RWL020-RWL021
                            'off', 'stepColorTemp', 'moveWithOnOff', 'move', 'moveHue', 'moveToSaturation', //OSRAM-Switch 4x EU-LIGHTIFY
                            'stopWithOnOff', 'moveToLevelWithOnOff', 'toggle', 'tradfriArrowSingle', 'tradfriArrowHold', 'tradfriArrowRelease',
                            'stepWithOnOff', 'moveToColorTemp', 'moveToColor', 'onWithTimedOff',];
```

Currently e.g. the commands `moveToColorTemp` or `moveToColor` are not parsed.

Can we update to a newer version, e.g. Koenkk/zigbee-shepherd@8c53bd423b69a0eef73e521a2edf447c9392b050 or are there any compatibility issues?

**Comment by sonntam** [comment]
Added PR #222. See the comment there for further information.

**Comment by killakaktus** [comment]
Any news here? I have this remote and want to use it. ;)

**Comment by sonntam** [comment]
@kirovilya Thank you for merging! 

Now the only thing left I have to test is the new zigbee-shepherd version. If all works well I will close the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sonntam** [comment]
With the added PR #253 and the now used zigbee-shepherd version everything seems to be working well. I'm closing the issue.

**Comment by killakaktus** [comment]
On 0.10.2 i succesfully paired the remote but no buttons in objects react. I paired via reset button on the backside of the remote.

**Comment by andre1974** [comment]
Same here... Succesfully paired but noe reaction in objects when i press any button

**Comment by sonntam** [comment]
Have you setup a group id correctly or are you using the latest coordinator firmware?

See my comment in #259.

**Comment by killakaktus** [comment]
THX. Flashed new firmware. Even all my devices are still there. Perfect.

**Comment by killakaktus** [comment]
Gibts ne Möglichkeit die Gruppenfunktion zu nutzen an der FB? Evtl. auch die Dimmtasten per längerem Tastendruck wiederholt "anschlagen" zu lassen?

**Comment by sonntam** [comment]
> THX. Flashed new firmware. Even all my devices are still there. Perfect.

Thanks for testing - haven't done it myself yet. This is encouraging me to do so, either :blush:



> Gibt's ne Möglichkeit die Gruppenfunktion zu nutzen an der FB? Oder die Dimmtasten per längerem Tastendruck wiederholt "anschlagen" zu lassen? Schöne Grüße ;)

Should be doable. I can see in the logfile that if you keep a button pressed a
`cmdMove:genLevelCtrl`
with a given rate of change and upon releasing a
`cmdStop:genLevelCtrl` 
are sent.

Probably some things may have to be changed deeper in the framework.

If you like you can create a new issue and we will track progress there. I will take a look and maybe someone else has got a solution already.

**Comment by KlausFindus** [comment]
@sonntam, @killakaktus  -> Tint remote
I have the following setup  Version 0.10.2 installiert with zigbee-sherpherd version 20190109
Pairing ok - but no reactions in the objects. I also have no group id set for the Tint remote

Does that mean that i have to flash a newer firmware to make this work? Which version is required?

**Comment by killakaktus** [comment]
I think you should. Latest frome [HERE](https://github.com/Koenkk/Z-Stack-firmware)
Than you don't need the group function.

I didn't need to re-pair my devices.

**Comment by KlausFindus** [comment]
I have flashed version  zigbee-shepherd ready. version: 2.6.3 rev 20190315 (Modifizierte Firmware zum Testen von arteck)  and suprise suprise its now working... but have to do a hardreset first and re-pair afterwards. (before hardreset it still didn't worked)
Thanks so much for the hint.

**Comment by KlausFindus** [comment]
Hi, i found one strange behaviour with the Tint Bulb and leveldimmer together with on/off.
leveldimmer does not has/maintains always the right value.
e.g level dimmer = 0 and when i switch the state of the bulb to true - the bulb light switch on even the level dimmer is 0?   Which may be is ok - but then the leveldimmer should change the value to the actual one as well - but it stays 0.

**Comment by modmax** [comment]
@KlausFindus 
That's a known problem. The reason for this is, that there is always just one command: setting the brightness and setting the state (on/off). A response only comes for that sent event. The brightness is programatically synced with the state, but the state is not synched with the brightness. That's a known problem without solution until now.,
But normally setting the brightness should be enough, cause the on/off state will be synched and a lamp is off, if brightness is set to 0.

**Comment by KlausFindus** [comment]
Hi modmax, thanks a lot for the explanation and can be easly manged by a workaround. 

One more...  I would assume that the bulb has a scene variable as well to set/get the scene. But this is not exposed as a variable in iobroker.

**Comment by KlausFindus** [comment]
Hope German is ok as well... :-)

Error: Timed out after 30000 ms ...

Wenn ich sehr schnell mit der Tint Fernbedienung (durch IOBroker) den Wert in die Lampe schreibe ist das System nicht mehr responsive und es kommen folgende Timeout Fehlermeldungen.

zigbee.0	2019-03-22 14:23:46.618	error Zigbee publish to '0x00158d000300075b', lightingColorCtrl - moveToColor - {"transtime":0,"colorx":34537,"colory":29255} - 1 failed with error Error: Timed out after 30000 ms

danach reagiert das System nur noch sehr träge und es kommt immer wieder diese Timeout Fehlermeldung (eigentlich nicht mehr benutzbar)

Die Fernbedienung erzeugt weiterhin events die in IOBroker ankommen - nur laueft das setzen der Lampe in einen Timeout.

auch hilft ein Softreset und der restart des Adapters nicht weiter...

Update: Betreibe ich die Mueller Lampe im Hue Netz und die Mueller Fernbedienung im CC253X Netz gibt es keine Timeouts

Hat jemand solches Verhalten schon mal gesehen.

Adapter 0.10.2 und Firmware 20190315

**Comment by KlausFindus** [comment]
Will get this error when i switch bulb on and off...
 
zigbee publish to '0x00158d000300075b', genOnOff - on - {} - 1 failed with error Error: Timed out after 30000 ms

it's currently not really usable.  Is there a change to fix this?

**Comment by sonntam** [comment]
@KlausFindus is this related to the tint remote functionality or to controlling the tint bulbs via iobroker? In the latter case you should create a new issue.
