### ISSUE TITLE
irritating green checks

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#2215]
So I was a bit lazy and some of my batteries are void .. what irritates me though is that all objects show a green check. Should that be sort of a red cross when something is wrong? What exactly does the green check stand for?

![grafik](https://github.com/user-attachments/assets/4348900c-1742-4b51-bdea-d4ae5a0ae213)

**Comment by daniel-lo** [comment]
Similarly irritating I find that I can switch actors that show a disconnection symbol:

![grafik](https://github.com/user-attachments/assets/a9364d02-ea47-4cee-9b38-4bc6dbaad540)

My interpreation would be that I shoulr not be able to control them in this state.

**Comment by asgothian** [comment]
> Similarly irritating I find that I can switch actors that show a disconnection symbol:
> 
> ![grafik](https://private-user-images.githubusercontent.com/4311558/371754622-a9364d02-ea47-4cee-9b38-4bc6dbaad540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MjYwOTcsIm5iZiI6MTcyNzUyNTc5NywicGF0aCI6Ii80MzExNTU4LzM3MTc1NDYyMi1hOTM2NGQwMi1lYTQ3LTRjZWUtOWIzOC00YmM2ZGJhYWQ1NDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTIxNjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA2MGViM2M5MzY4YTM3ODQ2MDNlODRkOWM1MzFkYzEzOWM2ZGZhMjU5MDk1Zjc1MzM3MzQ2MzUzMjU2ZjQ4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3FR_831lzFj4JkNTIlJFewZW4Yc4tQELfsPuq65-B6I)
> 
> My interpreation would be that I shoulr not be able to control them in this state.

Your interpretation is wrong on several levels:
- the update frequency of that symbol is limited.
- the symbol will update when the device will update its status or respond to a 'ping request'. The Osram plugs are well known for refusing to do so.
- The green check-mark marks if the last recorded link quality of the device was > 0. Especially for battery driven devices, this can be the case even if the device itself is marked unavailable.


A.
