### ISSUE TITLE
New device: sonoff ZBMINIR2

### ISSUE THREAD

**Issue by M42v1n** [ioBroker/ioBroker.zigbee#2216]
Hello,
I would like to report a new SONOFF Zigbee device ZBMINIR2.
https://www.zigbee2mqtt.io/devices/ZBMINIR2.html

Thank you in advance

With kind regards
M42v1n

Geräteinformation

    modelZigbee:ZBMINIR2
    type:Router
    nwk:63773
    manuf id:4742
    manufacturer:SONOFF
    power:Mains (single phase)
    app version:16
    hard version:16
    zcl version:3
    date code:20240509
    build:1.0.1
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genOnOff (6)
    haDiagnostic (2821)
    manuSpecificAmazonWWAH (64599)
    64529
    output clusters:genIdentify (3)
    genOnOff (6)
    genOta (25)

    endpoint:242
    profile:41440
    output clusters:greenPower (33)

**Comment by asgothian** [comment]
Please test if the device is supported in the current GitHub adapter 1.10.9

**Comment by M42v1n** [comment]
Thanks for the quick reply. After updating to github version 1.10.9 the device is recognized.

So everything is fine.

With kind regards
M42v1n
