### ISSUE TITLE
Aqara SRTS-A01 valve_position und window_isopen

### ISSUE THREAD

**Issue by MeisterQ** [ioBroker/ioBroker.zigbee#2222]
Hallo,

ich vermisse für die Aqara SRTS-A01 irgendwie die Datenpunkte valve_position und window_isopen.

Die Shelly TRV liefern diese Datenpunkte und ich finde sie sehr nützlich. Liefert das zigbee2mqtt nicht, oder kann der Adapter das nicht?

Gerade wenn man externe Fensterkontakte nutzt, ist das praktisch, damit man die aktuell gesetzte Temperatur nicht in einen Datenpunkt schreiben muss wenn man die Temp runter setzt wegen Fenster offen. Der Shelly merkt sich das schon "intern" und auch wenn während des Fenster offen eine neue Sollwert Vorgabe kommt, wird sich die gemerkt und nach dem schließen vom Fenster wird diese gesetzt.

Vor allem wird ja auch mit der Funktion geworben, aber ich habe das Gefühl, dass diese Funktion nur über das Aqara Hub realisiert wird wenn man es in diesem System nutzt.

**Comment by asgothian** [comment]
> Hallo,
> 
> ich vermisse für die Aqara SRTS-A01 irgendwie die Datenpunkte valve_position und window_isopen.
> 
> Die Shelly TRV liefern diese Datenpunkte und ich finde sie sehr nützlich. Liefert das zigbee2mqtt nicht, oder kann der Adapter das nicht?

zigbee2mqtt ? Bist du sicher das du den issue am korrekten Adapter angehängt hast ? Zigbee2mqtt wird vom Zigbee-Adapter nicht verwendet.


Seis drum - sowohl zigbee2mqtt als auch der Zigbee-Adapter setzen auf 2 Bibliotheken auf: 
- zigbee-herdsman für die Kommunikation mit der Hardware
- zigbee-herdsman-converters für die Definition der 'Konverter', sprich der Abbildung der Zigbee-Nachrichten zu einstellbaren Werten.

Und an der Stelle hast Du recht - die Datenpunkte werden von den Zigbee-herdsman-converters nicht so bereitgestellt wie du das erwartest:
- valve_position wird vom Ventil nicht unterstützt
- window_isopen gibt es als Informativen Datenpunkt, der auf wahr geht wenn die interne Fenster-offen Erkennung das Öffnen des Fensters erkannt hat. Dieses geht (üblicherweise) basierend auf der plötzlichen Temperaturänderung.

> 
> Gerade wenn man externe Fensterkontakte nutzt, ist das praktisch, damit man die aktuell gesetzte Temperatur nicht in einen Datenpunkt schreiben muss wenn man die Temp runter setzt wegen Fenster offen. Der Shelly merkt sich das schon "intern" und auch wenn während des Fenster offen eine neue Sollwert Vorgabe kommt, wird sich die gemerkt und nach dem schließen vom Fenster wird diese gesetzt.
> 
Ansonsten macht es Sinn sich mit dem Gerät auseinander zu setzen. So hat es den "mode" Datenpunkt. Den kannst du auf off setzen - dann schliesst das Ventil, ohne das die Vorgabe von Solltemperaturen blockiert wird.


Das ist gleichzeitig Vor- und Nachteil einer nicht herstellerspezifischen Lösung - man muss sich selber mit den einzelnen Geräten beschäftigen und schauen wie man die Funktionalität abbildet, nicht ob die gewohnten Datenpunkte verfügbar sind.


A.
