### ISSUE TITLE
Please add support for _TZE204_hcxvyxa5

### ISSUE THREAD

**Issue by astrakid** [ioBroker/ioBroker.zigbee#2231]
hi,
the device is already supported by zigbee-herdsman and zigbee-herdsman-converter:

`        fingerprint: [{ modelID: 'TS0601', manufacturerName: '_TZE204_hcxvyxa5' }],
        model: 'ZA03',
        vendor: 'Tuya',
        description: 'Siren alarm',
        fromZigbee: [tuya.fz.datapoints],
        toZigbee: [tuya.tz.datapoints],
        configure: tuya.configureMagicPacket,
        exposes: [
            e.binary('alarm', ea.STATE_SET, 'ON', 'OFF').withDescription('Sound the alarm'),
            e.enum('volume', ea.STATE_SET, ['low', 'medium', 'high', 'mute']),
            e.enum('ringtone', ea.STATE_SET, [
                'ringtone 1',
                'ringtone 2',
                'ringtone 3',
                'ringtone 4',
                'ringtone 5',
                'ringtone 6',
                'ringtone 7',
                'ringtone 8',
                'ringtone 9',
                'ringtone 10',
                'ringtone 11',
                'ringtone 12',
                'ringtone 13',
                'ringtone 14',
                'ringtone 15',
                'ringtone 16',
                'ringtone 17',
                'ringtone 18',
                'ringtone 19',
                'ringtone 20',
                'ringtone 21',
                'ringtone 22',
                'ringtone 23',
                'ringtone 24',
                'ringtone 25',
                'ringtone 26',
                'ringtone 27',
                'ringtone 28',
                'ringtone 29',
                'ringtone 30',
                'ringtone 31',
                'ringtone 32',
            ]),
            e
                .numeric('duration', ea.STATE_SET)
                .withValueMin(1)
                .withValueMax(380)
                .withValueStep(1)
                .withUnit('s')
                .withDescription('How long the alarm sounds for when triggered'),
        ],
        meta: {
            tuyaDatapoints: [
                [
                    5,
                    'volume',
                    tuya.valueConverterBasic.lookup({
                        low: tuya.enum(0),
                        medium: tuya.enum(1),
                        high: tuya.enum(2),
                        mute: tuya.enum(3),
                    }),
                ],
                [7, 'duration', tuya.valueConverter.raw],
                [13, 'alarm', tuya.valueConverter.onOff],
                [
                    21,
                    'ringtone',
                    tuya.valueConverterBasic.lookup({
                        'ringtone 1': tuya.enum(0),
                        'ringtone 2': tuya.enum(1),
                        'ringtone 3': tuya.enum(2),
                        'ringtone 4': tuya.enum(3),
                        'ringtone 5': tuya.enum(4),
                        'ringtone 6': tuya.enum(5),
                        'ringtone 7': tuya.enum(6),
                        'ringtone 8': tuya.enum(7),
                        'ringtone 9': tuya.enum(8),
                        'ringtone 10': tuya.enum(9),
                        'ringtone 11': tuya.enum(10),
                        'ringtone 12': tuya.enum(11),
                        'ringtone 13': tuya.enum(12),
                        'ringtone 14': tuya.enum(13),
                        'ringtone 15': tuya.enum(14),
                        'ringtone 16': tuya.enum(15),
                        'ringtone 17': tuya.enum(16),
                        'ringtone 18': tuya.enum(17),
                        'ringtone 19': tuya.enum(18),
                        'ringtone 20': tuya.enum(19),
                        'ringtone 21': tuya.enum(20),
                        'ringtone 22': tuya.enum(21),
                        'ringtone 23': tuya.enum(22),
                        'ringtone 24': tuya.enum(23),
                        'ringtone 25': tuya.enum(24),
                        'ringtone 26': tuya.enum(25),
                        'ringtone 27': tuya.enum(26),
                        'ringtone 28': tuya.enum(27),
                        'ringtone 29': tuya.enum(28),
                        'ringtone 30': tuya.enum(29),
                        'ringtone 31': tuya.enum(30),
                        'ringtone 32': tuya.enum(31),
                    }),
                ],
            ],
        },
    },
`

**Comment by asgothian** [comment]
Please test with the current 1.10.9 from GitHub if the device is supported.

A

**Comment by astrakid** [comment]
i have already updated to 1.10.9 yesterday before opening this issue.

**Comment by astrakid** [comment]
absolutely perfect working now!!! thx a lot!

**Comment by asgothian** [comment]
1.10.10 is now the current GitHub version. Closing this.
