### ISSUE TITLE
icon not displayed

### ISSUE THREAD

**Issue by fonebone42** [ioBroker/ioBroker.zigbee#2233]
I have 4 devices who's icons are not displayed in the Objects:
![image](https://github.com/user-attachments/assets/9ea2d772-2338-476e-a1c0-64d8a9160dbc)

it looks like the PNG files do exist but the web server returns a 404 when trying to access them:

- /adapter/zigbee/img/8719514440937-8719514440999.png
- /adapter/zigbee/img/9290024426.png
- /adapter/zigbee/img/929002398602.png
- /adapter/zigbee/img/SWV.png

![image](https://github.com/user-attachments/assets/de68fce0-0d9a-41b1-8f00-795df6c29986)

They might be missing in _./iobroker-data/files/zigbee.admin/_data.json_ where I could find all other images listed just not the ones missing ones ... I'm not the expert in how iobroker works internally, so this is just a guess :-)

P.S. I'm using the ZigBee Adapter v1.10.9

**Comment by asgothian** [comment]
Please check the sizes of the images. If they are too big they often cannot be displayed

**Comment by Apollon77** [comment]
How did you added the file? Please DO NOT just copy it in on filesystem because then this file is unknown and ignored. User Adm -> Files to upload it

**Comment by fonebone42** [comment]
no, the images were already there so didn't need to add them

**Comment by Apollon77** [comment]
If thy are not in the _data.json then they got there somehow aside the normal process.

try "iob file sync" ... that should sync the _data.json with the existing files again

**Comment by fonebone42** [comment]
```
$ iob file sync
1 file(s) successfully synchronized with ioBroker storage

The following notifications happened during sync:
- Added 1 Files in Directory "zigbee.admin"
```

but did not solve the problem and the images did still not get added to the zigbee adapter _data.json (bit the file has new modification timestamp)

**Comment by fonebone42** [comment]
I think I found the problem ... the images were not in the right directory
I found them in `/opt/iobroker/node_modules/iobroker.zigbee/admin/img` but they were not in `/opt/iobroker/iobroker-data/files/zigbee.admin/img` from the web server picked them up.

playing with `iob file sync` brought me onto the solution...thanks for the tip

I think there files do just not get copied to the correct directory during installation of the adapter

I did a diff of the 2 directories and exactly 4 ones I listed above were missing so after copying them and an iob file sync all looks ok again

**Comment by fonebone42** [comment]
I just upgraded to 1.10.10 and I found the following the logs

![image](https://github.com/user-attachments/assets/079d6b7c-baa0-470e-8b08-2dbf889e59bc)

which seems to back my hypothesis. After the upgrade the icons in the object tree have disappeared again so I needed to apply the manual fix again:

```
cp 8719514440937-8719514440999.png 929002398602.png 9290024426.png SWV.png /opt/iobroker/iobroker-data/files/zigbee.admin/img
iob stop
iob file sync
iob start
```
to make them reappear

Please automate this if images get automatically downloaded from zigbee2mqtt.

**Comment by arteck** [comment]
> I just upgraded to 1.10.10 and I found the following in the logs
> 
> ![image](https://private-user-images.githubusercontent.com/18752608/380624621-079d6b7c-baa0-470e-8b08-2dbf889e59bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MjY0ODgsIm5iZiI6MTczMDUyNjE4OCwicGF0aCI6Ii8xODc1MjYwOC8zODA2MjQ2MjEtMDc5ZDZiN2MtYmFhMC00NzBlLThiMDgtMmRiZjg4OWU1OWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA1NDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYmRhYTRkMGFjMDlhYTYyNDIyM2JhNzNhNWU4NWIwMTBjZmZhYWVkZTY2NmZkNzQ5YjhhNmYyYzg3MzY3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0FVnG8-02YgH6Z2bJd01u3jwzSN309hebA-v580fUVA)
> 
> which seems to back my hypothesis. After the upgrade the icons in the object tree have disappeared again so I needed to apply the manual fix again:
> 
> ```
> cd /opt/iobroker/node_modules/iobroker.zigbee/admin/img
> cp 8719514440937-8719514440999.png 929002398602.png 9290024426.png SWV.png /opt/iobroker/iobroker-data/files/zigbee.admin/img
> iob stop
> iob file sync
> iob start
> ```
> 
> to make them reappear
> 
> Please automate this if images get automatically downloaded from zigbee2mqtt.

really... RFTM

https://github.com/ioBroker/ioBroker.zigbee/wiki/Missing-icons-after-adatapter-Update
