### ISSUE TITLE
Adapter crashes when sending to a Zigbee device

### ISSUE THREAD

**Issue by biffbiff12** [ioBroker/ioBroker.zigbee#2234]
Hello ,
I am using version 1.10.9 . When sending ( vacation,sensitivity, duration, update_frequency ) to my Zigbee subscriber (Soda S8 premium window handle ) my adapter crashes and restarts
<img width="1309" alt="Bildschirmfoto 2024-10-13 um 16 16 07" src="https://github.com/user-attachments/assets/00af1dfd-7936-4742-9aa2-cd2875386022">

With kind regards

Jeff

**Comment by asgothian** [comment]
Duplicate of #2211
