### ISSUE TITLE
TZE204_hiith90n non pris en charge sur HA

### ISSUE THREAD

**Issue by pyloutom** [ioBroker/ioBroker.zigbee#2237]
![Pb disjoncteur1](https://github.com/user-attachments/assets/d25293d7-50d2-4933-b3c3-58387222b51f)
![Pb disjoncteur](https://github.com/user-attachments/assets/f1b5bff1-cd4f-423b-a07d-ece8f4f4b34a)
Bonjour

Je n'arrive pas à trouver un convertisseur pour le modèle _TZE204_hiith90n.

Pourriez-vous m'aider à trouver un convertisseur compatible, ou bien m'indiquer une solution si aucun convertisseur n'existe pour ce modèle

Merci beaucoup pour votre aide

**Comment by pyloutom** [comment]
![Pb disjoncteur2](https://github.com/user-attachments/assets/009a84be-c4a5-4e96-8a9b-3aea0c6767ca)
 Pour info c'est un disjonteur avec compteur de courant.

**Comment by asgothian** [comment]
I am afraid my French is not good enough to understand the above 2 comments.

**Comment by pyloutom** [comment]
Good morning

I can't find a converter for the _TZE204_hiith90n model.

Could you help me find a compatible converter, or give me a solution if no converter exists for this model?

Thank you very much for your help, FYI it is a circuit breaker with current meter. Sorry i use translate

**Comment by asgothian** [comment]
you can try to follow the [documentation](https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html) to get an external converter. But as it is a tuna device, transferring that to the zigbee Adapter may be difficult and implementing the device requires physical access to the device.

**Comment by pyloutom** [comment]
thank you I managed to connect it just that it is not supported by ZTM I cannot find an external converter at the moment

**Comment by asgothian** [comment]
you will need to make one. I doubt there is one in existence, if it is not on the z2m resources

**Comment by pyloutom** [comment]
ok I will try thanks
