### ISSUE TITLE
UNCAUGHT_EXCEPTION

### ISSUE THREAD

**Issue by fonebone42** [ioBroker/ioBroker.zigbee#2239]
with the ZigBee adapter v1.10.9 and a RaspBee II, I'm working on a Blocky implementaition of a dimmer using the Hue Tap Dial to change brightness of a group of 2 Hue lightbars (all directly on the ZigBee adapter). When rotating the dial forth an back the dimming suddenly stops and the log shows that the ZigBee adapter has crashed:

```
<html><body>
<!--StartFragment-->
zigbee.0 | 2024-10-16 22:14:55.297 | info | terminating
-- | -- | -- | --
zigbee.0 | 2024-10-16 22:14:55.066 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2024-10-16 22:14:55.066 | debug | Plugin sentry destroyed
zigbee.0 | 2024-10-16 22:14:55.065 | info | terminating
zigbee.0 | 2024-10-16 22:14:54.907 | debug | Stack trace for null: TypeError: Cannot read properties of undefined (reading 'resolveEntity')     at Groups.queryGroupMemberState (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:176:52)     at Zigbee.callPluginMethod (/opt/iobroker/node_modules/iobroker.zigbee/main.js:898:25)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:764:29
zigbee.0 | 2024-10-16 22:14:54.906 | error | Send command to 1 failed with no error code (undefined)
zigbee.0 | 2024-10-16 22:14:54.902 | error | Failed to call 'Groups' 'queryGroupMemberState' (TypeError: Cannot read properties of undefined (reading 'resolveEntity')     at Groups.queryGroupMemberState (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:176:52)     at Zigbee.callPluginMethod (/opt/iobroker/node_modules/iobroker.zigbee/main.js:898:25)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:764:29)
zigbee.0 | 2024-10-16 22:14:54.887 | debug | DeviceAvailability:Publish LQ for 0x60a423fffe371bc6 = 0
zigbee.0 | 2024-10-16 22:14:54.884 | debug | DeviceAvailability:Publish available for 0x60a423fffe371bc6 = false
zigbee.0 | 2024-10-16 22:14:54.881 | debug | DeviceAvailability:Publish LQ for 0x60a423fffe3718a3 = 0
zigbee.0 | 2024-10-16 22:14:54.879 | debug | DeviceAvailability:Publish available for 0x60a423fffe3718a3 = false
zigbee.0 | 2024-10-16 22:14:54.876 | debug | DeviceAvailability:Publish LQ for 0x847127fffe7875a5 = 0
zigbee.0 | 2024-10-16 22:14:54.872 | debug | DeviceAvailability:Publish available for 0x847127fffe7875a5 = false
zigbee.0 | 2024-10-16 22:14:54.869 | debug | DeviceAvailability:Publish LQ for 0x60a423fffe371b8e = 0
zigbee.0 | 2024-10-16 22:14:54.866 | debug | DeviceAvailability:Publish available for 0x60a423fffe371b8e = false
zigbee.0 | 2024-10-16 22:14:54.864 | debug | DeviceAvailability:Publish LQ for 0x60a423fffe445432 = 0

<!--EndFragment-->
</body>
</html>
```

mod-edit: corrected code tags

**Comment by fonebone42** [comment]
I'm doing this here (the transition_time of the group is set to 0.5sec)
![image](https://github.com/user-attachments/assets/6eacf44e-864f-4274-aefa-8e3d7a2d9957)
and it happens if I wildly turn the dial left and right which I did for testing

what exactly do you mean with "the correct code tags" ?

**Comment by asgothian** [comment]
Github knows 2 kinds of code tags. `Inline code tags`, which you generate by first clicking on the <> button and then pasting the data between them. these are for single line code snippets or inline code
and then there is the proper code tags as used in the post above (remember, I edited it). Those are generated by first pasting the code in, then selecting the code and pressing <>. Try it, you will see the difference.

Now to the issue: What you are doing is blasting the zigbee network with messages with no flood protection. Your script can generate in excess of 100 messages per second, depending on what you do with that dial. Please explain how the dial works in detail, and have a look at the brightness_move state. (setting that to a positive number will slowly dim the group brighter, speed depending on the number, while a negative value will slowly dim the group darker, again, speed depending on the number, while a value of 0 will stop at the given brightness.

A.

**Comment by fonebone42** [comment]
thanks for explaining the github issue !

the dial that I'm using is this one here: [Hue Tap Dial](https://www.zigbee2mqtt.io/devices/8719514440937_8719514440999.html).
It consists of 4 buttons and a rotating ring around the buttons. The rotating ring can be used to dim lights just by turning it.

here's the list of objects that it has including that ones that indicate 3 speeds of rotation for each direction:
![image](https://github.com/user-attachments/assets/d3e4de7c-ee33-4cc1-957d-ce5f62430d09)
I'm not sure whether you can configure it with a max number of messages per second ... let me try any play around with it a bit more.
It would also be nice to find out how the Hue bridge would deal with this ... any idea how we could find out (I still have one, so I could try)?
I can also try using the brightness_step_up/down events instead to see whether this avoids flooding

**Comment by fonebone42** [comment]
regarding your statement about flood control .... I don't quite agree with your view as if not having flood control will crash the adapter so all others will anyway be impacted. I think it would still be better to have flood protection and highlight it as and error with the message to review the user's code to make it produce less events.

**Comment by asgothian** [comment]
We will have to agree to disagree there. And a screenshot of the objects does little to explain how they work.

configuring a device to limit the number of messages per second is not usually feasible. Nor is it needed. Fluent dimming is **never** achieved by setting a long transition time and fast update on the target brightness. Instead, it is meant to be achieved using the above mentioned brightness_move datapoint, which is why it exists for groups.

A.

**Comment by asgothian** [comment]
If you want to try with the step events, use should be reasonably simple. Just define a value for 'step' and then set the positive value into the `brightness_step` state of your target group whenever the `dial_rotate_right_step` triggers, and as negative value when the `dial_rotate_left_step` triggers. (or vice versa)

**Comment by fonebone42** [comment]
this here seems to avoid running into the crash:
![image](https://github.com/user-attachments/assets/ad105fad-8b9b-4910-b87d-4064e31f1c77)
I also tried `dial_rotate_right_step` / `dial_rotate_left_step` but the above seems simpler as just using the `dial_rotate_right_step` is not sufficient because if you turn the dial a bit faster it will go to false and the `dial_rotate_right_slow` and later `dial_rotate_right_fast` will go to true instead i.e., only one of the 3 is true at a time.

**Comment by asgothian** [comment]
closing this, as a workaround exists, and no work is being done on the anti-flood system
