### ISSUE TITLE
COM Port Settings can't be SET  BANNER Too BIG

### ISSUE THREAD

**Issue by krzlison** [ioBroker/ioBroker.zigbee#2245]
Zigbee Banner  ist too big and covers the COM port Settings, can not be scrolled up 
![Zigbee Problem](https://github.com/user-attachments/assets/18311ba1-a459-4409-9554-c770083c9438)
![Zigbee Problem](https://github.com/user-attachments/assets/f78bf742-d127-4a8d-8f41-389df1064e8f)

**Comment by asgothian** [comment]
When did you do the install ? This was fixed yesterday.

Also, this is linked to using the latest admin, rather than the current stable admin.

**Comment by krzlison** [comment]
![obraz](https://github.com/user-attachments/assets/2fcb3316-9969-4538-935c-fde984a55fd8)
I update today to the latest versions

**Comment by asgothian** [comment]
Please verify manually that the index_m.html on your system matches the GitHub version
