### ISSUE TITLE
CC2531 Backup/Cloning/maybe Firmware-Update WITOUT LOOSING PAIRING with SmartRF04EB

### ISSUE THREAD

**Issue by bl4ckwhiteeagle** [ioBroker/ioBroker.zigbee#225]
Many thanks for the hard work, if its working its good but...

The CC2531 Pairing gets lost by only changing the channel from 11 to 25 and by restoring a backup of /opt/iobroker which had the channel 11 configured. Reverting back to the other channel isn't working, as the device resets itself.

I've to pair about ~30 devices again, because of only changing the channel. This should be implemented as any other HUB is able to switch this easily.

And now because of the Xiaomi Switches Pairing problems, i had to restore an old backup, but now i've to start the long pairing process another time, as here was the old channel 11 defined and i didn't knew about the device reset.

I've the old stable Firmware ~201810  on the stick, so this shouldn't be a problem.

The CC2531 device needs a simple backup function of the pairings urgently:
*send code 0x34894 an get csv of devices lists with codes CC2531
*send code 0x34895 put back the csv list with codes to the CC2531

The channel changing feature should be marked also RED with a big warning and must be ckecked twice.

I've spent now about 4-5 days of my life and i regret it a little bit, that i bought those devices for so much money....

Please solve it, as this is a really nice Project.

Many Thanks!
Mathias

**Comment by bl4ckwhiteeagle** [comment]
Okay now i've an SmartRF04EB debugger:
You can backup the whole flash of the CC2531 and clone it to a new device. The pairing doesn't get lost, so you can backup the device by this way:

1. You've to use the SmartRF Studio 7, select the 2.4Ghz Tab and the CC2531 device and Tools 8051 MCU
2. At "Flash image:" define a NEW Filename i.E. backup20190318205 in a directory.
3. Under "Actions" check "Read flash into hex-file"
4. Connect the CC2531 with the debugger and put it into the USB-Port
5. Press the Reset button for a second
6. Check if "Read flash into hex-file" is checked and Press "perform action"

You can write this image to a new CC2531

Another thing is, that you can upgrade the firmware WITHOUT LOOSING the pairing, too. Maybe this is not everytime possible, but worth a try.
I upgraded the firmware by downloading and simply copying the Data by this way:

1. Download & take a copy of the Firmware HEX file from Koenkk 
2. Edit it with i.E. with Notepad++ 
3. Deleted the first Line :020000040000FA 
4. Open the backup File you've already taken of your dongle in another tab
5. Search for the line :10C7F000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF49 or go to the Line 15495
6. Copy everything after that line :10C7F000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF49
7. Replace the Lines after :10C7F000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF49 included the last two short Lines, too i.E. :0400000500002D6367 & :00000001FF.
8. Flash it back to you dongle

I tried this method with the Firmware 20190223 (alternatives/max_devices) from https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531 and the new 20190315 from https://github.com/Koenkk/z-stack-firmware/issues/46

This seems to be so easy and it worked with the first try :)

All my Lamps, Plugs, Xiaomi Light Switches, Temperature or Magnet Sensors registered and work without any problems :)))

@Koenkk could this be a method, we can always use? 
Or could this be a problem with the flash/adresses of custom variables/datagrams used in future-firmwares?
Do we've to translate/rewrite the adresses in the Datagram, so nobody has to re-pairing those many devices anymore :)

Maybe you, or someone else could write a simple cmd-tool, which clones this part for an simple upgrade without looing the paring.

Can anybody test and confirm my method too?

So this is my contribution to this project
M. Lützner

**Comment by Koenkk** [comment]
AFAIK you can already upgrade the firmware without doing all of this, this is something that has been introduced in the 20190223 firmware. Many people confirmed that this works.

About the channel changing, I dont know. as far as I understand is that the devices arent aware of the new channel, but I'm not sure.

**Comment by apeeters** [comment]
I was also able to swap coordinator devices without re-pairing (did not change channel).

**Comment by bl4ckwhiteeagle** [comment]
Damn =D I've found the firmware by another post directly and I didn't read the new release notes, but i like to know the complicated way and binary data :)

The releasenotes should be included in the ZIP file, if this is possible.

But if someone uses an older firmware and tries to upgrade, my instruction could be helpful as i came from the 201810 FW too :)

The dev 20180315 firmware (normal) is working really stable for now :) Thank you very much @Koenkk WELL DONE!

Rejoin Problem lumi.weather lumi.sensor_motion.aq2:
I've had to reconnect only two lumi.weather and one lumi.motion devices as they didn't rejoin the zigbee network, even after replacing the battery or pressing the button. They worked fine for about a day. I've read that their firmware isn't implemented correctly or that i've to disable the rejoin function? Is it possible to disable this rejoin-function by every single device, as long as we need it?

Channel Change:
I don't own the Xiaomi Gateway but with this, it should be possible to change the channel directly, but i think that the devices get then a channel-change-info. But changing back to the original channel didn't work, the devices didn't respond anymore. If i find some time, i'll test again. I've ordered 4 another CC23531 already as i own the flasher :)

Thanks :)

**Comment by Koenkk** [comment]
It doesn't matter which firmware you are coming from, even when coming from a very old version, you dont have to re-pair.

**Comment by baerengraben** [comment]
@bl4ckwhiteeagle: I realy appreciate your contribution. I'm Using an older Firmware and all of my devices are working well. But I also spend days doing the paring / repairing thing. Once everything was working I NEVER EVER touched the Devices again. No updates at all. But maybe now I will give it a try.
