### ISSUE TITLE
Ikea E2002 and E2213 states are null

### ISSUE THREAD

**Issue by Grievous1900** [ioBroker/ioBroker.zigbee#2251]
I paired an Ikea E2213 shortcut button and two E2002 remotes via a Phoscon Conbee II with the zigbee adapter. 
The devices seem to be identified correctly, but the battery state and the states for button presses always remain on the value null. 
The only exception is the on/off states for the E2002, when pressing the top and bottom button repspectively. Holding the right or left arrow also trigger the on state instead of the arrow_left_hold and arrow_right_hold states. 

I instead also paired the devices with the ikea tradfri gateway, where they worked properly.

Update: A firmware update of the E2002 from 2.4.5 to 2.4.16 via the tradfri gateway fixed a few of the problems. But the following states are still not working with the E2002:
- arrow_left_hold
- arrow_right_hold
- battery

A firmware update of the E2213 did not fix anything.

**Comment by asgothian** [comment]
Please add the last 8 digits of the device Id of the device to the state `zigbee.0.info.debugmessages`, press the buttons and check the log for elevated warning messages following the rules described [here](https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages).
It will tell you if the device sends data for these states at all.

**Comment by Grievous1900** [comment]
I don't get any publishToState messages for the E2213. In the case of the E2002 I only get publishToState messages for linkquality every few hundred miliseconds if I hold the left or right arrow key.

**Comment by asgothian** [comment]
Are the devices listed as “configured:true” on the info page ? If not, keep the devices awake and try a reconfigure

**Comment by Grievous1900** [comment]
Reconfiguring the E2002 does not change anything. It is successful (according to the logs) but it is still listed as configured: false.
Trying to reconfigure the E2213 while pressing buttons on it produces the following log message: 

DeviceConfigure: 0xecf64cfffe35b28e SOMRIG shortcut button Failed to configure. When device works is all fine when not wake up the device and check again.

According to the logs the zigbee adapter receives linkquality messages from the E2213 from time to time. But it does not seem to be related to any button pushes.

**Comment by asgothian** [comment]
You will need to retry the configure. The shortcut button did not accept the configuration message. They are finicky like that and sometimes need more than one try

**Comment by Grievous1900** [comment]
I tried to reconfigure it dozens of times throughout the last days, but I always got the "Failed to configure" message.

**Comment by asgothian** [comment]
> I tried to reconfigure it dozens of times throughout the last days, but I always got the "Failed to configure" message.

this is an issue between the coordinator firmware and the device firmware. The wireless connection between the remote and the coordinator could also have an effect.

There is nothing the adapter can do.

**Comment by Grievous1900** [comment]
Okay, thank you for the help.
