### ISSUE TITLE
white text on white background

### ISSUE THREAD

**Issue by fonebone42** [ioBroker/ioBroker.zigbee#2258]
I'm experiencing this here in 1.10.10 when hovering over one of the devices in the network view

![image](https://github.com/user-attachments/assets/a54a8f43-f409-43ea-837a-ec66c1e3a3bd)

the tool tip would be nice if readable :-)

**Comment by asgothian** [comment]
The only short term solution I can offer ist to not use dark mode for the map.


I have no time to deal with this, so while the bug is on the list, do not expect any quick fix.

**Comment by fonebone42** [comment]
good to have it registered, this is not an essential issue, so fixing may stand behind other priorities ....

**Comment by arteck** [comment]
in next Version 

![grafik](https://github.com/user-attachments/assets/9b70b29a-5fe7-40aa-b493-9e7864d75b97)
![grafik](https://github.com/user-attachments/assets/d3fb69f8-5ccb-4160-aeb6-6b6d3ea5cf44)
