### ISSUE TITLE
Please add SONOFF ZBMINIR2

### ISSUE THREAD

**Issue by berwil84** [ioBroker/ioBroker.zigbee#2259]
Currently this Adapter isn't supported. 
Please add.

Kind Regards
Bernd

Details:

modelZigbee:ZBMINIR2
type:Router
nwk:62763
manuf id:4742
manufacturer:SONOFF
power:Mains (single phase)
app version:16
hard version:16
zcl version:3
date code:20240509
build:1.0.1
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genOnOff (6)
haDiagnostic (2821)
manuSpecificAmazonWWAH (64599)
64529
output clusters:genIdentify (3)
genOnOff (6)
genOta (25)
endpoint:242
profile:41440
output clusters:greenPower (33)

**Comment by berwil84** [comment]
It is already listed on zigbee2mqtt: https://www.zigbee2mqtt.io/devices/ZBMINIR2.html

**Comment by asgothian** [comment]
which adapter version did you test this ?

**Comment by berwil84** [comment]
Tested on v1.10.3Am 28.10.2024 19:44 schrieb asgothian ***@***.***>:
which adapter version did you test this ?

**Comment by asgothian** [comment]
Please test with the current GitHub version. There already was an issue about this device and it was confirmed to work in an earlier version.
