### ISSUE TITLE
code 10 (Cannot find start file of adapter)

### ISSUE THREAD

**Issue by mikkel75** [ioBroker/ioBroker.zigbee#226]
Hi,

I can't seem to get rid of this code 10 error - have tried most I should think
- new and old stable zigbee firmware
- started iobroker with sudo
- chmod 777 /dev/ACM0

Any ideas??

/M

host.raspberrypi | 2019-03-05 21:42:30.460 | error | instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)
-- | -- | -- | --
host.raspberrypi | 2019-03-05 21:42:27.846 | info | instance system.adapter.zigbee.0 started with pid 2453
host.raspberrypi | 2019-03-05 21:41:57.823 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.raspberrypi | 2019-03-05 21:41:57.822 | error | instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)
host.raspberrypi | 2019-03-05 21:41:55.118 | info | instance system.adapter.zigbee.0 started with pid 2442
host.raspberrypi | 2019-03-05 21:41:55.092 | info | object change system.adapter.zigbee.0
host.raspberrypi | 2019-03-05 21:41:54.053 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.raspberrypi | 2019-03-05 21:41:54.052 | error | instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)
host.raspberrypi | 2019-03-05 21:41:51.467 | info | instance system.adapter.zigbee.0 started with pid 2431
host.raspberrypi | 2019-03-05 21:41:21.444 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.raspberrypi | 2019-03-05 21:41:21.443 | error | instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)
host.raspberrypi | 2019-03-05 21:41:18.858 | info | instance system.adapter.zigbee.0 started with pid 2420
host.raspberrypi | 2019-03-05 21:40:48.833 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.raspberrypi | 2019-03-05 21:40:48.832 | error | instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)
host.raspberrypi | 2019-03-05 21:40:46.235 | info | instance system.adapter.zigbee.0 started with pid 2407
host.raspberrypi | 2019-03-05 21:40:16.208 | info | Restart adapter system.adapter.zigbee.0 because enabled

**Comment by Apollon77** [comment]
Please do

iobroker upload zigbee

On command line or via admin ui the upload button at zigbee adapter. 

Works it afterwards?

**Comment by mikkel75** [comment]
Hi,
Thanks for your input - however it didn't solve my issue....

pi@raspberrypi:~/node_modules/iobroker.zigbee $ sudo ./iobroker upload zigbee
got /home/pi/node_modules/iobroker.zigbee/admin
upload [90] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/unknown.png img/unknown.png image/png
upload [80] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/sensor_motion_aq2.png img/sensor_motion_aq2.png image/png
upload [70] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/philips_hue_rwl021.png img/philips_hue_rwl021.png image/png
upload [60] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/osram_surface_light_tw.png img/osram_surface_light_tw.png image/png
upload [50] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/lumi_lock_v1.png img/lumi_lock_v1.png image/png
upload [40] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/innr.png img/innr.png image/png
upload [30] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/gledopto_bulb.png img/gledopto_bulb.png image/png
upload [20] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/cube.png img/cube.png image/png
upload [19] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/ctrl_neutral2.png img/ctrl_neutral2.png image/png
upload [18] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/ctrl_neutral1.png img/ctrl_neutral1.png image/png
upload [17] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/ctrl_ln2.png img/ctrl_ln2.png image/png
upload [16] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/ctrl_ln1.png img/ctrl_ln1.png image/png
upload [15] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/contact.png img/contact.png image/png
upload [14] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/bitron_plug.png img/bitron_plug.png image/png
upload [13] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/battery_v.png img/battery_v.png image/png
upload [12] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/battery_p.png img/battery_p.png image/png
upload [11] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/aqara_temperature_sensor.png img/aqara_temperature_sensor.png image/png
upload [10] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/aqara_numan_body_sensor.png img/aqara_numan_body_sensor.png image/png
upload [9] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/aqara_bulb.png img/aqara_bulb.png image/png
upload [8] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/aqara.switch.png img/aqara.switch.png image/png
upload [7] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/TRADFRI.remote.control.png img/TRADFRI.remote.control.png image/png
upload [6] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/TRADFRI.bulb.E27.png img/TRADFRI.bulb.E27.png image/png
upload [5] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/FLOALT.panel.WS.png img/FLOALT.panel.WS.png image/png
upload [4] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/Eurotronic_Spirit_04.png img/Eurotronic_Spirit_04.png image/png
upload [3] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/86sw2.png img/86sw2.png image/png
upload [2] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/86sw1.png img/86sw1.png image/png
upload [1] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/img/86plug.png img/86plug.png image/png
upload [0] zigbee.admin /home/pi/node_modules/iobroker.zigbee/admin/admin.js admin.js application/javascript


I still get the log filled with

host.raspberrypi | 2019-03-06 09:36:31.376 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.raspberrypi | 2019-03-06 09:36:31.373 | error | instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)
host.raspberrypi | 2019-03-06 09:36:28.756 | info | instance system.adapter.zigbee.0 started with pid 638
host.raspberrypi | 2019-03-06 09:35:58.734 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.raspberrypi | 2019-03-06 09:35:58.732 | error | instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)
host.raspberrypi | 2019-03-06 09:35:56.098 | info | instance system.adapter.zigbee.0 started with pid 626
host.raspberrypi | 2019-03-06 09:35:26.069 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.raspberrypi | 2019-03-06 09:35:26.066 | error | instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)

Is it the correct way I start iobroker up?
pi@raspberrypi:~/node_modules/iobroker.zigbee $ sudo ./iobroker start
Starting iobroker controller daemon...
iobroker controller daemon started. PID: 535

Or do I have to use node?

The web interface works fine, but something most be broken with the serial interface - any suggestions on how to test that or reinstall that?

MANY THANKS

**Comment by mikkel75** [comment]
Please can someone point me to a guide on how to install and start iobroker.zigbee correctly?

I have tried to follow the guide for zigbee2mqtt and that works like a charm - that also connects fine to my CC2531.

**Comment by mikkel75** [comment]
Reinstalled iobroker from scratch and zigbee plugin from within iobroker webpage and this works.... :)
