### ISSUE TITLE
New device support: Philips Datura Big

### ISSUE THREAD

**Issue by markuswebert** [ioBroker/ioBroker.zigbee#2263]
Can you please add device support for the "Philips Datura Big", that was added to zigbee2mqtt today https://www.zigbee2mqtt.io/devices/929003736101.html? Is there anything I can help with?

Thanks!

**Comment by asgothian** [comment]
No. You will need to wait til the latest zigbee-herdsman-converts has been integrated into the adapter.

A.

**Comment by markuswebert** [comment]
Sounds like a plan, thank you!

**Comment by ma-gu-16** [comment]
i have the same lamp. but the small version of it.  ive installed it today and it paired, but it shows only the ? , guess not supported.  is there a timeline/roadmap when this herdsmann-convers will be integrated and the lamp added ? can i help somehow :)  thank you.
