### ISSUE TITLE
Xiaomi WXKG02LM doesn't pair anymore since 0.9x

### ISSUE THREAD

**Issue by bl4ckwhiteeagle** [ioBroker/ioBroker.zigbee#227]
Xiaomi WXKG02LM or lumi.sens doesn't pair anymore in 0.92. There are no logs! I reset both devices many times!
I tried everything as it worked with CC2531 and old stable FW 201810...with older versions 0.8x

They worked fine with the new version, but after an issue with the channel/changing which made an reset to the CC2351, the pairing got lost.

Lamps/Router like  ZBT-ExtendedColor, TRADFRI bulb E27 CWS opal 600lm, Osram Plug 01 pairs without any problems.

And non router devices like lumi.sensor_motion.aq2 and lumi.sensor_magnet.aq2 pairs fine.

Please solve it fast!

I can do a test again later, but i don't have a firmware flasher!
Many thanks!

**Comment by bl4ckwhiteeagle** [comment]
After several restart of the iobroker and the cc2351 driver yesterday, and leaving the system alone about 24h the first xiaomi did connect over night after the 60 seconds timer.
The second switch could now connect without any problems too, but i get an  Node Descriptor error in the 60 seconds. After this, the 2nd switch got connected and works too.

zigbee.0 | 2019-03-06 23:27:54.508 | info | new dev 0x...28 45023 lumi.remote.b286acn01
-- | -- | -- | --
zigbee.0 | 2019-03-06 23:26:10.060 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-03-06 23:25:56.604 | error | Cannot get the Node Descriptor of the Device: 0x...28 (Error: Timed out after 10000 ms)
zigbee.0 | 2019-03-06 23:25:07.622 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-03-06 23:23:53.649 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-03-06 23:23:46.494 | error | Cannot get the Node Descriptor of the Device: 0x...28 (Error: Timed out after 10000 ms)
zigbee.0 | 2019-03-06 23:23:26.491 | error | Cannot get the Node Descriptor of the Device: 0x...28 (Error: Timed out after 10000 ms)
zigbee.0 | 2019-03-06 23:22:51.538 | info | Zigbee: allowing new devices to join.

I ordered 5 more switches some days ago, i'll receive them in about 2-3 weeks. Then i can test again and more. I'll report here again.

**Comment by nob0dy80** [comment]
this isnt a bug.. this is just normal.. some devices take several times to pair. neded half a day to pair 30 devices .. Cannot get the Node Descriptor of the Device is just a simple paring error..if you get this, retry.

**Comment by bl4ckwhiteeagle** [comment]
Thank you for the answear! I thought this behavior isn't normal, because in the older version i've got both switches i own much faster connected to the stick in about 5 Min. Now it takes many hours, after soft-resetting the iobroker or CC2531 or USB-driver! I'll test again, when i've got the other switches.

The Xiaomi lumi.sensor_magnet.aq2 Magnet Sensor seems to have the same problem. Maybe something was changed here in the code?

**Comment by nob0dy80** [comment]
@bl4ckwhiteeagle 
i dont know. i started late with this adapter. so i just know it as slow as it is now.

best experience i had is, when i try to pair it close to the coordinator. 
when you try to pair it, take a look at the sensor-LED:

take your sensor and go close to the coordinator, hit the green allow-join button in the adapter, hold down the reset button on your sensor till the LED goes on, release the button in this moment.
Take a look at the sensor led's blinking code that will follow after 2-3 seconds:

- 1 long led blink = no zigbee communication found or error; will mostly end up in Error: Timed out after 10000 ms
- 3 short blinks = zigbee communcation found; most times it will pair now.

If you saw it 3 times blinking after a reset and the pairing counter is to 0, just wait a minute longer. sometimes communication is slower then the 60 seconds timer but i will show up anyway

thats all i found out till now, hope it helps

**Comment by bl4ckwhiteeagle** [comment]
Thany you for your answear, so i did everything right.
But this should help everyone else, who has those equivalent problems.

Okay, now i've done enough tests:

I've got a new SmartRF04EB debugger and a new CC2531 with an modded external antenna with a much more range and flashed the firmware CC2531ZNP-Prod_20190223 alternatives/max_devices) from Koenkk and it works now almost without any problems (I've somtimes a firmware related memory heap/crash after 1-2 days and excessive usage - there exists already another firmware, but this is another case and very rar, and after restarting the USB HW-Device, it works again)


5 of 7 Xiaomi lumi.remote.b286acn01 devices paired with the new CC2531+Antenna with the 1st or 2nd try and the saw the Zigbee network with a 3 times LED flashing immediately:
My Lamps: TRADFRI bulb E27 CWS opal 600lm, ZBT-ExtendedColor (Mueller Licht)
The Osram Smart Plug+ (All with the 1st try)
As the Xiaomi Devices: lumi.sensor_magnet.aq2, lumi.sens, lumi.sensor_motion.aq2 and the lumi.weather connected as usually fast.
But much faster as with the other dongle/older firmware or Zigbee Adapter 0.10.2 :)

(((This wasn't the case with the older CC2531 without an ext. Antenna and a Xiaomi switch lying directly to it or with a small range ~20cm.
The Switch did recognized the Zigbee Network after many tries, but didn't connect, even after a Reset.)))

I installed the 0.10.2 Zigbee Adapter and there seems to be no problems with the pairing, too.

So it semmed to be a problem with the firmware/the switch communication or whatever. 

But the 20190223(alternatives/max_devices) has a Problem with a memory/crash. I'll investigate here too, but this is another Problem.

I'll dig into cloning the device parings with the ext. Debugger now for further tests, so this case can be closed now.

Many Thanks
M. Lützner

**Comment by nob0dy80** [comment]
@bl4ckwhiteeagle 
i really wouldnt use the max devices firmware. 
dont forget, all your lamps and plugs are routers too which are able to connect more devices. normally, the max_devices firmware isnt needed!

**Comment by bl4ckwhiteeagle** [comment]
Thanks for your reply!
Yes, i can agree with this and i knew of the router functions of almost every external powered device.
Even externally powered light switches are able to route, if they support this, but i don't own such a thing as my bulbs are all zigbee ready :)

I tried the other firmware for testing purposes only. The memory of the device is not enough for this.
The latest dev 20180315 firmware (normal) is working really stable for now :)
