### ISSUE TITLE
Update Firmware Z03MMC

### ISSUE THREAD

**Issue by Skol6** [ioBroker/ioBroker.zigbee#2277]
Hi,

ich würde gerne meine Xiaomi Temperatursensoren auf eine andere Firmware bringen.
die aktuelle braucht leider sehr viel Strom.

Wie kann ich das beim Zigbee Adapter einstellen, das er das bin von hier verwenden soll:
https://github.com/pvvx/ZigbeeTLc 

Ich steh da irgendwie an.
Vielen Dank

**Comment by asgothian** [comment]
Das lässt sich aktuell nicht einstellen. Die Firmware wird vom Server des Herstellers vorgegeben.

A.
