### ISSUE TITLE
Hi ich habe den neuen 24 Ghz Human Presence Sensor bei ALI bestellt

### ISSUE THREAD

**Issue by flotzke** [ioBroker/ioBroker.zigbee#2281]
Der neue 24 GHz HP-Sensor wird nur wie auf dem Bild erkannt.
Könnt ihr ihn bitte hinzufügen?
Vielen Dank und Gruss,
Flo

![20241107_104937](https://github.com/user-attachments/assets/3b21f604-b772-4b69-bdbc-899e655efa31)
![20241106_184009](https://github.com/user-attachments/assets/fe85e539-db03-4f89-8b2f-08dd444a9aed)
![20241106_183817](https://github.com/user-attachments/assets/b6d6e284-f5d5-46a4-81de-c231ac46b1a5)

**Comment by asgothian** [comment]
- hast du getestet ob der mit der aktuellen Github Version unterstützt ist ?
- hast du geschaut ob er bei zigbee2mqtt.io als unterstützt gelistet ist ?


A.

**Comment by flotzke** [comment]
Bei zigbee2mqtt.io ist er gelisted als Tuya ZY-M100-24G aber den Adapter habe ich nicht installiert.
Müsste er dann automatisch auch im iobroker.zigbee Adapter gehen ?
Auf der Liste der aktuellen Github Version wird ja auf zigbee2mqtt verwiesen..

**Comment by asgothian** [comment]
> * hast du getestet ob der mit der aktuellen Github Version unterstützt ist ?
> 
> A.

Probier es aus.

**Comment by flotzke** [comment]
> > * hast du getestet ob der mit der aktuellen Github Version unterstützt ist ?
> > 
> > A.
> 
> Probier es aus.

Hab ich natürlich 

> * hast du getestet ob der mit der aktuellen Github Version unterstützt ist ?

Ist er nicht sonst hätte ich nicht angefragt.
Meine Version 1.10.3 funktioniert eben nicht mit diesem.

**Comment by asgothian** [comment]
> Meine Version 1.10.3 funktioniert eben nicht mit diesem.

Das ist nicht die aktuelle github Version.

**Comment by flotzke** [comment]
sondern?

**Comment by flotzke** [comment]
Du hast absolut Recht. Danke ;) Er funktioniert !
