### ISSUE TITLE
zigbee instance setup page incomplete

### ISSUE THREAD

**Issue by averlon** [ioBroker/ioBroker.zigbee#2282]
zigbee 1.10.9
admin 7.2.6

The view of the zigbee admin panel does not show the complete view:

1) it looks like the html-code is broken. The "S" seems that it should not be there where it is!
![grafik](https://github.com/user-attachments/assets/41336a0f-3aec-42d9-824c-3ee895ea1fbc)
2) the headline covers some settings:
![grafik](https://github.com/user-attachments/assets/0479f8d8-92c1-4dfd-bf67-c40157316562)

Browser: Firefox

**Comment by asgothian** [comment]
This is fixed in the current GitHub version (1.10.12). Alternatively, a downgrade of the admin to the current stable 7.1.5 will fix it too.
