### ISSUE TITLE
SONOFF Smart Bewässerungscomputer empfängt/überträgt manuelle Bedienung nicht

### ISSUE THREAD

**Issue by Fleurelle13** [ioBroker/ioBroker.zigbee#2284]
Hi,

erstmal ein Lob. Top-Adapter. Funktioniert bei allen anderen Geräten sehr zuverlässig.

Nur bei dem SONOFF Smart Bewässerungscomputer (https://www.amazon.de/dp/B0D5CTZN63?ref=ppx_yo2ov_dt_b_fed_asin_title) mag er nicht so wie er sollte. Schalten funktioniert zwar über iobroker, schaltet man ihn aber manuell über das Gerät selber, wird diese Änderung in iobroker nicht angezeigt. Auch die anderen Werte wie Durchflussmenge etc. wird nicht in iobroker angezeigt, geändert.

![image](https://github.com/user-attachments/assets/e2fced88-75c9-4cc5-b5d7-3594df5d3245)

![image](https://github.com/user-attachments/assets/286cf3cc-eb12-454d-ab89-48064e2234b5)

![image](https://github.com/user-attachments/assets/781c6c18-6a32-46ac-858d-8eb9a61897d8)

**Comment by fonebone42** [comment]
ich habe auch so ein Teil ... ist zwar im Moment noch nicht im Wasserfluss, aber wenn ich den Taster an der Front des Gerätes betätige, dann ändert sich der State im iobroker (zweitletztes Objekt im Screenshot oben) innerhalb von 2 Sekunden, scheint also ok zu sein ... lass mich das Teil mal ans Wasser anschliessen, so dass ich den Durchfluss testen kann.

**Comment by fonebone42** [comment]
ich habe es eben ausprobiert und der Durchfluss ("flow") wird auch angezeigt.
Ich würde vorschlagen, erst mal sicher zu stellen, dass du eine aktuelle Adapter Version (1.10.12 oder .13) hast und dass die Firmware des SWV auf den neusten Stand bringst. Dann sollte es eigentlich funktionieren.
Ich werde gelegentlich die anderen Funktionen des SWV noch ausprobieren, jetzt wo er angeschlossen ist ....

**Comment by fonebone42** [comment]
ich habe eben noch einen genaueren Blick auf die Objekte des SWV im iobroker geworfen und bin mir nicht ganz sicher, ob alles was auf der [zigbee2mqtt Seite](https://www.zigbee2mqtt.io/devices/SWV.html) beschrieben ist, auch im iobroker korrekt erscheint. Zum Beispiel finde ich die `cyclic_timed_irrigation` und `cyclic_quantitative_irrigation,` die dort erwähnt wird nicht.

Könntet ihr das bitte mal anschauen?

**Comment by arteck** [comment]
> Oder gehen die composites das via `send_payload` ?

ja sollten gehen... und ja wir haben nicht alle DP's im adapter von dem teil

**Comment by Fleurelle13** [comment]
Hallo zusammen,

also bei mir ist alles unverändert. Hab versucht, ein Firmwareupdate zu machen (über den blauen Button im Zigbee-Adapter) und habe folgende Fehlermeldung erhalten: 

![image](https://github.com/user-attachments/assets/b26d11ba-e77c-40bd-9853-db429a8b2888)

Hat jemand eine Idee?

Danke und liebe Grüße
Fleurelle

**Comment by fonebone42** [comment]
sieht schwer nach einer alten Zigbee Adapter Version aus, welche verwendest du im Moment?

**Comment by fonebone42** [comment]
dann musst du zuerst auf 1.10.13 gehen, damit es mit dem Update funktioniert

**Comment by Fleurelle13** [comment]
Die ist aber noch nicht als stable im iobroker. Hab da schon schlechte Erfahrungen mit den Betas gemacht. Wann geht die den stable?

**Comment by fonebone42** [comment]
ich habe die 1.10.13 schon seit sie verfügbar ist am Laufen und hatte bisher keine Probleme.
