### ISSUE TITLE
Zigbee Wasserstandsmelder, _TZ3000_upgcbody, wird nicht erkannt.

### ISSUE THREAD

**Issue by Stan3003** [ioBroker/ioBroker.zigbee#2285]
Hallo,

habe einen Zigbee Wasserstandsmelder gekauft. Leider wird er in iobroker nicht erkannt. Selbst mit der Version 1.10.13 nicht. 

Hier die Daten des Melders:

modelZigbee: SNZB-05
type: EndDevice
nwk: 6322
manuf id: 4742
manufacturer: _TZ3000_upgcbody
power: Battery

Genügen die Infos um ihn verfügbar zu machen?

Vielen Dank im Voraus.

**Comment by asgothian** [comment]
> Genügen die Infos um ihn verfügbar zu machen?

Nein. Da es sich um ein neues device handelt ist Zugriff auf ein device notwendig.

A.

**Comment by Stan3003** [comment]
Anbei meine weiteren Daten. Falls weitere benötigt werden, wie komme ich daran?
![Github](https://github.com/user-attachments/assets/18ac7f8c-e7a0-41c4-995f-a849e6481cec)

**Comment by asgothian** [comment]
Daten alleine werden nicht helfen. Ohne Zugriff auf ein Gerät ist eine erfolgreiche Einbindung nicht möglich. Im Wiki zum Adapter gibt es mehrere Artikel dazu, z.BSp. https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device

A.
