### ISSUE TITLE
Tuya Air Quality Monitor

### ISSUE THREAD

**Issue by futura2703** [ioBroker/ioBroker.zigbee#2297]
### Tested with adapter version

1.10.3

### modelZigbee

TS0601

### manufacturer

_TZE204_dwcarsat

### Link to device

https://www.zigbee2mqtt.io/devices/TS0601_air_quality_sensor.html

### Coordinator type selected in adapter setting

Zigbee Coordinator

### Coordinator

ConBee2/RaspBee2

### Coordinator firmware version and revision

version:0-0.38.114.0. revision:0x26720700

**Comment by asgothian** [comment]
Please test with 1.10.13. it should work.
