### ISSUE TITLE
Osmart Smart+ Bulbs funktionieren nicht mehr unter 0.9.2

### ISSUE THREAD

**Issue by camilios** [ioBroker/ioBroker.zigbee#230]
Hallo,

ich habe Schwierigkeiten die Osram Smart+ Bulbs unter dem 0.9.2. Adapter zu verwenden. Sie lassen sich pairen, aber sobald ich einen Steuerbefehl sende (Switch State, Brightness, Color) schaltet sich die Lampe ab und funktioniert erst wieder nachdem ich ein paar Mal den Strom unterbrochen habe. Danach erneut das selbe Verhalten. Unter 0.9.1. hatte alles noch funktioniert.

**Comment by modmax** [comment]
See issue #218
