### ISSUE TITLE
Sonoff ZBMINIR2

### ISSUE THREAD

**Issue by gelaendekiesel93** [ioBroker/ioBroker.zigbee#2300]
### Tested with adapter version

v1.10.3

### modelZigbee

ZBMINIR2

### manufacturer

SONOFF

### Link to device

https://www.zigbee2mqtt.io/devices/ZBMINIR2.html

### Coordinator type selected in adapter setting

TI Z-STACK/CCxxxx

### Coordinator

Texas_Instruments_TI_CC2531_USB_CDC

### Coordinator firmware version and revision

2-0.2.6.3.

**Comment by asgothian** [comment]
Test with 1.10.13 missing, no action will be taken until that has been done

**Comment by gelaendekiesel93** [comment]
Hi,

Can I test it?
The device is detected but not supported.

![image](https://github.com/user-attachments/assets/3d681da6-29fd-41e0-9f82-b0f8c827af19)
![image](https://github.com/user-attachments/assets/50794507-1d91-4828-a469-b74e143e1436)

These are the only data points created:

![image](https://github.com/user-attachments/assets/1d673481-6fd0-40fb-8abd-6f4ddad4c5c8)

Thank you 👍

**Comment by asgothian** [comment]
Of course you can. You need to install the adapter from GitHub to get the 1.10.13 version

A.

**Comment by gelaendekiesel93** [comment]
Thanks it works :) 
I didn't see the .**1**3 
Have a nice Day

**Comment by JeyR86** [comment]
Test with 1.10.13 was successful, devices has already been integrated.
Please be aware that you have to update to the latest beta version, 
it ist not part of the current stable release.

Thanks to all contributors at this point, 
you are doing a great Job!
