### ISSUE TITLE
Third Reality 3RDTS01056Z not supported

### ISSUE THREAD

**Issue by VMI1** [ioBroker/ioBroker.zigbee#2307]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

device not supported, zigbee2mqtt the device is supported

https://www.zigbee2mqtt.io/devices/3RDTS01056Z.html

![grafik](https://github.com/user-attachments/assets/58bb18f5-5bc4-406c-b2f6-7b4627bb6629)

### Adapter version

1.10.3

### Coordinator firmware version

2-1.2.7.1

### Coordinator

SONOFF USB Dongel E

### Setup

RPI

### Protocol of the error (as text, encapsulated in multiline code tags <>). Separate different occurrances into clearly split log sections

Interview successful: {"friendly_name":"0x282c02bfffec9130","supported":false}
New device joined '0x282c02bfffec9130' model 3RDTS01056Z
Device '0x282c02bfffec9130' announced itself
Interview started: 0x282c02bfffec9130

**Comment by asgothian** [comment]
Please test with the 1.10.13 version from Github.

A.

**Comment by VMI1** [comment]
thanks for the quick respone :)
Now it works.
Thank you
