### ISSUE TITLE
Sunricher Dimmer ZG9101SAC-HP (Wall box)

### ISSUE THREAD

**Issue by killakaktus** [ioBroker/ioBroker.zigbee#231]
Got [THIS](https://www.sunricher.com/zigbee-ac-phase-cut-dimmer-sr-zg9101sac-hp.html) dimmer today. Tested it and it works. Maybe anyone could implement it. The min.set function doesn't work for me but it also didn't work on my Trådfri Gateway.
edit: Min.set works. My fault. 2 sec press sets minimum brightness and 3 sec deletes it. 

No idea if it helps:

devices.js
```
    // Sunricher
    {
        zigbeeModel: ['ZG9101SAC-HP'],
        model: 'ZG9101SAC-HP',
        vendor: 'Sunricher',
        description: 'ZIGBEE DIMMER',
        extend: generic.light_onoff_brightness,
    },

```
devstates.js
```
    // Sunricher
    {
        vendor: 'Sunricher',
        models: ['ZG9101SAC-HP'],
        icon: 'img/immax_e14.png',
        states: lightStates,
        linkedStates: [comb.brightnessAndState],
    },  
```
icon is a placeholder ;)

**Comment by arteck** [comment]
done

**Comment by killakaktus** [comment]
Herzlichen Dank
