### ISSUE TITLE
Probleme mit Hue Wandschalter-Modul

### ISSUE THREAD

**Issue by fonebone42** [ioBroker/ioBroker.zigbee#2315]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

ich versuche ein [Hue wall switch module](https://www.zigbee2mqtt.io/devices/929003017102.html) einzubinden. Das pairing funktioniert tadellos, aber wenn ich die Objekte anschaue, dann fehlen Einträge, die auf der zigbee2mqtt Seite erwähnt sind, wie z.B. `left_press_release`. Eigentlich sollte das Teil in zwei Modi betrieben werden können: `push_button` und `rocker`. Auch wenn ich den Modus über `device_mode` einstellen kann, ich bekomme das Ding nicht im `rocker` Modus dazu das zu tun, was ich erwarten würde. Weder bleibt der `left_press` Zustand auf `true`, wenn der Schalter ein ist (er fällt immer gleich wieder auf `false` zurück), noch ist `left_hold` irgend ein Wert zu entlocken (ditto für die `right_*` Varianten).
Verstehe ich das Teil falsch, oder funktioniert es nicht so, wie es sollte?

![grafik](https://github.com/user-attachments/assets/e546f6b7-840e-4ea5-ae7e-2b6bb123b9b5)

### Adapter version

1.10.13

### Coordinator firmware version

version:0-0.38.114.0. revision:0x26720700

### Coordinator

RaspBee II

### Setup

Raspberry Pi 4

**Comment by arteck** [comment]
wechsel bitte auf zigbee2mqtt... wenn du alle funktionen nutzen willst.. wir bilden nicht alles ab.
