### ISSUE TITLE
Tuya RB-SRAIN01 is recognized as water leak detector

### ISSUE THREAD

**Issue by Smo-RBR** [ioBroker/ioBroker.zigbee#2319]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

The Tuya RB-SRAIN01 is recognized as water leak detector. It should expose rain and light intensity

ieee:0xa4c1385b15206613
nwk:55508 (0xd8d4)
model:[TS0207_water_leak_detector](https://www.zigbee2mqtt.io/devices/TS0207_water_leak_detector.html)
groups:

zigbee2mqtt page for the device:
https://www.zigbee2mqtt.io/devices/RB-SRAIN01.html

### Adapter version

1.10.3

### Coordinator firmware version

0-0.38.120.0. revision:0x26780700

### Coordinator

ConBee2/RaspBee2

### Setup

Ioborker on Ubuntu host

**Comment by asgothian** [comment]
Please test with the current GitHub version.

A.

**Comment by Smo-RBR** [comment]
Should i pair the device again for this?

**Comment by Smo-RBR** [comment]
Thank you. It seems to work :)
