### ISSUE TITLE
Avatto Dimmer 

### ISSUE THREAD

**Issue by MichGraf** [ioBroker/ioBroker.zigbee#2322]
### Tested with adapter version

1.10.3

### modelZigbee

TS0601

### manufacturer

_TZE204_nqqylykc

### Link to device

https://www.zigbee2mqtt.io/devices/ZDMS16-1.html

### Coordinator type selected in adapter setting

zStack3x0

### Coordinator

Sonfoff Zigbee Dongle - P

### Coordinator firmware version and revision

version 2-1.2.7.1.     revision 20210708

**Comment by MichGraf** [comment]
Würde mich sehr freuen! Nett, Euch in Solingen kennengelernt zu haben. :-) ioBroker ist echt stark.

**Comment by asgothian** [comment]
please test with the current GitHub version. Without this test, no work will be done on this.

**Comment by asgothian** [comment]
No test with current version - seems no interest. Closing this.
