### ISSUE TITLE
zigbee.0.info.pairingMode as switch

### ISSUE THREAD

**Issue by SlipKoRn88** [ioBroker/ioBroker.zigbee#2325]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

Hello,

i would like to use the zigbee.0.info.pairingMode datapoint  as switch to start the pairing mode in a VIS / Jarvis. Is it possible to get this datapoint workable for this case?

Thank you!

Forum link: https://forum.iobroker.net/topic/78760/zigbee-anlernen-%C3%BCber-vis-jarvis

**Comment by arteck** [comment]
sry but .. nope
