### ISSUE TITLE
ZG-204ZM Presence Sensor

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.zigbee#2328]
### Tested with adapter version

1.10.13 actual Github

### modelZigbee

ZG-204ZM

### manufacturer

_TZE200_kb5noeto

### Link to device

https://www.zigbee2mqtt.io/devices/ZG-204ZM.html

### Coordinator type selected in adapter setting

TI Z Stack / CCxxxx

### Coordinator

TI CC26x2R3

### Coordinator firmware version and revision

2-1.2.7.1. revision:20230507

**Comment by Ilovegym66** [comment]
wird erkannt, legt Datenpunkte an, kommen aber keine Werte: (gleiches auch, wenn Device excluded ist)
![Screenshot 2024-12-22 at 14 58 36](https://github.com/user-attachments/assets/527b8b5c-0f9a-4c78-8ffc-3353446927c4)

![Screenshot 2024-12-22 at 15 15 08](https://github.com/user-attachments/assets/948bc40f-56b6-4846-bd45-5179eb2076d0)

**Comment by Ilovegym66** [comment]
device als debug eingetragen:
`
zigbee.0 | 2024-12-22 15:27:13.134 | warn | ELEVATED publishToState: value generated '0' from device a4c1381ab2fb4715 for 'Link quality'
-- | -- | -- | --
zigbee.0 | 2024-12-22 15:27:13.134 | warn | ELEVATED publishToState: message received '{"linkquality":0}' from device a4c1381ab2fb4715 type 'ZG-204ZM'
zigbee.0 | 2024-12-22 15:27:13.134 | warn | ELEVATED publishToState: value generated 'false' from device a4c1381ab2fb4715 for 'Available'
zigbee.0 | 2024-12-22 15:27:13.134 | warn | ELEVATED publishToState: message received '{"available":false}' from device a4c1381ab2fb4715 type 'ZG-204ZM'


`
mehr kommt nicht..

**Comment by asgothian** [comment]
This indicates that the device configuration has not been done successfully. Please attempt to reconfigure the device from the device tile.

With no 'message received' entries, the adapter cannot do a thing.

A.

**Comment by Ilovegym66** [comment]
understand, but I reconfigure it and delete it and everytime the adapter accept the device with successful and add it to the devices list with the correct icon and all objects. 

why it don't send any data, or the adapter don't fetch the data, I don't know.
 Can it be, that my coordinator with 250 devices are too busy ? 
Everything is running fine, no issues with zigbee.

I connected the device to another zigbee coordinator (tuya bluetooth/zigbee gateway for 10Euro), added to the Tuya Adapter, and this works fine. For me its not a problem, so far the Tuya Adapter works :). ( I know, Tuya is a bad black listed word :))

**Comment by asgothian** [comment]
It is possible that the device does not report data but requires the adapter to pull data. Please attempt to gain data using the "device_query" state.


A.

**Comment by Ilovegym66** [comment]
ok, next try.. paired again successful to zigbee adapter, set the objet device query to true, but nothing happens.. :(
( with nothing I mean, nothing in the logfile and the objects don't change or update anything for the device)
I have three of them, same. with the Tuya Gateway everything works fine.. looks like something Tuya-Special... 
on zigbee2mqtt there is no hint, that something must be enabled oder after pairing send.. :(

**Comment by asgothian** [comment]
Is the device connected directly to the coordinator or going via a router ?

**Comment by Ilovegym66** [comment]
I paired on 2 different places, first time near the coordinator, and the second try I paired it to a router (Lidl Zigbee Light).
Today I would like to clean up some unused remote controls from the adapter, and make a try again. 
After this, I would like to reactivate my Backup Coordinator, install a second zigbee instance and make a try there.
My doubts are about the numbers of devices are connected in my system, these are anyway too much.. (254)..

**Comment by asgothian** [comment]
Keep in mind - it does not matter which button you use to open the network - the device is always paired to the network, not to a specific device. 
With the large number of devices, the question is if the respective device is connected directly to the coordinator. It is possible that it cannot be attached directly if the coordinator has too many devices connected directly.

I am curious to see the result of your test.

A.

**Comment by Ilovegym66** [comment]
Hello A.  problem is solved, I installed a second zigbee instance with my backup Coordinator, paired the device to it, and everything is working like expected. 
The differences between Zigbee instance 0 and 1:
Zigbee Coordinator on instance 0 working with 
type:zStack3x0
version:2-1.2.7.1.
revision:20230507
port:tcp://10.1.1.98:44444
channel:25
No. of paired devices: 248

Zigbee Coordinator on instance 1 working withtype:zStack3x0
version:2-1.2.7.1.
revision:20220219
port:tcp://10.1.1.99:20111
channel:11
No. of paired devices:  3

from my site the issue can be closed, was a local fault here - not an Adapter issue. Or it was the channel or it was the coordinator firmware ... 
Think next time, near 250 devices the network is full and don't report everything correctly any more..

Tuya Gateway is not needed any more.. local managed devices have prio in my network..
