### ISSUE TITLE
I can not control HUE lamps anymore.

### ISSUE THREAD

**Issue by Shantos** [ioBroker/ioBroker.zigbee#233]
If I want to turn HUE lights on and off, then it will work fine once in a while. After that, the writing is first green, then red and the lamp does nothing. All other devices work without problems. A switchable socket can be switched on and off as often as you like. The Xiaomi temperature sensors work without any problems. Only the Hue lamps do not work.

I use LWB010 and LCT012 Hue lamp´s.

**Comment by chrram85** [comment]
I have the same problem with a TRADFRI bulb E27 W opal 1000lm. About objects, it goes out only and the values ​​are red.Wenn I turn on analysis the lamp goes on without problems on and off, other devices are synonymous without problems.Use the version 0.9.2

**Comment by nob0dy80** [comment]
@chrram85 
no it isnt.
But you should use the older converters if you have RWL021 wall switches by Philipps. This isnt stillt working very good with the new converters till now.
The lamp issues are fixed as far as i know.

@Shantos
if you change ne state and it goes from green to red normally means the device is not reachable or not routed.
Without any debug logs.
Check if your LWB010 and LCT012 have at least a signal of 10 (coordinator ---> lamp)  or higher. Low signals mostly cause this error.
If yes, put adapter to debug , switch the light, and send the part of the log.

**Comment by arteck** [comment]
works in new Version
