### ISSUE TITLE
Tradfri Grouping

### ISSUE THREAD

**Issue by dmasur** [ioBroker/ioBroker.zigbee#234]
Hello,

i have about 20 Tradfri GU10 (some white and some color) with iobroker.zigbee connected. All of them react as normal objects.

I have five groups (all of them are in groups), but 7 light bulbs don't react on group commands (brightness). 

Is there anything i can do?

**Comment by nob0dy80** [comment]
@dmasur 
open your objects and take look at a brightness state on one of this GU10s. If its empty (no number) enter any for the first time.
had this problem too, hope that helps.

**Comment by dmasur** [comment]
@nob0dy80 Thanks for your response. 

I tried that (and updated to the new version)

It gets worse. Some of the other bulbs that i use show now the same. I can control them on there own, but not as group.

Is there anyway i can debug this?

**Comment by modmax** [comment]
Which Firmware Version do you have on the zigbee Stick?

**Comment by nob0dy80** [comment]
@dmasur 
well i have problem with newer version (above 20190119) ..so i stay with 20190119. 
Setting brightness manual cant make it more worse... this is your firmware update.

of cause you can debug it .. just turn ob debug for the zigbee adapter in the instances view.
even i've expierenced problems with groups too ... i dont use them
i made a scene with all needed bulps inside it and just trigger the scene.

**Comment by dmasur** [comment]
@modmax how can i see the firmware of the device? Its a TI Usb Stick

**Comment by nob0dy80** [comment]
@dmasur 
at startup of the zigbee adapter
zigbee-shepherd ready. version: 2.6.3 rev <here is your version>

**Comment by dmasur** [comment]
@nob0dy80 I don't like that:


> 
> zigbee.0 | 2019-03-17 12:04:42.222 | info | zigbee-shepherd ready. version: undefined rev undefined
> -- | -- | -- | --
> zigbee.0 | 2019-03-17 12:04:42.216 | info | zigbee-shepherd started!
> zigbee.0 | 2019-03-17 12:04:40.320 | info | Reset coordinator
> zigbee.0 | 2019-03-17 12:04:40.320 | info | Queue is: true
> zigbee.0 | 2019-03-17 12:04:40.320 | info | Start on port: /dev/ttyACM0 with panID 6754 channel 11
> zigbee.0 | 2019-03-17 12:04:40.320 | info | starting. Version 0.10.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v8.15.1

**Comment by nob0dy80** [comment]
@dmasur 
ok that is weired! 
maybe something is wrong with the flashing of your stick. please reflash it with an actual firmware.

**Comment by dmasur** [comment]
@nob0dy80 I have one a ftdi stick for sonoff flashing here. I think i need some other tools for CC flashing. so i am buying these (got the stick flashed by a friend). I will give you feedback when i tried it. thanks for your help so far.

**Comment by nob0dy80** [comment]
@dmasur 
yes you need a cc debugger and dont forget to buy the connection cable (mine came without).

**Comment by dmasur** [comment]
zigbee.0 | 2019-03-21 08:36:40.497 | info | zigbee-shepherd ready. version: 2.6.3 rev 20190223
-- | -- | -- | --




i flashed it and will test the system over the next few day. will report back.

**Comment by nob0dy80** [comment]
@dmasur 
nice, this looks much better :-)

**Comment by dmasur** [comment]
@nob0dy80 i have some problems to switch bulbs at all. Do i need to register every bulb new after flashing?

**Comment by nob0dy80** [comment]
@dmasur 
cause your firmware seemed to be broken before, i would strongly recommend this.
if your firmware wasnt 20190223 (ex 20190119) before, you have to repair it anyway cause the feature of non repairing was added in 20190223.

**Comment by dmasur** [comment]
I have 20190223. 

I added most of my bulbs. Cannot get them working with groups, but they work fine alone. so i changed my rules this way.

Next problem is this:

zigbee.0 | 2019-03-22 19:54:01.652 | error | Error while starting zigbee-shepherd!. Error: request timeout
-- | -- | -- | --
zigbee.0 | 2019-03-22 19:53:55.109 | info | Starting zigbee-shepherd

zigbee.0 | 2019-03-22 19:52:55.099 | info | Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds)
-- | -- | -- | --
zigbee.0 | 2019-03-22 19:52:46.389 | info | Reset coordinator
zigbee.0 | 2019-03-22 19:52:46.389 | info | Queue is: true
zigbee.0 | 2019-03-22 19:52:46.389 | info | Start on port: /dev/ttyACM0 with panID 6754 channel 11

I must restart the system (btw. Tiny PC with ubuntu without docker) to fix this.

**Comment by nob0dy80** [comment]
@dmasur 
you are not allone with this. :-/ Try the max_stable firmware.
https://github.com/Koenkk/Z-Stack-firmware/tree/dev/coordinator/max_stability

you shouldnt need to re-pair the devices.

**Comment by dmasur** [comment]
@nob0dy80 I switched to the max_stable firmware and all my bulbs work perfect. Thank you for your help and patience.
