### ISSUE TITLE
Iobroker should not add coordinator to groups cause it is not needed

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.zigbee#235]
I refer to this talk with Koenkk
https://github.com/Koenkk/Z-Stack-firmware/issues/54

with the latest firmware you can only create one group in the iobroker adapter.
the second one will give you a error message.
Failed to add group 2 to coordinator. Error: request unsuccess: 178

Koenkk said its because the coordinator is added unnecessary to the groups. (he limited the groups where the coordinator can be to 1 in the latest firmware). Dont even know why a coordinator should be added to any groups automatically, but i'm pretty sure Koenkk knows what he's talking about.

**Comment by nob0dy80** [comment]
Reflashed one of my cc2530 to get some debug output. forgot it last time.
fresh clean adapter, the only thing that has be done is adding two groups:

zigbee.1 | 2019-03-10 09:56:45.044 | error | Failed to add group 2 to coordinator. Error: request unsuccess: 178
-- | -- | -- | --
zigbee.1 | 2019-03-10 09:56:45.031 | debug | Failed to find group 2 in coordinator. {}
zigbee.1 | 2019-03-10 09:56:45.016 | debug | Successfully find group 1 in coordinator: {"status":0,"groupid":1,"namelen":7,"groupname":{"type":"Buffer","data":[103,114,111,117,112,95,49]}}
zigbee.1 | 2019-03-10 09:56:45.003 | debug | Successfully get groups from coordinator: [{"status":0,"groupid":1,"namelen":7,"groupname":{"type":"Buffer","data":[103,114,111,117,112,95,49]},"name":"group_1"}]
zigbee.1 | 2019-03-10 09:56:45.002 | debug | Successfully find group 1 in coordinator: {"status":0,"groupid":1,"namelen":7,"groupname":{"type":"Buffer","data":[103,114,111,117,112,95,49]}}
zigbee.1 | 2019-03-10 09:56:44.989 | debug | Successfully get groups from coordinator: {"groups":1,"grouplist":{"type":"Buffer","data":[1,0]}}
zigbee.1 | 2019-03-10 09:56:44.969 | debug | {"type":"Coordinator","ieeeAddr":"0x00124b001bb84b9c","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6],"status":"online","joinTime":1552208204}
zigbee.1 | 2019-03-10 09:56:44.968 | debug | Current active devices:
zigbee.1 | 2019-03-10 09:56:44.968 | debug | User stateChange zigbee.1.info.pairingMode {"val":false,"ack":false,"ts":1552208204933,"q":0,"from":"system.adapter.zigbee.1","lc":1552208007394}
zigbee.1 | 2019-03-10 09:56:44.945 | debug | User stateChange zigbee.1.info.connection {"val":true,"ack":false,"ts":1552208204932,"q":0,"from":"system.adapter.zigbee.1","lc":1552208007394}
zigbee.1 | 2019-03-10 09:56:44.939 | info | zigbee-shepherd ready. version: 2.6.3 rev 20190223

**Comment by kirovilya** [comment]
fixed https://github.com/ioBroker/ioBroker.zigbee/commit/45513358d86b427256d7a99b51cbcc18ac610229

**Comment by nob0dy80** [comment]
@kirovilya 
Thanks!
going to comment out that lines and give it a try on the weekend.
hopefully the zigbee sticks stops now  freezing now randomly. pretty sure it was something about the groups.
