### ISSUE TITLE
after installing 0.9.2 no devices found

### ISSUE THREAD

**Issue by overfl0w72** [ioBroker/ioBroker.zigbee#236]
Hi everybody, after I've just updated from the 0.7.1 to the 0.9.2, all my previously learned devices are gone, or not visible anymore. I have then paired a new xiaomi window contact, but even this is not displayed despite the fact that the device gejoint. in the log I get the following error:

`

zigbee.0 | 2019-03-10 13:20:09.669 | error | TypeError: adapter.getEnumsAsync is not a function at getDevices (/opt/iobroker/node_modules/iobroker.zigbee/main.js:424:17) at Adapter.adapter.on.obj (/opt/iobroker/node_modules/iobroker.zigb
-- | -- | -- | --
zigbee.0 | 2019-03-10 13:20:09.668 | error | message messagebox.system.adapter.zigbee.0 [object Object] adapter.getEnumsAsync is not a function
zigbee.0 | 2019-03-10 13:19:53.684 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3165:34)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at Adapter.emit (events.js:188:7)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at emitOne (events.js:96:13)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at Adapter.adapter.on.obj (/opt/iobroker/node_modules/iobroker.zigbee/main.js:76:25)
zigbee.0 | 2019-03-10 13:19:53.684 | error | at getDevices (/opt/iobroker/node_modules/iobroker.zigbee/main.js:424:17)
zigbee.0 | 2019-03-10 13:19:53.684 | error | TypeError: adapter.getEnumsAsync is not a function
zigbee.0 | 2019-03-10 13:19:53.683 | error | message messagebox.system.adapter.zigbee.0 [object Object] adapter.getEnumsAsync is not a function
zigbee.0 | 2019-03-10 13:19:49.230 | info | system.adapter.admin.0: logging true
zigbee.0 | 2019-03-10 13:19:25.104 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3165:34)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at Adapter.emit (events.js:188:7)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at emitOne (events.js:96:13)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at Adapter.adapter.on.obj (/opt/iobroker/node_modules/iobroker.zigbee/main.js:76:25)
zigbee.0 | 2019-03-10 13:19:25.104 | error | at getDevices (/opt/iobroker/node_modules/iobroker.zigbee/main.js:424:17)
zigbee.0 | 2019-03-10 13:19:25.104 | error | TypeError: adapter.getEnumsAsync is not a function
zigbee.0 | 2019-03-10 13:19:25.104 | error | message messagebox.system.adapter.zigbee.0 [object Object] adapter.getEnumsAsync is not a function
zigbee.0 | 2019-03-10 13:19:25.092 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3165:34)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at Adapter.emit (events.js:188:7)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at emitOne (events.js:96:13)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at Adapter.adapter.on.obj (/opt/iobroker/node_modules/iobroker.zigbee/main.js:76:25)
zigbee.0 | 2019-03-10 13:19:25.092 | error | at getDevices (/opt/iobroker/node_modules/iobroker.zigbee/main.js:424:17)
zigbee.0 | 2019-03-10 13:19:25.092 | error | TypeError: adapter.getEnumsAsync is not a function
zigbee.0 | 2019-03-10 13:19:25.089 | error | message messagebox.system.adapter.zigbee.0 [object Object] adapter.getEnumsAsync is not a function
zigbee.0 | 2019-03-10 13:19:24.991 | info | new dev 0x00158d0001e76a0a 5616 lumi.sensor_magnet
zigbee.0 | 2019-03-10 13:18:08.449 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-03-10 13:01:56.089 | info | Zigbee: allowing new devices to join.

`

I would really appreciate help. thank you in advance

**Comment by modmax** [comment]
Welch Version of the js Controller is über alles? ... Check it out under iobroker hosts. I think the version is too old.

**Comment by overfl0w72** [comment]
![image](https://user-images.githubusercontent.com/38362085/54085044-55037e80-4339-11e9-80f1-6b82a08bec86.png)

**Comment by overfl0w72** [comment]
how do I do the smartest js controller update? iobroker has to be closed or?

wie mache ich denn am schlausten nen js controller update? iobroker muss dazu beendet werden oder?

**Comment by modmax** [comment]
Okay ... as i thought. Too old...

So make a Backup of your iobroker Installation .... and Update the js controller...

Also at least node v6 should be installed...

**Comment by modmax** [comment]
Am einfachsten das ganze iobroker Verzeichnis einmal woanders hinkopieren oder als zip file packen.... dann kannste es einfach wieder herstellen wenn das Update fehl schlägt ....

**Comment by overfl0w72** [comment]
okay, leider habe ich von linux nicht so viel ahnung.. ich kann per ssh auf das board und dann? :/

**Comment by modmax** [comment]
Geht mit dem kommando gz unter Linux.... hab aber gerade nicht die Syntax hier da ich gerade keinen pc zur Verfügung habe....

**Comment by overfl0w72** [comment]
danke erstmal für deine antwort. ich installiere jetzt backitup und sichere mein iobroker auf meinem nas... dann google ich mal wie ich den controller upgrade. :)

**Comment by overfl0w72** [comment]
so habe nun auf die 1.57 geupdated, geräte sind leider immer noch nicht da :-( Ne Idee?

**Comment by overfl0w72** [comment]
sorry, nehme alles zurück. alle geräte wieder da, adapter läuft danke nochmals!
