### ISSUE TITLE
new converter and the dependency zcl-id and zcl-packet

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#239]
i see here a big Problem with dependencys.. 
when zigbee-shepherd-converters gets new functions .. and one our user take an install of zigbee adapter then he gets a problem.. such as : new function for Hue dimmer

**Comment by arteck** [comment]
i can not install the adapter .. new installation
zcl-id and zcl-packet are new and zigbee-shepherd-converters take many errors without

**Comment by kirovilya** [comment]
i fix this tonight

**Comment by arteck** [comment]
i hope this works also.. after you change :-)
https://github.com/ioBroker/ioBroker.zigbee/issues/232

**Comment by kirovilya** [comment]
packages updated

**Comment by arteck** [comment]
ok.. i check this .. big THX

**Comment by arteck** [comment]
hue dimmer doesn't works

**Comment by kirovilya** [comment]
What is error?

**Comment by arteck** [comment]
no error..nothing

**Comment by arteck** [comment]
after this 

zigbee.0 | 2019-03-11 21:50:32.997 | error | Zigbee publish to '0x0017880102ca68f3', genLevelCtrl - moveToLevelWithOnOff - {"level":51,"transtime":0} - 11 failed with error Error: request timeout
-- | -- | -- | --
zigbee.0 | 2019-03-11 21:47:31.452 | error | Cannot get the Node Descriptor of the Device: 0x0017880102f054a7 (Error: request timeout)
zigbee.0 | 2019-03-11 21:47:28.433 | error | Cannot get the Node Descriptor of the Device: 0x0017880102ca68f3 (Error: request timeout)
zigbee.0 | 2019-03-11 21:47:25.417 | error | Cannot get the Node Descriptor of the Device: 0x0017880102de40ac (Error: request timeout)
zigbee.0 | 2019-03-11 21:47:22.403 | error | Cannot get the Node Descriptor of the Device: 0x0017880104305d19 (Error: request timeout)
zigbee.0 | 2019-03-11 21:47:19.387 | error | Cannot get the Node Descriptor of the Device: 0x0017880103dcc9d2 (Error: request timeout)

result is this


zigbee.0 | 2019-03-11 21:53:20.426 | error | Error while starting zigbee-shepherd!. Error: request timeout

reboot help

p.s: i have new firmware..

**Comment by arteck** [comment]
after restart and pressd any button


host.zigbee-RasPi | 2019-03-11 21:57:53.118 | error | instance system.adapter.zigbee.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-03-11 21:57:53.117 | error | by controller[0]: at Timer.listOnTimeout (timers.js:290:5)
Caught | 2019-03-11 21:57:53.117 | error | by controller[0]: at tryOnTimeout (timers.js:323:5)
Caught | 2019-03-11 21:57:53.116 | error | by controller[0]: at ontimeout (timers.js:502:15)
Caught | 2019-03-11 21:57:53.116 | error | by controller[0]: at Timeout.actions [as _onTimeout] (/opt/iobroker/node_modules/zigbee-shepherd-converters/devices.js:881:37)
Caught | 2019-03-11 21:57:53.116 | error | by controller[0]: at Endpoint.ep.bind (/opt/iobroker/node_modules/zigbee-shepherd/lib/shepherd.js:571:36)
Caught | 2019-03-11 21:57:53.115 | error | by controller[0]: at Controller.bind (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/controller.js:445:23)
Caught | 2019-03-11 21:57:53.115 | error | by controller[0]: at Object.query.setBindingEntry (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/query.js:136:13)
Caught | 2019-03-11 21:57:53.115 | error | by controller[0]: at Object.proving.defined (/opt/iobroker/node_modules/proving/index.js:41:15)
Caught | 2019-03-11 21:57:53.113 | error | by controller[0]: TypeError: Invalid cluster id: manuSpecificPhilips.
zigbee.0 | 2019-03-11 21:57:53.085 | info | terminating
zigbee.0 | 2019-03-11 21:57:53.060 | error | at Timer.listOnTimeout (timers.js:290:5)
zigbee.0 | 2019-03-11 21:57:53.060 | error | at tryOnTimeout (timers.js:323:5)
zigbee.0 | 2019-03-11 21:57:53.060 | error | at ontimeout (timers.js:502:15)
zigbee.0 | 2019-03-11 21:57:53.060 | error | at Timeout.actions [as _onTimeout] (/opt/iobroker/node_modules/zigbee-shepherd-converters/devices.js:881:37)
zigbee.0 | 2019-03-11 21:57:53.060 | error | at Endpoint.ep.bind (/opt/iobroker/node_modules/zigbee-shepherd/lib/shepherd.js:571:36)
zigbee.0 | 2019-03-11 21:57:53.060 | error | at Controller.bind (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/controller.js:445:23)
zigbee.0 | 2019-03-11 21:57:53.060 | error | at Object.query.setBindingEntry (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/query.js:136:13)
zigbee.0 | 2019-03-11 21:57:53.060 | error | at Object.proving.defined (/opt/iobroker/node_modules/proving/index.js:41:15)
zigbee.0 | 2019-03-11 21:57:53.060 | error | TypeError: Invalid cluster id: manuSpecificPhilips.
zigbee.0 | 2019-03-11 21:57:53.058 | error | uncaught exception: Invalid cluster id: manuSpecificPhilips.

**Comment by kirovilya** [comment]
Sorry. Forgot https://github.com/ioBroker/ioBroker.zigbee/commit/02695c7994948be5657e456686015dce2612c37a. Try again

**Comment by arteck** [comment]
reboot

**Comment by arteck** [comment]
and the dimmer dosnt work.. i see only link_quality blink bot no state changed

**Comment by arteck** [comment]
corr..the dimme has this message

zigbee.0 | 2019-03-11 22:35:03.127 | warn | Failed to configure 0x0017880103caf394 RWL021, try again in 300 sec
zigbee.0 | 2019-03-11 22:35:03.052 | warn | Failed to configure 0x0017880103caa673 RWL021, try again in 300 sec

and i see only link_quality blink.. no state.. (a have here 5 dimmer)


I will redo the network.  . tommorow.. ...

**Comment by arteck** [comment]
after 

zigbee.0 | 2019-03-11 22:37:06.092 | error | Cannot get the Node Descriptor of the Device: 0x00178801040b1142 (Error: Timed out after 10000 ms)

adapter stopped .. 
all devices are not available..

**Comment by kirovilya** [comment]
:(
type 'readRsp' - is new type of event, emitted on response of commands. but we can not handle it is yet

**Comment by arteck** [comment]
not good

**Comment by kirovilya** [comment]
check out zcl-id module inside zigbee-shepherd and inside zcl-packet and inside zigbee-shepherd-converters is the same and has line https://github.com/Koenkk/zcl-id/blob/master/definitions/cluster_defs.json#L1314

**Comment by arteck** [comment]
so.. the adapter works with error  ok response is not handled... but it stops.. why ??  i dont know.. after last device added .. 

zigbee.0 | 2019-03-12 20:11:05.994 | warn | Failed to configure 0x0017880102e251de RWL021, try again in 300 sec
zigbee.0 | 2019-03-12 20:10:59.969 | warn | Failed to configure 0x0017880104ed9cab RWL021, try again in 300 sec
zigbee.0 | 2019-03-12 20:10:53.940 | warn | Failed to configure 0x0017880103caa673 RWL021, try again in 300 sec
zigbee.0 | 2019-03-12 20:07:47.011 | error | No converter available for '9290012573A' with cid 'genLevelCtrl' and type 'readRsp'
zigbee.0 | 2019-03-12 20:07:41.839 | error | No converter available for '8718696598283' with cid 'genLevelCtrl' and type 'readRsp'
zigbee.0 | 2019-03-12 20:07:34.864 | error | No converter available for '9290012573A' with cid 'genLevelCtrl' and type 'readRsp'
zigbee.0 | 2019-03-12 20:06:26.888 | warn | Failed to configure 0x0017880102e251de RWL021, try again in 300 sec
zigbee.0 | 2019-03-12 20:06:26.864 | warn | Failed to configure 0x0017880104ed9cab RWL021, try again in 300 sec
zigbee.0 | 2019-03-12 20:05:37.622 | info | Successfully configured 0x7cb03eaa00a747b1
zigbee.0 | 2019-03-12 20:05:37.363 | info | Successfully configured 0x7cb03eaa00af1a79
zigbee.0 | 2019-03-12 20:05:12.185 | info | new dev 0x0017880103648612 52058 LST002
zigbee.0 | 2019-03-12 20:05:10.914 | error | No converter available for '9290012573A' with cid 'genLevelCtrl' and type 'readRsp'

**Comment by arteck** [comment]
ok after acces to the rwl021 hue dimmer is end...
the adapter stops

**Comment by kirovilya** [comment]
Try agian

**Comment by arteck** [comment]
ok new turn

**Comment by arteck** [comment]
ok .. works.. but not all

up and down works

on/off not... here i see only link_quality update so set state

**Comment by arteck** [comment]
ahh ok I found it..
payload.action is different

**Comment by arteck** [comment]
I'll watch it.. but i think .. VERY GOOD JOB ILYA.. BIG THX..

what we can do that it does not happen again ?? 
can we work with static dependency ?? 



ahh and plz take a new npm version

**Comment by arteck** [comment]
supplement :-)

No converter available for '324131092621' with cid 'genBasic' and type 'devChange'

**Comment by kirovilya** [comment]
Ok. I updated dependencies to static commits. This will prevent the installation of new changes to old versions.
What can we do yet? Not to do any changes :)))

I will make new npm tonight

**Comment by arteck** [comment]
bad infos


```
host.zigbee-RasPi | 2019-03-13 08:26:03.369 | error | instance system.adapter.zigbee.0 terminated with code 0 (OK)
host.zigbee-RasPi | 2019-03-13 08:26:03.369 | error | Caught by controller[0]: at /opt/iobroker/node_modules/zigbee-shepherd/lib/components/query.js:167:18
host.zigbee-RasPi | 2019-03-13 08:26:03.368 | error | Caught by controller[0]: at performReq (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/query.js:163:9)
host.zigbee-RasPi | 2019-03-13 08:26:03.368 | error | Caught by controller[0]: at req (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/query.js:156:47)
host.zigbee-RasPi | 2019-03-13 08:26:03.367 | error | Caught by controller[0]: at Controller.request (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/controller.js:320:19)
host.zigbee-RasPi | 2019-03-13 08:26:03.367 | error | Caught by controller[0]: at Zdo.request (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/zdo.js:29:21)
host.zigbee-RasPi | 2019-03-13 08:26:03.367 | error | Caught by controller[0]: at Zdo._specialRequest (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/zdo.js:83:25)
host.zigbee-RasPi | 2019-03-13 08:26:03.366 | error | Caught by controller[0]: at Zdo._genericRequest (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/zdo.js:66:10)
host.zigbee-RasPi | 2019-03-13 08:26:03.366 | error | Caught by controller[0]: at Zdo._sendZdoRequestViaZnp (/opt/iobroker/node_modules/zigbee-shepherd/lib/components/zdo.js:40:12)
host.zigbee-RasPi | 2019-03-13 08:26:03.365 | error | Caught by controller[0]: at CcZnp.(anonymous function) [as zdoRequest] (/opt/iobroker/node_modules/cc-znp/lib/ccznp.js:218:21)
host.zigbee-RasPi | 2019-03-13 08:26:03.365 | error | Caught by controller[0]: at CcZnp.request (/opt/iobroker/node_modules/cc-znp/lib/ccznp.js:176:15)
host.zigbee-RasPi | 2019-03-13 08:26:03.364 | error | Caught by controller[0]: Error: ccznp has not been initialized yet
zigbee.0 | 2019-03-13 08:26:03.315 | error | Error: ccznp has not been initialized yet at CcZnp.request (/opt/iobroker/node_modules/cc-znp/lib/ccznp.js:176:15) at CcZnp.(anonymous function) [as zdoRequest] (/opt/iobroker/node_modules/cc-
zigbee.0 | 2019-03-13 08:26:03.314 | error | uncaught exception: ccznp has not been initialized yet
zigbee.0 | 2019-03-13 08:25:10.367 | error | Cannot get the Node Descriptor of the Device: 0x0017880103648612 (Error: request timeout)
```

**Comment by kirovilya** [comment]
I do not understand  what's wrong ... maybe some problems with the port or with power? or may be firmware? or with serialport 7.1.4?

**Comment by arteck** [comment]
port or with power , no i think no.. its same as old installation.. nothing modifications

**Comment by arteck** [comment]
i'm crazy... I started all to reconnect all my devices.. direct after first hue bulb run the adapter since 1 h

**Comment by arteck** [comment]
nope after 1 h is the end

**Comment by kirovilya** [comment]
What happens in an hour? Does restarting the adapter help or reboot the entire system?

**Comment by arteck** [comment]
reboot

**Comment by arteck** [comment]
so i repaired all my hue's.. nope

**Comment by kirovilya** [comment]
Let's do experiment:
in cc-znp change 1500 to 3000 in https://github.com/kirovilya/cc-znp/blob/master/lib/ccznp.js#L243

**Comment by arteck** [comment]
new turn

**Comment by arteck** [comment]
nope .. i think its  zigbee-shepherd
here is the problem...

**Comment by arteck** [comment]
i wrote with Asgotian and he has a old version of Firmware .. i have reflash the stick also to 20181224 
..

**Comment by kirovilya** [comment]
And how your turn?

**Comment by arteck** [comment]
all ok..

**Comment by modmax** [comment]
Perhaps then tue recommendation for the users should be to use tust Version instead of a newer one if problems occur....
