### ISSUE TITLE
Kann keinen Bewegungsmelder mehr anlernen.

### ISSUE THREAD

**Issue by R-Guhr** [ioBroker/ioBroker.zigbee#24]
zigbee.0 | 2018-07-15 14:04:18.738 | error | Cannot get the Node Descriptor of the Device: 0x00158d0001a9e3e2 (Error: Timed out after 10000 ms)
-- | -- | -- | --

**Comment by rocklobster42195** [comment]
Ist das ein Xiaomi Bewegungsmelder?
Probiere das dann einfach nochmal. Bei mir hat das auch erst beim zweiten oder dritten Versuch geklappt. 

Do you have a Xiaomi (Aqara) motion sensor?
Please try again. It worked for me after a couple of tries.

**Comment by R-Guhr** [comment]
Ja es ist ein Xiaomi Bewegungsmelder.
Ich bin jetzt mal noch näher an den USB-Dongle gerutscht. Danach ging das anlernen. Bei einem Temperatursensor hatte ich auch das Problem. Nach ca. 1h anlernversuche, ging es dann. Danke 
Fehler geschlossen.

Yes it is a Xiaomi motion detector.
I've now even closer to the USB dongle slipped. After that, the learning went on. At a temperature sensor, I had the problem. After about 1h learning experiments, it went. Thank you
Error closed.

**Comment by kirovilya** [comment]
@R-Guhr This error mean that you need press setup key every two seconds on device while "interview" not starting.
Look at this https://github.com/Koenkk/zigbee2mqtt/wiki/Pairing-devices#xiaomi

**Comment by arteck** [comment]
plz close here
