### ISSUE TITLE
Tradfri bulb does not turn on or dimm

### ISSUE THREAD

**Issue by mdn-united** [ioBroker/ioBroker.zigbee#240]
hi, I bought my first Tradfri light bulbs. They were also recognized in ioBroker and I found them in the object tree. If I enter a "false" in "switch state", the light bulb goes out. If I go back to "true", it does not turn on again. The light bulb also goes out when I change something to "brightness". For example I write "50" for 50% and the lamp just goes out. 
Via the instance "Zigbee adapter" -> "Developer" I can switch the light bulb off and on with "genOnOff". But if I change something in the object the light bulb just goes out. I don't know how to change the brightness with the instance "Zigbee adapter" -> "Developer", but I would like to try that. 
The firmware version of the light bulb is 1.2.214 and I don't have a Tradfri gateway to install a newer version. 

Thank you for your help!

**Comment by modmax** [comment]
Install the latest Version from github.... there is already a fix for brightness problem

**Comment by mdn-united** [comment]
@modmax  thank you for you quick reply. I can confirm that the issue is fixed with the version on Github.
