### ISSUE TITLE
Check online 0x00

### ISSUE THREAD

**Issue by maxpd1** [ioBroker/ioBroker.zigbee#246]
Hi,

whats the meaning of: zigbee:controller debug Check online 0x00124b001bd11dfc 0x00124b001bd11dfc
This prevents zigbee from running, at least today.

**Comment by kirovilya** [comment]
Any errors?
Checking online - periodically request to router to keep it online

**Comment by nob0dy80** [comment]
@maxpd1 
thats not preventing from anything..
like @kirovilya said this is a periodically check if  a device, you allready added, is responding
thats just normal.

**Comment by maxpd1** [comment]
the problem is, that zigbee isn't booting. I reinstalled the adapter even if I had the newest version now I see a complete other interface with lot more features but I face again a problem I saw in earlier times. I didn't get the adapter running:


host.raspberrypi | 2019-03-12 21:41:29.245 | error | instance system.adapter.zigbee.0 terminated with code 1 ()
-- | -- | -- | --
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:663:10)
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at Module._compile (module.js:652:30)
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at require (internal/module.js:11:18)
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at Module.require (module.js:596:17)
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at Function.Module._load (module.js:497:3)
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at tryModuleLoad (module.js:505:12)
host.raspberrypi | 2019-03-12 21:41:29.244 | error | Caught by controller[0]: at Module.load (module.js:565:32)
host.raspberrypi | 2019-03-12 21:41:29.243 | error | Caught by controller[0]: at Object.Module._extensions..node (module.js:681:18)
host.raspberrypi | 2019-03-12 21:41:29.243 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.raspberrypi | 2019-03-12 21:41:29.243 | error | Caught by controller[0]: NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
host.raspberrypi | 2019-03-12 21:41:29.243 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.raspberrypi | 2019-03-12 21:41:29.243 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.raspberrypi | 2019-03-12 21:41:29.243 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.raspberrypi | 2019-03-12 21:41:29.243 | error | Caught by controller[0]: ^
host.raspberrypi | 2019-03-12 21:41:29.242 | error | Caught by controller[0]: throw e
host.raspberrypi | 2019-03-12 21:41:29.239 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88

**Comment by maxpd1** [comment]
I reinstalled npm on /opt/iobroker and rebootet. 
I tried to reinstall npm in /opt/iobroker.zigbee as I did last time to solve the problem. But directory doesn't exist: 
![image](https://user-images.githubusercontent.com/15956503/54235880-8c795300-4512-11e9-9ecb-7eff3800b847.png)

**Comment by maxpd1** [comment]
If I try to rebuild npm in opt/iobroker with sudo I get a lot of access error messages. 


gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.11.1"

**Comment by nob0dy80** [comment]
@maxpd1 
at first i would start with the iobroker fix
https://forum.iobroker.net/topic/20211/iobroker-installation-fixer-beta-verf%C3%BCgbar/

i think this helps

**Comment by nob0dy80** [comment]
OR, if you are the only user on the system and you want it quick and dirty (not recommened)
do on the shell as root chmod -R 777 /opt/iobroker
this isnt never a good idea but has no further issues

**Comment by maxpd1** [comment]
I will try the way of your link. But I have to stop all processes. But how?
![image](https://user-images.githubusercontent.com/15956503/54237414-2db5d880-4516-11e9-8520-911242dc380d.png)

**Comment by maxpd1** [comment]
Installed the fix. But same issues:

![image](https://user-images.githubusercontent.com/15956503/54237896-4ecaf900-4517-11e9-9034-8cf1855f226c.png)

**Comment by nob0dy80** [comment]
do: sudo passwd root
- set password for root
do: su -

and then try this again

**Comment by nob0dy80** [comment]
if i were you, i would backup and reinstall iobroker..so many changed in permissions.. hard to figure out (for me).

**Comment by maxpd1** [comment]
yes. but without any effect:

![image](https://user-images.githubusercontent.com/15956503/54238389-a3bb3f00-4518-11e9-8487-e7f7aee1423a.png)

**Comment by maxpd1** [comment]
the only way to backup is to copy the SD card. is there a tut for another way? without having to rearrange all objects in my scripts?

**Comment by nob0dy80** [comment]
scripts can be exported...this is the most easiest thing...you can export all in one time and iobroker gives you a zip

**Comment by nob0dy80** [comment]
but before you do, are you ready for the quick and dirty method?

**Comment by maxpd1** [comment]
never found this. OK. this will be the emergency solution if QDM won't work. will try tomorrow. Thanks for your help by now!

**Comment by nob0dy80** [comment]
@maxpd1 
i still got a quick and dirty try for you

**Comment by nob0dy80** [comment]
sudo chmod -R 777 /opt/iobroker && sudo chmod -R 777 /root

! but this is a security risc if the host is used by other users !

**Comment by maxpd1** [comment]
I'm the only user

**Comment by nob0dy80** [comment]
@maxpd1 

well give it a try.

**Comment by nob0dy80** [comment]
@maxpd1 
but let me tell you: you have to reinstall for sure.. there is something wrong.. finding out what takes more time as a simple reinstall.. raspberry =30min, iobroker 30min, your settings 60mins.. 2 hours and you are done..would offer that time.

**Comment by maxpd1** [comment]
I think I will need 8hours and several days to get it back so far :dagger: 
but yes, there is too much wrong, also a lot of missing directory errors.

![image](https://user-images.githubusercontent.com/15956503/54239277-03b2e500-451b-11e9-8717-4e4608a0612e.png)

![image](https://user-images.githubusercontent.com/15956503/54239291-12010100-451b-11e9-8bce-f2e9d729a3d1.png)

**Comment by nob0dy80** [comment]
ok .. finally there are no permission denied anymore..that is what i expected. 
really dude, i would backup what is needed and do it fresh.. so much changed the last time.
and there seems to be something generally wrong.
searching the error and fixing it would for sure trake longer as 2 hours for a fresh start.

flash a new raspbian on the SD-card , login as pi and do:

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && sudo apt-get install -y build-essential libavahi-compat-libdnssd-dev libudev-dev libpam0g-dev nodejs && sudo reboot

after reboot
curl -sL https://iobroker.net/install.sh | bash -


everything should be fine then.

**Comment by maxpd1** [comment]
sudo chmod -R 777 /opt/iobroker && sudo chmod -R 777 /root in combination with npm rebuild fixed it for now ^^!!!!!!
But I think before I proceed with bigger changes I will set it up all new again.
I did screenshots of all adapter settings and exported the scripts.

Unfortunately the zigbee adapter didn't rembered the names of my devices. So I don't know anymore where which device is located.

**Comment by nob0dy80** [comment]
@maxpd1 
if you reinstall raspbian (which is advised) you have to do update and upgrade before all other commands.
Glad this dirty workarround fixed it for now. but be sure, other problems will come.
if you have the possibility reflash your zigbee stick too.

**Comment by maxpd1** [comment]
I wanted to use a CC2530 from koenkk as coordinator. But didn't get this running, so I am using a CC2531 as coordinator and a CC2530 as router.
Is there a significant update? Somehow changelog begins in Feb 2019?

**Comment by nob0dy80** [comment]
@maxpd1 
if you use the cc2530 or the cc2531 are not a big difference in generall. Even the firmwares work nearly the same way.
The main difference, which makes the cc2530 better, is the external antenna. This will prevent you more from transmission fails that can make the stick freeze (this issue is still in observeration). if you are running fine with the cc2531 and got a good link to all routers (i recommend a value of 10 or above for to have it stable), stay with your cc2531
