### ISSUE TITLE
CC2531 as router?

### ISSUE THREAD

**Issue by rocklobster42195** [ioBroker/ioBroker.zigbee#25]
Is there a firmware to use a CC2531 as router? Unfortunately I only have an arduino for flashing. I can't reach the sensors in the basement.
Thx
Boris

**Comment by kirovilya** [comment]
Read this article http://ptvo.info/cc2531-based-router-firmware-136/ it be usefull for our adapter too.
I wrote article in Russian https://github.com/kirovilya/ioBroker.zigbee/wiki/cc2531-router

**Comment by rocklobster42195** [comment]
Nice! I guess i have to improve Google-skills...

**Comment by rocklobster42195** [comment]
I flashed the cc2531 with the router firmware `CC2531-router-diag.hex` and restarted it. The red led is blinking every second. I started the pairing process in iobroker, pressed Switch2 for 5 seconds and pressed it again every 2 seconds or so.
After several tries, i couldn´t get the router paired.

**Comment by kirovilya** [comment]
@rocklobster42195 Strange. I do the same... After pairing it showing as unknown device, but it is ok:
![image](https://user-images.githubusercontent.com/8360230/42810773-6562bfb6-89c1-11e8-9395-55b507717211.png)
