### ISSUE TITLE
RWL021/RWL020 accepting configuration only once after pairing!

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.zigbee#252]
@kirovilya 
The philips dimm switch RWL020 and RWL021 will only accept a configuration once after pairing.
since you added a 300 seconds retry in the latest version, you will get every 300 seconds the warning if you restarted the adapter once.

related parts of the log:
zigbee.0	2019-03-14 16:04:59.919	warn	Failed to configure 0x0017880103a540fc RWL021, try again in 300 sec

zigbee.0	2019-03-14 16:03:39.119	info	zigbee-shepherd started!
zigbee.0	2019-03-14 16:03:38.043	info	Reset coordinator

zigbee.0	2019-03-14 15:31:55.977	info	Successfully configured 0x0017880103a540fc
zigbee.0	2019-03-14 15:31:18.906	info	zigbee-shepherd started!
zigbee.0	2019-03-14 15:31:17.773	info	Reset coordinator

zigbee.0	2019-03-14 15:27:45.202	info	new dev 0x0017880103a540fc 49605 RWL021
zigbee.0	2019-03-14 15:27:10.201	info	Zigbee: allowing new devices to join.

what do you think about creating an "isconfigured" datapoint to those switches to catch this warnings?

**Comment by kirovilya** [comment]
@allofmex can you help with configure devices? I think it will be option in device description (devstates.js)

**Comment by allofmex** [comment]
@nob0dy80 
I am still trying to optimize this a bit. 
Seems RWL021 accepts configuration in between too (see below). But you are right, it often takes some tries to match a moment where the device is awake. Success at first try like below is rare.

```
...
2019-03-15 08:27:48.502 | Successfully configured 0x0017880104af40a2 RWL021
...
2019-03-15 08:27:45.673 | Dev 0x00158d000192d1e1 SPZB0001 not yet configured, will try again in latest 300sec
...
2019-03-15 08:27:45.629 | Successfully configured 0x00158d000192d139 SPZB0001
...
2019-03-15 08:27:22.600 | Try to configure 0x0017880104af40a2 RWL021
...
2019-03-15 08:27:22.600 | Try to configure 0x00158d000192d139 SPZB0001
...
2019-03-15 08:27:22.598 | Try to configure 0x00158d000192d1e1 SPZB0001
2019-03-15 08:26:52.548 | 18 (0x00158d000192d1e1): SPZB0001 - Eurotronic Spirit Zigbee wireless heater thermostat (EndDevice)
...
2019-03-15 08:26:52.548 | 11 (0x00158d000192d139): SPZB0001 - Eurotronic Spirit Zigbee wireless heater thermostat (EndDevice)
...
2019-03-15 08:26:52.548 | 4 (0x0017880104af40a2): 324131092621 - Philips Hue dimmer switch (EndDevice)
...
2019-03-15 08:26:52.536 | zigbee-shepherd ready. version: 2.6.3 rev 20180815
2019-03-15 08:26:52.530 | zigbee-shepherd started!
2019-03-15 08:26:52.119 | Reset coordinator
```
I don't prefer a "isconfigured" datapoint. Most enddevices show similar behavior. And I **don't think it is a good idea to configure all enddevices only after they (rejoin)**. It really takes time until all devices rejoined after adapter restart. 

I see two options:
- rename warning to something less scary (as shown above)
- set level to debug instead of warn so retry message will not show in normal logs at all

**Comment by nob0dy80** [comment]
@nob0dy80 
first let me say your are right, in between its working too. a least at my site, it took about 80 tries for success. 
hmm i'm not really happy with both options. let me tell you why:
- Renaming it is just something for your optic. the log will be spamed anyway (but with nicer words :-D)
- debug level will just leave you wondering why your switch isnt working after successfully pairing. this information will go down under in the debug log anyway... you know what tons of informations are coming in debug mode.

But you didnt get the point of my datapoint. of cause it would be idiotic to set it only once after pairing. if this fails, nothing is configured and never will.
You only should set it to true if the configuration was once successfully after pairing (no matter when), cause this device never needs a re-configuration any time to work.

if this still isnt giving you good thoughts, what about a general solution for that kind of devices ? If every device of that kind would have a "configureinterval" datapoint that is set to 300 seconds by default, but is changeable to any value a user like (more as once a day wouldnt be a good idea too), everything should be fine with that? 

tell me your thoughts

kind regards

**Comment by asgothian** [comment]
I have set up a branch at asgothian/iobroker.zigbee/tree/admin_changes which includes a triggered configure when a message is received from a device which is awaiting configuration. In my tests, this enabled me to trigger configuration of remote devices (RWL020 and Ikea Remote) by pressing a button after restarting the adapter.

**Comment by allofmex** [comment]
@asgothian 
I thought about this approach too. The downside is:
if users have devices-to-be-configured that are permanently offline (power off by purpose, defect, whatever..), the list of pending-configurations has to be searched through (indexOf..) on **EVERY** incoming event. Just to check if this device is in list. This sums up on many devices and if someone is running a raspberry...

**Comment by allofmex** [comment]
@nob0dy80 

> configureinterval" datapoint

I understand what you mean. But it creates lots of overhead, just to avoid some warning messages in log. To be honest: I assume, 99% of users (incl. me) may not care much if there are some "configure retry" messages in log after adapter restart. There should not be much need to restart adapter often (in future, hopefully ;-) ).

What I just thought of: is there some kind of adapter-uptime variable? Then we could handle it as: "within first 30 minutes after adapter start retry every 300 sec, afterwards every 3 hours only"

**Comment by asgothian** [comment]
> What I just thought of: is there some kind of adapter-uptime variable? Then we could handle it as: "within first 30 minutes after adapter start retry every 300 sec, afterwards every 3 hours only"

I think this is counter-productive. Also, the messages alone are not the issue. I have to double check this with some of the components which delay configuration up to (max time i have seen) 14 hrs) - i remember at least one case where the component would not work as planned until configuration was complete.

If i cannot reproduce this effect, i would opt for removing the warning messages, and introducing an internal datapoint, which can be visible on the device card to show configuration status.

**Comment by nob0dy80** [comment]
@allofmex 
at the end, you are right. 
maybe i just need to get used to this new behavior. 

@asgothian 
I think nearly every Switch acts like this. I can reproduce this everytime with philips and tradfri. a switch must get the configuration at least once to work properly.

**Comment by allofmex** [comment]
Maybe we will find a better but clean approach later. I agree, it is not perfect yet. As of now I would suggest to keep it that way. It works at least and does not cause too much overhead.

**Comment by asgothian** [comment]
All my tests last night hint at the following behaviour:
- An end-device which was configured successfully for one network does not require reconfiguration when the bridge (zigbee-adapter) restarts
- Configuration right after pairing usually works after 2 or 3 tries.
- Removing power from the device for may remove an active configuration, and as such require re-configuration, even if the network pairing is retained.

I suggest the following changes (and will try to implement them):
- remove warning messages for reconfiguration attempts
- keep the periodic attempt at reconfiguration
- when the network is closed after pairing, activate a "configure on message" mode for n seconds (fixed, 60 seconds for now, possibly configurable later)
- On each device card, show configuration status and a button which places the device id in the reconfiguration queue and activates the "configure on message" mode for n seconds (see above).

Thoughts ?

**Comment by asgothian** [comment]
I have completed the work on the approach mentioned above - this is now available as a branch again, with one small change - the configure on message is now automatically open for 5 minutes after starting the adapter, and it no longer needs to look through the list of unconfigured devices, as i introduced a datapoint "configurationNeeded" in the "native" section of the object. This datapoint is set based on the endpoint configuration every time the adapter starts, and is also used by the devices tab to show the configuration status of the device. 
It is also possible to activate it for 1 minute, but it is not automatically activated after pairing a new device.
For now, things are working, but with this datapoint, the scheduling function for reconfiguration might be streamlined a bit. I will look into this.
I have put the debug version out for testing on the ioBroker forum, but would appreciate more comments / insights
The code is at 
`asgothian/iobroker.zigbee/tree/admin_changes`

**Comment by allofmex** [comment]
> configure on message is now automatically open for 5 minutes after starting the adapter

So what would happen if the device does not send anything within this 5 minutes? (like the remotes if no button pushed)

PS: 

> The code is at
asgothian/iobroker.zigbee/tree/admin_changes instead of 

Please use links to your github branch instead of plain text, thanks ;-)

**Comment by asgothian** [comment]
Fixed.
If a device does not send any message, the confgure on message is never triggered for this device. The system will still try to configure the device through the scheduled confit attempts. Any successful config will set the flag on the device to prevent duplicate configuration attempts.
