### ISSUE TITLE
Support for FNB56-ZSW01LX2.0

### ISSUE THREAD

**Issue by mdn-united** [ioBroker/ioBroker.zigbee#255]
hi @kirovilya, 
could you please add the support of the "FNB56-ZSW01LX2.0 - 3A Zigbee switch (2 gang)" ?

Here you'll find more about the device in Koen's project. (I think he also mentioned you in one post.)
https://github.com/Koenkk/zigbee-shepherd-converters/issues/278
https://github.com/Koenkk/zigbee-shepherd-converters/commit/2c2cdf474058dbd032419b58079938638b941e50

Thank you very much!

**Comment by asgothian** [comment]
Please post the device details, either the card(s) from pairing the device in iobroker or the log messages generated after device pairing.

**Comment by mdn-united** [comment]
Here are the log messages:

Zigbee | Time | Debug | Message
-- | -- | -- | --
zigbee.0 | 2019-03-19 17:25:30.184 | error | No converter available for 'HGZB-42-UK / HGZB-41' with cid 'genBasic' and type 'devChange'
zigbee.0 | 2019-03-19 17:25:12.259 | error | Device 00158d00025d7a9e "FNB56-ZSW01LX2.0" not described in statesMapping.
zigbee.0 | 2019-03-19 17:25:12.259 | error | Device 00158d00025d7a9e "FNB56-ZSW01LX2.0" not described in statesMapping.
zigbee.0 | 2019-03-19 17:24:17.823 | info | new dev 0x00158d00025d7a9e 28312 FNB56-ZSW01LX2.0
zigbee.0 | 2019-03-19 17:24:15.953 | info | Zigbee: allowing new devices to join.

And a few screen shots:
![grafik](https://user-images.githubusercontent.com/11157159/54623996-dad7a600-4a6c-11e9-9a7c-dae1afe9ebdd.png)
![grafik](https://user-images.githubusercontent.com/11157159/54624038-e925c200-4a6c-11e9-8046-ced498f91695.png)
![grafik](https://user-images.githubusercontent.com/11157159/54624054-f0e56680-4a6c-11e9-8359-ba9e8d99da5a.png)
![grafik](https://user-images.githubusercontent.com/11157159/54624173-27bb7c80-4a6d-11e9-9ba3-0096ac51e7af.png)
![grafik](https://user-images.githubusercontent.com/11157159/54624373-87b22300-4a6d-11e9-9241-9735528fe093.png)
![grafik](https://user-images.githubusercontent.com/11157159/54624398-939de500-4a6d-11e9-8787-ce3ec227a3c8.png)

**What else do you need?**

**Comment by asgothian** [comment]
That should do it, thanks. All I need now is a little time :)

**Comment by asgothian** [comment]
Please install the latest version from my GitHub branch to see if it is working, and let me know the status. Once all works i'll make a pull request into the main repository
```
https://github.com/asgothian/ioBroker.zigbee/tarball/ecozy
```

**Comment by mdn-united** [comment]
Unfortunately it still doesn't work. 
First I tried to get the latest version from Github (and I like the new network map!) and later I tried the link that you provided.

Here is what I found in the log:

Zigbee.0 | Time | Log | Message
-- | -- | -- | --
zigbee.0 | 2019-03-20 17:33:50.090 | error | Device 00158d00025d7a9e "FNB56-ZSW01LX2.0" not described in statesMapping.
zigbee.0 | 2019-03-20 17:33:50.088 | error | Device 00158d00025d7a9e "FNB56-ZSW01LX2.0" not described in statesMapping.
zigbee.0 | 2019-03-20 17:33:20.459 | error | No converter available for 'HGZB-42-UK / HGZB-41' with cid 'genBasic' and type 'devChange'
zigbee.0 | 2019-03-20 17:32:56.353 | info | new dev 0x00158d00025d7a9e 14709 FNB56-ZSW01LX2.0
zigbee.0 | 2019-03-20 17:32:50.337 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-03-20 17:31:46.259 | info | new dev 0x00158d000258456b 54941 FNB56-ZSW01LX2.0
zigbee.0 | 2019-03-20 17:31:41.035 | info | Zigbee: allowing new devices to join.

![grafik](https://user-images.githubusercontent.com/11157159/54702203-ae885c00-4b36-11e9-80b0-5891e4d54b21.png)

**Comment by asgothian** [comment]
Can you please check the version of the zigbee-shepherd-converters you have installed ?
(in the folders \opt\iobroker\node_modules\zigbee-shepherd-converters and/or \opt\iobroker\node_modules\iobroker.zigbee\node_modules\zigbee-shepherd-converters, do tail package.json to see the version

**Comment by mdn-united** [comment]
opt\iobroker\node_modules\zigbee-shepherd-converters\package.json -->version": "7.1.8

**Comment by asgothian** [comment]
Der ist schon mal zu alt. Hast du den anderen auch noch ?

**Comment by mdn-united** [comment]
###### Deutsch ist schon ok. So was wie 'ne Muttersprache für mich. Aber damit die Community auch was von dem Thread hat ...

That's the only path that exists. The other one doesn't.  
And honestly: I have no idea how to update those files or how they got installed in the first place.

**Comment by asgothian** [comment]
it will get installed when installing the adapter - or should. It might not get installed if you install straight from GitHub. Can you please update to the current stable 0.10.2 version via the normal iobroker suystem, then check what versions of the shepherd-converters you have, and if you have at least 8.0.0, install from the link above again ?

**Comment by mdn-united** [comment]
Strange thing: I installed 10.0.2 from the "latest" repository and then from Github directly, but every time I end up with "version": "2.0.20" 
/opt/iobroker/node_modules/zigbee-shepherd-converters/package.json

**Comment by mdn-united** [comment]
### HEY! IT WORKS!
I use the adapter from you link and after another pairing, the objects appeared immediately in the tree and I could turn the switch on and off via ioBroker. Thank you. I allready replaced the old wall switch and wrote a script to control it with my Aquara Cube.

The only thing missing is a picture of the switch. I bought the switch from Amazon and they have a good picture of it here: https://www.amazon.de/dp/B07GWR3VBX/ref=cm_sw_em_r_mt_dp_U_NAiLCb6YB4J9W

Another question: After the 2 gang switch is working I want to buy the 1 gang switch as well: https://www.amazon.de/dp/B07GXGQHB2/ref=cm_sw_em_r_mt_dp_U_hDiLCb9E8R8JT
Do I have to go through all the hassle with Koen for the Zigbee Shepherd Converter again or could I just post here a new request?

**Comment by asgothian** [comment]
Odd.. there should have been an image. But no matter... the pull request to Ilya will have the image.

With regards to the 1 gang switch - i think there is a decent chance you don't have to do anything, as the 2 gang switch actually uses 2 separate zigbee transmitters. Just try to connect it and post the results, and we'll take a look at it.
