### ISSUE TITLE
Add support for 4058075816718 OSRAM SMART+ outdoor wall lantern RGBW

### ISSUE THREAD

**Issue by Butz86** [ioBroker/ioBroker.zigbee#256]
Please add the support for the OSRAM SMART+ outdoor wall lantern RGBW (Model 4058075816718) from Koenkks project.

**Comment by asgothian** [comment]
Please post how the lantern is identified in iobroker (Text on the object card or log message when pairing the lantern)

**Comment by Butz86** [comment]
Outdoor Lantern W RGBW 
OSRAM
7cb03eaa00ae4310

**Comment by asgothian** [comment]
Fixed in my development branch. Please install from 
`https://github.com/asgothian/ioBroker.zigbee/tarball/ecozy` and check if it works.

Note - remember to perform an "upload" after installing from GitHub.
