### ISSUE TITLE
Cannot change state of Xiaomi wall switch QBKG04LM

### ISSUE THREAD

**Issue by DcFamas** [ioBroker/ioBroker.zigbee#258]
Hey guys,
when I try to change the state of my xiaomi aqara wall switch I get the following error log:

gbee publish to '_devicename_', genOnOff - off - {} - 1 failed with error Error: Timed out after 30000 ms

I use version 0.10.2 in ioBroker and the switch QBKG04LM.

Best regards

**Comment by asgothian** [comment]
Error Timeout indicates that the stick has no connection to the switch or that the switch did not respond to the action. This is not a software issue.

**Comment by DcFamas** [comment]
Hey, thanks for the answer. The wall switch is the only device, that set this failure. Also I can see a good link between the stick and the wall switch. Still the switch?

**Comment by asgothian** [comment]
As odd as it sounds - yes. Link state is a data point, which is updated when messages are exchanged. As such, the link value you see may be outdated at the time.
In my eyes, this still points to 1 of 2 issues:
- no active connection, thus no response to the message
- active connection, but something on the switch prevents it from responding to the on/off command.

I would ask you to query the firmware version of the switch by selecting the blue i icon on the card in the device view. I would be interested to know if the switch responds to this.

There are more things to check, but those i cannot describe before later tonight when i have access to my system.

**Comment by DcFamas** [comment]
Hey asgothian, thanks again for the support.
When I press the blue i, I get this text "Hardware Version: 38". 
Tomorrow I'll get another wall switch (with neutral) and I'm going to test the same with this one.

**Comment by asgothian** [comment]
A Question - did it work at one point, or was the error message always present when trying to change the status ?

**Comment by DcFamas** [comment]
Hey, it never worked. This is my first wall switch by xiaomi. Tomorrow I can tell you more. :)

**Comment by asgothian** [comment]
good.. is it a single or double switch ? I have a double one here which works just fine (with neutral)

**Comment by andromedi4** [comment]
Hi, guys! I`ve same problem with Aqara wall switch! Problem started after I updated adapter from 0.8.0 to 0.10.2. (Zigbee publish to '0x00158d00025252d1', genOnOff - on - {} - 1 failed with error Error: Timed out after 30000 ms)
If I reinstall adapter to 0.8.0 switch starting work correctly. I think it`s not a problem with connection.

**Comment by asgothian** [comment]
can you please post the Device details, then i can take a closer look at the changes. As i wrote above, i have a wall switch in use and do not have this issue with 0.10.2

**Comment by DcFamas** [comment]
Hey, I use an non neutral xiaomi aqara single wall switch. The product id is QBKG04LM. 
I installed version 0.8.0 and the switch work like a charme.

**Comment by andromedi4** [comment]
> can you please post the Device details, then i can take a closer look at the changes. As i wrote above, i have a wall switch in use and do not have this issue with 0.10.2

My setup:
1. Debian 8.11
2. node.js 8.15.1
3. npm 6.4.1
4. iobroker 3.6.0
5. serialport 7.1.4 (I tried to downgrade to serialport 6, issue persisted)
6. CC2531
7. ioBroker.zigbee 0.10.2 - I`ve issue (with ioBroker.zigbee 0.8.0 work correctly) 
8. Xiaomi Aqara Wall Single Swith (without neutral)

**Comment by DcFamas** [comment]
Hey, for sure:

1. Debian 9.5 stretch
2. node.js 6.14.3
3. npm 4.6.1
4. ioBroker 3.6.0
6. CC2531
7. ioBroker.zigbee 0.10.2 - I`ve issue (with ioBroker.zigbee 0.8.0 work correctly)
8. Xiaomi Aqara Wall Single Swith (without neutral) QBKG04LM

5. how to check for serialport version? 

root@ioBroker:/home/administrator# dmesg | grep tty
[    0.000000] console [tty0] enabled
[    2.991020] cdc_acm 1-2:1.0: ttyACM0: USB ACM device

Best regards

**Comment by andromedi4** [comment]
> 8. how to check for serialport version?

npm view serialport

**Comment by DcFamas** [comment]
8. 7.1.4

:)

**Comment by asgothian** [comment]
Can you please also verify the zigbee-shepherd and zigbee-shepherd-converters version, once before and once after downgrading to 0.8.0 ? I was unable to find a change related to the switch between in iobroker.zigbee between 0.8.0 and 0.10.2

**Comment by asgothian** [comment]
I have good news, so so news and bad news.
Good news - i found what is wrong.
so so news - i am not sure how to fix it outside an ugly hack.
bad news - it is in the zigbee-shepherd-converters. Meaning, i need to find out who changed it, why, and then possibly get it changed back. This will take a bit of time.

**Comment by DcFamas** [comment]
Hey @asgothian thanks for your work! :)

Take your time, as long as the 0.8.0 is working, everything is fine. When you need some information from other systems, pelase let me know.

Best regards.

**Comment by asgothian** [comment]
You're welcome. Fortunately, the folks at zigbee2mqtt reacted quickly and pointed me towards a change which was made which i could duplicate (and should) in iobroker.zigbee. 

can you install from 
```
https://github.com/asgothian/ioBroker.zigbee/tarball/Admin_Changes
```
(using the cat and then custom) to see if this fixes your switch ?

**Comment by DcFamas** [comment]
Hey @asgothian 
it is working! :)
I installed the link you sent me, than I created a new instance and learned the switch to ioBroker.
Only a cosmetic thing would be, that the standard name of the device is "lumi.ctrl_neutral1", that's not true because it is the nonneutral one.

What a great support, keep it up and many many thanks! :)

**Comment by asgothian** [comment]
Thank you for the praise. I'd appreciate if you keep using that version for a bit to see if there are any negative side effects before i make a pull request for the standard.

**Comment by DcFamas** [comment]
For sure! :)

**Comment by andromedi4** [comment]
@asgothian I installed and in my case it`s working correctly too.
THANK YOU!!!

**Comment by asgothian** [comment]
Please watch out for strange behavior for a few days - i had to make a change rather deep in the code which may affect other devices too. If i don't see any note before Sunday, i'll generate a pull request.

**Comment by andromedi4** [comment]
@asgothian Hi, I`ve some error... Look at this:

zigbee.0 | 2019-03-21 20:22:22.800 | error | Zigbee publish to '0x00158d00025252d1', genOnOff - read - [{"attrId":0}] - 2 failed with error Error: AF data request fails, status code: 240. MAC transaction expired.
-- | -- | -- | --
zigbee.0 | 2019-03-21 20:22:22.799 | error | Zigbee publish to '0x00158d00025252d1', genOnOff - on - {} - 2 failed with error Error: AF data request fails, status code: 240. MAC transaction expired.
zigbee.0 | 2019-03-21 20:22:16.565 | error | Zigbee publish to '0x000b57fffed9579d', genOnOff - read - [{"attrId":0}] - 1 failed with error Error: rsp error: 16

**Comment by DcFamas** [comment]
@asgothian same here:


zigbee.2 | 2019-03-21 08:11:40.173 | error | Zigbee publish to '0x00158d00030b2cfe', genOnOff - on - {} - 2 failed  with error Error: AF data request fails, status code: 240. MAC  transaction expired.
-- | -- | -- | --
