### ISSUE TITLE
Tradfri remote control still not working

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.zigbee#259]
even with latest zigbee adapter (0.10.2) and latest converters, the tradfri wireless dimmer isnt reporting any values.

zigbee.0 | 2019-03-17 15:04:29.333 | info | Successfully configured 0x000b57fffed28728
-- | -- | -- | --
zigbee.0 | 2019-03-17 14:34:26.012 | info | new dev 0x000b57fffed28728 14725 TRADFRI remote control
-- | -- | -- | --

![image](https://user-images.githubusercontent.com/28686079/54492471-4718a500-48c7-11e9-9140-9466cf7eb08c.png)

**Comment by sonntam** [comment]
For me it works flawlessly. If you are using an old pre 20190223 firmware for your CC2531/CC2530 stick you have to find out the group your IKEA remote is in by sniffing zigbee traffic (see [here](https://github.com/Koenkk/zigbee2mqtt.io/blob/5d7c46e4f3adc585714efa75d69ca429826f7eba/getting_started/pairing_devices.md)). Then you will have to create a group within iobroker.zigbee with that group ID so the coordinator can listen to the messages.
![image](https://user-images.githubusercontent.com/6692408/54495694-7ab6f780-48e6-11e9-8969-2739e75889cf.png)


Or you could try the new firmware from [here](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator).

**Comment by nob0dy80** [comment]
@sonntam 
thanks for your high qualified reply, really appriciated.
the problem is.. the latest stable firmware for me on a cc2530 is 20190119 .. i tried the 0223 but it freezes oftens during i wasnt ready paring all devices.

this seems to be a major bug (many have it) regarding link quality between coordinator and routers.

so i start with sniffing..
but why the heck is that needed? also got a tradfri wireless dimmer that works flawless.
this is the only device that isnt working..

but sniffing is a good start to find out ... 
or do you think i just can give it a try with 28110 ? is this a common  ID or does it change regulary ?

**Comment by nob0dy80** [comment]
ignore my questions. all answers are in your link :-<
