### ISSUE TITLE
Can I use Bitron Home devices with the adapter?

### ISSUE THREAD

**Issue by Smarti15** [ioBroker/ioBroker.zigbee#26]
Can I use Bitron Home devices with the adapter?
http://www.bitronvideo.eu/index.php/produkte/smart-home-produkte/

What do I need for this? A USB stick like this one here:

https: //www.aliexpress.com/item/Wireless-Zigbee-CC2531-Sniffer-Packet-Protocol-Analyzer-Module-USB-Interface-Dongle-Capture-Packet/32769663830.html

**Comment by kirovilya** [comment]
I think you can, cause it use protocol ZigBee Home Automation Version 1.2. But currentlly it is not supported yet. We need some debug logs from this devices, then write some code in library :)

About USB stick, please follow instruction here https://github.com/Koenkk/zigbee2mqtt/wiki/Getting-started

**Comment by Smarti15** [comment]
Wow that sounds good to many thanks :)
I order the first time all the equipment and build everything with me and then I'll call me again.

Many thanks :)

**Comment by Smarti15** [comment]
HI kirovilya. I have flashed the USB stick and I have already found and connected the first Xiaomi sensors. Now I would like to integrate the Bitron devices. What do you need now, so that you may integrate the devices? The adapter has already found the smart plug: http://www.bitronvideo.eu/index.php/produkte/smart-home-produkte/smart-plug-mit-schaltfunktion/

here is a debug logfile:
`

 
--


`

**Comment by Smarti15** [comment]
And a Smoke Alarm:


zigbee.0 | 2018-08-18 16:12:41.218 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  28","ack":false,"ts":1534601561213,"q":0,"from":"system.adapter.zigbee.0","lc":1534601561213}
-- | -- | -- | --
zigbee.0 | 2018-08-18 16:12:41.215 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":28,"ack":false,"ts":1534601561211,"q":0,"from":"system.adapter.zigbee.0","lc":1534601561211}
zigbee.0 | 2018-08-18 16:12:41.206 | debug | Join countdown. 28
zigbee.0 | 2018-08-18 16:12:40.215 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  29","ack":false,"ts":1534601560211,"q":0,"from":"system.adapter.zigbee.0","lc":1534601560211}
zigbee.0 | 2018-08-18 16:12:40.210 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":29,"ack":false,"ts":1534601560205,"q":0,"from":"system.adapter.zigbee.0","lc":1534601560205}
zigbee.0 | 2018-08-18 16:12:40.202 | debug | Join countdown. 29
zigbee.0 | 2018-08-18 16:12:39.570 | debug | sendTo "getDevices" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2018-08-18 16:12:39.570 | debug | getDevices result: [{"type":"device","common":{"name":"Temp & Luft  (HWR)","type":"lumi.sens","icon":"img/sensor_ht.png"},"from":"system.adapter.zigbee.0","ts":1534598909897,"_id":"zigbee.0.00158d0002
zigbee.0 | 2018-08-18 16:12:39.555 | debug | sendTo "getDevices" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2018-08-18 16:12:39.554 | debug | getDevices result: [{"type":"device","common":{"name":"Temp & Luft  (HWR)","type":"lumi.sens","icon":"img/sensor_ht.png"},"from":"system.adapter.zigbee.0","ts":1534598909897,"_id":"zigbee.0.00158d0002
zigbee.0 | 2018-08-18 16:12:39.493 | debug | Device 00124b0004261ab7 "902010/24" not described in statesMapping.
zigbee.0 | 2018-08-18 16:12:39.476 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"New device joined  0x00124b0004261ab7 model  902010/24","ack":false,"ts":1534601559469,"q":0,"from":"system.adapter.zigbee.0","lc":1534601559469}
zigbee.0 | 2018-08-18 16:12:39.473 | debug | Message without data cluster!
zigbee.0 | 2018-08-18 16:12:39.472 | debug | handleMessage.  {"type":"devStatus","endpoints":[{"device":{"_id":4,"type":"EndDevice","ieeeAddr":"0x00124b0004261ab7","nwkAddr":51975,"manufId":0,"manufName":"Bitron  Home","powerSource":"Battery","mo
zigbee.0 | 2018-08-18 16:12:39.467 | info | new dev 0x00124b0004261ab7 51975 902010/24
zigbee.0 | 2018-08-18 16:12:39.462 | debug | new device 0x00124b0004261ab7 joining the network!
zigbee.0 | 2018-08-18 16:12:39.462 | debug | handleMessage.  {"type":"devIncoming","endpoints":[{"device":{"_id":4,"type":"EndDevice","ieeeAddr":"0x00124b0004261ab7","nwkAddr":51975,"manufId":0,"manufName":"Bitron  Home","powerSource":"Battery","
zigbee.0 | 2018-08-18 16:12:39.455 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  100%","ack":false,"ts":1534601559442,"q":0,"from":"system.adapter.zigbee.0","lc":1534601559442}
zigbee.0 | 2018-08-18 16:12:39.440 | debug | Device 0x00124b0004261ab7 try to connect {"totalEp":1,"currentEp":1,"progress":100}
zigbee.0 | 2018-08-18 16:12:39.438 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":4,"current":4},"total":1}},"data":"0x00124b0004261ab7"}
zigbee.0 | 2018-08-18 16:12:39.212 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  30","ack":false,"ts":1534601559206,"q":0,"from":"system.adapter.zigbee.0","lc":1534601559206}
zigbee.0 | 2018-08-18 16:12:39.207 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":30,"ack":false,"ts":1534601559203,"q":0,"from":"system.adapter.zigbee.0","lc":1534601559203}
zigbee.0 | 2018-08-18 16:12:39.199 | debug | Join countdown. 30
zigbee.0 | 2018-08-18 16:12:38.962 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  75%","ack":false,"ts":1534601558955,"q":0,"from":"system.adapter.zigbee.0","lc":1534601558955}
zigbee.0 | 2018-08-18 16:12:38.954 | debug | Device 0x00124b0004261ab7 try to connect {"totalEp":1,"currentEp":1,"progress":75}
zigbee.0 | 2018-08-18 16:12:38.952 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":4,"current":3},"total":1}},"data":"0x00124b0004261ab7"}
zigbee.0 | 2018-08-18 16:12:38.531 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  50%","ack":false,"ts":1534601558524,"q":0,"from":"system.adapter.zigbee.0","lc":1534601558524}
zigbee.0 | 2018-08-18 16:12:38.522 | debug | Device 0x00124b0004261ab7 try to connect {"totalEp":1,"currentEp":1,"progress":50}
zigbee.0 | 2018-08-18 16:12:38.521 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":4,"current":2},"total":1}},"data":"0x00124b0004261ab7"}
zigbee.0 | 2018-08-18 16:12:38.284 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  25%","ack":false,"ts":1534601558278,"q":0,"from":"system.adapter.zigbee.0","lc":1534601558278}
zigbee.0 | 2018-08-18 16:12:38.276 | debug | Device 0x00124b0004261ab7 try to connect {"totalEp":1,"currentEp":1,"progress":25}

**Comment by Smarti15** [comment]
And here a Xiaomi Motion Sensor with error:


zigbee.0 | 2018-08-18 16:35:32.883 | debug | Join countdown. 23
-- | -- | -- | --
zigbee.0 | 2018-08-18 16:35:31.897 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  24","ack":false,"ts":1534602931893,"q":0,"from":"system.adapter.zigbee.0","lc":1534602931893}
zigbee.0 | 2018-08-18 16:35:31.894 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":24,"ack":false,"ts":1534602931889,"q":0,"from":"system.adapter.zigbee.0","lc":1534602931889}
zigbee.0 | 2018-08-18 16:35:31.880 | debug | Join countdown. 24
zigbee.0 | 2018-08-18 16:35:31.518 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Error: Cannot get  the Node Descriptor of the Device: 0x00158d0001a8fa29 (Error: Timed out  after 10000 ms). undefined","ack":false,"ts":1534602931
zigbee.0 | 2018-08-18 16:35:31.513 | error | Cannot get the Node Descriptor of the Device: 0x00158d0001a8fa29 (Error: Timed out after 10000 ms)
zigbee.0 | 2018-08-18 16:35:30.884 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  25","ack":false,"ts":1534602930879,"q":0,"from":"system.adapter.zigbee.0","lc":1534602930879}
zigbee.0 | 2018-08-18 16:35:30.880 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":25,"ack":false,"ts":1534602930877,"q":0,"from":"system.adapter.zigbee.0","lc":1534602930877}
zigbee.0 | 2018-08-18 16:35:30.874 | debug | Join countdown. 25
zigbee.0 | 2018-08-18 16:35:29.884 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  26","ack":false,"ts":1534602929877,"q":0,"from":"system.adapter.zigbee.0","lc":1534602929877}
zigbee.0 | 2018-08-18 16:35:29.878 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":26,"ack":false,"ts":1534602929873,"q":0,"from":"system.adapter.zigbee.0","lc":1534602929873}
zigbee.0 | 2018-08-18 16:35:29.870 | debug | Join countdown. 26
zigbee.0 | 2018-08-18 16:35:28.876 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  27","ack":false,"ts":1534602928873,"q":0,"from":"system.adapter.zigbee.0","lc":1534602928873}
zigbee.0 | 2018-08-18 16:35:28.874 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":27,"ack":false,"ts":1534602928870,"q":0,"from":"system.adapter.zigbee.0","lc":1534602928870}
zigbee.0 | 2018-08-18 16:35:28.867 | debug | Join countdown. 27

**Comment by kirovilya** [comment]
About `Xiaomi Motion Sensor `... from wiki:
> Most MiJia devices: press and hold the reset button on the device for +- 5 seconds (until the blue light starts blinking). IMPORTANT: Release and start pressing the reset button every second. This keeps the device awake, otherwise pairing will fail!.

About Bitron... from logs: 
"902010/28" - smart plug
"902010/24" - smoke alarm

Devices normally connected to the network, but now the most difficult thing is to find the codes of their events. It is not in the logs.
It is necessary to turn on and off the socket, connect the load to it - these events should get to the log and we'll see them.

With a smoke detector, you also need to somehow make it work :) to get to the log.

You have attached logs from the admin - it is truncated - I need complete log file. It is better to put it in to archive.

**Comment by kirovilya** [comment]
Logs are usually located here /opt/iobroker/log - theare many log files by days

**Comment by Smarti15** [comment]
I have you send a mail with logfile. 
Many thanks for your effort
