### ISSUE TITLE
While update getting "WARN bl@0.7.0 requires a peer of stream-browserify@* but none is installed"

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.zigbee#260]
While update to v. 0.10.2 I get this message: "WARN bl@0.7.0 requires a peer of stream-browserify@* but none is installed. You must install peer dependencies yourself."

I´m not sure if this happend to the versions before as well, and I also don´t have a clue what it means or how to resove it...

Anybody more clever than me? ;-)))

**Comment by killakaktus** [comment]
I had the same problem. Various tries to install it manually fails. Then i deleted the whole adapter and reinstalled it - faultless.

**Comment by Thomas1305** [comment]
Same here.
Update only works if you uninstall the adapter first.

**Comment by Michaelnorge** [comment]
Ok, so that was my mistake. I made an update on the stick in, and I needed to reconnect al zigbee units (I have 31) - it tok almost all weekend.

So i have to spent one more weekend i guess....

**Comment by killakaktus** [comment]
Pity. A new flash was not necessary.

**Comment by Michaelnorge** [comment]
ok, just one more time for stupids like me:
The firmware on the USB-dongle is updated to the last version.
So I just have to delete the zigbee-adapter and install it again, right?

But than I need to pair all my zigbee stuff again, right?

**Comment by killakaktus** [comment]
When you delete the adapter and reinstall it, the paired devices will NOT deleted - all paired devices will be there.

**Comment by Michaelnorge** [comment]
Nice I made an image before i tried it:
I deleted the adapter from the list, after that I reinstalled it.
While installing the same error was shown in the log again!
And  zigbee-adapter was available in the adapter list but not in the instance-list anymore. 
Tried several times to delete and reinstall, but it didn´t helped.

**Comment by killakaktus** [comment]
If there no instance you can manually add one. At adapters you can add a instance with the  + symbol. 

sorry if i couldn't help. :( 
in my case, this method solved the problem.
