### ISSUE TITLE
Please add support for GLEDOPTO GL-C-006 WW/CW Controller

### ISSUE THREAD

**Issue by tr1pp4** [ioBroker/ioBroker.zigbee#262]
Please add support for GLEDOPTO GL-C-006 WW/CW LED Controller

It's already supported in zigbee2mqtt
Log says: "Device 00124b001ba6dc61 "GL-C-006" not described in statesMapping."

Thanks a lot

**Comment by snador1977** [comment]
Yes, that would be great.

**Comment by snador1977** [comment]
Yes, that would be great. GL-C-007 (RGBW) and GL-C-008 (RGB + CCT) are already working ...

**Comment by asgothian** [comment]
You can't. But the good news is, the base for my test adapter is the current stable 0.10.2, i.e. all normal functionality should remain, and you should not need to re-pair any devices. If it does not work, you can just install the previous stable version through the iobroker interface to get back.

**Comment by snador1977** [comment]
I recapitulate: I install your adapter over the functions "Installation from own URl" => "any source". This overrides the normal Zigbee adapter? How can I see if the installation was successful and now your adapter is running? Thank you for your help!

**Comment by kueppert** [comment]
@snador, you can see it at the admin page. Version is shown behind the adapter name.
Don't forget the upload after update via GitHub (expert mode must be enabled)

**Comment by snador1977** [comment]
> @snador, you can see it at the admin page. Version is shown behind the adapter name.
> Don't forget the upload after update via GitHub (expert mode must be enabled)

Where I see the version that I know. But how can I tell if the alternative adapter was installed if it has the same version number as the original adapter?

**Comment by asgothian** [comment]
Right now, you can't, unless you look at the code. I can introduce a temporary version number change later tonight to make it visible.
Keep in mind that you have to upload after installing the adapter from GitHub before it becomes active.

**Comment by snador1977** [comment]
Ist this ok?

![screenshot](https://user-images.githubusercontent.com/45245918/54820796-9af90480-4ca0-11e9-928b-5ba5ff98d66a.jpg)

**Comment by snador1977** [comment]
Now the Resukt of GL-C-006

![screenshot](https://user-images.githubusercontent.com/45245918/54820956-1490f280-4ca1-11e9-88c0-76602936c9bb.jpg)

**Comment by asgothian** [comment]
The balance between ww and cw is handled by the coloremp datapoint. As far as I see it, there are n separate channels available in the zigbee-shepherd-converters. This can be integrated, but as all other lights with ww/cw balance use the ct datapoint we should do so here to.

A.

**Comment by snador1977** [comment]
So I control the brightness with one thing and the balance on the other. What does color.rgb do? Can I also set a HEX value at WW / CW?

**Comment by asgothian** [comment]
You will need to Test this. I would expect RGB to control the Color for the rgb LEDs only, whole ct will swap to using cw/ww leds only

**Comment by snador1977** [comment]
Sorry I do not really understand that yet. The controller has only one connector for white LEDS and one connector for warm white LEDS. So you can connect two LED Stripes or a combined LED Stripe. There is theoretically no further connection for RGB. The channel does not make sense unless it does something else ...

**Comment by asgothian** [comment]
Hmm.. i have to take a closer look at the implementation in the zigbee-shepherd-converters then. I simply exposed everything they had to ioBroker. I'll check that tomorrow and send you an update.

**Comment by snador1977** [comment]
switch: switches both channels on / off (true/false)

level.color.temperature: 
< 160 (WW-off/CW-full)
between: balance between WW und CW
>= 490 (WW-full/CW-off)

level.dimmer: dimm both channels WW / CW (0-off/100-full)

level.color.rgb: do nothing (value becomes red in admin)

**Comment by snador1977** [comment]
What are those strange numbers at the color temperature? I think the RGB channel can go away :-)

**Comment by asgothian** [comment]
Those control the color temperature. The Mapping to K should be approx. 2500K = 454, approx. 6500 K = 150
Can’t find the reference for it just now

**Comment by asgothian** [comment]
Ok, i fixed it in my repository, can you please reinstall from the link posted above ? You may have to manually delete the state "color" from your object tree, though

**Comment by snador1977** [comment]
WORKS! GREAT! THANKS!!!

**Comment by snador1977** [comment]
Only as info. I threw out the device and retrained and restarted ioBroker. This did not help. Only the complete reboot has made the device available.
