### ISSUE TITLE
tint remote - brightness long click for repeatedly keystroke (dimming) and groups

### ISSUE THREAD

**Issue by killakaktus** [ioBroker/ioBroker.zigbee#263]
as shortly discussed here [221](https://github.com/ioBroker/ioBroker.zigbee/issues/221#issuecomment-474100645) the ability to dimm the light more pleasing with a repeatedly keystroke would be great. 
also switching between groups (groups button on remote) would desirable ;)

**Comment by sonntam** [comment]
I will have a look at this. However, this weekend I don't have any access to a computer so. I have to put you off till next week.

**Comment by andre1974** [comment]
Any news on this?

**Comment by sonntam** [comment]
Unfortunately, I wasn't able to finish implementing it as I currently only have a limited amount of free time and no access to my computer at the weekends.

**Comment by sonntam** [comment]
I submitted a PR to koenkk/zigbee-shepherd-converters#409.
Shortly I will create a PR for iobroker.zigbee to accomodate for the new converters and states.

The functionality will be as follows:
There will be two new states

- brightness_down_hold
- brightness_up_hold

that will be set to "true" if the corresponding button is held and reset to "false" when the button is released. This way you can trigger some timer or pulse generator to control things in a cyclic manner with the button held.

**Comment by sonntam** [comment]
The PR #291 partly adresses this issue with respect to held brightness buttons:

Note: In order to be able to use this new functionality we will have to wait until Koenkk/zigbee-shepherd-converters#409 is merged and the used converters version has been upgraded in iobroker.zigbee.

@kirovilya: I tested the current master version of Koenkk/zigbee-shepherd-converters with no problems so I think it is safe to upgrade.

**Comment by sonntam** [comment]
Koenkk/zigbee-shepherd-converters#409 has been merged upstream

**Comment by sonntam** [comment]
@killakaktus It has been merged. Have you had the time to test it a bit? Does it work as intended? I myself don‘t use the hold functionality.

Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sonntam** [comment]
I think this issue can be closed. At least for me it is working.

If anything doesn't work after all, please create a new one.
