### ISSUE TITLE
No converter available for 'WSDCGQ11LM' with key 'temperature'

### ISSUE THREAD

**Issue by Hambootje** [ioBroker/ioBroker.zigbee#264]
This message is appearing on the Xiaomi weather sensor in the IOBroker logfile. Repairing the device did not help. 
Any idea?

**Comment by asgothian** [comment]
Does the data point in ioBroker update when the temperature changes, or does it stay fixed ?
which version of the adapter are you currently using ?

**Comment by Hambootje** [comment]
All data from the sensor is updated in ioBroker as expected. All values from this sensor (humitity, pressure, battery status) get an ack, except for temperature. Here the value turns red and this message is presented in the log.
I'm using the latest, 0.10.2 version of the adapter

**Comment by Hambootje** [comment]
After some more debugging I found out that a javascript was accidently writing to this temperature object too. Issue is solved, sorry for the trouble.
