### ISSUE TITLE
zigbee.0.group_1.brightness = 0 doesnt turn of lights

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.zigbee#265]
Hi, i added 4 Tradfri GU10 Lamps to a group. If you set zigbee.0.group_1.brightness to zero, the power state remains true and the lamp is dimmed down to a minimum.
If you set brightness 0 direct in a lamp object, the lamp goes off.

**Comment by nob0dy80** [comment]
Setting a value to zigbee.0.group_1.brightness (ex 50) wont turn on the light too.
zigbee.0.group_1.state remains false.

**Comment by allofmex** [comment]
This is a big issue for me too. Brightness state is broken on groups.
- Setting brightness to 0 works but ignores transition_time.
- If state is false, setting brightness to >0 does nothing, setting state to true afterwards switches bulb to set brightness but ignores transition_time again.

I cannot smoothly on/off my bulbs anymore! It worked before, just setting brightness to 0 (off) or >0 (on) worked perfectly with transition_time (no need for state handling). I don't understand why the converter was changed at all.

Guess its related to https://github.com/ioBroker/ioBroker.zigbee/issues/218
