### ISSUE TITLE
Paulmann RGBW controller (500.47) - white Channel / State is missing

### ISSUE THREAD

**Issue by snador1977** [ioBroker/ioBroker.zigbee#266]
The Paulmann RGBW controller (500.47) is recognized correctly but the channel for white is missing. The channels / states for level.dimmer and level.color.rgb exist but level.color.temperature is missing. For example, there is this channel / state on the GLEDOPTO GL-C-007 RGBW controller.

**Comment by asgothian** [comment]
How does this controller identify in ioBroker ? I could not find any reference to it in the zigbee-shepherd-converters. The two units which are implemented are 500.49, which is RGB, no W, and 500.45, which is White dimmable.

**Comment by snador1977** [comment]
I do not know that :-) But he does it.

![img_01](https://user-images.githubusercontent.com/45245918/54741081-91e33700-4bbd-11e9-898a-6ee991b924fe.jpg)
![img_02](https://user-images.githubusercontent.com/45245918/54741095-9d366280-4bbd-11e9-83ce-1cfa3aa35ac5.jpg)

**Comment by asgothian** [comment]
Ok. In order to fix this, we will need to patch the zigbee-shepherd-converters as well as the iobroker.zigbee. I can see if i can provide you with a test version on the weekend, but you will need to install both test versions (zigbee-shepherd-converters and iobroker.zigbee) manually.

**Comment by snador1977** [comment]
OK! We do so. I hope I get that with the installations :-)

**Comment by asgothian** [comment]
Fixed in my development branch. Please install from
```
https://github.com/asgothian/ioBroker.zigbee/tarball/ecozy and check if it works.
```

In order for this to work, you also need to install the zigbee-shepherd-converters from my repository. 
```
https://github.com/asgothian/zigbee-shepherd-converters
```

Connect to your iobroker, navigate to the Folder 
`/opt/iobroker/node_modules/iobroker.zigbee `
and execute 
```
npm install git+https://git@github.com/asgothian/zigbee-shepherd-converters.git
```
Note - remember to perform an "upload" after installing from GitHub.

**Comment by snador1977** [comment]
Hi, what's the zigbee-shepherd-converter? If I reinstall the original Zigbee adapter later, will we also reset the zigbee-shepherd-converter? Or how can I get it back to its original state?

**Comment by asgothian** [comment]
Yes, you will. I have made a pull request to the zigbee-shepherd-converters. Once that is through, you can install from the normal repository without any issues. Just give it a few days.

**Comment by asgothian** [comment]
Actually, the pull-request for the zigbee-shepherd-converters is already done. Bur the one for iobroker.zigbee is not yet.
