### ISSUE TITLE
No settings no network map showing anymore

### ISSUE THREAD

**Issue by djserkic** [ioBroker/ioBroker.zigbee#267]
Hi iam on the latest npm version but everything works well but
In the adapter there are nothing showing with network map and the other things please help

**Comment by asgothian** [comment]
Please post:
- Adapter Version
- node Version
- npm Version
- Version of zigbee-Shepherd-converters

**Comment by nob0dy80** [comment]
@djserkic 
first thing to try: open the map and use the mouse-wheel-scroll-up to minimize the map. maybe its just out of sight. had this once too.

**Comment by djserkic** [comment]
[Bild]




Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by djserkic** [comment]
I cant see the options of network map

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by allofmex** [comment]
@djserkic  I can't see your screenshots!

Please also do following:

- right click on map -> inspect
- tab "console"
- click "map reload" button bottom-right

Are there any errors showing?

**Comment by djserkic** [comment]
can you see the picture now?

________________________________
Von: serkan helvaci
Gesendet: Freitag, 22. März 2019 07:47
An: ioBroker/ioBroker.zigbee; ioBroker/ioBroker.zigbee
Cc: Mention
Betreff: Re: [ioBroker/ioBroker.zigbee] No settings no network map showing anymore (#267)


[Bild]




Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by djserkic** [comment]
![k](https://user-images.githubusercontent.com/48726350/54987556-187c8780-4fb5-11e9-9247-8f7d8e0d0e4c.png)

**Comment by arteck** [comment]
update your adapter.. its a very old version

**Comment by allofmex** [comment]
Should work in latest adapter version. Closing issue.
