### ISSUE TITLE
 Control GLEDOPTO GL-C-007 not yet completely correct

### ISSUE THREAD

**Issue by snador1977** [ioBroker/ioBroker.zigbee#269]
Hello asgothian - are we coming to the next device? :-) Thank you for your great work! At the
GLEDOPTO GL-C-007 (RGBW) counter, the controller does not work yet absolute correct. The channels level.dimmer / level.color.rgb / level.color.temperature / switch control the RGB part. The White Channel is alsways on. There is no way to control it.

**Comment by asgothian** [comment]
Fixing this needs changes to the zigbee-Shepherd-converters (again) - these are already queued for merge. I can have a look when they are active.

**Comment by snador1977** [comment]
Ok, big thank you! Tell me if something has changed or I still have to test something.
