### ISSUE TITLE
List supported devices

### ISSUE THREAD

**Issue by kirovilya** [ioBroker/ioBroker.zigbee#27]
We need our autogenerated list of supported devices like https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-devices

**Comment by arteck** [comment]
check

**Comment by kirovilya** [comment]
thank you. worked. https://github.com/ioBroker/ioBroker.zigbee/wiki/Supported-devices

**Comment by GermanBluefox** [comment]
Please link this list in README.md
