### ISSUE TITLE
Limit von 15 für Xiaomi Geräte andere funktionieren ??

### ISSUE THREAD

**Issue by m0rph2k** [ioBroker/ioBroker.zigbee#276]
Hallo

Ich habe bis jetzt insgesamt 15 Xiaomi Geräte aufgeteilt auf 2 x Osram Smart+ Plug und paar dirket auf dem CC2531 (siehe Map unten). Das es mit dem pairing immer etwas mühsam ist, ist mir nach 15 Geräten bekannt. 

Aber jetzt "glaube" ich zumindest, das ich keine Xiaomi Geräte mehr pairen kann, normalerweise bekomme ich wenigstens irgendwelche TimeOuts. Was mir aufgefallen ist das nach paar mal den Reset Knopf drücken das Geräte/LED 1 Sek lang leuchtet was mir eig. zum ersten mal aufgefallen ist.

Dann habe ich das gefunden das würde bedeuten das es fehlgeschlagen ist
[Button Function and LED light Indication](https://community.smartthings.com/t/original-aqara-xiaomi-zigbee-sensors-contact-temp-motion-button-outlet-leak-etc/113253)

Warum ich denke das es nur Xiaomi Geräte betrifft, weil ich vor kurzen allerdings nicht mit der 0.10.3 Version für einen Kollegen versucht habe eine Hue Dimmschalter zu pairen was funktioniert hat. Ich werde mir noch paar sachen ausborgen und Testen.

Sollte wem was bekannt sein bitte um Info, ich werde die Tage mal andere Geräte die nicht von Xiaomi sind versuchen zu pairen. 

Adapter Version: 0.10.3
Map
<a href="https://www.bilder-upload.eu/bild-6b0e4f-1553950079.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/6b0e4f-1553950079.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

LG

**Comment by arteck** [comment]
und wo ist dein problem ??

**Comment by m0rph2k** [comment]
> 
> 
> und wo ist dein problem ??

Das ich keine weiteren Xiaomi Geräte mehr pairen kann !?

**Comment by arteck** [comment]
lesen und verstehen... 

15 Devices direkt ohne Router nur am Stick..was bei dir ja nicht zutrifft

**Comment by m0rph2k** [comment]
die 15 Xiaomi Geräte hängen wie auf der Map zu sehen ist auf 2 x Osram Smart+ Plug und CC2531

**Comment by allofmex** [comment]
Was passiert wenn du einen der Plugs stromlos machst? (Und einige Zeit wartest). Verteilen sich die Sensoren dann auf den verbleibenden und den Coordinator? Oder gegen sie offline. Die Plugs haben sicher auch ein Limit an unterstützen Children. Vielleicht brauchst du also einen weiten Router...

**Comment by m0rph2k** [comment]
> 
> 
> Was passiert wenn du einen der Plugs stromlos machst? (Und einige Zeit wartest). Verteilen sich die Sensoren dann auf den verbleibenden und den Coordinator? Oder gegen sie offline. Die Plugs haben sicher auch ein Limit an unterstützen Children. Vielleicht brauchst du also einen weiten Router...

Ich habe jetzt einen Plug 12 Stunden lang ausgesteckt, die Geräte die voher laut MAP auf diesen Plug hingen funktionieren bis auf 2 Temp Sensoren. Die Netzwerkkatrte vom Adapter kann man jetzt aber überhaupt nicht mehr trauen wenn es nach der gehen würde sollte so gut wie nichts funktionieren.

<a href="https://www.bilder-upload.eu/bild-6592ea-1554018709.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/6592ea-1554018709.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Comment by m0rph2k** [comment]
OK, neue Situation. Nochmal versucht zu pairen diesmal "normales" verhalten was man gewohnt ist. Der große unterschied war diesmal das der Xiaomi statt 1 Sek lang leuchtet (was laut Doku bedeutet das der Join versuch fehlgeschlagen ist) 3 mal kurz blinkt.

Jetzt stellt sich die frage warum das so war ist sicher kein zufall das es nachdem ich den Plug stromlos gemacht habe und gewartet habe funktioniert hat. 
Das Paieren hat davor auf keinen Router/Coordinator funktioniert daher gehe ich nicht davon aus das es an den einzelnen Plug lag.

**Comment by allofmex** [comment]
Hattest du den Broker/CC2531 in der Zwischenzeit mal neu gestartet gehabt? Ich muss immer erst den Stick abziehen und neu stecken bevor ich neu pairen kann. Wenn er eine Weile lief funktioniert es nicht ("Cannot get node descriptor...)

**Comment by m0rph2k** [comment]
Vor dem ausstecken des Plugs habe ich alles neugestartet, hat nicht geholfen. In der Nacht wird immer ein Backup gemacht da wird aber nur IOboker gestoppt und wieder gestartet.

**Comment by arteck** [comment]
@m0rph2k  lese bitte genau was @allofmex  geschrieben hat 

>  Ich muss immer erst den Stick abziehen und neu stecken bevor ich neu pairen kann.
