### ISSUE TITLE
Change UART ports

### ISSUE THREAD

**Issue by Sergey116** [ioBroker/ioBroker.zigbee#28]
Hello! I have [this device](https://www.waveshare.com/product/CC2530-Eval-Kit5.htm). How I can change UART ports from P0_2, P0_3 to P1_4, P1_5 in firmware?

Здравствуйте! У меня есть [такой модуль](https://www.waveshare.com/product/CC2530-Eval-Kit5.htm). Подскажите, пожалуйста, как мне поменять UART порты с P0_2, P0_3 на P1_4, P1_5 в прошивке чтобы была возможность использовать штатный usb-serial конвертер? В наличии есть IAR и CC Debugger.

**Comment by kirovilya** [comment]
@Sergey116 Привет. Честно - не знаю как поменять. Но я знаю что там 2 uart подключения и можно подключиться ко второму https://sunmaysky.blogspot.com/2016/09/how-to-use-two-uart-ports-in-cc2530-z.html
А чем вызвана необходимость перекидывания? не выходит подключаться к основным контактам?

**Comment by Sergey116** [comment]
У этого модуля на плате распаян конвертер usb-serial, который подключен судя по всему к P1_4, P1_5 выводам CC2530. Хотелось бы использовать его раз он уже есть. Тем не менее спасибо за ответ, буду думать.

**Comment by kirovilya** [comment]
Хм, странно что он так выведен. Видимо это попытка имитировать xbee модуль и значит не корректно туда заливать прошивку ZNP (которую мы используем).
Мне кажется проще убрать эту (нижнюю) плату и подключаться к известным контактам чипа.

**Comment by kirovilya** [comment]
но попробуй еще поискать
