### ISSUE TITLE
WARN optional SKIPPING OPTIONAL DEPENDENCY

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.zigbee#281]
iobroker | 2019-04-03 15:48:37.953 | info | WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"o
-- | -- | -- | --
iobroker | 2019-04-03 15:48:37.951 | info | WARN bl@0.7.0 requires a peer of stream-browserify@* but none is installed. You must install peer dependencies yourself.npm

Not exactly sure what it means, happened while update...

**Comment by jongear** [comment]
xpc-connection is a Mac platform-specific library. if you are using windows/linux your install will ignore it. xpc-connection does not appear to be maintained anymore. Might I suggest you give [xpc-connect](https://www.npmjs.com/package/xpc-connect) a try which is a fork with added support for Mojave

**Comment by Apollon77** [comment]
Can be ignored because optional dependencies.
