### ISSUE TITLE
Support für INNR RB 265

### ISSUE THREAD

**Issue by Matthias2703** [ioBroker/ioBroker.zigbee#283]
HI,

ich hab ein paar Lampen INNR RB 265. Leider werden diese im Moment noch nicht von iobroker.zigbee unterstützt. 

In der devstates.js fehlt noch die Lampe. Nachdem ich diese dort eingetragen habe:

 {
        vendor: 'Innr',
        models: [
            'RB 265', 'RB 165', 'RB 175 W', 'RS 125', 'RB 178 T', 'RB 145', 'PL 110', 'ST 110', 'UC 110',
            'DL 110 N', 'DL 110 W', 'SL 110 N', 'SL 110 M', 'SL 110 W', 'RS 125'
        ],
        icon: 'img/innr1.png',
        states: lightStates,
        linkedStates: [comb.brightnessAndState],
    },

funktioniert sie auch im iobroker. Leider geht die Änderung natürlich nach jedem Update verloren. Wäre es möglich die Lampe beim nächsten Release mit aufzunehmen?

Vielen Dank

Matthias

**Comment by asgothian** [comment]
should be implemented now.

Please test the current master from GitHub and close this if it works.

A.

**Comment by Matthias2703** [comment]
Thank you very much!
