### ISSUE TITLE
[solved] cannot pair (supported) Eurotronic Thermostat. Please help

### ISSUE THREAD

**Issue by prankousky** [ioBroker/ioBroker.zigbee#289]
Hi everybody,

I read a few days ago that this adapter supports the Eurotronic SPZB0001
(SPZB0001) Spirit Zigbee wireless heater thermostat (temperature, heating system control). I bought one right away because my current solution (eq!Max Thermostats) is awful and I thought it'd be nice to control my heat via zigbee.

The device arrived today. I tried connecting it. When inserting the batteries, it says `PRP` for a second, then goes to `Jin`, which is join mode according to the manual.

I searched for new devices in ioBroker via the search button on the top right corner. Nothing. I then tried to control an `innr` light bulb on this floor to see if there was a problem with connectivity. It worked, so there *is* enough of a signal on this floor. I *then* tried searching **via** that `innr` bulb by using the search button next to it on `instances` -> `zigbee adapter` -> `devices` -> `innr first floor`; I figured this device works as a router anyway, and it is closer to the thermostat, so it ought to work. Did not work, either. I also have a dedicated repeater on this floor. It is pretty much next to the lamp with the innr bulb, but I tried that one as well. No success.

The thermostat itself will stay in `Jin` mode while the little antenna icon keeps flashing. Eventually it will display `ERR`. 

I have attached my ioBroker log, which only displays zigbee adapter relevant details. All those devices listed there have already been connected before. Unfortunately, the thermostat is not one of them. Just a couple of days ago I have added that innr bulb. My adapter version is `0.10.2`. 

Anybody got an idea what might be wrong here? It is also kinda curious that those supposedly `new dev someid LWB010` and `new dev someid RB 285 C` had been connected to the adapter for quite a while! They keep being identified as *new*, but I can both see them in the `objects` section as well as control them; for example, that `RB 285 C` should be the new `innr` bulb I just bought recently. Just while typing this, I tested it by setting it to a different color, which worked without any problems; however, it it were a new device, it would not have been there under it's "old" (correct) name that I gave it when I set it up. Same goes for those other two devices, which are Philips Hue White bulbs that turn on and off every evening, so they are successfully paired as well...

Thanks in advance for your help! 

```
zigbee.0	2019-04-13 16:50:22.269	info	Zigbee: allowing new devices to join.
zigbee.0	2019-04-13 16:49:08.178	info	Zigbee: allowing new devices to join.
zigbee.0	2019-04-13 16:48:55.347	info	new dev someid 60936 RB 285 C
zigbee.0	2019-04-13 16:48:22.424	info	new dev someid 30765 LWB010
zigbee.0	2019-04-13 16:48:03.226	info	new dev someid 29487 LWB010
zigbee.0	2019-04-13 16:46:50.820	info	Zigbee: allowing new devices to join.
zigbee.0	2019-04-13 16:46:43.927	info	21 (someid): RB 285 C - Innr E27 Bulb RGBW (Router)
zigbee.0	2019-04-13 16:46:43.927	info	20 (someid): 8718696449691 - Philips Hue White Single bulb B22 (Router)
zigbee.0	2019-04-13 16:46:43.927	info	19 (someid): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.927	info	18 (someid): MFKZQ01LM - Xiaomi Mi/Aqara smart home cube (EndDevice)
zigbee.0	2019-04-13 16:46:43.927	info	17 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.927	info	16 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.926	info	15 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.926	info	14 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.926	info	13 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.926	info	12 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.926	info	11 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.926	info	10 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.926	info	9 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.925	info	8 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.925	info	7 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.925	info	6 (someid): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.925	info	5 (someid): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.925	info	4 (someid): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.925	info	3 (someid): CC2530.ROUTER - Custom devices (DiY) [CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/) (Router)
zigbee.0	2019-04-13 16:46:43.924	info	2 (someid): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0	2019-04-13 16:46:43.923	info	1 (someid): 8718696449691 - Philips Hue White Single bulb B22 (Router)
zigbee.0	2019-04-13 16:46:43.902	info	zigbee-shepherd ready. version: 2.6.3 rev 20180507
zigbee.0	2019-04-13 16:46:43.892	info	zigbee-shepherd started!
zigbee.0	2019-04-13 16:46:43.305	info	Reset coordinator
zigbee.0	2019-04-13 16:46:43.273	info	Queue is: true
zigbee.0	2019-04-13 16:46:43.273	info	Start on port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___someid-if00 with panID 6754 channel 11
zigbee.0	2019-04-13 16:46:43.262	info	starting. Version 0.10.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v6.17.1
zigbee.0	2019-04-13 16:46:39.926	info	terminating
```

**Comment by allofmex** [comment]
Please stop iobroker, REPLUG cc2531 and try again. It often stops to pair new devices
If it was running for some time.
The Eurotronic works, I repaired my 6 devices just days ago.
What you may also try is holding all three button, then a counter starts and Spz resets.

**Comment by prankousky** [comment]
Thank you so much @allofmex This worked so far (could connect device, but not it throws an error; likely because it wants to adapt and is not connected to the radiator yet).

I will make a note of this, as I have had zigbee devices before that I was unable to connect, and then returned them because I thought they were just incompatible. This trick will save me so much stress in the future :)
