### ISSUE TITLE
Xiaomi wireless switch with less functionality as zigbee2mqtt

### ISSUE THREAD

**Issue by umbm** [ioBroker/ioBroker.zigbee#29]
zigbee2mqtt supports single, double, triple, quadruple click for Xiaomi Aqara wireless switch (WXKG11LM)

With this adapter I only get single and double click objects in iobroker.

Is it possible to enhance the functionality with triple at least?

**Comment by kirovilya** [comment]
@umbm Did you test this button with zigbee2mqtt?
I think this is an error in the description of this button, it does not support triple and quadruple click.
These events are supported only in the WXKG01LM button.

Or I mistake... :)

**Comment by arteck** [comment]
my aqara button suporrted all clicks..
![grafik](https://user-images.githubusercontent.com/6681528/43914334-ebed186c-9c07-11e8-86e6-bc2beea89fcc.png)

its the round button

**Comment by umbm** [comment]
ok, I trusted the description, only tried WXKG11LM (square button) with iobroker.zigbee

**Comment by kirovilya** [comment]
Sorry :( I was wrong. will be in the next release

**Comment by kirovilya** [comment]
Check it in 0.7.1 version

**Comment by umbm** [comment]
It works, thank you!
