### ISSUE TITLE
no pairing without stoping, unplugging, starting again

### ISSUE THREAD

**Issue by prankousky** [ioBroker/ioBroker.zigbee#294]
Hi everybody,

Recently I have had trouble connecting my `Eurotronic` thermostat controllers and asked about this here. I was advised to 

* stop ioBroker
* unplug my CC2531
* plug it back in
* re-start ioBroker

This works, and I was able to connect each device. But I had to do this **each time**! So pair one thermostat, stop, unplug, plug back in, start, *then* connect.

No I have received additional thermostats *and* magnet sensors, which I need to pair. I still cannot do this without going through these steps each time. Which takes a long amount of time.

I have tried to "cheat" by trying to pair four magnet sensors simultaneously, which did not work at all. None of them actually connected (even though output was that one of them did), so I am still at it.

Is this a bug? A hardware error? Too many devices in my network? I have the following

* 1x `CC2531` USB Stick
* 1x `CC2530` Repeater
(I might have those two mixed up, but I got one each)
* 16x `Xiaomi Door/Window Magnet Sensor` (plus 4x still to connect)
* 4x `Xiaomi Temp/Hum/Pres Sensor) (plus some still to connect)
* 2x `Philips Hue White Light Bulb`
* 1x `innr RGB Light Bulb`
* 5x `Eurotronic Thermostat` (plus two still to connect)

Now, I am aware that one controller can only handle *so many* devices. But if I understand correctly, some of those devices (light bulbs for sure) act as repeaters themselves, plus I have a dedicated repeater as well.

Since I can successfully pair after the procedure mentioned above (and as far as I can tell all connected devices work just fine), it seems like all devices can be handled by both the controller and ioBroker. 

I am using the latest stable version of `ioBroker.zigbee`. 

What can I do to fix this? I have **not** had this problem when I first started working with zigbee, but - naturally - I did not use that many devices right to start with (started with just Xiaomi Sensors, then added more).

Thanks in advance for any help to avoid going through all this for each new device that I need to pair :)

**Comment by allofmex** [comment]
I see the same issue. Seems like pairing does not work anymore after stick run for a while (few minutes).

**Comment by prankousky** [comment]
Are there plans to fix this in the future? I mean, I don't pair dozens of devices per day... But it'd be nice to just work when pairing rather than continuously having to go through all these steps...
