### ISSUE TITLE
CC2530 coordinator

### ISSUE THREAD

**Issue by maxpd1** [ioBroker/ioBroker.zigbee#296]
Hi,

my coordinator seems to be ok, because the adapter lights up green. But the CC2530 doesn't receive any signal from any sensor.

I used this tutorial: https://forum.iobroker.net/topic/15503/cc2530-als-coordinator-nutzen

Node: 8.15.1
Node.js: 8.15.1
NPM: 6.4.1
Adapter: 0.10.3

Firmware 23.02.2019

I have 12 devices connected with a CC2531 but range isn't enough. So I decided to exchange the CC2531 with  CC2530.

**Comment by nob0dy80** [comment]
and what is the question?  there is no known problems for cc2530 as router.

**Comment by maxpd1** [comment]
I wanted to use the CC2530 as Coordinator. But even if the zigbee instance is green I receive no signals from the sensor which are in the shepard database and which are working with fine with the CC2531.
