### ISSUE TITLE
again group brightness problem

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.zigbee#299]
Like issue #265, wie are facing again a new brightness group problem after reinstall with latest.
Brightness 0 will turn off, but any value between 1 and 100 wont turn on the light.
if you turn on the light with state, you can adjust the brightness again and turn it off with 0.

"_id": "iobroker.zigbee@0.10.3",
 "_id": "zigbee-shepherd@0.3.0",
_id": "zigbee-shepherd-converters@8.1.5" ..tried also 9.0.5

**Comment by nob0dy80** [comment]
@allofmex 
0.10.3 (allofmex) brightness fix

is this the fix for this issue?

**Comment by nob0dy80** [comment]
ah sorry, no.. i used this one allready.. forget the question. still waiting to fix :)

**Comment by allofmex** [comment]
I hope. Did you tried the latest GitHub version?
For me the groups are working correctly, 0 off, 1- on

**Comment by nob0dy80** [comment]
@allofmex 
not yet. so you did a commit/change to existing 0.10.3 without changing the version? cause i'm allready on 0.10.3.  Then i'll give it a try tomorrow.

**Comment by allofmex** [comment]
No, my pull request longer time ago fixed it for me. And it's still working in recent pre011 test branch

**Comment by nob0dy80** [comment]
@allofmex 
For testing a fix a always reinstall all on a test machine.
Working fine for now with 0.11.2 and altest converters.
lets see how long it takes till @koenkk does the next relevant changes to fuck up all following projects :-D :-D

THANKS for your work.
