### ISSUE TITLE
Zigbee Shepard - 2.6.3 rev 20190223 and Xiaomi Cube no pairing

### ISSUE THREAD

**Issue by JohnyDoe410** [ioBroker/ioBroker.zigbee#300]
Hi,

my xiaomi aqara cube doesn't work anymore. I delete it and want to pair again. After 50 tries and an hour later, i get these messages:

Cannot get the Node Descriptor of the Device: 0x00158d00028f707c (Error: Timed out after 10000 ms)

What can i do? What ist the Problem?

The Other Zigbewe Devices works great in ioBroker

**Comment by nob0dy80** [comment]
thats not a adapter problem... freshly installed all new yesterday and the cube is working fine. maybe your cube is broken.
you can close this issue.

**Comment by JohnyDoe410** [comment]
I have a second, new cube here and i cannot pair it. i think it is an adapter problem, because i cannot pair it.

**Comment by JohnyDoe410** [comment]
Here is the adapter protocol:


  |   |   |  
-- | -- | -- | --
zigbee.0 | 2019-05-13 21:12:49.245 | error | Cannot get the Node Descriptor of the Device: 0x00158d00028f707c (Error: Timed out after 10000 ms)
zigbee.0 | 2019-05-13 21:12:29.239 | error | Cannot get the Node Descriptor of the Device: 0x00158d00028f707c (Error: Timed out after 10000 ms)
zigbee.0 | 2019-05-13 21:11:22.934 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-05-13 21:11:15.194 | error | Join failure.. Error: Timed out after 10000 ms
zigbee.0 | 2019-05-13 21:11:15.051 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-05-13 21:11:05.191 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-05-13 21:10:52.992 | error | Cannot get the Node Descriptor of the Device: 0x00158d00028f707c (Error: Timed out after 10000 ms)
zigbee.0 | 2019-05-13 21:10:31.256 | error | Cannot get the Node Descriptor of the Device: 0x00158d00028f707c (Error: Timed out after 10000 ms)
zigbee.0 | 2019-05-13 21:10:00.689 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-05-13 21:08:01.629 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-05-13 21:06:47.611 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-05-13 21:06:45.687 | error | Error: spawn udevadm ENOENT
zigbee.0 | 2019-05-13 20:59:45.323 | error | Error: spawn udevadm ENOENT
zigbee.0 | 2019-05-13 20:58:34.229 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2019-05-13 20:58:31.070 | error | Error: spawn udevadm ENOENT
zigbee.0 | 2019-05-13 20:56:07.034 | info | Successfully configured 0x7cb03eaa00b1a56f Plug 01
zigbee.0 | 2019-05-13 20:56:05.096 | info | new dev 0x7cb03eaa00b1a56f 49402 Plug 01
zigbee.0 | 2019-05-13 20:55:54.130 | info | new dev 0x7cb03eaa00ac0bbb 46516 Classic A60 W clear - LIGHTIFY
zigbee.0 | 2019-05-13 20:55:28.052 | info | Successfully configured 0x7cb03eaa00b1a56f Plug 01
zigbee.0 | 2019-05-13 20:54:50.400 | info | 18 (0x7cb03eaa00b1a56f): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2019-05-13 20:54:50.400 | info | 17 (0x00158d000272bbaa): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.400 | info | 16 (0x00158d00027d053f): MFKZQ01LM - Xiaomi Mi/Aqara smart home cube (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.399 | info | 15 (0x00158d000232c1ac): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.399 | info | 14 (0x00158d000232c0b0): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.399 | info | 13 (0x00158d000232c17f): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.399 | info | 12 (0x00158d00023870bf): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.399 | info | 11 (0x00158d000232c10f): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.399 | info | 10 (0x00158d0002436400): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.398 | info | 9 (0x00158d000232c18e): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.398 | info | 8 (0x00158d0002387310): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.398 | info | 7 (0x00158d000232c51a): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.398 | info | 6 (0x00158d000232dcbb): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.398 | info | 5 (0x00158d000243640f): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.397 | info | 4 (0x00158d00024354f0): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.397 | info | 3 (0x00158d000232cb9f): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.397 | info | 2 (0x00158d000232dd62): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2019-05-13 20:54:50.395 | info | 1 (0x7cb03eaa00ac0bbb): AC03641 - OSRAM LIGHTIFY LED Classic A60 clear (Router)
zigbee.0 | 2019-05-13 20:54:50.371 | info | zigbee-shepherd ready. version: 2.6.3 rev 20190223
zigbee.0 | 2019-05-13 20:54:50.353 | info | zigbee-shepherd started!
zigbee.0 | 2019-05-13 20:54:49.713 | info | Reset coordinator
zigbee.0 | 2019-05-13 20:54:49.660 | info | Queue is: true
zigbee.0 | 2019-05-13 20:54:49.659 | info | Start on port: /dev/ttyACM0 with panID 6754 channel 11
zigbee.0 | 2019-05-13 20:54:49.628 | info | starting. Version 0.10.3 in /opt/iobroker/node_modules/iobroker.zigbee, node: v8.15.0
zigbee.0 | 2019-05-13 20:54:45.887 | info | zigbee-shepherd stopped
zigbee.0 | 2019-05-13 20:53:23.713 | info | Successfully configured 0x7cb03eaa00b1a56f Plug 01
zigbee.0 | 2019-05-13 20:51:15.487 | error | Zigbee publish to '0x00158d000272bbaa', genBasic - 0 - [{"attrId":16384},{"attrId":3}] - 1 failed with error Error: AF data request fails, status code: 183. APS no ack.
zigbee.0 | 2019-05-13 20:50:57.168 | error | Zigbee publish to '0x00158d000232c1ac', genBasic - 0 - [{"attrId":16384},{"attrId":3}] - 1 failed with error Error: AF data request fails, status code: 183. APS no ack.
zigbee.0 | 2019-05-13 20:50:50.518 | error | Error: spawn udevadm ENOENT
zigbee.0 | 2019-05-13 20:50:35.579 | error | Zigbee publish to '0x00158d00027d053f', genBasic - 0 - [{"attrId":16384},{"attrId":3}] - 1 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the
zigbee.0 | 2019-05-13 20:50:05.143 | error | Error: spawn udevadm ENOENT
zigbee.0 | 2019-05-13 20:48:23.247 | warn | Dev 0x7cb03eaa00b1a56f Plug 01 not configured yet, will try again in latest 300 sec
zigbee.0 | 2019-05-13 20:48:22.104 | info | new dev 0x7cb03eaa00b1a56f 49402 Plug 01

**Comment by nob0dy80** [comment]
ok hold on, just for, i delete one of mine now and try to pair it again, i'm using the latest adapter.

**Comment by nob0dy80** [comment]
New device joined 0x00158d00029a8fd5 model lumi.sensor_cube
Interview state: step 3/3. progress: 100%
Interview state: step 3/3. progress: 75%
Interview state: step 3/3. progress: 50%
Interview state: step 3/3. progress: 25%
Interview state: step 2/3. progress: 100%
Interview state: step 2/3. progress: 75%
Interview state: step 2/3. progress: 50%
Interview state: step 2/3. progress: 25%
Interview state: step 1/3. progress: 100%
Interview state: step 1/3. progress: 83%
Interview state: step 1/3. progress: 67%
Interview state: step 1/3. progress: 50%
Interview state: step 1/3. progress: 33%


Worked on the first try. Not an adapter fault.

**Comment by nob0dy80** [comment]
Cannot get the Node Descriptor of the Device: 0x00158d00028f707c (Error: Timed out after 10000 ms)
--


this is ALWAYS (ok lets say 99%) device problem. to far away from pairing point or broken

**Comment by JohnyDoe410** [comment]
Is it possible that the zigbee shepard 2.6.3 firmware with this date is the problem?

Is ist possible that 2 cubes are broken? One i use the other i open today.

**Comment by nob0dy80** [comment]
normaly not. but please show me your network map. maybe there are two many enddevices connected to a router device so its just simply "full".

**Comment by JohnyDoe410** [comment]
Hi,

the last days, i take off the battery from my two cubes and today, i try it again. trhe same Problem with the new cube.

Here you see my network map and the last connect of my old cube.

I think i have an idea. Is it possible, that the batteries on both devices are not good enough? i buy two devices, but i used only one devices for month. the new device i don't get of the package, but the battery ist on.

But both are blicking blue, when i press the link button. and after it blicking i press the link button every 1-2 seconds. Is it right?


Best Regards,
JohnyDoe410
