### ISSUE TITLE
GL-B-008Z / missing Saturation Channel / missing Light Mixing (white with color)

### ISSUE THREAD

**Issue by snador1977** [ioBroker/ioBroker.zigbee#301]
The GL-B-008Z lamp lacks the channel for saturation. There are 3 channels. 1: Brightness (dimmer 1-100), 2: Color (RGB / HEX) and 3: Color temperature for white light (0-500 / cold to warm). But there is no channel for the color saturation of the colored light. A feature that most RGBW controllers bring with them. And finally - there is currently no way to mix white light (no matter which light color) with proportions of colored light. Also a feature that most RGBW Stripe have.

**Comment by snador1977** [comment]
Is there an idea somewhere? Where is the mistake? What can I do?

**Comment by kirovilya** [comment]
Unfortunately, I do not have this device.
https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L2404
Therefore, focusing on the library of converters, I see that only features like this are added to this device: brightness, color, temperature.
https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L69

Additionally, there is a light_alert mode. But how to use another white channel - I can not undestand. Maybe someone else can.

**Comment by snador1977** [comment]
Will it help if I send you a device / hardware?
