### ISSUE TITLE
 getDevices error: {}

### ISSUE THREAD

**Issue by andre1974** [ioBroker/ioBroker.zigbee#303]
Hello,

my Zigbee adapter has lost his groups. They are not anymore in the objects.
When i open the instance i see no devices and get  "getDevices error: {}" in log.
The devices can still be controlled by the objects tab and Alexa.

Before that happened i updated the following adapters...

Iot, Discovery.

System updates were done as follows shortly before...

samba-vfs-modules amd64 2:4.5.16+dfsg-1+deb9u2 [361 kB]
samba-dsdb-modules amd64 2:4.5.16+dfsg-1+deb9u2 [329 kB]
python-samba amd64 2:4.5.16+dfsg-1+deb9u2 [1360 kB]
libsmbclient amd64 2:4.5.16+dfsg-1+deb9u2 [151 kB]
samba-libs amd64 2:4.5.16+dfsg-1+deb9u2 [5231 kB]
libwbclient0 amd64 2:4.5.16+dfsg-1+deb9u2 [124 kB]
samba amd64 2:4.5.16+dfsg-1+deb9u2 [934 kB]
samba-common-bin amd64 2:4.5.16+dfsg-1+deb9u2 [603 kB]
samba-common all 2:4.5.16+dfsg-1+deb9u2 [174 kB]
linux-libc-dev amd64 4.9.168-1+deb9u2 [1422 kB]

![Zwischenablage01](https://user-images.githubusercontent.com/11474126/57843771-27bacd00-77cf-11e9-954b-d6510c4f82dd.jpg)

![Zwischenablage02](https://user-images.githubusercontent.com/11474126/57843993-7cf6de80-77cf-11e9-91cb-4f84a882db6c.jpg)

![Zwischenablage03](https://user-images.githubusercontent.com/11474126/57844244-f55d9f80-77cf-11e9-9dac-c8436ae4ac3d.jpg)

**Comment by ToIObroker** [comment]
Hi Andre,

Could you fix the issue?
I am struggeling with the same one.

![image](https://user-images.githubusercontent.com/51965247/60034471-0640e100-96ab-11e9-97f8-f4e4a6e74482.png)

Regards

**Comment by derAndyk** [comment]
hello,  since today i got the same issue. 
yesterday everything as working fine. 
i added only one osram plug which i tested and worked. 
now i wanted to check something on the zigbee config site and saw all was empty.
i switched to log and saw many errors:  getDevices error: {}

**Comment by RichieXX** [comment]
Same issue here. Pairing and control objects works.

**Comment by kirovilya** [comment]
Can you run adapter until error in debug mode logging and attach log here?

**Comment by linuxq** [comment]
I have the same problem (devices appear in objects and work, but nothing in the device list or network chart in the settings). Here is my log:
`

zigbee.0 | 2019-08-20 21:54:33.364 | info | Successfully configured 0x7cb03eaa0a01252a Plug 01
-- | -- | -- | --
zigbee.0 | 2019-08-20 21:54:33.069 | info | Successfully configured 0x7cb03eaa00b0a114 Plug 01
zigbee.0 | 2019-08-20 21:54:31.757 | error | getDevices error: {}
zigbee.0 | 2019-08-20 21:54:31.655 | info | new dev 0x7cb03eaa00b0a114 65003 Plug 01
zigbee.0 | 2019-08-20 21:54:08.927 | error | getDevices error: {}
zigbee.0 | 2019-08-20 21:52:26.904 | warn | Dev 0x0017880103cac563 RWL021 not configured yet, will try again in latest 300 sec
zigbee.0 | 2019-08-20 21:51:48.361 | info | Successfully configured 0x7cb03eaa00ae7470 Plug 01
zigbee.0 | 2019-08-20 21:51:48.185 | info | Successfully configured 0x7cb03eaa0a00eaf3 Plug 01
zigbee.0 | 2019-08-20 21:51:45.820 | info | Successfully configured 0xd0cf5efffe212db7 TRADFRI remote control
zigbee.0 | 2019-08-20 21:51:38.271 | info | Successfully configured 0x7cb03eaa0a0162da Plug 01
zigbee.0 | 2019-08-20 21:51:36.542 | info | new dev 0x7cb03eaa0a0162da 49197 Plug 01
zigbee.0 | 2019-08-20 21:51:29.564 | info | new dev 0x7cb03eaa0a01252a 44788 Plug 01
zigbee.0 | 2019-08-20 21:50:26.503 | error | Cannot get the Node Descriptor of the Device: 0x7cb03eaa0a0162da (Error: request unsuccess: 16)
zigbee.0 | 2019-08-20 21:50:26.245 | error | Cannot get the Node Descriptor of the Device: 0x7cb03eaa0a01252a (Error: request unsuccess: 17)
zigbee.0 | 2019-08-20 21:49:26.536 | error | Cannot get the Node Descriptor of the Device: 0x7cb03eaa0a0162da (Error: request unsuccess: 16)
zigbee.0 | 2019-08-20 21:49:26.246 | error | Cannot get the Node Descriptor of the Device: 0x7cb03eaa0a01252a (Error: request unsuccess: 17)
zigbee.0 | 2019-08-20 21:48:46.395 | warn | Dev 0x0017880103cac563 RWL021 not configured yet, will try again in latest 300 sec
zigbee.0 | 2019-08-20 21:48:46.395 | warn | Dev 0xd0cf5efffe212db7 TRADFRI remote control not configured yet, will try again in latest 300 sec
zigbee.0 | 2019-08-20 21:48:26.532 | error | Cannot get the Node Descriptor of the Device: 0x7cb03eaa0a01252a (Error: request unsuccess: 17)
zigbee.0 | 2019-08-20 21:48:26.443 | warn | Dev 0x7cb03eaa00ae7470 Plug 01 not configured yet, will try again in latest 300 sec
zigbee.0 | 2019-08-20 21:48:08.496 | info | Successfully configured 0x7cb03eaa00a751c5 Plug 01
zigbee.0 | 2019-08-20 21:47:57.479 | info | Successfully configured 0x7cb03eaa0a0162da Plug 01
zigbee.0 | 2019-08-20 21:47:57.234 | info | Successfully configured 0x7cb03eaa00b0a114 Plug 01
zigbee.0 | 2019-08-20 21:47:26.058 | info | 12 (0xd0cf5efffe212db7): E1524/E1810 - IKEA TRADFRI remote control (EndDevice)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 11 (0x7cb03eaa00b0a114): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 10 (0x0017880103cac563): 324131092621 - Philips Hue dimmer switch (EndDevice)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 9 (0x7cb03eaa0000244f): 4052899926110 - OSRAM Flex RGBW (Router)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 8 (0x7cb03eaa0a00eaf3): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 7 (0x7cb03eaa00ae7470): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 6 (0x7cb03eaa00a751c5): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 5 (0x000b57fffe931b01): LED1650R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 4 (0x000b57fffe846170): LED1650R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router)
zigbee.0 | 2019-08-20 21:47:26.058 | info | 3 (0x000b57fffe897f45): LED1650R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router)
zigbee.0 | 2019-08-20 21:47:26.057 | info | 2 (0x7cb03eaa0a01252a): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2019-08-20 21:47:26.057 | info | 1 (0x7cb03eaa0a0162da): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2019-08-20 21:47:26.031 | info | Shepherd ready. {"state":"Coordinator","channel":"11","panId":6754,"extPanId":[221,221,221,221,221,221,221,221],"ieeeAddr":"0x00124b0019367a7d","nwkAddr":0}
zigbee.0 | 2019-08-20 21:47:26.031 | info | Zigbee-shepherd ready. Firmware version: 2.6.3 rev 20190608
zigbee.0 | 2019-08-20 21:47:25.978 | info | zigbee-shepherd started!
zigbee.0 | 2019-08-20 21:47:24.315 | info | Reset coordinator
zigbee.0 | 2019-08-20 21:47:24.315 | info | Queue is: true
zigbee.0 | 2019-08-20 21:47:24.315 | info | Start on port: /dev/ttyACM0 channel 11
zigbee.0 | 2019-08-20 21:47:24.313 | info | starting. Version 0.11.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v8.16.0

`

**Comment by kirovilya** [comment]
Please try to update js-controller to 1.5.* and newer.
It's too hard to reproduce this error for me...

**Comment by kirovilya** [comment]
Replace [732 line in main.js](https://github.com/ioBroker/ioBroker.zigbee/blob/master/main.js#L732) from:
`                adapter.log.error('getDevices error: ' + JSON.stringify(err));`
to:
`                adapter.log.error('getDevices error: ' + err.stack));`
and show logs
