### ISSUE TITLE
Prepare for 0.11

### ISSUE THREAD

**Issue by kirovilya** [ioBroker/ioBroker.zigbee#304]
Hi to all. @arteck @Apollon77 @asgothian @allofmex 
Let's try the dev version 0.10.999 https://github.com/ioBroker/ioBroker.zigbee/tarball/dev
I updated to the last zigbee-shepherd that works with z-stack 3.0 (by the way, I checked on the latest firmware 3.0.2 from Koen)
and latest converters 9.0.10
and serialport 7.1.15

Next, will be necessary to complement existing devices and new ones.

**Comment by nob0dy80** [comment]
@kirovilya 
do you get you right, by updating the adapter and flashing the stick to z-stack 3.0, a repairing of all devices has to be done?

**Comment by kirovilya** [comment]
I think yes.
I tried the ZS3 on a test installation and connected new devices.
I do not think that we need a move for the stick CC2531 from ZS1.2 to ZS3 - this is more for the new equipment CC265 * and CC2538, where there is more memory.

so, we test not only zs3, but new zigbee-shepherd and converters

**Comment by nob0dy80** [comment]
@kirovilya 
well there will be bugs often, since so many changes on the converter.
Maybe you recognized my latest report.
https://github.com/ioBroker/ioBroker.zigbee/issues/299
got that after a fresh reinstall where i tried converters 9.0.5.

you cant fix it as fast as Koen changes things :-)

**Comment by arteck** [comment]
@kirovilya thx for the info

**Comment by kirovilya** [comment]
@nob0dy80 I checked the work of the groups on the dev-branch. I have 2 lamps in the group (IKEA, JIAWEN) - they work correctly: they turn off at brightness 0, turn on at brightness 1-100.
maybe it depends on the lamp?

**Comment by kirovilya** [comment]
There is one useful change in the latest version of the zigbee-shepherd, which probably solves the problem of the freezing of some devices while controlling them (for example, a gledopto)

**Comment by kirovilya** [comment]
Someone besides me tried to use the dev version? everything works for me.

**Comment by Apollon77** [comment]
Sorry, I  don't had time so far. was busy with js-controller topics and other stuff … :-(

**Comment by allofmex** [comment]
Me too, no time to test yet. Sorry

**Comment by J-Paul0815** [comment]
привет Ilya,
I have installed your adapter version 0.10.999 in a test environment.
So if something does not work, that does not bother me.

Zigbee TI LaunchPad CC26X2R1 Chip Revision E
Koenkk Z-Stack-firmware/coordinator/Z-Stack_3.x.0
Windows10 x64, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz, RAM 7.69 GB
Node.js v10.16.0 NPM 6.9.0
ioBroker.js-controller OS: win32 1.5.11

Good news first: 
It works
I was able to pair a Xiaomi door sensor and an Osram switch socket. 
The objects were created normally. Status of the sensor works and also the switch on and off.
The system is now stable for several hours.

But:
The menu items in the adapter Device, Groups, Network Card, Analysis are completely empty.
In Settings COM4 Network ExtPanID DDDDDD PanID 6754 Channel 11 Security Transportation Key 32 digit numbers-letters combination

Please do not hesitate to contact me if I can test, or try something.
If you are interested I will send you the log.

**Comment by kirovilya** [comment]
@J-Paul0815 this is great news.
Can you show the pictures that is not displayed? and put logs here if there are errors

**Comment by J-Paul0815** [comment]
Here we go. Thanks for your work. Please say if I can do more.
[Zigbee_log.txt](https://github.com/ioBroker/ioBroker.zigbee/files/3236861/Zigbee_log.txt)
![1](https://user-images.githubusercontent.com/51191964/58631355-9bd29600-82e2-11e9-84c1-4acf0112c7e3.JPG)
![2](https://user-images.githubusercontent.com/51191964/58631366-9ffeb380-82e2-11e9-964a-f17edd8a5637.JPG)

**Comment by MerleHH** [comment]
and the objects have little pictures
![3](https://user-images.githubusercontent.com/48625290/58631744-c83ae200-82e3-11e9-9836-5ab4e8571dec.JPG)

**Comment by J-Paul0815** [comment]
and the objects have little pictures
![3](https://user-images.githubusercontent.com/51191964/58631841-13ed8b80-82e4-11e9-8d96-d182dc66595d.JPG)

**Comment by kirovilya** [comment]
@J-Paul0815 by the logs - it means nothing works :)

"TypeError: adapter.getEnumsAsync is not a function" - it means something is wrong with your js-controller.
Show what version of the controller do you have?

**Comment by J-Paul0815** [comment]
it´s:
ioBroker.js-controller OS: win32 1.5.11

**Comment by J-Paul0815** [comment]
But I try update from js-controller:
![4](https://user-images.githubusercontent.com/51191964/58632853-2fa66100-82e7-11e9-8fc6-97ae5f9071c7.JPG)

**Comment by kirovilya** [comment]
@J-Paul0815 hmm. This functionality (getEnumsAsync) appeared a long time ago and should work correctly.
how does it work now? what in logs?

**Comment by J-Paul0815** [comment]
Everything looks good. Am I mistaken, or is it fast?
[4.txt](https://github.com/ioBroker/ioBroker.zigbee/files/3237033/4.txt)

**Comment by kirovilya** [comment]
@J-Paul0815 all is ok in logs now :)

**Comment by J-Paul0815** [comment]
@kirovilya 
[zigbee_log2.txt](https://github.com/ioBroker/ioBroker.zigbee/files/3241470/zigbee_log2.txt)
[Blockly_export.txt](https://github.com/ioBroker/ioBroker.zigbee/files/3241473/Blockly_export.txt)


After one day, mistakes have come up. And again: It's just a test system just to try. It does not bother, but may help you. I'm testing with a script that turns on/off the power when the status of the sensor changes. Even if errors appear in the LOG, the function is usually still available, but no longer reliable. Maybe still problems in the young firmware for the CC26X2R1?

**Comment by kirovilya** [comment]
the error indicates the instability of the zigbee-network. It seems that the problem is in the firmware for the new chip cc26x2, which seems to be not yet stable.

**Comment by allofmex** [comment]
I tried latest dev branch, but it fails at https://github.com/ioBroker/ioBroker.zigbee/blob/4ea0fb05cf197177b97ec2d39138e00c2ed1c89b/main.js#L982
`forEach not a function`
Seems to be (sometimes?) an Object!? I had this when writing brightness to a (group of) bulb.

(test with latest github shepherd and converter, switched back to older adapter but kept new shepherd/converter and it works again)

**Comment by kirovilya** [comment]
@allofmex in version 9 of converters, an array should be returned here, so there is no check for the object. What device causes such an error?

**Comment by allofmex** [comment]
>  version 9 of converters

You were right. It still used 8. Tricky to make sure, nodejs using the intended version. :-/
I added a new log entry in https://github.com/ioBroker/ioBroker.zigbee/pull/308
`Lib-Versions: ZShepherd 0.3.0, ZSConverters 8.1.0`
That may help to detect such issues more easily in future.

**Comment by kirovilya** [comment]
@allofmex ok, merged

**Comment by kirovilya** [comment]
I think we can merge into the master and released.
Any objections?

**Comment by kirovilya** [comment]
merged to master and closed dev-branch

**Comment by kirovilya** [comment]
published

**Comment by kirovilya** [comment]
After the release of 0.11.0, an unpleasant situation arose. Some users had to re-pair their devices with the coordinator. I think because now they are specifying extpanid and security key.
Did someone have the same problems?
:( I am very sad

**Comment by kirovilya** [comment]
found a bug :(
