### ISSUE TITLE
Xiaomi lumi.sensor_switch.aq2 - Button states are empty

### ISSUE THREAD

**Issue by DoraDeu** [ioBroker/ioBroker.zigbee#310]
This is about the Xiaomi button (without gyro) that has the id "WXKG11LM " in the zigbee2mqtt converter.

Since a change in the converter the states of the data points "single", "double", "triple" and "quadruple" are empty in ioBroker.
Just the  states for battery, link_quality and voltage are shown properly and get updated.

**Comment by arteck** [comment]
check plz now

**Comment by DoraDeu** [comment]
I would love to do. Is it just in the development branch or how can I access it?

**Comment by arteck** [comment]
plz re-pair the button and check again

**Comment by DoraDeu** [comment]
Where are the fixes included? Do I have to install that latest stable or any other version?

**Comment by capitaenz** [comment]
I have successfully paired the "lumi.sensor_switch" with version 0.10.2 and 0.11.2.
Stable with the 0.10.2 - I just tested the 0.11.2 and I had to repaire the switch once.
Try to restart the Zigbee-Adapter!

**Comment by nob0dy80** [comment]
yeah no problem with that.pls close
