### ISSUE TITLE
Can't add Tradfri-bulbs to iot

### ISSUE THREAD

**Issue by DanielHD80** [ioBroker/ioBroker.zigbee#311]
Hello,

I have a problem with the connection between the Zigbee-adapter and the iot-adapter. I have created various Tradfri bulbs (GU10 and E27) and can control them in the objects-tree. But as soon as I want to add them manually into the iot-adapter, I only get an error message when selecting the Brightness parameter

"zigbee.0.000b57fffe32c002.brightness" not exists or no native part.

**Comment by KaiNW** [comment]
Facing the same issue here

**Comment by kirovilya** [comment]
try last iot from github

**Comment by KaiNW** [comment]
Got it to work by giving it write permissions for "everyone", in objects and states.

**Comment by KaiNW** [comment]
Reopening the issue. After a reinstallation of ioBroker, and setting read write permissions the same issue reoccurs even in the iot adapter, while doing the same in the cloud adapter just outputs nothing.

**Comment by Schimi1983** [comment]
i´ve the same issue..... a fix would be great....

all other objects or stats works with the iot adapter
