### ISSUE TITLE
Hue Motion Sensor Daylight sensitivity and Motion sensitivity

### ISSUE THREAD

**Issue by Hambootje** [ioBroker/ioBroker.zigbee#312]
Hi,

Is there a way to set the Daylight sensitivity and Motion sensitivity of a Hue motion sensor via the zigbee adapter?

Kind Regards, 
Berry

**Comment by kirovilya** [comment]
I do not known how.

**Comment by allofmex** [comment]
I will do this as soon as I find time. Tried it before already. Changing of setting worked, I just could not see any clear effect of the settings, that's why I did not add it as of now.

@Hambootje Did you saw any change in behavior of this settings (on hue bridge for example)?

**Comment by Hambootje** [comment]
Unfortunately I do not have a hue bridge to test this. I use all my zigbee devices directly with the zigbee adapter. I would be happy to test if these settings have any effect on the sensitivity. At the moment my hue sensor is so sensitive to change in daylight that it triggers every time there moves a cloud before the sun.

Another observation regarding the hue sensor.... Every time motion is detected, the internal LED is flashing red. According the manual this means there is no connection with the hue bridge. Obviously this is correct as I don't use the hue bridge. It is annoying though, because it draws attention to the sensor when it's dark outside. Is there a possibility to turn this LED off during motion detection?

**Comment by allofmex** [comment]
I added sensitivity setting. It will be available after zigbee-shepherd-converters was updated.

My internal LEDs are flashing orange on motion detected (on zigbee.adapter as well). Red only if sensor is offline, then it does not work at all.
I tried the ledindication setting mentioned [here](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Philips-Hue-sniffing). The value changes (0 + 1), but it doesn't make a difference. LED still flashes.
Suggest: use a non-transparent sticker to cover led..

Daylight sensitivity is not a setting on sensor. You need to interpret the illumination value according to your needs in your scripts.

**Comment by Hambootje** [comment]
How do I get the zigbee adapter where the sensitivity is added?
I tried reinstalling the adapter from github. I do now have a newer version (0.11.2) but I cannot see the sensitivity option added to the SML002 motion sensor.

**Comment by allofmex** [comment]
It should work if you are really using the github version. You may check the devstates.js file in your lib folder, it should have this line
https://github.com/ioBroker/ioBroker.zigbee/blob/57d8ecc2b4409741539c2cd9df5cfbc08cb04c5d/lib/devstates.js#L2623 
(check for the `states.sml_sensitivity` part at the end)
