### ISSUE TITLE
Pairing Issue OSRAM Classic E27 Multicolor

### ISSUE THREAD

**Issue by ToIObroker** [ioBroker/ioBroker.zigbee#316]
Hi all,

I could not find any solution to fix the issue with the OSRAM Classic E27 Multicolor.
I could pair different sensors from Xiaomi and an OSRAM plug, but I still do have issues to fully pair the LED.

The type code is CLA60 RGBW Z3. Is this a new firmware due to the Z3? I could not find any information about the Z3.

Please have a look at the following picture.

![59701251-7821b200-91f5-11e9-92b3-44988c5d55db](https://user-images.githubusercontent.com/51965247/59748392-4e12d300-927b-11e9-856e-ec8775d7eb52.png)

I use the zigbee2mqtt adapter, which I could find in iobroker. It is from kirovilya; version 0.11.0. 
What ist the difference to 
"arteck/ioBroker.zigbee forked from ioBroker/ioBroker.zigbee"

Thanks in advance.

Regards
ToIObroker

**Comment by kirovilya** [comment]
Hi. Just added your bulb model to adapter. Try installing the adapter from github and check

**Comment by ToIObroker** [comment]
Thanks for your fast response.
I will check it this evening or tomorrow morning.

Am I right, that I have to remove the whole zigbee2mqtt adapter and install it completely new?

**Comment by kirovilya** [comment]
Did you mean iobroker.zigbee and not zigbee2mqtt?
iobroker.zigbee you can just upgrade from github (https://github.com/ioBroker/ioBroker.zigbee) without deleting

**Comment by ToIObroker** [comment]
Sorry for confusing. I meant iobroker.zigbee.
I have just started and I am not that common with those names/versions.
Ok I will check and let you know.

Thanks, again!

**Comment by ToIObroker** [comment]
I just checked it and it is now working. Well done, thank you for your fast support.

One general question. I could not update it in iobroker adapter. it showed I am using 0.11.0 and could downgrade to 0.10.2. - I completely removed the adapter and installed it new on basis of the github link.
