### ISSUE TITLE
ibroker.zigbee as client of zibee2mqtt

### ISSUE THREAD

**Issue by kirovilya** [ioBroker/ioBroker.zigbee#317]
I am thinking about the topic: to realize the possibility of connecting the z2m service to the ioBroker.zigbee as to an MQTT-server.
This will be a separate mode of operation of the adapter, without using a serial port, but working on a mqtt. Parsing topics to separate states and back...

what do you think?

**Comment by Apollon77** [comment]
What would be the benefit compared to just use the MQTT adapter in iobroker if someone wants it that way?

**Comment by kirovilya** [comment]
It is like sonoff-adapter. in the project z2m objects come to topics and it need to be decomposed into state-attributes

**Comment by Apollon77** [comment]
So you want to convert all the MQTT stuff into the same objects and states like you would have with serialport mode?! Understood

But again: what would be the benefit?

**Comment by kirovilya** [comment]
yes.

The advantage in the possibility of using the service z2m. It is more developed than our adapter - I do not keep up with all its innovations.
Also, this theoretically allows you to start using some devices that are added to the z2м, but not added in our adapter.
In fact, it’s just from the grip of time to innovate the zigbee-adapter :(

**Comment by Apollon77** [comment]
Would not be an idea to change adapter to use z2m under the hood somehow?

**Comment by kirovilya** [comment]
Yes, there is such an idea.
but for now z2m is not a library. there it must also be rewritten.

**Comment by Apollon77** [comment]
:-(

**Comment by allofmex** [comment]
> connecting the z2m service to the ioBroker.zigbee as to an MQTT-server.

It would produce lots of overhead, resulting in extra delays. Not my preferred solution..

> Also, this theoretically allows you to start using some devices that are added to the z2м, but not added in our adapter.

I see your point. Wouldn't it be a good idea to move the additional data we have in devstates.js  to zigbee-shepherd-converter? (data types, data range, ...) That way there would not be a need anymore to add devices to zigbee adapter after they were added in converter. All device information could be extracted from converter. And zigbee2mqtt benefits too because it could generate it's docs as well from this data.

**Comment by arteck** [comment]
@allofmex 
> It would produce lots of overhead, resulting in extra delays. Not my preferred solution..

this is my opinion also.. we have today 2 mqtt adapters.. the user has one program more what he has to install und update (manually)

the merge idea with shepherd-converter is better..

**Comment by kirovilya** [comment]
I also thought about moving the device descriptions to converters. But...
In contrast to z2m, we need to split the messages received from the converters into separate attributes (states in iob). So, in addition to descriptions of devices, we still have to make a description of the attributes.
Or to have on our side the correspondence of converters and a set of attributes for basic cases (such as light bulbs, dimmers) and look for new devices at a set of converters.
