### ISSUE TITLE
lumi.sensor_motion.aq2

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#319]
Hi all, I check for a change of brightness larger x within a time frame and even though I cover the sensor and see the value change in the object list the blockly script gets old values. So basically the script doesn#t register a change - even though it should.

Additionally I try to trigger on movement but the script doesn't execute.

**Comment by arteck** [comment]
script problem ... my sensor warks fine..

**Comment by daniel-lo** [comment]
Always my first assumption. But at least witht he brightness script I am doubtful. Everything looks good .. but if I cover the sensor during the timout the value doesn't change according to debug. The object is updated though. Maybe you (someone) finds the time to skim through this:

![blockly](https://user-images.githubusercontent.com/4311558/60071602-011b7a80-971b-11e9-84b7-c798e822ff77.png)
![2019-06-25_07-29-20 bewegung](https://user-images.githubusercontent.com/4311558/60071606-04166b00-971b-11e9-9431-2248d5e63e31.png)
