### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by kirovilya** [ioBroker/ioBroker.zigbee#324]
- [x] move from zigbee-shepherd to zigbee-herdsman https://github.com/Koenkk/zigbee-herdsman and drop support nodejs 6 :(
- [x] binding
- [ ] rewrite readme
- [ ] support external coordinators (mqtt-or-other-services like z2m)

**Comment by SchumyHao** [comment]
Waiting for this version! Pairing Xiaomi device makes me mad :(

**Comment by kirovilya** [comment]
:) 'herdsman' branch of this repo... alpha version... you can try but without guarantee :)

**Comment by kirovilya** [comment]
You can try to install from git https://github.com/ioBroker/ioBroker.zigbee/tarball/herdsman and test... 
![image](https://user-images.githubusercontent.com/8360230/68645488-405f3200-0529-11ea-88c9-2483ff0f19fb.png)
basic functions working

**Comment by SchumyHao** [comment]
Hi @kirovilya 
herdsman has released 0.12.5, which contains a break update that can connect to dongle though tcp socket https://github.com/Koenkk/zigbee-herdsman/commit/4807db27b5d56663475a29438b3fffa389eff1e0
Please consider merge this feature into iobroker.zigbee.
This well help a lot of user who use ESP as serial2wifi.

**Comment by kirovilya** [comment]
@SchumyHao you can try now :)

**Comment by SchumyHao** [comment]
![image](https://user-images.githubusercontent.com/4982108/68876103-e46df680-073e-11ea-8e67-97d4c63bab2d.png)

Gread work!
