### ISSUE TITLE
Unknown device model Gardenspot RGB

### ISSUE THREAD

**Issue by capitaenz** [ioBroker/ioBroker.zigbee#325]
I have pairied Osram Garden spot RGB, but I get the error message "Unknown device model Gardenspot RGB", if I want to control something.
Deleting the device is no longer possible, I can then delete "Gardenspot RGB", but then get a "?" with the same serial number and after a few minutes "Osram Gardenspot RGB" is back.
I use 0.11.2.

`

zigbee.0 | 2019-07-08 17:07:56.012 | error | Unknown device model Gardenspot RGB
-- | -- | -- | --
zigbee.0 | 2019-07-08 17:07:56.011 | error | Unknown device model Gardenspot RGB
zigbee.0 | 2019-07-08 17:07:43.299 | info | new dev 0x7cb03eaa00xxxxxx 36669 Flex RGBW
zigbee.0 | 2019-07-08 17:07:34.701 | info | new dev 0x7cb03eaa00xxxxxx 55346 Flex RGBW
zigbee.0 | 2019-07-08 17:07:26.045 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genLevelCtrl","data":{"offTransitionTime":0,"defaultMoveRate":255}}
zigbee.0 | 2019-07-08 17:07:25.471 | info | new dev 0x84182600000xxxxxx 51764 Gardenspot RGB
zigbee.0 | 2019-07-08 17:07:24.888 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genLevelCtrl","data":{"offTransitionTime":0,"defaultMoveRate":255}}
zigbee.0 | 2019-07-08 17:07:23.845 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genLevelCtrl","data":{"offTransitionTime":0,"defaultMoveRate":255}}
zigbee.0 | 2019-07-08 17:07:22.843 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genLevelCtrl","data":{"offTransitionTime":0,"defaultMoveRate":255}}
zigbee.0 | 2019-07-08 17:07:22.805 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genLevelCtrl","data":{"offTransitionTime":0,"defaultMoveRate":255}}
zigbee.0 | 2019-07-08 17:07:22.569 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genLevelCtrl","data":{"currentLevel":254,"remainingTime":0,"onOffTransitionTime":0,"onLevel":255,"onTransitionTime":0}}
zigbee.0 | 2019-07-08 17:07:22.293 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genOnOff","data":{"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}}
zigbee.0 | 2019-07-08 17:07:22.009 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genScenes","data":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}}
zigbee.0 | 2019-07-08 17:07:21.757 | error | Unknown device model Gardenspot RGB emit event readRsp with data:{"cid":"genGroups","data":{"nameSupport":0}}
zigbee.0 | 2019-07-08 17:07:21.468 | error | Unknown device model Gardenspot RGB emit event readRsp with data:{"cid":"genIdentify","data":{"identifyTime":0}}
zigbee.0 | 2019-07-08 17:07:21.134 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genBasic","data":{"modelId":"Gardenspot  RGB","dateCode":"20140331CNEF****","powerSource":1,"deviceEnabled":1,"swBuildId":"V1.0
zigbee.0 | 2019-07-08 17:07:20.940 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genBasic","data":{"zclVersion":1,"appVersion":1,"stackVersion":2,"hwVersion":1,"manufacturerName":"OSRAM"}}
zigbee.0 | 2019-07-08 17:07:20.390 | error | Unknown device model Gardenspot RGB emit event readRsp with  data:{"cid":"genBasic","data":{"zclVersion":1,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20140331CNEF****","swBuildId":"V1.0

`
What can I do?

**Comment by captaindork** [comment]
I have some Gardenspots for quite some years, but used them with lightify Adapter and Gateway. I tried to connect them now to zigbee adapter as I want to get rid of the GW. Long Story Short: I am experiencing the same... Any further Logs we can deliver?

**Comment by capitaenz** [comment]
I lost my desire for the CC2531 stick and bought the Conbee II from Dresden Elektronik.
There is also an adapter at ioBroker and everything works as it should.
No more trouble.

**Comment by captaindork** [comment]
Thx, also moved to conbee...

**Comment by capitaenz** [comment]
Yes, everything is still running perfectly with the Conbee!
