### ISSUE TITLE
Is this OSRAM Smart+ Plug still supported?

### ISSUE THREAD

**Issue by joerghildering** [ioBroker/ioBroker.zigbee#326]
I want to use it as a router.

https://www.amazon.de/Osram-schaltbare-fernbedienbar-Lichtsteuerung-kompatibel/dp/B074PZLX2P/ref=sr_1_1_sspa?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=osram+smart+plug&qid=1563134984&s=gateway&sr=8-1-spons&psc=1

**Comment by allofmex** [comment]
Yes, it's supported.

(Note: I experience network issues with this and some other devices, see https://github.com/Koenkk/zigbee2mqtt/issues/1474)
