### ISSUE TITLE
b286acn01 not all states available

### ISSUE THREAD

**Issue by Batista156** [ioBroker/ioBroker.zigbee#327]
Hello,

when I add a new Xiaomi b286acn01 swich I don't get any available event, I only get the single button event but I don't get the double or the long press event.

**Comment by chhofi** [comment]
zigbee2mqtt supports multi-button-press for the  lumi.remote.b286acn01 xiomi buttons. Maybe this feature can be ported to ioBroker.zigbee as well?

**Comment by kirovilya** [comment]
already in the code, but the version is not released.
can install from github

**Comment by chhofi** [comment]
Great! Thx for the fast reply.
