### ISSUE TITLE
Node 4 failed

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.zigbee#33]
Can it bee, that Node 4 support is broken?
https://travis-ci.org/ioBroker/ioBroker.zigbee/jobs/415308100#L1031

If yes, please remove node4 from tests.

**Comment by kirovilya** [comment]
I have seen. I not found where the error yet. But I will find.

**Comment by GermanBluefox** [comment]
https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L40

**Comment by kirovilya** [comment]
hmm... Thank you. 
Rewrite to function?

**Comment by kirovilya** [comment]
Ah! I undestand - default value!
Thank you!

**Comment by kirovilya** [comment]
Fixed https://travis-ci.org/ioBroker/ioBroker.zigbee/builds/415399505
