### ISSUE TITLE
Changing Channel > CC2531 failed to start up

### ISSUE THREAD

**Issue by kugelkopf123** [ioBroker/ioBroker.zigbee#330]
Hey!

I tried to change the Channel within the preferences of the Zigbee Adapter in ioBroker. But if i do, if i change it to anything other than 11 it stops working.

Im sorry but i cant present you any Logs in the Moment, because I've borrowed the Stick to a friend to check if its the same with his RaspberryPi. And it is.
When i get it back, i could post some logs.

On the Stick is the newest FW. (CC2531_DEFAULT_20190608).
Zigbee Adapter: 0.11.2
nodejs 10

Perhaps someone could try this and see if its the same?

**Comment by kirovilya** [comment]
What in logs?

**Comment by kugelkopf123** [comment]
> What in logs?

Sorry, still dont got my Stick back. The friend of mine have an issue that he had to restart the Raspi almost every day.  Got a picture of his log today. But that has nothing to do with the channel problem, because he uses Ch11.
Hope that i met him today to get my zigbeestick back.

![58574494924__A5E0FBE1-307F-4529-A01D-5637469F9197](https://user-images.githubusercontent.com/45996965/61913943-0a2c8100-af3f-11e9-88a1-9da286f5599f.JPG)

**Comment by kirovilya** [comment]
I see that it can not open the port, maybe something is wrong with the rights or the user is not added to the dialup group

**Comment by kugelkopf123** [comment]
> I see that it can not open the port, maybe something is wrong with the rights or the user is not added to the dialup group

Ok, I have told him. But now he is at work. So hes going to try it tomorow. And back to Topic: I've my Stick back.

Log with Zigbee Adapter set to Ch6:
![Bildschirmfoto 2019-07-26 um 17 56 43](https://user-images.githubusercontent.com/45996965/61965072-b158f900-afcf-11e9-8262-33788205e946.png)
![Bildschirmfoto 2019-07-26 um 17 57 52](https://user-images.githubusercontent.com/45996965/61965089-bae26100-afcf-11e9-9b26-bcb8e053c1fe.png)


If you enter the Preferences from the Zigbee Adapter you get this Popup: 
![Bildschirmfoto 2019-07-26 um 17 56 31](https://user-images.githubusercontent.com/45996965/61965136-d188b800-afcf-11e9-8db7-8dd7239c5c76.png)

If I set it back to Ch11: 
Everything works... No popup dialog.
![Bildschirmfoto 2019-07-26 um 17 59 09](https://user-images.githubusercontent.com/45996965/61965180-ea916900-afcf-11e9-8239-080b05df749e.png)

**Comment by kirovilya** [comment]
Channels may be from 11 to 26 only :)
![image](https://user-images.githubusercontent.com/8360230/62025426-cce71e00-b1e0-11e9-858c-4e044a1c7b99.png)

**Comment by kugelkopf123** [comment]
> Channels may be from 11 to 26 only :)
> ![image](https://user-images.githubusercontent.com/8360230/62025426-cce71e00-b1e0-11e9-858c-4e044a1c7b99.png)

Oh! I didn't know this! That works. But it would be nice, if you cant select a lower Ch than 11. That would prevent those mistakes. Thanks!
