### ISSUE TITLE
IoBroker->selector does not work

### ISSUE THREAD

**Issue by Nahasapeemapetilon** [ioBroker/ioBroker.zigbee#331]
Hi,
`$('state[id=zigbee.0.00158d0002913a38.*]').each((id,i)=>{log(id)});`
does not return any elements, on other ID which didn't come from the Zigbee adapter it works
without a problem.
I restarted all adapters and scripts but it didn't work too.
![image](https://user-images.githubusercontent.com/16188935/61610997-ef19f280-ac5a-11e9-8d12-ae5716c55a02.png)

`{
  "type": "state",
  "common": {
    "name": "Battery percent",
    "type": "number",
    "unit": "%",
    "read": true,
    "write": false,
    "role": "battery.percent",
    "min": 0,
    "max": 100,
    "icon": "img/battery_p.png"
  },
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1562097482513,
  "_id": "zigbee.0.00158d0002c8d185.battery",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}`

**Comment by MubiTec** [comment]
I had the same problem, but there is an easy way to solve it.
Go to each datapoint, goto into it's settings and then to raw. Write something and delete it, so in the end you want change anything.
Now you save and close the settings. 
Now the selector will find it.
