### ISSUE TITLE
No device pairing possible after update 

### ISSUE THREAD

**Issue by crxo1** [ioBroker/ioBroker.zigbee#332]
Hello,

i'm using 5 aqara temperature sensors and one osram smart plug for one year without problems with this module. After one temperature sensor won't report actual temps back, i changed the battery and tried to reconnect it without luck. After deleting all devices, resetting and reinstalling the adapter and updating iobroker, no device will succeed to connect. The adapter is green and when trying to connect a device, simply nothing happens. This is my log:

`

zigbee.0 | 2019-07-23 18:49:06.394 | info | Zigbee: allowing new devices to join.
-- | -- | -- | --
zigbee.0 | 2019-07-23 18:38:43.182 | info | Shepherd ready. {"state":"Coordinator","channel":"11","panId":6754,"extPanId":[221,221,221,221,221,221,221,221],"ieeeAddr":"0x00124b0018ed3d99","nwkAddr":0}
zigbee.0 | 2019-07-23 18:38:43.180 | info | Zigbee-shepherd ready. Firmware version: 2.6.3 rev 20180815
zigbee.0 | 2019-07-23 18:38:43.173 | info | zigbee-shepherd started!
zigbee.0 | 2019-07-23 18:38:41.603 | info | Reset coordinator
zigbee.0 | 2019-07-23 18:38:41.543 | info | Queue is: true
zigbee.0 | 2019-07-23 18:38:41.542 | info | Start on port: /dev/ttyACM0 channel 11
zigbee.0 | 2019-07-23 18:38:41.508 | info | starting. Version 0.11.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v6.17.1
zigbee.0 | 2019-07-23 18:38:37.490 | info | terminating

`

How could this be fixed? Thanks in advance!

**Comment by kirovilya** [comment]
Try to change channel to 15 for example
