### ISSUE TITLE
Tradfri E1745

### ISSUE THREAD

**Issue by dergutebott** [ioBroker/ioBroker.zigbee#335]
Unfortunately the new Ikea Motion Sensor is not working. Type E1745. The old one which works is not sold in Germany anymore. Could you please make the new one work? Thank you!

**Comment by monarc83** [comment]
Any chance that E1745 will be supported as well soon?

**Comment by chr-jordan** [comment]
would be nice to use the new motion sensor in iobroker.zigbee

**Comment by oswaldo-be** [comment]
as discussed [here](https://github.com/ioBroker/ioBroker.zigbee/issues/375)

**Comment by chr-jordan** [comment]
![Bildschirmfoto_2020-01-05_07-53-47](https://user-images.githubusercontent.com/44375264/71776359-8c11e300-2f90-11ea-84e9-8d066b6bc83c.png)
Have paired the Tradfri E1745 with pressing on the Tradfri E1745 the connection key  in center 4 times instantly. Now I am puzzling with the  objectvalues. "Battery" an "link_quality" are fine but value for "last_motin" an "occupancy" (see picture) never got a status. Same behaviour for adapter version 11.5 and 1.0.0-c. Btw devicepicture is the one of E1525.

**Comment by Gwoony** [comment]
Does the E1745 motion detector have an Illuminance value like the Aqara Motion Detectors?

**Comment by chr-jordan** [comment]
![IMG_20200105_1057551](https://user-images.githubusercontent.com/44375264/71778182-c9836a00-2faa-11ea-9da2-f2dae3da46cd.jpg)
I can't tell for sure. As the manual says it has according to the left buttons with the two symbols (sun, moon) dark and bright environment trigger options. On the other hand the right button seems to be irrelevant as it signalizes only the two states short and long for direct paired lights. I didn't get into the zigbee specs to understand the zigbee-device-parameters yet..

**Comment by Gwoony** [comment]
I didn't notice any difference in the behavior of the left button

**Comment by Gwoony** [comment]
Does the sensor have a stable connection with you? 
Mine five keep losing connection

**Comment by chr-jordan** [comment]
sensor works fine for me now with the new coordinator firmware as a motion detector, very stable in a relatively nearby coordinator/bridge (3m). There is no illuminance value in objects.
