### ISSUE TITLE
New Shutter Device. Doesn`t work. Please Help

### ISSUE THREAD

**Issue by Jeba0815** [ioBroker/ioBroker.zigbee#338]
I have a new Zigbee shutter Touch switch.
is displayed as an unknown device.

Model HGZB 4D UK
Protocol: Zigbee 3.0

Device unknown in the Zigbee adapter: FNB56 - ZBW01LX1.2

![IMG_3040 (002)](https://user-images.githubusercontent.com/51450022/62808843-9327e880-baf9-11e9-8518-3b2436341a2d.jpg)
![IMG_3038](https://user-images.githubusercontent.com/51450022/62808844-9327e880-baf9-11e9-8021-5919ac508241.jpg)
![IMG_3039](https://user-images.githubusercontent.com/51450022/62808845-9327e880-baf9-11e9-88c2-0cbf497ea2d0.jpg)

**Comment by kirovilya** [comment]
I cannot help you quickly, because our device database does not have your device (model FNB56-ZBW01LX1.2).
https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js

Run the adapter in debug logging mode and record the log of button clicks. Attach it here
