### ISSUE TITLE
invert state for lumi.sensor_magnet

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#34]
for iobroker we need a configurable state for lumi.sensor_magnet
magnet close = false
magnet open = true 

or 

magnet close = true
magnet open = false 

i think in admin we can make a checkbox for this

**Comment by kirovilya** [comment]
already exists in dev version

**Comment by arteck** [comment]
ok

**Comment by kirovilya** [comment]
check it please

**Comment by arteck** [comment]
where is it?

**Comment by kirovilya** [comment]
In 0.7.1, state 'isopen' for magnet :)

**Comment by arteck** [comment]
lol..works
