### ISSUE TITLE
New Osram Device. Doesn`t work.

### ISSUE THREAD

**Issue by Sebastian3009** [ioBroker/ioBroker.zigbee#340]
I have a new Zigbee Bulb.
Is displayed as an unknown device.

OSRAM SMART+ spot GU5.3 tunable white (on/off, brightness, color temperature)

Please fix this, Thank You!!
<img width="803" alt="Bildschirmfoto 2019-08-12 um 18 56 10" src="https://user-images.githubusercontent.com/54037056/62882824-fea8ca80-bd32-11e9-935b-40cc896db0ca.png">

**Comment by Sebastian3009** [comment]
<img width="1032" alt="Bildschirmfoto 2019-08-12 um 19 19 01" src="https://user-images.githubusercontent.com/54037056/62884156-19c90980-bd36-11e9-88d7-cff1ea8892ac.png">

This in the log of IoBroker

**Comment by Sebastian3009** [comment]
Thank you very much for the update!!
Greetings

**Comment by Sebastian3009** [comment]
<img width="1536" alt="Bildschirmfoto 2020-01-25 um 17 35 22" src="https://user-images.githubusercontent.com/54037056/73124282-eb648100-3f99-11ea-9a81-3e3430cd8995.png">

My Bulbs Osram Smart+ spot GU5.3 doesn't work with Version 1.0.1.
I can't downgrade to 0.11.3.

Please fix this, Thank You!

**Comment by arteck** [comment]
del and add the device to actual adapter
