### ISSUE TITLE
Osram Device with modelID 'Plug Z3' is not supported?

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/ioBroker.zigbee#342]
Osram Smart Plug x4918 Plug Z3

**Comment by ma-john** [comment]
This helped to recognize Osram Z3 with me (and great assistance from iobroker forum) for iobroker
change file  /opt/iobroker/node_modules/iobroker.zigbee/lib/devastates.js 
line: models: ['PAR 16 50 RGBW - LIGHTIFY'], 
into line: models: ['PAR 16 50 RGBW - LIGHTIFY','PAR16 RGBW Z3'], 
then it will be correctly recognized and shown under adapters (incl. correct pic)
Open item here: ON/OFF, Dim and White value (cold-->warm white) works fine, but I can NOT change the RGB color. The object indicates a change (like 296,96,67) after playing with colors in the line level.color.rgb in 'habpanel VIS' but the bulb does not change color.
