### ISSUE TITLE
Umzug von Raspi 2 auf Raspi 4: Zigbee-Adapter Problem

### ISSUE THREAD

**Issue by Nuggelbeb** [ioBroker/ioBroker.zigbee#343]
Hallo,
als Smarthome Anfänger, habe ich, nach meinem Umzug auf den neuen Raspberry 4 leider ein Problem.
Alle Adapter funktionieren super nur der Zigbee Stick macht Probleme. Die LED des Sticks ist dauerhaft grün. Im ioBroker bleibt der Adapter ständig gelb.
In den Einstellungen des Adapters - COM Anschluss - habe ich
"/dev/serial/by-id/usb Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00193B0727-if00"
eingetragen.
Auf dem Raspberry 2 lief der Stick einwandfrei.
Kann mir jemand helfen?

Infos:
Hard-/Software
---------------------------------------------------------------------------------------------------------
Rasperry pi4 4Gb
Zigbee Stick CC2531
node -v
v10.16.3
nodejs -v
v10.16.3
npm -v
6.10.3
Zigbee Adapter Version
0.11.2

ls -la /dev/serial/by-id/
---------------------------------------------------------------------------------------------------------
insgesamt 0
drwxr-xr-x 2 root root 60 Aug 18 09:59 .
drwxr-xr-x 4 root root 80 Aug 18 09:59 ..
lrwxrwxrwx 1 root root 13 Aug 18 09:59 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00193B0727-if00 -> ../../ttyACM0

Log des Zigbee Adapter
---------------------------------------------------------------------------------------------------------
zigbee.0	2019-08-18 11:06:56.491	debug	User stateChange zigbee.0.info.connection {"val":false,"ack":false,"ts":1566119216477,"q":0,"from":"system.adapter.zigbee.0","user":"system.user.admin","lc":1566114867335}
zigbee.0	2019-08-18 11:06:56.490	debug	User stateChange zigbee.0.info.pairingMessage {"val":"Error: Error while starting zigbee-shepherd!. Error: Error Resource temporarily unavailable Cannot lock port","ack":false,"ts":1566119216475,"q":0
zigbee.0	2019-08-18 11:06:56.490	error	Error while starting zigbee-shepherd!. Error: Error Resource temporarily unavailable Cannot lock port
zigbee.0	2019-08-18 11:06:51.444	info	Starting zigbee-shepherd
zigbee.0	2019-08-18 11:05:51.437	info	Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds)
zigbee.0	2019-08-18 11:05:48.373	debug	system.adapter.admin.0: logging true
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:47.449	debug	system.adapter.admin.0: logging false
zigbee.0	2019-08-18 11:05:46.384	info	Reset coordinator
zigbee.0	2019-08-18 11:05:46.384	info	Lib-Versions: ZShepherd 0.3.0, ZSConverters 10.2.3
zigbee.0	2019-08-18 11:05:46.384	info	Queue is: true
zigbee.0	2019-08-18 11:05:46.384	info	Start on port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00193B0727-if00 channel 23
zigbee.0	2019-08-18 11:05:46.384	info	starting. Version 0.11.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.16.3
host.raspberrypi	2019-08-18 11:05:45.220	info	instance system.adapter.zigbee.0 started with pid 30500
host.raspberrypi	2019-08-18 11:05:45.219	info	object change system.adapter.zigbee.0
host.raspberrypi	2019-08-18 11:05:44.381	info	Do not restart adapter system.adapter.zigbee.0 because disabled or deleted
host.raspberrypi	2019-08-18 11:05:44.381	error	instance system.adapter.zigbee.0 terminated with code 7 (Adapter already running)

**Comment by Andreas-W-S** [comment]
Same issue
