### ISSUE TITLE
TRÅDFRI Bulb 1732G11 1000lm 11W

### ISSUE THREAD

**Issue by lhoem** [ioBroker/ioBroker.zigbee#344]
Hello, 

today I bought a TRÅDFRI Bulb LED1732G11 1000lm 11W in a complete set at IKEA. The lamp was paired by Zigbee. However, it does not appear in the object manager. I think this is a new version and will be updated. Is this lamp compatible in future?
Regards
lhoem

**Comment by kuersche1337** [comment]
Same goes for me -.-

**Comment by Jonfried92** [comment]
same for me, but i can't even the lampe

**Comment by Jonfried92** [comment]
This bulb is officially supported by the project zigbee2mqtt.

Maybe you can copy from there ?

Thanks.

**Comment by Narolakk** [comment]
You have to add a few lines in three files, then it works fine!

**Comment by Jonfried92** [comment]
Bei mir hat die Anpassung bei der LED1732G11 funktioniert.
Die files liegen hier:

devstates.js
/opt/iobroker/node_modules/iobroker.zigbee/lib/devstates.js

devices.js
/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd-converters/devices.js

Vielen dank für den Tipp.

**Comment by martinez81** [comment]
> 
> 
> Bei mir hat die Anpassung bei der LED1732G11 funktioniert.
> Die files liegen hier:
> 
> devstates.js
> /opt/iobroker/node_modules/iobroker.zigbee/lib/devstates.js
> 
> devices.js
> /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd-converters/devices.js
> 
> Vielen dank für den Tipp.

Das Verzeichnis der Datei "devices.js" hat bei mir nicht gestimmt.
Bei mir ist die devices.js in folgenden Verzeichnis:
/opt/iobroker/node_modules/zigbee-shepherd-converters/devices.js

Kleine Erklärung für Leute die evtl. noch Schwierigkeiten haben:
SSH Verbindung über ein Terminal zum iobroker aufbauen -> einfach mal google.
Im Terminal (Verbindung mit den Raspberry, oder was auch immer steht):
`sudo nano /opt/iobroker/node_modules/iobroker.zigbee/lib/devstates.js`

Strg-W "Wo ist" drücken und z.B. "TRADFRI" eingeben -> Enter
Jetzt eine passende Lampe raussuchen. (brightness, evtl. colortemp)
Wenn man eine passende Stelle gefunden hat kann man bei "models" einfach mit ein Komma den neuen richtigen Namen der Lampe am Ende hinzufügen.
Den richtigen Namen der Lampe bekommt man, wenn man die Lampe mit dem Zigbee-Adapter verbindet, dieser meldet zwar dann unbekanntes Gerät, aber der Name wird angezeigt.

Strg-X für Beenden und J für speichern.

Das gleiche muss man bei der anderen Datei auch noch machen.
`sudo nano /opt/iobroker/node_modules/zigbee-shepherd-converters/devices.js`

Ich habe dann die noch unbekannten Lampen wieder gelöscht und neu verbinden.
Fertig!

**Comment by JorinL** [comment]
This seems still not merged to the current version?
My LED1732G11 has no state for lightcolor/ct.
