### ISSUE TITLE
Tradfri LED1624G9: Colortemp not working

### ISSUE THREAD

**Issue by btiegel** [ioBroker/ioBroker.zigbee#348]
Hi,
i wanna use Tradfri LED1624G9 with the zigbee adaoter via the cc2531 stick.
I can pair the Bulb and state, dimmer and color works without problems.
But i cant use the 'colortemp' .
In the Log i see the following  entry:
" No converter available for 'LED1624G9' with key 'colortemp' "

**Comment by ma-john** [comment]
Hi,
same Report with Osram plus plug. 
No converter available for 'AC08559' with key 'color' when I changed rgb color which shows in iobroker in the object itself.

**Comment by klotzma** [comment]
I have the same Problem, i can't chance the colortemp!
In my log comes the error:
`No converter available for 'LED1624G9' with key 'colortemp'`
