### ISSUE TITLE
Hue motion sensitivity

### ISSUE THREAD

**Issue by Arek2k3** [ioBroker/ioBroker.zigbee#349]
Wenn beim Hue Outdoor Sensor die Empfindlichkeit unter Objekte geändert wird, stürzt der Zigbee Adapter ab.

host.raspberrypi | 2019-09-02 22:24:01.995 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2019-09-02 22:24:01.994 | error | instance system.adapter.zigbee.0 terminated with code 0 (OK)
Caught | 2019-09-02 22:24:01.994 | error | by controller[0]:     at Endpoint.ep.foundation  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd/lib/shepherd.js:625:25)
Caught | 2019-09-02 22:24:01.993 | error | by controller[0]:     at ZShepherd._foundation  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd/lib/shepherd.js:737:20)
Caught | 2019-09-02 22:24:01.993 | error | by controller[0]:     at Object.af.zclFoundation  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd/lib/components/af.js:263:25)
Caught | 2019-09-02 22:24:01.993 | error | by controller[0]:     at Object.zcl.frame (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/zcl.js:66:78)
Caught | 2019-09-02 22:24:01.992 | error | by controller[0]:     at FoundPayload.frame  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/foundation.js:111:21)
Caught | 2019-09-02 22:24:01.992 | error | by controller[0]:     at Array.forEach (<anonymous>)
Caught | 2019-09-02 22:24:01.991 | error | by controller[0]:     at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/foundation.js:112:22
Caught | 2019-09-02 22:24:01.991 | error | by controller[0]:     at FoundPayload._getBuf  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/foundation.js:171:25)
Caught | 2019-09-02 22:24:01.990 | error | by controller[0]:     at Array.forEach (<anonymous>)
Caught | 2019-09-02 22:24:01.990 | error | by controller[0]:     at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/foundation.js:176:27
Caught | 2019-09-02 22:24:01.988 | error | by controller[0]: Error: Payload of commnad: write must have attrData property.
zigbee.0 | 2019-09-02 22:24:01.905 | error | at Endpoint.ep.foundation (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd/lib/shepherd.js:625:25)
zigbee.0 | 2019-09-02 22:24:01.905 | error | at ZShepherd._foundation (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd/lib/shepherd.js:737:20)
zigbee.0 | 2019-09-02 22:24:01.905 | error | at Object.af.zclFoundation  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-shepherd/lib/components/af.js:263:25)
zigbee.0 | 2019-09-02 22:24:01.905 | error | at Object.zcl.frame (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/zcl.js:66:78)
zigbee.0 | 2019-09-02 22:24:01.905 | error | at FoundPayload.frame (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/foundation.js:111:21)
zigbee.0 | 2019-09-02 22:24:01.905 | error | at Array.forEach (<anonymous>)
zigbee.0 | 2019-09-02 22:24:01.905 | error | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/foundation.js:112:22
zigbee.0 | 2019-09-02 22:24:01.905 | error | at FoundPayload._getBuf (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/foundation.js:171:25)
zigbee.0 | 2019-09-02 22:24:01.905 | error | at Array.forEach (<anonymous>)
zigbee.0 | 2019-09-02 22:24:01.905 | error | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zcl-packet/lib/foundation.js:176:27
zigbee.0 | 2019-09-02 22:24:01.905 | error | Error: Payload of commnad: write must have attrData property.
zigbee.0 | 2019-09-02 22:24:01.904 | error | uncaught exception: Payload of commnad: write must have attrData property.
zigbee.0 | 2019-09-02 22:23:55.625 | info | new dev 0x0017880106465fb4 52045 SML002

**Comment by allofmex** [comment]
> Wenn beim...

Nächstes Mal bitte in Englisch!

This was my fault, converter was changed to use `low/medium/high` instead of ioBrokers `0 - 2` values and I didn't got the effect for us.

I created a PR https://github.com/Koenkk/zigbee-shepherd-converters/pull/593 to allow both.
(We stay with numbers instead of strings, because this is what will be read from device.)

Change should work in ioBroker as soon as @kirovilya switches to comming shepherd-converter version (>10.2.4, not released yet)
