### ISSUE TITLE
OSRAM PLUG Z3 (undefined) 0.11.3

### ISSUE THREAD

**Issue by snador1977** [ioBroker/ioBroker.zigbee#358]
Hi, is undefined:

```
zigbee.0 | 2019-09-17 18:20:57.421 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"lightLink","data":{"65533":1}}
-- | -- | -- | --
zigbee.0 | 2019-09-17 18:20:57.188 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"haDiagnostic","data":{"65533":1,"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":255,"lastMessageRssi":-56}}
zigbee.0 | 2019-09-17 18:20:56.821 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genOnOff","data":{"65533":1,"onOff":0}}
zigbee.0 | 2019-09-17 18:20:56.577 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genScenes","data":{"65533":1,"lastCfgBy":"0xffffffffffffffff"}}
zigbee.0 | 2019-09-17 18:20:56.454 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genScenes","data":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}}
zigbee.0 | 2019-09-17 18:20:56.198 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genGroups","data":{"65533":1,"nameSupport":0}}
zigbee.0 | 2019-09-17 18:20:55.957 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genIdentify","data":{"65533":1,"identifyTime":0}}
zigbee.0 | 2019-09-17 18:20:55.725 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genBasic","data":{"65533":1,"modelId":"Plug Z3","dateCode":"Sep 12 2018\u0000\u0000\u0000\u0000\u0000","powerSource":1,"swBuildId":"0
zigbee.0 | 2019-09-17 18:20:55.586 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genBasic","data":{"zclVersion":2,"appVersion":1,"stackVersion":2,"hwVersion":1,"manufacturerName":"LEDVANCE"}}
zigbee.0 | 2019-09-17 18:20:55.283 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genBasic","data":{"zclVersion":2,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"Sep 12 2018\u0000\u0000\u0000\u0000\u0000"
zigbee.0 | 2019-09-17 18:20:55.119 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genBasic","data":{"manufacturerName":"LEDVANCE","modelId":"Plug Z3","powerSource":1}}

```

**Comment by ma-john** [comment]
check my post to solve the Z3 issue. You have to manually add the Z3 in  
/opt/iobroker/node_modules/iobroker.zigbee/lib/devastates.js

**Comment by snador1977** [comment]
It is not the Osram Z3 RGB Device. Its the Osram Z3 Plug. For this device your changes have no effect...

**Comment by BoBeRzE** [comment]
Same Problem here:

`

zigbee.0 | 2019-09-20 15:28:57.421 | info | new dev 0xf0d1b800001256a9 3769 Plug Z3
-- | -- | -- | --
zigbee.0 | 2019-09-20 15:28:51.125 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"lightLink","data":{"65533":1}}
zigbee.0 | 2019-09-20 15:28:50.226 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genOnOff","data":{"65533":1,"onOff":0}}
zigbee.0 | 2019-09-20 15:28:49.624 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genGroups","data":{"65533":1,"nameSupport":0}}
zigbee.0 | 2019-09-20 15:28:49.123 | error | Unknown device model Plug Z3 emit event devChange with data:{"cid":"genBasic","data":{"zclVersion":2,"appVersion":1,"stackVersion":2,"dateCode":"Sep 12 2018\u0000\u0000\u0000\u0000\u0000"}}
zigbee.0 | 2019-09-20 15:28:49.119 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genBasic","data":{"zclVersion":2,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"Sep 12 2018\u0000\u0000\u0000\u0000\u0000"
zigbee.0 | 2019-09-20 15:28:48.923 | error | Unknown device model Plug Z3 emit event devChange with data:{"cid":"genBasic","data":{"manufacturerName":"LEDVANCE","modelId":"Plug Z3","powerSource":1}}
zigbee.0 | 2019-09-20 15:28:48.920 | error | Unknown device model Plug Z3 emit event readRsp with data:{"cid":"genBasic","data":{"manufacturerName":"LEDVANCE","modelId":"Plug Z3","powerSource":1}}

`

**Comment by snador1977** [comment]
Is this currently a problem that can be solved? In terms of time ... Or do technical conditions make implementation impossible?
