### ISSUE TITLE
adapter red after node.js update

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#359]
Hi, I updated node.js to the recommended version .. could somebody please help me with the command to resurrect my adapter. I'm afraid if I mess around myself I'll have to re-pair everything.

`

host.ioBroker | 2019-09-19 15:33:25.509 | error | instance system.adapter.zigbee.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/lib/linux.js:1:36)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at bindings (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/bindings/bindings.js:112:48)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at require (internal/modules/cjs/helpers.js:25:18)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]: NODE_MODULE_VERSION 57. This version of Node.js requires
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]: was compiled against a different Node.js version using
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]: Error: The module  '/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/build/Release/bindings.node'
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:         ^
Caught | 2019-09-19 15:33:25.509 | error | by controller[0]:         throw e;
Caught | 2019-09-19 15:33:25.508 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.zigbee/node_modules/bindings/bindings.js:121

`

**Comment by daniel-lo** [comment]
./reinstall.sh fixed it :-)

**Comment by Vaskes1986** [comment]
Hello, could you provide more information how you solved this problem?
