### ISSUE TITLE
Danalock V3 BTZB *** Problem: keine Zustandsanzeige

### ISSUE THREAD

**Issue by Nuggelbeb** [ioBroker/ioBroker.zigbee#360]
Hallo,
kann mir bitte jemand helfen? 

**Ich habe:**
- einen Raspberry 4 mit ioBroker
- Zigbee Adapter V 0.11.3
- einen Zigbee Stick CC2531
- und ein neu gekauftes Danalock V3 BTZB

Die Kopplung mit Zigbee funktionierte wunderbar. Der Batteriezustand, Verbindungsqualität und die Schließfunktion werden mir angezeigt, aber eine exakte Statusmeldung für offen oder zu fehlt.

**Meine Fragen:**
- Liegt dies am Adapter?
- Gibt es eine Möglichkeit die exakte Statusmeldung für ioBroker vom Danalock zu empfangen?
Dies wäre für die Aktivierung eines ioBroker Prozesses wichtig.

Danke im Voraus.

**Comment by stream2me** [comment]
In der aktuellen Version funktioniert die Statusanzeige noch nicht. Das hatte ich damals noch nicht richtig hinbekommen.
Wenn du die Anpassungen wie [hier](https://github.com/ioBroker/ioBroker.zigbee/pull/356) vornimmst dann läuft es aber.

**Comment by Nuggelbeb** [comment]
Ok, Danke. Aber ich bin leider ein Anfänger. 
Wo soll die Datei "devstates.js" hin?

Danke

**Comment by stream2me** [comment]
Du kannst die Datei aus meinem Repo zum testen nehmen. Die findest du [hier](https://raw.githubusercontent.com/stream2me/ioBroker.zigbee/patch-1/lib/devstates.js).
Die musst du dann im Installationspfad des Zigbee Adapters auf deinen Raspberry austauschen. Vorher am besten den Adapter anhalten.
Bei mir liegt die hier: /opt/iobroker/node-modules/iobroker.zigbee/lib

**Comment by Nuggelbeb** [comment]
@stream2me 
Super, super, super. Du hast die Harmonie zwischen meiner Frau und mir gerettet. Ich hatte erst vor kurzem ein Danalock, welches nicht funktionierte, dann kaufte ich mir ein zweites, der Zylinder noch dazu und schon war eine Summe für meine Frau zusammengekommen, wo sie ausrastete. Dummerweise funktionierte die Zuschaltung (lockstatus) für die Alarmanlage nicht. Naja dieses Theater. Erklärung hatte ich auch keine.

ABER: Jetzt kamst du, mit der rettenden Antwort. Ich bin dir sowas von dankbar. Wenn du in meiner Nähe wärst, würde ich gleich ein Bierfass mit dir leer machen. SUPER. Es funktioniert, keine Investition umsonst. Nochmals meinen Dank. Möge es der Herr dir vergelten.
Viele Grüße

DANKE!!!

**Comment by Nuggelbeb** [comment]
Hallo ich bins nochmal.
Habe gerade festgestellt, dass das Schalten des Schlosses über locked, unlocked nicht funktioniert.
Dieser Datenpunkt (lockState) ist jetzt nur noch eine Statusanzeige und kein Schaltpunkt mehr.

**Comment by stream2me** [comment]
Wie im [PR](https://github.com/ioBroker/ioBroker.zigbee/pull/356) beschrieben funktioniert das Schließen über lock/unlock.

**Comment by Nuggelbeb** [comment]
Danke für die schnelle Antwort.
Ok, das mit dem lock / unlock habe ich verstanden, aber ich habe in meinen Blockly Skript einen Befehl steuere lockState mit lock / unlock gesetzt, aber das funktionierte nicht. Also habe ich in den Objekten lock / unlock direkt eingegeben und über den Haken bestätigt, aber das Schloss zeigte keine Reaktion. Wenn ich es dann wiederum über das Handy geschalten habe, wurde der Zustand im lockState korrekt angezeigt.

Also ich bin der Meinung, zwei Datenpunkte wären besser, da man die Steuerung separat gegenüber dem Status verknüpfen kann. Ich weiß ja nicht, wie die Anderen denken. Ich persönlich habe zur Zeit viel mit Zustandsaktoren programmiert, damit war ich unabhängig und konnte sie immer anderweitig zur Abfrage nutzen.
