### ISSUE TITLE
New Ikea symfonisk Remote Controller

### ISSUE THREAD

**Issue by plbartek89** [ioBroker/ioBroker.zigbee#361]
Hello , new ikea Symfonisk Remote Controller is out. 
[PIC](https://images.ifun.de/wp-content/uploads/2019/09/sonos-schalter.jpg)
It supports : 
1xClick , 2xclick , 3xClick and Rotate.
Any plans to implement this one ?
I have two of them, if I can help somehow just report.

**Comment by asgothian** [comment]
Can you provide a link to where to get this ? I was unable to find it. Are you certain this will be zigbee, as the symfonisk speakers are WLAN speakers.

A.

**Comment by plbartek89** [comment]
yes , its zigbee 
https://www.ikea.com/fr/fr/manuals/symfonisk-telecommande-volume__AA-2160937-1_pub.pdf

**Comment by Againstyou** [comment]
Im interested in this too. :) It would be great if you can add support for these.

**Comment by Againstyou** [comment]
Sorry for repost: But it looks like Koenkk/Zigbee2MQTT supports this Controller now. If you can port this to this repo it would be awesome. :)

https://github.com/Koenkk/zigbee-herdsman-converters/commit/1039b89249c59d4bca4a3bcb27f666e79e94d2e8
