### ISSUE TITLE
Zigbee didn´t work in Admin 3.6.5 and Zigbee 0.11.3

### ISSUE THREAD

**Issue by Peter1980FFM** [ioBroker/ioBroker.zigbee#362]
Hello,
since i Upgrade the Zigbee to 0.11.3 the Adaper dont work...
![image](https://user-images.githubusercontent.com/45266139/65613971-1ec8dc00-dfb7-11e9-8e87-6e1f3a212887.png)
 And now the LOG

host.ioBroker-Pi | 2019-09-25 17:03:59.709 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.ioBroker-Pi | 2019-09-25 17:03:59.709 | error | instance system.adapter.zigbee.0 terminated with code 1 ()
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/lib/index.js:14:22)
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at require (internal/module.js:11:18)
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at Module.require (module.js:597:17)
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at Function.Module._load (module.js:498:3)
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at tryModuleLoad (module.js:506:12)
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at Module.load (module.js:566:32)
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at Module._compile (module.js:653:30)
host.ioBroker-Pi | 2019-09-25 17:03:59.708 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/lib/linux.js:1:98)
host.ioBroker-Pi | 2019-09-25 17:03:59.707 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/bindings/bindings.js:126:9)
host.ioBroker-Pi | 2019-09-25 17:03:59.707 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/lib/binding/node-v57-linux-arm/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.707 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.707 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.707 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.707 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/compiled/8.16.1/linux/arm/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.707 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/build/default/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.707 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/Release/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.706 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/out/Release/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.706 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/Debug/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.706 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/out/Debug/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.706 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/build/Release/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.706 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/build/Debug/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.706 | error | Caught by controller[0]: → /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/build/bindings.node
host.ioBroker-Pi | 2019-09-25 17:03:59.706 | error | Caught by controller[0]: Error: Could not locate the bindings file. Tried:
host.ioBroker-Pi | 2019-09-25 17:03:59.705 | error | Caught by controller[0]: ^
host.ioBroker-Pi | 2019-09-25 17:03:59.705 | error | Caught by controller[0]: throw err;
host.ioBroker-Pi | 2019-09-25 17:03:59.704 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.zigbee/node_modules/bindings/bindings.js:135
host.ioBroker-Pi | 2019-09-25 17:03:58.126 | info | instance system.adapter.zigbee.0 started with pid 10403

**Comment by Apollon77** [comment]
Please install again and post install log

**Comment by Peter1980FFM** [comment]
$ ./iobroker add zigbee  --host ioBroker-Pi
host.ioBroker-Pi create instance zigbee
host.ioBroker-Pi object zigbee.1.info.groups created
host.ioBroker-Pi object zigbee.1.info.pairingMessage created
host.ioBroker-Pi object zigbee.1.info.pairingCountdown created
host.ioBroker-Pi object zigbee.1.info.pairingMode created
host.ioBroker-Pi object zigbee.1.info.connection created
host.ioBroker-Pi object zigbee.1.info created
host.ioBroker-Pi object system.adapter.zigbee.1.outputCount created
host.ioBroker-Pi object system.adapter.zigbee.1.inputCount created
host.ioBroker-Pi object system.adapter.zigbee.1.uptime created
host.ioBroker-Pi object system.adapter.zigbee.1.memRss created
host.ioBroker-Pi object system.adapter.zigbee.1.memHeapTotal created
host.ioBroker-Pi object system.adapter.zigbee.1.memHeapUsed created
host.ioBroker-Pi object system.adapter.zigbee.1.cputime created
host.ioBroker-Pi object system.adapter.zigbee.1.cpu created
host.ioBroker-Pi object system.adapter.zigbee.1.connected created
host.ioBroker-Pi object system.adapter.zigbee.1.alive created
host.ioBroker-Pi object system.adapter.zigbee.1 created
process exited with code 0
