### ISSUE TITLE
NO Data from E1524

### ISSUE THREAD

**Issue by Secrenz** [ioBroker/ioBroker.zigbee#366]
Hello Guys,

i have an E1524 from IKEA and the CC2531
The remote is in iobroker installt, but i push a button and nothing happens.
i see the link quali, no button press.
The same is by the motion sensor.

(my englisch very bad xD) 

Can someone help me please? 
Thank you.

**Comment by asgothian** [comment]
Which firmware version does your cc2531 stick have ? i had to update my stick to a newer firmware for the E1524 to work.
