### ISSUE TITLE
Max Number of same End-Devices?

### ISSUE THREAD

**Issue by baerengraben** [ioBroker/ioBroker.zigbee#37]
Hi
I'm running a CC2531 USB Stick on a Raspberry Pi with ioBroker. Additionaly I run a second Stick CC2531 USB Stick as a router. Everthing works so far but it seems that i have a problem with maximum supported devices. I have paired 20 devices of type "MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)". I want to pair another 5 of theese devices. But pairing seems not possible anymore. the pairing-Process doesn't find any of them. Is there a limit of 20 Devices of "same type"?

**Comment by kirovilya** [comment]
This is a known problem with the number of devices :(

What firmware are you using?

By default, the firmware has a limit of 20 devices connected to the coordinator (cc2531). But if you have connected a router among 20 devices, you also need to connect devices through a router - then the number of devices will increase, because another 20 devices can be connected to the router.

You can build and flash a firmware with an increased number of connected devices, but then there will be less available memory on the stick.

Try installing the adapter version 0.7.1 and look at the network map to see how the devices are connected.

Tell me then how it happened.

**Comment by baerengraben** [comment]
The coordinator-device is flashed with this firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531/bin
The router-device is flashed with this firmware: http://ptvo.info/wp-content/uploads/2018/05/cc2531_1.2.2a.44539_firmware.zip

So by running the router I shoud can connect more of them. That sound good :)

I've now installed Version 0.7.1. Can you please let me know how I can look at the "network map" feature? I can't find it anyhow :(

**Comment by kirovilya** [comment]
> I've now installed Version 0.7.1. Can you please let me know how I can look at the "network map" feature? I can't find it anyhow :(
If you has installed from github, then you need "upload" admin files and restart adapter. Network map - tab in admin-page of adapter.

**Comment by baerengraben** [comment]
Ok, now it works. I can see the Network Map. Everything seems to be connected directly through the coordinator
![grafik](https://user-images.githubusercontent.com/9572444/44153307-3338b79a-a0a8-11e8-9fd4-1f0ffaa65c61.png)

I wonder how I can manage to connect devices through the router. Do you have a trick? :)

**Comment by kirovilya** [comment]
I do not know why yet, but lumi.router does not show any connection with the devices ... :( I'm looking for a solution for it.

So I think that 10 door sensors connected to your lumi.router.
How check this? Power off router :) And you should not receive signals from this sensors.

**Comment by kirovilya** [comment]
To specify to connect new device to router, you need press green button on router-card on first tab.

**Comment by baerengraben** [comment]
> So I think that 10 door sensors connected to your lumi.router.
How check this? Power off router :) And you should not receive signals from this sensors.

I can confirm this. When powering off the router, I do not receive any signals from some devices. Prowering on the router again => the signals are comming in again.

So the router does definitely some router-work :)

**Comment by baerengraben** [comment]
> To specify to connect new device to router, you need press green button on router-card on first tab.

Oh....intersting. This was not there before (new feature of 0.7.1?). So paring with the "router-green-button" will increase the amount of maximum supported "same devices"?

**Comment by baerengraben** [comment]
yesss... this works. :) With pairing through the router I can increase the maximum supported "same devices".

**Comment by baerengraben** [comment]
but the network-map is not showing it:
![grafik](https://user-images.githubusercontent.com/9572444/44155127-b532d5ba-a0ac-11e8-8ed4-3ee3da0b0807.png)
I have paired the device "noch nicht verwendet (pair router)" through the router. And it worked. But it doesn't show up like this on the network-map.

**Comment by kirovilya** [comment]
Unfortunately, I do not know yet why the map does not show the connection. I will sort this out.
How many devices did you connect?

**Comment by rocklobster42195** [comment]
My map does not show any connection at all. Let me know, if you need some help.
Shall we open another issue?

![image](https://user-images.githubusercontent.com/13438315/44161114-a6f26780-a0bc-11e8-8593-f803bfa7900b.png)

Thank you,
Boris

**Comment by kirovilya** [comment]
@rocklobster42195 it happens, but why and how to solve it - I do not know yet.
try disconnecting power from the lamp and reconnecting again.

**Comment by kirovilya** [comment]
@baerengraben By default, a large green button starts pairing on all devices on the network: on the coordinator and on all routers. And it is not clear through which device (coordinator or router) a new device will be connected.
Therefore, you had a part of the devices connected through a router.

Now, when you click on the small green button, it will only pair with a specific router.

**Comment by baerengraben** [comment]
> By default, a large green button starts pairing on all devices on the network: on the coordinator and on all routers. And it is not clear through which device (coordinator or router) a new device will be connected.

Aahhh, Ok.  :)

**Comment by kirovilya** [comment]
@rocklobster42195 look at logs, Maybe a similar error https://github.com/ioBroker/ioBroker.zigbee/issues/40

**Comment by rocklobster42195** [comment]
I posted my logs in #40

**Comment by kirovilya** [comment]
:) There is no network with two or more coordinators - the coordinator is always one!
Each firmware has its limitations on the number of connected devices - this is due to the available memory, the chip cc2530 is limited to 8Kb.
If you look here https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531 , you will see the parameters of the firmware assembly for the coordinator.
The same parameters are also found in the firmware of the router. I do not know with what parameters the firmware of the router is collected, maybe there is a quantity of 15 devices installed there.

It's strange that the coordinator is also not permit join anymore, maybe you need to bring the end device closer to the coordinator, or disconnect the router while connecting new devices.

The number of connected devices is a very painful moment for the chip cc2530. That's why I added a network map to see how the devices are connected to each other.

**Comment by baerengraben** [comment]
> The same parameters are also found in the firmware of the router. I do not know with what parameters the firmware of the router is collected, maybe there is a quantity of 15 devices installed there.

Interesting...Thanks for the link! When I find the time I will try to go a little bit deeper here...

> It's strange that the coordinator is also not permit join anymore, maybe you need to bring the end device closer to the coordinator, or disconnect the router while connecting new devices.

OK. I will try this out.

> :) There is no network with two or more coordinators - the coordinator is always one!

Yes :) I was thinking about installing a second zigbee-network on a different channel but on the same raspberry pi. This by putting a second coordinator to the raspberry pi and installing a second instance of the adapter but on a different channel. Do you thin this would be possible?

**Comment by kirovilya** [comment]
Here another link about max devices https://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/t/396713?The-meaning-of-NWK-MAX-DEVICE-LIST-NWK-MAX-DEVICES-NWK-MAX-ROUTERS-and-gNWK-MAX-SLEEPING-END-DEVICES#

> I was thinking about installing a second zigbee-network on a different channel but on the same raspberry pi

Yes, it is possible.

**Comment by arteck** [comment]
the question is : all devices or router only ..

**Comment by baerengraben** [comment]
> If you look here https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531 , you will see the parameters of the firmware assembly for the coordinator.

When I understand this correctly, it should be possible to connect 15 end-devices on a coordinator and also 15 Devices on a router. My test on august 19th would confirm the 15 devices on the router.

I did further testing:
Now I got it working with 25 devices:

* 1x instance on channel 13
  * with 7 devices on coordinator (cc2531)
* 1x instance on channel 11 
  * with 8 devices on coordinator (cc2531)
  * 1 router (cc2531)
    * with 10 devices on router

From now no further devices can be paired to the router. This is confusing. Once I could pair 15 devices (same devices) to this router.

In this "pairing-round" I had several errors when binding. It needed more tries until a device was successfully paired. Is it possible, that those unsuccessfull-pairing attempts are consuming memory-space on the router and it is not giving it back? Can that be the reason why, depending on "pairing-rounds", there are allways different numbers of successfull paired devices (depending on not successfull pair attempts)? What do you mean?

**Comment by baerengraben** [comment]
Addendum:
On the ioBroker instance i have now
- deleted all router-devices an the router itself
- and reflashed the router
I expected, that i can repair the router to the coordinator. 

But this is not working. Even any other device cannot be paired anymore to the coordinator. 
On August 19th I got this same behaviour. So this problem is reproducable. There are only 8 Devices paired to the coordinator. So I assume, that there must be another problem beside the "Max Number of Device" Question. Maybe this Problem worths opening another Issue?

**Comment by baerengraben** [comment]
Ok. I'm closing this one. I have now an operating system with more than 26 devices. And it seems to work with no Problems. Here is my conclusion:
- There is a limit of 15 Devices per Stick (cc2531). 
- The pairing-process is tricky and not allways successful
- When using a router the pairing-process is even more tricky and more "not allways successful"
- But once the devices are successfuly paired, the system runs smoothly

I removed the router and used a second raspberry instead of the router. This makes it more flexible because as soon as I got problems in pairing on router, I couldn't event pair any devices on the corresponding coordinator anymore. This end up with reflashing coordinator and router and repairing the devices. The last days I feel like pairng devices over hours...

Now this is my working System, based on two raspberries:

Raspberry 1:

* 1x instance on channel 13
  * with 7 devices on coordinator (cc2531)
* 1x instance on channel 11 
  * with 7 devices on coordinator (cc2531)

Raspberry 2:

* 1x instance on channel 15
  * with 12 devices on coordinator (cc2531)

Of course the sticks on Raspberry 1 (with 2 sticks) are not plugged in directly. Instead I used a USB-cable extension and placed the sticks with enough distance from each other.

This works for me.
