### ISSUE TITLE
IKEA Tradfri Motion Sensor

### ISSUE THREAD

**Issue by maku79** [ioBroker/ioBroker.zigbee#375]
Hi, i tried to pair the IKEA Tradfri Motion Sensor Type E1745, with ioBroker zigbee adapter
i got following error message in the log:

new dev 0x000d6ffffe4afa67 46185 TRADFRI motion sensor
zigbee.0 | 3 | error | Device 000d6ffffe4afa67 "TRADFRI motion sensor" not described in statesMapping.

**Comment by asgothian** [comment]
Please install the latest version (either from here or from my debug branch https://github.com/asgothian/ioBroker.zigbee/tarball/11.4-Devices ) and try again.

**Comment by sochin67** [comment]
Hi, 
I seem to have a similar issue, even with Adapter version 11.5.
I can't get the motion sensor connected to the cc2531 zigbee stick, I not even come to the error message described by maku79 above. The pairing process does not show any connection attempts.
I tried by permanently pressing the sensor pairing button, pressing every couple of seconds, reset.
Thanks in advance for any hints!
Tom

**Comment by oswaldo-be** [comment]
Same problem here with the same constellation as @sochin67 has.
Would appreciate a hint.
Thanks
Ben

**Comment by oswaldo-be** [comment]
@sochin67 oh, just wrote the comment, went back to the tab which tried to pair and I saw it was paired... weird. Got another 2 sensors and will test :-)

**Comment by sochin67** [comment]
@oswaldo-be: Thanks for your comment! 
Would you please let me know how you handled the Tradfri pairing button? Did you press once and hold it down all the time during the pairing process of the Zigbee adapter or did you press it regularly every couple of seconds? 
Many thanks!

**Comment by oswaldo-be** [comment]
Unfortunately it got connected. I could see the states, like occupancy and battery, but the stayed empty... I tried to connect again, but now it aint connected anymore...
When I was successful in connecting I hold the connect button for like 10sec and then pushed it several (maybe 5) times shortly. then after 20sec I saw the first connecting results...
But well, I can say it does not work my adapter is version 0.11.5

**Comment by sochin67** [comment]
Okay - your pairing process is exactly identical to my approach. So let's hope that either somebody knows a workaraound or it will be solved in the next Adapter version...
Thanks!

**Comment by N3rfski** [comment]
Just wanted to let you know that this issue is still a thing. After a full day of trying to connect 2 motion sensors (got them connected but no states) today i came across this issue.
It‘s the newest adapter version

**Comment by Gwoony** [comment]
The same problem for me too. I never got connected. Is it foreseeable when and if there will be a solution? Thanks for an answer and thanks for your help and a nice Christmas.

**Comment by SliX185** [comment]
First at All, Happy New year!
Got the same problem ... Cannot connect at all. There is no paring attempt in the adapter.

**Comment by chr-jordan** [comment]
![Bildschirmfoto_2020-01-05_07-53-47](https://user-images.githubusercontent.com/44375264/71776359-8c11e300-2f90-11ea-84e9-8d066b6bc83c.png)
Have paired the Tradfri E1745 with pressing on the Tradfri E1745 the connection key  in center 4 times instantly. Now I am puzzling with the  objectvalues. Battery an link_quality are fine but value for "last_motin" an "occupancy" (see picture) never got a status. Same behaviour for adapter version 11.5 and 1.0.0-c. Btw devicepicture is the one of E1525.

**Comment by SliX185** [comment]
... Well, it just worked. I've made a reset on the motionsensor directly after paring start and then pressed the button for little longer, followed by inkonstant short pressings.
Don't know if this will help someone.
