### ISSUE TITLE
IKEA Tradfri bulb E14 CWS opal 600lm

### ISSUE THREAD

**Issue by Sascha79** [ioBroker/ioBroker.zigbee#376]
Hello dear developer,
the ioBroker.zigbee adapter does not work with IKEA Tradfri bulb E14 CWS opal 600lm.
It's possible to pair this device, but there's no way to control it. No regular object is created, just a single entry in the Zigbee objects tree.

Log error message: "Device 000d6ffffe406ac7 "TRADFRI bulb E14 CWS opal 600lm" not described in statesMapping." 

Is something wrong with my ioBroker installation or does this device need to be added to the adapter device list?

Greeting,
Sascha

**Comment by asgothian** [comment]
I have a test version which should include this bulb, but cannot test it. Please install from
https://github.com/asgothian/ioBroker.zigbee/tarball/11.4-Devices

**Comment by Sascha79** [comment]
Hello asgothian,
thank you for your quick reply. I have the trial version installed. The pairing of the IKEA bulb worked without any problems. It is completely recognized. And all data points are created now. The following errors are still present: 
**Brightness**: only 0% (= off) and 99% (= highest brightness) work. By 100% the lamp dims very dark. **Color:** can not be controlled.
**Color temperature:** can not be controlled.
**State:** works, but the lamp flickers when turned on and off.
**Transition time:** I could not test so far.

This error is generated when trying to change the color temperature: 
2019-10-05 09:11:14.332 - error: zigbee.0 No converter available for 'LED1624G9' with key 'colortemp'

Best regards,
Sascha

**Comment by Sascha79** [comment]
**Edit:** 
Brightness, color and state work without errors. A wrong color value had caused the errors mentioned above. I'm so sorry. Transition time works as well. Only the color temperature causes problems.
Greetings, 
Sascha

**Comment by asgothian** [comment]
This seems to be an issue in the implementation in the zigbee-shepherd. It does allow for colortemp messages, but does not seem to react well to the required messages. I can disable colortemp for the iobroker.zigbee adapter for the time being.
Alternatively, you could run a number of tests for me to see how the lamp reacts when you try to set the colortemp on the direct level:
In the ioBroker.zigbee adapter configuration interface, choose the "developer" tab (rightmost tab), and select the following:
- Device: your lightbulb
- Endpoint: 1 (i think)
- Cluster Id: lightingColorCtrl(768)
- command Type: Foundation
- Command: write(2)
- Attribute ID: colorTemperature (7, type 33)
check "needs value", type ID unit16 (33)
for value, fill different values and check what the response of the lamp is and what happens with the color of the light.

A.

**Comment by Sascha79** [comment]
The lamp does not react at the given settings at all.
I tested values ​​between 1 and 10, 100 and 1000 and the usual values ​​for color temperatures in Kelvin (2700, 3000, 3500, 4000). The output in the log is always the same:

unsupAttribute {"msg":[{"status":134,"attrId":7}]}

**Comment by asgothian** [comment]
Humm.. good to know. If you try to read the colorTemperature attribute, does it also return "unsupAttribute" ? 
Also, can you try to use the foundation command "movetocolortemp", with attribute colortemperature and a value for the color temperature ?

If that also returns "unsupAttribute", it is safe to say that the lightbulb does not support color temperature, and i will remove the settings from the adapter.

**Comment by Sascha79** [comment]
I am not sure if I have adjusted everything correctly. The **_foundation command_** "movetocolortemp" does not exist with me. However, there is the **_functional command_** "movetocolortemp". I have made the settings as follows:
**Device:** my IKEA lamp
**Endpoint:** 1
**Cluster ID:** lightingColorCtrl (768)
**Command Type:** Functional
**Command:** moveToColorTemp (10)
**Attribute ID:** colorTemperature (7, type 33)
**Type ID:** unit16 (33)
**Value:** tested some different values

I always get the message: 
"undefined {"err":"The argument object has incorrect properties"}"

**Comment by asgothian** [comment]
you are right.. its functional - my bad. And it seems its not as simple to put the command together.
Not entirely sure how to test that. Id say the lamp doesn't do Colortemp. Other posts on the web suggest the same, so i'll remove  the ct datapoints from the adapter for now

**Comment by allofmex** [comment]
@Sascha79 
In DeveloperTap you have to use ExpertMode with
```
{
    "devId": "zigbee.1.90fd....",
    "ep": "1",
    "cid": "768",
    "cmd": "7",
    "cmdType": "functional",
    "zclData": {
        "colorx": "60000",
        "colory": "10000",
        "transtime":1
    },
    "cfg": null
}
```
colorx/y 0-65535, see https://github.com/Koenkk/zigbee-shepherd-converters/blob/a2bf25718ddfd728754b9bc1e64ad25b6d1d5461/converters/toZigbee.js#L476
(tested with ikea gu10 ws400)

**Comment by asgothian** [comment]
In this case, it would be

```
{
    "devId": "zigbee.1.90fd....",
    "ep": "1",
    "cid": "768",
    "cmd": "10",
    "cmdType": "functional",
    "zclData": {
        "colortemp": "300",
        "transtime":1
    },
    "cfg": null
}
```

**Comment by Sascha79** [comment]
Nope, it does not work.

**Comment by asgothian** [comment]
does not work means "unsupported attribute" or "undefined {"err":"The argument object has incorrect properties"}" ?

**Comment by Sascha79** [comment]
> does not work means "unsupported attribute" or "undefined {"err":"The argument object has incorrect properties"}" ?

unsupClusterCmd {"msg":{"cmdId":10,"statusCode":129}}

**Comment by asgothian** [comment]
Ok.. that makes it clear. I;ll update my branch removing the CT adjustment. The lamp clearly does not support setting color temperature

**Comment by 420Dope** [comment]
Nice to see that this problem picked up again.
Are you sure that the lamp don´t support setting color temperature? In the issue [#182](https://github.com/ioBroker/ioBroker.zigbee/issues/182) the user sinalco92 say that it worked in a early verion...

**Comment by klotzma** [comment]
With my Tradfri e27 it does not work to change the color temperature either.  It comes this error:
zigbee.0 2019-10-29 20:37:58.500 error (22553) No converter available for 'LED1624G9' with key 'colortemp'

**Comment by Domi920** [comment]
Erneuter Versuch die Farbtemperatur einstellen zu können:
https://github.com/ioBroker/ioBroker.zigbee/issues/994
