### ISSUE TITLE
IKEA TRADFRI ON/OFF switch E1743

### ISSUE THREAD

**Issue by zecki79** [ioBroker/ioBroker.zigbee#377]
Hi, i use a cc2531 stick (Firmware Z-Stack Home 1.2 default) on a raspberry pi 3 with iobroker. i bought the IKEA Tradfri on/off switch (E1743) but it is not supported on the zigbee adapter (ver. 0.11.3 ) yet. the friendly project zigbee2mqtt has this device on the list of supported device. will the device be supportet on a new version of this adapter? Thank you!!

**Comment by asgothian** [comment]
I have a test branch with this switch integrated, but cannot test it. Install from
https://github.com/asgothian/ioBroker.zigbee/tarball/11.4-Devices

**Comment by zecki79** [comment]
Hi asgothian, i tryed your test branch, the tradfri switch was recognized but when i pushed a button on the swicht, the zigbee adapter got disabeld (red) and so it dont work. then i deinstalled the adapter and after this my system chrashed and iobroker cant start

**Comment by asgothian** [comment]
What error do you get when trying to start it ?
Did you try to restart the system the iobroker is on ?

**Comment by zecki79** [comment]
hi asgothian, thank you very much, now the switch works!!!! great work!!!!!
