### ISSUE TITLE
Support for Nue/3A 3A12S-15 RGBW Controller

### ISSUE THREAD

**Issue by Frank1604** [ioBroker/ioBroker.zigbee#379]
Can you please add this device?

![grafik](https://user-images.githubusercontent.com/10420590/66338256-0bb3f580-e941-11e9-95a3-44834e3099bb.png)

![IMG_20191007_203018](https://user-images.githubusercontent.com/10420590/66338631-d065f680-e941-11e9-9585-a211ed25773f.jpg)

It looks similar to [this device](https://www.zigbee2mqtt.io/devices/XY12S-15.html).

zigbee.0 | 2019-10-07 19:44:40.814 | error | Unknown device model LXT56-LS27LX1.4 emit event readRsp with  data:{"cid":"genBasic","data":{"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20190604","swBuildId":"1000-0001"}
-- | -- | -- | --
zigbee.0 | 2019-10-07 19:44:40.705 | error | Unknown device model LXT56-LS27LX1.4 emit event readRsp with  data:{"cid":"genBasic","data":{"manufacturerName":"3A Smart Home  DE","modelId":"LXT56-LS27LX1.4","powerSource":1}}

**Comment by asgothian** [comment]
As of now, the device is not supported in the current zigbee-shepherd-converters. This is a requirement to support it in ioBroker.zigbee.

A.

**Comment by Frank1604** [comment]
Ok I understand. So, what are the next steps, what can I do to solve this problem?

**Comment by asgothian** [comment]
If you head over to the koenig/zigbee-shepherd-converters, you can open an issue there. Alternatively, i can try to have a look at it, but that will take a bit of time

**Comment by Frank1604** [comment]
I have opened [a ticket](https://github.com/Koenkk/zigbee-shepherd-converters/issues/677) now. I would appreciate further help.
