### ISSUE TITLE
Problem Xiaomi Temperatursensor mit js.controller 2.0.25

### ISSUE THREAD

**Issue by Nuggelbeb** [ioBroker/ioBroker.zigbee#383]
Hallo Gemeinde,
Seit Umstellung auf js.controller 2.0.25 habe ich ein Problem mit dem "lumi.weather". Durch Aktualisierung der Temperatur ändert sich ständig der eingestellte "unit" Wert von "°C" auf ein Hieroglyphenzeichen "�C". 

Kann mir bitte jemand von euch helfen?
Die Jungs von der Entwicklung des js.controllers 2.x vermuten ebenfalls das Problem beim Zigbee Adapter. 

Ich danke euch im Voraus.

**Comment by Apollon77** [comment]
It seems that there is some kind of encoding issue ...
