### ISSUE TITLE
Support for TRADFRI on/off switch

### ISSUE THREAD

**Issue by Frank1604** [ioBroker/ioBroker.zigbee#384]
Can you please add this device? Are you need any further informations?

zigbee.0 | 2019-10-10 21:11:51.202 | error | Device 14b457fffed02b53 "TRADFRI on/off switch" not described in statesMapping.
-- | -- | -- | --

**Comment by Frank1604** [comment]
![IMG_20191011_075959](https://user-images.githubusercontent.com/10420590/66628188-5dd56f00-ebfe-11e9-8a3d-7994d40a3dd0.jpg)

**Comment by eviw** [comment]
RAW:
{
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1570874022664,
  "common": {
    "name": "TRADFRI on/off switch",
    "type": "TRADFRI on/off switch",
    "icon": "img/unknown.png"
  },
  "native": {
    "id": "14b457fffe4dca32"
  },
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "zigbee.0.14b457fffe4dca32",
  "type": "device"
}

**Comment by eviw** [comment]
I've installed from test branch https://github.com/asgothian/ioBroker.zigbee/tarball/11.4-Devices and tested successfully. On/Off works. But brightness value is missing in object list and dimming does not work: 
![grafik](https://user-images.githubusercontent.com/8075884/66956389-9b098900-f064-11e9-90d5-1585d1c6d70b.png)

**Comment by Frank1604** [comment]
> 
> 
> I've installed from test branch https://github.com/asgothian/ioBroker.zigbee/tarball/11.4-Devices and tested successfully. On/Off works. But brightness value is missing in object list and dimming does not work:
> ![grafik](https://user-images.githubusercontent.com/8075884/66956389-9b098900-f064-11e9-90d5-1585d1c6d70b.png)

As you can see in my photo, this is an on / off switch. There is no brightness or dimming option. Do you mean the Tradfri dimmer?

**Comment by eviw** [comment]
It is dimmable by long pressing On (I) or Off (O) switch. Ikea delivers it together with a dimmable bulb: https://www.ikea.com/de/de/p/tradfri-set-mit-dimmer-10435926/

**Comment by Frank1604** [comment]
Uh, ok. I didn't know that, cause i by this with a socket: [TRÅDFRI Control outlet kit](https://www.ikea.com/us/en/p/tradfri-control-outlet-kit-70364803/) 
The description only says: You can wirelessly turn your lights on and off.
