### ISSUE TITLE
Errors after ioBroker update

### ISSUE THREAD

**Issue by Squelsh** [ioBroker/ioBroker.zigbee#385]
Hi!
Thanks for this great adapter! It worked like a charm until I updated ioBroker.
Now I see these errors in the log. Any hints on how to solve this issue would be greatly appreciated!
Specs from ioBroker: 
"hosts": [
    {
      "version": "1.5.14",
      "platform": "Javascript/Node.js",
      "type": "linux"
    }
  ],
  "node": "v8.16.1",
  "arch": "arm",
  "adapters": {
    "admin": {
      "version": "3.6.7",
      "platform": "Javascript/Node.js"
    },
    "zigbee": {
      "version": "0.11.3",
      "platform": "Javascript/Node.js"
    }

Cheers,
Andy 

Log errors:

host.raspberrypi | 2019-10-10 22:34:15.393 | error | instance system.adapter.zigbee.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-10-10 22:34:15.393 | error | by controller[0]:     at Function.Module._load (module.js:498:3)
Caught | 2019-10-10 22:34:15.393 | error | by controller[0]:     at tryModuleLoad (module.js:506:12)
Caught | 2019-10-10 22:34:15.393 | error | by controller[0]:     at Module.load (module.js:566:32)
Caught | 2019-10-10 22:34:15.393 | error | by controller[0]:     at Object.Module._extensions..js (module.js:664:10)
Caught | 2019-10-10 22:34:15.393 | error | by controller[0]:     at Module._compile (module.js:653:30)
Caught | 2019-10-10 22:34:15.392 | error | by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/@serialport/bindings/node_modules/debug/src/node.js:236:18)
Caught | 2019-10-10 22:34:15.392 | error | by controller[0]:     at require (internal/module.js:11:18)
Caught | 2019-10-10 22:34:15.392 | error | by controller[0]:     at Module.require (module.js:597:17)
Caught | 2019-10-10 22:34:15.392 | error | by controller[0]:     at Function.Module._load (module.js:475:25)
Caught | 2019-10-10 22:34:15.392 | error | by controller[0]:     at Function.Module._resolveFilename (module.js:548:15)
Caught | 2019-10-10 22:34:15.392 | error | by controller[0]: Error: Cannot find module './common'
Caught | 2019-10-10 22:34:15.392 | error | by controller[0]:     ^
Caught | 2019-10-10 22:34:15.391 | error | by controller[0]:     throw err;
Caught | 2019-10-10 22:34:15.391 | error | by controller[0]: module.js:550
host.raspberrypi | 2019-10-10 22:34:14.391 | info | instance system.adapter.zigbee.0 started with pid 3832

**Comment by Apollon77** [comment]
Reinstall adapter please

**Comment by Squelsh** [comment]
Thanks for that quick response! Solved my probs :+1: 
Still a noob in ioBroker. Will try reinstalling first when I experience problems with an adapter next time...
