### ISSUE TITLE
Adapter unable to start with Z-stack firmware CC26X2R1_20191106 (Master) on TI CC26x2r1

### ISSUE THREAD

**Issue by J-Paul0815** [ioBroker/ioBroker.zigbee#387]
Zigbee Adapter 0.11.5 seems no longer compatible with new Z-stack firmware CC26X2R1_20191106/CC26X2R1_20191106 

Adapter goes green, but if I try to open:
Error You need save and run adapter before pairing!
Log:
https://pastebin.com/5T6cSqqk

System:
Node.js v10.17.0
NPM 6.11.3
JS controller 2.0.39

Tested Firmware that works:
znp_CC26X2R1_LAUNCHXL_tirtos_ccs_with_patch CC2652R_20190515
znp_CC26X2R1_LAUNCHXL_tirtos_ccs CC2652R_20190426

new 20191011 Firmware fixed it!

Zigbee Adapter 0.11.4 seems no longer compatible with Z-stack firmware CC26X2R1_20191010 (Master) on TI CC26x2r1.
Adapter is unable to start. 
Error You need save and run adapter before pairing!
COM is correct /dev/ttyACM0
(3986) Error while starting zigbee-shepherd!. Error: rsp error: 2

Log after Adapter start:
https://pastebin.com/A4Vxe4JN

Tested Firmware that works:
znp_CC26X2R1_LAUNCHXL_tirtos_ccs_with_patch CC2652R_20190515
znp_CC26X2R1_LAUNCHXL_tirtos_ccs CC2652R_20190426

System:
Node.js v10.16.3
NPM 6.9.0
JS controller 2.0.25

Update:
Seems to be a problem with the firmware. I have a Zigbee2mqtt installed in a separate VM. With the firmware from 10.10. can not be started, but starts with earlier firmware versions.
Log:
https://pastebin.com/d6nFsG2R
zigbee2mqtt with older firmware:
https://pastebin.com/y9RryZdR
Would be grateful for any help

**Comment by kirovilya** [comment]
In the end, I did not understand, is it working now or not? :)

**Comment by kirovilya** [comment]
I am now rewriting the use of zigbee-herdsman and these changes should provide the same overall functionality with zigbee2mqtt project.
You can try the alpha version from here.
https://github.com/ioBroker/ioBroker.zigbee/tarball/herdsman
Attention! This is not the final version, only for test. Errors and omissions are possible.

**Comment by J-Paul0815** [comment]
Thank you, Ilya. As I said, this is just a test system. The alpha version of the adapter does not start. (yellow) see log:

https://pastebin.com/2PVhHCfy

**Comment by kirovilya** [comment]
```2019-11-07 14:41:21.374 - error: zigbee.0 (2011) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'```
Verify the port is correct.

**Comment by J-Paul0815** [comment]
Yes, I´m sure, that COM Port ist correct. It is always ttyACM0

iobroker@iobroker:~$ ls -l /dev/serial/by-id
insgesamt 0
lrwxrwxrwx 1 root root 13 Nov  7 17:35 usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L1100C7K-if00 -> ../../ttyACM0
lrwxrwxrwx 1 root root 13 Nov  7 17:35 usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L1100C7K-if03 -> ../../ttyACM1
(ttyACM0 is always the serial data port and ttyACM1 the debugger port)
As you can see at the LOG I have green Adapter full funktion at 17:39 at Com Port ttyACM0
Adapter 0.11.5 from Github and flash (older) znp_CC26X2R1_LAUNCHXL_tirtos_ccs_with_patch.hex
after Install 0.11.5 alpha Herdsman Version 17:41 Error while opening serialport

https://pastebin.com/veMbZL8Y

**Comment by kirovilya** [comment]
looking at the error - it cannot access the port, as if the port is already in use

**Comment by J-Paul0815** [comment]
OK, I stopped VM, deleted hardware in Proxmox USB Device, changed the USB port. The new port passed through into the VM. Same mistake. In the adapter soft reset. Same mistake. Hard reset. Adapter green, all devices available and controllable. Should I try the Alpha Herdsman version again?

https://pastebin.com/HZ2zLBuK

**Comment by kirovilya** [comment]
yes

**Comment by kirovilya** [comment]
On my Windows this is how it starts
![image](https://user-images.githubusercontent.com/8360230/68415315-23320880-01a3-11ea-8858-8eea7d124284.png)

**Comment by J-Paul0815** [comment]
https://pastebin.com/a5GQ1ZeS

**Comment by kirovilya** [comment]
hmm. strange. I'll think about it ...
thanks for the test.

**Comment by J-Paul0815** [comment]
https://pastebin.com/r2a2VhQR
my last try

**Comment by kirovilya** [comment]
ok, i will try to contact Koen about this error

**Comment by J-Paul0815** [comment]
OK, I tried Herdsman again. This time I stopped the Zigbee adapter first, then I deleted it. Only then I did install https://github.com/ioBroker/ioBroker.zigbee/tarball/herdsman. Com port /dev/ttyACM0 and channel 15 entered. One second later, the instance was green. Devices can pair, control and report the status.

https://pastebin.com/n2AX5Gis

(In Main.js I uncomment line 11 and 12 now)

**Comment by kirovilya** [comment]
This is very good, so it still works!
Lines 11 and 12 are needed for debugging the herdsman, in normal mode they do not give effect.

**Comment by J-Paul0815** [comment]
Yes, now for hours absolut stable with full funktion. Some times:

2019-11-10 15:07:31.497 - error: zigbee.0 (2662) Failed to execute routing table for '0x84182600000ed6cc'. "Error: AREQ - ZDO - mgmtRtgRsp after 10000ms\n at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)"

**Comment by J-Paul0815** [comment]
After Update to 1.0.0a Adapter runs stable.
https://pastebin.com/u5iwCtwP

**Comment by kirovilya** [comment]
Yes, I see some problems with the network manp (LQI request).
But everything is fine :)
