### ISSUE TITLE
Bitron Wireless wall thermostat with relay (AV2010/32)

### ISSUE THREAD

**Issue by smartpran** [ioBroker/ioBroker.zigbee#388]
Hi, I have see the friendly project Zigbee2mqtt supported the device Bitron Wireless wall thermostat with relay (AV2010/32). Can be the device supported in a new version? Thank you!

**Comment by elahorle** [comment]
I would also appreciate it if the Bitron wall thermostat would be compatible.

**Comment by smartpran** [comment]
Please reopen this ticket. It would be great if the wall thermostat could be implemented.
