### ISSUE TITLE
Cant start / use zigbee Adapter

### ISSUE THREAD

**Issue by soRailicious** [ioBroker/ioBroker.zigbee#389]
Just getting the responsoce "instance system.adapter.zigbee.0 terminated with code 10 (Cannot find start file of adapter)"

**Comment by allofmex** [comment]
This looks like an setup issue. Please reinstall the adapter. You may also check the file system.
In iobroker-data/file should be a folder zigbee.admin containing admin.js and other files. Also node_modules/iobroker.zigbee with main.js

Closing issue. (You did not provide any additional information (versions / was it working before / what did you tried /...)

**Comment by soRailicious** [comment]
@allofmex rly? Instant close?! 

i dont think so that that is an setup issue... maybe u can give me some advices to fix / clean install the adapter again without formatting/reinstalling iobroker.

i use: 
- npm v 6.120
- nodejs v 10.16.3
- iobroker v 1.5.14

what can / should i do? what to you maybe need?

ive tried a lot of time to reinstall / npm rebuild, npm uninstallt iobroker.zigbee and reinstall over iobroker adapters or directly with npm . nothing worked for me.

**Comment by Apollon77** [comment]
Try iobroker upload zigbee

Now?

**Comment by soRailicious** [comment]
Nope, but in export mode i installed a previois version and upgrade it after that. And i reinstalled shepherd again. Now it seems to work. Thanks for your Reply!
