### ISSUE TITLE
Support for Gledopto GL-MC-001

### ISSUE THREAD

**Issue by gromet** [ioBroker/ioBroker.zigbee#391]
Can you please add this device.

Unknown device model GL-MC-001 emit event readRsp with data:
```
{
	"cid": "genBasic",
	"data": {
		"zclVersion": 1,
		"appVersion": 1,
		"stackVersion": 2,
		"hwVersion": 1,
		"dateCode": "20131206",
		"swBuildId": "2.0.0"
	}
}
```

Unknown device model GL-MC-001 emit event readRsp with data:
```
{
	"cid": "genBasic",
	"data": {
		"manufacturerName": "GLEDOPTO",
		"modelId": "GL-MC-001",
		"powerSource": 1
	}
}
```

```
{
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1571328508332,
  "common": {
    "name": "GL-MC-001",
    "type": "GL-MCv-001",
    "icon": "img/unknown.png"
  },
  "native": {
    "id": "00124b001eadab6d"
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "zigbee.0.00124b001eadab6d",
  "type": "device"
}
```

![61iaTHwocXL _SL1200_](https://user-images.githubusercontent.com/4107508/67069955-047dba80-f17f-11e9-88b1-834955bbbd69.jpg)

**Comment by gromet** [comment]
Device added to Zigbee2mqtt Project. [https://github.com/Koenkk/zigbee2mqtt/issues/2180](https://github.com/Koenkk/zigbee2mqtt/issues/2180)

**Comment by DrMucki** [comment]
I just bought such a Device.
May I ask how to get it work with zigbee2mqtt? Do I have to wait for an update? I just did an update and it gave a few errors during update process:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/zigbee-shepherd-converters/node_modules/zigbee-herdsman/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/zigbee-herdsman/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})


The device is found as follows:

0x00124b001eadb378
zigbee2mqtt/0x00124b001eadb378

0x00124b001eadb378
NwkAddr: 38693 / manufId: 0

GL-MC-001
GL-MC-001

GLEDOPTO
HW: 1 / SW: 2.0.0

Router
Powersource: Mains (single phase)

But I cannot send any Mqtt to it... My Tradfri Things work fine with my setup....
Thank you very much for your help in advance!

**Comment by gromet** [comment]
sorry, i also cannot send any mqtt to it and my iobroker settings for GL-MC-001 are not working.
