### ISSUE TITLE
Support for new IKEA Tradfri bulbs LED1736G9 (E27 806lm) and LED1737R5, LED1739R5 (GU10 400lm)

### ISSUE THREAD

**Issue by CRT345** [ioBroker/ioBroker.zigbee#392]
Hello, could you please add support for the two IKEA tradfri bulbs LED1736G9 (E27 806lm)

https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-e27-806-lm-kabellos-dimmbar-weissspektrum-klar-30408470/

and LED1737R5, LED1739R5 (GU10 400lm).

https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-400-lm-kabellos-dimmbar-weissspektrum-90408603/

The first one is already supported by zigbee2mqtt.

https://www.zigbee2mqtt.io/devices/LED1736G9.html

If I could help you, please let me know how.

Thanks for your project!!!

**Comment by oOPsychokillerOo** [comment]
LED1837R5 
https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-400-lm-kabellos-dimmbar-warmes-tageslicht-60420041/
Wird zwar erkannt aber ist nur in einer Gruppe steuerbar und das Symbol ist ein ?

**Comment by andromedi4** [comment]
Hello, could you add support for IKEA tradfri bulbs LED1842G3 (E27 250 lm)
https://www.ikea.com/fi/fi/p/tradfri-led-lamppu-e27-250-lm-langaton-himmennettaevae-laemmin-hehku-pallonmuotoinen-ruskea-kirkas-lasi-70455676/

I`ve this lamp and so I will be able to help.
Thank you!

**Comment by Leviathan09** [comment]
Informations for IKEA tradfri bulbs LED1736G9 (E27 806lm)


**devices.js**
```
{
        zigbeeModel: ['TRADFRI bulb E27 WS clear 806lm'],
        model: 'LED1736G9',
        vendor: 'IKEA',
        description: 'TRADFRI bulb E27 WS clear 806 lumen, dimmable, white spectrum, clear',
        extend: generic.light_onoff_brightness_colortemp,
    },
```

**devstates.js**
```
{
        vendor: 'IKEA',
        models: ['TRADFRI bulb E27 WS clear 806lm'],
        icon: 'img/TRADFRI.bulb.E27.png',
        states: lightStatesWithColortemp,
        linkedStates: [comb.brightnessAndState]
    },
```

**Comment by gromet** [comment]
[Informations for IKEA tradfri bulbs LED1836G9 (E27 806lm)](https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-e27-806-lm-kabellos-dimmbar-warmes-tageslicht-opalweiss-90408797/)
**device.js**

```
{
    zigbeeModel: ['TRADFRI bulb E27 WW 806lm'],
    model: 'LED1836G9',
    vendor: 'IKEA',
    description: 'TRADFRI bulb E27 WW 806 lumen, dimmable, white spectrum, clear',
    extend: generic.light_onoff_brightness,
}, 
```

**devstates.js**
```
{
    vendor: 'IKEA',
    models: ['TRADFRI bulb E27 WW 806lm'],
    icon: 'img/TRADFRI.bulb.E27.png',
    states: lightStates,
    linkedStates: [comb.brightnessAndState]
}, 
```

**Comment by RestOp** [comment]
> LED1837R5
> https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-400-lm-kabellos-dimmbar-warmes-tageslicht-60420041/
> Wird zwar erkannt aber ist nur in einer Gruppe steuerbar und das Symbol ist ein ?

Haben Sie das geloest?
