### ISSUE TITLE
Support for Tint GU10 Spot 2700-6500K

### ISSUE THREAD

**Issue by snador1977** [ioBroker/ioBroker.zigbee#394]
I can not give any information, because the sport is not recognized at all. Since other Tint Devices work, maybe it is synonymous with the GU10 (Warmwhite/Coldwhite) spot. Thanks!

**Comment by allofmex** [comment]
You need to get it recognized first (this should work without any device specific support).
Please try to pair until you reach the point that the devices shows as card with question-mark.

Maybe you need to factory-reset the bulb first. Please also note that pairing may only work for the first minutes after cc2531 stick was plugged.

**Comment by snador1977** [comment]
This has not been successful so far, but I will try again by putting the spots back in advance. As soon as I have data I post ...
