### ISSUE TITLE
zigbee cannot installed

### ISSUE THREAD

**Issue by Ahrenfelde** [ioBroker/ioBroker.zigbee#397]
Hello,

I tried today to install the zigbee adapter and get this error message in logs:

iobroker npm-install: host.beelink Cannot install iobroker.zigbee@0.11.3: 1

iobroker Version: 2.0.3.5
npm: 6.11.3

It seems like the github link is not reachable

this is the interesting part of complete  log
`
36 silly saveTree ├── semver@5.7.1
36 silly saveTree └── yargs@7.1.0
37 verbose stack Error: 404 Not Found - GET https://github.com/kirovilya/zigbee-shepherd-converters/tarball/7dfa9c44edc68f332ca827764f4dbea6070bc413
37 verbose stack     at res.buffer.catch.then.body (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
37 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
38 verbose statusCode 404
39 verbose pkgid zigbee-shepherd-converters@https://github.com/kirovilya/zigbee-shepherd-converters/tarball/7dfa9c44edc68f332ca827764f4dbea6070bc413
40 verbose cwd /
41 verbose Linux 5.0.0-32-generic
42 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.zigbee@0.11.3" "--loglevel" "error" "--production" "--save" "--prefix" "/opt/iobroker"
43 verbose node v10.17.0
44 verbose npm  v6.11.3
45 error code E404
46 error 404 Not Found - GET https://github.com/kirovilya/zigbee-shepherd-converters/tarball/7dfa9c44edc68f332ca827764f4dbea6070bc413
47 error 404
48 error 404 'zigbee-shepherd-converters@https://github.com/kirovilya/zigbee-shepherd-converters/tarball/7dfa9c44edc68f332ca827764f4dbea6070bc413' is not in the npm registry.
49 error 404 You should bug the author to publish it (or use the name yourself!)
50 error 404 It was specified as a dependency of 'iobroker.zigbee'
51 error 404 Note that you can also install from a
52 error 404 tarball, folder, http url, or git url.
53 verbose exit [ 1, true ]
`

EDIT:

Now I was able to install zigbee over github link. This seems to work at the moment

**Comment by kirovilya** [comment]
Yes, this is our mistake. install from github please. will release 0.11.4 soon, fixing the bug
