### ISSUE TITLE
after restart the adapter are all values null

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#4]
for exaple
hue bulb the value for 

dimmer = 60
temp = 30
switch = false

are filled.

after restart the adapter

dimmer = 
temp = 
switch = false

the value must be preserved

**Comment by kirovilya** [comment]
Show starting log (in debug mode), please.

**Comment by arteck** [comment]
moment not atfer restart.. after reinstall or install new version

**Comment by kirovilya** [comment]
It is strange. After reinstall states not updated.
It is updating on start, but not changing value.
Try to repeat this case...

**Comment by kirovilya** [comment]
yes. I do not known what value to set while device not send it to me
