### ISSUE TITLE
adapter not starting after updating from previous version

### ISSUE THREAD

**Issue by moeff** [ioBroker/ioBroker.zigbee#400]
After Updating from 11.0 to 11.5 - adapter didnt start. Seems to be a problem of node version.

output - install and start log

`host.ioBroker | 2019-10-28 12:48:42.833 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.ioBroker | 2019-10-28 12:48:42.833 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-10-28 12:48:42.833 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-28 12:48:42.832 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-28 12:48:42.832 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.ioBroker | 2019-10-28 12:48:42.832 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.ioBroker | 2019-10-28 12:48:42.832 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-10-28 12:48:42.831 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker | 2019-10-28 12:48:42.831 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-28 12:48:42.831 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-28 12:48:42.831 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-28 12:48:42.830 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.ioBroker | 2019-10-28 12:48:42.830 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker | 2019-10-28 12:48:42.830 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:48:42.830 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.ioBroker | 2019-10-28 12:48:42.829 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker | 2019-10-28 12:48:42.829 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.ioBroker | 2019-10-28 12:48:42.829 | error | Caught by controller[0]: ^
host.ioBroker | 2019-10-28 12:48:42.829 | error | Caught by controller[0]: throw e
host.ioBroker | 2019-10-28 12:48:42.828 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88
host.ioBroker | 2019-10-28 12:48:41.566 | info | instance system.adapter.zigbee.0 started with pid 14570
host.ioBroker | 2019-10-28 12:48:11.540 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.ioBroker | 2019-10-28 12:48:11.539 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-10-28 12:48:11.539 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-28 12:48:11.539 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-28 12:48:11.539 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.ioBroker | 2019-10-28 12:48:11.539 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.ioBroker | 2019-10-28 12:48:11.538 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-10-28 12:48:11.538 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker | 2019-10-28 12:48:11.538 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-28 12:48:11.538 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-28 12:48:11.537 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-28 12:48:11.537 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.ioBroker | 2019-10-28 12:48:11.537 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker | 2019-10-28 12:48:11.537 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:48:11.537 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.ioBroker | 2019-10-28 12:48:11.536 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker | 2019-10-28 12:48:11.536 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.ioBroker | 2019-10-28 12:48:11.536 | error | Caught by controller[0]: ^
host.ioBroker | 2019-10-28 12:48:11.536 | error | Caught by controller[0]: throw e
host.ioBroker | 2019-10-28 12:48:11.535 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88
host.ioBroker | 2019-10-28 12:48:10.309 | info | instance system.adapter.zigbee.0 started with pid 11737
host.ioBroker | 2019-10-28 12:47:40.279 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.ioBroker | 2019-10-28 12:47:40.279 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-10-28 12:47:40.279 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-28 12:47:40.278 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-28 12:47:40.278 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.ioBroker | 2019-10-28 12:47:40.278 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.ioBroker | 2019-10-28 12:47:40.278 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-10-28 12:47:40.278 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker | 2019-10-28 12:47:40.277 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-28 12:47:40.277 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-28 12:47:40.277 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-28 12:47:40.277 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.ioBroker | 2019-10-28 12:47:40.277 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker | 2019-10-28 12:47:40.276 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:47:40.276 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.ioBroker | 2019-10-28 12:47:40.276 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker | 2019-10-28 12:47:40.276 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.ioBroker | 2019-10-28 12:47:40.275 | error | Caught by controller[0]: ^
host.ioBroker | 2019-10-28 12:47:40.269 | error | Caught by controller[0]: throw e
host.ioBroker | 2019-10-28 12:47:40.269 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88
host.ioBroker | 2019-10-28 12:47:39.137 | info | instance system.adapter.zigbee.0 started with pid 8887
host.ioBroker | 2019-10-28 12:47:09.101 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.ioBroker | 2019-10-28 12:47:09.101 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-10-28 12:47:09.100 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-28 12:47:09.100 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-28 12:47:09.099 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.ioBroker | 2019-10-28 12:47:09.099 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.ioBroker | 2019-10-28 12:47:09.098 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-10-28 12:47:09.098 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker | 2019-10-28 12:47:09.098 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-28 12:47:09.097 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-28 12:47:09.097 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-28 12:47:09.096 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.ioBroker | 2019-10-28 12:47:09.096 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker | 2019-10-28 12:47:09.095 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:47:09.094 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.ioBroker | 2019-10-28 12:47:09.094 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker | 2019-10-28 12:47:09.094 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.ioBroker | 2019-10-28 12:47:09.093 | error | Caught by controller[0]: ^
host.ioBroker | 2019-10-28 12:47:09.093 | error | Caught by controller[0]: throw e
host.ioBroker | 2019-10-28 12:47:09.092 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88
host.ioBroker | 2019-10-28 12:47:07.872 | info | instance system.adapter.zigbee.0 started with pid 6141
host.ioBroker | 2019-10-28 12:46:37.817 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.ioBroker | 2019-10-28 12:46:37.816 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-10-28 12:46:37.816 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-28 12:46:37.816 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-28 12:46:37.816 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.ioBroker | 2019-10-28 12:46:37.815 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.ioBroker | 2019-10-28 12:46:37.815 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-10-28 12:46:37.815 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker | 2019-10-28 12:46:37.814 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-28 12:46:37.814 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-28 12:46:37.814 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-28 12:46:37.814 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.ioBroker | 2019-10-28 12:46:37.813 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker | 2019-10-28 12:46:37.813 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:46:37.813 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.ioBroker | 2019-10-28 12:46:37.813 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker | 2019-10-28 12:46:37.812 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.ioBroker | 2019-10-28 12:46:37.812 | error | Caught by controller[0]: ^
host.ioBroker | 2019-10-28 12:46:37.812 | error | Caught by controller[0]: throw e
host.ioBroker | 2019-10-28 12:46:37.811 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88
host.ioBroker | 2019-10-28 12:46:36.555 | info | instance system.adapter.zigbee.0 started with pid 3287
host.ioBroker | 2019-10-28 12:46:06.500 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.ioBroker | 2019-10-28 12:46:06.499 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-10-28 12:46:06.499 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-28 12:46:06.499 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-28 12:46:06.499 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.ioBroker | 2019-10-28 12:46:06.498 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.ioBroker | 2019-10-28 12:46:06.498 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-10-28 12:46:06.498 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker | 2019-10-28 12:46:06.498 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-28 12:46:06.498 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-28 12:46:06.497 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-28 12:46:06.497 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.ioBroker | 2019-10-28 12:46:06.497 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker | 2019-10-28 12:46:06.497 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:46:06.496 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.ioBroker | 2019-10-28 12:46:06.496 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker | 2019-10-28 12:46:06.496 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.ioBroker | 2019-10-28 12:46:06.496 | error | Caught by controller[0]: ^
host.ioBroker | 2019-10-28 12:46:06.495 | error | Caught by controller[0]: throw e
host.ioBroker | 2019-10-28 12:46:06.494 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88
host.ioBroker | 2019-10-28 12:46:05.223 | info | instance system.adapter.zigbee.0 started with pid 477
host.ioBroker | 2019-10-28 12:45:35.119 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.ioBroker | 2019-10-28 12:45:35.119 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-10-28 12:45:35.119 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-28 12:45:35.118 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-28 12:45:35.118 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.ioBroker | 2019-10-28 12:45:35.118 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.ioBroker | 2019-10-28 12:45:35.118 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-10-28 12:45:35.117 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker | 2019-10-28 12:45:35.117 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-28 12:45:35.117 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-28 12:45:35.116 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-28 12:45:35.116 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.ioBroker | 2019-10-28 12:45:35.116 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker | 2019-10-28 12:45:35.115 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:45:35.115 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.ioBroker | 2019-10-28 12:45:35.114 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker | 2019-10-28 12:45:35.114 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.ioBroker | 2019-10-28 12:45:35.114 | error | Caught by controller[0]: ^
host.ioBroker | 2019-10-28 12:45:35.113 | error | Caught by controller[0]: throw e
host.ioBroker | 2019-10-28 12:45:35.112 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88
host.ioBroker | 2019-10-28 12:45:33.982 | info | instance system.adapter.zigbee.0 started with pid 30205
host.ioBroker | 2019-10-28 12:45:03.956 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.ioBroker | 2019-10-28 12:45:03.955 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-10-28 12:45:03.955 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-10-28 12:45:03.955 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker | 2019-10-28 12:45:03.955 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/node_modules/serialport/lib/bindings/linux.js:2:36)
host.ioBroker | 2019-10-28 12:45:03.955 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:81:44)
host.ioBroker | 2019-10-28 12:45:03.954 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-10-28 12:45:03.954 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker | 2019-10-28 12:45:03.954 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-10-28 12:45:03.954 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-10-28 12:45:03.954 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-10-28 12:45:03.953 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.ioBroker | 2019-10-28 12:45:03.953 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker | 2019-10-28 12:45:03.953 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:45:03.953 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.ioBroker | 2019-10-28 12:45:03.952 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker | 2019-10-28 12:45:03.952 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/cc-znp/node_modules/serialport/build/Release/serialport.node'
host.ioBroker | 2019-10-28 12:45:03.952 | error | Caught by controller[0]: ^
host.ioBroker | 2019-10-28 12:45:03.951 | error | Caught by controller[0]: throw e
host.ioBroker | 2019-10-28 12:45:03.951 | error | Caught by controller[0]: /opt/iobroker/node_modules/cc-znp/node_modules/bindings/bindings.js:88
host.ioBroker | 2019-10-28 12:45:02.625 | info | iobroker exit 0
host.ioBroker | 2019-10-28 12:45:01.653 | info | instance system.adapter.zigbee.0 started with pid 27270
host.ioBroker | 2019-10-28 12:45:01.599 | info | "system.adapter.zigbee.0" enabled
host.ioBroker | 2019-10-28 12:45:01.567 | info | iobroker host.ioBroker Adapter "system.adapter.zigbee.0" is started
host.ioBroker | 2019-10-28 12:45:01.565 | info | iobroker Adapter "zigbee" updated
host.ioBroker | 2019-10-28 12:45:01.499 | info | iobroker upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/admin.js admin.js application/javascript
host.ioBroker | 2019-10-28 12:45:01.347 | info | iobroker upload [1] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86plug.png img/86plug.png image/png
host.ioBroker | 2019-10-28 12:45:01.271 | info | iobroker upload [2] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw1.png img/86sw1.png image/png
host.ioBroker | 2019-10-28 12:45:01.196 | info | iobroker upload [3] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw2.png img/86sw2.png image/png
host.ioBroker | 2019-10-28 12:45:01.125 | info | iobroker upload [4] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ.png img/DIYRuZ.png image/png
host.ioBroker | 2019-10-28 12:45:01.054 | info | iobroker upload [5] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Eurotronic_Spirit_04.png img/Eurotronic_Spirit_04.png image/png
host.ioBroker | 2019-10-28 12:45:00.980 | info | iobroker upload [6] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/FLOALT.panel.WS.png img/FLOALT.panel.WS.png image/png
host.ioBroker | 2019-10-28 12:45:00.888 | info | iobroker upload [7] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/LH-32ZB.png img/LH-32ZB.png image/png
host.ioBroker | 2019-10-28 12:45:00.824 | info | iobroker upload [8] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/TRADFRI.bulb.E27.png img/TRADFRI.bulb.E27.png image/png
host.ioBroker | 2019-10-28 12:45:00.759 | info | iobroker upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/TRADFRI.remote.control.png img/TRADFRI.remote.control.png image/png
host.ioBroker | 2019-10-28 12:45:00.694 | info | iobroker upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara.switch.png img/aqara.switch.png image/png
host.ioBroker | 2019-10-28 12:45:00.618 | info | iobroker upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_bulb.png img/aqara_bulb.png image/png
host.ioBroker | 2019-10-28 12:45:00.541 | info | iobroker upload [12] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_curtain.png img/aqara_curtain.png image/png
host.ioBroker | 2019-10-28 12:45:00.477 | info | iobroker upload [13] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_numan_body_sensor.png img/aqara_numan_body_sensor.png image/png
host.ioBroker | 2019-10-28 12:45:00.413 | info | iobroker upload [14] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_temperature_sensor.png img/aqara_temperature_sensor.png image/png
host.ioBroker | 2019-10-28 12:45:00.348 | info | iobroker upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/basiczbr3.png img/basiczbr3.png image/png
host.ioBroker | 2019-10-28 12:45:00.284 | info | iobroker upload [16] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/battery_p.png img/battery_p.png image/png
host.ioBroker | 2019-10-28 12:45:00.200 | info | iobroker upload [17] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/battery_v.png img/battery_v.png image/png
host.ioBroker | 2019-10-28 12:45:00.134 | info | iobroker upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/bitron_plug.png img/bitron_plug.png image/png
host.ioBroker | 2019-10-28 12:45:00.069 | info | iobroker upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/contact.png img/contact.png image/png
host.ioBroker | 2019-10-28 12:44:59.999 | info | iobroker upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ctrl_ln1.png img/ctrl_ln1.png image/png
host.ioBroker | 2019-10-28 12:44:59.136 | info | iobroker upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/edp_redy_plug.png img/edp_redy_plug.png image/png
host.ioBroker | 2019-10-28 12:44:58.512 | info | iobroker upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/hive.png img/hive.png image/png
host.ioBroker | 2019-10-28 12:44:57.677 | info | iobroker upload [50] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/immax_e14.png img/immax_e14.png image/png
host.ioBroker | 2019-10-28 12:44:57.042 | info | iobroker upload [60] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/konke_kpft.png img/konke_kpft.png image/png
host.ioBroker | 2019-10-28 12:44:54.661 | info | iobroker upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/lumi_lock_v1.png img/lumi_lock_v1.png image/png
host.ioBroker | 2019-10-28 12:44:53.989 | info | iobroker upload [80] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/osram_a60_rgbw.png img/osram_a60_rgbw.png image/png
host.ioBroker | 2019-10-28 12:44:53.339 | info | iobroker upload [90] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_ambiance.png img/philips_hue_ambiance.png image/png
host.ioBroker | 2019-10-28 12:44:52.567 | info | iobroker upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_rwl021.png img/philips_hue_rwl021.png image/png
host.ioBroker | 2019-10-28 12:44:49.940 | info | iobroker Update "system.adapter.zigbee.0"
host.ioBroker | 2019-10-28 12:43:16.318 | info | iobroker npm install iobroker.zigbee@0.11.5 --loglevel error --production --save --prefix "/opt/iobroker" (System call)
host.ioBroker | 2019-10-28 12:43:16.313 | info | iobroker NPM version: 6.9.0

`

**Comment by Apollon77** [comment]
Did you alaso updated nodejs version?

host.ioBroker | 2019-10-28 12:45:03.953 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.ioBroker | 2019-10-28 12:45:03.953 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires

then please follow the "upgrade nodejs" instructions in forum
