### ISSUE TITLE
Support Senic Friends of Hue

### ISSUE THREAD

**Issue by Toki99** [ioBroker/ioBroker.zigbee#401]
Hallo, wird dieser geniale Schalter bereits unterstütz?

**Comment by Julius278** [comment]
> Hallo, wird dieser geniale Schalter bereits unterstütz?

Hallo Toki99, ich habe mir einen gekauft und die bisherigen Tests waren leider nicht erfolgreich.
Wenn mir jemand sagen kann, wie ich ihn anlernen muss, kann ich es testen.

MfG

**Comment by cmorlok** [comment]
No, these kind of switches are not yet supported. See https://github.com/Koenkk/zigbee-herdsman/issues/22

**Comment by juamiso** [comment]
> No, these kind of switches are not yet supported. See [Koenkk/zigbee-herdsman#22](https://github.com/Koenkk/zigbee-herdsman/issues/22)

But they are curently on development and planed to be supported
