### ISSUE TITLE
IKEA TRADFRI ON/OFF switch E1743 not yet in master branch

### ISSUE THREAD

**Issue by eviw** [ioBroker/ioBroker.zigbee#402]
Issue https://github.com/ioBroker/ioBroker.zigbee/issues/377 with IKEA TRADFRI ON/OFF switch E1743 has already been solved by @asgothian in test branch v 0.11.4. But it is not yet included in zigbee master v 0.11.5.
From where can I install it now?

**Comment by Albedorox** [comment]
> 
> 
> Issue #377 with IKEA TRADFRI ON/OFF switch E1743 has already been solved by @asgothian in test branch v 0.11.4. But it is not yet included in zigbee master v 0.11.5.
> From where can I install it now?

This relates to issue https://github.com/ioBroker/ioBroker.zigbee/issues/377 where @asgothian linked to dev branch 0.11.4 - after installing the button worked. 

However, it seems that @asgothian has commited to master branch now (6 days ago) as of https://github.com/asgothian/ioBroker.zigbee/pull/13

My question: Will this be fully implemented in the 0.11.6 update then? (sorry, I'm a newbie to Github)

**Comment by asgothian** [comment]
The switch should be working in the current 0.11.5. I am not sure there will be a 0.11.6 version.

A.

**Comment by arteck** [comment]
works
