### ISSUE TITLE
Ikea Symfonisk Remote Controller code

### ISSUE THREAD

**Issue by Againstyou** [ioBroker/ioBroker.zigbee#403]
Sorry, but since i dont get any reply on https://github.com/ioBroker/ioBroker.zigbee/issues/361
and im not sure if you check old issues, i now follow the official way and open a new issue, because Koenkk/Zigbee2MQTT supports this Controller now and you could implement the code in your Version too. :) This would be really nice! :)

Thanks in advance.

Koenkk/zigbee-herdsman-converters@1039b89

**Comment by ploebb** [comment]
Would be really nice to be integrated :-) Thanks!

**Comment by Againstyou** [comment]
push

**Comment by Againstyou** [comment]
Hey,
thanks for your work so far. :)
It would be really nice if some of you can reply on this issue. Is it possible to integrate the Symfonisk Remote Controller? If i can help you in any way, let me know.

**Comment by Againstyou** [comment]
reopend
