### ISSUE TITLE
Why not merge lumi.lock.v1 support?

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.zigbee#404]
Hi
I found bluefox create a pr to add lumi.lock.v1 support.
Why not merge this?
Can not wait to use this! Because I use this lock in my home :)

**Comment by kirovilya** [comment]
??? Already supported https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devstates.js#L2551
what is your adapter version?

**Comment by SchumyHao** [comment]
Opps, I found my lock is different...
<img width="308" alt="Screen Shot 2019-11-01 at 7 29 30 AM" src="https://user-images.githubusercontent.com/4982108/67992871-678c4880-fc79-11e9-86b5-4ae979cde2b7.png">

Lock looks like [this](https://www.youtube.com/watch?v=-eb9oF2AoGw) 

How can I support this device?

**Comment by kirovilya** [comment]
This device is not exists yet in the common base https://github.com/Koenkk/zigbee-herdsman-converters
If this lock is the same in functionality as 'Vima Smart Lock', then just add model 'lumi.lock.aq1' to the local files: 
* device.js https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L658 
* and devstates.js https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devstates.js#L2551 .
and check

**Comment by kirovilya** [comment]
But most likely this is a different lock and we need to deal with its commands

**Comment by SchumyHao** [comment]
Thanks @kirovilya

**Comment by kirovilya** [comment]
Is it work like 'lumi.lock.v1' or need to add new device?

**Comment by SchumyHao** [comment]
This device is more like lumi.lock.acn02
I need more time to add this device support.

shepherd is achived? Newest ioBroker.zigbee using shepherd or herdsman?
