### ISSUE TITLE
Support TRÅDFRI LED-Leuchtmittel E27 806 lm und TRÅDFRI LED-Leuchtmittel GU10 400 lm

### ISSUE THREAD

**Issue by martinez81** [ioBroker/ioBroker.zigbee#406]
Hi,
ich habe am Samstag zwei neu verfügbare IKEA Lampen gekauft.
Leider kann man sie noch nicht steuern.
Sie sind zwar mit dem zigbee Adapter im ioBroker verbunden, aber es kommt die Meldung "unbekanntes Gerät".
https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-e27-806-lm-kabellos-dimmbar-warmes-tageslicht-opalweiss-90408797/

https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-400-lm-kabellos-dimmbar-warmes-tageslicht-60420041/

Wann kommt ein update für den Adapter? Kann ich irgendwie unterstützen?
Grüße

**Comment by Narolakk** [comment]
evtl.kann man sie hinzufügen wie ich es mit der LED1732G11 gemacht habe, da ich die Lampen nicht selber besitze kann ich es nicht ausprobieren.

[https://github.com/ioBroker/ioBroker.zigbee/issues/344#issuecomment-549114410](url)

**Comment by martinez81** [comment]
Danke, das probiere ich aus!! Wo finde ich die Files?

**Comment by Jonfried92** [comment]
für die Speicherorte der FIles gucke auch in dem Post:
[Link](https://github.com/ioBroker/ioBroker.zigbee/issues/344#issuecomment-549737655)

**Comment by Narolakk** [comment]
Denk daran das die Lampe aus dem Link auch die Farbtemperaturen ändern können, die von dir genannten nicht, so am besten ein Datenpunkt als Beispiel nehmen der auch zu den neuen Lampen passt.

**Comment by martinez81** [comment]
Ja, guter Hinweis! Heute Abend komme ich dazu. Ich werde berichten...

**Comment by martinez81** [comment]
Moin!
Hat super funktioniert :) Vielen Dank nochmals.
(Nur das Verzeichnis hat nicht ganz gestimmt, ich habe mir die Datei dann über loacte gesucht. Eine kleine Erklärung schreibe ich in den anderen Thread.)
