### ISSUE TITLE
Converter issue with lumi.sensor_motion.aq2

### ISSUE THREAD

**Issue by baustoff** [ioBroker/ioBroker.zigbee#41]
I just paired the AQARA motion sensor lumi.sensor_motion.aq2 successfully and configured it via Blockly-Script to turn on lights when motion recognized. My goal is to keep the the sensor recognizing new motions immediatly, after first motion recognition.

By default the motion-sensor = occupancy is set to true when motion recognized and it remains in status true for exactly 60 sec. This means that the sensor is not able to recognize new motions within the 60 seconds.
Therefore I force the occupancy value via Blockly-Script from true to false after 3 secs, when motion has been recognized. Actually it worked for a while very good and as intended , but after 4-5 hours I am facing the following issues:

1) I receive this error-msg in the logs:
<img width="769" alt="converter" src="https://user-images.githubusercontent.com/42436242/44207188-95609c80-a15c-11e8-9fe7-e7867b8e1a4d.png">

2) After forcing it to false via script, the value doesn't switch to true anymore for exactly 60 sec, even if I move myself directly in front of the sensor. So within this 60 sec no new motion recognition is possible.

It it possible to fix this?

I've installed iobroker.zigbee 0.7.1 and zigbee-shepherd-converters v2.0.42

Thank you in advance.

**Comment by kirovilya** [comment]
Okay, I'll see how I can fix it.

**Comment by kirovilya** [comment]
The error in the picture is because there is no reaction to the event of changing the value of the `occupancy`. It would not have appeared if you had not changed the state value. It is normal.

I can make option for this sensor - `timeout` and remove occupancy status. In next version...

**Comment by baustoff** [comment]
That sounds great. With this solution it would be possible to change the timeout-value from 60 secs (default) to 3 secs for instance?

**Comment by kirovilya** [comment]
@baustoff I think so yes. from 0 to 60 for instance.

**Comment by baustoff** [comment]
@kirovilya that would be just perfect and hopefully the solution for my issue :)
I would be very happy and thankful if you insert this feature in your next release.

Thank you so much and keep up the great work!
Have a nice evening :)

**Comment by Smarti15** [comment]
I have the same problem with a Xiaomi motion sensor. I force the occupancy after 3 seconds and then this message appears in the logfile:


zigbee.0 | 2018-08-18 22:04:41.465 | debug | Publish {"occupancy":false}
-- | -- | -- | --
zigbee.0 | 2018-08-18 22:03:44.494 | error | No converter available for 'RTCGQ01LM' with key 'occupancy'
zigbee.0 | 2018-08-18 22:03:44.490 | debug | User  stateChange zigbee.0.00158d0001a8fa29.occupancy  {"val":false,"ack":false,"ts":1534622624485,"q":0,"from":"system.adapter.javascript.0","lc":1534622624485}
zigbee.0 | 2018-08-18 22:03:41.465 | debug | Publish {"occupancy":true}
zigbee.0 | 2018-08-18 22:03:41.465 | debug | Device 0x00158d0001a8fa29 emit event attReport with data:{"cid":"msOccupancySensing","data":{"occupancy":1}}
zigbee.0 | 2018-08-18 22:03:41.464 | debug | handleMessage.   {"type":"attReport","endpoints":[{"device":{"_id":3,"type":"EndDevice","ieeeAddr":"0x00158d0001a8fa29","nwkAddr":41692,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId

**Comment by kirovilya** [comment]
Added `occupancy_timeout` state for motion sensor.
Check it out on dev branch, please. https://github.com/ioBroker/ioBroker.zigbee/tarball/dev

**Comment by Smarti15** [comment]
THX ;) but how can i use occupancy_timeout?

**Comment by kirovilya** [comment]
@Smarti15 for example, set `occupancy_timeout` state to 10 sec and when occupancy event was fire, it will drop after 10 sec.

**Comment by Smarti15** [comment]
Ah, I do not have to set the state to false as the state if the motion sensor reacts to a motion after about 5 seconds. Now the state resets itself to false after the specified timeout?

**Comment by kirovilya** [comment]
@Smarti15 Yes, you need it? :)

**Comment by Smarti15** [comment]
Hinweise zum Datenschutz bei Google
Später erinnern
Ansehen
Suchergebnisse
Ergebnis zur Übersetzung

Ich habe gestern die Version probiert. Mein Blockly-Script ist so auf gebaut, das es bei Bewegung eine Lampe einschaltet, der Occupancy-Wert des Bewegungs Sensors nach 5 Sekunden auf "false" gesetzt wird und die Lampe nach 15 Sekunden sich wieder ausschaltet. Nun hab ich am Rechner im ioBroker unter Objekte den Wert Occupancy beobachtet und bin immer wieder in den Bewegungs-Sensor gelaufen. Nach 5 Sekunden geht er auf "false" und sobald er eine Bewegung registriert geht er wieder auf "true" Soweit passt alles und funktioniert. Die Lampe hab ich so eingestellt, das sie nach 15 Sekunden ausschaltet, außer der Bewegungs-Sensor registriert einen neue Bewegung, dann werden die 15 Sekdunden zurückgesetzt und laufen wieder von 0 los. Eigentlich funktioniert alles,  muss aber nochmal einen Langzeittest machen. Einziges Manko ist aber leider immer noch die Fehlermeldung im Log: "No converter available for 'RTCGQ01LM' with key 'occupancy'" 

I tried the version yesterday. My blockly script is built to turn on a lamp when moving, the occupancy value of the motion sensor is set to false after 5 seconds, and the lamp turns off after 15 seconds. Now I have observed on the computer in the ioBroker under objects the value of occupancy and have repeatedly run into the motion sensor. After 5 seconds he goes to "false" and as soon as he registers a movement he goes back to "true". Everything fits and works. The lamp is set to turn off after 15 seconds, unless the motion sensor registers a new motion, then the 15 seconds are reset and run again from zero. Actually everything works, but has to do a long-term test again. The only drawback is unfortunately still the error message in the log: "No converter available for 'RTCGQ01LM' with key 'occupancy'"

Blockly Script:
http://www.bilder-upload.eu/show.php?file=5efc26-1536915810.png

**Comment by kirovilya** [comment]
@Smarti15 "No converter available for 'RTCGQ01LM' with key 'occupancy'" - your script should not change the value of "occupancy"!!!

**Comment by kirovilya** [comment]
@Smarti15 use "occupancy_timeout" instead

**Comment by Smarti15** [comment]
Unfortunately does not work. As already described by Baustoff, it works the first time and then he sets himself after about 60 seconds again a movement. With my version, it works very well, but unfortunately you get an error message in the log. Unfortunately, the new data point did not work.

**Comment by kirovilya** [comment]
Hmm. I have RTCGQ11LM sensor. Did it work like you want https://youtu.be/tCy7rPVPi7Q ?

**Comment by baustoff** [comment]
Actually it did work like in your video, but...

1) After 3-5 hours it still switch occupancy from to true to false but afterwards it won’t recognize any new motion within 60 secs, as I already described above.

2) Changing the default time-out value or forcing the occupancy value has massive impact on battery drain. On one day within 4-5 hours battery dropped from ~100% to almost 65%.

KR
baustoff

**Comment by kirovilya** [comment]
1. I can not confirm this. I do not use the sensor all the time.

2. Occupancy timeout is a software solution. So this is the problem of the sensor itself.

What's next? Do we leave the timeout or remove it?

**Comment by Smarti15** [comment]
Thank you for the many time and effort. I'll probably just get another motion sensor that will make shorter timings possible.

**Comment by kirovilya** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/270#issuecomment-414999973
