### ISSUE TITLE
Support for new IKEA Tradfri bulbs LED1842G3 (E27 250 lm)

### ISSUE THREAD

**Issue by andromedi4** [ioBroker/ioBroker.zigbee#411]
Hello, could you add support for IKEA tradfri bulbs LED1842G3 (E27 250 lm)
https://www.ikea.com/fi/fi/p/tradfri-led-lamppu-e27-250-lm-langaton-himmennettaevae-laemmin-hehku-pallonmuotoinen-ruskea-kirkas-lasi-70455676/

I`ve this lamp and so I will be able to help.
Thank you!

**Comment by MikeEcho0815** [comment]
For me it's still not working with 0.11.5 ("TRADFRI on/off switch" not described in statesMapping.)
Schould it work or is it still not implemented?

**Comment by schmidti2007** [comment]
Hey there! I ve read something in Forum that it should be supported in 0.11.5. In the device list of zigbee2mqtt it is already listed. Any news yet?

Thank you!

**Comment by andromedi4** [comment]
Yes, I saw in device list of zigbee2mqtt, but in my instalation 0.11.5, this lamp still don`t work :(
Does anyone have any idea?

**Comment by schmidti2007** [comment]
I am still very new in the topic and a bit confused how everything works together. I could find out that these ikea bulbs are still in the devices.js in 10.2.7 shepherd converter. But it is missing in the devstates.js. Can i simply add it there? Can someone explain it to me?

**Comment by schmidti2007** [comment]
I added the device in my Herdsman fork and started pull request (Herdsman #431). But it wont take place in the master branch. Only herdsman is developed further.

**Comment by mickym2** [comment]
Look to #440 and #434 - what we find out - at least I got my bulbs running now. ;)

**Comment by hauschablous** [comment]
Indeed, fixed for me too.
Here´s what I did:

1. Via SSH-Connection navigate to folder `cd /opt/iobroker/node_modules/iobroker.zigbee/lib`

2. Stop iobroker and create a Backup of devstates.js 
`iobroker stop`
`sudo mv devstates.js devstates_backup.js`

3. Edit File `sudo nano devstates_backup.js`

4. Scroll down to where the individual devices are described. That looks somewhat like this:
// IKEA
{
        vendor: 'IKEA',
        models: [....

5. Right after //IKEA add the following lines:
{
        vendor: 'IKEA',
        models: [
            'TRADFRI bulb E27 WW clear 250lm',
        ],
        icon: 'img/TRADFRI.bulb.E27.png',
        states: lightStatesWithColortemp,
        linkedStates: [comb.brightnessAndState],
    },

6. Save the file and name it devstates.js

7. Restart your Device `sudo reboot`

**Comment by arteck** [comment]
works
