### ISSUE TITLE
Update Zigbee2MQTT 1.7.0

### ISSUE THREAD

**Issue by oHa510** [ioBroker/ioBroker.zigbee#413]
Hi, can you please merge new Zigbee2MQTT 1.7.0 release to this adapter? :)

That would be great!

https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.7.0

greets

**Comment by allofmex** [comment]
Work  progress https://github.com/ioBroker/ioBroker.zigbee/issues/324
You may help...
