### ISSUE TITLE
Aqara Devices do not Connect

### ISSUE THREAD

**Issue by ac1dwalk3r** [ioBroker/ioBroker.zigbee#414]
After having a good experience with xiaomi mijia bodymovement and window contacts, i can absolutely find no way to connect aqara window contacts (https://www.zigbee2mqtt.io/devices/MCCGQ11LM.html) and aqara temp and humidity sensor (https://www.zigbee2mqtt.io/devices/WSDCGQ11LM.html) 
in the pairing countdown in iobroker ui is absolutely no reaction. all other devices (4 at all) are connecting without a problem. pairing the devices with the xiaomi hub is no problem. interestingly, there are a few posts, that declare that they connect without a problem to iobroker. i've already reinstalled the adapter, tried it in another environment (windows instead of raspbian), deactivated other zigbee gateways, tried other methods of pressing the reset button of the device, but nothing.

the log in debug mode does not show any sign of recognizing the devices. it's as if they are invisible. 

Im Using a CC2531 Stick with antenna (https://www.amazon.de/gp/product/B07T25WSB4/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1)

**Comment by vain90** [comment]
Did you already try to press the reset button every 2 seconds after pressed it for 5 seconds?
This should help that the sensor doesn't go into standby...

**Comment by ac1dwalk3r** [comment]
Yes, i've also tried it with 1 seconds, 2 seconds, 7 seconds and 10 seconds, still no reaction.....same with eurozronic spirit zigbee. Arrived just a few hours ago, no reaction.

Ikea and mijia devices still work without a problem. Also no difference with different versions of the zigbee adapter

**Comment by M3talHe4d** [comment]
I have the same issue with the Aqara Motion Sensor. I bought this one because it is on the supported devices list but now I can't find a way to pair it.

**Comment by ac1dwalk3r** [comment]
After too many failed pairings and bug searches, I've decided to give the deconz zigbee system a try. Seems a bit more professional, ans should also be compatible with all my devices....hopefully a real compatiblity^^

**Comment by M3talHe4d** [comment]
I got mine working now... Themes like it just needed some more attempts. I talked to a an other guy who has aqara devices and he has the same issue. Some of these seem to need up to 10 pairing attempts till they work and on some you have to keep pressing the button every second (but not on everyone).  Seems to be a problem of the sensor itself. After getting them paired however, they work just fine.

**Comment by ac1dwalk3r** [comment]
Cool! But this still isn't a proof that it's the sensors fault. As i said, all of them connect in seconds with xiaomi mijia hub. This is bug. But i can't say if it's from zigbee2mqtt or from the zigbee adapter or from the cc2531 firmware.
Does anyone run an openhub instance to try?

**Comment by MikeEcho0815** [comment]
For me it seems to help to "Soft-Reset" the Stick, especially if i add more than one device... That upped my chances of successfully pairing a lot.
