### ISSUE TITLE
Eurotronic SPZB0001 heater thermostat stops responding

### ISSUE THREAD

**Issue by M3talHe4d** [ioBroker/ioBroker.zigbee#418]
I have a Eurotronic SPZB0001 heater thermostat with the cc21531, wich works fine after I paired it, but every time I restart my raspberry (model 3b+ where my iobroker is running) or unplug and replug the zigbee usb, the thermostat stops responding to any command. When this happens, the network map changes from the Eurotronic being a child of the coordinator to seemingly having 2 parents (the coordinator and one of my Osram CLA60 Z3 lights).
When I try to control it there is an error massage in the log:

Zigbee publish to '0x00158d0001ffc383', hvacThermostat - write - [{"attrId":16387,"dataType":41,"attrData":2200}] - 1 failed with error Error: AF data request fails, status code: 240. MAC transaction

Im using version 0.11.5 of the zigbee adapter.
The only way to get it back to work is to delete the thermostat and repair it. Does anybody know how to solve this or has a similar issue?

**Comment by allofmex** [comment]
It takes a while until the thermostat rejoins the new network. Some devices are fast, others do not check that frequent about changes (battery saving?)

Be patient, my 6 Eurotronic automatically rejoin. They also need to receive the configuration first, before acting as before

**Comment by M3talHe4d** [comment]
Hmmm... I already thought about something like this and did wait without luck, but maybe i wasn't patient enough... Do you have an approximate time it normally takes till they work again? Is it like minutes or more like an hour?
I will now disconnect the stick on purpose an then see if it starts to work again...

**Comment by allofmex** [comment]
Are you using the [SourceRouting](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin) firmware?
Please try the default one, else the route does not get updated correctly in some cases, see https://github.com/Koenkk/zigbee2mqtt/issues/1408

**Comment by M3talHe4d** [comment]
OK, I solved it by simply re-flashing the firmware on the stick. I was pretty sure I did use default all the time... Maybe I fetched the wrong file the first time or something went wrong during the flash... don't know...
However - it's solved.
