### ISSUE TITLE
Please implement Ikea Tradfri Remote

### ISSUE THREAD

**Issue by worf0r** [ioBroker/ioBroker.zigbee#42]
Dear Team,

many Tradfri Devices are bundled with this remote:
https://www.ikea.com/de/de/catalog/products/30338849/

Currently it is not supported by the adapter. I cannot even pair it.

I could give support for the integration if needed.

**Comment by kirovilya** [comment]
:)
:(
I have such a remote. I even paired it with the coordinator.
But I can not get any events from it https://github.com/Koenkk/zigbee2mqtt/issues/102

**Comment by worf0r** [comment]
Ok, I see. Then we can close this issue and use the already opened...

**Comment by worf0r** [comment]
I think we should definitly work this out. But as I see in the other thread, it's not easy.

Tradfri pairs the button with the lights. As a group. And not the lights directly to the coordinator. That's the main difference.

**Comment by kirovilya** [comment]
Added in 0.9.0
But you need to find group of your remote. Described here https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/getting_started/pairing_devices.md#ikea-tradfri-remote-control-e1524
Then you need to add this group in adapter admin-page

**Comment by Thomas1305** [comment]
i wanna do this, but i can´t find the 
configuration.yaml file.
can someone tell me i can find it?

**Comment by kirovilya** [comment]
@Thomas1305  https://github.com/ioBroker/ioBroker.zigbee/issues/178

**Comment by hehljo** [comment]
> @Thomas1305 #178

The link to find out the group doesn‘t work anymore. I can‘t find my self how to get the group of the remote.

**Comment by Thomas1305** [comment]
First you have to do this
http://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html
Than this
http://www.zigbee2mqtt.io/information/binding.html
at Ikea TRADFRI remote control E1524

**Comment by kirovilya** [comment]
@Thomas1305 @hehljo If you flash last coordinator firmware https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator so you not need sniff and add group

**Comment by Thomas1305** [comment]
Oh okay, i'll try it.
Maybe thats the reason why the remote dont work even with the group?

**Comment by kirovilya** [comment]
hmm... did it work before?

**Comment by Thomas1305** [comment]
Yes it did.

**Comment by kirovilya** [comment]
then it should work

**Comment by Thomas1305** [comment]
I will flash the Stick tomorrow and give you a Info.
Thanks

**Comment by Thomas1305** [comment]
One more question.
Should i update the zigbee-shepherd-converters from Koenkk, or do i have always the latest version if i install the zigbee from https://github.com/ioBroker/ioBroker.zigbee??
Thanks in advance.

**Comment by kirovilya** [comment]
You only need installed iobroker.zigbee from latest repository (0.10.2)

**Comment by Thomas1305** [comment]
It's the link from above, isn't it?
I installed it from there, but iobroker shows Version 0.9.2
Or have i to deinstall it first?

**Comment by Thomas1305** [comment]
@kirovilya 
works fine with new coordinator firmware and zigbee repository 0.10.2
don´t need the group any more
thx

**Comment by hehljo** [comment]
So i have to buy a CC Debugger to get  the remote working? I bought a CC2531 stick programmed with the Firmware from January 2019.

**Comment by Thomas1305** [comment]
@hehljo
Or you send it to me and i'll flash it
Where you from?

**Comment by hehljo** [comment]
Haha i think it could be a bit difficult. I'm from Germany :D
I should buy a CC Debugger for future firmware Updates.

**Comment by Thomas1305** [comment]
Yes you should.
And I'm from Germany/bavaria :-)

**Comment by hehljo** [comment]
Oh, that's a very big concidence! Im from bavaria, too. I'm living in Augsburg (Gersthofen) and you?

**Comment by Thomas1305** [comment]
In Kissing bei Augsburg.
Was ein Zufall :-)
