### ISSUE TITLE
Group limitation to 3?

### ISSUE THREAD

**Issue by asteingass** [ioBroker/ioBroker.zigbee#420]
I moved all of my Osram Lightify B40 TW bulbs to the zigbee adapter. Now I wanted to group them. In my bedroom I have 3 bulbs and grouped them together this is working fine. In my livingroom I have 4 bulbs, I also but all of these 4 into one new group, but it's always only triggering 3 of them. Are there any limitations?
I'm using version 0.11.3, this is the newest I get.
Adapter is CC2531 with the newest 3.0.X firmware
And have in total 13 devices connected

**Comment by allofmex** [comment]
Your version is outdated.
Please update to 0.11.5, there was a fix added in https://github.com/ioBroker/ioBroker.zigbee/pull/386

**Comment by asteingass** [comment]
How can I update to the 0.11.5? For me it's just showing 0.11.3 and "iobroker upgrade zigbee" tells me I'm on the newest version.

**Comment by asteingass** [comment]
Worked with 0.11.5 thanks
