### ISSUE TITLE
Anfrage: Ikea Rollos hinzufügen

### ISSUE THREAD

**Issue by Buhu91** [ioBroker/ioBroker.zigbee#425]
Hallo, ist es möglich, die beiden Smarten Rollos von IKEA FYRTUR und KADRILJ hinzuzufügen?

Im Zigbee2Mqtt sind die beiden ebenfalls schon enthalten. https://www.zigbee2mqtt.io/information/supported_devices.html

Gruß

**Comment by asgothian** [comment]
in meinem Repository gibt es einen Test branch (herdsman) in dem zumindest Fyrtuyr integriert ist. 
Bitte testen und kommentieren
Wichtig: der Branch basiert auf dem herdsman branch des zigbee adapters (version 1.0.0-a).

**Comment by arteck** [comment]
works
