### ISSUE TITLE
Konke Geräte werden nicht erkannt

### ISSUE THREAD

**Issue by tsappo** [ioBroker/ioBroker.zigbee#426]
Habe mir den Konke 2AJZ4KPBS (motion) und den Konke 2AJZ4KPFT (temperature) besorgt.

Meldungen beider erscheinen als "Unknown device model..." im log.

Laut changelog sollten beide in der 0.11.3 (2019-09-11) hinzugefügt worden sein.

<img width="392" alt="Bildschirmfoto 2019-11-27 um 12 59 19" src="https://user-images.githubusercontent.com/56339290/69721713-bd87cb00-1115-11ea-81b1-8f098c60fd33.png">

**Comment by arteck** [comment]
Die wurden nicht richtig erkannt wenn da unknown steht..weiter versuchen

**Comment by tsappo** [comment]
Habe jetzt ca. 20 mal gelöscht neu angelernt.
Am coordinator an jedem router getestet..nichts geht...
Hier am Beispiel des Bewegungsmelders:

<img width="471" alt="Bildschirmfoto 2019-11-29 um 16 12 13" src="https://user-images.githubusercontent.com/56339290/69877645-0335c680-12c3-11ea-9484-b42a64bfb5ea.png">
einwandfrei gepairt.

<img width="394" alt="Bildschirmfoto 2019-11-29 um 16 13 04" src="https://user-images.githubusercontent.com/56339290/69877684-219bc200-12c3-11ea-8b73-b86ec7e855c1.png">
nicht erkannt.

<img width="1471" alt="Bildschirmfoto 2019-11-29 um 16 15 19" src="https://user-images.githubusercontent.com/56339290/69877796-73444c80-12c3-11ea-813f-dac21e239b10.png">
Im log 

<img width="925" alt="Bildschirmfoto 2019-11-29 um 16 16 45" src="https://user-images.githubusercontent.com/56339290/69877883-a4bd1800-12c3-11ea-807e-0be0fc9fd130.png">
bei den Objekten
