### ISSUE TITLE
Support for Aqara Opple Wireless Switch?

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#427]
Hello Could u add an Support for the Arara Opple Wireless Switch? lumi.remote.b486opcn01

https://www.banggood.com/de/Original-Aqara-OPPLE-Wireless-International-Version-Smart-Switch-Work-With-Apple-HomeKit-Xiaomi-Eco-System-p-1588700.html?gmcCountry=DE&currency=EUR&createTmp=1&utm_source=googleshopping&utm_medium=cpc_bgs&utm_content=frank&utm_campaign=frank-ssc-de-all-0827-13-19bf-v2&ad_id=379628630321&gclid=CjwKCAiA_f3uBRAmEiwAzPuaMzX7Z1gET3dAE4tvMDhKZgvV6J_X21EpeZdO_z-M5bZcMVPOiNDa4xoCsm8QAvD_BwE&ID=6280215&cur_warehouse=CN

**Comment by arteck** [comment]
Check herdsman brunch

**Comment by Gwoony** [comment]
What do u mean? I’m not the pro 😊

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/tarball/herdsman

**Comment by Gwoony** [comment]
Okay and what should i do with the tar file? Sorry for stupid question :-)

**Comment by kirovilya** [comment]
@Gwoony install adapter from this url to iobroker

**Comment by Gwoony** [comment]
I have do this... after nothing works ;-) and I reinstall the master branch

**Comment by kirovilya** [comment]
![image](https://user-images.githubusercontent.com/8360230/70127113-6fca1000-168b-11ea-83c4-dc730d81bd26.png)

**Comment by kirovilya** [comment]
![image](https://user-images.githubusercontent.com/8360230/70127193-9ab46400-168b-11ea-868b-be661f591c55.png)

**Comment by Gwoony** [comment]
But doesn’t work with herdsman 1.0.0.b

**Comment by Gwoony** [comment]
And doesn't work with version 1.0.0.c
