### ISSUE TITLE
Add Request: Philips Hue White Color Ambiance GU10 (with Bluetooth) 

### ISSUE THREAD

**Issue by snowface83** [ioBroker/ioBroker.zigbee#429]
Hello, could you please add support for Philips Hue White Color Ambiance GU10 5.7w (Bluetooth)  spot with 350 lm? 

My installed Zigbee adapter version is: 0.11.5

And I got following device infos: 

![image](https://user-images.githubusercontent.com/58345945/69891295-d81b9900-12fb-11ea-9323-b3a9f681a22d.png)

![image](https://user-images.githubusercontent.com/58345945/69891310-fd100c00-12fb-11ea-916f-c22929ff9247.png)

And RAW data: 

> {
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1575064835175,
  "common": {
    "name": "LCG002",
    "type": "LCG002",
    "icon": "img/unknown.png"
  },
  "native": {
    "id": "0017880106ba01ad"
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "zigbee.0.0017880106ba01ad",
  "type": "device"
}

![image](https://user-images.githubusercontent.com/58345945/69891451-eddd8e00-12fc-11ea-9578-e85f6353c2bb.png)

**Comment by snowface83** [comment]
Hi, is there something new or did i miss the implementation of the lamp? 
Hi, gibt es hierzu etwas neues oder wurde die Lampe vielleicht sogar schon hinzugefügt?

**Comment by Strunzdesign** [comment]
This bulb works for me on adapter 1.0.4. I have the Bluetooth-ready LCG002. However, the picture provided by the adaptor is not correct yet. It still shows the bigger bulb reflecting the older version, not the smaller form factor.

So, please just include the picture provided in this bug report to the adaptor.

**Comment by Strunzdesign** [comment]
After my pull request merged was please test (works for me already)... then this bug can be closed.
