### ISSUE TITLE
Hue for Yahka Adapter

### ISSUE THREAD

**Issue by worf0r** [ioBroker/ioBroker.zigbee#43]
Hi team,

I want to add my IKEA TRADFRI bulb E27 CWS opal 600lm with RGB support to the IOBroker Yahka Adapter for HomeKit Usage.

But:
ioBroker.zigbee wants an RGB value for the colors

Yahka gives only a hue value from 0 to 360. Ist there a way to make this compatible?

**Comment by kirovilya** [comment]
Yahka also need saturation! So, need special convertation from RGB to hue+sat and back.
Like this:
https://forum.iobroker.net/viewtopic.php?f=21&t=13730&p=145649&hilit=saturation#p145649 
or
https://forum.iobroker.net/viewtopic.php?f=26&t=13737&p=145694&hilit=saturation#p145694
Try to find solution on forum.

**Comment by worf0r** [comment]
Here is my solution für TRADFRI bulb in yahka when paired to Zigbee Adapter:

`createState('RGBBulbs.Wohnzimmer.Stehlampe.Hue', {
    name: 'Hue',
    desc: 'Hue im HomeKit-Format'
});

createState('RGBBulbs.Wohnzimmer.Stehlampe.Saturation', {
    name: 'Saturation',
    desc: 'Saturation im HomeKit-Format'
});

function setRGB(r, g, b, id){
    var val = ''+('00'+r.toString(16)).slice(-2)+('00'+g.toString(16)).slice(-2)+('00'+b.toString(16)).slice(-2);
    //console.log(val);
    setState(id, val);
}

function hsvToRgb(h, s, v) {
    var r, g, b;
    var i;
    var f, p, q, t;
     
    // Make sure our arguments stay in-range
    h = Math.max(0, Math.min(360, h));
    s = Math.max(0, Math.min(100, s));
    v = Math.max(0, Math.min(100, v));
     
    // We accept saturation and value arguments from 0 to 100 because that's
    // how Photoshop represents those values. Internally, however, the
    // saturation and value are calculated from a range of 0 to 1. We make
    // That conversion here.
    s /= 100;
    v /= 100;
     
    if(s === 0) {
        // Achromatic (grey)
        r = g = b = v;
        return [
            Math.round(r * 255), 
            Math.round(g * 255), 
            Math.round(b * 255)
        ];
    }
     
    h /= 60; // sector 0 to 5
    i = Math.floor(h);
    f = h - i; // factorial part of h
    p = v * (1 - s);
    q = v * (1 - s * f);
    t = v * (1 - s * (1 - f));
     
    switch(i) {
        case 0:
            r = v;
            g = t;
            b = p;
            break;
     
        case 1:
            r = q;
            g = v;
            b = p;
            break;
     
        case 2:
            r = p;
            g = v;
            b = t;
            break;
     
        case 3:
            r = p;
            g = q;
            b = v;
            break;
     
        case 4:
            r = t;
            g = p;
            b = v;
            break;
     
        default: // case 5:
            r = v;
            g = p;
            b = q;
    }
     
    return [
        Math.round(r * 255), 
        Math.round(g * 255), 
        Math.round(b * 255)
    ];
}


on({id:"javascript.0.RGBBulbs.Wohnzimmer.Stehlampe.Hue"/*Hue*/, ack: false, change: 'any'}, function (obj) {
 var hue = parseInt(obj.state.val);
    var sat = parseInt(getState("javascript.0.RGBBulbs.Wohnzimmer.Stehlampe.Saturation"/*Saturation*/).val);
    //console.log(hue + '  ' + sat);
    var res = hsvToRgb(hue, sat, 100);
    //console.log(res);
    setRGB(parseInt(res[0]), parseInt(res[1]), parseInt(res[2]), "zigbee.0.----------------.color"/*Color*/);
});`

The Yahka Device gets RGBBulbs.Wohnzimmer.Stehlampe.Hue and RGBBulbs.Wohnzimmer.Stehlampe.Saturation as setting.
