### ISSUE TITLE
LEDVANCE Z3 Plug

### ISSUE THREAD

**Issue by Moeinator** [ioBroker/ioBroker.zigbee#435]
the new Osram Plug come from LEDVANCE in the version Z3 (Zigbee 3) I can not integrate this unfortunately in the Zigbee adapter.

get as in pictures the following answers in the Zigbee adapter.

I'm sorry for my bad english. I come from Germany

![2BD98A09-194F-4CA7-B5B2-DD6365433964](https://user-images.githubusercontent.com/58535071/70387543-8ed7e300-19a6-11ea-9d03-3028c71a8772.png)

![F4B27714-4009-42FF-AEFA-A461B96B1EAE](https://user-images.githubusercontent.com/58535071/70387544-8ed7e300-19a6-11ea-96d8-dabde22439d9.png)

**Comment by runam0K** [comment]
I have the same problem. I could not pair the Ledvance Smart+ Plug.

Is it not yet supported, even though it is identical to Osram?
Are there any plans to implement it?

**Comment by highseen** [comment]
Hey guys, same her. Would like to add the Z3 Plug.

Found the device at the zigbee-herdsman-converters project:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js

`
{
        zigbeeModel: ['Plug Z3'],
        model: 'AC10691',
        description: 'Smart+ plug',
        supports: 'on/off',
        vendor:  'OSRAM',
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            let endpoint = device.getEndpoint(3);
            // Endpoint 3 is not always present, use endpoint 1 in that case
            // https://github.com/Koenkk/zigbee2mqtt/issues/2178
            if (!endpoint) endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
        },
    },
`

**Comment by highseen** [comment]
Maybe this could be solved fairly easy and quick. Added a pull request:
#446

**Comment by arteck** [comment]
works in herdsman
