### ISSUE TITLE
Ikea Tradfri motion sensor E1745

### ISSUE THREAD

**Issue by oswaldo-be** [ioBroker/ioBroker.zigbee#436]
As mentioned [here ](https://github.com/ioBroker/ioBroker.zigbee/issues/375)we cannot get it paired.
Can anybody please help?`
Thank you very much 

Okay, I just could pair it but value in battery, link quality, no motion and occupancy stays empty

**Comment by chr-jordan** [comment]
can conform that. Didn't get any motion or occupancy value.

**Comment by Nuggelbeb** [comment]
Hallo, 
also das Paaren hat mit 4 x schnelles drücken der Verbindungstaste funktioniert,
aber leider gibt es keine Daten und Bewegungsreaktion.

![image](https://user-images.githubusercontent.com/46019514/72091058-9e34ae00-330f-11ea-9dfa-940c8ac70010.png)

**Comment by Gwoony** [comment]
Hmm komisch... bei mir zeigt es alles außer die Batterie...

Kann der Sensor generell die Helligkeit ausgeben? Leider gehen bei mir alle Lichter immer an 🙃

**Comment by Nuggelbeb** [comment]
> Hmm komisch ... bei mir zeigt es alles außer die Batterie ...
> 
> Kann der Sensor generell die Helligkeit ausgeben? Leider gehen bei mir alle Lichter immer an🙃

Hallo Gwoony,
es ist der gleiche Sensor wie [hier](https://github.com/ioBroker/ioBroker.zigbee/issues/335#issuecomment-570896866)

So, nach ca. 24 Stunden taucht plötzlich etwas auf
![image](https://user-images.githubusercontent.com/46019514/72170469-3777c900-33d1-11ea-86af-c5056020cd99.png)

aber nichts zum Verbinden mit einem Sonoffschalter.

**Comment by oswaldo-be** [comment]
I flashed [latest Firmware](https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/CC2531/bin) on the Stick.
Now I see something different.
But I still do not know whether it can also switch to fales ;-)
![tradfri](https://user-images.githubusercontent.com/57314654/72681386-4cd0af80-3ac3-11ea-8951-9a7d22299029.jpg)

**Comment by Nuggelbeb** [comment]
Okay, woher bekommt man die aktuelle SBL-Firmware als *.bin für den CC2531? ([Aktualisieren Sie die Firmware ohne CCDebugger / Arduino](https://github.com/Koenkk/zigbee2mqtt/issues/320))

**Comment by Gwoony** [comment]
Bei mir zeigt es alles an. SW vom Stick ist von Juni 19. aber kann man die Helligkeit auslesen? Gibt der Sensor was aus? Wie kann man dies rausfinden?

**Comment by Gwoony** [comment]
Bei mir zeigt es alles an. SW vom Stick ist von Juni 19. aber kann man die Helligkeit auslesen? Gibt der Sensor was aus? Wie kann man dies rausfinden? 

For me it shows everything. SW from the stick is from June 19th, but can you read the brightness? Does the sensor output anything? How can you find out?

**Comment by Nuggelbeb** [comment]
Okay, lag an der Firmware. Jetzt geht er.

![image](https://user-images.githubusercontent.com/46019514/72708406-ebf8b400-3b62-11ea-88d8-2fcd83eb33a0.png)

**Comment by chr-jordan** [comment]
Did you have to pair other zigbee-devices to your cc2531 again or did they remain with the bootloader?

**Comment by oswaldo-be** [comment]
I did not have to pair again

chr-jordan <notifications@github.com> schrieb am Mo., 20. Jan. 2020, 21:22:

**Comment by Nuggelbeb** [comment]
Ich auch nicht. Alles war gleich da.

**Comment by chr-jordan** [comment]
I think this issue can be marked as closed.

**Comment by Gwoony** [comment]
The question if the Sensor could be Show the illuminance value is not answered. Greets

**Comment by oswaldo-be** [comment]
because it simply can't
