### ISSUE TITLE
herdsman fails to configure hue dimmer switch

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.zigbee#438]
I currently face the issue, that my RWL021 / Hue Dimmer Switch won't work anymore. They are paired and in the network, but the won't react to button presses (not even the LED lights up). 

Backgruound:
I migrated to herdsman without repairing my devices. Back then everything worked fine, including the RWL021. So they basically work fine. But I got a new kind of USB Stick with Z_Stack 3 firmware and therefore needed to repair all my devices. (OT: pairing really is improved drastically with herdsman! Great work!)
I did reset the RWL021 and the re-joined the network. But after that, I could not see any communication in debug log.

There are two issues in zigbee2mqtt that might be related:
https://github.com/Koenkk/zigbee2mqtt/issues/2224 (there the suggestion is, that RWL021 was not configured properly, which I think, too. After pairing, I do not see any attempt to configure the RWL021, is that correct? Would it not make sense to try and configure it after pairing? I see one attempt to configure the RWL021 after adapter restart, but I always get a timeout issue. The attempt is never retried and I did not manage to "reset" at the right time like the user in the issue linked... not sure what she/he did different.)

https://github.com/Koenkk/zigbee2mqtt/issues/2438 (here somebody else seems to have the same issue, but no solution)

Here is a log of pairing the RWL021:
https://pastebin.com/9AX7BqVn
Not sure if that is relevant. I do not really like the "Wrong device" output, but I don't think it is the issue, because I get that with other devices during pairing, too. 😉

Log from configure (other RWL021):
```
2019-12-11 20:00:20.502  - debug: zigbee.0 (549) shouldConfigure? 0x00178801105f9b54 RWL021
2019-12-11 20:00:20.502  - debug: zigbee.0 (549) Yes!
2019-12-11 20:00:20.503  - info: zigbee.0 (549) Configuring 0x00178801105f9b54 RWL021
2019-12-11 20:00:30.505  - error: zigbee.0 (549) Failed to configure 0x00178801105f9b54 RWL021, attempt 1 (Error: AREQ - ZDO - bindRsp after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10))

```

**Comment by Gwoony** [comment]
I have the same problem? What is the solution?

**Comment by kirovilya** [comment]
Try the latest version from github?
battery devices are asleep and need to be woken up to configure them - during configuration, you can try to press the buttons on it. try it.

**Comment by Garfonso** [comment]
What worked for me is to place the remotes near the coordinator, let them lie there for a few days and press some buttons from time to time. And sometimes do the reset (i.e. press all for buttons until the LED lights orange or something). After a few days they worked... it was a bit random and they started working one by one... 

Not sure if something changed in the latest version.

You can see if they are configured or not if the LED lights up if you press a button. If nothing happens, then they are not configured properly.

**Comment by gausie** [comment]
@Garfonso I guess this is what I'm trying for the next few days!
