### ISSUE TITLE
No states with IKEA - Tradfri devices

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.zigbee#440]
I upgraded my iobroker zigbee Adapter to 0.11.5 and was at least able to pair and create some IKEA bulbs. The on/off switch was not working so I sent it back,
The signal repeater works, but was not properly created - no states.
The same with an other bulb - TRADFRI bulb E27 WS opal 1000lm 

  |   |   |  
-- | -- | -- | --
zigbee.0 | 2019-12-13 18:21:35.636 | error | (2068) Device ccccccfffeb3e954 "TRADFRI Signal Repeater" not described in statesMapping.

  |   |   |  
-- | -- | -- | --
zigbee.0 | 2019-12-13 18:24:24.651 | error | (2068) Device ccccccfffe021ec0 "TRADFRI bulb E27 WS opal 1000lm" not described in statesMapping.

Is there any way - if I can fix this problem and bring the system to create the necessary states in iobroker?

**Comment by arteck** [comment]
repeater has no states .. its only works.. :-)

**Comment by mickym2** [comment]
Sure but I get this error message - and if I look to Home Assistant config - you can at least have a state for the link quality. ;) 
https://www.zigbee2mqtt.io/devices/E1746.html

and then I would have not this error message

**Comment by mickym2** [comment]
states.link_quality, states.available


So I fixed everything by myself. I should have red IKEA TRADRFI LED1736G9 suppport #434 issue first to know what to modify but - I am very happy - that I solved it now.

As I am not really familiar with this adapter I write something for those who are beginners as well:

The key file for this error messages - that no states are created is the file: devstates.js under
iobroker/node_modules/iobroker.zigbee/lib

The first error I found in the original file was the error for the bulb:

{
        vendor: 'IKEA',
        models: [
            'TRADFRI bulb E27 opal 1000lm', 'TRADFRI bulb E27 WS opal 1000lm',
            'TRADFRI bulb E26 opal 1000lm'
        ],
        icon: 'img/TRADFRI.bulb.E27.png',
        states: lightStatesWithColortemp,
        linkedStates: [comb.brightnessAndState],
    },

The "S" was missing or may be - we need an additional definition - as this is a new model of the bulb.
TRADFRI bulb E27 W[b]S[/b] opal 1000lm

Second I changed the states in this definition from
lightStates to lightStatesWithColortemp - so that changing the color works as well. 
I do not know - if the other models in this section can change the color temperature, but then a complete new devicemust be created.

Now to the repeater:

    {
        vendor: 'IKEA',
        models: ['TRADFRI Signal Repeater'],
        icon: 'img/tradfri.repeater.png',
        states: [states.link_quality, states.available],
    },

There were 2 errors in this definition: states was empty like states: []
And in addition it seems that upper and lowercase letter play a role. I changed 'TRADFRI signal repeater' to 'TRADFRI Signal Repeater'.
As states I added states.link_quality, states.available and it works perfect!!!!

So may be the changes can be added - otherwise I have my documentation at least.

Sorry - when you find this not useful!

**Comment by mickym2** [comment]
Sorry for confusion - I posted my modifications and not the original settings.

**Comment by mickym2** [comment]
I reopened it - because I did not know - if my solution is correct for future development of the adapter. May be its only a workaround - that it working. ;)

**Comment by Zwitsch** [comment]
Great, that works for me!
