### ISSUE TITLE
New Name for IKEA TRADFRI transformer 30W

### ISSUE THREAD

**Issue by wolfganghuse** [ioBroker/ioBroker.zigbee#445]
Hi,
i got a Ikea Transformer 30W who has "TRADFRI Driver 30W" as Device Name... i had to put it manually into devstates.js

Regards,
Wolfgang

**Comment by Cobblepott** [comment]
Hi Wolfgang,

that was added in the new herdsman-version

https://github.com/ioBroker/ioBroker.zigbee/blob/c296f3ab667ac462c81fb82cf67c0f5d30b4fc75/lib/devstates.js#L3251
