### ISSUE TITLE
Changing Brightness in a Group doesn´t trigger the State

### ISSUE THREAD

**Issue by wolfganghuse** [ioBroker/ioBroker.zigbee#447]
Hi,
if i change Brightness for a lamp it automatically turns on (changes state to true).
If i do the same with a group then the states keeps false. 
That makes it impossible to use a zigbee group with iot-adapter as example.

Regards,
Wolfgang

**Comment by wolfganghuse** [comment]
Seems even more complicated... if i change brightness of a single lamp via script i see the value changing in the object but debug log shows that there is no transmit of somekind of message

**Comment by nob0dy80** [comment]
can confirm this.
didnt notice that before because if you use a group, the false/true value for the group is normaly enough.
if you really need this, you can write i short javascript to change the single light values with a on change trigger of the group.

**Comment by PiXBalance** [comment]
can I reopen that? still the same issue and couldn't find a solution so far
