### ISSUE TITLE
Support for Philips LWV001 Vintage Bulb

### ISSUE THREAD

**Issue by alex04103** [ioBroker/ioBroker.zigbee#448]
I would like to add support support for this bulb:

[](https://www2.meethue.com/de-de/p/hue-white-einzelpack-st64/8718699688868)

I think that the following section would add complete support for the bulb and have already tested it successfully by adding it to devstates.js:

```
    {
        vendor: 'Philips',
        models: ['LWV001'],
        icon: 'img/philips_hue_lwv001.png',
        states: lightStates,
        syncStates: [sync.brightness],
    },
```

Regarding the image file, I don't know if licensing issues prohibit the use of 3rd party product images. How is this handled?

**Comment by arteck** [comment]
done
