### ISSUE TITLE
Problems when sending more than one command to a lightbulb

### ISSUE THREAD

**Issue by worf0r** [ioBroker/ioBroker.zigbee#45]
Hi Team!

I have a problem with all my lights paired to Zigbee Adapter.

Lets say I have a script like this:
  setState("zigbee.0.----------------.state"/*switch*/, true); 
  setState("zigbee.0.----------------.colortemp"/*color Temp*/, 0);
  setState("zigbee.0.----------------.brightness"/*brightness*/,100);
  
Three commands. The first one is always (!!) ok and working 100 %. With the second and third a have a high risk that it doesn't work.

Errors look like:
zigbee.0	2018-08-17 22:10:20.726	error	Zigbee publish to '0x.----------------', genOnOff - on - {} - 1 failed with error Error: Timed out after 30000 ms
zigbee.0	2018-08-17 22:10:05.702	error	Zigbee publish to '0x.----------------', genOnOff - off - {} - 1 failed with error Error: rsp error: 17
zigbee.0	2018-08-17 22:10:05.603	error	Zigbee publish to '0x.----------------', genOnOff - on - {} - 1 failed with error Error: rsp error: 17
zigbee.0	2018-08-17 22:10:05.571	error	Zigbee publish to '0x.----------------', genLevelCtrl - moveToLevel - {"level":100,"transtime":0} - 1 failed with error Error: rsp error: 17

If I put a delay of 3,5 Seconds between the commands everthing is working 100%. But without delay chaos. As I said, the first command is always ok. With the second and third it is like lottery. This is valid for ALL my devices. I hear in IOBroker Forum other peoble are also having this problem.

What can be done? Any ideas? This problem makes real life use...difficult... ;(

**Comment by arteck** [comment]
Set brightness or state. Not both..
I set first the colortemp then one other

**Comment by worf0r** [comment]
I know this works for this special case. But I also run in this problem when setting color AND brightness. Only the first one works 100%...

**Comment by arteck** [comment]
the delay from 1 sek.. it's enough and this problem ist only when you send many information (max 2 combinatins) to the devices

**Comment by arteck** [comment]
after this line https://github.com/ioBroker/ioBroker.zigbee/blob/5cba76d20850d57d9cf1c8b96e6f07af882c5cab/main.js#L189

**Comment by worf0r** [comment]
300 ms? That's definitely not enouch to avoid the problem here. I definitely need 3000 ms. Hm...

**Comment by worf0r** [comment]
artec, I tried as you described. 300 ms, 500 ms und even more ms didn't help me.

**Comment by arteck** [comment]
i tested it with hue gu10 (brightness and temp) 
hue lightstripe brightness and color
and osram bulb ..  all device works correct..

which device you have ??

**Comment by worf0r** [comment]
I tested with the following devices:
TRADFRI bulb E27 WS opal 980lm
TRADFRI bulb E27 CWS opal 600lm
TRADFRI bulb E14 WS opal 400lm
TRADFRI bulb GU10 WS 400lm

Maybe we should add this delay to the GUI of the adapter, so that user can configure it themselfes.

But the better way would be to find the root cause of the problem. Delay is more or less only a workaround.

**Comment by arteck** [comment]
hmm maybe the problem is just from Ikea bulbs ??

**Comment by worf0r** [comment]
The problem does not occur with the IKEA Gateway with the same installation. I tested this.

**Comment by worf0r** [comment]
We have a user report with a Osram Lightify RGBW LED Band who has the same problem.
See here: https://forum.iobroker.net/viewtopic.php?f=36&t=14819&start=80

**Comment by worf0r** [comment]
I found a new workaround for my scripts!

` //Set Color Temp
  setState("zigbee.0.----------------.colortemp"/*Farbtemperatur Marcs Büro Fenster */, 400,function (err) {
      setState("zigbee.0.----------------.colortemp"/*Farbtemperatur Marcs Büro Fenster */, 400); 
   });                   

   
  //Set Brightness
  setState("zigbee.0.----------------.brightness"/*Helligkeit Marcs Büro Fenster */,100,function (err) {
      setStat("zigbee.0.----------------.brightness"/*Helligkeit Marcs Büro Fenster */,100); 
   });    
 `

In simple words: try it again if it didn't work. This does a really good job here!

**Comment by arteck** [comment]
in this workaround is a delay of 400ms first send and 100ms of second.
is same here but directly in Adapter  [git](https://github.com/ioBroker/ioBroker.zigbee/issues/45#issuecomment-414376710)

**Comment by worf0r** [comment]
Hm? 400 ms and 100 ms? No! 400 is the colortemp and 100 is the brightness! No delay...just retry...

**Comment by worf0r** [comment]
So what can we do?

1) Developers find the root cause, why we can't send more than one command reliable to a lightbulb.
2) We add a general delay to the adapter. Perhaps configureable via GUI.
3) We add a retry for sent commands which got an error. Perhaps the retry with delay. And retry and delay configureable via GUI.

Any other ideas? 
Of course 1) would be the best :)

**Comment by worf0r** [comment]
Retry is by the way very bad when user changes the status very fast. We need to find a way to stop the retry in this case...

**Comment by arteck** [comment]
i think i found the/one bug..
we send many undefined requests.. 

```

zigbee.0 | 2018-08-26 14:51:40.956 | info | wait ------------- id : 00158d0001c16153.battery value : undefined
-- | -- | -- | --
zigbee.0 | 2018-08-26 14:51:40.454 | info | wait ------------- id : 00158d0001c16153.voltage value : undefined
zigbee.0 | 2018-08-26 14:51:39.951 | info | wait ------------- id : 00158d0001c16153.humidity value : undefined
zigbee.0 | 2018-08-26 14:51:39.448 | info | wait ------------- id : 00158d0001c16153.temperature value : undefined
zigbee.0 | 2018-08-26 14:51:38.946 | info | wait ------------- id : 00158d0001f5621b.battery value : undefined
zigbee.0 | 2018-08-26 14:51:38.444 | info | wait ------------- id : 00158d0001f5621b.voltage value : undefined
zigbee.0 | 2018-08-26 14:51:37.942 | info | wait ------------- id : 00158d0001f5621b.pressure value : undefined
zigbee.0 | 2018-08-26 14:51:37.439 | info | wait ------------- id : 00158d0001f5621b.humidity value : undefined
zigbee.0 | 2018-08-26 14:51:36.935 | info | wait ------------- id : 00158d0001f5621b.temperature value : undefined
zigbee.0 | 2018-08-26 14:51:36.432 | info | wait ------------- id : 00158d0001573a56.battery value : undefined
zigbee.0 | 2018-08-26 14:51:35.929 | info | wait ------------- id : 00158d0001573a56.voltage value : undefined
zigbee.0 | 2018-08-26 14:51:35.427 | info | wait ------------- id : 00158d0001573a56.humidity value : undefined
zigbee.0 | 2018-08-26 14:51:34.925 | info | wait ------------- id : 00158d0001573a56.temperature value : undefined
zigbee.0 | 2018-08-26 14:51:34.423 | info | wait ------------- id : 00158d00010e534f.battery value : undefined
zigbee.0 | 2018-08-26 14:51:33.921 | info | wait ------------- id : 00158d00010e534f.voltage value : undefined
zigbee.0 | 2018-08-26 14:51:33.418 | info | wait ------------- id : 00158d00010e534f.humidity value : undefined
zigbee.0 | 2018-08-26 14:51:32.916 | info | wait ------------- id : 00158d00010e534f.temperature value : undefined
zigbee.0 | 2018-08-26 14:51:32.413 | info | wait ------------- id : 00158d0002019c22.battery value : undefined
zigbee.0 | 2018-08-26 14:51:31.911 | info | wait ------------- id : 00158d0002019c22.voltage value : undefined
zigbee.0 | 2018-08-26 14:51:31.408 | info | wait ------------- id : 00158d0002019c22.isopen value : undefined
zigbee.0 | 2018-08-26 14:51:30.906 | info | wait ------------- id : 00158d0002019c22.contact value : undefined
zigbee.0 | 2018-08-26 14:51:30.404 | info | wait ------------- id : 00158d0001e4508f.battery value : undefined
```
I took out wait and add a if 
[here](https://github.com/arteck/ioBroker.zigbee/blob/6ca42ec5fcde800467d106a981e6b023f06499d3/main.js#L190)

plz check with my Repo

**Comment by worf0r** [comment]
I tried this if, but still the same problem:
zigbee.0	2018-08-26 16:41:58.509	error	Zigbee publish to '------------------------', genLevelCtrl - moveToLevel - {"level":100,"transtime":0} - 1 failed with error Error: rsp error: 17
zigbee.0	2018-08-26 16:41:55.221	error	Zigbee publish to '------------------------', genLevelCtrl - moveToLevel - {"level":254,"transtime":0} - 1 failed with error Error: rsp error: 17
zigbee.0	2018-08-26 16:41:55.183	error	Zigbee publish to '------------------------', genLevelCtrl - moveToLevel - {"level":254,"transtime":0} - 1 failed with error Error: rsp error: 17
zigbee.0	2018-08-26 16:41:52.221	error	Zigbee publish to '------------------------', genLevelCtrl - moveToLevel - {"level":254,"transtime":0} - 1 failed with error Error: rsp error: 17

What is this rsp error 17?

**Comment by arteck** [comment]
[error: 17](https://github.com/Koenkk/zigbee2mqtt/issues/184)

**Comment by worf0r** [comment]
Hm ok. So Error 17 means the buffers on the Stick run full? But the first command always works? Thats strange...

**Comment by kirovilya** [comment]
@arteck 
> i think i found the/one bug..
> we send many undefined requests..

I think this is not a bug.
This is the case when the state is absent and then it must be created anew. This can be the case when a new device is connected - a state with an empty value is created.

**Comment by kirovilya** [comment]
@arteck This is always done at startup to restore a set of states even for existing devices.
Setting states for `voltages`, `humidity`, `pressure` and others does not form a message to the device and does not affect them in any way.
I think this part does not affect the current problem with sending messages.

**Comment by worf0r** [comment]
With Hue Bridge the Tradfri Lights also can‘t change Color and Brightness in one step. To avoid this it helps to set Transition Time to 0. Then more than one command works with Hue Bridge. May be a workaround here also? How can I change the transition time to 0?

**Comment by kirovilya** [comment]
Try to use 0.9.0 version
