### ISSUE TITLE
Aqara Wall Switch missing States

### ISSUE THREAD

**Issue by DevilDesire** [ioBroker/ioBroker.zigbee#454]
Hello :)

after a fresh install of iobroker and pairing the Xiaomi Aqara  Double Wall switches I missing some States

Double Click and long Press of both buttons

Any Ideas how i get them back?

**Comment by hauschablous** [comment]
Hi there,
I had the same problem a while ago, but installing the newest version of the adapter from github (in the adapter view, press the octocat-symbol, then choose zigbee and install) all the states where back again. I don`t remeber if I had to pair them again, but I think it worked from the spot.
At the moment it´s version 0.11.5 you`re upgrading to.
