### ISSUE TITLE
Missing location/sensitivity state on Xiaomi Smoke detector

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.zigbee#456]
As i can see in the Mi Home-App , the smoke detector got a sensitivity setting that can be set.
it seems to work close the same way as the gas detector works.

netgas got sensitivity in devstates.js:
 
natgas_sensitivity: {
      id: 'gas_sensitivity',
      name: 'Naturl Gas Sensitivity',
      prop: 'sensitivity',
      icon: undefined,
      role: 'state',
      write: true,
      read: true,
      type: 'string', // valid: low, medium, high
    },

tried to include it the same way but failed ...can somebody help to include a sensitivity state for the smoke detector?
Found this:
https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/devices/JTYJ-GD-01LM_BW.md#sensitivity

and this:
https://github.com/Koenkk/zigbee2mqtt/issues/2113
maybe this helps

**Comment by kirovilya** [comment]
can you try last developing-version from github repo?

**Comment by arteck** [comment]
Error on send to 0x00158d0002b31187 problem on set state

**Comment by skrabadiloseidon** [comment]
I got the same xiaomi smoke sensor, please add a option to set the sensitivity.

Other question:
Is it possible to access the mqtt broker and send the "sensitivity" message itself? (send a custom JSON)
