### ISSUE TITLE
Could not delete undefined Objects

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#460]
First the new version 1.0.0.c is very good. Thank for your good job.
I have only the problem, that I could not delete undefined Objects. If I delete an paired object it switch to undefined and I could not delete. I see it only in the adapter not on the object side.

Thank you for Helping

**Comment by arteck** [comment]
plz reparied and delete now..

**Comment by Gwoony** [comment]
I don’t have the parts for pairing again...

**Comment by huk13** [comment]
same behavior here. Cannot pair again because device is broken.

**Comment by Gwoony** [comment]
After update to the newest version i could not delete any device known and unknown :-)

And there is this error log:


zigbee.0 | 2020-01-18 20:24:22.105 | error | at Timer.processTimers (timers.js:223:10))
-- | -- | -- | --
zigbee.0 | 2020-01-18 20:24:22.105 | error | at listOnTimeout (timers.js:263:5)
zigbee.0 | 2020-01-18 20:24:22.105 | error | at tryOnTimeout (timers.js:300:5)
zigbee.0 | 2020-01-18 20:24:22.105 | error | at ontimeout (timers.js:436:11)
zigbee.0 | 2020-01-18 20:24:22.105 | error | at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
zigbee.0 | 2020-01-18 20:24:22.105 | error | (10678) Failed to do action 0x00158d0001e5fc63 lumi.sensor_m

**Comment by Gwoony** [comment]
After the update you could delete this object with the force mode. So its works and it is close
