### ISSUE TITLE
Support for Aqara Opple Wireless Switch?

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#461]
Update to 1.0.0.c no support for the switch #427 

zigbee.0 | 2020-01-03 22:23:47.842 | error | (8807) Failed to interview '0x04cf8cdf3c75bcf4', device has not succesfully been paired. undefined
-- | -- | -- | --
zigbee.0 | 2020-01-03 22:23:36.081 | error | (8807) Failed to interview '0x04cf8cdf3c75bcf4', device has not succesfully been paired. undefined

Could I help with some information?

**Comment by arteck** [comment]
works

**Comment by Gwoony** [comment]
now its work thank you... very fine

**Comment by Gwoony** [comment]
zigbee.0 | 2020-01-07 19:29:26.844 | error | at Timer.processTimers (timers.js:223:10))
-- | -- | -- | --
zigbee.0 | 2020-01-07 19:29:26.844 | error | at listOnTimeout (timers.js:263:5)
zigbee.0 | 2020-01-07 19:29:26.844 | error | at tryOnTimeout (timers.js:300:5)
zigbee.0 | 2020-01-07 19:29:26.844 | error | at ontimeout (timers.js:436:11)
zigbee.0 | 2020-01-07 19:29:26.844 | error | at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
zigbee.0 | 2020-01-07 19:29:26.844 | error | (15321) Failed to configure 0x04cf8cdf3c75bcf4 lumi.remote.b486opcn01, attempt 2 (Error: AREQ - ZDO - bindRsp after 10000ms

The remote works but there are this error logs
