### ISSUE TITLE
Support von Innr FL130C

### ISSUE THREAD

**Issue by Christoph1978** [ioBroker/ioBroker.zigbee#464]
Hallo zusammen,

wäre es möglich, dass das LED-Band FL130C von Innr unterstützt wird? Bei Zigbee2MQTT ist es bereits enthalten, siehe: [https://www.zigbee2mqtt.io/devices/FL_130_C.html](url)

Vielen Dank schon mal im voraus!
Christoph1978

**Comment by arteck** [comment]
kannst du es hier einstellen.. ich brauch da mehr infos zu
