### ISSUE TITLE
error log Xiaomi Opple Button

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#465]
Hey the Xiaomi Opple Button works but there are this error logs for your information:

zigbee.0 | 2020-01-07 19:29:26.844 | error | at Timer.processTimers (timers.js:223:10))
-- | -- | -- | --
zigbee.0 | 2020-01-07 19:29:26.844 | error | at listOnTimeout (timers.js:263:5)
zigbee.0 | 2020-01-07 19:29:26.844 | error | at tryOnTimeout (timers.js:300:5)
zigbee.0 | 2020-01-07 19:29:26.844 | error | at ontimeout (timers.js:436:11)
zigbee.0 | 2020-01-07 19:29:26.844 | error | at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
zigbee.0 | 2020-01-07 19:29:26.844 | error | (15321) Failed to configure 0x04cf8cdf3c75bcf4 lumi.remote.b486opcn01, attempt 2 (Error: AREQ - ZDO - bindRsp after 10000ms

**Comment by kirovilya** [comment]
for the correct _configure_, you need to briefly press the pairing button (on the back of the Opple Switch) - a message about successful _configure_ should appear in the logs. if it doesn’t work, then restart the adapter and try again.

**Comment by Gwoony** [comment]
i have try some times but every try is the same solution: the error log you see in the Post #324 Another idea?

**Comment by Gwoony** [comment]
Now its work... you don't must press the pairing button short rather longer until the Led flashes an second time for 3 Times. Now its work perfect. Thank you.
