### ISSUE TITLE
Philips Hue Go - LCT026 support ?

### ISSUE THREAD

**Issue by oberonn** [ioBroker/ioBroker.zigbee#466]
My recently purchased Philips Hue Go 7602031PH
pairs as LCT026 without any further functionality 
and does not list as a zigbee object.

Can I help you to add it to the list of supported devices ?

ioBroker.zigbee 0.11.5 running on ioBroker.admin 3.6.12 / Raspberry Pi 3+
with correctly configured CC2531, 8 other Hue and Osram objects work well

**Comment by arteck** [comment]
install new version

**Comment by oberonn** [comment]
> install new version

still 

zigbee.0 | 2020-01-12 10:34:08.458 | error | (1773) Device ...  "LCT026" not described in statesMapping
