### ISSUE TITLE
Hue Motion Sensor Illuminance

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#468]
I have pairing the Hue Motion Sensor sucessfully. But the value of the Illuminance is only high 2000 lux and more. Do u have the same problems? and how is the solution?

Thank you for helping

**Comment by Gwoony** [comment]
For what are this object?

- Illuminance Calibration Percentage
- Motion Sensitivity (0-2)
- Temperature Calibration Offset

**Comment by allofmex** [comment]
> Illuminance is only high 2000 lux and more

Works for me, 0 lux in darkness, ~400 with very little light, > 10000 if full light 
(herdsman branch, but was working on released version too)

> Illuminance Calibration Percentage
Temperature Calibration Offset

As it says, to calibrate the illuminance state.
set it for example to -10 (illuminance) or -2.2 (temp), and the reported illuminance/temperature will always be reported 10%/2.2 degree lower than before

> Motion Sensitivity (0-2)

This is the sensitivity setting that hue bridge also has (I did not see any difference, don't know how exactly the motion detection is effected)

**Comment by Gwoony** [comment]
okay thank you....
But why is the Lux Value so high?
