### ISSUE TITLE
Missing sensitivity state for Xiaomi Vibration Sensor (lumi.vibration.aq1)

### ISSUE THREAD

**Issue by grdminer** [ioBroker/ioBroker.zigbee#470]
Dear team,

The sensitivity state for Xiaomi Vibration sensor (lumi.vibration.aq1) is not available/supported.

According to [zigbee2mqtt](https://www.zigbee2mqtt.io/devices/DJT11LM.html) a sensitivity state is available. 

Would it be possible to add this state to this adapter?

Thank you for this adapter and your hard work!

Maybe related/similar to #456

**Comment by kirovilya** [comment]
can you try last developing-version from github repo?

**Comment by grdminer** [comment]
Thanks for response!

Updated to 0.11.5 (with some warnings) by `npm install iobroker.zigbee@latest --development`
and removed the device. After adding it again it shows the same states before (but some other new cool features - Thank you!). I assume that you are talking about a different development version? But I couldnt find any other branch or source. Just let me know how and I'll test it.

**Comment by kirovilya** [comment]
no-no, update from github
![image](https://user-images.githubusercontent.com/8360230/72751222-146ac780-3bd0-11ea-8fe0-9093dd461428.png)

**Comment by grdminer** [comment]
Ok meanwhile if found that and saw your post afterwards, thank you. Adapter is now updated to 1.0.0-d. The sensitivity state is available now. For now the vibration sensor doesnt answer to changes of sensitivity state but maybe it needs to seetle first `(1829) Error on send to 0x00158d00039da3bd problem on set state`. I'll test again later. the weird thing is that a lot of devices (mostly end devices) are shown as offline but behave normal including the vibration sensor.

**Comment by kirovilya** [comment]
:( I don’t have this sensor, so it’s hard for me to check ... I’ll think about how to fix it

**Comment by grdminer** [comment]
Ok, thank you. Just let me know if you need any logs etc.
In case your living in germany I could send you one.

**Comment by kirovilya** [comment]
@grdminer no :))) I am from Russia

**Comment by grdminer** [comment]
:) Thats what I thought. BTW setting the state occupancy_timeout of [lumi.sensor_motion](https://www.zigbee2mqtt.io/devices/RTCGQ01LM.html) works in 1.0.0-d. Maybe it helps.

**Comment by kirovilya** [comment]
occupancy_timeout - very old state :) it not helps

**Comment by grdminer** [comment]
ok, I thought it might be similar/comparable for easier fixing

**Comment by grdminer** [comment]
sorry to bother you again. Do you know how to get rid of the dev version of the zigbee adapter? Deleting the adapter and installing it again using the "normal way" leads to an error the a dev is installed and needs to be removed first.

**Comment by arteck** [comment]
works

**Comment by grdminer** [comment]
Hi arteck,

I cant confirm that it works! Installed latest version and sensitivity is still not set successfully
`

zigbee.0 | 2020-02-07 10:05:21.270 | error | at <anonymous>
-- | -- | -- | --
zigbee.0 | 2020-02-07 10:05:21.270 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
zigbee.0 | 2020-02-07 10:05:21.270 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-02-07 10:05:21.270 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:150:23)
zigbee.0 | 2020-02-07 10:05:21.270 | error | (4329) Error on send command to 0x00158d00039da3bd. Error: Error: Write 0x00158d00039da3bd/1 genBasic({"65293":{"value":11,"type":32}}, {"timeout":10000,"defaultResponseTimeout":15000,"manufacturerCo`
