### ISSUE TITLE
Problem !!! Zigbee Adapter V 1.0.3 -  Danalock V3-BTZB

### ISSUE THREAD

**Issue by Nuggelbeb** [ioBroker/ioBroker.zigbee#471]
Hallo, das Danalock V3-BTZB zeigt mit Zigbee Adapter V 1.0.0 einen Fehler im Log.

![image](https://user-images.githubusercontent.com/46019514/72253547-13e79500-3602-11ea-9360-0f4d5a4af097.png)

**Warum kommt nach dem Schalten mit "**lock**" und "**unlock**" keine Rückmeldung "**locked**" und "**unlocked**"?
**!!! Dies ist für eine Prüfung, ob das Schloss geschalten hat, WICHTIG !!!****

**Comment by smarthomegirl** [comment]
Ich habe auch das gleiche Problem, da ich ebenfalls locked / unlocked als Abfrage nutze und zum Senden lock / unlock verwende. Sch...

**Kann man das irgendwo ändern?**

**Comment by Nuggelbeb** [comment]
Keiner eine Lösung?

**Comment by smarteule** [comment]
Keiner eine Lösung? Ich habe auch das Problem.

**Comment by Matdos** [comment]
Was für ein System habt ihr? Raspy 4? Ich bekam keine Rückmeldung als ich den Zigbee Stick auf dem usb3 Port vom Raspy 4 Stecken hatte, anderer USB 2.0 Port war bei mir die Lösung. 

https://forum.iobroker.net/topic/29768/zigbee-adapter-1-0-2-danalock/40

Ihr könnt auch mal da rein schauen teilweise haben wir alle mit dem Danalock das Problem

**Comment by smarthomegirl** [comment]
> Was für ein System habt ihr? Raspy 4? Ich bekam keine Rückmeldung als ich den Zigbee Stick auf dem usb3 Port vom Raspy 4 Stecken hatte, anderer USB 2.0 Port war bei mir die Lösung.
> 
Nein, das denke ich nicht. Es fehlt ja nach dem Senden von "lock" und "unlock" komplett die Statusrückmeldung "locked" und "unlocked" ! Diese Meldung ist aber von hoher Notwendigkeit, gerade wenn man, wie @Nuggelbeb oben schon erwähnte, überprüfen will, ob das Schloss überhaupt geschalten hat. 

> https://forum.iobroker.net/topic/29768/zigbee-adapter-1-0-2-danalock/40
> 
> Ihr könnt auch mal da rein schauen teilweise haben wir alle mit dem Danalock das Problem

Ja, da habe ich schon reingeschaut, aber da kommen auch keine weiteren Änderungen. Naja, vielleicht tut sich jetzt was im Homeoffice, Zeit genug ist ja. 😅
