### ISSUE TITLE
Question: Compatibility with zigbee-herdsman

### ISSUE THREAD

**Issue by blakadder** [ioBroker/ioBroker.zigbee#472]
Not an issue, just a question. Is it safe to assume iobroker.zigbee is compatible with all zigbee devices in zigbee-herdsman-converters repo or are there differences? I'm asking since I'm building a list of supported zigbee devices across multiple platforms at https://zigbee.blakadder.com and I need to know whether I require a separate entry for ioBroker or not.

Thanks in advance!

**Comment by kirovilya** [comment]
Hey. Cool resource, well done!
All devices from the zigbee-herdsman-converters repository can be added to iobroker.zigbee. Not all https://github.com/ioBroker/ioBroker.zigbee/wiki/Supported-devices are added (there is no free time and resources). We ourselves are the authors of new devices for zigbee-herdsman-converters and add them there and to ourselves in iobroker.zigbee.
To add a device to iobroker.zigbee, you need to parse the attributes on the states and ensure that the changes of the states are translated back to the teams ... well, add the picture here https://github.com/ioBroker/ioBroker.zigbee/tree/master/admin/i18n
Devices are described here https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devstates.js#L2897
It would be possible to make a note about the presence in iobroker - only it will be necessary to monitor and maintain relevance.

**Comment by blakadder** [comment]
Ok thanks. I can automatically include a note on every device labelled as supported by zigbee-herdsman that it is supported in iobroker or in case it isn't a request for adding one has to be made.

I will also parse the linked devices.js and label devices in my liste with the same modelid as iobroker supported specifically. Is there any icon/logo you'd prefer me to use, it should be square sized atleast 50x50

**Comment by kirovilya** [comment]
Not all, only a subset of devices from heardsman is supported in the iobroker. You can check by the model codes - coincide with the model in the heardsman. https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devices.js#L71

Logo of ioBroker https://avatars3.githubusercontent.com/u/7231148?s=200&v=4
