### ISSUE TITLE
Hue dimmer switch: offline after battery change

### ISSUE THREAD

**Issue by Maschler** [ioBroker/ioBroker.zigbee#475]
Hello everybody,
Thank you for a great job.

I am currently connecting my Hue dimmer switch. I have noticed one problems:

When I change the battery on a dimmer switch, the switch no longer works with the new battery. Only after I reconnect the switch will it work again. With the original Hue Bridge the switch still works after changing the battery.

**Comment by allofmex** [comment]
What adapter version are you using? 
Please enable debug logging and check for any "configure" messages related to your device.

**Comment by Maschler** [comment]
hi,
okay. that's weird. I just tried to recreate the problem, but it always worked perfectly this time. Last time I opened the issue, it repeatedly didn't work.

I am using using the adapter version 0.10.2

I will continue to monitor this and will get back to you as soon as possible.

**Comment by arteck** [comment]
0.10.2 its very old..plz switch to new version
