### ISSUE TITLE
Hue dimmer switch: Click Count is missing

### ISSUE THREAD

**Issue by Maschler** [ioBroker/ioBroker.zigbee#476]
Hello,

I noticed a second thing. The click count, which is enumerated by the Hue dimmer switch (on/off, brightness, up/down/hold/release, click count) is also not existing for the objects.

<img width="690" alt="72560334-22a2a600-38a7-11ea-9b0e-c9fb765462e5" src="https://user-images.githubusercontent.com/38862834/72609853-3e00c600-3926-11ea-8afd-c0b67cdb2e11.PNG">

thx

**Comment by kirovilya** [comment]
Try to use last developing-version from git

**Comment by Maschler** [comment]
I'm sorry to ask so stupidly. How do I do that?

Do I have to delete version 0.10.2 first or how does it work? What happens with the existing devices?

**Comment by kirovilya** [comment]
![image](https://user-images.githubusercontent.com/8360230/72679755-565a1780-3ac3-11ea-909c-26202cf88fc2.png)

**Comment by Maschler** [comment]
Hi,
thanks for helping. Now the Click count is available. 

the click count works. However, you have to press pretty fast one after the other to get the count up. Is there a way to set this to allow about 1 second delay between clicks?

**Comment by kirovilya** [comment]
I do not know how to do it. if you can figure it out, then here it is counted https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L1741
