### ISSUE TITLE
Long-Press and Double-Click on Aqara Opple 1 band (WXCJKG12LM)

### ISSUE THREAD

**Issue by benny000004** [ioBroker/ioBroker.zigbee#477]
Single Press is working fine but Long-Press and Double-Click events are not registered, although it should be possible according to Aqara Site (see also https://www.zigbee2mqtt.io/devices/WXCJKG11LM.html).

**Comment by Gwoony** [comment]
Also by Opple 2 band. Button 1 and 2 has only single click Button 3 and 4 has single and double click.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/35467967/72670682-ae036f00-3a40-11ea-881e-38a59251e706.png">
