### ISSUE TITLE
Konke Motion Sensor (3AFE28010402000D)

### ISSUE THREAD

**Issue by Mistreko** [ioBroker/ioBroker.zigbee#478]
Hi,

when i'm going to pair my Konke motion sensor the Interview fails. 
It is just show as an unknown device.
I check the number from the Konke in the supported device list and relised the number is different. 
It's 3AFE14010402000D and mine is 3AFE28010402000D.
Maybe a new version? 

![konke motion sensor](https://user-images.githubusercontent.com/57731862/72661913-84b2f680-39e0-11ea-989d-3bf0a1769e1f.jpg)

**Comment by kirovilya** [comment]
update adapter from git for support

**Comment by Mistreko** [comment]
Ok i just updated. The motion sensor is now listed and recognised. But there is still an error: failed the interview. There are also no states in "Objects" except the signal.
![zigbee konke](https://user-images.githubusercontent.com/57731862/72684815-35ee8500-3ae4-11ea-8174-d9c916e2986a.jpg)

**Comment by positron48** [comment]
I have similiar problem but my konke devices dont join to pairing... I just see countdown and nothing more

**Comment by Mistreko** [comment]
@positron48 i read in another chat that just some channels are working with konke sensors. I use channel 20. But 15 and 25 should work aswell. Change it, restart adapter and try it again.

**Comment by arteck** [comment]
konke works on channel 15

**Comment by positron48** [comment]
@Mistreko thank you. I switched it to channel 20 and it works.

**Comment by Mistreko** [comment]
@positron48 does yours work fine? (like a xiaomi aqara motion Sensor if you have one)
Or has it a recognition Pause for like 2min After it recognized a Person? 
My xiaomi update the object stats like every second but konke doesnt. Which is a problem in my corridor when i Stay in it for Example to clean floor, ist Turns off the Lights After countdown 😅

**Comment by positron48** [comment]
@Mistreko i have no troubles. Motion sensor shortly set true if it  something. But then maybe it have some delay to set true again. You can log events to history, my messages from telegram here:

3AFE28010402000D Occupancy event => Обнаружено движение в коридоре

3AFE28010402000D Occupancy event => switched off

3AFE28010402000D Occupancy event => Обнаружено движение в коридоре

3AFE28010402000D Occupancy event => switched off

3AFE28010402000D Occupancy event => Обнаружено движение в коридоре

3AFE28010402000D Occupancy event => switched off
I also have a door sensor and it works fine too.
