### ISSUE TITLE
Integration of Philips Hue Aurelle

### ISSUE THREAD

**Issue by valentin38315** [ioBroker/ioBroker.zigbee#479]
Hello everybody,

would it be possible for the Philips Hue Aurelle LED panel to be supported?  It is already included in Zigbee2MQTT, see: 

https://www.zigbee2mqtt.io/devices/3216331P5.html

 Thank you in advance!

**Comment by cstudener** [comment]
Hi!

Thank you for this great adapter! It's working fine for me with my Xiaomi Sensors and (most) of my hue bulbs!

I'm also using two Aurelle panels and both panels are not paired with success. My models are LTC014 and LTC015. They both show on the pairing dialog a state like:
![B7D5FF73-98D4-4F45-82AF-1E879687742C_1_105_c](https://user-images.githubusercontent.com/8917327/73796207-f0e97480-47ac-11ea-97c1-8c2e2b83bd87.jpeg)

- announced itself
- a few "...not described in stateMapping..." errors
- and the the full "New Device joined..." message.

But, the device is only shown with the question mark on the devices list and I have no objects
![94EB7F3A-C6EF-472E-B859-753C787E3BE4_1_201_a](https://user-images.githubusercontent.com/8917327/73796581-dfed3300-47ad-11ea-8d7d-f1b97cd9f603.jpeg)

I can see, the devices exist in devices.js. Is there something else missing?

Thank you! :-)

**Comment by kirovilya** [comment]
Added. you can try to use github version

**Comment by cstudener** [comment]
Hi! Thank you! It's working fine!

Can be closed... :-)
