### ISSUE TITLE
Ikea Tradfri Light Bulb

### ISSUE THREAD

**Issue by steyen** [ioBroker/ioBroker.zigbee#48]
Hello,

how can IKEA Lightbulb be connected to the iobroker without gateway?

Thank you for your help

**Comment by arteck** [comment]
rtfm !!!

**Comment by worf0r** [comment]
I have got the following Tradfri devices online with this adapter:
TRADFRI bulb E27 WS opal 980lm
TRADFRI bulb E27 CWS opal 600lm
TRADFRI bulb E14 WS opal 400lm
TRADFRI bulb GU10 WS 400lm

Just reset them this way:
https://www.youtube.com/watch?v=mJm9YpPrGzk

And then pair them to the adapter.

**Comment by steyen** [comment]
@arteck --> thanks for the nice contribution ):

@worf0r  --> Thank you very much, this helps me a lot because in the fucking Manual i dont find any solution like @arteck mentioned
