### ISSUE TITLE
Geräte werden nicht angezeigt

### ISSUE THREAD

**Issue by MichaWilk** [ioBroker/ioBroker.zigbee#480]
Hallo, ich kann die Geräte einlernen und verwenden.
Aber die werden mir unter den
![Unbenannt](https://user-images.githubusercontent.com/58995833/72667596-c7df8a80-3a1d-11ea-90d9-1d1210e877bd.jpg)
 Reiter GERÄTE  nicht angezeigt.
Unter Reiter Netzwerkkarte wird mir alles angezeigt.
Ist das Problem schon bekannt ?

Adapter Vision 1.0.0-c
Node.js   v10.18.0
NPM   6.13.4

**Comment by Apollon77** [comment]
Irgendein Fehler in der Browser Konsole?

**Comment by MichaWilk** [comment]
![Unbenannt](https://user-images.githubusercontent.com/58995833/72670065-4564c400-3a39-11ea-9f24-98d95e472f61.jpg)
![1Unbenannt](https://user-images.githubusercontent.com/58995833/72670070-57defd80-3a39-11ea-8985-21642c47a5c1.jpg)
Das sieht bei mir so aus

**Comment by arteck** [comment]
installiere die neue version

**Comment by nakakiba** [comment]
Hallo!
Hab ein sehr ähnliches Problem.
In der Zigbee Instanz sind die Objekte weder im Reiter 'Geräte' noch sonst wo zu sehen.
In den Objekten stehen sie aber und funktionieren auch.
Im Log stehen immer wieder die oberen 4 Fehler, die mir leider nicht viel sagen :-/
Weiß da jemand mehr als ich?
Vielen Dank für eure Hilfe schon im Voraus!
![zigbee](https://user-images.githubusercontent.com/60752615/73969955-9c650700-491c-11ea-9e59-4f8ceea01688.png)


Adapter Vision 1.0.2
Node.js v10.18.1
NPM: 6.13.7
