### ISSUE TITLE
Deleting of Known Device

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#484]
Hello, after updating to the newest version I could not delete know devices (also unknown). There is only this error log

zigbee.0 | 2020-01-19 15:14:41.670 | error | at Timer.processTimers (timers.js:223:10))
-- | -- | -- | --
zigbee.0 | 2020-01-19 15:14:41.670 | error | at listOnTimeout (timers.js:263:5)
zigbee.0 | 2020-01-19 15:14:41.670 | error | at tryOnTimeout (timers.js:300:5)
zigbee.0 | 2020-01-19 15:14:41.670 | error | at ontimeout (timers.js:436:11)
zigbee.0 | 2020-01-19 15:14:41.670 | error | at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
zigbee.0 | 2020-01-19 15:14:41.670 | error | (3626) Failed to do action 0xec1bbdfffe1a7f92 TRADFRI motion sensor, attempt 1 (Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms

**Comment by Gwoony** [comment]
could somebody help?

**Comment by kirovilya** [comment]
Did you use last version from github? 1.0.0-d?

**Comment by Gwoony** [comment]
I have repaired the device and now I could delete them. Sometimes you must delete first the object and then the device in the Adapter Page.

Thank you. Now works fine 😀
