### ISSUE TITLE
Paul Neuhaus NLG-RGBW light

### ISSUE THREAD

**Issue by valentin38315** [ioBroker/ioBroker.zigbee#485]
Hello,

I Have a problem to send values to my Paul Neuhaus NLG-RGBW light. (light is available)
ERROR: 
![Screenshot_20200119-171749](https://user-images.githubusercontent.com/47112999/72684366-6502f780-3ae0-11ea-9595-5a942299c68f.jpg)

![Screenshot_20200119-172036](https://user-images.githubusercontent.com/47112999/72684379-819f2f80-3ae0-11ea-9615-af5ee141061d.jpg)

Does someone knoe hoe to get it work? :)

**Comment by arteck** [comment]
install new adapter version
