### ISSUE TITLE
GLEDOPTO, GL-C-008 not work

### ISSUE THREAD

**Issue by LiveSide** [ioBroker/ioBroker.zigbee#486]
I have the device 
GLEDOPTO 2.4G Wireless RGB-CCT LED Controller
FCC ID: 2AR8F-GL-C-008
Model No: GL-C-008S

Is it posible to insert this Model?

Thank you alot

**Comment by LiveSide** [comment]
ieee:0x00124b001edd703f
nwk:7462 (0x1d26)
model:GL-C-008S

**Comment by kirovilya** [comment]
Added. Can you try from github. Will be in next version

**Comment by arteck** [comment]
done
