### ISSUE TITLE
GLEDOPTO Zig.Bee GL-B-007Z

### ISSUE THREAD

**Issue by LiveSide** [ioBroker/ioBroker.zigbee#487]
I have the device 
GLEDOPTO Zig.Brr GL-B-007Z AV100-240V R27 6E RGBEE Kompatible with Philips HUE

Is it possible to insert this Model?

Thank you a lot

**Comment by LiveSide** [comment]
ieee:0x00124b001ea82411
nwk:63422 (0xf7be)
model:GL-B-007Z

**Comment by kirovilya** [comment]
Added. Can you try from github. Will be in next version

**Comment by LiveSide** [comment]
Hello Kirovilya,
i can controle the bulb with node-red and turn it on... but if i want turn it off they dont turn off...
but the object change and send the feedback... 

if i turn that object off by hand... the buld shut down... .
