### ISSUE TITLE
 "Classic A60 W clear - LIGHTIFY" not described in statesMapping

### ISSUE THREAD

**Issue by derAuge** [ioBroker/ioBroker.zigbee#49]
Hallo,

i have a Problem with  "Classic A60 W clear - LIGHTIFY"
see allso:
https://forum.iobroker.net/viewtopic.php?f=36&t=14819&start=100#p172645

**Comment by arteck** [comment]
done

**Comment by modmax** [comment]
Issue can be closed. Also tested successfuly with latest version.
