### ISSUE TITLE
No signal strength in network tab

### ISSUE THREAD

**Issue by cosmonoid** [ioBroker/ioBroker.zigbee#493]
Since updating to Version 1.0.0-c there is no signal strength shown in the network tab. Some devices are shown as offline but all devices do work. 
![8D309984-55AE-4236-BB51-1341AF221EDB](https://user-images.githubusercontent.com/3930345/72999955-6eea6a80-3e00-11ea-8160-66a7f222f1c8.jpeg)
The signal strength in the devices tab seems to be correct. 

Please reply if there are more details needed.

**Comment by grdminer** [comment]
Same behaviour here. Since v1.0.2 there are not relations at all in network map

**Comment by kirovilya** [comment]
@cosmonoid signal levels show when you click on the device

@grdminer I think you need to pair the devices again :(

**Comment by grdminer** [comment]
sorry I forgot do mention that alle devices are working as expected (exc. the vibration sensitivity) and the device page shows this:

![ZigBeeDevices](https://user-images.githubusercontent.com/19997112/74037202-1d280f80-49be-11ea-93dc-9575886a64ac.png)

**Comment by cosmonoid** [comment]
> signal levels show when you click on the device



@kirovilya 
I did clicked the device ZG9101SAC-HP seen on my screenshot. As you can see the levels are shown as (0/0) off for all connected devices even with the coordinator. Checking all devices by click every level related to the coordinator or other devices are marked as off. But everything is working as expected so it can not be that the levels are (0/0) off for each.

**Comment by kirovilya** [comment]
Try to check out latest version from github (1.0.3)

**Comment by cosmonoid** [comment]
> Try to check out latest version from github (1.0.3)

Thanks. That did the trick.  Levels are now showing correct. 
Awesome work by the way. Keep on coding.
