### ISSUE TITLE
no components

### ISSUE THREAD

**Issue by Ceel84** [ioBroker/ioBroker.zigbee#494]
`
zigbee.0 | 2020-01-24 22:46:11.341 | warn | (856) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!
-- | -- | -- | --
zigbee.0 | 2020-01-24 22:46:11.331 | warn | (856) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!
zigbee.0 | 2020-01-24 22:46:11.320 | warn | (856) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!
zigbee.0 | 2020-01-24 22:46:11.309 | warn | (856) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!
zigbee.0 | 2020-01-24 22:46:11.290 | warn | (856) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!
zigbee.0 | 2020-01-24 22:46:11.240 | warn | (856) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!
`

![1](https://user-images.githubusercontent.com/60227609/73106466-ca4d5300-3efb-11ea-8af6-aff0afb1844f.png)
![2](https://user-images.githubusercontent.com/60227609/73106468-cae5e980-3efb-11ea-9b72-127619be4513.png)

**Comment by arteck** [comment]
which version ??

**Comment by kirovilya** [comment]
@Ceel84 please update adapter to 1.0.2 version from Latest repository (or from github)

**Comment by Ceel84** [comment]
Ist works
Thx
