### ISSUE TITLE
Adapter crashes due to a typo in device.js

### ISSUE THREAD

**Issue by Frank1604** [ioBroker/ioBroker.zigbee#495]
There is a typo in device.js in line 1282. The leading "s" of "states" is missing. That cause the adapter to crash if you have a "Müller Licht tint Smart Switch".

`    {
        vendor: 'Mueller Licht',
        models: ['tint Smart Switch'],
        icon: 'img/zbt_smart_switch.png',
        tates: [states.state],
    },`

**Comment by kirovilya** [comment]
fixed in 1.0.2
