### ISSUE TITLE
Philips Hue Single Bulb

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.zigbee#499]
Problems with adding the following product:
Philips Hue E27 Bulb ZigBee/Bluetooth
It is recognized but not known. It is named Lwa001 but shown with a big question mark.

**Comment by Dragon0501** [comment]
![Screenshot 2020-01-31 at 21 35 30](https://user-images.githubusercontent.com/59663011/73573005-8b2a7f00-4472-11ea-9dba-ee8c90128a53.png)
![Screenshot 2020-01-31 at 21 35 45](https://user-images.githubusercontent.com/59663011/73573006-8b2a7f00-4472-11ea-8ec6-87fd047d4c16.png)
The pairing doesn'r work correct

**Comment by arteck** [comment]
works

**Comment by Dragon0501** [comment]
I am sorry but I tried it now. It still doesnt work. What should I do?

**Comment by Dragon0501** [comment]
![IMG_20200203_143531](https://user-images.githubusercontent.com/59663011/73658897-7d087880-4695-11ea-96d5-34a7e8c4abd5.jpg)
