### ISSUE TITLE
GL_D_003ZS not fully recognized 

### ISSUE THREAD

**Issue by vmgonzo** [ioBroker/ioBroker.zigbee#501]
I was able to pair this GL_D_003ZS LED spot, but it creates a single line on the object screen without any properties to control the bulb. 
The GL_D_003Z already exists in the supported device library.
Will appreciate any help.
![GL_D_003ZS-objects - ioBroker](https://user-images.githubusercontent.com/54170640/73178223-1cb38d00-4111-11ea-89b2-e0748cb8f8d5.png)

**Comment by DaCHRIS** [comment]
Where did you see that this spot exists somewhere?

Imho it is neither included in the zigbee-herdsman-converters, nor in the iobroker.zigbee currently.

**Comment by arteck** [comment]
i nedd more infos .. as like this 
![grafik](https://user-images.githubusercontent.com/6681528/75331582-403e3480-5883-11ea-89fc-909616822aaa.png)

**Comment by arteck** [comment]
is comming
