### ISSUE TITLE
Finding no new device

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#502]
After updating to 1.0.1 i could not find any new device. I have made an soft reset of the stick and reload the adapter. I have tested: Ikea motion Sensor E1745, Aqara Cube, Aqara Motion Sensor, Hue Remote Dimmer and Aqara Opple.

Some device are complete new for the stick. Some device paired in past and was deleted.

Have Somebody the same problem and could help?

**Comment by allofmex** [comment]
What firmware stack are you using? Original 1.2 or 3.x?
For 1.2: are you sure you replugged the stick before you searched for devices? Pairing only works within the first minutes!

**Comment by Gwoony** [comment]
Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}

Which is that?

**Comment by Gwoony** [comment]
Update: After some resets in get the message Joining already permitted. After that I start the next pairing modus and now I will find the IKEA Motion sensor. But lost the connection after I bring it to the bath (long way). But some repeaters (Osram Plugs) are close.

**Comment by Gwoony** [comment]
For the next device also not found... I don't know what's happen...

**Comment by Gwoony** [comment]
Today i try my cc2531 Stick flash with repeater SW. He will not found.
After deleting one device. I found the new motion sensor. @ the moment i have 40 devices.
Is there an limit?

**Comment by arteck** [comment]
40 devices.. it's a lot.. I commend to you switch the cc2531 to CC2538+CC2592 PA or cc26x2r1
here is the link quality better
