### ISSUE TITLE
Warning in Log after upgrade iobroker 

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.zigbee#505]
I upgrade iobroker to the recommended version - iobroker.js-controller to  version 2.2.8.

Now I get warning messages from the zigbee-Adpater:

`

zigbee.0 | 2020-01-28 22:25:14.603 | warn | (2133) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!
-- | -- | -- | --
zigbee.0 | 2020-01-28 22:25:14.602 | warn | (2133) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!

`

I already have installed version 0.11.5

At this moment I haven_t noticed any functional problems. I have only a problem with the 

> lumi.sensor_motion.aq2 (Xiaomi - motion sensor)

they often lost the connection to the coordinator in the network map - but this is wrong info. The link value in the object is fine - and they are working properly. So I just ignored the network map - as the information isn't valid.

**Comment by apla2016** [comment]
Update Zigbee adapter to the latest 1.0.1

**Comment by mickym2** [comment]
Installation failed - as it at the end a Osram png file was missing exit code 1. So I got a lot of error messages - however after 10 minutes - the adapter seems to have repaired itself.

So 1.0.1 is running now - and all devices seems to work and the network map is fine as well. 

`

zigbee.0 | 2020-01-29 09:00:57.622 | info | (9462) Zigbee started
-- | -- | -- | --
zigbee.0 | 2020-01-29 09:00:57.621 | info | (9462) 0x00158d000451a514 (addr 56099): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.621 | info | (9462) 0x00158d000411b98e (addr 20161): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.620 | info | (9462) 0x00158d000424453c (addr 44538): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.620 | info | (9462) 0x00158d0004282104 (addr 17104): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.620 | info | (9462) 0x00158d00042006e1 (addr 7192): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.619 | info | (9462) 0x00158d0004201088 (addr 11006): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.619 | info | (9462) 0x00158d0004281fd5 (addr 65275): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.618 | info | (9462) 0x00158d0004221522 (addr 8195): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.618 | info | (9462) 0x00158d0003f4bf3e (addr 49994): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.617 | info | (9462) 0xccccccfffe021ec0 (addr 14026): LED1732G11 - IKEA TRADFRI LED bulb E27 1000 lumen, dimmable, white spectrum, opal white (Router)
zigbee.0 | 2020-01-29 09:00:57.617 | info | (9462) 0xccccccfffeb3e954 (addr 2727): E1746 - IKEA TRADFRI signal repeater (Router)
zigbee.0 | 2020-01-29 09:00:57.617 | info | (9462) 0x086bd7fffe5a9302 (addr 44100): LED1733G7 - IKEA TRADFRI LED bulb E14 600 lumen, dimmable, white spectrum, opal white (Router)
zigbee.0 | 2020-01-29 09:00:57.616 | info | (9462) 0xec1bbdfffeeae2df (addr 1137): LED1649C5 - IKEA TRADFRI LED bulb E12/E14/E17 400 lumen, dimmable warm white, chandelier opal (Router)
zigbee.0 | 2020-01-29 09:00:57.616 | info | (9462) 0xec1bbdfffeebe96b (addr 27762): LED1649C5 - IKEA TRADFRI LED bulb E12/E14/E17 400 lumen, dimmable warm white, chandelier opal (Router)
zigbee.0 | 2020-01-29 09:00:57.615 | info | (9462) 0xec1bbdfffeeadb1a (addr 9019): LED1649C5 - IKEA TRADFRI LED bulb E12/E14/E17 400 lumen, dimmable warm white, chandelier opal (Router)
zigbee.0 | 2020-01-29 09:00:57.614 | info | (9462) 0x00158d0003f13adf (addr 23973): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2020-01-29 09:00:57.610 | info | (9462) Currently 16 devices are joined:
zigbee.0 | 2020-01-29 09:00:57.584 | info | (9462) --> transmitPower : normal
zigbee.0 | 2020-01-29 09:00:57.572 | info | (9462) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
zigbee.0 | 2020-01-29 09:00:56.084 | info | (9462) Starting Zigbee...
zigbee.0 | 2020-01-29 09:00:56.044 | info | (9462) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.18.1


`


Tank you

**Comment by mickym2** [comment]
And in the new version I can see link quality and battery status in the devices view!!!
Great!!
