### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by thatso** [ioBroker/ioBroker.zigbee#508]
I experience two issues In the settings tab of Zigbee adapter 1.0.1:
- typo in the channel selection pulldown: the headline reads "Choose channel**l**"
- if I enter a PanID, select "save and close" and come back, the PanID field is empty. However, if I enter the same PanID again, the save buttons stay greyed out, so internally it is recognized that nothing actually changed?

**Comment by thatso** [comment]
*bump*

**Comment by kirovilya** [comment]
can you clarify how to repeat the problem with panId?

**Comment by thatso** [comment]
I've just tried again with FF 75 and Chromium 76: opening Zigbee adapter -> settings shows an empty field for PanID despite having manually set one.

**Comment by kirovilya** [comment]
Can not reproduse :(
If it is empty - adapter use default value 6754

**Comment by thatso** [comment]
It is **NOT** empty. The ID is set but NOT displayed. Did you even bother to read my description in the first place?

I'm really sick and tired with the attitude the ioBroker project treats issues. Either they are simply ignored for years or quickly closed without any attempt for a fix.
This, the fact that the stable release is outdated for years forcing users to install testing versions and the total lack of any usable documentation (even the wiki on the main page is outdated or simply missing pages) together with hilarious spelling errors all over the place makes my decision easy: I've had it with this project. Moving on to something more mature, where contributors of bugs are welcome. Thank you for nothing.
