### ISSUE TITLE
Unexpected end of JSON input at JSON.parse on getDevices

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#509]
Every time I open the Zigbee Config page I got this error and no devices are showed.

```
zigbee.0 | 2020-01-30 08:46:01.925 | error | (5555) getDevices error: SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at adapter.getStateAsync.then (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:123:72)
-- | -- | -- | --
zigbee.0 | 2020-01-30 08:45:49.536 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
zigbee.0 | 2020-01-30 08:45:49.536 | error | at adapter.getStateAsync.then (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:123:72)
zigbee.0 | 2020-01-30 08:45:49.536 | error | at JSON.parse (<anonymous>)
zigbee.0 | 2020-01-30 08:45:49.536 | error | (5555) getDevices error: SyntaxError: Unexpected end of JSON input
```

---

**System data:**

Model: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM: 7.64 GB
Node.js: v10.18.1
NPM: 6.13.4
Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
JS-Controller (1): 2.1.1
Admin: 3.7.8
Zigbee: 1.0.2

> *created by ioBroker.info*

**Comment by kirovilya** [comment]
It seems that in some "groups" state the device is stored not a correct value.
Try to find them and fix or clear

**Comment by ldittmar81** [comment]
On info.groups I got: {} All other groups states are empty. 

![30-01-_2020_09-26-23](https://user-images.githubusercontent.com/9552828/73432586-579d0700-4343-11ea-9af1-4012f3e257d0.jpg)
![30-01-_2020_09-31-16](https://user-images.githubusercontent.com/9552828/73432592-59ff6100-4343-11ea-82bb-1a2114d4c1cf.jpg)

I made one group for test, but I deletet it. I got no groups now.

**Comment by ldittmar81** [comment]
Hmm... I will try  to put some logs on the command.js to see what happens.

**Comment by kirovilya** [comment]
thank you. I made changes in code

**Comment by ldittmar81** [comment]
Thx :+1:
