### ISSUE TITLE
Xiaomi AQara keine binding

### ISSUE THREAD

**Issue by mcchickents** [ioBroker/ioBroker.zigbee#51]
Guten Abend,

bekomme den Xiaomi AQara nicht gebindet. Drücke den Knopf einmal am AQara bis es blau blink leider keine Verbindung zum zigbee auf Io

Error: Cannot get the Node Descriptor of the Device

**Comment by arteck** [comment]
Xiaomi AQara ist eine Gerätereihe.. was ist das für ein teil ??

**Comment by DenwoT** [comment]
Wenn du sie Verbinden möchtest musst du den Sensor wach halten.

1. Klicke auf Gerät hinzufügen
2. Der Scan läuft
3. Halte den reset Button für 5 Sekunden gedrückt bis der Sensor 3 mal blinkt
4. Drücke weiter den reset Button (kurz) alle 1-2 Sekunden (somit hältst du den Sensor wach)
5. Im Scan siehst du dann die % Anzahl wenn er ihn gefunden hat.

Sollte wieder die Error Meldung kommen, geh weiter an den Stick heran. Der Motion Sensor hat mit dem Stick bei mir ein Motion detection von 1 Minute. Dazwischen ist leider Funkstille.

**Comment by daniel-lo** [comment]
Apologies!
zigbee adapter won't let me pair my Aqara Cube which has just arrived. ioBroker is ready for devices to join but sees nothing of the Cube. I tried following above instructions: press 5 seconds and then keep the sensor awake by pressing every 1-2 secs. No reaction whatsoever. I moved closer to the USB stick to no avail.

**Comment by daniel-lo** [comment]
Made it. The think is that the response of the keep-awake button presses has to be a flashing LED and not a short on-off. Otherwise you are too far away from the Zigbee controller. What I need to find out now is the range that I can used devices in .. if it's as small as for pairing .. I have a problem ;-)

**Comment by arteck** [comment]
look in forum for range problem.. you can install a router .. problem solved..
