### ISSUE TITLE
Philips Hue Motion Sensor (SML002) missing Values 

### ISSUE THREAD

**Issue by iob2020** [ioBroker/ioBroker.zigbee#513]
Hi,
with the iobroker zigbee adapter Version 1.0.2 I have following Variables
![image](https://user-images.githubusercontent.com/60627429/73690165-0dfc4580-46d0-11ea-8fb4-5070e2e5c664.png)
When i look at the deconz app (Dresden Elektronik) the conbee2 Stick has a lot more Variables:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Philips-Hue-sniffing#hue-motion-sensor
Also the Lux Value is wrong / extremely high.

Is it possible to get the all the Values with the iobroker?

**Comment by allofmex** [comment]
What variables are missing in your opinion? We have almost all available already. (Only those with cluster/attribute values in deconz table are possible)

Regarding illuminance:
There is pending PR that may be related https://github.com/Koenkk/zigbee-herdsman-converters/pull/950. When they are finished there, we may add the converted-to-lux for SML001+2 too. But let's wait until it is finalized.

**Comment by iob2020** [comment]
ledindication or usertest ?

thanks for the information converted-to-lux. i did not know that.

**Comment by allofmex** [comment]
> ledindication or usertest ?

You may test both with DeveloperTab already. 

As far as I remember, `usertest` was some kind of test mode. When activated, sensor was permanently publishing occupancy changes, ignoring minimum 15sec occupancy_timeout. That will drain battery very fast, so it's not a normal mode of operation -> no need to implement as state. Those who want to use it for whatever reason may switch it via DeveloperTab.

When I tried last time `ledindication`, it did not changed anything for me. But you may test in DevTab yourself and report here. It may be of interest to implement enable/disable-led-on-occupancy-change.

**Comment by iob2020** [comment]
OK. Thank You. I will test it. But where can I find the exact commands for usertest and ledindication to activate?

**Comment by allofmex** [comment]
Just tried it myself. Seems it's not possible with herdsman version to send non-standard/custom attributes yet. Have to look in this later how to fix.
Sorry, DeveloperTab does not help you for this at the moment, because there is no attribute 50 (=0x0033) available.
