### ISSUE TITLE
adapter red after node.js update

### ISSUE THREAD

**Issue by Vaskes1986** [ioBroker/ioBroker.zigbee#516]
After update I got this 

instance   system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
--
Caught   by controller[0]: at Object.Module._extensions..js   (internal/modules/cjs/loader.js:789:10)
Caught   by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
Caught   by controller[0]: at Object.<anonymous>   (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/serialport/lib/bindings/linux.js:2:36)
Caught   by controller[0]: at bindings   (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/bindings/bindings.js:81:44)
Caught   by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
Caught   by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
Caught   by controller[0]: at Function.Module._load   (internal/modules/cjs/loader.js:585:3)
Caught   by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Caught   by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
Caught   by controller[0]: at Object.Module._extensions..node   (internal/modules/cjs/loader.js:807:18)
Caught   by controller[0]: the module (for instance, using `npm rebuild` or `npm   install`).
Caught   by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or   re-installing
Caught   by controller[0]: NODE_MODULE_VERSION 57. This version of Node.js requires
Caught   by controller[0]: was compiled against a different Node.js version using
Caught   by controller[0]: Error: The module   '/opt/iobroker/node_modules/iobroker.zigbee/node_modules/serialport/build/Release/serialport.node'
Caught by controller[0]: ^
Caught by controller[0]:   throw e
Caught   by controller[0]:   /opt/iobroker/node_modules/iobroker.zigbee/node_modules/bindings/bindings.js:88

I tried many things, but nothing helped
sudo npm install serialport --unsafe-perm --build-from-source
sudo npm rebuild
sudo npm install iobroker.zigbee --unsafe-perm 
this picture I see after rebuild
> @serialport/bindings@8.0.7 install /home/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.19.75-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node_modules/@serialport/bindings
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.7 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@8.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-06T19_01_34_409Z-debug.log

**Comment by SteevieBDE** [comment]
same on my iobroker...

**Comment by kirovilya** [comment]
the error is due to the fact that you updated the nodejs, after installing the serialport.
try running `npm rebuild` in iobroker or in adapter directory

**Comment by Vaskes1986** [comment]
My success story:
1. iobroker stop
2. cd /opt/iobroker/node_modules/iobroker.zigbee cd /opt/iobroker/node_modules/iobroker.zigbee
3. sudo npm rebuild --unsafe-perm
4.  iobroker start
Thank you!
