### ISSUE TITLE
Missing sensitivity state for Xiaomi Vibration Sensor (lumi.vibration.aq1)

### ISSUE THREAD

**Issue by grdminer** [ioBroker/ioBroker.zigbee#517]
Issue #470 was closed but Issue is not solved yet

I cant confirm that it works! Installed latest version and sensitivity is still not set successfully
`

zigbee.0 | 2020-02-07 10:05:21.270 | error | at anonymous
-- | -- | -- | --
zigbee.0 | 2020-02-07 10:05:21.270 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
zigbee.0 | 2020-02-07 10:05:21.270 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-02-07 10:05:21.270 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:150:23)
zigbee.0 | 2020-02-07 10:05:21.270 | error | (4329) Error on send command to 0x00xx. Error: Error: Write 0x00xx/1 genBasic({"65293":{"value":11,"type":32}}, {"timeout":10000,"defaultResponseTimeout":15000,"manufacturerCo`

_Originally posted by @grdminer in https://github.com/ioBroker/ioBroker.zigbee/issues/470#issuecomment-583298849_

**Comment by grdminer** [comment]
Ok, I think I've got a solution. The standard behaviour in the Mi Home App for changing the sensitivity level one need to confirm the change by pushing the button at the sensor within a quite short timeframe (around 10s) after changing the level. Seems to be a security feature. The same thing seems to work for the zigbee adapter, at least no error message appears. Can anyone confirm that?

@Experts: is it burned in hardware or is there a chance to "overwrite" that behaviour? In my opinion this security feature is only one thing: uncomfortable.

**Comment by kirovilya** [comment]
This is not a security feature. the sensor is usually in a state of sleep. therefore, all messages to it may not reach. in order to wake up the sensor - briefly press the button on it.
this applies to all sensors on batteries.

**Comment by grdminer** [comment]
Ok, that makes sense. But setting the occupancy_timeout for the xiaomi motion sensor doesnt need this confirmation/wake up step and works without any interaction with the sensor.
