### ISSUE TITLE
Can't connect ecozy

### ISSUE THREAD

**Issue by Meinsda** [ioBroker/ioBroker.zigbee#519]
Hello!

I want to connect my ecozy thermostat to my iobroker system an alwys get this error message 

zigbee.0 | 2020-02-08 08:43:19.108 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
zigbee.0 | 2020-02-08 08:43:19.108 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-02-08 08:43:19.108 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:235:23)
zigbee.0 | 2020-02-08 08:43:19.108 | error | (2404) Failed to configure 0x70b3d5de000013dc Thermostat, attempt 2 (Error: Bind 0x70b3d5de000013dc/3 hvacThermostat from '0x00124b0014d9d890/1' failed (Error: AREQ - ZDO - bindRsp after 10000ms)
zigbee.0 | 2020-02-08 08:43:03.993 | info | (2404) Configuring 0x70b3d5de000013dc Thermostat
zigbee.0 | 2020-02-08 08:42:57.008 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
zigbee.0 | 2020-02-08 08:42:57.008 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-02-08 08:42:57.008 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:235:23)
zigbee.0 | 2020-02-08 08:42:57.008 | error | (2404) Failed to configure 0x70b3d5de000013dc Thermostat, attempt 1 (Error: Bind 0x70b3d5de000013dc/3 genPowerCfg from '0x00124b0014d9d890/1' failed (Error: AREQ - ZDO - bindRsp after 10000ms)

I have two devices. Both makes the same error!
If i connect the device i see them in the list, but there are no values and it needs a lot of time to open the configaration at the adpater.

**Comment by asgothian** [comment]
The devices refuse the initial device configuration for communication. This is most likely an error with the zigbee connection or the ecosystem device itself. I had made an attempt to integrate them but had to give up as the device did not function properly.

A.
