### ISSUE TITLE
Please implement Heiman Smart Siren

### ISSUE THREAD

**Issue by MichaelGier** [ioBroker/ioBroker.zigbee#52]
Dear Team,

Currently it is not supported by the adapter. I cannot even pair it.

THANKS

**Comment by MichaelGier** [comment]
[debug_zigbee_heiman_siren.txt](https://github.com/ioBroker/ioBroker.zigbee/files/2375087/debug_zigbee_heiman_siren.txt)

Hi.
Thanks for your answer. 
Here are the debug-file of pairing.

bye

**Comment by kirovilya** [comment]
@MichaelGier :( there is no data about pairing process. it should contain more data. such as here
https://github.com/ioBroker/ioBroker.zigbee/issues/26#issuecomment-414058595

**Comment by MichaelGier** [comment]
i hope now the infos complete ;-) Its my first time !


zigbee.0 | 2018-09-12 14:56:34.704 | debug | getDevices result:  [{"type":"device","common":{"name":"lumi.router","type":"lumi.router","icon":"img/lumi_router.png"},"from":"system.adapter.zigbee.0","ts":1536756329456,"_id":"zigbee.0.00124b00181d
-- | -- | -- | --
zigbee.0 | 2018-09-12 14:56:34.645 | debug | Device 000d6f000be7b1d9 "WarningDevice" not described in statesMapping.
zigbee.0 | 2018-09-12 14:56:34.627 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"New device joined  0x000d6f000be7b1d9 model  WarningDevice","ack":false,"ts":1536756994614,"q":0,"from":"system.adapter.zigbee.0","lc":153675699461
zigbee.0 | 2018-09-12 14:56:34.620 | debug | Message without data cluster!
zigbee.0 | 2018-09-12 14:56:34.619 | debug | handleMessage.  {"type":"devStatus","endpoints":[{"device":{"_id":6,"type":"Router","ieeeAddr":"0x000d6f000be7b1d9","nwkAddr":13418,"manufId":4619,"manufName":"Heiman","modelId":"WarningDevice","epLis
zigbee.0 | 2018-09-12 14:56:34.612 | info | new dev 0x000d6f000be7b1d9 13418 WarningDevice
zigbee.0 | 2018-09-12 14:56:34.608 | debug | new device 0x000d6f000be7b1d9 joining the network!
zigbee.0 | 2018-09-12 14:56:34.607 | debug | handleMessage.  {"type":"devIncoming","endpoints":[{"device":{"_id":6,"type":"Router","ieeeAddr":"0x000d6f000be7b1d9","nwkAddr":13418,"manufId":4619,"manufName":"Heiman","modelId":"WarningDevice","epL
zigbee.0 | 2018-09-12 14:56:34.601 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  100%","ack":false,"ts":1536756994589,"q":0,"from":"system.adapter.zigbee.0","lc":1536756994589}
zigbee.0 | 2018-09-12 14:56:34.588 | debug | Device 0x000d6f000be7b1d9 try to connect {"totalEp":1,"currentEp":1,"progress":100}
zigbee.0 | 2018-09-12 14:56:34.587 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":7,"current":7},"total":1}},"data":"0x000d6f000be7b1d9"}
zigbee.0 | 2018-09-12 14:56:34.474 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  35","ack":false,"ts":1536756994467,"q":0,"from":"system.adapter.zigbee.0","lc":1536756994467}
zigbee.0 | 2018-09-12 14:56:34.467 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":35,"ack":false,"ts":1536756994463,"q":0,"from":"system.adapter.zigbee.0","lc":1536756994463}
zigbee.0 | 2018-09-12 14:56:34.460 | debug | Join countdown. 35
zigbee.0 | 2018-09-12 14:56:34.349 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  86%","ack":false,"ts":1536756994344,"q":0,"from":"system.adapter.zigbee.0","lc":1536756994344}
zigbee.0 | 2018-09-12 14:56:34.342 | debug | Device 0x000d6f000be7b1d9 try to connect {"totalEp":1,"currentEp":1,"progress":86}
zigbee.0 | 2018-09-12 14:56:34.341 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":7,"current":6},"total":1}},"data":"0x000d6f000be7b1d9"}
zigbee.0 | 2018-09-12 14:56:33.851 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  71%","ack":false,"ts":1536756993843,"q":0,"from":"system.adapter.zigbee.0","lc":1536756993843}
zigbee.0 | 2018-09-12 14:56:33.840 | debug | Device 0x000d6f000be7b1d9 try to connect {"totalEp":1,"currentEp":1,"progress":71}
zigbee.0 | 2018-09-12 14:56:33.838 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":7,"current":5},"total":1}},"data":"0x000d6f000be7b1d9"}
zigbee.0 | 2018-09-12 14:56:33.519 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  57%","ack":false,"ts":1536756993506,"q":0,"from":"system.adapter.zigbee.0","lc":1536756993506}
zigbee.0 | 2018-09-12 14:56:33.504 | debug | Device 0x000d6f000be7b1d9 try to connect {"totalEp":1,"currentEp":1,"progress":57}
zigbee.0 | 2018-09-12 14:56:33.503 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":7,"current":4},"total":1}},"data":"0x000d6f000be7b1d9"}
zigbee.0 | 2018-09-12 14:56:33.458 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  36","ack":false,"ts":1536756993454,"q":0,"from":"system.adapter.zigbee.0","lc":1536756993454}
zigbee.0 | 2018-09-12 14:56:33.451 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":36,"ack":false,"ts":1536756993447,"q":0,"from":"system.adapter.zigbee.0","lc":1536756993447}
zigbee.0 | 2018-09-12 14:56:33.444 | debug | Join countdown. 36
zigbee.0 | 2018-09-12 14:56:33.266 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  43%","ack":false,"ts":1536756993257,"q":0,"from":"system.adapter.zigbee.0","lc":1536756993257}
zigbee.0 | 2018-09-12 14:56:33.255 | debug | Device 0x000d6f000be7b1d9 try to connect {"totalEp":1,"currentEp":1,"progress":43}
zigbee.0 | 2018-09-12 14:56:33.253 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":7,"current":3},"total":1}},"data":"0x000d6f000be7b1d9"}
zigbee.0 | 2018-09-12 14:56:33.010 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  29%","ack":false,"ts":1536756993001,"q":0,"from":"system.adapter.zigbee.0","lc":1536756993001}
zigbee.0 | 2018-09-12 14:56:32.999 | debug | Device 0x000d6f000be7b1d9 try to connect {"totalEp":1,"currentEp":1,"progress":29}
zigbee.0 | 2018-09-12 14:56:32.997 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":7,"current":2},"total":1}},"data":"0x000d6f000be7b1d9"}
zigbee.0 | 2018-09-12 14:56:32.710 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Interview state:  step 1/1. progress:  14%","ack":false,"ts":1536756992702,"q":0,"from":"system.adapter.zigbee.0","lc":1536756992702}
zigbee.0 | 2018-09-12 14:56:32.700 | debug | Device 0x000d6f000be7b1d9 try to connect {"totalEp":1,"currentEp":1,"progress":14}
zigbee.0 | 2018-09-12 14:56:32.699 | debug | handleMessage.  {"type":"devInterview","status":{"endpoint":{"current":1,"cluster":{"total":7,"current":1},"total":1}},"data":"0x000d6f000be7b1d9"}
zigbee.0 | 2018-09-12 14:56:32.450 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  37","ack":false,"ts":1536756992446,"q":0,"from":"system.adapter.zigbee.0","lc":1536756992446}
zigbee.0 | 2018-09-12 14:56:32.446 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":37,"ack":false,"ts":1536756992443,"q":0,"from":"system.adapter.zigbee.0","lc":1536756992443}
zigbee.0 | 2018-09-12 14:56:32.441 | debug | Join countdown. 37
zigbee.0 | 2018-09-12 14:56:31.462 | debug | User stateChange zigbee.0.info.pairingMessage {"val":"Time left:  38","ack":false,"ts":1536756991447,"q":0,"from":"system.adapter.zigbee.0","lc":1536756991447}
zigbee.0 | 2018-09-12 14:56:31.458 | debug | User stateChange zigbee.0.info.pairingCountdown  {"val":38,"ack":false,"ts":1536756991442,"q":0,"from":"system.adapter.zigbee.0","lc":1536756991442}
zigbee.0 | 2018-09-12 14:56:31.437 | debug | Join countdown. 38

**Comment by MichaelGier** [comment]
okay. i will wait.
thx for your work
