### ISSUE TITLE
Heiman SmokeSensor-N-3.0

### ISSUE THREAD

**Issue by stamboleo** [ioBroker/ioBroker.zigbee#520]
![image](https://user-images.githubusercontent.com/47795609/74083121-cfb0ae80-4a60-11ea-9018-c7eacdba2591.png)

Not alle of my Heiman Smoke Sensor are working :(

**Comment by stamboleo** [comment]
Details
model:HS3SA
vendor:HEIMAN
description:Smoke detector
supports:smoke
model:SmokeSensor-N-3.0
type:EndDevice
nwk:48921
manuf id:4619
manufacturer:HEIMAN
power:Battery
app version:20
hard version:16
zcl version:2
stack version:2
date code:2018.9.27
build:2000-0001
interviewed:true
configured:true
endpoint:1
profile:260
input clusters:0,3,1,1280,1282,2821
output clusters:25

**Comment by stamboleo** [comment]
zigbee.0 | 2020-02-21 09:33:48.252 | error | (851) Device 00158d00027546c1 "SmokeSensor-N-3.0" not described in statesMapping.
-- | -- | -- | --
zigbee.0 | 2020-02-21 09:13:09.057 | error | (851) Device 00158d00027559b0 "SmokeSensor-N-3.0" not described in statesMapping.
zigbee.0 | 2020-02-21 09:13:07.904 | error | (851) Device 00158d00027559b0 "SmokeSensor-N-3.0" not described in statesMapping.

**Comment by stamboleo** [comment]
Someone can help with this issue?

**Comment by DaCHRIS** [comment]
There is a typo in the devices.js

![image](https://user-images.githubusercontent.com/8064903/75050902-3310f680-54cd-11ea-90d6-c89505ba6686.png)

I'll send a PR, for the meantime change it manually in the file:
 /opt/iobroker/node_modules/iobroker.zigbee/lib/devices.js

Cheers 
Chris

**Comment by DaCHRIS** [comment]
PR sent: 
https://github.com/ioBroker/ioBroker.zigbee/pull/534 

HaVe PhUn...

**Comment by stamboleo** [comment]
Thanks
