### ISSUE TITLE
Adapter is being red

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#524]
Hello

i have the problem after an update to 1.0.3 the adapter ist being red.
Also after downgrading to 1.0.2

this it the error log

host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.297 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.297 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/@serialport/bindings/lib/index.js:14:22)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.297 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.296 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.296 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.296 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.296 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.295 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.295 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.295 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/@serialport/bindings/lib/linux.js:2:36)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.295 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/bindings/bindings.js:126:9)
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.294 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/lib/binding/node-v64-linux-arm/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.294 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.294 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.293 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.293 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/compiled/10.17.0/linux/arm/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.293 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/build/default/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.292 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/Release/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.292 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/out/Release/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.292 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/Debug/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.292 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/out/Debug/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.291 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.291 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/build/Debug/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.291 | error | Caught by controller[0]: → /opt/iobroker/node_modules/@serialport/bindings/build/bindings.node
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.291 | error | Caught by controller[0]: Error: Could not locate the bindings file. Tried:
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.290 | error | Caught by controller[0]: ^
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.290 | error | Caught by controller[0]: throw err;
host.ioBroker-RasPi-fabster | 2020-02-09 20:18:46.289 | error | Caught by controller[0]: /opt/iobroker/node_modules/bindings/bindings.js:135

**Comment by Gwoony** [comment]
After an update I get the new Error Code:


host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.405 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.405 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.404 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.404 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.404 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.404 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.403 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/serialport/lib/index.js:2:17)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.403 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.403 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.403 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.402 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.402 | error | Caught by controller[0]: Error: Cannot find module '@serialport/bindings'
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.402 | error | Caught by controller[0]: ^
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.401 | error | Caught by controller[0]: throw err;
host.ioBroker-RasPi-fabster | 2020-02-09 22:15:48.401 | error | Caught by controller[0]: internal/modules/cjs/loader.js:638

**Comment by Gwoony** [comment]
hello please help, my whole flat is dark. No light no Button nothings works... :-(

**Comment by kirovilya** [comment]
your problems in serialport package.
make backup. then, try to remove adapter and reinstall it again.

**Comment by Gwoony** [comment]
Must I pair my device again?
I have also the Problem that I could not stop iobroker and restore a backup.

Backup is available 

Thank you

**Comment by kirovilya** [comment]
no, if the database file is saved in the iobroker-data directory (or you can restore it from backup)

**Comment by Gwoony** [comment]
how could I restore it?

**Comment by kirovilya** [comment]
it is simple file iobroker-data/zigbee_0/shepherd.db - just stop adapter and copy.

**Comment by Gwoony** [comment]
Thanks now it’s work
