### ISSUE TITLE
New Devices

### ISSUE THREAD

**Issue by Neuling999** [ioBroker/ioBroker.zigbee#526]
Hi there,
is it possible to add devices myself?
If so, where and how.
for example:
Philips LWG001
OSRAM AC08560

**Comment by DaCHRIS** [comment]
Heyas Neuling, 

both bulbs are already included in the zigbee-herdsman-converters > https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js 

If you own them try adding them into the file "/opt/iobroker/node_modules/iobroker.zigbee/lib/devices.js". Copy one other bulb and fill in the model information, or fill in the new model as a second option to an already available one. As I can see it, for osram and philips the block is always the same. 

Cheers 

Chris

**Comment by DaCHRIS** [comment]
Commits for your lights requested in 
https://github.com/ioBroker/ioBroker.zigbee/pull/534

HaVe PhUn
