### ISSUE TITLE
Error in device detection iluminize Zigbee 3.0 Schalt-Aktor Mini, 1 Kanal 230V (511.202) 

### ISSUE THREAD

**Issue by Maschler** [ioBroker/ioBroker.zigbee#528]
Hello, everybody,

I just wanted to couple my 511.202 ZigBee 3.0 switching actuator Mini from iluminize. It can only switch lamps on or off. I am using the zigbee version 1.0.3.

The actuator was found and created as 511.202. But I can't find it among Zigbee objects.
<img width="455" alt="1" src="https://user-images.githubusercontent.com/38862834/74527965-59f88700-4f27-11ea-9748-f488a0d9b05c.PNG">

<img width="202" alt="2" src="https://user-images.githubusercontent.com/38862834/74527981-62e95880-4f27-11ea-9598-6bdf2797f0e0.PNG">

![grafik](https://user-images.githubusercontent.com/38862834/74528673-83fe7900-4f28-11ea-85d6-da9afefe7ebe.png)

This is the output of the Details:
    
model:511.202
    vendor:Iluminize
    description:Zigbee 3.0 Schalt-Aktor mini 1x230V, 200W/400W
    supports:on/off
    model:511.202
    type:Router
    manuf id:4107
    manufacturer:iluminize
    power:Mains (single phase)
    app version:0
    hard version:0
    zcl version:3
    stack version:0
    date code:NULL
    build:2.5.3_r40
    interviewed:true
    configured:true

Currently supported is the 511.201 ZigBee 3.0 dimming actuator mini 1x 230V (on/off, brightness).

**Comment by DaCHRIS** [comment]
Hi Maschler, 
at least it is included in zigbee-herdsman-converters. 

For the iobroker Part I have no idea, but to test you could try to add it in the file "/opt/iobroker/node_modules/iobroker.zigbee/lib/devices.js" under the Illuminize block
´´´
    {
        vendor: 'Illuminize',
        models: ['511.202'],
        icon: 'img/illuminize_511_201.png',
        states: [states.state],
    },
´´´
...or as alternative the "states:" like the other 201 illuminize.

**Comment by Maschler** [comment]
Hello,

this works fine. Even the iobroker Part works.

<img width="843" alt="54" src="https://user-images.githubusercontent.com/38862834/74774603-5bfa7700-5294-11ea-9d1b-5e7b1a354270.PNG">

**Comment by DaCHRIS** [comment]
Nice, Then please fork this repo, fill in your changes and make a pull request. 

Cheers
Chris

**Comment by DaCHRIS** [comment]
Added the necessary commit to my pending PR https://github.com/ioBroker/ioBroker.zigbee/pull/534/commits/70ec5fd9fdebd7ff15d1f60258fa0f483a43c874
