### ISSUE TITLE
States of grouped devices are not updated

### ISSUE THREAD

**Issue by denzel1994** [ioBroker/ioBroker.zigbee#529]
When controlling lightbulbs, which are grouped together, via the group states the states of the individual lightbulbs are not updated.

<img width="1479" alt="52171585-8ba91080-275f-11e9-9093-8d7b18c8d827" src="https://user-images.githubusercontent.com/36551243/74597175-ad1f2680-505a-11ea-88e8-853e8f460236.png">

For example: Stehlampe "Oben" "Mitte" "Unten" are gathered in group 2. If I set the switch state of group 2 to "false" all three lightbulbs turn off as expected, but the switch state of each individual lightbulb still shows "true.
Same goes for changing brightness or colortemp.

**Comment by PiXBalance** [comment]
hope there will be a solution. it's not only the sate, also brightness of the device is not updated if the group brightness is changed.

**Comment by denzel1994** [comment]
Nothing has changed so far. Individual device states are not updated when changed in the corresponding group.

**Comment by vain90** [comment]
Are here any new informations? This problem is really annoying. Especially I would like to use scenes and turn off all lights with a group.

**Comment by Strunzdesign** [comment]
Yes, I agree, please do not let this bug get closed due to inactivity... I also have the problem that I would like to use the groups / scenes feature, ideally similar to that provided by a HUE bridge, but currently that is simply not possible. Having a sync of states from a group down to the grouped objects would be a good start.

**Comment by allofmex** [comment]
I admit it has some limitations, that individual states are not updated, but why not just rely on the group object values and assume that all bulbs got set accordingly?
What's the use case of handling group AND individual states at same time?

**Comment by vain90** [comment]
> What's the use case of handling group AND individual states at same time?

Not at same time! I have one scene to turn all living room lights to off. No matter how many lights are turned on by other scenes. The "turn off" scene only triggers the group state. This reduce zigbee traffic.

**Comment by vain90** [comment]
Reopen.

Unfortunately the issue is still closed.
Is there anything new?

Same question here #831
