### ISSUE TITLE
Implement Serial Port selector in Configuration Dialog

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.zigbee#53]
You can see the implementation here:
Frontend:
https://github.com/ioBroker/ioBroker.zwave/blob/master/admin/index.html#L119
https://github.com/ioBroker/ioBroker.zwave/blob/master/admin/index.html#L338

Backend: 
https://github.com/ioBroker/ioBroker.zwave/blob/master/main.js#L153
https://github.com/ioBroker/ioBroker.zwave/blob/master/main.js#L524

**Comment by Apollon77** [comment]
works in general ... BUT UI selection list is broken and not showing complete list ... when I scroll whole page I see more

<img width="1564" alt="bildschirmfoto 2018-09-27 um 21 39 05" src="https://user-images.githubusercontent.com/11976694/46170469-371bf300-c29e-11e8-89ca-797c2808f71b.png">

**Comment by kirovilya** [comment]
Strange, I see a scroll bar ...
![image](https://user-images.githubusercontent.com/8360230/46193779-fbb60e80-c307-11e8-907e-cde5f08560c2.png)

Ubuntu 18.04 Chrome 69
