### ISSUE TITLE
paring counter hangs in ui

### ISSUE THREAD

**Issue by Meinsda** [ioBroker/ioBroker.zigbee#532]
at my iobroker the paring counter stops after some secounds. Also the green button. In the logfile i can see the start and stoping the pairing mode. But i can't start the paring mode again without restarting the adapter.

**Comment by asgothian** [comment]
Please provide log files of the adapter in debug mode when this happens. I have no issues with entering pairing mode with the current version.

**Comment by arteck** [comment]
which adapter version ??

**Comment by Meinsda** [comment]
Which version do you mean? Hard or software?

**Comment by arteck** [comment]
adapter version is software...

**Comment by Meinsda** [comment]
I can't say because i have change my hardware to a 26x2r1 chipset, There the communication works much better.
