### ISSUE TITLE
Error when No state available 

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.zigbee#535]
Adapter Version 1.0.3

Wenn bei den Objekten (z.B. beim lumi.sensor_magnet.aq2) ein neues Objekt eingefügt wird,
z.B. OpenAlarm, um einen Tür-Offen Alarm anzuzeigen,
dann erhalte ich im Log:
error: "No state available for 'lumi.sensor_magnet.aq2' with key 'OpenAlarm'"
es funktioniert aber, nur der error stört.
Das Alarm-Objekt unter dem Gerät wäre dafür ja ideal, um nicht extra ein neues Root-Objekt
anlegen zu müssen.

Es wäre sehr schön, wenn jemand von den Spezialisten diesen Alarm entfernen würde.
Vielen Dank schon einmal.

**Comment by Hans-Zwiesel** [comment]
Ich habe OpenAlarm gelöscht und neu AlarmStatus und AlarmZeit angelegt.
Bekomme aber nur den Fehler: No state available for 'lumi.sensor_magnet.aq2' with key 'AlarmStatus'


![grafik](https://user-images.githubusercontent.com/49147193/75144276-f294c100-56f6-11ea-9aec-d44e098906d4.png)

**Comment by Hans-Zwiesel** [comment]
Plötzlich erscheint auch ein Fehler bei AlarmZeit:
(17525) No state available for 'lumi.sensor_magnet.aq2' with key 'AlarmZeit'

**Comment by arteck** [comment]
dir ist schon klar dass das erzeuge states sind die man nicht ändern oder hinzufügen sollte... 
ergo kein issue

**Comment by Hans-Zwiesel** [comment]
...war mir nicht klar, habe aber inzwischen ein eigenes root objekt dafür erzeugt.
Vielen Dank für den Hinweis.
