### ISSUE TITLE
TRADFRI wireless dimmer

### ISSUE THREAD

**Issue by axelbub** [ioBroker/ioBroker.zigbee#54]
Hello,
can you please implement the  IKEA TRADFRI wireless dimmer ?
The friendly project ZIGBEE2MQTT has it implementated but it would be nice to controll it directly in the Zigbee iobroker adapter.

Thank you,
Axel

**Comment by n3roGit** [comment]
+1

**Comment by Bieka** [comment]
+1. Hoped it would be included in the next Version but 0.7.6 didn't include that. Please add the Wireless Dimmer ;) Thanks in Advance!

**Comment by hotterstedt** [comment]
+1

**Comment by cy-coe** [comment]
+1

**Comment by killakaktus** [comment]
Hi! Any news?

**Comment by Bieka** [comment]
Works with 0.8.0 but it's acting a little weird. Sensible on one Hand and on the other hand it works the wrong Way... E.g. when you turn it right too much it jumps to off or 5% or something different! But in the End i'm happy that it works now. Kudos to the devs! Maybe someone could tweak it a little bit. 
Maybe the other Tradfri Remote could be implented too?

**Comment by killakaktus** [comment]
@Bieka thanks for reply. 

just tested it. like you said, its weird. difficult to get the desired value but i thinks its on a good way. hope it will work soon.
