### ISSUE TITLE
Xiaomi EU Plug funktioniert nicht (lumi.plug.mmeu01)

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.zigbee#545]
ich habe zwei oben genannte Geräte die sich beide nicht korrekt koppeln lassen.

das Gerät erscheint im Zigbee-Adapter und er verwendet ihn scheinbar auch als Repeater aber sonst kann man ihn nicht verwenden (keine Datenpunkte).
Koppeln über Alexa Show 10 funktioniert, aber leider ohne Verbrauchsmessung.

JS controller 2.2.9
Nodejs v10.19.0
Zigbee Adapter 1.0.3
Zigbee stick: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}

Plug-Details: 

    model:ZNCZ04LM
    vendor:Xiaomi
    description:Mi power plug ZigBee EU
    supports:on/off, power measurement

    model:lumi.plug.mmeu01
    type:Router
    nwk:22174
    manuf id:4447
    manufacturer:LUMI
    power:Mains (single phase)
    app version:22
    hard version:1
    zcl version:3
    stack version:2
    date code:09-06-2019
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:0,2,3,4,5,6,9,1794,2820
    output clusters:10,25

    endpoint:242
    profile:41440
    input clusters:
    output clusters:33

`zigbee.0 | 2020-02-29 10:47:22.888 | info | (15217) Zigbee: stop joining
-- | -- | -- | --
zigbee.0 | 2020-02-29 10:46:28.538 | error | (15217) Device 04cf8cdf3c75a6e2 "lumi.plug.mmeu01" not described in statesMapping.
zigbee.0 | 2020-02-29 10:46:26.090 | error | (15217) Device 04cf8cdf3c75a6e2 "lumi.plug.mmeu01" not described in statesMapping.
zigbee.0 | 2020-02-29 10:46:23.814 | info | (15217) Device '0x04cf8cdf3c75a6e2' is supported, identified as: Xiaomi Mi power plug ZigBee EU (ZNCZ04LM)
zigbee.0 | 2020-02-29 10:46:23.813 | info | (15217) Successfully interviewed '0x04cf8cdf3c75a6e2', device has succesfully been paired
zigbee.0 | 2020-02-29 10:46:23.747 | error | (15217) Device 04cf8cdf3c75a6e2 "lumi.plug.mmeu01" not described in statesMapping.
zigbee.0 | 2020-02-29 10:46:23.692 | error | (15217) Device 04cf8cdf3c75a6e2 "lumi.plug.mmeu01" not described in statesMapping.
zigbee.0 | 2020-02-29 10:46:23.632 | error | (15217) Device 04cf8cdf3c75a6e2 "lumi.plug.mmeu01" not described in statesMapping.
zigbee.0 | 2020-02-29 10:46:23.565 | error | (15217) Device 04cf8cdf3c75a6e2 "lumi.plug.mmeu01" not described in statesMapping.
zigbee.0 | 2020-02-29 10:46:23.501 | error | (15217) Device 04cf8cdf3c75a6e2 "lumi.plug.mmeu01" not described in statesMapping.
zigbee.0 | 2020-02-29 10:46:22.832 | info | (15217) Starting interview of '0x04cf8cdf3c75a6e2'
zigbee.0 | 2020-02-29 10:46:21.853 | info | (15217) Zigbee: allowing new devices to join.

`

**Comment by DaCHRIS** [comment]
Der müsste aber ein Fragezeichen haben und auch keine Linkquality anzeigen?

In den zigbee2mqtt supported devices sieht er sehr ähnlich aus zum Modell 02LM, in den herdsman-converters unterscheidet er sich dann aber. 

Teste mal bitte in Deiner lokalen Installation folgendes in die Datei "/opt/iobroker/node_modules/iobroker.zigbee/lib# nano devices.js" als nächsten Block hinter ['lumi.plug'] einzufügen. 

```
    {
        vendor: 'Xiaomi',
        models: ['lumi.plug.mmeu01'],
        icon: 'img/plug.png',
        states: [states.state, states.load_power, states.plug_voltage, states.plug_consumption, states.plug_temperature],
    },

```
Danach den die Zigbee Instanz restarten und dann siehst Du mal nach welche Datenpunkte danach in den Objekten sind und welche davon funktionieren.

**Comment by Omega236** [comment]
habe es gemacht und es funktionier! Vielen Dank.
Das icon lightify-plug.png passt etwas besser.

ich erzeuge mal noch einen Pullreques

**Comment by Omega236** [comment]
![grafik](https://user-images.githubusercontent.com/25373047/75625576-b1515500-5bbf-11ea-9b51-c6ab854756b7.png)

Ok, die Load_power kam zwar auch erst nach rund einer Minute. aber die Voltage und die consumption and temprature ist immernoch leer

**Comment by DaCHRIS** [comment]
Dann kann er die nicht - musst Du dann rausnehmen, damit die Datenpunkte verschwinden. 

Das hatte ich aber auch schon befürchtet, da in den herdsman-converters entsprechend weniger fromZigbee States definiert sind. 

Guckst Du: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js
