### ISSUE TITLE
Blacklist devices from acting as router/repeater

### ISSUE THREAD

**Issue by Coalado** [ioBroker/ioBroker.zigbee#549]
I have several bulbs that act as router/repeater when powered. However, these bulbs are switched on/off by a regular switch and are not on 24/7. 
The adapter now is constantly trying to ping and route over devices that are not available.

from time to time, these even leads to "lost devices" that cannot be controlled any more at all.

It would be great if we could tell the adapter which devices should be used as router.

is this possible, or is this request to "low level"?

**Comment by allofmex** [comment]
That's sadly not possible. The enddevices choose there routers by themselves. That's Zigbee design.
Coordinator has no control.
Devices select new parent router if previous is not available anymore.

Note: There is a bug in stack 1.2 that leads to defect routes in some cases. You may try non-source-routing firmware or stack 3 firmware

**Comment by Coalado** [comment]
I read about this here:
https://github.com/Koenkk/zigbee2mqtt/issues/1408
That seems to be exactly my problem - and yes, I use the source routing 1.2 Firmware on a CC2531.

My network is rather large (60+ devices)  I'm afraid of getting into performance issues without source routing.

**Comment by allofmex** [comment]
I'll try the TI patch, mentioned in issue 1408 as soon as possible. Would like to switch back to source routing too. (No problems with non-sr and 35 devices)

**Comment by Coalado** [comment]
Did you find precompiled binaries for the TI patch?

**Comment by allofmex** [comment]
No. We will have to build an own version.
