### ISSUE TITLE
New feature in network map possible?

### ISSUE THREAD

**Issue by cyclopz584** [ioBroker/ioBroker.zigbee#55]
Hello,

could you implement a map overview? It would be nice if we can upload a floor plan of the building in the "network map" and distribute the ZigBee components virtually.

UniFi from Ubiquiti supports such a possibility with their network components.

Here is an example.
http://cdn.makeuseof.com/wp-content/uploads/2018/01/UniFi-Controller-map.png

best regards
Torsten

**Comment by kirovilya** [comment]
I think it should not concern this driver.
Such map can be drawn and displayed in the Vis-driver and placed on it not only zigbee-devices, but also wired, wifi, z-wave.

**Comment by cyclopz584** [comment]
In VIS I can not draw a dynamic connection including intensity between the devices. (over which socket which enddevice works).
