### ISSUE TITLE
Blitzwolf BW-IS4

### ISSUE THREAD

**Issue by klakro** [ioBroker/ioBroker.zigbee#550]
Wird der Zigbee Temperatur- Feuchtesensor von Blitzwolf unterstützt?
Ich kann den Sensor in Zigbee einbinden, sehe aber keine Daten.

**Comment by DaCHRIS** [comment]
Der dürfte identisch bis sehr ähnlich zu den vorhandenen sein, bislang sind in der Liste allerdings nur "TuYa TS0201" und "iHorn LH-32ZB".

Wie sieht denn die Kachel des Sensors in den Geräten des Zigbee Adapters aus? Kannst Du die mal posten? 

Welches "Model" und "Vendor" sind da eingeblendet?

**Comment by klakro** [comment]
Ich bekomme im Zigbee-Adapter folgendes angezeigt
TS0201 ec1bbdfffedf6fde und als Bild ein Fragezeichen.
Unter Objekte 
0xec1bbdfffedf6fde Temperatur & Feuchte 
ec1bbdfffedf6fde  ? TS0202    device
Unter dem I ist nur Details, sonst nichts.
Leider kein Eintrag mit Temperatur oder Feuchte.
Hilft Dir das weiter?

**Comment by DaCHRIS** [comment]
Leider nicht. Wenn es wirklich das Model TS0201 ist, dann müsste es erkannt werden und dürfte kein Fragezeichen haben.

Von denen habe ich aktuell keinen hier zum Testen, habe aber welche bestellt.

**Comment by klakro** [comment]
Hi Chris,

schon ein model bekommen?
Ich könnte dir auch meines zum Testen schicken.
Gruß Klaus

**Comment by mistersms** [comment]
Hallo Chris,
konnte schon jemand diesen Temp-Sensor testen?
Ich würde mich auch für diesen Sensor interessieren und in den iobroker einbauen wollen.
Danke!
LG Richard
