### ISSUE TITLE
Ikea Fyrtur stop function

### ISSUE THREAD

**Issue by cschnack24** [ioBroker/ioBroker.zigbee#551]
Hello, 

I do own multiple Ikea Fyrtur e1753 and already added one.

Am i correct that the object stop should stop the blind and then it should hold its position?

Because with my e1753, the roller blind raises again when pressed.

I know that officially only the e1757 is supported, but i would like to know if this is due to the different versions of the roller blind or if it is a problem on my side.

Any idea?

Regards 
Carsten

**Comment by HansMaier** [comment]
Same behaviour here on Fyrtur e1757, so it's not on your side.

**Comment by xcashy** [comment]
I have the same issue. In addition the battery state has no value and there is no open or close Button. Only position and link_quality works.

**Comment by ewdob** [comment]
Hello all
are there any news on this issue? Actually I cannot optimize my Scripts due to the problem that there is no "stop" functionality. 
Thank you and br!

**Comment by HansMaier** [comment]
What do you try to accomplish? Maybe you can set the position to the current position?
