### ISSUE TITLE
Can not pairing the lumi.plug.mmeu01

### ISSUE THREAD

**Issue by Ceel84** [ioBroker/ioBroker.zigbee#556]
Zigbee version 1.0.3

add in file: "/opt/iobroker/node_modules/iobroker.zigbee/lib/devices.js"
> {
        vendor: 'Xiaomi',
        models: ['lumi.plug.mmeu01'],
        icon: 'img/lightify-plug.png',
        states: [states.state, states.load_power, states.plug_voltage, states.plug_consumption, states.plug_temperature],
    },

Pairing:
> ...
Pairing time left: 40
Pairing time left: 41
Pairing time left: 42
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Pairing time left: 43
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Pairing time left: 44
New device joined '0x04cf8cdf3c7771cf' model lumi.plug.mmeu01
Interview successful: {"friendly_name":"0x04cf8cdf3c7771cf","model":"ZNCZ04LM","vendor":"Xiaomi","description":"Mi power plug ZigBee EU","supported":true}
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Error: Device 04cf8cdf3c7771cf "lumi.plug.mmeu01" not described in statesMapping.. undefined
Pairing time left: 45
Device '0x04cf8cdf3c7771cf' announced itself
Interview started: 0x04cf8cdf3c7771cf

Details:
> model:ZNCZ04LM
vendor:Xiaomi
description:Mi power plug ZigBee EU
supports:on/off, power measurement
model:lumi.plug.mmeu01
type:Router
ieee:0x04cf8cdf3c7771cf
nwk:4892
manuf id:4447
manufacturer:LUMI
power:Mains (single phase)
app version:22
hard version:1
zcl version:3
stack version:2
date code:09-06-2019
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:0,2,3,4,5,6,9,1794,2820
output clusters:10,25
endpoint:242
profile:41440
input clusters:
output clusters:33

Screenshots:
[https://ibb.co/w656btr](url)
[https://ibb.co/LRnz6CW](url)

**Comment by DaCHRIS** [comment]
Sieh bitte nochmal in beide Dateien.

Erstmal in die Datei /opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js um zu prüfen dass der Plug grundsätzlich in den converters vorhanden ist. 

Danach dann nochmal in die Datei /opt/iobroker/node_modules/iobroker.zigbee/lib/devices.js ob Deine manuellen Änderungen noch drin sind, oder ob die Datei wieder überschrieben wurde - ist mir auch schon mal passiert dass die Datei unmittelbar nach meinen Änderungen überschrieben wurde und ich überall wie ein Blöder gesucht habe. 

Die States für Voltage, Consumption und Temperature sollen wohl nicht laufen beim EU Adapter, siehe https://github.com/ioBroker/ioBroker.zigbee/issues/545#issuecomment-593091185 

Die müsstest Du wenn Du das nochmal geprüft hast vor dem pull request dann wieder rausnehmen, um keine toten Datenpunkte zu erzeugen.

**Comment by Ceel84** [comment]
damit geht es:

>{
vendor: 'Xiaomi',
models: ['lumi.plug.mmeu01'],
icon: 'img/lightify-plug.png',
states: [states.state, states.load_power],
},
