### ISSUE TITLE
Please implement device firmware update

### ISSUE THREAD

**Issue by Schimi1983** [ioBroker/ioBroker.zigbee#557]
HI,

it would be great if we can upgrade the device firmware....

**Comment by allofmex** [comment]
@kirovilya @arteck @asgothian: Anyone working on this already?
(I may start myself, but don't want to do it double)

**Comment by kirovilya** [comment]
I do not work. I have only one IKEA light for checking :)

**Comment by Schimi1983** [comment]
if you need testers....

I have 2 Osram SmartPlug and 2 Ikea TRÅDFRI GU10 400 lm

Win10 x64 Hyper-V VM with iobroker

**Comment by arteck** [comment]
@allofmex nope i not and asgothian also not

**Comment by Alex-Ga** [comment]
I have some IKEA Stuff for testing here.
- E27 1000lm white (old firmware, does not work on echo plus, but this Adapter)
- E27 white spectrum
- E27 retro bulb
- GU10 white
- new dimmer (cross)
- old dimmer (wheel)
- SYMFONISK remote

**Comment by allofmex** [comment]
I'm working on it...

**Comment by allofmex** [comment]
Done
see https://github.com/ioBroker/ioBroker.zigbee/pull/562

**Comment by Schimi1983** [comment]
work!!

I updated 1 Osram SmartPlug (the other have no newer Firmware) and 2 Ikea TRÅDFRI GU10 400 lm

Great Work!!! :-)
