### ISSUE TITLE
Error Log from Adapter

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#56]
Sorry .. I don't speak Zigbee:

https://pastebin.com/4NFXtsjP

And now and then if I go into configuration I get the message that I need to configure and save the adapter first before I pair something. But something is already paired.
But generally all seems to work .. just thought it might be helpful to let you devs know.

`host.raspi  2018-09-23 08:09:50.018 info    instance system.adapter.zigbee.0 terminated with code 0 (OK)
Caught  2018-09-23 08:09:50.016 error   by controller[7]: Sun, 23 Sep 2018 06:09:49 GMT cc-znp:SREQ --> ZDO:mgmtPermitJoinReq, { addrmode: 15, dstaddr: 65532, duration: 0, tcsignificance: 0 }
Caught  2018-09-23 08:09:50.016 error   by controller[6]: Sun, 23 Sep 2018 06:09:49 GMT zigbee-shepherd:request REQ --> ZDO:mgmtPermitJoinReq
Caught  2018-09-23 08:09:50.016 error   by controller[5]: status: 'online' } ]
Caught  2018-09-23 08:09:50.016 error   by controller[5]: parent: '0x00124b0014d9de74',
Caught  2018-09-23 08:09:50.015 error   by controller[5]: deviceType: 2,
Caught  2018-09-23 08:09:50.015 error   by controller[5]: depth: 1,
Caught  2018-09-23 08:09:50.015 error   by controller[5]: lqi: 12,
Caught  2018-09-23 08:09:50.015 error   by controller[5]: nwkAddr: 2909,
Caught  2018-09-23 08:09:50.015 error   by controller[5]: Sun, 23 Sep 2018 06:09:23 GMT zigbee:controller debug lqiScan result: [ { ieeeAddr: '0x00158d000278e743',
Caught  2018-09-23 08:09:50.015 error   by controller[4]: Sun, 23 Sep 2018 06:09:23 GMT zigbee-shepherd:msgHdlr IND <-- ZDO:mgmtLqiRsp
Caught  2018-09-23 08:09:50.015 error   by controller[3]: Sun, 23 Sep 2018 06:09:23 GMT cc-znp:AREQ <-- ZDO:mgmtLqiRsp, { srcaddr: 0, status: 0, neighbortableentries: 1, startindex: 0, neighborlqilistcount: 1, neighborlqilist: [ { extPandI
Caught  2018-09-23 08:09:50.014 error   by controller[2]: Sun, 23 Sep 2018 06:09:23 GMT cc-znp:SRSP <-- ZDO:mgmtLqiReq, { status: 0 }
Caught  2018-09-23 08:09:50.014 error   by controller[1]: Sun, 23 Sep 2018 06:09:23 GMT cc-znp:SREQ --> ZDO:mgmtLqiReq, { dstaddr: 0, scanchannels: undefined, scanduration: undefined, startindex: 0 }
Caught  2018-09-23 08:09:50.014 error   by controller[1]: Sun, 23 Sep 2018 06:09:23 GMT zigbee-shepherd:request REQ --> ZDO:mgmtLqiReq
host.raspi  2018-09-23 08:09:49.935 info    stopInstance system.adapter.zigbee.0 killing pid 14553`

**Comment by arteck** [comment]
` error by controller[7]: ` its iobroker problem which version from js-conrtoller you have ??

**Comment by daniel-lo** [comment]
Node.js: v8.12.0
NPM: 4.6.1

**Comment by arteck** [comment]
mom.. the error is after stopped the adapter right ??

**Comment by daniel-lo** [comment]
between the stop and the confirmation

**Comment by daniel-lo** [comment]
(0x00158d000278e743): MFKZQ01LM - Xiaomi Mi smart home cube (EndDevice)

is that also okay .. or laready an indication of a range prob?

**Comment by arteck** [comment]
plz close here
