### ISSUE TITLE
CR2531 limit of 40 Devices?

### ISSUE THREAD

**Issue by Gwoony** [ioBroker/ioBroker.zigbee#561]
Hello Community,

I connected 42 devices to my CR2531. The 41 and 42 devices immediately lost the connection again after a few seconds.

Is there a device limit here or is it a coincidence that this is the case for devices over 40?

Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}

Thank you all

**Comment by Sacred-Shadow** [comment]
Der Hintergrund:
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator
