### ISSUE TITLE
Geräte Verbindungen Link Qualität

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.zigbee#563]
Hallo
installiert ist Zigbee 1.0.4

- Die angezeigte Signalstärke in der Netzwerkkarte stimmt nicht mit der Geräteansicht/Objekt
  überein und wird auch bei ausgeschaltetem Gerät nicht aktualisiert. Nicht erreichbare Geräte 
   können nicht erkannt werden.

- Gerät kann nur gelöscht werden, wenn es noch erreichbar ist.

- Ich habe als Router zwei CC2531 und eine Osram Smart+ Steckdose. Diese werden zwar in der
  Netzwerkkarte angezeigt, ich habe  aber noch keine Reichweiten Verbesserung festgestellt. Dabei
  habe ich alle denkbaren Strecken Hub-Router-div. Geräte  versucht und oft mehrere Stunden
  abgewartet.
  Die Osram Smart+ Steckdose ist noch nie in der Netzwerkkarte mit einem Gerät als Router
  verbunden gewesen. Ein/Aus schalten funktioniert, aber die Router Funktion ist nicht erkennbar.

- Wenn ein Gerät über einen Router die Verbindung verliert, dann erfolgt kein reconnect.

**Comment by Schimi1983** [comment]
HI,

die ersten zwei punkte sind mir auch aufgefallen....
Bei mir werden die zwei Osram Plugs als Router benutzt...

**Comment by Sacred-Shadow** [comment]
Also Punkt 2 kann ich nicht bestätigen, man bekommt ja auch die Hinweismeldung und kann die Löschung erzwingen. Punkt 1 hatte ich auch schon, lässt man die Karte einige Zeit offen, stimmt es dann doch ganz gut mit den Werten der Geräteansicht überein.

**Comment by Hans-Zwiesel** [comment]
> 
> 
> Also Punkt 2 kann ich nicht bestätigen, man bekommt ja auch die Hinweismeldung und kann die Löschung erzwingen. Punkt 1 hatte ich auch schon, lässt man die Karte einige Zeit offen, stimmt es dann doch ganz gut mit den Werten der Geräteansicht überein.

Die CheckBox Löschen erzwingen bewirkt rein gar nichts.

**Comment by allofmex** [comment]
> Signalstärke in der Netzwerkkarte stimmt nicht

Korrigiert mich wenn ich falsch liege:

- Die Netzwerkkarte fragt die Signalstärken von allen **Routern** direkt ab, der Wert wird nur in der Karte angezeigt, aber in diesem Fall **nicht in der Objektansicht aktualisiert**.

- Die Signalstärke in Objektansicht wird **nur** aktualisiert, wenn vom Gerät eine reguläre Nachricht kommt und ist die Qualität des von diesem Gerät zuletzt **empfangen** Packets.

Zusammengefasst: 

1. Objektansicht und Karte zeigen immer Werte von **unterschiedlichen Zeitpunkten** an, werden also selten komplett übereinstimmen.
2. Linkqualität in Objektansicht bei einem **Endgerät** ist die **Empfangsqualität am Endgerät**, Linkqualität in Karte an Linie zum Endgerät ist **Empfangsqualität am Router**!

> noch nie in der Netzwerkkarte mit einem Gerät als Router
verbunden gewesen

Ist Entscheidung vom Endgerät, wenn ihm die Link-Qualität direkt zum Coordinator ausreicht, dann wäre das der kürzeste (zu bevorzugende) Weg. Kein Bedarf einen Router dazwischenzuschalten..

> kein reconnect.

Sollte eigentlich nicht passieren. Von was für einem Gerät sprichst du?

**Comment by Hans-Zwiesel** [comment]
Vielen Dank für die Erläuterung der Signalstärke, da erklärt sich vieles.
Das Gerät war der Aquarius Bewegungsmelder lumi.sensor_motion.aq2
