### ISSUE TITLE
Can not pairing the FNB56-ZSW02LX2.0

### ISSUE THREAD

**Issue by Ceel84** [ioBroker/ioBroker.zigbee#565]
Zigbee version 1.0.4

I can not pair the FNB56-ZSW02LX2.0
please help me

Screenshot:
[https://ibb.co/3StHq7c](url)

Details:

model:HGZB-42
vendor:Nue / 3A
description:Smart light switch - 2 gang v2.0
supports:on/off
model:FNB56-ZSW02LX2.0
type:Router
nwk:53973
manuf id:4478
manufacturer:FeiBit
power:Mains (single phase)
app version:1
hard version:1
zcl version:2
stack version:1
date code:201808.08
build:1000-0001
interviewed:true
configured:true
endpoint:11
profile:49246
input clusters:genBasic (0)
genGroups (4)
genIdentify (3)
genOnOff (6)
genScenes (5)
touchlink (4096)
genLevelCtrl (8)
output clusters:genOta (25)
endpoint:12
profile:49246
input clusters:genBasic (0)
genGroups (4)
genIdentify (3)
genOnOff (6)
genScenes (5)
genLevelCtrl (8)
output clusters:genOta (25)

**Comment by Ceel84** [comment]
i have test:

`    {
        vendor: 'Nue / 3A',
        models: ['FNB56-ZSW02LX2.0'],
        icon: 'img/tuya_switch_2.png',
        states: [states.left_state, states.right_state],
    },
`

**Comment by Ceel84** [comment]
Could someone add the switch please?

**Comment by kirovilya** [comment]
For this device you must create _top_ and _bottom_ states. https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L3798
For example add block in states.js:
```
state_top: {
        id: 'state_top',
        prop: 'state_top',
        name: 'Top switch state',
        icon: undefined,
        role: 'switch',
        write: true,
        read: true,
        type: 'boolean',
        getter: (payload) => (payload.state_top === 'ON'),
        setter: (value) => (value) ? 'ON' : 'OFF',
        setattr: 'state',
        epname: 'top',
    },
```
and then add to devices.js:
```
{
    vendor: 'Nue / 3A',
    models: ['FNB56-ZSW02LX2.0'],
    icon: 'img/tuya_switch_2.png',
    states: [states.state_top],
},
```

**Comment by Ceel84** [comment]
Oh thx, but i didn't understand ist

Is this right?

`state_top: {
        id: 'state_top',
        prop: 'state_top',
        name: 'Top switch state',
        icon: undefined,
        role: 'switch',
        write: true,
        read: true,
        type: 'boolean',
        getter: (payload) => (payload.state_top === 'ON'),
        setter: (value) => (value) ? 'ON' : 'OFF',
        setattr: 'state',
        epname: 'top',
    },

state_bottom: {
        id: 'state_bottom',
        prop: 'state_bottom',
        name: 'Top switch state',
        icon: undefined,
        role: 'switch',
        write: true,
        read: true,
        type: 'boolean',
        getter: (payload) => (payload.state_bottom === 'ON'),
        setter: (value) => (value) ? 'ON' : 'OFF',
        setattr: 'state',
        epname: 'bottom',
    },

and to devices.js:

{
    vendor: 'Nue / 3A',
    models: ['FNB56-ZSW02LX2.0'],
    icon: 'img/tuya_switch_2.png',
    states: [states.state_top, states.state_bottom],
},

**Comment by kirovilya** [comment]
yes

**Comment by Ceel84** [comment]
i have added the lines but than the adapter crash (doesn't work)
could you add the switch to the Adapter?

**Comment by Ceel84** [comment]
devices.js

>    {
         vendor: 'Nue / 3A',
         models: ['FNB56-ZSW02LX2.0'],
         icon: 'img/tuya_switch_2.png',
         states: [states.top_state, states.bottom_state],
    },

states.js

>top_state: {
           id: 'top_state',
           prop: 'state_top',
           name: 'Top switch state',
           icon: undefined,
           role: 'switch',
           write: true,
           read: true,
           type: 'boolean',
           getter: payload => (payload.state_top === 'ON'),
           setter: (value) => (value) ? 'ON' : 'OFF',
           setattr: 'state',
           epname: 'top',
    },
        bottom_state: {
           id: 'bottom_state',
           prop: 'state_bottom',
           name: 'Bottom switch state',
           icon: undefined,
           role: 'switch',
           write: true,
           read: true,
           type: 'boolean',
           getter: payload => (payload.state_bottom === 'ON'),
           setter: (value) => (value) ? 'ON' : 'OFF',
           setattr: 'state',
           epname: 'bottom',
    },

**Comment by Ceel84** [comment]
Version 1.1.1 doesn't work
