### ISSUE TITLE
Zigbee not connected (yellow)

### ISSUE THREAD

**Issue by valentin38315** [ioBroker/ioBroker.zigbee#566]
Hello,

My raspberry pi restarts every night and for some reason once every week my zigbee status is not connected (yellow). Then I have to replug the stick and it works again for around 1 week. 
@ @
![log](https://user-images.githubusercontent.com/47112999/77220820-2de2ae00-6b44-11ea-80b9-cacd885fdd62.png)

Thanks in advance :)

**Comment by thomasBrecho** [comment]
same issue here, zigbee stopped suddenly working. Same error. Started zigbee in Proxmox environment, in lxc container, cc2531 stick was working without any issue before...

**Comment by elzershark** [comment]
same issue here

**Comment by thomasBrecho** [comment]
Try shutdown the computer. Not only reboot. After a complete my ZigBee
Instance come up green...

Elzershark <notifications@github.com> schrieb am Fr., 27. März 2020, 17:21:

**Comment by cola32** [comment]
Same problem here 
Shut down the computer doesn’t work

**Comment by cola32** [comment]
the backups of the last few days don't work either and a downgrade of the Zigbee adapter to 1.0 doesn't work either

**Comment by elzershark** [comment]
Wrong Firmware

**Comment by cola32** [comment]
Which Firmware can i use ?
It worked for 4 weeks

**Comment by elzershark** [comment]
https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html
