### ISSUE TITLE
Osram Gardenspot W connected but no state/brightness changes

### ISSUE THREAD

**Issue by chr-jordan** [ioBroker/ioBroker.zigbee#567]
The device appears with connection. Changing values like brightness and state have no effect. Tried many pairing processes.
![Bildschirmfoto_2020-03-22_07-59-16](https://user-images.githubusercontent.com/44375264/77244338-1e329a80-6c14-11ea-999b-12506e6583e4.png)
![Bildschirmfoto_2020-03-22_07-59-55](https://user-images.githubusercontent.com/44375264/77244332-0bb86100-6c14-11ea-81ce-e510a4488e8d.png)
![Bildschirmfoto_2020-03-22_07-38-26](https://user-images.githubusercontent.com/44375264/77244333-0d822480-6c14-11ea-9311-02093dfeb905.png)

**Comment by arteck** [comment]
error log ??
