### ISSUE TITLE
Router Geräte reconnect

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.zigbee#568]
Hallo liebe Entwickler
jetzt ist es ja so, dass wenn sich die Router-Situation ändert, die Geräte permanent an der einmal
gefundenen Router kleben bleiben.
Abhilfe: Geräte neu pairen.

Das ist besonders umständlich und ärgerlich, wenn man die besten Verbindungswege sucht
indem man Router ändert bzw. neu positioniert.

Meine Bitte: ein automatisches re-Routing oder wenigstens ein manuelles im Adapter,
damit würde es wesentlich einfacher und sicherer!!!

**Comment by allofmex** [comment]
> Geräte permanent an der einmal gefundenen Router kleben bleiben.

Wie bereits an anderen Stellen mehrfach erklärt: Zigbee Geräte suchen sich ihre Router selbst und können auch jederzeit selbstständig auf einen anderen Router wechseln. Wenn ein Router wegfällt, erkennen das die Endgeräte (nach einiger Zeit!!) selbst und suchen sich einen neuen Router. Das ist im Zigbee Standard so festgelegt. Der Coordinator/Adapter hat keinerlei Möglichkeiten das zu beeinflussen!

In folgenden Situationen könnte es vorkommen, das Endgerät keinen neuen Router finden:

- Fehler in Endgeräte Firmware (unwahrscheinlich, ist ja eine Grundfunktion von Zigbee)
- zu wenig Router in Reichweite (Router können nur eine bestimmte Anzahl verbundene Endgeräte zur gleichen Zeit haben)
- Fehler in Router Firmware (https://github.com/Koenkk/zigbee2mqtt/issues/1474)
