### ISSUE TITLE
Please extend OSRAM panels to the model TW Z3

### ISSUE THREAD

**Issue by krumbholz** [ioBroker/ioBroker.zigbee#581]
Hi,
I've got the osram/ledvance panel "Panel TW Z3" that behaves the very same as "Panel TW 595 UGR22". I just added it locally to the UGR22 declaration having it working fine:

node_modules/zigbee-herdsman-converters/devices.js
![converter devices js](https://user-images.githubusercontent.com/63000306/78142194-e2c27800-742c-11ea-8faa-63138b4e8817.png)

node_modules/iobroker.zigbee/lib/devices.js
![lib devices js](https://user-images.githubusercontent.com/63000306/78142202-e655ff00-742c-11ea-8e10-9376878f9670.png)

Best regards,
Steffen

**Comment by Sacred-Shadow** [comment]
Funktioniert wirklich alles? 
Also alle Funktionen die das Gerät haben müsste?

**Comment by krumbholz** [comment]
Jop, hat so alles funktioniert (An, Aus, Dimmen 10-100%, Weißwert, Transition time). Bis gestern das Netzteil abgeraucht ist :-(

VG, Steffen

**Comment by krumbholz** [comment]
Ich konnte das Netzteil reparieren, wäre also auch für Tests verfügbar.
VG, Steffen

**Comment by Sacred-Shadow** [comment]
Okay, also vorgearbeitet habt ihr ja schon.
Also damit alle was davon haben und es sauber wird, sollte erstmal das Gerät bei Koenkk in den Converter rein:
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Hier wird ja immer die aktuelle Version vom Conveter genutzt, bringt uns also weniger, wenn es nur hier ist. 
Ist das Teil dort auf der Liste schieben wir hier die Anpassung der Devies nach.

Dadurch können dann sowohl die Leute auf der "Koenkk Welt" als auch die Leute hier auf der "ioBroker Zigbee Welt" das Gerät sauber nutzen. 

Kannst du das in Richtung Koenkk übernehmen?
