### ISSUE TITLE
Add device Philips Hue Gu10 LWG004 - 9290019535 please

### ISSUE THREAD

**Issue by xxxTODxxx** [ioBroker/ioBroker.zigbee#582]
Can you please add the Philips Hue GU10 device.
Model: LWG004 or 9290019535

    model:LWG004
    vendor:Philips
    description:Hue white GU10 bluetooth
    supports:on/off, brightness, power-on behavior

    model:LWG004
    type:Router
    manufacturer:Philips
    power:Mains (single phase)
    app version:2
    hard version:1
    zcl version:2
    stack version:1
    date code:20200124
    build:1.65.9_hB3217DF4
    interviewed:true
    configured:false

    endpoint:11
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    touchlink (4096)
    64514
    output clusters:genOta (25)

    endpoint:242
    profile:41440

The device is also in the zigbee2mqtt list:
https://www.zigbee2mqtt.io/devices/LWG004.html

**Comment by kirovilya** [comment]
Added. You can try update from github

**Comment by xxxTODxxx** [comment]
Thanks, it works fine.
