### ISSUE TITLE
Please add LLKZMK11LM - Interlock mode from zigbee2mqtt

### ISSUE THREAD

**Issue by igraf767** [ioBroker/ioBroker.zigbee#585]
Can you please make Interlock ON/OFF available in the Analysis Tab.

Add interlock mode for Aqara relay (LLKZML11LM)
#544 Aqara relay LLKZMK11LM - Interlock mode

from https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.8.0

**Comment by juamiso** [comment]
Yes please, or tell us how to do so :)

**Comment by juamiso** [comment]
any chance to get this working? I need to re-pair again this device and is a pain to disconnect the wires to avoid frying the shutter motor ( pressing the pairing button closes both relays, with produces a short-cut in the shutter motor if no interlock is defined)

**Comment by Vodochnik** [comment]
Up)
