### ISSUE TITLE
please add Paulmann LED Panel from zigbee2mqtt

### ISSUE THREAD

**Issue by Mimamau** [ioBroker/ioBroker.zigbee#586]
I can pair it and switch it on and off in developer tab.
It doesn't create an object for now.

https://www.zigbee2mqtt.io/devices/798.09.html

**Comment by Sacred-Shadow** [comment]
Do you dare to change a file in your installation?
We can test it to see if it works.

Add that to the file:
/opt/iobroker/node_modules/iobroker.zigbee/lib/devices.js
```
    {
        vendor: 'Paulmann',
        models: ['798.09'],
        icon: 'img/paulmann_rgbw_controller.png',
        states: lightStates,
        syncStates: [sync.brightness],
    },
```

Then restart the adapter and teach the device.
If it can be taught, please test whether **all** functions work.

So here:
on/off, brightness, color temperature, color xy

Please just give us a quick feedback if it works.

**Comment by Sacred-Shadow** [comment]
@Mimamau 
Have you already tested it?

**Comment by Mimamau** [comment]
Sorry for the delay.

It works, but I can't see a value for color xy, it should be possible to change the RGB color.
On/off, brightness, and color temperature works.

Thanks

**Comment by Sacred-Shadow** [comment]
Did you cleanly remove and re-teach the device after the changes?
What values ​​do you see?

**Comment by Mimamau** [comment]
I just removed and re-paired it. 
I see available, brightness, colortemp, groups, link_quality, state and transition_time.
It also doesn't show up with its name, only as 371000002.
On the device information it says: "supports: on/off, brightness, color temperature, color xy".

**Comment by Mimamau** [comment]
Now I got it!

    {
        vendor: 'Paulmann',
        models: ['371000002'],
        icon: 'img/paulmann_rgbw_controller.png',
        states: lightStatesWithColor,
        syncStates: [sync.brightness],
    },

**Comment by Sacred-Shadow** [comment]
@Mimamau 
Can you show me the device info?
I am surprised because the other Paulmann devices really show the model number.
