### ISSUE TITLE
Outdoor Lantern W RGBW OSRAM --> kein ColorXY

### ISSUE THREAD

**Issue by PFranitza** [ioBroker/ioBroker.zigbee#587]
Hallo zusammen,

leider zeigt der iOBroker bei der Osram Outdoor Lantern W RGBW keinen Wert für ColorXY an.

Anschalten und das verstellen der weißen Farbtemperatur funktioniert.

Gibt es hier einen Trick wie ich die Farben der Lampe Steuern kann?

**Comment by Sacred-Shadow** [comment]
Traust du dir zu, eine File zu bearbeiten? :)

Ich hab nen Unterschied entdeckt .. habe die Osram Classic A60 RGBW.
Die werden mit diesem Code angesteuert:
`    {
        vendor: 'OSRAM',
        models: ['Classic A60 RGBW', 'CLA60 RGBW OSRAM', 'CLA60 RGBW Z3'],
        icon: 'img/osram_a60_rgbw.png',
        states: lightStatesWithColor,
        syncStates: [sync.brightness],
    },`

Die Osram Outdoor Lantern W RGBW müsste doch auch nur die gleichen Funktionen haben?
Also AN/Aus, Farbe, Farbtemperatur, Helligkeit.

Für deine Latern gilt dieser Code:
`    {
        vendor: 'OSRAM',
        models: ['Outdoor Lantern W RGBW OSRAM'],
        icon: 'img/osram_4058075816718.png',
        states: lightStatesWithColortemp,
        syncStates: [sync.brightness],
    },

Kannst es ja mal testen:
/opt/iobroker/node_modules/iobroker.zigbee/lib/devices.js 

Dort einfach mal bei deiner Latern das lightStatesWithColortemp gegen lightStatesWithColor tauschen und den Adapter neustarten. Nach ein paar Minuten müssten die Werte für die Farbe auftauchen und sich ändern lassen.

Wenn ich das richtig gesehen habe, wird lightStatesWithColortemp nur für Osram Lampen genutzt die nur Weiß können.

**Comment by PFranitza** [comment]
Super, danke. Probiere ich später mal aus.

**Comment by Sacred-Shadow** [comment]
Meldest dich dann zurück?
Wenns funktioniert, können wir das ja gleich Dingfest für alle machen. ;)

**Comment by PFranitza** [comment]
Moin, die Änderung der devices.js hat es gebracht. Vielen Dank für die Hilfe und schöne Ostern

**Comment by Sacred-Shadow** [comment]
@kirovilya can you close the issue?
