### ISSUE TITLE
Several issues with the Zigbee adapter

### ISSUE THREAD

**Issue by Maschler** [ioBroker/ioBroker.zigbee#588]
Hello,
i'm having some problems with the zigbee adapter recently. I have the same issue on raspberry pi 4 even with all latest adapters, node.js, controller, etc.. I will list them below:

**1. problem**

The 0x14b457fffec4e9df (511.202 - Iluminize Zigbee 3.0 switching actuator mini 1x230V, 200W/400W (Router)) is permanently on power. However, this error message appears constantly.

`2020-04-11 08:30:37.868  - _[31merror_[39m: zigbee.0 (17811) Error on send command to 0x14b457fffec4e9df. Error: Error: Command 0x14b457fffec4e9df/1 genOnOff.off({}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error: Data request failed with error: 'No network route' (205))
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:339:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
`

The same applies to 0x000b57fffebef848 (IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router))

`2020-04-11 08:45:31.491  - _[31merror_[39m: zigbee.0 (15254) Error on send command to 0x000b57fffebef848. Error: Error: Command 0x000b57fffebef848/1 genOnOff.off({}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error: Data request failed with error: 'No network route' (205))
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:339:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
`

**2. problem**
The motion detector (0x0017880102036c78=model:SML001) is known and worked properly. But sometimes it works (it is configured successfully, but all other three motion sensors are not reconfigured each time). But after restarting the zigbee module this message appears (always):

`
zigbee.0 (15254) Configuring 0x0017880102036c78 SML001
zigbee.0 (15254) Failed to configure 0x0017880102036c78 SML001, attempt 5 (Error: Bind 0x0017880102036c78/2 genPowerCfg from '0x00124b0018e24929/1' failed (Error: AREQ - ZDO - bindRsp after 10000ms)
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:235:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
`
What cann i do to fix it?

**Comment by gogo-111** [comment]
Hi 

I have basically the same Problem (Error: Error: Command ... genOnOff.off({}, {"timeout":....)  with a Xiaomi power plug. First, I thought it is the distance between sender and receiver. But even with closer distance it was not improved. Any suggestion what could be the problem?

`zigbee.0	2020-04-17 21:53:56.781	error	at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
zigbee.0	2020-04-17 21:53:56.781	error	at Generator.throw (<anonymous>)
zigbee.0	2020-04-17 21:53:56.781	error	at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:339:23)
zigbee.0	2020-04-17 21:53:56.781	error	(4202) Error on send command to 0x00158d0002799b95. Error: Error: Command 0x00158d0002799b95/1 genOnOff.off({}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error:
`
