### ISSUE TITLE
Philips Hue RWL021 dimmer switch - state change on down/up button

### ISSUE THREAD

**Issue by PiXBalance** [ioBroker/ioBroker.zigbee#593]
Hello,

the RWL021 dimmer switch has a two buttons for on and off and two for dimming. If the state is false and I press the button for dimming lighter, the state does not switch to true nor can I set it to true manually. If I activate writing for the state it's set backt to not writable after the next change.
is it possible to make state writable permanently?

Regards,
Tobias

**Comment by allofmex** [comment]
State is the status of O/I buttons on remote. If you press I, it should switch to true, if you press O it should go false.
No need to make the object writeable.
