### ISSUE TITLE
HEIMAN Sirene supported but not work

### ISSUE THREAD

**Issue by Communicator7** [ioBroker/ioBroker.zigbee#594]
Hi,

i am trying to use the HEIMAN warniung device via Zigbee. The Device was interviewed correctly an shown in the ZigBee adapter device overview (vendor missing). If i go to the details, all informatin are there.
The main problem is, only one entry in the objects are available for a short while. No objects that are usually created are there.
So sirene is not working but from the compatibility website, this has to be compatibel.
Are there any dependencies, that i have to know?

Device details:
```
    model:HS2WD-E
    vendor:HEIMAN
    description:Smart siren
    supports:warning

    model:WarningDevice
    type:Router
    nwk:43852
    manuf id:4619
    manufacturer:Heiman
    app version:18
    hard version:16
    zcl version:1
    stack version:2
    date code:2018.03.21
    interviewed:true
    configured:true

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genPowerCfg (1)
    genIdentify (3)
    genGroups (4)
    genAlarms (9)
    ssIasZone (1280)
    ssIasWd (1282)
    output clusters:genIdentify (3)
    genOta (25)
```

My System:
=======

Raspberry PI 3 with 1GB RAM ( ~250 MB free), updatet today
Node.js: 10.20.0
NPM 6.14.4
ZigBee Adapter: 1.0.4
HDD: 4GB free
CC2531 Zigbee Stick
No other issues at all

**Comment by Sacred-Shadow** [comment]
**Changelog:** 
1.1.0 (2020-04-12)
[...]
(palsch) Heiman HS2WD-E siren


You have the wrong version (1.0.4).

**Comment by Communicator7** [comment]
omg, thx. Dont see it.
