### ISSUE TITLE
Firmware Update Check for Osram Devices failed

### ISSUE THREAD

**Issue by mikepiko** [ioBroker/ioBroker.zigbee#598]
Since it´s a new Feature ...

It´s getting me an Error if i hit the "Check Firmware" Button:

`Failed to check if update available for '0x7cb03eaa00a717dd' (logger.warn is not a function)`

Do i need to put the Firmware files somewhere ? Or is it checked against the Osram server ? 
Or does it not work at all currently ?

**Comment by allofmex** [comment]
Is there more details on the logs, or is this the whole error?

**Comment by mikepiko** [comment]
Thats all :

`

zigbee.0 | 2020-04-17 13:02:20.680 | error | (30523) Failed to check if update available for '0x84182600000ea4f1' (logger.warn is not a function)
-- | -- | -- | --
zigbee.0 | 2020-04-17 13:02:13.587 | error | (30523) Failed to check if update available for '0x7cb03eaa00a717dd' (logger.warn is not a function)
zigbee.0 | 2020-04-17 13:01:52.513 | info | (30523) Zigbee started
zigbee.0 | 2020-04-17 13:01:52.512 | info | (30523) 0x00158d000304226a (addr 46904): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-04-17 13:01:52.511 | info | (30523) 0x00158d0002f2a249 (addr 3931): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2020-04-17 13:01:52.511 | info | (30523) 0x00158d0002248feb (addr 34521): RTCGQ01LM - Xiaomi MiJia human body movement sensor (EndDevice)
zigbee.0 | 2020-04-17 13:01:52.510 | info | (30523) 0x00158d000224997c (addr 14734): RTCGQ01LM - Xiaomi MiJia human body movement sensor (EndDevice)
zigbee.0 | 2020-04-17 13:01:52.509 | info | (30523) 0x7cb03eaa00a717dd (addr 33208): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2020-04-17 13:01:52.508 | info | (30523) 0x84182600000ea4f1 (addr 25442): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0 | 2020-04-17 13:01:52.503 | info | (30523) Currently 6 devices are joined:
zigbee.0 | 2020-04-17 13:01:52.493 | info | (30523) --> transmitPower : normal
zigbee.0 | 2020-04-17 13:01:52.483 | info | (30523) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190109}}
zigbee.0 | 2020-04-17 13:01:51.020 | info | (30523) Starting Zigbee...
zigbee.0 | 2020-04-17 13:01:50.999 | info | (30523) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.16.3
zigbee.0 | 2020-04-17 13:01:46.953 | info | (21061) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
zigbee.0 | 2020-04-17 13:01:46.952 | info | (21061) terminating
zigbee.0 | 2020-04-17 13:01:46.637 | info | (21061) Zigbee: disabling joining new devices.
zigbee.0 | 2020-04-17 13:01:46.636 | info | (21061) cleaned everything up...
zigbee.0 | 2020-04-17 13:01:46.635 | info | (21061) Got terminate signal TERMINATE_YOURSELF

`

**Comment by mikepiko** [comment]
Can provide some new Information .
Problem exists only with the Osram Plug 01.
Just added a Classic A60 RGBW where the Firmware could be checked successfully.

**Comment by mikepiko** [comment]
Next Update ... Paired a newly bought Plug 01 and there i can check and even upgrade the Firmware.(just running in the Background) 
Will try unpairing the old ones and pairing them again to see if it makes a difference.
(after the other Update is completed)

**Comment by mikepiko** [comment]
Okay unpairing and new pairing does not make any difference. 

But any Plug (even the one i added and upgraded) now throws out the Error. Only Lamps say that the Firmware is latest.

**Comment by allofmex** [comment]
Found the error. Fixed with https://github.com/ioBroker/ioBroker.zigbee/commit/39f51173e955d78c0e047d18a2171a8107ea339a
Should be included in next release. (Or update to latest github version)
