### ISSUE TITLE
after reflash reconnect to all devices

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#6]
Is it possible a reconnect to all pairing devices ??

**Comment by kirovilya** [comment]
I think - yes.
Pairing keys stored in shepherd.db and use on adapter start. So you also can change zigbee-stick and it may work.

**Comment by arteck** [comment]
How can I reset the stick?

**Comment by kirovilya** [comment]
:) no-no... it is a visual bug with different heights of card (with rooms and without it).

**Comment by arteck** [comment]
hmm ok...

**Comment by arteck** [comment]
Oh, now I understand it... all devises are in shepherd.db..

**Comment by kirovilya** [comment]
You can try reflash and then start adapter with old shepherd.db.
Or you can delete shepherd.db and reconnect devices again.
This issue is still actual https://github.com/Koenkk/zigbee2mqtt/issues/172 ?

**Comment by arteck** [comment]
it works
