### ISSUE TITLE
Support for Philips Hue Attract

### ISSUE THREAD

**Issue by ppent** [ioBroker/ioBroker.zigbee#603]
Hi,
I already raised an issue at the zigbee2mqtt project to have Philips Hue Attract added to the suppported device list. This was done:
https://github.com/Koenkk/zigbee2mqtt/issues/3316

Could you add support within the iobroker adapter as well, please? Currently, I manually edited the devices.js and added the following:
{
vendor: 'Philips',
models: ['1746130P7'],
icon: 'img/philips_hue_1746130P7.png',
states: lightStatesWithColor,
syncStates: [sync.brightness],
}

This seems to work, the only issue I have is that the "available" state updates with high delay. Not sure if this is normal and I may raise a separate issue.

Thank you!

**Comment by Sacred-Shadow** [comment]
Can you upload the png? 
Does everything work with this code that should work with the lamp?

**Comment by ppent** [comment]
Yes, the lamp works as expected. I can turn on/off, set color & color temp, brightness, transition time.
The only issues I have:
1. when I turn on/off the light via wall switch (turn power on/off) it takes very long (up to 10 minutes) until the "available" state updates. This makes it difficult or rather impossible to write a script for power on behavior. 
Any idea?
2. I uploaded the png file into folder "iobroker-data/files/zigbee.admin/img" but it's not displayed in adapter settings (file not found).
![philips_hue_1746130P7](https://user-images.githubusercontent.com/15210151/79969206-75d15980-8491-11ea-84bd-b46a8ab06886.png)

**Comment by Sacred-Shadow** [comment]
@ppent 
1. So there is nothing we can do about it. When the device needs so long to start and reconnect. It would be better not to switch the device off completely, but only to tell him to switch off the lamp.

2. Thank you, I upload the picture. If you have uploaded the picture manually, you have to transfer the picture to the website with "iobroker upload zigbee".

**Comment by Sacred-Shadow** [comment]
@arteck kann wohl zu
