### ISSUE TITLE
Tradfri LED E27,  600lm - Warning zu Color State x,y

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.zigbee#607]
Hallo,
nach dem Neustart einer Tradfri E27 600lm Color LED kommt neuerdings folgende Warning:
zigbee.0 | 2020-04-24 20:00:49.899 | warn | (15321) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2020-04-24 20:00:49.898 | warn | (15321) State value to set is invalid for zigbee.0.ccccccfffe9844a8.color: The state contains the forbidden properties x, y!

Merkwürdig ist, dass ich überhaupt keinen Color Status setze. Es gibt lediglich ein Script, welches die LED nach dem Neustart ausschaltet, da diese ja sonst ständig an ist nach dem Anlegen von Netzspannung bzw. Neustart des Adapters.
Zigbee Adapter 1.1.1
LED Version:
![grafik](https://user-images.githubusercontent.com/26110738/80243496-9c48ed80-8667-11ea-879c-ceabc5839c46.png)

**Comment by FabianHM** [comment]
Mittlerweile habe ich kein Script mehr was auf die LED zugreift und trotzdem erscheinen in unregelmäßigen Abständen Warnings im Log:

zigbee.0 | 2020-04-26 19:26:05.328 | warn | (6751) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2020-04-26 19:26:05.328 | warn | (6751) State value to set is invalid for zigbee.0.ccccccfffe9844a8.color: The state contains the forbidden properties x, y!

**Comment by Sacred-Shadow** [comment]
Mal unter die Objekte der LED geschaut? Welche Werte sind dort gerade drin?
Dabei mal achten, ob einer der Werte rot angezeigt wird.

Ich hatte als Beispiel schon einmal den Fall, dass mit VIS oder IQcontrol oder Alexa Müll versucht haben darein zu schreiben.

**Comment by FabianHM** [comment]
> 
> 
> Mal unter die Objekte der LED geschaut? Welche Werte sind dort gerade drin?
> Dabei mal achten, ob einer der Werte rot angezeigt wird.
> 
> Ich hatte als Beispiel schon einmal den Fall, dass mit VIS oder IQcontrol oder Alexa Müll versucht haben darein zu schreiben.

Hinweis war gut, es war innerhalb von Ei Test mit dem ColorPickerWidget!
Kannst Du mir sagen in welchem Format man bei diesem Adapter den Color Wert von Tradfri LED eigentlich korrekt einträgt?

**Comment by Sacred-Shadow** [comment]
Muss dir sagen, ich hab die Lampe nicht, kann jetzt auch nicht rauslesen ob es eine RGB oder RGBW ist.
Kannst ja mal #0000ff probieren, sollte ein Blau sein.

**Comment by Sacred-Shadow** [comment]
@FabianHM hat es funktioniert?

**Comment by FabianHM** [comment]
> 
> 
> @FabianHM hat es funktioniert?

Nein, leider nicht. Irgendwie stellt COLOR anscheinend ein Problem dar.
Bei dem Lampenpreis von 7,99€ hab ich jetzt keine Lust u Zeit mehr auf Ikea LED und kaufe eine andere.....

**Comment by Sacred-Shadow** [comment]
@kirovilya any idea what's going on?

**Comment by FabianHM** [comment]
> 
> 
> @FabianHM hat es funktioniert?

Ich habe die LED erneut auf Werkseinstellungen gesetzt. 
Um beim Neustart bzw. nach einer erneuten Stromverbindung der LED ein ungewolltes Einschalten zu korrigieren, prüft ein Script den Status "Available" und setzt beim Erkennen der neu verbundenen LED per "Aktualisierung" den "Brightness" State auf 0. 
Im Ergebnis meldet das Log wieder:
zigbee.0 | 2020-05-04 14:01:46.346 | warn | (8282) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2020-05-04 14:01:46.345 | warn | (8282) State value to set is invalid for zigbee.0.ccccccfffe9844a8.color: The state contains the forbidden properties x, y!

Das Problem sollte doch eigentlich bei mehr Nutzern mit Tradfri auftreten...

**Comment by FabianHM** [comment]
@Sacred-Shadow 
Ich habe die LED erneut auf Werkseinstellungen gesetzt. 
Um beim Neustart bzw. nach einer erneuten Stromverbindung der LED ein ungewolltes Einschalten zu korrigieren, prüft ein Script den Status "Available" und setzt beim Erkennen der neu verbundenen LED per "Aktualisierung" den "Brightness" State auf 0. 
Im Ergebnis meldet das Log wieder:
zigbee.0 | 2020-05-04 14:01:46.346 | warn | (8282) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2020-05-04 14:01:46.345 | warn | (8282) State value to set is invalid for zigbee.0.ccccccfffe9844a8.color: The state contains the forbidden properties x, y!

Das Problem sollte doch eigentlich bei mehr Nutzern mit Tradfri auftreten...

**Comment by Sacred-Shadow** [comment]
Das Problem ist ja nicht Brightness .. versucht irgendwas in den Color zu schreiben?
Schau einfach mal in die Objekte, da siehst du ja ob der Wert dort immer Rot wird und welcher Wert versucht wird da rein zu schreiben.

**Comment by FabianHM** [comment]
> 
> 
> Das Problem ist ja nicht Brightness .. versucht irgendwas in den Color zu schreiben?
> Schau einfach mal in die Objekte, da siehst du ja ob der Wert dort immer Rot wird und welcher Wert versucht wird da rein zu schreiben.

Also so einfach ist es leider nicht.
Kein Script und kein VIS Objekt greifen noch auf diese LED zu.

Ich habe die LED sogar komplett aus den Objekten gelöscht, um sicherzustellen dass keine States mehr vorhanden sind und die LED nochmals auf Werkseinstellungen gesetzt.
Meine Vermutung ist, dass das Firmwareupdate bei der Tradfri LED Änderungen vorgenommen hat, die nicht mit dem Adapter harmonieren.

**Comment by Garfonso** [comment]
Ich kriege die Warnungen auch, habe keine Tradfri Lampe. Ich glaube auch nicht, dass es an der Lampe liegt. Die Warnung interpretiere ich so: "Der Adapter fummelt zu viele Felder in den State, die da nicht hingehören". Vielleicht passiert das auch bei einem setState im Adapter, i.e. wenn ein Update von den Lampen kommt.

Das ist definitiv etwas, was man sich im Adapter angucken muss.

```
2020-05-11 14:35:07.646  - warn: zigbee.0 (27179) State value to set is invalid for zigbee.0.00178801000cb403.color: The state contains the forbidden properties x, y, saturation, hue!
2020-05-11 14:35:07.646  - warn: zigbee.0 (27179) This value will not be set in future versions. Please report this to the developer.

```
00178801000cb403 ist eine Phillips Iris (LLC010). Es passiert aber auch mit Lightstrips und (gefühlt nicht 100% geprüft, aber da sind einige IDs) allen anderen Lampen, die Farbe unterstützen.

**Comment by FabianHM** [comment]
Ich habe auch weiterhin die Phänomene, obwohl ich die Tradfri LED aus dem Adapter entfernt habe. Habe diese LED's nun alle über Deconz ohne Probleme laufen.

Eigentlich möchte ich mir ja die Mühe ersparen alles umzuziehen, jedoch scheint sich nach nunmehr 18 Tagen kein Entwickler des Zigbee Adapters dieses Thema annehmen zu wollen, schade....

**Comment by Garfonso** [comment]
Nur wegen der Warnung im Log so einen Aufwand...? Oder geht irgendwas nicht?

**Comment by FabianHM** [comment]
> 
> 
> Nur wegen der Warnung im Log so einen Aufwand...? Oder geht irgendwas nicht?
> 
> Die Entwickler sind halt auch nicht hauptberuflich hier beschäftigt. ;-)

Ich habe mich dazu entschlossen den Post zu löschen...

**Comment by Sacred-Shadow** [comment]
Also ich hab das Problem nun auch. 
Nur mit einer OSRAM Birne ... und auch erst nachdem ich Node.js auf v12.x geupdatet habe.

**Comment by modmax** [comment]
It seems, that there is a problem with setting x,y values for rgb lamps.
Seems to be related to Node.js or js-controller or zigbee implemtation . I personally thinks the problem ist
inside the JS controller ...

Even if someone sets an RGB value into the "color" field, then this will be internally transformed via rgb_to_cie into a xy-value, and that causes the problem.

**Comment by arteck** [comment]
```
color: {
        id: 'color',
        prop: 'color',
        name: 'Color',
        icon: undefined,
        role: 'level.color.rgb',
        write: true,
        read: true,
        type: 'string',
        setter: (value) => {
            // convert RGB to XY for set
            const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(value);
            let xy = [0, 0];
            if (result) {
                const r = parseInt(result[1], 16),
                    g = parseInt(result[2], 16),
                    b = parseInt(result[3], 16);
                xy = rgb.rgb_to_cie(r, g, b);
            }
            return {
                x: xy[0],
                y: xy[1]
            };
        },
        setterOpt: (value, options) => {
            const hasTransitionTime = options && options.hasOwnProperty('transition_time');
            const transitionTime = hasTransitionTime ? options.transition_time : 0;
            return {...options, transition: transitionTime};
        },
    },
```

this is the color function.. and the state is string.. hmm
its ok here.. 

for all :  the problem ist not NODE 12 or only Tradfri.. Osram works also not correct

**Comment by BigDi** [comment]
I also got this "warning" with a OSRAM LIGHTIFY Indoor Flex RGBW stripes.

**Comment by modmax** [comment]
I still have the same problem and does not depend on Node or the Zigbee Adapter Version.
I think the problem is from an internal used library which is used by the zigbee adapter.
Or event th OSRAM oder TRADFRI devies are just sendung x,y values.

The problem occurs independently of any interaction. So I think it occuirs if the bulb sends an update to the coordinator and the xy value is transformed. 

Until no I could not find the library with the original warning.

**Comment by asgothian** [comment]
A possible fix is available. Probable cause for the error:
- when a device returns from being offline, the adapter attempts to read the states color, color_temp, state and brightness. For most devices, color requires a transformation to x,y, while color temp requires a conversion to mired. Most states do not offer a getter to convert from x,y to hex, or from mired to whatever the state requires.

The fix is available [here](https://github.com/asgothian/ioBroker.zigbee/tree/Hue/HueCalib), and is being tested as we speak. If no negative effects are found it will become part of the 'official' 1.4.1 version.
