### ISSUE TITLE
No Connection to Osram Smart+ Plug with transmitPower : high

### ISSUE THREAD

**Issue by JabelsBS** [ioBroker/ioBroker.zigbee#609]
Hallo, 

wenn die Sendeleistung auf Normal ist, kann ich den Osram Smart+ Plug verbinden und auch steuern. Wenn die Sendeleistung auf High gestellt ist, ist keine Kommunikation zu dem Osram Smart+ Plug möglich.

**Comment by Sacred-Shadow** [comment]
Sry für die blöde Frage, aber du verwendest auch ein CC1352P o CC26X2R1?

**Comment by JabelsBS** [comment]
@Sacred-Shadow oh sorry das habe ich vergessen dazu zu schreiben. Ich verwende einen CC2531 ohne Antennen-Mod.
