### ISSUE TITLE
Gedopto GL-C-008 The state contains the forbidden properties x, y

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#611]
```
zigbee.0 | 2020-04-29 16:23:13.142 | warn | (5434) This value will not be set in future versions. Please report this to the developer.
zigbee.0 | 2020-04-29 16:23:13.141 | warn | (5434) State value to set is invalid for zigbee.0.00124b001d84e8a4.color: The state contains the forbidden properties x, y!
```
model:GL-C-007
vendor:Gledopto
description:Zigbee LED controller RGBW
supports:on/off, brightness, color, white
model:GL-C-007
type:Router
nwk:28567
manuf id:0
manufacturer:GLEDOPTO
power:Mains (single phase)
app version:1
hard version:1
zcl version:1
stack version:2
date code:20180920
build:2.0.2
interviewed:true
configured:false
endpoint:11
profile:49246
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
lightingColorCtrl (768)
endpoint:13
profile:49246
input clusters:touchlink (4096)
output clusters:touchlink (4096)
endpoint:15
profile:49246
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
lightingColorCtrl (768)

**Comment by Sacred-Shadow** [comment]
Versuchst das gleiche wie in #607 ?

**Comment by ldittmar81** [comment]
Irgendwie kommt die Meldung nicht mehr. Voll komisch... ich schließe es mal.
