### ISSUE TITLE
Philips Hue GU10 The state contains the forbidden properties x, y!

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#612]
```
zigbee.0 | 2020-04-29 16:22:47.491 | warn | (5434) This value will not be set in future versions. Please report this to the developer.
zigbee.0 | 2020-04-29 16:22:47.490 | warn | (5434) State value to set is invalid for zigbee.0.0017880102df06fc.color: The state contains the forbidden properties x, y!
```
model:8718696485880
vendor:Philips
description:Hue white and color ambiance GU10
supports:on/off, brightness, color temperature, color xy, power-on behavior
model:LCT003
type:Router
nwk:7971
manuf id:4107
manufacturer:Philips
power:Mains (single phase)
app version:2
hard version:15
zcl version:1
stack version:1
date code:20181121
build:5.127.1.26420
interviewed:true
configured:false
endpoint:11
profile:49246
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
touchlink (4096)
lightingColorCtrl (768)
manuSpecificLegrandDevices (64513)
output clusters:genOta (25)
endpoint:242
profile:41440
input clusters:greenPower (33)
output clusters:greenPower (33)

**Comment by Sacred-Shadow** [comment]
Gleiche wie #607 ?

**Comment by ldittmar81** [comment]
Irgendwie kommt die Meldung nicht mehr. Ich schließe erstmal
