### ISSUE TITLE
State value to set is invalid for zigbee.0.00158d0001c9c771.color: The state contains the forbidden properties x, y!

### ISSUE THREAD

**Issue by kueppert** [ioBroker/ioBroker.zigbee#613]
Hi,
i received following message in my ioBroker LOG, which should be send to the developer:
`

zigbee.0 | 2020-04-30 13:56:15.748 | warn | (19674) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2020-04-30 13:56:15.748 | warn | (19674) State value to set is invalid for zigbee.0.00158d0001c9c771.color: The state contains the forbidden properties x, y!

`

I'm on Proxmox-VM with Debian Buster, JS-Controller 3.0.20, Node 13.12.0 (yes, will update on 14 when available) and Zigbee-Adapter v1.1.1

Thank you, Thorsten

**Comment by Sacred-Shadow** [comment]
Same as #607 ?

**Comment by kueppert** [comment]
Yes,sorry
