### ISSUE TITLE
zigbee geht immer wieder von Grün auf Gelb

### ISSUE THREAD

**Issue by daxemann** [ioBroker/ioBroker.zigbee#614]
igbee.0	2020-04-30 19:09:31.063	error	at process._tickCallback (internal/process/next_tick.js:68:7)
zigbee.0	2020-04-30 19:09:31.063	error	at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:200:19)
zigbee.0	2020-04-30 19:09:31.063	error	at Array.forEach (<anonymous>)
zigbee.0	2020-04-30 19:09:31.063	error	at stateList.forEach (/opt/iobroker/node_modules/iobroker.zigbee/main.js:212:43)
zigbee.0	2020-04-30 19:09:31.063	error	(2698) TypeError: Cannot read property 'toZigbee' of null
zigbee.0	2020-04-30 19:09:31.062	error	(2698) uncaught exception: Cannot read property 'toZigbee' of null

was kann ich da machen ??

---

**System data:**

Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v10.20.1
NPM: 6.14.4
Platform: linux
Distribution: Raspbian GNU/Linux
Architecture: arm
JS-Controller (1): 3.0.20
Admin: 4.1.1
Zigbee: 1.1.1

> *created by ioBroker.info*

**Comment by Sacred-Shadow** [comment]
Saubere Installation? Oder wars nen Update?

**Comment by daxemann** [comment]
eigendlich war alles gut . hab seit 2 Tagen festgestellt das es spinnt , seit die ganzen js-controller
updates gekommen sind .
Installiert: 3.0.20 , zigbee 1.1.1. bin jetzt mal runter auf 1.1.0 , bis jetzt kein gelb oder so , aber bei 1.1.1 immer wieder gelb und kann keine Geräte steuern Xiaomi Aquara bzw , Osram Steckdosen .
mal sehen ob das so geht dann lass ich erst mal die 1.1.0 drauf
