### ISSUE TITLE
SLC SmartOne AC Wanddimmer 300W

### ISSUE THREAD

**Issue by m1chel87** [ioBroker/ioBroker.zigbee#615]
Hallo,

kann dieser Dimmer eingebunden werden??

https://www.tlg.no/slc-smartone-ac-wall-dimmer-300w-zigbee

**Comment by Sacred-Shadow** [comment]
Mit den Angaben nicht, 

Du solltest erstmal hier durch:
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Wenn das Gerät dann in Zigbee2mqtt drin ist, kommt es auch hier in den Support. 
Die Anleitung ist auch recht umfangreich.

**Comment by m1chel87** [comment]
@Sacred-Shadow was heißt mit den Angaben nicht? 
Ich werde mir die Anleitung mal ansehen. Ich muss sowieso erstmal rausfinden wo ich einen solchen Dimmer beziehen kann. Bisher habe ich nichts gefunden
