### ISSUE TITLE
OSRAM Plug enters unresponsive state after hours of working OK

### ISSUE THREAD

**Issue by juamiso** [ioBroker/ioBroker.zigbee#616]
Osram Plug does not respond to commands, after several days of working OK. Recovers once you click in the physical button on the plug

Error message:
`error: zigbee.0 Error on send command to 0x7cb03eaa0a08fe47. Error: Error: Command 0x7cb03eaa0a08fe47/3 genOnOff.on({}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error: Data request failed with error: 'No network route' (205))
`

## Reproducible :
Not really easy, looks random (once per week?) It happened already at least 3x

## Debug Info
Iobroker Zigbee Adapter version version: 1.0.4
Adapter hardware: CC2531
Device info:
eee:0x7cb03eaa0a08fe47
nwk:27382 (0x6af6)
model:Plug 01
vendor:OSRAM

Logs
[https://pastebin.com/4WXaAEG7](url)

**Comment by arteck** [comment]
update to 1.1.1
