### ISSUE TITLE
how to send touchlink via iobroker?

### ISSUE THREAD

**Issue by OberstVonGatow** [ioBroker/ioBroker.zigbee#617]
Hi,
is it possible to send a touchlink command from the iobroker instance?
I try to pair an old philips living color with touchlink like here https://www.zigbee2mqtt.io/information/touchlink

Regards

**Comment by kirovilya** [comment]
Currently only the reset command is working

**Comment by OberstVonGatow** [comment]
Okay and is it possible to factory reset a device which was not paired with iobroker zigbee before?
In the docu https://www.zigbee2mqtt.io/information/touchlink it is said "...communicate with each other without being in the same network." but how can i send a reset? 
If i go to the analyse tab need to choose an existing device for every command.

**Comment by kirovilya** [comment]
![image](https://user-images.githubusercontent.com/8360230/81053176-5a247500-8ecd-11ea-80bf-4490009855d7.png)

**Comment by OberstVonGatow** [comment]
Ah okay. I think i have an old firmware version and need to update first.
