### ISSUE TITLE
Adapter restart automatically

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.zigbee#620]
Hi,

the following errors i have the second or third time,

Copy from log tab:
zigbee.0 | 2020-05-03 14:28:39.489 | error | at processTimers (internal/timers.js:492:7)
-- | -- | -- | --
zigbee.0 | 2020-05-03 14:28:39.489 | error | at listOnTimeout (internal/timers.js:549:17)
zigbee.0 | 2020-05-03 14:28:39.489 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
zigbee.0 | 2020-05-03 14:28:39.489 | error | (12788) Error: Timeout - 62092 - 3 - 192 - 0 - 1 after 10000ms
zigbee.0 | 2020-05-03 14:28:39.469 | error | (12788) uncaught exception: Timeout - 62092 - 3 - 192 - 0 - 1 after 10000ms

Copy from log file:

2020-05-03 14:28:39.469 - error: zigbee.0 (12788) uncaught exception: Timeout - 62092 - 3 - 192 - 0 - 1 after 10000ms
--
2020-05-03 14:28:39.489 - error: zigbee.0 (12788) Error: Timeout - 62092 - 3 - 192 - 0 - 1 after 10000ms
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7)

Installed version is 1.1.1, Node.js 12.16.3, js-controller 3.0.20

Thanks
Michael

**Comment by kueppert** [comment]
same for me :(

**Comment by Apollon77** [comment]
@arteck @kirovilya Maybe an error event handler is missing?

**Comment by Apollon77** [comment]
or a promise catch :-)

**Comment by kirovilya** [comment]
@kueppert @MMeinhardt1 Try to install from github. Herdsman updated there

**Comment by kueppert** [comment]
@kirovilya for me the github version (same v1.1.1) works. Since 11:37 o`clock till now no more shutdowns of the zigbee-Adapter. Thank you very much :+1:
