### ISSUE TITLE
Zigbee Adapter kein pairing mit Ikea tradfri LED1739R5

### ISSUE THREAD

**Issue by vheese** [ioBroker/ioBroker.zigbee#622]
Hallo zusammen,
ich habe bereits mehrere Zigbee Komponenten am laufen (Xiaomi, Ikea tradfri) habe mir jetzt 3 neue GU10 Birnen "LED-Leuchtmittel GU10 400 lm, kabellos dimmbar Weißspektrum" von IKEA mit der Modellkennung **LED1739R5** zugelegt. 
Dies lassen sich leider nicht pairen ! 
Gibt es da eine möglichkeit ?
lg Volker

**Comment by vheese** [comment]
so kleines Update,
habe in der Datei /opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js
mir eine Lampe rausgesucht die die gleich Funktion hat "model:LED1537R6"
und dort nur den Eintrag mit LED1739R5 ersetzt.
Jetzt funktioniert pairing und alle Objekte und Funktionen sind gegeben

**Comment by vheese** [comment]
Firmeware Update der Lampen über die Oberfläche funktioniert auch
Finished update of '0xec1bbdfffeaf96e4', from '{"softwareBuildID":"2.0.022","dateCode":"20190308"}' to '{"softwareBuildID":"2.0.023","dateCode":"20190407"}'

**Comment by arteck** [comment]
> 
> 
> so kleines Update,
> habe in der Datei /opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js
> mir eine Lampe rausgesucht die die gleich Funktion hat "model:LED1537R6"
> und dort nur den Eintrag mit LED1739R5 ersetzt.
> Jetzt funktioniert pairing und alle Objekte und Funktionen sind gegeben

welche währe das ??

**Comment by vheese** [comment]
Die Funktion an/aus, Dimmen und lichttemperatur 
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Wed, May 13, 2020 at 11:06 AM +0200, "arteck" <notifications@github.com> wrote:


















so kleines Update,


habe in der Datei /opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js


mir eine Lampe rausgesucht die die gleich Funktion hat "model:LED1537R6"


und dort nur den Eintrag mit LED1739R5 ersetzt.


Jetzt funktioniert pairing und alle Objekte und Funktionen sind gegeben





welche währe das ??

**Comment by vheese** [comment]
Die Birne ist diese hier :
https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-400-lm-kabellos-dimmbar-weissspektrum-90408603/

**Comment by tobstare** [comment]
Hallo,
danke für den Tipp! Das gleiche habe ich mit dem LED Leuchtmittel "LED1835C6'" gemacht.
Ich habe in der Datei 
"/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js" 
die Zeile: 
`model: 'LED1903C5'` 
in mein LED-Leuchtmittel geändert: 
`model: 'LED1835C6'`
Oder hätte ich den Abschnitt einfach kopieren können? Das hatte ich nämlich zuerst versucht, leider ohne erfolg. Was letztendlich aber daran liegen könnte, dass ich anschließend den Raspberry neugestartet habe und den Bindingvorgang erneut getestet hatte. Nach dem zurücksetzen des Leuchtmittels, über das 6-malige anschalten und etwas Geduld wurde diese dann aber erfolgreich gefunden und kann nun verwendet werden.

**Comment by arteck** [comment]
ihr seid mir ja 2 Experten.. macht das mal ordentlich und erspart mir das gesuche

ein PR ist hilfreich hier.. ansonsten mach ich hier zu

**Comment by tobstare** [comment]
Sorry,
ich kenne mich leider nicht so gut mit GitHub aus. Ich möchte hier niemandem Arbeit machen, aber allen anderen dabei Helfen Ihre Zigbee Komponenten zum laufen zu bringen. 
Aber das ganze gehört hier wohl garnicht hin, so wie ich das jetzt sehe müssen diese devices zur zigbee-herdsman Komponente hinzugefügt werden. Einen entsprechenden pull request habe ich dort aufgemacht. Somit kann hier wohl wirklich zu gemacht werden. Vielen Dank!

**Comment by arteck** [comment]
wenn du es da gemacht hast dann muss hier auch ein PR gestellt werden.. da wir es auch auflösen müssen im Adapter

**Comment by tobstare** [comment]
Antwort vom Entwickler: "It seems that the device was already supported but under a different model so I've updated the existing entries. thanks!"
[Merged #1262 into master.](https://github.com/Koenkk/zigbee-herdsman-converters/pull/1262)
Ich denke also ein PR ist hier nicht nötig, da die Unterstützung über bereit existierende Modelle läuft.
