### ISSUE TITLE
Device 0x00124b0006233afb "902010/23" not described in statesMapping.

### ISSUE THREAD

**Issue by huperis** [ioBroker/ioBroker.zigbee#623]
I would like to use the Bitron home 902010/23 remote control via the ZigBee adapter.

What information do you need about the device?
I have attached the information from the ZigBee adapter.

Thank you!
![bitronhome](https://user-images.githubusercontent.com/56505559/81169442-29aa0d00-8f99-11ea-8c27-626130a15dc7.JPG)

**Comment by Sacred-Shadow** [comment]
The device is not even supported by zigbee2mqtt.io.
You should therefore first go through the path:
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
