### ISSUE TITLE
NodOn "GreenPower_2" not described in statesMapping.. undefined

### ISSUE THREAD

**Issue by juamiso** [ioBroker/ioBroker.zigbee#626]
Can I somehow port the device from Koenkks files? devices.js or fromzigbee.js conversters have at least some GreenPower definitions. Looks like current iobroker.zigbee adapter has none (yet).

model:GreenPower_On_Off_Switch
vendor:GreenPower
description:On/off switch
supports:action
model:GreenPower_2
type:GreenPower
nwk:41383
manuf id:null
interviewed:true
configured:false

```
Error: Device 0x000000000171a1a7 "GreenPower_2" not described in statesMapping.. undefined
New device joined '0x000000000171a1a7' model GreenPower_2
Error: Device 0x000000000171a1a7 "GreenPower_2" not described in statesMapping.. undefined
Interview successful: {"friendly_name":"0x000000000171a1a7","model":"GreenPower_On_Off_Switch","vendor":"GreenPower","description":"On/off switch","supported":true}
```

[reference @ zigbee3mqtt](https://github.com/Koenkk/zigbee2mqtt/issues/3322#issuecomment-625523931)

Can I help in any way?

**Comment by juamiso** [comment]
adapter version 1.1.1 on CC2531

**Comment by HansBorjes** [comment]
When adding in file

/opt/iobroker $ sudo vi node_modules/iobroker.zigbee/lib/devices.js

the following definition the error above disappears. An object with datapoints is created. Unfortunately only the link_quality is being updated. But you can already trigger on the link_quality being updated. :-)

const devices = [
    {
        vendor: 'GreenPower',
        models: ['GreenPower_2'],
        icon: 'img/xiaomi_wireless_switch.png',
        states: [
            states.button_action_press, states.button_action_hold, states.button_action_release,
        ],
    },

**Comment by juamiso** [comment]
well, definitely a step in the proper direction, but not really useful yet

**Comment by HansBorjes** [comment]
According to 
https://www.manualslib.com/manual/1572891/Dolphin-Ptm-216z.html

the Command IDs for press and release are 0x69 and 0x6A. Probably in file 
node_modules/zigbee-herdsman-converters/converters/fromZigbee.js

in "greenpower_on_off_switch: {"

needs to be added

                0x69: 'press',
                0x6A: 'release',

But I am not sure how the Button Status bits will be processed then that are encoding which of the four buttons have been pressed. Maybe @Koenkk can give a hint? Or one of the more experienced guys here can help to understand whether this is a herdman or iobroker topic?

**Comment by HansBorjes** [comment]
When putting zigbee adapter in debug logging upon button press/release I can see messages like 

Publish {"action":"recall_scene_0"}

where _0 indicates left button up press and _4 indicates left button up release.

Can anyone give a hint how to map this to a state?

**Comment by HansBorjes** [comment]
Okay, I got it working. Not sure whether this is according to the iobroker design rules... :-)

node_modules/iobroker.zigbee/lib/devices.js

```
const devices = [
    {
        vendor: 'GreenPower',
        models: ['GreenPower_2'],
        icon: 'img/xiaomi_wireless_switch.png',
        states: [
            states.button_action_press, states.button_action_release, states.action,
        ],
    },

```
node_modules/iobroker.zigbee/lib/states.js

```
    action: {
        id: 'action',
        prop: 'action',
        name: 'button action',
        role: 'button',
        write: false,
        read: true,
        type: 'text',
    },

```

**Comment by HansBorjes** [comment]
I tried to make a pull request from these changes.
https://github.com/ioBroker/ioBroker.zigbee/pull/640

**Comment by juamiso** [comment]
Hi @HansBorjes I replicated your changes and coud get the switch paired and no errors showed in the logs. However in no button states were being tracked. The device was listed in the objects list but nothing was being updated. I wanted to "repair" it to try again and could not get to pair it again. Tried like more than 10 times. Changed Zigbee ID, channel, lost all the pairings to my devices after a hard reset and this NodOn switch does not want to pair any more :( very confused... I've tried on Ch11 and on Ch20, and it does not advertise as it did before, nothing, just as if it was dead (but it is not, still working OK with Philips Hub)

**Comment by HansBorjes** [comment]
I am using it on Ch15. Not sure whether pairing is possible with CC2531 directly, but after pairing a greenpower 'gateway' is necessary that is paired to the CC2531 and has power supply. In my case it is a ZBT-ExtendedColor from Mueller Licht. The range of the switch seems somewhat limited.

Have you put the Zigbee adapter into loglevel debug in order to see all messages? The "action" datapoint shows the activity. The button_press and button_release datapoints remain empty.

**Comment by juamiso** [comment]
I am not sure if I can follow you. I am only using iobroker adapter, so no idea about how to put the CC2531 in debug mode.
I also do not understand what do you mean by pairing the switch with a greenpower gateway and then to the CC2531. I have a philips hue v3 bridge which I use to control the lamps and (just in case iobroker will never be able to) to control the greenpower switch as well.  But it is not able to distinguish between long press/short press, which I 'need'. So having this switch running on the CC2531 is my long term goal, since then I can avoid the people moving up the shutter by mistake (long press needed for it).

**Comment by HansBorjes** [comment]
In order to put the Zigbee adapter in debug logging go to "Instances". Enable "Expert Mode" at the top with the blue symbol. In the "Loglevel" column click in the row for "zigbee.0". Change the default value of "info" to "debug". Now take a look at "Log". You will find more details from the Zigbee adapter. Don't forget to revert to "info" afterwards as this will flood you log file.

I don't know details about the original Hue Bridge, but it seems to me that you probably need to pair the switch and the Hue Bulb with the CC2531. I would expect that Coordinator, "Router" (the bulb) and the switch need to be in the same Zigbee network.

**Comment by juamiso** [comment]
Thanks for the instructions. I had "expert" mode off in the adapter view so I could not see the debug modes...

I coudl kind-of-pair it again today, but it did not work with the button states. What I have done:
start a pairing process. Press the button 3 (channel 11) for more than 10s. Then looks like it sucessfully pairs, it appears under objects but no debug info is seen in the logs when buttons are pressed. Then I try to re-pair it without sucess. After that I've done a soft-reset from the CC2531, tried again, nothing. Paired back again with Philips bridge, worked. Even tried change the Philips Bridge from ch 25 to ch11 to see wheather this somehow helps and tried again to re-pair. But it did not help.



```
2020-05-25 22:09:25.022  - [32minfo[39m: zigbee.0 (8531) Zigbee: allowing new devices to join.
2020-05-25 22:09:25.029  - [34mdebug[39m: zigbee.0 (8531) sendTo "letsPairing" to system.adapter.admin.0 from system.adapter.zigbee.0: Start pairing!
22020-05-25 22:09:36.183  - [34mdebug[39m: zigbee.0 (8531) Publish {"state":"OFF"}
2020-05-25 22:09:37.471  - [34mdebug[39m: zigbee.0 (8531) handleDeviceJoined. {"device":{"ID":10,"_type":"GreenPower","_ieeeAddr":"0x000000000171a1a7","_networkAddress":41383,"_manufacturerID":null,"_endpoints":[],"_modelID":"GreenPower_2","_interviewCompleted":true,"_interviewing":false,"meta":{},"_lastSeen":null}}
2020-05-25 22:09:37.473  - [34mdebug[39m: zigbee.0 (8531) handleDeviceInterview. {"status":"successful","device":{"ID":10,"_type":"GreenPower","_ieeeAddr":"0x000000000171a1a7","_networkAddress":41383,"_manufacturerID":null,"_endpoints":[],"_modelID":"GreenPower_2","_interviewCompleted":true,"_interviewing":false,"meta":{},"_lastSeen":null}}
2020-05-25 22:09:37.473  - [32minfo[39m: zigbee.0 (8531) Successfully interviewed '0x000000000171a1a7', device has succesfully been paired
2020-05-25 22:09:37.473  - [32minfo[39m: zigbee.0 (8531) Device '0x000000000171a1a7' is supported, identified as: GreenPower On/off switch (GreenPower_On_Off_Switch)
2020-05-25 22:09:37.474  - [34mdebug[39m: zigbee.0 (8531) New device event: {"type":"device","device":{"ID":10,"_type":"GreenPower","_ieeeAddr":"0x000000000171a1a7","_networkAddress":41383,"_manufacturerID":null,"_endpoints":[],"_modelID":"GreenPower_2","_interviewCompleted":true,"_interviewing":false,"meta":{},"_lastSeen":null},"mapped":{"zigbeeModel":["GreenPower_2"],"model":"GreenPower_On_Off_Switch","vendor":"GreenPower","description":"On/off switch","supports":"action","fromZigbee":[{"cluster":"greenPower","type":"commandNotification"}],"toZigbee":[],"whiteLabel":[{"vendor":"Philips","description":"Hue Tap","model":"8718696743133"},{"vendor":"Niko","description":"Friends of Hue switch","model":"91004"}]},"name":"0x000000000171a1a7"}
2020-05-25 22:09:37.475  - [34mdebug[39m: zigbee.0 (8531) Publish available for 0x000000000171a1a7 = true
2020-05-25 22:09:37.475  - [34mdebug[39m: zigbee.0 (8531) new device 0x000000000171a1a7 41383 GreenPower_2
2020-05-25 22:09:37.477  - [34mdebug[39m: zigbee.0 (8531) Wrong device 000000000171a1a7 null
...   
```

x
![nodon](https://user-images.githubusercontent.com/50164437/82843195-aebf7c80-9edc-11ea-88ca-f07a783cb7a5.png)
![nodon2](https://user-images.githubusercontent.com/50164437/82843206-b54df400-9edc-11ea-9b52-3e120ec07585.png)

**Comment by HansBorjes** [comment]
Have you "uploaded" the files after editing? This is done in "Adapters" view: "change view", "Adapters with instances", "Expert Mode", "Upload", then in "Instances" reload the adapter.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/1429215/82843903-00690680-9edf-11ea-93f1-4d58500f2210.png">

BTW: did you install the 1.1.1 release version? I installed directly from github which grabbed more recent commits than the 1.1.1 release.

**Comment by juamiso** [comment]
OK, did not know that had to "upload" the files. I did restart the adapter, of course. Normally with changes into devices.js was enough. I will try now again.

I also would like to use the source code from github direclty, but I am afraid if I get it from there I will have to re-pair again all my devices. is it really enough to backup the file sheperd.db?

**Comment by HansBorjes** [comment]
You have to store manually:
- Network name
- Network key
- Channel

https://github.com/simatec/ioBroker.backitup/issues/305#event-3353378258

I installed using
/opt/iobroker# npm install git+URL

https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

Installing from git did not affect my paired devices.

**Comment by juamiso** [comment]
Lost all pairings again :( I am too tired maybe, going to bed for today. At least I got the adapter installed from Github, that is also not straight forward. The backup adapter is also not at "apple level"... haha, also several issues there...
All devices appear as linked but none reacts to the commands/updates. Need to re-pair all of them. On top, the stupid Nod-On does not want to pair , yet again.
