### ISSUE TITLE
Kein Pairing mit Osram Outdoor Flex Multicolor Lightstrip

### ISSUE THREAD

**Issue by mikepiko** [ioBroker/ioBroker.zigbee#627]
Gerät taucht später in der Liste als Undefined auf.

Im Log steht :
`Failed to interview '0x7cb03eaa00a37ed4', device has not succesfully been paired. undefined`

Unter Device Info steht:
type: Router , endpoint 3
nwk: 439
Manuf id: 48042
interviewed false
configured false

Wenn noch angaben benötigt werden , bitte melden ;-)

**Comment by Sacred-Shadow** [comment]
Kannst du die Details mal komplett posten?

Insbesondere der obere Teil.
Also sowas hier...



    model:4052899926110
    vendor:OSRAM
    description:Flex RGBW
    supports:on/off, brightness, color temperature, color xy

**Comment by mikepiko** [comment]
Nachdem er mehrfach nur als "undefined" aufgetaucht ist, hab ich ihn jetzt nach dem dritten Versuch registriert bekommen:

`model:4058075036185
vendor:OSRAM
description:Outdoor Flex RGBW
supports:on/off, brightness, color temperature, color xy`

Hat danach sogar gemeldet das nen Firmware Update verfügbar ist.

Firmware update ist durchgelaufen, danach nochmal gelöscht und neu angelernt. Funktioniert.

on/off, rgb und color temp reagieren auch auf Änderungen.

Könnte somit auch unter "supported devices" gelistet werden :)

**Comment by Sacred-Shadow** [comment]
Da issa mit drin ^^
![grafik](https://user-images.githubusercontent.com/61997661/81497943-2b8a0e00-92c2-11ea-85fa-b8d12d519254.png)

Na is doch fein, dass es geklappt hat.
