### ISSUE TITLE
Xiaomi Mi power plug ZigBee EU

### ISSUE THREAD

**Issue by Schimi1983** [ioBroker/ioBroker.zigbee#628]
HI,

habe zwei Xiaomi Smart Plugs.... scheinen aber irgednwie "anders" zu sein....

![image](https://user-images.githubusercontent.com/4581474/81409853-2735e780-9140-11ea-8c9b-5916d70ffde2.png)
![image](https://user-images.githubusercontent.com/4581474/81409864-2c933200-9140-11ea-98f3-261824687aad.png)

![image](https://user-images.githubusercontent.com/4581474/81409940-4765a680-9140-11ea-9a39-a2c9df20d396.png)

Leider kenn ich mich nicht so gut aus....
kann man da den vielleicht den Tagesverbrauch hinzufügen? Oder geht das "Hardware" mäßig nicht von den Plugs her? (jemand nen tipp? ZigBee oder WLAN)
OTA Updates funktionieren auch nicht, Meldung: "No firmware update aviable"

Wenn ich was ausprobieren soll, gerne... brauche dann aber eine Anleitung :-)

**Comment by Sacred-Shadow** [comment]
Die Teile speichern nicht die Werte .. du musst dir entsprechende Tools in den iobroker einbauen.
Gibt ja einige Möglichkeiten eine Statistik für Werte einzubauen.

Wieso sollten die OTA Updates nicht funktionieren?
Bekommst doch keine Fehlermeldung sondern einfach, dass es keine andere FW gibt. 
Oder hast du eine neuere, die nicht gezogen wird?

**Comment by Schimi1983** [comment]
Jap, habe ich auch gemacht... wollte nur die Infos teilen da es so aussieht als ob es zwei verschiedene varianten wären (wegen den "endpunkten").

OTA funktioniert logischerweise nicht da (wenn ich es richtig gelesen habe) Xiaomi "Updateserver" nicht bekannt und damit ja nicht implementiert sind :-)

Falls für "euch" keine brauchbaren Infos vorhanden sind... kann das hier gerne geschlossen werden :-)

Finde eure Arbeit aber echt TOP!! :-)
