### ISSUE TITLE
Support Innr Flex FL 130 C - RGBW-LED-Strip

### ISSUE THREAD

**Issue by dernicc** [ioBroker/ioBroker.zigbee#629]
Hi there,

the Innr Flex FL 130 C is missing in the devices.js.
This causes an error while pairing this device. I can't recall it at the moment but it was something like: The statesmapping for the device is missing. 

So I added the following part to the devices.js under the innr-category.

`{
        vendor: 'Innr',
        models: ['FL 130 C'],
        icon: 'img/innr_flex.png',
        states: lightStatesWithColortemp,
        linkedStates: [comb.brightnessAndState],
    },`

And I added the follwing img for the flex strip.
![innr_flex](https://user-images.githubusercontent.com/2436841/81493659-8ca1e980-92a2-11ea-9d7e-2c999b22453f.png)

Could you maybe add this to the devices.js in the repository so we do not have to make these modifications after an upgrade?

**Comment by Sacred-Shadow** [comment]
Do all functions work?

**Comment by dernicc** [comment]
With the previous configuration the color lightStatesWithColortemp I was not able to change the color via RGB. So I changed the states to lightStatesWithColor:

`{ vendor: 'Innr', models: ['FL 130 C'], icon: 'img/innr_flex.png', states: lightStatesWithColor, linkedStates: [comb.brightnessAndState], },`

With this configuration all functions are working.

But I still won't get the icon.
I places the img file under "...\iobroker\iobroker-data\files\zigbee.admin\img" and "...\iobroker\node_modules\iobroker.zigbee\admin\img" and modified the permissions according the other files in these folders.
This is the error I get in the console: 
`Could not load image: img/innr_flex.png`
`i.image.onerror | @ | vis-network.min.js:25"`


It is still possible to add only "FL 130 C" to line 1092 in the devices.js `models: ['RB 185 C', 'RB 285 C', 'RB 250 C'],` so it will be `models: ['RB 185 C', 'RB 285 C', 'RB 250 C','FL 130 C'],`.

**Comment by Sacred-Shadow** [comment]
So is built in, with the next version they are in there.
