### ISSUE TITLE
..we can transfer and add the same functionality to this adapter. If you notice this, then write the issue - we'll postpone it..

### ISSUE THREAD

**Issue by blackjack3000** [ioBroker/ioBroker.zigbee#633]
!!!PLEASE!!! adapt the follow zigbee modul to your Adapter.

Modell: E1744

![Bildschirmfoto 2020-05-13 um 23 42 18](https://user-images.githubusercontent.com/23570751/81869053-a75eb180-9573-11ea-9147-7ac97afe28dd.png)

THX

**Comment by nbars** [comment]
Hello guys, thanks for the great adapter. Is there any plan to implement support for the `SYMFONISK Sound Controller`?

Thanks in advance.
