### ISSUE TITLE
Transition time is ignored for brightness=0 or state=false

### ISSUE THREAD

**Issue by Strunzdesign** [ioBroker/ioBroker.zigbee#635]
Hi,

all my Philips Hue bulbs are affected, but I refer to my LCT012 here as I have tested it again right now. The transition_time field works as expected for switching on a bulb and setting a brightness value between 1 and 100 (max). Unfortunately, it seems that the transition_time field is ignored for either setting a brightness value of zero or switching it off by setting state=false. However, switching the bulb on with state=true does ignore the transition_time field as well, which should be discussed separately.

Thus, it is not possible to switch a bulb off using a slow "fade out effect" (multiple seconds desired) using the transition_time field. I think that the transition_time field should also work for for a brightness value of 0.

Newest adaptor, of course :-) I can help implementing stuff, but need a hint where I can start to dig fixing this issue.

Regards,
Florian

**Comment by arteck** [comment]
you can use brightness only .. set this to 0 or 100 and you have a fade in or out effect

**Comment by Strunzdesign** [comment]
Okay, I got that, thus lets only talk about setting the brightness. You can set any brightness level and a transition_time is respected, but if you want do dim to 0, then it is ignored. In fact, there is some sort of dimming if setting brightness to 0, but it can neither be disabled (by setting transition_time to 0) or changed.

Thus, it is not possible to dim from 100 to 0 over a time span of 5 seconds.

Please test this:
- Set a bulb to brightness 100
- Select a transition_time of 10 (seconds)
- Set bulb brightness to 0

Here on my setup, the bulb dims to 0 in under 1 second. The transition_time is ignored.

**Comment by arteck** [comment]
i dont know how long is the max transition_time for hue .. i have here max 5 sec

**Comment by Strunzdesign** [comment]
Hi arteck,

the issue is the same with a transition_time of 5 seconds. If you go from brightness level 100 down to 1, then it takes 5 seconds, fine. If you go down to 0, then the fade-out needs only ~0.5 second, which is a similar dimming behavior as if switching the bulb off via "state -> 0".

May it be that setting a brightness level of 0 takes a shortcut in the stack somehow? That this brightness level value is checked for zero and then treated differently, as if state was set to zero, and hereby the optional parameter "transition time" is sheared off?

BTW my HUE bulbs at hand have no problem with a transition time of 60 seconds, no idea yet where the limit is. However, if your lamps have their limit at 5 seconds, please test with 5 or 4 seconds. You should see a difference between level 1 and 0.

Regards,
Florian
