### ISSUE TITLE
Tradfri Signalverstärker miteinander pairen funktioniert nicht (cc1352p_2)

### ISSUE THREAD

**Issue by rmp63526** [ioBroker/ioBroker.zigbee#636]
Hallo, habe ein cc1352p_2 board und die zigbee V1.0.4 drauf.
Leider lassen Sie die Ikea Repeater untereinander nicht koppeln.

**Comment by Sacred-Shadow** [comment]
Was meinst du mit, dass die sich untereinander nicht koppeln lassen? 
Was probierst du wie?

**Comment by rmp63526** [comment]
@Sacred-Shadow, Ich habe einen tradfri Signal Verstärker in Raum A und möchte mich mit dem anderen Tradfri verstärker in Raum B mich verbinden.

**Comment by Sacred-Shadow** [comment]
Sry aber wenn ich das nicht falsch verstanden habe, musst du das garnicht machen.
Der Standard selbst übernimmt, wer mit wem spricht.

Ein manuelles koppeln ist nicht nötig.

**Comment by rmp63526** [comment]
Alles klar, danke. 
Werde ich versuchen und berichten.

**Comment by rmp63526** [comment]
Habe spaßeshalber mein zigbee stick cc2532 angeschlossen und konnte darüber die Tradfri Repeater miteinander koppeln. Leider bin ich mit dem Stick und seiner Reichweite nicht zufrieden.

Mit dem CC1352p_2 Board ist das nicht möglich.

Meine Ansätze bis jetzt mit dem CC1352p_2: 
Ich habe beide Tradfri Repeater getrennt an den Coordinator gekoppelt, jedoch liegt hier dann die link Quality bei gerade mal 35-50 bei einem Abstand von höchstens 3-4 m bis zum CC1352p_2 Board.
Habe sogar mein W-Lan ausgeschaltet, um irgendwelche Störfrequenzen auszuschließen.
Den CC1351p_2 habe ich nochmal mit dem Flash-Programmer-2-1.8.1 geflasht.
Die zigbee Instanz gelöscht und nochmal installiert. Auch die shepher datei  im /opt/iobroker/iobroker-data/Zigbee_0 gelöscht.

Denke mal es heißt abwarten und auf die neue Version warten?

**Comment by arteck** [comment]
das Netz bau sich von selbst auf.. ergo es ist nicht nötig das was du Vorhast zu machen..
