### ISSUE TITLE
Problem mit Xiaomi MiJia light intensity sensor

### ISSUE THREAD

**Issue by Bibo13** [ioBroker/ioBroker.zigbee#637]
Hi, 
Zigbee 1.04 hat nach erfolgreichem Interview des Sensors Probleme mit dem Config. 
Was kann ich tun?

20-05-18 13:59:36.762 | info | (4599) Zigbee: stop joining
-- | -- | --
zigbee.0 | 2020-05-18 13:59:18.768 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
zigbee.0 | 2020-05-18 13:59:18.768 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-05-18 13:59:18.768 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:235:23)
zigbee.0 | 2020-05-18 13:59:18.768 | error | (4599) Failed to configure 0x04cf8cdf3c78c9b3 lumi.sen_ill.mgl01,  attempt 1 (Error: Bind 0x04cf8cdf3c78c9b3/1 genPowerCfg from  '0x00124b00014d2885/1' failed (Error: AREQ - ZDO - bindRsp after 10000ms
zigbee.0 | 2020-05-18 13:59:08.764 | info | (4599) Configuring 0x04cf8cdf3c78c9b3 lumi.sen_ill.mgl01
zigbee.0 | 2020-05-18 13:59:08.761 | info | (4599) Device '0x04cf8cdf3c78c9b3' is supported, identified as: Xiaomi MiJia light intensity sensor (GZCGQ01LM)
zigbee.0 | 2020-05-18 13:59:08.760 | info | (4599) Successfully interviewed '0x04cf8cdf3c78c9b3', device has succesfully been paired
zigbee.0 | 2020-05-18 13:58:47.904 | info | (4599) Starting interview of '0x04cf8cdf3c78c9b3'
zigbee.0 | 2020-05-18 13:58:35.704 | info | (4599) Zigbee: allowing new devices to join.

**Comment by Bibo13** [comment]
Daten kann man nicht lesen deshalb als Textfile
[Zigbee Log.txt](https://github.com/ioBroker/ioBroker.zigbee/files/4644037/Zigbee.Log.txt)

**Comment by arteck** [comment]
update to GIT version

**Comment by Bibo13** [comment]
Ich habe den update auf 1.1.1 vorgenommen. hat sich aber nichts verändert.
[Zigbee2.txt](https://github.com/ioBroker/ioBroker.zigbee/files/4648827/Zigbee2.txt)

**Comment by Bibo13** [comment]
Auch nach löschen und Neu anlernen. Kein erfolg. Er wird interviewed aber nicht configuriert.
Im Anhang log und wie er im Adapter sichtbar ist.
[Zigbee3.txt](https://github.com/ioBroker/ioBroker.zigbee/files/4649477/Zigbee3.txt)
![Mija_Lumi](https://user-images.githubusercontent.com/45422390/82310366-945d3e80-99c4-11ea-9272-74f93ec1c0c3.JPG)

**Comment by arteck** [comment]
update auf 1.1.1 ist nicht dein ernst

**Comment by Plenium-ui** [comment]
Hi, ich würde das Problem gern nochmal aufmachen, da für mich hier keine Lösung zu finden ist.

Ich nutzt auch den MiJia Lichtsensor von Xiaomi. Koppelung mit einem CR2531 Zigbee-Stick über den Zigbee-Adapter (v 1.3.1) klappt sofort, jedoch wurde der Sensor nicht konfiguriert:
![Bildschirmfoto 2021-01-08 um 09 59 06](https://user-images.githubusercontent.com/46446009/103995614-045d4680-5199-11eb-96d4-c88dbf967ac0.png)

**Comment by Bibo13** [comment]
> 
> 
> update auf 1.1.1 ist nicht dein ernst

Warum wo war damals im Mai das Problem? Sie haben doch selbst vorgeschlagen diese Version zu installieren. Oder she ich das Falsch?

**Comment by Plenium-ui** [comment]
@Bibo13  klappt es inzwischen bei dir?

**Comment by Bibo13** [comment]
> 
> 
> @Bibo13 klappt es inzwischen bei dir?

Nein. Ich bin mittlerweile auch auf 1.3.1  Keine Verbesserung. Aber auch nicht lebensnotwendig. Der Sonsor funktioniert trotz Warnung.

**Comment by Plenium-ui** [comment]
> > @Bibo13 klappt es inzwischen bei dir?
> 
> Nein. Ich bin mittlerweile auch auf 1.3.1 Keine Verbesserung. Aber auch nicht lebensnotwendig. Der Sonsor funktioniert trotz Warnung.

Echt? Bei mir wird keine Brightness angezeigt:
![Bildschirmfoto 2021-01-08 um 10 33 15](https://user-images.githubusercontent.com/46446009/103999296-ff9a9180-519c-11eb-8ed3-15eaa2bc9374.png)

**Comment by JimmyBondi** [comment]
Ich habe drei Stück davon im Einsatz. Weder mit CC2531 noch mit CC2538 hatte ich Probleme damit.
Bin aktuell auf 1.3.1, aber auch mit älteren Versionen, gab es keine Schwierigkeiten.

**Comment by Bibo13** [comment]
![image](https://user-images.githubusercontent.com/45422390/103999619-6a4bcd00-519d-11eb-9ff3-e9d8daa2bd2c.png)
Kein Problem zu sehen. Ich habe auch 3 Stück. Sie zicken nur beim Start von Zigbee. Jeder gibt jeweils 5 Warnungen aus. Angeblich nicht konfigurierbar.

**Comment by Plenium-ui** [comment]
Habs mit Hilfe hinbekommen. Neustart > Soft-Reset > Neustart -des Zigbee-Adapter und nun geht es.
