### ISSUE TITLE
Add support for Gledopto GL-W-003

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#638]
http://www.gledopto.cn/pd.jsp?id=36 

I ordered one. It should arrive in a month. Then I can supply data to the device. What information is needed?

**Comment by Sacred-Shadow** [comment]
The best thing to do is here:
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html 

If the device support is in there, we can go on here.

**Comment by ldittmar81** [comment]
Ok... I will wait till the remote is here and then try to add it.

**Comment by SoulOnFire** [comment]
> Ok... I will wait till the remote is here and then try to add it.

@ldittmar81  Did you made any progress on this?
