### ISSUE TITLE
Nice to have: short description while mouse over Icon's

### ISSUE THREAD

**Issue by Pendora2017** [ioBroker/ioBroker.zigbee#639]
Could you please add some short description on this icons for mouse over?

![Screenshot_2020-05-21 instances - ioBroker](https://user-images.githubusercontent.com/28994273/82557736-93ffa780-9b6c-11ea-9ed8-157377e5721d.jpg)

**Comment by allofmex** [comment]
This would be a nice (and simple) project for someones very-first OpenSource-Pull-Request ;-) ;-)

**Comment by ElRakiti** [comment]
I might even try to add these descriptions. My problem is: I cannot find a good explanation anywhere. I'm wondering myself what these icons excatly stand for (e.g. the numbers of the link qualitity etc.). Am I just blind or is this really nowhere documented?

Thanks!
