### ISSUE TITLE
extPanID: doesn't applied from settings

### ISSUE THREAD

**Issue by sacculus** [ioBroker/ioBroker.zigbee#643]
Hi
I have a problem with extpanid value - I've defined my own value on settings page, but it not applied to controller when it starts.
I use TI cc1352 controller, node v10.19.0, IOB.admin 4.0.10 and iobroker.zigbee 1.0.4

What I see in log when adapter starts
`
zigbee.0 | 2020-05-26 17:07:28.341 | debug | (7720) Zigbee network parameters: {"panID":5114,"extendedPanID":"0xdddddddddddddddd","channel":25}
-- | -- | -- | --
zigbee.0 | 2020-05-26 17:07:28.328 | info | (7720) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20200417}}
zigbee.0 | 2020-05-26 17:07:28.325 | debug | (7720) zigbee-herdsman started
`

**Comment by arteck** [comment]
take the version from git
