### ISSUE TITLE
Osram Smart Plug Outdoor

### ISSUE THREAD

**Issue by MarkusE27** [ioBroker/ioBroker.zigbee#644]
Hello all,

just a question:
Is the outdoor-variant of the Osram Smart Plug also supported? I don´t find it in the list of supported devices, only the indoor variant.

Best regards
Markus

**Comment by Sacred-Shadow** [comment]
Welches Model ist das?
Das hier?
------------------------
Which model is it?
This one?

![grafik](https://user-images.githubusercontent.com/61997661/83075660-87031c80-a074-11ea-8f1d-b61950547aca.png)

**Comment by MarkusE27** [comment]
Yes, exactly

**Comment by Sacred-Shadow** [comment]
Then please take a look here:
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

If the device is supported there, we can also support it quickly here.

**Comment by arteck** [comment]
> 
> 
> Then please take a look here:
> https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
> 
> If the device is supported there, we can also support it quickly here.

then. do it..
