### ISSUE TITLE
bad link quality in map view

### ISSUE THREAD

**Issue by ac-bra** [ioBroker/ioBroker.zigbee#648]
Hi,

I'm using a CC2531 stick incl. some Xiaomi devices and as routers some Osram smart plugs. No matter how close the devices to the coordinator are it always shows a very bad link quality which I guess is just a wrong representation. The distance between the ioBroker/CC2531 stick and the Osram plug is 3 m with clear sight.

Is this a common issue?

<img width="645" alt="Screenshot 2020-06-04 at 14 55 28" src="https://user-images.githubusercontent.com/58888538/83759572-08aa0a00-a674-11ea-9b96-20be4a6b2b90.png">

**Comment by schadis** [comment]
my osram plugs also have bad connection like yours. I was thinking about changing the antenne in them. my contact sensor is about 30 cm form the plug at the same spot in the same room and is connected with a link quality of 50 to the coordinator and the blug has a link quality with 5-10 (changes when i go there with my smartphone)
