### ISSUE TITLE
New coverage property for each sensor/device

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.zigbee#65]
According to the network map there are connections and also the number, which display how good the connection ist.
Can this be also displayed for each zigbee device? Perhaps as new state "coverage"?
Then this can be used to determine if a device is reachable or not.
Or a direct property "reachable", iperhaps from the stick or determined by coverage?

**Comment by cimba007** [comment]
Would like to check this state also. My current map is totally messed up and just plain wrong ...

**Comment by allofmex** [comment]
The network map was changed recently. It has much more details than before. Hope this meets your wishes.

A state "reachable" would be difficult. We have it for routers, but enddevices are tricky. Many just send data on key press and do rarely respond to polls. No chance for adapter to know if a device is not reachable or just sleeping. 
(You may use state `link_quality` and its `last_updated` property to check if device was active recently. But the timings would be device specific)
