### ISSUE TITLE
Please add Tuya Scene Switch TS0041

### ISSUE THREAD

**Issue by huk13** [ioBroker/ioBroker.zigbee#651]
**error | (14976) Device 0xec1bbdfffe79e066 "TS0041" not described in statesMapping**

TS0041 and TS0042 are available for zigbee2mqtt.
Tile: 
![image](https://user-images.githubusercontent.com/53121010/83900193-fb674b00-a759-11ea-9d98-2d24ab63f877.png)
Device Information:
![image](https://user-images.githubusercontent.com/53121010/83938846-563f8780-a7d8-11ea-944a-dc4cc9cbacff.png)
Thank you and regards

**Comment by ospectreo** [comment]
Same error TS0043

**Comment by Kuehni84** [comment]
Implemented right now?!
