### ISSUE TITLE
Mega23M12, Please report this to the developer.

### ISSUE THREAD

**Issue by FredF63** [ioBroker/ioBroker.zigbee#654]
Adapter Version: 1.1.1
Warnmeldung:
zigbee.0 (15675) State value to set is invalid for zigbee.0.00212effff032cb1.color: The state contains the forbidden properties x, y!
zigbee.0 (15675) This value will not be set in future versions. Please report this to the developer.
Gerät:
`model:Mega23M12
vendor:Dresden Elektronik
description:ZigBee Light Link wireless electronic ballast
supports:on/off, brightness, color temperature, color xy
model:FLS-PP3
type:Router
nwk:36736
manuf id:4405
manufacturer:dresden elektronik
power:Mains (single phase)
app version:2
hard version:1
zcl version:1
stack version:3
date code:20180517
build:0214.201000EB
interviewed:true
configured:false
endpoint:10
profile:49246
input clusters:genBasic (0)
touchlink (4096)
genGroups (4)
genIdentify (3)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
lightingColorCtrl (768)
64718
output clusters:genOta (25)
endpoint:11
profile:49246
input clusters:genBasic (0)
touchlink (4096)
genGroups (4)
genIdentify (3)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)`

**Comment by modmax** [comment]
Duplicate to #607
