### ISSUE TITLE
Aqara Vibration Sensor

### ISSUE THREAD

**Issue by Joschi11** [ioBroker/ioBroker.zigbee#66]
I would like to use the Aqara vibration sensor with the Zigbee adapter. Paarenb in the setting of the adapter works, but it will be displayed as "Unknown" and no objects will be created.
Please, please, I could do so much with the sensor.
Greetings Joschi

**Comment by n3roGit** [comment]
+1

**Comment by plbartek89** [comment]
https://github.com/Koenkk/zigbee2mqtt  support it allready

**Comment by nisiode** [comment]
sensor is listed as supported device, but still the object is unknown after pairing.
is this sensor supported?

**Comment by plbartek89** [comment]
i installed git version 0.8.0a still 
undefined
00158d0002a91ead

**Comment by kirovilya** [comment]
@plbartek89 after install from github, you need to upload admin files (press button on adapter card or run command)

**Comment by plbartek89** [comment]
@kirovilya https://gyazo.com/39eb2994ea9c0ed38ac37747a79b0ea2

**Comment by kirovilya** [comment]
@plbartek89 Did you upload files after install?
![image](https://user-images.githubusercontent.com/8360230/47934427-4965fe00-dee8-11e8-94d5-254289ba6299.png)

**Comment by plbartek89** [comment]
I really dont know whats the problem.

> 

zigbee.0 | 2018-11-03 14:48:59.032 | info | new dev 0x00158d0002a91ead 14071 undefined
-- | -- | -- | --
zigbee.0 | 2018-11-03 14:47:39.059 | info | Zigbee: allowing new devices to join.
zigbee.0 | 2018-11-03 14:47:36.745 | info | List of ports:  [{"comName":"/dev/ttyACM0"},{"comName":"/dev/ttyS2"},{"comName":"/dev/ttyS3"},{"comName":"/dev/ttyS0"},{"comName":"/dev/ttyS1"}]
zigbee.0 | 2018-11-03 14:47:06.794 | info | List of ports:  [{"comName":"/dev/ttyACM0"},{"comName":"/dev/ttyS2"},{"comName":"/dev/ttyS3"},{"comName":"/dev/ttyS0"},{"comName":"/dev/ttyS1"}]
zigbee.0 | 2018-11-03 14:46:57.316 | info | (0x00158d000238eb2b): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
zigbee.0 | 2018-11-03 14:46:57.315 | info | (0x00158d0002132fc6): WXKG11LM - Xiaomi Aqara wireless switch (EndDevice)
zigbee.0 | 2018-11-03 14:46:57.315 | info | (0x00158d00023f02e6): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2018-11-03 14:46:57.314 | info | (0x00158d000232519f): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
zigbee.0 | 2018-11-03 14:46:57.307 | info | (0x00158d00020b55a4): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
zigbee.0 | 2018-11-03 14:46:57.243 | info | zigbee-shepherd ready. version: 2.6.3 rev 20180507
zigbee.0 | 2018-11-03 14:46:57.205 | info | zigbee-shepherd started!
zigbee.0 | 2018-11-03 14:46:54.684 | info | Start on port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0012013C6C-if00 with panID 6754 channel 11
zigbee.0 | 2018-11-03 14:46:54.659 | info | starting. Version 0.8.0-a in /opt/iobroker/node_modules/iobroker.zigbee, node: v6.14.4
host.IObroker | 2018-11-03 14:46:52.222 | info | instance system.adapter.zigbee.0 started with pid 922
host.IObroker | 2018-11-03 14:46:49.776 | info | instance system.adapter.zigbee.0 terminated with code 0 (OK)
zigbee.0 | 2018-11-03 14:46:49.712 | info | terminating
host.IObroker | 2018-11-03 14:46:49.698 | info | stopInstance system.adapter.zigbee.0 killing pid 912
host.IObroker | 2018-11-03 14:46:49.697 | info | stopInstance system.adapter.zigbee.0
host.IObroker | 2018-11-03 14:46:49.696 | info | object change system.adapter.zigbee.0
zigbee.0 | 2018-11-03 14:46:33.936 | error | Serial port not selected! Go to settings page.
zigbee.0 | 2018-11-03 14:46:33.911 | info | starting. Version 0.8.0-a in /opt/iobroker/node_modules/iobroker.zigbee, node: v6.14.4
iobroker | 2018-11-03 14:46:29.818 | info | exit 0
iobroker | 2018-11-03 14:46:29.746 | info | host.IObroker object system.adapter.zigbee.0 created
host.IObroker | 2018-11-03 14:46:29.734 | info | instance system.adapter.zigbee.0 started with pid 912
host.IObroker | 2018-11-03 14:46:29.708 | info | object change system.adapter.zigbee.0
iobroker | 2018-11-03 14:46:29.660 | info | host.IObroker object system.adapter.zigbee.0.alive created
iobroker | 2018-11-03 14:46:29.620 | info | host.IObroker object system.adapter.zigbee.0.connected created
iobroker | 2018-11-03 14:46:29.580 | info | host.IObroker object system.adapter.zigbee.0.memHeapUsed created
iobroker | 2018-11-03 14:46:29.543 | info | host.IObroker object system.adapter.zigbee.0.memHeapTotal created
iobroker | 2018-11-03 14:46:29.501 | info | host.IObroker object system.adapter.zigbee.0.memRss created
iobroker | 2018-11-03 14:46:29.456 | info | host.IObroker object system.adapter.zigbee.0.uptime created
iobroker | 2018-11-03 14:46:29.416 | info | host.IObroker object system.adapter.zigbee.0.inputCount created
iobroker | 2018-11-03 14:46:29.376 | info | host.IObroker object system.adapter.zigbee.0.outputCount created
iobroker | 2018-11-03 14:46:29.338 | info | host.IObroker object zigbee.0.info created
iobroker | 2018-11-03 14:46:29.297 | info | host.IObroker object zigbee.0.info.connection created
iobroker | 2018-11-03 14:46:29.260 | info | host.IObroker object zigbee.0.info.pairingMode created
iobroker | 2018-11-03 14:46:29.225 | info | host.IObroker object zigbee.0.info.pairingCountdown created
iobroker | 2018-11-03 14:46:29.180 | info | host.IObroker object zigbee.0.info.pairingMessage created
iobroker | 2018-11-03 14:46:29.133 | info | host.IObroker create instance zigbee
iobroker | 2018-11-03 14:46:27.353 | info | add zigbee  --host IObroker
iobroker | 2018-11-03 14:46:12.059 | info | exit 0
iobroker | 2018-11-03 14:46:11.892 | info | upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/admin.js admin.js application/javascript
iobroker | 2018-11-03 14:46:11.829 | info | upload [1] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/de/translations.json  i18n/de/translations.json application/json
iobroker | 2018-11-03 14:46:11.768 | info | upload [2] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/en/translations.json  i18n/en/translations.json application/json
iobroker | 2018-11-03 14:46:11.702 | info | upload [3] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/es/translations.json  i18n/es/translations.json application/json
iobroker | 2018-11-03 14:46:11.634 | info | upload [4] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/fr/translations.json  i18n/fr/translations.json application/json
iobroker | 2018-11-03 14:46:11.563 | info | upload [5] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/it/translations.json  i18n/it/translations.json application/json
iobroker | 2018-11-03 14:46:11.485 | info | upload [6] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/nl/translations.json  i18n/nl/translations.json application/json
iobroker | 2018-11-03 14:46:11.423 | info | upload [7] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/pt/translations.json  i18n/pt/translations.json application/json
iobroker | 2018-11-03 14:46:11.358 | info | upload [8] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/ru/translations.json  i18n/ru/translations.json application/json
iobroker | 2018-11-03 14:46:11.273 | info | upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86plug.png img/86plug.png image/png
iobroker | 2018-11-03 14:46:11.199 | info | upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw1.png img/86sw1.png image/png
iobroker | 2018-11-03 14:46:11.127 | info | upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw2.png img/86sw2.png image/png
iobroker | 2018-11-03 14:46:11.053 | info | upload [12] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/img/FLOALT.panel.WS.png  img/FLOALT.panel.WS.png image/png
iobroker | 2018-11-03 14:46:10.952 | info | upload [13] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/img/TRADFRI.bulb.E27.png  img/TRADFRI.bulb.E27.png image/png
iobroker | 2018-11-03 14:46:10.846 | info | upload [14] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/img/TRADFRI.remote.control.png  img/TRADFRI.remote.control.png image/png
iobroker | 2018-11-03 14:46:10.774 | info | upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara.switch.png img/aqara.switch.png image/png
iobroker | 2018-11-03 14:46:10.699 | info | upload [16] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_numan_body_sensor.png  img/aqara_numan_body_sensor.png image/png
iobroker | 2018-11-03 14:46:10.622 | info | upload [17] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_temperature_sensor.png  img/aqara_temperature_sensor.png image/png
iobroker | 2018-11-03 14:46:10.550 | info | upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/battery_p.png img/battery_p.png image/png
iobroker | 2018-11-03 14:46:10.479 | info | upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/battery_v.png img/battery_v.png image/png
iobroker | 2018-11-03 14:46:10.404 | info | upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/contact.png img/contact.png image/png
iobroker | 2018-11-03 14:46:09.731 | info | upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ge_bulb.png img/ge_bulb.png image/png
iobroker | 2018-11-03 14:46:09.053 | info | upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/jiawen.png img/jiawen.png image/png
iobroker | 2018-11-03 14:46:08.283 | info | upload [50] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/img/osram_lightify.png  img/osram_lightify.png image/png
iobroker | 2018-11-03 14:46:07.533 | info | upload [60] zigbee.admin  /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_white.png  img/philips_hue_white.png image/png
iobroker | 2018-11-03 14:46:06.809 | info | upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/sylvania_br.png img/sylvania_br.png image/png
iobroker | 2018-11-03 14:46:06.162 | info | got /opt/iobroker/node_modules/iobroker.zigbee/admin
iobroker | 2018-11-03 14:46:04.454 | info | upload zigbee

>

**Comment by kirovilya** [comment]
added in 0.8.0 version
