### ISSUE TITLE
Sensors do not use some plugs

### ISSUE THREAD

**Issue by ChristianGrieger** [ioBroker/ioBroker.zigbee#660]
Hey there,

I have noticed that some sensors do not take the plugs which are definitely much much closer to them. Or they not even use them. I added them later to the network but did a complete hard-reset before.

Do i need to flash the stick again so it forget about the pairing or is the hard-reset all i need?

How can i tell all sensors to search for new devices and use them instead of the ones they are paired with. 

I am sorry but i do not full understand how the connection works and when? & and if? and how? they repair and if they switch automated?

I really hope to get some info about this :)

![network](https://user-images.githubusercontent.com/8712219/84521652-a1283600-acd5-11ea-8a66-aabf89563db9.jpg)

Thank you!

Chris

**Comment by allofmex** [comment]
As mentioned in multiple issues already: The devices choose there parent router by themselves. There is no way in Zigbee to point a device to a specific route. Devices may also change there parent from time to time. But this cannot be triggered as well.
