### ISSUE TITLE
found light bulbs, what now?

### ISSUE THREAD

**Issue by downspath** [ioBroker/ioBroker.zigbee#661]
i have installed ioBroker and added the zigbee adapter. i found all 3 light bulbs. but how do i controll them now? i keep googling. bit it is impossible to find something. (i tryed to connect ioBroker to alexa, but this doesnt work, is there another way?)

**Comment by downspath** [comment]
I managed to edit the color trough the "objects" tab. so i am good for now.

is therr another way to change the colors? its allot ofclicks to get to the point where i can change the colors.

**Comment by allofmex** [comment]
> I managed to edit the color trough the "objects" tab. so i am good for now.
is therr another way to change the colors? its allot ofclicks to get to the point where i can change the colors.

After you did the first step (`objects`), the next should be to learn about `Visualisation` adapter. Then you have it... 
(And after this: `Scripts`)
