### ISSUE TITLE
unhandled promise rejection: Cannot access 'syncStateList' before initialization

### ISSUE THREAD

**Issue by seankmg** [ioBroker/ioBroker.zigbee#663]
`

zigbee.0 | 2020-06-13 22:02:28.492 | info | (1549) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
zigbee.0 | 2020-06-13 22:02:28.490 | info | (1549) terminating
zigbee.0 | 2020-06-13 22:02:28.391 | info | (1549) Zigbee: disabling joining new devices.
zigbee.0 | 2020-06-13 22:02:28.387 | info | (1549) cleaned everything up...
zigbee.0 | 2020-06-13 22:02:28.384 | error | (1549) ReferenceError: Cannot access 'syncStateList' before initialization at /opt/iobroker/node_modules/iobroker.zigbee/main.js:207:63 at Array.forEach (<anonymous>) at Zigbee.publishFrom
zigbee.0 | 2020-06-13 22:02:28.383 | error | (1549) unhandled promise rejection: Cannot access 'syncStateList' before initialization
zigbee.0 | 2020-06-13 22:02:28.381 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2020-06-13 22:02:27.089 | info | (1549) Zigbee started

`

Using Adapter CC2531

This happens, when i try to update object "transitionDuration" of my Philips Hue device by using a script like this in my Homekit Adapter:

var result = value;
if (result <= 10){
return 0;
} else if (result <= 20 && result > 10){
return 1;
} else if (result <= 40 && result > 20) {
return 2;
} else if (result <= 60 && result > 40) {
return 3;
} else if (result <= 80 && result > 60) {
return 4;
} else if (result <= 100 && result > 80) {
return 5;
} else if (result <= 1) {
return 0;
} else {
return 0;
}

**Comment by allofmex** [comment]
As the error says:
>  Cannot access 'syncStateList' before initialization 

You may need to wait a bit until Zigbee adapter is initialized, before you fire your script.

**Comment by BenjaminHae** [comment]
Same here! Happened a long time after the adapter was initialized.
Started when I upgraded to js-controller 3.1

**Comment by BenjaminHae** [comment]
Also happens every time I set `transition_time` in a script.
Explicitly waited for "Zigbee started" in the logs.

**Comment by BenjaminHae** [comment]
I've looked into it for a bit. It seems as if the `syncStateList` variable is accessed before it is declared.

This is fixed in a recent commit 627ac4b in the master branch so it should be working once the new version is pushed to npm.

**Comment by kirovilya** [comment]
there are many changes in the current version on github. the next version will be number 1.2
you can try to install the version from github and use

**Comment by BenjaminHae** [comment]
It works in version 1.1.1 so I suggest closing this issue.
