### ISSUE TITLE
Xiaomi smoke detector missing sensitivity

### ISSUE THREAD

**Issue by skrabadiloseidon** [ioBroker/ioBroker.zigbee#664]
Please add a option to set the sensitivity.

I know this is a duplicate to #456, but a smoke sensor is a important device that can safe lives, so configuring it properly is essential.

See https://www.zigbee2mqtt.io/devices/JTYJ-GD-01LM_BW.html (Sensitivity)

**Comment by baerengraben** [comment]
Thumbs up for this one. Additionally please add the self-test option too. :+1:

**Comment by Apollon77** [comment]
@baerengraben Please add thumps up to the initial port. And "sneaking in more stuff in an existing issue also makes not that much sense ... please create an extra one

**Comment by kirovilya** [comment]
try to update from github and check

**Comment by skrabadiloseidon** [comment]
selftest is working and sensitivity seems too (has confirmed state in objects).
thank you
