### ISSUE TITLE
Typo in Extended PAN ID

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.zigbee#668]
While fighting with my Zigbee installation I was trying to get the network working with the same settings I have in ioBroker, but with koenkk/zigbee2mqtt (on docker).

I found after restarting ioBroker after running my zigbee2mqtt tests the CC2351 stick would flash its LEDs while starting the adapter. By running koenkk/zigbee2mqtt with different configurations I found that this is always the case when some config changed (I tried changing PAN ID and the network key in koenkk/zigbee2mqtt's `configuration.yaml`).

While I tried my best to reproduce my non-default ioBroker settings with koenkk/zigbee2mqtt's configuration.yaml the CC2351 always decided that it is time to reprogram after I changed from koenkk/zigbee2mqtt to ioBroker and vice versa.

I dug further into ioBroker.zigbee and found that the Extended PAN ID that you configure on the ioBroker UI is actually never passed to zigbee-herdsman.

zigbee-herdsman expects [`extendedPanID`](https://github.com/Koenkk/zigbee-herdsman/blob/49fee25722daa2ec5d402e8059fc77d1fe096f50/src/adapter/tstype.ts#L3), but ioBroker.zigbee passes [`extenedPanID`](https://github.com/ioBroker/ioBroker.zigbee/blob/d38c1d6133233f9a35a59435dc7ca8b2ddd05543/lib/zigbeecontroller.js#L49).

I guess this will be hard to fix. If the typo is corrected people like me with non-default Extended PAN IDs will probably [have to repair all their devices](https://www.zigbee2mqtt.io/information/FAQ.html#requires-repairing).

**Comment by kirovilya** [comment]
Oh, you're right. Thank!
I did not notice these changes https://github.com/Koenkk/zigbee-herdsman/commit/da731e5ce7b339839dc140e6471fbc6babe5a54f

**Comment by kirovilya** [comment]
Yes, now launching requires re-pairing for those who use extPanId other than default https://github.com/Koenkk/zigbee-herdsman/blob/master/src/controller/controller.ts#L38
[0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD]
[221, 221, 221, 221, 221, 221, 221, 221]

**Comment by kirovilya** [comment]
@agross Thanks for the problem found.
I tried to solve it. Do you think such a solution is suitable? Should not break existing networks.
