### ISSUE TITLE
Wrong battery status for many Aqara smart home devices

### ISSUE THREAD

**Issue by ChristianGrieger** [ioBroker/ioBroker.zigbee#673]
Ich habe mir eine Sprachausgabe gebastelt für den Batteriestatus aller Geräte und alle Fensterkontakte, Bewegungsmelder und Wassersensoren (die,die ich besitze), haben einen Wert von 100%. Nur der Multisensor scheint den Wert richtig anzugeben.

Scheinbar hat noch ein User das Problem festgestellt.

--

I have made a voice output for the battery status of all devices and all window contacts, motion detectors and water sensors (the ones I own) and all values for the battery are 100%. Only the multisensor seems to give the correct value.

It seems that another user has detected the problem.

https://forum.iobroker.net/topic/32805/aqara-%C3%BCber-zigbee-stick-zeigt-falschen-batterie-wert/2

**Comment by Sacred-Shadow** [comment]
Welche Geräte hast du denn überhaupt?
Gibt es bei diesen Geräten in den Objekten entsprechende Punkte?

**Comment by ChristianGrieger** [comment]
Fensterkontakte, Bewegungsmelder, Wassersensoren und bald Relays.

Vielleicht sollte ich noch mal alles Bei anlernen? Hat sonst keiner das Problem?

**Comment by Sacred-Shadow** [comment]
Es fehlt immer noch genau welche .. die wenigsten Geräte die ich kenne, haben nen Datenpunkt für die Batterie. ;)

**Comment by arteck** [comment]
nochmal und zum Zigtausendsten mal

die Werte bekommen wir so vom coverter und wir werden diese nicht weiter aufbröseln, verschönern oder anpassen..

ich führe die Diskussion nicht noch einmal
