### ISSUE TITLE
Conbee 2 don^'t work?!

### ISSUE THREAD

**Issue by ChrisVonFrosta** [ioBroker/ioBroker.zigbee#674]
maybe the stick (conbee 2) works but it has no effect in my system.
The stick is is plugged in a rPi3 as Multihost Slave. The Multihost master is a RPi 4.

i set the right Port and adapter starts with some info output.
Put paring does not find any device.
![grafik](https://user-images.githubusercontent.com/16272493/85567600-4c6bb000-b631-11ea-9869-a8de3bbe1e6d.png)
![grafik](https://user-images.githubusercontent.com/16272493/85567859-7f15a880-b631-11ea-885e-4dfb6b05fa79.png)
![grafik](https://user-images.githubusercontent.com/16272493/85567903-88067a00-b631-11ea-9897-c7cbb09dd652.png)

**Comment by Sacred-Shadow** [comment]
Stimmt der COM Anschlussname?

**Comment by ChrisVonFrosta** [comment]
er Sollte eigentlich gestimmt haben, aber da war etwas Wirrwar bei mir aufgekommen.
Nach einem Neustart, ging es dann.

Jedoch wird das Danalock nicht wie gewünscht angelernt:
![grafik](https://user-images.githubusercontent.com/16272493/85626119-d2f1b300-b66c-11ea-8ebb-58ad0002d0dd.png)
Es sind zwar Objekte erwschienen aber die aktualisieren sich nicht und lassen auch keine Steuerung zu.

Mit dem CCxx Adapter klappte zuvor problemlos und dann anschließend aber auch erst wieder nachm dritten Pairing Versuch. Zuvor wurden die Objekte zwar fast zuverlässig angelegt aber wurden nicht upgaded wenn das Schloss anders gesteuert wurde oder steuerten das Schloss nicht, wenn man das Objekt manipulierte...

Ich wundere mich aber auch jedesmal über die lange Zeitdauer die die Zigbee Geräte beim Pairen benötigen. Beim Danalock kommt es nicht selten vor, dass ich ein zweites oder drittes mal das Pairing anstoßen muss und manchmal muss ich trotzdem im Adapter einen zweiten Pairingdurchlauf starten, weil sich keine Gerät meldete...
Bei Zwave dauert so ein Pariningvorgang 1 Sekunde.
