### ISSUE TITLE
please add Tuya TS0121 UK/EU Plug 

### ISSUE THREAD

**Issue by juamiso** [ioBroker/ioBroker.zigbee#675]
[https://www.zigbee2mqtt.io/devices/TS0121.html](https://www.zigbee2mqtt.io/devices/TS0121.html)

Already supported in mqtt.io, should be an easy port

**Comment by juamiso** [comment]
Added this 
```
    {
        vendor: 'Tuya',
        models: ['TS0121'],
        icon: 'img/innr_plug.png',
        states: [states.state],
    },
```

into devices.js and the switch is working. However power measurement is missing.

**Comment by bennatzen** [comment]
Please support this device with PowerMetering. Ive bought some devices as well.

**Comment by juamiso** [comment]
looks like it does not have power metering at all, according to another thread. This is a shame, I also bought two units just because of this feature....

**Comment by bingo6** [comment]
Meanwhile the device was added to the dev branch at igbee2mqtt. See: https://github.com/Koenkk/zigbee2mqtt/issues/3812. I tried to manually move the newer devices.js from zigbee-herdsmann-converts to iobroker, but unfortunately the plugin did not start after that. I'm now waiting to see if the device will be officially updated in the future and in the meantime try to use zigbee2mqtt directly or switch to Hass.Io.

**Comment by Shadesh** [comment]
Looks like it's done, even with power measuring. https://github.com/ioBroker/ioBroker.zigbee/commit/0faae2b7b9eb597124c3582fc329749801fbdac1

**Comment by bingo6** [comment]
> Looks like it's done, even with power measuring. [0faae2b](https://github.com/ioBroker/ioBroker.zigbee/commit/0faae2b7b9eb597124c3582fc329749801fbdac1)

Thank you! And thank you @arteck. I have try it and its works very well.

**Comment by olylak** [comment]
I have BlitzWolf Smart Socket BW-SHP13. Can anyone tell me how to connect (pair) it to zigbee2mqtt?
