### ISSUE TITLE
make port define by ID possible again

### ISSUE THREAD

**Issue by umbm** [ioBroker/ioBroker.zigbee#68]
Til v0.7.1 I defined COM port by ID to get sure it's correct after reboot and/or add another USB device to server. 

With update 0.7.3 I can't setup the port manually as before (like: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0Xxxxx4B00120144AF-if00), only get to choose one port from dropdown list.
In worst case the port changes for cc2531 an it does not work without re-configuration.

**Comment by kirovilya** [comment]
Check out work with version 0.7.5
