### ISSUE TITLE
Problem in installation adapter Zigbee in IOBROKER ERROR host.80d539225807

### ISSUE THREAD

**Issue by cardco** [ioBroker/ioBroker.zigbee#682]
When i try install adapter Zigbee in IOBroker I get:

$ ./iobroker url "github.com/ioBroker/ioBroker.zigbee"
install github.com/ioBroker/ioBroker.zigbee
NPM version: 6.14.5
npm install github.com/ioBroker/ioBroker.zigbee --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code ENOLOCAL
npm ERR! Could not install from "github.com/ioBroker/ioBroker.zigbee" as it does not contain a package.json file.
npm ERR! A complete log of this run can be found in:npm ERR!     /opt/iobroker/.npm/_logs/2020-07-01T00_15_24_482Z-debug.log
ERROR: host.80d539225807 Cannot install github.com/ioBroker/ioBroker.zigbee: 1
ERROR: process exited with code 25

**Comment by arteck** [comment]
which system ??
