### ISSUE TITLE
please add: OSRAM Switch 4x EU-LIGHTIFY

### ISSUE THREAD

**Issue by Arneee1** [ioBroker/ioBroker.zigbee#686]
Hey there,

ist there a way to add the "OSRAM Smart+ 4 Switch" into the repo?

[https://www.amazon.de/Osram-Switch-Lichtschalter-Fernbedienung-Erweiterung/dp/B074PZLX2Y/ref=asc_df_B074PZLX2Y/?tag=googshopde-21&linkCode=df0&hvadid=231877237116&hvpos=&hvnetw=g&hvrand=15357706056070861044&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1004507&hvtargid=pla-420390443190&psc=1&th=1&psc=1](url)

    model:4058075816459
    vendor:OSRAM
    description:Smart+ switch
    supports:action

    model:Switch 4x EU-LIGHTIFY
    type:EndDevice
    nwk:10909
    manuf id:4364
    manufacturer:OSRAM
    power:Battery
    app version:1
    hard version:1
    zcl version:1
    stack version:0
    date code:201904022126370
    build:e.1.0.0M
    interviewed:true
    configured:true

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genPowerCfg (1)
    genPollCtrl (32)
    touchlink (4096)
    64768
    output clusters:genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    genOta (25)
    lightingColorCtrl (768)
    touchlink (4096)

    endpoint:2
    profile:260
    input clusters:genBasic (0)
    touchlink (4096)
    64768
    output clusters:genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    lightingColorCtrl (768)
    touchlink (4096)

    endpoint:3
    profile:260
    input clusters:genBasic (0)
    touchlink (4096)
    64768
    output clusters:genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    lightingColorCtrl (768)
    touchlink (4096)

    endpoint:4
    profile:260
    input clusters:genBasic (0)
    touchlink (4096)
    64768
    output clusters:genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    lightingColorCtrl (768)
    touchlink (4096)

    endpoint:5
    profile:260
    input clusters:genBasic (0)
    touchlink (4096)
    64768
    output clusters:genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    lightingColorCtrl (768)
    touchlink (4096)

    endpoint:6
    profile:260
    input clusters:genBasic (0)
    touchlink (4096)
    64768
    output clusters:genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    lightingColorCtrl (768)
    touchlink (4096)

**Comment by arteck** [comment]
no sry.. and the other one (the little one with 3 buttons) also not..
we have big problems with the group comminication from this switch
