### ISSUE TITLE
Battery Percent and Volt no Number

### ISSUE THREAD

**Issue by der-eine** [ioBroker/ioBroker.zigbee#69]
Hello,
in version 0.7.3 is a bug with battery percent and volt. If no number is displayed, but "zero" in letters.

Many greetings

**Comment by arteck** [comment]
which devices ??

**Comment by arteck** [comment]
which Aqara Window Contact ?? pic plz

**Comment by kirovilya** [comment]
@der-eine  For newly connected devices, the battery comes within an hour.
