### ISSUE TITLE
hold Action for WXKG11LM

### ISSUE THREAD

**Issue by tipp88** [ioBroker/ioBroker.zigbee#699]
connecting WXKG11LM does not provide a datapoint for 'hold/long press' action. It only adds 'click' and 'double_click' + triple and quadruple click (which both are not supported by WXKG11LM switch from Aquara. The switch has three functions: click, double click, hold.

Zigbee is CC2531 with firmware "revision":20190608

![image](https://user-images.githubusercontent.com/68737433/88387237-5f011280-cdb2-11ea-9366-30a840b5660c.png)
![image](https://user-images.githubusercontent.com/68737433/88387329-822bc200-cdb2-11ea-9bf6-34f43655d80c.png)

**Comment by Shadesh** [comment]
Should be solved now.

**Comment by tipp88** [comment]
Thanks, but in which version, I don't see any new version released?

**Comment by kirovilya** [comment]
install from github. I plan to release a new release next week
