### ISSUE TITLE
upgrade 0.7.3

### ISSUE THREAD

**Issue by noah3112** [ioBroker/ioBroker.zigbee#70]
Unfortunately, the update does not work as desired. For me, the level remains at 0.7.1.

**Comment by arteck** [comment]
take my repo https://github.com/arteck/ioBroker.zigbee for test

**Comment by kirovilya** [comment]
what is wrong?

**Comment by arteck** [comment]
i think "zigbee-shepherd-converters": "2.0.47" is buggy

**Comment by kirovilya** [comment]
@noah3112 Check out work with version 0.7.5 please
