### ISSUE TITLE
Please add Paulmann remotecontrol and LED Panel Amaris

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/ioBroker.zigbee#704]
Please add the Paulmann Products RemoteControl and the LED Panel Amaris.

Both is already supported by the zigbee2mqtt project:

https://www.zigbee2mqtt.io/devices/798.09.html
https://www.zigbee2mqtt.io/devices/500.67.html

the data for the devices should be:

{
        zigbeeModel: ['371000002'],
        model: '798.09',
        vendor: 'Paulmann',
        description: 'LED panel Amaris 595x595mm 35W matt white',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
    },

    {
        zigbeeModel: ['RemoteControl '],
        model: '500.67',
        vendor: 'Paulmann',
        description: 'RGB remote control',
        supports: 'action',
        fromZigbee: [
            fz.command_on, fz.command_off, fz.command_toggle, fz.command_step,
            fz.command_move_to_color_temp, fz.command_move_to_color, fz.command_stop,
            fz.command_move, fz.command_color_loop_set, fz.command_ehanced_move_to_hue_and_saturation,
            fz.tint404011_scene,
        ],
        toZigbee: [],
    },

Thank you very much for your help and support :)

**Comment by 1rfsNet** [comment]
BTW: Also have the Paulmann Amaris Panel (60x60 and 120x30) and both are recognized as the same model.

**Comment by kirovilya** [comment]
Try to update adapter from github and check

**Comment by Hesse-Bub** [comment]
I can confirm , both are working now. Thank you very much :)
