### ISSUE TITLE
Fehlermeldung beim einbinden vom "Aquara Smart Plug"

### ISSUE THREAD

**Issue by Schimi1983** [ioBroker/ioBroker.zigbee#705]
Kann da jemand was mit anfangen?

`2020-07-29 19:32:33.691 - error: zigbee.0 (2076) Failed to configure 0x04cf8cdf3c79c1b2 lumi.plug.maeu01, attempt 1 (Error: Read 0x04cf8cdf3c79c1b2/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')`

nach dem anlernen ist das Gerät auch da und kann ein/aus geschaltet werden und zeigt einen Stromverbrauch (Watt) an

**Comment by Schimi1983** [comment]
ahso, ne zweiter SmartPlug (der gleiche) macht dies ohne Fehler.... in den Details unterscheiden sie sich nicht

**Comment by Shadesh** [comment]
Should be solved since: https://github.com/Shadesh/zigbee-herdsman-converters/commit/9b221029074cdd79ad4a8cad5afa2bac24c8ddf7

**Comment by Schimi1983** [comment]
Yes!! Great!!! :-)
