### ISSUE TITLE
Problem: Update datapoints from lights only when change via Zigbee adapter

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/ioBroker.zigbee#707]
I recognized an issue with updates of datapoints from lights.
They got only new values, when it was changed by the zigbee datpoint. It don't get the values from light automatical. 

For example if you have a direct connected remote, the zigbee adapter deosn't recognuze the status changes (for example state or brightness).

The same happens if the light is shortly powered off or cut from electricity, when it comes back it is turned of, but the state of the datapoint is still false and does not change.

** Update**
It is not only with ikea lights, it happens with every light. It seems like there is a problem with the reporting function.

**Comment by nob0dy80** [comment]
expected behavior in my eyes.
there can only be one ultimative master and this should be iobroker in that case.
connect your remote to iobroker (zigbee adapter) and not to the bulp and use scripts to handle this.

**Comment by Hesse-Bub** [comment]
> 
> 
> expected behavior in my eyes.
> there can only be one ultimative master and this should be iobroker in that case.
> connect your remote to iobroker (zigbee adapter) and not to the bulp and use scripts to handle this.

I'm not sure ... because regarding the documentation of binding (https://www.zigbee2mqtt.io/information/binding), there should be a reporting option, to get informed about changes. Dresden electronic has the same function included in deconz.

In my point of view this is a bug of iobroker.zigbee .... it also didn't get any change, if the bulp was cut from power and comes back for example with other brightness

**Comment by Hesse-Bub** [comment]
no one an idea?
