### ISSUE TITLE
Please implement OSRAM SMART+ GARDENPOLE Multicolor 

### ISSUE THREAD

**Issue by hawi1981** [ioBroker/ioBroker.zigbee#71]
As already described in the headline, please add the OSRAM SMART+ GARDENPOLE Multicolor

**Comment by arteck** [comment]
more information plz..

**Comment by ralfthiel** [comment]
What information do you need? Model No. of Osram Lightify Gardenpole is 4058075004993

**Comment by arteck** [comment]
i need the exactly name for .. as like 
![file](https://user-images.githubusercontent.com/6681528/46647732-05563680-cb92-11e8-8e80-8d59ec1324ee.jpg)

**Comment by hawi1981** [comment]
![instances - iobroker 2018-10-14 14-00-38](https://user-images.githubusercontent.com/43812894/46916361-aa6d7680-cfb9-11e8-93f6-0da749470730.png)

**Comment by hawi1981** [comment]
![objects - iobroker 2018-10-14 14-03-15](https://user-images.githubusercontent.com/43812894/46916371-edc7e500-cfb9-11e8-8381-3b7ec82903bb.png)

If you need more information, let me know

**Comment by arteck** [comment]
done
