### ISSUE TITLE
Error: Cannot find module 'zigbee-herdsman/node_modules/debug'

### ISSUE THREAD

**Issue by 150d** [ioBroker/ioBroker.zigbee#710]
Hi,

installing the version from Github (master) logs the following error:

Caught by controller[0]: internal/modules/cjs/loader.js:638
Caught by controller[0]: throw err;
Caught by controller[0]: ^
Caught by controller[0]: Error: Cannot find module 'zigbee-herdsman/node_modules/debug'
Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:8:15)
Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)

The release version v1.1.1 does not show this error.

Can this be fixed by installing some updated dependency?

Regards

**Comment by 150d** [comment]
Could someone please have a look at this issue? I'm currently unable to run the GitHub-version of the adapter because of this fault, and the release version (v1.1.1) can't pair any devices here (seperate issue reg. the ConBee stick, may be resolved in the GitHub version).

**Comment by kirovilya** [comment]
strange. Have you installed the adapter correctly, no errors?

**Comment by kirovilya** [comment]
try to update from github again

**Comment by 150d** [comment]
Great job! I just installed the Github-version again and now it starts without error.

Thank you!
