### ISSUE TITLE
Илья, добавьте пожалуйста freepad, известный также как пульт v2 от jager

### ISSUE THREAD

**Issue by SeleRom** [ioBroker/ioBroker.zigbee#714]
Будьте добры. Читал, что вы его приобрели себе. Спасибо за ваши труды.

**Comment by kirovilya** [comment]
Speak English for other users, please.
Try it, update the adapter from github

**Comment by SeleRom** [comment]
Many thanks. Freepad added. Works great. Works out all types of clicks. [Freepad firmware version 2.0.0.](https://github.com/diyruz/freepad/releases/tag/2.0.0) Please add for 12 and 20  buttons.
