### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/@serialport/parser-ready/-/parser-ready-8.0.6.tgz

### ISSUE THREAD

**Issue by he-so** [ioBroker/ioBroker.zigbee#715]
When installing the zigbee adapter on a freshly installed raspberry pi os, nodejs 10 and iobroker *, the installation fails with:

`
19687 warn optional SKIPPING OPTIONAL DEPENDENCY: rxjs@6.5.4 (node_modules/zigbee-herdsman/node_modules/rxjs):
19688 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/opt/iobroker/node_modules/.staging/rxjs-e2769b71'
19689 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
19689 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
19690 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@serialport/parser-ready/-/parser-ready-8.0.6.tgz
19690 verbose stack     at res.buffer.catch.then.body (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:114:15)
19690 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
19691 verbose statusCode 404
19692 verbose pkgid @serialport/parser-ready@8.0.6
19693 verbose cwd /opt/iobroker
19694 verbose Linux 4.19.118-v7+
19695 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.zigbee@1.0.4" "--loglevel" "error" "--prefix" "/opt/iobroker"
19696 verbose node v10.22.0
19697 verbose npm  v6.14.6
19698 error code E404
19699 error 404 Not Found - GET https://registry.npmjs.org/@serialport/parser-ready/-/parser-ready-8.0.6.tgz
19700 error 404
19701 error 404 '@serialport/parser-ready@8.0.6' is not in the npm registry.
19702 error 404 You should bug the author to publish it (or use the name yourself!)
19703 error 404 It was specified as a dependency of 'zigbee-herdsman'
19704 error 404 Note that you can also install from a
19705 error 404 tarball, folder, http url, or git url.
19706 verbose exit [ 1, true ]
`

* Followed the manuals:
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
curl -sL https://iobroker.net/install.sh | bash -

**Comment by kirovilya** [comment]
try to install iobroker.zigbee from github

**Comment by he-so** [comment]
Hi, unfortunately, it does not work either:

iobroker npm install https://github.com/ioBroker/ioBroker.zigbee/tarball/master --loglevel error --prefix "/opt/iobroker" 

> 

36394 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
36395 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
36395 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
36395 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
36395 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm
36396 verbose stack Error: @serialport/bindings@9.0.0 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
36396 verbose stack Exit status 1
36396 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
36396 verbose stack     at EventEmitter.emit (events.js:198:13)
36396 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
36396 verbose stack     at ChildProcess.emit (events.js:198:13)
36396 verbose stack     at maybeClose (internal/child_process.js:982:16)
36396 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
36397 verbose pkgid @serialport/bindings@9.0.0
36398 verbose cwd /opt/iobroker
36399 verbose Linux 4.19.118-v7+
36400 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "https://github.com/ioBroker/ioBroker.zigbee/tarball/master" "--loglevel" "error" "--prefix" "/opt/iobroker"
36401 verbose node v10.22.0
36402 verbose npm  v6.14.6
36403 error code ELIFECYCLE
36404 error errno 1
36405 error @serialport/bindings@9.0.0 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
36405 error Exit status 1
36406 error Failed at the @serialport/bindings@9.0.0 install script.
36406 error This is probably not a problem with npm. There is likely additional logging output above.
36407 verbose exit [ 1, true ]

**Comment by he-so** [comment]
I also tried it this way:

`$ ./iobroker url "https://github.com/ioBroker/ioBroker.zigbee" --debug`

> 
install https://github.com/ioBroker/ioBroker.zigbee/tarball/fe8611341638d4b61b7a290fd273fc84824abb8d
ERROR: /usr/lib/node_modules/npm/node_modules/ansi-regex/index.js:1SyntaxError: Invalid or unexpected token    at Module._compile (internal/modules/cjs/loader.js:723:23)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)    at Module.load (internal/modules/cjs/loader.js:653:32)    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)    at Function.Module._load (internal/modules/cjs/loader.js:585:3)    at Module.require (internal/modules/cjs/loader.js:692:17)    at require (internal/modules/cjs/helpers.js:25:18)    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/strip-ansi/index.js:2:17)    at Module._compile (internal/modules/cjs/loader.js:778:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)Error trying to check npm version: Error: Command failed: npm -v/usr/lib/node_modules/npm/node_modules/ansi-regex/index.js:1SyntaxError: Invalid or unexpected token    at Module._compile (internal/modules/cjs/loader.js:723:23)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)    at Module.load (internal/modules/cjs/loader.js:653:32)    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)    at Function.Module._load (internal/modules/cjs/loader.js:585:3)    at Module.require (internal/modules/cjs/loader.js:692:17)    at require (internal/modules/cjs/helpers.js:25:18)    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/strip-ansi/index.js:2:17)    at Module._compile (internal/modules/cjs/loader.js:778:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Aborting install because the npm version could not be checked!Please check that npm is installed correctly.Use "npm install -g npm@4" or "npm install -g npm@latest" to install a supported version.You need to make sure to repeat this step after installing an update to NodeJS and/or npm!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: process exited with code 30

**Comment by he-so** [comment]
It seems, this was an npm issue. After removing node and npm (sudo apt-get remove nodejs npm) and reinstalling the zigbee install runs better. :)

**Comment by nob0dy80** [comment]
@he-so 
when its done, close this issue .
