### ISSUE TITLE
Add Device Request: Hornbach FLAIR Viyu Smarte LED GU10/5W(50W) SKU 10011724

### ISSUE THREAD

**Issue by ivo443** [ioBroker/ioBroker.zigbee#716]
Hello everybody

The illuminant is extremely cheap and of high quality.
It would be a real alternative to Philips Hue GU10 lamps which are overpriced. Further Ikea offers no Tradfri GU10 lamps.

Device information:

model:VIYU-GU10-350-CCT-10011724
type:Router
nwk:15141
manuf id:4709
manufacturer:HORNBACH Baumarkt AG
power:Mains (single phase)
app version:1
hard version:1
zcl version:2
stack version:1
date code:20190127-27
build:2.7
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
lightingColorCtrl (768)
touchlink (4096)
output clusters:genOta (25)
endpoint:242
profile:41440
output clusters:greenPower (33)

Thank you very much.
Ivo

**Comment by nob0dy80** [comment]
Tradfri offers no GU10 ? You are so wrong.. and they even cost half of the hornbach gu10.
there you go:
https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-400-lm-kabellos-dimmbar-warmes-tageslicht-60420041/

**Comment by killakaktus** [comment]
Good to know , thanks.
The Viyu bulbs have white-tones - for whom it is important.

**Comment by nob0dy80** [comment]
yeah ikea too ...
https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-400-lm-kabellos-dimmbar-weissspektrum-90408603/

if you want support for a new led, just ask for it .. you dont need to use wrong arguments (like: there is no ikea gu10).

**Comment by ivo443** [comment]
hello together

thank you for the answers.

the ikea GU 10 only have white light.
ikea has no color GU 10

the hornbach's can "lightingColorCtrl"

Sorry, I didn't make myself clear.

Greetings
Ivo

**Comment by nob0dy80** [comment]
hmm are you sure?
when i google the modell you provided ("VIYU-GU10-350-CCT-10011724") i end up here:
https://www.hornbach.de/shop/FLAIR-Viyu-Smarte-LED-Reflektorlampe-GU10-5W50W-350-lm-2700-6500-K-warmweiss-tageslichtweiss-Kompatibel-mit-SMART-HOME-by-hornbach/10011724/artikel.html

10011724 matches as  an identifier so this is only a white light too.

googling more ended up in this: https://www.smartlights.de/licht/flair-viyu/hornbach-steigt-ein-eigene-zigbee-leuchtmittel-namens-flair-viyu/

and still the same result..there is no color VIYU GU10.

**Comment by ivo443** [comment]
aargh... you're absolutely right. The SKU is 10011724 and not color. I should be able to read it. I apologize. my first post and right beside it.
