### ISSUE TITLE
Add Sonoff Zigbee Bridge

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.zigbee#717]
Pleased add Sonoff Zigbee Bridge

**Comment by kirovilya** [comment]
I don't understand what you want. Sonoff Zigbee Bridge is an autonom hub.
it can be flashed but cannot be connected as a zigbee device
https://notenoughtech.com/home-automation/flashing-tasmota-on-sonoff-zigbee-bridge/
https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html?m=1

**Comment by duczz** [comment]
Oh okay, i have think it can be connect/config like a zigbee stick

**Comment by kirovilya** [comment]
there are prerequisites that it will be possible to connect it as a remote port (like 'tcp: //192.168.1.46:8880'). but so far there is no such possibility.

**Comment by duczz** [comment]
@kirovilya is it planed to add this prerequisites?

**Comment by kirovilya** [comment]
I'm waiting for the implementation in zigbee-herdsman. After that, it will already be available in our adapter
