### ISSUE TITLE
Groups - Change between level.color.rgb and level.color.temperature did not work

### ISSUE THREAD

**Issue by moelski** [ioBroker/ioBroker.zigbee#718]
Hi !

I´m testing the ZigBee implementation to replace my Zigbee2Mqtt instance. But I think there is a problem with the groups for color bulbs. 
My setup ... 
**Stick** CC2531 
**Bulb** GLEDOPTO GL-S-007Z ZigBee Smart RGB + CCT GU10 5W
**Zigbee Version** 1.1.3 from Github

The Bulb is in one group named "Esszimmer". That´s all ... 

Now I change the colortemp for the group (level.color.temperature). The bulb changes directly which is as expected.
And it doesn´t matter if the bulb lights with some RGB color or if it is in CCT mode. 

Now I change the RGB Color to FF0000. I would expect that the light immediately switch the full Red. Instead it shows a little bit of red combined with the CCT Color. Look at the attached picture. 

![red](https://user-images.githubusercontent.com/17078960/89705100-ac58b480-d95a-11ea-9cec-184bfe886798.jpg)

Sorry for the quality, but it´s hard to capture the lights ... But you can see that the CCT lights are also on. 

Things get more strange if you send the FF0000 RGB setting for the group multiple times. Now the CCT lights get darker until the switch off and the red color gets brighter. 

Really strange ... Can this be fixed? Otherwise the Groups for color bulbs are a little bit useless. 
If I can assist in any way please give me a note. 

Thx

Dominik

**Comment by kirovilya** [comment]
Please run adapter in debug mode and show logs for group command.
