### ISSUE TITLE
repairing cc2530 with cc2531

### ISSUE THREAD

**Issue by volkerrichert** [ioBroker/ioBroker.zigbee#719]
Hi!

I have a CC2521 as coordinator with 3 CC2530. Two of them are flashed as router, one is unused. All of them are not in production atm. I switched to deconz a year ago.

After reading about deconz support in ioBroker.zigbee, I want to give it a try. So I grabbed the old stuff and try to use it with v1.1.1.

The coordinator was detected and I was able to pair e.g. an OSRAM Plug 01 or a Xiaomi Cube. GREAT! To increase range I decided to re-pair one of my CC'30 router. This wasn't possible. I tried flashing the latest FW version, plug and unplug to re-pair as described... nothing. Reflashing cc'31 with the differend Versions (Z3.0, Z1.2, Z1.2 source rounting).  Nothing, again.

Now I flashed the ununsed CC'30... BOOOM paired. After testing and flashing coordinator again, I try to re-pair the working CC'30 again. You guessed it.... Nothing.

So re-pairing CC'30 doesn't work. I tried repairing and/or reflashing multiple time. 

Any Ideas or hint?

THX,

Volker

**Comment by kirovilya** [comment]
your cc2530 may already be in network and therefore does not want to re-enter.
check it, in the file iobroker-data/zigbee_0/shepherd.db search your device by ieeeAddr. if it is there stop the adapter and remove it from there.

**Comment by volkerrichert** [comment]
The newly flashed one was in it. So, i removed it and did a retry. Nothing.... like before not router is detected anymore.
