### ISSUE TITLE
Warn message color x.y (Paulmann Amaris LED Panel 798.09)

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/ioBroker.zigbee#721]
The Paulman LED is working great with new github, but it only generates the following warnings:

`

zigbee.0 | 2020-08-10 07:14:31.823 | warn | (7575) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2020-08-10 07:14:31.817 | warn | (7575) State value to set is invalid for zigbee.0.00158d00057ad735.color: The state contains the forbidden properties x, y!

`

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/729

**Comment by Hesse-Bub** [comment]
I guess the problem is, that the incoming x.y status from the lamp ist not converted to RGB...

**Comment by Hesse-Bub** [comment]
Is there a function to change the incoming x.y status sent from the the lamp to RGB for the datapoint?
