### ISSUE TITLE
Update 1.2 - Lumi Sen (Aqara - GZCGQ01LM) DeviceConfig failed

### ISSUE THREAD

**Issue by Einklaus** [ioBroker/ioBroker.zigbee#724]
Hatte diesen Fehler bei 1.04 noch nicht.
(7808) DeviceConfigure failed 0x04cf8cdf3c772202 lumi.sen_ill.mgl01, attempt 2 (Error: Bind 0x04cf8cdf3c772202/1 genPowerCfg from '0x00124b00182afdc1/1' failed (AREQ - ZDO - bindRsp after 10000ms)

Gruß
Klaus

**Comment by Bibo13** [comment]
Ich habe die gleiche Meldung. Nach 5 Versuchen ist dann Ruhe. Der Sensor funktioniert übrigens.

DeviceConfigure failed 0x04cf8cdf3c78dbc9 lumi.sen_ill.mgl01, attempt 5 (Error: Bind 0x04cf8cdf3c78dbc9/1 genPowerCfg from '0x00124b00014d2885/1' failed (AREQ - ZDO - bindRsp after 10000ms)

**Comment by Bibo13** [comment]
Any News about the case?

**Comment by krumbholz** [comment]
Hi, habe ich auch für Blaupunkt Roller Shutter SCM-1. In 1.1.x gab es diesen Fehler nicht. (Ich weiß Blaupunkt war damals im Release nicht drin, hatte ihn manuel im Code eingefügt). Der Fehler tritt beim Zigbee-Start auf, ansonsten Funktioniert das SCM-1.
VG, Steffen

**Comment by palsch** [comment]
Hallo zusammen, 
ich hab ebenfalls das Problem hier mit dem Helligkeitssensor:

zigbee.0 | 2020-09-22 22:02:20.743 | error | (22937) DeviceConfigure failed 0x04cf8cdf3c776b00 lumi.sen_ill.mgl01, attempt 1 (Error: Bind 0x04cf8cdf3c776b00/1 genPowerCfg from '0x00124b00194306d5/1' failed (AREQ - ZDO - bindRsp after 10000ms)
-- | -- | -- | --

`Zigbee Version 1.2.1, node: v10.22.0, js-controller: 3.1.6`

Und abgesehen davon auch noch extreme Probleme mit dem ganzen Netzwerk. D.h. meine Geräte verlieren immer wieder die Verbindung, so dass ich meine Raspi neustarten muss, damit es eine zeitlang funktioniert. 
Das Netzwerk lief fast ein Jahr lang problemlos, und jetzt hab ich das Problem. Könnte wohl tatsächlich mir der Version 1.2 zusammen hängen.

**Comment by palsch** [comment]
Ich habe gestern auf die Version 1.1.1 gewechselt, und bis jetzt läuft wieder alles Problemlos.
