### ISSUE TITLE
"GL-C-007-2ID" not described in statesMapping

### ISSUE THREAD

**Issue by praepo** [ioBroker/ioBroker.zigbee#727]
After the update to version 1.20 (before 1.1.2) my Gledopto GL-C-007 was detected as undefined. In the logs I found this message: "GL-C-007-2ID" not described in statesMapping. I did a little research and found out that the device is not defined in devices.js. Only the 1ID version. I tried to add it and the pairing is working but without the white channel states.

**Comment by kirovilya** [comment]
Please update from github

**Comment by praepo** [comment]
Thank you! It works.
