### ISSUE TITLE
zigbee warning for "Gardenpole Mini RGBW OSRAM"

### ISSUE THREAD

**Issue by jplenio** [ioBroker/ioBroker.zigbee#729]
I repeatedly have this warning in my log file, referring to my "Gardenpole Mini RGBW OSRAM".

zigbee.0 | 2020-08-16 13:39:22.338 | warn | (704) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
zigbee.0 | 2020-08-16 13:39:22.337 | warn | (704) State value to set is invalid for zigbee.0.7cb03eaa00ae4db6.color: The state contains the forbidden properties x, y!

Any idea?

**Comment by vaaarg** [comment]
the same here
