### ISSUE TITLE
Feature request: Power on behavior

### ISSUE THREAD

**Issue by xengosam** [ioBroker/ioBroker.zigbee#738]
Hi *,

first of all, thanks for your great work with this adapter, I'm using it quite a while and it's very stable.

Any chance to see the feature power on behavior to see implemented in future, or something similar like that?
That would be awesome!

Regards, 
xenogosam

**Comment by tetzlav** [comment]
+1

**Comment by sbormann** [comment]
+1

**Comment by cstudener** [comment]
Hey guys!

I'm sorry for not adding a +1 to this feature. I thought it is a mandatory problem for all of us...

Without a "Power on behavior"-setting possibility, all our lights will be set to "on", on every power-loss. Even, if we are on holidays for x days and might not notice the lights being "On"...

I think, this is a good feature request...

Regards
