### ISSUE TITLE
Aqara switch 

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.zigbee#74]
Hey folks, I want to add a "wxkg11lm" xioami button to iobroker. But it does not work after paring.

Sometimes it's "undefined" or "lumi.remote.b1acn01".

Any ideas?

**Comment by arteck** [comment]
can you see the objects ??

**Comment by arteck** [comment]
check my repo https://github.com/arteck/ioBroker.zigbee

**Comment by n3roGit** [comment]
What's the difference in your repo?

**Comment by n3roGit** [comment]
https://github.com/Koenkk/zigbee-shepherd-converters/pull/89

**Comment by arteck** [comment]
done

**Comment by kirovilya** [comment]
added in 0.8.0 version
