### ISSUE TITLE
Time to release a new stable version?

### ISSUE THREAD

**Issue by MartinSchlender** [ioBroker/ioBroker.zigbee#741]
Is there a new version that could be released as stable? I would like to have some of the new features (update of my OSRAM switches etc.) but I don´t want to risk my running system

And it´s really been a while that you released the last stable...

**Comment by Shadesh** [comment]
16.08.2020 was the latest release. You can also install from Github as many here do (Including me). Github Version is stable enough for many devices and daily usage.

**Comment by kennymc-c** [comment]
Is there a reason why the latest version in ioBroker is almost 4 months old? When they last 4 releases are stable enough why they are not released directly via ioBroker?
Does the latest version on GitHub support the new cc26X2R1 based sticks like Electrolama's zzh? Unfortunately, the changelog does not explicitly mention this. The SoC itself is supposed to be supported, but there might be some additional customizations needed for the models. Before there was only a developer kit for the CC26X2 available. In ZigBee2MQTT the support was mentioned explicitly.

**Comment by MartinSchlender** [comment]
> 16.08.2020 was the latest release. You can also install from Github as many here do (Including me). Github Version is stable enough for many devices and daily usage.

The recommendation in ioBroker is clearly not to install release adapters. I had issues with new releases. So why not release a new stable?

**Comment by MrThreesome** [comment]
How to change the last stable version number? package.json is 1.2.1.

**Comment by kirovilya** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/741
