### ISSUE TITLE
Network map shows no connections 

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.zigbee#743]
Hi, 
the network map does not show any connections. 
Used by the adapter in version: 1.2.1
And as stick: Conbee (v1)

![image](https://user-images.githubusercontent.com/19333515/91416988-6c496b00-e850-11ea-8984-6d3840efff40.png)

**Comment by kirovilya** [comment]
Any error in log?

**Comment by o0shojo0o** [comment]
no, there are no errors found in the log. 
Everything else works fine, but I can't get any information about the network.
![image](https://user-images.githubusercontent.com/19333515/91436478-7f683500-e868-11ea-8fa0-00bd58054543.png)
![image](https://user-images.githubusercontent.com/19333515/91436562-a45ca800-e868-11ea-8ab9-c170ad9786ef.png)

**Comment by o0shojo0o** [comment]
Here is a debug log from a restart of the instance.
I do not notice anything :(
https://pastebin.com/E4E26jea

**Comment by kirovilya** [comment]
I do not see a request for building a network map in the logs (getMap)... it is executed when you open the admin panel
![image](https://user-images.githubusercontent.com/8360230/91445757-2f489d00-e87f-11ea-9307-1c0e6b22fd96.png)

**Comment by o0shojo0o** [comment]
Ah have now found something in the log:
`(2914) Failed to get map: "TypeError: Cannot read property 'stack' of undefined\n at ZigbeeController.getMap (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:530:115)"`

**Comment by kirovilya** [comment]
try to comment from 527 to 546 lines in lib/zigbeecontroller.js
![image](https://user-images.githubusercontent.com/8360230/91447266-28228e80-e881-11ea-8ce4-05d1ddc0a90b.png)
then rerun adapter

**Comment by kirovilya** [comment]
it is additional request for routing table... it is not necessary

**Comment by o0shojo0o** [comment]
It will only output the debug message from targets 525 4 times and then it will stop again, it will not reach line 549.

the error  `(3169) Failed to get map: "TypeError: Cannot read property 'stack' of undefined\n at ZigbeeController.getMap (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:496:105)\n at run`

**Comment by o0shojo0o** [comment]
I now have in the zigbeecontroller of all try catch blocks the error removed that this is always undefined.
Now I get a map but it is not complete.
![image](https://user-images.githubusercontent.com/19333515/91609392-a6615c80-e977-11ea-9fc2-8e1285d8e3b4.png)
![image](https://user-images.githubusercontent.com/19333515/91609399-a8c3b680-e977-11ea-9c7d-edb18d0a00ec.png)

**Comment by sbormann** [comment]
For me the same problem, also with conbee (but conbee 2). Network map shows only connections of routers, no connection of th coordinator is shown.

**Comment by weidlix** [comment]
Same for me. The Coordinator is no longer visible after the adapter update.
![grafik](https://user-images.githubusercontent.com/60174671/93744787-b4ab3d00-fbf2-11ea-9f97-4314628ecff9.png)

**Comment by sbormann** [comment]
Hi, the problem still exists. Would be nice to have the map, maybe one of the developers can have a look?
There is another Problems with conbee II, you can't delete devices (neither normal delete, nor forced delete). Maybe this needs only a small fix?

**Comment by bachph** [comment]
> Hi, the problem still exists. Would be nice to have the map, maybe one of the developers can have a look?
> There is another Problems with conbee II, you can't delete devices (neither normal delete, nor forced delete). Maybe this needs only a small fix?

The network map does not function well for me too. 

@sbormann You need to delete the device several times. After a couple of tries it is deleted.
