### ISSUE TITLE
The state contains the forbidden properties y and x! (Smart+ gardenpole 8.7W RGBW)

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.zigbee#747]
Hi, I have just received the messages:
![image](https://user-images.githubusercontent.com/19333515/91647314-d08b4b00-ea59-11ea-8e75-62c65624e5bb.png)
![image](https://user-images.githubusercontent.com/19333515/91647340-05979d80-ea5a-11ea-82a1-150c6b85cf7c.png)
Do you need more information?

**Comment by o0shojo0o** [comment]
The message can still be found in the log, and this is not rare.

**Comment by o0shojo0o** [comment]
issues is fixed with the current version 1.3.9dev :)

**Comment by asgothian** [comment]
Closed, is duplicate of Issue #607
