### ISSUE TITLE
Невозможно задать имя порта

### ISSUE THREAD

**Issue by Sergio-tix** [ioBroker/ioBroker.zigbee#75]
Имею Orange Pi Plus 2E. В USB установил CC2531.
![01](https://user-images.githubusercontent.com/18720428/46708843-583ef500-cc49-11e8-98f9-55380a50aa5a.PNG)
Но не могу ничего ввести в графе "Имя или адрес порта", поле недоступно для ввода.
![02](https://user-images.githubusercontent.com/18720428/46708902-b10e8d80-cc49-11e8-9235-e0ac507d93b4.PNG)
Я пробовал IE, Opera, FF и Chrome. Ни в одном из этих браузеров поле не открывается для ввода.
Где и как я ещё могу указать порт?

**Comment by GermanBluefox** [comment]
In the object system.adapter.zigbee.0 => native.port

**Comment by kirovilya** [comment]
Переключитесь на latest репозиторий и установите обновление до версии 0.7.5
Похоже что-то не так с вашей версией, давно не видел такого интерфейса у настроек :)

**Comment by kirovilya** [comment]
Кажется понял - это админка 2.0. На ней не проверял настройки

**Comment by Sergio-tix** [comment]
Разобрался. Старая версия была, но ставил старую специально. Дело в том, что раннее сидел на сяоми шлюзе, всё работало прекрасно, и была фишка - некоторые устройства отправляли heartbeat с интервалом 50 минут, например это делал Door sensor. А потом всё обновилось и пульс жизни от устройств приходить перестал. Как дела с этим обстоят у ZigBee свистка?
