### ISSUE TITLE
after Update from 1.1.1 to 1.2.1 lumi.sen_ill.mgl01 can not configure

### ISSUE THREAD

**Issue by hoepps2802** [ioBroker/ioBroker.zigbee#750]
with 1.1.1 the lumi.sen_ill.mgl01 ( Aqara Lux Sensor ) work and can configure.
0x04cf8cdf3c7cb525 (addr 39893): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
0x04cf8cdf3c786c8b (addr 62089): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)

After update to 1.2.1 it show this error

zigbee.0 | 2020-09-03 07:04:58.268 | error | (26839) DeviceConfigure failed 0x04cf8cdf3c786c8b lumi.sen_ill.mgl01, attempt 2 (Error: Bind 0x04cf8cdf3c786c8b/1 genPowerCfg from '0x00124b000e8cc069/1' failed (AREQ - ZDO - bindRsp after 10000ms)
-- | -- | -- | --
zigbee.0 | 2020-09-03 07:04:48.244 | info | (26839) Configuring 0x04cf8cdf3c786c8b lumi.sen_ill.mgl01
zigbee.0 | 2020-09-03 07:04:41.040 | error | (26839) DeviceConfigure failed 0x04cf8cdf3c7cb525 lumi.sen_ill.mgl01, attempt 2 (Error: Bind 0x04cf8cdf3c7cb525/1 genPowerCfg from '0x00124b000e8cc069/1' failed (AREQ - ZDO - bindRsp after 10000ms)
zigbee.0 | 2020-09-03 07:04:31.016 | info | (26839) Configuring 0x04cf8cdf3c7cb525 lumi.sen_ill.mgl01
zigbee.0 | 2020-09-03 07:04:21.119 | error | (26839) DeviceConfigure failed 0x04cf8cdf3c7cb525 lumi.sen_ill.mgl01, attempt 1 (Error: Bind 0x04cf8cdf3c7cb525/1 genPowerCfg from '0x00124b000e8cc069/1' failed (AREQ - ZDO - bindRsp after 10000ms)
zigbee.0 | 2020-09-03 07:04:17.907 | error | (26839) DeviceConfigure failed 0x04cf8cdf3c786c8b lumi.sen_ill.mgl01, attempt 1 (Error: Bind 0x04cf8cdf3c786c8b/1 genPowerCfg from '0x00124b000e8cc069/1' failed (AREQ - ZDO - bindRsp after 10000ms)
javascript.0 | 2020-09-03 07:04:11.827 | info | (5450) script.js.Haussteuerung.Fenster: Auslösender Aktor: die Haustür: true
zigbee.0 | 2020-09-03 07:04:11.097 | info | (26839) Configuring 0x04cf8cdf3c7cb525 lumi.sen_ill.mgl01
zigbee.0 | 2020-09-03 07:04:07.856 | info | (26839) Zigbee started

**Comment by Bibo13** [comment]
I have exactly the same since updating from 1.1.1 to newer Versions
DeviceConfigure failed 0x04cf8cdf3c78c9b3 lumi.sen_ill.mgl01, attempt 1 (Error: Bind 0x04cf8cdf3c78c9b3/1 genPowerCfg from '0x00124b00014d2885/1' failed (AREQ - ZDO - bindRsp after 10000ms)

**Comment by killakaktus** [comment]
Problems also here. No more lux values in objects

**Comment by Bibo13** [comment]
Is there any new Info about the Problem?
I have the warnings every new Start of Zigbee.
It's boring
