### ISSUE TITLE
Added default bulb to device.js but Device not described in statesMapping

### ISSUE THREAD

**Issue by maxpd1** [ioBroker/ioBroker.zigbee#755]
Hi,

I have 25 bulbs from China ^^

I added to device.js (node_modules/zigbee-herdsman-converters/devices.js) the following lines 

`{
    zigbeeModel: [{modelID: 'TS0505A', manufacturerName: '_TZ3000_evag0pvn'}],
    model: 'TS0505A',
    description: 'E27 RGBW bulb',
    vendor: 'TuYa',
    extend: generic.light_onoff_brightness_colortemp_colorxy,
},`

If I pair my RGBW bulbs I get the following notification in pairing window:

Error: Device 0x842e14fffe0f5310 "TS0505A" not described in statesMapping.. undefined
New device joined '0x842e14fffe0f5310' model TS0505A
Interview successful: [object Object]

and in Log:

zigbee.0 | 2020-09-03 06:30:26.816 | error | (24616) Device 0x842e14fffe0f5312 "TS0505A" not described in statesMapping.
-- | -- | -- | --

Any idea?

Regards 
maxpd1

**Comment by kirovilya** [comment]
You also must add this model to iobroker.zigbee/lib/devices.js file.
like other bulbs https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devices.js#L480

**Comment by maxpd1** [comment]
Thanks for fast reply.
But I don't have the rights to change this file:

![image](https://user-images.githubusercontent.com/15956503/92240186-7e648280-eebc-11ea-82b1-917b4f38a347.png)

**Comment by maxpd1** [comment]
this helped: https://community.allstarlink.org/t/help-winscp-permission-denied-error-code-3-error-message-from-server-permission-denied/16267/5

**Comment by maxpd1** [comment]
Great, no error message anymore during pairing. But in log:

![image](https://user-images.githubusercontent.com/15956503/92241910-47dc3700-eebf-11ea-8b40-3065e5a3a242.png)


And a folder with values is also shown. But these values aren't filled. 

Except for the ones I filled for testing, but bulbs aren't tured off or bightness down.

![image](https://user-images.githubusercontent.com/15956503/92241992-6e9a6d80-eebf-11ea-9bcf-eeac6fd6066a.png)

**Comment by maxpd1** [comment]
@kirovilya 

I also tried now this one as it is no Ikea but Tuya device. But same problem. 
Do I have to change something else in  iobroker.zigbee/lib/devices.js
or do you have another idea with which device it could be comparable?

If I add the bulb to a group, I can control it via the group, but then the whole adapter crashes.
`

{
--
  | zigbeeModel: ['TS0505A'],
  | model: 'TS0505A',
  | vendor: 'TuYa',
  | description: 'E27 RGBW bulb',
  | supports: 'on/off, color (hue/saturation)',
  | fromZigbee: [fz.on_off, fz.tuya_led_controller],
  | toZigbee: [tz.tuya_led_controller, tz.ignore_transition, tz.ignore_rate],
  | },

`

**Comment by kirovilya** [comment]
you have to make changes to 2 files
node_modules / zigbee-herdsman-converters / devices.js
node_modules / iobroker.zigbee / lib / devices.js

what errors are displayed in the log now?

**Comment by maxpd1** [comment]
In  node_modules / zigbee-herdsman-converters / devices.js I have

`{
  | zigbeeModel: ['TS0505A'],
  | model: 'TS0505A',
  | vendor: 'TuYa',
  | description: 'E27 RGBW bulb',
  | supports: 'on/off, color (hue/saturation)',
  | fromZigbee: [fz.on_off, fz.tuya_led_controller],
  | toZigbee: [tz.tuya_led_controller, tz.ignore_transition, tz.ignore_rate],
  | },`


In node_modules / iobroker.zigbee / lib / devices.js I have

`   {
        models: ['ZNLDP12LM'],
        icon: 'img/aqara_bulb.png',
        states: lightStatesWithColortemp,
        syncStates: [sync.brightness],
    },`

If I change something in the object values like the brightness of the bulb the log says:

`

host.iobroker | 2020-09-10 09:54:25.368 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.iobroker | 2020-09-10 09:54:25.362 | info | instance system.adapter.zigbee.0 terminated with code 0 (NO_ERROR)
zigbee.0 | 2020-09-10 09:54:24.824 | info | (2908) Terminated (NO_ERROR): Without reason
zigbee.0 | 2020-09-10 09:54:24.823 | info | (2908) terminating
zigbee.0 | 2020-09-10 09:54:24.527 | info | (2908) Zigbee: disabling joining new devices.
zigbee.0 | 2020-09-10 09:54:24.525 | info | (2908) cleaned everything up...
zigbee.0 | 2020-09-10 09:54:24.524 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
zigbee.0 | 2020-09-10 09:54:24.524 | error | at runMicrotasks (<anonymous>)
zigbee.0 | 2020-09-10 09:54:24.524 | error | at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:317:19)
zigbee.0 | 2020-09-10 09:54:24.524 | error | at Array.forEach (<anonymous>)
zigbee.0 | 2020-09-10 09:54:24.524 | error | at /opt/iobroker/node_modules/iobroker.zigbee/main.js:329:43
zigbee.0 | 2020-09-10 09:54:24.524 | error | (2908) TypeError: Cannot read property 'toZigbee' of null
zigbee.0 | 2020-09-10 09:54:24.523 | error | (2908) uncaught exception: Cannot read property 'toZigbee' of null

`

**Comment by kirovilya** [comment]
Brrr...
> fromZigbee: [fz.on_off, fz.tuya_led_controller], | toZigbee: [tz.tuya_led_controller, tz.ignore_transition, tz.ignore_rate]
why? it was
`extend: generic.light_onoff_brightness_colortemp_colorxy`

> { models: ['ZNLDP12LM'], icon: 'img/aqara_bulb.png', states: lightStatesWithColortemp, syncStates: [sync.brightness], },
why `ZNLDP12LM` ? need to be `TS0505A`

**Comment by maxpd1** [comment]
I am so sorry. Wrong copy now. yes I changed model name to TS0505A correctly as in comment https://github.com/ioBroker/ioBroker.zigbee/issues/755#issuecomment-687129570 at the end

extend: generic.light_onoff_brightness_colortemp_colorxy did't work 

(https://github.com/ioBroker/ioBroker.zigbee/issues/755#issuecomment-687129570)

so I changed to a Tuya similar device with same effect.

**Comment by kirovilya** [comment]
> (2908) uncaught exception: Cannot read property 'toZigbee' of null

this means that the model was not found in the converters
maybe your converters are in another file
node_modules / iobroker.zigbee / node_modules / zigbee-herdsman-converters / devices.js

**Comment by maxpd1** [comment]
This worked!

But why are there 2 converters? 
I also find the second one during my way through the files but sticked to the plan of my helper ^^

Now I can change white temperature but as it is a RGB+W bulb I have the felling the RGB setting is missing.

**Comment by kirovilya** [comment]
try to change converters to light_onoff_brightness_colortemp_colorxy

**Comment by maxpd1** [comment]
You mean only removing "generic." from extend: generic.light_onoff_brightness_colortemp_colorxy, ?

**Comment by kirovilya** [comment]
yes

**Comment by kirovilya** [comment]
and in lib/devices.js use lightStatesWithColor

**Comment by kirovilya** [comment]
try to find correct name for this extend on top of file zigbee-herdsman-converters/devices.js

**Comment by maxpd1** [comment]
The const where to find it is called generic. So i think the generic. has to be written in front. But this doesn't help.

`const generic = {
    light_onoff_brightness: {
        supports: 'on/off, brightness',
        fromZigbee: [fz.on_off, fz.brightness, fz.ignore_basic_report],
        toZigbee: [
            tz.light_onoff_brightness, tz.ignore_transition, tz.ignore_rate, tz.light_alert,
            tz.light_brightness_move, tz.light_brightness_step,
        ],
    },
    light_onoff_brightness_colortemp: {
        supports: 'on/off, brightness, color temperature',
        fromZigbee: [fz.color_colortemp, fz.on_off, fz.brightness, fz.ignore_basic_report],
        toZigbee: [
            tz.light_onoff_brightness, tz.light_colortemp, tz.ignore_transition, tz.ignore_rate, tz.light_alert,
            tz.light_brightness_move, tz.light_colortemp_move, tz.light_brightness_step,
            tz.light_colortemp_step,
        ],
    },
    light_onoff_brightness_colorxy: {
        supports: 'on/off, brightness, color xy',
        fromZigbee: [fz.color_colortemp, fz.on_off, fz.brightness, fz.ignore_basic_report],
        toZigbee: [
            tz.light_onoff_brightness, tz.light_color, tz.ignore_transition, tz.ignore_rate, tz.light_alert,
            tz.light_brightness_move, tz.light_brightness_step,
            tz.light_hue_saturation_move, tz.light_hue_saturation_step,
        ],
    },
    light_onoff_brightness_colortemp_colorxy: {
        supports: 'on/off, brightness, color temperature, color xy',
        fromZigbee: [fz.color_colortemp, fz.on_off, fz.brightness, fz.ignore_basic_report],
        toZigbee: [
            tz.light_onoff_brightness, tz.light_color_colortemp, tz.ignore_transition, tz.ignore_rate,
            tz.light_alert, tz.light_brightness_move, tz.light_colortemp_move, tz.light_brightness_step,
            tz.light_colortemp_step, tz.light_hue_saturation_move, tz.light_hue_saturation_step,
        ],
    },
};
`

**Comment by kirovilya** [comment]
So, you neet to write 
`extend: generic.light_onoff_brightness_colortemp_colorxy,`
to your device

**Comment by maxpd1** [comment]
Yes. Thats what I thought so too and I also did. Now in both paths of the device.js (not the lib/)
But the objects don't show any additional values for color.

**Comment by kirovilya** [comment]
for objects you need changes in lib/devices.js
`states: lightStatesWithColor,`

**Comment by maxpd1** [comment]
Puhhhh
It's working now!!!

Will these changes be gone with adapter update?

Do i somehow have to do a pull request?

**Comment by kirovilya** [comment]
yes, you have to make PRs to converters and iobroker.zigbee :)

**Comment by maxpd1** [comment]
I tested it, yes. 

In lib/devices.js:

   {
        models: ['TS0505A'],
        icon: 'img/aqara_bulb.png',
        states: lightStatesWithColor,
        syncStates: [sync.brightness],
    },


In node_modules / iobroker.zigbee / node_modules / zigbee-herdsman-converters / devices.js

// 3rd-party Tuya

{

zigbeeModel: ['TS0505A'],
model: 'TS0505A',
description: 'E27 RGBW bulb',
vendor: 'TuYa',
extend: generic.light_onoff_brightness_colortemp_colorxy,

},

**Comment by maxpd1** [comment]
@kirovilya Do you know why adapter is always restarting if I want to change states via group?
Structure in group doesn't look like structure in object. But for group I can't define how the values should look, do I?

Log attached:
`

zigbee.0 | 2020-09-11 06:43:01.888 | error | at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
-- | -- | -- | --
zigbee.0 | 2020-09-11 06:43:01.888 | error | at Generator.next (<anonymous>)
zigbee.0 | 2020-09-11 06:43:01.888 | error | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:311:27)
zigbee.0 | 2020-09-11 06:43:01.888 | error | (5681) Error: Command 0x842e14fffe0f5312/1 genGroups.removeAll({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufactur
zigbee.0 | 2020-09-11 06:43:01.887 | error | (5681) uncaught exception: Command 0x842e14fffe0f5312/1 genGroups.removeAll({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":

`

**Comment by maxpd1** [comment]
If I assign the bulbs to a group and give commands to the group, they are not inherited by the bulbs themselves. Is there anything missing?

![image](https://user-images.githubusercontent.com/15956503/92968023-9c148780-f47a-11ea-980d-d9330d53a5fc.png)
