### ISSUE TITLE
Add support Paulneuhaus NLG-TW

### ISSUE THREAD

**Issue by Dome2075** [ioBroker/ioBroker.zigbee#757]
Hi,

Please add Support for Paulneuhaus NLG-TW + Remote

I thought that the supported deviced are the same like zigbee2mqtt.io??

https://www.zigbee2mqtt.io/devices/NLG-TW_light.html

Thanks

![image](https://user-images.githubusercontent.com/37158961/92302516-37829580-ef6d-11ea-841e-90eb09dd394c.png)

**Comment by Dome2075** [comment]
Firtst thanks to support!

But i can't control this lamp now..??

it was succesfully paired and saied "Supported"

![image](https://user-images.githubusercontent.com/37158961/93606761-c6110100-f9c8-11ea-8d79-f820622c7f4c.png)
![image](https://user-images.githubusercontent.com/37158961/93606966-02446180-f9c9-11ea-8b65-2d44f9e2428d.png)
![image](https://user-images.githubusercontent.com/37158961/93607084-286a0180-f9c9-11ea-9273-a2e456b83f0e.png)

Thanks for help

**Comment by cron0mat** [comment]
Remote control is supported now -  #855

**Comment by arteck** [comment]
done
