### ISSUE TITLE
Backup does not include network name, key, channel

### ISSUE THREAD

**Issue by HansBorjes** [ioBroker/ioBroker.zigbee#758]
I am looking for the correct place to raise this issue
https://github.com/ioBroker/ioBroker.admin/issues/581#issuecomment-685356257

After restoring from backup I am always losing important configuration data.

This should be included in ioBroker backup.

**Comment by kirovilya** [comment]
Zigbee adapter settings are stored in system states and restored with them

**Comment by kirovilya** [comment]
only information about devices is stored in the zigbee adapter database

**Comment by HansBorjes** [comment]
And what would be the way forward to get the missing pieces included in backup? From users perspective it is painful if you don't remember those data. Re-pairing all devices is a lot of work.

**Comment by kirovilya** [comment]
how do you backup the settings of other adapters?
just for the zigbee adapter, you still need to save the device base. it is necessary to restore both the adapter settings and the device base together.

**Comment by HansBorjes** [comment]
On my NAS I am having two zip archives per scheduled backup: iobroker*.tar.gz and zigbee*.tar.gz.

Transfer is via FTP. Two selections are checked: "Save zigbee database" and "ioBroker Backup". Am I missing something?

I wasn't aware that restoring zigbee backup only is not supposed to be complete. Does that make any sense to have two backup files if they cannot be treated separately? I am confused.

**Comment by kirovilya** [comment]
"Save zigbee database" is for an additional backup, not the main one. it does not contain adapter settings

**Comment by HansBorjes** [comment]
I am getting you right that I could remove the checkmark on "Save zigbee database" and everything (including paired devices) would be backed up in one place, i.e. the iobroker*.tar.gz?

**Comment by kirovilya** [comment]
no, only the adapter settings will be saved to the iobroker*.tar.gz, without connected devices

**Comment by HansBorjes** [comment]
Okay, so I will keep my backup settings and restore both next time. Thanks!

**Comment by kirovilya** [comment]
yes. if there was a possibility, then I would store the device base in states as well. but alas, it is stored separately in a file. therefore 2 files are backed up.
