### ISSUE TITLE
BITRON Rauchmelder 902010/24 und Außensirene 902010/29

### ISSUE THREAD

**Issue by galegro** [ioBroker/ioBroker.zigbee#766]
Ich möchte die Außensirene 902010/29 mittels des ZigBee Adapters betreiben. Leider wird dieses Gerät noch gar nicht unterstützt. Im Forum habe ich hierzu bereits alles, was ich an [Daten](https://forum.iobroker.net/post/473986) finden konnte, eingestellt.

Die Sirenen der bereits unterstützten Rauchmelder 902010/24 können als Signalgeber angesteuert werden. Leider wird dies noch nicht unterstützt.

**Comment by Apollon77** [comment]
Bitte issue im Zigbee Adapter öffnen

**Comment by Apollon77** [comment]
(Sorry fault)

**Comment by galegro** [comment]
Besteht überhaupt eine Hoffnung, dass hieran jemand arbeitet?

Obwohl ich erst rund vier Wochen dabei bin: Der ZigBee-Adapter in Verbindung mit CC26X2R1 von Texas Instruments arbeitet deutlich zuverlässiger als der ganze Homemaitk Kram (keine Verbindungsprobleme, keine Störung von Gerätekommunikationen, ..). Eine interne Alarmierung über die bereits angepassten Rauchmelder wäre eine große Bereicherung.

**Comment by galegro** [comment]
In [MQTT](https://www.zigbee2mqtt.io/devices/902010_24.html) wurde die Alarmfunktion bereits implementiert. Bitte auch für den ZigBee Adapter übernehmen.

**Comment by joBr99** [comment]
@galegro Ich habe die Alarmfunktion für den Bitron AV2010/24A hinzugefügt, es kann sein, dass der State hierzu auch mit dem 902010/24 funktionieren würde, das kann ich aber leider nicht testen, da ich diesen Rauchmelder nicht besitze.

**Comment by galegro** [comment]
@joBr99 Vielen Dank für diese gute Nachricht.

Was könnte/müsste ich tun, um die Sache zu testen?

**Comment by joBr99** [comment]
Du brauchst zum einen die aktuelle Version von diesem Adapter und außerdem muss du den bitron_execute_warning State zu dem Device 902010/24 hinzufügen.

Ich hab die nötigen Änderungen in einem Branch auf meinem Fork bereits vorgenommen, es reicht also wenn du den Adapter auf die aktuelle Version aus diesem Branch aktualisierst. Dazu musst du diese URL verwenden: "git://github.com/joBr99/ioBroker.zigbee#joBr99-902010/24-warning-test"

Adpater -> Installieren aus eigener URL (GitHub Logo oben links) -> BELIEBIG und dann die gerade genannte URL.
https://github.com/ioBroker/ioBroker.docs/blob/master/docs/de/dev/webstorm.md

**Comment by galegro** [comment]
@joBr99 Vielen Dank für deine Unterstützung. Da ich mich auf diesem Gebiet noch sehr unsicher fühle, werde ich @asgothian um Hilfe bitten. Wenn wir das Ganze getestet haben, melde ich mich wieder.

**Comment by arteck** [comment]
done

**Comment by bastian1607** [comment]
Hallo @galegro, was haben deine Tests ergeben? Ich bin auf der Suche nach einem Zigbee-Rauchmelder und dieser scheint hier zu meinen Anforderungen zu passen. 
Kannst du den Alarm selbst auslösen?

**Comment by galegro** [comment]
> Hallo @galegro, was haben deine Tests ergeben? .. Kannst du den Alarm selbst auslösen?

Dank @asgothian funktioniert bei mir alles wie gewünscht. Ich habe ein System aufgebaut, das gleich vier verschiedene Alarmarten unterstützt: Einbruch (Hüllschutz), Rauch, Wasser und Gas. Die Meldungen der Sensoren werden von entsprechenden Skripten verarbeitet, um die Außensirene und die einzelnen Rauchmelder anzusteuern.

**Comment by kptkip** [comment]
In der Version 1.6.0 hat die Funktion bei mir bei beiden Gerätetypen klasse funktioniert.
Seit der Version 1.6.6 ff leider nur noch beim Rauchmelder 902010/24A. Die o.g. Geräte gehen nun wieder nicht :-(

**Comment by galegro** [comment]
Bei uns setze ich die Version 1.6.16 ein. Bei mir schein soweit alles zu funktionieren.

Wie äußert sich das Ganze? Verbinden sich die Geräte erst gar nicht über den Coordinator zum ZigBee-Adapter?

**Comment by kptkip** [comment]
Bin mit @asgothian in diesem thread bereits am diskutieren. Dort findest Du auch die Fehlerbeschreibung:
https://github.com/ioBroker/ioBroker.zigbee/issues/1397

**Comment by galegro** [comment]
Wenn ich deine Schilderungen in der referenzierten Diskussion richtig interpretiere, ..

- kannst keinen Alarm auslösen, in dem du den Datenpunkt "execute warning" beschreibst!?
- nur bei bei den 2010/24A Meldern funktioniert das Ganze noch!?

Bei uns sind ausschließlich noch die älteren Geräte 902010/24 (Rauchmelder) und 902010/29 (Außensirene) in Verwendung. Dies waren wohl auch die ersten Geräte, die im Herdsman/ZigBee Adapter eingepflegt wurden. @asgothian hatte mir damals eine Testinstallation eingerichtet, die später in die stabilen Versionen aufgenommen wurden.

Es mag also durchaus sein, dass es an der Geräte-Version liegen könnte.

Wenn ich mit meiner obigen Einschätzung richtig liege, werden ich gerne (sozusagen sicherheitshalber) das Ganze für dich bei uns (nochmals) überprüfen. Allerdings muss ich zuvor meine Nachbarn warnen, damit diese nicht alle anschließend bei mir auf der Matte stehen. ;-)

**Comment by kptkip** [comment]
@galegro Danke für Deine Antwort.

> Wenn ich deine Schilderungen in der referenzierten Diskussion richtig interpretiere, ..
> * kannst keinen Alarm auslösen, in dem du den Datenpunkt "execute warning" beschreibst!?
> * nur bei bei den 2010/24A Meldern funktioniert das Ganze noch!?

Genau so ist es. In der Version 1.6.0 hat es bei allen Gerätetypen noch wunderbar funktioniert. Bei den späteren Versionen (aktuell bei mir 1.6.16) leider nicht mehr. Welche setzt ihr denn ein?

> Wenn ich mit meiner obigen Einschätzung richtig liege, werde ich gerne (sozusagen sicherheitshalber) das Ganze für dich bei uns (nochmals) überprüfen. Allerdings muss ich zuvor meine Nachbarn warnen, damit diese nicht alle anschließend bei mir auf der Matte stehen. ;-)

Das wäre natürlich super. So können wir auf jeden Fall ausschließen, dass das Problem nicht wieder bei mir vor dem Computer sitzt :-)

**Comment by galegro** [comment]
Wie ich oben schrieb, setzen wir 1.6.16 ein.

Nun habe ich in den Objekten einmal einen Rauchmelder ausprobiert und dort den Wert 2 in den Datenpunkt „execute_warnig“ geschrieben. Auch bei uns funktioniert es nicht mehr: Der Rauchmelder bleibt stumm. Dabei spielt es keine Rolle, ob ich mit oder ohne Bestätigung den Wert schreibe.

Da wurde offenbar etwas verbastelt. ;-(

**Comment by kptkip** [comment]
Danke @galegro für die Rückmeldug. Das beruhigt mich :-)

**Comment by galegro** [comment]
Ich denke, hier haben wir den Grund ..

<img width="862" alt="image" src="https://user-images.githubusercontent.com/70838532/159295733-9ebd16d0-85be-4d58-9c41-4be8df7a8d05.png">

**Comment by galegro** [comment]
Ich bleibe doch ruhig. ;-)

Aber 1.6.16 ist doch nicht _beta_. Ich habe als Repository immer nur _stabil_ eingestellt.

Wurde im Herdsman denn etwas geändert?

Wenn ihr Unterstützung benötigt, können wir das Ganze bei mir (online) ausprobieren, ganz so, wie's Asgothian beim mir gemacht hat.

**Comment by arteck** [comment]
Beta 1.6.16 hier in GIT... nicht die auf NPM.. wir ziehen die Version nicht immer hoch.. 
das Problem ist ca. 7 Monate alt nach meiner Analyse..

**Comment by galegro** [comment]
Oh je, so lange ist das schon her?

Auf welche Version sollte ich demnach zurückgehen? Ich möchte nicht auf die vier Alarmarten (Hüllschutz/Einbruch, Gas, Wasser und Rauch verzeichnen müssen.

Nun weiß ich auch, warum kein Familienmitglied mehr einen Fehlalarm auslöste. Und ich dachte schon, man hat mit dem Alarmsystem umzugehen gelernt. ;-)

**Comment by arteck** [comment]
geha auf die 1.6.0 zurück die laut @kptkip funktioniert.. wie gesagt ich kannst dir nicht sagen.. hab die Teile nicht

**Comment by galegro** [comment]
> geh auf die 1.6.0 zurück die laut @kptkip funktioniert.. wie gesagt ich kannst dir nicht sagen.. hab die Teile nicht
> oder du Testest den brunch von Axel

Wenn du mir sagst, wo/wie ich den _Brunch_ von Axel finden und bei mir einbauen kann, will ich's gerne versuchen. Dank _ApplePiBaker_ kann ich meine gesamte SSD innerhalb von 30 Minuten sichern/wiederherstellen. Die Zeit dazu habe ich. ;-)

Wie gesagt: Gerne kann Axel es online bei mir ausprobieren.

**Comment by kptkip** [comment]
Aloa
> geh auf die 1.6.0 zurück die laut @kptkip funktioniert.. wie gesagt ich kannst dir nicht sagen.. hab die Teile nicht

Zu meiner Entschuldigung muss ich sagen, dass ich das nur aus dem ioBroker-Forum von hier übernommen habe:
https://forum.iobroker.net/topic/50010/zigbee-1-6-6-update-kein-ansteuern-der-aussensirene?_=1647891612276
Springreiter behauptet das in seinem ersten Post, um genau zu sein.

> oder du Testest den branch von Axel
> [#1397 (comment)](https://github.com/ioBroker/ioBroker.zigbee/issues/1397#issuecomment-1073810780)

Das habe ich jetzt ausprobiert und muss feststellen, dass ich damit die gleichen Probleme habe. Zwar sind nun neue Datenpunkte (send_payload) da, um den Alarm-Befehl per JSON einzugeben. Klappt aber trotzdem nicht ;-(

Ich wühl' jetzt mal nach der 1.6.0.

**Comment by galegro** [comment]
> > geh auf die 1.6.0 zurück die laut @kptkip funktioniert.. wie gesagt ich kannst dir nicht sagen.. hab die Teile nicht
> 
> Zu meiner Entschuldigung muss ich sagen, dass ich das nur aus dem ioBroker-Forum von hier übernommen habe: 
> 
> Ich wühl' jetzt mal nach der 1.6.0.

Axel hat mir geantwortet, dass er dran sei. Ich müsse jedoch Geduld haben, da es wohl etwas dauere. Er bestätigte, dass nicht im ZigBee-Adapter Änderungen erfolgten, sondern wie vermutet im Herdsman. Daraus schließe ich, dass ein Rückzug auf 1.6.0 am Ende auch nichts bringt. ;-(

**Comment by galegro** [comment]
> Wie es scheint, laufen die Gerätegenerationen V1 gerade aus. Sie sind kaum noch zu bekommen.

Das kann ich bestätigen. Ich habe vor Monaten nach langem Suchen von einem Händler aus der EP-Gruppe dessen zwei letzten Exemplare (902010/24) erwerben können.

**Comment by kptkip** [comment]
Vlt. müssen wir die Hardware früher oder später eh auf die V2 wechseln. Dann sind wir aus dem Problem raus ;-)

**Comment by galegro** [comment]
> Vlt. müssen wir die Hardware früher oder später eh auf die V2 wechseln. Dann sind wir aus dem Problem raus ;-)

Daran möchte ich nun wirklich nicht denken müssen. Die Teile waren nicht gerade preiswert, um sie nach vier Jahren bereits in die Tonne zu klopfen.
