### ISSUE TITLE
Better assign roles, types and mappings

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.zigbee#77]
I have now two kinds of devices using Zigbee and I needed to learn the following:

* brightness is using value range 0..254 (also defined as min/max) in object. Now I need to manually map this to the "normal"/"expected" level.dimmer range of 0..100% ... This could be mapped already by the adapter and would be great if so. Hopefully rools like material can work with such defined states
* color Temperature is kind of the same, but a bit different. There are ni min/max vaues defined in the obejct, but from experiments the range is 0..454 while 0 is the "coldes" temperature and 454 is the "warmest" one. I needed some time to figure that out.
Here I also would expect to see a role with level.color.temperature allowing to enter K values which are then also mapped to the real data "behind the scenes".
Because of the fact that each device needs to be added manually to the adapter for it's meta data also the "Kelvin-range" or allowed Kelvin values or such could be added easiely there and then being mapped automatically

**Comment by modmax** [comment]
According to the color temperature there are some differences. Appollon77 mentions 0-454 for the IKEA tadfri LED panel.

But for my OSRAM Surface light TW there are values between 153...370 allowed. You can test it, if you manually enter i.e. 10, then it will be set to 153 by the adapter; also if you enter 450 the adapter sets it to 370.

So I think there is no generic mapping for color temperatures, cause they might differ from device to device.

**Comment by arteck** [comment]
we have here a issue ... but i dont know how we can solve it.. the values range is to large

**Comment by modmax** [comment]
My idea would be to enhance the file devStates, where the devices are declared,
so that there is a new object entry called "colortempRange: [minValue,maxValue]",
which is only used for device with colortemp state.

May be that at the beginning some ranges are unknown for several devices;
then they have to be added later on if someone can determine the range.

I determined the range for a OSRAM Surface Light TW by entering 0 or 1 and see
what value the adapter sets, if it acks the state; same for the max value.

Best regards
Markus

**Comment by kirovilya** [comment]
For brightness, I think that I can make a separate state, which will correspond to a percentage value of 0..100

And for the color temperature, I like the @modmax idea of describing the range of acceptable values. But my idea is that you can make a predefined list of ready-made modes for each model:
```
modes: {0: "warmest", 1: "hot", 2: "cold"},
modesColorTemp: {0: 454, 1: 300, 2: 0},
```
and allow to select them in a separate state, and when choosing to set the value in colorTemp state

**Comment by GermanBluefox** [comment]
Please think about material. Material understand only max, min

**Comment by Apollon77** [comment]
Also wanted to add that regarding material. also such modes are really "subject to user understanding" :-)
And for brightness? Why an extra state for 0..100? Why not using the original one and release a new "major" version of the adapter to cover such a breaking change ... ? The adapter is relative joung and all such stuff stays in there forever :-)

**Comment by Apollon77** [comment]
Additionally you should use different roles!
* For color Temperature use level-color.temperature
* Für color use level.color.rgb (if it is rgb coded)
