### ISSUE TITLE
Problem with new Conbee 2 Version and pairing

### ISSUE THREAD

**Issue by Chiller2019** [ioBroker/ioBroker.zigbee#772]
Good Evening,

I bought a new conbee 2 from dresden electronics.

I set allthink like the readme.
The Adapter is gepairt with zigbee-adapter (green light in iobroker).

The Problem is, I cant pairing my aqara Temp-/Hum.-Sensor and my motion detector.

I think the problem is the new conbee firmware version.

Kind regards
Chiller

**Comment by asgothian** [comment]
- Please post the conbee firmware version number.
- Can other devices be paired ?
- Can you control already paired devices ?

**Comment by BernhardLinz** [comment]
> Good Evening,
> 
> I bought a new conbee 2 from dresden electronics.
> 
> I set allthink like the readme.
> The Adapter is gepairt with zigbee-adapter (green light in iobroker).
> 
> The Problem is, I cant pairing my aqara Temp-/Hum.-Sensor and my motion detector.
> 
> I think the problem is the new conbee firmware version.
> 
> Kind regards
> Chiller

I had have simlar problems:

* Install the newest Firmware to the Conbee 2 Sticks (0x26580700) if the sticks not already have (Version is shown in Log when ZigBee Adapter is startet)
* Take a look at the file 
`/opt/iobroker/iobroker-data/zigbee_0/shepherd.db`
I is a textfile. This file have a line for every paired ZigBee Device. Compare the ieee Entrys (and the total number of) Devices with the ones which are shown in the ZigBee Adapter.
* If there are to much devices:
* Stop the ZigBee Adpater
* delete all which are not shown in ZigBee Adapter in the file
* re-number the devices in file
* Start ZigBee Apapter an try pairing again.

**Devices which are listet in the shepard.db will not be detected again!**
