### ISSUE TITLE
Feature request: Sonoff Zigbee Bridge support?

### ISSUE THREAD

**Issue by neolution** [ioBroker/ioBroker.zigbee#777]
How can I use this adapter with the new sonoff zigbee bridge? Is is supported yet?

**Comment by asgothian** [comment]
The bridge itself will most likely not be supported, as it is a "zigbee coordinator", not a "zigbee device". It is used to allow use of zigbee devices within the sonoff ecosystem.

You should be able to use most of the sonoff zigbee devices natively without using the bridge itself.

The bridge does NOT enable the use of sonoff wifi devices within the zigbee network.

**Comment by zefixx1** [comment]
Maybe this can help:
https://zigbee.blakadder.com/Sonoff_ZBBridge.html

**Comment by asgothian** [comment]
Sorry, but no. This will allow to use the sonoff zigbee bridge with the sonoff Adapter, and it might enable the use of supported zigbee items with the sonoff Adapter - but not with the zigbee Adapter.

A.

**Comment by onkeldittmayer** [comment]
I would also prefer to use the Sonoff Zigbee Bridge "native" with the io.broker zigbee plugin.
It is possible to flash the sonoff Bridge with Tasmota and use a custom Firmware for the ZigBee module.
Further you can config the whole thing as a Serial-TCP Bridge.
BUT its not possible to set the EZSP Module in the io.broker ZigBee plugin...

i think when its possible to write a custom Firmware for the ZigBee Module OR a support for existing firmware, than we will be happy ;-)

**Comment by kirovilya** [comment]
https://github.com/Koenkk/zigbee-herdsman/issues/168

**Comment by Hedda** [comment]
> It is possible to flash the sonoff Bridge with Tasmota and use a custom Firmware for the ZigBee module.
> Further you can config the whole thing as a Serial-TCP Bridge.
> BUT its not possible to set the EZSP Module in the io.broker ZigBee plugin...

Sonoff ZBBridge is supported by Tasmota, see https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html

But to clearify; ioBroker depends on the zigbee-herdsman project for Zigbee coordinator hardware/interface/protocol abstraction support and that library does not yet support Silicon Labs EZSP (EmberZNet Serial Protocol), see https://github.com/Koenkk/zigbee-herdsman/issues/168
