### ISSUE TITLE
T1829 - IKEA GUNNARP panel 40*40

### ISSUE THREAD

**Issue by Tob1a5** [ioBroker/ioBroker.zigbee#782]
Please add support for the IKEA GUNNARP panel 40*40 - T1829.

In zigbee2mqtt it is already implemented. 
https://www.zigbee2mqtt.io/devices/T1829.html

**Comment by Burner76** [comment]
Yes please, I also need the support for IKEA GUNNARP panel 40*40.

**Comment by asgothian** [comment]
Please post the Tile from the zigbee adapters config interface so we can see how it is identified by the Adapter.

This will make implementing this A LOT faster.
