### ISSUE TITLE
Not working anymore from one moment to another

### ISSUE THREAD

**Issue by LittleNo** [ioBroker/ioBroker.zigbee#789]
I'm using the cc2531 connected to a Raspberry for controlling my ZigBee Devices. I'm on version 1.2.1. Everything worked fine for 2 weeks until yesterday evening. Without reason it was not controlling any ZigBee Devices anymore. The adapter is running and in objects-tree the changes to a device state works correctly. However the devices itself show no reaction to any state-changes. 

A while ago I've seen a similar issue with a Philips remote control. That day unpairing and again new pairing the devices fixed the issue. However, this is not a solution when all devices are involved in this issues every now and then.

Here's the log:

`zigbee.0	2020-09-25 02:38:11.240	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:38:11.240	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:38:11.240	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:38:11.240	error	(1200) Error on send command to 0x680ae2fffe3dbd87. Error: Error: Command 0x680ae2fffe3dbd87/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"
zigbee.0	2020-09-25 02:37:56.234	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:37:56.234	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:37:56.234	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:37:56.234	error	(1200) Error on send command to 0xd0cf5efffebde4dd. Error: Error: Command 0xd0cf5efffebde4dd/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"
zigbee.0	2020-09-25 02:37:48.816	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:37:48.816	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:37:48.816	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:37:48.816	error	(1200) Error on send command to 0xec1bbdfffe6fd246. Error: Error: Command 0xec1bbdfffe6fd246/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"
zigbee.0	2020-09-25 02:37:33.711	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:37:33.711	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:37:33.711	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:37:33.711	error	(1200) Error on send command to 0xec1bbdfffe6fd556. Error: Error: Command 0xec1bbdfffe6fd556/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"
zigbee.0	2020-09-25 02:37:24.079	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:37:24.079	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:37:24.079	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:37:24.079	error	(1200) Error on send command to 0xec1bbdfffe6fd246. Error: Error: Command 0xec1bbdfffe6fd246/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":21148,"colory":21561}, {"timeout":10000,"disableRe
zigbee.0	2020-09-25 02:37:08.766	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:37:08.766	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:37:08.766	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:37:08.766	error	(1200) Error on send command to 0x680ae2fffe3dbd87. Error: Error: Command 0x680ae2fffe3dbd87/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,
zigbee.0	2020-09-25 02:36:59.207	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:36:59.207	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:36:59.207	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:36:59.207	error	(1200) Error on send command to 0xec1bbdfffe6fd246. Error: Error: Command 0xec1bbdfffe6fd246/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,
zigbee.0	2020-09-25 02:36:46.866	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:36:46.866	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:36:46.866	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:36:46.866	error	(1200) Error on send command to 0x680ae2fffe3dbd87. Error: Error: Command 0x680ae2fffe3dbd87/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"s
zigbee.0	2020-09-25 02:36:34.707	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:36:34.707	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:36:34.707	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:36:34.707	error	(1200) Error on send command to 0xec1bbdfffe6fd246. Error: Error: Command 0xec1bbdfffe6fd246/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"s
zigbee.0	2020-09-25 02:36:24.127	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:36:24.127	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:36:24.127	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:36:24.127	error	(1200) Error on send command to 0xec1bbdfffe6fd556. Error: Error: Command 0xec1bbdfffe6fd556/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":21148,"colory":21561}, {"timeout":10000,"disableRe
zigbee.0	2020-09-25 02:36:09.984	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:36:09.984	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:36:09.984	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:36:09.984	error	(1200) Error on send command to 0xd0cf5efffebde4dd. Error: Error: Command 0xd0cf5efffebde4dd/1 lightingColorCtrl.moveToColorTemp({"colortemp":0,"transtime":0}, {"timeout":10000,"disableResponse":fals
zigbee.0	2020-09-25 02:35:58.776	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:35:58.776	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:35:58.776	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:35:58.776	error	(1200) Error on send command to 0xec1bbdfffe6fd556. Error: Error: Command 0xec1bbdfffe6fd556/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,
zigbee.0	2020-09-25 02:35:47.789	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:35:47.789	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:35:47.789	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:35:47.789	error	(1200) Error on send command to 0xd0cf5efffebde4dd. Error: Error: Command 0xd0cf5efffebde4dd/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,
zigbee.0	2020-09-25 02:35:33.381	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:35:33.381	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:35:33.381	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:35:33.381	error	(1200) Error on send command to 0xec1bbdfffe6fd556. Error: Error: Command 0xec1bbdfffe6fd556/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"s
zigbee.0	2020-09-25 02:35:26.148	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:35:26.148	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:35:26.148	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:35:26.148	error	(1200) Error on send command to 0xd0cf5efffebde4dd. Error: Error: Command 0xd0cf5efffebde4dd/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"s
zigbee.0	2020-09-25 02:35:03.504	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:35:03.504	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:35:03.504	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:35:03.504	error	(1200) Error on send command to 0xec1bbdfffe6fd246. Error: Error: Command 0xec1bbdfffe6fd246/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":21148,"colory":21561}, {"timeout":10000,"disableRe
zigbee.0	2020-09-25 02:34:46.057	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:34:46.057	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:34:46.057	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:34:46.057	error	(1200) Error on send command to 0x680ae2fffe3dbd87. Error: Error: Command 0x680ae2fffe3dbd87/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,
zigbee.0	2020-09-25 02:34:39.379	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:34:39.379	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:34:39.379	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:34:39.379	error	(1200) Error on send command to 0xec1bbdfffe6fd246. Error: Error: Command 0xec1bbdfffe6fd246/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,
zigbee.0	2020-09-25 02:34:23.961	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0	2020-09-25 02:34:23.961	error	at Generator.next (<anonymous>)
zigbee.0	2020-09-25 02:34:23.961	error	at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
zigbee.0	2020-09-25 02:34:23.961	error	(1200) Error on send command to 0x680ae2fffe3dbd87. Error: Error: Command 0x680ae2fffe3dbd87/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"s`

How can I fix that issue?

**Comment by LittleNo** [comment]
Today I tried another cc2531 (again paired all devices), without change on the problem.

**Comment by asgothian** [comment]
The log entries hint at issues reaching various zigbee endpoints / receiving messages from them.

I would check the WiFi vs. Zigbee channel load.

See here: 
![Unknown](https://user-images.githubusercontent.com/45667167/95074819-74c67880-070f-11eb-9388-812e90885f0c.jpeg)

If possible, do not only check which wifi channels are in use by your equipment but also which wifi channels may be used bei neighbours. Also - crosscheck the issue with positioning of the endpoints / coordinator in relation to the WiFi router, nearest WiFi source/drain, DECT Phones / DECT Base Stations.

A.
