### ISSUE TITLE
Can not pair Philips Hue Ensis

### ISSUE THREAD

**Issue by WernerRH21** [ioBroker/ioBroker.zigbee#790]
![image](https://user-images.githubusercontent.com/67897090/94295090-06d8bf00-ff61-11ea-81ce-53bc59a6e27a.png)

**Comment by Sacred-Shadow** [comment]
Works with devices from this list https://github.com/ioBroker/ioBroker.zigbee/wiki/Supported-devices

**Comment by WernerRH21** [comment]
Is there a possibility to add this device in future? Feature Request?

**Comment by arteck** [comment]
done

**Comment by WernerRH21** [comment]
Thanks a lot!
