### ISSUE TITLE
Add smoke detector Bitron AV2010/24A

### ISSUE THREAD

**Issue by Butz86** [ioBroker/ioBroker.zigbee#794]
Hi,
please add the optical smoke detector Bitron AV2010/24A
[https://www.zigbee2mqtt.io/devices/AV2010_24A.html](url)
![image](https://user-images.githubusercontent.com/48626605/94373094-50610f80-0103-11eb-83ab-8d350399989e.png)
![image](https://user-images.githubusercontent.com/48626605/94373131-8d2d0680-0103-11eb-8b30-824b117e8fd1.png)

**Comment by joBr99** [comment]
Hi @Butz86,
Bitron AV2010/24A should be working now.

(except for the tamper thing, I did not really found something about this and I have no Idea how to trigger it on the device)
