### ISSUE TITLE
Add zigbee Keypad Develco F0066Z0401

### ISSUE THREAD

**Issue by MojitoJoe1813** [ioBroker/ioBroker.zigbee#795]
As iobroker-compatible zigbee keypads (as well as zwave keypads) are very rare - if not unavailable at all - this keypad would add tremendous user benefit to be available and useable in any smarthome system:

[https://www.develcoproducts.com/products/sensors-and-alarms/keypad/#KeypadTechnicalSpecifications](url)

Even more detailed technical information available [here](https://www.develcoproducts.com/media/2032/kepzb-110-technical-manual-keypad.pdf).

**Comment by asgothian** [comment]
- is this device supported by zigbee2mqtt.io ?
- can you post the tile for this device once it has been paired with the adapter, as well as the "info" page accessible by selecting the i icon on the tile ?
