### ISSUE TITLE
Xiaomi Aqara curtain motor resets position to 255 after assigning a value

### ISSUE THREAD

**Issue by bpichon** [ioBroker/ioBroker.zigbee#797]
Hi everybody,

when trying to control the Xiaomi Aqara curtain motor ZNCLDJ11LM I noticed a strange behavior.
After setting a value (e.g. 20%) in the ioBroker object view, the value resets to 255%, which seems to be invalid, since the range is 0%-100%. Please see the attached log file.
The issue is reproducible and I did not find any workaround to control the curtain. 

ZigbeeAdapter version 1.2.1
[curtainLog.txt](https://github.com/ioBroker/ioBroker.zigbee/files/5295238/curtainLog.txt)

**Comment by Dmitrii-1969** [comment]
Hi all!
I have the same ZNCLDJ11LM motor for curtains.The same behavior is manifested - after any movement position resets to 255%.
ZNCLDJ11LM firmware: 01-25-2022 (I tried to roll back to the previous one and dropped it to red LED)
Completely reinstalled Zigbee2MQTT + Broker MQTT, I tried with another of the same engine - the situation does not change.
State:
```
{
    "device_temperature": 34,
    "last_seen": "2022-07-04T11:56:01.403Z",
    "linkquality": 80,
    "motor_state": "stopped",
    "options": {
        "hand_open": true,
        "reverse_direction": false
    },
    "position": 255,
    "power_outage_count": 59,
    "running": false,
    "state": "OFF"
}

```Home Assistant Core: 2022.6.7
Home Assistant Supervisor: 2022.05.3 
Zigbee2MQTT version: 1.26.0-1 
Broker MQTT: 6.1.2
Coordinator zigbee: SONOFF Zigbee 3.0 USB Dongle Plus; firmware 20211217.
