### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by dimidrolka** [ioBroker/ioBroker.zigbee#798]
Können sie den Gerät in iobroker einbinden DIYRuZ_Flower. Das ist ein Bodenfeuchtigkeitssensor . 
https://modkam.ru/?p=1700#more-1700
Илья если вам не трудно  помогите добавить  этот датчик  в iobroker .   датчик собрал , но он зараза с iobroker не работает .

**Comment by arteck** [comment]
@kirovilya you part

**Comment by kirovilya** [comment]
The main problem is that the converters for this device are external. https://github.com/diyruz/flower/blob/master/converters/DIYRuZ_Flower.js
It is not in the general zigbee-herdsman-converters :(
