### ISSUE TITLE
No data object update from philips hue lamp

### ISSUE THREAD

**Issue by Matthias1912** [ioBroker/ioBroker.zigbee#799]
I’m using the following lamps:
https://www.philips-hue.com/de-de/p/hue-white---color-ambiance-doppelpack-e27/8718699673284

There is no update from the data object inside the zigbee adapter.
For example: dim lamp to 50% -> switch off power -> switch on power again (lamp has now 100%), but inside object dim value is still at 50%.

Is this normal? Is there a way to get the real information about dim, state and color value?

**Comment by arteck** [comment]
Is this normal? yes it is...
swich on is = 100 %
