### ISSUE TITLE
sort within admin table is bugy

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zigbee#8]
with rooms assignment is the sort within admin table wrong.
![42178401-8b64d222-7e30-11e8-8473-8a9d583c1a69](https://user-images.githubusercontent.com/6681528/42200421-660a0926-7e93-11e8-9e5a-5e1cb10302ae.png)

**Comment by kirovilya** [comment]
Fixed

**Comment by arteck** [comment]
not all
![grafik](https://user-images.githubusercontent.com/6681528/42237802-2b40c53e-7eff-11e8-9b54-7527fa35db33.png)

**Comment by arteck** [comment]
and can you sort by room ??

**Comment by kirovilya** [comment]
In small size layout corrupted by device names :(

> and can you sort by room plz??

hmm... if multiple rooms link to device?

**Comment by arteck** [comment]
maybe sort only on room... see my screenshot .. 
![grafik](https://user-images.githubusercontent.com/6681528/42239113-3633f39a-7f03-11e8-9164-d82ebdc901f0.png)

**Comment by kirovilya** [comment]
Try

**Comment by arteck** [comment]
nice
![grafik](https://user-images.githubusercontent.com/6681528/42240277-17e1876e-7f07-11e8-8d7d-cc2ad52df1d1.png)
