### ISSUE TITLE
ZLED-RGB9 color change problem

### ISSUE THREAD

**Issue by Lours373** [ioBroker/ioBroker.zigbee#801]
Dear all,
I bought a color led TRUST.
Evrything is going well directly with iobroker, when I send commande, color, dimmer etc..
But I had in node-red to pilot it from alexa.
Dimmer is ok, On/OFF is ok
But for the color it doesn't work.
Color arrive in the correct place in iobroker directly and with the correct HEXA code.
But I've to validate in the iobroker case to send to the lamp.
Can you help me?
![image](https://user-images.githubusercontent.com/70146161/94710281-f2246e80-0346-11eb-9ba4-fee93cb98905.png)

**Comment by asgothian** [comment]
Does the format of the value sent from node-red match the format of the value you enter manually ?

**Comment by Lours373** [comment]
Yes it does.
I found the mistakes, in Node-red it was put as Value and not command.
Now it works fine.

Tnaks for your answer.
