### ISSUE TITLE
Iobroker LOG

### ISSUE THREAD

**Issue by RoboCop0815** [ioBroker/ioBroker.zigbee#803]
adapter.getMessage is deprecated and will be removed in js-controller >= 3.2. Please report this warning to the developer of this adapter!
Verfügbare Version: 1.2.1
Installierte Version: 0.10.2
Installierte Instanzen: 1
Installiert auf Rasberry 2B+ mit cc2531 Stick

**Comment by arteck** [comment]
ist nicht dein ernst .. Installierte Version: 0.10.2
