### ISSUE TITLE
Aqara Opple Switch WXCJKG13LM / long press (hold) problem

### ISSUE THREAD

**Issue by darkdan2000** [ioBroker/ioBroker.zigbee#804]
Hello

If I press a button of Aqara Opple Switch to long (for more than 5 sec) and release him then the value of  e.g. "button_1_hold" stays in true and doesnt switch back to false. Is that "works as designed" or can it be fixed?

Thx in advance!

**Comment by asgothian** [comment]
Please leave more details about the actual switch you are talking about
- Model name
- Model number

best case - an image of the respective tile in the ioBroker interface.

A.

**Comment by darkdan2000** [comment]
Hi,
I mean these models:
![image](https://user-images.githubusercontent.com/65658473/95103012-62126a80-0734-11eb-8fbc-ce9f78d4106b.png)

**Comment by kirovilya** [comment]
this is a known problem/feature of opple remotes
