### ISSUE TITLE
Add TuYa TS0601_thermostat please

### ISSUE THREAD

**Issue by derex33** [ioBroker/ioBroker.zigbee#806]
Hi,

Please add Support for TuYa TS0601_thermostat

https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html

![0200F3C0-4524-4467-A0D7-AD39AF6C5D3D](https://user-images.githubusercontent.com/43520758/95056407-f9f06400-06f4-11eb-91f0-7c56617f55ca.jpeg)

**Comment by asgothian** [comment]
Please link the tile from the adapter interface which shows the paired thermostat. 
Tuya is (in)famous for using the same Model number (TS0601) for a wide range of products, using other details to identify the exact version. As far as i know, the thermostat is already supported "in principle", but additional information to ensure the correct identification may be needed both in the ioBroker adapter and the underlying zigbee-herdsman-converters library.

A.
