### ISSUE TITLE
limi.sensor cube battery percentage

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#81]
Battery percentage showed 53% .. so I changed it for a new Duracell. Still showing 53%. Strange.

lumi.sensor cube
battery.percent
53.00%

**Comment by kirovilya** [comment]
The percentage of charge is determined based on the current voltage of the battery. It is the voltage value sent by the sensor.

Up to version 0.7.6, we used our function of determining percent - it was a linear function, where 0% is 2.700v and 100% is 3.200v https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devstates.js#L132

Starting from 0.7.6, we use the general percentage definition function based on the voltage and percentage correspondence table https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L14
In it, the values of 0% correspond to 2.000v, and 100% - 3.211v

Therefore, if you are confused by the value of the percentage - look at the voltage

**Comment by daniel-lo** [comment]
Hi kirovily, thanks for this information. The old battery was 3V and the new 3.3V .. I expected to see a difference .. this is what confused me.

**Comment by kirovilya** [comment]
maybe you just did not wait for the sensor to send updated battery voltage? :)
