### ISSUE TITLE
Installed Version not always clear

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.zigbee#811]
Hey

i have been trying to debug issues and check things, and ran up against the issue that the version number does not really tell us the correct version of the adapter.

I would suggest that we add a "commit" String, which needs to be updated on every commit to the adapter, and have that added to the version number as it is reported in the iobroker log.

I would put that in by myself, but a change like this does require a certain process which the person(s) committing the pull requests need to follow.

What do you think ?

**Comment by kirovilya** [comment]
I agree. I think we can connect travis or github-actions for this.
today or tomorrow I plan to release version 1.3 and then we can change the numbering mechanism ... but I don’t know how :)

**Comment by arteck** [comment]
we have now a string after the start 
Installed Version : GIT direct link...
