### ISSUE TITLE
TRADFRI LED1624G9 - ColorTemp not working 

### ISSUE THREAD

**Issue by sinalco92** [ioBroker/ioBroker.zigbee#813]
I have the problem that the ColorTemp not working with IKEA TRAFDRI bulb E27 CWS opal 600lm d0cf5efffe22e689
with the Zigbee Adapter Version: 1.3.0.

This issue excist a long time. 

But now I found some new thing out:
If I set a value from 150 to 450 instant off the state ColorTemp. to the state color, than the light change to the right ColorTemp for about 1s and than goes off.

For example: I put the value 201 in the Color state and than the lamp change the light for about 1second to the ColorTemp and goes off.
![image](https://user-images.githubusercontent.com/42220498/95728286-a0031780-0c7b-11eb-977c-38045a5e4fff.png)

Maybe there's a way to fix this, that we also control the ColorTemp.
Because the light definitely have the Color Temp. function.

**Comment by o0shojo0o** [comment]
This device? 
https://www.zigbee2mqtt.io/devices/LED1545G12.html

**Comment by sinalco92** [comment]
> This device?
> https://www.zigbee2mqtt.io/devices/LED1545G12.html

No its this device: https://www.zigbee2mqtt.io/devices/LED1624G9.html

**Comment by sinalco92** [comment]
It does support. On the supplier page the description is: „dimmable colour and white spectrum„ 
https://www.ikea.com/nl/en/p/tradfri-led-bulb-e27-600-lumen-wireless-dimmable-colour-and-white-spectrum-globe-opal-white-00408612/

**Comment by sinalco92** [comment]
> If I am not mistaken, the LED1624G9 does not support ColorTemp
> ![image](https://user-images.githubusercontent.com/19333515/102202684-f08b3100-3ec7-11eb-8f87-49958aef9ec2.png)

It does support. On the supplier page the description is: „dimmable colour and white spectrum„
https://www.ikea.com/nl/en/p/tradfri-led-bulb-e27-600-lumen-wireless-dimmable-colour-and-white-spectrum-globe-opal-white-00408612/

**Comment by o0shojo0o** [comment]
Yes the problem is that this function is not provided by herdsman (zigbee2mqtt).
You would have to open an issues there to have that fixed.

**Comment by arteck** [comment]
check new version 1.4.1
