### ISSUE TITLE
Eurotronic Spirit Zigbee thermostats DPs are not accepting Data

### ISSUE THREAD

**Issue by Bibo13** [ioBroker/ioBroker.zigbee#815]
Hello all

I want to control my Eurotronic Spirit Zigbee thermostats from a zigbee Version 1.21. Getting data from the thermostat works fine, but sending messages to the thermostat does not work. Always Errors. Is this new?
Thanks for any Help

2020-10-15 09:15:30.251 - error: zigbee.0 (2496) Error on send command to 0x00158d00032f6d80. Error: Error: Write 0x00158d00032f6d80/1 hvacThermostat({"16387":{"value":2250,"type":41}}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')

**Comment by CreatsheR** [comment]
same Problem here:


zigbee.0 | 2020-11-05 10:07:27.539 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:25:65)
-- | -- | -- | --
zigbee.0 | 2020-11-05 10:07:27.539 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-11-05 10:07:27.539 | error | at DeconzAdapter.<anonymous>  (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:552:23)
zigbee.0 | 2020-11-05 10:07:27.539 | error | (5707) Error on send command to 0x00158d00032f6e6c. Error: Error: Read  0x00158d00032f6e6c/1 hvacThermostat([16392],  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultRes

**Comment by TheMBeat** [comment]
The problem was also reported in the DezCon and Zigbee2MQTT repo and there was a bug in the firmware which will be fixed in the next days/weeks via OTA 
[More information](https://github.com/Koenkk/zigbee2mqtt/issues/4571)

**Comment by asgothian** [comment]
Fix for this issue requires a firmware update by the manufacturer. This issue will be closed once the firmware update is available, but no work will be done on the adapter on this.

**Comment by asgothian** [comment]
As of today, a firmware [update is available](https://github.com/EUROTRONIC-Technology/Spirit-ZigBee/wiki/OTA-update-quick-guide-via-deCONZ) to fix this issue. Unfortunately, the manufacturer does not offer a web service, so an update using the iobroker.zigbee adapter is not currently feasible.
