### ISSUE TITLE
Please add Osram Smart+ Motion Sensor

### ISSUE THREAD

**Issue by Zoelibat** [ioBroker/ioBroker.zigbee#82]
Hello, 

please add support for the Osram Smart+ Motion Sensor:

https://www.osram-lamps.de/ekatalog/smart-home/smart-home-komponenten/smart-motion-sensor/index.jsp

https://www.amazon.de/dp/B074KHZZ6B

![grafik](https://user-images.githubusercontent.com/16280409/47246580-edd34500-d3fe-11e8-9bcd-ac1afba546b0.png)

What else do you need?

**Comment by Zoelibat** [comment]
log:

zigbee.0	2018-10-20 00:37:26.587	error	Cannot get the Node Descriptor of the Device: 0x000d6f000f7110a4 (Error: Timed out after 10000 ms)
zigbee.0	2018-10-20 00:37:23.096	debug	system.adapter.admin.0: logging true
zigbee.0	2018-10-20 00:36:46.566	debug	User stateChange zigbee.0.info.pairingMessage {"val":"Error: Cannot get the Node Descriptor of the Device: 0x000d6f000f7110a4 (Error: Timed out after 10000 ms). undefined","ack":false,"ts":15399886065
zigbee.0	2018-10-20 00:36:46.558	error	Cannot get the Node Descriptor of the Device: 0x000d6f000f7110a4 (Error: Timed out after 10000 ms)
zigbee.0	2018-10-20 00:36:45.771	debug	User stateChange zigbee.0.info.pairingMessage {"val":"Time left: 33","ack":false,"ts":1539988605752,"q":0,"from":"system.adapter.zigbee.0","lc":1539988605752}
zigbee.0	2018-10-20 00:36:45.768	debug	User stateChange zigbee.0.info.pairingCountdown {"val":33,"ack":false,"ts":1539988605750,"q":0,"from":"system.adapter.zigbee.0","lc":1539988605750}
zigbee.0	2018-10-20 00:36:45.750	debug	Join countdown. 33
zigbee.0	2018-10-20 00:36:44.756	debug	User stateChange zigbee.0.info.pairingMessage {"val":"Time left: 34","ack":false,"ts":1539988604747,"q":0,"from":"system.adapter.zigbee.0","lc":1539988604747}
zigbee.0	2018-10-20 00:36:44.754	debug	User stateChange zigbee.0.info.pairingCountdown {"val":34,"ack":false,"ts":1539988604744,"q":0,"from":"system.adapter.zigbee.0","lc":1539988604744}
zigbee.0	2018-10-20 00:36:44.745	debug	Join countdown. 34
zigbee.0	2018-10-20 00:36:43.753	debug	User stateChange zigbee.0.info.pairingMessage {"val":"Time left: 35","ack":false,"ts":1539988603745,"q":0,"from":"system.adapter.zigbee.0","lc":1539988603745}
zigbee.0	2018-10-20 00:36:43.749	debug	User stateChange zigbee.0.info.pairingCountdown {"val":35,"ack":false,"ts":1539988603741,"q":0,"from":"system.adapter.zigbee.0","lc":1539988603741}
zigbee.0	2018-10-20 00:36:43.741	debug	Join countdown. 35
zigbee.0	2018-10-20 00:36:42.759	debug	User stateChange zigbee.0.info.pairingMessage {"val":"Time left: 36","ack":false,"ts":1539988602742,"q":0,"from":"system.adapter.zigbee.0","lc":1539988602742}
zigbee.0	2018-10-20 00:36:42.756	debug	User stateChange zigbee.0.info.pairingCountdown {"val":36,"ack":false,"ts":1539988602738,"q":0,"from":"system.adapter.zigbee.0","lc":1539988602738}
zigbee.0	2018-10-20 00:36:42.737	debug	Join countdown. 36
zigbee.0	2018-10-20 00:36:41.750	debug	User stateChange zigbee.0.info.pairingMessage {"val":"Time left: 37","ack":false,"ts":1539988601737,"q":0,"from":"system.adapter.zigbee.0","lc":1539988601737}
zigbee.0	2018-10-20 00:36:41.748	debug	User stateChange zigbee.0.info.pairingCountdown {"val":37,"ack":false,"ts":1539988601733,"q":0,"from":"system.adapter.zigbee.0","lc":1539988601733}
zigbee.0	2018-10-20 00:36:41.734	debug	Join countdown. 37
zigbee.0	2018-10-20 00:36:40.743	debug	User stateChange zigbee.0.info.pairingMessage {"val":"Time left: 38","ack":false,"ts":1539988600733,"q":0,"from":"system.adapter.zigbee.0","lc":1539988600733}
zigbee.0	2018-10-20 00:36:40.738	debug	User stateChange zigbee.0.info.pairingCountdown {"val":38,"ack":false,"ts":1539988600729,"q":0,"from":"system.adapter.zigbee.0","lc":1539988600729}
zigbee.0	2018-10-20 00:36:40.729	debug	Join countdown. 38

**Comment by arteck** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/507

**Comment by dcsg** [comment]
I really would like this to be added. What can we do to help?

**Comment by wossix** [comment]
It looks like they found a solution in zigbee2mqtt#507;
How can we implement that to iobroker.zigbee?

device.js
{
        zigbeeModel: ['Motion Sensor-A'],
        model: 'AC01353010G',
        vendor: 'OSRAM',
        description: 'SMART+ Motion Sensor',
        supports: 'occupancy and temperature',
        fromZigbee: [
            fz.generic_temperature, fz.ignore_temperature_change, fz.ias_zone_motion_dev_change,
            fz.ias_zone_motion_status_change,
        ],
        toZigbee: [],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const actions = [
                (cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb),
                (cb) => device.functional('ssIasZone', 'enrollRsp', {enrollrspcode: 0, zoneid: 23}, cb),
                (cb) => device.bind('msTemperatureMeasurement', coordinator, cb),
                (cb) => device.report('msTemperatureMeasurement', 'measuredValue', 30, 600, 1, cb),
                (cb) => device.bind('genPowerCfg', coordinator, cb),
                (cb) => device.report('genPowerCfg', 'batteryPercentageRemaining', 0, 1000, 0, cb),
            ];
            execute(device, actions, callback);
        },
fromzigbee.js
ias_zone_motion_dev_change: {
        cid: 'ssIasZone',
        type: 'devChange',
        convert: (model, msg, publish, options) => {
            if (msg.data.data.zoneType === 0x000D) { // type 0x000D = motion sensor
                const zoneStatus = msg.data.data.zoneStatus;
                return {
                    occupancy: (zoneStatus & 1<<1) > 0, // Bit 1 = Alarm 2: Presence Indication
                    tamper: (zoneStatus & 1<<2) > 0, // Bit 2 = Tamper status
                    battery_low: (zoneStatus & 1<<3) > 0, // Bit 3 = Battery LOW indicator (trips around 2.4V)
                };
            }
        },
    },
    ias_zone_motion_status_change: {
        cid: 'ssIasZone',
        type: 'statusChange',
        convert: (model, msg, publish, options) => {
            const zoneStatus = msg.data.zoneStatus;
            return {
                occupancy: (zoneStatus & 1<<1) > 0, // Bit 1 = Alarm 2: Presence Indication
                tamper: (zoneStatus & 1<<2) > 0, // Bit 2 = Tamper status
                battery_low: (zoneStatus & 1<<3) > 0, // Bit 3 = Battery LOW indicator (trips around 2.4V)
            };
        },
    },

https://github.com/Koenkk/zigbee2mqtt/commit/782287677dd0d00b1f18ebfe6b58f7e084b1457e for iAS cluster, zapp-cie

Would need it as well. So let me know how I can assist. :)

Cheers

**Comment by kluge86** [comment]
Any updates on this issue? 

Would really like to know if and how to integrate Osram motion sensor to iobroker.
