### ISSUE TITLE
Failed to start Zigbee  cc2531

### ISSUE THREAD

**Issue by OberstVonGatow** [ioBroker/ioBroker.zigbee#821]
Everything worked fine with my cc2531 raspberry pi 4 iobroker setup until yesterday.
Now nothing is working anymore. 
Every time i restart the raspberry the instance is starting without errors but i get errors as soon as i try to interact with a zigbee device.

When i then try to restart the instance the instance ist not starting correctly.
I didn't updated anything before the problem. After i got the errors i tried reinstalling the adapter but got the same problem again.

Here is the log in debug mode after reactivating the instance:
`
[iobroker.2020-10-21.log](https://github.com/ioBroker/ioBroker.zigbee/files/5416309/iobroker.2020-10-21.log)
2020-10-21 15:32:52.572  - [32minfo[39m: host.pihost "system.adapter.zigbee.0" enabled
--
  | 2020-10-21 15:32:52.606  - [32minfo[39m: host.pihost instance system.adapter.zigbee.0 started with pid 28558
  | 2020-10-21 15:32:53.927  - [34mdebug[39m: zigbee.0 (28558) Redis Objects: Use Redis connection: 127.0.0.1:9001
  | 2020-10-21 15:32:53.963  - [34mdebug[39m: zigbee.0 (28558) Objects client ready ... initialize now
  | 2020-10-21 15:32:53.967  - [34mdebug[39m: zigbee.0 (28558) Objects create System PubSub Client
  | 2020-10-21 15:32:53.969  - [34mdebug[39m: zigbee.0 (28558) Objects create User PubSub Client
  | 2020-10-21 15:32:53.970  - [34mdebug[39m: zigbee.0 (28558) Objects client initialize lua scripts
  | 2020-10-21 15:32:53.992  - [34mdebug[39m: zigbee.0 (28558) Objects connected to redis: 127.0.0.1:9001
  | 2020-10-21 15:32:53.999  - [34mdebug[39m: zigbee.0 (28558) objectDB connected
  | 2020-10-21 15:32:54.001  - [34mdebug[39m: zigbee.0 (28558) Redis States: Use Redis connection: 127.0.0.1:9000
  | 2020-10-21 15:32:54.007  - [34mdebug[39m: zigbee.0 (28558) States create User PubSub Client
  | 2020-10-21 15:32:54.009  - [34mdebug[39m: zigbee.0 (28558) States create System PubSub Client
  | 2020-10-21 15:32:54.017  - [34mdebug[39m: zigbee.0 (28558) States connected to redis: 127.0.0.1:9000
  | 2020-10-21 15:32:54.018  - [34mdebug[39m: zigbee.0 (28558) statesDB connected
  | 2020-10-21 15:32:54.024  - [31merror[39m: zigbee.0 (28558) zigbee.0 already running
  | 2020-10-21 15:32:54.025  - [33mwarn[39m: zigbee.0 (28558) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
  | 2020-10-21 15:32:54.545  - [31merror[39m: host.pihost instance system.adapter.zigbee.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
  | 2020-10-21 15:32:54.545  - [32minfo[39m: host.pihost Restart adapter system.adapter.zigbee.0 because enabled
  | 2020-10-21 15:33:06.161  - [31merror[39m: host.pihost instance system.adapter.zigbee.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
  | 2020-10-21 15:33:06.163  - [32minfo[39m: host.pihost Do not restart adapter system.adapter.zigbee.0 because desired by instance
  | 2020-10-21 15:33:16.237  - [31merror[39m: host.pihost instance system.adapter.zigbee.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
  | 2020-10-21 15:33:16.238  - [32minfo[39m: host.pihost Do not restart adapter system.adapter.zigbee.0 because desired by instance
  | 2020-10-21 15:33:24.582  - [32minfo[39m: host.pihost instance system.adapter.zigbee.0 started with pid 28576
  | 2020-10-21 15:33:25.898  - [34mdebug[39m: zigbee.0 (28576) Redis Objects: Use Redis connection: 127.0.0.1:9001
  | 2020-10-21 15:33:25.932  - [34mdebug[39m: zigbee.0 (28576) Objects client ready ... initialize now
  | 2020-10-21 15:33:25.936  - [34mdebug[39m: zigbee.0 (28576) Objects create System PubSub Client
  | 2020-10-21 15:33:25.938  - [34mdebug[39m: zigbee.0 (28576) Objects create User PubSub Client
  | 2020-10-21 15:33:25.939  - [34mdebug[39m: zigbee.0 (28576) Objects client initialize lua scripts
  | 2020-10-21 15:33:25.962  - [34mdebug[39m: zigbee.0 (28576) Objects connected to redis: 127.0.0.1:9001
  | 2020-10-21 15:33:25.968  - [34mdebug[39m: zigbee.0 (28576) objectDB connected
  | 2020-10-21 15:33:25.971  - [34mdebug[39m: zigbee.0 (28576) Redis States: Use Redis connection: 127.0.0.1:9000
  | 2020-10-21 15:33:25.976  - [34mdebug[39m: zigbee.0 (28576) States create User PubSub Client
  | 2020-10-21 15:33:25.979  - [34mdebug[39m: zigbee.0 (28576) States create System PubSub Client
  | 2020-10-21 15:33:25.987  - [34mdebug[39m: zigbee.0 (28576) States connected to redis: 127.0.0.1:9000
  | 2020-10-21 15:33:25.988  - [34mdebug[39m: zigbee.0 (28576) statesDB connected
  | 2020-10-21 15:33:26.133  - [32minfo[39m: zigbee.0 (28576) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.19.0, js-controller: 3.1.6
  | 2020-10-21 15:33:26.168  - [34mdebug[39m: zigbee.0 (28576) Using zigbee-herdsman with settings: {"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]},"databasePath":"/opt/iobroker/node_modules/iobroker.js-controller/../../iobroker-data/zigbee_0/shepherd.db","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"}}
  | 2020-10-21 15:33:26.170  - [32minfo[39m: zigbee.0 (28576) Starting Zigbee...
  | 2020-10-21 15:33:26.171  - [34mdebug[39m: zigbee.0 (28576) Starting zigbee-herdsman...
  | 2020-10-21 15:33:26.471  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter Path '/dev/ttyACM0' is valid for 'ZStackAdapter'
  | 2020-10-21 15:33:26.473  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"},"databasePath":"/opt/iobroker/node_modules/iobroker.js-controller/../../iobroker-data/zigbee_0/shepherd.db","databaseBackupPath":null,"backupPath":null,"adapter":null,"acceptJoiningDeviceHandler":null}'
  | 2020-10-21 15:33:26.477  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyACM0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
  | 2020-10-21 15:33:31.506  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:znp:log Serialport opened
  | 2020-10-21 15:33:47.094  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
  | 2020-10-21 15:33:47.097  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
  | 2020-10-21 15:33:48.106  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
  | 2020-10-21 15:33:48.111  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
  | 2020-10-21 15:33:54.115  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
  | 2020-10-21 15:33:54.117  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
  | 2020-10-21 15:34:00.119  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
  | 2020-10-21 15:34:00.121  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
  | 2020-10-21 15:34:06.124  - [31merror[39m: zigbee.0 (28576) Failed to start Zigbee
  | 2020-10-21 15:34:06.126  - [31merror[39m: zigbee.0 (28576) Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
  | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:89:31)
  | at Generator.throw (<anonymous>)
  | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
  | 2020-10-21 15:34:16.130  - [32minfo[39m: zigbee.0 (28576) Try to reconnect. 1 attempts left
  | 2020-10-21 15:34:16.131  - [32minfo[39m: zigbee.0 (28576) Starting Zigbee...
  | 2020-10-21 15:34:16.132  - [34mdebug[39m: zigbee.0 (28576) Starting zigbee-herdsman...
  | 2020-10-21 15:34:16.358  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter Path '/dev/ttyACM0' is valid for 'ZStackAdapter'
  | 2020-10-21 15:34:16.359  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"},"databasePath":"/opt/iobroker/node_modules/iobroker.js-controller/../../iobroker-data/zigbee_0/shepherd.db","databaseBackupPath":null,"backupPath":null,"adapter":null,"acceptJoiningDeviceHandler":null}'
  | 2020-10-21 15:34:16.361  - [34mdebug[39m: zigbee.0 (28576) zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyACM0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
  | 2020-10-21 15:34:21.424  - [31merror[39m: zigbee.0 (28576) Failed to start Zigbee
  | 2020-10-21 15:34:21.426  - [31merror[39m: zigbee.0 (28576) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
  | at Znp.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
  | at Generator.next (<anonymous>)
  | at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
  | at new Promise (<anonymous>)
  | at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
  | at SerialPort.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
  | at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
  | at /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12

`
Regards
Fabian

**Comment by apla2016** [comment]
I started to have similar problems with Zigbee behavior, having similar error messages. Re-flashing CC2531 or replacing it with different one did not help. Reinstalling Zidbee adapter did not help.

`

zigbee.0 | 2020-10-21 19:01:11.011 | error | at /opt/iobroker/node_modules/serialport/node_modules/@serialport/stream/lib/index.js:242:12
-- | -- | -- | --
zigbee.0 | 2020-10-21 19:01:11.011 | error | at SerialPort._error (/opt/iobroker/node_modules/serialport/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee.0 | 2020-10-21 19:01:11.011 | error | at SerialPort.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
zigbee.0 | 2020-10-21 19:01:11.011 | error | at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
zigbee.0 | 2020-10-21 19:01:11.011 | error | at new Promise (<anonymous>)
zigbee.0 | 2020-10-21 19:01:11.011 | error | at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
zigbee.0 | 2020-10-21 19:01:11.011 | error | at Generator.next (<anonymous>)
zigbee.0 | 2020-10-21 19:01:11.011 | error | at Znp.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
zigbee.0 | 2020-10-21 19:01:11.011 | error | (2285) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
zigbee.0 | 2020-10-21 19:01:11.010 | error | (2285) Failed to start Zigbee

`

**Comment by apla2016** [comment]
Which version of CC2531 firmware did you flash? I use CC2531_DEFAULT_20190608.

**Comment by OberstVonGatow** [comment]
I got a preinstalled Stick with this firmware 
[https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20190608.zip](https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20190608.zip)

**Comment by OberstVonGatow** [comment]
Strange behavior is also, if i unplug the stick and replug it and restart the instance, it works but only for one interaction (maybe 10 seconds) afterwards i get again Errors.
`(2627) Error on send command to 2. Error: Error: Command 2 genOnOff.off({}) failed (SRSP - AF - dataRequestExt after 6000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/`

**Comment by apla2016** [comment]
> I got a preinstalled Stick with this firmware
> https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20190608.zip

Thank you, I have same CC2531 firmware

**Comment by OberstVonGatow** [comment]
Took an easy way out because nothing else worked. Bought an Conbee 2 Stick and i'm using the deconz adapter for it.

**Comment by apla2016** [comment]
That's a good idea! I will do the same.

**Comment by apla2016** [comment]
> Took an easy way out because nothing else worked. Bought an Conbee 2 Stick and i'm using the deconz adapter for it.

How difficult was to setup Conbee? I configured it on my Windows PC, paired four Ikea bulbs, then plugged it into X64 Linux controller, installed adapter, got an Api key,  can see all four bulbs in Objects, everything looks good, but not able to turn bulbs ON/OFF. Any idea?

**Comment by OberstVonGatow** [comment]
Was pretty easy for me. Why did you configure it on Windows first? I installed the Software in the Raspberry and pluged it into the Raspberry. Then started the Software and configured everything over the Webinterface. I think you should check out the conbee documentation and if it is not working ask in a conbee/deconz forum/issue. I think here is not the right place for that 😉

**Comment by apla2016** [comment]
I was not able to install Deconz software on Linux controller. But, you are right, I will talk to tech support. Thank you!

**Comment by apla2016** [comment]
Was able to install Deconz, have to modify one of the config file to do it (with help of Deconz fortum) . Started Deconz, was able to connect to Conbee, decided to update firmware and that's it. After update system no longer sees Conbee. The worse part is that Amazon is out of stock, so I am not able to get a replacement... Bummer

**Comment by apla2016** [comment]
> Took an easy way out because nothing else worked. Bought an Conbee 2 Stick and i'm using the deconz adapter for it.

Hello. While waiting for Conbee replacement, I noticed Zigbee adapter update, I updated it and everything started to work. Will keep Conbee as backup...
