### ISSUE TITLE
Support Hue Fair 4033930P7

### ISSUE THREAD

**Issue by STDank** [ioBroker/ioBroker.zigbee#825]
Hello everybody,

I have moved all my Zigbee devices to a Raspberry with IOBroker and a cc2531. Except for one device, everything worked. Only my Hue Fair lamp 4033930P7 does not work. I reset the lamp to the factory settings and the pairing also works. I just keep getting the following error message in the log "error: zigbee.0 (1838) Device 0x001788010337dce2" 4033930P7 "not described in statesMapping." can somebody help me?
![Hue_Fair_info](https://user-images.githubusercontent.com/73409123/97095795-3e23b400-1664-11eb-8ba5-52fcd467fad0.png)
![Hue Fair_error](https://user-images.githubusercontent.com/73409123/97095796-411ea480-1664-11eb-8688-884f8824ff57.png)

**Comment by arteck** [comment]
done
