### ISSUE TITLE
Please add new Device iluminize 511-544

### ISSUE THREAD

**Issue by BigMike71** [ioBroker/ioBroker.zigbee#829]
please add support for  iluminize 511-544 (zigbee3.0-wand-dimmer-schalter-rgb-rgbw-rgbw 230V)

[Link]https://www.iluminize.com/de/shop/led-steuerung/led-controller/product/499-511-544-zigbee-wand-dimmer-schalter-rgb-rgbw-rgbws-led-4z.html

**Comment by arteck** [comment]
done
