### ISSUE TITLE
Install Zigbee Adpater

### ISSUE THREAD

**Issue by hail0** [ioBroker/ioBroker.zigbee#83]
Hi,

I have problems with the installion of the Zigbee adapter in IoBroker. I´m facing the follwoing error:

iobroker | 2018-10-20 11:20:46.590 | info | exit 13
-- | -- | -- | --
iobroker | 2018-10-20 11:20:46.574 | error | host.raspberrypi Cannot install zigbee
iobroker | 2018-10-20 11:20:46.569 | info | host.raspberrypi install adapter zigbee
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR!     /root/.npm/_logs/2018-10-20T09_20_46_468Z-debug.log
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR! A complete log of this run can be found in:
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR! Please check if you have git installed and in your PATH.
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR! Failed using git.
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR!
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR! No git binary found in $PATH
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR! undefined
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR!
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR! undefined ls-remote -h -t https://github.com/Koenkk/zcl-packet.git
iobroker | 2018-10-20 11:20:46.569 | info | npm ERR! code ENOGITnpm ERR! Error while executing:

BR Hail0

**Comment by kirovilya** [comment]
Try to reinstall. I fixed some dependences

**Comment by hail0** [comment]
Problem solved....Thx for your support.
