### ISSUE TITLE
Failed to remove device

### ISSUE THREAD

**Issue by CreatsheR** [ioBroker/ioBroker.zigbee#834]
Hi,

I want to remove my TRADFRI remote from the network, but it isn't working.
The Log says:

zigbee.0 | 2020-11-03 14:30:57.613 | error | at ZigbeeController.remove (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:358:65)
-- | -- | -- | --
zigbee.0 | 2020-11-03 14:30:57.613 | error | (1537) Failed to remove TypeError: Cannot read property 'stack' of undefined

Hardware is a Conbee II connected to a Raspberry Pi 4b running Raspbian Buster.
Coordinator firmware version: {"type":"ConBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":88,"maintrel":0,"revision":"0x26580700"}}

I already tried to reinstall the adapter but this made no difference. Any suggestions?

**Comment by kirovilya** [comment]
Try to update adapter from github

**Comment by CreatsheR** [comment]
This question may be stupid but: how can I do this? I installed the adapter out of ioBroker.

**Comment by kirovilya** [comment]
![image](https://user-images.githubusercontent.com/8360230/98143030-ac287080-1ed9-11eb-99dc-65d3f7753dd8.png)

**Comment by CreatsheR** [comment]
Great this version works. I had to force delete but it works.
