### ISSUE TITLE
Probleme mit Datenpunkten color und rgb

### ISSUE THREAD

**Issue by DennisMenger** [ioBroker/ioBroker.zigbee#836]
Ich nutze verschiedene Lampen mit dem Zigbee-Adapter über den Conbee II-Stick.

Bei einem habe ich Probleme mit den Datenpunkten bezüglich Color und RGB.

Beim OSRAM Smart+ LED-Stripe 27 W RGBW (im Adapter heißt der LIGHTIFY Indoor Flex RGBW)
Hier haben Änderungen in dem Datenpunkt "level.color.rgb" keine Auswirkungen.

Beim Datenpunkt "level.color.temperature" funktioniert es.

**Comment by arteck** [comment]
versuche die neue version 1.4.1

**Comment by linuxq** [comment]
Ich habe das gleiche Problem mit dem Osram RGB Stripe. Farbtemperatur kann ich ändern, Farbe funktioniert nicht. Ich nutze Version 1.4.3.

**Comment by linuxq** [comment]
![IMG_20210210_112001](https://user-images.githubusercontent.com/752355/107496775-08162b80-6b92-11eb-852e-8830bec9d214.jpg)
