### ISSUE TITLE
Backup data from CC2652R

### ISSUE THREAD

**Issue by BigMike71** [ioBroker/ioBroker.zigbee#839]
is this feature already built in like zigbee2mqtt?
"A backup of the CC2652R is taken at every shutdown of zigbee2mqtt, file can be found under data/coordinator_backup.json. This backup is automatically restored when starting with a new flashed CC2652R."

since the development is constantly going on on the firmware for the CC2652R and I flash the firmware again from time to time, an intregation would be nice

**Comment by arteck** [comment]
install new version and check again
