### ISSUE TITLE
Adding Sunricher SR-ZG9101FA-DIM device (takeover from zigbee2mqtt)

### ISSUE THREAD

**Issue by Wacho1** [ioBroker/ioBroker.zigbee#842]
I have a SR-ZG9101FA-DIM LED Dimmer which is unknown by the Zigbee Adapter. According the hardware, the manufacturer is Mextronic, also iluminize is possible. Would be great, if I can use the device also in ioBroker with the Zigbee Adapter. 

The ioBroker Zigbee Info gives following:

model:511.10
description:Zigbee LED-Controller
supports:on/off, brightness
model:DIM Lighting
type:Router
nwk:842
manuf id:4107
manufacturer:Sunricher
power:Mains (single phase)
app version:0
hard version:0
zcl version:3
stack version:0
date code:NULL
build:2.3.1_r21
interviewed:true
configured:false

endpoint:1
profile:260
input clusters:genBasic (0)
genIdentify (3)
genGroups (4)
genScenes (5)
genOnOff (6)
genLevelCtrl (8)
haDiagnostic (2821)
touchlink (4096)
output clusters:genOta (25)
touchlink (4096)
endpoint:242
profile:41440
output clusters:greenPower (33)

I found some entries in the device list of zigbee2mqtt project for "511.10" or "SR-ZG9101FA-DIM", maybe it is possible to take over these setting to this zigbee adapter?!

I have found also the following link, which looks similar to my hardware. 
[https://github.com/Koenkk/zigbee2mqtt/issues/1446](url)
 
Thanks,
Wacho

**Comment by arteck** [comment]
done
