### ISSUE TITLE
Battery Percent missing

### ISSUE THREAD

**Issue by TheMBeat** [ioBroker/ioBroker.zigbee#848]
All of my battery percentage displays are missing.  I've waited several days to weeks now, but they don't appear.

**Comment by TheMBeat** [comment]
Update: Only IKEA Remotes doesn't work.

**Comment by Hesse-Bub** [comment]
I guess I have the same issue, my Ikea devices did not update the battery datapoint since around 6 weeks.
But it is only a problem with the ikea battery devices, anything else has up to date battery data

**Comment by asgothian** [comment]
Current Adapter 1.4.1: Ikea remotes have battery percent.
