### ISSUE TITLE
Xiaomi Aqara Cube (MFKZQ01LM) (only fall & shake is working) 

### ISSUE THREAD

**Issue by Messiahs** [ioBroker/ioBroker.zigbee#851]
I switched from node red (node-red-contrib-zigbee) to Zigbee-Adapter (1.3.1).
After this, events like flip, slide and rotate are gone. 
Only events fall & shake are recognized.

Any ideas ?
[zigbee.log](https://github.com/ioBroker/ioBroker.zigbee/files/5533562/zigbee.log)

**Comment by kirovilya** [comment]
check battery

**Comment by Messiahs** [comment]
curious... now working (without battery change).
Thanks.
