### ISSUE TITLE
[SOLVED]SONOFF SNZB-03

### ISSUE THREAD

**Issue by spaxxilein** [ioBroker/ioBroker.zigbee#858]
Hi guys,

i cannot use the Sonoff device without crashing the iobroker zigbee adapter. The sensors sometimes adds fine and everything looks good, but the adapter crashes every ~1-2 minutes with the following error:

`
zigbee.0 | 2020-11-18 07:40:41.115 | warn | (32577) DeviceConfigure failed 0x00124b002247bd4f 66666, attempt 1 (Error: Bind 0x00124b002247bd4f/1 msTemperatureMeasurement from '0x00124b001938cbdc/1' failed (AREQ - ZDO - bindRsp after 10000ms)
-- | -- | -- | --
zigbee.0 | 2020-11-18 07:40:31.107 | info | (32577) Zigbee started
zigbee.0 | 2020-11-18 07:40:31.107 | info | (32577) 0x00124b002247bd4f (addr 4766): SNZB-03 - SONOFF Motion sensor (EndDevice)
zigbee.0 | 2020-11-18 07:40:31.106 | info | (32577) 0x001788011049ee47 (addr 58059): 324131092621 - Philips Hue dimmer switch (EndDevice)
zigbee.0 | 2020-11-18 07:40:31.104 | info | (32577) Configuring 0x00124b002247bd4f 66666
zigbee.0 | 2020-11-18 07:40:31.103 | info | (32577) Currently 2 devices are joined:
zigbee.0 | 2020-11-18 07:40:31.097 | info | (32577) --> transmitPower : normal
zigbee.0 | 2020-11-18 07:40:31.088 | info | (32577) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190223}}
zigbee.0 | 2020-11-18 07:40:29.234 | info | (32577) Installed Version: https://github.com/ioBroker/ioBroker.zigbee/commit/master
zigbee.0 | 2020-11-18 07:40:29.199 | info | (32577) Starting Zigbee npm ...
zigbee.0 | 2020-11-18 07:40:29.173 | info | (32577) starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.19.0, js-controller: 3.1.6
host.iobroker | 2020-11-18 07:40:28.746 | info | instance system.adapter.zigbee.0 started with pid 32577
host.iobroker | 2020-11-18 07:39:58.735 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.iobroker | 2020-11-18 07:39:58.733 | info | instance system.adapter.zigbee.0 terminated with code 0 (NO_ERROR)
zigbee.0 | 2020-11-18 07:39:58.225 | info | (32437) Terminated (NO_ERROR): Without reason
zigbee.0 | 2020-11-18 07:39:58.225 | info | (32437) terminating
zigbee.0 | 2020-11-18 07:39:57.988 | info | (32437) Zigbee: disabling joining new devices.
zigbee.0 | 2020-11-18 07:39:57.988 | info | (32437) cleaned everything up...
zigbee.0 | 2020-11-18 07:39:57.988 | error | at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
zigbee.0 | 2020-11-18 07:39:57.988 | error | at Generator.next (<anonymous>)
zigbee.0 | 2020-11-18 07:39:57.988 | error | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:339:27)
zigbee.0 | 2020-11-18 07:39:57.988 | error | (32437) Error: Command 0x00124b002247bd4f/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direct
zigbee.0 | 2020-11-18 07:39:57.987 | error | (32437) unhandled promise rejection: Command 0x00124b002247bd4f/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefault
Unhandled | 2020-11-18 07:39:57.987 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2020-11-18 07:38:46.260 | info | (32437) DeviceConfigure successful 0x00124b002247bd4f 66666`

I updated the adapter manually to Github 1.3.1 because with 1.2.1 in iobroker i cannot add the adapter at all.

Maybe you can figure out what the problem is.

DeviceConfigure successful 0x00124b002247bd4f 66666 is the Sonoff SNZB-03

I am running a CC2531 Zigbee USB Stick.

If you need any further info, please dont hesitate to ask.

Best Regards,

spaxxilein

**Comment by spaxxilein** [comment]
`30895) DeviceConfigure failed 0x00124b002247bd4f 66666, attempt 1 (Error: Bind 0x00124b002247bd4f/1 msTemperatureMeasurement from '0x00124b001938cbdc/1' failed (AREQ - ZDO - bindRsp after 10000ms)`

This seems really odd. Seems like problem is same as here: https://github.com/Koenkk/zigbee-herdsman-converters/issues/1449

But i dont know how to fix it. Please help

**Comment by Hyperion1181** [comment]
Hi,

for me it worked to change the modelid from 66666 to MS01 in the database file _(in my case: /opt/iobroker/iobroker-data/zigbee_0/shepherd.db)_ after this the device was recognized correctly.

Hope it works for you too.

Best regards

**Comment by spaxxilein** [comment]
> Hi,
> 
> for me it worked to change the modelid from 66666 to MS01 in the database file _(in my case: /opt/iobroker/iobroker-data/zigbee_0/shepherd.db)_ after this the device was recognized correctly.
> 
> Hope it works for you too.
> 
> Best regards

Thank you! This worked ;)
