### ISSUE TITLE
Please add support for Heiman HS1RC-N Smart Remote

### ISSUE THREAD

**Issue by olix74** [ioBroker/ioBroker.zigbee#859]
Hello, please add support for Heiman HS1RC-N smarte remote controller which is supported by zigbee2mqtt.
The device looks identical to the S9ZGBRC01 device but does not seem to be supported. The log says: 
(22726) Device 0x000d6f00104f28e4 "RC-EM" not described in statesMapping.
The device info lists:

   model:RC-EM
    type:EndDevice
    nwk:583
    manuf id:4619
    manufacturer:HEIMAN
    power:Battery
    app version:16
    hard version:16
    zcl version:2
    stack version:2
    date code:2017.11.1
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genPowerCfg (1)
    genIdentify (3)
    ssIasZone (1280)
    output clusters:genIdentify (3)
    ssIasAce (1281)

Is there anything else that you need to know?
Thank you very much and best regards,
Oliver

**Comment by arteck** [comment]
check new version

**Comment by olix74** [comment]
Hello "Arteck", first of all thank you for updating the Zigbee adapter.
The remotes are now detected successfully, but button press is not recogized.
I used "deconz" previously and they have a similar problem. It seems the "IAS Zone" (intended for security systems) needs to be enabled - can you guide me how to do that?
Thank you,
Oliver
