### ISSUE TITLE
Support for PTVO configúre able Firmware 

### ISSUE THREAD

**Issue by schwaigi** [ioBroker/ioBroker.zigbee#860]
Is it possible to add most common Sensors in devices like ds18b20 dht11/22 ?
would be great to build own Sensor-devices.

**Comment by ericsboro** [comment]
+ 1 here
I'm moving from wifi devices to DIY zigbee and this would be perfect opportunity

**Comment by asgothian** [comment]
Please provide more information:
- where should sensors be added ?
- How will they send their data to the Zigbee network.

**Comment by schwaigi** [comment]
HyI tried to build CC25xx boards with ds18b20  like described here:https://ptvo.info/zigbee-configurable-firmware-features/I'm not sure how data string looks likeI've seen code frome zigbee-herdsman-converters (koenkk) Devices.js few Days agoMaybe in next update it will work automaticly...zigbeeModel: ['ptvo.switch'], model: 'ptvo.switch', vendor: 'Custom devices (DiY)', description: '[Multi-channel relay switch](https://ptvo.info/zigbee-switch-configurable-firmware-router-199/)';, fromZigbee: [fz.on_off, fz.ptvo_multistate_action, fz.legacy.ptvo_switch_buttons, fz.ptvo_switch_uart, fz.ptvo_switch_analog_input, fz.brightness, fz.ignore_basic_report], toZigbee: [tz.ptvo_switch_trigger, tz.ptvo_switch_uart, tz.ptvo_switch_analog_input, tz.ptvo_switch_light_brightness, tz.on_off], exposes: [ e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.switch().withEndpoint('l3'), e.switch().withEndpoint('l4'), e.switch().withEndpoint('l5'), e.switch().withEndpoint('l6'), e.switch().withEndpoint('l7'), e.switch().withEndpoint('l8'), exposes.text('', exposes.access.STATE).withEndpoint('l1').withProperty('l1'), exposes.text('', exposes.access.STATE).withEndpoint('l2').withProperty('l2'), exposes.text('', exposes.access.STATE).withEndpoint('l3').withProperty('l3'), exposes.text('', exposes.access.STATE).withEndpoint('l4').withProperty('l4'), exposes.text('', exposes.access.STATE).withEndpoint('l5').withProperty('l5'), exposes.text('', exposes.access.STATE).withEndpoint('l6').withProperty('l6'), exposes.text('', exposes.access.STATE).withEndpoint('l7').withProperty('l7'), exposes.text('', exposes.access.STATE).withEndpoint('l8').withProperty('l8'), e.temperature(), e.voltage(), e.pressure(), e.humidity(), e.action(['single', 'double', 'triple', 'hold'])], meta: {multiEndpoint: true}, endpoint: (device) => { return {l1: 1, l2: 2, l3: 3, l4: 4, l5: 5, l6: 6, l7: 7, l8: 8, action: 1}; }, },Thanks for your work Best ReggardsToni-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.12.20, 00:46 schrieb asgothian <notifications@github.com>:

   
  Please provide more information: 
   
   where should sensors be added ? 
   How will they send their data to the Zigbee network.

**Comment by asgothian** [comment]
Please fix the post. The link goes nowhere and the code needs do be in extended code tags. It is next to unreadable in its current form.

**Comment by schwaigi** [comment]
here the Code from [Zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters) Devices.js :

`{ zigbeeModel: ['ptvo.switch'], model: 'ptvo.switch', vendor: 'Custom devices (DiY)', description: '[Multi-channel relay switch](https://ptvo.info/zigbee-switch-configurable-firmware-router-199/)', fromZigbee: [fz.on_off, fz.ptvo_multistate_action, fz.legacy.ptvo_switch_buttons, fz.ptvo_switch_uart, fz.ptvo_switch_analog_input, fz.brightness, fz.ignore_basic_report], toZigbee: [tz.ptvo_switch_trigger, tz.ptvo_switch_uart, tz.ptvo_switch_analog_input, tz.ptvo_switch_light_brightness, tz.on_off], exposes: [ e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.switch().withEndpoint('l3'), e.switch().withEndpoint('l4'), e.switch().withEndpoint('l5'), e.switch().withEndpoint('l6'), e.switch().withEndpoint('l7'), e.switch().withEndpoint('l8'), exposes.text('', exposes.access.STATE).withEndpoint('l1').withProperty('l1'), exposes.text('', exposes.access.STATE).withEndpoint('l2').withProperty('l2'), exposes.text('', exposes.access.STATE).withEndpoint('l3').withProperty('l3'), exposes.text('', exposes.access.STATE).withEndpoint('l4').withProperty('l4'), exposes.text('', exposes.access.STATE).withEndpoint('l5').withProperty('l5'), exposes.text('', exposes.access.STATE).withEndpoint('l6').withProperty('l6'), exposes.text('', exposes.access.STATE).withEndpoint('l7').withProperty('l7'), exposes.text('', exposes.access.STATE).withEndpoint('l8').withProperty('l8'), e.temperature(), e.voltage(), e.pressure(), e.humidity(), e.action(['single', 'double', 'triple', 'hold'])], meta: {multiEndpoint: true}, endpoint: (device) => { return {l1: 1, l2: 2, l3: 3, l4: 4, l5: 5, l6: 6, l7: 7, l8: 8, action: 1}; }, },`

**Comment by asgothian** [comment]
Using exposes, this device should already be supported. I would need access to a device flashed with the configurable firmware to verify and debug the exposes for this device. I cannot use the linked tools due to a complete lack of windows computers.

A.

**Comment by schwaigi** [comment]
Will try in next npm update with new herdsman...
Thanks

**Comment by schwaigi** [comment]
Hello Again
Tested with Vers.1.4.2
Only switch states  will be created no sensor states.
I installed Zigbee2mqtt and get a sring with the temperature..  maybe you can add missing states 
here the Zigbee2mqtt string:

`Zigbee2MQTT:info  2021-01-03 23:33:11: MQTT publish: topic 'zigbee2mqtt/PTVO-switch', payload '{"device_l1":"28-FF-95-79-97-19-03-F8","l1":21.375,"linkquality":239,"state_l3":"OFF","state_l4":"OFF","state_l5":"OFF","temperature_l1":21.4}'

Here´s a string with 2 Sensors ..the state is allways l1 only the hex address changes : 

`Zigbee2MQTT:info  2021-01-04 00:06:27: MQTT publish: topic 'zigbee2mqtt/0x00124b001241fa68', payload '{"device_l1":"28-51-03-07-D6-01-3C-DE","l1":22.75,"linkquality":243,"state_l3":"OFF","state_l4":"OFF","state_l5":"OFF","state_l6":"OFF","state_l7":"OFF","state_l8":"OFF","temperature_l1":22.8}'
Zigbee2MQTT:info  2021-01-04 00:06:27: MQTT publish: topic 'zigbee2mqtt/0x00124b001241fa68', payload '{"device_l1":"28-FF-95-79-97-19-03-F8","l1":21.875,"linkquality":243,"state_l3":"OFF","state_l4":"OFF","state_l5":"OFF","state_l6":"OFF","state_l7":"OFF","state_l8":"OFF","temperature_l1":21.9}'`

for DHT11/22 i,m not sure how string looks like will try to test.

best reggards 
Toni

**Comment by asgothian** [comment]
I am afraid that i will need some form of access to a running device to either
- Fix the exposes to work with the exposed information
- implement the required states directly in ioBroker.

The string alone can be a basis for an initial implementation but it would only solve the issue for the current firmware configuration.

This device is not easy to support in iobroker due to the fact that its datapoint are variable and a device with the same hardware ID can require different DP layouts.

Access can be either a device provided for testing (it will be returned) or some form of remote access to a system where such a device is paired to.

**Comment by schwaigi** [comment]
Send me a Delivery Adress to a.schwaigi@gmx.net
I'll send you a Test kit

**Comment by asgothian** [comment]
Initial setup is available at this branch of my fork: https://github.com/asgothian/ioBroker.zigbee/tree/ptvo_on_tour

(install in iobroker from https://github.com/asgothian/ioBroker.zigbee/tarball/ptvo_on_tour)

What works:
- switch status is reported by the switch
- sensor status is reported by the switch
- reporting interval can be set
- multiple sensors on the same input can be used.
What doesnt work:
- naming is iffy
- switches cannot be set from iobroker currently
- the image is wrong

A.

**Comment by schwaigi** [comment]
working gr8 thanks a lot 👍

**Comment by asgothian** [comment]
Improved version is up now. There were a few issues which i managed to improve:

- naming is better
- image is fixed
- multi sensors work even if they do not have different HW id's
- switches can be controlled

Unfortunately, this breaks a few things, so it makes sense to delete all states for existing pvto devices before updating the adapter.

Please reinstall from the same address as before and test.

If this works i will see if we can get this merged into the main tree.

**Comment by schwaigi** [comment]
Hallo

Habe den Adapter de und dann neu Installiert
Bild wird erkannt , ds18b20 ebenfalls.
Nur Hardware switching funktioniert nicht mehr 
Der State leuchtet kurz grün auf bleibt aber auf false.
Software-switching wird noch getestet.(gemessen)
Bmp noch nicht getestet.

Werden States jetzt automatisch getriggert ?
Analog input (VDC) z.b. wird nicht erkannt .
Weitere tests folgen .

Thanks&Greets Toni

**Comment by schwaigi** [comment]
Hier ein sring mit Voltage:

Zigbee2MQTT:info  2021-02-09 09:21:59: MQTT publish: topic 'zigbee2mqtt/0x00124b00123c74e7', payload '{"l3":0.233,"linkquality":70,"state_l1":"OFF","state_l2":"ON","voltage_l3":0.2}'

**Comment by schwaigi** [comment]
Testreporting 1.4.3 PTVO_on_tour V2:
BMP/E280            --->  working
DS18b20              ---> working (max 4 as described)
Analog in             ---> no state (Voltage_Lx) (only 1 simultan --> high Power consumption)
Switching via SW ---> not working  (fallback to ground state after some time, no action on HW)
Switching via HW ---> State don´t change (only short green blink)
Image & naming ---> OK

**Comment by asgothian** [comment]
I have updated the branch with
- additional functionality
- additional logging functions.

Can you please test especially the things which do not work and post (if available) the warning messages generated for your test ?
The adapter should generate 2 warning messages for every successfully handled message to a ptvo.switch unit, similar to these:

```
2021-02-10 15:22:00.466  - warn: zigbee.0 (10254) publishToState caught {"l5":19.188,"device_l5":"28-51-03-07-D6-01-3C-DE","temperature_l5":19.2}for 00124b001241fa68
2021-02-10 15:22:00.467  - warn: zigbee.0 (10254) publishtoState: detected value {"stateid":"28510307D6013CDE_temperature","value":19.188,"name":"temperature 0x28510307D6013CDE","unit":"C","role":"temperature"}

```

A.

**Comment by schwaigi** [comment]
V3 tested
DS18b20 OK
BMP280 OK

Analog input not working 
`zigbee.0	2021-02-10 23:39:53.494	warn	(9500) publishToState caught {"l2":265.6,"voltage_l2":265.6}for 00124b00123c74e7
zigbee.0	2021-02-10 23:39:53.488	warn	(9500) publishtoState: detected value 49`

GPIO:

Inputs linked to an output  no change in states 
State is not switchable from IOBroker 
`zigbee.0	2021-02-11 00:06:25.603	warn	(4880) publishToState caught {"state_l3":"OFF"}for 00124b00123c74e7
zigbee.0	2021-02-11 00:06:25.601	warn	(4880) publishtoState: detected value 55
zigbee.0	2021-02-11 00:07:26.229	warn	(4880) publishToState caught {"state_l1":"ON"}for 00124b00123c74e7
zigbee.0	2021-02-11 00:07:26.226	warn	(4880) publishtoState: detected value 60`

Input without linking to output  :
Single double tripple detect ok (in Firmware an option  for "long press" also would exists)
State when set as switch or toggle mode dont stay true or false (just a sek state is true)

`zigbee.0	2021-02-11 00:18:31.433	warn	(4880) publishToState caught {"click":"l5_single"}for 00124b00123c74e7
zigbee.0	2021-02-11 00:18:31.433	warn	(4880) publishtoState: detected value true`



important for inputs would be "switch" mode to handle i.e.  reedcontacts or coupling relay etc. 
double tripple toggle etc isnt necessary  can be done by scripts.

outputs without linking to any input working correct (state switchable by IOBroker )


Greets Toni

**Comment by asgothian** [comment]
New update: the voltage state should work with the latest version of my branch. I did not have the time to dig through the click and linked states issue as i cannot test them with the unit i have. I need to read more on the actual unit to hook up a switch or two to test this.

Note: there is a bug in the version which makes the adapter crash should you try to use the "state cleanup" button. Once this is fixed i will see to merge this version into the main adapter, but still see if i can get the switches and presses to work correctly.

A.

**Comment by schwaigi** [comment]
Hello
Voltage is Working correct  👍


Info:
In new Masterbranch 1.4.4 switch behavior is working good ( only double long etc don't work)

Greets 
Toni

**Comment by schwaigi** [comment]
Now tested 1.4.5 
If it goes to npm users have to exclude ptvo to get the standard switch setting.

Attached a Firmware (test-setting like image)
I always use just a wire to gnd to emulate switching.
Texas Instruments provide Uniflasher for Linux Systems
https://software-dl.ti.com/ccs/esd/uniflash/uniflash_sl.6.2.0.3059.run
   
[test1-ptvo.zip](https://github.com/ioBroker/ioBroker.zigbee/files/6018129/test1-ptvo.zip)
![setting](https://user-images.githubusercontent.com/57870693/108632598-23294b00-7470-11eb-9f2b-00e21da6846a.png)

**Comment by asgothian** [comment]
I'll try that one. I do intend to ensure that the switches will work with the dedicated implementation as well. Unfortunately, i was away for a few days and need a few more before i can get back to it.

A.

**Comment by schwaigi** [comment]
Beim aktuellen Git- Master funktioniert Ptvo Firmware perfekt..
Vielen dank ..
Eine frage hab ich noch :
Wie bzw. von welcher Wurzel/Pfad aus müssen eigene exposes.js eingetragen/gespeichert werden... ( externe Converter) in der Einstellungs Karte ?
Kann nichts zu dieser neuen funktion finden 
!
[Screenshot_20210320-193354](https://user-images.githubusercontent.com/57870693/111881960-3ec23b80-89b3-11eb-9d4a-d90e82dff3ca.png)

**Comment by asgothian** [comment]
These should be read from /opt/iobroker/iobroker-data/zigbee_0

But i haven't tried that yet.

A.

**Comment by schwaigi** [comment]
Guess can be closed 
Everything is working in git-master version

Thanks & Greets

**Comment by asgothian** [comment]
I am very glad it does. Again thank you very much for providing the hardware so this could be implemented.

A.

**Comment by wlad1m** [comment]
Hallo zusammen,
ich versuche seit ein paar Tagen ein DS18b20 mit CC2530 ans laufen zu bringen.
Leider ohne nennenswerte erfolg.
In zigbee adapter wird das Gerät als DIY ptvo.switch erkannt
aber ich bekomme keine werte. Liegt wahrscheinlich an irgendeine fehlende Konfiguration?

Kann mir einer bitte helfen?

Laut Post von schweigi am 11.02.2021 ist DS18b20 getestet und funktioniert.

Ich habe zigbee Adapter version 1.8.10

`New device joined '0x00124b000cb52616' model ptvo.switch
Interview successful: {"friendly_name":"0x00124b000cb52616","model":"ptvo.switch","vendor":"Custom devices 
(DiY)","description":"[Multi-channel relay switch](https://ptvo.info/zigbee-switch-configurable-firmware-router-199/)","supported":true}`
![objekte3](https://user-images.githubusercontent.com/61880047/228602693-df63f0b1-ec0c-46fb-b239-3c4648113dae.JPG)
