### ISSUE TITLE
Add new device Philips Hue Nyro please

### ISSUE THREAD

**Issue by xxxTODxxx** [ioBroker/ioBroker.zigbee#862]
Hello,
can you add the new device Philips Hue Nyro please. Thx

![grafik](https://user-images.githubusercontent.com/5030829/99978548-5f340d80-2da6-11eb-8e5a-5d0b32b00c5c.png)

Link to zigbee2mqtt: https://www.zigbee2mqtt.io/devices/1745630P7.html

**Comment by kirovilya** [comment]
try to install version from github

**Comment by xxxTODxxx** [comment]
Pairing works, the color.rgb also, but I cant change back to the white mode. If I change the color.temperatur it is still in the rgb mode. The same Problem in material.io, i can't change back to the white mode.

![Screenshot 2020-11-23 202110](https://user-images.githubusercontent.com/5030829/100015460-47757d00-2dd8-11eb-9771-372c750bcfad.jpg)

And a small picture in objects is missing. (not so important)

**Comment by xxxTODxxx** [comment]
Brightness and color works fine, but if I change the color temperature to 182 daylight, 370 warmwhite or 143 coldwhite, nothing happens. No matter if I change it manuall, with alexa or the material.io app. The value change in objects, but the lamp dont change to the white color.

**Comment by arteck** [comment]
check now

**Comment by xxxTODxxx** [comment]
Thanks, works now. :-)
