### ISSUE TITLE
Please, add working Sonoff ZBMINI to devices.js

### ISSUE THREAD

**Issue by orghol** [ioBroker/ioBroker.zigbee#864]
I sucessfully added the Sonoff  Zigbee Two Way Smart Switch.
https://www.itead.cc/sonoff-zbmini-zigbee-smart-switch.html

![image](https://user-images.githubusercontent.com/73031520/100085800-c906f280-2e4c-11eb-836c-9713ff0a7e24.png)
![image](https://user-images.githubusercontent.com/73031520/100086745-1d5ea200-2e4e-11eb-8474-24530972d02d.png)

**Below the configuration:**
in zigbee-herdsman-converters:
{
   zigbeeModel: [‘01MINIZB’],
   model: ‘01MINIZB’,
   vendor: ‘SONOFF’,
   description: ‘Zigbee Two Way Smart Switch’,
   extend: generic.switch,
   fromZigbee: [fz.on_off_skip_duplicate_transaction],
},

in iobroker.zigbee/lib:
{
   models: [‘01MINIZB’],
   icon: ‘img/ITEAD01ZBMINI.png’,
   states: [states.state],
},
![ITEAD 01ZBMINI](https://user-images.githubusercontent.com/73031520/100086389-a1fcf080-2e4d-11eb-8e8f-af64ab891dc8.png)
The picture was pasted into the image library.

Please, add to the next release.
Thanks,

Carlo

**Comment by kirovilya** [comment]
Try to install version from github (without modifications above)

**Comment by numberdotone** [comment]
Installed around 0900 PM CEST today
Works fine with 1.3.9dev
Image is missing on devices overview and network map

modelZigbee: 01MINIZB
model: ZBMINI
description: Zigbee two way smart switch
"On/off state of the switch" switch between ON and OFF ;-)

thx for integration!

**Comment by orghol** [comment]
Hi kirovilya,

I installed 
![image](https://user-images.githubusercontent.com/73031520/100202799-142f0d00-2f02-11eb-8cf5-96fcce2b3d4d.png)
and removed the entries above.
After zigbee instance restart I get the error:

>> (25913) Device 0xec1bbdfffe31f1fe "01MINIZB" not described in statesMapping.
>> (25913) 0xec1bbdfffe31f1fe (addr 45441): Not supported (model 01MINIZB)(Router)

![image](https://user-images.githubusercontent.com/73031520/100202964-46d90580-2f02-11eb-8c72-6b3fceebdf44.png)

What to do?

Regards, Carlo

**Comment by kirovilya** [comment]
@orghol "from github", not from "latest" :)
will release soon

**Comment by orghol** [comment]
@kirovilya 
Results:
(26743) starting. Version 1.3.9-dev in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.19.1, js-controller: 3.1.6
>> no error messages
>> uploaded image via GUI -> worked
>> devices -> 
![image](https://user-images.githubusercontent.com/73031520/100238552-a1895600-2f30-11eb-8fbe-d0c9e82f19d4.png)
>> network map ->
![image](https://user-images.githubusercontent.com/73031520/100238774-e1e8d400-2f30-11eb-93a3-90ab5a25abd5.png)

Thx, waiting for the stable release.
regards, orghol

**Comment by numberdotone** [comment]
Hi kirovilya,


don't know if reopen the issue or create a new one or if it's a topic at my side: Icon within the object list / overview is still not available. Placeholder is a question mark. 

Can I do something by myself?

Bregs

no.1

**Comment by kirovilya** [comment]
@numberdotone  what version of the adapter do you have? show how the page looks like

**Comment by numberdotone** [comment]
Hi ilya,

it's the stable version 1.5.6

I added today 2 additional ZBMINI and the overview shows this time for both devices nothing and still the question mark for the old one. Is there some kind of cache to delete?

![image](https://user-images.githubusercontent.com/25619572/143722899-dabd23d8-0aee-4791-938c-e63956531fb5.png)

**Comment by numberdotone** [comment]
sorry, didn't know that's possible to add own icons. This is what I did now!

![image](https://user-images.githubusercontent.com/25619572/143782879-1fcaf48a-1f22-4548-8be1-9396a070310f.png)
