### ISSUE TITLE
Device "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping

### ISSUE THREAD

**Issue by derFeierabend** [ioBroker/ioBroker.zigbee#865]
I'd love to have access to my "QS-Zigbee-D02-TRIAC-2C-LN". But unfortunately it does not show up as objects in my iobroker like other devices. The log tells me that it was successfully interviewed and paired, but it was not able to configure it (see log below).

The displayed device info is:

    model:TS0121_plug
    description:10A UK or 16A EU smart plug
    supports:on/off, power measurements

    model:TS0121
    type:Router
    nwk:42384
    manuf id:4098
    manufacturer:_TZ3000_g5xawfcq
    power:Mains (single phase)
    app version:65
    hard version:1
    zcl version:3
    stack version:0
    date code:
    interviewed:true
    configured:true

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    seMetering (1794)
    haElectricalMeasurement (2820)
    output clusters:genOta (25)
    genTime (10)

And the Logfile:

info: zigbee.0 (1774) Zigbee: allowing new devices to join.
info: zigbee.0 (1774) Starting interview of '0xbc33acfffe656251'
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
....
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
info: zigbee.0 (1774) Successfully interviewed '0xbc33acfffe656251', device has succesfully been paired
info: zigbee.0 (1774) Device '0xbc33acfffe656251' is supported, identified as: Lonsonho 2 gang smart dimmer switch module with neutral (QS-Zigbee-D02-TRIAC-2C-LN)
info: zigbee.0 (1774) Configuring 0xbc33acfffe656251 TS110F
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
...
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
error: zigbee.0 (1774) Device 0xbc33acfffe656251 "QS-Zigbee-D02-TRIAC-2C-LN" not described in statesMapping.
warn: zigbee.0 (1774) **DeviceConfigure failed 0xbc33acfffe656251 TS110F, attempt 1 (Error: ConfigureReporting 0xbc33acfffe656251/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 6808 - 1 - 95 - 6 - 7 after 10000ms)
at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)**
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7))
info: zigbee.0 (1774) Zigbee: stop joining

Playing around in expert mode, i discovered the following, without knowing what I do:

- Reading of genLevelCtrl currentLevel worked
- Also writing. Because written value can be read out later.
- Connected light bulb did not change brightness according to written value
- Reading of genOnOff onOff worked. (light on: value 1, light off: value 0)
- Writing of genOnOff does not work, "Zigbee error 136 received!"

Any comment is welcome,
auch natürlich auf deutsch.   ;-)

**Comment by kirovilya** [comment]
try to install adapter verison from github

**Comment by derFeierabend** [comment]
Updated from V1.3.1 to github Version 1.3.9dev      --->   now "TS110F"  is working!

Thank's a lot!
Richard

**Comment by derFeierabend** [comment]
Updated from V1.3.1 to github Version 1.3.9dev ---> now "TS110F" is working!

Thank's a lot!
Richard
