### ISSUE TITLE
DEV 1.3.9 No Network Map

### ISSUE THREAD

**Issue by spaxxilein** [ioBroker/ioBroker.zigbee#866]
Hey guys, i am getting the following error in the chrome console when opening the network drive:

`DevTools failed to load SourceMap: Could not load content for http://192.168.178.2:8081/adapter/zigbee/vis-network.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

I see all devices in red, but they are not connected to the coordinator and also the other routers (osram plugs, hue bulbs) are not connected to each other.

I already tried iobroker upload all, but it stays the same.

Hope somebody has an idea.

Thanks in advance!

**Comment by olix74** [comment]
Hello, sorry I can't help, but I have similar problem with my Cobee2 based network. Network is working (kind of) but absolutely no links are shown and link quality in device list seems to be "random". I have never seen above error message though. Best regards, Oliver

P.S.: I have a parallel installation of Phoscon/ deconz on another Raspberry PI. So I can physicaly switch the USB cable of the CONBEE 2 from the "IOBROKER Raspi" to the "Phoscon/deconz RASPI" without moving the CONBEE 2 a single milimeter - on Deconz the network is building up quickly and has a very vivid mesh - so it not a general network issue. I'm using latest CONBEE 2 firmware deCONZ_ConBeeII_0x26670700.bin.GCF. If there is any recommendation on which firmware to use, I would appreciate any hints

**Comment by kirovilya** [comment]
You can read this thread about Conbee and z2m (similar iobroker.zigbee).
https://github.com/Koenkk/zigbee2mqtt/issues/4039
