### ISSUE TITLE
cant set Setpoint due to [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by MiracelVip** [ioBroker/ioBroker.zigbee#868]
`2020-12-01 15:14:11.884 - error: zigbee.0 (1081) Error on send command to 0x00158d0003c45e62. Error: RangeError [ERR_OUT_OF_RANGE]: Write 0x00158d0003c45e62/1 hvacThermostat({"localTemperatureCalibration":250}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (The value of "value" is out of range. It must be >= -128 and <= 127. Received 250)`

I try to set the localTemperatureCalibration to 25 °C but in the log, I can find that it tries to send 250
![image](https://user-images.githubusercontent.com/28352461/100752044-5e275f80-33e8-11eb-9c69-d3e08fdcb10b.png)
![image](https://user-images.githubusercontent.com/28352461/100752102-71d2c600-33e8-11eb-8efb-76468de9305a.png)
![image](https://user-images.githubusercontent.com/28352461/100752143-82833c00-33e8-11eb-8900-aa1c24fa9c39.png)

**Comment by asgothian** [comment]
Same as #815
