### ISSUE TITLE
Looks like the Model BW-IS2 manufactured by BlitzWolf is released in a new version which is not supported.

### ISSUE THREAD

**Issue by MirkoHuf** [ioBroker/ioBroker.zigbee#869]
Hi, 
I can found the Model BW-IS2 manufactured by BlitzWolf on all the "supported devices Lists"
https://github.com/ioBroker/ioBroker.zigbee/wiki/Supported-devices
https://zigbee.blakadder.com/BlitzWolf_BW-IS2.html

But I have such a device - labelt with BW-IS2 - and it's not supported.
I attached a screen from the pairing process.

![image](https://user-images.githubusercontent.com/7764831/100920901-13870f80-34dc-11eb-856c-57486104b9ed.png)

Is there anything I can do to support you to add these device into the list of known devices?

Thanks in advance.
BR
Mirko

**Comment by asgothian** [comment]
Please verify if this issue remains with the 1.4.1 versiin

**Comment by MirkoHuf** [comment]
Hi - looks good now. Thanks!
