### ISSUE TITLE
Bought some Silvercrest devices today...

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.zigbee#871]
Occupancy Sensor works pretty well.
The switched Power outlet also works.

The "Silvercrest HG06338" doesn't work. Its registered and shown in the objects. The state is refreshed when switched at the device. Switching in the broker causes an error.

`zigbee.0 2020-12-03 13:42:31.248 error (18961) No converter available for 'HG06338' with key 'state_l1'`

The device doesnt switch the outlet on or off.

The e27 light bulb is recognized as an TS0502A. The state can be switched but all other Data points are empty. 
I am using the 1.3.9dev adapter version because in the 1.3.1 version the devices aren't recognized correct.

**Comment by kirovilya** [comment]
try to update from github and test

**Comment by BigDi** [comment]
I updated the adapter aber error still exists.

**Comment by Dragon0501** [comment]
Works perfect! Thank you very much!

**Comment by Dragon0501** [comment]
Is it possible to add the usb ports as switchable device?

**Comment by BigDi** [comment]
The adapter don't restarts after update. I restarted the adapter and now it works. Many thanks!
