### ISSUE TITLE
Please add Silvercrest HG06335 (Lidl)

### ISSUE THREAD

**Issue by kemenap** [ioBroker/ioBroker.zigbee#875]
it is supported https://www.zigbee2mqtt.io/devices/HG06335.html
Thanks !

**Comment by hanwel** [comment]
works fine with the Conbee2, but not with the CC26X2R1 
(271273) Failed to interview '0x680ae2fffe06e40b', device has not succesfully been paired. undefined

**Comment by DcFamas** [comment]
Works fine for me with the CC26X2R1:

**Comment by hanwel** [comment]
> Works fine for me with the CC26X2R1:
> `(4973) Device '' is supported, identified as: Lidl Silvercrest smart motion sensor (HG06335)`

strange. What firmware version and adapter version are you using?

**Comment by kemenap** [comment]
CC2531 with firmware 20190608. It's found, but there are no dates.

**Comment by alook90** [comment]
The Silvercrest HG06335 device is also not working with the LAUNCHXL-CC1352P-2

`(2753) Failed to interview '0xbc33acfffe501ae5', device has not succesfully been paired. undefined`

with firmware

`Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20201026}}`

and adapter version

`Installed Version: iobroker.zigbee@1.4.0`
