### ISSUE TITLE
Coordinator card

### ISSUE THREAD

**Issue by markus2701** [ioBroker/ioBroker.zigbee#876]
Stick ist CC2531

![2020-12-04 07_16_26-zigbee-0 - ioBroker](https://user-images.githubusercontent.com/6629158/101129040-2810f800-3601-11eb-95dd-d1f97439526b.png)

**Comment by o0shojo0o** [comment]
Hatte ich auch, drück bitte einmal den Upload Button.

![image](https://user-images.githubusercontent.com/19333515/101129683-593df800-3602-11eb-845a-0559eba721d0.jpeg)

**Comment by markus2701** [comment]
Version und Revision wird noch nicht angezeigt

![2020-12-04 07_45_14-zigbee-0 - ioBroker](https://user-images.githubusercontent.com/6629158/101131007-db2f2080-3604-11eb-9125-b4ef29e92dde.png)

**Comment by o0shojo0o** [comment]
@asgothian kann es sein, dass deine Pull Probleme mit einen  TCP angebundenen Coordinator hat?

**Comment by markus2701** [comment]
Also im Log bekomme ich die Meldung:

(2210) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
--

**Comment by asgothian** [comment]
Please check with the latest GitHub version. I did some things which should make it more stable.

A.

**Comment by asgothian** [comment]
closed - issue should be fixed in 1.4.1
