### ISSUE TITLE
Please add the new lidl smart-plug CH Version

### ISSUE THREAD

**Issue by kilasat** [ioBroker/ioBroker.zigbee#878]
Installed Adapter Verison 1.3.9dev.

Hardware: modcam.ru V3

HG06337-CH

https://zigbeealliance.org/zigbee_products/lidl-home-smart-plug-4/

![image](https://user-images.githubusercontent.com/42370557/101168751-2dd7ff00-363c-11eb-92a8-ca373df354ca.png)

![image](https://user-images.githubusercontent.com/42370557/101168769-3597a380-363c-11eb-98b8-b55a32f8c7f5.png)

**Comment by kirovilya** [comment]
did not see zigbeeModel?

**Comment by kilasat** [comment]
![image](https://user-images.githubusercontent.com/42370557/101173804-531c3b80-3643-11eb-946f-f9aea508f3f9.png)

**Comment by EdgarM73** [comment]
Hi,

I am unfortunatly not able to bind the lidl device:

Interview successful: [object Object]
Pairing time left: 59
Error: Device 0xec1bbdfffe79d579 "TY0202" not described in statesMapping.. undefined
New device joined '0xec1bbdfffe79d579' model TY0202
Interview successful: [object Object]
Pairing time left: 60

**Comment by kirovilya** [comment]
try 1.4.0 version
