### ISSUE TITLE
New device: ZBT-DIMController-D0800

### ISSUE THREAD

**Issue by quotschmacher** [ioBroker/ioBroker.zigbee#879]
it is a tint remote. currently (1.3.9dev) it can be discovered, but is not recognized. detailed description can be found here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2906

**Comment by asgothian** [comment]
Please verify if this persists with 1.4.1.

A.

**Comment by quotschmacher** [comment]
just updated to the actual github version.
the problem dows not really persist - it kind of changed.

```Device '0x00158d0002d501c4' is supported, identified as: Müller Licht Tint dim remote control (404002)```

the device is recognized and shown at the zigbee overview page

![tint_remote_01](https://user-images.githubusercontent.com/50583947/102926235-f323f280-4494-11eb-8b42-1cb41840ec81.png)

datapoints are created for the object 

![tint_remote_02](https://user-images.githubusercontent.com/50583947/102926240-f4551f80-4494-11eb-9706-b60c256bd09c.png)

now the new problem: if i push the buttons on the remote the values of the object do not change. so the remote is recognized, but does not work. datapoints stay empty.

**Comment by asgothian** [comment]
Please post:
- the coordinator tile from the Zigbee adapter
- the log entries you get when you added the remote
- any warn messages which come up related to the remote.

A.

**Comment by quotschmacher** [comment]
- coordinator tile
  ![tint_remote_03](https://user-images.githubusercontent.com/50583947/103042492-16749d80-457a-11eb-96c5-aa236f7dd45d.png)
- log entries
  ![tint_remote_04](https://user-images.githubusercontent.com/50583947/103042515-28564080-457a-11eb-9b7a-a520c944921e.png)
- nothing else happens in the log. i added a trigger to a button, but nothing happens. i pressed all buttons - short an long - nothing happens in the log

**Comment by asgothian** [comment]
Plese unpair the device, pair it again and post the log of the pairing process. I am especially interested in any messages related to "configure" attempts.

A.

**Comment by quotschmacher** [comment]
as far as i can see, this are all messages from the pairing, filtering log for "config" does not bring any success

```

zigbee.0 | 2020-12-27 22:15:12.527 | debug | (7931) Wrong device 00158d0002d501c4 null
-- | -- | -- | --
zigbee.0 | 2020-12-27 22:15:12.518 | debug | (7931) Wrong device 00158d0002d501c4 null
zigbee.0 | 2020-12-27 22:15:12.513 | debug | (7931) Publish available for 0x00158d0002d501c4 = true
zigbee.0 | 2020-12-27 22:15:12.511 | debug | (7931) Type readResponse device {"type":"device","device":{"ID":22,"_type":"EndDevice","_ieeeAddr":"0x00158d0002d501c4","_networkAddress":3835,"_manufacturerID":4456,"_endpoints":[{"ID":1,"profileID":
zigbee.0 | 2020-12-27 22:15:12.510 | debug | (7931) Received Zigbee message from '0x00158d0002d501c4', type 'readResponse', cluster 'genBasic', data '{"modelId":"ZBT-DIMController-D0800"}' from endpoint 1 with groupID null
zigbee.0 | 2020-12-27 22:15:12.508 | debug | (7931) handleMessage. {"type":"readResponse","device":{"ID":22,"_type":"EndDevice","_ieeeAddr":"0x00158d0002d501c4","_networkAddress":3835,"_manufacturerID":4456,"_endpoints":[{"ID":1,"profileID":260,
zigbee.0 | 2020-12-27 22:15:12.419 | debug | (7931) Publish {"brightness":12}
zigbee.0 | 2020-12-27 22:15:12.406 | debug | (7931) Type attributeReport device {"type":"device","device":{"ID":9,"_type":"Router","_ieeeAddr":"0x7cb03eaa0a00aeb1","_networkAddress":64679,"_manufacturerID":48042,"_endpoints":[{"ID":3,"profileID"
zigbee.0 | 2020-12-27 22:15:12.404 | debug | (7931) Received Zigbee message from '0x7cb03eaa0a00aeb1', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":12}' from endpoint 3 with groupID null
zigbee.0 | 2020-12-27 22:15:12.403 | debug | (7931) handleMessage. {"type":"attributeReport","device":{"ID":9,"_type":"Router","_ieeeAddr":"0x7cb03eaa0a00aeb1","_networkAddress":64679,"_manufacturerID":48042,"_endpoints":[{"ID":3,"profileID":492
zigbee.0 | 2020-12-27 22:15:12.304 | debug | (7931) Type commandQueryNextImageRequest device {"type":"device","device":{"ID":22,"_type":"EndDevice","_ieeeAddr":"0x00158d0002d501c4","_networkAddress":3835,"_manufacturerID":4456,"_endpoints":[{"ID
zigbee.0 | 2020-12-27 22:15:12.303 | debug | (7931) Received Zigbee message from '0x00158d0002d501c4', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"manufacturerCode":4456,"imageType":524,"fileVersion":285278213
zigbee.0 | 2020-12-27 22:15:12.302 | debug | (7931) handleMessage. {"type":"commandQueryNextImageRequest","device":{"ID":22,"_type":"EndDevice","_ieeeAddr":"0x00158d0002d501c4","_networkAddress":3835,"_manufacturerID":4456,"_endpoints":[{"ID":1,
zigbee.0 | 2020-12-27 22:15:10.804 | debug | (7931) No converter available for '404006/404008/404004' with cluster 'genOta' and type 'commandQueryNextImageRequest'
zigbee.0 | 2020-12-27 22:15:10.800 | debug | (7931) Type commandQueryNextImageRequest device {"type":"device","device":{"ID":15,"_type":"Router","_ieeeAddr":"0x00158d000360bb45","_networkAddress":52421,"_manufacturerID":4635,"_endpoints":[{"ID":
zigbee.0 | 2020-12-27 22:15:10.798 | debug | (7931) Received Zigbee message from '0x00158d000360bb45', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"manufacturerCode":4635,"imageType":20499,"fileVersion":2853437
zigbee.0 | 2020-12-27 22:15:10.797 | debug | (7931) handleMessage. {"type":"commandQueryNextImageRequest","device":{"ID":15,"_type":"Router","_ieeeAddr":"0x00158d000360bb45","_networkAddress":52421,"_manufacturerID":4635,"_endpoints":[{"ID":1,"p
zigbee.0 | 2020-12-27 22:15:07.968 | info | (7931) Starting interview of '0x00158d0002d501c4'
zigbee.0 | 2020-12-27 22:15:07.966 | debug | (7931) handleDeviceInterview. {"status":"started","device":{"ID":22,"_type":"Unknown","_ieeeAddr":"0x00158d0002d501c4","_networkAddress":3835,"_endpoints":[],"_interviewCompleted":false,"_interviewing
zigbee.0 | 2020-12-27 22:15:07.965 | debug | (7931) handleDeviceJoined. {"device":{"ID":22,"_type":"Unknown","_ieeeAddr":"0x00158d0002d501c4","_networkAddress":3835,"_endpoints":[],"_interviewCompleted":false,"_interviewing":false,"meta":{},"_la
zigbee.0 | 2020-12-27 22:14:58.020 | debug | (7931) sendTo "letsPairing" to system.adapter.admin.0 from system.adapter.zigbee.0: Start pairing!
zigbee.0 | 2020-12-27 22:14:58.019 | info | (7931) Zigbee: allowing new devices to join.

```

i don't know how i can copy the complete message, i think this is the one that coult be most interesting:
![tint_remote_05](https://user-images.githubusercontent.com/50583947/103179999-d707c300-4891-11eb-9309-b994f6ebea62.png)

**Comment by asgothian** [comment]
Again this information is incomplete. You need to
- set the adapter to debug
- go to the log page in iobroker and delete the current log (optional, only if you don't need it)
- pair the device again
- go to the log page and use the "download log" button to obtain the complete log
- filter out all messages which do NOT originate from zigbee.0
- Trim the log to only show entries from the start of pairing  (this will be a lot easier if you were able to delete the log in the optional step)
- post the log

The message "Wrong device 00158d0002d501c4 null" leads me to believe there is something fishy going on.

A.

**Comment by quotschmacher** [comment]
ok - i did not recognize that bif fat blue "log herunterladen"... i tried copying it...
here https://pastebin.com/7bLYNgRA is the complete log. it is connected, datapoints are creted but they don't change when pressing a button. "available" is true, but nothing more (expect "link_quality")

**Comment by Kentrath** [comment]
Ive got the same Problem. On zigbee2mqtt there is a solution. Maybe it is possible to get the update here. Big thanks
https://github.com/Koenkk/zigbee-herdsman-converters/pull/2042

**Comment by asgothian** [comment]
Fixed with latest GitHub version.

Remote needs to be removed and paired again to work.

**Comment by kuumaur** [comment]
Hi Guys,
sorry for asking a silly question, but how to update my existing iobroker.zigbee 1.3.1 to this Github Version?
I did a "git clone", but it looks, that nothing changed for my iobroker.zigbee installation. Version is still 1.3.1.
Any ideas?
Regards

**Comment by kuumaur** [comment]
Ok, sorry now i remember that i have to change from stable to beta in ioBroker settings.
Adapter is now Version 1.4.2. 
As mentioned, i removed the remote 404002 and paired it again. 
Now i see a device of model 404002 and i can see the object attributes, but it looks to me, that there is no reaction while pressing any button on the remote control.
Did someone have a similar behavior?
Regards Kuumaur
