### ISSUE TITLE
Kann keine weiteren Sensoren/Geräte pairen

### ISSUE THREAD

**Issue by A13nka** [ioBroker/ioBroker.zigbee#883]
Hallo, ich bekomme kein weiteres Gerät zu dem zigbee Adapter hinzugefügt.
Bis vor ein paar Tagen lief das System noch super, ich hatte 4 Aqara Fenster Kontakte angelernt. Aus für unerklärlichen Gründen ist einer der Sensoren auf einmal zu weit entfernt (es sind ca 5m) und verliert andauernd die Verbindung. 
Dachte nun dass ich diesen neu anlerne um so zu testen wie weit er dieses Mal reicht. 

Nachdem ich den Fensterkontakt aus der Liste gelöscht habe, da er selbst bei einer Entfernung von weniger als 10cm nicht die Verbindungen halten konnte, lässt er sich nun nicht mehr verbinden.

Ich habe dann noch eine Tradfri Fernbedienung und einen Tradfri Reapter hier liegen und habe versucht diese mit dem Zigbee.0 Adapter zu pairen. Leider beides nach mehrmaligen Versuchen ohne Erfolg.

Zu meinem ioBroker Setup.
Mein ioBroker läuft in Docker auf einem Raspberry Pi4. Bei Rückfragen kann ich gerne die .yml Datei teilen. Der Conbee2 Stick ist dem Container zugewiesen. Die aktuell noch 3 verbunden Fenstersensoren "funktionieren" auch. Jedoch haben diese eine Signalqualität von unter 30. Da ich dieses nicht so ganz glauben konnte, habe ich mal einen Kontakt davon direkt neben den Stick gelegt, so ca 5cm. Die Signalqualität steigt leider nicht. 

P.S.: ich bin auf der 1.3.1 Zigbee Version

Vielleicht hat jemand eine Idee, wie ich diese Probleme beheben kann.

**Comment by sym-code** [comment]
Und ich hexe hier scho 2 Tage rum und zweifel schon an meinem Verstand... selbes Setup -> ähnliche Probleme.
Habe vor nen paar Wochen nen RPI3 mit dem Setup problemlos ans laufen bekommen und nun will ich den Stick an einem RPI4 betreiben und bekomme ihn nicht richtig ans laufen in ioBroker.
Installation läuft sauber durch, Zigbee Adapter zeigt grün, aber ich bekomme kein Pairing hin. Ganz selten klappt es mal aber dann buged die Empfangstärke rum und die LED ist schnell nicht mehr erreichbar. Im ioBroker Log kommen sporadisch verschiedene Meldungen... startet meistens nach ner sauberen isntall damit das er meckert das die PAN ID schon vergeben ist... egal was man für eine eingibt...

Setup:
RPI4 - 4GB - Raspberry OS 64bit - node: v12.20.0, js-controller: 3.1.6, Zigbee Version 1.31

Ein Downgrade auf zigbee adapter v1.2 grad gemacht, scheint das Prob aber auch nciht zu lösen.
Probiere das ganze nun noch mit ner sauberen install und node v.10.x aus - die hatte ich am RPi3 auch drauf.
Und dann mal schauen ob ich nicht direkt den zigbee adapter in einer niedrigeren version installieren kann.

**Comment by 1rfsNet** [comment]
Hast du inzwischen eine Lösung gefunden? Hast du die Batterie mal getauscht? Das war bei mir ein Problem mit einem Aqara Sensor. 

Übrigens würde ich davon abraten die Funktionen mit IKEA Komponenten zu testen. Ich habe gerade auch massive Probleme mit der IKEA Fernbedienung (will sich nicht anlernen lassen). Und auch mit anderen Tradfri Geräten lief es nicht auf Anhieb.

**Comment by vain90** [comment]
Ich hatte nach einem Stromausfall leider das Problem das mein Zigbee Adapter alle Geräte vergessen hatte. Es schien so als würde er die von mir angegebenen IDs verlernt haben. Naja jeden falls habe ich mich dran gemacht und alles neu angelernt.

In diesem Zuge ist mir nun aufgefallen das ich die Aquara Temperatursensoren nicht mehr angelernt bekomme. Die Fensterkontakte hingegen schon. Auch die Aquara Bewegungsmeldern sind kein Problem. Wobei ich diese separiert habe. Diese haben ja bekanntlich Probleme mit Anderen Herstellern.

Ich nutze einerseits den CC2531 als Koordinator für die Bewegungsmeldern in Verbindung mit Gledopto LED Controller. Und einen CC1352P-2 als “großer” Koordinator für alle anderen Zigbee Geräte.

**Comment by 1rfsNet** [comment]
Bei mir hat es geholfen die Adapter Instanz zu löschen und eine neue anzulegen.

**Comment by vain90** [comment]
@1rfsNet Dann muss ich aber nicht alles neu pairen oder?

**Comment by asgothian** [comment]
Solange du die shepherd.db in /opt/iobroker/iobroker_data/zigbee_0 nicht anfasst sollte das ohne neu anlernen gehen.

A.

**Comment by vain90** [comment]
@asgothian dann versuche ich das heute mal. Vorher kopiere ich mir die shephard mal weg.

**Comment by vain90** [comment]
Problem gefunden! Es lag an "leeren" Batterien.
