### ISSUE TITLE
Cannot connect to zigbee with conbee

### ISSUE THREAD

**Issue by matzesutopia** [ioBroker/ioBroker.zigbee#885]
I have a conbee 2 stick and I cannot connect it to zigbee. I put the COM Port like this:

/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DEXXXXXXXX

host.raspberrypi | 2020-12-08 01:23:12.273 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2020-12-08 01:23:12.273 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2020-12-08 01:23:12.273 | error | Caught by controller[0]: }
host.raspberrypi | 2020-12-08 01:23:12.272 | error | Caught by controller[0]: ]
host.raspberrypi | 2020-12-08 01:23:12.272 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.zigbee/main.js'
host.raspberrypi | 2020-12-08 01:23:12.272 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js',
host.raspberrypi | 2020-12-08 01:23:12.272 | error | Caught by controller[0]: requireStack: [
host.raspberrypi | 2020-12-08 01:23:12.271 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2020-12-08 01:23:12.271 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:952:19) {
host.raspberrypi | 2020-12-08 01:23:12.271 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
host.raspberrypi | 2020-12-08 01:23:12.270 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:928:32)
host.raspberrypi | 2020-12-08 01:23:12.270 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
host.raspberrypi | 2020-12-08 01:23:12.270 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
host.raspberrypi | 2020-12-08 01:23:12.269 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js:3:25)
host.raspberrypi | 2020-12-08 01:23:12.269 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:88:18)
host.raspberrypi | 2020-12-08 01:23:12.269 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:952:19)
host.raspberrypi | 2020-12-08 01:23:12.269 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:725:27)
host.raspberrypi | 2020-12-08 01:23:12.268 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
host.raspberrypi | 2020-12-08 01:23:12.268 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/main.js
host.raspberrypi | 2020-12-08 01:23:12.268 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js
host.raspberrypi | 2020-12-08 01:23:12.267 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2020-12-08 01:23:12.267 | error | Caught by controller[0]: Error: Cannot find module 'zigbee-herdsman/dist/adapter/serialPortUtils'
host.raspberrypi | 2020-12-08 01:23:12.267 | error | Caught by controller[0]: ^
host.raspberrypi | 2020-12-08 01:23:12.267 | error | Caught by controller[0]: throw err;
host.raspberrypi | 2020-12-08 01:23:12.266 | error | Caught by controller[0]: internal/modules/cjs/loader.js:883
host.raspberrypi | 2020-12-08 01:23:11.103 | info | instance system.adapter.zigbee.0 started with pid 9469
host.raspberrypi | 2020-12-08 01:22:41.067 | info | Restart adapter system.adapter.zigbee.0 because enabled

**Comment by asgothian** [comment]
Please reinstall the zigbee adapter. You seem to be missing a vital library which got removed by something you did.

A.

**Comment by asgothian** [comment]
closed - issue seems fixed.
