### ISSUE TITLE
Funktioniert nicht mit FreeBSD 11.2-RELEASE-p3

### ISSUE THREAD

**Issue by 1Topf** [ioBroker/ioBroker.zigbee#89]
Leider kann ich den Adapter nicht unter FreeBSD installieren. Gibt es da eine Lösung? Ich habe ioBroker auf meinem NAS laufen [(XigmaNAS)](https://www.xigmanas.com), installiert direkt über die Shell. Gibt es eine Möglichkeit, den Adapter zu installieren?
Andi

**Comment by Apollon77** [comment]
What exactly is not working? Some more details will be very helpfull!
Log output from installation?

**Comment by 1Topf** [comment]
Hi,
da mein englisch nicht soooo perfekt ist, gehts in deutsch weiter ;o). Wie gesagt, der Zigbee-Adapter läßt sich bei mir unter FreeBSD nicht installieren. Eventuell ein reines FreeBSD-Problem?
Installation habe ich bereits über ioBroker, PuTTY und Shell versucht. Dauert jedesmal EWIG und endet immer gleich. Den npm - Befehl hab ich aus der Adapterinstallation in ioBroker entnommen. Habe es aber auch schon mit `npm i iobroker.zigbee` versucht.
Anbei mal der PuTTY-Auszug (leider keine Spoilerfunktion) und das Logfile.
npm = 4.6.1, node = 10.11.0

> Using username "root".
root@192.168.178.2's password:
Last login: Tue Oct 30 08:16:43 2018 from 192.168.178.57
Welcome to XigmaNAS!
nas4free: ~# iobroker restart
Stopping iobroker controller daemon...
iobroker controller daemon stopped.
Starting iobroker controller daemon...
iobroker controller daemon started. PID: 80399
nas4free: ~# npm install iobroker.zigbee --production --save --prefix "/opt/iobroker"                                                                                                     
npm ERR! tar.unpack untar error /root/.npm/github-from-package/0.0.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/mimic-response/1.0.1/package.tgz
iobroker.inst@1.1.2 /opt/iobroker
├─┬ iobroker.js-controller@1.4.2
│ └─┬ winston-syslog@1.2.6
│   └─┬ unix-dgram@0.2.3
│     ├── bindings@1.1.1
│     └── nan@2.3.5
└── zigbee-shepherd@0.3.0  extraneous

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: debug@2.6.9 (node_modules/choices-separator/node_modules/debug):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, chown '/opt/iobroker/node_modules/.staging/debug-f22a8b87/package.json.3645235020'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: for-own@1.0.0 (node_modules/for-own):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, chown '/opt/iobroker/node_modules/.staging/for-own-759db3a2/package.json.1163862438'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: are-we-there-yet@1.1.5 (node_modules/are-we-there-yet):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, chown '/opt/iobroker/node_modules/.staging/are-we-there-yet-74d5ece2/package.json.1511475327'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, chown '/opt/iobroker/node_modules/.staging/has-unicode-04d049ed/package.json.1998000792'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: github-from-package@0.0.0 (node_modules/github-from-package):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/github-from-package-c443e7c4/test/e.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mimic-response@1.0.1 (node_modules/mimic-response):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: EEXIST: file already exists, mkdir '/opt/iobroker/node_modules/.staging/mimic-response-bbc9ccd6'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File exists: /opt/iobroker/node_modules/.staging/mimic-response-bbc9ccd6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: koalas@1.0.2 (node_modules/koalas):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/koalas-4bbac784/package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: info-symbol@0.1.0 (node_modules/info-symbol):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/info-symbol-bdc0121f/package.json.453713969'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/ini-48ec7e87/package.json.2507928619'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: decompress-response@3.3.0 (node_modules/decompress-response):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/decompress-response-6c0dd6ef/package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: for-in@0.1.8 (node_modules/mixin-object/node_modules/for-in):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/for-in-c0f3be6c/package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mixin-object@2.0.1 (node_modules/mixin-object):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/mixin-object-059f8f29/package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/minimist-9115292a/package.json'
npm ERR! path /opt/iobroker/node_modules/.staging/fs-constants-5251f519/package.json.228228929
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/.staging/fs-constants-5251f519/package.json.228228929'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

> npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-30T11_00_05_428Z-debug.log
nas4free: ~#

[2018-10-30T11_00_05_428Z-debug.txt](https://github.com/ioBroker/ioBroker.zigbee/files/2529402/2018-10-30T11_00_05_428Z-debug.txt)

Mußte das LOG in ein TXT wandeln, da hier mein Log nicht angehängt werden kann? Wird mir mit _"We don’t support that file type. **Try again with** a GIF, JPEG, JPG, PNG, DOCX, GZ, **LOG**, PDF, PPTX, TXT, XLSX or ZIP."_ quittiert. :-D
Wenn Du mehr Infos brauchst, einfach sagen. Wenn das hier klappt, muß ich immer noch den Com-Port des CC-Sticks herausfinden, is unter BSD auch nicht so leicht. :o/
Ich bin übrigens mit FreeBSD nicht so dicke, hab das nur wegen meinem NAS. Wenn das hier nicht klappt, werd ich wohl ioBroker auf einem Linux installieren.

Viele Grüße,
Andi

**Comment by Apollon77** [comment]
npm -v ?
node -v ?

npm cache clean

und dann nochmal versuchen?

**Comment by 1Topf** [comment]
> npm = 4.6.1, node = 10.11.0

Hatte ich oben schon geschrieben. Bin grad auf Arbeit, den Cache kann ich erst heut abend leer machen :-). Weiß nicht, ob das per VPN über die GUI vom NAS funzen würde, da bin lieber vor Ort. Melde mich dann wieder.

**Comment by 1Topf** [comment]
Kleines Update. Ich habe es geschafft, den Adapter in FreeBSD zu installieren, aber eben nur im reinen FreeBSD. Sobald ich versuche, es in XigmaNAS zu installieren, funktioniert es nicht. Im reinen FreeBSD funktioniert es aber auch nur, wenn ich noch ein `pkg install python` mache, obwohl python ja schon installiert ist. Aber bei XigmaNAS funktioniert das nicht.
Da hab ich echt zu wenig Ahnung, wo es da hängt. Schade. Falls noch jemand eine Idee hat, soll er die hier bitte posten. Danke schon mal. :o)
Andi
