### ISSUE TITLE
Support for LIDL / LIVARNO LUX LED Panel

### ISSUE THREAD

**Issue by onyxkyr** [ioBroker/ioBroker.zigbee#891]
Hello everyone,

I bought the [LED panel](https://www.lidl.de/de/livarno-lux-wand-und-deckenpanel-zigbee-smart-home-fernbedienung/p354578) currently offered by Lidl under the brand LIVARNO LUX.
It comes with the panel itself and a small remote. I was able to pair both device with ioBroker.zigbee under the current stable 1.3.1.
See the provided device information in the images below:

Panel:
![device_information_panel](https://user-images.githubusercontent.com/75786462/101765339-79c5f080-3ae1-11eb-9848-01665943eb00.png)

<details open>
<summary>Device information(panel)</summary>

    model:TS0502A
    description:Light controller
    supports:on/off, brightness, color temperature

    model:TS0502A
    type:Router
    nwk:56965
    manuf id:4098
    manufacturer:_TZ3000_oh7jddmx
    power:Mains (single phase)
    app version:80
    hard version:1
    zcl version:3
    stack version:0
    date code:
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genIdentify (3)
    genGroups (4)
    genScenes (5)
    genOnOff (6)
    genLevelCtrl (8)
    lightingColorCtrl (768)
    touchlink (4096)
    output clusters:genOta (25)
    genTime (10)

    endpoint:242
    profile:41440
    output clusters:greenPower (33)
</details>

Remote:
![device_information_remote](https://user-images.githubusercontent.com/75786462/101765354-7fbbd180-3ae1-11eb-98a7-97538d85821f.png)
[The remote is apparently already supported in the current beta of zigbee2mqtt](https://www.zigbee2mqtt.io/devices/FB20-002.html).

I would greatly appreciate the support for this device.
Kind regards,

**Comment by asgothian** [comment]
Did you try to install the current 1.4.0 version of the Adapter ? This panel should be covered using the exposes from the zigbee-herdsman-converters.

A.

**Comment by onyxkyr** [comment]
With a manual install via the projects git url I could update to 1.4.0 (it was not possible for me to so via a simple update).
I can report that with 1.4.0 both panel and remote work flawlessly, thanks :)

**Comment by o0shojo0o** [comment]
@onyxkyr 
Can you set the ColorTemp with a Kelvin value e.g. 2000 - 6000 ?
Or is Mired used here again 150 - 500 ?
Can you please check this once?

**Comment by onyxkyr** [comment]
@o0shojo0o 
I just checked this, the colour temperature changes for values between 150-500, and there are no changes beyond a value of 500.

**Comment by o0shojo0o** [comment]
Okay, that's what I thought.
I'll add the Base Device right away and make a pull request.
(https://www.zigbee2mqtt.io/devices/TS0502A.html)
