### ISSUE TITLE
Eurotronic SPZB0001 - window_open not changeable

### ISSUE THREAD

**Issue by tsvsj** [ioBroker/ioBroker.zigbee#894]
Hi,

I'm using the Eurotronic SPZB0001, which is supported as per https://github.com/ioBroker/ioBroker.zigbee/wiki/Supported-devices. When the device is paired, I have a state `window_open`. This state is writeable and I thought of setting it to `true`, if my window sensor tells then window is open. The Thermostat doesn't detect the open window.

Unfortunately changing this state is not possible. The adapter logs an error:
```
error: zigbee.0 (814) Error on send command to 0x00158xxx. Error: Error: Write 0x00158xxx/1 hvacThermostat({"16392":{"value":17,"type":34}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')
    at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:173:23)
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:202:26)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
```

It seems like an issue for me and would be happy, if this could be fixed.

Regards

**Comment by Benno42** [comment]
May be a firmware problem?

https://forum.iobroker.net/topic/37659/zigbee-eurotronic-spirit-thermostat-funktioniert-nicht/41

**Comment by tsvsj** [comment]
Thanks for this info. But all of my Thermostates are on the same firmware:
```
app version: 22
hard version: 35
zcl version: 2
stack version: 5
```

I've checked the behavior on all other devices. It works on only one of my Thermostates. All others (4) create the error message above.

**Comment by asgothian** [comment]
Please check if you can perform the following actions on the Thermostats which do not accept the open window:

- change the "local_temperature_calibration"
- change the "current_heating_setpoint"
- change the "child lock" or "display orientation"

My expectation is that all these actions will generate the same error. This would indicate that the three affected Thermostats have an error in their Firmware.

A.

**Comment by tsvsj** [comment]
Ok, I've checked the devices physically and based on the cardboards they are the newer firmware. I've gone through the whole thread on ioBroker. They wrote, that Euronics is aware of issues with the current firmware and will provide an update of the firmware as OTA. I will check on that. Does the adapter support OTA for Zigbee devices? I'm aware of the `check for firmware updates` button, but it didn't ever show any update, so I'm wondering if this is just a placebo? ;-)

**Comment by asgothian** [comment]
It should not just be a placebo, but it relies on the manufacturer properly implementing the OTA feature. Lets hope that the eurotronic firmware will be available through this button.

A.

**Comment by asgothian** [comment]
Same as #815
