### ISSUE TITLE
Tuya thermostat dont save values 

### ISSUE THREAD

**Issue by SLongus** [ioBroker/ioBroker.zigbee#897]
My Tuya thermostats (https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html) don't save the values from iobroker. I get no error message from iobroker when I save a value, but after a couple of minutes my change is dissapeared and the old value is back.

I've read here https://github.com/Koenkk/zigbee2mqtt/issues/4460 that the thermostat maybe needs a firmware upgrade - but I don't have a Tuya Gateway and the Firmware Upgrade function from the Zigbee Adapter says the firmware is up to date.

model:TS0601_thermostat
description:Radiator valve with thermostat
modelZigbee:TS0601
type:EndDevice
nwk:27303
manuf id:4098
manufacturer:_TZE200_ckud7u2l
power:Battery
app version:85
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
output clusters:genOta (25)
genTime (10)

**Comment by asgothian** [comment]
- Please specify which values are affected.
- there was an update on how the Thermostat is handled within the last few days. Please ensure you have the latest 1.4.0 version installed.
- The Thermostat might support OTA Updates. Can you try to perform said update from the admin interface ?

**Comment by SLongus** [comment]
Hi,

every value, I cant set any value =( Or to say it right, I can set the values but after a couple of minutes the old value appears.

I have version 1.4.0 installed.

**Comment by asgothian** [comment]
All values being affected makes it likely that you are affected by the firmware-bug you linked to. At this point, there is little which can be done on the Zigbee Adapter.

**Comment by SLongus** [comment]
I hoped that the firmware update would be possible over the zigbee adapter. When I click on "Check for Firmware Upgrades", the Adapter search for Updates for the thermometers but says "Up-to-Date". The Thermometers accept OTA updates.

It's not really nice to buy the Tuya Gataway, , create a tuya account, re-learn all thermometers with the tuya gataway, re-learn the thermometers with the cc2531 stick/iobroker und to sell? the tuya gataway =(

**Comment by asgothian** [comment]
Agreed - this is not nice, but unless tuya provides a means for OTA software upgrades without their gateway, that is the way to go.

A.
