### ISSUE TITLE
unable to pair Neo Zigbee Siren Alarm

### ISSUE THREAD

**Issue by kemenap** [ioBroker/ioBroker.zigbee#899]
Hello. I'm unable to pair https://szneo.com/en/products/show.php?id=241. It should work since 1.2.0.
Tried several times.

Log:
Error: Device 0x5c0272fffecaf0a6 "TS0601" not described in statesMapping.. undefined
New device joined '0x5c0272fffecaf0a6' model TS0601
Interview successful: [object Object]
Device '0x5c0272fffecaf0a6' announced itself
Interview started: 0x5c0272fffecaf0a6

![screenshot_93](https://user-images.githubusercontent.com/75466977/102263447-9bc1d780-3f14-11eb-8cc9-090eec950e1c.png)

Any idea? Thanks,

CC2531 with firmware 20190608. ioBroker.zigbee 1.4.0

**Comment by asgothian** [comment]
The descriptor sent by your device does not match the one present in the zigbee-herdsman-converters. As such, support for this version of the siren requires a change of the converters. Please post an issue / device support request [here](https://github.com/Koenkk/zigbee-herdsman-converters/issues).

**Comment by kemenap** [comment]
many thanks for the support.
strange, I bought exactly this device.
i will post an issue / device support request.
