### ISSUE TITLE
EZSP

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.zigbee#900]
Kann man EZSP als Art noch mit hinzufügen?
https://zigbee.blakadder.com/Sonoff_ZBBridge.html

![image](https://user-images.githubusercontent.com/25475385/102452183-39fb8d80-403a-11eb-9b5d-0d7966bdfd52.png)

**Comment by asgothian** [comment]
This integration must be realised in zigbee-herdsman-converters before any work can be done to a possible iobroker.zigbee integration. I do not see this integration as sensible in ioBroker.zigbee. IoBroker.Zigbee does not support any of the other "bridge" objects (Hue, Deconz, Tradfri, Tuya, Osram, Amazon ...)

A.

**Comment by asgothian** [comment]
Follow up - it seems there is a python library to directly address the zigbee radio on the sonoff gateway. Support might be interesting, but due to the completely different hardware, implementation may be difficult.

A.
