### ISSUE TITLE
Ikea E1524/E1810

### ISSUE THREAD

**Issue by markus2701** [ioBroker/ioBroker.zigbee#901]
Version GitHub 1.4.0

(18718) No converter available for 'E1524/E1810' with cluster 'genOnOff' and type 'commandToggle'

(18718) Type commandToggle device {"type":"device","device":{"ID":12,"_type":"EndDevice","_ieeeAddr":"0x680ae2fffed3770e","_networkAddress":20862,"_manufacturerID":4476,"_endpoints":[{"ID":1,"profileI
--

(18718) Received Zigbee message from '0x680ae2fffed3770e', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 901
--
(18718) handleMessage. {"type":"commandToggle","device":{"ID":12,"_type":"EndDevice","_ieeeAddr":"0x680ae2fffed3770e","_networkAddress":20862,"_manufacturerID":4476,"_endpoints":[{"ID":1,"profileID":2

--

**Comment by asgothian** [comment]
Please post the tile from the adapter config so that we can see which device is affected. Also - this issue is most likely no issue for the iobroker.zigbee adapter, but for zigbee2mqtt.io

A.

**Comment by quotschmacher** [comment]
i had the same issue. affected device: https://www.zigbee2mqtt.io/devices/E1524_E1810.html

installed right nox github version (should be https://github.com/ioBroker/ioBroker.zigbee/commit/225d3dbf8afa7c5e73eedf491c52b941ecd4f48a ).

the toggle datapoint works again.

but i didn't receive "battery" and "hold" until now.

**Comment by asgothian** [comment]
> i had the same issue (toggle didn't work after installing github version). affected device: https://www.zigbee2mqtt.io/devices/E1524_E1810.html
> 
> installed right nox github version (should be [225d3db](https://github.com/ioBroker/ioBroker.zigbee/commit/225d3dbf8afa7c5e73eedf491c52b941ecd4f48a) ).
> 
> the toggle datapoint works again.
> 
> but i didn't receive "battery" and "hold" until now.

- Do you get errors in the log ?
- Did you try to trigger the hold message ?
A.

**Comment by quotschmacher** [comment]
no errors at all. and if i add triggers to "hold" and "toggle": when pushing the button, the toggle event is fired two times with a delay of 300 ms an hold is not fired. when i release the button nothing happens.

**Comment by asgothian** [comment]
I was able to test the situation with a E1524, and have the following behavior:

- if i hold the button, i get a toggle event immediately (swap false to true, swap back to false after approx. 220 ms)
- approx 500 ms after the toggle event fired, i get a "hold" event (true, approx 250 ms later back to false)

Can you check if you can produce the same behavior ?

A.

**Comment by quotschmacher** [comment]
updated to new github version, now i get following output:

```
javascript.0 | 2020-12-27 22:38:59.272 | info | (2303) script.js.Lichtsteuerung.Bad.licht_steuern: Hold event - false
-- | -- | -- | --
javascript.0 | 2020-12-27 22:38:58.980 | info | (2303) script.js.Lichtsteuerung.Bad.licht_steuern: Hold event - true
javascript.0 | 2020-12-27 22:38:55.761 | info | (2303) script.js.Lichtsteuerung.Bad.licht_steuern: Toggle event - false
javascript.0 | 2020-12-27 22:38:55.457 | info | (2303) script.js.Lichtsteuerung.Bad.licht_steuern: Toggle event - true
```

so in some way it works. but: three seconds is a bit long and how do i detect if hold gets released?

**Comment by asgothian** [comment]
> so in some way it works. but: three seconds is a bit long and how do i detect if hold gets released?

You can't. The way it is implemented you only get a "hold" event, i.e. a notification that someone pressed the button longer. There is no "hold ended" event.

A.
