### ISSUE TITLE
Tuya Gas/Water Valve 

### ISSUE THREAD

**Issue by apla2016** [ioBroker/ioBroker.zigbee#902]
Trying to pair Tuya Gas/Water Valve model SM-AW713Z (written on the valve) SM-AZ713 (written on the box). It is being recognized by ioBroker Zigbee adapter as TS011F but no objects become available after pairing completes. 

Here is pairing log:

Error: Device 0xbc33acfffeff263f "TS011F" not described in statesMapping.. undefined
New device joined '0xbc33acfffeff263f' model TS011F
Interview successful: [object Object]
Device '0xbc33acfffeff263f' announced itself
Interview started: 0xbc33acfffeff263f

Is this a new device that needs to be added?

**Comment by asgothian** [comment]
- Which adapter version are you running ?
- can you post the tile from the Adapter devices page, as well as the info which can be accessed from the info icon ?
- have you checked on zigbee2mqtt if this device is listed as supported ?
A.

**Comment by apla2016** [comment]
I am running adapter 1.4.0. This device functionally is not in zigbee2mqtt, but there is TuYa TS011F socket module (switch) there which, I guess, can be adapted since I need command to open/close the valve and feedback to read valve status, so it can be treated as switch.  Please see attached images as you requested.

![Info](https://user-images.githubusercontent.com/19657413/102621408-7ea42900-410d-11eb-9645-10c4c2c880a8.jpg)
![Tile](https://user-images.githubusercontent.com/19657413/102621422-8368dd00-410d-11eb-81b3-8ed1c41d5efa.jpg)

**Comment by asgothian** [comment]
Yes, this is related. Until the device is working in zigbee2mqtt, no change in the zigbee adapter will make it work.

Once it is in, it should show up as "exposed" device 

A.

**Comment by apla2016** [comment]
Thank you, I will add my comment into existing issue at zigbee2mqtt

**Comment by asgothian** [comment]
You need to
- verify which version of the zigbee-herdsman-converters the device is supported in
- check if this version is currently used by iobroker.zigbee. We are often a few versions behind with using the latest herdsman due to the need to verify changes.
Once the zigbee adapter uses the correct herdsman-converters version, it should be supported immediately.

Also - when posting information about other issues - don't post screenshots. Post links to the issue / post, so we can read without having to dig through the list of issues to identify it.
A

**Comment by apla2016** [comment]
Sorry about the link, here it is if you still need it: https://github.com/Koenkk/zigbee2mqtt/issues/5333 

- According to Github, the TS011F is supported in latest version v13.0.28 of zigbee-herdsman-converters (multiple devices mentioned under FS011F, but most of them are switches, which is functional equivalent to the on/off valve from control point of view. Refer to https://github.com/Koenkk/zigbee-herdsman-converters/releases 
- Not sure how to check what is latest version of zigbee-herdsman-converters is used by iobroker

**Comment by asgothian** [comment]
easiest is to check the package.json file of the zigbee adapter. It currently lists v13.0.25 for the zigbee-herdsman-converters.

A.

**Comment by apla2016** [comment]
Thank you for your help and prompt response. Is there anything you need to know for fixing it?

**Comment by asgothian** [comment]
Thank you for the offer, but all that is needed is time. It will probably take until the beginning of next year for the newer herdsman version to be tested and activated in the zigbee Adapter.

**Comment by apla2016** [comment]
Thank you, work fine after update.

Happy New Year!

Anatoly
