### ISSUE TITLE
DeviceConfigure failed: TRADFRI on/off switch E1743

### ISSUE THREAD

**Issue by Caroma97** [ioBroker/ioBroker.zigbee#903]
Hallo zusammen, 

ich versuche den ganzen Tag schon meine IKEA TRADFRI on/off switche (E1743) mit diesem Adapter zu verbinden, jedoch klappt das leider nicht so wie ich will...

Die Schalter lassen sich anlernen, aber ich bekomme immer folgende Fehler im Log:
`

zigbee.0 | 2020-12-18 18:25:34.890 | warn | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:25:65))
-- | -- | -- | --
zigbee.0 | 2020-12-18 18:25:34.890 | warn | at Generator.throw (<anonymous>)
zigbee.0 | 2020-12-18 18:25:34.890 | warn | at DeconzAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:660:23)
zigbee.0 | 2020-12-18 18:25:34.890 | warn | (4603) DeviceConfigure failed 0xec1bbdfffea27abf TRADFRI on/off switch, attempt 1 (Error: Bind 0xec1bbdfffea27abf/1 genOnOff from '901' failed (waiting for response TIMEOUT)

`

ioBroker ist im Docker mit der Version 5.1.0 installiert (alles aktuell).
Zigbee Adapter: Aktuell ist die Version 1.4.1 installiert, der Fehler ist jedoch auch bei der 1.3.0 aufgetreten.
Deconz ist auf dem System nicht mehr installiert.
Raspbee Version: 0x26390500
E1743 Version: 2.2.008 
Der ganze Spaß läuft auf einem Pi3

Meine restlichen Zigbee Geräte funktionieren einwandfrei. Nur diese IKEA Schalter machen Probleme.
Kann ich die Schalter eventuell irgendwie manuell konfigurieren?

![image](https://user-images.githubusercontent.com/45965965/102644093-880ab100-4160-11eb-84bc-ef73f760a5ae.png)

**Comment by asgothian** [comment]
Bitte beobachten. Die Schalter sollten ihre Konfiguration akzeptieren wenn sie aktiv geschaltet werden. Da es sich um batteriebetriebene Geräte handelt kann es sein das das Configure nicht vom Gerät bestätigt wird.

Die entscheidende Frage ist - bekommst Du die Events in den Objekten mit.

Im Normalfall sind diese Meldungen unkritisch - der Schalter sollte trotzdem funktionieren wenn er mindestens 1 mal erfolgreich konfiguriert wurde. In dem Fall kannst Du die Warnmeldungen ignorieren - sie sollten weg gehen wenn du das Gerät nutzt.

A.

**Comment by Caroma97** [comment]
Erst einmal, vielen dank für die schnelle Antwort :)

Bei den Objekten passiert leider Garnichts.
Bei allen 3 Schaltern schauts einfach nur so aus, egal wie oft oder lange ich die Knöpfe drücke:

![image](https://user-images.githubusercontent.com/45965965/102654621-1f780000-4171-11eb-9f61-8751ff3a4a6d.png)

**Comment by asgothian** [comment]
Das ist schon seltsam. 
- Wenn du den Adapter in debug setzt, bekommst du dann vom Schalter irgendwelche Meldungen wenn du tasten drückst ?
- Wird die Link-Quality aktualisiert ?
- wie oft kommt die Warnmeldung, und gibt es im Log vor der Warnmeldung weitere Meldungen mit der Addresse ec1bbdfffea27abf 

A.

**Comment by Caroma97** [comment]
Nein, da kommen gar keine Meldungen von dem Schalter. In den Objekten steht bei available mittlerweile auch false.

Ich bin mir nicht ganz sicher was mit Link-Quality gemeint ist. Falls du damit das "WLAN ähnliche Symbol" in der Übersicht meinst, das wird bei keinem Gerät angezeigt
![image](https://user-images.githubusercontent.com/45965965/102908723-22783680-4478-11eb-8581-3299f8c3253b.png)

Die Warnmeldung kommt jetzt gar nicht mehr.
Ich hab IoBroker mal neu gestartet. Das ist der Log von der ersten halben h nach dem Start:
[https://pastebin.com/mrVyXvvf](https://pastebin.com/mrVyXvvf)
Ich habe auch mehrmals in der Zeit den IKEA Schalter gedrückt, aber es ist keine Meldung aufgetaucht.

**Comment by asgothian** [comment]
Bitte den Schalter noch einmal löschen und erneut anlernen. Dabei während der Schalter angelernt wird regelmässig den Schalter drücken damit er "wach" bleibt.

A.

**Comment by Caroma97** [comment]
[https://pastebin.com/0HmTUHtC](https://pastebin.com/0HmTUHtC)

Wenn ich das richtig deute:
Bis zum Interview mit dem Schalter (Zeile bei 18:18:41.556) bekomme ich Nachrichten von dem Gerät
Ab dann ist der Schalter wieder wie davor und es wird kein Tastendruck erkannt.

**Comment by asgothian** [comment]
Das Verhalten ist seltsam. Im Log kommen keinerlei Nachrichten von der Remote an, obwohl die device-configuration angeblich erfolgreich war. Die Nachrichten die du im Log vom Gerät bekommst sind Antworten auf die Abfragen die beim Pairen gestellt werden (Supported clusters, hw and sw id, und so weiter).
Danach kommen nur Anfragen zu over-the-air updates an der Remote an.

A.

**Comment by Caroma97** [comment]
Sry für die lange Pause. War über die Feiertage/Silvester bei der Familie.

Ich hab jetzt mal einen frischen Container aufgesetzt und nur den Zigbee Adapter (v1.4.2) installiert.
Die Schalter ließen sich wieder Problemlos anlernen, aber der IKEA funktioniert leider immer noch nicht.

Hier mal ein Link zum Log nach dem Anlernen und einem gescheitertem OTA Versuch:
[https://pastebin.com/Bz9Rd9Ds](https://pastebin.com/Bz9Rd9Ds)

Jetzt wird aber wenigstens die Link Qualität angezeigt, ob die jedoch stimmt bezweifle ich ein bisschen (bei beiden immer 10)
![image](https://user-images.githubusercontent.com/45965965/103707749-868a1700-4faf-11eb-8e9a-477c44b5fe3b.png)

**Comment by o0shojo0o** [comment]
Das ist schon komisch, ich habe aktuell 3 St. von denen im betrieb ohne jegliches Problem. 
Die letzten 2 habe ich sogar erst vor 4 Tagen angelernt.

Allerdings nutze ich ein anderen Coordinator (TI Board), vielleicht deutet das dann auf ein Conbee bzw. RaspBee  Problem hin.

**Comment by Caroma97** [comment]
Ich hab jetzt einen CC2652RB stick bei slaeh's iot stuff bestellt (Link aus dem Wiki)
Mal schauen obs dann funktioniert.

**Comment by Caroma97** [comment]
Der CC2652RB Stick ist jetzt angekommen.
Ich habe versucht den Stick in der alten ioBroker Installation zum Laufen zu bringen, jedoch ohne Erfolg. 

Mit einer neuen Installation funktioniert jetzt alles einwandfrei. :)
Keine Ahnung woran es nun schlussendlich lag...

Danke für eure Hilfe! :)

**Comment by asgothian** [comment]
Schön das es läuft. Closing this.
