### ISSUE TITLE
Question: Where to put device type specific configuration?

### ISSUE THREAD

**Issue by volkerrichert** [ioBroker/ioBroker.zigbee#908]
some devices have "device type specific configuration"like the ED-100xx i added to zigbee-herdsman-converters. This can be something like 

```
simulated_brightness:
  delta: 20 # delta per interval, default = 20
  interval: 200 # interval in milliseconds, default = 200
``` 

How can i add this additional config to iobroker.zigbee? This is normaly don in configuration.yaml of zigbee2mqtt.

Volker

**Comment by asgothian** [comment]
You will have to analyze the fromZigbee and toZigbee functions from the device to see how they can be matched with a state in iobroket and then generate the state(s).

A.

**Comment by volkerrichert** [comment]
That's not what I mean. 

I'm looking for an additional config file like the configuration.yaml in zigbee2mqtt in iobroker.zigbee. I could change the devices.js but I'm looking for something being update safe.

But, yes: I didn't check if this property will be pushed to ioBorker.... I'll give it a try

Volker

**Comment by volkerrichert** [comment]
But `simulated_brightness` is part of the default command_move handling [see here](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L911) for a lot of devices. So, we just have to set the options...

**Comment by asgothian** [comment]
> I'm looking for an additional config file like the configuration.yaml in zigbee2mqtt in iobroker.zigbee. I could change the devices.js but I'm looking for something being update safe.

This config file does not exist. You will need to figure out how the option is set and then code it in.

A.

**Comment by asgothian** [comment]
> But `simulated_brightness` is part of the default command_move handling [see here](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L911) for a lot of devices. So, we just have to set the options...

can you in a few sentences explain exactly what the simulated_brightness does and how it is supposed to be used ? Digging through code will only tell me what happens, not why. If you can get it explained well, and if it seems useful for the adapter, we can have a look at implementing it as an option.

A.

**Comment by volkerrichert** [comment]
Some devices have just one on and one off button, but they didn't store any state. This can be used to simulate brightness internally and you can map the directly to a bulb e.g.

**Comment by asgothian** [comment]
I am afraid I do not really understand this. What kind of devices use this simulated brightness ? Relais ? Remotes ? Switches ?

can you give an example with a device which does support this and a detailed use case ?

A.

**Comment by BenjaminHae** [comment]
For example [this switch](https://www.zigbee2mqtt.io/devices/E1743.html) (by IKEA) has this feature.
The switch itself has no state, it only sends actions. However when paired with a lightbulb it acts as a dimmer.

In zigbee2mqtt a `brightness_value` can be simulated, that automatically is calculated based on the actions.

**Comment by asgothian** [comment]
> For example [this switch](https://www.zigbee2mqtt.io/devices/E1743.html) (by IKEA) has this feature.
> The switch itself has no state, it only sends actions. However when paired with a lightbulb it acts as a dimmer.
> 
> In zigbee2mqtt a `brightness_value` can be simulated, that automatically is calculated based on the actions.

I see the item having the option. I do not see how this has any use, though. When the remote is bound to the lamp, it can change the brightness - this should not require said state. If you want to change the brightness from ioBroker, you change the dp on the lamp, not the remote. As far as i remember, there is no way to "trigger" the button of the remote from iobroker either. So again the question:

What is it useful / needed for ?  How will it be used from ioBroker to achieve something which cannot currently be achieved ?
I do not intend to spend a few hours figuring it out, then implementing it without a clear use understanding how useful it really is.

A.

**Comment by asgothian** [comment]
Closing this due to lack of interest.

**Comment by quotschmacher** [comment]
Even though this is closed it is not solved. I found an example: the Blitzwolf SHP-13 plug. It has a poll interval, which is not stored on the plug itself, but it says how often it should be polled by - I don't now.... The Herdsman converter? 

https://www.zigbee2mqtt.io/devices/TS0121_plug.html

So it would be nice to have this feature, but as I read through the issues you are only going to serve the states presented by the converter...

**Comment by asgothian** [comment]
There can be any number of functions which are handled by the zigbee2mqtt.io code. Each and every one of them would need to be recreated in the ioBroker Zigbee adapter to be made available.

**Noone** will dig through all the devices, identify these configurations and add them to the adapter. Each and every function will need to be requested separately, and for each and every function, a judgement will have to be made if it is worth the effort or not.
