### ISSUE TITLE
How to add socket BW-SHP13?

### ISSUE THREAD

**Issue by kuzma00** [ioBroker/ioBroker.zigbee#909]
How to add socket blitzwolf BW-SHP13?
ioBroker.zigbee version 1.4.0

**Comment by asgothian** [comment]
- Please update to 1.4.1 to verify that it is not covered by the later version and the new exposes
- Verify that the socket is supported in zigbee-herdsman-converters v. 13.0.25.

If the socket is not supported in the herdsman 13.0.25, but supported in the latest, all you need to do is wait for the zigbee Adapter to upgrade to the later herdsman.
If it is not supported in the latest herdsman, please place a device support request here: https://github.com/Koenkk/zigbee-herdsman-converters/issues

A.

**Comment by kuzma00** [comment]
It is supported in zigbee-herdsman-converters. I updated to the 1.4.1 zigbee. But how I can add this socket to the zigbee adapter ? Any documentation ?

**Comment by asgothian** [comment]
Please post the tile from the adapter. It should be covered by the "expose" functionality if it is already supported in the herdsman.

A.

**Comment by kuzma00** [comment]
I can't pair. I have adapter cc2538 and cc2531 and I can't understand what is problem.

**Comment by asgothian** [comment]
Please check the channel in use, also check if you correctly reset the device to factory defaults. If in doubt, go to one of  the ZLL default channels (11,15,20,25).
Even if the device is completely not supported, it has to pair with the zigbee network.

A.

**Comment by kuzma00** [comment]
Thanks. I changed the channel to 20 and everything works.
