### ISSUE TITLE
Pairing Hue bulbs

### ISSUE THREAD

**Issue by hail0** [ioBroker/ioBroker.zigbee#91]
Hi,

I have a questions regarding pairing of a HUE bulb and the Zigbee adapter.
At first I did a factory reset of the bulb  and disconnected the HUE bridge.
Afterwards I clicked several times on the pairing button of the adapter
and after 60 seconds nothing happens. 
Is there any specialty besides turn on the bulb?

Can anyone help me?

BR Hail0

**Comment by Apollon77** [comment]
From my experience turn them on works well ... maybe you need to try several times. else question is if they are really "unpaired". maybe unpair them again

**Comment by kirovilya** [comment]
Try to follow this manual https://github.com/Koenkk/zigbee2mqtt/wiki/Pairing-devices#philips-hue
