### ISSUE TITLE
Temperature from the sensor <-25C

### ISSUE THREAD

**Issue by Guest124** [ioBroker/ioBroker.zigbee#911]
There is a problem when the temperature is not shown below -25C:
1. In the file /opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js by searching for "-25" we find 2 lines "if (temperature> -25 && temperature <65) {"
2. Change "-25" to your value [my value: -45]

**Comment by asgothian** [comment]
Please add more information:
- Which device
- Which situation
- Which version (of the zigbee adapter)
- Which version of the zigbee-herdsman-converters (see package.json)

A.

**Comment by Guest124** [comment]
WSDCGQ01LM (Xiaomi Round Temperature Sensor)
Measured temperature <-25C. The temperature value is not updated or changed
ZigBee 1.4.0
zigbee-herdsman@0.13.39
