### ISSUE TITLE
Error on visiting configuration

### ISSUE THREAD

**Issue by BenjaminHae** [ioBroker/ioBroker.zigbee#913]
Version 1.3.1

Every time I open the configuration page, this error appears and the zigbee adapter terminates:
![image](https://user-images.githubusercontent.com/7386033/103175064-8aa78d80-4867-11eb-8b97-1ea267d6fcf7.png)

Afterwards the adapter is working (but not the configuration page).

Logs are:

zigbee.0 | 2020-12-27 17:18:14.874 | info | (141) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
zigbee.0 | 2020-12-27 17:18:14.872 | info | (141) terminating
zigbee.0 | 2020-12-27 17:18:14.553 | info | (141) Zigbee: disabling joining new devices.
zigbee.0 | 2020-12-27 17:18:14.545 | info | (141) cleaned everything up...
zigbee.0 | 2020-12-27 17:18:14.543 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
zigbee.0 | 2020-12-27 17:18:14.543 | error | at onErrorNT (internal/child_process.js:468:16)
zigbee.0 | 2020-12-27 17:18:14.543 | error | at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
zigbee.0 | 2020-12-27 17:18:14.543 | error | (141) Error: spawn udevadm ENOENT
zigbee.0 | 2020-12-27 17:18:14.541 | error | (141) unhandled promise rejection: spawn udevadm ENOENT
Unhandled | 2020-12-27 17:18:14.514 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by asgothian** [comment]
Please update to 1.4.0 or newer and verify if the error persists.

- post a complete log of the startup until opening the admin page
- post your hardware (which zigbee-coordinator, node version, etc.)
- place the log in full code quotes (\''' \''' rather than \' \')

**Comment by asgothian** [comment]
Closed as this relates to an outdated version. Please reopen if the issue persists with Adapter Version 1.4.1
