### ISSUE TITLE
Heiman HS1RC-N Smart Remote: button press not recognized 

### ISSUE THREAD

**Issue by olix74** [ioBroker/ioBroker.zigbee#914]
Hello "Arteck", first of all thank you for updating the Zigbee adapter to detect the Heiman smart remotes.
The remotes are now detected successfully, but button press is not recogized.
I used "deconz" previously and they have a similar problem. It seems the "IAS Zone" (intended for security systems) needs to be enabled - can you guide me how to do that or do you have another idea why they might not be working?
Thank you,
Oliver

**Comment by asgothian** [comment]
you need to check in the used zigbee-herdsman-converters (devices.js) for the "configure" code on the remote. If it does not configure reporting for the IAS Zone, that could be a reason the button press does not reach

**Comment by olix74** [comment]
Hello asgothian,
thank you for your support.
I tried the following in devices.js, (two versions) - regrettably both don't work in the sense of button press still don't work - any idea on what I might be doing wrong?
Thank you,
Oliver
    {
        fingerprint: [{modelID: 'RC-EM', manufacturerName: 'HEIMAN'}],
        model: 'HS1RC-EM',
        vendor: 'HEIMAN',
        description: 'Smart remote controller',
// Version 1
        fromZigbee: [fz.battery, fz.heiman_smart_controller_armmode, fz.command_emergency],
        toZigbee: [],
        exposes: [e.battery(), e.action(['emergency', 'disarm', 'arm_partial_zones', 'arm_all_zones'])],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genTime', 'genBasic', 'ssIasAce', 'ssIasZone']);
            await configureReporting.batteryPercentageRemaining(endpoint, {min: repInterval.MINUTES_5, max: repInterval.HOUR});
            await endpoint.read('genPowerCfg', ['batteryPercentageRemaining']);
        },

/* Version 2 - copied from Tuya remote
        fromZigbee: [fz.command_arm, fz.command_emergency, fz.battery],
        exposes: [e.battery(), e.action(['disarm', 'arm_day_zones', 'arm_night_zones', 'armall_zones', 'invalid_code', 'emergency'])],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genTime', 'genBasic', 'ssIasAce', 'ssIasZone']);
        },
*/
    }

**Comment by asgothian** [comment]
Na ja.. einfach Konfigurationen von anderen Remotes zu kopieren hilft in den seltensten Fällen. Du musst Dir schon anschauen was an Funktionen im fz. und tz. heran gezogen werden, und auf welche Zigbee Meldungen der Button wie reagiert. Auch alleine die Konfiguration eintragen reicht nicht unbedingt, du musst dann auch sicher stellen das diese Konfiguration auf der Remote ankommt.

A.

**Comment by olix74** [comment]
Hallo, nochmal besten Dank. Habe ich mir gedacht. Wie könnte ich mich einem Debugging nähern? Ich habe in den Iobroker Adapter Settings die "Zigbee-herdsman debug info" eingeschaltet, kann aber nirgendwo einen entsprechenden Log finden (bzw. sehe ich in den Iobroker Logs keine entsprechenden einträge). Gibt es eine gute Möglichkeit die "Zigbee Meldungen" anzuzeigen?
Danke, Oliver

**Comment by asgothian** [comment]
Wenn du in dem Log keine Log einträge "message received" bekommst wenn der Knopf gedrückt wird dann sendet die FB keine Nachricht. In diesem Fall musst du:

- im fz.xxx nachschauen wie die Nachricht aussehen soll auf die der Schalter reagieren soll
- schauen ob du per "bind" und "configure_reporting" in der Konfiguration die FB dazu bringen kannst Nachrichten zu senden
Dabei solltest du sicherstellen das das configure auch durch geht (keine Warnmeldungen über failed configure im log) und das configure bei jedem Adapterstart erzwingen (in zbDeviceConfigure.js) gibt es eine Liste von Geräten die bei jedem Start neu konfiguriert werden.

A.

**Comment by olix74** [comment]
Hallo, ich hoffe ich überstrapziere Deine Hilfsbereitschaft nicht. Ich weiß leider nicht, wo das "Zigbee Herdsman Log" liegt und wie ich es öffne? Im Iobroker Log ist nichts (auch nicht von anderen Zigbee-Devices). Danke, Oliver

**Comment by asgothian** [comment]
gemeint ist das normale log, aber die Ausgaben die erst dann kommen wenn der Adapter im Debug ist und gleichzeitig herdsman-debug-info gesetzt ist.

A.

**Comment by olix74** [comment]
Thanks a lot - I can see debug messages now. 
Nevertheless I'm still struggeling a lot on how to add or debug new devices and I have 2 questions:
1. A more general one: Is there a tutorial or any documentation on the concepts of zigbee-herdsman or this adapter? I just don't want to waste anybodies time with stupid questions, since I think I can work into it when understanding general concepts (esp. between devices.js, fromzigbee.js, tozigbee.js).
2. Concrete One: According to Zigbee Spec IasAce Devices need to get some special response and I would like to add those, but I don't know how to send them? I tried to add a handler to "tozigbee.js" (similar to arm_mode) and added a handler to "toZigbee[]" in devices.js, but I don't understand when/ how this is triggered. I also tried to add an event to devices.js, but same story here - I don't know when they are triggered. 
Any help appreciated. Thank you,
Oliver

**Comment by asgothian** [comment]
closing this issue - further handling in Issue #922. Once that issue is resolved, this should be resolved as well.
