### ISSUE TITLE
fehlerhafte Netzwerkkarte

### ISSUE THREAD

**Issue by FV1405** [ioBroker/ioBroker.zigbee#915]
hallo, ich nutze einen Raspberry 4 mit einem Conbee II Stick und den Zigbee-Adapter.
Alle Geräte sind eingebunden, funktionieren auch, haben auch eine ausreichende Verbindung. trotzdem zeigt mir die Netzwerkkarte im Zigbee-Adapter keine Verbindungen an:
![image](https://user-images.githubusercontent.com/76660615/103177079-86836c00-4877-11eb-8da6-0ba0d0bf72a1.png)

ist dieses Problem schon mal aufgetreten und kann man es beheben?
Danke für eure Hilfe
FV1405

**Comment by asgothian** [comment]
- Which version are you running ?
- did you check back after 120 seconds to see if the map completes ?

A.

**Comment by FV1405** [comment]
hello, at last it's version 1.41. I changed it from 1.40 to 1.31 and 1.41
with 1.41 it is better:
![image](https://user-images.githubusercontent.com/76660615/103205750-95f7c900-48fa-11eb-84c8-d372b8286c6c.png)

**Comment by asgothian** [comment]
That is about as good as it can get. The issue with battery driven devices is that they can not always be queried, so it is not ensured that they will respond to a routing query. As the zigbee network is a self organizing mesh the network map needs to be regenerated by requesting the route from its members. If a device does not respond, it will be shown as red for the map.

Also: the Osram Plugs do not play nice when doing routing queries, so they also might be the reason for missing lines between devices.

A

**Comment by FV1405** [comment]
thank you asgothian, 
thanks, then at least i know that the installation was okay. everything works too
