### ISSUE TITLE
Zigbee adapter works for one day than restarts every 5 minute

### ISSUE THREAD

**Issue by Heleklu** [ioBroker/ioBroker.zigbee#916]
Hardware: Pi 4 with 4 GB, CC26X2R1 with latest Firmware 3.X.0
Zigbee Adpaterversion is 1.3.1

its a clean set up from yesterday so everything is new but i had the problem serveral times before thats why i made a new setup

I attached the iobroker logfile
[iobroker.2020-12-28.log](https://github.com/ioBroker/ioBroker.zigbee/files/5747283/iobroker.2020-12-28.log)

**Comment by asgothian** [comment]
please update to 1.4.1 and see if the error persists.
Also please stop the adapter when the error occurs next, verify that the adapter was completely shut down and then start the adapter again manually.

A.

**Comment by Heleklu** [comment]
still the same problem than before. 
I attached the new log file. i stopt the adapter and startet it again
[iobroker.current.log](https://github.com/ioBroker/ioBroker.zigbee/files/5748741/iobroker.current.log)

**Comment by asgothian** [comment]
On the iobroker forum you mentioned your iobroker installation dying.
Did you replace the SD card before setting up your system again ? Did you install fresh, or did you restore from a full backup ?
The error messages hint at a broken object / state database, which would indicate an issue with the SD Card.
If not, please do the following:
- stop the zigbee adapter
- on the console, go to /opt/iobroker/iobroker-data/zigbee_0
- check the shepherd.db file. There should be several backups of this file. Please try to identify the backup which is from before the crashing issue. Remove the shepherd.db and restore it from said backup
- start the zigbee adapter
A.

**Comment by Heleklu** [comment]
It's a fresh setup.
Yesterday I also tried to delete the whole adapter and reinstalled the 1.3 version. The system runs stable until now but I only connected 7 bulbs and one aqara motion sensor. Maybe there is a problem with the IKEA smart plug I connected it some days before the first error occurred. I'll trie two connect more and more sensor until it starts again.

**Comment by asgothian** [comment]
Did you try what i suggested you try in the previous post ?

A.

**Comment by Heleklu** [comment]
There are only backups from the past to days. I made a clean install three days ago so there are only backups with a faulty database

**Comment by asgothian** [comment]
You said that it ran for a day before it started crashing.. the first (oldest) database should be a good backup, i would say - one to try.

A.

**Comment by asgothian** [comment]
I found a bug in the zigbee shepherd which may also cause your issue. Can you please follow the description below and post all lines linked to the first error which causes the Adapter to restart:

- disable the adapter
- Disconnect your zigbee coordinator from the system for 30 seconds
- Reconnect the coordinator
- Start the adapter - it should either crash within the first 30 seconds after starting or after approx 5 minutes if the bug I mentioned affects you.

As I did before, I can offer to try and get to the bottom of this crash in a remote session. Would you be interested ? We would be using the iobroker discord for voice communication and any desk for remote access to your system.

A.

**Comment by Heleklu** [comment]
sorry for my late reply

meanwhile i changed the sd to a ssd. and toda i tried your suggestion but the error ist still the same. i attached the log file.

yes we can make a remote session.

**Comment by asgothian** [comment]
I can offer a remote session sometime next week, possibly Thursday evening, using the ioBroker discord as initial point of contact. I will be there around 7 PM CET. You are welcome to check at other times if i am there, often around 7 PM.

A.

**Comment by Heleklu** [comment]
Thank you. On Thursday I'll be there at 7 pm.

**Comment by asgothian** [comment]
Main issue seems to be fixed with update to 1.4.3
