### ISSUE TITLE
Wrong Paring result with SEA801-Z01 valve (finding SEA802...)

### ISSUE THREAD

**Issue by extreme4u** [ioBroker/ioBroker.zigbee#921]
Hello, 

i want to pair a SEA801-Z01 in combination with an Deconz/Conbee II USB Adapter. 
But i get just a wrong pairing result. 
![Screenshot 2020-12-31 132311](https://user-images.githubusercontent.com/59170539/103411020-386bb280-4b6e-11eb-82b5-272f407ee77d.png)
![Screenshot 2020-12-31 132550](https://user-images.githubusercontent.com/59170539/103411026-41f51a80-4b6e-11eb-906e-1af9006f22c3.png)
The adapter think i have an SEA802 valve. But thats wrong.

**Comment by o0shojo0o** [comment]
Please update your adapter from this git, and try again.

**Comment by extreme4u** [comment]
Sorry i am actually a noob....
![Unbenannt](https://user-images.githubusercontent.com/59170539/103413607-a322eb00-4b7a-11eb-832a-056270dcb761.PNG)

**Comment by o0shojo0o** [comment]
![image](https://user-images.githubusercontent.com/19333515/103414322-c69b6500-4b7d-11eb-92f9-f96f4c69b31b.png)

**Comment by extreme4u** [comment]
Okay, 
i have clear some disk space but still the same problem. 
![Unbenannt](https://user-images.githubusercontent.com/59170539/103466655-18431b80-4d47-11eb-916e-7c20d8345a2f.PNG)

**Comment by asgothian** [comment]
Please install the 1.4.2as version from

https://github.com/asgothian/ioBroker.zigbee/tarball/Thermostating

Please note that this version may have additional side effects as it is a test version, but it should link the thermostat to the changed data in the latest herdsman.

A.

**Comment by extreme4u** [comment]
Still the same problem. There is one other error. Maybe this one makes problems?

![Screenshot 2021-01-03 230331_111](https://user-images.githubusercontent.com/59170539/103489900-43497000-4e18-11eb-9fb4-27ddb1bcebfa.png)

**Comment by asgothian** [comment]
Please copy the text from the message and post it in extended code tags. The screenshot is nearly unreadable and hints at issues with the adapter installation.

Note that the message shows that you did not install the requested 1.4.2as version but the 'standard' GitHub version.

Please check the iobroker log for the adapter version reported at adapter start and post it.

As far as i could make out you still have an issue with your node / nodejs installation. This needs to be fixed before the thermostat can work.

A.

**Comment by extreme4u** [comment]
Good news! I updated my nodejs from Version 10 to 12. 
I instal the debug version and now i can pair the valve. I also try to controll the valve. I work now. 
Thank you so far! :)

**Comment by asgothian** [comment]
Nice.. closing this.
