### ISSUE TITLE
Incomplete implementation of IAS ACE causes multiple "keyfob" devices to send duplicate button events/repeats

### ISSUE THREAD

**Issue by olix74** [ioBroker/ioBroker.zigbee#922]
This one is somewhat linked to #914.

## What happened
I'm seeing multiple retries/messages of button events on multiple security remote controller keyfobs (at least Heiman HS1RC and Immax 07046L). Heiman semms to be sending four repeats every ~7s before giving up, Immax sending two events ~5s. Both seem to indicate a failed transaction with a red led afterwards. Regrettably each repeat comes with a seperate transaction number, so they can not be filtered out easiliy/ it is not possible to distinguish two consecutive button presses from the repeat.
 
## Why is this bad?
Some applications require one touch actions - first press -> turn on, second press -> turn off. These can not be implemented. Appart from that batteries are drained much faster due to unnecessary repeats. 
Keyfob indicates failed transaction with red led - which is confusing to users.

## What did you expect to happen
Avoid retransmitions. Transaction successfull indication on keyfob with green led (instead of transaction failed)

## How to reproduce it (minimal and precise)
Happens on every single button press on the Heiman remote and happens for all buttons except "SOS" on Immax remote.
Regrettably I can only reprdocue on Immax since I still don't see any events on Heiman remote for whatever reason (but I do observe same behaviour on Heiman on phoscon/deconz adapter)  -see #914.

## Debug info
Adapter version: Iobroker.adapter 1.4 as of Dec. 2020 which is using zigbee-herdsman library.
Adapter hardware: Conbee II
Adapter firmware version: 26680700 as of 30th of November 2020 /should be latest

## Analysis and Proposal
I'm also really no expert in Zigbee. Nevertheless I had a look at https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf which I assume to be part of the relevant zigbee spec.
As both devices are IAS ACE devices I'm xpecting that they require a responses from a security system, so it would be needed to "pretend" to be such a security system.
Here is my proposal for that after reading through the spec:

8.3 specifies IAS ACE,
8.3.2.4 the Commands Received (from Heiman and Immax remote )and
8.3.2.5 the expected/proposed responses to be generated (currently missing in Adapter implementation).

Proposal 1:
I assume that all buttons except SOS generate an "Arm Command" according to 8.3.2.4.1
As such they probably expect a response according to 8.3.2.4.1.5
Here it says "The device SHALL generate an "Arm Response command" (see 8.3.2.5.1)to indicate the resulting armed state."
8.3.2.5.1 explains this response.
Respone should be two bytes and is explained below:
Command ID --> 0x00 Arm Response
followed by following "Arm Notification" (enum8) content according to following table
- 0x01 Only Day/Home Zones Armed
- 0x00 All Zones Disarmed
- 0x03 All Zones Armed

Proposal 2:
In addition it MIGHT be necessary to send "Panel Status Changed Command" ID=0x04 according to 8.3.2.5.5
I would assume following responses

Panel Status: 0x01 Armed Stay, Seconds Remaining: 0x00, Audible Notification: 0x01 (default), Alarm Status: 0x00 (no Alarm)
Panel Status: 0x00 Panel disarmed, Seconds Remaining: 0x00, Audible Notification: 0x01 (default), Alarm Status: 0x00 (no Alarm)
Panel Status: 0x03 Armed away, Seconds Remaining: 0x00, Audible Notification: 0x01 (default), Alarm Status: 0x00 (no Alarm)

Nevertheless one could argue that this should only be triggered by a real IAS alarm system connected to adapter instead of being riggered directly by adapter.

Proposal 3:
Regrettably 8.3.2.4.3 does not explain the response to emergency button 3002.
I would propose to also send a "Panel Status Changed Command" ID=0x04 according to 8.3.2.5.5
Panel Status: 0x07 In alarm, Seconds Remaining: 0x00, Audible Notification: 0x01 (default), Alarm Status: 0x03 (Emergency)

I'm happy to help, but I failed to understand the concept behind IObroker zigbee adapter and zigbee herdsman. So if someone could guide me on how to send responses I'm happy to contribute.
My assumption would be:
Proposal 1 should be implemented as a direct response from the Adapter - as such may be imlemented as an "event" in devices.js or "fromzigbee.js"?
Proposal 2 should be implemented as an application responce from outside the adapter - as such maybe impleneted as a "tozigbee" service?

I would propose to start with Proposal 1 first - hopefully that is already sufficient.
Best regards,
Oliver

**Comment by asgothian** [comment]
This is an issue which needs to be handled on this project:

[https://github.com/Koenkk/zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters)

Please open an issue at this project. Once the implementation is complete we can see how to work with it in our adapter.

A.

**Comment by olix74** [comment]
Hello @asgothian,
I opened it in zigbee2mqtt and @koenkk already provided a hint on how to fix in https://github.com/Koenkk/zigbee2mqtt/issues/5489 . **He also raised the question if the "onEvent" method of zigbee-herdsman  is called by IOBroker? Does anybody know if this is the case?**
I'm still struggeling with my debug efforts since I can't see any console.log() nor am I able to get node inspect to work.
Any help appreciated (on above question), Oliver

**Comment by asgothian** [comment]
The onEvent function is called if defined.

**Comment by asgothian** [comment]
> Hello @asgothian,
> I opened it in zigbee2mqtt and @Koenkk already provided a hint on how to fix in [Koenkk/zigbee2mqtt#5489](https://github.com/Koenkk/zigbee2mqtt/issues/5489) . **He also raised the question if the "onEvent" method of zigbee-herdsman is called by IOBroker? Does anybody know if this is the case?**
> I'm still struggeling with my debug efforts since I can't see any console.log() nor am I able to get node inspect to work.
> Any help appreciated (on above question), Oliver

What i would do: 
- set up a devcontainer (there is a long post in the iobroker forum as to how to do this)
- run the adapter inside the devcontainer using visualstudio.code. 

If you grab the adapter from my repository (asgothian/iobroker.zigbee), you should find the required configuration for a devcontainer already present. In order to use it, you would have to start the container through visual studio code, install the adapter locally in the container and add an instance, but not start it from admin. Once that is done, you can start the adapter itself from visual studio code and access most variables and events.

Alternatively, you can use the functions 'this.log, this.warn and this.error to print information into the iobroker log.

A

**Comment by olix74** [comment]
Thank you, I will give that a try.
Best regards,
Oliver

**Comment by asgothian** [comment]
@olix74 Any news on this issue ? I noticed that the issue on the herdsman side has been closed. Has it been resolved ?
