### ISSUE TITLE
Support for Revolt Thermostat NX-4914-919 (fvq6avy)

### ISSUE THREAD

**Issue by huk13** [ioBroker/ioBroker.zigbee#926]
The Revolt NX-4914-919, a variant of the Tuya thermostat, needs to be listed in the herdsman-converters file devices.js. The following patch, introduced under //Siterwell (another variant) fixes the statesMapping error:

`zigbeeModel: ['ivfvd7h', 'eaxp72v\u0000', 'kfvq6avy\u0000', 'fvq6avy\u0000', 'fvq6avy'], `

(adding the last 2 models). See [forum contribution](https://forum.iobroker.net/post/548888)
Thank you and regards,
HUK

**Comment by asgothian** [comment]
a PR is made to the zigbee-herdsman-converters to include these changes. It has gone through, so as soon as the zigbee adapter adapts the latest herdsman, the changes will be in. Closing this for now.

**Comment by huk13** [comment]
Thanks
HUK
