### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by RudiXXL** [ioBroker/ioBroker.zigbee#927]
Hi guys! Have a grat new year!

Thanks a lot for your time and hard work on the adapter. It runs very stable now and also the ZigBee map is working proper. Congrats!

With Update from 1.2.1 to 1.4.2 I had a restart of the zigbee adapter every 5 minutes. In the log I had the hint to a device. It is the thermostate valve from [MOES](https://zigbee.blakadder.com/Moes_HY369-ZB-RVT.html). In ver. 1.2.1 it was working proper and the correct picture was shown. With ver 1.4.2 also the picture came up wrong. After deleting the device the failure was away. When rejoining to the network the process stopped after frist line with "interview" and after that the adapter started every 5 mins again with nearly the same message. See log below.

BR
Rudi

type:ConBee2/RaspBee2
version:0-0.38.104.0.
revision:0x26680700

JS controller  3.1.6
Node.js: v12.20.0
NPM: 6.14.8

zigbee.0 | 2021-01-03   15:57:29.179 | info | (4849) cleaned   everything up...
-- | -- | -- | --
zigbee.0 | 2021-01-03   15:57:29.178 | error | (4849) Error:   Command 0xec1bbdfffe8d51b0/1   manuSpecificTuya.setTime({"payloadSize":8,"payload":[95,241,219,29,95,241,233,45]},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disable
zigbee.0 | 2021-01-03   15:57:29.177 | error | (4849) unhandled   promise rejection: Command 0xec1bbdfffe8d51b0/1   manuSpecificTuya.setTime({"payloadSize":8,"payload":[95,241,219,29,95,241,233,45]},   {"timeout":10000,"disableResponse":false,"disableRe
zigbee.0 | 2021-01-03   15:57:29.176 | error | Unhandled promise   rejection. This error originated either by throwing inside of an async   function without a catch block, or by rejecting a promise which was not   handled with .catch().
heatingcontrol.0 | 2021-01-03   15:56:46.008 | info | (450) 4 cron   job(s) created
zigbee.0 | 2021-01-03   15:56:13.870 | info | (4849) Starting   interview of '0xec1bbdfffe8d51b0'
zigbee.0 | 2021-01-03   15:56:03.163 | warn | (4849) Failed to   ping 0xbc33acfffef4ce07 TS0601
zigbee.0 | 2021-01-03   15:56:01.863 | info | (4849) Zigbee:   allowing new devices to join.

**Comment by asgothian** [comment]
- Please post a complete log. Your log entries are truncated before getting to the interesting part.
- Please post the exact identification of the affected device - most notably the model and zigbee model entries from your tiles.

A.

**Comment by RudiXXL** [comment]
here is the complete log.
[thermostat.txt](https://github.com/ioBroker/ioBroker.zigbee/files/5769840/thermostat.txt)

**Comment by asgothian** [comment]
This log is as incomplete as the pasted information. See this line:

`zigbee.0	2021-01-05 12:02:12.250	error	(23640) Error: Command 0xec1bbdfffe8d51b0/1 manuSpecificTuya.setTime({"payloadSize":8,"payload":[95,244,70,248,95,244,85,8]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableD
`

It cuts of mid message.

**Comment by RudiXXL** [comment]
was my fault, sorry, all good things need three times ;-) I learned that it is not possible to copy the log by marking the screeen... I hope the kog is fine now.

[thermostat 2.txt](https://github.com/ioBroker/ioBroker.zigbee/files/5770111/thermostat.2.txt)

**Comment by RudiXXL** [comment]
> Please post the exact identification of the affected device - most notably the model and zigbee model entries from your tiles.

ieee:0xec1bbdfffe8d51b0
nwk:35883 (0x8c2b)
model:TS0601_thermostat

**Comment by asgothian** [comment]
I had some time to dig through this. It seems as if the initial identification is sending a command to the lamp which then causes the zigbee-herdsman to die. I do remember that there was an issue with two thermostat versions from Moes reporting the same version but actually being different. Hence the question - the image shown on the page you linked matches the image of the thermostat ? 

Also - are you available on thursday or friday for a remote session to try and debug this behavior ? Sending logs back and forth won't necessarily help, and with the location of the error, it seems tricky to identify just  what exactly happens when it dies.

A.

**Comment by asgothian** [comment]
I also managed to find some differences in the code handling the thermostats. I believe there is a chance to patch the herdsman-converters to evade the error for now, but additional work might be needed in the herdsman to recover full functionality to the thermostat.

A.

**Comment by RudiXXL** [comment]
> the image shown on the page you linked matches the image of the thermostat ?
Yes the picture from the link is that thermostat I have.  

> are you available on thursday or friday for a remote session to try and debug this behavior ?
I have time on thursday and friday in the evening. I propose 19:00 CET.

**Comment by asgothian** [comment]
Lets meet on Thursday, 19:00 on the [ioBroker discord.](https://discord.gg/Fk4r5tqf)

A.

**Comment by asgothian** [comment]
The fix has been implemented in the latest Zigbee-Herdsman-Converters. It should make its way into the adapter with the next version number upgrade.

A.

**Comment by RudiXXL** [comment]
many thanks @asgothian, the fix is working fine :-)
