### ISSUE TITLE
Failed to Ping" warnings with Version 1.4.2

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.zigbee#928]
Hello together,
In version 1.4.2 I now constantly receive info messages in the LOG about:

zigbee.0 | 2021-01-06 08:45:14.168 | warn | (1146) Failed to ping 0x588e81fffed984f7 TS0121
-- | -- | -- | --
zigbee.0 | 2021-01-06 08:44:14.162 | warn | (1146) Failed to ping 0x00124b001efe8072 lumi.router
zigbee.0 | 2021-01-06 08:44:13.162 | warn | (1146) Failed to ping 0x00124b001f3202b9 lumi.router

Is it possible to suppress this? or only output this Messages at DEBUG Mode if necessary.
Thank you.

Greetings Fabian

**Comment by modmax** [comment]
Duplicate to #923

**Comment by FabianHM** [comment]
> 
> 
> Duplicate to #923

Completely correct, my mistake. thanks
