### ISSUE TITLE
Please add support for QS-Zigbee-C01 Zigbee Curtain Module

### ISSUE THREAD

**Issue by BepT-DK** [ioBroker/ioBroker.zigbee#929]
Hi, 

link to device from ali:
https://www.aliexpress.com/item/1005001530266723.html
![image](https://user-images.githubusercontent.com/77129329/103955875-fa632580-514f-11eb-92a1-3f2663e5c45c.png)

Device in iobroker looks like another device model with another properties:
![image](https://user-images.githubusercontent.com/77129329/103956044-5ded5300-5150-11eb-8c51-48ded8d1b56b.png)

model:TS130F
description:Curtain/blind switch
modelZigbee:TS130F
type:Router
nwk:58229
manuf id:4098
manufacturer:_TZ3000_vd43bbfq
power:Mains (single phase)
app version:64
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false

![image](https://user-images.githubusercontent.com/77129329/103956143-90974b80-5150-11eb-927e-e0ad36455ef2.png)

I find properties for this model from iobroker.tuya:
![image](https://user-images.githubusercontent.com/77129329/103956515-5b3f2d80-5151-11eb-8018-3a0bf294b31b.png)

{mode:rw,code:control,name:设备控制,property:{range:[open,stop,close],type:enum},iconname:icon-a_power,id:1,trigger:direct,type:obj},
	{mode:rw,code:percent_control,name:百分比控制,property:{unit:%,min:0,max:100,scale:0,step:10,type:value},iconname:icon-icon-percent,id:2,type:obj},
	{mode:rw,code:cur_calibration,name:行程校准,property:{range:[start,end],type:enum},iconname:icon-dp_loop,id:3,type:obj},
	{mode:rw,code:control_back,name:电机转向,property:{range:[forward,back],type:enum},iconname:icon-dp_loop,id:8,type:obj},
	{mode:rw,code:tr_timecon,name:行程时间设置,property:{unit:s,min:1,max:120,scale:0,step:1,type:value},iconname:icon-dp_time,id:10,type:obj}

Thank you very much.

**Comment by asgothian** [comment]
The issue with the image is secondary. We are moving away from component images and towards symbol images instead. The key questions from my point of view are:

- can you control the unit using the "position" DP (values 0 to 100)
- does it update the "moving" DP when it is moving the blinds up and down ?
- can you turn the motor on/off by using the "state" DP to true / false
- can you change motor direction using the motor_reversal DP ?
A.

**Comment by BepT-DK** [comment]
All these things are working but it seems that driver exposes properties from device with another manufactor_id:
 modelID: 'TS130F' manufacturerName: '_TZ3000_egq7y6pr'

I have device with   modelID: 'TS130F', manufacturerName: '_TZ3000_vd43bbfq' and some properties are missing:
{mode:rw,code:tr_timecon,name:行程时间设置,property:{unit:s,min:1,max:120,scale:0,step:1,type:value},iconname:icon-dp_time,id:10,type:obj}

**Comment by asgothian** [comment]
The new Unit should be available on the 1.4.2 version of the zigbee Adapter, installable from Github. It may or may not show up with the correct image, but it should be usable from the zigbee-herdsman-converters exposes.

Please install the latest version from Github and verify.

A.

**Comment by BepT-DK** [comment]
Last version installed, still missing property of schedule time (time from full open to full close position). Set by calibration device
![image](https://user-images.githubusercontent.com/77129329/104127057-aaab7680-5368-11eb-921a-b185f5ea5afc.png)

![image](https://user-images.githubusercontent.com/77129329/104127080-c878db80-5368-11eb-84ad-87a9cdf3ed8a.png)

**Comment by asgothian** [comment]
Please open an issue at [this](https://github.com/Koenkk/zigbee-herdsman-converters) project to get this implemented. It is not yet present in the converters, so the iobroker adapter cannot provide the datapoint.

Due to the fact that the item is a rebranded Tuya Product, which does not adhere to the typical Zigbee Cluster mechanics, you will need assistance from an expert in these kinds of products.

A.

**Comment by asgothian** [comment]
closed due to inactivity.
