### ISSUE TITLE
multibe adapter errors "Cannot read property '100' of undefined"

### ISSUE THREAD

**Issue by thps1990** [ioBroker/ioBroker.zigbee#93]
Hi iobroker.zigbee developers,

i´m using this zigbee-adapter with a cc2531 coordinator and one  cc22531 router for a couple of days. 
Every 15 to 30 minutes i´m getting many errors in my iobroker log. It starts with:
`2018-11-03 19:18:50.471  - [31merror[39m: zigbee.0 uncaught exception: Cannot read property '100' of undefined`

and ends with

`2018-11-03 19:18:50.521  - [31merror[39m: host.Smarthome instance system.adapter.zigbee.0 terminated with code 0 (OK)`

The log is attached here. 
[error_log.txt](https://github.com/ioBroker/ioBroker.zigbee/files/2545268/error_log.txt)

There´s another issue on my zigbee instance and im not shure if this is conjoined to this issue: 
My network map looks like this:
![network map](https://user-images.githubusercontent.com/35417595/47956301-aaeaa300-dfa2-11e8-9cae-af5900d22f58.PNG)
All sensors are working fine (in case the adapter isn´t restarting ....), even the endpoint that are not connected to the coordinator on the map. I´m also not able to pair the router. I unpaired the router and try to pair it again, but it does not work at all. imho the endpoints, that are not connected with the coordinator are connected to the router (and they work!)

any ideas to this issue?

thanks a lot!

**Comment by allofmex** [comment]
Please update to latest adapter version. Network map was changed recently and the other issue may hopefully be gone too.
