### ISSUE TITLE
Please add scheduled pairing feature

### ISSUE THREAD

**Issue by setfire2** [ioBroker/ioBroker.zigbee#930]
I have some lightswitches that occasionally (every few days) loose their connection from the Zigbee network. After initiating the pairing in ioBroker, they work again. It would be nice if it was possible to schedule the pairing process regularly. I noticed that the normal use of the Zigbee setup is not affected by pairing. It works as usual during the pairing process.

**Comment by setfire2** [comment]
I think the best would be, if the attribute zigbee.0.info.pairingMode would be writable. Then it would be easy to create a Javascript/Blockly/Nodered or whatever that could monitor the availability of the Zigbee devices and start pairing mode if one device becomes unavailable.

**Comment by asgothian** [comment]
I am afraid this will not solve your problem.
A Switch which becomes unresponsive but joins the network after pairing mode was active has been removed from the network. This usually happens with switches which are connected through a router device which - due to an inactivity timeout - has removed the Switch from its routing table while the switch still has the router as active connection. I have been able to confirm that this happens consistently with Immax plugs (see the Wiki article on problem devices).
Opening the network will only help if the Switch is pressed during the time the Network is Open. The chance for this occurring is directly linked to the ratio nétwork open/network closed.

A.

**Comment by asgothian** [comment]
> I think the best would be, if the attribute zigbee.0.info.pairingMode would be writable. Then it would be easy to create a Javascript/Blockly/Nodered or whatever that could monitor the availability of the Zigbee devices and start pairing mode if one device becomes unavailable.

This is technically possible, but not sensible:

- the available DP for battery powered devices (end devices) is set based on a timeout. If the device does not send a message within x seconds, the device is considered unavailable
- Some devices only send a message when actively triggered, and as such are marked unavailable if the activation occurs too rarely.
- The available DP for router devices is linked to a periodic Ping attempt. Issue #923 shows  also generates false detections on a regular basis.

as it stands now, using this state to open the network would open the network 
- too often
- most likely at the wrong time
- In cases where this is not needed/sensible.

it could even lead to a network which is almost permanently open if a monitored device is not used and therefore never returned to an available state.

A.

**Comment by setfire2** [comment]
Other idea: make it possible to activate automated pairing after adapter starts. That makes sense since some devices loose the connection after a reboot of the homeserver. Then, combined with the scheduled adapter restart that already exists in ioBroker, a scheduled repairing can be configured as well.

**Comment by asgothian** [comment]
> Other idea: make it possible to activate automated pairing after adapter starts. That makes sense since some devices loose the connection after a reboot of the homeserver. Then, combined with the scheduled adapter restart that already exists in ioBroker, a scheduled repairing can be configured as well.

This also will not fix anything. The operator will be required to trigger the device for a reconnect when the system restarts. How will the “human” know which devices to trigger when if this is automated ?

**Comment by setfire2** [comment]
Well, in my experience, devices that once had joined the network and then get bumped out do automatically reconnect if the coordinator is available again and in promiscous mode.

**Comment by setfire2** [comment]
And especially after rebooting my device or after a power loss it would be nice if the pairing is executed once automatically. Because this is what I do manually every time after such an event. And I don't need to active the pairing mode on the other devices than the coordinator to get them back into the network.

**Comment by asgothian** [comment]
This may be true for router devices. It is not true for battery powered devices, as these will only have wireless activity when needed.

A.

**Comment by setfire2** [comment]
Maybe. Nevertheless, what is the conclusion? I can only talk about my user experience with the adapter and my devices. I have a door sensor and a smoke detector as well (both) battery driven. They do not have any issues with reconnecting to the network after a reboot of the coordinator. My light switches (which don't act as routers, btw) do have an issue there and putting the coordinator into pairing mode once after a restart would pretty sure bring some cure.

**Comment by asgothian** [comment]
Can you post the device type of your light switches ? It is possible that they are not bumped off the network but require a reconfigure after network restart to send their status changes to the correct device. This can be easily patched in for a test.

A.

**Comment by setfire2** [comment]
Sure. They are of this kind:
https://www.zigbee2mqtt.io/devices/TI0001.html

**Comment by kirovilya** [comment]
`sendTo('zigbee.0', 'letsPairing', {});`

**Comment by setfire2** [comment]
Hi, thanks for that line of code. Where do I need to put it?

**Comment by kirovilya** [comment]
@setfire2 in any schedule scripts

**Comment by setfire2** [comment]
Do you mabe know a way to do this once after the start of the zigbee adapter?

**Comment by setfire2** [comment]
Im mean there is this event trace in iobroker but I can't find a way to react on a specific event.

**Comment by kirovilya** [comment]
when 'zigbee.0.info.connection' set to true
but this can happen before the scripts start and therefore it will not be possible to catch it

**Comment by asgothian** [comment]
The way to do this is
- place an if Statement at the start of a script to see if zigbee.0.info.connection is true and system.zigbee.0.alive is true.if it is, you can run the send to command.
- If it is false set a trigger for zigbee.0.info.connection to be greater than before. In the trigger run the Script.

the if statement will run when the JS adapter starts. System.zigbee.0.alive will be true if the zigbee adapter is running, so if it is and the connection state is true too the zigbee adapter already started.

I still think this is not the way to go. If you are willing to test a patch you can add “TI0001” to the array forcedConfigureOnEachStart in lib/zbDeviceConfigure.

this will ensure that the adapter tries to configure them on every adapter start might solve your issue without opening the network automatically.

A.
