### ISSUE TITLE
Sunricher in wall switch 

### ISSUE THREAD

**Issue by boeckp** [ioBroker/ioBroker.zigbee#933]
Hallo,

wenn ich den Switch state in den Objekten ändere startet der ZigBee Adapter neu.
Der Aktor behält seinen alten Zustand.
Im Entwickler Tab ist es möglich den State zu ändern.
Woran könnte das liegen?
![IMG_0435](https://user-images.githubusercontent.com/2220951/104212517-997c6b80-5435-11eb-9c79-bfe3c9f7cfef.jpeg)
![IMG_0436](https://user-images.githubusercontent.com/2220951/104212538-9f724c80-5435-11eb-81df-82e0afb5e2f0.jpeg)
[zigbee_log.txt](https://github.com/ioBroker/ioBroker.zigbee/files/5797178/zigbee_log.txt)

Peter

**Comment by asgothian** [comment]
Which version of the zigbee adapter do you have installed ?

A.

**Comment by boeckp** [comment]
Version 1.4.2

**Comment by asgothian** [comment]
Please install the test version from my fork (https://github.com/asgothian/ioBroker.zigbee). It should include a fix for this error, but might raise warning messages whenever you attempt to control the device. If it does, please post these messages.

A.

**Comment by boeckp** [comment]
Thank you, it works.

**Comment by asgothian** [comment]
Reopened - the fix needs to go into the main branch. Also: I need the messages you get. There should’ve been some.

A.

**Comment by boeckp** [comment]
Messages:
`2021-01-12 14:53:11.664 - warn: zigbee.0 (4170) publish from State - LinkedState is not a function {"id":"state","name":"Switch state","role":"switch","write":true,"read":true,"type":"boolean","inOptions":true}
2021-01-12 14:53:17.041 - warn: zigbee.0 (4170) publish from State - LinkedState is not a function {"id":"state","name":"Switch state","role":"switch","write":true,"read":true,"type":"boolean","inOptions":true}`

**Comment by asgothian** [comment]
Thank you for the message. I was now able to pinpoint the actual reason for the error, rather than just evading it with some sanity checks. A PR with the changes will go out on the weekend. We should keep this issue open until that PR is done.

A.

**Comment by asgothian** [comment]
Fixed in 1.4.3
