### ISSUE TITLE
Paulmann 929.63 supporter but doesn't work

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.zigbee#935]
Paulmann 929.63 don't work, but it's supported by Herdmanns-Converter and Zigbee Adapter.

Log: (1950) 0x00158d000448b30d (addr 51239): Not supported (model H036-0006)(Router)

<img width="358" alt="Bildschirmfoto 2021-01-13 um 17 10 23" src="https://user-images.githubusercontent.com/8231359/104478719-eb9ec780-55c2-11eb-8e28-a1bdb871c8fb.png">

**Comment by o0shojo0o** [comment]
The device does not report as Paulmann 929.63 but as H036-0006.
This is the definition in herdsman-converter:
~~~
  {
        zigbeeModel: ['500.46'],
        model: '929.63',
        vendor: 'Paulmann',
        description: 'SmartHome Zigbee LED-Modul Coin 1x6W Tunable White',
        extend: preset.light_onoff_brightness_colortemp,
    },
~~~

**Comment by Schmakus** [comment]
I tried to solved it by my self for testing. But I dont't know, which files I have to Edit (Herdmanns and Adaptor). Could you explain it, maybe?

**Comment by o0shojo0o** [comment]
Here for the herdsman https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
And in the adapter you need the [device.js](https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devices.js) and maybe the [states.js](https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/states.js) has to be adapted.

**Comment by asgothian** [comment]
> And in the adapter you need the [device.js](https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devices.js) and maybe the [states.js](https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/states.js) has to be adapted.
> 

An initial attempt should be made by only adding the device to the zigbee-herdsman-converters. As i see it, this is a standard light device, which should be fully covered by the exposes functionality. Please verify that a device does not work with exposes before adapting the devices in the zigbee adapter.

A.

**Comment by Schmakus** [comment]
I have put the device to Herdmanns and now it works!

**Comment by asgothian** [comment]
Great.  An you make a pull request against the zigbee-herdsman-converters so that
- you don’t lose the lamp with the next update
- Others can use the lamp too ?

A.

**Comment by Schmakus** [comment]
I don't know, if other users could use the lamp with the different model name too. 

And I don't know, how I can do a pull request. I have tried it, but I have less enough informations about it.

**Comment by asgothian** [comment]
Making a pull request is simple. You need
- a GitHub account (you got that)
- fork the koenkk/zigbee-herdsman-converters repository
- modify the files in your forked repository
- test the modification
- hit the 'make pull request' button 

Done, Dusted.
