### ISSUE TITLE
Please fix support of FreePad_LeTV_8 device

### ISSUE THREAD

**Issue by yivasyuk** [ioBroker/ioBroker.zigbee#940]
I am trying to add new FreePad_LeTV_8 zigbee device but getting error in conlsole.
And any states were created.
![image](https://user-images.githubusercontent.com/915073/105044581-91dd4800-5a6f-11eb-9c57-9d592df3f6f2.png)
![image](https://user-images.githubusercontent.com/915073/105044811-d4068980-5a6f-11eb-9bd8-37000d15f92e.png)

In devices tab I've got the following
![image](https://user-images.githubusercontent.com/915073/105045043-1b8d1580-5a70-11eb-89f0-a4598fddc9a0.png)

Some useful links:
[Link to zigbee2mqtt ](https://www.zigbee2mqtt.io/devices/FreePad_LeTV_8.html) device
[Link to device review](https://www.youtube.com/watch?v=8U4Cs51-tbM&t=229s)

**Comment by o0shojo0o** [comment]
Hi,
which version of ioBroker.zigbee adapter are you using?

**Comment by yivasyuk** [comment]
1.3.1

**Comment by o0shojo0o** [comment]
Please update the adapter via git to version 1.4.3, and try again.

**Comment by yivasyuk** [comment]
I am not sure what's the right way for updating adapter using git. I did the following
- cleared /node_modules/iobroker.zigbee folder
- run sudo git clone https://github.com/ioBroker/ioBroker.zigbee.git iobroker.zigbee
- cd iobroker.zigbee
- sudo npm i
and finally I am getting same error
Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/build'
Tried to provide all chmod -r a+rwx rights but it didn't help
So I just reverted all changes.
Could you point me to some instructions how to update adapter manually via git?

**Comment by o0shojo0o** [comment]
https://github.com/ioBroker/ioBroker.zigbee/wiki/GIT-install

**Comment by yivasyuk** [comment]
Thanks it helped but partly. Currently I am trying to catch some click event from the device but actually observing only change of link_quality state like in 
![screenshot](https://user-images.githubusercontent.com/915073/105242974-12d33700-5b77-11eb-87ee-c12825f15c6a.png)

**Comment by asgothian** [comment]
This definitely looks strange, as if the expose definition does not work properly.

Please do the following:

- set the adapter to debug
- enabled 'zigbee herdsman debug info' in the adapter settings
- delete the current iobroker log
- press buttons on your device. Please note down the order in which the buttons are pressed so received messages can be mapped to the buttons you pressed.
- download the log to your main system
- remove all lines which reference an adapter which is different from zigbee.0
- post the log.

A.

**Comment by asgothian** [comment]
@yivasyuk Please run the requested test. Fixing this issue requires access to the device, which the developers do not have.

A.
