### ISSUE TITLE
Support of several states analogous to Zigbee2MQTT

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.zigbee#941]
With Zigbee2MQTT, some devices indicate that a command for e.g. brightness_step (dimming) can be sent. Please discuss whether this would also be possible for the adapter.

Here the additional states from Zigbee2MQTT:
` {
  "brightness_move": -40, // Starts moving brightness down at 40 units per second
  "brightness_move": 0, // Stop moving brightness
  "brightness_step": 40 // Increases brightness by 40
  "color_temp_move": 60, // Starts moving color temperature up at 60 units per second
  "color_temp_move": "stop", // Stop moving color temperature
  "color_temp_step": 99, // Increase color temperature by 99
  }`

**Comment by asgothian** [comment]
Please describe in detail how you would like these to be implemented and what the use cases are. 

Please also link a few examples where their use is described in zigbee2mqtt.

**Comment by Schmakus** [comment]
> Please describe in detail how you would like these to be implemented and what the use cases are.

The state "brightness_step" or is perfekt do dim the lights without any calculations in javascript. Many users have switches with "long_press". So they can set a trigger to this Button and then setState(brightness_step, 10) for dimming in 10% steps.

> Please also link a few examples where their use is described in zigbee2mqtt.

[https://www.zigbee2mqtt.io/devices/929.63.html](url)
[https://www.zigbee2mqtt.io/devices/929002335001.html](url)

**Comment by asgothian** [comment]
This was implemented for most lights in 1.5.1
