### ISSUE TITLE
Please support LEDVANCE Classic E27 Multicolor

### ISSUE THREAD

**Issue by Garbracht** [ioBroker/ioBroker.zigbee#942]
I am running IoBroker on a Raspberry Pi 4 
I have installed Zigbee Adapter 1.4.0

The LEDVANCE Classic E27 Multicolor seems not be listed. Can you please add this device. 

I got the following Message:

Pairing time left: 43
Error: Device 0xf0d1b8000018a634 "A60 RGBW Value II" not described in statesMapping.. undefined
New device joined '0xf0d1b8000018a634' model A60 RGBW Value II
Interview successful: [object Object]
Pairing time left: 44
Device '0xf0d1b8000018a634' announced itself
Pairing time left: 55
Interview started: 0xf0d1b8000018a634
Pairing time left: 59
Pairing started 

Thank you in advance

**Comment by markus2701** [comment]
aktuell is 1.4.3

**Comment by Garbracht** [comment]
Thanks, great, it works. 

 

Is it possible to receive a notification when a new update is released?  IoBroker says that the latest version is 1.3.1 ???

 

Von: Markus Cords <notifications@github.com> 
Gesendet: Mittwoch, 20. Januar 2021 14:23
An: ioBroker/ioBroker.zigbee <ioBroker.zigbee@noreply.github.com>
Cc: Clemens Garbracht <clemens@garbracht.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.zigbee] Please support LEDVANCE Classic E27 Multicolor (#942)

 

aktuell is 1.4.3

**Comment by asgothian** [comment]
> aktuell is 1.4.3

This is the latest beta version. It may not be for everyone as it might have issues.



> Thanks, great, it works. 
> Is it possible to receive a notification when a new update is released? IoBroker says that the latest version is 1.3.1 ??? 

It is possible for you to subscribe to merges on the iobroker.zigbee repository. But it is not necessarily sensible.

Current version numbers are:

1.3.1 - stable release. This is the default version for everyone. it should be bug-free but might not have the latest features and might not support the newest devices.

1.4.2 - latest release - This is a version which has been vetted for bugs but may still have a few issues. It will support more devices and be closer to the current developer version

1.4.3 - current GitHub version. This is a developer version. It will contain the latest and greatest changes, but might contain changes which will be undone at a later date (before release into the latest channel)

You can change the repository for iobroker to latest. This will have the info adapter give you notifications about new versions. But this will affect all adapters, not just the zigbee adapter.

A.

p.s still closing this issue - it is already fixed.

**Comment by crazytegeler** [comment]
Hey guys!

My first post on github... so i hope i´m doing everything right. 

So as i see, the "A60 RGBW Value II" lightbulbs are supported. I just bought some "A60S RGBW" lightbulbs, which unfortunately dont´t work/ are not supported. Is there any way how i can quickly include them in my system? I guess it could be easy, because they should be similar to the A60 RGBW Value II ones. Otherwise i would send them back soon.

![grafik](https://user-images.githubusercontent.com/113830706/190897405-466ea84c-a5c1-4676-9c5a-08bda7cf1c24.png)

Hope you can help me - thank you in advance!
