### ISSUE TITLE
Müller Licht Filament 404037 not working (not described in statesmapping)

### ISSUE THREAD

**Issue by greyestapps** [ioBroker/ioBroker.zigbee#943]
The [filament bulb 404037 from Mueller Licht](https://www.mueller-licht.de/produktinformationen/artikel/404037/) is not working despite being added in devices.js

`{ zigbeeModel: ['tint-ColorTemperature'], model: '404037', vendor: 'M ller Licht', description: 'Tint retro filament LED-bulb E27, Edison bulb gold, white+ambiance (1800-6500K), dimmable, 5,5W', extend: generic.light_onoff_brightness_colortemp, toZigbee: generic.light_onoff_brightness_colortemp.toZigbee.concat([tz.tint_scene]), }`

iobroker gives me the error message _(6079) Device 0x00158d00013d5547 "404037" not described in statesMapping._

According to [zigbee-herdsman-converters project](https://github.com/Koenkk/zigbee-herdsman-converters/issues/2120) this is an iobroker issue.

**Comment by asgothian** [comment]
Please install the 1.4.2 from the Latest repository and restart.

A.

**Comment by greyestapps** [comment]
I'm running on 1.4.2. This is the exact log:


zigbee.0 | 2021-01-21 16:16:50.381 | error | (6079) Device 0x... "404037" not described in statesMapping.
-- | -- | -- | --
zigbee.0 | 2021-01-21 16:16:50.347 | info | (6079) Device '0x...' is supported, identified as: Müller  Licht Tint retro filament LED-bulb E27, Edison bulb gold, white+ambiance  (1800-6500K), dimmable, 5,5W (404037)
zigbee.0 | 2021-01-21 16:16:50.347 | info | (6079) Successfully interviewed '0x...', device has succesfully been paired

**Comment by asgothian** [comment]
This does bot add up. Please post the tile from the lamp aus the tile from the coordinator shown in the adapter device list.

A.

**Comment by greyestapps** [comment]
Not sure what you're referring to exactly but here is a screenshot from the device tile as well as the device information.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/39057837/105548219-a6377400-5cff-11eb-97ac-b43f48371940.png">

<img width="641" alt="image" src="https://user-images.githubusercontent.com/39057837/105548260-b8191700-5cff-11eb-97bb-914667e309a5.png">

**Comment by asgothian** [comment]
If you are running 1.4.2, there should be a tile for your coordinator:
<img width="306" alt="Screen Shot 2021-01-23 at 09 25 05 " src="https://user-images.githubusercontent.com/45667167/105573309-e37e1f00-5d5c-11eb-9dfd-a7af9c2f684c.png">

I assume that the version you are running is not 1.4.x, as
- the device 404037 is defined with exposes in the zigbee-herdsman-converters
- from 1.4.1 onwards, devices with exposes work 'out of the box'
Are you by chance running iobroker in Multihost and the zigbee adapter on the slave ?

A.

**Comment by greyestapps** [comment]
I'm running single host. Originally I've been running 1.3.1 but after your first message updated via npm to 1.4.2 (changed the version for iobroker.zigbee in package.json and ran `npm i` afterwards). I'm running iobroker 2.0.3 btw - might that be an issue?

<img width="356" alt="image" src="https://user-images.githubusercontent.com/39057837/105573648-61432a00-5d5f-11eb-81d6-8d3951cecb50.png">

Thanks for your patience A.

**Comment by asgothian** [comment]
Something is still very odd.. please check:
- the version of the zigbee-herdsman-converters you are running.  (see node_modules/zigbee-herdsman-converters/package.json or node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/package.json
Also - the tile you posted is not the one from your running adapter. Please check the 'devices' view for the tile i posted above. Does it exist ?

A.

**Comment by greyestapps** [comment]
Ok got it working now by updating zigbee-herdsman-converters from 14.0.3 to 14.0.30. Thanks a ton!
