### ISSUE TITLE
Pairing not working anymore

### ISSUE THREAD

**Issue by sirvancobra** [ioBroker/ioBroker.zigbee#945]
Hi,

I configured the zigbee adapter with a CC2531 USB Stick and added 6 devices (aquara/xiaomi) everything worked perfect.
Some days later I want to add more devices but pairing seem not working anymore.
No devices could be connected (no entry in Logs), some of them where the same device type as the working ones.
I decided to remove one of the connected and re-pair it, without success.
The already connected devices works, all states get changed, so I don't think the CC2531 should be the problem.
The devices still can be paired with my Aquara Hub. 

Restart system / adapter / usb, reinstall adapter, reset (soft / hard) do not helps.

Regards sirvancobra

------------------------------------------
Raspberry Pi4
Docker: buanet/iobroker:v5.1.0
Nodejs 12.20.1
js-controller 3.1.5
Zigbee 1.3.1

Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190619}}

**Comment by arteck** [comment]
adapter stop
put out the stick
put in back
and start the adapter

**Comment by sirvancobra** [comment]
> adapter stop
> put out the stick
> wait 3 sec
> put in back
> and start the adapter

Still didn't work. Is there maybe a bug with CC2531 firmware? A friend have the same setup but the previous firware version and it's work.

**Comment by allofmex** [comment]
Few additional suggests to try (also for others):

- keep stick detached longer than few seconds (>30sec). (Brownout issues??)
- open .../iobroker-data/zigbee_0/shepherd.db file and remove duplicated device lines (stop adapter first)
- power off some existing router devices to reduce load (on larger networks)
- be fast to start pairing after adapter start, on larger networks I usually can't pair anymore after network is up for more than few minutes.
- reflash cc2531 with same firmware (memory corruption, see https://github.com/Koenkk/Z-Stack-firmware/issues/263#issuecomment-780060237)

**Comment by sirvancobra** [comment]
> Few additional suggests to try (also for others):
> 
> * keep stick detached longer than few seconds (>30sec). (Brownout issues??)
> * open .../iobroker-data/zigbee_0/shepherd.db file and remove duplicated device lines (stop adapter first)
> * power off some existing router devices to reduce load (on larger networks)
> * be fast to start pairing after adapter start, on larger networks I usually can't pair anymore after network is up for more than few minutes.
> * reflash cc2531 with same firmware (memory corruption, see [Koenkk/Z-Stack-firmware#263 (comment)](https://github.com/Koenkk/Z-Stack-firmware/issues/263#issuecomment-780060237))

First suggestests does not helped. I will try the last one after purchasing the equipment

**Comment by sirvancobra** [comment]
> > Few additional suggests to try (also for others):
> > 
> > * keep stick detached longer than few seconds (>30sec). (Brownout issues??)
> > * open .../iobroker-data/zigbee_0/shepherd.db file and remove duplicated device lines (stop adapter first)
> > * power off some existing router devices to reduce load (on larger networks)
> > * be fast to start pairing after adapter start, on larger networks I usually can't pair anymore after network is up for more than few minutes.
> > * reflash cc2531 with same firmware (memory corruption, see [Koenkk/Z-Stack-firmware#263 (comment)](https://github.com/Koenkk/Z-Stack-firmware/issues/263#issuecomment-780060237))
> 
> First suggestests does not helped. I will try the last one after purchasing the equipment

It works. I flashed with firmware 20190523 yesterday and pairing is not problem anymore. Thank you for help.
