### ISSUE TITLE
Device 'xxx' announced itself / failed to ping

### ISSUE THREAD

**Issue by vaaarg** [ioBroker/ioBroker.zigbee#947]
type:zStack30x
version:2-2.2.7.2.
revision:20200211
port:/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
channel:15

pi4 4gb
js controller 3.2.8
zigbee 1.4.2
Node.js
v12.20.1
NPM
6.14.10

Product: eurotronic zigbee thermostate (new revision - gold package)

getting this warnings from several devices (eurotronic, xiaomi mi plugs, philips switch) after upgrading to zigbee 1.4.2

warnings occur while not in pairing mode

`
zigbee.0 | 2021-01-24 09:10:30.785 | warn | (1246) Device '0x00158d00053d3fdc' announced itself
-- | -- | -- | --

zigbee.0 | 2021-01-24 09:17:46.921 | warn | (1246) Failed to ping 0x00158d0003c473ce SPZB0001
-- | -- | -- | --

zigbee.0 | 2021-01-24 08:50:15.302 | warn | (1246) Failed to ping 0x00178801031179a4 LTW010
-- | -- | -- | --

`

**Comment by asgothian** [comment]
This was already discussed in Issue #923
