### ISSUE TITLE
Info messages about another not used Coordinator

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.zigbee#949]
Hello,

I noticed that when I using a Coordinator ConBee2 Info messages are issued that would actually only be relevant when using a CC253X Coordinator.
Neither LED on / off and  transmitPower are not relevant on the Conbee II, correct?

Even if it is currently invalid, maybe it can be fixed in a future release.

zigbee.0 | 2021-01-25 09:59:24.405 | info | (9279) Currently 26 devices are joined:
-- | -- | -- | --
zigbee.0 | 2021-01-25 09:59:24.395 | info | (9279) Unable to set transmit power, unsupported function.
zigbee.0 | 2021-01-25 09:59:24.393 | info | (9279)   --> transmitPower : normal
zigbee.0 | 2021-01-25 09:59:24.392 | info | (9279) Unable to disable LED, unsupported function.

![grafik](https://user-images.githubusercontent.com/26110738/105730250-6c988000-5f2e-11eb-8720-1f7d726188b8.png)

Thanks and Greetings
Fabian

**Comment by asgothian** [comment]
An interesting suggestion. Not sure how well / if we can identify in detail what function to attempt. 

A.

**Comment by asgothian** [comment]
After checking - there is no way to determine if the coordinator we are connected with is capable of supporting said functions. As such, the messages should remain as note that this was attempted.

A.
