### ISSUE TITLE
Gelöst: Zigbee ID: "TS0044" undefinied

### ISSUE THREAD

**Issue by He2205** [ioBroker/ioBroker.zigbee#950]
![image](https://user-images.githubusercontent.com/78033004/105863333-14768200-5ff1-11eb-844e-cf9fcb0d266c.png)
Model ESW-0ZAA-EU manufactured by Earda

Der 4Gang Schalter wird beim CC2531 als undefined erkannt.

It is undefined!!! :-(

**Comment by markus2701** [comment]
Welche Zigbee Version nutzt Du?

**Comment by He2205** [comment]
Wenn du die Version auf dem Stick meinst? dann ist es die koenkk 08.06.2019

**Comment by markus2701** [comment]
ne Adapter Version

**Comment by asgothian** [comment]
Please check [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised)

**Comment by He2205** [comment]
zigbee 1.3.1

**Comment by asgothian** [comment]
> zigbee 1.3.1

Please read [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised), and follow its advice.

A.

**Comment by He2205** [comment]
Damit komm ich nicht so wirklich klar.

**Comment by He2205** [comment]
![image](https://user-images.githubusercontent.com/78033004/106028264-05183700-60cc-11eb-8344-9faf76f79572.png)

Das sehe ich vom Taster wenn ich ihn anlerne.
Aber wie kann ich ihn jetzt definieren?
unter Entwicklung kann ich das eingeben aber es verändert nichts.

**Comment by asgothian** [comment]
- Hast du geprüft ob das Gerät bei zigbee2mqtt als unterstützt angegeben ist ? Wenn ja, mit welchem Ergebnis
- Hast du geprüft ob es eine neuere Version des Zigbee adapters gibt als die die du installiert hast ? Wenn ja, mit welchem Ergebnis
- Wenn es eine neuere Version gibt (sofern du immer noch auf 1.3.1 bist gibt es die) - hast du versucht diese zu installieren ?

A.

**Comment by He2205** [comment]
ZITAT:
- Hast du geprüft ob das Gerät bei zigbee2mqtt als unterstützt angegeben ist ? Wenn ja, mit welchem Ergebnis

  **Ja, hab ich geprüft. Der Schalter wird unterstützt. Aber was soll ich damit nun machen?**

ZITAT:
- Hast du geprüft ob es eine neuere Version des Zigbee adapters gibt als die die du installiert hast ? Wenn ja, mit welchem Ergebnis
Wenn es eine neuere Version gibt (sofern du immer noch auf 1.3.1 bist gibt es die) - hast du versucht diese zu installieren ?

 **Ich habe die letzte Version installiert.**

**Comment by asgothian** [comment]
Definiere "die letzte Version" ? 

Die neuste aus dem Stable kanal (das wäre 1.3.1)
Die neuste aus dem Lastest Kanal (das wäre 1.4.2)
Die aktuelle GitHub version (das wäre 1.4.3)

Du musst schon konkret sagen welche Version du meinst, sonst wird das mit dem helfen schwierig. Wir haben weder das Gerät, noch eine Glaskugel mit dem wir prüfen können was du tust.

Bei der 1.4.3 sollte der Schalter über Exposes bereits Datenpunkte erzeugen die auch schaltbar sind.

A.

**Comment by He2205** [comment]
Ok, ich schau mal ob ich den 1.4.3 Adapter installieren kann, denn ich hab aktuell den 1.3.1 Adapter aber der zeigt mir keine neuere Version an.

Ich versuchs mal manuell. :-)

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.zigbee/wiki/GIT-install

schon gesehen ?

**Comment by He2205** [comment]
so, jetzt hab ich den 1.4.3 adapter drin und jetzt erkennt der adapter den switch als ts0201 temp-sensor.
das gibts doch gar nicht.... 

hab den neuen adapter über den alten installiert....

**Comment by He2205** [comment]
so, nochmal alles gelöscht und den raspi neu gestartet.
Jetzt läufts. vielen Dank.

1.4.3 Adapter funktioniert.

**Comment by asgothian** [comment]
Fein.
