### ISSUE TITLE
GL-C-008P doesn't have white settings

### ISSUE THREAD

**Issue by M1cS0w** [ioBroker/ioBroker.zigbee#951]
Hello, this
![image](https://user-images.githubusercontent.com/51213428/105882823-6675d280-6006-11eb-870f-9604c4ad401e.png)
doesn't have the same settings like the other GL-C-007-2ID. Both controller can handle with only white LED.

Could it be added, that the states:
![image](https://user-images.githubusercontent.com/51213428/105883272-f4ea5400-6006-11eb-859b-22e6a4887a9c.png)

That would be awesome. And in the objects-tree there is a ? not the correct symbol / picture like in zigbee adapter.

Regards

**Comment by asgothian** [comment]
- Which adapter version are you running ?
- which states does the object have
- which states do you think should the object have ?

the issue with the image is due to the fact that the device is accessed through exposes (see wiki for details)

A.

**Comment by M1cS0w** [comment]
Hello,

thanks for ur fast answer and questions:

- I am using zigbee adapter version: 1.4.3
- the following are already there:
![image](https://user-images.githubusercontent.com/51213428/105906905-9338e280-6024-11eb-9d14-c048a76ad0df.png)

There should be like for the other controllers:
![image](https://user-images.githubusercontent.com/51213428/105906998-b5326500-6024-11eb-8ec3-46c7e5572d8e.png)

**Comment by M1cS0w** [comment]
> * Which adapter version are you running ?
> * which states does the object have
> * which states do you think should the object have ?
> 
> the issue with the image is due to the fact that the device is accessed through exposes (see wiki for details)
> 
> A.

Another question, so have i correctly understand, that the controller is not fully included like another devices? That this device will be integrated in zigbee in another update, and will be fully supported? Or did I understand exposes not correctly?

Because basically the controller can control the white leds of a led stripe, on the one hand u have the colors, yes there i could bring the white color too, but then the connection for led stripe with W will not used correctly or have I a mistake in my thought?

Regards

**Comment by asgothian** [comment]
This depends mostly on if the device functions properly.

If you use the colortemp dp to control the device, it should use the white LED;s and not the colored ones.

A.

**Comment by M1cS0w** [comment]
Hello,

thanks for the informations. But with colortemp, there is any change. Only using the Color, and State, and Brightness works, some of the effect like "blink" and "OK" works. The other not.

Would it be possible to implement this controller completely, like the others with white brightness and so on?

Regards
