### ISSUE TITLE
1.4.2 runs fine, but very rarely it crashes and restart. (I have already the fix from #927)

### ISSUE THREAD

**Issue by RudiXXL** [ioBroker/ioBroker.zigbee#952]
Hi,

today I was able to get the log from a restart of the ZigBee Adapter. It very rarely, so I was not able to fetch the Log... See attached. May be it is relatetd to the latest JS controller 3.2.11 (I'm not sure if the error was also before)

The 000d6ffffeb2cac3 in the log is the following device:
    modelZigbee:TRADFRI Driver 10W
    type:Router
    nwk:5892
    manuf id:4476
    manufacturer:IKEA of Sweden
    power:Mains (single phase)
    app version:17
    hard version:1
    zcl version:1
    stack version:87
    date code:20170529
    interviewed:true
    configured:false
[ICPSHC24-10EU-IL-1](https://www.zigbee2mqtt.io/devices/ICPSHC24-10EU-IL-1.html)
[Zigbee.txt](https://github.com/ioBroker/ioBroker.zigbee/files/5875685/Zigbee.txt)

br
:-) Rudi

**Comment by asgothian** [comment]
There is no crash of the adapter logged. The Adapter was terminated by the host. I cannot see any reason for this.

A.

**Comment by arteck** [comment]
i see also nothin ..close here
