### ISSUE TITLE
Lidl HG06467 change of effect-type

### ISSUE THREAD

**Issue by hytrek** [ioBroker/ioBroker.zigbee#954]
Hi there
glad you now support these device. Bit unfortunatly change of the "effect-type" results in:

host.ioBroker2-raspberrypi | 2021-01-26 18:47:27.794 | error | instance    system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --

zigbee.0 | 2021-01-26   18:47:26.578 | error | at processImmediate   (internal/timers.js:463:21)
-- | -- | -- | --
zigbee.0 | 2021-01-26   18:47:26.578 | error | at Immediate.   (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:238:38)
zigbee.0 | 2021-01-26   18:47:26.578 | error | at Zigbee.setState   (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
zigbee.0 | 2021-01-26   18:47:26.578 | error | at validateSetStateObjectArgument   (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
zigbee.0 | 2021-01-26   18:47:26.578 | error | (9652) Error: The state contains the forbidden   properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.577 | error | (9652) unhandled promise rejection: The state   contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.577 | error | (9652) Unhandled promise rejection. This error   originated either by throwing inside of an async function without a catch   block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-01-26   18:47:26.572 | error | (9652) The state contains the forbidden   properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.571 | error | at processImmediate   (internal/timers.js:463:21)
zigbee.0 | 2021-01-26   18:47:26.571 | error | at Immediate.   (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:238:38)
zigbee.0 | 2021-01-26   18:47:26.571 | error | at Zigbee.setState   (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
zigbee.0 | 2021-01-26   18:47:26.571 | error | at validateSetStateObjectArgument   (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
zigbee.0 | 2021-01-26 18:47:26.571 | error | (9652) Error: The state contains the forbidden   properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.570 | error | (9652) unhandled promise rejection: The state   contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.569 | error | (9652) Unhandled promise rejection. This error   originated either by throwing inside of an async function without a catch   block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-01-26   18:47:26.566 | error | (9652) The state contains the forbidden   properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.565 | error | at processImmediate (internal/timers.js:463:21)
zigbee.0 | 2021-01-26   18:47:26.565 | error | at Immediate.   (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:238:38)
zigbee.0 | 2021-01-26   18:47:26.565 | error | at Zigbee.setState   (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
zigbee.0 | 2021-01-26   18:47:26.565 | error | at validateSetStateObjectArgument   (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
zigbee.0 | 2021-01-26   18:47:26.565 | error | (9652) Error: The state contains the forbidden   properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.564 | error | (9652) unhandled promise rejection: The state   contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.563 | error | (9652) Unhandled promise rejection. This error   originated either by throwing inside of an async function without a catch   block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-01-26   18:47:26.558 | error | (9652) The state contains the forbidden   properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.557 | error | at processImmediate   (internal/timers.js:463:21)
zigbee.0 | 2021-01-26   18:47:26.557 | error | at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:238:38)
zigbee.0 | 2021-01-26   18:47:26.557 | error | at Zigbee.setState   (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
zigbee.0 | 2021-01-26   18:47:26.557 | error | at validateSetStateObjectArgument   (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
zigbee.0 | 2021-01-26   18:47:26.557 | error | (9652) Error: The state contains the forbidden   properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.550 | error | (9652) unhandled promise rejection: The state   contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26   18:47:26.549 | error | (9652) Unhandled promise rejection. This error   originated either by throwing inside of an async function without a catch   block, or by rejecting a promi

**Comment by asgothian** [comment]
Please post:
- which adapter version are you running ?
- which js controller version are you running >
- which nodeJS version are you running.
A.

**Comment by hytrek** [comment]
Hi Agothian
Thanks so much for looking into it. Herer are the requested infos's
Adapter 1.4.2
js Controller: 3.2.11
nodeJS: 12.20.1

**Comment by asgothian** [comment]
OK.. i can confirm the bug - it is connected to the update of the jscontroller to 3.2.x. It does not happen on 3.1.x.

I'll see if i can get it fixed, but it might take a few days.

A.

**Comment by hytrek** [comment]
Thank you so much. I am looking forward getting it fixed :-)
Have a great day... Please update the ticket once fixed so I get notified

**Comment by asgothian** [comment]
Thanks to some help from @arteck an @o0shojo0o, the fix i already in. If you install the latest version from GitHub the error should fix it.

Please test.

A.

**Comment by asgothian** [comment]
Followup - something is off.. more testing is needed.

**Comment by hytrek** [comment]
Hi there. I am not trying to push...I am just interested to know if there is any news :-)

**Comment by asgothian** [comment]
did you test latest GitHub version ?

A.

**Comment by hytrek** [comment]
Hi there
wow, that really was a fast reply... 
nope, havn't tested yet. to be honest I am a wimp with too little knowledge... if it fails I do not know how to return to a working solution ...

**Comment by asgothian** [comment]
that's easy.. 
install from GitHub. See if it dies. If it dies, install normally from the latest channel, an you are back.

The current GitHub version should no longer crash for you

A.

**Comment by hytrek** [comment]
And here it starts.... Don't know how. I have the cat icon in ioBroker and clicked on the cat, pasted the link: "https://github.com/asgothian/ioBroker.zigbee" and clicked "install"

And nothing happened... As I said... I have too little knowledge... MEA CULPA

**Comment by hytrek** [comment]
Sorry, GOT IT!! It runs smoothly! Many Thanks

**Comment by hytrek** [comment]
One more thing: If you change the settings on the devices controller, these values are not returned back to the zigbee controller...

**Comment by asgothian** [comment]
That is a limitation of the controller - it does not send updates when you change stuff on it.

A

**Comment by asgothian** [comment]
Confirmed fixed.
