### ISSUE TITLE
Please implement OSRAM Gardenspot W

### ISSUE THREAD

**Issue by chr-jordan** [ioBroker/ioBroker.zigbee#96]
Gardenspot W
8418260000d9dbac"
Tunable White Gardenspot
Tile:
"Gardenspot W

Gardenspot W
8418260000d9dbac"

Thx!

**Comment by arteck** [comment]
done

**Comment by kirovilya** [comment]
added in 0.8.0 version

**Comment by chr-jordan** [comment]
Sorry for late testing. Gardenspot is shown in objekt tree now, but shows no funktion when changing any values. Thx so far

Gardenspot W

Gardenspot W
8418260000d9dbac


![anmerkung 2018-12-25 220320](https://user-images.githubusercontent.com/44375264/50426567-3d1b7300-0891-11e9-9fbe-77df891459ac.jpg)
