### ISSUE TITLE
Xiaomi Mijia

### ISSUE THREAD

**Issue by david883** [ioBroker/ioBroker.zigbee#964]
Model: GZCGQ01LM
Zigbee Adapter 1.4.2 and 1.4.3
The Illuminance value does not appear under Objects.
![mijia](https://user-images.githubusercontent.com/28392840/106487482-fd350a00-64b2-11eb-9382-eecbb20ff6ac.png)

**Comment by asgothian** [comment]
Please run the adapter in debug an d try to catch messages from the device where it announces the illuminance value.

A.

**Comment by david883** [comment]
I stopped the Zigbee adapter and set the hook at Herdsman debug info. Adapter started.
![zig1](https://user-images.githubusercontent.com/28392840/106506102-80615a80-64c9-11eb-8945-61224f4ac45b.png)

zigbee.0	2021-02-01 19:46:50.384	info	(31129) Zigbee started
zigbee.0	2021-02-01 19:46:50.383	info	(31129) 0x842e14fffedb9335 (addr 42989): NAS-AB02B0 - Neo Temperature & humidity sensor and alarm (EndDevice)
zigbee.0	2021-02-01 19:46:50.382	info	(31129) 0x04cf8cdf3c7f0e6a (addr 56817): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
zigbee.0	2021-02-01 19:46:50.381	info	(31129) 0x842e14fffe52efb2 (addr 17648): HG06337 - Lidl Silvercrest smart plug (EU, CH, FR, BS) (Router)
zigbee.0	2021-02-01 19:46:50.380	info	(31129) 0xbc33acfffe86184a (addr 28756): E1525/E1745 - IKEA TRADFRI motion sensor (EndDevice)
zigbee.0	2021-02-01 19:46:50.373	info	(31129) 0x847127fffe92f9c1 (addr 25810): ZBMINI - SONOFF Zigbee two way smart switch (Router)
zigbee.0	2021-02-01 19:46:50.364	info	(31129) Currently 5 devices are joined:
zigbee.0	2021-02-01 19:46:50.354	info	(31129) --> transmitPower : normal
zigbee.0	2021-02-01 19:46:50.354	info	(31129) Unable to disable LED, unsupported function.
zigbee.0	2021-02-01 19:46:50.341	info	(31129) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20201026}}
zigbee.0	2021-02-01 19:46:48.071	info	(31129) Installed Version: https://github.com/ioBroker/ioBroker.zigbee/commit/master
zigbee.0	2021-02-01 19:46:47.948	info	(31129) Starting Zigbee npm ...
zigbee.0	2021-02-01 19:46:47.855	info	(31129) starting. Version 1.4.3 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.20.1, js-controller: 3.1.6
zigbee.0	2021-02-01 19:46:27.733	info	(1730) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.0	2021-02-01 19:46:27.733	info	(1730) terminating
zigbee.0	2021-02-01 19:46:27.279	info	(1730) Zigbee: disabling joining new devices.
zigbee.0	2021-02-01 19:46:27.278	info	(1730) cleaned everything up...
zigbee.0	2021-02-01 19:46:27.276	info	(1730) Got terminate signal TERMINATE_YOURSELF


After I emptied the log, no further messages appeared in the log. Even if I turn Zigbee devices on or off or walk past the motion detector. No messages in the log.

![zig2](https://user-images.githubusercontent.com/28392840/106506108-835c4b00-64c9-11eb-94ba-cfc3835496f0.png)


Is there another log? Or can I find the log somewhere else?

**Comment by JoachimEngelmann** [comment]
You need to set the log to "debug" in the Instances Tab

<img width="1256" alt="grafik" src="https://user-images.githubusercontent.com/32760573/106512519-02558180-64d2-11eb-9298-66ca8772bdcf.png">

**Comment by asgothian** [comment]
Please follow [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/Recording-device-messages) for recording device messages. Note that the zigbee-herdsman debug info should not be required at this stage.

A.

**Comment by david883** [comment]
Hello, thanks for the information. Thanks to you I was able to learn something new again. I tried again and deleted all Zigbee devices and the adapter. Version 1.4.3 installed and all devices re-paired. I don't know why but now everything works as it should. Thank you for the help and in general for your great work!
