### ISSUE TITLE
Lidl Silvercrest Power Button Status

### ISSUE THREAD

**Issue by david883** [ioBroker/ioBroker.zigbee#965]
Lidl Silvercrest HG06337

The device itself is working properly. Unfortunately, the status among the objects in the IOBroker is not changed when the On/Off button is pressed at the socket itself.

Zigbee Adapter 1.4.2 and 1.4.3

![hg0](https://user-images.githubusercontent.com/28392840/106487978-85b3aa80-64b3-11eb-91f2-1433e7951d73.png)

**Comment by JoachimEngelmann** [comment]
Could be related to https://github.com/ioBroker/ioBroker.zigbee/issues/961. I have the same problem with not updating states since Adapter Version 1.4.x where the exposes framework is used. You could check with Version 1.3.2 and compare the debug log output like in the mentioned ticket.

**Comment by asgothian** [comment]
@david883 Please attempt to record the messages sent by the device when its state is changed using the device button. Please refer to [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/Recording-device-messages) for instructions on how to obtain the desired messages.

As a second test, and to verify if it is related to issue #961, you could also perform the test for exposes mentioned there:

- install the current 1.4.3 Adapter version from GitHub
- use the "exclude" or "Ausnahmeliste" by adding said Busch Jäger Device to the list and restart the adapter.
- check the states for function.

Note that you may lose the device image when activating this function.

A.

**Comment by david883** [comment]
Hello, thanks for the information. Thanks to you I was able to learn something new again. I tried again and deleted all Zigbee devices and the adapter. Version 1.4.3 installed and all devices re-paired. I don't know why but now everything works as it should. Thank you for the help and in general for your great work!
