### ISSUE TITLE
Please add support for LIDL GU10 LED Light Bulb

### ISSUE THREAD

**Issue by syd1986** [ioBroker/ioBroker.zigbee#966]
Hi,
would be great to have the LIDL HG06106A added to the supported devices:
https://www.zigbee2mqtt.io/devices/HG06106A.html

Thanks!!!

**Comment by asgothian** [comment]
Have you verified if the device is supported in the latest GitHub version of the adapter ?

A.

**Comment by syd1986** [comment]
Sorry, updated adapter from Github and working now.
