### ISSUE TITLE
Netzwerkkarte als Datenpunkt verfügbar machen

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.zigbee#967]
Ich wollte eigentlich einen Pull Request auf machen, aber irgendwie bin ich zu doof dafür.

Mein Vorschlag wäre, ob man die Zigbee Netzwerk Karte, nicht ähnlich wie bei den Saugrobotern, als Datenpunkt ausgeben, damit man diese im VIS einbinden könnte.

**Comment by asgothian** [comment]
Please explain in detail:
- what do you want to achieve ?
- do you already have an idea how this can be done ?

As far as i understand it, the current network map does not have its own web address, so it is not that easily exposed. Additionally, triggering a reload on the map triggers the zigbee system to go through the map generation process again which can take quite some time and can generate some load on the zigbee system. As such, i am not sure if it is quite feasible to expose the network map.

A.

**Comment by JBSullivan** [comment]
Die Idee dahinter ist es eine Netzwerkkarte in das VIS einzubinden. 

Die Saugroboter Adapter für Roomba und Xiaomi nutzen CANVAS für die Darstellung der erzeugen Reinigungskarte. Das sieht dann so aus. Diese ist allerdings dynamisch.

![image](https://user-images.githubusercontent.com/44617472/106783701-da8a2900-664b-11eb-856d-e41df5221c1f.png)

Die Idee für die Zigbee Karte beruht NICHT auf einer dynamischen Einbindung, sondern auf der Möglichkeit, sich via VIS einen Snapshot des aktuellen Zigbee Netzwerk  in ein img-Widget zu laden.

Also bei Anforderung wird im Hintergrund (wie auch immer) ein Snapshot generiert und als png Bild in einem ioBroker Verzeichnis abgelegt. Über eine entsprechende img Verknüpfung aktualisiert sich dann dieses Bild. 

Das ist meiner Meinung nach ein deutlicher schnellerer Weg, als ich über den Admin bis in die Zigbee Instanz zu klicken um die Netzwerk Karte zu sehen.  So könnte man die Karte auch Remote sehen, ohne eine ioB Lizenz für den Pro Cloud Zugang zu besitzen. 

Könnte z.B. so aussehen.

![image](https://user-images.githubusercontent.com/44617472/106785277-84b68080-664d-11eb-8fd6-8e0855fdc771.png)

**Comment by Sacred-Shadow** [comment]
Would be kind of cool.

**Comment by MrDrache333** [comment]
Ich hätte auch großes Interesse an solch einem Feature. Ich nutze auch die Möglichkeit die Karte meines Roombas anzuzeigen und dazu dann auch in der Lage zu sein, sich das ZigBee Netzwerk grafisch anzeigen zu lassen, ohne jedesmal in dem Adapter so lange zu warten wäre schon sehr cool.
