### ISSUE TITLE
Neues Gerät: SilverCrest Bewegungssensor

### ISSUE THREAD

**Issue by Scarbous** [ioBroker/ioBroker.zigbee#968]
Ich habe mir "SilverCrest Bewegungssensor" gekauft und würde diese gerne in ioBroker einbinden.
Das gerät wird derzeit nicht erkannt.
Nun meine Frage liegt es an der zigbee Integration?

**Geräteinformation**
model:TY0202
type:EndDevice
nwk:45207
manuf id:4619
manufacturer:_TZ1800_fcdjzz3s
power:Battery
app version:65
hard version:1
zcl version:1
stack version:2
date code:2019.12.12
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genPowerCfg (1)
genIdentify (3)
ssIasZone (1280)
haDiagnostic (2821)
output clusters:genOta (25)

**Comment by o0shojo0o** [comment]
Take a look at this: https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised

**Comment by raspilaurent** [comment]
Works for me with zigbee adapter version 1.43 from GitHub.

**Comment by Scarbous** [comment]
Thank you @raspilaurent I installed the GitHub Version now it Works fine.
