### ISSUE TITLE
Battery state of an aquara sensor missing

### ISSUE THREAD

**Issue by endurance0** [ioBroker/ioBroker.zigbee#969]
Hello

I started to test the Zigbee Adapter with a Conbee 2 Stick for my installation, and I got no battery and voltage state:

![image](https://user-images.githubusercontent.com/64706238/106881286-9a738680-66dd-11eb-97c6-7a99874ea2ef.png)

Adapter 1.3.1

**Comment by raspilaurent** [comment]
Takes some time, till you get a battery value (maybe 24 hours).if not, maybe you have to update the adapter (-> version 1.43).

**Comment by endurance0** [comment]
ok, I just updated to 1.4.3, nothing changed, 20min later I got the state, thx
