### ISSUE TITLE
Better handle timing for "parallel" requests

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.zigbee#97]
I have several light bulbs that always are controlled together (because located in one physical "lamp"). Very often one of the lamps do not receive all the data and brightness is different or do not turn on or such.
How the adapter is handling "parallel state cganges"? Is there a needed "delay" between the commands the usb zigbee stick can handle or such? Is the adapter handling this atomatically? If not, he should :-) If he already tries to then the timing does not always work ...

Any informationon this?

**Comment by kirovilya** [comment]
I heard about this problem, but because I do not have a lot of lamps, I did not watch it.
The adapter simply sends commands in the order in which they arrive (states change).

I'll think about how to make a queue of commands with the delays between them.

**Comment by Apollon77** [comment]
I think this is the idea. The only question is what the best length of delays is. How the MQTT project is handling this? Maybe worth a look.

**Comment by Apollon77** [comment]
Just found: https://github.com/Koenkk/zigbee2mqtt/issues/529 sounds comparable

**Comment by kirovilya** [comment]
@Apollon77 Can you check out last update with your lamps?

**Comment by Apollon77** [comment]
will try, but I'm currently on arteck fork because of LCT024 (new Hue Play Bars ...) and a manually patched sheppard-converters :-) Will try to puzzle it together tomorrow

**Comment by Apollon77** [comment]
BTW: Did you tried with shepperd-converters 5.0.0 ...last try on arteck fork nothing worked anymore with 5.0.0 of them

**Comment by arteck** [comment]
ilya fix it..

**Comment by Apollon77** [comment]
So you can make the PR for the new devices again?

**Comment by arteck** [comment]
yes..wait for yours OK

**Comment by kirovilya** [comment]
:( ok... I will try to change...

**Comment by kirovilya** [comment]
Try using this code:
https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/zigbeecontroller.js#L350
```
        // Add job to queue
        this.queue.push((queueCallback) => {
            const callback_ = (error, resp) => {
                if (error) {
                    this.error(
                        `Zigbee publish to '${deviceID}', ${cid} - ${cmd} - ${JSON.stringify(zclData)} - ${ep} ` +
                        `failed with error ${error}`);
                }
                if (callback) callback(error, resp);
            };
            if (type === 'functional') {
                device.functional(cid, cmd, zclData, callback_);
            } else if (type === 'foundation') {
                device.foundation(cid, cmd, zclData, callback_);
            } else {
                this.error(`Unknown zigbee publish type ${type}`);
            }
            setTimeout(()=>{queueCallback}, 200);
        });
    }
```

**Comment by Apollon77** [comment]
pppuuuhhhh ... I experimented a bit and this and this queueing is very slow as implemented originally and becomes very very strange and unreliable as soon as I started calling the queue callback "earlier" (using a timeout instead of in the done callback.

:-(

**Comment by Apollon77** [comment]
for your code exmaple ... I also tried that ... with 100ms it stays veeery slow (feels like 1s between actions are visible, really maybe 1/2s) ... and whyn I lower things become very strange :-(

**Comment by kirovilya** [comment]
try this.queue.timeout = 1;

Or may be it is my mistake with 2 timeouts: https://github.com/ioBroker/ioBroker.zigbee/blob/master/main.js#L594
but there should be 0 as default.

**Comment by arteck** [comment]
i'm not allone with this

**Comment by arteck** [comment]
// wait a timeout for write
 ```
       setTimeout(()=>{
            zbControl.publish(deviceId, message.cid, message.cmd, message.zclData, ep, message.cmdType);
        }, readTimeout || 0);


            // wait a timeout for read
            adapter.log.debug(`Read timeout for cmd '${message.cmd}' is ${readTimeout}`);
            setTimeout(()=>{
                const readMessage = converter.convert(preparedValue, preparedOptions, 'get');
                if (readMessage) {
                    adapter.log.debug('read message: '+safeJsonStringify(readMessage));
                    zbControl.publish(deviceId, readMessage.cid, readMessage.cmd, readMessage.zclData, ep, readMessage.cmdType);
                }
           
}, changedState.timeout);
```

why not

**Comment by kirovilya** [comment]
@arteck it is work for you?
that not correct.
first zbControl.publish - is send command, so no need timeout for this.
second zbControl.publish - is read command for getting current value for state.

timeouts I use for waiting transition time, but in default case it is = 0

**Comment by kirovilya** [comment]
@Apollon77 @arteck Try to comment out the use of the queue, will it work better or not?

**Comment by Apollon77** [comment]
> @Apollon77 @arteck Try to comment out the use of the queue, will it work better or not?
Did that already yesterday ... timing is "as before" ... I did not noticed other missing actions till bow, but also before it only happened sometimes

**Comment by kirovilya** [comment]
@Apollon77 @arteck Sorry, I do not undestand... Problem not with Queue? With somthing else?
Can you provide video example to feel timing?

**Comment by Apollon77** [comment]
Ok, which code I should use to send example of timing and effects? (Currently i removed the queue again because works more reliable without :-(

**Comment by kirovilya** [comment]
@Apollon77 want see work with queue and without it

**Comment by Apollon77** [comment]
will try to do tonight. so original code for queue as on github?

**Comment by Apollon77** [comment]
Will not make it tonight, need to fix Alexa2 somehow (Amazon changed things ... gggrrr). Tomorrow. Sorry

**Comment by arteck** [comment]
check now

**Comment by Apollon77** [comment]
Which code version would be Test candidate?!

**Comment by kirovilya** [comment]
@Apollon77 latest

**Comment by Apollon77** [comment]
Official repo works, so here the videos.

1.)  with queue as in repo ... as you can see (better visible when lamps go off, delay is comparable to on) ... 1/2-1s roughly
--> https://www.dropbox.com/s/lllhop53qchgvv6/IMG_6631.mov?dl=0

2.) without queue ( i just removed the "queue push" logic in code ... the dalay is waaaay slower ...
--> https://www.dropbox.com/s/wl535z605m1327g/IMG_6632.mov?dl=0

**Comment by arteck** [comment]
here also better.. but perfect..

**Comment by kirovilya** [comment]
@Apollon77 hmm... let's try to disable some of the innovations.
Comment next line:
https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/zigbeecontroller.js#L45
Change lines:
https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devstates.js#L624
to:
`return {transition: 0};`
and line:
https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devstates.js#L629
to:
`return 0;`

and then check out

**Comment by Apollon77** [comment]
Will do tonight. Thank you!

**Comment by arteck** [comment]
hmm have a problem

```
Time left: 3
Error: Cannot get the Node Descriptor of the Device: 0x84182600000e4d12 (Error: Timed out after 10000 ms). undefined
Time left: 4
```

**Comment by arteck** [comment]
update to version 0102511 did not help either. .hmm very strange

**Comment by Apollon77** [comment]
Ok, tried it ...

1.) Without queue logic but your changes: interestingly enough turning on still have the same delays as before ... turning off happens nearly at the same time.

https://www.dropbox.com/s/eychmfrz5vx7srd/IMG_6634.mov?dl=0

But I also had some timout error in the log as I did that video and the third time after switchin g all lamps off two of them just turned on afterwards without any reall command from me ... :

```
2018-11-19 23:42:30.250  - error: zigbee.0 Zigbee publish to '0x0017880102b58fc2', genLevelCtrl - moveToLevelWithOnOff - {"level":127,"transtime":0} - 11 failed with error Error: Timed out after 30000 ms
2018-11-19 23:43:11.376  - error: zigbee.0 Zigbee publish to '0x0017880102b58fc2', genOnOff - read - [{"attrId":0}] - 11 failed with error Error: Timed out after 30000 ms
2018-11-19 23:43:26.375  - error: zigbee.0 Zigbee publish to '0x0017880102a35cc5', genOnOff - on - {} - 11 failed with error Error: Timed out after 30000 ms
2018-11-19 23:43:26.435  - error: zigbee.0 Zigbee publish to '0x0017880102b58fc2', genLevelCtrl - moveToLevelWithOnOff - {"level":127,"transtime":0} - 11 failed with error Error: Timed out after 30000 ms
2018-11-19 23:43:26.449  - error: zigbee.0 Zigbee publish to '0x0017880102a35cc5', genLevelCtrl - read - [{"attrId":0}] - 11 failed with error Error: Timed out after 30000 ms
2018-11-19 23:43:26.587  - error: zigbee.0 Zigbee publish to '0x00178801041d4ca0', genLevelCtrl - moveToLevelWithOnOff - {"level":127,"transtime":0} - 11 failed with error Error: Timed out after 30000 ms
2018-11-19 23:43:26.620  - error: zigbee.0 Zigbee publish to '0x00178801041d4ca0', genLevelCtrl - read - [{"attrId":0}] - 11 failed with error Error: Timed out after 30000 ms

```


2.) With enabled queue and your changes ... as slow as before for on and off (feels slower):

https://www.dropbox.com/s/po6aop8ocx0hvly/IMG_6637.mov?dl=0

**Comment by kirovilya** [comment]
@Apollon77  One question: how do you turn the lamps on and off? Do you set the brightness to 50 and decrease to 0? Or switch the state on and off? I think you change the brightness

The problem is that when switching brightness I have to send 2 requests: change of brightness and at the end - change of state (to turn it off or on). This is necessary for some lamps that, when setting brightness to 0, do not turn off by themselves - they need to send a command forcibly.

If I remove the queue, it means that there will be more errors that you sent - request timeouts.

I'm sad. I do not know how to do better.

**Comment by Apollon77** [comment]
In the video yesterday I use my wall switch that will set brightness when turning on and state when turning off. 

In the Videos yesterday I only controlled the state.  I can try tonight How this behaves with your changes from above. 

Is there no was to send multiple changes in one command?

**Comment by arteck** [comment]
you send now one write request (switch on/off) and then you send direct the read request, right ??
what is when you send only write requests and after send last request you send reads..

**Comment by kirovilya** [comment]
@arteck yes, I send write and read request. 
Reading is necessary to get the current state from device. Previously, it was ignored.
But after the transition_time appears, the states may change during the change process and at the end it is necessary to read the final state.

**Comment by arteck** [comment]
i switch the queue also to off... the lag is very very long..

**Comment by kirovilya** [comment]
@arteck Deleting the queue does not help? Is this with the latest changes https://github.com/ioBroker/ioBroker.zigbee/commit/3b70be8bf941eae200c8ae121caccb99fcca5769 ?

**Comment by arteck** [comment]
what is with https://github.com/ioBroker/ioBroker.zigbee/issues/97#issuecomment-439781414

**Comment by arteck** [comment]
any possibilities/options ??

**Comment by kirovilya** [comment]
I do not know what else can be done now ... I propose to be released.
In the next version I plan to make support zigbee groups - this will allow you to send one message to a group of devices, and they will receive it all at once.

**Comment by Apollon77** [comment]
This sounds resonable ... only question is: release or remove the queue ... groups are the better solution, so I would say "remove queue again" and add groups in next version :-)

**Comment by kirovilya** [comment]
By your reviews - removing the queue does not greatly affect the processing speed. Therefore, I suggest to leave.

**Comment by Apollon77** [comment]
My feeling was still that it is slower ... so I have disabled the queue in my prod system, but ok as you think

**Comment by arteck** [comment]
i build a prototype with on/off queue.. in my repo noqueue brunch

not tested... in settings is a checkbox for on/off queue

**Comment by arteck** [comment]
on/off queue in Admin is done.. merge PR Ilya plz

**Comment by modmax** [comment]
See if light on/off works better without write events (linkedStates); #141.
Instead sending a write for turning on/off lamp a read event is used which works faster in my opinion and investigations with OSRAM lights.

But I think that the bottleneck is the Zigbee stick itself; cause it's just a serial connection ... and so on. Just my assumption.

**Comment by kirovilya** [comment]
let's try groups https://www.youtube.com/watch?v=Jdioavy2ppQ
https://github.com/ioBroker/ioBroker.zigbee/tarball/groups
but I really care about this version - it is not clear how to update the values of the states of the lamps in the group, although they themselves should have sent them.
