### ISSUE TITLE
Zigbee Gruppen funktionieren nicht korrekt.

### ISSUE THREAD

**Issue by He2205** [ioBroker/ioBroker.zigbee#970]
installierter Adapter: 1.4.3

Wenn ich nur eine Gruppe anlege, dann kann ich den Status Switch auch ändern und die Gruppe (2x Gu10 Tradfri) geht dann auch real auf true oder false.

Sobald ich eine 2te Gruppe anlege mit anderen Lampen, kann ich zwar den Status ändern aber die Lampen schalten real nicht.
Einzeln schalten funktioniert aber. und die vorher ersstelle Gruppe funktioniert dann auch nicht mehr.

Dimmer.Level wurde vorher in der Gruppe auf 100 gesetzt.
Geschaltet sollen GU10 Tradfri nur mit Dimmen ohne Colortemp.

Woran könnte das ev. liegen?

**Comment by asgothian** [comment]
I cannot confirm this behavior

I can generate multiple groups, and can switch these groups by using the state.

Please test again, and provide a detailed report of the steps taken to reproduce this error.

A.

**Comment by schniddsel** [comment]
Can confirm @He2205 's report.

Version 1.4.3:
Having 3 Groups with two or mor bilbs in each one of them.

Changing state to true/false works for each bulb seperately, but not when i want to controll them in a group.

What else do you need two reproduce? Some log in a specific time?

**Comment by Maddin3011** [comment]
I can confirm He2205 report as well.

**Comment by asgothian** [comment]
In order to get some traction to this, please do the following:

- update to the current latest version (1.4.4)
- post the hardware used for the test (which coordinator, which bulbs)
- post the exact sequence of tests which lead to the group not being able to be controlled.

Note that 
- the group will only react together when controlled from the group_x state. Controlling a single group member will not affect the group in any way
- as of now, the group members will not automatically update their status when the group is controlled. A solution for this is being worked on, but this is not as simple as it seems.

I currently do not have this issue. I can create any number of groups with the light devices i have (Ikea LED1649C5, Ikea LED1623G12, Ikea ICPSHC24-10EU-IL-1, HGZB-02A, Philips 9290012573A, Philips 433714, Coordinator is TI LaunchXL CC26X2R1) 

A.

**Comment by Maddin3011** [comment]
Since a I had a ioBroker crash and have reinstalled ioBroker, I do not have this issue anymore.

**Comment by asgothian** [comment]
I did a full rewrite of the group functions. Please install the current test branch from
https://github.com/asgothian/ioBroker.zigbee/tarball/Groups to check if the error persists.

A.

**Comment by tliesen** [comment]
Hallo,
bei mir funktionieren die Gruppen auch nicht mehr. Ich habe gestern eine neue Gruppe angelegt. Danach konnte ich bei den alten Gruppen nicht mehr alle Lampen schalten. Ich habe 6 Lampen in der Gruppe Wohnzimmer. Nach dem Anlegen einer neuen Gruppe werden in der Gruppe Wohnzimmer nur noch 3 Lampen geschaltet. 
Ich habe schon versucht eine Sicherung von vor 2 Tagen einzuspielen und habe auch die Version 1.4.5 installiert. Jedoch ohne Erfolg

**Comment by asgothian** [comment]
@tliesen:
- Log Dateien ?
- Welche 1.4.5 hast du installiert ?
- Log Dateien nach der Installation von 1.4.5, insbesondere nachdem Du damit die Gruppen neu erstellt hast ?
- gibt es Abstürze des Adapters ?

Die Aussage "das ist bei mir auch so" ist relativ wertlos. Ohne weitere Informationen lässt sich daraus absolut **nichts** ableiten.

Ansonsten: Unter dem oben angegebenen Link liegt eine weitere Testversion mit weiteren Anpassungen:
- Entfall von unnötigen Warnmeldungen beim Erstellen/Löschen/Modifizieren der Gruppen
- Synchronisationsversuch der Device-States mit dem Gruppen-State wenn von der Gruppe aus geschaltet wird.
- Versionsnummer 1.4.6 (um sicher zu gehen das ich sehe ob das meine ist)

Bitte testen.

A.

**Comment by tliesen** [comment]
@asgothian 

Ich hatte bis gestern 1.4.4 installiert. Als der Fehler aufgetreten ist, habe ich die Lampen aus den Gruppen entfernt und wieder hinzugefügt. Ohne Erfolg. Danach habe ich über Githup 1.4.5 installiert. Hat aber auch nichts gebracht.
Ich habe jetzt 1.4.6 installiert und die Lampen aus den Gruppen entfernt und wieder hinzugefügt. Jetzt gehen alle Lampen aus einer Gruppe wieder an und aus, so wie es sein soll. Mit 1.4.6 geht es wieder. Ich habe vorher noch auf Debug gestellt.
Mir sind keine Abstürze des Adaper aufgefallen

**Comment by asgothian** [comment]
Fixed in 1.4.6, closing
