### ISSUE TITLE
HUE Leuchtmittel model:9290012573A Bild wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by dp20eic** [ioBroker/ioBroker.zigbee#971]
Hi,

ich habe einmal auf die 1.4.3 migriert, dabei ist mir aufgefallen, das bei meinen drei Leuchtmittel HUE model:9290012573A die Bilder nicht mehr angezeigt werden. Ein Upload habe ich gemacht, ohne Erfolg. Der interne Link zur Seite von "zigbee2mqtt" passt "https://www.zigbee2mqtt.io/devices/9290012573A.html"

Bild 1: Beispiel Geräteübersicht
![image](https://user-images.githubusercontent.com/71387331/107043913-e7ca2380-67c3-11eb-90f0-5af04dd2f095.png)

Bild 2: Beispiel Geräteinfo
![image](https://user-images.githubusercontent.com/71387331/107044066-1d6f0c80-67c4-11eb-81c0-8bb8c23a91e5.png)

Bild 3: Netzwerkübersicht (OG_Treppe)
![image](https://user-images.githubusercontent.com/71387331/107044173-3b3c7180-67c4-11eb-8f1d-db7c2b07c577.png)

### Zusätzliche Infos:
Platform: linux
os: linux
Architecture: x64
CPUs: 4
Speed: 3200 MHz
Model: AMD Phenom(tm) II X4 955 Processor
RAM: 4 GB 
System uptime: 23 T. 01:57:26
Node.js: v12.20.1
NPM: 6.14.10
Disk size: 12.0 GiB
Disk free: 6.9 GiB
adapters count: 385
Uptime: 3 T. 11:50:34
Active instances: 30

Zigbee:
Verfügbare Version:1.4.2
Installierte Version:1.4.3
Installierte Instanzen:1

**Comment by Sacred-Shadow** [comment]
Stimmt denn das Bild hier?
https://github.com/ioBroker/ioBroker.zigbee/blob/master/admin/img/philips_hue_color.png

**Comment by Sacred-Shadow** [comment]
Da hat sich ein _ zuviel eingeschlichen. 
Hab mal nen Fix gemacht. :)

**Comment by dp20eic** [comment]
zum Bild, ja das ist das korrekte.
zum Patch der funktioniert auch.

Danke.
