### ISSUE TITLE
Sonoff Temperature und Luftfeuchtigkeit - Sensor aktualisiert keine Werte 

### ISSUE THREAD

**Issue by jeffconrad18** [ioBroker/ioBroker.zigbee#973]
Hallo zigbee-Adapter-Community,
ich habe, um meine neuen Blitzwolf Bw-SHP13 - Steckdosen einzubinden, den zigbee-Adapter von Version 1.3.1 auf 1.4.1 geupdatet, leider kann ich nun meine Sonoff Temperature und Luftfeuchtigkeit - Sensoren nicht mehr einbinden bzw. wenn es och funktioniert aktualisieren sich ihre Werte nicht.
Was kann ich machen?

(Systeminformationen:
Node.js
v12.20.1
NPM
v6.14.10)

**Comment by Sacred-Shadow** [comment]
Welchen Sonoff? Model?

**Comment by jeffconrad18** [comment]
> Welchen Sonoff? Model?

Der ganze normale Temperature und Luftfeuchtigkeit - Sensor SNZB-02 (https://www.zigbee2mqtt.io/devices/SNZB-02.html)!

**Comment by asgothian** [comment]
Please follow [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/Recording-device-messages) to verify if it is an issue between the sensor and the zigbee library or an issue between the zigbee library and the zigbee adapter.

A.
