### ISSUE TITLE
Einige Aqara/Xiaomi Clients fehlen mit v.1.4.3

### ISSUE THREAD

**Issue by rainbowcat1989** [ioBroker/ioBroker.zigbee#975]
Hallo,

nach dem Update auf die neueste Version , ist mir aufgefallen das der Aqara Cube sowie der Vibrationssensor nicht eingelernt werden kann. 

Da bei mir 23 Geräte von mir eingelernt werden konnte (verschiedener Hersteller) , gehe ich davon aus das hier evtl. ein Bug vorliegt.

getestet habe ich 2 Aqara Cubes und ein Xiaomi Vibrationssensor

Pairing-Vorgang wurde mehrfach durchgeführt um auf Nummer sicher zu gehen.

In diesem Fall der Vibrationssensor.

![image](https://user-images.githubusercontent.com/64091338/107158127-43450e80-6988-11eb-871a-8da04a6d046f.png)

zigbee.0 | 2021-02-07 20:05:31.675 | error | (20012) Failed to interview '0x00158d0002b23c89', device has not succesfully been paired. undefined
-- | -- | -- | --

Ich verwende einen CC2538+CC2592

zigbee.0 | 2021-02-07 20:02:51.772 | info | (20012) Coordinator firmware version: {"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200327}}
-- | -- | -- | --

Grüße

Marcus

**Comment by asgothian** [comment]
I have no issue pairing an aquara cube, but i am using a ti Launchxl as coordinator. 
- Did you have the sensor / cube connected with the cc2538 with an earlier software version ?
- Do you have any chance to obtain the model ID of the vibration sensor and the Cube ?
- did you try to keep the devices "alive" by repeatedly pressing the pairing button approx. every 2 seconds (just short presses) during pairing ?
A.

**Comment by rainbowcat1989** [comment]
Hi, 

- i tried to pair the devices with my second iobroker and a cc2531. I know for sure that i had successfully paired this devices to this stick before.


- **But your Hint with repeatedly pressing the pairing button worked** .
