### ISSUE TITLE
Warnung vor Raspberry USB-Boot im README.md

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.zigbee#976]
Ich habe bei einem Kumpel einen Raspberry mit USB-Boot eingerichtet (inkl. Docker). Der Erste Zigbee Stick (cc2531) wollte garnicht. Der Zweite (Conbee2) machte auch garnichts. Der Dritte Stick (cc2531) lief im ersten Moment OK, aber hatte nach rund 2 Wochen teilweise komplett aussetzer oder das schalten dauerte 10 bis 30 Sekunden.

Daraufhin einen cc26x2r gekauft weil ich dachte der cc2531 läuft am Limit (rund 30 Geräte davon aber 15 Router).

Dieser cc26x2r startete auch nur bei 3 von 4 Adapter-Starts und koppeln war fast unmöglich, genauso wie Befehle senden.

Erst nach vielen Stunden Fehlersuche bin ich darauf gekommen, dass es am USB-Boot (mit USB 3.0) liegt.

Problem wurde hier schon behandelt: 
https://forum.iobroker.net/topic/33072/pi-4-auf-ssd

Es wäre schön wenn eine Warnung auf der README wäre. Damit anderen diese Probleme erspart bleiben. Und ich gehe davon aus, dass der Raspberry die häufigste Hardware ist und eine SSD besser als microsd ist.

**Comment by Sacred-Shadow** [comment]
Sry aber daraus lässt sich nichts schließen, dass man vor USB Boot warnen müsste?!? 
Mal abgesehen davon, dass mein PI auch von ner USB 3.0 Platte läuft.
