### ISSUE TITLE
Do I need to pair to repeater?

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#978]
Hi, one thing that has always been unclear to me: Is it ok to pair all devices to the coordinator .. and let the mesh do the rest .. or should you pair with the nearest repeater?

**Comment by asgothian** [comment]
It does not matter where you pair. The communication always goes to the coordinator.

A.

**Comment by daniel-lo** [comment]
@asgothian

Thank you .. what irritates me though is that the devices that I pair with the coordinator stick to the coordinator even though repeater sockets are much closer. All devices paired today via coordinator:

![mesh](https://user-images.githubusercontent.com/4311558/107437119-cc964580-6b2e-11eb-9be2-b5de8dd6e79d.png)

**Comment by daniel-lo** [comment]
Nothing has changed in the mean time .. objects are still all attached to the Coordinator.
I believe I must add that I use Conbee II with this adapter.
