### ISSUE TITLE
Please add support for Innr RS 128 T (already in zigbee2mqtt)

### ISSUE THREAD

**Issue by steffiland** [ioBroker/ioBroker.zigbee#98]
Hi, could you please add support for the Innr RS 128 T, which is already supported by zigbee2mqtt?

After many on and off switches for the lamp, I could finally add it to the zigbee adapter, but it does not create an object for it.

The Log says:

zigbee.0 | 2018-11-12 21:44:27.894 | info | Zigbee: allowing new devices to join.
-- | -- | -- | --
zigbee.0 | 2018-11-12 21:44:13.996 | info | new dev 0x00158d0001cbbfc8 11729 RS 128 T
zigbee.0 | 2018-11-12 21:44:12.974 | info | List of ports: [{"comName":"/dev/ttyAMA0"},{"comName":"/dev/ttyUSB0"}]
admin.0 | 2018-11-12 21:44:12.403 | info | successful connection to socket.io from ::ffff:176.10.54.159

I can see the lamp in the adapter instance...:
![image](https://user-images.githubusercontent.com/2899791/48374810-3a403680-e6c6-11e8-831b-4388944edbd8.png)

but not in the objects:
![image](https://user-images.githubusercontent.com/2899791/48374765-1ed52b80-e6c6-11e8-9df7-0ece6f591370.png)

Thanks!

**Comment by steffiland** [comment]
Ok, i just restarted the adapter, now the log says:

zigbee.0 | 2018-11-12 22:05:43.541 | info | (0x00158d0001cbbfc8): RS 128 T - Innr GU10 Spot 350 lm, dimmable, white spectrum (Router)
-- | -- | -- | --
zigbee.0 | 2018-11-12 22:05:43.541 | info | zigbee-shepherd ready. version: 2.6.3 rev 20182308
zigbee.0 | 2018-11-12 22:05:43.495 | info | zigbee-shepherd started!
zigbee.0 | 2018-11-12 22:05:42.449 | info | Start on port: /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_01900B9F-if00-port0 with panID 6754 channel 11
zigbee.0 | 2018-11-12 22:05:42.445 | info | starting. Version 0.7.7 in /opt/iobroker/node_modules/iobroker.zigbee, node: v8.12.0
host.ioBroker-RasPi | 2018-11-12 22:05:38.317 | info | instance system.adapter.zigbee.0 started with pid 4221
host.ioBroker-RasPi | 2018-11-12 22:05:35.873 | info | instance system.adapter.zigbee.0 terminated with code 0 (OK)
Caught | 2018-11-12 22:05:35.873 | error | by controller[3]: Mon, 12 Nov 2018 21:05:35 GMT cc-znp:SREQ --> ZDO:mgmtPermitJoinReq, { addrmode: 15, dstaddr: 65532, duration: 0, tcsignificance: 0 }
Caught | 2018-11-12 22:05:35.872 | error | by controller[2]: Mon, 12 Nov 2018 21:05:35 GMT zigbee-shepherd:request REQ --> ZDO:mgmtPermitJoinReq
Caught | 2018-11-12 22:05:35.871 | error | by controller[1]: Mon, 12 Nov 2018 21:05:35 GMT zigbee-shepherd zigbee-shepherd is stopping.
host.ioBroker-RasPi | 2018-11-12 22:05:35.776 | info | stopInstance system.adapter.zigbee.0 killing pid 4119
host.ioBroker-RasPi | 2018-11-12 22:05:35.775 | info | stopInstance system.adapter.zigbee.0


The lamp is now some kind of visible in the objects list:
![image](https://user-images.githubusercontent.com/2899791/48375163-5beded80-e6c7-11e8-8d3f-5f42ae2ea2b2.png)

but after refreshing the view, it disappears:
![image](https://user-images.githubusercontent.com/2899791/48375204-7aec7f80-e6c7-11e8-8a98-1b2d088cbe27.png)

**Comment by steffiland** [comment]
great, it works :thumbsup:
The lamps show up in iobroker as objects and I can dimm and change light temp.
Thank you so much!

**Comment by steffiland** [comment]
of course, switching on an off works, too.  :)

**Comment by arteck** [comment]
done check my Repo https://github.com/arteck/ioBroker.zigbee
