### ISSUE TITLE
BHT-002-GCLZB: Set local Time

### ISSUE THREAD

**Issue by SaberRiderStarsheriff** [ioBroker/ioBroker.zigbee#981]
Is it possible to set the local time with zigbee? The time on the device is inaccurate.

**Comment by asgothian** [comment]
This will be possible with the latest herdsman version.

Which adapter version are you running ?

A.

**Comment by SaberRiderStarsheriff** [comment]
great :-)

I am relatively up to date Version 1.4.2. Is there an extra data point or happend that automatically in the background?

**Comment by asgothian** [comment]
It will happen automatically in the background.

You can try to install 1.4.3 from GitHub to see if it is already available.

A.

**Comment by SaberRiderStarsheriff** [comment]
works fine. great development. thanks
