### ISSUE TITLE
innr SP120 plug has problems to report power, energy and current

### ISSUE THREAD

**Issue by ardu1** [ioBroker/ioBroker.zigbee#983]
Hello,

I have 3 innr SP120 plugs. I paired them with the Zigbee adapter under ioBroker. The ioBroker has the version 4.2.1, the Zigbee adapter has the version 1.4.3. and I use a Conbee II coordinator.

1. problem
In the objects list I only find at the SP120 plug this information: Load Power, Switch State, Link Quality, Available and Groups. There is no current and no energy, how is described here:

https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/SP_120.md

2. problem
I connected my water pump with the plug. At the pump is a pressure switch, that starts the motor when the pressure is down. The pump runs about 4-5 times a day. When I want to see the working time from the pump in Grafana I was wondering, that the value Power shows 0W. Then I connected a lamp with 150W and it is showing the correct power value? That problem I have with all three new plugs.

Does anyone has an idea to solve the problem and to bring current and energy in the adapter?

Thanks and best regards!

**Comment by ardu1** [comment]
![image](https://user-images.githubusercontent.com/36503094/107886221-cd4c2480-6efe-11eb-88f0-e25a5a23af82.jpeg)
Here I connected the innr plug with a AVM Deckt 200 plug. You could see that the AVM plug is showing the power value of my pump, and the innr plug is showing nothing.

**Comment by SevenUp666** [comment]
Here also the same problem. I switched from deconz adapter to Zigbee adapter v1.44 (+ switch from Conbee to TI CC26x2r1).
I am missing the values for "Sum of consumed energy".
"current" and "voltage" would be nice too, but not essential.

**Comment by ardu1** [comment]
Hello Sven does you SP120 works with the Conbee II?

**Comment by SevenUp666** [comment]
@ardu1 yes, SP120 was working with Conbee II + deconz + deconz-Adapter

**Comment by asgothian** [comment]
Please update to the current latest version (1.4.4) and add this device to the "Ausschlussliste" to obtain the states as exposed by the zigbee-herdsman-converters.

A.

**Comment by ardu1** [comment]
![image](https://user-images.githubusercontent.com/36503094/108357473-c4549f00-71ed-11eb-973b-19746ce2938d.jpeg)
Hello I did all as described. Here is a screenshot.

**Comment by ardu1** [comment]
![Uploading image.jpeg…]()

**Comment by SevenUp666** [comment]
@asgothian thank you. 
i have v1.44 and i have added the devices to Ausschlußliste. Now the value for the voltage and current is also displayed.
The value for "energy" (total) is there, but it is not updated.

Do you have a hint for this? I wanted to use the value to log the total consumption (by day and month).
With Conbee + deConz this was possible without any problems. So it is not really a problem with SP120?

[![Bild 2021-02-1820_47_16-wiegkn1.png auf abload.de](https://abload.de/img/2021-02-1820_47_16-wiegkn1.png)](https://abload.de/image.php?img=2021-02-1820_47_16-wiegkn1.png)

**Comment by ardu1** [comment]
![Screenshot-18-53-2021_08 53 31](https://user-images.githubusercontent.com/36503094/108413887-dc4b1380-722b-11eb-9805-36b9719daee8.jpg)
Now I find out that the current and the energy is also shown. Thanks!

But there is still the problem, that I do not get any data when my pump is running (see my first post).

**Comment by asgothian** [comment]
> But there is still the problem, that I do not get any data when my pump is running (see my first post).

This is an issue of the device and the method it uses to determine the load. It seems that the plug has issues determining the load when there is a phase shift which i assume is caused by the Pumps AC motor. Normal Lightbulbs do not generate said phase shift and as such will not be affected.

A.

**Comment by ardu1** [comment]
Thanks, this I also thought, but if I use a 650W drilling machine it works😳. But may be it depends how strong is phase shift. I wrote this to the Innr support, but they said it is not in the official description so they supported this problem not.
