### ISSUE TITLE
Support Linkind LED "ZL1000701-27-EU-2-V1A02"

### ISSUE THREAD

**Issue by tectecnik** [ioBroker/ioBroker.zigbee#985]
Hello together, 

could you please include the "Linkind" LED Bulb in your next Update? Its already included in zigbee2mqtt: 
https://www.zigbee2mqtt.io/devices/ZL1000701-27-EU-V1A02.html

Would be great, I bought a few before checking the list of supported devices. 

Thank you. 
Kind regards
Nick

**Comment by asgothian** [comment]
Please update to 1.14.3 from Github - this should already support the device.

A.

**Comment by tectecnik** [comment]
Great! Thank you very much.
