### ISSUE TITLE
ecozy Thermostat

### ISSUE THREAD

**Issue by ollimagic** [ioBroker/ioBroker.zigbee#99]
Hi is it possible to add these ecozy thermostat to the supportet devices?
zigbee.0 | 2018-11-13 15:10:13.833 | info | List of ports: [{"comName":"/dev/ttyAMA0"},{"comName":"/dev/ttyACM0"}]
-- | -- | -- | --
zigbee.0 | 2018-11-13 15:09:33.295 | info | new dev 0x70b3d5de00000c7d 3934 Thermostat
zigbee.0 | 2018-11-13 15:08:24.909 | info | Zigbee: allowing new devices to join.
Regards
Oliver

**Comment by kirovilya** [comment]
Not ready yet :(
https://github.com/Koenkk/zigbee2mqtt/issues/129

**Comment by ollimagic** [comment]
ok thanks for the info, it would be so nice because the central unit in my case it is not working and i would love to control everything in node red.
Regards
Olli

**Comment by EliasKotlyar** [comment]
Can we have it now? It seems that the support is already merged into zigbee2mqtt. I am willing to help porting it here, just point me to a tutorial how to start. Is it just editing the https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/devstates.js file and adding all the required parameters?

**Comment by asgothian** [comment]
An initial implementation exists now, needs testing. Please install from 
`https://github.com/asgothian/ioBroker.zigbee/tarball/ecozy`
Discussion on operation is ongoing in the iobroker forum, i‘d Rather not keep two threads updated
