### ISSUE TITLE
MS-104BZ identified as TS011F now show Second Channel

### ISSUE THREAD

**Issue by Osrx** [ioBroker/ioBroker.zigbee#990]
Buyed on aliexpress dual channel relay module with possibility to connect with external switches identified as TS011F don't have second channel possible for read and configuration.
Add a second channel please! =)

ieee:0x60a423fffe61d8d2
nwk:31092 (0x7974)
model:TS011F

Device information
model:TS011F
description:Socket module
supports:on/off
model:TS011F
type:Router
nwk:31092
manuf id:4098
manufacturer:_TZ3000_pmz6mjyu
power:Mains (single phase)
app version:65
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genGroups (4)
genScenes (5)
genOnOff (6)
output clusters:genOta (25)
genTime (10)
endpoint:2
profile:260
input clusters:genGroups (4)
genScenes (5)
genOnOff (6)

**Comment by asgothian** [comment]
- which adapter version did you try this with ?
- is the device listed to support 2 channels at zigbee2mqtt.io ?

Please read [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised) for more information

A.

**Comment by Osrx** [comment]
1. I use: 1.3.1
2. Yes it Supported https://www.zigbee2mqtt.io/devices/MS-104BZ.html

Is it supported in Git Hub version?

**Comment by asgothian** [comment]
Please follow the linked document. I would assume that the device will be supported with either 1.4.2 or 1.4.3

A.

**Comment by asgothian** [comment]
closed. Assumed solved due to inactivity
