### ISSUE TITLE
RGBW Controller (GL-C-007-ID)

### ISSUE THREAD

**Issue by kafibo** [ioBroker/ioBroker.zigbee#992]
Hallo, ich beschäftige mich erst seit kurzem mit ioBroker und bräuchte nun mal Hilfe bzw. könnte es auch ein Bug sein. Ich habe mehrere von diesen Zigbee LED Contoller RGBW (GL-C-007-2ID).
![GL-C-007-2ID_daten](https://user-images.githubusercontent.com/79101447/107969058-80745680-6faf-11eb-9bad-8180ff56b964.png)
Ich habe folgenden Coordinator: von Texas Instruments LAUNCHXL-CC26X2R1 mit der Firmware von
Koenkk (20201026) und mit dem Adapter Zigbee in der Version 1.4.4.
![Coordinator](https://user-images.githubusercontent.com/79101447/107969091-8e29dc00-6faf-11eb-83d0-7fd2fd5d2076.png)
Soweit funktioniert auch alles was angelernt wurde, auch eigentlich diese oben genannten Controller:
Aber !!!
Jedesmal wenn die VIS aufgerufen wird wo diese Controller eingebunden sind verändert sich sofort die Farbe oder wenn die LEDs ausgeschaltet sind schalten sie sich sofort ein, was meiner Meinung nicht sein darf. Dies geschieht auch wenn ich den VIS-Editor mit der entsprechenden Seite aufrufe – die LEDs werden gleich eingeschaltet oder die Farbe ändert sich. Eigentlich sollte es doch so sein, dass man erst den Switch einschaltet und dann Farbe; Farbtemperatur oder die Helligkeit verändern kann.
Ich hoffe ich habe mich verständlich genug ausgedrückt und kann dies nachvollziehen.
![softwareversionen](https://user-images.githubusercontent.com/79101447/107969541-317af100-6fb0-11eb-9369-d8d6cfb9e940.png)

**Comment by asgothian** [comment]
Please verify if the vis Updates the device states when being called - this will update the device as well.

a.

**Comment by kafibo** [comment]
Das verstehe ich nicht !
Was soll ich prüfen ? Wie, Wo ???
Entschuldigung für meine Unwissenheit oder Unkenntnis.
Wenn ich nur den Datenpunkt "color" oder "colortemp" ändere, geht das Licht ein (wenn es bis dahin aus war), der Datenpunkt "switch" bleibt dann auf false. Wenn der Datenpunkt auf false bleibt dürfte das Licht nicht angehen!
Wenn ich "brightness" ändere geht der Datenpunkt "switch" auf true und das Licht geht an (verstehe ich ja noch).

Wenn ich aber nur die VIS-Seite aufrufe geht das Licht schon an, obwohl ich überhaupt nichts geändert habe. Das kann meiner Meinung nach nicht richtig sein.

Bei einer LED Leuchte von Müller Licht passiert dies nicht. Das funktioniert einwandfrei und zuverlässig.

**Comment by asgothian** [comment]
Das von Dir beschriebene Verhalten ist ein Fehlverhalten des Controllers und kann nicht durch den Adapter unterbunden werden. 

Wenn ein Aktualisieren des States "color" und/oder "colortemp" das Licht in Farbe einschaltet dann ist das etwas was der Controller selber macht.

Offensichtlich aktualisiert deine Vis Seite beim Laden diese Datenpunkte, was dazu führt das der Controller das Licht einschaltet. An dieser Stelle kannst du ggf. anfassen.

Ich sehe nicht was wir im Adapter Sinnvolles tun können um dieses Verhalten zu ändern.

A.

**Comment by asgothian** [comment]
Closed due to inactivity.
