### ISSUE TITLE
not working zigbee adapter

### ISSUE THREAD

**Issue by rebel1985** [ioBroker/ioBroker.zigbee#993]
adapter is not working i iobroker on raspi 4

log errors are:

host.PI-4-Horus | 2021-02-15 19:37:06.623 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.PI-4-Horus | 2021-02-15 19:37:06.623 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.PI-4-Horus | 2021-02-15 19:37:06.623 | error | Caught by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.PI-4-Horus | 2021-02-15 19:37:06.623 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
host.PI-4-Horus | 2021-02-15 19:37:06.623 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.PI-4-Horus | 2021-02-15 19:37:06.623 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.PI-4-Horus | 2021-02-15 19:37:06.622 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js:3:25)
host.PI-4-Horus | 2021-02-15 19:37:06.622 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:25:18)
host.PI-4-Horus | 2021-02-15 19:37:06.622 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:692:17)
host.PI-4-Horus | 2021-02-15 19:37:06.622 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
host.PI-4-Horus | 2021-02-15 19:37:06.622 | error | Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
host.PI-4-Horus | 2021-02-15 19:37:06.622 | error | Caught by controller[0]: Error: Cannot find module 'zigbee-herdsman/dist/adapter/serialPortUtils'
host.PI-4-Horus | 2021-02-15 19:37:06.622 | error | Caught by controller[0]:     ^
host.PI-4-Horus | 2021-02-15 19:37:06.622 | error | Caught by controller[0]:     throw err;
host.PI-4-Horus | 2021-02-15 19:37:06.621 | error | Caught by controller[0]: internal/modules/cjs/loader.js:638

please help me where is the problem?
are zigbee adapter the problem or jscontroller?
i have no idea

**Comment by asgothian** [comment]
- the issue is handled at the iobroker Forum
- You need a clean node install and then reinstall the Adapter.
-

**Comment by rebel1985** [comment]
wie clean node install, läuft ja nicht obwohl ich damals normal node installiert hatte.
wie reinstall adapter, also im io broker löschen und neu installieren? gehen dann nicht auch meine einstellungen flöten?
