### ISSUE TITLE
Beginner question: setting color temperature & color (RGB, Ikea)

### ISSUE THREAD

**Issue by Domi920** [ioBroker/ioBroker.zigbee#994]
Hi,
First of all, a big sorry for the probably stupid question.
I bought new E27 lamps from Ikea (LED1624G9).

For this I found this page of the documentation:
https://www.zigbee2mqtt.io/devices/LED1624G9.html

How must the format for the "Color" field in the object list in IOBroker be in order
- set a color
- adjust the color temperature

What formats are there & how do I have to send the command?

I've been looking for an answer to that one question for a while, but have only found serious problems.

Thanks in advance!

Greetings Dominik

**Comment by asgothian** [comment]
The "color" field expects a 6 digit hex code, i.e. 0176ff, alternatively, a named color should be possible from the extended colours on this page: https://en.wikipedia.org/wiki/Web_colors. Note that the state expects all lower case numbers. The linked page will also provide you with color references for the 6 digit codes.
The "colortemp" field expects either a color temperature in mired or in Kelvin.

A.

**Comment by Domi920** [comment]
Thank you for your prompt reply!
 Is there a way to enter the colors in RGB format?

 Unfortunately, the Colortemp field does not exist.
 But the lamps should support white spectrum.
 How can you enter the Colortemp then?

**Comment by asgothian** [comment]
You need to use a script to format the color from rgb to hex. There are several options available on the forum.
In the hex value, the first 2 digits are R, the next 2 are G, the last two are B

Please install the current "stable" version or newer, and see if the Bulb will gain a colortemp entry if you add it to the "exclude" or "ausschliessen" List.

A.

**Comment by Domi920** [comment]
I installed the latest version: 1.4.4
Unfortunately there is still no color temp.

What should I do?
I don't quite understand the rest.

**Comment by asgothian** [comment]
Plese refer to this post:
https://forum.iobroker.net/topic/42253/zigbee-neue-version-1-4-4?page=1

**Comment by Domi920** [comment]
I clicked on the new data point "Trigger device query".
I also tried the exclude list.
Then restarted the adapter.

Unfortunately everything remains unchanged.

Am I doing something wrong?

**Comment by Domi920** [comment]
There is also the wrong image of an E14 lamp.

Here is the list of objects:
![Screenshot](https://user-images.githubusercontent.com/68474558/108206105-395ca180-7126-11eb-8418-09808dfd4b88.jpg)

**Comment by asgothian** [comment]
Following the description on zigbee2mqtt, this lamp does not support colortemp setting. It only supports color and brightness.

A.

**Comment by Domi920** [comment]
Laut Ikea sollte dies unterstützt werden:
LED-Leuchtmittel E27 600 lm, kabellos dimmbar Farb- **und Weißspektrum/rund opalweiß**

According to Ikea, this should be supported:
 LED lamp E27 600 lm, cordless dimmable color ** and white spectrum / round opal white **

https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-e27-600-lm-kabellos-dimmbar-farb-und-weissspektrum-rund-opalweiss-00408612/

**Comment by Domi920** [comment]
https://fccid.io/FHO-LED1624G9/Internal-Photos/Internal-Photos-3631433

Bei geöffneter Lampe kann man die Warmweißen & Kaltweißen LEDs zusätzlich zu RGB erkennen.

When the lamp is open you can see the warm white & cold white LEDs in addition to RGB.

**Comment by asgothian** [comment]
This page (https://www.zigbee2mqtt.io/devices/LED1624G9.html) clearly lists that the bulb supports color and brightness, but not colortemp. The issue would need to be fixed at this stage. What you can do is:
- open the zigbee adapter config
- go to the developer tab
- select the lightbulb as device
- select the correct endpoint for the lamp
- select the _ lightingColorCtrl_ Cluster ID
- set the command type to foundation
- attempt to read or write specific attributes from / to the lamp, taking note of the response.

With the response, there are 3 things to look out for:
- A zigbee Error message (eg. UNSUPPORTED ATTRIBUTE (134))
- A success message
- A timeout message.
If the bulb does support colortemp, then it needs to respond with values to entries from this cluster.

A.

**Comment by Domi920** [comment]
Unfortunately I get the following error message:
UNSUPPORTED_ATTRIBUTE "Zigbee error 134 received!"

![Fehlermeldung](https://user-images.githubusercontent.com/68474558/108338918-13dba080-71d7-11eb-9308-99c51942c881.png)

For me it would almost look as if the lamps have built in the warm white & cold wise LEDs, but cannot be controlled in the conventional way.

Could it theoretically be that the transmission is different?
Is there some way to see all the available values ​​from the lamp?
What other measures could you take?

**Comment by asgothian** [comment]
There are all kinds of possibilities. Some companies use "manufacturer specific" clusters to implement specific functions. The main issue is for the lamp to actually report these to the coordinator and then catch those messages to analyse them.

The other thing you can try is to see if you can find a functional command which you can use to send the colortemp. Last option is to see if you can send a "moveToColortemp" message with the payload {colortemp:350} to the bulb.

A.

**Comment by Domi920** [comment]
Unfortunately, the next option of yours didn't work.

That's why I took a look under the hood.
A lot can now be explained:
![20210218_192137](https://user-images.githubusercontent.com/68474558/108403426-fc280a80-721e-11eb-828f-548a19b2bee4.jpg)
There are NO cold white LEDs!
So you can't adjust the color temperature either.
The following LEDs are installed:
7x red, 5x green, 5x blue, 10x warm white

I have now tested a few colors with the object list:
![20210218_171553](https://user-images.githubusercontent.com/68474558/108403958-925c3080-721f-11eb-90b7-6b2085851355.jpg)
![20210218_184816](https://user-images.githubusercontent.com/68474558/108403976-99833e80-721f-11eb-9bea-ccbec5eb0c5c.jpg)

A few things stand out:
 - The green LEDs do not light up in the familiar green tone (as with rgb), but as shown in the picture (yellow tint)
 - If activated in blue, the green or yellowish LEDs light up.  Therefore, no direct blue can be realized.
 - If the control is white, the red LEDs do not light up. But the warm white LEDs a little

When you connect the lamps to the Zigbee adapter for the first time, the warm white LEDs light up.
I was able to find out the X & Y light value with the developer settings.
With a HEX color code, I cannot switch the warm white LEDs on to full power and not alone.
In which format do I have to send the X & Y values ​​and where?

If you only control the color blue (0000ff), the green LEDs also light up. Are there ways to prevent this?

I previously learned this lamp in the "Ikea Home Smart" and tested the behavior and operation via the app and remote control.
This is what the color settings look like in the app:
![Screenshot_20210218-194850_Home smart (TRDFRI)](https://user-images.githubusercontent.com/68474558/108406356-9ccbf980-7222-11eb-8041-8df0fe042e72.jpg)
If you choose the color above in the middle you get warm white (no other LEDs light up)

Made a video of it. If this is interesting, I can upload it.


 Greetings Dominik

**Comment by asgothian** [comment]
Keep in mind that "warm white" is also a color, i.e. each color temperature in the white spectrum can be identified by an RGB value. It is not unlikely that the ikea app will control the warm white features through the RGB (or possibly XYy) colorspace and not expose the colortemp attributes.

As for which LED;s turn on - due to differences in color between different LEDs and limitations in LED brightness it is common practice to mix colors by turning on different LED's in different amounts. As such, the fact that blue and and white LED;s are being used for a "cold" color is quite normal.

A.

**Comment by Domi920** [comment]
Unfortunately, a combination of warm white and cold white LEDs is not as bright as if it were purely warning white and cold white LEDs.
Warm white LEDs are installed.
The only problem is that with the Color Picker from IOBroker Vis it is not possible to light up the pure (and only the) warm white LEDs.

I was able to find out X & Y values ​​for ONLY warm white with the developer settings:
SUCCESS {"currentX": 30015}
SUCCESS {"currentY": 26870}

BUT I cannot forward the values ​​despite a few attempts because the color is always different.
Now the question is, how do I have to send the values ​​in order to get this warm white?
Or how can I convert these X & Y values ​​into a hex code?
On the Internet I can only find instructions that convert the values ​​X, Y & Z. But I don't know the Z value.

Please help.

Greetings Dominik

**Comment by asgothian** [comment]
I can generate a Test state for you where you can directly send xy values to the lamp. If that works we can set a state which switches the lamp to simulated white.

All this will have to wait til next week. 

A.

**Comment by Domi920** [comment]
That would be great!

Thanks for the quick answers and all your efforts!

Greetings Dominik

**Comment by Domi920** [comment]
Hi,
 just wanted to ask if there is already an update on this topic?

 Greetings Dominik

**Comment by asgothian** [comment]
I am afraid not. I have been bogged down with other issues so i couldn't generate the promised branch.

**Comment by asgothian** [comment]
I have a branch for you for testing now.

It will add a color_xy state to any light which supports color. Please note that there may be some side effects with linked states (i.e. lamps not changing on/off state when they turn on via brightness) as that is what i am working currently.

You can install it from my GitHub:

https://github.com/asgothian/ioBroker.zigbee/tarball/linkedstatesinexposes

**Comment by Domi920** [comment]
Vielen Dank für die Bemühungen!

Hab die neue Version installiert und es tauch auch das Feld "color_xy" auf.
Nur leider weiß ich nicht wie ich die Werte eingeben soll, bzw. welches Format dieses Feld haben will.
Habe schon einige Versuche probiert, aber ohne Erfolg.

Folgendes konnte ich aus den Entwicklereinstellungen für warmweiß herauslesen:
SUCCESS {"currentX":30015}
SUCCESS {"currentY":26870}

**Comment by asgothian** [comment]
Sorry, i should have mentioned that: The State expects a pair of x,y or x;y. The values for x and y are between 0 and 1, so for the values you read above, you should enter
0.30015,0.26870

A.

**Comment by Domi920** [comment]
Now it works!
Is there a more detailed documentation about your structure somewhere with a few examples?

What is the difference between XY & XYZ?

**Comment by asgothian** [comment]
Unfortunately, i do not see this patch go into the main adapter due to the issue with updating all color variants correctly when color is being updated.

I do have an alternative for you to test though:

Please install the current latest beta (1.4.5) from GitHub and attempt to use this code in a script to set the color on your osram lamp:

```
sendTo("zigbee.0", "SendToDevice", {
   "device": '90fd9ffffe20c681',
   "payload": {"x":0.30015, "y":0.26870}
}, function(result) {
  if (result.success) console.log("success") else console.log("error : " + result.error)
});
```

You should be able to set the color using this function. It is also available in Blockly:
<img width="354" alt="Screen Shot 2021-03-10 at 13 42 08 " src="https://user-images.githubusercontent.com/45667167/110631060-6ab91200-81a6-11eb-9f2c-0c2430b9760b.png">


A.

**Comment by Domi920** [comment]
Warum soll ich den 2. Versuch starten wenns zurvor über den neuen Datenpunkt geklappt hat?
Gab es bei der Variation ein Problem?

Habde das Blockly nachgebaut & folgende Fehlermeldung im Log erhalten:

zigbee.0 | 2021-03-11 06:53:50.898 | error | (29054) No converter available for '' with key 'y'
-- | -- | -- | --
zigbee.0 | 2021-03-11 06:53:50.897 | error | (29054) No converter available for '' with key 'x'

**Comment by asgothian** [comment]
> Why should I start the 2nd attempt if the new data point worked before?
> Was there a problem with the variation?
> 
The issue is that every color lamp will have the added color_xy state. Which means there are then 2 states controlling color which are not being kept in sync, i.e. when the color_xy state is changed the "color" state stays the same. Of course these can be synced, but then you run into exactly the problem as before due to the fact that the color state has only 256 values for each color which results in specific x/y combinations unreachable for the color_xy state.

Inconsistent states which control the same characteristic are unwanted.

Now to the Script: I made a mistake. The Payload needs to be
{"color":{"x":0.30015, "y":0.26870}}

A.

> Got the Blockly after viewing & following error message in the log:
> 
> zigbee.0	2021-03-11 06:53:50.898	error	(29054) No converter available for '' with key 'y'
> zigbee.0	2021-03-11 06:53:50.897	error	(29054) No converter available for '' with key 'x'

**Comment by Domi920** [comment]
Yes, the payload works and without an error message.

What solution do you have for the problem?

**Comment by asgothian** [comment]
> Yes, the payload works and without an error message.

This means that the lamp reacts as expected to the change of color values too ?
> 
> What solution do you have for the problem?

The scriptable function is part of the adapter and will go into the stable version once this is updated. Therefore, the "solution" will have to be that this script needs to be used when you want to tune this specific lamp to only use the warm white LED's. 
I do not see this as a major issue, though. As far as i understand, you would have to use a script anyhow to utilize the color_xy state to change color as this is not usually supported by the color pickers or voice assistants.
You can also keep using this function to change the color of the lamp to any other value or alternatively use the color state with RGB color for setting "colored" light and the script to set it to warm white.

Since the Bulb does not react to setting color temperature, there is little else to do.

A.

**Comment by Domi920** [comment]
Yes exactly!  The lamp has changed the color according to your input.

 Which X & Y value do I have to enter for a pure warm white?

 I realized the control of the lamp with the help of Node Red.
 There I can evaluate the payload & set the IOBroker or lamp data point to the correct value.

 Now I just have to know what real warm white is.
 Is there a simple explanation for this?

**Comment by asgothian** [comment]
Unfortunately, there is no simple explanation.

I did find a formula for calculating K out of x/y pairs, but not the other way around.
https://www.waveformlighting.com/tech/calculate-color-temperature-cct-from-cie-1931-xy-coordinates


Easiest resource is 
https://en.wikipedia.org/wiki/CIE_1931_color_space

As to xyz vs xy:

in the xyz color scheme the z coordinate defines the brightness without color change.

xy is actually no color scheme. It is shorthand for xyY, where Y (0 to 100) is the brightness.

A.
