### ISSUE TITLE
How could I delete fragments of a device in ZigBee Adapter?

### ISSUE THREAD

**Issue by ardu1** [ioBroker/ioBroker.zigbee#995]
Hello,

I use a ZigBee adapter (1.4.4) together with a ConBee II stick in my ioBroker. During I tried to add some smoke detectors HEIMAN HS1SA some did´t want to pair. They started the interview and nothing more happened. After I tried to pair again the interview did´t start any more. So I asked the Heiman support and they told me, may be there are any fragments of the first pairing, so an other pairing is not possible. If that is true, how could I find this fragments and how could I delete them?

Thanks and best regards!

**Comment by asgothian** [comment]
The zigbee adapter / Herdsman does not store any information for devices which did not complete the pairing. If anything is saved it is entered into the shepherd.db, which will always generate a state in ioBroker.

The only thing for you to check is if there is any state or device with the ieee address of the device. Deleting the state and the device will remove all remaining information for the device.

A.
