### ISSUE TITLE
Pairing of 4-Noks device failed

### ISSUE THREAD

**Issue by kuumaur** [ioBroker/ioBroker.zigbee#996]
Hi,
i try to pair a switch from 4-Noks ( 4noks ) ZR-PLUG-EU-J.
Getting error message in Log file:
(20809) Failed to interview '0x000d6f0000d393c9', device has not successfully been paired. Undefined
Has any one experience with this kind of device and vendor?
Host=Debian 10 x64
Node.js=v12.20.1
NPM=6.14.11
js-controller=3.1.6 
zigbee=1.4.4
What additional information needs to be provided?

**Comment by asgothian** [comment]
- Is the plug listed as supported device ?
- have you tried multiple times ?
A.

**Comment by kuumaur** [comment]
Not in this List:
https://github.com/ioBroker/ioBroker.zigbee/wiki/Supported-devices

Should i follow this guide?
https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device

**Comment by asgothian** [comment]
Yes. If you feel up to trying to implement the support yourself.

Note that there is an option to make things a little easier, but this is not yet available in the main adapter.

For this you need to install from my GitHub (https://github.com/asgothian/ioBroker.zigbee). With this version, you can enter the ieee (000d6f0000d393c9) in the info.debugmessages state to catch the zigbee messages for just this one device.

A.

**Comment by kuumaur** [comment]
I will try my best.

Some additional Information (FYI):
https://www.besd.nl/sites/default/files/documents/manuals/4-noks/4-noks-zigbee-energy-meter-ZR-PLUG%20manual.pdf

Before Iobroker it was paired with:
Quivicon Homebase (Telekom) with ZigBee-USB

**Comment by kuumaur** [comment]
I did the change to GitHub Version.
I did these steps:
- enable the 'zigbee herdsman debug info' in the configuration of the zigbee adapter.
- activate the debug log for the zigbee instance to be used for the test
- wait for the zigbee adapter to restart.
- delete the current log file
But it still creates a lot of entries.
What exactly do you mean with:
With this version, you can enter the ieee (000d6f0000d393c9) in the info.debugmessages state to catch the zigbee messages for just this one device
Where can i find it?

**Comment by kuumaur** [comment]
Ups, i did a cross check after installing the GitHub Version.
The installed version is now 1.4.3, but in beta channel is 1.4.4
What did i wrong?

**Comment by asgothian** [comment]
Nothing - my debug version is still on 1.4.3, although it contains 95% of the 1.4.4 changes already. I did not have the time to back port the 1.4.4 change to my fork.

The debug messages state should be available under zigbee.0.info

If you use it, you do not need to start the adapter with debug enabled, and will only get log entries for the device(s) you specified.


A.

**Comment by kuumaur** [comment]
Sorry for the delay, it is currently a busy time for me.
Now i have these entries in my log.
zigbee.0 | 2021-03-01 11:16:14.250 | debug | (8112) zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0x000d6f0000d393c9', attempt 3
-- | -- | -- | --
zigbee.0 | 2021-03-01 11:16:10.452 | debug | (8112) Non-pingable device 0x000d6f0000d393c9 undefined was last seen '28.865' seconds ago.
zigbee.0 | 2021-03-01 11:16:07.188 | debug | (8112)  getMap result:  {"lqis":[{"parent":"0x00124b0021cc3a4c","networkAddress":29029,"ieeeAddr":"0x00158d0002d64768","lqi":114,"relationship":1,"depth":1,"status":"online"},{"parent":"0x00124b0021cc3a
zigbee.0 | 2021-03-01 11:16:07.188 | debug | (8112)  Get map succeeded  [{"parent":"0x00124b0021cc3a4c","networkAddress":29029,"ieeeAddr":"0x00158d0002d64768","lqi":114,"relationship":1,"depth":1,"status":"online"},{"parent":"0x00124b0021cc3a4c","
zigbee.0 | 2021-03-01 11:16:07.187 | debug | (8112) Routing table succeeded for '0x000d6f0000d393c9'
zigbee.0 | 2021-03-01 11:16:07.187 | debug | (8112) Routing for '0x000d6f0000d393c9': undefined
zigbee.0 | 2021-03-01 11:16:07.187 | debug | (8112)  Failed to execute routing table for '0x000d6f0000d393c9'. "Error: AREQ -  ZDO - mgmtRtgRsp after 10000ms\n    at Timeout._onTimeout  (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitres
zigbee.0 | 2021-03-01 11:15:57.178 | debug | (8112) LQI succeeded for '0x000d6f0000d393c9'
zigbee.0 | 2021-03-01 11:15:57.177 | debug | (8112)  Failed to execute LQI for '0x000d6f0000d393c9'. "Error: AREQ - ZDO -  mgmtLqiRsp after 10000ms\n    at Timeout._onTimeout  (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35
zigbee.0 | 2021-03-01 11:15:51.230 | debug | (8112) zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0x000d6f0000d393c9', attempt 2
zigbee.0 | 2021-03-01 11:15:46.979 | debug | (8112)  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - mgmtLqiRsp -  {"srcaddr":38669,"status":0,"neighbortableentries":17,"startindex":3,"neighborlqilistcount":3,"neighborlqilist":[{"extPandId":"0x6
zigbee.0 | 2021-03-01 11:15:46.715 | debug | (8112)  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - mgmtLqiRsp -  {"srcaddr":54907,"status":0,"neighbortableentries":16,"startindex":3,"neighborlqilistcount":3,"neighborlqilist":[{"extPandId":"0x6
zigbee.0 | 2021-03-01 11:15:41.587 | debug | (8112) zigbee-herdsman:controller:log Not interviewing '0x000d6f0000d393c9', completed 'false', in progress 'true'
zigbee.0 | 2021-03-01 11:15:41.587 | debug | (8112) zigbee-herdsman:controller:log Device '0x000d6f0000d393c9' joined
zigbee.0 | 2021-03-01 11:15:41.586 | debug | (8112)  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd -  {"nwkaddr":29513,"extaddr":"0x000d6f0000d393c9","parentaddr":54907}
zigbee.0 | 2021-03-01 11:15:28.207 | debug | (8112) zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0x000d6f0000d393c9', attempt 1
zigbee.0 | 2021-03-01 11:15:23.550 | debug | (8112) zigbee-herdsman:controller:log Not interviewing '0x000d6f0000d393c9', completed 'false', in progress 'true'
zigbee.0 | 2021-03-01 11:15:23.549 | debug | (8112)  zigbee-herdsman:controller:log Device '0x000d6f0000d393c9' is already  in database with different networkAddress, updating networkAddress
zigbee.0 | 2021-03-01 11:15:23.549 | debug | (8112) zigbee-herdsman:controller:log Device '0x000d6f0000d393c9' joined
zigbee.0 | 2021-03-01 11:15:23.549 | debug | (8112)  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd -  {"nwkaddr":29513,"extaddr":"0x000d6f0000d393c9","parentaddr":54907}
zigbee.0 | 2021-03-01 11:15:10.452 | debug | (8112) Non-pingable device 0x000d6f0000d393c9 undefined was last seen '5.269' seconds ago.
zigbee.0 | 2021-03-01 11:15:05.185 | info | (8112) Starting interview of '0x000d6f0000d393c9'

What can i do next?

**Comment by asgothian** [comment]
The next steps are quite straight forward. You need to identify the messages which the plug will send, and which messages the plug reacts to.
You can do following the [document linked above](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device)

In a nutshell, you want to identify what can be read and what can be controlled on the device.

I would go to the developer tab in the zigbee adapter configuration and see if the plug reacts to the respective clusters.
The idea is to first send read commands to clusters / attributes which make sense for this device.

I would try the 
genOnOff cluster 
genPowerCfg cluster
seMetering cluster
haElectricalMeasurement cluster 

on the genOnOff cluster it also makes sense if you can send the device "functional" commands from the command list to turn it on or off.

The key information is to identify which attributes of these clusters can be read and/or written to.

Armed with that you can check the devices.js file in the zigbee-herdsman-converters for a device which is similar and work off that.

A.

**Comment by kuumaur** [comment]
Thank you very much for your support, i appreciate it really.
I believe it too much for me. I do have only little knowledge about ioBroker, Zigbee, etc. 
Tries to understand the documentation, but still missing a lot of explanation between the lines.
Again, thank you very much, but i will stop here.

Br Kuu Maur

**Comment by asgothian** [comment]
Integration in zigbee-herdsman-converters was canceled, closing this too
