### ISSUE TITLE
OTA for Tradfri not working

### ISSUE THREAD

**Issue by gfacek** [ioBroker/ioBroker.zigbee#997]
I have 3 new Ikea Tradfri LED. When I search for Updates, Adapter tells me, that there is a Update available. When I click to update, I get this message in Log:
(29396) Update of '0x5c0272fffec7ed54' failed (Image is truncated: not long enough to contain a valid tag)

A few weeks ago, the update worked fine.

In the meantime I have updated the Zigbee adapter to version 1.4.1 and the firmware of my CC26X2R1. I also tried updating the Zigbee Adapter to 1.4.4, and downgrading to 1.3.1. Nothing helped. So there is only left, that the firmware for the CC26X2R1 causes this error (I cant downgrade, because I need the firmware for the Sonoff Window Sensors), or something on the Ikea-Servers.

**Comment by JorinL** [comment]
Same here.

`

igbee.0 | 2021-02-22 11:14:46.977 | error | (22076) Error: Timeout - 39941 - 1 - null - 25 - 1 after 30000ms at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35) at listOnTimeout (internal/time
-- | -- | -- | --
zigbee.0 | 2021-02-22 11:14:46.977 | error | (22076) unhandled promise rejection: Timeout - 39941 - 1 - null - 25 - 1 after 30000ms
zigbee.0 | 2021-02-22 11:14:46.976 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-02-22 11:14:19.721 | error | (22076) Update of '0x680ae2fffe36a869' failed (Image is truncated: not long enough to contain a valid tag)

`

**Comment by JorinL** [comment]
Situation ist still unchanged:

<html>
<body>


zigbee.0 | 2021-08-01 16:32:43.767 | error | (498) Update of '0x680ae2fffe36a869' failed (Image is truncated: not long enough to contain a valid tag)
-- | -- | -- | --



</body>
</html>

**Comment by JorinL** [comment]
<html>
<body>


2021-08-20 17:03:13.531 | error | Update of '0x680ae2fffe36a869' failed (Image is truncated: not long enough to contain a valid tag)
-- | -- | --



</body>
</html>
