### ISSUE TITLE
Adapter does not start due to missing external config (after update).

### ISSUE THREAD

**Issue by MichaelKorn** [ioBroker/ioBroker.zigbee#998]
After updating the adapter I do not have a "external" element in my config.

I suppose this should be handed but the responsible line does not make sense: https://github.com/ioBroker/ioBroker.zigbee/blob/master/main.js#L150
The `|| [];` is useless because the `split()` function never evaluates to false. If something is wrong an exception is thrown. In my case "Cannot read property 'split' of undefined", because this.config.external === undefined!

As quick workaround (we need our lights) I added at the beginning of the function:
```
if (this.config.external === undefined) {
    return;
}
```

**Comment by kirovilya** [comment]
"external" config 
https://github.com/ioBroker/ioBroker.zigbee/blob/master/io-package.json#L194

**Comment by MichaelKorn** [comment]
@kirovilya, I can't understand why this ticket was closed:
1. I just had to manipulate the code so that I would have light again after an update.
2. I linked code that is obviously defective (partially dead). That should be fixed.

**Comment by kirovilya** [comment]
sorry, maybe I closed the Issue by mistake

I wanted to write that this field "external" in the config appears when the adapter is uploaded. how did you update the adapter that this field did not appear?

**Comment by MichaelKorn** [comment]
Thanks for reopening.
In fact, I had to make some changes elsewhere. On occasion I did the update in the terminal with `npm update`. I'm not an ioBroker expert and I didn't know that this could have side effects.
I would suggest changing the Code (https://github.com/ioBroker/ioBroker.zigbee/blob/master/main.js#L150) as follows:
If you are sure, that `external` always exists:
```javascript
const extfiles = this.config.external.split(';');
```
If you want to make it more robust:
```javascript
if (this.config.external === undefined) {
    return;
}
const extfiles = this.config.external.split(';');
```

**Comment by asgothian** [comment]
@MichaelKorn I suggest that you generate a PR with these changes. I do not see anyone else going into the code and changing it, given that it only affects people who do not perform the (required) upload after a manual install/update of the adapter and thus will have additional errors to deal with.

I expect the PR to go through without a hitch.
